### ISSUE TITLE
Redfish: Code Update - Host ApplyTime support

### ISSUE THREAD

**Issue by jaypadath** [ibm-openbmc/dev#1000]
Support of Host ApplyTime feature 

This feature has below parts:
1. Software management code support to read this dbus property after a software activate to know whether an automatic reboot of the host should be done or not.

Design doc is present at https://github.com/openbmc/docs/blob/master/designs/firmware-update-over-redfish.md. 

The redfish schema defines an Enum, ApplyTime:

        "ApplyTime": {
            "enum": [
                "Immediate",
                "OnReset",
                "AtMaintenanceWindowStart",
                "InMaintenanceWindowOnReset"
            ]

As of now we are supporing "Immediate" and "OnReset" options.

**Comment by jaypadath** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/openpower-pnor-code-mgmt/+/23821

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-pnor-code-mgmt/+/23821 merged
