### ISSUE TITLE
Redfish: Code Update - Support health status of firmware inventory objects

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1001]
Forum discussion is here - https://redfishforum.com/thread/212/health-softwareinventory-objects

Design doc review on this was here - https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/21986

This issue is code in the resolution on what to put in Health Status for the different failure scenarios.

**Comment by geissonator** [comment]
There was pretty limited discussion in the forum so here's what I propose.

Update https://github.com/openbmc/bmcweb/blob/master/redfish-core/include/utils/fw_utils.hpp#L264 to also put the Health in (remove hard code from https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/update_service.hpp#L713)

Since none of the failures result in the device which was being updated to be in a failed state, we will just set to "Warning". Use this for Invalid and Failed states.

https://github.com/openbmc/docs/blob/master/designs/firmware-update-over-redfish.md#status-of-an-image

**Comment by wangkair** [comment]
@geissonator After reading the discussion and doc above, I'm still not very sure the mapping relationship between dbus status and redfish health. Could you please help to check or fill out the form? How about Critical, no one matches it?

| dbus status | redfish state | redfish health |
|--------|--------|--------|
| NotReady | Disabled | Warning |
| Invalid | Disabled | Warning |
| Ready | Disabled | Ok |
| Activating | Updating | Ok |
| Active | Enabled | Ok |
| Failed | Disabled| Warning|

**Comment by geissonator** [comment]
That looks good to me @wangkair. The forum discussion said to only use critical if the firmware update failure has caused the device it belongs to, to be inoperable. Since we always update the alternate side of flash, we will never cause this type of failure so warning is as much as we want.

**Comment by wangkair** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/27578
