### ISSUE TITLE
FP5280G2: add distro feature for mac2 support

### ISSUE THREAD

**Issue by wangzqbj** [ibm-openbmc/dev#1003]
Fp5280g2 uses a uboot patch from zaius, This task is to add a distro feature to avoid code duplication

**Comment by bradbishop** [comment]
can we get the Zaius patch upstreamed?  I think we are in the process of moving to upstream u-boot, right @shenki ?

**Comment by wangzqbj** [comment]
merged: https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/23415
