### ISSUE TITLE
FP5280G2: enable UART mirror 

### ISSUE THREAD

**Issue by wangzqbj** [ibm-openbmc/dev#1006]
Mirror host console to  UARTx

**Comment by XiaochaoMa** [comment]
Tasks:
- [ Verified bmc uart1 mirrored host console on fp5280g2.]

**Comment by XiaochaoMa** [comment]
Tasks

- [ ] Verified bmc uart1 mirrored host console on fp5280g2.

**Comment by XiaochaoMa** [comment]
Task 
- [ ] Verified bmc uart1 mirrored host console on fp5280g2.
  Merged:https://gerrit.openbmc-project.xyz/c/openbmc/meta-inspur/+/23482
