### ISSUE TITLE
Add support for a Host TPM Fault Sensor

### ISSUE THREAD

**Issue by mzipse** [ibm-openbmc/dev#1010]
My understanding of this requirement is that when the TPM fails, Hostboot will surface and error.  The OpenBMC FW should handle that part normally.  However, the BMC FW is then also supposed to turn on a TPM Fault sensor on the GUI indicating a problem.

I believe Hostboot has already made changes to support this sensor.  Now we need to implement this story to address the BMC support.  Nick Bofferding should have details on this.  Also need to implement the GUI part of this as well.

**Comment by mzipse** [comment]
I wonder if this was the same as #238?  Not sure why that got closed.

**Comment by derick-montague** [comment]
> I wonder if this was the same as #238? Not sure why that got closed.

We also have #403, which is set for A.1.999 along with #590 which allows the user to choose to boot with or without the TPM enabled.

**Comment by rfrandse** [comment]
tracking in jira
