### ISSUE TITLE
PSU code update: script to create an update tarball

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#1014]
Create a script (or re-use existing one) to generate a tarball for PSU code update.
The tarball shall contain:
* MANIFEST
* PSU image(s)
* signatures

**Comment by mine260309** [comment]
Refer to https://github.com/openbmc/openpower-pnor-code-mgmt/blob/master/generate-tar, the tool should:
* Accept the following arguments:
   * Image file(s)
   * The version string
   * The model string
   * The manufacturer string (optional)
   * The private key for signing (maybe optional)
* Generate the MANIFEST including the above info, something like below:
   ```
   purpose=xyz.openbmc_project.Software.Version.VersionPurpose.PSU
   version=<version-string>
   extended_version=model=<model>[,manufacture=<xxx>]
   KeyType=OpenBMC
   HashType=RSA-SHA256
   ```
* Sign the image file(s), MANIFEST, and the public key
* Generate a tarball (could be gzipped or not)

It's better to write a description in `README.md` to introduce the usage of this tool as well.

**Comment by ChicagoDuan** [comment]
Done. 
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-psu-code-mgmt/+/27921
