### ISSUE TITLE
PSU code update: implement update

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#1016]
Implement the PSU code update on Swift and FP5280G2.

The implementation shall be made as generic as possible and the vendor-specific tools will be put in separated machine layers.

If a system has different models of PSUs, it shall be checked and only the applicable image should be updated to the correct PSU hardware.

E.g. provide a common systemd service to start the update, and let a script to do the different jobs on different machines, and on different PSUs.
Json or yaml configs could be used to describe the machine specifications.

**Comment by mine260309** [comment]
@derekhoward55 
I am going to implement this task, so information is needed:
1. The PSU image(s) for Witherspoon/Swift;
2. The update tools for the PSUs.

For 2), if there are no existing tools, could you provide the specs about how to do PSU update, e.g. the spec about which i2c registers to read/write.

**Comment by derekhoward55** [comment]
I emailed the power supply guys and cc'ed you, hopefully they can get you the images/etc.
Thanks.

**Comment by mine260309** [comment]
The service will need to check if an image matches a PSU. The original idea is to chck the PSU model, that the image's MANIFEST shall contain the model name in extended version.
Feedback from IPS indicates that it's better to check both manufacture and model.
But Witherspoon PSU's manufacture is empty, so the possible solutions would be:
1. If there is manufacture in either extended version or PSU inventory, it shall be checked;
2. Model shall always be checked.

**Comment by mine260309** [comment]
For the common part, commits are submitted to https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-psu-code-mgmt/+/25445/2

I would like to defer Witherspoon/Swift's update tool, but using a dummy update service to continue the working.
New tasks will be created for Witherspoon/Swift specific tools.

Besides, IPS is helping to write a update tool for FP5280G2 system, and I could use that tool to do test as well.

**Comment by mine260309** [comment]
https://github.com/ibm-openbmc/dev/issues/1330 is created to track the vendor-specific tool for Witherspoon/Swift.

Close this as the generic code is merged.
