### ISSUE TITLE
PSU code update: Update by new BMC image

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#1017]
This issue shall implement all the necessary tasks that enable the BMC to update PSU by a new BMC image.
It shall include:
- Save the previous updated PSU images in a proper RW filesystem;
- Checks the PSU images in BMC's RO filesystem, and tell which one is newer;
- Checks the PSU hardware's version, and decide if an update shall be performed.
- Invoke the related DBus APIs to do the update if necessary.

**Comment by mine260309** [comment]
Subtasks:

- [ ] Add configure options to specific the RO and RW directories
- [ ] Store updated image(s) to RW
- [ ] On start, check RO and RW to get the newer image
- [ ] On start, check the HW and to get which has newer version
- [ ] Update to HW if RO or RW has a newer image

**Comment by mine260309** [comment]
@derekhoward55 Is there a stable way to compare the PSU image version?
E.g. on a system with two PSUs with version `01120114` and `00000110`, can we assume the newer one is `01120114`? Or it needs to let vendor tools to decide which one is newer?

**Comment by derekhoward55** [comment]
Well, although I'm not the expert on vendors' version numbering, I doubt it would be consistent across every possible vendor.  I agree the vendor-specific tool should decide.

**Comment by mine260309** [comment]
OK, the code is updated to defer to vendor tool to decide the newer version.
Going back for Witherspoon/Swift, how can we know which is the latest version? This function will be implemented in `phosphor-power`.

**Comment by mine260309** [comment]
Till https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-psu-code-mgmt/+/26055/1, all the functions are implemented.

**Comment by mine260309** [comment]
The commits are merged.
