### ISSUE TITLE
Redfish: Code Update - Static layout support

### ISSUE THREAD

**Issue by jaypadath** [ibm-openbmc/dev#1020]
This covers the code update ApplyTime support for the static layout systems like romulus/zaius.

Change needs to be carried out for both BMC and host code updates.

**Comment by anoo1** [comment]
The host code update implementation has been completed.
The BMC implementation was taken up by Bright Cheng: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/27621
