### ISSUE TITLE
GUI: BMC Reboot - Hard Reset

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1023]
## Stakeholders
**SME**: @geissonator
**RAS SME**: Justin Thaler
**Design Researcher**:
**UX Designer**:
**FED**:
**BMC Stakeholders**: @vishwabmc 

## Questions for creating the use case
- [ ] Why/When would a user need a hard reset?
- [ ] Can this action result in file corruption?

## Use Case
TBD

## InVision Prototype
TBD

## Design Issue (phosphor-webui)
TBD

## Development Issue 
TBD

## References/Resources
TBD

**Comment by amboar** [comment]
What's this about?

**Comment by derick-montague** [comment]
> What's this about?

We haven't done the full design discovery around this feature. This ticket is to determine the requirements and use case.

**Comment by vishwabmc** [comment]
@derick-montague Please add me as co stakeholder for this.

Are you asking about the requirements for BMC GUI to trigger a reset of the BMC ?. Are you trying to map the feature with ASMI on this ?

**Comment by derick-montague** [comment]
> @derick-montague Please add me as co stakeholder for this.
> 
> Are you asking about the requirements for BMC GUI to trigger a reset of the BMC ?. Are you trying to map the feature with ASMI on this ?

Yes, we currently have a soft reset and are looking into a hard reset. I believe we are trying to map the feature to ASMI. We don't have any subject matter experts outside of Andrew, so I was assuming this is a common BMC feature we will be building.

**Comment by vishwabmc** [comment]
@derick-montague Are you referring to   `System Service Aids --> Reset Service Processor` ? I believe we would still need this as a last resort to fix a bad system ( Mostly a lab usecase ) and a CE usecase.

We don't have any back-end  implementation of it now. But I see it as a need as I know CEs's have used it and it was used heavily in the lab.

**Comment by amboar** [comment]
> But I see it as a need as I know CEs's have used it 

What's a CE?

**Comment by vishwabmc** [comment]
> > But I see it as a need as I know CEs's have used it
> 
> What's a CE?

CE --> Customer Engineer; Person that visits the field and works the issues.

**Comment by derick-montague** [comment]
@geissonator - Do we want to move this into backlog or close. Not sure when we will be implementing it.

**Comment by geissonator** [comment]
I'm a bit confused. Don't we already have an option in the GUI to reboot the BMC?
