### ISSUE TITLE
GUI: FED: Update sensors to use Redfish

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1024]
## Stakeholders
**SME**: @gtmills 
**Design Researcher**: TBD
**UX Designer**: TBD
**FED**: TBD

## Overview
Sensor data is currently requested using the xyz API and needs to be converted to use Redfish

## Development Issue 
TBD

## References/Resources
TBD

**Comment by dixsie** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22496 

SensorCollection for Redfish

**Comment by derick-montague** [comment]
This is ready for FED work

**Comment by derick-montague** [comment]
Duplicate of #1213.
