### ISSUE TITLE
Make the necessary changes in openbmctool (LDAP) function.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1027]
With this story we have the following expectation.
1) openbmctool should be compatible with OP930 as well as OP940
2) openbmctool interface should not be changed.

How does openbmc tool knows that the managed system is OP930/OP940
1) If redfish support is there  => OP940
2) If redfish support no there => OP930.

**Comment by raviteja-b** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/23664

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/23664 merged
