### ISSUE TITLE
Openbmctool: Fix required to change root user password function for OP940 

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1028]
OP930  change password works with REST url only for root user, Now with the latest master we have removed that D-bus interface hence REST url will not work.

In OP940 we can use the redfish way to change the password for the root.

We have to make sure that current openbmc tool should support OP930(REST) as well as OP940(Redfish).

How does openbmc tool knows that the managed system is OP930/OP940

If redfish support is there => OP940
If redfish support no there => OP930.

**Comment by sunharis** [comment]
Patch set is up for review at https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/23666

**Comment by sunharis** [comment]
Changes are merged to master
