### ISSUE TITLE
Specify a PEL repository maximum size

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1032]
Figure out a way to specify, based on the system type, the maximum amount of size that all PELs can take up. 
i.e. pass in as a configure option, read the size from some config file on the BMC, etc.

**Comment by bradbishop** [comment]
A random thought/idea that popped into my head when I saw this was https://github.com/logrotate/logrotate.  Just getting it out of my head and onto (virtual) paper.

**Comment by spinler** [comment]
I'm just  going to hardcode this size for now, since I'd prefer to keep PEL specific flags out of configure.ac unless absolutely necessary which is where an option like this would probably go.  Can be revisited in the future if necessary.
