### ISSUE TITLE
PFP::Monitor - Nonfunctional fan at startup when sensor not on dbus

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1033]
When fan monitor starts up and retrieves the tach feedback sensor values from dbus, the associated fan should be marked nonfunctional when the sensor value is not found on dbus. Currently fan monitor defaults to mark a fan as functional then when this exception occurs, it is ignored and the functional state latches to functional incorrectly.

**Comment by JolieKu** [comment]
I test `phosphor-fan-monitor --init` in witherspoon qemu, print the `functional` in `inventory()` are all 1, does that mean fan monitor defaults to mark a fan as functional you mentioned?
Can I test sensor object is not exist on dbus in qemu?

**Comment by msbarth** [comment]
Yes, this is part of what this issue is going to address. Fan monitor (during `--init`) marks each fan as functional (this is by design, so on each poweron a new error log is created for any fans that were non-functional at the point of the previous poweroff). The problem here is, a fan that's missing its corresponding sensor on dbus upon poweron, will get marked as functional but since there's no sensor on dbus associated with it at poweron, it will never be updated to non-functional. So this issue is to correct this by not defaulting to mark a fan with a missing dbus sensor as functional upon poweron.

You'll find that an exception is currently thrown when a fan's sensor fails to be found on dbus, however this exception is then caught and silently nothing happens. This issue needs to address handling this exception and mark the fan as non-functional.

**Comment by JolieKu** [comment]
In witherspoon qemu, I found that fans will be marked as functional upon poweron, and only log `Not monitoring a tach sensor` if cannot get sensor value from dbus.
And you want to mark fans as nonfunctional if missing sensor on dbus, is my understanding correct?

**Comment by msbarth** [comment]
Basically yes.

However, you should note that the fan and each tach sensor have separate functional states that are linked by configuration(i.e. x number of tach sensors that are non-functional cause the fan object to also be considered non-functional). So this change needs to handle both the functional state of the tach sensor(which was unable to be retrieved from dbus) AND the fan's overall functional state.

I'm working thru another issue that will expand this fix further by subscribing to the state of the service that serves each tach sensor comprising each fan and therefore marking the tach sensors as non-functional if that service crashes.

**Comment by JolieKu** [comment]
I have uploaded a commit
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/36328

I also test on mihawk, it can read value(-110) even remove a fan, I am not sure the difference from qemu?

**Comment by msbarth** [comment]
> I have uploaded a commit
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/36328

Great! I'll take a look soon as I get some time.

> I also test on mihawk, it can read value(-110) even remove a fan, I am not sure the difference from qemu?

Not sure I follow what you're saying its reading on mihawk. The issue is not on removing a fan but on the service providing the fan tach sensors disappearing from dbus and getting the fans' functional state to reflect they are non-functional due to this since we cant detect any speed status for them.

**Comment by JolieKu** [comment]
> > I have uploaded a commit
> > https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/36328
> 
> Great! I'll take a look soon as I get some time.
> 
> > I also test on mihawk, it can read value(-110) even remove a fan, I am not sure the difference from qemu?
> 
> Not sure I follow what you're saying its reading on mihawk. The issue is not on removing a fan but on the service providing the fan tach sensors disappearing from dbus and getting the fans' functional state to reflect they are non-functional due to this since we cant detect any speed status for them.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/36328
