### ISSUE TITLE
Redfish: CPU Processors (missing properties) - Assembly

### ISSUE THREAD

**Issue by gkeishin** [ibm-openbmc/dev#1035]
The scope of this issue is limited to "TotalCores". Reference: https://github.com/ibm-openbmc/dev/issues/278

The remaining missing fields Model, PartNumber, SerialNumber, ProductionDate, Producer, and Version will be implemented as part of Assembly.

**Comment by gkeishin** [comment]
@ratagupt @gtmills @trajeswaran Here is the story for it requested.

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/dev/issues/1371 covers the PartNumber, SerialNumber, Version properties. Do we need ProductionDate? Producer ?

I have never seen ProductionDate filed out and we already have Manufacturer.

```
 curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET  https://${BMC_IP}/xyzopenbmc_project/inventory/system/chassis/motherboard/cpu0
{
  "data": {
    "BuildDate": "1996-01-01 - 00:00:00",
    "Cached": false,
    "FieldReplaceable": true,
    "Functional": true,
    "Manufacturer": "IBM",
    "Model": "",
    "PartNumber": "02CY209",
    "Present": true,
    "PrettyName": "PROCESSOR MODULE",
    "SerialNumber": "YA1934389578",
    "Version": "22"
  },
```

Model is already done here. 

https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/cpudimm.hpp#L134

I don't think we need a Assembly  for processor.

**Comment by gtmills** [comment]
@gkeishin Closing. If you think we are still missing things, let me know. 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/29388 Added Redfish: Processor: 
PartNumber, SerialNumber, and Version.
