### ISSUE TITLE
Read UPS signals via the BMC USB cable connector

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1037]
Customers can attach UPS's to their systems to provide backup power.  The UPS's provide 4 signals that can be monitored to know if power is lost, if the battery is low, etc.

IBM provides a cable to communicate the serial UPS signals to the BMC via the USB port.   The UPS device continues to use the serial port modem control lines to communicate the UPS status, these signals should be read by a device driver for the USB serial device.

This issue is for the low-level support to read if the cable is attached/detached and to read the 4 signals from the UPS (UPS online, UPS bypassed, UPS utility fail, and UPS battery low).  This information will be presented to a higher level app to act on the information.  The higher level app will be tracked with a different issue/story.

One possible implementation is to put the cable presence and UPS status (the 4 signals) on DBUS, where it could be read by a higher level app.  Another possible implementation is to see if the 'upsd' server or any of the drivers from networkupstools.org can be used/updated.

If possible, we should allow the UPS cable to be plugged or unplugged in any system state.  When the cable presence changes, or any of the 4 ups signals change, the higher level app should be notified so it can react appropriately.  The same information should be able to be read at any time by the higher level app (not just when it changes).

**Comment by amboar** [comment]
Is there more information on how this hardware configuration (UPS serial to BMC USB) works somewhere? I'm curious.

**Comment by derekhoward55** [comment]
Sure, take a look at the knowledgecenter page
https://www.ibm.com/support/knowledgecenter/TI0003J/p8had/p8had_ups.htm

Let me know if that doesn't contain the info you looking for.

**Comment by amboar** [comment]
Thanks. What type of USB device does it appear as on the service processor?

**Comment by bjwyman** [comment]
Does `pl2303` sound like an answer to what you are asking @amboar ?

**Comment by amboar** [comment]
The pl2303 is just a USB-to-serial device - is the UPS actually talking RS232 and we just need to interpret the data, or is it physically asserting some lines that happen to be exposed on a DB-9 connector, that we could access via a USB-to-serial device? This is what's not clear to me.

> IBM provides a cable to communicate the serial UPS signals to the BMC via the USB port. The UPS device continues to use the serial port modem control lines to communicate the UPS status, these signals should be read by a device driver for the USB serial device.
>
> This issue is for the low-level support to read if the cable is attached/detached and to read the 4 signals from the UPS (UPS online, UPS bypassed, UPS utility fail, and UPS battery low). This information will be presented to a higher level app to act on the information. The higher level app will be tracked with a different issue/story.

**Comment by derekhoward55** [comment]
I assume it's the latter, but my team didn't actually write the building block code so we don't know for sure unfortunately.  The person on the BB team who wrote that level of code is no longer at IBM.  We could ask someone on the BB team today if they would be willing to look into it (Eddie James and Chris Bostics names come to mind).

**Comment by amboar** [comment]
@bradbishop @eddiejames can you help here?

**Comment by bradbishop** [comment]
IBM didn't write any special code for this, beyond a very thin wrapper around the interface provided by the vanilla pl2303 driver.  All the wrapper does is provide explicitly named functions for the TIOCMGET and TIOCMIWAIT ioctls.

**Comment by amboar** [comment]
Right, so there's no kernel work to be done here.

**Comment by bradbishop** [comment]
> Right, so there's no kernel work to be done here.

Agreed...did something make you think kernel work was being described here?

**Comment by amboar** [comment]
I found the initial description confusingly ambiguous so I was trying to work out what was necessary.

**Comment by derekhoward55** [comment]
Thanks guys from looking into this.  My understanding based on these comments then is no pl2303 DD updates are needed.  The app would simply need to call the pl2303 DD to read the 4 ups signals and put them on dbus or something equivalent.

How about detecting when the usb cable is plugged/un-plugged, in which layer of code is that detected?

**Comment by amboar** [comment]
I expect we can use systemd/udev to start/stop the service when the tty device appears/disappears. USB hotplug is all handled in the kernel, and it's signalled to userspace via udev.

**Comment by bjwyman** [comment]
Not that I know what the systemd/udev rule for the USB connected UPS widget will look like, but I thought an example reference might be somewhat handy.

I thought I made such a udev update in the past, and I tracked it down:
https://github.com/openbmc/meta-phosphor/commit/675ce0bea5639de40baded9c957cceff9ad0cd81

**Comment by bradbishop** [comment]
at 4:36 PM, B. J. Wyman <notifications@github.com> wrote:

> Not that I know what the systemd/udev rule for the USB connected UPS  
> widget will look like, but I thought an example reference might be  
> somewhat handy.
>
> I thought I made such a udev update in the past, and I tracked it down:
> openbmc/meta-phosphor@675ce0b

Right.  One thing that has changed since then is nowadays I ask that you  
distribute the rule with your repo via its build and install process and  
not with the bitbake metadata.

**Comment by mzipse** [comment]
@derekhoward55 , we have this as a "ReadyForDev" candidate work.  Can this be tested on a Witherspoon or other openpower box?  Will the developer need a special cable to test with?

**Comment by mzipse** [comment]
Also, if you don't mind, can you add a story point estimate on how much work this might be?

**Comment by derekhoward55** [comment]
As far as I know it couldn't be tested on Witherspoon, I believe hw team had to add a usb connector on the bup vehicle.  We have the special cable and homemade 4-bit device in Austin.

But perhaps folks with more obmc experience than me could think of a way to test it on other boxes.  Should I get more input before you discuss this with IPS?

**Comment by amboar** [comment]
Can you send me the schematics for this setup? I feel like I'm still short of clarity on what we're doing here.

**Comment by derekhoward55** [comment]
> Can you send me the schematics for this setup? I feel like I'm still short of clarity on what we're doing here.

Yes I'll ask the hw team for it thanks.

**Comment by mzipse** [comment]
Reassigning this to @eddiejames.  Eddie, per our discussion last week.

**Comment by BMC-Bruce** [comment]
There is a Linux command [statserial](https://linux.die.net/man/1/statserial) that will **display serial port modem status lines**.
However I do not see this package in `meta-openembedded` or `poky`; @bradbishop what would it take get this command pulled into OpenBMC?
Here is one place I found its source https://searchcode.com/codesearch/view/22754947/

**Comment by amboar** [comment]
@BMC-Bruce has you looked at packaging it yourself?

**Comment by BMC-Bruce** [comment]
No, as I am not sure how that is done.  Should it get added to OpenEmbedded, Yocto, or OpenBMC; then is how to do that for those projects.

**Comment by BMC-Bruce** [comment]
Here is my code to read the Modem signals that are drive by the UPS:

@eddiejames has taken a look and gave some feedback.
@amboar if you have time to take a quick look and offer critiques would be appreciated. 
[https://github.com/BMC-Bruce/ups_handler](https://github.com/BMC-Bruce/ups_handler)

These are the only signals that are being addressed:
```
/*
 * Signals to be read by the UPS TO USB cable Part No. 00FV631
 * for monitoring the potentially attached UPS.
 *     CTS - Clear To Send       - UPS On
 *     DCD - Data Carrier Detect - UPS Batter Low
 *     RI  - Ring Indicator      - UPS Utility Fail
 *     DSR - Data Set Ready      - UPS Bypass
 */
```
