### ISSUE TITLE
Use the right values for CODE_LINE and CODE_FUNC in journal traces

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1039]
Opening here for tracking purposes.

The phosphor::logging::log() API writes to the journal, but doesn't really get those 2 journal fields right.  See https://github.com/openbmc/openbmc/issues/2297.

That issue does mention a few ideas on how to solve it.

**Comment by vmauery** [comment]
c++20 offers a new option, once projects have moved to that: std::source_location
https://en.cppreference.com/w/cpp/experimental/source_location

The header files that expose the API should probably use some #ifdef magic to check the c++ compiler version and expose the correct logging interface, with source_location for c++20 and without it for lower versions. Then, the logging library can be built with c++20 and any project calling it can take advantage of the new feature without change by simply updating the -std=c++20 option.

**Comment by lxwinspur** [comment]
@spinler @vmauery 

Around this issue, I have a question:
We have an example code:
```
#include <iostream>
#include <string_view>
#include <experimental/source_location>
 
void log(const std::string_view& message, const std::experimental::source_location& location = std::experimental::source_location::current())
{
    std::cout << "info:"
              << location.file_name() << ":"
              << location.line() << " "
              << message << '\n';
}
 
int main()
{
    log("Hello world!");
}
```

So my initial idea is to define `const std::experimental::source_location& location = std::experimental::source_location::current()` into the log method.
But for the log method, has defined a variable parameter, so it can not receive the default parameter again.

link: https://github.com/openbmc/phosphor-logging/blob/master/phosphor-logging/log.hpp#L157

Note: We better not update the log method of *.cpp.
So, Do you have a better way to process it? We can discuss it here.
Please let me know, Thanks

**Comment by lxwinspur** [comment]
@spinler @mzipse 
Could you give me some suggestions? Thanks.

**Comment by spinler** [comment]
Hi @lxwinspur, this sounds like a good question for the mailing list, I suspect people there will have some  ideas.

**Comment by lxwinspur** [comment]
@spinler 
I sent an email to OpenBMC
https://lore.kernel.org/openbmc/CANFuQ7AvV_R-Q0q0-QEKH_CsYv9vk7dVHzL+e4NvjifeFRbknw@mail.gmail.com/

Let us keep waiting

**Comment by lxwinspur** [comment]
About this issue, I saw Patrick pushed a new design doc:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/45310

**Comment by lxwinspur** [comment]
@spinler 
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/45310
This patch has been merged.
Also, I updated [phosphor-led-manager], and tested it, we can get the correct `CODE_LINE` and `CODE_FUNC` values can be used in log tracking.

So, Can we close this issue?

[phosphor-led-manager]: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-led-manager/+/44702
