### ISSUE TITLE
GUI: Design: Brand GUI as IBM

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1041]
## Stakeholders
**SME**: 
**Design Researcher**: @jandraa 
**UX Designer**: @jandraa 
**FED**:

## Use Case
Update login screen with IBM branding and determine favicon. 

## References/Resources
Current Branding: 
![IBM-Branding-header](https://user-images.githubusercontent.com/5455127/61727039-3f1ab700-ad38-11e9-8dcd-a67c26f4a387.PNG)
![IBM-Branding-login-page](https://user-images.githubusercontent.com/5455127/61727040-3f1ab700-ad38-11e9-97d7-99aa7d7ad129.PNG)
![favicon](https://user-images.githubusercontent.com/5455127/61727041-3f1ab700-ad38-11e9-8a36-110d78d17644.PNG)

**Comment by jandraa** [comment]
Updated login screen: 

<img width="1633" alt="Screen Shot 2019-07-26 at 1 20 11 PM" src="https://user-images.githubusercontent.com/44675611/61972815-21ec1f80-afa8-11e9-9ab0-b28fbb7b6927.png">


To be consistent with the rest of IBM and follow IBM standards, we will use the IBM Bee as a favicon, which can be found here: https://www.carbondesignsystem.com/guidelines/iconography/library#maincontent
<img width="158" alt="Screen Shot 2019-07-26 at 1 15 27 PM" src="https://user-images.githubusercontent.com/44675611/61972560-7e027400-afa7-11e9-8707-8bf8c146cf33.png">

**Comment by gtmills** [comment]
@jandraa built on OpenBMC or the OpenBMC logo in the lower right?

**Comment by jandraa** [comment]
My bad, just updated the screenshots above. The logo should be 'built on OpenBMC'.

**Comment by jandraa** [comment]
Adding for reference on where to find the 'built on OpenBMC' logo: https://github.com/openbmc/docs/blob/master/logo/BuiltOnOpenBMC.svg

**Comment by jandraa** [comment]
> The logo should be separated from other visual elements by a distance equal to its height, at a minimum. 

Spacing markup as follows: 
![oBMC Log In - Markup](https://user-images.githubusercontent.com/44675611/62074973-8823ad00-b209-11e9-858b-87299ef36695.jpg)
