### ISSUE TITLE
GUI : Brand GUI as IBM

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1042]
## Summary
As part of the new releases of the UI, we want a more aesthetic design of the login page. The as is design is functional, but does not convey the modernization and aesthetic that we feel represents the Power brand. We would also like to include the Power logo to establish the Power brand.

### Design Goals
- [x] Update the design to an aesthetic that will help create more trust with users
- [x] Establish the Power system brand into the design

### InVision Prototype
- https://ibm.invisionapp.com/share/YBO1CK3DQ4J

##### As Is upstream experience
![image](https://user-images.githubusercontent.com/1183515/101546006-bc66bc00-396d-11eb-8035-3f88f5d5b9ca.png)

##### To Be upstream experience
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1183515/119899223-76e08000-bf08-11eb-9f3d-cf96a4840901.png">

##### As Is downstream experience
![image](https://user-images.githubusercontent.com/1183515/101547040-49f6db80-396f-11eb-8aaa-00bea74f47f4.png)

##### To be downstream experience
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/1183515/119897341-e2751e00-bf05-11eb-8abc-cc75ea008a9f.png">

### Community
- [x] Created design review story in webui-vue repo - https://github.com/openbmc/webui-vue/issues/63
- [x] Sent email to community sharing the design review story

### UX Flow / Interaction Requirements
- [x] Change layout
- [x] Move OpenBMC logo to right corner
- [x] Determine if we can use environmental variable to add Power brand upstream
- [x] Update change password layout

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [x] Tested responsive layout on supported viewport sizes
- [x] Verified functionality works as expected, e.g. success and failure use cases
- [x] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [x] Verified markup is semantic
- [x] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [x] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
This is specific to the login page only and favicon (use IBM Bee). Future discussion about more branding downstream (fonts, colors...).

**Comment by derick-montague** [comment]
The work here is understanding how the IBM logos will be pulled in from the meta layer.

**Comment by gtmills** [comment]
Yeah would be nice if this could live upstream

**Comment by derick-montague** [comment]
@gtmills this seems like a server-side story rather than a client-side story. I am going to assign to you and remove the FED label.

**Comment by derick-montague** [comment]
@gtmills - I know there is some Meta layer work here, but I also see some work on pulling logos in to the login page. My feeling is that we can make a decision and share with the community. Those that are opposed to can make changes down stream. Do we know when the meta-layer work might be ready? I realize it is lower priority.

**Comment by gtmills** [comment]
Yeah, I would really like us to work with the community to do something here and come up with something that works for all members. I know other companies have this use case. 

Setting the .ibm.env on an IBM build is something on my plate. I will try to work that here soon. I think there will need to be additional changes for the logo unless the logos go in webui-vue? Which I'm not sure I love.

**Comment by derick-montague** [comment]
> I think there will need to be additional changes for the logo unless the logos go in webui-vue? Which I'm not sure I love.

I agree and that is true for the favicon as well.

**Comment by gtmills** [comment]
I think #3099 will close this? Passing 'ibm' to webui-vue?

**Comment by derick-montague** [comment]
> I think #3099 will close this? Passing 'ibm' to webui-vue?

But I don't think we have a design for that environment.

**Comment by gtmills** [comment]
@derick-montague Assigned you and unassigned me.

**Comment by derick-montague** [comment]
Updated design and added to the design review project in the webui-vue repo.

**Comment by derick-montague** [comment]
The only concern was the title of the page that can be updated downstream.

**Comment by DBurkh** [comment]
Moved to review, keys removed from es and ru as suggested.
