### ISSUE TITLE
Implement getFRURecordByOption

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1046]
This is for the libpldm and libpldmresponder work. See DSP0257 v1.0.0 table 12. 

GetFRURecordTable is implented already. GetFRURecordByOption is an alternative that lets the user fetch specific FRU information (based on the FRU record set identifier, etc) and is more optimal. Hence the desire to implement this command.

Also need code in pldmtool to test this.

**Comment by wangzqbj** [comment]
pldmtool: Implement GetFRURecordByOption:
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/33679 Merged

libpldmresponder: Implement GetFRURecordByOption Merged
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/33551/10 Merged

libpldm: Add encode/decode APIs for GetFRURecordByOption
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/33453 Merged
