### ISSUE TITLE
GUI : FED: Alert user of need and ability to change expired password

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1049]
## Requirements
Code, Test, and Review based on design requirements outlined in #1048.

## Backend Issue
#1047

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/26436

**Comment by derick-montague** [comment]
@gtmills - I just commented on the Gerrit review regarding your edge case concern. Do we have this downstream already? Trying to determine if there is any work needed for this story.

**Comment by gtmills** [comment]
Tracked by https://github.com/ibm-openbmc/dev/issues/1648. Closing this story
