### ISSUE TITLE
Document the openbmc target design and flow within systemd

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#105]
<a href="https://github.com/geissonator"><img src="https://avatars2.githubusercontent.com/u/1612261?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [geissonator](https://github.com/geissonator)**
_Tuesday Jan 31, 2017 at 15:47 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/1054_

----

It's difficult to visualize and understand the flow of targets on the openbmc using systemd.  There's multiple ways out there to document this, we need to pick one and implement it across all of our targets.

Here's a comment from Brad on it:
https://gerrit.openbmc-project.xyz/#/c/2115/1/meta-phosphor/common/recipes-core/systemd/obmc-targets/obmc-quiesce-system%2540.target

Also, see the mailing list discussion where @amboar generated a systemd-analyze pic.
https://lists.ozlabs.org/pipermail/openbmc/2017-January/006309.html

**Comment by rfrandse** [comment]
<a href="https://github.com/geissonator"><img src="https://avatars2.githubusercontent.com/u/1612261?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geissonator](https://github.com/geissonator)**
_Wednesday Jan 03, 2018 at 14:59 GMT_

----

https://github.com/openbmc/docs/blob/master/openbmc-systemd.md is where the base doc is now.

**Comment by kunyi731** [comment]
Long time ago I was experimenting with systemd-analyze generating the vector file for the targets dependency, and got some good results. We might be able to include some graphics like this?

# systemd-analyze dot 'obmc*@0.target' > obmc_start_deps.dot

scp the .dot file to workstation and 

cat obmc_start_deps.dot | dot -Tsvg -Kdot > obmc_start_sequence_dot.svg

**Comment by amboar** [comment]
The problem is systemd-analyse  can't resolve parameterized unit dependencies and the graph looks like a circular dependency mess as a consequence. Or at least did back when I was looking at it

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
