### ISSUE TITLE
PSU Information Read

### ISSUE THREAD

**Issue by slylinux** [ibm-openbmc/dev#1050]
Read power supply information and pass back

**Comment by vishwabmc** [comment]
@slylinux thanks for creating it. Do we have some more details on this ?

**Comment by slylinux** [comment]
we want to read some information such as psu fw version,manufacture ,SN,Power,Voltage,etc.
do you have any suggestion?@vishwabmc

**Comment by vishwabmc** [comment]
> we want to read some information such as psu fw version,manufacture ,SN,Power,Voltage,etc.
> do you have any suggestion?@vishwabmc

@slylinux Have you looked at inventory D-Bus object ?. They are in /xyz/openbmc_project/inventory/

**Comment by vishwabmc** [comment]
Okay .. here is the command :

1/. login to BMC : curl -k -H "Content-Type: application/json" -X POST https://$bmc_ip/login -d '{"username" :  "root", "password" :  "$password"}'

This gives some tokens on success:

{
  "token": "xxxxxxxxxxxxxxxxxxxxx"
}
......................................
2/. $ curl -k -H "X-Auth-Token: <token from above>" -X GET https://$bmc_ip/xyz/openbmc_project/sensors/power/ps0_input_power
{
  "data": {
    "CriticalAlarmHigh": false,
    "CriticalAlarmLow": false,
    "CriticalHigh": 2500000000,
    "CriticalLow": 0,
    "Functional": true,
    "MaxValue": 0,
    "MinValue": 0,
    "Scale": -6,
    "Unit": "xyz.openbmc_project.Sensor.Value.Unit.Watts",
    "Value": 126000000,
    "WarningAlarmHigh": false,
    "WarningAlarmLow": false,
    "WarningHigh": 2350000000,
    "WarningLow": 0
  },
  "message": "200 OK",
  "status": "ok"
}
---------------------------------------------

**Comment by mine260309** [comment]
@vishwabmc Good to see that is kind of ready.
Be noted that now we have `VersionPurpose.PSU`, so the `Purpose` property could be updated.
And for PSU code update, we need to know the current code version of the PSU as well.

**Comment by vishwabmc** [comment]
@mine260309 thanks.. So you are going to support: https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Software/Version.interface.yaml#L34 .. Does that mean, the current implementation having `Other` goes away ?

For the "Code version", is this not the one ? https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Software/Version.interface.yaml#L4

**Comment by slylinux** [comment]
@vishwabmc Yes, psu fw version is the same as https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Software/Version.interface.yaml#L4.
ips will add some other info such as vendor id,SN and rated power etc.

**Comment by bjwyman** [comment]
Depending on which system type this is referring to, the psu-monitor in the openbmc/witherspoon-pfault-analysis repository will fill in the SN, some Version property, PN/FN, CCIN, and other D-Bus properties. This application runs on Witherspoon and Swift systems.

https://github.com/openbmc/openbmc/blob/master/meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis_git.bb

https://github.com/openbmc/openbmc/blob/master/meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/power-supply-monitor%40.service

https://github.com/openbmc/openbmc/tree/master/meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/witherspoon/obmc/power-supply-monitor

https://github.com/openbmc/openbmc/tree/master/meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/swift/obmc/power-supply-monitor

https://github.com/openbmc/witherspoon-pfault-analysis/blob/5b2964fa8e57c46d60c0c0d95d5668c9f9a5ce23/power-supply/power_supply.cpp#L627

**Comment by wangzqbj** [comment]
tasks:

- IPS psu driver 
Applied to hwmon-next: https://lists.ozlabs.org/pipermail/openbmc/2019-August/017694.html
-  Port witherspoon-pfault-analysis to support  ips psu

**Comment by bjwyman** [comment]
I have been watching this, and seen the updates.
I did re-track down what "hwmon-next" refers to and found the two patches:
https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/commit/?h=hwmon-next&id=2c90f125381e69c9951bcd54e30038b1144f6317

https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/commit/?h=hwmon-next&id=5d0bd5d101dc629a34f0e318bb70c608411f1c9c

**Comment by bjwyman** [comment]
It also has now made it to linux-next:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tree/Documentation/hwmon/inspur-ipsps1.rst?h=next-20190823

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/Documentation/devicetree/bindings/trivial-devices.yaml?h=next-20190823&id=5d0bd5d101dc629a34f0e318bb70c608411f1c9c

**Comment by lxwinspur** [comment]
-  Add an example JSON file based on phosphor-power/power-supply
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/25662
- Update to get PSU Asset information from parsing JSON file
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/25664
