### ISSUE TITLE
eBMC: kdump enablement

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1058]
A story to track enabling kdump within OpenBMC. As we look at eBMC and the requirements that come with it, we need to ensure we have the ability to debug kernel based failures without the need for recreates. There is a story on the BMC dump application side to store these (https://github.com/ibm-openbmc/dev/issues/81) but nothing that deals with setting up the kernel to detect and collect dumps.

There are ongoing discussions about including mechanisms for the host to trigger a kdump and then reboot of the BMC for recovery scenarios. This story will need to handle those requirements as well.

Still a lot to be worked out here but wanted to get a placeholder story open so we don't forget about it.

**Comment by geissonator** [comment]
General agreement that this can be deferred until next year (1Q/2Q 2020). 

We do need to be sure when we do the kexec to the new kernel that the DMA code in the crashing kernel does not do something bad to the kdump kernel.

Seems like yocto has some recipes we can pull in 
- poky/meta/recipes-kernel/kexec/kexec-tools_2.0.19.bb
- meta-openembedded/meta-oe/recipes-kernel/crash/crash_7.2.5.bb

But this will need some more thought and investigation.

**Comment by geissonator** [comment]
The hope is that some kernel drivers will be using ftrace (for things like recording messages going back and forth over mctp). We need to ensure the kdump collects this ftrace data for post processing.

**Comment by rfrandse** [comment]
tracking in jira
