### ISSUE TITLE
GUI : FED : Consistent page layout

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1059]
## As Is
The page layout is inconsistent between pages. The white space varies from page to page and section to section.

## To Be
All pages will have a consistent layout based on a set of common patterns that can be used for any new or existing page.

## Requirements
- [x] Create a page component consisting of page (handles page max-width and margins) and page-title (h1)
- [x] Create a section component consisting of section (handles margins), section-title (replace subheading ruleset)
- [x] Update  systems overview page to use new elements

## References/Resources
Gerrit Review: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24143

**Comment by derick-montague** [comment]
The first two requirements were completed as part of #937 on the Power Usage page

**Comment by derick-montague** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24143

**Comment by derick-montague** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24143

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24143 merged
