### ISSUE TITLE
Know when to return hidden logs via Redfish

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1067]
Normal users should not receive redfish event logs for PELs with the 'hidden' flag set. 

However, there is a special user id for use on the web UI by IBM service personnel, and when logged in with that ID, the web UI needs to show event logs that are flagged as hidden.

**Comment by bradbishop** [comment]
> Normal users should not receive redfish event logs for PELs with the 'hidden' flag set.
Can we document why this is?  Is it just a usability concern or is the data sensitive and the system owner cannot have access to it? 

The former we can just add a new OEM field or map hidden to something that already exists, and the webui can filter on that property.

The latter is more complicated.  I'd guess we'd need an entirely new LogService to which only a specific user role has access to.  It seems like stuffing them in the same LogService as events that "normal" users have access to is going to be confusing.  They'll likely ask "why are there gaps in in the events?"

@thalerj thoughts on the above?

**Comment by spinler** [comment]
There is a new requirement that hidden logs can't have whatever the Redfish FRU callout fields are. (Also true when they are being sent to the HMC)

**Comment by gtmills** [comment]
Ties in with #2007 
Maybe we should just close one ? @spinler 
Does this track the D-Bus work ?

**Comment by spinler** [comment]
I think we need to put some sort of 'hidden' property on D-Bus that bmcweb can look at, so we can use this story for that. 

Is 'hidden' still the right abstraction for bmcweb do you think?

**Comment by spinler** [comment]
Similar pattern as #3081.

**Comment by sbteeks** [comment]
@vflobo is this issue addressed? Issue #2007 has dependency on #1067

**Comment by vflobo** [comment]
> 
> 
> @vflobo is this issue addressed? Issue #2007 has a dependency on #1067

@sbteeks The code changes are done but the dbus property is stuck behind the review and I am not able to get the logging changes in yet. I will let you know when this issue closes so that you can pick that up for #2007

**Comment by sbteeks** [comment]
Thanks @vflobo . What is the review link?

**Comment by vflobo** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/45139
