### ISSUE TITLE
eBMC State Management - Manual[Maintenance] / Normal Mode of BMC operation

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1068]
In the Enterprise system, we had this feature of Operating Mode [ Normal / Maintenance ] on FSP.

Normal Mode: Default mode that is set in the field. In this mode, BMC would do:
 - Automatic error recovery from terminations.
    - Meaning: It would reboot the box from termination state
- Automatic power on if the system has had power outages.

Manual mode: Mode that is set in the lab / manufacturing. In this, BMC would do:
  - No recovery from termination
  - No Auto power on if the system is coming back from a power outage
  - Asks for termination if the system encountered a HW error.
```
This mode was also used by system firmware to see if the partitions need to be automatically started for example.

Opening this issue to see the need of this in eBMC. For example:

[ - ] Why does the system firmware care if the system booted because user did it or the APOR mechanism did it ?
  - If needed, we need to device a PLDM way to share this information.

[ - ] What is the field usecase ?

[ - ] TBD

**Comment by geissonator** [comment]
@ryanarnell has interviewed some customers and they are familiar with manual mode and have used it for different service scenarios.

**Comment by vishwabmc** [comment]
> @ryanarnell has interviewed some customers and they are familiar with manual mode and have used it for different service scenarios.

I thought Manual mode was meant for the lab.. Do we know what customers had to use that ?, and If so, how did they use it ?.

**Comment by geissonator** [comment]
> I thought Manual mode was meant for the lab.. Do we know why customers had to use that ?, and If so, how did they use it ?.

It's definitely an option within ASM when powering on the systems. Sounds like they use it when  diagnosing an issue with the system.

**Comment by vishwabmc** [comment]
> It's definitely an option within ASM when powering on the systems. Sounds like they use it when diagnosing an issue with the system.

yeah.. I logged into ASMI using the ID that is meant for the customer and I can see we let 'em choose Normal/Manual. So, yeah I agree.. 

This can be something in phosphor-settings. I can probably start on cooking one..

**Comment by geissonator** [comment]
Great. Be good to engage the community, see if it's something other companies would like. Generically, it's allowing the system to be booted without any type of recovery enabled.

**Comment by ryanarnell** [comment]
Yes. Andrew sums it up right. Also @vishwabmc if you need to ask anything to our customers, feel free to reach out to me.

**Comment by vishwabmc** [comment]
I have sent an email to the community on this. Will see......

**Comment by mzipse** [comment]
@vishwabmc , are you working this for the first MFG delivery?

**Comment by geissonator** [comment]
Create setting, state manager monitors setting and switches between recoveryoff and recoveryon.

**Comment by vishwabmc** [comment]
> @vishwabmc , are you working this for the first MFG delivery?

@mzipse This is not really needed for MFG delivery. For MFG, `obmcutil disablerecovery` would do.

**Comment by vishwabmc** [comment]
Tasks involved :

- [ ] Defining a setting 
- [ ] Using the setting in phosphor-state-manager and calling disable recovery ( can be part of systemd target too I think ).

Note: All the users that have a need to know the mode, will consult the settings and then take the action

**Comment by jinuthomas** [comment]
@vishwabmc 
Just curious , will there be a setting for manual mode / Normal mode that can. be set/ or read  ?

**Comment by geissonator** [comment]
@gtmills I think the plan here was to identify the individual pieces of "Manual Mode" and provide Redfish API's for those? Then a user would just set them individually? Like the terminate on hw callout and disabling of re-ipl. Or do you think Redfish would be interested in a generic "disable all system recovery" option?

**Comment by spinler** [comment]
There is bit in the SRC for normal vs maint, so if you are dropping that we'll need to discuss with the stakeholders if it needs to be replaced with multiple status bits.

**Comment by gtmills** [comment]
@geissonator We can ask Redfish but I'm not sure if our case is very strong. We want to call 1 API vs 3? Or is there additional things this system recovery would/could do?
Does Bios attritube make any sense here?

**Comment by geissonator** [comment]
I don't think a BIOS attribute works because these are properties used by the BMC as well. Basically from a user interface perspective, you can either set one thing (manual mode) and have that underneath the covers set all of the corresponding settings OR make the user set each individual setting.

If we go with the second option then we'll have to work with Matt for which setting to look at and map to "manual" vs. "normal" mode.

**Comment by gtmills** [comment]
Or ask stakeholders if it is needed?

**Comment by geissonator** [comment]
May be able to just put this under https://github.com/ibm-openbmc/dev/issues/1977 but there's some more technical discussion required with @tomjoseph83 to understand how we get settings that are needed by both the BMC and the Host into the BIOS design.

**Comment by derick-montague** [comment]
I don't see this listed as a BIOS setting in #1977. We have a dependency on this story for #973 and #1131.

**Comment by geissonator** [comment]
Manual mode breaks down to these two D-Bus properties:

1) Tell firmware to not recover and instead quiesce sysetm on any error with callout
```
busctl set-property xyz.openbmc_project.Settings /xyz/openbmc_project/logging/settings xyz.openbmc_project.Logging.Settings QuiesceOnHwError b true
```
This does not have a Redfish API.

2) Tell firmware to leave system powered off if there is a power loss
```
busctl set-property xyz.openbmc_project.Settings /xyz/openbmc_project/control/host0/power_restore_policy xyz.openbmc_project.Control.Power.RestorePolicy PowerRestorePolicy s xyz.openbmc_project.Control.Power.RestorePolicy.Policy.AlwaysOff
```
The Redfish API for this one is:
```
curl -k -X PATCH -d '{"PowerRestorePolicy":"AlwaysOff"}' https://${bmc}/redfish/v1/Systems/system
```
This is also a customer setting though so I'm not sure how the GUI differentiates between the customer setting and the override of manual mode here?

**Comment by mzipse** [comment]
@gtmills @geissonator , what the remaining work here?  Replace the busctl commands with redfish APIs for the GUI to use?

**Comment by gtmills** [comment]
Need to implement the Redfish API here.

**Comment by gtmills** [comment]
Just need to implement the Redfish here for AutomaticRetryConfig. 
D-Bus is here.

**Comment by lxwinspur** [comment]
@gtmills @mzipse 
> Just need to implement the Redfish here for AutomaticRetryConfig.

I noted that this property has been implemented
https://github.com/openbmc/bmcweb/commit/6bd5a8d
https://github.com/openbmc/bmcweb/commit/69f3530

Maybe I am wrong, or I am missed something, Could you kindly explain it? Thanks :)

**Comment by gtmills** [comment]
Listed the wrong property above. It should be

```
        "StopBootOnFault": {
            "enum": [
                "Never",
                "AnyFault"
            ],
            "enumDescriptions": {
                "AnyFault": "The system should stop the boot on any fault.",
                "Never": "The system performs any normal recovery actions during boot if a fault occurs."
            },
            "enumLongDescriptions": {
                "AnyFault": "This value shall indicate the system will stop the boot if a fault occurs.  This includes, but is not limited to, faults that affect performance, fault tolerance, or capacity.",
                "Never": "This value shall indicate the system will continue to attempt to boot if a fault occurs."
            },
            "type": "string"
        },
 ```
 Correct @geissonator  and it maps to the 3 above?

**Comment by zhanghaodi** [comment]
Commit:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/44175

**Comment by gtmills** [comment]
@zhanghaodi Can you address comments on https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/44175 and try to get that in upstream ?
If it doesn't get in soon (let's say by 9/17) can we create a PR here: https://github.com/ibm-openbmc/bmcweb

**Comment by zhanghaodi** [comment]
@gtmills The comments have been resolved and I have submitted them.

**Comment by gtmills** [comment]
@zhanghaodi Can you resolve merge conflicts on https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/44175 ? 
Can you also create a PR here against 1020 https://github.com/ibm-openbmc/bmcweb/tree/1020 ? 
We need this for the GUI. 
Thanks!! 
FYI @mzipse

**Comment by zhanghaodi** [comment]
@gtmills Merge conflicts have been resolved,and I have create a PR https://github.com/ibm-openbmc/bmcweb/pull/116.

**Comment by mzipse** [comment]
@gtmills , the above PR is merged.  Can this be closed or marked "Code Review in Driver"?

**Comment by gtmills** [comment]
For this to be closed we need  https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/44175  in. 
This has been pulled downstream here: 
ibm-openbmc/bmcweb#116 so marked as "Code Review in Driver"

**Comment by lxwinspur** [comment]
@gtmills  @mzipse 
Meregd by: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/44175
Please close this issue.
