### ISSUE TITLE
GUI : FED : Header information rendering as variable name

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1069]
## Expected Behavior
Items in header are rendered using variable values.

## Actual Behavior
Items in header are rendered using variable names.

## Steps to Reproduce the Problem

  1. Open BMC in Safari

## Specifications
  - Browser: Safari

## Screenshot
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/dac9e6c7-3421-49b3-9725-c47674df02f7)

## Internal Tracking
- SW472020

**Comment by gtmills** [comment]
Only see on Safari

**Comment by derick-montague** [comment]
Works fine locally

![image](https://user-images.githubusercontent.com/1183515/62500446-17056c00-b7ac-11e9-9db5-6aee82dc3227.png)

**Comment by derick-montague** [comment]
Seems that when loading from the IP Address, the user can also not log out in Safari. I suspect it is related to the https certificate and Safari settings. If I use the image we created for front-end work with the security flags set to true to turn off security, it works fine as shown in the image in the above comment.

**Comment by rahulmah** [comment]
@Derick Montague: As discussed, I tried installing CA signed certificate (i.e. valid certificate) on my system and I still see this issue with Safari browser.

![image](https://user-images.githubusercontent.com/17079490/62639803-f11fc900-b95d-11e9-8e25-365fc66be7e8.png)

**Comment by yoshiemuranaka** [comment]
Seems to fix #1101

**Comment by derick-montague** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24404

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24404 merged
