### ISSUE TITLE
Document OpenBMC Dump API and usage

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#107]
<a href="https://github.com/dkodihal"><img src="https://avatars1.githubusercontent.com/u/22700515?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dkodihal](https://github.com/dkodihal)**
_Thursday Nov 30, 2017 at 15:45 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2689_

----

**Comment by rfrandse** [comment]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ojayanth](https://github.com/ojayanth)**
_Thursday Dec 14, 2017 at 06:08 GMT_

----

# **Status** 
12/14  Interface Documentation review is in progress. Working on Dump plugin documentaion.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-debug-collector/+/7066/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
