### ISSUE TITLE
DIMM's SizeMiB and MemorySummary TotalSystemMemoryGiB

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1070]
Currently, 
 ```"Memory": {
   "@odata.id": "/redfish/v1/Systems/system/Memory"
 },
 "MemorySummary": {
   "Status": {
     "State": "Disabled" 
   },
   "TotalSystemMemoryGiB": 0
```
```
 curl -k https://${bmc}/redfish/v1/Systems/system/Memory/dimm9
{
  "@odata.context": "/redfish/v1/$metadata#Memory.Memory",
  "@odata.id": "/redfish/v1/Systems/system/Memory/dimm9",
  "@odata.type": "#Memory.v1_6_0.Memory",
  "Id": "dimm9",
  "Manufacturer": "Micron Technology",
  "Name": "DIMM Slot",
  "PartNumber": "",
  "SerialNumber": "0x1434d91a",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  }

```

SizeMiB is a  OCP Server Hardware Management requirement

**Comment by gtmills** [comment]
Sounds like Hostboot already sends this down. 

Daniel Crowell 12:53 PM
we do send the size down in the fru inventory now, but it is a human readable string

Daniel Crowell 1:03 PM
there isn't a defined field for that in ipmi so it is all just strings

William Hoffa 1:13 PM
We are going to modify the DIMM Fru Inventory record we send you for Axone. But it already should contain the dimm size as a string as part of that record. Or are you looking for this information in a different IPMI message? We definitely don't send it any other way than via the Fru Inventory.

    we are going to modify the DIMM Fru Inventory record

== We are going to send you more data about other parts of the DDIMM. We already send the dimm size, that will remain unchanged.

**Comment by lxwinspur** [comment]
This change is being reviewed.
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25754

**Comment by mine260309** [comment]
A correction: the `SizeMiB` is not part of `Memory`, but in `Region`.
The correct property should be `CapacityMiB`.

@gtmills Could you confirm?

**Comment by gtmills** [comment]
@mine260309 is correct. You can see this here: https://redfish.dmtf.org/schemas/v1/Memory.v1_8_0.json

**Comment by mine260309** [comment]
DIMM interface is going to be added:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/24976

And this task depends on ipmid to implement the interface.

**Comment by tomjoseph83** [comment]
The DIMM size is part of the IPMI FRU Section: "Board" and IPMI FRU property : "Name". In OpenBMC it will need special data messaging to parse the the DIMM size from the property. This can be avoided if hostboot can pass the DIMM size as a custom field.

**Comment by mine260309** [comment]
Is the "custom field" well defined or some custom extension?

@tomjoseph83 Is it possible for you to push hostboot to send DIMM size (and possibly other properties) in custom field if you would like to go with this approach?

**Comment by geissonator** [comment]
We discussed today in our team meeting and decided that with what we know now, we'd like to just defer this story to when we have PLDM support in place. @dkodihal will ensure the appropriate work is defined to support this in PLDM. At this point we do not want to put more work into our IPMI stack and we don't want Hostboot to put any new effort into IPMI either.

Sorry for the confusion, sometimes you don't know if something is ready until you really dig into it. The work here will set a good base for when we have PLDM support for it.

**Comment by gtmills** [comment]
Daniel Crowell 
Once someone defines the interfaces to send inventory down, that would include whatever BMC needs

**Comment by mzipse** [comment]
Still waiting for feedback from the Hostboot team on interfaces.  We'll sit on this for now.

**Comment by gtmills** [comment]
The direction now for this is "The BMC can calculate the size based on the various fields in the SPD (ranks, capacity, width, etc), same as we do on the FSP"
@santoshpuranik Do you have a story to get this out on D-Bus? Or should this track that work ?

**Comment by gtmills** [comment]
The Redfish property is already mapped to a D-Bus property
https://github.com/openbmc/bmcweb/blob/c511b7febf37f211c97af0bf838dc7eb030586d0/redfish-core/lib/memory.hpp#L749
redfish-core/lib/memory.hpp:749

https://github.com/openbmc/phosphor-dbus-interfaces/blob/32304979b404c24e32f195d08[…]roject/Inventory/Item/PersistentMemory/Partition.interface.yaml

So the work is getting that property populated on D-Bus then this should work in Redfish / GUI.

**Comment by lxwinspur** [comment]
@gtmills @mzipse 

As far as I know, for the Dimm interface:
https://github.com/openbmc/phosphor-dbus-interfaces/blob/1e8c11bf2656ed4a5fb27baa2dec3a65763bb47e/xyz/openbmc_project/Inventory/Item/Dimm.interface.yaml

Has been implemented on the x86 system (`smbios-mdr`)
But there is no similar daemon to implement it on the POWER system(Correct?).
So will we have a new daemon to implement it in the future, or close this task?

**Comment by gtmills** [comment]
@santoshpuranik 
I think your team was going to calculate the size based on the various fields in the SPD (ranks, capacity, width, etc)?

Can your team own this story ?

**Comment by santoshpuranik** [comment]
Extend the scope of this story to also include parsing the SPD to get IBM VPD details like Serial Number, Part Number and CCIN

**Comment by gtmills** [comment]
I think this is done. Can we close @santoshpuranik or move to "Code Review in Drvier"?

**Comment by santoshpuranik** [comment]
All of this is merged upstream, so am closing this.
