### ISSUE TITLE
eBMC Flight Recorder

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1071]
Legacy code used a custom flight recorder with the following properties:

- In-memory (speed requirement and flash wear prevention)
- Able to run-time create flight recorder instances
- Automatic wrapping on a custom size limit (defined when creating flight recorder)
- Individual buffers (one software component could not wrap out another software components data)
- Ability to add arbitrary amount of most recent data into logs for later viewing

systemd-journald has replaced some of these legacy requirements but certain code functions still require a flight recorder like described above.

This story is to investigate these requirements, ensure they are all still required, engage the community, and look for open source options that could be used or enhanced to fill these requirements.

**Comment by rfrandse** [comment]
tracking in jira
