### ISSUE TITLE
Rainier Power BMC reset support - FF

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1072]
BMC reset - init all power/thermal function that is needed as appropriate (for example, ensure correct apps all started, ensure system-specific info read from appropriate config files, etc) - most of this should have been done in epic 875.

For pin-hole resets, Emile was going to hook up the PHR hw to directly reset all the "power" hw (power sequencer etc).

If bmc reset happened in middle of a power transition, power off.

Hot_restart - handle bmc reset to runtime, maintaining system powered on state.  cache/determine system state, re-init only as needed, re-post errors as needed, etc.

Persist system state and if it was in a power transition so system stays up if hot_restart, and so system powers everything off if it was in the middle of a power transition.

Known problem with fan watchdog results in fans staying at high speed after BMC reset.

If the BMC system has been booted, the host is running, and then the BMC itself is reset, the BMC state manager transitions thru all the power on targets again even though the system is already at runtime.  So the boot steps have to do checks, if necessary, to detect if the system is already up.  e.g. for VRM config, we don't want to redo that if the system is already up.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
