### ISSUE TITLE
Redfish: Set the power cap 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1076]
Need to be able to set the power cap from Redfish

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/21681 added reading the power cap.

**Comment by gtmills** [comment]
PowerLimit is Read/Write in Redfish

**Comment by wangkair** [comment]
I'm learning the existing code these days, and tried to override sensor values with redfish Patch, referring to the Voltages example of https://github.com/openbmc/bmcweb/search?q=413961de&type=Commits, but met an error "Invalid argument". Comparing the code https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/sensors.hpp#L2192 and the doc https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Sensor/Value.interface.yaml#L21, the current code uses double type, but the doc says the value type should be int64. It seems a scale difference. Why the code uses double here?

**Comment by wangkair** [comment]
Closed by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/26223.
