### ISSUE TITLE
GUI: FED:  Move Server Power Operations to Redfish

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1077]
The server on/off operations are currently calling the old API
https://github.com/openbmc/phosphor-webui/blob/c9c8e67bce63b13d81f1860f39832655d521b4ec/app/common/services/api-utils.js#L665

## Resources
[Slack conversation on System Operating Mode](https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1588352403238100)

**Comment by gtmills** [comment]
See: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW469388
Should also move the openbmctool to redfish for server power on/off

**Comment by derick-montague** [comment]
This will be done as part of https://github.com/ibm-openbmc/dev/issues/1215

**Comment by derick-montague** [comment]
@gtmills was this completed with #1215?

**Comment by gtmills** [comment]
Quiesced support was added here, 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/31868

Can we do this TODO and then we can close?
https://github.com/openbmc/webui-vue/blob/598bf7e96704f54400ec1730255168dd4d274218/src/store/modules/GlobalStore.js#L19

Probably should add support for DiagnosticMode as well  (    "State": "InTest")
https://github.com/openbmc/bmcweb/commit/83935af944c6f8f94497ce1e437730cc80f0002f

**Comment by derick-montague** [comment]
@yoshiemuranaka seems like we have not updated host state to redfish yet. If you look at Gunnar's comment above and the TODO item. Question is:

**Comment by yoshiemuranaka** [comment]
@derick-montague 
1. No, I don't think so–seems like it was originally created for Angular
2. Yes, probably since it's available

@gtmills Yes, I will push something for Redfish 'Quiesced' mode. Not sure what to do with DiagnosticsMode in the hostStateMapper. This is used to change the Power status icon in the app header. Do you think a yellow warning icon would be appropriate for this mode?
https://github.com/openbmc/webui-vue/blob/598bf7e96704f54400ec1730255168dd4d274218/src/store/modules/GlobalStore.js#L10

**Comment by yoshiemuranaka** [comment]
HostStateMapper also used to show host state as text on the server power operations page. Should we show "Diagnostics mode" or "In test" or something else?

![Screen Shot 2020-05-13 at 12 34 21 PM](https://user-images.githubusercontent.com/8097306/81856817-2cb37900-9516-11ea-8d15-50beb0c09de8.png)

**Comment by gtmills** [comment]
For "Diagnostics mode", yeah yellow warning icon seems reasonable. 
```
        - name: 'DiagnosticMode'
          description: >
            Host firmware is capturing debug information. Powering off your
            system while the host is in this state will prevent the debug data
            from being properly collected. The host will move to one of the
            other states once complete.
```

So yeah "capturing debug information", "processing debug", "Diagnostic Mode", "Capturing Debug"

**Comment by yoshiemuranaka** [comment]
@gtmills do you think I should just use the Status.State property to map the host status instead of checking for InTest/Quiesced?

https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/32284/1/src/store/modules/GlobalStore.js#59

**Comment by gtmills** [comment]
> https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/32284/1/src/store/modules/GlobalStore.js#59

Looks good to me. since looking at 2 properties, not trivial.. Could do something where you pass both / push more logic to that function but I think this is as clean as you can get. 
Thanks Yoshie!

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/32284

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/32284 merged
