### ISSUE TITLE
Phosphor-networkd : document API

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#108]
<a href="https://github.com/dkodihal"><img src="https://avatars1.githubusercontent.com/u/22700515?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dkodihal](https://github.com/dkodihal)**
_Thursday Nov 30, 2017 at 15:56 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2692_

----

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
This has been merged long ago.
https://github.com/openbmc/phosphor-networkd/blob/master/docs/Network-Configuration.md
