### ISSUE TITLE
eBMC State Management - IPL type, Hypervisor, HMC Managed, FW Side

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1080]
Need to provide some back end data required by the op-panel and probably the webui. This requirement comes from a spreadsheet from Gunnar titled "P9 Op panel functions on ZZ 041919 JAC V4 print"

The OS IPL type and Hypervisor items are probably settings that will end up being hosted by phosphor-state-manager applications. HMC managed and FW mode will come from those respective areas.

May need separate stories for each but for now track in just one:
- OS IPL type (A, B, C, D)
- Hypervisor type (PowerVM, OPAL)
- HMC managed or not
- FW mode (P, T)

FYI @ratagupt @anoo1 @vishwabmc @gtmills

**Comment by vishwabmc** [comment]
>     * OS IPL type (A, B, C, D)
`It was part of IPL parameters that got into HDAT. In one of the previous discussions, we have closed on this. The expectation is not on the State Manager and this is something PHYP would use PLDM BIOS settings for.  

>     * Hypervisor type (PowerVM, OPAL)
 --> This one also should not be any owned by State Manager. It can be a PLDM command / HDAT construction thing
 
>     * HMC managed or not

--> Yeah. this one seems BMC related. 

>     * FW mode (P, T)
--> These are the sides and not modes. Modes are [Manual]/[Normal]

**Comment by vishwabmc** [comment]
@geissonator I think, this may not put any requirements on State Management 

For example: PHYP / HDAT reads much of these directly from data sources.
```
OS IPL type --> This needs to be some PLDM / PDR thing
Hypervisor Type --> Should be part of setting
HMC Managed or not --> Should be again some setting / at least not anything with State Management 
P/T side --> PHYP already reads this via PDR or so..
```

May be, we just need to close with 'em and see if all this is already available and/or will be available through the framework that they are already using.

**Comment by geissonator** [comment]
Closing this one out based on above comments and what we've seen so far.
