### ISSUE TITLE
Store the BMC dump state in SRC hex data word 2

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1082]

**Comment by spinler** [comment]
In: SRC word 2   (hexData[0]), second byte, second nibble, bit 0:
0x8 = BMC dump available
0x0 = BMC dump not available

BMC dumps are represented by D-Bus objects, so we should able to look for those.

**Comment by sumitk56** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/46145
