### ISSUE TITLE
Store the flash side in SRC hex data word 2

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1083]
See PEL spec.

**Comment by spinler** [comment]
This information isn't readily available on the BMC, and really isn't that useful anyway, so we decided to just hardcode the value to Permanent.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35113

Though really this just documents that field as the default value of zero is what we wanted anyway.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35113 merged
