### ISSUE TITLE
Store the last progress code in SRC hex data word 4

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1086]
see PEL spec

**Comment by spinler** [comment]
@manojkiraneda What would the D-Bus API look like to always find the latest progress code?

**Comment by manojkiraneda** [comment]
@spinler the flow of progress codes are caught up with the Raw Value Property hosted by snoopd daemon.Here is the dbus GET request for that:
```bash
busctl call xyz.openbmc_project.State.Boot.Raw /xyz/openbmc_project/state/boot/raw0 org.freedesktop.DBus.Properties Get ss xyz.openbmc_project.State.Boot.Raw Value
v (tay) 6004496007600167200 72 2 0 0 1 0 0 0 72 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 83 84 65 78 68 66 89 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32
```

**Comment by vflobo** [comment]
@manojkiraneda Looks like this progress code is only updated when we have the system in AIX? is that what is required here?

**Comment by spinler** [comment]
The spec says:
```
Hex value of the SRC of the last progress code
This field is reserved (set to zero) for progress codes. In
addition, it is only present for errors occurring prior to or
during IPL. After the platform has been IPL'ed, this field
is set to 0.
```

**Comment by spinler** [comment]
There is a commit up for this at https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/48042.  However the issue is that nothing clears progress codes on a power off so any errors at power off show a progress code from the last time PHYP was booted.  Since the BMC doesn't create any progress codes itself anyway, I don't see this as important as it as on previous generations.

**Comment by spinler** [comment]
I revived that commit, and it should merge shortly.

**Comment by rfrandse** [comment]
tracking in jira
