### ISSUE TITLE
GUI : FED : IE 11 - Primary Navigation Icon Positioning

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1093]
## Expected Behavior
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/95db4eef-401f-4e20-b287-9cda381f2c4f)

## Actual Behavior
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/60dff786-a824-4287-84d7-b6415d3e8403)![image.png]

## Steps to Reproduce the Problem

  1. View any page in Internet Explorer 11

## Specifications
  - Browser: Internet Explorer
  - Version: 11

## Internal Tracking
- SW472531

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25878

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25878 merged
