### ISSUE TITLE
GUI : FED : IE 11 - Server Overview - Quick Links SOL link

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1094]
## Expected Behavior
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/948c594a-3f20-4d0d-95eb-83e9d8b8dec4)

## Actual Behavior
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/724668a2-fb0d-4414-be58-163664a9c7ca)

## Steps to Reproduce the Problem

  1. Visit Server Overview page on IE 11

## Specifications
  - Browser: Internet Explorer
  - Version: 11

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/26096

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/26096 merged
