### ISSUE TITLE
eBMC State Management - IPL types

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1095]
On Enterprise boxes, we had the usage of IPL types, which is a number like 0x00000002 etc..

An IPL type indicated why the system is being taken from one state to another and who was responsible for initiating that.

For example: If someone did a Power-On using the HMC, then FSP would assign a number indicating that it's a power-on request coming from HMC. Similarly, FSP would assign a number if the power-on / power off request came from ASMI / Operator Panel / CLI. Under the cover, all of these types resulted in executing the same power-on / power-off sequence.

If FSP had to automatically power-on the box because it came back from an AC loss, there would be a number indicating that.

If FSP did re-IPL post termination, then again, there would be a number for that .. and the list goes on .......

FSP would pack this information as part of HDAT to be consumed by PowerVM, which in-turn would share with OS on some of these.

Opening this issue to investigate the need of such types in eBMC. For example: It may not make sense to have different types just to differentiate who initiated a particular operation.

Many components did take decisions based on the IPL types and made it a critical need.

Also, why is PowervM / OS interested in it... 

Here is my proposal so that the code does not become IBM specific:

1/. Take out these IPL types
2/. Have individual components be responsible for branching their logic depending on their own data / system condition etc..
3/. If it is impossible to get rid of IPL type for whatever reason, depending on the need, support only minimal set instead of one for each.

**Comment by spinler** [comment]
These were captured in every PEL as well I think?  Let me know if there is some equivalent we'd like to do.

**Comment by geissonator** [comment]
Close out until we have a reason for this.
