### ISSUE TITLE
GUI : FED : Expiring certificate icon missing from certificate list

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1096]
#### When a certificate is expiring, an icon should appear next to the certificate. 

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/21bcd1dd-1f69-447e-8860-ed38fdcd85b7)

#### When the certificate is expiring, no icon is present to show visual indication of the expiration.

![image](https://user-images.githubusercontent.com/1183515/62974688-6536f280-bdde-11e9-814d-55999e2ace8f.png)

## Steps to Reproduce the Problem

  1. Go to certificate page and find the date that certificate will expire
  1. Update the date and time on your system or upload a certificate with an expiration date in the next week
  1. Go back to the certificates page

## Specifications
Invision Prototype: https://ibm.invisionapp.com/share/K8NYRVZVEC5#/screens/319070968

## Internal Tracking
SW472527

**Comment by miramurali23** [comment]
@derick-montague @jandraa when is a good time to display the warning message? Ex: 30 days until the certificate will expire?

**Comment by nicoleconser** [comment]
We've had users say that 30 days is too long — i.e. they may receive the warning then forget about it. Can we show the warning at intervals, to be safe? i.e. 60 days, 30 days, 10 days?

**Comment by derick-montague** [comment]
@nicoleconser 
> Can we show the warning at intervals, to be safe? i.e. 60 days, 30 days, 10 days

That brings in questions like:
1. How long would the interval be visible for?
1. Should there be different visual indicators based on the the interval so the user realizes there is some urgency?
1. Would more user testing be needed?
1. Is that needed to fix this bug for OP940?

**Comment by jandraa** [comment]
30 days is good and I think we show it until they 'x' out of it or they resolve the issue.
If the 30 days have past and the certificate has now expired, the message should change to be an error message (red) and say 'The uploaded ______ certificate is expired and must be replaced with a new certificate.' 

@derick-montague 
> Is that needed to fix this bug for OP940?
Are you referring to adding the icon to the table or to adding the message on the top entirely?

Also @miramurali23 I see that the message in the screenshot Derick pasted says the 'server' certificate expired, and in the table we call it 'HTTPS' certificate. Can we make those consistent to HTTPS?

**Comment by derick-montague** [comment]
> Are you referring to adding the icon to the table or to adding the message on the top entirely?

Referring specifically to having multilateral intervals.

**Comment by miramurali23** [comment]
Yes -- will make that consistent @jandraa ! So when they click the x button the icon should disappear?

**Comment by miramurali23** [comment]
@jandraa @gtmills @derick-montague Do you guys know if we are checking the expiration date with today's date or are we checking it with NTP Server time and date (found under Server configuration --> Date and Time)

**Comment by jandraa** [comment]
> So when they click the x button the icon should disappear?
We talked and there will not be an x button. The notification will persist until a new certificate has been uploaded. 

>Do you guys know if we are checking the expiration date with the browser's date or are we checking it with NTP Server time and date (found under Server configuration --> Date and Time)
A certificate comes with a date and time expiration, right? I would think we map that to whatever has been configured in the Date and Time panel and check against that.

**Comment by miramurali23** [comment]
Confirmed with Rahul, we are checking expiration date with bmc time. Thanks @jandraa !!

**Comment by miramurali23** [comment]
Gerrit PR link: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24549

**Comment by gtmills** [comment]
Resolves https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24549
