### ISSUE TITLE
GUI : FED : IE 11 - Edit button on SNMP Settings page not working

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1097]
#### Clicking the edit button on an SNMP manager will trigger edit mode. 
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/7b74e63b-ba71-4237-9296-b867775ddc86)

#### Clicking the edit button does not change the mode.
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/ef160930-d905-464b-a25d-a0ab1d474bee)

## Steps to Reproduce the Problem

  1. Go to SNMP Settings page
  1. If a manager doesn't exist, add one and save
  1. Click the edit button

## Specifications
  - Browser: Internet Explorer
  - Version: 11

## Internal Tracking Reference
- SW472541

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25019

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25019 merged
