### ISSUE TITLE
GUI : FED : IE 11 - Replace certificate button not working

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1098]
#### Clicking the replace certificate button will open the certificate upload interface.
![image](https://user-images.githubusercontent.com/1183515/62789807-558e7580-ba8f-11e9-8cdb-5d116ad12a93.png)

#### Clicking the replace certificate button does not open the certificate upload interface
![image](https://user-images.githubusercontent.com/1183515/62789897-8a9ac800-ba8f-11e9-8ed9-c88eac146d92.png)

## Steps to Reproduce the Problem

  1. Open the Certificate Management page in IE 11
  1. If a certificate does not exist, add one
  1. Click the replace certificate icon

## Specifications
  - Browser: Internet Explorer
  - Version: 11

## Internal Tracking
- SW472543

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24726 merged
