### ISSUE TITLE
GUI : FED : IE 11 - Network Settings - Not able to remove IP

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1099]
## Expected Behavior
Clicking on remove in for an IPv4 Address should remove the item from the screen allowing the user to either cancel or save the change.

## Actual Behavior
Clicking on remove for an IPv4 Address removes the item and triggers a full page reload and redirects the user to the Server Overview page.

## Steps to Reproduce the Problem

  1. In IE 11, go to Server Control > Network Settings
  1. If a static IPv4 address does not exist, add one and save the settings
  1. Click the remove button (text)

## Specifications
  - Browser: Internet Explorer
  - Version: IE 11

## Internal Tracking
- SW472540

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24752 merged
