### ISSUE TITLE
GUI : FED : Safari - No Power Operation button shown on page

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1100]
## Expected Behavior
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/83d71d49-cec0-4c32-958d-9686fed52b4f)

## Actual Behavior
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/30dbbb94-9c37-431e-aa68-4c132723118b)

## Steps to Reproduce the Problem

  1. Go to Server Control > Server Power Operations in Safari

## Specifications
  - Browser: Safari

## Internal Tracking
- SW472039

**Comment by derick-montague** [comment]
This and #1069 are most likely related to web socket subscriptions. See the console in Safari developer tools.

> Refused to connect to wss://9.5.180.233/subscribe because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24759

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24759 merged
