### ISSUE TITLE
GUI : FED : Safari - SoL Console does not display data

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1102]
## Expected Behavior
When the server power is on and the user navigates to the SoL page, data should be displayed in the console.

## Actual Behavior
When the server power is on and the user navigates to the SoL page, data is not being displayed in the console.

## Steps to Reproduce the Problem

  1. Go to the Server Control > Serial over LAN console page in Safari

## Notes
Safari is also not showing the system as running on the Server power operations page. This could be related to #1100.

## Specifications
  - Browser: Safari
 
## Internal Tracking
- SW472505

**Comment by yoshiemuranaka** [comment]
I'm not sure how console should look if working. When I navigate to the page on Chrome it looks the same as safari. 
on chrome:
<img width="1421" alt="Screen Shot 2019-08-22 at 11 40 01 AM" src="https://user-images.githubusercontent.com/8097306/63541150-5503cf00-c4d2-11e9-8a08-637775ab8224.png">

**Comment by rahulmah** [comment]
@yoshiemuranaka : You need to power on the system to watch the console data. If system is already booted to OS, then press any key to see login prompt on the screen. At power off state you will not see any data in console.

![image](https://user-images.githubusercontent.com/17079490/63829288-bfab8380-c986-11e9-9a4e-529318c61f39.png)

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24759

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24759 merged
