### ISSUE TITLE
GUI : FED : Safari - Refresh button and SoL Open in new tab button not functional

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1103]
## Expected Behavior
- When clicking on the refresh button in the header the page should refresh
- When clicking on the `Open in new tab` button on the Serial over LAN console page a new window should open.

## Actual Behavior
- When clicking on the refresh button in the header nothing happens
- When clicking on the `Open in new tab` button on the Serial over LAN console page nothing happens

## Notes
There are many Safari related bugs. It is possible that many of these issues are related and possibly resolving any of them could resolve these issues if they are related to JavaScript errors that are blocking execution of the actions discussed in this story.

## Steps to Reproduce the Problem

  1. Click on the refresh button in the header from any page
  1. Go to the Server Control > Serial over LAN console page and click the `Open in new tab` button

## Specifications
  - Browser: Safari

## Internal Tracking: 
- SW472511

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24724 merged
