### ISSUE TITLE
Excessive journal logging from IpKVM

### ISSUE THREAD

**Issue by eddiejames** [ibm-openbmc/dev#1105]
When the host shuts down, the IpKVM application continues to attempt input operations on the USB gadget. This results in many kernel and journal error messages.

**Comment by eddiejames** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/obmc-ikvm/+/24327/1

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/obmc-ikvm/+/24327 merged
