### ISSUE TITLE
Redfish: PATCH PowerSupplies/Fan LED

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1106]
Need to be able to PATCH PowerSupplies/Fan IndicatorLED like we do for the system IndicatorLED. 
```
PATCH /redfish/v1/Systems/system 

{
    "IndicatorLED": "Lit"
}
```

**Comment by gtmills** [comment]
There was some concern here from @vishwabmc since we were calling the physical LEDs directly

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/dev/issues/287 added these LEDs

**Comment by mzipse** [comment]
To be tracked as part of #2082 .  Closing.
