### ISSUE TITLE
VRM bind/unbind scripts

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1107]
Even though we don't actually need to bind or unbind the device drivers to run workarounds during a boot (yet), the MFG toolkit still wants us to provide a script to they can unbind them and do whatever it is they do.

**Comment by amboar** [comment]
What do they expect this script to contain? What problems is it going to solve over them unbinding/binding manually?

**Comment by spinler** [comment]
@trajeswaran Could you explain your use case?

**Comment by spinler** [comment]
not needed anymore
