### ISSUE TITLE
Redfish: Power metrics (average & maximum)

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1108]
The change done under the following issue needs to be pulled into bmcweb to provide the power aggregation history data in to the power metrics section of Redfish.

https://github.com/ibm-openbmc/dev/issues/290

Confirm this fixes https://github.com/ibm-openbmc/dev/issues/1394 as well.

**Comment by gtmills** [comment]
See https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24002

**Comment by gtmills** [comment]
@derekhoward55 @msbarth Can we just do this via Redfish Telemetry, specifically the "Calculated" part of the Telemetry Service.

**Comment by gtmills** [comment]
The thinking was yes, this can be done with the telemetry service

**Comment by derekhoward55** [comment]
Yes, short term we have a downstreamed solution, but long term this should be done with the telemetry service.

The 30s ave can already be collected (via the psX_input_power sensor), and a peak can be calculated based on the highest 30s ave, but as of yet the psu-determined peak is not collected (not an EnergyStar requirement).

**Comment by rfrandse** [comment]
tracking in jira
