### ISSUE TITLE
Redo layout of /docs

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#111]
<a href="https://github.com/gtmills"><img src="https://avatars3.githubusercontent.com/u/5455127?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gtmills](https://github.com/gtmills)**
_Friday Jan 12, 2018 at 18:36 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2783_

----

Our docs need some architecture/flow. Random bits of information currently. Look at what other projects do. Redo https://github.com/openbmc/openbmc README and have it be the starting point.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
No plans to do anything here, except for future documentation.  Closing this.
