### ISSUE TITLE
Rainier Simulation Power-On Epic

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1110]
https://github.com/ibm-openbmc/dev/issues/294 can be used as a reference to find gerrit commits that did these same stories for Swift.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Done

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Added some story points to cover the Stories that didn't have Story point estimates.
