### ISSUE TITLE
Rainier GPIO definitions

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1114]
At the time of this writing, they're in 'skeleton/obmc-libobmc-intf/gpio_defs.json'.

Need these defined to power on the system, buttons, checkstop GPIO, chassis-cooling-type GPIO

See https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/20381 for reference.

**Comment by wrightjl1** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/25292
