### ISSUE TITLE
Rainier fan bringup support for simulation

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1116]
Need to work with simulation team to understand what is modeled and ensure the fan control code doesn't log any errors or cause the simulated system to crash.

FYI @msbarth

**Comment by geissonator** [comment]
Sounds like we can close this one out @msbarth ?

**Comment by msbarth** [comment]
@geissonator That's news to me. Has Rainier powered on in sim? I thought it only got to standby currently?

**Comment by geissonator** [comment]
I just thought you said there was no work here for simulation? But if there is, lets queue it up!

**Comment by msbarth** [comment]
I didnt say that. All I recall was mentioning that the cooling type application could be removed. I havent seen what's being included for fan configs in the Rainier image yet. But primarily as long as PDM isnt configured enough to shut the system down for any reason, we should be fine.

**Comment by geissonator** [comment]
ok, please use this story to do whatever is needed to ensure we can start bringup in simulation.
