### ISSUE TITLE
Create Rainier flash image for simulation start

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1117]
Go with just eMMC NAND or a NOR based one initially? What type of overlay filesystem? Need to work out these questions in this story.

**Comment by geissonator** [comment]
I think the final decision is to use a NOR based image with AST2500 SPI controller? Probably can reduce the points on this and call it done?

**Comment by anoo1** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/24734

**Comment by anoo1** [comment]
> @anoo1 we'll also need a file that can be used for virtual PNOR. Track with this story or somewhere else?

Let's use a new one - https://github.com/ibm-openbmc/dev/issues/1232

**Comment by anoo1** [comment]
Image already part of the build process, closing.
