### ISSUE TITLE
Rainier power sequencing support for simulation

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1120]
Update power on / power sequencing code for UCD90320 for simulation power on. Re-use existing support (power sequencing/skeleton/scripts) as appropriate.

Avoid stopping IPL as needed - assumption is simulation support will exist for UCD90320, appropriate gpios, etc.

Update system config files as needed.  Minimal pgood checking, this will be expanded when support for hw power on added.

Execute minimal ucd90320 sequencing.

**Comment by wrightjl1** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/25294
