### ISSUE TITLE
GUI : FED : Move to over to Redfish Sessions for login/ logout/

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1122]
This is needed before we can use the new expired password design. 
The old D-Bus API, according to @joseph-reynolds will not create a Session, when the password is expired. This session will be needed to change the password.

**Comment by miramurali23** [comment]
<img width="924" alt="Screen Shot 2019-09-16 at 11 18 58 AM" src="https://user-images.githubusercontent.com/11800028/64975594-051bec00-d875-11e9-9a65-d2fb0369e7a5.png">
The cookies for the D-Bus login call

<img width="1528" alt="Screen Shot 2019-09-16 at 11 22 40 AM" src="https://user-images.githubusercontent.com/11800028/64975624-16fd8f00-d875-11e9-9864-7e3ac187c0a8.png">
The cookies for the Redfish sessions call. I am creating using ngCookies. I am passing in the x-auth-token from the header as the XSRF token and the ID I am getting back from the response data to the SESSION key. Still I am getting unauthorized and I am unable to login. Does anyone have an idea why I am getting unauthorized? Do I need to pass in different key value pairs when I pass in the cookie for the redfish sessions call? @gtmills @joseph-reynolds

**Comment by joseph-reynolds** [comment]
Redfish does not use cookies.  Instead, a successful login (with password expired or not) will give you a HTTP response head which contains an X-Auth-Token.  You need to keep this token secret, and supply it on all subsequent HTTP requests.  <-- Does your web-app framework do this for you?

**Comment by miramurali23** [comment]
I am using an AngularJS service called ngCookies to store the x-auth-token I am getting from the HTTP response. I assumed that once it is a cookie, the framework will handle all other HTTP requests with that stored cookie I provided.  I guess a good question to ask is if I need to store anything else other than the x-auth-token? Maybe the key name I stored it as is wrong. Any thoughts? @joseph-reynolds @gtmills

**Comment by joseph-reynolds** [comment]
That sounds wrong.  Cookie based authentication is different from Token based authentication.  Don't want to accept, store, or create any cookies.  Drop them on the floor.  To use BMCWeb's Redfish APIs, you must use Token-based authentication, which means the X-Auth-Token you got when the session was created must be part of the HTTP request headers for all subsequent requests made by your session.  Doing so will enable access to the old-style REST APIs and Redfish APIs.  I don't know how to enable that in your framework, but you want to use X-Auth-Tokens and not use Cookies.

Technical reference: You can see how BMCWeb attempts different kinds of authentication.  In the line below, lines 34-54 show how X-Auth-Token auth, Cookie auth, and Basic auth are attempted in sequence.
https://github.com/openbmc/bmcweb/blob/d9207047c5883b610b462d9b661f45f99104498d/include/token_authorization_middleware.hpp#L34
