### ISSUE TITLE
GUI : FED:  Certificate Management: Generate CSR Modal and Certificate Modal close button accessibility

### ISSUE THREAD

**Issue by miramurali23** [ibm-openbmc/dev#1125]
- Add Aria-labels to close button in generate csr modal and certificate modal
- Add Aria-label to inform users when the modal is open and when the modal is closed

Refer to Generate CSR gerrit patch review comments for more accessibility issues

**Comment by derick-montague** [comment]
If this modal is converted to the bootstrap modal, this work might be handled for us.

**Comment by derick-montague** [comment]
No longer relevant due to vue rewrite #1555
