### ISSUE TITLE
GUI : FED: User Password Input Field does not have validation message

### ISSUE THREAD

**Issue by miramurali23** [ibm-openbmc/dev#1126]
As is:
![Screen Shot 2019-08-19 at 3.10.51 PM.png](https://images.zenhubusercontent.com/5cbe113007507b08996e8984/eded6cee-3dd4-4ba2-8215-be8c743843ab)

Should be:
Have "Field is required" underneath the red validation line when user tabs out of input field.

**Comment by derick-montague** [comment]
No longer relevant due to vue rewrite #1555
