### ISSUE TITLE
Rainier device driver updates for UCD90320

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1127]
The UCD90320 power sequencer is a follow-on to the UCD90160, which uses the UCD9000 DD.  Make the DD updates for additional slots etc.

**Comment by wrightjl1** [comment]
https://www.spinics.net/lists/linux-hwmon/msg06859.html

**Comment by wrightjl1** [comment]
Linux hwmon-next commits:
- https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/commit/?h=hwmon-next&id=771ca6875ff39f8870a9c069d57d57388b56c8cd
- https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/commit/?h=hwmon-next&id=76f2ee357da6ea26f95832197e658a51b8f73544

**Comment by wrightjl1** [comment]
OpenBMC device driver review patch:
- https://lists.ozlabs.org/pipermail/openbmc/2019-December/019761.html

**Comment by wrightjl1** [comment]
OpenBMC device tree review patch:
- https://lists.ozlabs.org/pipermail/openbmc/2019-December/019763.html

**Comment by wrightjl1** [comment]
OpenBMC device driver commits:
- https://github.com/openbmc/linux/commit/279103e59e605646cbd47b4596c93170740abaa1
- https://github.com/openbmc/linux/commit/0cc5496ade7519dfc9b524e2ed7c5e84441144d3

OpenBMC device tree commit:
- https://github.com/openbmc/linux/commit/b7cd960d553f030bda9069811d0ae6143c04a864
