### ISSUE TITLE
Rainier device driver updates for power supplies

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1128]
Update ibm-cffps for 900W/1400W/2300W ps.  All are pmbus and similar cmds supported, but different pn/ccin.

Any paging updates as needed.  Any additional cmds supported as needed.

Change DD to NOT clear faults every poll?

**Comment by bjwyman** [comment]
One complaint I have heard is that the device driver with regards to LED control will start off with 00h in the register, giving LED control to the power supply. If the BMC detects a fault or the LED is manually turned on, the device driver changes that to 02h, if the fault is resolved or the LED is turned off, the device driver changes that to 04h. Basically, the power supply starts out in control of the LED, then loses its ability to control it if the BMC ever takes over to turn on or blink the LED.

**Comment by eddiejames** [comment]
Updated ibm-cffps with support for different power supplies determined by CCIN
Added support for multiple pages
Changed LED control to give control of the LEDs back to PSU FW when BMC wants the LEDs off.

**Comment by derekhoward55** [comment]
Sorry just seeing this update now, thanks for updating it.  I think the above "complaint" is how it should work though.  When BMC firmware writes a X4h, the BMC should remain in control of the led.  If the BMC writes a X0h, then and only then should the ps firmware have control of the led.  Bjwyman am I missing something?  Going forward our ps handling app should always be in control of the led, not the ps fw.

**Comment by bjwyman** [comment]
@derekhoward55 you would need to `@` in front of my ID to get my attention, but I happened to be looking at notifications and saw your profile picture on this one.

That complaint from back on September 5th was from some hardware designers, partly relayed on by some users from ORNL, as I understood it. I noted the complaint, but did not see any update to point out why we should **not** be doing it the way those other users perceived it should work.

**Comment by derekhoward55** [comment]
@bjwyman the hw designers and ORNL users don't know the lightpath or guiding light led strategies our eBMC systems will use.  for instance, the ps led shouldn't even come on solid with guiding light.

Eddie and I discussed this, he is going to change the DD back to set SYS_CONFIG to 04 instead of 00 when an app requests to turn the led off, so the app is always in control of the led.  Not high priority, it can wait to piggyback on some future DD update.  Thanks.

**Comment by bjwyman** [comment]
@derekhoward55 I do recall talking about this in person, but it failed to get noted in this story. Thanks for the update/clarification.

**Comment by bjwyman** [comment]
The not doing CLEAR_FAULTS was mentioned again in #1424.

**Comment by bjwyman** [comment]
https://lore.kernel.org/linux-hwmon/1567192263-15065-1-git-send-email-eajames@linux.ibm.com/
https://lore.kernel.org/linux-hwmon/1567192263-15065-4-git-send-email-eajames@linux.ibm.com/

**Comment by bjwyman** [comment]
https://github.com/openbmc/linux/commit/4b32eaac733430e249c17393e7306b0ee4d3e03a
