### ISSUE TITLE
Rainier device driver updates for MAX31785 rev B

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1129]
MAX31785 revA fan controller DD should be supported already.  

Discussion is ongoing with Maxim to request fixes (revB?) for a couple issues (dual rotor rpm being reported as 0 before reaching target speed, intermittent i2c fails). 

TBD if other enhancements are needed.

**Comment by msbarth** [comment]
I've basically got the needed changes done for the driver to support the revB. Waiting on verification that the revision number for revB wont change from what we had when verifying it.

**Comment by msbarth** [comment]
Hi Nicole,
 
I just heard back from Engineering to confirm 0x3061 is correct for MFC_REVISION register.
 
Thanks,
Taylor Veleke
Principal Account Executive
Mobile: +1 (952) 500-1759
Maxim Integrated | www.maximintegrated.com

**Comment by msbarth** [comment]
Resolved by http://patchwork.ozlabs.org/project/openbmc/patch/20210129175435.2241080-1-msbarth@linux.ibm.com/

**Comment by msbarth** [comment]
Patch sent upstream as well: https://patchwork.kernel.org/project/linux-hwmon/patch/20210201165043.36751-1-msbarth@linux.ibm.com/
