### ISSUE TITLE
Update the openpower vpd parser app with IPZ VPD support

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1133]
The openpower VPD parser application needs to be updated to parse out all records and keywords in an IPZ format VPD. The goal of this story is to make necessary updates to the parser and create a new application called the ipz-vpd-parser while reusing the parsing logic already contained in the openpower VPD parser code (that is create a new executable, but reuse existing code as much as possible).

The story would also include making the IPZ VPD parser a compile time configurable option within the openpower VPD parser application.

**Comment by Alpana07** [comment]
Resolved By - https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/25086

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/25086 merged
