### ISSUE TITLE
Update the openpower vpd parser app with Keyword VPD support

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1134]
Update the Openpower VPD parser with keyword VPD format support. This story involves writing up a new executable that can be compiled in or out at using a config option. The application should (for the scope of this story) parse the keyword format VPD (which is an input parameter pointing to a file/eeprom sysfs path) and store it as a map of keyword names to their values.

**Comment by PriyangaRamasamy** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/25208

**Comment by rfrandse** [comment]
Previous gerrit mentioned that the change was squashed into 
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/27412

**Comment by mzipse** [comment]
@santoshpuranik , just a reminder to confirm whether this is merged or not.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/27412 merged
