### ISSUE TITLE
VPD: Templatize the VPD parser service

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1137]
The systemd service that is invoked to collect VPD for the singular eeprom on openpower systems needs to be templatized such that multiple instances can be invoked for systems such as Rainier.

This story is to investigate the changes necessary to templatize the service.

**Comment by jinuthomas** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/26355
