### ISSUE TITLE
VPD: Update the Inventory with IPZ VPD parsed data.

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1138]
VPD parsed out from EEPROMs containing VPD in IPZ format needs to be published into the inventory. Every record in the VPD becomes an interface and the keywords under that record become properties under that interface.

**Comment by santoshpuranik** [comment]
Implemented here: https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/25086

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/25086 merged
