### ISSUE TITLE
VPD: Update the Inventory with Keyword VPD parsed data

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1139]
Update the inventory with data parsed out of FRUs containing keyword format VPD. There should be one single interface (such as com.ibm.keywordvpd - name TBD) and all keywords in the VPD should be placed under the interface as properties.

**Comment by santoshpuranik** [comment]
Resolved By: https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/27412

**Comment by mzipse** [comment]
@santoshpuranik , just a reminder to confirm whether this is merged or not.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/27412 merged
