### ISSUE TITLE
VPD ECC: Put Up a Dummy ECC implementation in the IPZ VPD parser

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1140]
Place a dummy VPD ECC implementation in the IPZ/OpenPower VPD parsers. The dummy implementation should just be a no-op.

At a later point, we will plug in the actual implementation into this.

**Comment by Alpana07** [comment]
Resolved By: https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/27625

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/27625 merged
