### ISSUE TITLE
GUI : FED : Certificate management replace cert accessibility

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#1143]
## As Is

Unable to tab to "Choose file" button.

![Screen Shot 2019-08-26 at 2.46.36 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/9d095361-fced-415d-a9e0-05ecff40810f)

## To Be

User should be able to table to "choose file button"

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24746 merged
