### ISSUE TITLE
GUI : FED : Local User Management - Roles Description

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1148]
## As Is
The roles description table is hard coded. It does not support any dynamic roles or change if SSH is disabled

## To Be
Support for dynamic roles and show SSH disabled or removed from IPMI group.

**Comment by nicoleconser** [comment]
Need to consider adding helper text to explain what "NoAccess" means. When an Admin creates a new user via IPMI, that user is considered “NoAccess” until the Admin grants them privileges (i.e. Admin, Operator, or ReadOnly). So while NoAccess is a temporary status, it needs to be included so that the Admin can see which users they still need to grant privileges to. 

(discussed 1/17/20 with @gtmills, @ryanarnell, Joe, Russ)

**Comment by nicoleconser** [comment]
@derick-montague @dixsie @yoshiemuranaka The "create new Local User" flow is currently broken.

**Comment by nicoleconser** [comment]
Info from @joseph-reynolds regarding the "NoAccess" privilege: `The NoAccess role is assigned to users created via the IPMI interface. Assign an appropriate role to such users, or disable the user, or delete the user.`

Earlier discussion here: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/23962

**Comment by derick-montague** [comment]
The `NoAccess` privilege isn't listed in the Redfish roles. It's still listed as `Callback` which shows that the user has permissions to login. I am not sure how relevant this story is.

Redfish API: redfish/v1/AccountService/Roles

**Comment by derick-montague** [comment]
Another role and privilege is being suggested also, `ServiceRep`
- Link to maillist posting: https://lists.ozlabs.org/pipermail/openbmc/2020-June/021927.html

**Comment by derick-montague** [comment]
There will be some changes needed for this base on [this slack convo](https://ibm-systems-power.slack.com/archives/CPQF3NJTW/p1594751126085200?thread_ts=1594748880.082900&cid=CPQF3NJTW)

**Comment by derick-montague** [comment]
Concerns pulling from Redfish include:
1. Doesn't contain all the different role descriptions
1. Will not be translated unless Refish API sends translated response

**Comment by derick-montague** [comment]
@gtmills wondering about backend availability and if this is ready to start.

**Comment by gtmills** [comment]
Not ready today. 
https://github.com/ibm-openbmc/dev/issues/612 is SSH access
https://github.com/ibm-openbmc/dev/issues/1830 is work to support CE login
