### ISSUE TITLE
PFP: Parameter override ability

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#115]
<a href="https://github.com/msbarth"><img src="https://avatars2.githubusercontent.com/u/14202667?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [msbarth](https://github.com/msbarth)**
_Monday Jan 09, 2017 at 03:37 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/946_

----

- [ ] Add fan parameter override according to parameter input structure defined
- [ ] Add status msg to journal (or elsewhere) to denote when using override values
- [ ] Lock down ability to override fan parameters?

**Comment by rfrandse** [comment]
<a href="https://github.com/geissonator"><img src="https://avatars2.githubusercontent.com/u/1612261?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geissonator](https://github.com/geissonator)**
_Friday Sep 15, 2017 at 14:11 GMT_

----

Phase 7 since this is internal thermal team type test function.

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
This will need to be broke down further after root design on where the overrides would reside (on dbus, on BMC filesystem, ?).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
This will be resolved after all fan applications support handling the SIGHUP signal along with the use of JSON configuration files.

**Comment by msbarth** [comment]
Last remaining issue to complete enabling this ability is #1363. Closing this issue since there is no work to be done additionally after #1363.
