### ISSUE TITLE
GUI : FED : Customer with 32 character minimum password requirement 

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1150]

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25326

**Comment by derick-montague** [comment]
This is in driver, but it won't be part of OP940. @gtmills - should we close this story and remove it from 940?

**Comment by gtmills** [comment]
Closing since in OP940. For eBMC, we hopefully will handle this better on the backend.
