### ISSUE TITLE
GUI : FED : Add Sort to reusable table component

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1156]
## As Is
The sort functionality has not been created.

## To Be
The table component will have the ability to add sorting to specific columns. Some columns will not be sortable. 

- [ ] Visual indicator of sort options
- [ ] Which icon shows for descending and which shows for ascending
- [ ] User should be able to click on the label as well as the icon to have sort
- [ ] Need to be able determine which column is sorted by default and in which direction (asc, desc)

**Comment by yoshiemuranaka** [comment]
I forgot what we landed on for ascending descending arrow icon direction. Is this right?

<img width="186" alt="Screen Shot 2019-09-05 at 8 44 29 AM" src="https://user-images.githubusercontent.com/8097306/64357400-70360a80-cfb9-11e9-95e2-e706c4d241fc.png">
<img width="176" alt="Screen Shot 2019-09-05 at 8 44 25 AM" src="https://user-images.githubusercontent.com/8097306/64357402-70360a80-cfb9-11e9-8386-f7779bc2df36.png">

**Comment by yoshiemuranaka** [comment]
@ryanarnell @jandraa

**Comment by derick-montague** [comment]
Ascending Up and Descending Down

**Comment by ryanarnell** [comment]
Correct- Ascending Up and Descending Down

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25004
