### ISSUE TITLE
GUI : FED : Add Expand / Collapse to Table Component

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1158]
## As Is
The expand/collapse functionality has not been created.

## To Be
The table component will have the ability to optionally expand additional row content when clicking an expand icon in the table. 

- [ ] Visual indicator for expand/collapse trigger 
- [ ] Visual indicator for showing expanded vs collapsed state
- [ ] User should be able to click on the expand button and see additional row data

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25022
