### ISSUE TITLE
GUI : FED : Certififcate Management - Alert icons implementation and alignment

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1159]
## As Is
1. The alert icons used on the Certificate upload page are using background images rather than the icon directive. 
1. The alert icon in the table is not properly aligned

## To Be
1. The alert icons will be added using the icon directive.
1. The alert icon in the table will be aligned properly

### Icon alignment
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/3dcb8065-2abe-4928-8cdf-d34439f88f80)

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25050

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25050 merged
