### ISSUE TITLE
Combined code update (BMC/PNOR) to help end user

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#116]
<a href="https://github.com/sivassrr"><img src="https://avatars0.githubusercontent.com/u/19144129?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sivassrr](https://github.com/sivassrr)**
_Monday Feb 06, 2017 at 08:34 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/1087_

----

Get the combined code update done. 
As both BMC/PNOR generated by IBM for witherspoon, We can have a combined code update from BMC. This will help end user of Witherspoon.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
Done with https://github.com/ibm-openbmc/dev/issues/532
