### ISSUE TITLE
GUI : FED : Certificate Management - Convert table to use table component

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1160]
## As Is
The layout of the certificate management utilizes a series of `<div>` elements to create a table like structure.

## To Be
The layout of the certificate management should be semantic and should be coded using an accessible `<table>` structure.

**Comment by dixsie** [comment]
Table and ng-repeat is not working correctly when using semantic table elements, but works in `<div>`. Need to explore this issue more.

**Comment by derick-montague** [comment]
This will be handled in the vue rewrite and does not need to be tracked inividually
