### ISSUE TITLE
Build peltool for non-BMC

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1161]
peltool needs to be able to run on x86/ppc64le, not just on the BMC.

**Comment by mine260309** [comment]
I guess it should be able to run on ppc64le as well, is it?

**Comment by spinler** [comment]
Some users we know we need to support:
1. RHEL 7.7 on x86 (eblis)
2. RHEL 7.9 using Fedora 35 containers on ppc64le (ISDW - call home databases)
3. RHEL 7.9 on ppc64le (STELA)
4. RHEL 7.9 on x86 ECUREP  (decode PELs from BMC dumps coming back from the field) 
5. Some developer pools systems are ubuntu?

To run peltool along with all of its parsers we need:
1. peltool itself, built from C++
2. message_registry.json from the phosphor-logging repo (on the bmc it goes into /usr/share/phosphor-logging/extensions/pels/
3. The python SRC and UserData parsers

The python modules on the BMC today look like:
```
root@p10bmc:/usr/lib/python3.9/site-packages# ls srcparsers/
__init__.py  __pycache__  be500        bsrc         oe500        osrc
root@p10bmc:/usr/lib/python3.9/site-packages# ls udparsers/
__init__.py  b0100        b0500        b0900        b0c00        b1a00        b1e00        b3600        be500        o3500
__pycache__  b0300        b0700        b0a00        b0e00        b1d00        b2600        b4500        helpers      oe500
```
Those parsers get installed from various recipes in openbmc/openbmc

Currently peltool is built during the normal build, and pulls in a lot of code that isn't strictly necessary, which brings in dependencies on sdbusplus, systemd,  phosphor-dbus-interfaces, etc.  All it needs to support on other platforms though is reading a PEL file,  that should bring down its dependencies to nlohmann-json and libformat, and libpython for the C APIs to call the modules.  I think tha would have to be at least python3.6

What I would like to do is restructure the code (a lot of work) or put in compile flags (messy, but less work) to get it down to just get those two dependencies.

Since the PEL code is riding along in the phosphor-logging project which a lot of people use who don't use PELs, I'd like to avoid making any changes to any higher level meson.build files, so possibly we can make a new meson.build file in a new directly we can use to build the standalone peltool.

I talked to the ISDW team, and they said ideally they'd like to get RPMs they can use to install into their contains.  So that would be a peltool RPM with peltool/message_registry.json, plus somehow RPMs for the python modules, however that works.  nlohmann JSON is header only so nothing installed on users system there, but there is a lib for libformat.  Not sure if that's another RPM or just statically linked in.  Can it just be a meson subproject and statically linked in maybe?

I think the first step is to make a new meson.build file, maybe in a extensions/openpower-pels/pel_standalone directory, that can be used to build a standalone peltool.  After that, we can worry about dockerfiles for building the RPMs

**Comment by spinler** [comment]
I put up the commit https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/51492 to add a wrapper so we can trace in that code without using phosphor-logging.  Eventually it can just use std::cerr in the standalone case and the normal log<>() otherwise.

**Comment by spinler** [comment]
An example of some hostboot python plugins is https://github.com/open-power/hostboot/blob/master-p10/setup.py

**Comment by spinler** [comment]
Based on the survey of our users, the first thing we need to be able to do is get 'peltool --file = <raw pel file>' working on RHEL 7.9.

On Fedora 35, can just do the normal meson build, though that pulls more than necessary into peltool, but it doesn't work on RHEL.

With the follow PEL data, (base64 encoded here so it can be shown):
EgAMAEANQAgIgMIGEAnGSAiAwgYQCcpTwAACgAAEZwAAAAAAAAAAFAAX9hQAF/YVUgAGAEAIAAS
A0AAAAAAAAAAqAAAAAMCUFMAUAEBNQACAAAJAAAASAAIAFUuLQAQAAAAAAAAAAAAAKQEAAAAAAAA
AAAAAAAAQkQxMjM1MDAgICAgICAgICAgICAgICAgICAgICAgICBFSABgAQAgADkxMDUtMjJBMTM5
RjBCMAAAAAAATkwxMDIwXzAyMgAAAAAAAGZ3MTAyMC4wMC00My4xAAAAAAAAAAAAAAAAAAAAAAAU
QkQxMjM1MDBfMkUyRDAwMTAAAABNVAAcAQAgADkxMDUtMjJBMTM5RjBCMAAAAAAAVUQA8AEBIAB7
IkJNQ1N0YXRlIjoiUmVhZHkiLCJCb290U3RhdGUiOiJTeXN0ZW1Jbml0Q29tcGxldGUiLCJDaGFz
c2lzU3RhdGUiOiJPbiIsIkZXIFZlcnNpb24gSUQiOiJmdzEwMjAuMDAtNDMuMS0xMDIwLjIyMDgu
MjAyMjAyMjVhIChOTDEwMjBfMDIyKSIsIkhvc3RTdGF0ZSI6IlJ1bm5pbmciLCJQcm9jZXNzIE5h
bWUiOiIvdXNyL2Jpbi9vcGVucG93ZXItb2NjLWNvbnRyb2wiLCJTeXN0ZW0gSU0iOiI1MDAwMTAw
MSJ9VUQAVAEBIAB7IlNCRV9FUlJfTVNHIjoiU0JFIGNvbW1hbmQgcmVwb3J0ZWQgZXJyb3IiLCJT
UkM2IjoiNDE5ODgiLCJfUElEIjoiMjEwOSJ9AAAAVUQALAHLNQD/3AAJAACkBADdsoEAAAAEAAAA
AAAG0DUAAAABAAAAAAAAAARVRAAMAQEgAFtdAABVRACsAQMgAEhXUF9SQyA9IFJDX1NCRV9QSUJf
QUREUkVTU19FUlJPUgpIV1BfUkNfREVTQyA9IFNCRSBTQ09NIGZhaWx1cmUgLSBTQ09NIGFkZHJl
c3MgZmFpbHVyZQpIV1BfRkZEQ19GYWlsZWQgU0NPTSBhZGRyZXNzID0gMTkxNzc3NTkyODg4NTI0
OApIV1BfRkZEQ19QSUIgUkMgPSA2NzEzMzI4NgoA

it would give:
```
$ ./peltool --file ~/2022030818402729_50005FD8
{
"Private Header": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Created by":               "0x3500",
    "Created at":               "03/08/2022 18:40:27",
    "Committed at":             "03/08/2022 18:40:27",
    "Creator Subsystem":        "BMC",
    "CSSVER":                   "",
    "Platform Log Id":          "0x50005FD8",
    "Entry Id":                 "0x50005FD8",
    "BMC Event Log Id":         "4508"
},
"User Header": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Log Committed by":         "0x2000",
    "Subsystem":                "Processor Chip Cache",
    "Event Scope":              "Entire Platform",
    "Event Severity":           "Unrecoverable Error",
    "Event Type":               "Not Applicable",
    "Action Flags": [
                                "Service Action Required",
                                "Report Externally",
                                "HMC Call Home"
    ],
    "Host Transmission":        "Sent",
    "HMC Transmission":         "Acked"
},
"Primary SRC": {
    "Section Version":          "1",
    "Sub-section type":         "1",
    "Created by":               "0x3500",
    "SRC Version":              "0x02",
    "SRC Format":               "0x55",
    "Virtual Progress SRC":     "False",
    "I5/OS Service Event Bit":  "False",
    "Hypervisor Dump Initiated":"False",
    "Power Control Net Fault":  "False",
    "Backplane CCIN":           "2E2D",
    "Terminate FW Error":       "False",
    "Deconfigured":             "False",
    "Guarded":                  "False",
    "Valid Word Count":         "0x09",
    "Reference Code":           "BD123500",
    "Hex Word 2":               "00080055",
    "Hex Word 3":               "2E2D0010",
    "Hex Word 4":               "00000000",
    "Hex Word 5":               "00000000",
    "Hex Word 6":               "0000A404",
    "Hex Word 7":               "00000000",
    "Hex Word 8":               "00000000",
    "Hex Word 9":               "00000000"
},
"Extended User Header": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Created by":               "0x2000",
    "Reporting Machine Type":   "9105-22A",
    "Reporting Serial Number":  "139F0B0",
    "FW Released Ver":          "NL1020_022",
    "FW SubSys Version":        "fw1020.00-43.1",
    "Common Ref Time":          "00/00/0000 00:00:00",
    "Symptom Id Len":           "20",
    "Symptom Id":               "BD123500_2E2D0010"
},
"Failing MTMS": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Created by":               "0x2000",
    "Machine Type Model":       "9105-22A",
    "Serial Number":            "139F0B0"
},
"User Data 0": {
    "Section Version": "1",
    "Sub-section type": "1",
    "Created by": "0x2000",
    "BMCState": "Ready",
    "BootState": "SystemInitComplete",
    "ChassisState": "On",
    "FW Version ID": "fw1020.00-43.1-1020.2208.20220225a (NL1020_022)",
    "HostState": "Running",
    "Process Name": "/usr/bin/openpower-occ-control",
    "System IM": "50001001"
},
"User Data 1": {
    "Section Version": "1",
    "Sub-section type": "1",
    "Created by": "0x2000",
    "SBE_ERR_MSG": "SBE command reported error",
    "SRC6": "41988",
    "_PID": "2109"
},
"User Data 2": {
    "Section Version":          "1",
    "Sub-section type":         "203",
    "Created by":               "0x3500",
    "Data": [
        "FF DC 00 09 00 00 A4 04  00 DD B2 81 00 00 00 04  |  ................",
        "00 00 00 00 00 06 D0 35  00 00 00 01 00 00 00 00  |  .......5........",
        "00 00 00 04                                       |  ...."
    ]
},
"User Data 3": {
    "Section Version": "1",
    "Sub-section type": "1",
    "Created by": "0x2000",
    "Data": []
},
"User Data 4": {
    "Section Version": "1",
    "Sub-section type": "3",
    "Created by": "0x2000",
    "Data": [
        "HWP_RC = RC_SBE_PIB_ADDRESS_ERROR",
        "HWP_RC_DESC = SBE SCOM failure - SCOM address failure",
        "HWP_FFDC_Failed SCOM address = 1917775928885248",
        "HWP_FFDC_PIB RC = 67133286",
        "."
    ]
}
}
```

**Comment by spinler** [comment]
I put up a chain of commits starting at https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/51970/ to remove all the dbus and dependencies to the code that builds into peltool so that it can compile on RHEL:

```
$ ldd build/peltool
	linux-vdso.so.1 =>  (0x00007ffff7ffa000)
	libpython3.6m.so.rh-python36-1.0 => /opt/rh/rh-python36/root/usr/lib64/libpython3.6m.so.rh-python36-1.0 (0x00007ffff78cd000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ffff75c5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ffff72c3000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ffff70ad000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ffff6cdf000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffff6ac3000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ffff68bf000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007ffff66bc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffff7ddb000)
```

**Comment by spinler** [comment]
We decided to just rewrite peltool in python to avoid the headache of having to build it separately for all of the platforms.  I'm going to close this issue  and open a new one for that so we can start clean.
