### ISSUE TITLE
GUI : FED : SNMP Page layout consistency

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#1164]
## As Is
![Screen Shot 2019-09-05 at 1.09.42 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/bc6f15cc-4c4f-4ca1-8408-f93a9d533268)

## To Be
- [ ] Add page, section, and form-action styling
- [ ] Correct accessibility

![Screen Shot 2019-09-06 at 10.51.10 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/6b73d8f6-69eb-4896-9897-6612e60a7029)

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25039

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25039 merged
