### ISSUE TITLE
GUI : FED : Clean up icons 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1169]
We have 2 warning icons, 
https://github.com/openbmc/phosphor-webui/blob/master/app/assets/images/icon-warning.svg
https://github.com/openbmc/phosphor-webui/blob/master/app/assets/icons/icon-warning.svg
Other duplicate or unused icons, we can clean up ?

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25421
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25420/3
Were these commits part of this issue? Does any other work need to be done?

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25513
