### ISSUE TITLE
GUI : FED :  Certificate Management- page layout consistency

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#1173]
## As Is
Certificate management page is not using consistent page layout.

## To Be
- Add page and section styles
- Remove unnecessary styles
- Migrate modals to their own files to reduce the size of the certificate management view

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25284

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25284 merged
