### ISSUE TITLE
Backend: Server Model and SerialNumber have ellipses

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1174]
Can we get rid of these ellipses?
![image](https://user-images.githubusercontent.com/5455127/64802016-5b282100-d54f-11e9-927d-91b382c4dc96.png)

**Comment by dixsie** [comment]
@gtmills This is how we are getting it from the backend 

<img width="286" alt="Screen Shot 2019-09-26 at 2 42 50 PM" src="https://user-images.githubusercontent.com/26472611/65719789-29917880-e06c-11e9-80a3-fb0dc6642a9e.png">

**Comment by gtmills** [comment]
Moving to a backend issue. @dixsie Thank you for looking.

**Comment by gtmills** [comment]
Similar to https://github.com/ibm-openbmc/dev/issues/448

**Comment by derick-montague** [comment]
@gtmills this is in sprint +1...This is a backend story, correct?

**Comment by gtmills** [comment]
Yeah looks to be.

**Comment by gtmills** [comment]
Still see these on the vue rewrite.

**Comment by gtmills** [comment]
@santoshpuranik Could someone on your squad look at this?

**Comment by gtmills** [comment]
@sandeepasingh116 @kennyfully88 I assume you haven't see this with eBMC? 
I am going to close, please reopen if still a problem.
