### ISSUE TITLE
Romulus: Remove cooling type application

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1178]
Romulus has no need for the cooling type application and this should be removed along with updating the necessary configuration yaml files to no longer rely on the associated air/water cooled properties in inventory.

If this is unable to be done due to issues with the other fan applications being dependent on a cooling type being defined, additional issues should be opened as this should be an optional application and property config.

**Comment by msbarth** [comment]
@mine260309 Could you look into this? Unfortunately Romulus being the reference platform for P9 openpower systems, having a cooling type defined should not be required if the machine has a single cooling mechanism (i.e. air).

**Comment by mine260309** [comment]
@msbarth Sure I could look into this.

But before doing that, one question:
What the Romulus cooling type application does is to "hard-code" the `AirCooled` to true and `WaterCooled` to false, this is somehow expected and does not confuse others.
So why do you think it should remove the cooling type applications?

Btw, I did some check in the code, and it looks like the `zone_conditions` is optional, so probably we could just remove the cooling type check.

**Comment by mine260309** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/25261

**Comment by msbarth** [comment]
@mine260309 Thanks for getting this updated. Now between Romulus and Witherspoon being reference openbmc machines, it will show that the cooling type application isnt really necessary.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/25261

**Comment by mine260309** [comment]
> @mine260309 Thanks for getting this updated. Now between Romulus and Witherspoon being reference openbmc machines, it will show that the cooling type application isnt really necessary.

It's a good attempt and good to know that the cooling type app is optional.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/25261 merged
