### ISSUE TITLE
PEL Parser support for printing detailed SRC descriptions

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1179]
The PEL parser needs to somehow get descriptions for SRCs to print.  This is different than the UserData parsers.

One idea is to just have these be in JSON that the tool can look up based on the SRC type:

BD_SRC.json:
```
[
   {
      "<reason code>":
      {
         "message": "some SRC message"
         "word 6":  "what word 6 means"
         "word 7":  "what word 7 means"
         "word 8":  "what word 8 means"
         "word 9":  "what word 9 means"
  } 
]
```

For BMC errors, we can pull them out of the message registry.  hostboot and others can have recipes to install them onto the BMC.  Unsure yet about x86 parsing, we can probably have them install into a data dir.

**Comment by spinler** [comment]
We'll handle printing the message registry descriptions just using the message registry file.  This issue will be for printing SRC descriptions for BMC checkstop analysis (needs data from hostboot), and hostboot itself.

**Comment by spinler** [comment]
We're going to use python modules for this like we're using for the UserData parsers.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/34373

**Comment by harisuddin82** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35777

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35777 merged
