### ISSUE TITLE
GUI: FED: Date Time fails from NTP to Manual

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1181]
## Expected Behavior
A user should be able to change the time from NTP to manual and then update the date and time setting. 

## Actual Behavior
The user changes from NTP to Manual and then updates the date and time. The backend returns a 401 unauthorized on the `first attempt` to make the change. This is caused by the date and time being changed before the setting change from NTP to Manual has been completed.

## Steps to Reproduce the Problem

  1. Go to date and time page
  1. Change the value from NTP to Manual
  1. Change the date and/or time
  1. Click Submit

## Specifications
  - Browser: All

## Internal Tracking
SW472445

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25611

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25611 merged
