### ISSUE TITLE
GUI: FED: Serial Over Lan and KVM fail to reload using refresh button in header

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1182]
## Expected Behavior
When the refresh button is pressed in the header the SOL and KVM consoles will reload.

## Actual Behavior
When the refresh button is pressed in the header the SOL and KVM consoles are removed from the page and not reloaded/initialized.

## Steps to Reproduce the Problem

  1. Go to SoL page
  1. Click `Refresh` button in page header
  

## Specifications
  - Browser: All

## Internal Tracking Number
SW475438

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25460

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25460 merged
