### ISSUE TITLE
PFP: Thermal mode setting at standby

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1183]
Determine if `phosphor-settingsd` is able to be configured to host the thermal mode interface for that currently resides on `phosphor-fan-presence/control`. If able to be configured on `phosphor-settingsd` then the thermal mode should be accessible at BMC standby, otherwise, `phosphor-fan-presence/control` will need an update to present this interface at BMC standby (which means something within fan control will need to run at standby which is TBD).

**Comment by msbarth** [comment]
`phosphor-settingsd` has no ability to load a specified set of settings based on the state of a property which is what's needed to load the appropriately supported thermal modes for fan control (air vs water cooled have different lists of supported modes to be loaded at runtime).

Working on altering `phosphor-fan-presence/control` services and fan control's configuration to have fan control loaded at standby and trigger an event that sets the fans to full speed upon poweron. During the power off path, the witherspoon system will not set fan speeds after the OCC's go inactive, however it may be possible to configure an additional event that would remove all stored events when powered off (and then enhance the poweron event to load those events in addition to setting the fans to full speed).

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/25415

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/25415 merged
