### ISSUE TITLE
GUI : FED : Add batch actions to local user management table

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#1184]
## As Is
this is new functionality

## To Be

Add batch action options to the local user table.

- [ ] User should be able to select a single or multiple rows and perform a batch operation
- [ ] Enable, disable, remove actions should be available after making a selection
- [ ] root user cannot be selected

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25289

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25289 merged
