### ISSUE TITLE
GUI : FED :  Remove Purpose from inventory item 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1185]
![image](https://user-images.githubusercontent.com/5455127/64994484-60160900-d89e-11e9-8ec9-388f9072a716.png)

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25395

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25395 merged
