### ISSUE TITLE
GUI : FED : Event Log - Date pickers not working in Safari

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1187]
## Overview
This implementation uses the native date input type. Chrome and other browsers support this and build the date picker natively. Safari will not have a date picker until they support the date type input element.

The problem is the date format. The date picker changes the format for supported browsers to mm/dd/yyyy. The format is converted to  yyyy-mm-dd by the browser, but the user never sees that in supported browsers. 

###  Internal Tracking Number
SW472518

## As Is
The only label used to indicate to the expected format to the user used the placeholder attribute. This is not accessible and provides a challenging user experience since the placeholder text is removed as the user begins typing. Also, the only invalid format indicator is a red bottom border

## To Be
The current design does not account for a visually displayed label or helper text. At minimum we will need to: 

- [ ] Add error messaging letting the user know the date format is not valid and the expected format.

The best solution would be to provide:
 - [ ] Visual labels for `Start Date` and `End Date`
- [ ] Helper text to describe the expected format other than just using the placeholder

## Browsers Affected
- IE 11
- Safari

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25335

**Comment by derick-montague** [comment]
Testing:
Safari and IE will not have date pickers and will have a date format pattern set to yyyy/mm/dd. All other browsers should have a date picker (they are all slightly different) and the date format pattern is mm/dd/yyyy.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25335 merged
