### ISSUE TITLE
GUI : FED : Update front-end framework

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1188]
## As Is
The framework being used is AngularJS, which sunsets on June 30, 2021.

https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c

## To Be
Replace AngularJS framework with a community agreed upon framework.

## Resources
- https://vuejs.org/v2/guide/comparison.html

**Comment by derick-montague** [comment]
## Some info form the Vue framework comparison guide:

### Angular JS
https://vuejs.org/v2/guide/comparison.html#AngularJS-Angular-1
> Some of Vue’s syntax will look very similar to AngularJS (e.g. v-if vs ng-if). This is because there were a lot of things that AngularJS got right and these were an inspiration for Vue very early in its development. There are also many pains that come with AngularJS however, where Vue has attempted to offer a significant improvement.

### Angular
https://vuejs.org/v2/guide/comparison.html#Angular-Formerly-known-as-Angular-2
> Recent versions of Angular, with AOT compilation and tree-shaking, have been able to get its size down considerably. However, a full-featured Vue 2 project with Vuex + Vue Router included (~30KB gzipped) is still significantly lighter than an out-of-the-box, AOT-compiled application generated by angular-cli (~65KB gzipped).

### React
https://vuejs.org/v2/guide/comparison.html#React
> In React, everything is just JavaScript. Not only are HTML structures expressed via JSX, the recent trends also tend to put CSS management inside JavaScript as well. This approach has its own benefits, but also comes with various trade-offs that may not seem worthwhile for every developer. Vue embraces classic web technologies and builds on top of them.

**Comment by derick-montague** [comment]
@gtmills - Maybe we should crate a gerrit review to capture some of this conversation with the community after our meeting next week?

**Comment by gtmills** [comment]
@derick-montague Why a gerrit review? Why not just reply to Ed's note on the list?

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Community determined to use Vue.js. Issues are being tracked in #1555
