### ISSUE TITLE
Implement LID read on BMC

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1189]
The hypervisor (PHYP) and OS would read it's image sections (LIDs) stored on the BMC via PLDM commands. This epic tracks stories for LID reads. The LID read flow :

A component (could be PHYP, or an OS, or another firmware component) requests a LID read using a specific LID number. PHYP translates that into a PLDM ReadFileByTypeIntoMemory call that will pass:
1) File type (whatever value means "LID")
2) File number - for LIDs this is the LID ID. You should be able to find the file using this number. eg, if 0x80a02023 is passed then the file name is 80a02023.lid
3) Length to read. PHYP will make sure this is a multiple of 16 bytes.
4) Offset to start reading.
5) Address to use on the PCI bus to put the results - this is the same as for the NVRAM. (edited)

Then, for the last 0-15 bytes, we will issue an in-band ReadFileByType command with parameters 1-4 to get those last few bytes, and we're expecting those bytes to come back in the PLDM response.

**Comment by mzipse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
