### ISSUE TITLE
Implement encode/decode APIs for ReadFileByType

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1192]
Implement Requester and Responder encode/decode. See https://github.com/ibm-openbmc/dev/issues/1189.

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/25686

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/25686 merged
