### ISSUE TITLE
Analysis on HTTP-HTTPS redirect

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1199]
This issue is to analyze the work impact on bmcweb.
1/ Do we need two bmcweb processes to listen on port 80 and port 443 or it should be a single instance?
2/ If we are going with a single process which listens on both ports(80 and 443), how are we planning to differentiate the request(80 vs 443)
3/ Do we need to redirect all the URL or selected URL(security impact)
4) If selected URL then how it is useful to the customer?

**Comment by gtmills** [comment]
@ratagupt Can we close? and the work will be tracked by https://github.com/ibm-openbmc/dev/issues/895

**Comment by ratagupt** [comment]
Yes makes sense, I am closing this one.
