### ISSUE TITLE
Implement certificate upload

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#12]
For customers to implement their own TLS certificates, there are two possible options :
- A simple certificate + private key upload
- Asking the BMC to create a Certificate Signing Request (CSR) and corresponding private key. The customer then gets the CSR signed and uploads to BMC. Private key never leaves BMC. This is deemed more secure.

This epic covers both approaches, because the CSR work is a super-set of the plain upload.

A potential list of stories and person-day sizing :

1) Design API to request CSR generation (cater different certificate types?). 3PD.
2) Implementation the CSR generation API. 10PD.
3) Design Download CSR API (cater different certificate types?). 2PD.
4) Implement Download CSR API. 2PD.
5) Design APIs to upload certificate and optionally private key (cater different certificate types?). 3PD.
6) Design APIs to activate certificate (specify certificate target service?). 3PD.
7) Implement API to upload certificate (cater different certificate types?). 2PD.
8) Implement validation of uploaded certificate. 5 PD.
9) Implement activation of web server certificate. 3 PD.
10) Implement activation of LDAP certificate. 3 PD.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
