### ISSUE TITLE
Refactoring the code which writes to the systemd-networkd config file.

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#120]
<a href="https://github.com/ratagupt"><img src="https://avatars1.githubusercontent.com/u/15628264?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ratagupt](https://github.com/ratagupt)**
_Thursday Jun 08, 2017 at 02:49 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/1751_

----

Currently we have two places where we modify the config file 1) during network factory reset(networkConfig.cpp)
2) and other operation (network_manager.cpp)
The plan is to merge it so systemd-networkd config file should be modified from a single place.

**Comment by rfrandse** [comment]
<a href="https://github.com/ratagupt"><img src="https://avatars1.githubusercontent.com/u/15628264?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ratagupt](https://github.com/ratagupt)**
_Wednesday Jun 21, 2017 at 10:39 GMT_

----

Currently we have written our own INI parser,We need to take a look can we use the one which is already there in yocto?
https://github.com/benhoyt/inih/blob/master/ini.c

**Comment by rfrandse** [comment]
<a href="https://github.com/ratagupt"><img src="https://avatars1.githubusercontent.com/u/15628264?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ratagupt](https://github.com/ratagupt)**
_Wednesday Aug 23, 2017 at 13:11 GMT_

----

# **STATUS**
08/23
Didn't get a chance to work on this due to other priority work.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by sunharis** [comment]
Upstream already has refactored a lot of code around this area. This story is not needed
