### ISSUE TITLE
GUI : FED : Should not reboot the BMC if the image failed

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1201]
If the firmware image "failed" we should display a toast and not reboot the bmc 
https://github.com/openbmc/phosphor-webui/blob/master/app/configuration/controllers/firmware-controller.js#L64

https://github.com/openbmc/phosphor-webui/blob/master/app/configuration/controllers/firmware-controller.js#L101

**Comment by gtmills** [comment]
To test, on a Witherspoon, turn field mode on, upload and try to activate a master build image.

to turn field mode on/off

https://github.com/openbmc/docs/blob/900e4ddbed1dd5b2adbae73b9af4c3e59456dbed/code-update/code-update.md#software-field-mode

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25839

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25839 merged
