### ISSUE TITLE
Script to check sensor count of a system

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1203]
Create a script(python?) that can be called providing the location of the sensor and inventory FFDC dump output. Use these dump outputs along with a configurable system input parameter to determine that the proper sensors exist for a given machine.

**Comment by msbarth** [comment]
The intent is to provide a mechanism that will provide an input file with a list of sensors for a machine that will be compared to the sensor FFDC dump output to verify that all expected sensors for that machine exist. The use of the providing the inventory FFDC dump output is optional where the machine's input file would define a set of value(s) to differentiate the expected sensors based on those value(s). ex.) The cooling type property in inventory for a Witherspoon machine changes the number of expected fan sensors since fan1 is not required.

**Comment by msbarth** [comment]
Script is complete and reviewed with member of DVT on use. Decision is to migrate the script's functionality into their DVT structure to enhance a current application that closely mimics what this script does.

Still intend to push this script up to `openbmc-tools` repo once finished testing as it may be applicable/useful elsewhere.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/26978

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/26978 merged
