### ISSUE TITLE
openbmctool: Handle PasswordChangeRequired

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1204]
See https://github.com/openbmc/openbmc-tools/issues/53

**Comment by joseph-reynolds** [comment]
This is related to #1026

**Comment by joseph-reynolds** [comment]
Code review in https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/26123

**Comment by mzipse** [comment]
@joseph-reynolds , I think we can close this; commit is merged.  If you disagree, please reopen and let me know why.  Thanks.
