### ISSUE TITLE
Factory reset should expire the root password

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#1205]
This work is for #947 and is related to #1047 for BMC function to ensure the root password is expired on the systems coming off the manufacturing line.

Background: There are two approaches:
1. Create the firmware image to have an expired password.  For example, run the `chroot passwd --expire root` command on the firmware image before packaging it.
2. Have the factory (assembly line) expire the password as one of the last manufacturing steps before shipping the system to the user.  For example, it can use the factory reset function.

The difference is option 2 allows a BMC that does not have an expired password, and the password only becomes expired after factory reset.

This story is to help implement approach 2 above.  That is, when the system is factory reset, it erases all user information, which returns the system to the default root password.  That password is *not* expired in the firmware image.  Instead, the BMC will change the password to expired the first time it boots up after a factory reset, like the systemd https://www.freedesktop.org/software/systemd/man/systemd-firstboot.html service.

The requirement is that the root password be changed to expired after factory reset.

**Comment by geissonator** [comment]
Found that ConditionFirstBoot will not work for us due to https://github.com/systemd/systemd/issues/8268. But an easy solution is to just follow what first-boot-set-hostname.service does and just disable the service once it has run. This ensures it does not run again until the system is factory reset.

**Comment by geissonator** [comment]
Code up at https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/25615

**Comment by geissonator** [comment]
@joseph-reynolds since this was a downstream-only solution, do we keep this open to track a long term solution or is that tracked elsewhere?

**Comment by geissonator** [comment]
@joseph-reynolds going to assume this is tracked elsewhere for a long term solution.
