### ISSUE TITLE
NVme support through i2c mux

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1206]
Todd asked that we get something open to track this. 

The base NVme design is here: https://github.com/openbmc/docs/blob/master/designs/nvmemi_over_SMbus.md

The initial code is here: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-nvme/+/22551

We need to ensure this design will support NVme devices that are behind i2c muxes.

**Comment by mzipse** [comment]
@amboar  and @strange671 , is this the same story as issue #1670?

**Comment by strange671** [comment]
yes, I think it's the same because these nvme modules also need raw smbus. and with #1670 adds initial code in dbus-sensors apps. here's gerrit code with work in process and fixing with bunch of comments : https://gerrit.openbmc-project.xyz/#/c/openbmc/dbus-sensors/+/37391/

**Comment by mzipse** [comment]
I think we have this covered.  Closing.
