### ISSUE TITLE
Upstream thermal support for additionally supported pci cards

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1207]
A different fan curve will be used to support an additional pci cards that also require new thermal modes to be supported/selected when these cards are installed.

Thermal curve numbers and mode name to be provided by thermal team.

**Comment by msbarth** [comment]
To support 2 additional pci cards, 2 new thermal modes will be created for both air & water cooled witherspoon support along with back-porting the current air thermal mode ("CUSTOM") to be supported on water cooled witherspoons.

**Comment by msbarth** [comment]
This issue will be used to get the OP940 changes upstreamed to support the additional thermal modes on witherspoon.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/25952

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/25952 merged
