### ISSUE TITLE
GUI: FED: Add translation service

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1208]
## Requirements
- [ ] Determine the appropriate i18n service to use

**Comment by derick-montague** [comment]
Duplicate

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/28965

**Comment by derick-montague** [comment]
Duplicate of work being done in Vue rewrite.
