### ISSUE TITLE
Download manager: Support for system image type (BMC + PNOR)

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#121]
<a href="https://github.com/anoo1"><img src="https://avatars0.githubusercontent.com/u/9052527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anoo1](https://github.com/anoo1)**
_Thursday Jun 08, 2017 at 20:28 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/1757_

----

The download manager needs to support an image type of purpose "System" which will contain a BMC and a PNOR tarball image. Then need to extract each of those images in their corresponding directory.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
We can close this.  Work will be tracked under #1334
