### ISSUE TITLE
GUI : FED : Server Health - Hardware status

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1212]
## Overview
Recreate the page in Vue.js based on current layout in AngularJS.

## cURL
```
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis
```
```
System:  /redfish/v1/Systems/system
Motherboard:  /redfish/v1/Chassis/motherboard
Processor and GPU: /redfish/v1/Systems/system/Processors
Memory: /redfish/v1/Systems/system/Memory
Fans: /redfish/v1/Chassis/chassis/Thermal
Power Supplies: /redfish/v1/Chassis/chassis/Power
BMC: /redfish/v1/Managers/bmc
```

## Screenshots
<img width="971" alt="Screen Shot 2020-06-02 at 8 48 31 AM" src="https://user-images.githubusercontent.com/8097306/83549976-f89afa80-a4ba-11ea-852a-d8ce46e750eb.png">

Expanded row:
![Screen Shot 2020-06-03 at 10 48 06 AM](https://user-images.githubusercontent.com/8097306/83670265-c1464f80-a587-11ea-8368-3f2f2380292e.png)

**Comment by yoshiemuranaka** [comment]
System table unknown properties: 
- [ ] CCIN
- [ ] FRU number
- [ ] Location code

**Comment by yoshiemuranaka** [comment]
System table

**Comment by yoshiemuranaka** [comment]
Follow up stories to add missing table properties:
- #2308 
- #2309 
- #2310 
- #2311 
- #2312
- #2313
