### ISSUE TITLE
GUI : FED : Server Control - Server power operations page

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1215]
## Overview
Create the existing Server Power Operations page using Vue.js. This does not include eBMC Power Server Operations changes.

## Tasks
- [ ] Determine if we can use the Redfish API - See #1077 
- [ ] Include translation in development

## Concerns
- ### Concerns
- `Last power operations` is not part of the Redfish API. Unclear the importance to users.
![image](https://user-images.githubusercontent.com/1183515/74477576-278c5280-4e71-11ea-9682-2b13648a3a87.png)

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29793/1
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29794/3
Resoved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29851
