### ISSUE TITLE
GUI : FED : Server Control - Manage power usage

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1216]
## Overview
Recreate page using Vue.js

## Tasks
- [x] Determine if Redfish API can be used
- [x] Verify design with design team (look at the save/cancel form pattern)
- [x] Include translation

## Current UI
![image](https://user-images.githubusercontent.com/1183515/77670277-fa44c100-6f53-11ea-849f-15750535ccf3.png)

**Comment by derick-montague** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/30822

**Comment by derick-montague** [comment]
@yoshiemuranaka @Srisuk @gtmills is what we would expect on first load?

![image](https://user-images.githubusercontent.com/1183515/82130116-f08a4d80-978d-11ea-8163-58cb0c7f90a9.png)

**Comment by gtmills** [comment]
Looks reasonable to me. One day (hopefully) we can get a min and max power cap out on the API
