### ISSUE TITLE
PFP: Create a dbus object to enable/disable automatic fan control

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#122]
<a href="https://github.com/msbarth"><img src="https://avatars2.githubusercontent.com/u/14202667?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [msbarth](https://github.com/msbarth)**
_Friday Jul 07, 2017 at 18:21 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/1922_

----

Each fan control zone should create a dbus object that can be used to enable/disable automatic fan control. The ability to set a zone as active/inactive already exists, so this issue needs to address exposing the dbus object that a user could then enable or disable automatic fan control on a per zone basis.

Interface design discussion reference --> https://gerrit.openbmc-project.xyz/#/c/4897/

**Comment by rfrandse** [comment]
<a href="https://github.com/msbarth"><img src="https://avatars2.githubusercontent.com/u/14202667?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [msbarth](https://github.com/msbarth)**
_Friday Aug 11, 2017 at 15:14 GMT_

----

- [ ] Determine if https://gerrit.openbmc-project.xyz/#/c/4897/ interface will be used
- [ ] Create enable/disable fan control (from per zone) property & interface yaml
- [ ] Update zone code to serve enable/disable property
- [ ] Subscribe zone to property change signal of enable/disable property
- [ ] When enabled, automatic fan control function is active on the zone
       Update internal target speed value from current target and continue auto control
- [ ] When disabled, automatic fan control function is non-active on the zone
       Leave target speed at last set value (or go to full speed?)

**Comment by rfrandse** [comment]
<a href="https://github.com/amboar"><img src="https://avatars0.githubusercontent.com/u/526481?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amboar](https://github.com/amboar)**
_Sunday Aug 13, 2017 at 23:46 GMT_

----

Out of curiosity, did anyone ever look at the kernel's of_thermal capability and the thermal devicetree bindings?

**Comment by rfrandse** [comment]
<a href="https://github.com/msbarth"><img src="https://avatars2.githubusercontent.com/u/14202667?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [msbarth](https://github.com/msbarth)**
_Wednesday Aug 16, 2017 at 18:44 GMT_

----

@amboar I have not looked into that, however I'm not sure how it would help in what this issue is going to address. The fan control application in userspace requires a way to enable/disable its control over the fan speeds automatically (for mfg, thermal characterization, etc..). This issue will bind a dbus property that a user could set to enable/disable the running of the automatic fan control application so fan speeds could be set manually.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Simply stopping the fan control service from the BMC suffices when manual control of the fan speeds is necessary.
```
systemctl stop phosphor-fan-control@0.service
```

A design direction is to provide a `fanctl` tool that will handle the service state when wanting to manually control fan speeds or return to automatic fan control. #1870
