### ISSUE TITLE
GUI : FED : Server Configuration - Date and time settings

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1225]
## Overview
Add ability to modify date and time settings. 

## Interaction requirements
- [x] User can view current BMC date and time
- [ ] User can choose between a **Manual** or **NTP** settings
- [ ] If **Manual** radio selected the date picker and time picker become interactive and **NPT** input fields become disabled
- [ ] If **NTP** radio selected the primary and secondary input fields become interactive and **Manual** date/time picker become disabled
- [ ] Backend request made when clicking **Save settings** - toast message to show success/error

## CURL Commands
```
curl -k -v  -X PATCH https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol \
-d '{"NTP":{"ProtocolEnabled": false}}'


curl -k -v  -X PATCH https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol \
-d '{"NTP":{"NTPServers":["1.1.1.1"]}}'
```
Can see both of these set at

```
 curl -k https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol
...
  "NTP": {
    "NTPServers": [
      "1.1.1.1"
    ],
    "ProtocolEnabled": false
  },
```

## InVision Link
https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319488036_01-Date-And-Time-Settings-07

## Notes
- If profile settings updated to allow timezone offset preference, add a link to Profile settings. If not, leave it out #2203 
- **Host needs to be powered Off for backend request to work**

## Screenshots
Vue redesign
![Screen Shot 2020-05-14 at 2 36 39 PM](https://user-images.githubusercontent.com/8097306/81988480-65c01c00-95f0-11ea-9c21-2359186459fb.png)

Angular (as reference)
![Screen Shot 2020-05-14 at 1 19 59 PM](https://user-images.githubusercontent.com/8097306/81981816-ad8d7600-95e5-11ea-9b9e-cbfabb1a4a24.png)

**Comment by yoshiemuranaka** [comment]
Questions from planning
- Since NTP servers is an array–is the first item primary and the second item secondary?
- Need cURL for manually setting date/time
- Saving the manual date/time will require the NTP protocol to be disabled

**Comment by derick-montague** [comment]
Discussions about the NTP servers in Redfish being an API and the design using two static input for Primary and Secondary. Redfish moved away from that concept. Discussion about how to handle this is happening in this slack thread: 

https://ibm-systems-power.slack.com/archives/CBVN398HK/p1593013693057900

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34147

**Comment by derick-montague** [comment]
Quick question: 

![image](https://user-images.githubusercontent.com/1183515/85974334-d8b40500-b99a-11ea-8554-49c9b6bf68ba.png)

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34147 merged
