### ISSUE TITLE
GUI : FED : Access Control - Local users management - Language Translation

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1227]
## Overview
Add language translation to Local user management page.

**Comment by derick-montague** [comment]
@yoshiemuranaka - This was done with some of the other stories. Should we move this into code review or close it?

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29888

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29888 merged
