### ISSUE TITLE
GUI: FED: Event Logs - Filter not displaying correct logs

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1229]
## Expected Behavior
The event log filter allows any content that is contained in the event log. If the value in the filter matches information such as, SRC code, type, priority the event logs to 

## Actual Behavior
SRC Code and priority, along with various other strings contained in the event log are not found when filtering

## Steps to Reproduce the Problem

  1. Go to the Event logs
  1. Filter using the SRC code

## Specifications
  - Browser: All
  - Unclear when this was introduced

## Internal Tracking Number
SW476940

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25809 merged
