### ISSUE TITLE
phosphor-regulators: C++ class wrappering the i2c-dev API

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1231]

**Comment by smccarney** [comment]
The phosphor-regulators application will initially use direct I2C communication to voltage regulators.  Device drivers will not be used.

Linux provides a userspace (application) API to perform I2C communication.  It is called i2c-dev.  It is documented here:  https://www.kernel.org/doc/Documentation/i2c/dev-interface

A C++ class is needed by the phosphor-regulators application to wrapper the i2c-dev API.  It should provide the ability to read and write bytes to a device.  It should detect and handle errors.

**Comment by bradbishop** [comment]
at 5:31 PM, Shawn McCarney <notifications@github.com> wrote:

> The phosphor-regulators application will initially use direct I2C  
> communication to voltage regulators. Device drivers will not be used.
>
> Linux provides a userspace (application) API to perform I2C  
> communication. It is called i2c-dev. It is documented here:  
> https://www.kernel.org/doc/Documentation/i2c/dev-interface
>
> A C++ class is needed by the phosphor-regulators application to wrapper  
> the i2c-dev API. It should provide the ability to read and write bytes to  
> a device. It should detect and handle errors.

Can we look for something that already exists for this??  I quickly found  
this one:

https://github.com/bqUAB/linux-i2c but it is GPL.  There has to be others  
that could work for us.

**Comment by smccarney** [comment]
> Can we look for something that already exists for this?? I quickly found this one: https://github.com/bqUAB/linux-i2c but it is GPL. There has to be others that could work for us.

That is fine with me.  I can look around.

**Comment by derekhoward55** [comment]
I think that is a good reminder in general to look for something that already exists, thanks for the reminder.  There is some level of time spent looking for existing support, so whoever gets assigned this story should look for existing support and if nothing found or enhancements need to be made, then do what is required.  Does that sound like an appropriate course of action?

**Comment by bradbishop** [comment]
> Does that sound like an appropriate course of action?

👍

**Comment by smccarney** [comment]
I updated my [initial comment](https://github.com/ibm-openbmc/dev/issues/1231#issuecomment-535693985) to have more complete requirements.

**Comment by smccarney** [comment]
Lei YU wrote a C++ class wrappering the i2c-dev API for the power supply update work.

I have been closely reviewing his implementation in Gerrit.  It looks good to me, so I'm planning to use it for the phosphor-regulators application as well.

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/27627

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/27627 merged
