### ISSUE TITLE
Rainier Power Host Interface - Frame VPD

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1233]
PHYP/IBMi need the frame vpd to be returned in same way as fru vpd over pldm (eg with GetFRURecordTable cmd).  Eg https://github.com/ibm-openbmc/dev/issues/793,  https://github.com/ibm-openbmc/dev/issues/1450.

Below is what keywords were included with the frame vpd, going forward it will be in pldm format.

Frame VPD 
--
 Info | Length | Data | Comment
 RI    | x'04' | x'00 C0 00 30' | Power Resource ID for the frame = 00 C0 config ID (=0x30).
 SE  | x'08' | Enclosure SN | CEC Enclosure Serial Number
 FC | x'08' | Enclosure TM | CEC Enclosure Type and Model / Feature Code

The design is this data needs to be in DBUS.  The FC and SE are already in dbus, and need to be sent up in the GetFRURecordTable cmd under the "motherboard"/chassis record.  The RI keyword (and hardcoded 4-byte value) is being added to the backplane vpd image to be read by the ibm-vpd-parser app.  The plan of record is to put the RI keyword in the DINF record in the vpd, then no yaml file updates would be needed (the ibm-vpd-parser yaml file would need to be updated to include a property for the RI keyword to be added to DBUS if it's placed in a different record, and a new DBUS interface would be need to be created if the RI keyword would be included in a new record in the vpd image).

The PLDM JSON config file needs to be updated to include the RI, FC, and SE keywords in the list to be returned (see issue https://github.com/ibm-openbmc/dev/issues/1197).  At that point, the GetFRURecordTable should return the motherboard record with the 3 needed properties.

Determine if this (and vpd over pldm) will be upstreamed for use on Witherspoon BUP vehicle.

**Comment by derekhoward55** [comment]
Based on conversation with Santosh&Deepak, RI keyword will be added to the backplane vpd (with the 4 data bytes 00 C0 00 30).  We should know shortly if this will be added to existing DINF record, which already has a dbus interface defined.

So work for this story will be to:
1. Update ibm-vpd-parser yaml file to include the RI property (and if necessary, add new dbus interface if the RI keyword can't be added to the existing DINF record in the vpd).
2. Update pldm json config file to include the RI property in the motherboard record.
3. Test with pldmtool or equivalent.

**Comment by strange671** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/34032/

Merged
