### ISSUE TITLE
rainier: first-boot-set-hostname fails

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1235]
See this when booting. I believe later changes showed us reading the VPD but that it was invalid so may just need some work to ensure VPD is being collected.

```
Jan 01 00:00:18 rainier first-boot-set-hostname[295]: No BMC item found in the Inventory. Is VPD EEPROM empty?
Jan 01 00:00:18 rainier first-boot-set-hostname[299]: BMC Serial Number empty! Setting Hostname as 'hostname + mac address'
Jan 01 00:00:19 rainier first-boot-set-hostname[318]: No Ethernet interface found in the Inventory. Unique hostname not set!
Jan 01 00:00:19 rainier systemd[1]: first-boot-set-hostname.service: Main process exited, code=exited, status=1/FAILURE
Jan 01 00:00:19 rainier systemd[1]: first-boot-set-hostname.service: Failed with result 'exit-code'.
```

**Comment by geissonator** [comment]
Some more data:
```
root@rainier:/lib/systemd/system# journalctl | grep vpd
Oct 03 01:55:47 rainier systemd-udevd[130]: Configuration file /lib/udev/rules.d/70-op-vpd.rules is marked executable. Please remove executable permission bits.
 Proceeding anyway.
Oct 03 01:55:56 rainier openpower-read-vpd[346]: Malformed VPD

```

**Comment by jinuthomas** [comment]
The vpd is not in open-power format, it is in IPZ format and so this issue . we are currently working on this.

**Comment by santoshpuranik** [comment]
The VPD errors are gone and we can now see the Serial number of the BMC in the inventory. I am not so sure if  we should be carrying forward the first-boot-set-hostname and first-boot-set-mac to Rainier, though. I think we discussed an alternate design in one of the design exchange meetings for this, @ratagupt ? Assuming you are tracking that via separate stories, we can close this one out

**Comment by geissonator** [comment]
You solved what we were tracking here so lets close this one out.
