### ISSUE TITLE
rainier: failed to start assert bmc_booted LED

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1238]
Missing device tree change? Missing yaml file?
```
Jan 01 00:00:19 rainier systemd[1]: Starting Assert bmc_booted LED...
Jan 01 00:00:19 rainier obmc-led-group-start[324]: path or object not found
Jan 01 00:00:19 rainier systemd[1]: obmc-led-group-start@bmc_booted.service: Main process exited, code=exited, status=1/FAILURE
Jan 01 00:00:19 rainier systemd[1]: obmc-led-group-start@bmc_booted.service: Failed with result 'exit-code'.
Jan 01 00:00:19 rainier systemd[1]: Failed to start Assert bmc_booted LED.
```

**Comment by vishwabmc** [comment]
bmc_booted should be the default group even if there are no physical LEDs under it. So, this should have actually worked. Is there a system I can look into ?.

**Comment by geissonator** [comment]
See internal directions on how to start simulation.

**Comment by vishwabmc** [comment]
```root@rainier:~# cat /etc/os-release 
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.8.0-dev"
VERSION_ID="2.8.0-dev-574-gac05cfe-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.8.0-dev"
BUILD_ID="2.8.0-dev"
OPENBMC_TARGET_MACHINE="rainier"
root@rainier:~# ```

..................................

```
[[0;1;32m*[[0m obmc-led-group-start@bmc_booted.service - Assert bmc_booted LED
   Loaded: loaded (/lib/systemd/system/obmc-led-group-start@.service; static; vendor preset: enabled)
  Drop-In: /lib/systemd/system/obmc-led-group-start@bmc_booted.service.d
           `-bmc_booted.conf
   Active: [[0;1;32mactive (exited)[[0m since Tue 2019-10-15 08:26:42 UTC; 19min ago
  Process: 407 ExecStart=/bin/sh -c busctl call `mapper get-service /xyz/openbmc_project/led/groups/bmc_booted` /xyz/openbmc_project/led/groups/bmc_booted org.f
reedesktop.DBus.Properties Set ssv xyz.openbmc_project.Led.Group Asserted b true (code=exited, status=0/SUCCESS)
 Main PID: 407 (code=exited, status=0/SUCCESS)

Oct 15 08:26:42 rainier systemd[1]: Starting Assert bmc_booted LED...
Oct 15 08:26:42 rainier systemd[1]: Started Assert bmc_booted LED.
```
...................................
```
root@rainier:~# busctl get-property xyz.openbmc_project.LED.GroupManager /xyz/openbmc_project/led/groups/bmc_booted xyz.openbmc_project.Led.Group Asserted
b true
```

**Comment by vishwabmc** [comment]
I see this is working.. Please re-open if the issue is seen.
