### ISSUE TITLE
GUI : Design : "Collect service data" button in event log page 

### ISSUE THREAD

**Issue by ryanarnell** [ibm-openbmc/dev#1240]
## Stakeholders
**SME**: Justin Thaler
**Design Researcher**:
**UX Designer**:
**FED**:

## Use Case
TBD

## InVision Prototype
TBD

## Design Issue (phosphor-webui)
TBD

## Development Issue 
TBD

## References/Resources
- feature discovery folder: 
- user research notes*: 
- user research synthesis: 

*This folder is restricted in accordance with GDPR guidelines.

**Comment by derick-montague** [comment]
Closing this issue. If this is needed, it will be defined in future work for eBMC.
