### ISSUE TITLE
Rainier fan control simics verification

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1242]
Ensure simics implements the max31785 controller correctly before we enable the fan/cooling services and turn on fan support before hardware power on.

Enable all fan&cooling apps/services.

**Comment by msbarth** [comment]
An update has been made to the sim model to emulate a max31785revA controller chip now. Found inconsistencies in the Rainier dts for configuring the max31785revA that needs to be updated and pushed upstream. This should then provide a functional max31785revA to BMC userspace.

**Comment by msbarth** [comment]
Updated Rainier dts to the expected config for max31785revA and pulled down latest sim model(which contains the revA fix) and dmesg shows no errors.
Will push updated dts upstream and then continue to get base framework configs in place to expose the max31785revA to userspace/dbus.

**Comment by msbarth** [comment]
Unable to push the updated Rainier dts upstream as the sim models need to be updated to reflect a correction in Rainier model emulation which changes the number of fan rotors expected (which is driven by the dts).

Will hack up the needed configs against the current model being emulated to verify how its emulated the fans are presented correctly to the driver and userspace.

**Comment by msbarth** [comment]
Pushed initial Rainier dts up -> https://lists.ozlabs.org/pipermail/openbmc/2019-November/019654.html
Once that has been merged, I'll be able to resolve this issue with -> https://gerrit.openbmc-project.xyz/27593

**Comment by msbarth** [comment]
Was able to hack in hwmon configs against each sim model and they looked to provide the correct objects on dbus according to what was presented within sysfs. Target speeds are able be set and then reflected within the feedback files per fan.

Only a minor issue was noticed that the target set on one fan is then reflected as the feedback speed of all fans. This is not a gating problem in sim for fan control so will be worked when/if needed.
