### ISSUE TITLE
NCSI Link Failover

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#1243]
Witherspoon has a service that uses netlink to adjust the NC-SI topology to only allow the BMC to get a link on one of the two ports.

This is desirable for users who want their BMC to be isolated from the network.

The alternative (and default) is that the BMC will fail over to whichever link is active.

OpenBMC could allow this to be configured by the user. They could choose which physical port to enable it on:

-  Port A
-  Port B
-  Either
-  None

**Comment by mine260309** [comment]
What happens if the user chooses "None", does it disables NCSI?
If yes, then the user will be unable to connect to BMC anymore...

**Comment by shenki** [comment]
I was assuming "none" could mean "don't program the NCSI device to do anything, let it use it's defaults.

Perhaps this is a bad idea.

**Comment by mzipse** [comment]
@shenki , do we need to do anything for GA1 related to this issue?  Or is this already completed?

**Comment by shenki** [comment]
I would say yes. We would need to check with the design required for the relevant machines and make sure we're configuring the ports correctly.

**Comment by rfrandse** [comment]
tracking in jira
