### ISSUE TITLE
GUI : FED : Create reusable file upload component

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#1244]
## To Be
![Screen Shot 2019-10-03 at 11.22.26 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/d91b4afe-79b8-4433-955a-a991f020aae7)

![Screen Shot 2019-10-03 at 11.22.41 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/2befa3ab-28fa-4ddd-9569-4f6991f65262)

![Screen Shot 2019-10-03 at 11.22.51 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/755fa185-2d6d-4abe-9dcb-330657407ef5)

![Screen Shot 2019-10-03 at 11.22.58 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/4fcebc1b-2b32-4f79-b4ff-c359c8c97dea)

**Comment by yoshiemuranaka** [comment]
Did carbon change file upload styling? https://www.carbondesignsystem.com/components/file-uploader/code
@jandraa

**Comment by jandraa** [comment]
Yes, looks like they did...

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/27398

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/27398 merged
