### ISSUE TITLE
GUI : Design : VMI (Virtulization Management Interface) IP Address

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1245]
## Stakeholders
**BMC SME**: @ratagupt 
**PHYP SME**: Tom Burks
**Others**: Joe, Russ

## Use Case
As a user I need to see the IP Address on the VMI. 

## InVision Prototype
https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319348488_Server_Overview_-_VMI_-_Current_UI

## References/Resources
- [eBMC Feature: 1.1.11](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)
- feature discovery folder: 
- user research notes*: 
- user research synthesis: 

*This folder is restricted in accordance with GDPR guidelines.

**Comment by jandraa** [comment]
The GUI should display the VMI IP address in the Server Overview page and the Network Settings page. 

Will follow up with whether the same applies for the MAC Address and Hostname.

**Comment by jandraa** [comment]
Determined VMI MAC should also be surfaced, as it can be helpful in connection issues to view the MAC as a way to make sure we don't have IP conflicts.  We've seen scenarios where 2 devices are inadvertently given the same IP, which causes conflicts, and you can verify with MAC. But, only if you can see it.

**Comment by jandraa** [comment]
Did not consider it is IBM only and would be a hard sell in the community -- will not display in the server overview page.

Duplicates #407
