### ISSUE TITLE
GUI : Design : Disable / Enable Protocols

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1246]
## Stakeholders
**BMC SME**: @ratagupt 
**RAS SME**: Justin Thaler
**Design Researcher**:
**UX Designer**:
**FED**:

## Use Case
TBD

## InVision Prototype
TBD

## Design Issue (phosphor-webui)
TBD

## References/Resources
- [Content Inventory Feature: 4.2.3](https://ibm.ent.box.com/file/455779315260)
- feature discovery folder: 
- user research notes*: 
- user research synthesis: 

*This folder is restricted in accordance with GDPR guidelines.

**Comment by nicoleconser** [comment]
Decision has been made that HTTP will be disabled by default. (1/8/20 security workgroup with Joseph Reynolds)

**Comment by derick-montague** [comment]
Closing - Work being done in #1273.
