### ISSUE TITLE
GUI : Design : Firmware Access Key

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1249]
## Stakeholders
**BMC SME**: @anoo1
**PHYP SME**: Paul Olsen, BJ Vette
**Design Researcher**: Nicole Conser
**UX Designer**: Jen Spatz
**FED**: TBD

## Background
POWER8 (and later) servers include an “update access key” that is checked when system firmware updates are applied to the system. In order to be installed, the firmware must have been released prior to the expiration date of this key. When attempting to install system firmware updates, if the release date for the firmware is newer than the expiration date for the update access key, the update will not be processed. 

For example, if the current date is Jan 2020, and your Firmware Access Key expired on Nov 2019, then you can install any firmware released prior to Nov 2019. If you attempt to install firmware released on Dec 2019, the BMC (or HMC) will generate an error and the update will fail. 

See the Discovery doc (link below) for the various ways a user can acquire a new Access Key. 

## Use Case
Before being able to update their Firmware, System Administrators must know whether they have an up-to-date Access Key, or if it has expired. This will determine which level of Firmware they will be able to update to. If it has expired, System Administrators need to know how to renew it. 

See the Discovery doc (link below) for the various ways a user can be notified of a soon-to-be expired or currently expired Access Key. 

## Considerations:
- Access Key does not exist on Linux-only systems (OPAL systems) such as the AC922
- Notification methods depend on whether the system is HMC-managed or not 
- This is IBM-specific (down-stream only)

## Design Questions:
- [x] Where should this live in the eBMC GUI? (currently lives in ASMI header) 
This is an IBM only feature and this will live on the firmware page. It will not be part of the header or the overview page since it only needs to be accessed when updating firmware. 

## References/Resources
- [eBMC Feature 4.8.6](https://ibm.ent.box.com/file/455779315260)
- IBM Wiki: https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/Power%20Systems/page/Update%20Access%20Key
- Feature discovery notes: https://ibm.box.com/s/qq4bya85nc1o6rwt2py3qms2bu76f6h4
- User research*: https://app.mural.co/t/ibmpower1831/m/ibmpower1831/1571936976368/b1ff838003b86e36c124ce840b73b1799541cc3b

*This document is restricted in accordance with GDPR guidelines. 

## Invision
https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319429119_01-Firmware-Access-Key-02

Old Mockups
https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319380202_01-Firmware-Access-02
Firmware Access Key: https://ibm.invisionapp.com/share/TMNZJY795HQ
Firmware Access Key Tool-tips: https://ibm.invisionapp.com/share/EGNZJYADSFT

**Comment by jandraa** [comment]
Un-assigning myself for now. @nicoleconser will work on getting user feedback to determine the location within the Information Architecture then we will work on #1289

**Comment by nicoleconser** [comment]
The decision has been made to include the Firmware Access Key expiration date on the Firmware page (vs on the Header, where it currently lives in ASMI) due to the following user feedback — 

- Users only check the expiration date when updating their firmware 
- Users expect the Access Key expiration date to live on the Firmware page

**Comment by derick-montague** [comment]
Requires user testing to fully understand content.

**Comment by ryanarnell** [comment]
We tested latest invision mockup with users - https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319429119_01-Firmware-Access-Key-02 
If we need to adjust the flow based on single or multiple file firmware update, we can do so once the fimware update backend is ready
