### ISSUE TITLE
Fan Control: Handle add/remove of timer based events

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#125]
<a href="https://github.com/msbarth"><img src="https://avatars2.githubusercontent.com/u/14202667?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [msbarth](https://github.com/msbarth)**
_Wednesday Sep 13, 2017 at 14:50 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2304_

----

When an event that includes a timer has a precondition defined, once the precondition is false the event group is removed however the timer is not. The timer should also be removed when the precondition is false.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
This is handled now with #2911 enhancements where the event's name is used as a key for finding the signals, timers, etc.. and removing them.
