### ISSUE TITLE
Server Overview Consistency

### ISSUE THREAD

**Issue by jspatz1** [ibm-openbmc/dev#1250]
## Use Case
As a user I expect to see consistent patterns across interactive elements and visual styling on each page.

## As is
![Serv Ov Orange.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/7df64e9b-3b65-4f86-b5f1-0f814e63374f)

## To be
![Serv Ov blue.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/03ffed42-5601-4068-b1b0-25fba23da5c3)

1. Sub-header text should be the same size on every page: Heading 2
2. Capitalize only the first word of each subheading
3. Extend lines to same length when not interrupted by components (the longer length)

## As is
![Group 5](https://user-images.githubusercontent.com/32603278/66344593-e1980e80-e913-11e9-9261-fc0b7114e157.png)

## To be
![Group 4](https://user-images.githubusercontent.com/32603278/66344646-f8d6fc00-e913-11e9-834c-02e2e8b31b76.png)

4. Info icon should not be used here

**Comment by derick-montague** [comment]
No longer relevant due to vue rewrite #1555
