### ISSUE TITLE
GUI : FED : Drop Down Consistency

### ISSUE THREAD

**Issue by jspatz1** [ibm-openbmc/dev#1251]
## Use case
As a user I expect to see consistent patterns across interactive elements and visual styling on each page.

## As is - Event Log
![event log orange.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/5344eab7-74e4-4e5e-ab42-58774523377b)

## To be - Event Log
![event log - blue.png]
![Screen Shot 2019-10-07 at 3.50.19 PM.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/cfd95352-9763-4008-9d60-c181d6fab313)
1. Dropdown menus should reflect the designs in the style guide

**Comment by derick-montague** [comment]
No longer relevant due to vue rewrite #1555
