### ISSUE TITLE
GUI : FED : Network Settings - Toast message for invalid Gateway

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1252]
## Expected Behavior
A toast message should be displaying the gateway is invalid only when the value of the Gateway field is invalid.

## Actual Behavior
A toast message is displayed stating the Gateway value is invalid when the field is empthy

## Steps to Reproduce the Problem

  1. Go to the Network Settings page
  1. Add a new IP without a Gateway
  1. Save Network settings

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25923

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25923 merged
