### ISSUE TITLE
GUI : FED : Server Health Consistency

### ISSUE THREAD

**Issue by jspatz1** [ibm-openbmc/dev#1253]
## Use Case
As a user I expect to see consistent patterns across interactive elements and visual styling on each page.

## As is - Hardware Status subpage

![grey2.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/d7925f10-6525-44e8-a229-0742893683a4)

## To be - Hardware Status subpage

![to be hardware.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/a0e2de79-eb12-4af7-a98d-1898ce74fe25)

1. Vertical spacing between labels and and dynamic text should be 8px. Vertical spacing between [label and dynamic text] pairings should be 24px.

## As is - Sensors subpage - part 1

![sensors orange](https://user-images.githubusercontent.com/32603278/66415927-57f34a00-e9c2-11e9-8d75-d36175b22a0d.png)

## To be - Sensors Status subpage - part 1

![Sensors blue](https://user-images.githubusercontent.com/32603278/66415962-66416600-e9c2-11e9-9236-1f57dc226f86.png)

1. Vertical spacing between the "Filter Sensors" text entry field and the "Filter by Severity" heading should be 24px
2. Vertical spacing between the Export link and the divider line should be 8 px.

## As is - Sensors subpage - part 2

![3 orange](https://user-images.githubusercontent.com/32603278/66424026-6c3f4300-e9d2-11e9-93bc-d267fa7c98e8.png)

## To be - Sensors subpage - part 2

![3 blue](https://user-images.githubusercontent.com/32603278/66424060-7c572280-e9d2-11e9-943b-e7a627100d25.png)

3. Width of table/text field should match the width of table/text field on other pages (such as hardware page.)

**Comment by derick-montague** [comment]
Will be resolved in the vue rewrite.
