### ISSUE TITLE
GUI : FED : Fix icon-warning syntax error

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1254]
## As Is
There are some uses of the `icon-warning` icon that is not property defined resulting in errors when webpack tries to build the assets.

## To Be
The icons are properly defined.

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25917

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25917 merged
