### ISSUE TITLE
GUI : FED : Server Control Consistency 

### ISSUE THREAD

**Issue by jspatz1** [ibm-openbmc/dev#1255]
## Use Case
As a user I expect to see consistent patterns across interactive elements and visual styling on each page.

## As Is - Manage Power Usage subpage

![orange managepower usage.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/7299f3f0-2ce1-4858-8f82-2e127b9f62fb)

## To Be - Manage Power Usage subpage
1. Button corners have no radius

## As is - Reboot BMC subpage

![reboot bmc orange.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/abb42d3b-c06d-445f-82f2-ba22a44c84e9)

## To be - Reboot BMC subpage 

![reboot bmc blue.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/3075b9b2-2cbb-42b8-b316-3c1b70f71fd6)

1. Divider line thickness is equal for all lines.

## As is - Virtual media subpage 

![virtual media orange.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/6fabbc7a-30f6-495e-b90e-0eac722b0600)

## To be - Virtual media subpage

![virtual media blue.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/1ba5ef91-2714-4475-92db-0313eccec124)

1. "Choose file" button, file selection bar,, and "Start" button should be center aligned. The space between the buttons and the file selection bar should be 8px.

**Comment by derick-montague** [comment]
This will be resolved in the vue rewrite
