### ISSUE TITLE
GUI : FED : Server Configuration Consistency 

### ISSUE THREAD

**Issue by jspatz1** [ibm-openbmc/dev#1256]
## Use Case
As a user I expect to see consistent patterns across interactive elements and visual styling on each page.

## As is - Network settings subpage

![Network settings.png]

![network settings.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/01852a78-74b7-49a2-a912-182f412a5a6f)

## To be - Network settings subpage

1. Should read "Network settings"
2. Header text should not be all caps
3. Radio buttons should not be accompanied by all caps text
5. More padding at the bottom of page
 
![3.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/b16c74cb-c14b-4e86-821d-b53e4db99993)

**Comment by derick-montague** [comment]
Will be handled in vue rewrite.
