### ISSUE TITLE
eBMC GUI: Server Configuration - HMC

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1259]
## Overview
This Epic covers all the features that will be part of the HMC menu within Server Configuration. This is a menu that is specific to IBM systems.

## References/Resources
- [eBMC Content Inventory](https://ibm.ent.box.com/file/455779315260)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
This is a duplicate of #1360

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
