### ISSUE TITLE
GUI : FED : Server Configuration - Hardware Management Client Sessions

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1261]
## Overview
The client sessions is a base table implementation. There are some changes that FED will make that are slightly different from the design prototype. These changes will be noted in the UX Flow / Interaction Requirements. 

## UX Flow / Interaction Requirements
- [ ] User can delete single or multiple sessions
- [ ] Deleting will show a success or error with the number of sessions deleted
    - `Connection successfully removed` or `Error removing connection` for individual sessions
    - `X Connections successfully removed` or `Error removing X connections` for multiple sessions

## Final Invision Mockup
[Latest prototype](https://ibm.invisionapp.com/share/TBO0R65JC5D#/screens/319803951)

## cURL Commands
All Sessions: `/redfish/v1/SessionService/Sessions`
Session: `/redfish/v1/SessionService/Sessions/<session id>`

```
curl --insecure -X POST -D headers.txt https://{${BMC}/redfish/v1/SessionService/Sessions -d '{"UserName":"root", "Password":"0penBmc"}'
```

```
{
  "@odata.id": "/redfish/v1/SessionService/Sessions/1ZOAXl4ieS",
  "@odata.type": "#Session.v1_3_0.Session",
  "ClientOriginIPAddress": "::ffff:x.xxx.xx.xxx",
  "Description": "Manager User Session",
  "Id": "1ZOAXl4ieS",
  "Name": "User Session",
  "Oem": {
    "OpenBMC": {
      "@odata.type": "#OemSession.v1_0_0.Session",
      "ClientID": ""
    }
  },
  "UserName": "root"
}
```

## Notes
- [x] Follow up with engineering team to determine if there is an API for deleting all sessions or if multiple calls will be needed when performing batch actions
- [x] There will be helper text for the page section that will be provided by design
- [x] We will want to add a new table column for user name and populate it with the username value
    - This is not in the design prototype
- [x] Update toast message to follow common success and error pattern
    - Design shows an info message asking user to refresh (follow UX Flow / Interaction info above)
- [x] To remove a session, make a delete request: `DELETE /redfish/v1/SessionService/Sessions/<session id>`

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [x] Tested responsive layout on supported viewport sizes
- [x] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in DAP

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38731
