### ISSUE TITLE
GUI : FED : Truncated Icon

### ISSUE THREAD

**Issue by jspatz1** [ibm-openbmc/dev#1267]
## Use case
As a user I expect to see consistent patterns across interactive elements and visual styling on each page

Please note: the following inconsistencies are specific to **Safari**

## As Is - Local User Management

![orange x 1.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/45079ee4-d500-4e52-b68d-e1df53b4bcc2)

![orange x 2.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/4eec3ac5-3d91-4c8a-b88d-11057d577abd)

## As Is - SNMP settings

![orange x 3.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/ad1aa308-83e3-4472-9d2c-223ac2037db2)

## To Be

![blue x.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/4f380d92-32fa-4613-933f-a6cbd436834f)

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/27309

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/27309 merged
