### ISSUE TITLE
GUI : FED : Access Control Consistency

### ISSUE THREAD

**Issue by jspatz1** [ibm-openbmc/dev#1268]
## Use Case
As a user I expect to see consistent patterns across interactive elements and visual styling on each page.

## As Is - LDAP subpage

![LDAP.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/c4012679-b2bc-494a-89bd-bb6f0a9d98a2)

## To Be - LDAP subpage

![Screen Shot 2019-10-10 at 4.18.55 PM.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/d2fff90b-d091-4b08-a45c-57b2b2b2a20e)
1. "Enable LDAP authentication" is center aligned with checkbox and "LDAP authentication must be enabled to modify role groups" is above.
2. Eyeball icon appear in the the text entry field when it is not greyed out/inactive.

![Screen Shot 2019-10-10 at 4.20.29 PM.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/d7d19082-1d75-4167-bc92-1da8e4b8efb4)

## As Is - Local User Management subpage

![local user orange.png](https://images.zenhubusercontent.com/5d5da54b8869c80001378dc2/a8737860-66b2-4b09-9437-04306c9df34a)

## To Be - LDAP
3. No black mark in icon (this happens in Safari)

**Comment by derick-montague** [comment]
Will this still be valid in the Vue rewrite?
