### ISSUE TITLE
IPMI : Add ability to specify system-specific providers

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#127]
<a href="https://github.com/dkodihal"><img src="https://avatars1.githubusercontent.com/u/22700515?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dkodihal](https://github.com/dkodihal)**
_Tuesday Nov 14, 2017 at 16:10 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2622_

----

Have current implementation in an openpower repo.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by tomjoseph83** [comment]
Closing the issue, not relevant.
