### ISSUE TITLE
GPIO: D-bus daemon for libgpio

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1272]
We need to preserve the state of GPIO's after applications exit. There is a WIP for this function out at https://github.com/brgl/libgpiod/commit/f946be764e12e4a5949c15df0592f95d2c41419b

This story tracks working with upstream libgpiod to finalize this and work with the OpenBMC community to incorporate it.

FYI @santoshpuranik @spinler @derekhoward55

**Comment by geissonator** [comment]
To make it easier on OpenBMC consumers, could we get the D-bus API into OpenBMC quickly and then implement back end later?

**Comment by amboar** [comment]
So we still have the problem that when the daemon is shut down as part of a BMC reboot it will release the GPIO lines and cause their state to reset, which will affect e.g. SOFTWARE_PGOOD among others that control host power state. I don't have a good solution to this issue without changing the kernel interface (or at least exposing a persistence flag, which I have proposed in the past).

**Comment by rfrandse** [comment]
tracking in jira
