### ISSUE TITLE
GUI : Design : Security Panel

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1273]
## Stakeholders
**BMC SME**: @joseph-reynolds, @ratagupt, @geissonator 
**RAS SME**: ~~Justin Thaler~~ George Ahrens
**SME Firmware**: Dean Sanner
**IBM i SME**: Nicole Schwartz
**PHYP SME**: Tom Burks III

## Overview
There are many features that the admin needs to be able to enable and disable. The UI does not have the centralized location for this information. It will be helpful to determine:

1. Is this type of panel needed?
1. Where should this menu live within the information architecture?
1. What are all the features that would need to be accessible from this menu?
1. Is there impact to any existing screens that have similar functionality?

### Related stories
The design stories are work that is being captured in this story, but was broke down into smaller chunks. That break down might be needed for UI implementation. We can refer back to these stories for detailed info as needed. 

- Disable/enable out of band IPMI
    - Design #512
    - Backend Story: #513
- Disable BMC shell access for support 
    - Design #734
- Enable / Disable USB (CE login only)
    - Design #1275 
    - Backend #1781 
- Enable / Disable RTAD 
    - [Gerrit Design Doc](https://ibm.ent.box.com/file/658556488536)

### Enable / Disable IPMI
As as user, I want the ability to enable and disable IPMI to prevent security vulnerability stemming from out of band network access to BMC / host.

### Enable / Disable USB
1. Make sure that USB disable is present... and then have a separate disable for Host / BMC.

https://redfish.dmtf.org/schemas/ManagerNetworkProtocol.v1_4_0.json defines a property, IPMI, that is of type protocol, that has a ProtocolEnabled property. Use that to toggle the enable/disable of out of band IPMI

## References/Resources
- [Content Inventory Features: 4.2.3](https://ibm.ent.box.com/file/455779315260)
- Feature discovery: https://ibm.box.com/s/np5t0c0l2wagkf95dxx0jar3cf906uws
- Feature Notes for #512: https://ibm.ent.box.com/notes/476773318955
- All possible interfaces: https://ibm.box.com/s/xcjomf52va94ae6gvhe0my7m8z9mrjic
- Redfish: ( Redfish - definitions > ManagerNetworkProtocol > properties ) : https://redfish.dmtf.org/schemas/ManagerNetworkProtocol.v1_4_0.json

### Invision prototype
**Low fidelity**
https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319453441_01-Security-Settings-00
**HI fi**
https://ibm.invisionapp.com/share/SGO0QDLQ8VD

**Comment by jandraa** [comment]
For the Web GUI, the Security Workgroup discussed the idea of having a single page view that shows all of the controllable interfaces and their status (enabled/disabled).  This can have links to pages with more detail, for example, detailed network configuration settings.

Identified a core set of interfaces that cannot be disabled simultaneously: 
- IPMI   (out of band)     
- IPMI (inband) 
- SSH    
-  Redfish / REST / HTTPS     

Need to push a gerrit review containing the list of interfaces, and information about each (such as exactly what the interface is, if OpenBMC offers that interface, if it is enabled by default, how the BMC Admin can enable or disable it, etc.)

See workgroup notes: https://docs.google.com/document/d/1b7x9BaxsfcukQDqbvZsU2ehMq4xoJRQvLxxsDUWmAOI/edit#

**Comment by jandraa** [comment]
Need to push a gerrit review containing the list of interfaces, and information about each (such as exactly what the interface is, if OpenBMC offers that interface, if it is enabled by default, how the BMC Admin can enable or disable it, etc.). 

I've shared the interface tracking Excel file with @joseph-reynolds. Once there is more clarity on what the requirements are from the GUI in terms of which interfaces to disabled and which not, the design team will pick up this story again.

**Comment by jandraa** [comment]
@joseph-reynolds pushed a doc to gerrit review for this. See https://lists.ozlabs.org/pipermail/openbmc/2019-December/019867.html

**Comment by jandraa** [comment]
Latest comments from Joseph:

> As  I mentioned in https://github.com/ibm-openbmc/dev/issues/612, I want to have at least SSH and network IPMI on the list. (edited) 
> [3:02 PM]
> There is also the related concept of “whitelisted” host IPMI commands which resticts an untrusted host to using only the commands it needs.  I’ll add that to the review.  <-- I think the webui might want to be able to enable/disable that feature.  It’s a bit tricky because its an IBM thing, and I believe Intel does it differently.
> [3:03 PM]
> Hopefully we can move away from IPMI altogether and onto PLDM over MCTP.

**Comment by nicoleconser** [comment]
**Jandra:** FYI -- this is feedback I got from Joseph Reynolds. When yall decide to do more research on this, it might be good to reach out to BMC leaders. We talked with Andrew at a very early point, he might be good to follow up with.
`Thinking about the "BMC interfaces" work, it felt like we were the blind leading the blind, missing the benefit of a BMC architect, that is, someone who could answer all of our questions in just a few minutes.  After we defined our problem statement (which interfaces to disable), we should have sought after some BMC leaders' opinions.`

**Comment by ryanarnell** [comment]
This issue lists some of the backend discovery work https://github.com/ibm-openbmc/dev/issues/612

**Comment by derick-montague** [comment]
@ryanarnell - I am consolidating the stories that we discussed in sprint planning today. One thing to note is that in the IA we currently have a `BMC Options` menu that is a child of server configuration in the spreadsheet, item 4.2. We will want to think about this when determining where this is placed in the IA.

**Comment by derick-montague** [comment]
The security panel was supposed to be part of  new `BMC Options` section. We should look at the Epic and try to see how this might change if the entire `BMC Options` section included these settings along with the other BMC Options outlined in the Epic

**Comment by nicoleconser** [comment]
@derick-montague Thoughts on taking this **_out_** of the BMC options epic, and adding it to a **_new_** epic called Security Settings? 

1. We're not sure if we're moving forward with BMC Options 
2. It's looking like the settings on this page aren't limited to just the BMC — some might also (or only) impact the host

**Comment by nicoleconser** [comment]
**Key Clear** #2302 (called Secure Storage Policy in ASMI) might belong on this page per [7/15 conversation](https://ibm-systems-power.slack.com/archives/GKXDFTLFJ/p1594765651028900) w/ Maury & Chris Engel.

**Comment by derick-montague** [comment]
@nicoleconser 

> Thoughts on taking this out of the BMC options epic, and adding it to a new epic called Security Settings?

I am not sure we are moving forward with Security settings either. ;) Does it make sense to leave everything as is until we have a better idea of if we are removing BMC options and can move around based on that info?

**Comment by derick-montague** [comment]
This will potentially also include External services management. We need to revisit and validate the designs and potentially include RTAD from external services management.

**Comment by ben-bacon** [comment]
ASMI > External Services Management > RTAD (related to VMI)
ASMI > Network Services > Network Access (this is an allow/block list for IP addresses - does it make sense here since it’s security related? if not, where?)
ASMI > System Configuration > Security > Secure Storage Policy (not something most customers will want to do bc it could potentially invalidate the warranty of the box / related to clearing TPM data / Factory default option might go away / note this is not on all servers)
ASMI > System Configuration > Security > USB Policy (CE login only - believe this is already  on Ryan’s prototype)

**Comment by nicoleconser** [comment]
**Joseph Reynolds:** We should consider adding ability to disable SoL console here for security reasons. Need to find out if customers would want to disable access to their host console. Assumption is Service reps would always want to keep that open.

**Comment by ben-bacon** [comment]
Only spent a small time researching the current data with the newly found constraints/additions. [Documented possible executions](https://ibm.invisionapp.com/share/E7O0EVQ5KB2)

**Comment by priyanka-pillai97** [comment]
**Current Status** 
From GUI team:
- The 7 items shown in the current prototype are not related to the excel sheet - the excel sheet came afterwards.
- Whether more than just BMC related settings need to be shown here is part of the Discovery.

From Joseph Reynolds:
- "Interface Overview doc: Only an overview. Specifically, it shows many interfaces which we would never want to disable. I don’t think we’ve finalized which of these services we need to enable and disable." Link: https://github.com/openbmc/docs/blob/master/architecture/interface-overview.md
- "Excel tracker: I have not finalized the Excel spreadsheet.  I will review it and make notes. I am not aware that any of the BMC/PHYP interfaces need to be disabled." Link: https://ibm.ent.box.com/file/551613138421?s=vn1sx4reo5b2m23hto3hpj4zc9i8lj1b
- "I’m not sure about the use cases to be able to disable: mDMS discovery, VirtualMedia, and KVMIP. Was @Nicole going to user-research these?  Sorry, I’ve lost track."
- Check if HostConsole is part of the excel.
- Reviewed and suggested how to re-word the UI descriptions. He also said we should get a Content writer to help us with these.

Next steps for GUI team:

- Determine IA of this page. This is also dependent on point 2.
- Determine what all settings can be disabled enabled - not sure if we have to determine this. As per our understanding, Joseph needs to give us this information in the excel after reviewing it. (TBD)
- Need to know if phyp settings has to be included. Joseph has asked us to include him to the call if we are meeting with a PHYP SME.
- Determine the design (especially interaction model) of this page. This we can probably do without the above 2 as of now, up to a LoFi level.

**Comment by ParishrutB** [comment]
Note: Security settings was earlier called Protocol enablement.

Next steps DRAFT:

1. Add all possible settings to the excel sheet - check ASMI & Interfaces overview doc, eBMC Feature planning doc, Susan's IA which shows what all was supposed to be in BMC Options.
2. Get Joseph to complete the excel sheet- or we do it together with him - we might need to provide some information on use cases. 
3. Decide which settings should go to which pages - especially which settings should be part of Settings page.

**Comment by ParishrutB** [comment]
Security Panel update:

After going through Joseph’s mural, Interfaces Overview doc, and meeting with Ratan to discuss what is parity with FSP, following ones were considered as requiring Enable/Disable control from Security Panel. Have also checked them against Nicole's feature tracker to see which ones are relevant for GA1. 

Remaining doubts are mentioned next to each.

1. Out of band IPMI - Nicole’s tracker says ‘not keeping’
2. Inband IPMI - Nicole’s tracker says ‘no longer needed, IPMI removed’
3. SSH Port 22 (BMC Shell) - Nicole’s tracker says ‘not keeping’, Github #612 shows as not implemented
4. SSH Port 2200 (SoL, Host Console) - Can this be enabled or disabled? If yes, is the enable/disable control relevant to SoL page? 
5. Avahi mDNS - not found on Nicole’s tracker
6. Physical network - no definition found even in Interfaces Overview doc
7. USB external - Does this refer to the physical USB port on the BMC?
8. Usb to host - Does this refer to the physical USB port on the Host?

Checking 4,6,7,8, on Slack with Ratan and Joseph first.

**Comment by ParishrutB** [comment]
###Short summary

The following interfaces will be available to enable/disable on this page:
1. USB External
2. Out of band IPMI
3. SSH Port 22 (BMC Shell)
4. SSH Port 2200 (SoL)
5. RTAD

Waiting for confirmation on:
1. Inband IPMI [here](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1603886690117500?thread_ts=1602513321.188100&cid=C0Q6TQP5Z)

Note: Whether SSH Port 2200 is required to be enabled/disabled, needs to be checked in the research. We can do this during the LoFi testing, hence included it in this list.

**Comment by nicoleconser** [comment]
Pasting comment over from #1781 — 

Per @joseph-reynolds, the BMC should be able to enable/disable individually each of the BMC's 2 USB ports.

The BMC should also be able to enable/disable access to the host-embedded USB ports (collectively: not individually).

But we don’t know which of these controls we will have APIs for the BMC admin to use. Do we tie them all together? Articulate them separately? Control some but not others?

More details in this Slack conversation.

**Comment by priyanka-pillai97** [comment]
Points to remember
1. Server attached USB will be a service login function only. 
2. TPM will need to be added to the right sub section.
