### ISSUE TITLE
GUI : FED : Update toast notification component

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#1274]
Update visual styles and toast types

## As Is

![Screen Shot 2019-10-15 at 1.58.31 PM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/5f3b8669-69f6-492e-9926-dac37fb652d0)

![Screen Shot 2019-10-15 at 1.58.39 PM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/90e8f77c-afdc-4772-9851-992b7cc41ffa)

## To Be

![Screen Shot 2019-10-15 at 1.59.39 PM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/a8922aa6-39f9-4df1-b0be-f118c8d4bfd0)

**Comment by jandraa** [comment]
For legibility, I modified the opacity of the colors we have established on the app. Let me know if this is a problem. 
![Screen Shot 2019-10-15 at 4 45 09 PM](https://user-images.githubusercontent.com/44675611/66872370-71b90200-ef6b-11e9-9e74-60b42213311d.png)

**Comment by yoshiemuranaka** [comment]
This looks great, thanks for sending the hex codes. So I am updating to these colors across the app right?

**Comment by yoshiemuranaka** [comment]
Also, did we define the behavior? Should some be automatically dismissed (timeout) and others  manually dismissed by the user (close button)? @jandraa @derick-montague

**Comment by derick-montague** [comment]
I'll leave that to @jandraa and just add that I feel there is value in having a notification option that must be dismissed manually by the user.

**Comment by jandraa** [comment]
>So I am updating to these colors across the app right?

Would it be terrible to have notification specific colors? I ask because looking at lower opacity of these colors in the rest of the app looks odd. It might be just me because I've seen this so much. What do you think? 
<img width="628" alt="Screen Shot 2019-10-16 at 4 56 42 PM" src="https://user-images.githubusercontent.com/44675611/66962170-f708e900-f035-11e9-959d-d5070dfc8f21.png">


>Should some be automatically dismissed (timeout) and others manually dismissed by the user (close button)?

I agree with @derick-montague that there is value in manually dismissing. @jspatz1 and I discussed, we landed on they should all be manually dismissed, expect for 'success'. Do you agree with that?

**Comment by yoshiemuranaka** [comment]
Yeah, I think it's fine to add toast specific colors if we need, but most of them are close to existing shades. not sure if the style guide/variable names are synced up. This is what we have existing below. If we add the new toast colors, I would make a new lighter variable name so 
$color--red-10, $color--yellow-10, etc.


```
$color--red-50: #DA1416;
$color--red-20: #FAD3D3;

$color--yellow-50: #FEDF39;
$color--yellow-20: #FFF8E4;

$color--green-50: #0A7D06;
$color--green-20: #C6E8C5;

$color--blue-40: #2D60E5;
$color--blue-20: #CCD7F4;
```

Everyone is ok with all toasts needing to be manually dismissed except success? Success will still have a the close button but will also automatically dismiss after 10 seconds (current pattern).

**Comment by derick-montague** [comment]
> I agree with @derick-montague that there is value in manually dismissing. @jspatz1 and I discussed, we landed on they should all be manually dismissed, expect for 'success'. Do you agree with that?

I agree. Success is not as necessary, but anything informational and especially warnings and errors should require the user to dismiss.

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/26264

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/26264 merged
