### ISSUE TITLE
BMC Isteps: proc_select_boot_master

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1277]
- Review HWP,
- Enable HWP in libekb Build infrastructure
- Enable this istep in IPL Infrastructure.

Any additional work related to BMC specific business logic effort is not included here.

**Comment by ojayanth** [comment]
Based on the latest design direction , not a hwp driven step now and not required for poower-on

**Comment by lkammath** [comment]
WIP

**Comment by lkammath** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-proc-control/+/31731/ - code upder review

**Comment by ojayanth** [comment]
IPL Changes : https://github.ibm.com/openbmc/openbmc/pull/362

**Comment by lkammath** [comment]
openpower-proc-control changes are already integrated

Bump and other required changes -> https://github.ibm.com/openbmc/openbmc/pull/368

**Comment by lkammath** [comment]
This is completed.
