### ISSUE TITLE
HMC-BMC(Certificate sign)Investigation story for PLDM interface

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1284]
This story is to investigate the PLDM interface for the certificate sign.

Should we use the PLDM File/IO interface for the certificate sign? or 
Should we keep the certificate as BIOS attribute?

Discussion needs to be done with PLDM stakeholders and come up with the agreed PLDM interface for the communication with PHYP.

Can we make the PLDM call synchronous? 

or PLDM having asynchronous calls with PHYP, but the client(bmcweb) would be getting the synchronous behavior i.e(PLDM abstract the asynchronous behavior)

**Comment by raviteja-b** [comment]
My understanding of Using PLDM file IO for VMI certificate exchange
On recieving signCSR request, bmc sends "new file available" PLDM command to PHYP.
PHYP will reserve tce address and send readFileByTypeIntoMemory and ReadFileByType(if needed) to bmc.
bmc will transfer the CSR and send response.

PHYP sends CSR string to VMI, VMI the signs CSR and sends signed certificate and the Root CA certificate to PHYP

PHYP calls 'WriteFileByTypeFromMemory' to bmc, which write to a file on bmc.

signCSR API needs to wait for this operation to complete and provide response to HMC


impacts:
1.Create new pldm file type 'CERTIFICATE_EXCHANGE' for VMI certificate exchange.
2.Decide on file paths to store files during certificate excahnge

Points needs to be discussed:
1. Does phyp send signed certificate and RootCA certificate as two different files?
   need to define two file types?
2. do we need to delete files created on BMC during file exchange?

**Comment by raviteja-b** [comment]
My understanding of Using PLDM BIOS attribute for VMI certificate exchange
On recieving signCSR request from management console, 
the BMC immediately updates the BIOS attributes locally and then 
BMC can provide updates to the BIOS using PLDM messages(set/updateBIOSTable)

PHYP sends CSR string to VMI, VMI the signs CSR and sends signed certificate and the Root CA certificate to PHYP

PHYP updates this cerificate strings into BIOS attributes using update/setBIOSTable.

signCSR API needs to wait for this operation to complete and provide response to HMC


-Impacts:
1.Create new BIOS attributes 'CERTIFICATE' and 'ROOT_CERT' for VMI certificate exchange.

-Points needs to be discussed:
can phyp set same attribute  with rootCA and client certificate string??
certificate string size may go upto 3-4K, which increases BIOS attribue table size.
what is max length of BIOS attribute string defined by phyp
can bmc call setBIOSTable any time after phyp is up and running?

**Comment by ratagupt** [comment]
@amboar ^^^^

**Comment by raviteja-b** [comment]
we had discussion with PHYP and PLDM folks and decided that we are going to use PLDM file IO for certificate exachange
