### ISSUE TITLE
HMC-BMC how to handle the multiupart-form data. 

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1286]
Outcome for this story would be to find how to handle the multipart-form data. If we solve this problem then it would also solve one of the workshop action items where it was asked by the MC team to provide the API which updated multiple files in a single request so that we can provide the atomicity.
multipart-form http request  looks like  below
eg
```=================================================================
POST / HTTP/1.1
[[ Less interesting headers ... ]]
Content-Type: multipart/form-data; boundary=---------------------------735323031399963166993862150
Content-Length: 834

-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="text1"

text default
-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="text2"

aωb
-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="file1"; filename="a.txt"
Content-Type: text/plain

Content of a.txt.

-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="file2"; filename="a.html"
Content-Type: text/html

<!DOCTYPE html><title>Content of a.html.</title>

-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="file3"; filename="binary"
Content-Type: application/octet-stream

aωb
-----------------------------735323031399963166993862150--
=============================================================```

Boost beast doesn't have the support for multipart form parser.
https://github.com/boostorg/beast/issues/952

It is suggested to use the mimetic library for parsing the multipart.

Don't limit your research till mimetic, Look for other tiny opensource which can be used to parse multipart-form data.

**Comment by geissonator** [comment]
https://github.com/ibm-openbmc/dev/issues/654 also requires multi-part work so we should keep an eye on each other.

**Comment by sunharis** [comment]
The libmimetic is used as the multipart form data parser. 
The hardware management console usecase for parsing the save-area file upload to the BMC is implemented using this library. The code is up in the gerrit at https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/24986/

**Comment by rsnair** [comment]
Handling multipart-form data was not in scope for the committed & delivered milestone for Save Area. Hence moving it out.

**Comment by ratagupt** [comment]
@asmithakarun: Can you please paste the gerrit link here?

**Comment by asmithakarun** [comment]
The implementation for multipart file upload using this library (mimetic) has been pushed.

Heres the link: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/31030

**Comment by asmithakarun** [comment]
@EdTanous have mentioned another multipart parser in place of libmimetic which is comparatively smaller in size.

Hence, moving forward using that parser. Rework is going on!

**Comment by ratagupt** [comment]
Seems HMC doesn't need this functionality, we can work on this after GA1.

**Comment by sunharis** [comment]
We are not working on this
