### ISSUE TITLE
GUI : Alerts - SNMP traps

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1288]
## Stakeholders
**SME**: @ratagupt, Todd Rosedahl
**RAS**: TBD

## Use Case
TBD

## Overview
Based on user feedback conducted by @nicoleconser this is one of the most important features in the GUI. This is a merge of both Redfish Alerts and SNMP Alerts (Traps only).

## InVision Prototype
~~Iteration 1: https://ibm.invisionapp.com/d/main#/console/15347903/319665218/preview~~
For feature validation: https://ibm.invisionapp.com/d/main#/console/15366764/319741955/preview

For implementation (Use the **Local User Management** page as a reference): https://ibm.invisionapp.com/d/main#/console/15347903/319910246/preview
Screenshots: https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1615965846004800?thread_ts=1615890562.001000&cid=GBVDZRCQK

## Key Conversations
- API details - https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1614681302299800

## cURL commands
 - https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599/8//COMMIT_MSG#40
`^^ more info here also`
```
curl -k -H "X-Auth-Token: $token" -X POST https://${bmc}/redfish/v1/EventService/Subscriptions -d '{"Destination": "http://192.168.31.30:58", "SubscriptionType": "SNMPTrap", "DeliveryRetryPolicy": "TerminateAfterRetries", "Protocol": "SNMPv2c"}'
```

## Notes
- Backend Gerrit Review: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/30575

## References/Resources
- [eBMC Feature 4.1.5](https://ibm.ent.box.com/file/455779315260)
- Email from Todd Rosedahl on August 5th (@priyanka-pillai97, @ParishrutB, @nicoleconser, @gtmills, and @derick-montague all included)
- feature discovery doc: https://ibm.box.com/s/t362dloye48skxmqfqme34bouufiz19b
- user research notes*: 
- user research synthesis: 

*This folder is restricted in accordance with GDPR guidelines.

**Comment by derick-montague** [comment]
Need to validate with users. @nicoleconser determining how to quickly determine value to users.

**Comment by derick-montague** [comment]
@nicoleconser - There is a Redfish Epic #786. I need to verify how these are related to push notifications, but wanted to make you aware of this story.

**Comment by derick-montague** [comment]
There is a [Gerrit review](https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38059) also for Redfish Push Notifications referenced in #1776. There is also some downstream code completed for Push Notifications related to HMC that may be useful for the GUI. It is possible that this story results in:

1. A new alerts page that has SMP alerts (trap only)
1. A follow up story for Redfish Alerts based on [Gerrit review](https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38059) in #1776 and current work downstream.

**Comment by derick-montague** [comment]
Ratan shared today that the community does not have agreement for Redfish subscriptions, so the implementation is downstream only and only a some of the options. Given that, we need to understand if there is value in building that out today.

**Comment by derick-montague** [comment]
The Gerrit review for SNMP traps has some discussion that may slow the delivery - https://github.com/ibm-openbmc/dev/issues/256#issuecomment-747803459

**Comment by ParishrutB** [comment]
### Old mockups - for reference

**Edited mockups:**
![image (23)](https://user-images.githubusercontent.com/61419136/110612257-056d1d00-81b6-11eb-9b18-3d85b355b5c1.png)
On selection:
![Screenshot_2021-03-10 Local user management](https://user-images.githubusercontent.com/61419136/110612265-0900a400-81b6-11eb-8d21-db5f6206c4dd.png)
Modal to add:
![638D77A0-D517-46A9-B37F-C146A89C1F17_4_5005_c](https://user-images.githubusercontent.com/61419136/111300054-aeb08900-8676-11eb-8e6a-0e46b81e25f0.jpeg)
Modal to delete:
![5ABD6071-AE5B-4FCC-BE1E-9A131DE026BC_4_5005_c](https://user-images.githubusercontent.com/61419136/111300069-b3753d00-8676-11eb-986d-0bb37fdaf6e3.jpeg)

**Comment by derick-montague** [comment]
> ### Old mockups - for reference
> 
> **Edited mockups:**
> ![image (23)](https://user-images.githubusercontent.com/61419136/110612257-056d1d00-81b6-11eb-9b18-3d85b355b5c1.png)

**FYI: This is just the pattern for layout using the user management screen for reference.** 
We want to use the design linked in description section under Invision prototype.

**Comment by derick-montague** [comment]
Based on Redfish, the user will only be able to create and delete the event.

**Comment by derick-montague** [comment]
Blocked by Gerrit reviews in #256.

**Comment by sandeepasingh116** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/41674

**Comment by derick-montague** [comment]
@sandeepasingh116 - It looks like all the FEDs are assigned as reviewers. Can you work with the team to determine who should be assigned and who should be CC'd?

**Comment by gtmills** [comment]
This is in downstream. Can we push this downstream?

**Comment by derick-montague** [comment]
Once the information architecture (IA) is merged, we can update this and move the commit downstream. #256 is ready downstream and is not a blocker for moving this downstream.

**Comment by derick-montague** [comment]
Please make sure to keep this story in the `Code review in Driver` pipeline once this is completing.

**Comment by mzipse** [comment]
Work is complete.  Closing.
