### ISSUE TITLE
BMC Image FIT Verification

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#129]
<a href="https://github.com/anoo1"><img src="https://avatars0.githubusercontent.com/u/9052527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anoo1](https://github.com/anoo1)**
_Thursday Jan 25, 2018 at 21:17 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2829_

----

Epic for checking FIT in u-boot before booting from a newly flashed image.

**Comment by rfrandse** [comment]
<a href="https://github.com/anoo1"><img src="https://avatars0.githubusercontent.com/u/9052527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anoo1](https://github.com/anoo1)**
_Tuesday Feb 13, 2018 at 22:24 GMT_

----

A reference link from Yugi - https://chromium.googlesource.com/chromiumos/third_party/u-boot-next/+/chromeos-v2013.06/doc/uImage.FIT

**Comment by rfrandse** [comment]
<a href="https://github.com/anoo1"><img src="https://avatars0.githubusercontent.com/u/9052527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anoo1](https://github.com/anoo1)**
_Monday Feb 26, 2018 at 15:48 GMT_

----

This should probably also ensure that netbooted images are verified.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
Not a current requirement.
