### ISSUE TITLE
Code Update: Minimum Ship Level

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#1293]
Epic to track the implementation of the Minimum Ship Level, which specifies the version that the system cannot be downgraded from. For ex. if the MSL is 100, then a version of 99 cannot be applied to the system.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
Done with https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/29914

**Comment by mzipse** [comment]
Added some story points to cover the work in the stories linked to this Epic since none of the Stories had estimates.
