### ISSUE TITLE
Commit/Accept: New interface to mirror the BMC image to the alternate side

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#130]
<a href="https://github.com/anoo1"><img src="https://avatars0.githubusercontent.com/u/9052527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anoo1](https://github.com/anoo1)**
_Thursday Feb 01, 2018 at 20:17 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2864_

----

Currently a BMC firmware update only updates one BMC chip. If a system has 2 BMC chips, there's a desired to be able to mirror that image to the 2nd chip so that both chips have the same firmware version.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
Maybe this means deleting the alternate image. There's only one flash chip, so keeping 2 images the same doesn't add resiliency if the chip fails.

**Comment by anoo1** [comment]
We're not going to implement this.
