### ISSUE TITLE
GUI : FED : Language Translation

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1302]
## Use Cases
1. Users want to be in control.  There are people that speak both languages, and in general prefer an English BMC, given that even the best UI translations will always include things that weren't translated, like IPMI SELs, Sensor names, and other things that are defined by the system or protocol in the backend, and not by the framework.
1. A user may not have put all their preferences on said system at the time they're using the BMC, so giving them an easy way to select what they want is a win.
1. The languages that are supported is listed to make it clear what translations are offered

## Overview
- [x] Determine how the language translation will be supported
As a user of the OpenBMC Web UI, I need the language translations to be determined by my operating system preferences with the ability to change those settings before and after logging into the system.

- [x] Plugin to use
Vue I18n

- [x] What is in ASMI that is translated and how is it handled? 
ASMI supports English, French, German, Italian, Spanish.

## Group 0:
FSP has all the Group 0 languages installed on the flash by default. 

    - English
    - French
    - German
    - Italian
    - Spanish

## Group 1:
The Group 1 languages are optionally installed by the customer.  It sounds like there was a separate LID for those languages.

    - Brazilian Portuguese
    - Japanese
    - Korean
    - Simplified Chinese
    - Traditional Chinese

## References/Resources
- [ASMI Content Inventory item 10.4](https://ibm.ent.box.com/file/455779315260)
- [feature discovery folder](https://ibm.box.com/s/vym58ukem44b5mb3dq9maou71rb03229)
- user research notes*: 
- user research synthesis: 

*This folder is restricted in accordance with GDPR guidelines.

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/28965
