### ISSUE TITLE
phosphor-regulators: Implement chassis, device, and rail

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#1309]
Implement the following C++ classes:
* Chassis
* Device
* Rail

To do this, basic versions of the following C++ classes must also be created:
* Configuration
* PresenceDetection
* SensorMonitoring

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/30265

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/30265 merged
