### ISSUE TITLE
phosphor-regulators: Implement PresenceDetection/ComparePresenceAction classes

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#1310]
**Overview**

Complete implementation of the following classes related to regulator presence

* PresenceDetection
* ComparePresenceAction

**PresenceDetection**

The execute() method implementation should be similar to Configuration::execute().  It should construct an ActionEnvironment, execute the actions, and catch/handle any exceptions.  It should return whether the device is present.  Unlike Configuration::execute(), it should not write anything to the journal unless an error occurs.

See docs/config_file/presence_detection.md for more information.

The test cases should be similar to Configuration::execute():
* Test where device is present
* Test where device is not present
* Test where an error occurs

**ComparePresenceAction**

The execute() method implementation should be similar to I2CCompareBitAction::execute().  However, rather than reading a bit value from a device over I2C, it should read the presence value using the Services->getPresenceService()->isPresent() method.  Then it should compare the actual value to the expected value.  It should return true if they match and false if they don't.

Note that the isPresent() method above is not yet implemented.  I am working on that right now under issue 2737.

See docs/config_file/compare_presence.md for more information.

The test cases should be similar to I2CCompareBitAction::execute()
* Test where works: actual value equals expected value
* Test where works: actual value not equal to expected value
* Test where fails: PresenceService throws an exception

**Comment by bobkingkkp** [comment]
Resolved by https://gerrit.openbmc-project.xyz/38515

**Comment by smccarney** [comment]
ComparePresenceAction was resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/38125

**Comment by smccarney** [comment]
PresenceDetection was resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/38515/9
