### ISSUE TITLE
phosphor-regulators: Include application in Rainier firmware image

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#1313]
Modify the build process to include the phosphor-regulators application and the associated JSON config file(s) in the Rainier firmware image:
- [x] Update meson build files in phosphor-power repository as needed
- [x] Create/update bitbake recipes in various meta layer repositories.
- [x] Determine proper executables directory on BMC
- [x] Copy phosphor-regulators application executable into executables directory in firmware image
- [x] Create directories in firmware image that are required by the phosphor-regulators application:
  * /usr/share/phosphor-regulators
* Copy Rainier JSON config file(s) into /usr/share/phosphor-regulators directory in firmware image (`config_files` within the repo dir to store all configs)

The phosphor-regulators application and JSON config files are not currently needed on other systems like Witherspoon.

**Comment by msbarth** [comment]
I've created a first pass of 3 service files and have successfully got them installed (along with the phosphor-regulators binary) and linked with the necessary systemd targets. Need to make some updates to the binary to verify the dbus method calls from 2 of the services occur at the expected points of poweron.

Binary started at BMC standby:

```
root@rainier:/lib/systemd/system/obmc-chassis-poweron@0.target.wants# obmcutil power
pgood = 0
state = 0
pgood_timeout = 10
root@rainier:/lib/systemd/system/obmc-chassis-poweron@0.target.wants# systemctl list-units | grep phosphor-regulators
  phosphor-regulators@0.service                                                                                             loaded active running   Phosphor Pow
er Regulators Daemon    
```

**Comment by msbarth** [comment]
The final bit of functionality of this issue is working now. Any/all config files that reside within `phosphor-power/phosphor-regulators/config_files/` are installed within `/usr/share/phosphor-regulators` in all BMC images using phosphor-regulators. This was my understanding what what was requested and similarly follows how the entity-manager project handles configuration files.

I'll clean and push up the commits for review now covering each area listed.

**Comment by msbarth** [comment]
Recipes updates &rarr; https://gerrit.openbmc-project.xyz/28154
Config file installed &rarr; https://gerrit.openbmc-project.xyz/28140
Service to load/start binary in image &rarr; https://gerrit.openbmc-project.xyz/28141
