### ISSUE TITLE
phosphor-regulators: Unbind regulator device drivers in Rainier device tree

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#1316]
Currently there are device drivers bound to the voltage regulators in the Rainier device tree.  They need to be removed since the phosphor-regulators application will communicate with the regulators directly using i2c-dev.

**Comment by msbarth** [comment]
Removed all `ir` devices from the Rainier dts and verified in sim that there were no longer errors in dmesg on those devices. Pushed the updated Rainier dts upstream -> https://lists.ozlabs.org/pipermail/openbmc/2020-January/020217.html

**Comment by msbarth** [comment]
Reviewed
https://lists.ozlabs.org/pipermail/openbmc/2020-January/020224.html
https://lists.ozlabs.org/pipermail/openbmc/2020-January/020225.html

Just waiting on it to be merged and pulled into our builds

**Comment by msbarth** [comment]
Status
http://patchwork.ozlabs.org/patch/1224310/

**Comment by msbarth** [comment]
This has been accepted into the linux kernel (v5.4?)
