### ISSUE TITLE
GUI : FED : Firmware - Update to use Singe image upload with current design

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1325]
## Use Case
As an IBM lab team member, I need to be able to use the single file image upload to test upcoming systems prior to the release upstream.

## Overview
We have a new design to accommodate single image upload. That design will take some time to implement. We need a way to help the IBM lab test/use the single file image update quickly.

## Expectations
If this takes more than 2 days effort, it is not worth the effort and we should prioritize the implementation of the new design for double and single image.

## Requirements
1. Use the existing design to accommodate the IBM labs team.
    - API call will not change and does accept the single image of host and bmc firmware
    - Get image develop and test with from @anoo1 
2. Only show one upload section and update title to be clear to the user what they are updating
    - Replace BMC with Firmware
3. Show both the BMC and Server Firmware version info

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/deca55ac-32d2-498d-8e88-67bce7e882b8)

**Comment by yoshiemuranaka** [comment]
@derick-montague who is the backend I should be working with? I also need an image to test with

**Comment by derick-montague** [comment]
@gtmills - this was the temporary story. It's in a driver for test. Rather than changing the milestone, should we close it?

**Comment by gtmills** [comment]
@derick-montague yes
