### ISSUE TITLE
GUI : FED : Create reusable card component

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#1326]
## As Is

New component

## To Be

Card component should have a header and optionally a body.

The header background color can change to show status (grey, red, green)

![Screen Shot 2019-10-24 at 6.59.16 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/d1fc0aca-0a10-4f3e-8eed-444db889cda9)

![Screen Shot 2019-10-24 at 6.59.12 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/720037ac-6e24-4ea9-b9ac-859b5fe276a0)

![Screen Shot 2019-10-24 at 6.59.09 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/993ce569-16e5-439d-9481-5d70cfd28c6a)

![Screen Shot 2019-10-24 at 6.59.01 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/d854b816-8ccf-461a-95f4-c80df01f8a0c)

![Screen Shot 2019-10-24 at 6.58.58 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/4dfb4429-0fea-4b3e-a297-152777a9d728)

![Screen Shot 2019-10-24 at 6.58.55 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/60d3a1b7-d8b0-4ed8-a9e7-032de487b137)

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/26666

**Comment by yoshiemuranaka** [comment]
Attempted to make a global reusable component but struggled with passing dynamic templates (AngularJS limitation)

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/26666 merged
