### ISSUE TITLE
xCAT-BMC Discovery

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#1327]
This is to ensure xCAT has the data it needs to discover the BMC.
See similar work for HMC here: https://github.com/ibm-openbmc/dev/issues/782

**Comment by joseph-reynolds** [comment]
We may want to be able to disable the BMC's Avahi service per https://github.com/ibm-openbmc/dev/issues/612, for example, after the BMC is discovered.

**Comment by ratagupt** [comment]
I am not getting, what we are addressing with this issue?
Is it that Xcat is not getting the avahi discovery data? This seems to me their env problem.
Avahi service should support dynamic enable/disable.. That needs to be done..

**Comment by joseph-reynolds** [comment]
The story to allow the BMC admin to enable and disable Avahi mDNS discovery is #612 
The default stays the same: enable Avahi mDNS discovery service.

**Comment by joseph-reynolds** [comment]
This was not needed for current systems.
