### ISSUE TITLE
PSU code update: do update on Witherspoon/Swift

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#1330]
This issue is a follow up of https://github.com/ibm-openbmc/dev/issues/1016 to track the effort to do PSU update on Witherspoon/Swift.

It shall provide the vendor-specific code to:
1. Check the pre-condition to see if it is ready to perform the PSU update;
2. Run the PSU code update process.

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/26825/2/tools/power-utils/updater.cpp#155

A previous discussion had indicated that all power supplies except the one being updated should be providing DC standby power to the system.

**Comment by mine260309** [comment]
From the gerrit comment:

>"Providing DC standby power" obviously cannot happen if the power supply has (or thinks it has) VIN_UV_FAULT, but I am not so sure that the VOUT_FAULT and INPUT_FAULT_WARN mean that it is not providing standby power.

That is something worth discussing...
There are cases when a PSU gets VIN/VOUIT fault: (say we have PSU0 and PSU1 in the system)
* If PSU0 itself is good and there really is no input, it is NOT safe to update PSU1, because PSU1 may have no input as well, and it depends on PSU0 to provide power during the update.
* If PSU0 firmware has bug and get such issue, it is NOT safe to update PSU1 either, due to the same reason as above.

So to *safely* update PSU, it is expected that "all other PSUs" should provide DC standby power.

I see someone mentions that "only one PSU providing DC standby power is OK", this may work in 4 PSU systems. But do we really want to take the risk in that case? Usually, the PSU firmware will be updated to all the PSUs in the system, so ideally all the PSUs are expected to have standby power.

**Comment by bjwyman** [comment]
The point of my last comment was that DC standby power could be good if VOUT_FAULT and/or INPUT_FAULT_WARN are on, well, at least that is what I was wondering.

DC standby power is likely NOT good if VIN_UV_FAULT is on, so checking that makes sense.

**Comment by derekhoward55** [comment]
> From the gerrit comment:
> 
> > "Providing DC standby power" obviously cannot happen if the power supply has (or thinks it has) VIN_UV_FAULT, but I am not so sure that the VOUT_FAULT and INPUT_FAULT_WARN mean that it is not providing standby power.
> 
> That is something worth discussing...
> There are cases when a PSU gets VIN/VOUIT fault: (say we have PSU0 and PSU1 in the system)
> 
> * If PSU0 itself is good and there really is no input, it is NOT safe to update PSU1, because PSU1 may have no input as well, and it depends on PSU0 to provide power during the update.
> * If PSU0 firmware has bug and get such issue, it is NOT safe to update PSU1 either, due to the same reason as above.
> 
> So to _safely_ update PSU, it is expected that "all other PSUs" should provide DC standby power.
> 
> I see someone mentions that "only one PSU providing DC standby power is OK", this may work in 4 PSU systems. But do we really want to take the risk in that case? Usually, the PSU firmware will be updated to all the PSUs in the system, so ideally all the PSUs are expected to have standby power.

I agree with the above, lets not risk it.  Even if there are 4 PSU, I think we should expect that ALL of the other PSU (not just "at least one other") are providing DC standby power.

Also, I think we should check with the ps owners to find out the best way to check for DC standby power.  I'll email them to get their advice.

**Comment by derekhoward55** [comment]
Here is what psu owner said:
"For the control supply, I would recommend register 0x80-bit 6 12VCS FAULT.  Also register 0xDE reads the 12VCS voltage on the PSU side of the ORing fet, there may be leakage, so would need to make sure the voltage was greater than some threshold, maybe 8v or so."

**Comment by mine260309** [comment]
Set blocked due to lack of stable PSUs.
When Rainier systems and PSUs are ready, this task could be updated to implement the function on Rainier.

**Comment by lxwinspur** [comment]
@mzipse 
Who will effort this issue on the Rainier system?
Or could we close this issue?

**Comment by mzipse** [comment]
We have de-prioritized this work for the time being.  When resources free up, we will revisit.

**Comment by mzipse** [comment]
Closing this.  There are no plans now to do PSU Updates on Witherspoon.
