### ISSUE TITLE
PSU code update: update PSU sensors functional state

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#1331]
As the [design doc](https://github.com/openbmc/docs/blob/master/designs/psu-firmware-update.md)
> During the update, the service shall set the related sensors to non-functional, and when the update is done, it shall set the related sensors back to functional.

This issue is to implement the above function to update the PSU related sensors' functional state.

**Comment by ChicagoDuan** [comment]
I used busctl to set the “Functional” property of the sensor to false, but it didn't work. I think there may be a place in hwmon to disable the setting, and I am working on it.

root@fp5280g2:/tmp# busctl introspect xyz.openbmc_project.Hwmon-1772350680.Hwmon1 /xyz/openbmc_project/sensors/power/psu0_pout |cat
NAME                                                  TYPE      SIGNATURE RESULT/VALUE                             FLAGS
org.freedesktop.DBus.Introspectable                   interface -         -                                        -
.Introspect                                           method    -         s                                        -
org.freedesktop.DBus.Peer                             interface -         -                                        -
.GetMachineId                                         method    -         s                                        -
.Ping                                                 method    -         -                                        -
org.freedesktop.DBus.Properties                       interface -         -                                        -
.Get                                                  method    ss        v                                        -
.GetAll                                               method    s         a{sv}                                    -
.Set                                                  method    ssv       -                                        -
.PropertiesChanged                                    signal    sa{sv}as  -                                        -
xyz.openbmc_project.Sensor.Value                      interface -         -                                        -
.MaxValue                                             property  x         0                                        emits-change writable
.MinValue                                             property  x         0                                        emits-change writable
.Scale                                                property  x         -6                                       emits-change writable
.Unit                                                 property  s         "xyz.openbmc_project.Sensor.Value.Uni... emits-change writable
.Value                                                property  x         750000                                   emits-change writable
xyz.openbmc_project.State.Decorator.OperationalStatus interface -         -                                        -
.Functional                                           property  b         true                                     emits-change writable
root@fp5280g2:/tmp# 
root@fp5280g2:/tmp# 
root@fp5280g2:/tmp# busctl set-property xyz.openbmc_project.Hwmon-1772350680.Hwmon1 /xyz/openbmc_project/sensors/power/psu0_pout xyz.openbmc_project.State.Decorator.OperationalStatus Functional b false
root@fp5280g2:/tmp# 
root@fp5280g2:/tmp# busctl introspect xyz.openbmc_project.Hwmon-1772350680.Hwmon1 /xyz/openbmc_project/sensors/power/psu0_pout |cat
NAME                                                  TYPE      SIGNATURE RESULT/VALUE                             FLAGS
org.freedesktop.DBus.Introspectable                   interface -         -                                        -
.Introspect                                           method    -         s                                        -
org.freedesktop.DBus.Peer                             interface -         -                                        -
.GetMachineId                                         method    -         s                                        -
.Ping                                                 method    -         -                                        -
org.freedesktop.DBus.Properties                       interface -         -                                        -
.Get                                                  method    ss        v                                        -
.GetAll                                               method    s         a{sv}                                    -
.Set                                                  method    ssv       -                                        -
.PropertiesChanged                                    signal    sa{sv}as  -                                        -
xyz.openbmc_project.Sensor.Value                      interface -         -                                        -
.MaxValue                                             property  x         0                                        emits-change writable
.MinValue                                             property  x         0                                        emits-change writable
.Scale                                                property  x         -6                                       emits-change writable
.Unit                                                 property  s         "xyz.openbmc_project.Sensor.Value.Uni... emits-change writable
.Value                                                property  x         750000                                   emits-change writable
xyz.openbmc_project.State.Decorator.OperationalStatus interface -         -                                        -
.Functional                                           property  b         true                                     emits-change writable
root@fp5280g2:/tmp#

**Comment by ChicagoDuan** [comment]
I used busctl to set the “Functional” property of the sensor to false, but it didn't work. I think there may be a place in hwmon to disable the setting, and I am working on it.
```root@fp5280g2:/tmp# 
root@fp5280g2:/tmp# busctl set-property xyz.openbmc_project.Hwmon-1772350680.Hwmon1 /xyz/openbmc_project/sensors/power/psu0_pout xyz.openbmc_project.State.Decorator.OperationalStatus Functional b false
root@fp5280g2:/tmp# busctl get-property xyz.openbmc_project.Hwmon-1772350680.Hwmon1 /xyz/openbmc_project/sensors/power/psu0_pout xyz.openbmc_project.State.Decorator.OperationalStatus Functional
b true
root@fp5280g2:/tmp# busctl introspect xyz.openbmc_project.Hwmon-1772350680.Hwmon1 /xyz/openbmc_project/sensors/power/psu0_pout |cat
NAME                                                  TYPE      SIGNATURE RESULT/VALUE                             FLAGS
org.freedesktop.DBus.Introspectable                   interface -         -                                        -
.Introspect                                           method    -         s                                        -
org.freedesktop.DBus.Peer                             interface -         -                                        -
.GetMachineId                                         method    -         s                                        -
.Ping                                                 method    -         -                                        -
org.freedesktop.DBus.Properties                       interface -         -                                        -
.Get                                                  method    ss        v                                        -
.GetAll                                               method    s         a{sv}                                    -
.Set                                                  method    ssv       -                                        -
.PropertiesChanged                                    signal    sa{sv}as  -                                        -
xyz.openbmc_project.Sensor.Value                      interface -         -                                        -
.MaxValue                                             property  x         0                                        emits-change writable
.MinValue                                             property  x         0                                        emits-change writable
.Scale                                                property  x         -6                                       emits-change writable
.Unit                                                 property  s         "xyz.openbmc_project.Sensor.Value.Uni... emits-change writable
.Value                                                property  x         750000                                   emits-change writable
xyz.openbmc_project.State.Decorator.OperationalStatus interface -         -                                        -
.Functional                                           property  b         true                                     emits-change writable

```

**Comment by mine260309** [comment]
The functional state is "recovered" by hwmon service when the reading is OK, so it is set back to true after you modified the `Functional` state.

Probably it's not a problem because typically the update tool will unbind the PSU driver, and then the hwmon service will quit, and the sensors will be gone on DBus; after the PSU is updated, the driver will be bind again, the hwmon service will restart, and the sensors will be created on DBus again.

**Comment by ChicagoDuan** [comment]
> The functional state is "recovered" by hwmon service when the reading is OK, so it is set back to true after you modified the `Functional` state.
> 
> Probably it's not a problem because typically the update tool will unbind the PSU driver, and then the hwmon service will quit, and the sensors will be gone on DBus; after the PSU is updated, the driver will be bind again, the hwmon service will restart, and the sensors will be created on DBus again.

You are right. When the update tool unbind the PSU driver,  the value of the PSU sensor will change to `Disable`. So this is not an issue, close it.
```
psu0_pin         | B2h | ns  | 10.13 | Disabled
psu1_pin         | B3h | ns  | 10.14 | Disabled
psu0_pout        | B4h | ns  | 10.15 | Disabled
psu1_pout        | B5h | ns  | 10.16 | Disabled
psu0_vin         | B6h | ns  | 10.17 | Disabled
psu1_vin         | B7h | ns  | 10.18 | Disabled
psu0_vout        | BAh | ns  | 10.21 | Disabled
psu1_vout        | BBh | ns  | 10.22 | Disabled
```
