### ISSUE TITLE
Support for "System" version purpose

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#1334]
- [ ] Set the version purpose to "System" during the build process if the host-fw package is included.
- [x ] BMC Updater: Preserve the version purpose so that after reboot it restores the purpose value to BMC or System.
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/27045
- [ ] PNOR Updater: Create writable directories in /var if version is System which means a combined image was updated.
- [x ] Add support in bmcweb to correlate the System purpose to a BMC/Host version in redfish.
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/27144
- [ ] Handle ApplyTime

**Comment by bradbishop** [comment]
> On Oct 31, 2019, at 2:06 PM, Adriana Kobylak <notifications@github.com> wrote:
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Can you elaborate a little on the conditions in which this new enumeration is used?

It would be great to see this problem-to-be-solved announced on the list:

“How can we package and deploy multiple firmware images types?”

**Comment by anoo1** [comment]
> Can you elaborate a little on the conditions in which this new enumeration is used? It would be great to see this problem-to-be-solved announced on the list: “How can we package and deploy multiple firmware images types?”

Yeah, that's a good point. Sent this to the list: https://lists.ozlabs.org/pipermail/openbmc/2019-November/019411.html

**Comment by gtmills** [comment]
from https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/W5d74d2bb8660_4d6e_9bb6_08e4fc6ff375/page/OpenBMC%20Design%20Reviews


    ​​​​​​​Can we indicate that the image points at both the bmc and the system?  E.g. SoftwareInventory.RelatedItem?

**Comment by derick-montague** [comment]
Updated milestone based on [October feature sync meeing](https://ibm.box.com/s/g5jveq2vo3dba6chljjzvkcq7b58646u)

**Comment by mzipse** [comment]
Planning to stick with our current implemetnation for GA1.  Deferring to GA2.

**Comment by anoo1** [comment]
No plans to support this.
