### ISSUE TITLE
Adding pre-req service in  obmc-dump-monitor service 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1343]
obmc-dump-monitor service should start only after successful start of  systemd-coredump@.service. This will enable auto disable feature incase coredump is disabled.

Proposed fix ,  Add  "Requires=systemd-coredump@.service" in obmc-dump-monitor@.service

**Comment by devenrao** [comment]
Fix is uploaded here and is merged.
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/27010
