### ISSUE TITLE
MPIPL/SystemDump: Dump offload to an external tool.

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#1346]
This epic connects the internal milestones from various eBMC teams for transferring the system dump from host memory to an external storage.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
This functionality has been implemented via commit https://github.com/openbmc/openbmc-tools/commit/d8be0b43f8a660c3401d409493497de4b8fc7460#diff-abcc9e29a8b2603519591fd9074adf5f.

**Comment by ratagupt** [comment]
@dhruvibm Do you have something more here?

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
System dump offload has been done through openbmctool script.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
