### ISSUE TITLE
Implement PLDM host soft off requester application

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1351]
- Functionally this should be similar to phosphor-softpoweroff. Currently phosphor-softpoweroff is too tied up to IPMI. Hence it's probably better to write a new PLDM requester app. The app can sit in the pldm repo. Like phosphor-softoff, it should trigger a host soft off and wait for a certain time. Post that time it should check if the host acked the softoff (via sending a chassis off request), if not, it should report an error.

- The app has to send a PLDM request message to set a state effecter on the host (that represents the host power effecter). The app should be configurable in terms of providing the soft off timeout, MCTP eid, effecter id, and state value. The app will eventually have to use a PDR if the host firmware implements it to determine the state effecter for host soft off, but that is outside the scope of this story.

- The requester API, which this app will have to use, will be merged soon - https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/26057/. This commit also has an example utility which does a set state effecter.

- https://github.com/openbmc/openbmc/blob/master/meta-phosphor/recipes-phosphor/ipmi/phosphor-ipmi-host/xyz.openbmc_project.Ipmi.Internal.SoftPowerOff.service will have to be replaced to call the pldm app, but we need to figure out (hopefully via some community discussion) on how we'll let systems choose the ipmi soft off vs pldm soft off. Note that @vishwabmc (who implemented most of the ipmi soft off) and I talked if we could rewrite phosphor-softoff to have common aspects and branch out to ipmi/pldm based on the inband host protocol for a system, but currently that seems impracticle to do, given how much phosphor-softoff is IPMI specific.

**Comment by vishwabmc** [comment]
Adding some technical info ( today's implementation ) that could help

Building blocks:

`phosphor-softoff`
    --> Starts and sends IPMI SMS_ATN to host
    --> Exposes D-Bus API to reflect how did host react to it
    
`Host`
    --> Ack's SMS_ATN by sending GetMsgFlags IPMI command
    
`phosphor-host-ipmid`
    --> Receives GetMsgFlags IPMI command and responds.
    See https://github.com/openbmc/phosphor-host-ipmid/blob/5aa2693770ea4bb17eb581ab9d5274e7a1edf862/systemintfcmds.cpp#L23
    
    Note: This is the same path used for sending soft power off and sending a cmd to reset the OCC's.  So the new interface needs to be generic
    
    See: host-cmd-manager.hpp/cpp, host-interface.hpp/cpp
    
    If the response sent as part of Get_Msg_Flags is Soft_off, then, Host will go
    ahead with shutting down the partitions.
    
    IPMI then receives Chassis_Off when the partitions are down: 
    https://github.com/openbmc/phosphor-host-ipmid/blob/master/chassishandler.cpp#L1120

**Comment by vishwabmc** [comment]
When I was talking to Deepak, my preference was do it all new and not kind of plug something into the existing codebase. But just want to make sure that we have a common framework that we can use to sent the soft-off or a OCC reset commands upwards.

In the current design,  ipmid/host-interface.hpp/cpp abd host-cmd-manager.cpp provides this layer.

**Comment by mine260309** [comment]
One question about this task: is it supposed to replace the ipmi soft-off function, or is it to add a function for soft off with PLDM?

The reason I ask is:
* If it is to replace the ipmi soft-off, the host needs to be changed as well, so we need to "design" a protocol between BMC and host on PLDM
* If it is to add a function for soft off with PLDM, them PLDM could just invoke a host off request to host state manager, and the soft-off is still performed by `xyz.openbmc_project.Ipmi.Internal.SoftPowerOff.service`

**Comment by vishwabmc** [comment]
@mine260309 This would be all the new parallel implementation using PLDM for soft off. 

We would like to have the IPMI soft off *as is*  since others are using that feature.

**Comment by mine260309** [comment]
Then I think we should involve host guys for discussion because there should be a contract between BMC and host, what do you think?

**Comment by dkodihal** [comment]
This is going to be a standard PLDM effecter on the host, which can be fetched via the host PDR. That's basically the host protocol/contract to turn it off.

**Comment by mine260309** [comment]
@dkodihal So BMC will be a PLDM requester to send the request to host, is it?
Do we have existing code for BMC to send requests to host? I thought we currently only have responder code.

And do we have existing code for BMC to get PDR from host and so it could use the set-effecter API?

**Comment by vishwabmc** [comment]
@mine260309 BMC will be a PLDM requester : Yes
I remember Deepak mentioning the requester code being ready.. See.. https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/26057/

**Comment by dkodihal** [comment]
> Do we have existing code for BMC to send requests to host? I thought we currently only have responder code.

Here's an example requester app. @spinler is also working on a PEL daemon that will act as a PLDM requester.

> And do we have existing code for BMC to get PDR from host and so it could use the set-effecter API?

Not yet, that will be implemented by a different story. I wouldn't consider that a bloxker for this thought - if via this we can make the setEffecter call with a hard-coded/predetermined effecter id for a certain host stack, then adding additional code to get that via PDR can be incrementally added to this app.

**Comment by mine260309** [comment]
So basically this task involves:
1. An app that invokes set effecter to host to ask for soft power off;
2. It shall wait for a time that is configurable;
3. If the host acks the soft off, the app could turn off the chassis power;
4. If the host does not ack within the time, the app should log an error.

* In the above 3, how does host acks the soft off?
* In the above 4, should the app turn off the chassis after it logs the error?

**Comment by vishwabmc** [comment]
@mine260309 On

 `If the host acks the soft off, the app could turn off the chassis power;`
> I don't believe that is the case. All the partitions need to shutdown and then the host will send us a chassis PowerOff command.

**Comment by mine260309** [comment]
> I don't believe that is the case. All the partitions need to shutdown and then the host will send us a chassis PowerOff command.

By "host will send us a chassis PowerOff command", do you mean host really will send a "chassis off"
 command by PLDM, or it sends a "ack" that it is safe to chassis off?

The reason I ask is because with ipmi soft-off, the host only "ack" that, and BMC will turn off chassis power when it receives the "ack". There is no such a "chassis off command" from host in ipmi (correct me if I was wrong)

**Comment by vishwabmc** [comment]
> The reason I ask is because with ipmi soft-off, the host only "ack" that, and BMC will turn off chassis power when it receives the "ack". There is no such a "chassis off command" from host in ipmi (correct me if I was wrong)

@mine260309 Host does send the chassis-off after the partitions are shutdown. I have put the current flow at the top. Please let me know if you have any questions on that.

**Comment by mine260309** [comment]
> Host does send the chassis-off after the partitions are shutdown. I have put the current flow at the top. Please let me know if you have any questions on that.

OK, so what exactly is the "chassis-off", is it PLDM command? Is it already implemented or not?

**Comment by vishwabmc** [comment]
@mine260309 It would be some sort of PLDM thing. I will let @dkodihal respond to that

**Comment by dkodihal** [comment]
> OK, so what exactly is the "chassis-off", is it PLDM command? Is it already implemented or not?

It's a PLDM set effecter by the host to control the chassis power - it's implemented already.

**Comment by mine260309** [comment]
So here is what the application should do:
1. Send a set effecter to host to trigger host soft off.
   -> Do we have known effecter id and state value for host soft off?
2. Start a configurable timer to force power off
3. If host ack the off, it invokes set effecter to BMC for chassis-off;
   -> Does the chassis-off effecter directly trigger BMC to chassis-off?
      If yes, then the application should register a watch for chassis state, and stop the timer when chassis becomes off.
      If no, what D-Bus object/interface/property does the chassis-off effecter maps to?
4. If the timer expires, BMC does the chassis-off and it forces shutdown the power.

@dkodihal @vishwabmc Could you please comment on the above steps and questions?

**Comment by vishwabmc** [comment]
I feel that we need to still have the power off operations to be a set of .service files.

Example: The power-off will have this soft-off + chassis off

So, in my view: the new application will :

- Set the effector so the Host knows it's a soft off
- BMC needs to wait ( some quick timer etc ) for Host ack indicating the acceptance of soft-off
    - or is it part of setting the effector ?
- If the soft off is accepted, then BMC will start a new configurable timer
- If the timer expires, the soft-off app will exit, thus letting the chassis-off to take over
- If host finishes shutting down, we need to exit the app ( how can this be plugged in ) ?
    - or does the host set an effector to do chassis off explicitly ?

**Comment by geissonator** [comment]
One thing I don't like about our current design is how we dual-use the chassis off. It can be sent by a external user to indicate they want a chassis off. It's also used by the host to indicate it has completed the soft power off.  https://lists.ozlabs.org/pipermail/openbmc/2020-February/020534.html is my summary of this issue. Could we have a specific PLDM command that the host sends down to indicate they have completed their soft shutdown? That command could be routed to the soft-off application so it knows to exit and allow the power down target to continue.

**Comment by mine260309** [comment]
> Could we have a specific PLDM command that the host sends down to indicate they have completed their soft shutdown? That command could be routed to the soft-off application so it knows to exit and allow the power down target to continue.

I just read this comment, and it is very good suggestion.
@dkodihal Do you think we could have two different "effecters" for Host, one for chassis-off, the other for "host is off, it's safe to chassis-off"? If yes, how do you map the latter to the D-Bus object?

**Comment by dkodihal** [comment]
> @dkodihal Do you think we could have two different "effecters" for Host, one for chassis-off, the other for "host is off, it's safe to chassis-off"? If yes, how do you map the latter to the D-Bus object?
@mine260309 I think "host is off, it's safe to chassis-off" will be a PLDM event sent by the host, and not an effecter. @tomjoseph83 is designing event infrastructure now. We should be able to map PLDM events to something on D-Bus. There are two possibilities:
- Map a PLDM event to a D-Bus change, in this case the D-Bus object is owned by some other app, for eg the soft-ff app. This is what @tomjoseph83 is designing/implementing now.
- A problem with the above is it mandates something on D-Bus, and that something has to be hosted by another app as a D-Bus server. Another alternative is to have the PLDM daemon fire D-Bus signals (that other apps that are not D-Bus servers can catch). This signal can have PLDM specifics and/or use-case specifics (host graceful off).

**Comment by mine260309** [comment]
> Map a PLDM event to a D-Bus change, in this case, the D-Bus object is owned by some other app, for eg the soft-ff app. This is what @tomjoseph83 is designing/implementing now.

It looks good.
Does the PLDM event require a backend D-Bus object? If not, it's flexible that we could either map it to a D-Bus object or send a signal (though this may be lack of documentation...)
^ @tomjoseph83

**Comment by tomjoseph83** [comment]
@mine260309 The PLDM event falls into different categories like Sensor, Effecter, PDR change etc. For the PLDM events pertaining to sensors and effecters the plan is to have a D-Bus backend and PLDM daemon will update it.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ChicagoDuan** [comment]
@dkodihal  Hi dkodihal,I am developing the task of PLDM host soft off, https://github.com/ibm-openbmc/dev/issues/1856. I need to send a set effecter to host to trigger host soft off, can you give me effect_id, mctp_eid and json file? thanks.

**Comment by dkodihal** [comment]
@mine260309 @ChicagoDuan : I Wanted to capture the end-to-end flow once again here. This involves processing of Host provided PDRs as well, which is outside of the scope of this issue. Until the host firmware provides that, we would have to work with hard-coded sensor/effecter ids.

1) BMC gets host fiwmare's PDRs. BMC exposes this information on D-Bus, or some other way. These PDRs would help in the following ways :
- given a PLDM entity (DSP0248) and PLDM state set (DSP0249), fetch the sensor/effecter id. Needed to be able to send up sensor/effecter commands from the BMC up to the host, for eg 2)
- given a sensor/effecter id, fetch the PLDM entity and PLDM state set information. Needed to understand sensor/effecter events from the Host, for eg 3)

2) Set an effecter on the host firmware to trigger host soft off. Until we can get the effecter id from host PDR (not scope of this issue), use the following information for hard-coding : effecter id = 3, effecter value = 5. Also look at https://github.com/openbmc/pldm/blob/master/utilities/requester/set_state_effecter.cpp, this utility does something similar.

3) The new app has to block the power down target until it can receive a PLDM event msg from the host firmware. If host PDR info is accessible, then we would have retrieved from the PDR based on the sensor number the entity and state info, and would have mapped that to a D-Bus call to be made (this is the part @tomjoseph83 is working on). In this case I don't think a D-Bus call needs to be made by the app anyway, it just needs to unblock the power down target. An alternative here (if PDR info is not available from host) is to hard-code the sensor again : if sensor id in event == some known value, then take an action.

4) Host firmware will set an effecter on the BMC to request chassis off. This works today already.

**Comment by geissonator** [comment]
> @mine260309 @geissonator Is the plan to do the obmcutil integration (which also means co-existence of IPMI and PLDM soft-off apps, and obmcutil should somehow choose) as part of this story as well?

Currently this is all driven via a systemd target and services. https://github.com/openbmc/phosphor-host-ipmid/blob/master/xyz/openbmc_project/Ipmi/Internal/SoftPowerOff.interface.yaml is the D-Bus API that the code in https://github.com/openbmc/phosphor-host-ipmid/tree/master/softoff implements. 

Ideally we would have this application support both IPMI and PLDM. It could call both shutdown interfaces (IPMI and PLDM) and then require PLDM and IPMI to call back it's interfaces indicating host acknowledgement and then shutdown completion. It would operate under the assumption that the host will only respond to one of the paths and once one successful response occurs it could ignore the other path.

It would be good to get the D-Bus API out of the Ipmi service path and make them more generic. Only other option I could see is making the code smart enough to detect if it's IPMI vs. PLDM but that could be difficult. Hostboot moves to PLDM at some point, OPAL moves at some point... differentiating what code is running could be difficult so seems best to just try both.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by tomjoseph83** [comment]
### Preface

The pldm soft-off application will be used for two use cases: 
1. Graceful shutdown of the host 
2. Graceful reboot of the host.

The systemd target file will take care of powering off the chassis in the case of graceful shutdown after the host has been shutdown. Similarly in the case of graceful reboot the target file will take care of starting the host again without powering off the chassis.

IBM systems have multi-stage firmware like HB(Hostboot) and PHYP/OPAL. Depending on the stage of booting, the graceful shutdown request needs go to hostboot or to the PHYP. So soft-off application will depend on the availability of the host PDR's to make this distinction.

### PLDM Model

PHYP and HB will implement a state effecter (that the BMC can set to trigger graceful shutdown) and corresponding state effecter PDR. 

 **HB State Effecter** :

- Entity Type : 31 ( System Firmware)
- State Set ID : 129 ( Software Termination Status) 
- Supported states: 5 (Graceful Shutdown Requested)

**PHYP State Effecter** :
- Entity Type : 33 (Virtual Machine Manager)
- State Set ID : 129 ( Software Termination Status) 
- Supported value : 5 (Graceful Shutdown Requested)

PHYP and HB will implement a state sensor indicating the state of the shutdown request. When the shutdown is complete, host will send a PlatformEventMessage to BMC with the event type sensorEvent.

 **HB State Sensor** :

- Entity Type : 31 ( System Firmware)
- State Set ID : 129 ( Software Termination Status) 
- The event state in PlatformEventMessage command will be 7 (Graceful Shutdown - The software entity has been shut down gracefully. )

**PHYP State Sensor** :
- Entity Type : 33 (Virtual Machine Manager)
- State Set ID : 129 ( Software Termination Status) 
- The event state in PlatformEventMessage command will be 7 (Graceful Shutdown - The software entity has been shut down gracefully. )

### Implementation Details :

- In contrast with IPMI soft-off application, pldm soft-off application will not expose a D-Bus interface to expose the life cycle of the application. There is no usecase for a D-Bus interface.
- Systemd service to start the pldm soft-off application.

- Start the graceful shutdown
    -  Check if the `CurrentHostState` is `Running` https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/State/Host.interface.yaml before issuing SetStateEffecterStates command
    - The State Effecter PDRs can be found using the D-Bus method FindStateEffecterPDR. This will be implemented by the PLDM daemon. https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/31774
   - If no matching PDRs are available, return from the application.
   - If PHYP state effecter is available, then issue SetStateEffecterStates using effecterID of PHYP, otherwise use the effecterID of HB.
   - Use `pldm_send` API instead of `pldm_send_recv` because there could be a window where host is transitioning from HB to PHYP and  `pldm_send_recv` can hang. Use `pldm_recv` to read the response of SetStateEffecterStates command.

- Completion of graceful shutdown
    - Define and implement a D-Bus interface `xyz.openbmc_project.PLDM.SensorEvent` which emits a signal with `TID, sensorID, sensorOffset, eventState, previousEventState`. This can be the default behavior for a PlatformEventMessage sensorEvent along with the action to set D-Bus property. An additional handler needs to be added for the eventType sensorEvent.
    - Define and implement FindStateSensorPDR in the PLDM daemon for soft-off application to lookup HB & PHYP state sensors.
   - pldm soft-off application will set a D-Bus signal match for `xyz.openbmc_project.PLDM.SensorEvent` with watch for HB and PHYP state sensor information.

**Comment by lxwinspur** [comment]
merged by:
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/30152
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/30153
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/31507

**Comment by rfrandse** [comment]
refresh
