### ISSUE TITLE
pldmtool: fixup command line options

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1352]
`pldmtool -c GetPLDMTypes` works but `pldmtool --command GetPLDMTypes` doesn't. Also the `raw` option should be passed in as `-r` or `--raw`, and not just `raw`. It looks like pldmtool doesn't effectively use CLI11. This issue is to fixup pldmtool to enable passing in command line args as regular linux CLI.

**Comment by lxwinspur** [comment]
fix command line
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27011
