### ISSUE TITLE
 Implement PLDM responder to read a PEL

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1354]
In the ReadFileByTypeIntoMemory handler, add support for the file type PEL. In the PELHandler, add code to read a PEL (via D-Bus API), given a PEL id. The PEL id will come in as an input to ReadFileByTypeIntoMemory.

Write unit test(s).

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27369

**Comment by dkodihal** [comment]
Done by 2da1bfea011a5419e4bf0a5bbc62fc51671b96e1
