### ISSUE TITLE
PLDM: Implement reading PERM/TEMP LIDs

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1355]
As an extension to https://github.com/ibm-openbmc/dev/issues/1190, add the ability to read both perm and temp LIDs. They would have the same name, but would be stored at different locations.

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/26513

**Comment by dkodihal** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/25932/
