### ISSUE TITLE
GUI : FED : Update loading icon

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#1356]
## As Is
Current loading implementation does not use an icon svg.

## To Be
Update existing loader icon with carbon icon. 

https://www.carbondesignsystem.com/components/loading/code#loading

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/27325

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/27325 merged
