### ISSUE TITLE
Upstream Event logs Properties to Redfish 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1358]
Have properties like that we should try to get into the Redfish Spec: 
```
        {
          "EventID" : SRC or LC CommonEventID
          "EventNumber": <logPosition>,
          "FruList": [
          (FruDesc: Location)
         ],
         "Serviceable": True or False,
         "Resolved": True or False,
         "UpdatedTime" : <timestamp>,
         "EventType": < 1 of EventTypes>,
          "AffectedSubsystem": <Take from PEL or PolicyTable>,
          "RawData": Pointer to rawData as hex (PEL or eSEL),
         "CallHome": True or False,
         "Notified": [
           <UUIDr>: True or false
         ], 
```

**Comment by gtmills** [comment]
Justin submitted a proposal here: https://members.dmtf.org/wg/Redfish/document/53862 
To present 2/18

**Comment by gtmills** [comment]
Active / Modified have been approved just need to do the work.

**Comment by gtmills** [comment]
Resolved will be in 2020.4

**Comment by derick-montague** [comment]
@gtmills do we know when this will be ready? @Srisuk looking for the properties so she can work on #2201

**Comment by gtmills** [comment]
IPS is working on https://github.com/ibm-openbmc/dev/issues/1827 
I am hoping it is this month after we move to 2020.4

**Comment by gtmills** [comment]
As for the other properties, Matt is talking at the SEET meeting next week and depending on that is what we will upstream

**Comment by gtmills** [comment]
Matt and I are presenting tomorrow about adding 

```
"AutomatedServiceNotify": "Whether the event is a candidate to be sent to the service provider, if the sending service is enabled"
<true/false>

"RecommendedActions": "Recommended actions to take to address the LogEntry"
<array of Redfish messages>
```

**Comment by derick-montague** [comment]
> Matt and I are presenting tomorrow about adding
> 
> ```
> "AutomatedServiceNotify": "Whether the event is a candidate to be sent to the service provider, if the sending service is enabled"
> <true/false>
> 
> "RecommendedActions": "Recommended actions to take to address the LogEntry"
> <array of Redfish messages>
> ```

We don't have a design for showing an array of messages. This will require some rework once finalized.

**Comment by derick-montague** [comment]
@gtmills what was the outcome and the expectation for including these?
FYI: @ParishrutB @priyanka-pillai97 @sandeepasingh116

**Comment by gtmills** [comment]
This work is complete.
