### ISSUE TITLE
eBMC GUI : Configure - I/O Enclosures

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1359]
## Stakeholders
**SME**:

## Use Case
TBD

## InVision Prototype
TBD

## Design Issue (phosphor-webui)
TBD

## References/Resources
- [eBMC Feature Item: 4.10](https://ibm.ent.box.com/file/455779315260)
- feature discovery folder: 
- user research notes*: 
- user research synthesis: 

* This folder is restricted in accordance with GDPR guidelines.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by nicoleconser** [comment]
per Pete Heyrman: This function is not at all related to **I/O Adapter Enlarged Capacity**. I/O Adapter Enlarged Capacity allows users to set aside memory for better throughput/performance when running Linux.

**Comment by nicoleconser** [comment]
FYI @mzipse we are unsure of any back-end dependencies for this. Also unsure who the SMEs are.

**Comment by derick-montague** [comment]
@nicoleconser -We need to flag this in Mural. The milestone does not match between backend and our board.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
