### ISSUE TITLE
PFP::presence - Enable JSON runtime configuration

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1361]
- [x] Convert current YAML config to JSON
- [x] Create JSON class to construct similar format from generated YAML source
- [x] Parse input JSON file into new class structure
    - [x] Process fan entries from JSON file
    - [x] Process sensor entries from JSON file
    - [x] Construct policies from processed fan and sensor entries

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/27565

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/27565 merged
