### ISSUE TITLE
PFP::monitor - Enable JSON runtime configuration

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1362]
- [x] Create class from generated YAML source
- [x] Convert current YAML config to JSON
- [x] Parse input JSON file into new class structure

**Comment by msbarth** [comment]
Support for JSON configurations is complete under https://gerrit.openbmc-project.xyz/33526
Still working to add support for handling a SIGHUP to reload the JSON config

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/33762

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/33526

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/33526 merged
