### ISSUE TITLE
PFP - Add configure flag for JSON enablement

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1365]
Use a configure flag to enable the use of a runtime JSON config file for the fan applications. Each fan application should default to use a yaml compile time config unless this configure flag is given to enable using a JSON file at runtime(which requires support within each fan application before being able to be supported).

**Comment by bradbishop** [comment]
> On Nov 12, 2019, at 1:35 PM, Matthew Barth <notifications@github.com> wrote:
> 
> Use a configure flag to enable the use of a runtime JSON config file for the fan applications. Each fan application should default to use a yaml compile time config

You might consider making the default be what you prefer your users do going forward.

> unless this configure flag is given to enable using a JSON file at runtime(which requires support within each fan application before being able to be supported).

**Comment by msbarth** [comment]
But that would break everyone using yaml currently and I think it would be best to switch the default over to json once each fan app has been updated to support it.

I'm looking to add this flag now and then implement json support within each fan app. Once its implemented in each fan app, then the default could be switched over to be json based. I thought this was the correct way to go to handle backwards compatibility until the use of yaml could be deprecated?

**Comment by bradbishop** [comment]
> On Nov 12, 2019, at 6:40 PM, Matthew Barth <notifications@github.com> wrote:
> 
> But that would break everyone using yaml currently

Not if you add something like EXTRA_OECONF = “-—use-yaml” to the existing bbappends.

> and I think it would be best to switch the default over to json once each fan app has been updated to support it.

This sounds sensible, yes.

> I'm looking to add this flag now and then implement json support within each fan app. Once its implemented in each fan app, then the default could be switched over to be json based. I thought this was the correct way to go to handle backwards compatibility until the use of yaml could be deprecated?

Wouldn’t it be simpler to just add the flag after you’ve added the support to all the applications?

Is the flag for you or for your users?  If it is for your users, it probably makes the most sense to not even expose it until the function behind it is entirely implemented.  Once it is, add the option and make the json the default (and add EXTRA_OECONF) to the existing bbappends.

If it is for you while you develop the feature, make the option something like —-enable-experimental-json and leave it off by default while you are developing it.  Once the feature is done, rename the option —-enable-yaml and turn that off by default.

I’m just trying to provide a user's perspective.  Feel free to disregard if these ideas don’t make sense.

**Comment by msbarth** [comment]
> Not if you add something like EXTRA_OECONF = “-—use-yaml” to the existing bbappends.

So I got my hand slapped before for breaking users that had not upstreamed their configs when making a change that altered the yaml config format. Wouldnt that be the case here for those using `phosphor-fan-presence` but not have a bbappends upstream for their machine? What is the official openbmc direction on this?

> Is the flag for you or for your users?  If it is for your users, it probably makes the most sense to not even expose it until the function behind it is entirely implemented.  Once it is, add the option and make the json the default (and add EXTRA_OECONF) to the existing bbappends.

I see this being an eventual flag for users to use when transitioning their configs over to json under the current `phosphor-fan-presence` repo. But I believe switching the default to be json and having a `--enable-yaml` may be when `phosphor-fan-presence` is deprecated. I would eventually prefer to not support both yaml and json in the same repo due to all the config flags being in the code.

> If it is for you while you develop the feature, make the option something like —-enable-experimental-json and leave it off by default while you are developing it.  Once the feature is done, rename the option —-enable-yaml and turn that off by default.

At this time, this flag is for me and named it `--enable-runtime-json` and it will be merged to be supported per fan app as they are updated to use json configs at runtime.

To support backwards compatibility for those upstreamed or not while this functionality is being implemented, this seemed to be the best option to not affect anyone's use of the repo's apps while being worked.

**Comment by bradbishop** [comment]
> On Nov 13, 2019, at 11:39 AM, Matthew Barth <notifications@github.com> wrote:
> 
> So I got my hand slapped before for breaking users that had not upstreamed their configs when making a change that altered the yaml config format. Wouldnt that be the case here for those using phosphor-fan-presence but not have a bbappends upstream for their machine? What is the official openbmc direction on this?

Fair point.  No official direction - just to be cognizant of your users - which it sounds like you are.

> I see this being an eventual flag for users to use when transitioning their configs over to json under the current phosphor-fan-presence repo. But I believe switching the default to be json and having a --enable-yaml may be when phosphor-fan-presence is deprecated. I would eventually prefer to not support both yaml and json in the same repo due to all the config flags being in the code.
> 
> At this time, this flag is for me and named it --enable-runtime-json and it will be merged to be supported per fan app as they are updated to use json configs at runtime.
> 
> To support backwards compatibility for those upstreamed or not while this functionality is being implemented, this seemed to be the best option to not affect anyone's use of the repo's apps while being worked.

Agreed - sounds like a plan!

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/27549

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/28343 merged
