### ISSUE TITLE
Implement encode/decode (responder flow only) for FileAck

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1366]
Refer https://ibm.ent.box.com/file/392172076032 for the command structure.

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27373

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27373 merged
