### ISSUE TITLE
Redfish: Manager: "Manufacturer", "PartNumber", and "SerialNumber"

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1370]
"Manufacturer", "PartNumber", and "SerialNumber" were added to the 2019.4 standard Manager schema. 
See https://github.com/ibm-openbmc/dev/issues/480 and DMTF/Redfish#3727 for more information.

**Comment by gtmills** [comment]
Redfish 2019.4 has these properties

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/29302 moves us to 2019.4 

From 
[Redfish_Release_2019.4_Overview(1).pdf](https://github.com/ibm-openbmc/dev/files/4200432/Redfish_Release_2019.4_Overview.1.pdf)

![2019 4-overview-manager](https://user-images.githubusercontent.com/5455127/74468318-420a0000-4e60-11ea-81d3-0e20adbc0ec8.PNG)

**Comment by gtmills** [comment]
@ChicagoDuan @XiaochaoMa I think this should be a straight forward one

**Comment by ChicagoDuan** [comment]
> @ChicagoDuan @XiaochaoMa I think this should be a straight forward one

@gtmills Sorry，I am not following，can you describe it in detail，thanks.

**Comment by gtmills** [comment]
There should be some examples of getting properties like Manufacturer (e.g. for system) out on D-Bus 
https://github.com/openbmc/bmcweb/search?l=C%2B%2B&q=Manufacturer

The Redfish manager defines these new properties: https://redfish.dmtf.org/schemas/v1/Manager.v1_10_0.json

**Comment by ChicagoDuan** [comment]
Closed
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38606/5
