### ISSUE TITLE
PFP::presence - Use JSON file location from dbus

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1373]
Treat the JSON file location provided at configure time as the default configuration and add the ability to use a same/different JSON file location provided by a dbus object/interface/property that would take priority over the default configuration.

This allows fan presence to fall back to a default configuration when one is provided on a dbus object and the one expected on dbus may not exists (due to the service missing, etc.. of the application configured to provide that dbus object).

Essentially, fan presence will load the JSON provided at configure time and use that unless replaced by a JSON file provided on dbus.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/27827

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/27827 merged
