### ISSUE TITLE
PFP::monitor - Use JSON file location from dbus

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1378]
Treat the JSON file location provided at configure time as the default configuration and add the ability to use a same/different JSON file location provided by a dbus object/interface/property that would take priority over the default configuration.

This allows fan monitor to fall back to a default configuration when one is provided on a dbus object and the one expected on dbus may not exists (due to the service missing, etc.. of the application configured to provide that dbus object).

Essentially, fan monitor will load the JSON provided at configure time and use that unless replaced by a JSON file provided on dbus.

**Comment by msbarth** [comment]
Refer to https://github.com/ibm-openbmc/dev/issues/1639 for determining what object will provide the data necessary to load the system's fan monitoring JSON configuration file from.

**Comment by msbarth** [comment]
The ability to use a JSON config file location from dbus was included in #1362 and done in commit https://gerrit.openbmc-project.xyz/33521

Using this issue to enable the use of a JSON configuration file on the witherspoon machine.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/33934

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/33934 merged
