### ISSUE TITLE
PDM - Use JSON file location from dbus

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1379]
Treat the JSON file location provided at configure time as the default configuration and add the ability to use a same/different JSON file location provided by a dbus object/interface/property that would take priority over the default configuration.

This allows dbus monitor to fall back to a default configuration when one is provided on a dbus object and the one expected on dbus may not exists (due to the service missing, etc.. of the application configured to provide that dbus object).

Essentially, dbus monitor will load the JSON provided at configure time and use that unless replaced by a JSON file provided on dbus.

**Comment by bradbishop** [comment]
> On Nov 18, 2019, at 11:58 AM, Matthew Barth <notifications@github.com> wrote:
> 
> Treat the JSON file location provided at configure time as the default configuration and add the ability to use a same/different JSON file location provided by a dbus object/interface/property that would take priority over the default configuration.
> 
> This allows dbus monitor to fall back to a default configuration when one is provided on a dbus object and the one expected on dbus may not exists (due to the service missing, etc.. of the application configured to provide that dbus object).
> 
> Essentially, dbus monitor will load the JSON provided at configure time and use that unless replaced by a JSON file provided on dbus.

What do you think about this logic:

no configure time configurable behavior

when your program starts:

first, look for configuration data in /etc/phosphor-fan/<token>.conf (writeable, for thermal team to do overrides)
if nothing found, look for configuration data in /usr/share/phosphor-fan/conf/<token>.conf (read-only & to support systems without entity-manager)
finally, if nothing still found, look for configuration data in entity-manager (to support systems with entity-manager).

to re-trigger this logic, you can do:

kill -HUP <my-daemon-pid>
or 
systemctl reload <my-unit> (which just sends the sighup via pid file).

<token> would be whatever domain makes sense to you - maybe zones?

What is your plan for overrides through a code update (wrt persistency)?

**Comment by msbarth** [comment]
> no configure time configurable behavior

Without this, wouldn't it cause problems with the compile time yaml driven PDM since some users may not want to provide the ability to have PDM's config available on the BMC and possibly changed at runtime (which could be done by using yaml)?

> when your program starts:
first, look for configuration data in /etc/phosphor-fan/<token>.conf (writeable, for thermal team to do overrides)
if nothing found, look for configuration data in /usr/share/phosphor-fan/conf/<token>.conf (read-only & to support systems without entity-manager)
finally, if nothing still found, look for configuration data in entity-manager (to support systems with entity-manager).

When you say `configuration data in /etc/phosphor-fan/<token>.conf` is this still in json format or something else? This process path is basically what I had planned to implement in the fan code first before working on it over here in PDM.

> to re-trigger this logic, you can do:
kill -HUP <my-daemon-pid>
or
systemctl reload <my-unit> (which just sends the sighup via pid file).
<token> would be whatever domain makes sense to you - maybe zones?

Ack. Another possibility that I'd like to consider to re-trigger the logic to pick up changes/overrides would be a `propertiesChanged` signal in the case where the config file is provided on a property hosted by some other application (such as entity manager, etc..) This seems to be one way that the re-trigger logic could be externalized from logging into the BMC....still thinking this option thru.

> What is your plan for overrides through a code update (wrt persistency)?

Right now, overrides would not be persisted as they should only be intended for lab & debug use and not something relied on in the field.

**Comment by bradbishop** [comment]
I didn’t realize this was a PDM story - so I used phosphor-fan in my examples but you can s/phosphor-fan/phosphor-dbus-monitor/ ...

> On Nov 25, 2019, at 5:22 PM, Matthew Barth <notifications@github.com> wrote:
> 
>> no configure time configurable behavior
> 
> Without this, wouldn't it cause problems with the compile time yaml driven PDM since some users may not want to provide the ability to have PDM's config available on the BMC and possibly changed at runtime (which could be done by using yaml)?

I’m not sure.  Did you intend to support old yaml-style and new json-style in the same binary?  Would it be any simpler to just have two different binaries - one for yaml-style and one for json-style?  Could we reuse most of the code that already exists like that?  Not sure if this idea is any good or not..just thinking out loud.

You are correct that currently we don’t currently provide the possibility of configuration changes, and some users might value that ( I doubt it though ... do you like it? :-) ).  Integrators of PDM could still achieve that I think by setting the right permissions on the config file (writeable by root only).

>> when your program starts:
>> first, look for configuration data in /etc/phosphor-fan/.conf (writeable, for thermal team to do overrides)
>> if nothing found, look for configuration data in /usr/share/phosphor-fan/conf/.conf (read-only & to support systems without entity-manager)
>> finally, if nothing still found, look for configuration data in entity-manager (to support systems with entity-manager).
> 
> When you say configuration data in /etc/phosphor-fan/<token>.conf is this still in json format or something else? This process path is basically what I had planned to implement in the fan code first before working on it over here in PDM.

yep - json.  I would anticipate that users would copy the configuration from /usr/share/phosphor-fan/conf/<token>.conf to /etc/phosphor-fan/<token>.conf and then tweak it to apply their overrides.  How does that sound?

>> to re-trigger this logic, you can do:
>> kill -HUP 
>> or
>> systemctl reload (which just sends the sighup via pid file).
>> would be whatever domain makes sense to you - maybe zones?
> 
> Ack. Another possibility that I'd like to consider to re-trigger the logic to pick up changes/overrides would be a propertiesChanged signal in the case where the config file is provided on a property hosted by some other application (such as entity manager, etc..) This seems to be one way that the re-trigger logic could be externalized from logging into the BMC....still thinking this option thru.

That is an interesting thought.  I hadn’t considered how to do overrides with EM provided configs.  If the plan is to just have EM host the path to the config files, I would still suggest having users copy the configs out of /usr/share and into /etc.  If the plan is to have EM host the actual configuration and not just a pointer to it…invention required I think.  Maybe we could add support to entity manager overrides to entity manager itself. 

>> What is your plan for overrides through a code update (wrt persistency)?
> 
> Right now, overrides would not be persisted as they should only be intended for lab & debug use and not something relied on in the field.

Ok.  If you assume you only have a shared place (i.e. not deleted during code update) to store mutable data (/etc) for use by both your old and new application versions, how would implement this?

**Comment by msbarth** [comment]
> I’m not sure.  Did you intend to support old yaml-style and new json-style in the same binary?  Would it be any simpler to just have two different binaries - one for yaml-style and one for json-style?  Could we reuse most of the code that already exists like that?  Not sure if this idea is any good or not..just thinking out loud.

At this time, I do intend to support yaml & json in the same binary. I'm not sure either at this point if having separate binaries would be more beneficial or not for PDM, however as we discussed previously, my plan is to drop yaml in PFP when its renamed to `phosphor-fan`(PF). 
> You are correct that currently we don’t currently provide the possibility of configuration changes, and some users might value that ( I doubt it though ... do you like it? :-) ).  Integrators of PDM could still achieve that I think by setting the right permissions on the config file (writeable by root only).

So in my view of thermal safety, there are areas that I believe its beneficial to `not` allow users the ability to either knowingly or not knowingly make changes to the application configs that impact thermal control & safety. This is where I'm thinking I'll need to store more info if config changes would be possible in the chance that they are changed by an end-user so that its fully logged, etc.. in case a thermal even occurs possibly due to those changes... I do not agree with simply making the permissions on the config writeable only by root as that still gives someone the ability to do so (maybe I'm being over paranoid, but in the end I would need some way to log when config changes are applied and/or removed).
> yep - json.  I would anticipate that users would copy the configuration from /usr/share/phosphor-fan/conf/<token>.conf to /etc/phosphor-fan/<token>.conf and then tweak it to apply their overrides.  How does that sound?

Yes, that's what I figure will be the case as well.
> That is an interesting thought.  I hadn’t considered how to do overrides with EM provided configs.  If the plan is to just have EM host the path to the config files, I would still suggest having users copy the configs out of /usr/share and into /etc.  If the plan is to have EM host the actual configuration and not just a pointer to it…invention required I think.  Maybe we could add support to entity manager overrides to entity manager itself.

My initial plan is to have EM (or something else..) provide the location of the config file to the thermal applications. Users could place an override config in /etc (which the original does not necessarily come from /usr/share) but I was figuring why make an additional `hard-coded` check to /etc and just use whatever file location is provided on a dbus object. If the interface hosted by EM (or whatever else..) is writeable, then whether its a file location or the actual json config being provided on dbus, I could just do a `get` when the application starts and subscribe to propertiesChanged signals to see if it ever changes. It seems to me that this could handle multi-machine/single image support and the ability to override them all-in-one, do you see why it shouldnt be done like this? ...thinking more on it, it'd be nice if there was a switch that could be flipped when a BMC image is shipped to turn off the write ability to those dbus interfaces so that they can not be changed by an end-user. Thoughts?
> Ok.  If you assume you only have a shared place (i.e. not deleted during code update) to store mutable data (/etc) for use by both your old and new application versions, how would implement this?

I'm not that far yet in my thinking in regard to code updates. I guess it really depends on how things pan out with handling the configs with the use of EM or not and whether the ability to override them in the field is given. If overriding the configs are not possible in the field, I think the config & application are then just matched in the BMC image update...

**Comment by bradbishop** [comment]
> At this time, I do intend to support yaml & json in the same binary.

Ok.  My biggest concern is keeping things simple for both you and the users.

> So in my view of thermal safety, there are areas that I believe its beneficial to not allow users the ability to either knowingly or not knowingly make changes to the application configs that impact thermal control & safety.  

We can’t have this and give users the ability to do overrides can we?  Or are you thinking we’ll have lab only builds that allow overrides and ship level builds that don’t?

> This is where I'm thinking I'll need to store more info if config changes would be possible in the chance that they are changed by an end-user so that its fully logged, etc.. in case a thermal even occurs possibly due to those changes... I do not agree with simply making the permissions on the config writeable only by root as that still gives someone the ability to do so (maybe I'm being over paranoid, but in the end I would need some way to log when config changes are applied and/or removed).

Are you worried about lab users or customers?  Would you feel differently if the root account was deactivated on shipped products?

> My initial plan is to have EM (or something else..) provide the location of the config file to the thermal applications. Users could place an override config in /etc (which the original does not necessarily come from /usr/share) but I was figuring why make an additional hard-coded check to /etc and just use whatever file location is provided on a dbus object.

Because this is how most linux programs work and anyone looking to understand how your program works will have to un-learn that.

> If the interface hosted by EM (or whatever else..) is writeable, then whether its a file location or the actual json config being provided on dbus, I could just do a get when the application starts and subscribe to propertiesChanged signals to see if it ever changes. It seems to me that this could handle multi-machine/single image support and the ability to override them all-in-one, do you see why it shouldnt be done like this? ...thinking more on it, it'd be nice if there was a switch that could be flipped when a BMC image is shipped to turn off the write ability to those dbus interfaces so that they can not be changed by an end-user. Thoughts?

I’ll take a todo to find out if EM interfaces are writeable.  Can you remind me if I don’t get back to you?  If they are it seems like it would be easy enough to add a read-write or read-only attribute in the EM config files.

> I'm not that far yet in my thinking in regard to code updates. I guess it really depends on how things pan out with handling the configs with the use of EM or not and whether the ability to override them in the field is given. If overriding the configs are not possible in the field, I think the config & application are then just matched in the BMC image update...

Ok but this is what is driving all my questions.  I’m trying to make sure we can provide a coherent package upgrade experience.  We need to understand how that will work before a choice is made here.

**Comment by amboar** [comment]
> 
> So in my view of thermal safety, there are areas that I believe its 
> beneficial to `not` allow users the ability to either knowingly or not 
> knowingly make changes to the application configs that impact thermal 
> control & safety. This is where I'm thinking I'll need to store more 
> info if config changes would be possible in the chance that they are 
> changed by an end-user so that its fully logged, etc.. in case a 
> thermal even occurs possibly due to those changes... I do not agree 
> with simply making the permissions on the config writeable only by root 
> as that still gives someone the ability to do so (maybe I'm being over 
> paranoid, but in the end I would need some way to log when config 
> changes are applied and/or removed).
> 

Everything is open-source - you're not preventing anyone changing their
fan configs if they want to - they can always recompile and reflash. I feel
like preventing runtime configuration is just putting hurdles in the way of
people who are conscious that adjustments will potentially void their
warranty. OpenBMC should be useful to hacker/maker communities as
well as enterprise systems, and you're working on a generic component
of OpenBMC, so we need to factor in more than just IBM's requirements on
enterprise systems with respect to some of our customers.

In my ideal world we're better off providing documentation of the
operating thermal envelopes and how our systems are supported by the
existing fan profiles. This gives interested people the information they
need to choices that aren't catastrophic.

**Comment by msbarth** [comment]
>Everything is open-source - you're not preventing anyone changing their
fan configs if they want to - they can always recompile and reflash. I feel
like preventing runtime configuration is just putting hurdles in the way of
people who are conscious that adjustments will potentially void their
warranty. OpenBMC should be useful to hacker/maker communities as
well as enterprise systems, and you're working on a generic component
of OpenBMC, so we need to factor in more than just IBM's requirements on
enterprise systems with respect to some of our customers.

I know this and in the case a customer/user wants to recompile and reflash their BMC, they no longer run an IBM (or any other company using OpenBMC) signed image which voids possible support of that system that was characterized against what was in the signed image. I'm sure I stated it clearly that I want to keep the ability to keep a customer/user from altering the thermal config(s), either knowingly or not, in the BMC image provided on a purchased system. What they do with the BMC(reflash, etc..) after receiving the system is their choice but may void warranties and/or support of that system by doing so. Documenting the cause and effects of what is done to an OpenBMC based system in regards to these warranties and support contracts are outside my realm of developing the options that can be used to configure the thermal profiles.

**Comment by msbarth** [comment]
> We can’t have this and give users the ability to do overrides can we?  Or are you thinking we’ll have lab only builds that allow overrides and ship level builds that don’t?

Yes, I'm thinking we need in some form or another an ability to "lock out" the ability to do overrides or the ability to log each time an override is applied in the case that issues arise due to that override being applied in the field.

> Are you worried about lab users or customers?  Would you feel differently if the root account was deactivated on shipped products?

Customers. Yes, having the root account deactivate could be a form of "locking out" the ability for overrides...

>> My initial plan is to have EM (or something else..) provide the location of the config file to the thermal applications. Users could place an override config in /etc (which the original does not necessarily come from /usr/share) but I was figuring why make an additional hard-coded check to /etc and just use whatever file location is provided on a dbus object.

> Because this is how most linux programs work and anyone looking to understand how your program works will have to un-learn that.

So at this time, I'm attempting to really enable 3 ways for configuring the fan presence application that I intend to apply to the other related thermal applications. Each of these would be decided at configure time for the application
1. YAML - Compile time config, no override/runtime change supported
2. JSON-FILE(direct file based) - Configure time provided BMC location(possibly read-only) of json config file with an ability to override the json config with a file in /etc and sending a SIGHUP signal to reload the config(using what's in /etc first, otherwise what was provided at configure time).
3. JSON-FILE-DBUS(file based given over dbus) - Due to the size of the json configuration files, the ability to provide the json config file over dbus is also valuable for the case to support multi-machine configs within a single BMC image. In this case, the ability to do overrides would be over the same dbus path where a file could be placed in, say /etc, and then set the dbus property containing the location of the json config file and updating it on the dbus object itself. This would cause a propertiesChanged signal that the application could use to reload the config.

Of course, eventually I'd prefer to not have to support all of these possible configure time drive options but I'm at a loss to how to enable what is really needed for each use-case that is necessary when it comes to thermal related applications and their configurations. *AND in the case I've mentioned with "locking out" the override ability, 2 and 3 would need some other possible mechanism to provide this(i.e. root deactivated or enable read-only dbus objects?..).

> I’ll take a todo to find out if EM interfaces are writeable.  Can you remind me if I don’t get back to you?  If they are it seems like it would be easy enough to add a read-write or read-only attribute in the EM config files.

Will do...this relates to configure option 3 which I havent started working on yet within fan presence yet.

> Ok but this is what is driving all my questions.  I’m trying to make sure we can provide a coherent package upgrade experience.  We need to understand how that will work before a choice is made here.

That's fair...I think the main concern would be package upgrading where the configure option changes would result in dangling configs being left on the BMC. I still need to study thru the upgrade path and if these would result in other possible issues during an upgrade.

**Comment by msbarth** [comment]
The functionality that PDM provided has been integrated into the fan monitor application. At this time, PDM is looked at being deprecated, so this issue is not needed.
