### ISSUE TITLE
GUI : Design : Profile Settings (Change Password for ReadOnly & Operator Roles)

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1381]
The access is allowed as follows:
/redfish/v1/ - allowed by everyone
/redfish/v1/AccountService - only Admin
/redfish/v1/AccountService/Accounts - only Admin
/redfish/v1/AccountService/Accounts/{user} - only Admin and that user

Because of this ReadOnly and Operator Roles can not access the current User Management page, they get redirected to our forbidden page. They can change their own password, which is the experience we need to design for. 

## Stakeholders
**SME**:
@ratagupt 
@joseph-reynolds 
Should also run this by Richard from Intel.

## Use Case
TBD

## InVision Prototype
https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319407923_02-Profile-Settings-03

## Design Issue (phosphor-webui)
TBD

## References/Resources
SW474797

**Comment by joseph-reynolds** [comment]
FYA, saying the Admin has access to the account management pages is correct, but not _exactly_ correct.

Technically, any user who has the ConfigureUsers Privilege has full access to the account management URIs (GET, PATCH, POST, PUT, DELETE).  Also, any user who has the ConfigureManager Privilege has GET access to these URIs.  Currently in BMCWeb, only users who have the Administrator Role have these Privileges (per Redfish spec DSP0266).  Please note the situation may change when BMCWeb implements custom Roles and when BMCWeb implements the dynamic Role-to-Privilege mapping defined by the Redfish spec.  I think one of these is likely to happen.  At that point, the webui app would no longer be able to assume only the Admin can access the account management pages.

Details:

You can learn what Privilege is required for each operation from the Redfish Privilege Registry (document DSP8011).  The mapping between URIs defined by BMCWeb and the Redfish types used in the spec are as follows:
- AccountService at /redfish/v1/AccountService
- ManagerAccountCollection at /redfish/v1/AccountService/Accounts
- ManagerAccount (plural) at /redfish/v1/AccountService/Accounts/{user}

For example, the DSP8011 entry for ManagerAccount indicates the GET operation requires: ConfigureManager OR ConfigureUsers OR ConfigureSelf.  This means you need at least one of these privileges to be allowed to GET /redfish/v1/AccountService/Accounts/{user}.

Additionally, the ConfigureSelf Privilege has a special meaning ("Can change the password for the current user account and log out of their own sessions" per DSP0246).  The pending expired-password BMCWeb changes (https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25146) implement the correct ConfigureSelf behavior.  The PropertyOverrides (explained in DSP0266 and listed in DSP8011) detail how ConfigureSelf is used.  All of that detail is intended to support the meaning of the ConfigureSelf Privilege: Can change the password for the current user account and log out of their own sessions.

The Web App can learn what Privileges are associated with each User Role by (1) first looking up the User's Role from that user's ManagerAccount, and then (2) looking up the AssignedPrivileges for that Role in either /​redfish/​v1/​AccountService/​Roles/​{RoleId} or /​redfish/​v1/​Managers/​{ManagerId}/​RemoteAccountService/​Roles/​{RoleId}.

That's the Redfish way to get this information.  But I don't know if we need to implement that to support plans for custom Roles or dynamic Role-to-Privilege mapping.

**Comment by joseph-reynolds** [comment]
Anyway, the point of the above is to use language like: ... users who have the ConfigureUsers Privilege.... (instead of talking about: ...users who have the Admin Role...).

**Comment by ryanarnell** [comment]
We are skipping the implementation of requiring old password to change the current password as backend is not providing the required response needed. 
![main](https://user-images.githubusercontent.com/4976631/73487059-e02f9d80-436b-11ea-9322-908366517e04.jpg)

More info can be found here- https://github.com/ibm-openbmc/dev/issues/1530
