### ISSUE TITLE
Redfish: Support host firmware mode for dual boot system

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1383]
This story is to add the support to set the Host firmware mode.
We can use the system bios property which is a list of attributes.
One of the attribute would be the host firmware mode.

Need to add the firmware mode attribute in the phosphor-settings manager which can be read by the PLDM.

**Comment by mzipse** [comment]
Reassigning to @ratagupt for now.  Ratan can reassign once someone is ready to work on this.  Ratan, one question....  Is this story a dupicate of #1615

**Comment by ratagupt** [comment]
Yes @mzipse, I closed the 1615.

**Comment by ojayanth** [comment]
@mzipse  this is not required for Manufacturing D1 Milesteone.

**Comment by geissonator** [comment]
Per a discussion with Ratan, this is not a new Redfish API, it would just be a BIOS setting. There does not appear to be any requirement for this function currently though. Going to move this out from the Dual-boot epic. May want to move under https://github.com/ibm-openbmc/dev/issues/1977

**Comment by ratagupt** [comment]
@mzipse seems this is not immediate priority as we would not be supporting dual boot on Rainier.

**Comment by sunharis** [comment]
Adjusting the milestone as its not impacting GA1

**Comment by sunharis** [comment]
We are not going to support OPAL on IBM systems. Need to check if this is required? Will discuss with Dean and take an action.

**Comment by mzipse** [comment]
Closing this.
