### ISSUE TITLE
HMC-BMC : Lock: Write the test cases for the lockmanagement interfaces

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1385]
This story is to write test cases for lock management interfaces.
We need to write a good amount of test cases which almost covers all the conflicting/good scenario.

Once it is done we need to get the Test report reviewed by the management console team

**Comment by manojkiraneda** [comment]
Code is up for review : https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/27671

**Comment by manojkiraneda** [comment]
The code is already merged in master , and the hmc team is already consuming the lock infrastructure.
