### ISSUE TITLE
IPMI: IPMI FRU, Restriction Mode, LAN Access on/off NOT Working

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#1389]
This issue is to track getting Legacy function operational on FW1010 images
Test team results indicated this function was not working.

**Comment by mzipse** [comment]
@sampmisr , this was a carryover from WItherspoon OP940 release, ensuring that our OP940 functionality worked in eBMC.  Can you get someone on your squad to confirm whether this is resolved or not?.....the test team could probably tell you whether this is still an issue.  If resolved, please close.

**Comment by nmuruli** [comment]
We will get back on this

**Comment by gkeishin** [comment]
This hasn't worked since the time we tested on Tacoma but we can re-check and update it..

**Comment by rfrandse** [comment]
tracking in jira
