### ISSUE TITLE
LDAP group to role mapping

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#139]
This issue is opened to define an interface which the user can use to map LDAP group to a role. An application will implement the interface that allows the user to map LDAP group to privilege.

- [ ]  Define the interface for privilege mapper

- [ ] An application that implements the interface that allows the user to create mapping between LDAP group name to privilege.

- [ ] The mapper objects should be persisted.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
It is done, so closing it
