### ISSUE TITLE
Certificate: Response changed, Replace and CA certificate need debugging.

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#1392]
This issue is to track getting Legacy function operational on FW1010 images
Test team results indicated this function was not working.

**Comment by devenrao** [comment]
Please do a version bump for 1010 release, latest changes have been verified by Rahul and it looks good.

Some things to take note
1) Uploading certificate with same subject name and issuer name will throw not allowed error.
2) Replace of an expired certificate with same issuer name and subject name are allowed.

This checking is done to not to upload the same certificate again and again.

**Comment by devenrao** [comment]
Changes has been merged and the issue can be closed.
