### ISSUE TITLE
NTP: NTP configuration setting failed.

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#1393]
This issue is to track getting Legacy function operational on FW1010 images
Test team results indicated this function was not working.

**Comment by ratagupt** [comment]
need more info on this what is failing.

**Comment by gkeishin** [comment]
Other NTP config are working except  **NTPEnabled**

```
KEYWORD Redfish . Patch ${REDFISH_NW_PROTOCOL_URI}, body={u'NTPEnabled': ${True}}
Start / End / Elapsed:	20200124 23:44:43.473 / 20200124 23:44:43.643 / 00:00:00.170
23:44:43.488	INFO	Attempt 1 of /redfish/v1/Managers/bmc/NetworkProtocol	
23:44:43.629	INFO	Response Time to /redfish/v1/Managers/bmc/NetworkProtocol: 0.0 seconds.	
23:44:43.643	FAIL	ValueError: The HTTP status code was not valid:
status:                                           400
valid_status_codes:
  [0]:                                            200
```

**Comment by mzipse** [comment]
Feedback from Ratan:
NTP is working fine in latest master and is included in FW1010 branch.
There may be some confusion with the test team: NTP works in FW1010 but there is a different redfish url.  @ratagupt can you provide @gkeishin with details and then we can close this.

I guess we have to decide whether this redfish url change should be backported to OP940.

**Comment by gtmills** [comment]
This had me worried. So tested and worked for me on a recent master. 
```
curl -k-v  -X PATCH https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol -d '{"NTP":{"ProtocolEnabled": false}}'
```
```
curl -k-v  -X PATCH https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol -d '{"NTP":{"NTPServers":["1.1.1.1"]}}'
```

Can see both of these set at 

```
 curl -k https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol
...
  "NTP": {
    "NTPServers": [
      "1.1.1.1"
    ],
    "ProtocolEnabled": false
  },
```

My vote is we don't backport to OP940 and close this issue. 
@mzipse @gkeishin @ratagupt Can we close?

**Comment by mzipse** [comment]
I'm good with that.  Closing.
