### ISSUE TITLE
Power(Voltage): Power Voltage Readings looks good but missing  MaxConsumedWatts and EfficiencyPercent properties

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#1394]
This issue is to track getting Legacy function operational on FW1010 images
Test team results indicated this function was not working. 

Power Voltage Readings looks good but missing MaxConsumedWatts and EfficiencyPercent properties. Need automation fix for Ambient Temperature.

**Comment by msbarth** [comment]
FWIW -> https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24002

**Comment by bjwyman** [comment]
EfficiencyPercent is showing up in latest builds, 90.

**Comment by bjwyman** [comment]
Okay, not quite sure how this blocks #1709. I think the MaxConsumedWatts (possibly moved or renamed in Redfish) is (supposed to be) coming down to the BMC via OCC polling ... total_power.

**Comment by bjwyman** [comment]
Did we end up with just a PR in ibm-openbmc to address this? Nothing in Gerrit?

https://github.com/ibm-openbmc/bmcweb/pull/135

PowerWatts is the new name?

**Comment by bjwyman** [comment]
EfficiencyPercent: https://github.com/openbmc/bmcweb/commit/42cbe53889b5f2d358d1174245df51a23efcb3f8

**Comment by bjwyman** [comment]
PowerMetrics -> PowerWatts.

Old:
```
[PowerMetrics]:
      [AverageConsumedWatts]:                     303
      [IntervalInMin]:                            10
      [MaxConsumedWatts]:                         386
```

Min and Max values for the new Redfish schema apparently still missing.

**Comment by bjwyman** [comment]
`curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply0`

- Rainier: Sensor changed to /redfish/v1/Chassis/chassis/EnvironmentMetrics (PowerWatts)

**Comment by derekhoward55** [comment]
PowerWatts is being returned (this is from rain104):
```
"PowerWatts": {
"@odata.id": ["/redfish/v1/Chassis/chassis/Sensors/total_power"](https://rain104bmc.aus.stglabs.ibm.com/redfish/v1/Chassis/chassis/Sensors/total_power),
"DataSourceUri": "/redfish/v1/Chassis/chassis/Sensors/total_power",
"Reading": 316.0
}
```

So all that is remaining is to test by defining a MetricReportDefinition so the telemetry service can construct the max PowerWatts.

**Comment by derekhoward55** [comment]
Verified we're able to collect a Max PowerWatts with redfish telemetry service:

`    {
      "MetricId": "MaxTotalPower_5s",
      "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/total_power/Reading",
      "MetricValue": "797.000000",
      "Timestamp": "1970-10-06T06:37:15+00:00"
    },
`
