### ISSUE TITLE
LED: Missing Led Indicator

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#1395]
Missing Led Indicator, known SW474357.

This issue is to track getting Legacy function operational on FW1010 images
Test team results indicated this function was not working.

**Comment by vishwabmc** [comment]
@rfrandse I see the issue SW474357 is closed. Is this still valid ?

**Comment by gtmills** [comment]
@rfrandse @vishwabmc Can we close?

**Comment by vishwabmc** [comment]
@gtmills I see the CQ is closed. So, this should be closed too unless @rfrandse thinks there is still something more to it.

**Comment by gtmills** [comment]
Closing. @rfrandse @gkeishin Please reopen if still an issue
