### ISSUE TITLE
peltool:  Fill in and use the Description field in the PEL Values arrays

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1397]
These will be better to read than the registry constants.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/27809

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/27809 merged
