### ISSUE TITLE
Implement  Certificate Signing Request api

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#14]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ojayanth](https://github.com/ojayanth)**
_Thursday Aug 02, 2018 at 10:55 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3337_

----

Create CSR using openSSL functions .
BMC should store the Signed certificate and private key in a persistent secured storage location..

Note: A new CSR generate on same type request will overwrite the previous CSR. User should take caution to not repeat CSR requests to prevent overwriting pending CSRs.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Duplicate issue: https://github.com/ibm-openbmc/dev/issues/227

**Comment by ojayanth** [comment]
Just realized #227 tracks only BMC web changes.
This issue used to track Phosphor-certificate manager related changes
- Private kety creation based on user requested attributes.
- Generating CSR based on user input attributes.
- Installing CSR based certificates.

**Comment by ojayanth** [comment]
d-bus Link:
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/16571/

Design Discussion details available here.
https://lists.ozlabs.org/pipermail/openbmc/2019-February/015102.html

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Coding is in progress.

**Comment by rfrandse** [comment]
refresh

**Comment by devenrao** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-certificate-manager/+/19205/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Review #19205 is abandoned . 
Resolve by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-certificate-manager/+/19383
