### ISSUE TITLE
Power / Cooling - EPOW

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#140]
<a href="https://github.com/anoo1"><img src="https://avatars0.githubusercontent.com/u/9052527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anoo1](https://github.com/anoo1)**
_Tuesday Jun 14, 2016 at 19:44 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/346_

----

Placeholder for EPOW support functions on future systems.

**Comment by rfrandse** [comment]
<a href="https://github.com/geissonator"><img src="https://avatars2.githubusercontent.com/u/1612261?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geissonator](https://github.com/geissonator)**
_Tuesday Jan 16, 2018 at 19:52 GMT_

----

A lot of this is sending events up to the OS to let them know when bad things are starting to happen (fans starting to fail, ambient rising, ...) to allow a controlled shutdown.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derekhoward55** [comment]
Closing this as dupe of issue 585
