### ISSUE TITLE
Rainier power/thermal support for PEL message registry

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1402]
Add base SRCs to message registry with callouts/severities/action flags etc not already added in previous stories.

Nag function moved out to 1030.

Any ctrm type dependencies?
_Andrew: power/thermal code would log a PEL that has the “terminating” bit set within the PEL registry. I know @shawnmm has been doing that already for some of the VRM related fails. That bit then triggers some back end things like displaying that SRC to the panel and such. BMC doesn’t really have a “terminate” state but the things that need to happen like the panel display occur based on that bit in the logged PEL.
Shawn: set the Severity to critical_system_term and set the PowerFault flag to true.
I think the Severity property value is the one that Andrew is referring to for causing the extra "back-end" things._
**Should be added for 00AC (in pseq (already done) and state management (phosphor-state-manager/chassis_state_manager.cpp, near the "report Blackout") code) & 2602 (in message registry).**

Update field in the message registry (PowerFault).  It has a true or false value.  Historically was 'true' for critical errors.  Was used for FSP APOR and powrFaultQuery, however those designs are refactored on the bmc and no longer need the PowerFault bit set.  No known usage from HMC nor any OS service agent, so no longer any need to bring this forward to BMC.
**Remove any setting of the bit in the message registry and code.**
Eg, in ambient temp sensing code:

    // If this is a power off, specify that it's a power
    // fault and a system termination.  This is used by some
    // implementations for service reasons.
    if (isPowerOffError)
    {
        **ad.emplace("POWER_THERMAL_CRITICAL_FAULT", "TRUE");**
        ad.emplace("SEVERITY_DETAIL", "SYSTEM_TERM");
    }

**Comment by bjwyman** [comment]
- [x] Add 2602 fault to message_registry.json
    - This is the standby VRM failure that can cause BMC reset
    - Severity as critical in the registry.
    - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/52055
    - https://github.com/openbmc/phosphor-logging/commit/2a2d0aeb2aa6470952d9b4cbc7a99d18c7f8eb14
- [x] Updates for 00AC - Blackout.
    - [x] Update state manager code to log as severity critical/term (YAML file implications?) https://github.com/openbmc/phosphor-state-manager/commit/073fa2b3824387671288279456d2c8d46025794a
    - [x] Update sequencing code to set severity as critical/term if pgood fault and PSU error is brownout.
        - Already done earlier? https://github.com/openbmc/phosphor-power/commit/930458c23ce545620614e31cdd32d9ee545230f3 & https://github.com/openbmc/phosphor-power/commit/ccea2d2b95e1f826d42a14a47b1b30aaec5cd93d
    - [x] Remove severity from message_registry.json Blackout fault. 
        - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/52021
        - https://github.com/openbmc/phosphor-logging/commit/42d0259e84e1cad569fc26230b1c774ac8070b40
- [x] Remove PowerFault bit usage.
    - [x] Remove PowerFault bit from message_registry.json entries. https://github.com/openbmc/phosphor-logging/commit/a2d7b7750ce7a93b1cc785f568acfb69c1ca01b1
    - [x] Remove code setting PowerFault bit. https://github.com/openbmc/phosphor-fan-presence/commit/b2766c15ebbf9ad12bccc349d264ef903a5ffd66

**Comment by bjwyman** [comment]
SRCREV bump: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/52230
