### ISSUE TITLE
Code Update: ApplyTime support not available

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#1407]
This issue is to track getting Legacy function operational on FW1010 images
Test team results indicated this function was not working.

**Comment by mzipse** [comment]
@jaypadath , can you confirm that this is complete for eBMC?  If so, please close.

**Comment by mzipse** [comment]
@geissonator or @jaypadath or @anoo1 , this story was a carryover from Witherspoon, ensuring that equivalent functionality is available for eBMC.  Can someone confirm that this is closed with our other Code Update work?  Or is there something that needs to be done here yet?

**Comment by geissonator** [comment]
Yes, Jay can reopen if I'm wrong but my understanding is we have all ApplyTime support in with https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24679

**Comment by jaypadath** [comment]
Yes the ApplyTime support is already present with eBMC systems
