### ISSUE TITLE
EPOW - Enable OS communication

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#141]
<a href="https://github.com/msbarth"><img src="https://avatars2.githubusercontent.com/u/14202667?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [msbarth](https://github.com/msbarth)**
_Tuesday Jan 03, 2017 at 18:45 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/911_

----

- [ ] Determine standard format/data accepted by OS (use PLDM state sets, event will be sent on state set change)
- [ ] Setup pldm state set data and interfaces to notify OS (PHYP/OPAL)
- [ ] Create function to populate EPOW data
- [ ] Create function to set/clear EPOW events(timers)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derekhoward55** [comment]
This work completed already in other issues.
