### ISSUE TITLE
Combined image version

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1415]
Come up with a version string that represents the version of the combined image and store it somewhere that other code (Redfish/web UI, PEL) can find it.

@anoo1

**Comment by anoo1** [comment]
- [ ] Include the level for the non-running side.

**Comment by mzipse** [comment]
Deferring this to the next GA to wait and get feedback on current design.

**Comment by anoo1** [comment]
No current plans to support this.
