### ISSUE TITLE
Fill in the Server Firmware Released Version field in the ExtendedUserHeader PEL section

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1416]
The Extended User Header section has a field for the server firmware version, as opposed to the BMC firmware version.  Currently this is not available anywhere.  When it is, start filling it in.

#1415 tracks that field being available.

**Comment by spinler** [comment]
This is now available in the VERSION_ID field in /etc/os-release inside parentheses:


$ cat /etc/os-release 
ID=openbmc-openpower
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="fw1020.00-18.6"
VERSION_ID=fw1020.00-18.6-1020.2116.20210414a **(NL1020_003)**

**Comment by sumitk56** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/43178
