### ISSUE TITLE
Enable ECMD istep control (Steps by major number) for OpenBmc

### ISSUE THREAD

**Issue by lkammath** [ibm-openbmc/dev#1417]
Requires the implementation in following order and test it on openpower configuration as well

1) Implement dllIStepsByNumber(const ecmdDataBuffer & i_steps) in the ecmd-pdbg pluggin layer -  This function executes the given list of istep numbers.

2) Setup the istep mode (Using SBE scratchpad registers)

3) Call ipl_run_major(int major) api from phal/ipl multiple times  depending start and end isteps incrementing major number every time it called in loop

**Comment by ojayanth** [comment]
This Issue Track the  ecmd Infrastructure work.  Backened is tracked under #1163

**Comment by lkammath** [comment]
https://github.com/open-power/ecmd-pdbg/pull/17/ in code review

**Comment by lkammath** [comment]
PR Integrated.. need to bump up the version downstream

**Comment by lkammath** [comment]
https://github.ibm.com/openbmc/openbmc/pull/156

Integrated downstream. available in builds
