### ISSUE TITLE
Enable ECMD istep control (Steps by name)  for OpenBmc

### ISSUE THREAD

**Issue by lkammath** [ibm-openbmc/dev#1418]
Requires the implementation in following order and test it on openpower configuration as well

    1. Implement dllIStepsByName(std::string i_stepName) in the ecmd-pdbg pluggin layer by Lookup i_stepName in IPL Table - This function executes the given istep name
      error - i_stepName not found!  Then, list the istep by running istep list (Which needs to open the list of isteps htxt file which is updated as per the ipl specification)

    2. Setup the istep mode (Using  SBE scratchpad registers)

    3. Call ipl_run_step (const char *name)  api from phal/ipl to execute istep by name to execute single istep

**Comment by lkammath** [comment]
Work in progress

**Comment by lkammath** [comment]
https://github.com/open-power/ecmd-pdbg/pull/29/ - code is under review

**Comment by lkammath** [comment]
Integrated to ecmd-pdbg upstream

**Comment by ojayanth** [comment]
Available in the latest driver.
