### ISSUE TITLE
Enable ECMD istep control (Steps by name multiple)  for OpenBmc

### ISSUE THREAD

**Issue by lkammath** [ibm-openbmc/dev#1419]
Requires the implementation in following order and test it on openpower systems

[] Implement dllIStepsByNameMultiple(std::list< std::string > i_stepNames) in for loop incrementing iterators -  This function executes the given list of istep names. 
[]List passed in is a series of isteps to be called in order
[] Setup the istep mode (Using SBE scratchpad registers)
[] Call dllIStepsByName(pointer to istep iterator) in for loop incrementing iterators

**Comment by lkammath** [comment]
https://github.com/open-power/ecmd-pdbg/pull/29/ - Code is under review.

**Comment by lkammath** [comment]
integrated ecmd-pdbg upstream

**Comment by ojayanth** [comment]
Available in the latest driver.
