### ISSUE TITLE
EPOW - EPOW 3 enablement

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#142]
<a href="https://github.com/msbarth"><img src="https://avatars2.githubusercontent.com/u/14202667?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [msbarth](https://github.com/msbarth)**
_Friday Jan 06, 2017 at 20:59 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/933_

----

- [ ] Create EPOW 3 interface
- [ ] Populate EPOW data for OS to know EPOW 3 event
- [ ] Add 15min timer function including set/reset EPOW 3 event
- [ ] Add ability to shutdown(orderly) after 15min timer expires

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derekhoward55** [comment]
This work completed with other issues.
