### ISSUE TITLE
Enable ECMD istep control (range of istep names) for OpenBmc 

### ISSUE THREAD

**Issue by lkammath** [ibm-openbmc/dev#1420]
Requires the implementation in following order and test it on openpower configuration as well 

 []    Validate if valid start and end isteps are provided
 []	Lookup i_stepNameBegin in IPLTable
 []    Start istep should be smaller than end istep
 []    Set the ipl mode to istep using sbe scratchpad registers
 []    call dllStepsByName() in loop

**Comment by ojayanth** [comment]
Reducing complexity.

**Comment by lkammath** [comment]
Work in progress

**Comment by lkammath** [comment]
https://github.com/open-power/ecmd-pdbg/pull/29/ - code is under review

**Comment by lkammath** [comment]
integrated ecmd-pdbg upstream

**Comment by ojayanth** [comment]
Available in the latest Driver.
