### ISSUE TITLE
ecmd getSPR/putSPR support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1422]
Add required pdbg hooks in edbg and validate in Simulation environment.

**Comment by ojayanth** [comment]
pdbg back-end api sizing is not included

**Comment by lkammath** [comment]
Work In progress

**Comment by lkammath** [comment]
https://github.ibm.com/phal/ecmd-pdbg/pull/18 - under review

**Comment by lkammath** [comment]
Integrated

**Comment by lkammath** [comment]
Available in the release driver
