### ISSUE TITLE
HMC-BMC Lock: Return the transaction ID as part of aquire lock response

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1425]
Should return the Transaction ID as part of aquire lock API response.
This transaction ID would be used to release the resource lock associated with the transaction.

**Comment by manojkiraneda** [comment]
The code is already merged in master as a part of the following commit .

https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/27671/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/27954/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/27953/
