### ISSUE TITLE
HMC-BMC (Lock Management)implement aquire lock API

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1426]
Every  request to aquire a lock will be assigned with unique 32 bit number called as transactionID.  (used by the management console to debug).
•    There should be a provision to obtain either a write lock (which is acquired
if a resource is to be modified) or a read lock (which is acquired if the
 resource is to be read).
•    There should a provision to obtain multiple read locks on same resource.
•     Multiple write locks on same resource are prohibited.
•     Read lock on resource which is write locked should not be valid.
•    Write lock on resource which is read locked should not be valid.
•    There should be a provision to obtain multi-level locks (parent and child  locking mechanism), so that we should be able acquire lock for all/some  resources which are under another resource.

**Comment by manojkiraneda** [comment]
The code is already merged in master .

https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/27671/

Closing this issue.
