### ISSUE TITLE
HMC-BMC LOCK Implement the GET lock list API

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1428]
This API will get all the locks associated with the session.
User can get all the session by querying the session service to get the sessions and from that user can ask the locks associated with the session.
This API would require ADMIN privilege.

**Comment by manojkiraneda** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/27954/

Code is merged in master ,so closing this issue.
