### ISSUE TITLE
eBMC: RTC Battery test

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1429]
We need to test the battery and see the likelihood of it sustaining the power. If a week battery is detected, need to log an error and notify.

This would need a battery test circuit to be built . Need to discuss with the system engineers.

**Comment by mine260309** [comment]
On Romulus, the RTC battery voltage is monitored by an IIO and handled by `phosphor-hwmon`.
It is configured to read this sensor once a day to prevent draining the battery out.

To report the error, it is possible to use phosphor-dbus-monitor to monitor the sensor, log and report.

**Comment by vishwabmc** [comment]
@mine260309 thanks.. We were having some discussion on this.. The gist is along the same path as you mentioned. 

There will be a ADC that the BMC would read via hwmon and then when the value is `< 1.034`, log an error..  Additionally, we could check read the value twice before declaring the failure.

**Comment by vishwabmc** [comment]
Whenever this is ready ... would your team be interested in looking into ? @mine260309

**Comment by mine260309** [comment]
It depends on the HW design, e.g. the ADC and IIO configs.
What we could do is to write a dbus-monitor config to log an error, e.g. on FP5280G2.

**Comment by vishwabmc** [comment]
```Read the ADC
  --> If the value is < 1.034V
      --> Sample it again in some time
      --> If the value is still < 1.034V, declare an error.
```

**Comment by spinler** [comment]
@vishwabmc Is there going to be a menu option to start/stop battery maintenance?  Will that have to stop/start the monitoring?

**Comment by vishwabmc** [comment]
> @vishwabmc Is there going to be a menu option to start/stop battery maintenance? Will that have to stop/start the monitoring?

@spinler yeah.. I think it's a good idea to have a menu for that.

**Comment by vishwabmc** [comment]
@gtmills do you want to take this forward ?.. Is there a lamp_test need ?

**Comment by gtmills** [comment]
@vishwabmc Take forward a readyToRemove? https://github.com/ibm-openbmc/dev/issues/2012
Redfish issue 4234 
Does a SafeToRemove" boolean? or an enum "notSafe", "cold", "hotplug" make more sense?

RTC battery will be an assembly so the ask to redfish was to add this to assembly and pcie device

**Comment by derick-montague** [comment]
> @spinler yeah.. I think it's a good idea to have a menu for that.

When we suggest menu item, is this specific to the GUI?

**Comment by gtmills** [comment]
Did we have this on ASMI ?

**Comment by derick-montague** [comment]
@gtmills 
> @derick-montague Did we have this on ASMI ?

I don't believe so. I would think this would be part of the log service and not something there would be an explicit GUI menu item for.

**Comment by mzipse** [comment]
Work is complete.  Closing.
