### ISSUE TITLE
EPOW - EPOW 4 enablement

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#143]
<a href="https://github.com/msbarth"><img src="https://avatars2.githubusercontent.com/u/14202667?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [msbarth](https://github.com/msbarth)**
_Friday Jan 06, 2017 at 21:04 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/934_

----

- [ ] Create EPOW 4 interface
- [ ] Populate EPOW 4 data for OS to know of event
- [ ] Add 23sec timer(non-modifiable) function including setting of EPOW 4 event (can not be modified/reset)
- [ ] Add ability to shutdown(hard) after timer expires

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derekhoward55** [comment]
This work completed with other issues.
