### ISSUE TITLE
GUI : Research : Show Guard records and Clear Guard

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1432]
## Stakeholders
**SME**: @ojayanth 
**BMC**:
**RAS**:
**PHYP**:

## Summary
- [ ] Add summary

### Background
---
The user should be able to clear the GARD records. 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/27459 implements Redfish ResetBios which clears the GARD records. Should we call this `reset Bios` ? Should we call this `Reset Bios (Clear GARDs)` ? Is GARD something customers know?
- Gunnar

### End users
- [ ]  TBD

### User Needs
- [ ] TBD

### User Quotes
- [ ] TBD

## User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

## References
- [eBMC Feature 4.9.6](https://ibm.ent.box.com/file/455779315260)
- [Discovery doc](https://ibm.box.com/s/la3pke2bmnv3nfmnr2egvyrv1dqn72gn)

**Comment by gtmills** [comment]
@derick-montague Do we have to story to display the GARD records?

**Comment by derick-montague** [comment]
> @derick-montague Do we have to story to display the GARD records?

Record should be a different story?

**Comment by derick-montague** [comment]
@nicoleconser - [Discussed here on 7/21](https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/W5d74d2bb8660_4d6e_9bb6_08e4fc6ff375/page/OpenBMC%20Design%20Reviews) proposing at a Redfish log service

**Comment by derick-montague** [comment]
Closing as this work is part of HW Deconfiguration #1508
