### ISSUE TITLE
Integrate the nbd-proxy into http server framework

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#144]
Reference: http://github.com/jk-ozlabs/jsnbd

[ ] Enable NBD in the kernel defconfig and add the nbd-client tool as well.
[ ] Connect the nbd proxy to the websocket
[ ] Integrate the nbd proxy to bmcweb

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/17561

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/17561 merged
