### ISSUE TITLE
Turn off current phosphor-logging error log caps

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1440]
When the code is in place to purge old PELs based on some maximum size or percentage (from the other stories in this epic), need to tell phosphor-logging to stop capping error logs at 200.

A call to DISABLE_LOG_ENTRY_CAPS() in entry_points.cpp will do this.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/34432

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/34432 merged
