### ISSUE TITLE
PFP::presence - Produce an "informational" error on single detection failure

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1442]
Need to ability to log something to notify manufacturing to investigate further why a single method of presence detection failed but the other methods still resulted in a single fan enclosure being marked as present. This is necessary to ensure all methods configured for fan presence detection are functioning properly after the machine is assembled.

ex.) Gpio line broken but fan is still marked present since its feedback speed exists. Would need to log something to have the gpio line looked at in this case.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/42519

**Comment by msbarth** [comment]
Duplicate of https://github.com/ibm-openbmc/dev/issues/2903
