### ISSUE TITLE
GUI : FED : Update BMC Information in Server Overview

### ISSUE THREAD

**Issue by jandraa** [ibm-openbmc/dev#1444]
## As Is
`BMC Information` section in Server Overview needs to include IP address, hostname, and MAC address for a single port only. 
 ![Screen Shot 2019-12-06 at 1.17.22 PM.png](https://images.zenhubusercontent.com/5c59b678d6ca520817b16dbf/3fec0929-37c1-4603-a84c-dea0e31e30ea)

## To Be
`BMC Information` section in Server Overview needs to include IP address, hostname, and MAC address for both network ports, eth0 and eth1. 
![Screen Shot 2019-12-06 at 1.17.32 PM.png](https://images.zenhubusercontent.com/5c59b678d6ca520817b16dbf/a6f41a7c-f64d-493b-9016-ee887bed0891)
https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319351716_Server_Overview_-_Double_Ports

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/28789

**Comment by dixsie** [comment]
@derick-montague FYI: This needs to be revisited to display eth1 network port when it becomes available (only one network port is supported at this time). 

The commit https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/28789 only implements the layout redesign for overview server information

<img width="662" alt="Screen Shot 2020-02-03 at 3 00 00 PM" src="https://user-images.githubusercontent.com/26472611/73690448-fbfdb100-4695-11ea-8f9e-88bb501eb19b.png">
