### ISSUE TITLE
PLDM: libpldmresponder BIOS parser code refactor

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1449]
The PLDM bios_parser code is a little hard to read now, but this can be improved now that the libpldresponder handlers are OO - this allows for example for better abstraction and encapsulation of the parser code.

**Comment by wangzqbj** [comment]
Resolved by

- [ ] ibpldm: bios: Implement iter for attr value table
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27639

- [ ] libpldm: Add API to find an attribute value entry
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27640

- [ ] Add cc only response
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27667

- [ ] Implement GetBIOSAttributeCurrentValueByHandle
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27731

**Comment by wangzqbj** [comment]
Resolved by 

- bios: Implement BIOSAttribute 
 https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/29315
- bios: Implement BIOSStringAttribute:
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/29317
- bios: Implement BIOSConfig
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/29318
- bios: Implement BIOSIntegerAttribute
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/29353
- bios: Implement BIOSEnumAttribute
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/29358
- bios: Use the new APIs in bios table commands
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/29447

**Comment by wangzqbj** [comment]
All of the changes are merged,
