### ISSUE TITLE
Start the USB gadget on nbd startup

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#145]
Add hooks to automatically start/stop the USB mass-storage gadget on nbd session setup.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/17494

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/17494 merged
