### ISSUE TITLE
PLDM : Add build time dependencies

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1460]
The pldm daemon depends on boost and cli11. Add these deps to the meson build file as well as the pldm recipe.

**Comment by XiaochaoMa** [comment]
Add cli11：

- [ ] https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/31140

**Comment by XiaochaoMa** [comment]
The "boost" is not useful in pldm now. We use another crc function to instead it.   
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/31139

**Comment by XiaochaoMa** [comment]
Remove boost depends in pldm_git.bb 
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/31225

**Comment by XiaochaoMa** [comment]
Version bump of pldm is failing after the CLI11 added. So reverted by Deepak:
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/31269
