### ISSUE TITLE
PLDM : Implement command SetBIOSAttributeCurrentValue

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1463]
Implement SetBIOSAttributeCurrentValue as per DSP0247 v1.0.0.

- Error should be returned if the attribute is read only.
- Persisted attribute value table must be udpated.
- If the attribute is mapped to a d-bus property, that must be updated as well.

**Comment by wangzqbj** [comment]
merged: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/28130
