### ISSUE TITLE
eBMC State Management:  Enable Warm IPL ( Warm Re-IPL )

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1466]
In the scenarios where the Host crashes and thus demanding a reboot of the Host, we don't have to start all over again doing powerOff + PowerOn. Instead, we could bypass the whole PowerOn sequence and directly jump to Host portion of it. This story is to enable such a Warm Re-IPL

**Comment by vishwabmc** [comment]
There are 2 usecases of this:

1/. Host asking the BMC to do the Warm Reboot: This will be the case during OS lid updates.
--> This would be a PLDM command asking for such a Re-IPL. 

2/. Host crash
--> Need to chain the sequence post Quiesce

**Comment by geissonator** [comment]
Stop Instructions Story: https://github.com/ibm-openbmc/dev/issues/736 
Although, we may be able to just do a "pdbg -a" initially to stop instructions.

**Comment by geissonator** [comment]
My plan is to at least get the target framework and basic services in place. May need to move a few points from this into a follow on story depending on how much extra application work is needed to do the full warm reboot.

**Comment by geissonator** [comment]
Some additional work this entailed:
- Working with DMTF to understand mappings to ResetType - https://redfishforum.com/thread/261/host-warm-reboots
- A new design doc for the new host states - https://github.com/openbmc/docs/blob/master/designs/state-management-and-external-interfaces.md
- New phosphor-dbus-interfaces - https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/State/Host.interface.yaml#L35
- DTS updates to name gpio pins so new libgpiod can be used with cfam-reset (required for warm re-ipl) - https://lists.ozlabs.org/pipermail/openbmc/2020-February/020425.html
- Creation of new targets - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/28879

Still in process:
- Support in phosphor-state-manager for new interfaces
- Support in openpower-proc-control to stop instructions and cfam reset

**Comment by geissonator** [comment]
Everything tested and ready. Waiting on kernel dts change to get in:
- https://lists.ozlabs.org/pipermail/openbmc/2020-February/020425.html

proc-control changes:
- https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/29087/7
- https://gerrit.openbmc-project.xyz/c/openbmc/meta-openpower/+/29470

state-manager changes:
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/29334
- https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/29471

**Comment by geissonator** [comment]
Everything is in and verified on witherspoon-128
