### ISSUE TITLE
Timed Power On: Implement the service

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#1468]
The service shall implement the interface defined by https://github.com/ibm-openbmc/dev/issues/1467, providing functions:
* Set a timer (or timestamp) for when the host shall be powered on;
* Power on the host when the timer expires, or the timestamp is passed;
* After it's powered on, reset the timer (or timestamp) to 0;
* If the host is not ready to power on when the timer (or timestamp) is reached, e.g. when BMC is rebooting, BMC shall know such case and power on the host after it is ready.

**Comment by wangkair** [comment]
Procedure:
1.  add base interfaces for Timed Power On
2. handle with the received time
3. implement timer
4. implement power on process
5. store the specified time value into flash

**Comment by mine260309** [comment]
Yup, there shall be at least:

```
8. Handle time changed case
```

**Comment by wangkair** [comment]
> > Procedure:
> > ```
> > 1. add base interfaces for Timed Power On.   Done
> > 
> > 2. handle with the received time.  Done
> > 
> > 3. implement timer.   Done
> > 
> > 4. implement power on process.  Done
> > 
> > 5. store the specified time value into flash
> > 
> > 6. build systemd service for TPO
> > 
> > 7. add test cases
> >    (consider: If the host is not ready to power on when the timer (or timestamp) is reached, e.g. when BMC is rebooting, BMC shall know such case and power on the host after it is ready.)
> > ```
> 
> Sorry, only checking now... is it all done ?. may I know how is the timer implemented ?. How is it checking with the current time ?.. What happens if the time is changed ?

I wrote this procedure to avoid to forget something, because I will start my Spring Festival next week. The steps with "Done" are all finished on my local project. I wanna push them onto gerrit after the yaml file is merged first, otherwise, the jenkins can't pass my code and I may change the code again if yaml file is changed.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Removing @wangkair as I don't think she will be finishing this effort.  Carol, if you are able, can you document how far you got with this?  I believe some of this has been pushed up to Gerrit.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
I've added the timed power on feature to all flash images with https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/40097

Here are some commands I used for testing:
```
# Get epoch time from command line
date "+%s"

busctl get-property xyz.openbmc_project.State.ScheduledHostTransition /xyz/openbmc_project/state/host0 xyz.openbmc_project.State.ScheduledHostTransition ScheduledTime
busctl get-property xyz.openbmc_project.State.ScheduledHostTransition /xyz/openbmc_project/state/host0 xyz.openbmc_project.State.ScheduledHostTransition ScheduledTransition

busctl set-property xyz.openbmc_project.State.ScheduledHostTransition /xyz/openbmc_project/state/host0 xyz.openbmc_project.State.ScheduledHostTransition ScheduledTransition s "xyz.openbmc_project.State.Host.Transition.On"

busctl set-property xyz.openbmc_project.State.ScheduledHostTransition /xyz/openbmc_project/state/host0 xyz.openbmc_project.State.ScheduledHostTransition ScheduledTime t <number of seconds past UTC>
```

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Sounds like there is more week needed here.  The Timed Power on function can be initiated by the Host OS.  So there is some PLDM work to interact between the Hypervisor and the BMC to suppport that.  @sampmisr , once we understand what that design, please create a story and link it to this Epic.

**Comment by sampmisr** [comment]
the pldm work is done via https://github.com/ibm-openbmc/dev/issues/1545 
Host sets the DBus interface via an effecter

**Comment by geissonator** [comment]
Everything is now in, closing.
