### ISSUE TITLE
PFP::presence - Tier json config file usage

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1471]
Enhance the use of a json configuration to load the first json config file found in the following order:

1. Alternate/override file in hard coded directory location within `/etc/phosphor-fan-presence/presence/`
2. Directory location given at configure time within the `PRESENCE_CONFIG_PATH`
3. Directory location given by a dbus object where the interface and property names are given at configure time within `PRESENCE_CONFIG_DBUS_INTF` and `PRESENCE_CONFIG_DBUS_PROP` variables.

**Comment by msbarth** [comment]
After further consideration, in addition to this tiered approach, the paths will instead be hardcoded for each of the locations and the dbus interface & property will be hardcoded to simplify the logic and enforce the use of designated areas within the BMC image that would contain application configuration data.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/27990

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/27990 merged
