### ISSUE TITLE
GUI : Research : Factory Configuration - Factory Reset

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1472]
## SME
**BMC**: @anoo1 
**RAS**: George Ahrens
**PHYP**:

## Summary
The user will be able to perform two different resets, full factory reset and partition reset only. There is a fair amount of conversation with Russell Y, Joe M, and Todd R.

### Background
- [ ] TBD

### End users
- Paul (Product Engineer)
- Tricia (Power Sys Admin)
- Noah (Junior Sys Admin w/o HMC) 
- (IBM test)

### User Needs
- Understand how many ways you can reset + what each option entails. 
- Understand what the system state should ideally be in. 
- How does the system react when something is reset? 

### User Quotes
- [ ] TBD

## User Story

- As an admin, I want to factory reset to get a clean system, so that for example, I can re-purpose my system.
-  As a customer Support team member, I need to factory reset to fix a problem, so that the system can continue working as it was before.
- As a user, I want to reset the Hypervisor settings to configure it to a non-HMC managed system.  

## References
- [ ] eBMC Feature Item <add number>
- [ ] [Link to Discovery folder](https://ibm.box.com/s/9w45hjcbcjrz47z3wrst00j8n2pdppkm)

### Invision prototype
**Lo fi**
https://ibm.invisionapp.com/share/JDO0P85V86K
**HI fi**
https://ibm.invisionapp.com/share/ZHO0QDQX3U5

**Comment by nicoleconser** [comment]
In today's sync-up, we discovered the following (edited above to match): 
- Back up & Restore Host / Server Configuration --> **need to confirm value to customers** (if low, don't include in GUI) 
- Back up & Restore BMC Configuration  --> **need to confirm value to customers** (if low, don't include in GUI) 
- Reset to Factory Configuration  --> high value to Support (definitely needed in GUI); **need to confirm if user will have options on what to reset**

**Comment by derick-montague** [comment]
> Reset to Factory Configuration --> high value to Support (definitely needed in GUI); need to confirm if user will have options on what to reset

@gtmills noted that the Redfish API is ready for Reset to Factory Config. It was noted that offering all settings could be potential security issue and that the group other than PE thought that consensus had already been reached. We will need to talk to Todd about this.

**Comment by gtmills** [comment]
API is 
```
curl -k -X POST \
https://${bmc}/redfish/v1/Managers/bmc/Actions/Manager.ResetToDefaults \
-d '{"ResetToDefaultsType": "ResetAll"}'
{
  "@Message.ExtendedInfo": [
    {
      "@odata.type": "#Message.v1_0_0.Message",
      "Message": "Successfully Completed Request",
      "MessageArgs": [],
      "MessageId": "Base.1.4.0.Success",
      "Resolution": "None",
      "Severity": "OK"
    }
  ]
}
```
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32991

**Comment by nicoleconser** [comment]
Per Todd: 

> On the factory reset screens, there needs to be a warning that tells IBM customers they are potentially deleting private keys. Designer to work with **Chris Engel** to determine the exact text.

(see 9/17/20 email from Todd to Nicole)

**Comment by derick-montague** [comment]
@nicoleconser - Based on the conversations today in the feature sync meeting, how do you feel about breaking this into two stories. One for `Backup and Restore` and one for `Reset to factory configuration`? We know the milestone for factory reset, but still unclear about the milestone for back up and restore.

**Comment by derick-montague** [comment]
This story was split into two different stories. It is likely that there will be a revisit to this page when #2633 is being designed. That story is not relevant currently. There is an early version prototpye linked in the story, but likely will need to be reworked and not relevant for this story other than to think about future scalability.

**Comment by ParishrutB** [comment]
On factory reset:
From [discussion](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1603385952474800) with Adriana and Gunnar: The plan is to have 1 and 3, meaning that ‘reset bmc settings’ only is not supported, more details in this box note under the ‘factory reset’ title - https://ibm.ent.box.com/notes/661340616362

![image](https://user-images.githubusercontent.com/61419136/96991022-7da7ae80-1545-11eb-8db2-9131d27ce398.png)

**Comment by ParishrutB** [comment]
### To do

- [ ] Meet with Adriana, Gunnar, Yoshie to understand: 
              - What conditions must be true before user can reset? E.g. does the server require to be powered off?
              - What happens after the user starts the reset process? E.g Does the screen become non-responsive due to BMC 
                reboot?

- [ ] Meet with Chris Engel to discuss the copy for information outside the warning modal as well as inside the warning modal. 

- [ ] Finish the design. 

- [ ] Review with team to see if there is any need for testing/research. Maybe that can be done with internal experts over a quick call. 

I think if the copy and interactions are finalized, then once Yoshie starts implementing it, we will get to see how the API works. Few design modifications can be done at that time as well.

**Comment by priyanka-pillai97** [comment]
### To do

- [ ] Meet with Adriana, Gunnar, Yoshie, along with the mockup, to understand: 
              - What conditions must be true before user can reset? E.g. does the server require to be powered off?
              - What happens after the user starts the reset process? E.g Does the screen become non-responsive due to BMC reboot? Does it need to be refreshed? How long does it take? Do the users need to stay on in the same screen? 

              **Note:** There was some discussion happening on this [here](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1603385952474800). Can be reviewed but I think it is better to close it on a call with all of them. 

- [ ] Meet with Chris Engel to discuss the copy for information outside the warning modal as well as inside the warning modal. Tried messaging him on slack here [but](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1603883325116400) that didn't work. 

- [ ] Finish the design. 

- [ ] Review with team to see if there is any need for testing/research. Maybe that can be done with internal experts over a quick call. 

I think if the copy and interactions are finalized, then once Yoshie starts implementing it, we will get to see how the API works. Few design modifications can be done at that time as well.
