### ISSUE TITLE
phosphor-regulators: Obtain config file name from D-Bus

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#1474]
The phosphor-regulators application is driven by a JSON configuration file (config file).

Each system type will have its own config file, since each system has different regulators, voltage requirements, hardware work-arounds, etc.

The config files with have unique names based on the system type, such as foo_2u_vrm_config.json for a 2U version of a "Foo" system.

At run-time, the phosphor-regulators application will need to determine the correct config file for the system type it is running on.  The current plan is that EntityManager will determine the system type and store the associated config file name in a D-Bus object path.  The phosphor-regulators application will get the config file name from D-Bus.

This work item involves the following:
* Determine the correct D-Bus object path, interface, and property to use.
* Implement code in phosphor-regulators to get the config file name from D-Bus.

**Comment by msbarth** [comment]
- [ ] Determine the correct D-Bus object path, interface, and property to use.
- [ ] Implement code in phosphor-regulators to get the config file name from D-Bus.

**Comment by msbarth** [comment]
Initially will use the following for the path, interface and property:
- Path: `/xyz/openbmc_project/inventory/system`
- Interface: `xyz.openbmc_project.Inventory.Item.System`
- Property: `Identifier`

*Note the `Identifier` property does not exist on this interface currently, so may change (along with the path and/or interface) once the design of EM is finalized to provide the needed system name.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/29886

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/29886 merged
