### ISSUE TITLE
GUI : Research : PCIe Hardware Topology

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1475]
## SMEs
**BMC**: @bradbishop (working on redfish mockup), Link properties @sampmisr , VPD @santoshpuranik , LEDs @vishwabmc
**PHYP**: Justin King, Adam Stallman, Jessee Arroyo
**RAS**: Justin Thaler

### Use Case
As a PE/Admin/SSR, I need to troubleshoot the connection problems so that I can fix issues with cabling and connectivity between servers and expansion drawers.

### InVision Prototype
https://ibm.invisionapp.com/d/main#/console/15347903/320017936/preview

## Design Issue (phosphor-webui)
https://github.com/openbmc/webui-vue/issues/66

## References/Resources
- [eBMC Feature Item: 2.2.4](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)
- Discovery doc: https://ibm.ent.box.com/notes/818358757033

### UX Flow / Interaction Requirements
- Meeting on 06/28/2021 with Parishrut, Sukanya, Sandeepa about each component and interaction:**
Meeting link: https://ibm.webex.com/recordingservice/sites/ibm/recording/02aaaf37ba3710399fad0050568f090e/playback
Password: sMwAQHi3
- [Design exchange meeting on 08/04/21 regarding UI feasibility](https://ibm.box.com/s/6sk6lvj6uloymbychpqbi8k8elzknz2f)

### To Do 
- [ ] Follow up with internal users regarding Redfish language vs ASMI language
- [x] Follow up with Maury on timeline
- [ ] Document for Knowledge Center discussion
---
- [ ] Refresh date and time: The time stamp reflects the date and time of the last time when the entire table was refreshed. For example, if on using Reset Link function, entire table gets refreshed, then the time stamp needs to be updated. 
- [ ] Expansion row layout: If possible, use 2 separate layouts: one for primary links which don't have parent ID (e.g. Link 21) and other for secondary links which have parent ID (e.g. Link 337). Otherwise, use layout shown for Link 21. 
- [ ] Identify LEDs: This will show Location LED toggles only for the locations associated directly with a link. See [this for primary link](https://ibm.invisionapp.com/d/main#/console/15347903/320017939/preview) and [this for secondary link](https://ibm.invisionapp.com/d/main#/console/15347903/320017943/preview). If layout cannot be dynamic, then use Link 21's layout.
- [ ] ID and Parent ID: Need to be sortable. 
- [ ] Default sorting _(if possible)_: By ID. However, secondary links with parent ID should follow right after the corresponding parent link (e.g. in the prototype, links 337 to 342 should come after 21.
- [ ] Link Status: Need to be filterable. Show warning icon for 'Degraded' and 'Failed' status only. No other icons needed.
- [ ] Reset link: Takes around 10 seconds to finish, which is why we added a info toast with a time stamp. 

### cURL Commands and Redfish Response
**This will be based on the Chassis schema (refer Hardware Inventory story)**
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] [Redfish schema info slack conversation](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1628089229063300)
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
ASMI Info: https://www.ibm.com/support/knowledgecenter/POWER8/p8hby/pcietopology.htm

**Comment by derick-montague** [comment]
This seems like a page that would utilize a log service. I have set the Epic to `tbd`  until it's determined during the research of this feature.

**Comment by derick-montague** [comment]
## Screen Captures
![image](https://user-images.githubusercontent.com/1183515/104374701-e3be2500-54e7-11eb-846d-cc09529cc847.png)

**Comment by nicoleconser** [comment]
**Definition of PCIe**
> PCIe slots allow your motherboard to connect with your PC’s most critical components and provide key functionality. PCIe is short for **peripheral component interconnect express** and it’s primarily used as a standardized interface for motherboard components including graphics, memory, and storage. A PCIe or PCI express slot is the point of connection between your PC’s “peripheral components” and the motherboard. The term “PCIe card” and “expansion card” simply refers to hardware, like graphics cards, CPUs, solid-state drives (SSDs), or HDDs, you may add to your device through PCIe slots, making both catch-all terms for a variety of components.

**Comment by ParishrutB** [comment]
**For link properties and VPD**

Comments from @santoshpuranik 
There is a lot to be figured out for Link properties and PCIe VPD here:
- Where does the data come from? Most of this information has to be sent to us by PHYP
- How is the data going to be represented on BMC's D-Bus model?
- The Redfish API to represent this data and the relations.

@sampmisr  (SME for link properties) also communicated that is is a complex story and need to go though a few rounds of discussions.

Have requested for myself and @priyanka-pillai97 to be included in the meeting next week.

**For LEDs**
Email from Ravindra S Rao stating "the MEX LED support is targeted for 9/30."

**Comment by derick-montague** [comment]
Today's BMC leadership meeting discussed this. @santoshpuranik and @sampmisr will be setting up time with PHYP team. I have asked that @ParishrutB and @priyanka-pillai97 be included. There is quite a bit of backend that needs to be discussed and planned.

**Comment by derick-montague** [comment]
Design ready, Redfish API and backend work is not ready. Blocked until backend is ready.

**Comment by ParishrutB** [comment]
Added dependencies. @santoshpuranik says discussions are still going on and so there may be more to it.

**Comment by derick-montague** [comment]
This was reviewed in the Design Exchange meeting. There is a [list of key takeaways and to dos in Box](https://ibm.box.com/s/6sk6lvj6uloymbychpqbi8k8elzknz2f).

## Summary
- There is still work required to meet the user needs
- There are backend design discussions happening now
- It is expected that the design can be fully implemented with change mostly to naming coming from the Redfish API terminology and standards. 
    -  These need to be discussed with the ID and support teams.

**Comment by derick-montague** [comment]
Milestone update based on conversation with Maury. Brad Bishop is the BMC SME for this feature.

**Comment by derick-montague** [comment]
Further conversation from the design exchange meeting can be found here:

Summary of to do's from the meeting:
- [ ] Follow up with internal users regarding Redfish language vs ASMI language
- [ ] Follow up with Maury on timeline
- [ ] Document for Knowledge Center discussion
- [ ] Add PCIe HW topology to Support interfaces for SEET presentation (tenatively for September)
