### ISSUE TITLE
GUI : Service Indicators

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1478]
## SMEs
**BMC**: @lkammath 
**PHYP**: Adam Stallman 
**RAS**: George Ahrens

### Summary
The goal of this story is to finalize the fault and service indicators in the HW status and inventory page. 

**Two kinds of service indicators for specific FRUs**
(A) Fault LED (Cannot be switched on/off by a user) 
> Fault LED is mapped to the Health, so:
> fault LED ON = Health Critical
> fault LED OFF = Health OK
> fault LED OFF = Health Warning

(B) Identify LED (Can be switched on/off by a user)

**Four kinds of service indicators for systems**
(A) Power status (read only)
(B) System identify LED
(C) System attention LED
(D) Lamp test

#### Background
- [ ] TBD

#### End users
- Paul (Product Engineer)
- Tricia (Power Sys Admin)
- Noah (Junior Sys Admin w/o HMC) 

#### User Needs
- [ ] Needs a quick way to point out which hardware components need to be serviced/replaced.

#### References/Resources
- ASMI -> `Enclosure indicators` and `Indicators by Location Code`
- [eBMC Feature Item: 2.4.2, 2.4.3, 2.4.4](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)
- [ ] Link to Discovery folder
- 2.4.1: Server LED, 2.4.2: System Information Indicators
- 2.4.3: ~~Indicators by Location Code~~ `Not needed since the Indicator LED toggle will be associated with the component in the Hardware Inventory along with the Location Code`

### User Story
As a system admin
I need to know if a FRU is faulty and be able to turn on the LED service indicator
in order to easily locate the part that needs to be replaced.

### Use Case(s)
- [ ] Add use case(s)

### Design Goals
- [ ] Allow the user to easily identify and locate a faulty part for replacement
- [ ] Should be integrated in the Hardware Vital Product Data page

### InVision Prototype
- [Iteration 0](https://ibm.invisionapp.com/share/79O15948FTS)

### Community
- [ ] Created design review story in webui-vue repo
- [ ] Sent email to community sharing the design review story

#### Upstream
- Add System attention indicators section
- Add Power status/state (on or off)
- Add the System Identify LED

#### Downstream
- Add Lamp test

#### Unknown
- System Attention LED (Backend still in dicussion)

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
Expect the design for this to be part of the Hardware Status and VPD design #2210

**Comment by derick-montague** [comment]
## ASMI screen captures

### Indicators by Location code
![image](https://user-images.githubusercontent.com/1183515/105254197-9b85af00-5b46-11eb-8f53-5bdb51de6a29.png)

#### Error Message
![image](https://user-images.githubusercontent.com/1183515/105254213-a5a7ad80-5b46-11eb-8ae3-2dc7b62648db.png)

### Enclosure indicators
![image](https://user-images.githubusercontent.com/1183515/105254272-c7a13000-5b46-11eb-94eb-704ccbddba92.png)

![image](https://user-images.githubusercontent.com/1183515/105254280-cc65e400-5b46-11eb-94e7-648911f9adcb.png)

**Comment by nicoleconser** [comment]
From preliminary card sort (not validated w/ users) — this was to help us group all things indicator/LED related: 

![image](https://user-images.githubusercontent.com/15746733/105722124-f0307d80-5eea-11eb-8ddc-ac7ef5a38ef5.png)

**Comment by priyanka-pillai97** [comment]
### Important Slack Conversations
Participants: Gunnar, Vishwa and Santosh
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1615357717014500?thread_ts=1611132244.032200&cid=C0Q6TQP5Z

Summary: 
Fault LED is mapped to the Health, so: 
1.  fault LED ON = Health Critical + Warning
2. fault LED OFF = Health OK

![FaultLED+Health_Reference](https://user-images.githubusercontent.com/61419618/115365580-23c92e00-a1e2-11eb-9fed-80bf0af7a3a4.png)

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43959

**Comment by Srisuk** [comment]
System attention indicator will be available by Sept 2021 stated by @lkammath ([here](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1626177973266900?thread_ts=1626173116.265600&cid=C0Q6TQP5Z))
