### ISSUE TITLE
On new PEL, remove old PEL(s) to free up space if necessary

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1481]
There are existing rules on how to choose which logs to delete.   I'll get them in here at some point.

**Comment by spinler** [comment]
Note that if there is a corresponding openbmc log, it should be deleted too, however there may not be one if someone deleted it using Redfish.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/34430

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/34430 merged
