### ISSUE TITLE
GUI : Power Management - Idle Power Saver

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1487]
## SMEs
**BMC**: @marthabroyles, Chris Cain, @gtmills 
**PHYP**: Stuart Jacobs
**RAS**: Kanisha Patel

### Background
- Idle power saver: When system utilisation falls into a certain threshold, this mode is activated. It is set by a range of threshold to enter and exit. 

### Related stories:
- Power saver modes: #1485
- Power cap settings: #2865 

### Current ASMI Screen
![image](https://user-images.githubusercontent.com/1183515/102216600-01747c00-3ea1-11eb-9308-1b16ce223d63.png)

### Proposed webui-vue screen
![image](https://user-images.githubusercontent.com/1183515/130301302-08b1369a-98bc-4c34-9a4d-18fcc250d597.png)

## Prototype
- Idle power saver https://ibm.invisionapp.com/d/main#/console/15347903/320023962/preview

## References/Resources
- [eBMC Feature Item: 3.5.3](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)
- eBMC GUI Feature Tracker ID: 96
- [Gerrit Redfish Design document](https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/38786/6/designs/ibm/system-power-mode.md)
- Conversation about thresholds https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1625738516227000
### Community
- [ ] Created design review story in webui-vue repo
- [ ] Sent email to community sharing the design review story

### UX Flow / Interaction Requirements
- [ ] Feature breakdown
- [ ] Update overview page with power idle property - show Disabled or "threshold to enter - threshold to exit" if enabled.[Mockup](https://ibm.invisionapp.com/share/C2O1E629BRS#/screens/320050499)

### cURL Commands and Redfish Response
```
$ curl -s -k -X GET https://$bmc/redfish/v1/Systems/system | grep -A6 IdlePowerSaver
  "IdlePowerSaver": {
    "Enabled": false,
    "EnterDwellTimeSeconds": 240,
    "EnterUtilizationPercent": 8,
    "ExitDwellTimeSeconds": 10,
    "ExitUtilizationPercent": 12
  },

$ curl -k -X PATCH -d '{"IdlePowerSaver":{"Enabled":true}}' https://$bmc/redfish/v1/Systems/system

$ curl -k -X PATCH -d '{"IdlePowerSaver":{"Enabled":false,"EnterUtilizationPercent":8,"EnterDwellTimeSeconds":240,"ExitUtilizationPercent":12,"ExitDwellTimeSeconds":10}}' https://$bmc/redfish/v1/Systems/system
```

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by dixsie** [comment]
Redfish may be available end of September.

**Comment by cjcain** [comment]
Can you add (if you don't already have) a check to make sure the enter utilization <= exit utilization when values get changed?

When violated, that would lead to a case where the utilization could meet both enter and exit conditions:
    Enter IPS condition when utilization is below enter utilization
    Exit IPS condition when utilization is above exit utilization

The code will prevent using values not meeting that condition, but best to notify the user when they are attempting to change the parameters.

**Comment by dixsie** [comment]
b/e is available in driver 32+

**Comment by dixsie** [comment]
![image](https://user-images.githubusercontent.com/26472611/144908333-08096898-9bad-4f7b-8c60-a175465c32e5.png)

 
We can leave out the "Value must be between..." help text for now

**Comment by Srisuk** [comment]
Resolved by https://github.ibm.com/openbmc/webui-vue/pull/34
