### ISSUE TITLE
GUI : Debug Virtual TTY / Hypervisor Command Line

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1492]
## SMEs
**BMC**: Gunnar Mills, @sunharis - (ASMI/FSP)
**PHYP**: Adam Stallman
**RAS**: George Ahrens

### Summary
The Debug virtual tty is a console that is used similar to the Serial over LAN console. The purpose to get information from the Hypervisor. This feature exists in ASMI today, but the suggestion from the Gunnar Mills and Brad Bishop is that the BMC GUI does not need a virtual tty console. Instead, it needs a 2nd SoL console for interacting with the Hypervisor.

### User Story
As a PE or Power Hypervisor support, we use it to access the hypervisor prompt. It has also been used for Open Firmware debug sessions for AIX/Linux partitions.

### InVision Prototype
Service login consoles https://ibm.invisionapp.com/d/main#/console/15347903/320050117/preview
Serial over LAN console https://ibm.invisionapp.com/d/main#/console/15347903/320050507/preview

### References/Resources
- eBMC Feature Item: 3.6.5
- Discovery doc: https://ibm.ent.box.com/notes/837106898190

### UX Flow / Interaction Requirements
- Operating system (or Host) command line - accessible to all. 
- BMC command line - accessible only to service login.
- Hypervisor command line - accessible only to service login after entering a macro. 
- [ ] Add  `wss://${window.location.host}/console1` in websocket plugin line 77 (hypervisor console)
- [x] console 0 is SOL console
- [ ] `wss://${window.location.host}/bmc-console` for BMC console
- [ ] Macro modal not required, user can enter this command in the console

**Connecting to PHYP console**
WIP [in discussion here.](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1627545295087000?thread_ts=1588709628.377800&cid=C0Q6TQP5Z)
1. Go to "Service login consoles" page
2. BMC console shown by default
3. Select Hypervisor console from dropdown
4. Immediately show a popup for the macro
5. After submitting macro, GUI activates hypervisor console _and_ simultaneously connects to it. 

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
@gtmills @nicoleconser - At the workshop in 5/7/20 with Joe M, Russel Y, Justin T, @bradbishop, and @mzipse it was determined that this feature is not needed. Based on my notes it seemed that this could be performed with the SoL console. 

- Is this an accurate determination?
- Can this story be closed? 

We did note, which i am capturing in another story that we need to plan for future work the need to support multiple SoL consoles in the GUI.

**Comment by gtmills** [comment]
@derick-montague Sort of. We are going to have 2 serial consoles on eBMC. If we want to track that work in a different story, that is mine. More information can be found at: 
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1588709628377800

**Comment by dixsie** [comment]
> Need to follow up and find out what to do with the BMC console when selecting hypervisor and vice versa? Do the consoles terminate?

Users can terminate the connection in the console, the dropdown will hide/show the selected consoles

**Comment by dixsie** [comment]
@Srisuk system should be powered on to get a response

**Comment by Su-kan** [comment]
Resolved by https://github.ibm.com/openbmc/webui-vue/pull/50
