### ISSUE TITLE
GUI : Power Restore Policy

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1495]
## SME
**BMC**: Andrew Geissler - `@andrewg `

### Summary
When configuring the power restore policy, the following three options are available: 
- Always Off: The server will remain powered off even when power is restored.
- Last state: System will go back to the same state before the power disturbance. (The server will automatically be powered on when power is restored if the server was powered on at the time that the power failure occurred. Otherwise, the server power will remain off when power is restored)
- Always On: The server will automatically power on when power is restored. 

#### Background
- Use Case: To configure how the server reacts when the power is restored after a sudden power disturbance. 
- Need: An unexpected power outage can happen to a customer's system due to any of the following reasons. 
    (1) an unexpected power off 
    (2) a lot of them connect to UPS systems or 
    (3) there's some sort of blackout issue

#### End users
- Tricia the Traditional Power Systems Admin (with HMC) 

#### User Needs
- Define the behavior when there is a power disturbance. 
- Clear assistance to understand the outcome for each option

### User Quotes
- [ ] TBD

### References
- eBMC Feature Item: 4.2.1
- ASMI Content Inventory Item: 2.2 Auto Power Restart
- [feature discovery folder](https://ibm.ent.box.com/notes/667084037827)

### User Story
As an admin, I need to configure how the server reacts when the power is restored after a sudden power disturbance,
so that the system will avoid any undefined behavior when the power is back on. 

### InVision Prototype
1. [Iteration 0 - Low-fidelity](https://ibm.invisionapp.com/share/JPO0RGV8N9Z)

### UX Flow / Interaction Requirements
- [ ] Feature breakdown

#### Redfish Schema
`/redfish/v1/JsonSchemas/ComputerSystem/ComputerSystem.json`
```
"PowerRestorePolicyTypes": {
    "description": "The enumerations of PowerRestorePolicyTypes specify the choice of power state for the system when power is applied.",
    "enum": [
        "AlwaysOn",
        "AlwaysOff",
        "LastState"
    ],
    "enumDescriptions": {
        "AlwaysOff": "The system always remains powered off when power is applied.",
        "AlwaysOn": "The system always powers on when power is applied.",
        "LastState": "The system returns to its last on or off power state when power is applied."
    },
    "type": "string"
},
```
#### Redfish Endpoint and property
- `/redfish/v1/Systems/system/`
- `PowerRestorePolicy`

#### cURL
```
export bmc=<add IP address>

// Get token
export token=`curl -k -H "Content-Type: application/json" -X POST https://${bmc}/login -d '{"username" :  "root", "password" :  "0penBmc"}' | grep token | awk '{print $2;}' | tr -d '"'`

// Get Power Restore Policy
curl -k -H "X-Auth-Token: $token" https://$bmc/redfish/v1/Systems/system/

// Set Power Restore Policy
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"PowerRestorePolicy": "AlwaysOff"}' https://${bmc}/redfish/v1/Systems/system/
```

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
We can fully implement this now. There are some changes that need to be handled by the backend for handling brown outs and black outs for Rainier and Everest systems. Any changes to the backend (#870, #1860) should not impact the GUI

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39104
