### ISSUE TITLE
Design and implement openBMC REST API to Renew Certificate Signing Request  

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#15]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ojayanth](https://github.com/ojayanth)**
_Thursday Aug 02, 2018 at 10:55 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3338_

----

  Provide d-bus interface to create CSR. 
   Implementation of the  renew Certificate Signing Request.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
This is not a valid use case based latest Redfish spec.
