### ISSUE TITLE
System: Initiate dump when host is checkstopped

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#150]
<a href="https://github.com/cdeadmin"><img src="https://avatars1.githubusercontent.com/u/23025061?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cdeadmin](https://github.com/cdeadmin)**
_Monday Dec 18, 2017 at 16:03 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2725_

----

<cde:info> SW411583 </cde:info>

**Comment by rfrandse** [comment]
<a href="https://github.com/geissonator"><img src="https://avatars2.githubusercontent.com/u/1612261?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geissonator](https://github.com/geissonator)**
_Monday Dec 18, 2017 at 21:04 GMT_

----

The host team has requested we generate a BMC dump when a checkstop occurs.  The main reason for this is that our dump will collect the host console log which is very useful for debugging the different checkstops.  This issue will be used to add the host console to the error based BMC dumps and to collect this BMC dump when the org.open_power.Host.Boot.Error.Checkstop error is created.

**Comment by rfrandse** [comment]
<a href="https://github.com/rfrandse"><img src="https://avatars3.githubusercontent.com/u/15894767?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rfrandse](https://github.com/rfrandse)**
_Wednesday Dec 27, 2017 at 12:45 GMT_

----

<https://gerrit.openbmc-project.xyz/8349> Enable obmcconsole script for elog type error
Resolves  #2725 System: Initiate dump when host is checkstopped

**Comment by rfrandse** [comment]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ojayanth](https://github.com/ojayanth)**
_Friday Jan 05, 2018 at 13:53 GMT_

----

Need to redesign the code to address the review comments from @bradbishop

**Comment by rfrandse** [comment]
<a href="https://github.com/rfrandse"><img src="https://avatars3.githubusercontent.com/u/15894767?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rfrandse](https://github.com/rfrandse)**
_Monday Jan 22, 2018 at 14:41 GMT_

----

<https://gerrit.openbmc-project.xyz/8349> Enable obmcconsole script for elog type error
Resolves  #2725 System: Initiate dump when host is checkstopped

**Comment by rfrandse** [comment]
<a href="https://github.com/devenrao"><img src="https://avatars3.githubusercontent.com/u/26330444?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [devenrao](https://github.com/devenrao)**
_Thursday May 24, 2018 at 05:24 GMT_

----

Background:
Currently BMC dump is created based on one of the following
        * User Initiated
        * Application core
        * Error Log of type "Internal failures"
        * Host Checkstop (to be done)
..............................................................................
Extending Dump Infrastructure:
The existing Dump framework can be extended as follows to support new Dump type
and/or new dump content:
1) Existing Dump type with existing plugin(s)
     * Annotate the plugin with the dump type.
2) Existing Dump type with new plugin(s)
     * Provide the plugin under plugins.d
     * Annotate the plugin with the dump type.
3) A new Dump type with existing plugins
     * Configure the new dump type in sample.conf
     * Annotate the plugin with the dump type.
4) A new Dump type with new plugin(s)
     * Configure the new dump type in sample.conf
     * Provide the plugin under plugins.d
     * Annotate the plugin with the dump type.
..............................................................................
Motivation & Proposal:
The current dump management framework allows to collect debug data upon a User
request. Also additional debug data can be collected for internal failures over
and above what is present in the Error Log. This proposal extends the framework
to associate dump creation with specific Error logs.

The design guideline is to create a dump based on the Error code.  The
framework consists of a json based policy configuration which associates the
Error Log type with the corresponding Dump type. This framework provides the
flexibility to configure the dump collection behavior for an existing Error Log
type and/or for new Error Log types introduced in future. For every Error Log
type that must trigger a Dump, there must be configuration info int he json
policy file. The policy configuration is compiled binary config info which will
be used by Dump Manager.
..............................................................................

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Merged into master yesterday.
