### ISSUE TITLE
GUI : Memory Resource Mgmt - Memory - Logical Memory Block Size

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1501]
## SMEs
**BMC**: @sampmisr  
**PHYP**: Ken Vossen, Stuart Jacobs, Tom Sand 
**RAS**: ~~Justin Thaler~~ George Ahrens
**Host Boot**: Nick Bofferding
**PowerVM**: David Stanton, Adam Stallman
**AIX**: Brian Veale
**Designers**: @priyanka-pillai97 

### Summary
There are two other features that are part of the Resource management/Memory page
- #3304 
- #2421  

#### Background
- Logical Memory Block Size: The logical block size is the size of the blocks that the VM uses to read or write files. Option to enhance the performance of the managed system by changing the logical-memory block size and enabling cache locking mode. It can be changed at run time, but change will get into affect after IPL.

#### End users
- Paul (Product Engineer)
- Tricia (Power Sys Admin)
- Noah (Junior Sys Admin w/o HMC) - most, but not all

### References/Resources
- [eBMC Feature Item: 4.12.1, 4.12.2, 4.12.3, 4.12.4, 4.12.5](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)
- [feature discovery folder ](https://ibm.ent.box.com/notes/678801706046)
- user research notes*: 
- user research synthesis: https://ibm.box.com/s/r23b7z4dwui1t4t9dkx7f76t5872lrvc
- `#openbmc-celogin` slack channel
- `#hmc-peloogin` slack channel

### User Story
As an **admin/PE**,
I need to **manually or automatically change the values of my Logical memory block size**
in order to **enhance the system performance.**

### InVision Prototype
- Final: https://ibm.invisionapp.com/share/PYO1HKPE25X

### Community
Down stream only

### UX Flow / Interaction Requirements
- [ ] `Logical memory block size`:
- [ ] Need to verify the the BIOS attributes needed for this story
- [x] Need to verify the ability to show pending reboot states if a value has changed that won't be applied until the next reboot (IPL)
    - IPL will be based on a Pending BIOS attribute - [slack thread](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1628193270099200)

### cURL Commands and Redfish Response
- [ ] https://{$bmc}/redfish/v1/Registries/BiosAttributeRegitry/BiosAttributeRegistry
- [ ] Add cURL commands

```
"AttributeName": "hb_memory_region_size",
"CurrentValue": "256MB",
"DefaultValue": "256MB",
"DisplayName": "Memory Region Size (pending)",
"HelpText": "Specifies the size of the logical memory block the system uses to read memory, requires a reboot for a change to be applied.",
"ReadOnly": false,
"Type": "Enumeration",
"Value": [
{
"ValueName": "128MB"
},
{
"ValueName": "256MB"
}
]
},
```

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
@priyanka-pillai97 - I added a new SME. Brian Veale for AIX. Todd Rosedahl asked us to discuss the need for a discussion with both PHYP and AIX. He suggested the following people.

>  I would think this is a PHYP/AIX discussion on what these are used for.  We need Stuart Jacobs or Dave Stanton and Brian Veale to weigh in.  So is this in being investigated by someone?

**Comment by derick-montague** [comment]
## Managing your system with ASMI
- [Changing the logical memory block size](https://www.ibm.com/support/knowledgecenter/9080-M9S/p9hby/logicalmem.htm)
- [System memory page size](https://www.ibm.com/support/knowledgecenter/9080-M9S/p9hby/sysmemorypagesetup.htm)

**Comment by derick-montague** [comment]
Verified all BIOS settings should be ready in the A.1.203 milestone

**Comment by derick-montague** [comment]
All settings listed in this Slack conversation. Currently only @gtmills, @nicoleconser, @mzipse  and @derick-montague have access to this conversation.


1. Default partition environment (AIX, i5/OS, Linux) — on boot page, needs to be validated, keeping in GUI
1. IPL Mode (i5 OS only) — on boot page, needs to be validated, keeping in GUI
1. Logical Memory Block Size — performance setting; keeping in GUI
1. System Memory Page Setup — performance setting; keeping in GUI
1. Predict Dynamic Memory Dealloc — performance setting; keeping in GUI
1. ~~HW Page Table Size~~: dropped
1. ~~Dispatch Wheel Time~~: dropped
1. I/O Adapter Enlarged Capacity — discovery research not begun; unclear if keeping in GUI
1. Virtual TPM — discovery research not begun; unclear if keeping in GUI
1. ~~I/O Enclosure config~~ Configure I/O Enclosures
    - @Derick Montague is tackling foundational questions we have about this related to SPCN / LEDs; keeping in GUI
1. I/O Enclosure FW Policy Update  — not sure what this is, have not seen it in ASMI

**Comment by derick-montague** [comment]
@ParishrutB @priyanka-pillai97 @nicoleconser - We didn't discuss this one in sprint planning today. What is our status on this?

**Comment by derick-montague** [comment]
I updated status in the discovery document for Logical Memory Block size

**Comment by derick-montague** [comment]
This is an overarching story that contains BIOS settings that we need to breakdown and associate the settings with the expected pages/views/experiences.

**Comment by derick-montague** [comment]
Looks like Logical Memory Block Size will be merged soon: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/41296

**Comment by priyanka-pillai97** [comment]
In discussion: Whether desired state is saved somewhere before an IPL
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1622791063425700

**Comment by derick-montague** [comment]
This could be ready now. I am updating the milestone to reflect conversation with Maury. There is a [spreadsheet with the BIOS attribute status](https://ibm.box.com/s/y2ifgfgv9de24s43c7hnmenp6vi5ffng)

**Comment by dixsie** [comment]
Instead of a radio button, automatic and manual will be in a dropdown only

**Comment by Srisuk** [comment]
@derick-montague If we are changing automatic and manual to dropdown options then how about the sizes which are coming currently below the manual setting.

**Comment by sandeepasingh116** [comment]
Resolved by : https://github.ibm.com/Sandeepa-Singh/webui-vue/pull/new/Logical-Memory

**Comment by derick-montague** [comment]
> @derick-montague If we are changing automatic and manual to dropdown options then how about the sizes which are coming currently below the manual setting.

I am not sure what you mean by `sizes`.

**Comment by mzipse** [comment]
Closing.  Work is complete.
