### ISSUE TITLE
GUI : Network Services - Network Access

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1503]
## SMEs
**BMC**: @ratagupt 
**PHYP**: Tom Burks
**RAS**: Justin Thaler

### Summary
This feature allows the user to determine IP addresses that are allowed or blocked. In ASMI, it lives in the `Network Services` section of the IA. 

#### Background
It is not clear where this feature should live in the eBMC IA. Some discovery work has already been conducted.

#### ASMI Screen Capture
![image](https://user-images.githubusercontent.com/1183515/102167824-cba9a600-3e54-11eb-8696-edb34cd7532a.png)

#### End users
- [ ]  TBD

#### User Needs
- [ ] TBD

#### User Quotes
- [ ] TBD

### References
- [feature discovery doc](https://ibm.ent.box.com/notes/666323518695)

### User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

### Use Case(s)
- [ ] Add use case(s)

### Design Goals
- [ ] Goal 1
- [ ] Goal 2
- [ ] Goal 3

### InVision Prototype
- [ ] Iteration 0
- [ ] Iteration 1
- [ ] Iteration 2
- [ ] Iteation 3 (Final)

### Community
- [ ] Created design review story in webui-vue repo
- [ ] Sent email to community sharing the design review story

### UX Flow / Interaction Requirements
- [ ] Feature breakdown

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by ParishrutB** [comment]
Tasks

- [ ] 1
- [ ] 2
- [ ] 3

**Comment by derick-montague** [comment]
Updated milestone here and in Mural based on https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1592917265480100?thread_ts=1592408207.395400&cid=C0Q6TQP5Z

**Comment by derick-montague** [comment]
It is likely that this fits nicely into the Security Panel #2819, but there isn't a design for this page that supports elements other than toggles.

**Comment by derick-montague** [comment]
Milestone updated based on feature sync meeting with Maury and Gunnar on 3/5/21.

**Comment by sandeepasingh116** [comment]
@gtmills and @mzipse should we migrate this to jira?

**Comment by rfrandse** [comment]
tracking in jira
