### ISSUE TITLE
phosphor-regulators: Define system type -> config file name mapping

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#1505]
The phosphor-regulators application is driven by a JSON configuration file (config file).

Each system type will have its own config file, since each system has different regulators, voltage requirements, hardware work-arounds, etc.

The config files with have unique names based on the system type, such as foo_2u_vrm_config.json for a 2U version of a "Foo" system.

At run-time, the phosphor-regulators application will need to determine the correct config file for the system type it is running on. The current plan is that EntityManager will determine the system type and store the associated config file name in a D-Bus object path. The phosphor-regulators application will get the config file name from D-Bus.

This work item covers whatever is necessary to define the mapping from system types to regulator config file names.  At this time I am guessing this will involve changes to an EntityManager JSON file, but other changes may be needed as well.

Not all system types will use the phosphor-regulators application, so it must be valid for a system type to not map to any regulators config file.

**Comment by amboar** [comment]
Why do we want phosphor-regulators to get the config path from entity manager? This seems like we're spreading internal implementation details of phosphor-regulator across the (BMC) system architecture. Isn't it enough for EntityManager to identify the platform type and have phosphor-regulators use the platform type to determine the location of the appropriate configuration file?

We have a similar (but different) problem for GPIO management. Looping in @bradbishop because I've had discussions with him along these lines.

**Comment by bradbishop** [comment]
> On Dec 15, 2019, at 6:25 PM, Andrew Jeffery <notifications@github.com> wrote:
> 
> Why do we want phosphor-regulators to get the config path from entity manager? This seems like we're spreading internal implementation details of phosphor-regulator across the (BMC) system architecture.  

Can you elaborate on how we are doing that?

> Isn't it enough for EntityManager to identify the platform type and have phosphor-regulators use the platform type to determine the location of the appropriate configuration file?

It might be.  I think this works when there is a static, 1 to 1 mapping between an applications data and the system type.  Is that the case with phosphor-regulators?  I’m assuming so if we are just putting config file paths in EM.

We could revisit if at a later time phosphor-regulators becomes dependent on the presence of FRUs other than the system itself (system type).

Shawn I am not opposed to this tweak if you don’t find any issues with it and want to make a slight course correction here.

**Comment by smccarney** [comment]
Brad and Andrew - Thank you for the comments.  I am flexible on how this works; I'll follow whatever the best practice is.

Brad, you and I discussed how this would work a few weeks ago when the move to EntityManager (EM) was gaining traction.  I thought what I described in this issue was your recommended design.  EM would determine the system type and then put a VRM config file name property on DBus.  Then my application would get the config file name from the DBus property.

Is the recommendation instead to just get a system type from EM and then perform the system type -> config file name mapping within my own repo?  That is easier for me, as it avoids the need for changes in the EM repo.  I could define that mapping in a separate JSON file within my repo.

My only requirement is that I need fairly detailed system type information.  On some systems, just knowing the base system type ("Foo") will probably be sufficient.  All variants of Foo will share a common VRM config file.

But on other system types ("Bar"), I will probably need to know whether it is a 2u or 4u Bar.  I may also need to know whether it is the newer Bar version that supports a new PCI standard.  Those system differences sometimes drive significant VRM hardware differences that result in different VRM config files.

So can EM provide not only the base system type (Foo vs. Bar) but also information like whether it is a 2u vs. 4u system?  If so, that would be fine with me.  I assume this information would be on D-Bus?  And it could be obtained by using ObjectMapper and querying for a documented D-Bus interface?

**Comment by bradbishop** [comment]
> On Dec 16, 2019, at 12:56 PM, Shawn McCarney <notifications@github.com> wrote:
> 
> Brad and Andrew - Thank you for the comments. I am flexible on how this works; I'll follow whatever the best practice is.

I think we are establishing best practices right now :-)

> 
> Brad, you and I discussed how this would work a few weeks ago when the move to EntityManager (EM) was gaining traction.

We did.

> I thought what I described in this issue was your recommended design. 

It was.

> Is the recommendation instead to just get a system type from EM and then perform the system type -> config file name mapping within my own repo? That is easier for me, as it avoids the need for changes in the EM repo. I could define that mapping in a separate JSON file within my repo.

Yes IIUC that is the suggestion.  Andrew can you confirm?

> My only requirement is that I need fairly detailed system type information. On some systems, just knowing the base system type ("Foo") will probably be sufficient. All variants of Foo will share a common VRM config file.
> 
> But on other system types ("Bar"), I will probably need to know whether it is a 2u or 4u Bar. I may also need to know whether it is the newer Bar version that supports a new PCI standard. Those system differences sometimes drive significant VRM hardware differences that result in different VRM config files.

> So can EM provide not only the base system type (Foo vs. Bar) but also information like whether it is a 2u vs. 4u system? If so, that would be fine with me. I assume this information would be on D-Bus? And it could be obtained by using ObjectMapper and querying for a documented D-Bus interface?

Sure - We have to do this anyway, to create inventory dbus objects to serve up for Redfish.  So this is certainly an option.

Andrew - would it be fair to say you are (effectively) suggesting we move the logic for mapping application policy to system configuration from EM config files to the application (method TBD/ up to the application).  A couple nice things about delegating that to EM is each application need not implement that, and all the policy <-> configuration mapping data is centrally managed, rather than distributed across a zillion applications with differing mapping implementations.

**Comment by amboar** [comment]
> On Dec 15, 2019, at 6:25 PM, Andrew Jeffery ***@***.***> wrote: Why do we want phosphor-regulators to get the config path from entity manager? This seems like we're spreading internal implementation details of phosphor-regulator across the (BMC) system architecture.
> Can you elaborate on how we are doing that?

Why should EntityManager care where the phosphor-regulators configuration file lives? Say it's in `/usr/share/phosphor-regulators/witherspoon.conf` but a user wants to tweak some settings by putting a modified copy of the configuration in `/etc/phosphor-regulators/witherspoon.conf` ("usual" UNIX-ish configuration hierarchy, principle of least surprise). How would entity-manager know which to present? Does the user need to modify the EntityManager configuration as well? I feel like that's an unnecessary layer of indirection.

> Isn't it enough for EntityManager to identify the platform type and have phosphor-regulators use the platform type to determine the location of the appropriate configuration file?
> It might be. I think this works when there is a static, 1 to 1 mapping between an applications data and the system type. Is that the case with phosphor-regulators? I’m assuming so if we are just putting config file paths in EM. We could revisit if at a later time phosphor-regulators becomes dependent on the presence of FRUs other than the system itself (system type). 

But phosphor-regulators should be querying EM/DBus for the presence of those FRUs and configuring itself appropriately right? My understanding of EntityManager is it's the DBus implementation of [IFTTT](https://en.wikipedia.org/wiki/IFTTT). In my mind phosphor-regulators just needs some approach to probe the system to determine the configurations it needs to load.

**Comment by amboar** [comment]
> Is the recommendation instead to just get a system type from EM and then perform the system type -> config file name mapping within my own repo? 
> Yes IIUC that is the suggestion. Andrew can you confirm?

Yes, this is what I am suggesting

> That is easier for me, as it avoids the need for changes in the EM repo. I could define that mapping in a separate JSON file within my repo.

Hopefully our problem isn't so complex so as to require configuration files for configuration files. You have me worried here.

If we break down our problems right we just need each component to discover its own configuration, rather than try to orchestrate a set of configuration files with another configuration file.

I think the key thing is for "components" or "FRU support" code in phosphor-regulators to probe the system for whether it's required. Is this feasible?

> My only requirement is that I need fairly detailed system type information. On some systems, just knowing the base system type ("Foo") will probably be sufficient. All variants of Foo will share a common VRM config file. But on other system types ("Bar"), I will probably need to know whether it is a 2u or 4u Bar. I may also need to know whether it is the newer Bar version that supports a new PCI standard. Those system differences sometimes drive significant VRM hardware differences that result in different VRM config files. So can EM provide not only the base system type (Foo vs. Bar) but also information like whether it is a 2u vs. 4u system? If so, that would be fine with me. I assume this information would be on D-Bus? And it could be obtained by using ObjectMapper and querying for a documented D-Bus interface?
> Sure - We have to do this anyway, to create inventory dbus objects to serve up for Redfish. So this is certainly an option. Andrew - would it be fair to say you are (effectively) suggesting we move the logic for mapping application policy to system configuration from EM config files to the application (method TBD/ up to the application). A couple nice things about delegating that to EM is each application need not implement that, and all the policy <-> configuration mapping data is centrally managed, rather than distributed across a zillion applications with differing mapping implementations.

It sounds like your concern here is effectively code sharing? Otherwise, if each application has different policies about which configuration should be chosen, how is EntityManager to know? We'd be encoding the same logic there? If the problem boils down to code sharing, then if it's enough of a problem we could create a shared object to contain the common logic.

**Comment by smccarney** [comment]
> Why should EntityManager care where the phosphor-regulators configuration file lives? Say it's in `/usr/share/phosphor-regulators/witherspoon.conf` but a user wants to tweak some settings by putting a modified copy of the configuration in `/etc/phosphor-regulators/witherspoon.conf` ("usual" UNIX-ish configuration hierarchy, principle of least surprise). How would entity-manager know which to present? Does the user need to modify the EntityManager configuration as well? I feel like that's an unnecessary layer of indirection.

I do plan to support loading the config file from either of those locations.  It is documented here:  https://github.com/openbmc/phosphor-power/blob/master/phosphor-regulators/docs/config_file/README.md#installation

For that reason, I am only looking for a mapping from system type to the *base name* of the config file.  The containing directory will be one of the two above.

> Hopefully our problem isn't so complex so as to require configuration files for configuration files. You have me worried here.
> If we break down our problems right we just need each component to discover its own configuration, rather than try to orchestrate a set of configuration files with another configuration file.
> I think the key thing is for "components" or "FRU support" code in phosphor-regulators to probe the system for whether it's required. Is this feasible?

There is a one config file for each system type.  It defines all the VRM configuration and monitoring that should be done for that system type.  This config file is normally created and maintained by the hardware team.  It allows them to perform the detailed configuration that is required for that system type.  The same VRM type (for example, an IR35221) is configured differently depending on the type of rail it is producing and what hardware work-arounds are needed by the system type.

All I need is a mechanism that will allow me to determine the current system type and map that to the base name of the corresponding config file.

On a prior system I worked on, the system type was obtained from the "IM" VPD keyword value.  The keyword value had the right level of detail, in that indicated not only that it was a "Foo" system but also that it was the "2U" variant.

I was hoping to get the corresponding information (system type and 2u vs. 4u) from a D-Bus property on a well-documented interface.  This would provide a loose coupling between the source of the data (such as EM) and my application.  EM wouldn't have to know about my application, and my application wouldn't have to know that EM is the source of the data.

If that wouldn't work well, I could look at a VPD keyword value.  If the keyword name varies depending on system type/manufacturer, then I could make the keyword name configurable.

**Comment by amboar** [comment]
> > Why should EntityManager care where the phosphor-regulators configuration file lives? Say it's in `/usr/share/phosphor-regulators/witherspoon.conf` but a user wants to tweak some settings by putting a modified copy of the configuration in `/etc/phosphor-regulators/witherspoon.conf` ("usual" UNIX-ish configuration hierarchy, principle of least surprise). How would entity-manager know which to present? Does the user need to modify the EntityManager configuration as well? I feel like that's an unnecessary layer of indirection.
> 
> I do plan to support loading the config file from either of those locations. It is documented here: https://github.com/openbmc/phosphor-power/blob/master/phosphor-regulators/docs/config_file/README.md#installation
> 
> For that reason, I am only looking for a mapping from system type to the _base name_ of the config file. The containing directory will be one of the two above.

Great.

> 
> > Hopefully our problem isn't so complex so as to require configuration files for configuration files. You have me worried here.
> > If we break down our problems right we just need each component to discover its own configuration, rather than try to orchestrate a set of configuration files with another configuration file.
> > I think the key thing is for "components" or "FRU support" code in phosphor-regulators to probe the system for whether it's required. Is this feasible?
> 
> There is a one config file for each system type. It defines all the VRM configuration and monitoring that should be done for that system type. This config file is normally created and maintained by the hardware team. It allows them to perform the detailed configuration that is required for that system type. The same VRM type (for example, an IR35221) is configured differently depending on the type of rail it is producing and what hardware work-arounds are needed by the system type.
> 
> All I need is a mechanism that will allow me to determine the current system type and map that to the base name of the corresponding config file.

Right.

> 
> On a prior system I worked on, the system type was obtained from the "IM" VPD keyword value. The keyword value had the right level of detail, in that indicated not only that it was a "Foo" system but also that it was the "2U" variant.
> 
> I was hoping to get the corresponding information (system type and 2u vs. 4u) from a D-Bus property on a well-documented interface. This would provide a loose coupling between the source of the data (such as EM) and my application. EM wouldn't have to know about my application, and my application wouldn't have to know that EM is the source of the data.
> 
> If that wouldn't work well, I could look at a VPD keyword value. If the keyword name varies depending on system type/manufacturer, then I could make the keyword name configurable.

So my suggestion was that all these implementation details get put in a probe() function for a given backend, where probe() returns success if the backend finds the system it's designed for otherwise failure. That way we're keeping all the implementation details of determining which backend to choose inside the backend itself.

**Comment by smccarney** [comment]
> So my suggestion was that all these implementation details get put in a probe() function for a given backend, where probe() returns success if the backend finds the system it's designed for otherwise failure. That way we're keeping all the implementation details of determining which backend to choose inside the backend itself.

OK.  I can definitely see the wisdom in encapsulating the system type detection so that it can be pluggable.

For the purposes of this issue/work effort, I'll need to pick a specific implementation for at least the first system (backend).

Should I assume that EM will provide a D-Bus property and worry about the exact interface/property name later?  Or assume VPD?  I'll update the title and comments accordingly.

**Comment by amboar** [comment]
> Should I assume that EM will provide a D-Bus property containing the system type and 2u/4u distinction? And worry about the exact interface/property name later?
> 
> Or should I assume I need to look at a VPD keyword?
> 
> I'll update the title and comments accordingly.

IMO as long as you define the interfaces between the application and the backends (i.e. at least the probe() method) your first backend chould simply have:

```
int my_backend_probe(void)
{
    return 0; // Success
}
```

And we can leave the details to later.

**Comment by smccarney** [comment]
Brad Bishop and I met today to discuss this issue.

As Brad has become more familiar with EntityManager, he now believes it is not the best way to provide this mapping.  EntityManager does not need to be involved.

Below are the plans we agreed upon.  Plan A is the goal, and Plan B is a backup.

**Plan A**
* The VPD application will read the IM keyword and store the value on D-Bus.  This value is numeric (4 hex bytes I think?)
* Some application (TBD) will map this numeric value to a string like "rainier_2s2u".  Note that the internal (code) name should be used, as the external name is not available until late in the release cycle.
* Brad Bishop will define a D-Bus interface and property that will contain this string IM value ("rainier_2s2u").  The property would be named something like "SystemType" or "InternalSystemType".
* The phosphor-regulators application will define a C++ abstract base class like "ConfigFileNameLocator" that will define a pure virtual method for finding the config file name.
* A concrete subclass like "DBUSConfigFileNameLocator" will be created that will get the system type from the D-Bus interface/property that Brad defined.  A ".json" suffix will be added to the system type to form the expected file name.  No mapping would be required.
* In the future, other concrete subclasses of "ConfigFileNameLocator" could be defined to find the file name in a different way.  Conditional compilation could be used if necessary.

**Plan B**
Similar to Plan A, but with the following exceptions:
* Brad will not create a new D-Bus interface/property to hold the system type.
* The DBUSConfigFileNameLocator class will instead directly obtain the IM keyword value from D-Bus.  It will need to map that numeric value to a config file name.

**Comment by bradbishop** [comment]
Hi @smccarney.  I talked at length with @amboar and we mostly settled on Plan A.

> Some application (TBD) will map this numeric value to a string like "rainier_2s2u". Note that the internal (code) name should be used, as the external name is not available until late in the release cycle.

Agreed.  The plan is to use EM to do this :-)  @amboar agrees (now) that this makes sense.  An alternative we talked about was using IM directly and making symlinks to fix the usability issue e.g.: 23c4.json.  However the mapping information would need to be replicated for each application, so it makes more sense to have it in a centrally located place like the 2U or 4U EM configuration file.

I am not yet certain which interface will host the property.

**Comment by smccarney** [comment]
Thanks @bradbishop and @amboar !

I'll use the new D-Bus interface & property when it has been defined.

**Comment by smccarney** [comment]
Changing this to the FF epic.  I have a temporary solution for power on, and the real solution (D-Bus property from EntityManager) is still being designed.

https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/31670

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/39842
