### ISSUE TITLE
GUI : Design : Server Power Operations - Auto Reboot

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1507]
## SMEs
**BMC**: @geissonator 
**RAS**: Justin Thaler 

## Use Case
TBD

## InVision Prototype
TBD

## Design Issue (phosphor-webui)
TBD

## References/Resources
- [eBMC Feature Item: 3.7.10](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)
- feature discovery folder: 
- user research notes*: 
- user research synthesis: 

* This folder is restricted in accordance with GDPR guidelines.

**Comment by derick-montague** [comment]
@geissonator - we had a question about this feature. Is this a policy setting or is this solely based on MRW, e.g. We auto reboot when we hit a processor checkstop?

**Comment by geissonator** [comment]
I don't believe in the past we've allowed our customers to set this. It just reboots X amount of times on all BIOS boot failures. Was this found in ASMi?

Gunnar is working on getting this into the Redfish API via https://github.com/gtmills/Redfish/commit/0561f8942b435c67b8e3f1dabc69f62d321d03b3

But, I don't think this is something we want in the GUI.

**Comment by derick-montague** [comment]
@gtmills - Noticing this on the roadmap as a 204 milestone. Based on Andrew's comment, is this needed for the web ui?

**Comment by nicoleconser** [comment]
@geissonator Any updates on whether this needs to be in the GUI? Or maybe @gtmills

**Comment by geissonator** [comment]
The only reason we would have to put this in the GUI is if ASMi had it. Does anyone know if that was the case?

At a high level, the value for this is selected by our internal teams based on chance of a reboot recovering the system vs. time wasted doing reboots. It's an error path option and allowing our users to configure it seems a bit dangerous to me.

**Comment by gtmills** [comment]
I don't see it on its own. I think this was set as part of System operating mode: Normal, Manual

**Comment by nicoleconser** [comment]
Thank you! @derick-montague FYI

**Comment by derick-montague** [comment]
Thanks everyone for following up. It sounds like we can close this story and update the tracking spreadsheet. Agree @gtmills?

**Comment by gtmills** [comment]
Covered by `System operating mode`: Normal, Manual as part of https://github.com/ibm-openbmc/dev/issues/1322
