### ISSUE TITLE
GUI : FED : Hardware Deconfiguration

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1509]
## SME
BMC: @dhruvibm, @RameshIyyar 

## Overview
As a **customer Support team member**, I need to be able to view a server's deconfigured resources, understand why and when they were deconfigured, get the information I need to replace a faulty part, and then re-configure that resource.

As a **customer**, I need to be able to quickly share relevant troubleshooting information with Support (via email or phone), as they may not be able to see what's on my screen.

## UX Flow / Interaction Requirements
- [ ] Consolidate 5 ASMI pages attributed to Hardware Deconfiguration to provide a more informative "hub" to manage deconfigured resources.
- [ ] Level 2 & 3 PEs can easily guide users to identify a deconfigured resource, get a live-text Log, and use that information to reconfigure a deconfigured resource - while maintaining scale-ability for a multi-node system.
- [ ] Level 2 &3 PEs can easily trace and obtain deconfiguration records and attempt to force-reconfigure them in one location. 

## Notes
- Will need to add hardware ID column to Deconfiguration records page

## Final Invision Mockup
- [Hardware Deconfiguration](https://ibm.invisionapp.com/share/X4O0DTDQWFU)
- [Redfish proposal](https://lists.ozlabs.org/pipermail/openbmc/2020-December/024262.html)

## New components introduced
- In-page tab system 
  - [Bootstrap Vue component](https://bootstrap-vue.org/docs/components/tabs) to be restyled

## cURL Commands
- [ ] Add cURL commands
- [ ] Work with Engineering to determine the Redfish endpoints and when they are expected
- [ ] Verify the UI to make sure we can support all of the new UI (two examples below)
    - Clearing of of individual log types, e.g. Memory vs Processor
    - Statistics presented on the UI pages

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Screenshots
Hardware deconfig page
![Screen Shot 2021-02-18 at 8 46 19 AM](https://user-images.githubusercontent.com/8097306/108390822-e2a6a480-71c5-11eb-956f-a50a2b39b906.png)

**Comment by yoshiemuranaka** [comment]
Decided after meeting on 1/19/21 

**Deconfiguration records page** 

- Deconfiguration type maps to Severity redfish property
  - Critical => Unrecoverable, Warning => Predictive
  - Since there are more deconfiguration types than Severity options. Dhruvaraj or Ramesh will look into providing the value as a separate property
- Reference column (SRC code) will be provided as a MessageID property. Dhruvaraj will check with Matt S
- Deconfiguration logs will not show "good" deconfigurations (manual, FCO deconfigured)

 
**Hardware deconfiguration page (prototype link)**

- Functional state and Deconfiguration type will be provided by hardware inventory. Yoshie will check with backend developer to make sure deconfiguration properties are included.
- Ramesh will work on the API to configure/deconfigure hardware (Clear records will configure hardware)

**Comment by yoshiemuranaka** [comment]
Slack convo about including configuration state as part of VPD
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1611161040041300

**Comment by yoshiemuranaka** [comment]
My suggestion, after some FED discovery into available API, is to include the ability to configure/deconfigure hardware and showing the "Functional state" as part of the hardware inventory page since most of the information on the page will be provided through hw inventory data.

**Comment by yoshiemuranaka** [comment]
Continued conversation about PCIe and Processor chips on deconfig page https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1612968011417100

**Comment by derick-montague** [comment]
In a meeting today, it was determined that we may not add Deconfig policies for GA1 and the work to add policies to the Deconfig page may not be needed. This will be downstream work.

**Comment by sandeepasingh116** [comment]
Resolved by :
https://github.ibm.com/openbmc/webui-vue/pull/84
