### ISSUE TITLE
phosphor-regulators: Enhance C++ wrapper for I2C interface

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#1510]
Enhance the C++ I2CInterface/I2CDevice wrapper classes to support the following:
* Explicitly opening, closing, and re-opening the device interface
* Cache adapter functionality so it is only obtained once after opening device interface

These enhancements are required by the phosphor-regulators application.

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/27900

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/27900 merged
