### ISSUE TITLE
Dynamic device tree: Generating dtb file from Intermediate xml.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1511]
#1276 is used to generate intermediate xml work system workbook. This issue used for genrating dtb file from Intermediate xml.

**Comment by ojayanth** [comment]
This workok includes below tasks . Looking at the work nature , output is dtb file. Not splitting the issue into smaller one.
                1

- [ ] XMLParser : For targetInstance, targetType, attribute(definition) and enumerationType tags
- [ ] Target hierarchy:
            - As per pdbg expectation (index)
           -  Prepare AddressCell, SizeCell and Reg property for DTS if required by pdbg

- [ ] Prepare DTS datatype

  - Add attribute value by using data type which is defined in attribute tag
- [ ] DTS Indention
      - If required
- [ ]  GenerateDTS
 -  Generate based on prepared data from xml

**Comment by ojayanth** [comment]
@RameshIyyar was working on this issue from Jan 1 st sprint.
Initial  Devioce tree ( with Targets only) is sent for reveiw.

**Comment by RameshIyyar** [comment]
Device tree generate tool is ready. 
Once finalized the repository details will push tool review.

**Comment by ojayanth** [comment]
All the required code is merged in pdata repo. Not outstanding work associated to this issue. , closing

**Comment by ojayanth** [comment]
https://github.ibm.com/phal/pdata/pull/10
