### ISSUE TITLE
pHAL: Dynamic Device : Hostboot support.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1512]
This epic is used to track work related to enable Device tree in Hostboot environment. and BMC side changes to IPL the system using device tree.
- Work with Hostboot team on usage of extending Devoce tree API's for hostboot usage
- Add the support for updating Hostboot required attributes during step 0
-  Device tree Updates handling during Hostboot IPL window ( lock support).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
