### ISSUE TITLE
GUI : FED : Network Settings - Add DHCP

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1515]
## Overview
- [ ] The user will be able to update DHCP Settings in the GUI

## UX Flow / Interaction Requirements
- [ ] Feature breakdown TBD 5/18/20

## Final Invision Mockup
- [ ] Not available TBD 5/18/20

## cURL Commands
```
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"DHCPv4": {"DHCPEnabled": true}}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"DHCPv4": {"UseNTPServers": false}}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"DHCPv4": {"UseDomainName": false}}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"DHCPv4": {"UseDNSServers": false}}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
```

## Notes
- [ ] **Previous Design Story:** https://github.com/ibm-openbmc/dev/issues/936
- [x] 5/18/20 **Internal Error ID: SW492646** - Current build is broken, unable to enable DHCP 

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in DAP

**Comment by dixsie** [comment]
@ryanarnell I am not seeing the Invision prototype for DHCP in Invision anymore. Is the screen shot below the correct design for this story?

![Screen Shot 2020-03-16 at 2.33.55 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/562bc95f-a8b1-4bc3-b74a-00c86a5ff0d7)

Also, below is what I see in the backend for DHCP settings, but I am not seeing where to update  Hostname and Send Hostname?

![Screen Shot 2020-03-16 at 2.37.16 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/a8622d75-1a2a-4d1b-9c73-d02c95e4526c)

**Comment by derick-montague** [comment]
Also blocked by Network DHCP server-side WIP.

**Comment by dixsie** [comment]
@derick-montague is this story still blocked? https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24725
If not, I would like to pick this one up

**Comment by derick-montague** [comment]
@dixsie It's not ready to be picked up, it's blocked by the research story, #2130

**Comment by derick-montague** [comment]
Closing -> Work will be complete in #2130
