### ISSUE TITLE
eBMC GUI : System Logs

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1523]
## SMEs
**BMC**: @spinler, @santoshpuranik, @dkodihal 
**PHPY**: Adam Stallman
**RAS**: Justin Thaler
**IBM i** Randy Tomfohrde
**Security** Joseph Reynolds

## Summary

Known Redfish LogServices include ([per Gunnar on 7/21](https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1595264636257600)): 

- Audit Logs: /redfish/v1/Managers/BMC/LogServices/Audit/
- Maintenance: /redfish/v1/Managers/BMC/LogServices/Maintenance
- Progress/Boot Logs: /redfish/v1/Managers/BMC/LogServices/Progress
- Hidden: /redfish/v1/Managers/BMC/LogServices/Hidden - [slack conversation](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1627407651037600)
- Event: /redfish/v1/Managers/BMC/LogServices/Event (Endpoint may change)

-  BMC Dump 
-  System Dump (will likely contain multiple types of dumps) 
-  Gard *** does not currently exist (7/21), but will 

Some of these Event logs will have a link to PELs. Should the link be in the log?
PELs will be a file with hex data on the BMC. 
PELs will not be displayed on the GUI. 

## Use Case
TBD

## References/Resources
- [eBMC Feature Item: 2.5](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)
- feature discovery folder: 
- user research notes*: 
- user research synthesis: 

* This folder is restricted in accordance with GDPR guidelines.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by nicoleconser** [comment]
**Relevant comments from today's SEET meeting re: Service Flows:** 

- **_All_** P10 standalone servers will be able to Call HAllome (as long as it's configured) 
- PEL data is only needed for complex problems - not for replacing parts. PEL data is typically only needed for PEs in action when they don’t know what’s wrong. 
- Concern #1 (Russ): Customers with legacy environments are used to seeing errors from their OS; will have to get used to logging in to the eBMC GUI instead. This also means standalone servers are now going to need to be connected to a network. 
- Concern #3 (Russ): Data from the OS needs to be packaged up & served to the eBMC to avoid any information gaps. 
- Concern #5 (Doyle McCoy): Many scenarios result in a “train wreck” of errors — duplicate errors, no isolation of the actual problem — which can only be solved with higher-level software. Is this being fixed in P10? P11? 

**Relevant questions:** 
- How many high priority events are displayed on the dashboard? what do PEs expect?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Hidden logs discussion with @gtmills and @spinler in slack: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1627407651037600

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Work is complete except some backlog work that we may or may not do.
