### ISSUE TITLE
Define new roles ServiceAgent and ManufacturingRep

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#1529]
This is to define new Redfish Roles needed for manufacturing and service personnel.

Reason: The BMC administrator should not have access to operations involving the manufacturing process or servicing the host because these operations can damage the system.

Examples of access needed:
1. ServiceRep - Needs to access BMC operations to service the system, such as re-enabling locked out field replaceable units (FRUs) after replacing a defective unit.
2. OemRep (was: ManufacturingRep) - Needs to access BMC operations to test the host system, such as how the system responds to overheating.

Example solution:
1. Create two new [Redfish roles and Privileges](https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.7.0.pdf#%5B%7B%22num%22%3A134%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C0%2C477%2C0%5D) (DSP0266 “Privilege model” section).  Suggest:
   A. Role = ServiceAgent;  Assigned privileges = ServiceSystem
   B. Role name = OemRep;  Assigned privileges = OemAccess
2. Define operation-to-privilege mappings appropriately and implement them in BMCWeb.
3. When service is needed, the BMC Admin will create a "service" account with Role=ServiceAgent and give access to the service agent.

Notes:
- The manufacturing and service agents should NOT have access to the user management or the BMC configuration.  However, that said, for the forseeable future, the ManufacturingAccess will likely necessarily have enough access to do whatever needs to be done, including having full access to all BMC capabilities.
- Per the Redfish spec, the Administrator role can escalate privilege to assume a service agent or manufacturing representative role.  How to fix?  See #2739 .

**Comment by joseph-reynolds** [comment]
For what it's worth, the ServiceAgent role corresponds to the IBM CELogin (customer engineer login) account.  The CELogin model was a single privileged account.  The new model is a ServiceAgent role the BMC admin can use to create zero or more accounts.

**Comment by joseph-reynolds** [comment]
@gtmills 
This story is to define new Redfish Roles `ServiceAgent` and `OemAgent`.  If Redfish does not accept these, can we define an Oem.OpenBMC.ServiceAgent role?

As part of this, we'll have to clearly state what a "ServiceRep" should be able to do that an Administrator should not be allowed to do.

This topic was discussed briefly in the OpenBMC security working group, 2019-11-27: https://docs.google.com/document/d/1b7x9BaxsfcukQDqbvZsU2ehMq4xoJRQvLxxsDUWmAOI
I'll send that followup email....

**Comment by joseph-reynolds** [comment]
Email: https://lists.ozlabs.org/pipermail/openbmc/2020-February/020540.html

**Comment by gtmills** [comment]
@joseph-reynolds What things does OemRep/ManufacturingRep have that Admin doesn't? 
Can you just use root? Disable root before shipping.

**Comment by joseph-reynolds** [comment]
The CELogin (ServiceRep) (or perhaps more properly the Manufacturing rep) should be able to put the system in a mode where it stops processing if it encounters any error or warning while processing.  Normally, the system is designed to be fault tolerant and continue processing when it encounters errors it can recover from.  This mode is used by the manufacturing process to test the system to help ensure it has no defects before it is shipped, and help us debug any problems.  ==> The BMC Admin should not be able to enter this mode.

**Comment by joseph-reynolds** [comment]
Hi Gunnar.  We're still working out within IBM exactly what privileged operations we need to prevent the Admin from doing, and how to partition those into Roles.  The ServiceRep and OemRep roles I mentioned above are straw-man.

We want to move away from exposing root user SSH access, yet acknowledge that we need it for some configuration and some debug operations.  See that discussion in https://github.com/ibm-openbmc/dev/issues/612

So we may need root user SSH access as part of the CELogin role.  But we want to prevent the BMC admin from becoming root.  And we want the BMC Admin to control the CELogin account access, but not be able to escalate their privilege to CELogin.  <-- If that sounds maddeningly circular and frustrating, it is.

I don't have a better answer.  I am reaching out to the community for help, for example, the OpenBMC security working group (https://docs.google.com/document/d/1b7x9BaxsfcukQDqbvZsU2ehMq4xoJRQvLxxsDUWmAOI > 2019-11-27 > agenda item 7.

**Comment by joseph-reynolds** [comment]
openbmc community email asking about stop-of-first-failure mode:
https://lists.ozlabs.org/pipermail/openbmc/2020-February/020575.html

**Comment by joseph-reynolds** [comment]
@geissonator ^^^ For your awareness

**Comment by joseph-reynolds** [comment]
The ManufacturingRep can update MAC addresses.  The admin must not have that capability.

**Comment by joseph-reynolds** [comment]
Per Gunnar's Feb 14 post: We want to move away from root user login per #1528.
We don't want the admin to be able to access the BMC as root; that access should be reserved for roles like Manufacturing Rep.  It's cleaner to use Redfish's Role model compared to having a specific userid.  This story is moving toward that.

**Comment by joseph-reynolds** [comment]
Field mode is curious https://github.com/openbmc/docs/blob/f75a11159b2e46ffc40763b566a0ddfc2828f5f0/code-update/code-update.md#software-field-mode.
Field mode should be enabled by the Manufacturing agent before the BMC Admin gets the system, then can be readable by everyone.

**Comment by joseph-reynolds** [comment]
Manufacturing needs to be able to patch sensor values (send false values) for temperatures and fan speeds to test the system's response before it is shipped.  Administrators and service agents should not have this capability.

**Comment by gtmills** [comment]
@joseph-reynolds Why can't manufacturing use busctl?

**Comment by joseph-reynolds** [comment]
Yes, the manufacturing group can use ssh access to the BMC's shell to run the busctl command to achieve the same effect.  But that wouldn't be using Redfish.  My assertion above is from a Redfish-centric worldview where there should be a standardized Redfish interface for this.

**Comment by mzipse** [comment]
@joseph-reynolds  give the above, is this story needed anymore?

**Comment by joseph-reynolds** [comment]
Done, closing.  The Service Agent role was defined.  Manufacturing agent was not needed.
