### ISSUE TITLE
Docs: improve the genesis experience

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#1531]
This is to improve the documentation surrounding the genesis experience (a.k.a. new out of box experience).  Specifically, the project has details for [getting started](https://github.com/openbmc/openbmc/blob/master/README.md) which describes how to build a firmware image, and documentation for [how to use an operational system](https://github.com/openbmc/docs), but lacks details about how to put a BMC into operation.

This proposes to add documentation to the docs repo in the following areas:
- Build considerations.  Give advice for:
   - Source code configuration, for example, link to [BMCWeb config docs](https://github.com/openbmc/bmcweb/blob/master/README.md#configuration).  Customizing the built-in account default password.
   - Private key used to sign the image.
   - Planning for secure and verified boot ([design](https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/26169)).
- Discovery.  How to discover the BMC, such as via Avahi.
- Genesis boot.  Give guidance to the BMC administrator for the following:
   - How to access the BMC (which interfaces are available).  Logging in  Setting a password.
- Initial admin tasks.  Give advice or links to documentation for items such as:
  - How to configure the BMC's IP address.
  - How to add users and configure LDAP.
  - How and why to disable unneeded interfaces (and validate by testing).
- Terminal admin tasks, de-provisioning the system  Give advice:
   - Removing accounts and accesses.
   - Removing secrets
- Privacy considerations

To partly address this, I started the Configuration Guide here: https://github.com/openbmc/openbmc/wiki/Configuration-guide

**Comment by joseph-reynolds** [comment]
See https://lists.ozlabs.org/pipermail/openbmc/2020-February/020478.html
for more advice that we should put into the BMC admin guide.

**Comment by joseph-reynolds** [comment]
Specifically, review BMCWeb's build-time options such as 
BMCWEB_ENABLE_DBUS_REST in https://github.com/openbmc/bmcweb/blob/master/CMakeLists.txt

**Comment by joseph-reynolds** [comment]
Maybe the project should have a guide for BMC admins?  Some more admin topics (stubs) are:
- Enabling and disabling debug ~ https://lists.ozlabs.org/pipermail/openbmc/2020-February/020489.html
- Looking through log files ~ https://lists.ozlabs.org/pipermail/openbmc/2020-February/020494.html

**Comment by joseph-reynolds** [comment]
Admin task: How to set the BMC's IP address: See https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Network/README.md

**Comment by joseph-reynolds** [comment]
For build considerations > image signing: advise the system integrator which private keys to use to sign the firmware image.  For example (strawman ideas):
- Use one key for a seminal firmware version and that same key to sign images in that same series, typically fix versions.
- Use a separate key for separate host/BMC combinations.

In this way, issues with one signature may be limited and contained.

Also, point to OpenBMC docs on how to sign, and to best practices for how to store the private key and secure build and image signing practices.

**Comment by joseph-reynolds** [comment]
Initial admin task: Add certificates to the BMC.  For example, replace the self-signed HTTPS site identity certificate with one signed by a certificate authority (CA).  Is this URI /xyz/openbmc_project/certs/server/https
https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Certs

**Comment by joseph-reynolds** [comment]
Add this to build considerations:
- If you want to remove the BMC'snetwork IPMI capabilty, disable it in the image, otherwise...
- Change the ipmi /etc/key_file before building the image, per https://lists.ozlabs.org/pipermail/openbmc/2020-April/021246.html  Ideally, install or generate an unique key_file per BMC.

**Comment by joseph-reynolds** [comment]
Add to build considerations:
- Toggle WebGUI app features helps you make environment-specific build modifications to customize the customer's browser experience.  Representative review: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29079

**Comment by joseph-reynolds** [comment]
Here is how to set initial passwords at build-time.  For the root account's initial password such as here: https://github.com/ibm-openbmc/openbmc/blob/master/meta-phosphor/conf/distro/include/phosphor-defaults.inc
See email archive https://lists.ozlabs.org/pipermail/openbmc/2020-August/022645.html titled "How to compute the password hash".  Spoiler alert:
> From my Linux system, I use:
openssl passwd -1 -salt "UGMqyqdG" 0penBmc
$1$UGMqyqdG$FZiylVFmRRfl9Z0Ue8G7e/
>
> Notes:
> - The -1 option and the -salt "UGMqyqdG" option were used to get the 
exact result in the project default [2].  You would probably want to use 
sha512 and your own salt.
> - The first character of the password is a zero, not a capital O.
>
> \[2]: https://github.com/openbmc/openbmc/blob/master/meta-phosphor/conf/distro/include/phosphor-defaults.inc

**Comment by joseph-reynolds** [comment]
I started the Configuration Guide here: https://github.com/openbmc/openbmc/wiki/Configuration-guide

**Comment by joseph-reynolds** [comment]
An idea came up (not from me) for a sanity checker or a security dashboard display.  It would show things like:
- The BMC time of day clock is not set (affects certificate expiration).
- Access to LDAP servers is configured (affects who can access the BMC).
- Service access is granted (allows authorized service reps extraordinary access to the system).

**Comment by anoo1** [comment]
Per Joseph this is an on-going work and it's documented in box. Closing issue.
