### ISSUE TITLE
eBMC GUI : Sensor Readings

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1532]
## SMEs
**BMC**: @spinler 

## Use Case
TBD

## References/Resources
- [eBMC Feature Item: 2.3](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)
- feature discovery folder: 
- user research notes*: 
- user research synthesis: 

* This folder is restricted in accordance with GDPR guidelines.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by nicoleconser** [comment]
FYI from Justin Thaler, Michael, Todd - "we should start generating logs when crossing thresholds. This would also be a post GA1 function" https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1588267915228500

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Determined out of scope: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1590693647136800

**Comment by nicoleconser** [comment]
Per comments made during our annual playback - we need to find out how our customers use sensor readings - i.e. do they want this level of granularity? (some thought no, this is too much detail)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
