### ISSUE TITLE
GUI : HW Inventory - PCIe devices - (CEC Only)

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1533]
## SME
**BMC**: @santoshpuranik, @gtmills @sampmisr , @bradbishop 

## Summary
The expectation is that there will be an endpoint in Redfish and we will need to implement this in the Hardware Status page similar to the other inventory items. 

### End users
- [ ]  TBD

### User Needs
- [ ] TBD

### User Quotes
- [ ] TBD

## User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

## References
- eBMC Feature Item: 2.3.6
- Discovery: https://ibm.ent.box.com/notes/818358757033
This is the discovery doc for PCIe hardware topology. Check VPD row in "Functions and API" table.

# FED

## Overview
- [ ] Add Overview

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by nicoleconser** [comment]
@derick-montague Since we know this is going on the Hardware Inventory / Status page ([per Gunnar](https://github.com/ibm-openbmc/dev/issues/2010)), should this belong to epic #1520 instead of #1532 ?

**Comment by derick-montague** [comment]
> @derick-montague Since we know this is going on the Hardware Inventory / Status page ([per Gunnar](https://github.com/ibm-openbmc/dev/issues/2010)), should this belong to epic #1520 instead of #1532 ?

That makes sense. I'll make some updates.

**Comment by derick-montague** [comment]
Determined this will be an implementation story and design will help as needed.

**Comment by ParishrutB** [comment]
SME: @santoshpuranik 
This feature is yet to be discussed. 
https://github.com/ibm-openbmc/dev/issues/1475#issuecomment-856780060

**Comment by derick-montague** [comment]
Updated title as there will only be support for PCIe devices. CAPI devices is future facing.

**Comment by derick-montague** [comment]
Based on discussion with Maury, this could be ready for implementation soon. Some questions we will need to ask are:
1. What schema will the PCIe devices use. I expect it to be the Assembly schema

**Comment by derick-montague** [comment]
I have created #3303 as the story to bring in the MEX drawer

**Comment by dixsie** [comment]
- [ ] Still waiting on #2010 for the API

Discussed with Maury and Gunnar possibly using the API mockup to hardcode the properties in the store to build and test the UI. If we go forward with this route it was suggested to push downstream until the backend is merged.

PCIe topology will be downstream for now, long term it will be upstream.

**Comment by dixsie** [comment]
CEC - central electronics complex
CEC is the server chassis & stuff in it

MEX drawer - sheet metal chassis w/ PCIe slots; connects to the main server chassis (CEC) with cables. Let's you increase the # of PCIe slots 

CEC and MEX has PCIe slots in it

PCIe slots have LEDs

CEC = `/redfish/v1/Chassis/chassis`
MEX will another row on the chassis table

**Comment by dixsie** [comment]
Not needed, the table for `Chassis/chassis` is the CEC
