### ISSUE TITLE
eBMC GUI : Capacity on Demand

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1537]
## SMEs
**BMC**: TBD
**PHYP**: Paul Olsen
**RAS**: Justin Thaler

## Overview
Includes the following features:
- 4.4.1 CoD Order Information
- 4.4.2 CoD Activation
- 4.4.3 CoD Recovery
- 4.4.4 CoD Command
- 4.4.5 CoD Processor Information
- 4.4.6 CoD  Memory Information
- 4.4.7 CoD Capacity Setting
- 4.4.8 VET Capability Setting
- 4.4.9 CoD Virtualization Enablement Technology Info
- 4.4.10 VET Capability

## Use Case
TBD

## References/Resources
- [eBMC Feature Item: 4.4](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)
- feature discovery folder: 
- user research notes*: 
- user research synthesis: 

* This folder is restricted in accordance with GDPR guidelines.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
FYI - the ASMI screen captures are not associated with the correct sections in the discovery document.

**Comment by derick-montague** [comment]
Update milestone based on feature sync meeting with Maury and Gunnar on 3/15/21.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Work is complete.  Closing.
