### ISSUE TITLE
phosphor-state-manager: add support for building with meson

### ISSUE THREAD

**Issue by wangkair** [ibm-openbmc/dev#1543]

**Comment by wangkair** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/28198

**Comment by wangkair** [comment]
Meet an parser error during CI compiling. The solution can refer to https://github.com/mesonbuild/meson/issues/6323

**Comment by geissonator** [comment]
phosphor-state-manager is moved to meson with https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/27880/5 chain of commits

**Comment by wangkair** [comment]
> phosphor-state-manager is moved to meson with https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/27880/5 chain of commits

Oh, I should have checked this project on gerrit first. I close this issue then. Thanks for the reminding.
