### ISSUE TITLE
VPD ECC: Come up with a way to patch the ECC implementation in GHE builds

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1548]
https://github.com/ibm-openbmc/dev/issues/1140 will provide a dummy implementation of the IPZ ECC in the openpower-vpd-parser repo. This story is to use the actual implementation, and patch it in for GHE builds only.

**Comment by Alpana07** [comment]
ECC implementation patch is pushed to the GHE. 
Will wait for #1140  to be merged then will create a Pull request for this.
