### ISSUE TITLE
phosphor-rest-server : Support for changing the local users password through PAM

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#155]
With the introduction of the new user management, The design principle are as follows.

For security reasons, avoid transmitting passwords over any D-Bus API. Observe this rule even while creating, modifying or authenticating the user.

Have applications use the PAM module to authenticate the user instead of relying on a D-Bus API-based approach.

With this issue we would be enabling the support of changing the local user password through PAM for rest server.

**Comment by ratagupt** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-rest-server/+/13976/

**Comment by xiuzhi123** [comment]
@ratagupt 
The webui setpassword page didn't give  any errors  when I input the old  and new  password of user "root" . But the password didn't changed any more when I login again.
Is there  anything missing on BMC pam module? I login the bmc OS by serial   port and input passwd command, the error read :
root@haiguang1:~# passwd                                                        
passwd: Module is unknown                                                       
passwd: password unchanged

**Comment by xiuzhi123** [comment]
I modified the comm-password ,then password works, but when I change the password by REST API SetPaasword ,the bmc raise an error:
{
  "data": {
    "description": "Internal Server Error", 
    "exception": "NameError(\"global name 'PAMError' is not defined\",)", 
    "traceback": [
      "Traceback (most recent call last):", 
      "  File \"/usr/lib/python2.7/site-packages/bottle.py\", line 862, in _handle", 
      "    return route.call(**args)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1395, in __call__", 
      "    return self.callback(*a, **kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1460, in wrap", 
      "    return callback(*a, **kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1684, in __call__", 
      "    return self.callback(*a, **kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1658, in wrap", 
      "    return self.to_jsonp(callback(*a, **kw))", 
      "  File \"/usr/lib/python2.7/site-packages/bottle.py\", line 1742, in wrapper", 
      "    rv = callback(*a, **ka)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1622, in wrap", 
      "    data = callback(*a, **kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1511, in wrap", 
      "    return callback(*a, **kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1714, in __call__", 
      "    resp = self.callback(*a, **kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 243, in __call__", 
      "    return getattr(self, 'do_' + request.method.lower())(**kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 800, in do_post", 
      "    except PAMError as e:", 
      "NameError: global name 'PAMError' is not defined"
    ]
  },

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
We have moved to bmcweb, where the support is there to change the password through Redfish.

**Comment by mzipse** [comment]
Closing this.  The Redfish solution is already merged to master.
