### ISSUE TITLE
PLDM: libpldm: implement encode/decode for GetStateSensorReadings

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1554]
Implement ```encode_get_state_sensor_readings``` and ```decode_get_state_sensor_readings``` in libpldm, as per https://www.dmtf.org/sites/default/files/standards/documents/DSP0248_1.1.2.pdf. The command ```GetStateSensorReadings``` allows a PLDM requester, for eg the host firmware, to read a sensor off of the BMC. This story is just for the encode/decode commands.

This can be tested via unit tests. For eg look at how the corresponding setStateSensor is implemented and tested in openbmc/pldm.

**Comment by JolieKu** [comment]
merged [https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/28464](url)
