### ISSUE TITLE
Write ffdc data in Json format

### ISSUE THREAD

**Issue by devenrao** [ibm-openbmc/dev#1563]
1. At present the parser takes in fapi2::ReturnCode and returns data in stl::map format so that the same can be added as AdditionalData in the creation of PEL using https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Logging/Create.interface.yaml interace
2. The same needs to be modified to return the data in Json object format so that it can be written to a file and invoke Logging.Create.CreateWithFFDCFiles defined here https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/26544
3. This issue needs to be taken once the corresponding infrastructure in phosphor-loggin is available.

Note:
1. Writing failure data in json format saves the effort for writing parser to parse the PEL.

**Comment by devenrao** [comment]
When receiving debug trace data from libekb format the data in json format

**Comment by ojayanth** [comment]
Milestone updated .

**Comment by rfrandse** [comment]
tracking in jira
