### ISSUE TITLE
pHAL : Error Infrastructre design

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1564]
Design document , which includes complete flow of pHAL repos openBMC application error handling of pHAL failures.

**Comment by devenrao** [comment]
Document pushed for review https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/25443

addressed review comments, need to get it to closure.

**Comment by devenrao** [comment]
Most comments are addressed need to address 1 comment regarding the document location

**Comment by devenrao** [comment]
Design document needs to be updated as per latest discussion involving changes to the returning of failure data

**Comment by devenrao** [comment]
Design document needs to be updated as per latest discussion involving changes to the returning of failure data

**Comment by devenrao** [comment]
Updated design document as per latest design changes and the same has been uploaded for review
