### ISSUE TITLE
ecmd-pdbg: Enable Processor Control instruction Start/stop)

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1565]

**Comment by lkammath** [comment]
https://github.com/open-power/ecmd-pdbg/pull/22 - under code review

**Comment by lkammath** [comment]
Integrated and available in builds

**Comment by lkammath** [comment]
cipinstruct start/stop individual thread - WIP

**Comment by ojayanth** [comment]
Startall and stopall Support work support is planned for this.   @lkammath create another issue for thread level control . This needd pdbg back-end support

**Comment by lkammath** [comment]
#1659 will implement single/multiple thread-level granularity
