### ISSUE TITLE
eBMC State Management - Terminate on callout support

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1566]
Manufacturing has a requirement that any error with a hardware callout cause a termination of the system. This is so hardware failures can be quickly found and repaired in the manufacturing environment. 

This story is to define this new flag in Settings and then add the appropriate call to the IBM-specific back-end phosphor-logging code to check this policy on error with callouts and terminate if required.

This story could be broken into two if needed (to track the two items above). For now just size into one story.

**Comment by geissonator** [comment]
The basics of the setting and the checking of that setting in the common phosphor-logging path is done via the following commits series:

https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/32403
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/32155

Run the following to turn on this feature:
```
busctl set-property xyz.openbmc_project.Settings /xyz/openbmc_project/logging/settings xyz.openbmc_project.Logging.Settings QuiesceOnHwError b true
```

To test it, create an error with a callout like so:
```
busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging xyz.openbmc_project.Logging.Create Create ssa{ss} xyz.openbmc_project.Common.Error.Timeout xyz.openbmc_project.Logging.Entry.Level.Error 2 "TIMEOUT_IN_MSEC" "5" "CALLOUT_INVENTORY_PATH" "/xyz/openbmc_project/inventory/system/chassis/motherboard"```

Verify the blocking error via:
```
obmcutil listbootblock
```

Resolve or delete the error to allow the power on to complete
```
obmcutil deletelogs
```

FYI @gkeishin @trajeswaran

**Comment by trajeswaran** [comment]
@geissonator  Thank you very much.
