### ISSUE TITLE
Redfish: Query parameters: Only 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1569]
From DSP0266 version 1.8.0, there is a query parameter (section 7.3), only which is used on a collection to return the member if there is only 1 member. 

[DSP0266_1.8.0.pdf](https://github.com/ibm-openbmc/dev/files/4056172/DSP0266_1.8.0.pdf)

```

only | Applies to resource collections.  If the target  resource collection contains exactly one member, clients can use this  query parameter to return that member's resource.If the  collection contains either zero members or more than one member, the  response returns the resource collection, as expected.Services should return the HTTP 400 Bad Request with the QueryCombinationInvalid message from the Base Message Registry if only is being combined with other query parameters.Example:https://resourcecollection?only
-- | --


```

**Comment by gtmills** [comment]
Will want to work with Intel about how this should be done

**Comment by mzipse** [comment]
@gtmills , could I ask you to add a story point estimate for this work?  Also, are you expecting the developer assigned to this to work with Intel or were you planning to be involved?

**Comment by gtmills** [comment]
The developer to work with Intel and the community. Set estimate.

**Comment by mzipse** [comment]
Thanks  @gtmills

**Comment by lxwinspur** [comment]
Hi, @gtmills @mzipse 
Is there any new progress in this task?
In other words, what can we do in this task?
Thanks :)

**Comment by gtmills** [comment]
@lxwinspur Sorry for the slow response here, missed this. 
Only is defined in the Redfish Spec. 
[DSP0266_1.11.0.pdf](https://github.com/ibm-openbmc/dev/files/5504098/DSP0266_1.11.0.pdf)

It would be for collections. 
If Only is passed and there is only 1 member in the collection then return that member instead of the collection. 
If there is 0 or more than 1 member, return the colleciton. 

You would need to work with the community / bmcweb members to come up with a design that works. 
The first thing that comes to my mind is, could we redirect the collection request ?

**Comment by XiaochaoMa** [comment]
reviewed here:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38952/3

**Comment by XiaochaoMa** [comment]
@gtmills I used redirection to return the URL of the only member. 
And successfully displayed the desired result on the web.
But Ed mentioned that redirection is not the right way. A single resource should be returned here...

**Comment by gtmills** [comment]
@XiaochaoMa 

Without only query parameter:
```
$ curl -k  https://${bmc}/redfish/v1/SessionService/Sessions
{
"@odata.id": "/redfish/v1/SessionService/Sessions/",
"@odata.type": "#SessionCollection.SessionCollection",
"Description": "Session Collection",
"Members": [
	{
	 "@odata.id": "/redfish/v1/SessionService/Sessions/vuEa8sgv6R"
	}	
],
"Members@odata.count": 1,
"Name": "Session Collection"
}

```

With only query parameter:

```
$ curl -k https://$bmc/redfish/v1/SessionService/Sessions\?only
{
  "@odata.id": "/redfish/v1/SessionService/Sessions/vuEa8sgv6R",
  "@odata.type": "#Session.v1_3_0.Session",
  "ClientOriginIPAddress": "",
....
```

Is it possible to change the route to be /redfish/v1/SessionService/Sessions/vuEa8sgv6R after you determine there is only 1 member in the colleciton?

**Comment by XiaochaoMa** [comment]
@gtmills 
I thoroughly understand the effect that this parameter should achieve.
What I am confused now is how to implement "change the route".

Is it similar to this implementation? Use the method function of BMCWEB_ROUTE.
     BMCWEB_ROUTE(app, "/ibm/v1/Host/ConfigFiles")
         .privileges({"ConfigureComponents", "ConfigureManager"})
         .methods(boost::beast::http::verb::get)(
             [](const crow::Request&, crow::Response& res) {
                 handleConfigFileList(res);
             });
This seems to be a way to register route, and it cannot be used with me.

Are there some methods that can be referred to?

**Comment by XiaochaoMa** [comment]
Waiting for the submission of the patch set to integrate the similar AsyncResp in the bmcweb repository.

**Comment by gtmills** [comment]
Okay, thanks for the update. Although would like to see this, there is other more important things missing in Redfish today, so dropped the priority on this one.

**Comment by gtmills** [comment]
Merged here:  https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/47474/20
