### ISSUE TITLE
rsyslog : updating server IP address and port in one operation.

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#157]
The plan is to design a new Object.Update interface, that takes in a dictionary of property-value, in order to update multiple properties of a D-Bus object in one shot. This prevents us from doing things like updating a property and restarting a service for each property update. It can reduce D-Bus round trips as well. The work involves defining the new D-Bus API, and then implementing the same in the rsyslog config application.

**Comment by mzipse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
No plans to do anymore with this.  Closing.
