### ISSUE TITLE
Gard d-bus Interface implementaion

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1576]

**Comment by ojayanth** [comment]
Based on the latest direction need to enable Guard tool back-end library.

**Comment by amboar** [comment]
What's the requirement here?

**Comment by ojayanth** [comment]
This is to enable user interface ( Redfish) for GUARD functions. @amboar

**Comment by ojayanth** [comment]
Required redfish definition to start this implementaion. moving to backlog

**Comment by ojayanth** [comment]
Add support for the Gard d-bus back-end support  for Gard command , list , delete, manual gurad 
Please refer design document for details .
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/27804

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/dev/issues/1775 is the story for the redfish api implementation

**Comment by ojayanth** [comment]
This issue covers
-  Guard manager design and d-bus implementation in BMC.
-  Error handling support.
-  Adding unit test cases

**Comment by ojayanth** [comment]
#2930 #2931 and #2932 is used track dbus interface reveiw and implementation.
