### ISSUE TITLE
Guard Tool: CLI support 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1577]
-  Support command line features  based on design  document
	Design document Link: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/27804
       - provide display support for requited format.

**Comment by gtmills** [comment]
@ojayanth What is this tool? Can't just use the redfishtool?

**Comment by ojayanth** [comment]
As discussed we are planing to use the existing opal-gard tool till redfish support in place.

**Comment by ojayanth** [comment]
Based on the latest discussion with OPAL/BMC team , planing to create BMC specific Guard CLI for lab/development till the redfish support in place. 
This will be supporting new guard record format and run natively from BMC.

**Comment by devenrao** [comment]
1) will provide options for the users to create, list, delete guard records
2) Need to use CLI11 framework for the tool
3) Tool need to cater for catching any exceptions thrown by the guard library.

**Comment by ojayanth** [comment]
https://github.ibm.com/open-power/guard/pull/2
