### ISSUE TITLE
VPD: Update system inventory JSON with Location Codes For FRUs without VPD

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1583]
The system JSON will be updated with location codes for all the FRUs we collect VPD for with issue #1558 . This story is to add other miscellaneous FRUs like connectors (for example the ethernet and USB ports on the BMC card) to this JSON.

An application (which can be the backplane VPD parser) will have to prime the inventory with this data once the system type is discovered and the right JSON is loaded.

**Comment by mzipse** [comment]
Per feedback from Santosh, code is in review.

**Comment by santoshpuranik** [comment]
We need to scrub the JSONs and the workbook to make sure we have all inventory items. This has about 5 SP of effort still remaining.

**Comment by mzipse** [comment]
@santoshpuranik , is this completed now?  Also, does this include Fan VPD as well?

**Comment by santoshpuranik** [comment]
This is in a driver.
