### ISSUE TITLE
VPD: Expand Location Codes In the Inventory

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1584]
The location codes in the system JSON will be unexpanded (ex: Ufcs-P1-C1). The "fcs" string has to replaced at runtime with data that comes from the backplane VPD's FC and SE keywords.

The current plan here is:
1) Split the VPD collection services into two: One that would just collect the backplane VPD info and prime the inventory.
2) All other FRUs.

2) will be started after 1) is done (using systemd dependencies). 1) Will setup the backplane system VPD info after determining the right system type (IM keyword) and setting up the right system JSON.

All services that start in 2) will then use the information populated by 1) to properly expand the location codes.

**Comment by mzipse** [comment]
Per feedback from Santosh, this work is now complete.  Closing.
