### ISSUE TITLE
VPD: Support System Specific JSONs in a Single Image

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1585]
The VPD parser services look at the inventory JSON to determine the data that needs to be put in the inventory. We need the ability to select the right JSON based on the system we are running on (example a 2U vs a  4U system).

The basic direction here is:
* Start a service to read the backplane VPD (or the FRU that can tell us the system type). This will put just the backplane VPD data into the inventory and setup a symlink to the right system JSON based on the system type (IM keyword)
* Once the right JSON is linked, future VPD collection services can refer to the now properly setup system JSON to determine VPD inventory properties.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
This support for handling multiple systems in a single image is now in place.

**Comment by rfrandse** [comment]
refresh
