### ISSUE TITLE
VPD: RAS: Callouts and Error Logging for VPD Functions

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1586]
This epic will cover all work needed in the VPD parsers and related applications for any firmware RAS requirements such as error logging and FRU callouts.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
This is merged to master as well as in a GHE driver.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
