### ISSUE TITLE
BMC PSU support for oversubscription

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1589]
BMC PSU support needed for oversubscription - 2 or 4 ps supported.  Write to N_MODE_VREF gpio to specify 2/4 ps based on config requirements for this type of system and type of ps.  Which gpio to update is read from entity manager config file or hardcoded in dts.

**Comment by anoo1** [comment]
Gerrit:
- [ ] [psu-ng: Implement gpio write function](https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/47590)
- [ ] [psu-ng: Get the power config full load property](https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/48501)
- [ ] [psu-ng: Set the power-config-full-load GPIO](https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/47865)

PRs:
- [ ] [ARM: dts: aspeed: rainier: Add power-config-full-load gpio](https://github.ibm.com/openbmc/linux/pull/148)
- [ ] [Supported Configuration: Add PowerConfigFullLoad](https://github.com/ibm-openbmc/entity-manager/pull/12)

**Comment by anoo1** [comment]
Merged.
