### ISSUE TITLE
Design and implement openBMC REST API to Download CSR

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#16]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ojayanth](https://github.com/ojayanth)**
_Thursday Aug 02, 2018 at 10:56 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3339_

----

   Provide REST API to download CSR. 
   Implementation of the Certificate Signing Request.

**Comment by joseph-reynolds** [comment]
Today I asked the security working group to review the design in https://gerrit.openbmc-project.xyz/#/c/11840/.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Already have issue related to redfish interface to support download CSR . As per current plan, CSR certificate management is only available using redfish interface.
