### ISSUE TITLE
PLDM: libpldm: Implement PlatformEventMessage

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1604]
- Add encode/decode APIs (responder flow only) for the command PlatformEventMessage, from https://www.dmtf.org/sites/default/files/standards/documents/DSP0248_1.2.0.pdf
- Define C structs for the 'sensorEvent' event data format - these structs will enable a user to typecast the event data that's part of the PlatformEventMessage request.
- Define C struct for the 'pldmPDRRepositoryChgEvent' event data format.
- Add unit tests

**Comment by zaxxed** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/29988

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/29988 merged
