### ISSUE TITLE
pHAL: Dual Boot Support.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1605]
pHAL code need to set cfam regs on all chips  based on PLDM BIOS setting core type.

**Comment by mzipse** [comment]
Assigning to Jayanth for now.  He can reassign once someone is ready to work on this.

**Comment by ojayanth** [comment]
https://rchgit01.rchland.ibm.com/gerrit1/#/c/93376/  HWP reveiw.

**Comment by ojayanth** [comment]
Pdata Support:  https://github.ibm.com/phal/pdata/pull/11 - Merged.
ipl Support: https://github.ibm.com/phal/ipl/pull/18 -Review is in progess

**Comment by ojayanth** [comment]
https://github.ibm.com/openbmc/openbmc/pull/362
