### ISSUE TITLE
Design for how common OpenBMC applications communicate what to call out

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1607]
Common (to other architectures) openbmc applications cannot mention PEL specific concepts like callout priorities, but we still need priority callouts in PELs.  Design what all has to happen so applications can still meet IBM callout requirements.

**Comment by bradbishop** [comment]
> Common (to other architectures) openbmc applications cannot mention PEL specific concepts like callout priorities

I'm not so sure.  Could you ask if anyone would be interested in the feature being in the base?

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/29349

**Comment by spinler** [comment]
Merged.
