### ISSUE TITLE
Fill in FRU identity callout section for new callouts

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1609]
This section has things like CCIN/PN/SN, location code, maint procedure, symbolic FRU name.  They need to be gathered and written into the PEL for a FRU callout.  TBD what the index is to do this.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30334/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30334 merged
