### ISSUE TITLE
Handle callouts for CALLOUT_INVENTORY_PATH errors

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1612]
This will be a single inventory item FRU callout. Call it out as high.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30338/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30338 merged
