### ISSUE TITLE
Handle callouts for CALLOUT_DEVICE_PATH errors

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1613]
Will need to grab all of the affected FRUs and their priorities from the MRW hopefully with a script, and turn that into something the code can use to find all of the callouts for the log.

The current script that does this is not good enough because it just has a single FRU without priorities, and we can't really change that because OpenBMC doesn't do callout priorities. May need to turn it off.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
This is complete, closing.
