### ISSUE TITLE
Create 'Resolved Timestamp' property on Logging.Entry objects

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1616]
Knowing when the resolved property was set (either by a user or by code) is useful information for debugging by field support.  So, add a new property to OpenBMC event logs to hold the timestamp of when the property was set to true.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/29734

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30005

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30005 merged
