### ISSUE TITLE
Prioritize 12v fault over downstream faults

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1617]
Design/implement logging for 12v main fault before/instead of pgood/vrm/chip fails.

Create PEL with correct iso procedure callout.

**Comment by bjwyman** [comment]
- [x] 0x1Bxx fault (?)

0x1B01 for IoutOC fault: https://github.com/openbmc/phosphor-logging/commit/90c884031eddeddaa6d506c9abe2a66bc15c8086

psu-ng: Add in detection of IOUT_OC fault: https://github.com/openbmc/phosphor-power/commit/b10b3be0da7284082afab79881d9e015c9ae4728

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/51132

**Comment by bjwyman** [comment]
PSU monitor side to call setPowerSupplyError: https://github.com/openbmc/phosphor-power/commit/10fc6e8746d00faa638b29ba547d82d2f8057ddf

**Comment by bjwyman** [comment]
Note that if the method to call is not present, there is an INFO journal trace, example:
```
phosphor-psu-monitor[19217]: Failed calling setPowerSupplyError due to error sd_bus_call: org.freedesktop.DBus.Error.UnknownMethod: No such method
```

**Comment by bjwyman** [comment]
pseq: Add setPowerSupplyError D-Bus method: https://github.com/openbmc/phosphor-power/commit/ccea2d2b95e1f826d42a14a47b1b30aaec5cd93d

pseq: Clear power supply error at power on: https://github.com/openbmc/phosphor-power/commit/abd64b949bebebe17f0b28131c1a038dd021c255

pseq: Prevent multiple failures: https://github.com/openbmc/phosphor-power/commit/48752626d222ff2d0842ede1b0a66de5ee9595dc

pseq: Issue failures as system terminating: https://github.com/openbmc/phosphor-power/commit/7f20c5d05bf5a44c8e6954f903b9b3c8ec0fd05c

**Comment by bjwyman** [comment]
PEL: Remove severity from power supply errors: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/51629
