### ISSUE TITLE
VPD: Redfish Interfaces

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#1621]
There are requirements to:
* Display VPD inventory in the BMC GUI. (Details like PN/SN/CCIN)
* Program system VPD from the BMC GUI.

This epic will cover:
* Define Redfish interfaces that the BMC will provide to support the above requirements.
* Any backend work in the Redish server to support reading and writing of VPD.

**Comment by santoshpuranik** [comment]
@gtmills : FYI, I have this epic open to define Redfish interfaces for VPD functions in the GUI. At the very least, we have to support displaying the inventory (I think the GUI uses REST APIs for this currently) and the ability to program certain system VPD keywords (ASMi supports this).

Wondering if you have looked at these requirements before and have thoughts on whether we can fit these into standard Redfish somehow.

My very cursory look at the REdfish schemas did not throw out anything obvious.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Closing.  Work is complete.
