### ISSUE TITLE
phosphor-settings :: Make BOTH as the default TimeOwner

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1622]
As we are discussing in the mailing list, TimeOwner is not being liked by anyone and is the time to sunset that feature. As a first step, need to change the default TimeOwner from BMC to BOTH in phosphor-settings

Eventually. TimeOwner related code needs to be removed from time-manager repo.

**Comment by zhanghaodi** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/28684/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/28684 merged
