### ISSUE TITLE
GUI : FED : Research ability to toggle build specific features

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1626]
## Problem
Need a way to use parameters passed to the GUI to keep components (pages) from being included in the JavaScript bundle. Unclear of the possibility and complexity of this.

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29079

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29079 merged
