### ISSUE TITLE
GUI : Firmware Update - Full Redfish Support

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1627]
## SMEs
**BMC SME**: @anoo1, @geissonator, @gtmills 
**PHYP SME**: BJ Vette

## Useful links
- [Discovery box folder](https://ibm.ent.box.com/folder/118008591363)
- [Discovery doc](https://ibm.ent.box.com/notes/727650342693)
- [Wireframes](https://ibm.ent.box.com/folder/122791358096)
- [LoFi Testing plan](https://ibm.ent.box.com/notes/724132578836)
- [Design critique (Refer for running updates on UI)](https://ibm.ent.box.com/notes/690669193362)

## Prototype
- Key screens, single files: https://ibm.invisionapp.com/d/main#/console/15347903/319842088/preview
- Key screens, two file: https://ibm.invisionapp.com/d/main#/console/15347903/319842091/preview
- Key flow with access key update and server shut down: https://ibm.invisionapp.com/d/main#/console/15347903/319842093/preview
- Flow with minimum firmware required error: https://ibm.invisionapp.com/d/main#/console/15347903/319842114/preview
- Flow for copy to backup: https://ibm.invisionapp.com/d/main#/console/15347903/319842121/build
- Flow for running backup image: https://ibm.invisionapp.com/d/main#/console/15347903/319842124/preview

## References/Resources
- [eBMC Feature Item: 4.8.3](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)

## Notes
- Use the associated Epics to find related stories
- The original design story is #420 

* This folder is restricted in accordance with GDPR guidelines.

**Comment by nicoleconser** [comment]
A customer we spoke with yesterday thought that "Copy Running to Backup" literally meant creating a backup of the "Running" image file. This verbiage has caused confusion throughout testing. 

If we don't want to explore other verbiage/labels, we should consider making it more clear that "Running" maps to the "Running" column below (and same with "Backup"). I propose making the "Running" and "Backup" text bold.

**Comment by derick-montague** [comment]
> A customer we spoke with yesterday thought that "Copy Running to Backup" literally meant creating a backup of the "Running" image file. This verbiage has caused confusion throughout testing.

It seems like their needs to be more clarity around the word `copy`. I wonder if something like:
`Replace OP940 Backup image with Running image`

>  I propose making the "Running" and "Backup" text bold.

+1

**Comment by derick-montague** [comment]
@ryanarnell - Can you please make sure the single and double file images associated with this story are updated to include #1249 designs?

**Comment by ryanarnell** [comment]
Will do. We are still deciding on how to handle this with redfish. You can find the ongoing discussion here- https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1580141923030100

**Comment by derick-montague** [comment]
Here is a link to the conversation in our slack channel: 
https://ibm-systems-power.slack.com/archives/G3WAVQYTH/p1584569722242800

**Comment by derick-montague** [comment]
@gtmills - What did I miss here when I copied from the chat.
```
"OnReset": "Apply on a reset."
},
"enumLongDescriptions": {
    "AtMaintenanceWindowStart": "This value shall indicate the HttpPushUri-provided software is applied during the maintenance window specified by the MaintenanceWindowStartTime and MaintenanceWindowDurationInSeconds properties.  A Service may perform resets during this maintenance window.",
    "Immediate": "This value shall indicate the HttpPushUri-provided software is applied immediately.",
    "InMaintenanceWindowOnReset": "This value shall indicate the HttpPushUri-provided software is applied during the maintenance window specified by the MaintenanceWindowStartTime and MaintenanceWindowDurationInSeconds properties, and if a reset occurs within the maintenance window.",
    "OnReset": "This value shall indicate the HttpPushUri-provided software is applied when the system or Service is reset."
},

Not sure we will support more than 2 of these (what we do today)..
"ApplyTime": {
    "enum": [
        "Immediate",
        "OnReset",
        "AtMaintenanceWindowStart",
        "InMaintenanceWindowOnReset"
    ],
"enumDescriptions": {
    "AtMaintenanceWindowStart": "Apply during an administrator-specified maintenance window.",
    "Immediate": "Apply immediately.",
    "InMaintenanceWindowOnReset": "Apply after a reset but within an administrator-specified maintenance window.",
    "OnReset": "Apply on a reset."
},
```
You can schedule a time using MaintenanceWindowStartTime

**Comment by gtmills** [comment]
Edited your comment. Need some discussion on the backend if we will support AtMaintenanceWindowStart, InMaintenanceWindowOnReset

**Comment by derick-montague** [comment]
Based on this conversation, we need to revisit the design to make sure it supports the backend limitations. Here is the workflow as I understand it:

1. User uploads single image with Host and BMC
1. Image will be activated following a successful upload
1. The ApplyTime setting determines if the BMC will be rebooted automatically as part of activation

Based on the ApplyTime options it would seem we need a way for the user to determine that when uploading.

**Comment by derick-montague** [comment]
### Needs
1. Need to make sure that any backend work that. @anoo1 has completed downstream is merged upstream.
1. Determine the backend story that we need to have completed to move forward

### Questions / Assumptions
1. It is assumed that the host will be rebooted in order to apply the single image update. If that is true:
    - How impactful is taking the host down?
    - How important is it that the user understand that this is not just a BMC reboot any longer?

**Comment by nicoleconser** [comment]
Based on today's sprint planning mtg - the 2 new options will be: 

- (1) upload, reboot & apply immediately, or 
- (2) upload only, apply upon next reboot

**Comment by nicoleconser** [comment]
@anoo1 Is it safe to assume that this page needs to include the **Firmware Update Policy**? 

The Firmware Update Policy is currently a standalone page in ASMI, but it just contains a statement saying that if the server is client-managed, firmware updates are only allowed from the client. It also shows the minimum code level supported. 

![Screen Shot 2020-08-05 at 8 35 35 AM](https://user-images.githubusercontent.com/15746733/89424026-db71ea80-d6fc-11ea-876d-ff51c0f55698.png)

FYI @ParishrutB

**Comment by nicoleconser** [comment]
^ above question was resolved on Slack: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1596646776377700

**Comment by nicoleconser** [comment]
**Adriana** says we won’t be shipping with a minimum ship level (that value will only be defined once it is needed). She suggests that the GUI show something like **NA** if the minimum ship level is not present, or show whatever Firmware level was released at GA1, because there won't be anything older than that.

**Comment by gtmills** [comment]
Clarifing note: I am good with NA if the backend is not there or empty but we should not set something besides that on the front end (i.e. we should not "show whatever Firmware level was released at 1st release" on the front end, should be backend).

**Comment by derick-montague** [comment]
If it's empty or not there, what is the value showing it in the first GA?

**Comment by ParishrutB** [comment]
**Regarding Minimum Firmware level:** 

I think they meant that it applies only after they apply this change to a system which had a related hw issue. And that it is already supported. _Waiting for confirmation on this question in the chat._

If that is the case, it would need to be supported in the design right now. Following up to that, I am confused regarding what would happen if user tries to update such a system with a firmware level lower than the minimum value. _Waiting for confirmation on this question in the chat._

Chat link: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1596646776377700

**Comment by ParishrutB** [comment]
**Regarding client managed system:**

@yoshie @Derick Montague @Nicole @Dixsie 

Is there any other page/pre-existing design for this scenario (that a feature/section is not available for a client-managed system)?

If not, then possible options:
1. A message on top of the page. Related sections are removed from the page - so it would be blank.
2. A message on top of the page + related sections are disabled. 

My suggestion is the 1st one. The message should be generic, but we can give an example of HMC. Nicole, I think that was your suggestion as well?

**Comment by derick-montague** [comment]
![image](https://user-images.githubusercontent.com/1183515/89551815-ff066500-d7d0-11ea-9843-15d040645d5f.png)


We will want to determine the content here. HMC is an IBM product and we will need to understand how we know that the the system is managed by an HMC and then determine how we set up this message. This is more of a FED concern, but wanted to share that here.

**Comment by nicoleconser** [comment]
> ![image](https://user-images.githubusercontent.com/1183515/89551815-ff066500-d7d0-11ea-9843-15d040645d5f.png)
> 
> We will want to determine the content here. HMC is an IBM product and we will need to understand how we know that the the system is managed by an HMC and then determine how we set up this message. This is more of a FED concern, but wanted to share that here.

Seems like a question for Stacia?

**Comment by derick-montague** [comment]
> Seems like a question for Stacia?
I was thinking more of a question for engineering and how they are going to determine that a system is being managed by an HMC.

**Comment by nicoleconser** [comment]
> > Seems like a question for Stacia?
> 
> I was thinking more of a question for engineering and how they are going to determine that a system is being managed by an HMC.

Oh! So I just heard back from Rajiv on this (literally just now). He said that Ratan is going to provide a standard Redfish API that will tell the BMC if it is HMC-managed or not. 

My suggestion re: Stacia was for determining the verbiage of the message.

**Comment by derick-montague** [comment]
Thanks!
> My suggestion re: Stacia was for determining the verbiage of the message.

She can help on occasion, but that is not her responsibility in general. I think we need to find a resource that has some bandwidth for us. :)

**Comment by derick-montague** [comment]
There is a base design that @yoshiemuranaka suggested. @ParishrutB will be using that and creating all the flows needed to support and validating the design decisions that were made.

We also need to include the FW Update Policy when a system is HMC managed.

**Comment by ParishrutB** [comment]
Update from Adriana: Even in case of HMC managed systems, code update can be done from the GUI. Other functions on the Firmware page are also unaffected. 

https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1598436528060100

**Comment by derick-montague** [comment]
[Notes from GUI Design Work Group](https://github.com/openbmc/openbmc/wiki/GUI-Design-work-group#concerns-with-different-fw-update-requirements)

#### Concerns with different FW Update requirements
- Intel is interested in using the single file upload pattern
    - Intel currently does not have the same use case as IBM. The host does not need to be powered down in order to upload a new FW image
- Intel does not support TFTP FW uploads
- Bruce M. asked brought up use case about a single file upload that was BMC Only and did that require a host to be powered off in order to apply the update
 
##### Actions
- Research Redfish spec and the `allowed` property to see how to dynamically render GUI elements (FED)
- [Send email to community email list to start discussion about single file update with BMC only update use case](https://lists.ozlabs.org/pipermail/openbmc/2020-October/023795.html)

**Comment by nicoleconser** [comment]
Enhancements that did not make it into this MVE can be found in #2891
