### ISSUE TITLE
Catering for populating GARD, Callout, Deconfig data in error log 

### ISSUE THREAD

**Issue by devenrao** [ibm-openbmc/dev#1630]
1) Need to update targets to gard, callout, deconfig as part of error log object
2) Information need to be pulled from the error xml file.
Dependency: Corresponding support in phosphor-logging

**Comment by devenrao** [comment]
Matt said
"What do you think the callouts will be?  Inventory strings?  location code strings? 

I need to add functionality to the PEL daemon to be able do arbitrary mappings of AdditionalData key names to some sort of internal callout tables, which can be used here if necessary, or you can pass well known names in directly most likely as this is Power specific code so we don't need so much abstraction of the PEL stuff."

https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/25443/11/designs/error-log-handling-for-phal.md

**Comment by devenrao** [comment]
Still need more discussion.

**Comment by RameshIyyar** [comment]
patch details : https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/36651
