### ISSUE TITLE
Set and store PDBG error level

### ISSUE THREAD

**Issue by devenrao** [ibm-openbmc/dev#1632]
PDBG need to change the debug level externally probably through some tool or
command
1.1 As pdbg is implemented as a library, it should cater to store the pdbg level in persistent location in some conf file and use it.
1.2 Should allow the setting through the pdbg command
1.3 PDBG should load the pdbg from a persistent location
1.2 Any getcfams should output all the traces.
1.4 This kind f thing was used in scand traces in FSP

**Comment by devenrao** [comment]
not yet started

**Comment by ojayanth** [comment]
Proposed approch is to environment variable for setting pdbg log level.
Code changes required in pdbg side 
 - Enabling environment variable based logging
- Enable addition logging message to debug hw failures.

Increasing complexity .

**Comment by rfrandse** [comment]
tracking in jira
