### ISSUE TITLE
Implement CreateWithFFDCFiles D-Bus interface

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1633]
When the D-Bus interface https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/26544 is merged, implement this new method and create UserData sections for each file passed in, taking care of padding the data to a 4B boundary, and setting the component ID and subType and version fields appropriately based on the method args.

BSON data needs to have the padding removed before parsing or it will fail, so the pad amount needs to be stored somewhere in the section.

Also, need to check that the PEL will be under 16KB still before adding the section.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30702/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30702 merged
