### ISSUE TITLE
peltool: Print CBOR and Text UserData sections

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1634]
The CBOR needs to have its padding removed before parsing, so the code that creates the CBOR sections from FFDC files must be done first.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30705

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30705 merged
