### ISSUE TITLE
Create packages for phosphor-power repo apps

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1635]
There are multiple apps in the phosphor-power repo.  Not all of them should be included in every firmware image.  For example, there are two different PSU monitoring apps.  Some apps may not be desired on a given system type.

A method is needed to select which apps should be included in a firmware image.  This should be done in the bitbake recipe and appends.

Brad Bishop recommended continuing to have all the apps in the repo build and install within the meson build process.  However, bitbake should place each app and its associated config/service files into separate bitbake packages.  Then each firmware image should select which bit-bake packages they want to include.

**Comment by bjwyman** [comment]
Just noticed that there was a plan to do this, apparently, based on a comment in #917: https://github.com/ibm-openbmc/dev/issues/917#issuecomment-542007739

**Comment by mine260309** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/29105
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/29106
