### ISSUE TITLE
PLDM: implement validation of BIOS related JSON config files

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1637]
- Write a python script in openbmc/pldm to validate BIOS JSONs against corresponding JSON schema files (to be written as well). Make use of the python `jsonschema` module.
- The JSON schema files and the python script have to be placed in the pldm repository.

Based on https://github.com/openbmc/pldm/tree/master/libpldmresponder/examples/bios,

For the enum_attrs.json, validate that :

a) there is an array called "entries", contained of one or more JSON object types
b) each object has the following mandatory properties : attribute_name(string), possible_values(array of strings), default_values(array of strings)
c) possible_values has at least two items
d) default_values has at least one item
e) the items in the default_values array must be contained in the possible_values array
f) an object can have an optional "dbus" section, with the following manual properties : object_path(string), interface(string), property_name(string), property_type(string), property_values(array)
g) object_path must match the pattern : one or more  of "/[a-z][0-9][_]"
h) interface must match the pattern : one or more of "[a-z][0-9][_]" separated by periods
i) property_type must be one of bool, uint8_t, int16_t, uint16_t, int32_t, uint32_t, int64_t,
 uint64_t, double, std::string
j) the type of the items in the property_values array must be the same as the type mentioned in property_type

**Comment by nmuruli** [comment]
Good to have ISSUE. Post GA

**Comment by rfrandse** [comment]
tracking in jira
