### ISSUE TITLE
PFP::presence: Update json configuration loading

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#1639]
The direction is to have the `system-type` provided on dbus. This `system-type` will reflect the specific machine configuration to load. Use this `system-type` property value as a subdirectory to find the location of the json configuration to load & use.

- [x] Verify the `/etc` location does not require a change to use the `system-type`. (No need to use `system-type` when `/etc` is designed to contain a json config for override/patch purposes on a machine and is placed there manually on the bmc.)
- [x] Append the `system-type` as a subdirectory to the default config location. i.e.) `/usr/share/phosphor-fan-presence/presence/[system-type]/config.json`
- [x] If no `system-type` property is provided, check for a json config file in the default location of `/usr/share/phosphor-fan-presence/presence/` to allow loading a config without the use of putting a `system-type` property (or anything else) on dbus.

**Comment by msbarth** [comment]
When no `system-type` is found initially (after subscribing to interfacesAdded as well), check the default `/usr/share/phosphor-fan-presence/presence/` location, and if nothing is found there and a poweron is attempted where no config has been loaded yet, fail and halt the poweron.

**Comment by msbarth** [comment]
Details for retrieving the `system-type` info

Interface : `xyz.openbmc_project.Inventory.Decorator.Compatible`
Property : `Names`
Property Details : Contains `system-type` in the form of "manufacturer, model" (i.e. "ibm", "rainier") where the use of the "model" will determine the `system-type` and which config file to load.

**Comment by msbarth** [comment]
At this time, I have not found a reason that fan presence needs to subscribe to an interfacesAdded signal since the fan presence service drives when to start checking for fan presence so once the service is started, everything must be available for it to load its configuration. An interfacesAdded signel subscribtion is unnecessary because of this.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/31907

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/31907 merged
