### ISSUE TITLE
GUI : FED :  Application Header Data

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1640]
## Requirements

- [x]  Get data for Status
- [x] Get data for Server Health
- [x] Refresh data

**Comment by derick-montague** [comment]
Moved to IBM tracking repo

**Comment by derick-montague** [comment]
Duplicate of #1211

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29172
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29178/1

I am concerned about implementing inconsistent patterns in the header for status, refresh and profile settings. I can't find the final mock-up but I think Jandra and Kathy both liked having the last refreshed timestamp show in a tooltip when **hovering** over refresh button.
https://bootstrap-vue.js.org/docs/components/tooltip

Once we have the user profile settings in place, we will want to use a dropdown to show the logout and link to profile page 
https://bootstrap-vue.js.org/docs/components/dropdown
>They're toggled by clicking (or pressing space or enter when focused), not by hovering; this is an intentional design decision.

Using these two different components will cause unexpected inconsistencies for the user.

The commit for refresh functionality doesn't implement the tooltip on hover––maybe we can revisit when we add the profile settings page? Thoughts? @derick-montague @ryanarnell
