### ISSUE TITLE
GUI : FED : Focus States missing for btn-link class

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1641]
## Tasks
1. Create a bootstrap overrides scss file
2. Add a focus state that will match the focus state for links

## Overview
The reason for adding the overrides is to be able to not tightly couple any overrides with global or scoped styles. This will allow for any overrides to be easily tested and removed if/when Bootstrap is updated in the future. I submitted an [issue in the bootstrap repo](https://github.com/twbs/bootstrap/issues/29891).

### Original Issue
https://github.com/gtmills/phosphor-webui-vue/issues/59

**Comment by derick-montague** [comment]
@yoshiemuranaka - can you double check to see if we have fixed this.

**Comment by yoshiemuranaka** [comment]
Button link variants should have a focus state
https://github.com/openbmc/webui-vue/blob/master/src/assets/styles/_buttons.scss#L22

Navigation link items were not button link variants so did not inherit the focus styles. Fix for the navigation focus here
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29034
