### ISSUE TITLE
Identify the work needed to get the IBMi console work with BMC based system

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1642]
This story is to identify the work needed for the IBMi console. 

- Identify how it was working in the legacy system
     1) Set the partition details via fsp remote
     2) telnet 30002 port
     3) All other consoles(aix,linux,phyp) works with the above settings, only IBMI doesn't work
     4) Need to find a way to make it work on the legacy system via telnet to 30002 and find out what extra changes are required for the BMC

**Comment by rfrandse** [comment]
@ratagupt Is there an epic this can be assigned?

**Comment by ratagupt** [comment]
This was an story which I worked with manufacturing ...I had given the script.
No more work needed here hence closing it.
