### ISSUE TITLE
GUI : FED : Add Toast component

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1644]
## Overview
Add the bootstrap toast component and start using with success and error callbacks

## Requirements
- [ ] Consistent way to call error messages. Currently using store, will that be where we initiate toasts? Need a consistent pattern

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29127
@derick-montague @dixsie 
Would like to hear your thoughts on this pattern for handling error/success backend response? In this commit I
- console.log all errors in the store (so we should not console log on component level)
- Handle backend errors/success messages in the store (map backend errors to user friendly messages at the store level)

Curious if/how this will work with translations also.

Also FYI, I couldn't find an easy way to include the status icons inside of the toasts. background-image would be easiest but wouldn't allow us to change colors with sass. If we think this is important enough to pursue, we'll want to revisit.

**Comment by derick-montague** [comment]
> console.log all errors in the store (so we should not console log on component level)
Handle backend errors/success messages in the store (map backend errors to user friendly messages at the store level)

This makes sense to me

> Curious if/how this will work with translations also.

@dixsie - Any thoughts on this. Seems like it shouldn't be an issue. We did figure out how to translate the route meta data, right?

> Also FYI, I couldn't find an easy way to include the status icons inside of the toasts. background-image would be easiest but wouldn't allow us to change colors with sass. If we think this is important enough to pursue, we'll want to revisit.

I agree. The Bootstrap toast messages out of the box don't meet our current design patterns. I expect we want an easy way to determine the type of toast. Can we pass a prop and based on that prop just show a different icon. I'm sure you probably already thought about that.

**Comment by dixsie** [comment]
@yoshiemuranaka It should work with translations https://github.com/kazupon/vue-i18n/issues/415

**Comment by dixsie** [comment]
@yoshiemuranaka It should work with translations

**Comment by yoshiemuranaka** [comment]
> I agree. The Bootstrap toast messages out of the box don't meet our current design patterns. I expect we want an easy way to determine the type of toast. Can we pass a prop and based on that prop just show a different icon. I'm sure you probably already thought about that.

I've styled them to get as close to our styles as possible...this is how they look with commit
<img width="381" alt="Screen Shot 2020-02-07 at 7 54 15 AM" src="https://user-images.githubusercontent.com/8097306/74044002-36f63200-497f-11ea-8b13-a24a47da31e5.png">

They are just missing the icons https://github.com/ibm-openbmc/dev/issues/1274

<img width="614" alt="Screen Shot 2020-02-07 at 7 56 14 AM" src="https://user-images.githubusercontent.com/8097306/74044119-67d66700-497f-11ea-9fdf-294d5093884d.png">

**Comment by yoshiemuranaka** [comment]
Since the toasts are created 'on-demand' via JS, i'm not messing with the actual components in the template. The other option would be to have <b-toast> components for each type somewhere near document root and initiate with different content, but didnt' see an easy way to do that either

https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29127/2/src/components/Mixins/BVToastMixin.js
