### ISSUE TITLE
Modify when phosphor-regulators starts/stops monitoring

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#1653]
The phosphor-regulator application has a "monitor" D-Bus method with a boolean argument.  This method is used to start and stop monitoring regulators.

Regulator monitoring includes the following activities:
* Reading regulator sensor values.  This was done by driver + hwmon on some previous systems.
* Checking for phase faults (if needed by hardware)
* Checking for redundant enable faults (if needed by hardware)

Regulator monitoring should be *started* right after the power sequencer has enabled (turned on) all regulators and power supplies.

Regulator monitoring should be *stopped* right before the power sequencer will disable (turn off) all regulators and power supplies.

This issue involves changes to service files for system types that use the phosphor-regulators application.

**Comment by bradbishop** [comment]
> On Jan 30, 2020, at 3:41 PM, Shawn McCarney <notifications@github.com> wrote:
> 
> The phosphor-regulator application has a "monitor" D-Bus method with a boolean argument. This method is used to start and stop monitoring regulators.
> 
> Regulator monitoring includes the following activities:
> 
> 	• Reading regulator sensor values. This was done by driver + hwmon on some previous systems.
> 	• Checking for phase faults (if needed by hardware)
> 	• Checking for redundant enable faults (if needed by hardware)
> Regulator monitoring should be started right after the power sequencer has enabled (turned on) all regulators and power supplies.
> 
> Regulator monitoring should be stopped right before the power sequencer will disable (turn off) all regulators and power supplies.
> 
> This issue involves changes to service files for system types that use the phosphor-regulators application.

A straw-man alternative here would be to have phosphor-regulators not delegate when to start/stop and own that logic itself.  Pros/Cons ?

**Comment by smccarney** [comment]
I thought service/unit files were the encouraged way to cause code to run at certain points in the power on/off process.

If you think it would be better for this application to listen for D-Bus events and react accordingly, that would be fine with me.  It would probably be easier because it would avoid the need to create and install service/unit files on a per-system basis.

What do you recommend?

**Comment by bradbishop** [comment]
> I thought systemd service/unit files were the encouraged way to cause code to run at certain points in the power on/off process.

The best practices around this are pretty fuzzy.  Instead I would say: "systemd services are the encouraged way to **start/stop applications** at certain points in the power on/off process."

But we aren't starting or stopping an application here - we are making an already running program transition into a different state (monitor vs don't monitor).  We do that sort of thing in other places using systemd units too but IMO it would just be simpler to have the application itself decide when to transition.

This does generate an idea - what if we simply have systemd start/stop your program in the places you described?  That would remove the need for you to write any code to monitor anything?  Does your application need to be running when the VRMs don't have power?

**Comment by bradbishop** [comment]
@geissonator fyi...

**Comment by smccarney** [comment]
Brad Bishop and I discussed his comments above earlier today.  Summarizing the discussion here:

> But we aren't starting or stopping an application here - we are making an already running program transition into a different state (monitor vs don't monitor). We do that sort of thing in other places using systemd units too but IMO it would just be simpler to have the application itself decide when to transition.

We discussed some alternatives to using systemd units.
- The power sequencer application could call the phosphor-regulators D-Bus methods directly to configure VRMs, start monitoring, and stop monitoring.  However, this would tightly couple those two applications together.  For example, if a system doesn't use the phosphor-regulators application or it uses a different power sequencer application, then this solution would require changes.
- The phosphor-regulators application could listen for D-Bus signals sent from systemd when boot steps are completed.  However, Brad said they tried this in the past, and it was ugly.  systemd doesn't publish those by default; you have to call a 'subscribe' method first.  Once it does start publishing them, they are somewhat complicated to parse.

> This does generate an idea - what if we simply have systemd start/stop your program in the places you described? That would remove the need for you to write any code to monitor anything? Does your application need to be running when the VRMs don't have power?

This has been discussed a few times in the past.  The reasons I want to start the application at standby and keep it running are:
* Parse JSON file (possibly thousands of lines long) during a non-critical time period.  If I parse it when we are booting, and that takes a second or two, that is a direct add of a second or two to the boot time.  The power sequencer cannot start turning on VRMs until my app is done parsing the config file and configuring the VRMs.
* Allow the sharing of information between regulator operations.  For example, if an I2C error was logged against a device when configuring it, it would be possible to avoid logging another I2C error against the same device during sensor monitoring.  Also, if a high-end system is designed with redundant device paths, and one path is found to be faulty, all regulator operations can use the other device path.
* I was planning to create the regulator sensors on D-Bus at standby with an Unavailable state.  (Note: I am currently unsure if I can completely achieve this due to the dynamic nature of the config file).

**Comment by msbarth** [comment]
I've started implementing the use of a private interface that will be extended by the manager object to handle the entry points to change the mode of the phosphor-regulators application. In turn with this we could look at utilizing a small external program/script that uses this private interface to change the mode which in turn is called specifically by the services at the appropriate states.

**Comment by msbarth** [comment]
Use `regsctl` for the name of the small external program/script that will control the mode in which the phosphor-regulators application will run in at the appropriate different states of the system.

**Comment by msbarth** [comment]
Private manager dbus interface commit -> https://gerrit.openbmc-project.xyz/30840
This replaces the use of `sdbus++` to generate the manager dbus interface uses by phosphor-regulators.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/28875

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/28875 merged
