### ISSUE TITLE
GUI : FED : Local User account settings

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#1654]
## As Is

New functionality

## To Be

Add account settings management on local user page

### Functions
- [x] Max login attempts
- [x] Account lockout type

**Comment by derick-montague** [comment]
Can we add sorting so that root user is always first user? There was a story for that and I am wondering if that is still necessary.

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29586
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29637
