### ISSUE TITLE
Design: pHAL: DTM Packaging in Hostboot build 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1656]
This is a design story for  #666

**Comment by ojayanth** [comment]
#666 packaging device tree binary blob  in  hostboot task is also handled as part of this  issue.

**Comment by lkammath** [comment]
Packaged with hand-coded device tree and given send the PR for Hostboot BUP

https://github.ibm.com/open-power/op-build/pull/200/
https://github.ibm.com/open-power/pnor/pull/8

**Comment by lkammath** [comment]
https://github.ibm.com/open-power/op-build/pull/275
https://github.ibm.com/open-power/pnor/pull/13
https://github.ibm.com/open-power/pnor/pull/15/

It is all done and integrated to HB build.

**Comment by RameshIyyar** [comment]
I have enabled pdata packaged to generate device tree in op-build and below PR is reference for that
https://github.ibm.com/open-power/op-build/pull/237

**Comment by lkammath** [comment]
integrated and available in build
