### ISSUE TITLE
Integrate bmcweb into meta-ibm layer

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#166]
All remaining work required to fully move to bmcweb.

- Enable and verify all REST api's
-- Lots of testing here, web sockets, new logging requirements, anything else special done in current REST server.
- Remove nginx and use bmcweb directly

**Comment by mzipse** [comment]
I'm assuming this is required for OP930.  Marking 9.3.1.

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Done!

**Comment by rfrandse** [comment]
refresh
