### ISSUE TITLE
PLDM: oem-ibm: detect max xdma buffer size

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1661]
For performing DMAs, a max size (and a corresponding mmap) is hard-coded today : https://github.com/openbmc/pldm/blob/master/oem/ibm/libpldmresponder/file_io.hpp#L30. DMA operations larger than this are split-up : https://github.com/openbmc/pldm/blob/master/oem/ibm/libpldmresponder/file_io.hpp#L112. The problem with this is the max size can change across platforms.

Here's a better solution :
a) don't assume a max size
b) from the `transferAll` function, pass in the `length` as is to `DMA::transferDataHost`
c) In `DMA::transferDataHost`, attempt to mmap the `pageAlignedLength`. If this fails with errno=ENOMEM, bisect the length (divide by 2), and retry - continue this until the mmap succeeds.
d) Have the looping logic similar to `transferAll` to split up the dma operation into max chunks found in c). Still need to mmap for each chunk and ensure to mmap page aligned sizes.
e) Remember the value in c) once computed, so that it doesn't have to be remembered each time

To test this, make sure the host firmware boots.

**Comment by amboar** [comment]
> Still need to mmap for each chunk and ensure to mmap page aligned sizes.

This isn't the case, you just reuse the existing mapping and submit another job. The `write()` syscall will either block until the DMA is complete or if you're using non-blocking IO you can `poll()` for completion.

**Comment by tomjoseph83** [comment]
> > Still need to mmap for each chunk and ensure to mmap page aligned sizes.
> 
> This isn't the case, you just reuse the existing mapping and submit another job. The `write()` syscall will either block until the DMA is complete or if you're using non-blocking IO you can `poll()` for completion.

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/29446

**Comment by rfrandse** [comment]
tracking in jira
