### ISSUE TITLE
GUI : Research : Consistent form save layout pattern

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1662]
## Overview
Create a pattern for saving and clearing forms that is consistent throughout the site. We have a couple of different patterns leading to a need for a more consistent and intuitive user experience. 

## Considerations
- [x] Consistency on disabled/enabled prior to form validation
    Enabled showing errors when on action rather than disabled until form valid
- [x] Clarity for cancel button
- [x] Association of buttons with form (examples: LDAP layout)

**Comment by derick-montague** [comment]
Here is a Network page redesign 
https://ibm.invisionapp.com/d/main#/console/15354657/319398051/preview

**Comment by ParishrutB** [comment]
This the Mural on which we are posting the screenshots and our initial observations.

**Comment by ParishrutB** [comment]
Findings mural: https://app.mural.co/invitation/mural/ibmpower1831/1583320787325?sender=parishrutb8073&key=f63462be-0f3f-425e-8704-b694a7ad3a0d

We are going to articulate our findings so far, in this mural.
