### ISSUE TITLE
GUI : FED : Guidellines - Add internationalization documentation

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1663]
## Overview
Add documentation to explain:

1. Key naming convention
1. How to use the vue i18n plugin
1. Resource references

**Comment by sandeepasingh116** [comment]
Resolved by  https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/41128

**Comment by derick-montague** [comment]
Merged
