### ISSUE TITLE
PLDM: Dual-boot: BIOS attribute for choosing OS

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1664]
There are 3 elements to the work involved here. They're all data file changes :

- In the phosphor-dbus-interfaces, define a new D-Bus interface in the /com/ibm namespace. This interface should effectively be an enum property that can be read/written, to choose between PowerVM and OPAL as the hypervisor

- The next step is to have the settings app create a D-Bus object that would implement the above interface. The settings app can do this by reading YAML files. Add a new YAML file for the same here - downstream openbmc/openbmc/tree/1010/meta-ibm/meta-witherspoon/recipes-phosphor/settings/phosphor-settings-manager. Look at existing examples here. FYI, the settings app is https://github.com/openbmc/phosphor-settingsd.

- The last step is to define a corresponding PLDM BIOS attribute. This will be of type Enum. Make the new entry here : downstream openbmc/openbmc/blob/1010/meta-ibm/meta-witherspoon/recipes-phosphor/pldm/pldm/enum_attrs.json.

Testing:
- With pldmtool, make sure the new attribute shows up in all 3 types of BIOS tables.
- Modify the attribute value via busctl, make sure the BIOS tables are updated (using pldmtool)
- Use pldmtool raw to update this BIOS attribute's current value, and make sure D-Bus property is updated
- Make sure the new attribute shows up via host firmware's PLDM tools.

**Comment by mzipse** [comment]
Assigning to Deepak for now.  He can reassign once someone is ready to work on this.

**Comment by dkodihal** [comment]
The settings objects are created via YAML entries - see https://github.com/openbmc/openbmc/blob/master/meta-phosphor/recipes-phosphor/settings/phosphor-settings-defaults/defaults.yaml. Since this an IBM specific setting, it will go an override here - https://github.com/openbmc/openbmc/tree/master/meta-ibm/meta-witherspoon/recipes-phosphor/settings/phosphor-settings-manager

Details about the BIOS attribute :


Name: hb-hyp-switch
BIOS DataType: BIOSEnumeration
Possible Values: “PowerVM”, “OPAL”
Default Value: “PowerVM”
