### ISSUE TITLE
PLDM: Fix GetBIOSAttributeCurrentValueByHandle

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1666]
GetBIOSAttributeCurrentValueByHandle should add certain headers to the response as per table 14 from https://www.dmtf.org/sites/default/files/standards/documents/DSP0247_1.0.0.pdf. At the moment it doesn't do that.

**Comment by wangzqbj** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/28978

**Comment by wangzqbj** [comment]
Merged by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/28978
