### ISSUE TITLE
PCIe switch temp sensor fan control loop integration support

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1669]
PCIe switches on optional (Flett) cable cards.  Could be 0-3 cards present, any pcie slot.  Would have to get switch temps from phyp due to security concerns with pcie switch.  Not in FSP today, POR will not be supported. 

TMP461 temp sensors were added that can "remotely" read the thermal diode inside pcie switches to report accurate temps.  The tmp401.c device driver already supports the TMP461 sensor.  Then fit into typical hot adapter support (eg Bearpaw, https://github.com/ibm-openbmc/dev/issues/1668).  Not hot-pluggable, only nvme drives are hot-pluggable.  Some unknowns since new switch design, eg new errata published regarding a potential 3 degree C error in the internal thermal diode.

**Comment by msbarth** [comment]
> eg new errata published regarding a potential 3 degree C error in the internal thermal diode

We should be able to handle this using an `OFFSET` in the hwmon config for the TMP461 device similar to what we had done with the ambient sensor on Witherspoon
For reference -> https://github.com/openbmc/openbmc/blob/master/meta-ibm/meta-witherspoon/recipes-phosphor/sensors/phosphor-hwmon/witherspoon/obmc/hwmon/ahb/apb/bus%401e78a000/i2c-bus%40100/dps310%4076.conf#L6

**Comment by spinler** [comment]
We have the epic https://github.com/ibm-openbmc/dev/issues/574  for tracking all of the support for the hot adapter temp sensors, which will cover this.  Will close this.  I don't think we need to move any of these points over.

Officially, both the Flett and Bear River have a TMP435 that have the remote temp wired to the switch.  Bear River is on both Everest and Rainier.

**Comment by derekhoward55** [comment]
hey @spinler do you mean https://github.com/ibm-openbmc/dev/issues/1668 tracks this work?

**Comment by spinler** [comment]
yea that one :)
