### ISSUE TITLE
Move Remote Logging to Redfish (/xyz/openbmc_project/logging/config/remote)

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1673]
/xyz/openbmc_project/logging/config/remote should be moved to Redfish. 
I beleive this is already in the Redfish spec 
FYI @santoshpuranik

**Comment by gtmills** [comment]
Used in openbmctool and the GUI here:
https://github.com/openbmc/openbmc-tools/blob/182c3a3b6447158f673188340c63f691950314dd/thalerj/openbmctool.py#L2480

https://github.com/openbmc/phosphor-webui/commit/e4194ce0dc8a941c4f30fd0995f9ba4c13cec560

**Comment by santoshpuranik** [comment]
> I beleive this is already in the Redfish spec

@gtmills : Do you know which Redfish schema covers this? I don't find anything in the LogService schema that can control the remote log server IP/port.

**Comment by gtmills** [comment]
https://redfishforum.com/thread/305/redfish-ocp-virtual-summit
look at "Syslog Configuration proposal"

**Comment by gtmills** [comment]
Needed for GUI for parity with AngularJS. 
From email on 5/18/2020: 
```
If we are to simply carry forward the rsyslog implementation, yes I think 1Q21 should work.
I will discuss this in one of our design meetings again, but I would be OK if the GUI work can come in later.
```

**Comment by gtmills** [comment]
An update: 
Santosh Puranik  7 hours ago
This is not planned anytime soon. 4Q most likely at the earliest

**Comment by lxwinspur** [comment]
@gtmills @mzipse 
Is there any progress on this issue?

**Comment by rfrandse** [comment]
tracking in jira
