### ISSUE TITLE
GUI : FED : Consistent Definition list and Label pattern

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#1680]
## As Is
Currently using out of the box bootstrap font weight

![Screen Shot 2020-02-03 at 3.00.00 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/b158685b-36ad-4cb3-a40a-4bc1c2c4eab1)

![Screen Shot 2020-02-04 at 10.15.55 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/440b8b14-d6e0-4f39-8def-328c3dfffaf1)

 ![Screen Shot 2019-12-06 at 1.17.32 PM.png](https://images.zenhubusercontent.com/5c59b678d6ca520817b16dbf/a6f41a7c-f64d-493b-9016-ee887bed0891)

## To Be
Update font-weight to be consistent on all pages

### Considerations

- [ ] Should labels be uppercase or lowercase? 
- [ ] Reusable pattern?

**Comment by derick-montague** [comment]
Regarding the considerations around labels being UPPER CASE or Sentence case or Proper Case, regardless of the choice, we need to make sure we do not use the CSS text-transform property to establish the casing.

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29561
