### ISSUE TITLE
GUI : FED : Profile Settings

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1681]
## Overview
Add profile settings page that allows user to change their own password.

Related to #1682

**Comment by ryanarnell** [comment]
GUI Issue- https://github.com/ibm-openbmc/dev/issues/1381
Invision mockup - https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319407923_02-Profile-Settings-03

**Comment by derick-montague** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31733

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31733 merged
