### ISSUE TITLE
GUI : FED : Persist language settings

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1682]
## Overview
We need a way to persist language settings and provide a good experience to users. Currently, language is set on login and a full page refresh will reset to english. 

Also, need to determine how/where a user will change any language settings after logging in. One suggestion is to have an language option on the profile settings page.

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29769
