### ISSUE TITLE
GUI : FED : Local User Management - Batch actions

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1683]
## As Is
No batch actions in the vue rewrite

## To Be
As an admin user I need to be able to perform multiple edit actions on the system users, e.g remove, enable, disable.

![image](https://user-images.githubusercontent.com/1183515/73764918-6156ae00-4739-11ea-886b-21a173c800cb.png)

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29461
