### ISSUE TITLE
GUI : FED : Local User Management - Password visibility toggle

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1684]
As an open bmc user
I want to be able see the the password I am entering
so that I can be sure I am entering the correct password

## As Is
In the Vue rewrite, we don't have a way for the user to toggle the visibility of text in a password input element.

## To Be
Add the ability for the user to toggle the text visibility within a password input

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29576
