### ISSUE TITLE
PLDM: Improve FRU table construction algorithm

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1689]
The current PLDM FRU table construction code (for FRUs the BMC has access to, in terms of reading VPD) are constructed based on JSON configuration files, which the code looks for here - https://github.com/openbmc/pldm/blob/master/libpldmresponder/fru.cpp#L20. These JSON files have information on what D-Bus interface/objects to pull out D-Bus properties from, and to what PLDM FRU fields to map them to. Here's an example :

```
{
   "record_details":
   {
        "fru_record_type" : 1,
        "fru_encoding_type": 1,
        "dbus_interface_name": "xyz.openbmc_project.Inventory.Item.Panel"
   },
   "fru_fields":[
      {
         "fru_field_type" : 2,
         "dbus":
            {
               "interface" : "xyz.openbmc_project.Inventory.Decorator.Asset",
               "property_name" : "Model",
               "property_type" : "string"
            }
      },
      {
         "fru_field_type" : 3,
         "dbus":
            {
               "interface" : "xyz.openbmc_project.Inventory.Decorator.Asset",
               "property_name" : "PartNumber",
               "property_type" : "string"
            }
      },
      {
         "fru_field_type" : 4,
         "dbus":
            {
               "interface" : "xyz.openbmc_project.Inventory.Decorator.Asset",
               "property_name" : "SerialNumber",
               "property_type" : "string"
            }
      }
    ]
}
```

While this mechanism is good for fetching platform/OEM specific FRU information, it should be possible to map D-Bus objects implementing standard D-Bus inventory interfaces (https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Inventory/Item) to PLDM FRU concepts. For eg we know that an object implementing the Item.BMC interface is the BMC card (on IBM systems, at the moment, these interfaces are implemented by the phosphor-inventory-manager app. In the future that could change to entity-manager, but the should be a minimal impact to this work (to switch to fetch objects from entity manager)). With this approach, it becomes necessary to write config JSONs only if OEM properties need to be added to the FRU record.

This story is to introduce a code path in case no FRU JSONs are found, and in that case query the inventory manager and build the FRU record table based on that information. D-Bus properties that can't be mapped to standard PLDM FRU properties can be left out. The mapping between the D-Bus properties to the PLDM FRU properties can be in the code.

**Comment by wangzqbj** [comment]
Resolved-by: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/32176

> This story is to introduce a code path in case no FRU JSONs are found, and in that case query the inventory manager and build the FRU record table based on that information.

@dkodihal , I'm not sure if I do it right.

what I do is 

1.  Remove the Cpu_General.json and Board_General.json
2. Add FRU_General.json
3. Add fru general record info to each entity defined in FRU_Master.json
