### ISSUE TITLE
PLDM: libpldm: GetNumericEffecterValue and GetSensorReading

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1690]
Implement encode/decode APIs for GetNumericEffecterValue and GetSensorReading from https://www.dmtf.org/sites/default/files/standards/documents/DSP0248_1.2.0.pdf.

**Comment by JolieKu** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/30069
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/30682
merged
