### ISSUE TITLE
GUI : FED : Overview - Move Firmware version call to use Redfish

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1694]
https://github.com/openbmc/webui-vue/blob/5fa09a25c207d13ec1c9a8df92fc058f15a872e1/src/store/modules/Configuration/FirmwareStore.js#L26

setBmcActiveVersion uses `'/xyz/openbmc_project/software/enumerate')` today, can use the bmc firmware under at `/redfish/v1/Managers/bmc` 

setHostActiveVersion can use /redfish/v1/Systems/system 

@dixsie FYI

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29787
