### ISSUE TITLE
GUI : FED : Overview page move total power & power cap over to Redfish 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1695]
https://github.com/openbmc/webui-vue/blob/5fa09a25c207d13ec1c9a8df92fc058f15a872e1/src/store/modules/Control/PowerConsumptionStore.js#L21

 .get('/xyz/openbmc_project/sensors/power/total_power') can be found at /redfish/v1/Chassis/chassis/Power/       "PowerConsumedWatts": 232.0,

@dixsie 

https://github.com/openbmc/webui-vue/blob/5fa09a25c207d13ec1c9a8df92fc058f15a872e1/src/store/modules/Control/PowerCapStore.js#L22

        .get('/xyz/openbmc_project/control/host0/power_cap') 

can be PowerLimit from 

curl -k https://${bmc}/redfish/v1/Chassis/chassis/Power
  ...
  "PowerControl": [
    {
      "PowerLimit": {
        "LimitInWatts": null
      }

**Comment by dixsie** [comment]
Need to combine power cap and power consumption store based on conversation in https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29521/2/src/store/modules/Control/ControlStore.js#4

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29763
