### ISSUE TITLE
GUI : FED : Arrange the navigation in alphabetical order

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1699]
## As Is
The navigation menu items are arranged in a random order.

## To Be
The navigation menu items should be arranged alphabetically.

**Comment by derick-montague** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29089

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29089 merged
