### ISSUE TITLE
Design and implement openBMC REST API to  Update digitally signed certificate.

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#17]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ojayanth](https://github.com/ojayanth)**
_Thursday Aug 02, 2018 at 10:56 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3340_

----

  Provide REST API to upload Digitally signed certificate for the specified type

**Comment by rfrandse** [comment]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ojayanth](https://github.com/ojayanth)**
_Thursday Aug 02, 2018 at 11:01 GMT_

----

This is not required #3331 already created to track this.

**Comment by ojayanth** [comment]
Just realise issue #3331 is an epic.

**Comment by ojayanth** [comment]
Design REST API to update Singed certificate and Private key based on the type.
  Provide REST interface for update the signed certificate. Input should .pem file which includes both Signed certificate and private key.
Implementation of REST API to update Signed certificates.
    - Restserver changes related to API implementation.
    - Move  the certificate to /tmp/cert/<type>/ <filename.pem>.

**Comment by rfrandse** [comment]
Jayanth Othayoth [6 minutes ago]
Code is merged , you ca close this
