### ISSUE TITLE
GUI : FED : Update contributing file to repo

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1700]
## As Is
There aren't any contribution guidelines currently.

## To Be
Add contribution guidelines that include: 

- [ ] Code of conduct link - https://github.com/openbmc/docs/blob/master/code-of-conduct.md
- [ ] Link to project documentation /docs
- [ ] Submitting code
    - Similar or link to https://github.com/openbmc/docs/blob/master/CONTRIBUTING.md#submitting-changes
    - Could include link to or use info from https://chris.beams.io/posts/git-commit/

**Comment by nicoleconser** [comment]
Scratch pad for what this page content will be: https://ibm.box.com/s/5nlvvgebrltpfcpy1i6b64ogd3dsk9f6

**Comment by nicoleconser** [comment]
"User Research" section is done! https://ibm.box.com/s/5nlvvgebrltpfcpy1i6b64ogd3dsk9f6

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/32853
