### ISSUE TITLE
PFP::control - Integrate component temps in fan control loop

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1701]
Read component temp sensors using appropriate interfaces. BMC-connected and from OCC.

Backplane has a TMP275 sensor, get from dbus.

Processor and dimm and pmic temps from OCC.  Also read/report total power consumption read from the OCC (require hwmon OCC config file to be created), https://github.com/ibm-openbmc/dev/issues/2537.

Nvme drives retrieved and populated in dbus via https://github.com/ibm-openbmc/dev/issues/1670.  Integrate in fan control.

Ensure settings such as tcontrol hi/low, inc/drop settings, error, sample time is data driven and filled in.

**Comment by msbarth** [comment]
All component temps are included in fan control's 2sec control loop.
