### ISSUE TITLE
Temperature and altitude reading collection via redfish

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1703]
Ensure Redfish queries report ambient temps and altitude - populate DBus data if needed.  Altitude/pressure sensor is supported in redfish.

Need to update Inventory ObjectMapper association to map sensor to DBus object (https://github.com/openbmc/openbmc/blob/master/meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager/associations.json) for the Rainier/Everest systems.

No Exhaust heat index in Redfish. Not needed for any other reason.  IBM systems don't have an exhaust heat temp sensor, so no need to supply that for Redfish.

Need to subtract pre-heat from ambient temp readings before filling in? No, this could be done in the future within dbus_sensors and a specific pre-heat offset read from EM, but not needed for this issue.

Need to notify IPMI when starting 15min shutdown timer (epow3) for ambient temps being too high? No, not needed.

**Comment by mzipse** [comment]
@lxwinspur , issue #649 will get the data from the ambient sensor(s) to dbus.  So based on @derekhoward55 description above, the work for this is to grab the data from dbus and ensure all the pieces are then expose to the user via the proper Redfish, DCMI and IPMI APIs.  I realize this story is dependent on the completion of #649 however you could mock up dbus to start this work and verify at least at a unit test level.  You mentioned you may have some questions about this work.  If so, please articulate in this issue and we can get Derek to follow up.  Thanks!
