### ISSUE TITLE
Tracing enhancements for power and thermal

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1705]
Needed for lab and field.
Maintain 11001F02 info error logs when traces wrap? Used often in field.

Fast and slow wrapping?

Needs to be included with PELs.

Field examples of debug data/info sent:
CPS included full PEL
CPS included some PEL contents
CPS included link to iqylog
CPS/email included link to iqylog, also trace from PEL in question
CPS included dump, later links to PELs
CPS/email included dump or link to dumps
CPS included dump and specific PEL contents
Retain tips reference trace data in PELs

Lab examples of debug data/info sent:
MPV sends full PEL. (most common)
MPV defect with list of PELs, some contents, or just link to PELs
MPV defect contained PEL contents, link to ffdc or traces
STC defect contains list of PELs
MFG defect contains PEL contents
MFG defect contains PEL contents and link to ffdc
MFG email contains list of PELs
MFG email contains PEL contents
Mem team defect contains traces and PEL

**Comment by derekhoward55** [comment]
From: Bradley W Bishop/Rochester/IBM
Subject: Interlock with Australia team - OpenBMC/SP-Next Discussion
Date: Mon, Jun 1, 2020 3:41 PM

Hi all
I had a todo from the 5/13 call to start to formalize the OpenBMC logging best practices and then identify some work we could do to implement those - the immediate goal being to make debugging problems faster when we do P10 bringup.

I think this will be an iterative process - the one I've heard the most feedback on is that journal -o verbose is required to debug and slows things down, so I started with that and put something out on the project mailing list here:

https://lists.ozlabs.org/pipermail/openbmc/2020-June/021899.html

If you could have a look and weigh in that would be appreciated.  Also if you have any thoughts on what the next anti-pattern to fix should be please reply here or to my post on the mailing list, and I'll push that along.

To get started I propose we audit these repositories for interactions with the kernel:

phosphor-hwmon
ibm-vpd-parser/openpower-vpd-parser
phosphor-power

and ensure that anywhere we are doing fileops on i2c devices we add the filename, system call and errno to the MESSAGE field.

To do this, we should implement a phosphor::logging::log wrapper that enables a MESSAGE field format string (right now it only works with a fixed string).

thx - brad

**Comment by derekhoward55** [comment]
Andrew Geissler  8:39 AM
@Derek Howard @msbarth, probably an example where some additional data in the journal would help understand why the fan service is failing with this new 5.7 kernel update:
`Jul 10 13:04:21 witherspoon-YL30UF74T02X phosphor-fan-control[12198]: Uncaught DBus service lookup failure exception
Jul 10 13:04:21 witherspoon-YL30UF74T02X systemd[1]: phosphor-fan-control-init@0.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 13:04:21 witherspoon-YL30UF74T02X systemd[1]: phosphor-fan-control-init@0.service: Failed with result 'exit-code'.
Jul 10 13:04:22 witherspoon-YL30UF74T02X systemd[1]: phosphor-fan-control-init@0.service: Scheduled restart job, restart counter is at 8872.`

**Comment by rfrandse** [comment]
tracking in jira
