### ISSUE TITLE
Verify PSU hotswap config and init

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1708]
Verify hot-swapped PS initializes correctly and VPD gets collected/updated appropriately. This should have been done already for POR, ensure is suffice for hot-swap as well.

Check PS config such as type&input to ensure it's appropriate for the system type.

Send alert to PHYP when removed, and after VPD has been collected when installed.  This should have been done already.

**Comment by bjwyman** [comment]
I think an IBM test team may have found an issue, but verifying it seems to be a somewhat lengthy test.
Starting at clean state (no VPD persisted via cereal files):
1. Insert power supplies in E2 and E3 (E0 and E1 missing).
2. Startup, power on, power off.
3. Remove power (AC pull from E2 and E3).
4. Move E2 to E0 (not sure if that was exactly it, could double check that vpd info you put in defect).
5. Move E3 to E1...
6. Apply AC.
7. Power on.
8. Remove E0.
9. Insert E0 and apply AC.
10. Power off.
11. Reboot.
12. Power on.
13. Power off.

**Comment by bjwyman** [comment]
Noted an errno=2 issue a while back, thought had a kernel update issue, but Eddie James did not see what kernel change might cause that.

Testing in simulator, still see that on missing to present. There was an internal defect as well, on Everest that seemed to indicate a problem.

I think the ordering change that tries to updateInventory() before binding the device driver is the issue.

Swizzled ordering here: https://github.com/openbmc/phosphor-power/commit/ca1e9ea1f91ca98792b698ffd9c61d13697488e6

**Comment by bjwyman** [comment]
Remove/install, errno=2 issues reading and updating VPD/inventory. Fix(es):
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/52254
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/52255

Oops! Appending '\0' to the string is a bad idea. PHYP testing found problems, labeled it corrupt VPD. Fix: 
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/52297

**Comment by derekhoward55** [comment]
FTC team will do system - level test now that all defect fixes are in.
