### ISSUE TITLE
Verify needed power supply info in Redfish

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1709]
Verify Redfish support - store needed things in DBUS.  bmcweb gets from DBUS for redfish, so json file with associations in object mapper needs to be updated. Also, update the phosphor-hwmon config file as below.

Include: ps vpd fields, loc code, health/operational status, chassis, efficiency. Done.
Add: PowerSubsystem wattages in https://github.com/ibm-openbmc/dev/issues/3543. 
Add: Accuracy for input power measurements to the Metric definitions (eg ["/redfish/v1/Chassis/chassis/Sensors/ps0_input_power"](https://xxx/redfish/v1/Chassis/chassis/Sensors/ps0_input_power)).
Don't need: rid, input voltage/type to OCC, chassis input power (can be obtained by adding ps input powers together). 

In previous systems, a phosphor-hwmon config file was created that contained the ps sensors such as:
curr1_label:iout1
curr2_label:iout2
in1_label:vin
in2_label:vmon
in3_label:vout1
in4_label:vout2
power1_label:pin

This hasn't been done yet for Rainier.  In the interest of time, use hwmon as we did in previous systems.  For a future enhancement, as we are creating entity-manager config files for ps information in general, create a file (such as https://github.com/openbmc/entity-manager/blob/master/configurations/Delta_DPS-2000AB_PSU.json) for each of the ps's supported for Rainier, so the sensor info can be placed on dbus by the strategic dbus-sensors instead of hwmon.  Don't need the fan pid info, nor the threshold values defined, just the sensor labels which can be copied from witherspoons config file and updated as appropriate.

RedundancyMode support added later with https://github.com/ibm-openbmc/dev/issues/3569.

Alerts/events when presence or fault status changes needed for ipmi? No.

**Comment by gtmills** [comment]
@derekhoward55 This story includes the power supply Redfish's Redundancy ?\
@msbarth Do we have a similar story for Redfish Fan Redundancy? Fan redundancy looks related to https://github.com/ibm-openbmc/dev/issues/491

**Comment by gtmills** [comment]
Redfish Power Supply Redundancy looks like 
![redundancy-PS](https://user-images.githubusercontent.com/5455127/117499400-6d32b080-af38-11eb-8210-2f5aacd8237b.JPG)

**Comment by bjwyman** [comment]
I was a bit thrown off by the in2_label = vmon thing. I was not familiar with that, and it did not appear to match the Linux DD docs.
https://github.com/openbmc/openbmc/blob/master/meta-ibm/recipes-phosphor/sensors/phosphor-hwmon/witherspoon/obmc/hwmon/ahb/apb/bus@1e78a000/i2c-bus@100/power-supply@68.conf
* input voltage
* input power
* output voltage
* output current

Those look like the ones to cover to have parity with Witherspoon.

**Comment by bjwyman** [comment]
The output voltage could *maybe* include the extra one for standby voltage.

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/50743
sensors:p10bmc:Add power-supply hwmon configs

https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/50744
meta-ibm: Add power supply sensor associations

**Comment by bjwyman** [comment]
sensors:p10bmc:Add power-supply hwmon configs: https://github.com/openbmc/openbmc/commit/3772aab33c3a17d9716463543d06ae7cffcdfb23

meta-ibm: Add power supply sensor associations: https://github.com/openbmc/openbmc/commit/bc13317c4252037b2fc99a7186539d6f8f10c600

**Comment by bjwyman** [comment]
> Include RedundancyMode (a read-write property)

Still need to determine where that goes, how to do that.

**Comment by bjwyman** [comment]
Added power supply temperatures: 
- https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/51941
- https://github.com/openbmc/openbmc/commit/7eb569c9b994c3c0ab2c9faeb33a0d2528d9e117

**Comment by derekhoward55** [comment]
Heres a mockup of all the PowerSubsystem fields:

![image](https://user-images.githubusercontent.com/22683949/162220694-6d65a6af-6500-4ff9-be62-e8de57f9d2da.png)

**Comment by bjwyman** [comment]
sensor: Add Accuracy to Value interface
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/53569

**Comment by derekhoward55** [comment]
Closing this for GA.  Incremental post-GA improvements tracked in other issues.
