### ISSUE TITLE
Allow PEL severity to be based on system type

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1712]
In the PEL message registry, the PEL severity field should be able to vary based on some system type value, as defined by entity manager.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/31263

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/31263 merged
