### ISSUE TITLE
pHAL: enable support on p9 bring-up box.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1713]

**Comment by geissonator** [comment]
One key piece of this is providing the command line interface for stopinstructions. This will then be utilized by https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/28967/2/op-stop-instructions%2540.service.in#13

**Comment by ojayanth** [comment]
Enabled base infrastructure  in Bring-up boxes using https://github.ibm.com/openbmc/openbmc/pull/226.

**Comment by ojayanth** [comment]
Found issues in the warm reboot path. and disabled phal support in bring-up boxes.

**Comment by ojayanth** [comment]
#SW48723 used to track the warm re-ipl issue.
