### ISSUE TITLE
Power on/off sequencing full function

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1717]
Power on and sequencing:
Re-collect vpd from anything appropriate since could be swapped at standby (eg op panel if need to know type of sensors, procs if ensuring procs correct or it specifies reg requirements, etc).  Not needed; done in individual apps.
Ensure minimum off delay expired.
Ensure PS config valid. Done by psu-monitor.
Dasd bp vpd handled via common design PLDM VPD passing, no unique requirements.
Persist power_transition so can turn off if get bmc reset in middle of transition? Not needed, state management already does this.
TBD unknowns.

Power off:
start 25s min off delay - allows caps to discharge etc and helps prevent thrashing during brownouts.
ensure 15s min off delay on cold start as well.

**Comment by wrightjl1** [comment]
Code review for minimum power off time: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/51808
