### ISSUE TITLE
Consume PMIC temps/telemetry data 

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1721]
PMIC/DDIMM impacts (collect telemetry, temps via SBE).  This will be done by the memory team writing the BMC&SBE code.

SBE will use hw procedure(s) to read the appropriate temperature and telemetry data.  It stores the data to be accessed by the BMC.  Work with SBE and hw procedure contacts and memory team to help define data, data collection rates (POR once/second), and at which system states the data should be collected.  Telemetry data POR is Vout, Vout peak (maximum), Vout valley (minimum), Iout, Iout peak, Iout valley, Temperature, Temperature peak - but need hw&mem team to confirm these are all available, and lots of other data is being requested on some but not all of the ddimms.

BMC will need to pull the data from SBE.  BMC-SBE FIFO-OCC path in kernel already.  Need new chip ops for pmic data in SBE, but same concept, and collect using PDBG BMC support.  Ensure new chip ops appropriate.
https://github.com/open-power/pdbg/blob/master/README.md

BMC then put the data on DBUS.  Then Redfish support can work as normal.  Ensure temps & other telemetry data are on DBUS where accessible, timings acceptable, etc.

2U DDIMMs don't have internal temp sensors, 4U DDIMMs do.
2U DDIMMs don't have v/i peak/valley readings (being confirmed), 4U DDIMMs do.
1U/2U/4U have pmbus registers (status_word etc) if those are agreed to be supported.

**Comment by amboar** [comment]
> BMC will need to pull the data from SBE. BMC-SBE FIFO-OCC path in kernel already. Need new chip ops for pmic data in SBE, but same concept, and collect using PDBG BMC support. Ensure new chip ops appropriate.

This is a bit of a mixed bag; What involvement does the OCC have? The OCC data is acquired via the SBEFIFO as that's the only path that's accessible on a system configured for secure-boot, but it feels like you only mentioned the OCC due to its relationship with the SBEFIFO?

> 1U/2U/4U have pmbus registers (status_word etc) if those are agreed to be supported.

What's the plan here? Passing PMBus commands to devices via the SBEFIFO?

**Comment by derekhoward55** [comment]
The OCC won't actually have any part of getting the internal pmic temps through the SBE.  I only mentioned it as background information for the coder in case they want to look at existing code/etc.

**Comment by derekhoward55** [comment]
> > BMC will need to pull the data from SBE. BMC-SBE FIFO-OCC path in kernel already. Need new chip ops for pmic data in SBE, but same concept, and collect using PDBG BMC support. Ensure new chip ops appropriate.
> 
> This is a bit of a mixed bag; What involvement does the OCC have? The OCC data is acquired via the SBEFIFO as that's the only path that's accessible on a system configured for secure-boot, but it feels like you only mentioned the OCC due to its relationship with the SBEFIFO?

The OCC won't actually have any part of getting the internal pmic temps through the SBE. I only mentioned it as background information for the coder in case they want to look at existing code/etc.
> 
> > 1U/2U/4U have pmbus registers (status_word etc) if those are agreed to be supported.
> 
> What's the plan here? Passing PMBus commands to devices via the SBEFIFO?

**Comment by derekhoward55** [comment]
This is no longer needed based on the design change to have HBRT collect/log the data.
