### ISSUE TITLE
GUI : FED : Page Title component - Header element not accessible

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1722]
## Overview
Having multiple `<header>` elements on a page requires that each have an `arial-label` or `aria-labelledby` attribute. The following code needs to be updated in the PageTitle component in order to be complaint.

### Code
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/75801d93-844a-4c6c-a225-0cd39cd4acf5)

### Violation Info
https://aat.w3ibm.mybluemix.net/token/82c6f45f-caf9-43f4-b4ad-8b6f891c89fb/01b78da0-e8a7-4010-b663-ba8cf47be32d/latest///doc/w3/help/en-US/idhi_accessibility_check_g1160.html

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29296
