### ISSUE TITLE
Cleanup the use of emit_interfaces_added in various repos

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#1728]
In several repos there are similar code like this:
```
class ActivationProgress : public ActivationProgressInherit
{
  public:
    /** @brief Constructs ActivationProgress.
     *
     * @param[in] bus    - The Dbus bus object
     * @param[in] path   - The Dbus object path
     */
    ActivationProgress(sdbusplus::bus::bus& bus, const std::string& path) :
        ActivationProgressInherit(bus, path.c_str(), true), bus(bus), path(path)
    {
        progress(0);
        std::vector<std::string> interfaces({interface});
        bus.emit_interfaces_added(path.c_str(), interfaces);
    }

    ~ActivationProgress()
    {
        std::vector<std::string> interfaces({interface});
        bus.emit_interfaces_removed(path.c_str(), interfaces);
    }

  private:
    // TODO Remove once openbmc/openbmc#1975 is resolved
    static constexpr auto interface =
        "xyz.openbmc_project.Software.ActivationProgress";
    sdbusplus::bus::bus& bus;
    std::string path;
};
```

There is a TODO indicating that the code related to `emit_interfaces_added()` and `emit_interfaces_removed()` could be removed.

Now sdbuplus supports `action::emit_interface_added` when the object is created, the above code could be cleaned up.

The cleanup could be done in below repos:
* phosphor-bmc-code-mgmt
* openpower-pnor-code-mgmt
* phosphor-psu-code-mgmt

**Comment by mine260309** [comment]
- [ ] phosphor-bmc-code-mgmt
    https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/29402
- [ ] openpower-pnor-code-mgmt
- [ ] phosphor-psu-code-mgmt

**Comment by XiaochaoMa** [comment]
OpenPower-pnor..mgmt has

**Comment by zhanghaodi** [comment]
openpower-pnor-code-mgmt has done.
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-pnor-code-mgmt/+/29901

**Comment by zhanghaodi** [comment]
phosphor-psu-code-mgmt has done.
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-psu-code-mgmt/+/29902
