### ISSUE TITLE
PELs:  Help hostboot fill in a specific UserData section

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1730]
As was done on the FSP, hostboot is requesting the BMC add a UserData section with the same various bits of debug information that are added to the BMC PELs, things like that internal code level name and the bmc/host/chassis states.

The plan is that the BMC code will look in incoming PELs for an ED section with specific compID/version/subtype fields, and then modify it with the appropriate contents.  They will change their code to add an empty section with those fields and of a certain default size, so they can ensure they always have room for it (as opposed to our code just always attempting to tack it on the end)

**Comment by spinler** [comment]
Here's the empty section in a hostboot PEL:
```
00000130  45 44 00 D4 01 00 09 00  4F 00 00 00 00 00 00 00  |  ED......O.......
00000140  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
00000150  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
00000160  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
00000170  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
00000180  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
00000190  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
000001A0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
000001B0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
000001C0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
000001D0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
000001E0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
000001F0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
00000200  00 00 00 00 55 44 00 1C  01 06 01 00 02 00 41 4B  |  ....UD........AK
```

**Comment by spinler** [comment]
The function that creates this UserData section on the BMC is PEL::makeSysInfoUserDataSection.

**Comment by sumitk56** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/42621/12
