### ISSUE TITLE
Redfish: Power restore policy

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1731]
Map policy restore d-bus interface to Redfish 
https://github.com/openbmc/phosphor-dbus-interfaces/blob/05375b14e5a68ac249da6a8cd68e3d522a7ed022/xyz/openbmc_project/Control/Power/RestorePolicy.interface.yaml#L7

curl -k  https://${bmc}/xyz/openbmc_project/control/host0/power_restore_policy
{
  "data": {
    "PowerRestorePolicy": "xyz.openbmc_project.Control.Power.RestorePolicy.Policy.AlwaysOff"
  },

https://github.com/openbmc/bmcweb/blob/6f44b7524f1d48d009ec87b1309481c7905b13b4/static/redfish/v1/JsonSchemas/ComputerSystem/ComputerSystem.json#L512

```
                "PowerRestorePolicy": {
                    "$ref": "#/definitions/PowerRestorePolicyTypes",
                    "description": "The desired power state of the system when power is restored after a power loss.",
                    "longDescription": "This property shall indicate the desired PowerState of the system when power is applied to the system.  The `LastState` value shall return the system to the PowerState it was in when power was lost.",
                    "readonly": false,
                    "versionAdded": "v1_6_0"
```

https://github.com/openbmc/bmcweb/blob/6f44b7524f1d48d009ec87b1309481c7905b13b4/static/redfish/v1/JsonSchemas/ComputerSystem/ComputerSystem.json#L986

```
        "PowerRestorePolicyTypes": {
            "description": "The enumerations of PowerRestorePolicyTypes specify the choice of power state for the system when power is applied.",
            "enum": [
                "AlwaysOn",
                "AlwaysOff",
                "LastState"
            ],
            "enumDescriptions": {
                "AlwaysOff": "The system always remains powered off when power is applied.",
                "AlwaysOn": "The system always powers on when power is applied.",
                "LastState": "The system returns to its last on or off power state when power is applied."


```

**Comment by lxwinspur** [comment]
review：
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/31234
