### ISSUE TITLE
GUI : FED : Global Search/Filter component

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1733]
## Description
The search input used to filter information should be reusable by all pages that have this functionality.

## Requirements
1. Create a reusable search input component that can be used on the following pages.
- Event logs (Not ready)
- Hardware status (Not ready)
- Sensors (Complete)
2. Add the search input to the Sensors page

## Design
 - [Event Logs prototype](https://ibm.invisionapp.com/d/main#/console/15347903/319450564/preview)

### Screen capture of component to create
![image](https://user-images.githubusercontent.com/1183515/79795571-c1f98e00-8319-11ea-8584-be938ea5b778.png)

## Resources
Use the recent table filter work as a guide to creating this custom component. Review the code in this [Gerrit review](https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31168)

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33023

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33023 merged
