### ISSUE TITLE
GUI : FED : Global Filter menu component

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1734]
## Description
The filter menu is a new filter design and should be reusable by all pages that have this functionality. The following pages use this information.

The new design is located in #650 and in the following InVision prototype https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319141765_01-Event-Logs

- Event log
- Sensors

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31168
