### ISSUE TITLE
GUI : FED : Export functionality

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1736]
## As Is
The action to to export information from the Hardware status and Sensors pages is aligned with a section header. The proximity to the control can be confusing to some users. There has also been a new table design pattern added that included batch actions. It is unclear if users would want to export specific information. Currently, the export action downloads a JSON file of all information in the same format that the API returns the data.

## To Be
TBD

## Action Items
- [ ] Work with design to determine value of this data to users
- [ ] Work with design to determine a way to better associate the action with the information being exported

**Comment by derick-montague** [comment]
This may or may not be reusable. We will add this as part of the table actions pattern. This story could be as simple as adding this functionality to the 3 pages that require it.

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31782
