### ISSUE TITLE
GUI : Design : Server Health - Hardware status

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1739]
## SMEs
**BMC**: @gtmills 
**RAS**: Justin Thaler
**PE**: Russ Young, Joe Mulholland

## Description
The current UI pattern used in the AngularJS FW GUI is a vertically stacked list of accordion items for each hardware component. This pattern is not easy to navigate or quickly find information. We are planning to use the Redfish API for all pages in the Vue rewrite. Redfish has a different structure than the REST API which should be considered while redesigning this page.

### Design Goals
- [x] Improve ability for the user to quickly scan hardware information
- [x] Add ability for user to quickly locate hardware components in a warning state
- [x] Base content on Redfish API 

## InVision Prototype
- https://ibm.invisionapp.com/share/V3O02B362ZE#/screens/319550704_01-Hardware-Status-04

## Design Issue (webui-vue)
- [x] Need to add link since there is a change to the design for OpenBMC

## References/Resources
- [Feature discovery](https://ibm.ent.box.com/folder/106564446310)
- user research notes*: 
- user research synthesis: 
- [Redfish Mockup](https://redfish.dmtf.org/redfish/mockups/v1/950)

* This folder is restricted in accordance with GDPR guidelines.

**Comment by ryanarnell** [comment]
@derick-montague @gtmills Do we have a sample redfish API output that I can look to find out what data is available to us?

**Comment by derick-montague** [comment]
@ryanarnell - I have the basic info, but need to get the output for you.

```
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis
```

```
System:  /redfish/v1/Systems/system
Motherboard:  /redfish/v1/Chassis/motherboard
Processor and GPU: /redfish/v1/Systems/system/Processors
Memory: /redfish/v1/Systems/system/Memory
Fans: /redfish/v1/Chassis/chassis/Thermal
Power: /redfish/v1/Chassis/chassis/Power
```

**Comment by gtmills** [comment]
3/23/2020: added BMC, and edited one on the list above

**Comment by derick-montague** [comment]
[Slack conversation about correlation of logs and hardware status](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1588264231220300)

**Comment by derick-montague** [comment]
Conversation with @gtmills discussing the important of the `Contains` and `ManagedBy` properties to show the clear hierarchy of the systems. 

There is a property of links that would link hardware components, e.g. linking fans to Chassis. Need to research the value of this with RAS and PE design partners.

**Comment by derick-montague** [comment]
Decided to move forward with an MVP to reach parity with OpenBMC using the Redfish API's. There will be a new story created for the eBMC Hardware Status that potentially would be based on a hierarchy, along with integrated VPD.

**Comment by ryanarnell** [comment]
## Hardware status- Iteration MVP
We wanted to reach parity with our existing OpenBMC GUI and include some update along the way. 

1. Separated the hardware component sections.
2. Added sorting to the sections columns.
3. Introduced searching and filtering for long tables like DIMMs.
4. Added health status information.
5. Exposed important information like part number and serial numbers in table header.

[View the Invision prototype](https://ibm.invisionapp.com/share/V3O02B362ZE#/screens/319550704_01-Hardware-Status-04)

### Hardware status page
![01-hardware-status-04@2x](https://user-images.githubusercontent.com/4976631/82504129-475e9280-9ac0-11ea-8d4d-7971daaf9f5e.png)


### Hardware status page expanded 
![02-hardware-status-04@2x](https://user-images.githubusercontent.com/4976631/82504138-4d547380-9ac0-11ea-8499-87e611777521.png)

**Comment by derick-montague** [comment]
Remaining design work is to find a way to format the details in the expanded table that is easier to scan / more readable.

**Comment by yoshiemuranaka** [comment]
worked with @ben-bacon to land on layout below. [slack convo](https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1590013491032900)
![Screen Shot 2020-06-01 at 1 29 49 PM](https://user-images.githubusercontent.com/8097306/83451602-19f0dd80-a40c-11ea-9e7a-e3af419df8c0.png)

**Comment by derick-montague** [comment]
This was the issue to reach parity with the AngularJS application and can be closed.
