### ISSUE TITLE
Support for gard mnfg policy flag

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#1740]
This story is to track the implementation of gard mnfg policy flag on the bmc

**Comment by gtmills** [comment]
@dhruvibm Intel has a mnfg mode, can we correlate on a design? 
 https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/28671/16/redfish-core/lib/sensors.hpp#2738

**Comment by ojayanth** [comment]
GUARD feature in BMC side application is going to enable to 1Q2020. So this is not required for Manufacturing milestone.

**Comment by RameshIyyar** [comment]
https://github.com/ibm-openbmc/dev/issues/1509#issuecomment-868556960 - we may not going to add policy

**Comment by rsnair** [comment]
Adjusting the milestone as its not needed for GA1

**Comment by ojayanth** [comment]
0x00000002 | MNFG_NO_GARD | Disable all GARD is required to for manufacturing to disable the guard related action in manufacturing mode.

**Comment by RameshIyyar** [comment]
> 0x00000002 | MNFG_NO_GARD | Disable all GARD is required to for manufacturing to disable the guard related action in manufacturing mode.

@ojayanth Who is the consumer for this policy? There was a discussion about this in one of Todd calls and no one knows who is the consumer for eBMC so the team planned to drop for GA1
@derick-montague @rsnair

**Comment by RameshIyyar** [comment]
Guard manager codes are available in fw1020.00-29.
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/46272
https://github.com/ibm-openbmc/openpower-hw-isolation/pull/3

**Comment by RameshIyyar** [comment]
op-proc-control supports were also added.
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/46604
