### ISSUE TITLE
Set the Manufacturing support for FCO policy falgs.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1741]
Set the   mnfg FCO mode on/off : Provide policy flag to enable/disable FCO:  This should be shared to hostboot.

Set the   mnfg FCO - Input the Number of cores to be disabled. -- User input should be stored in setting and shared to hostboot.

**Comment by ojayanth** [comment]
Need to revisit the complexity based on the FCO design direction. 
Keeping minimal complexity here.

**Comment by ojayanth** [comment]
@sampmisr is this work include PLDM FCO work?  @mzipse

**Comment by ojayanth** [comment]
@mzipse FYI.

**Comment by nmuruli** [comment]
PLDM Changes are completed part of this :https://github.com/ibm-openbmc/dev/issues/1995
