### ISSUE TITLE
HMC-BMC DUMP: Write a script for the Dump operation

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1743]
This script does the following operation, we can extend the openbmc tool script for the same.

-> Does the NBD setup 
-> List all the dumps
-> Offload dump
-> Delete dump
-> Get the dump detail

**Comment by raviteja-b** [comment]
Upstream link https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/30497

**Comment by ratagupt** [comment]
closing as it is merged.
