### ISSUE TITLE
IPv6 support for VMI

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#1744]
Support for the following IPv6 configuration for the VMI
=> IPV6 Static
=> IPv6 Dhcp
=> IPv6 SLAAC.

**Comment by rsnair** [comment]
TODO: @sunharis  Split this into smaller stories. Also, create stories for the PLDM bios changes. Let us track this as an epic

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by sunharis** [comment]
Migrate-Yes

**Comment by rfrandse** [comment]
tracking in jira
