### ISSUE TITLE
Support for 1600W psu

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1748]
Add support for 1600W titanium ps to appropriate 4u config files.  Replacement for older 1400W ps.

They will use the same ccin as the 1400W ps for legacy reasons, so can use the same label power, ccin, etc.  FW cannot tell the difference (same for 1000w titanium replacing older 900w ps, if in future they are used).  Ensure power cap appropriate, etc.

PS won't be officially supported until after GA, but get this code in first GA driver so no code compatibility issues.  Test early versions of ps with hw team before GA to ensure no problems when they later start shipping and get added to field stock.

Confirm DD works as is for new ps.  Confirm ccin is swapped (msb/lsb) like for 1400w ps.

Ensure ps behavior (cmds, status register bit ordering, etc) same as 1400W ps.

**Comment by bjwyman** [comment]
"Confirm DD updates for new ps completed. Ensure ccin is lsb/msb like 2300w/1960w/witherspoon ps, and not swapped like for 1400w ps."

Making the CCIN swap to show in the VPD inventory might need to be done via the userspace application, not the device driver, since the device driver is looking at the CCIN to determine how certain commands/features are supported.

**Comment by derekhoward55** [comment]
> "Confirm DD updates for new ps completed. Ensure ccin is lsb/msb like 2300w/1960w/witherspoon ps, and not swapped like for 1400w ps."
> 
> Making the CCIN swap to show in the VPD inventory might need to be done via the userspace application, not the device driver, since the device driver is looking at the CCIN to determine how certain commands/features are supported.

The plan was changed, ccin will now be swapped to match the 1400w exactly.

**Comment by bjwyman** [comment]
Waiting on some device driver updates to ibm-cffps from @eddiejames. New CCIN needed, and something to handle PEC byte (1600W supports, 1400W CAPABILITY 0xFF is not right).

**Comment by bjwyman** [comment]
Looking for information on the CCIN handling.

I suppose I can note the commits I know are part of getting handling of 1600W, PEC, and CAPABILITY.
https://github.com/openbmc/linux/commit/b1fbe673b89e88adae0800ab8bef69854be58720#diff-425b49bde3f53a9740fccda555025e4d34c97339a74423e9ca0e6baa5565f0a3

https://github.com/openbmc/linux/commit/9d741f0f7443a71fecd6e17f92a6406a1966a5b3#diff-4a9f1fc50789c53da02a595d3a9c33e48780e636d89625dcd89b182707a6aca0

https://github.com/openbmc/linux/commit/2cd8529cfb28eb9bc392a8a36c66dd318aafd49d#diff-4a9f1fc50789c53da02a595d3a9c33e48780e636d89625dcd89b182707a6aca0

**Comment by bjwyman** [comment]
```
# i2cget -f -y 3 0x69 0x7e b
0x80
```
"Invalid Or Unsupported Command Received"
Well, that isn't a good sign.

**Comment by bjwyman** [comment]
PEC was disabled, but apparently we should have sent a command to the power supply to disable it.
Still have this issue: https://github.com/ibm-openbmc/dev/issues/2375

**Comment by bjwyman** [comment]
Some "files" in sysfs apparently should not be manually read, as it can lead to sending unsupported commands. Apparently STATUS_OTHER is unsupported, status0_other, leading to CML fault.

CLEAR_FAULTS is not sent like it used to be. @eddiejames pointed to:
https://github.ibm.com/openbmc/linux/commit/a919ba06979a7858dab65492eb580121ccbd524f

**Comment by bjwyman** [comment]
hwmon: (pmbus/ibm-cffps) Do not swap max_power_out
http://patchwork.ozlabs.org/project/openbmc/patch/20210827230433.3596370-1-bjwyman@gmail.com/

**Comment by bjwyman** [comment]
A7h on Witherspoon is apparently returning MSB/LSB, but is the PMBus LSB/MSB format on 1400W and Rainier power supplies.

1400W:
```
# i2cget -f -y 3 0x68 0xa7 w
0x0578
# i2cget -f -y 3 0x69 0xa7 w
0x0578
# i2cget -f -y 3 0x6a 0xa7 w
0x0578
# i2cget -f -y 3 0x6b 0xa7 w
0x0578
# i2cget -f -y 3 0x68 0xa7 b
0x78
# i2cget -f -y 3 0x69 0xa7 b
0x78
# i2cget -f -y 3 0x6a 0xa7 b
0x78
# i2cget -f -y 3 0x6b 0xa7 b
0x78
#

# grep . /sys/kernel/debug/pmbus/hwmon*/cffps*/max_power_out
/sys/kernel/debug/pmbus/hwmon10/cffps1/max_power_out:30725
/sys/kernel/debug/pmbus/hwmon7/cffps1/max_power_out:30725
/sys/kernel/debug/pmbus/hwmon8/cffps1/max_power_out:30725
/sys/kernel/debug/pmbus/hwmon9/cffps1/max_power_out:30725
```

**Comment by bjwyman** [comment]
Witherspoon:
```
# # MAX_POWER_OUT
# i2cget -f -y 3 0x68 0xa7 w
0x4c0c
# i2cget -f -y 3 0x69 0xa7 w
0x4c0c
# for d in hwmon3 hwmon4; do grep . /sys/kernel/debug/pmbus/$d/status0; done
0x0840
0x0840
# # MAX_POWER_OUT 1-byte
# i2cget -f -y 3 0x68 0xa7 b
0x0c
# i2cget -f -y 3 0x69 0xa7 b
0x0c
# grep . /sys/kernel/debug/pmbus/hwmon*/cffps*/max_power_out
/sys/kernel/debug/pmbus/hwmon3/cffps1/max_power_out:3148
/sys/kernel/debug/pmbus/hwmon4/cffps1/max_power_out:3148
#
```

**Comment by bjwyman** [comment]
http://patchwork.ozlabs.org/project/openbmc/patch/20210928205051.1222815-1-bjwyman@gmail.com/
[v2] hwmon: (pmbus/ibm-cffps) max_power_out swap changes

**Comment by bjwyman** [comment]
hwmon: (pmbus/ibm-cffps) max_power_out swap changes
https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/commit/?h=hwmon-next&id=f067d5585cda2de1e47dde914a8a4f151659e0ad

**Comment by bjwyman** [comment]
MFR_ID updates that allow for fixing the fw_version reads:
http://patchwork.ozlabs.org/project/openbmc/list/?series=265341

cffps1 will do the four 1-byte reads. cffps2 will do the three 2-byte reads.

**Comment by bjwyman** [comment]
https://github.com/openbmc/linux/commit/875c86927bdbcbfcee5e1074f9803a71b45e8c3c

https://github.com/openbmc/linux/commit/a54efb1a3cb24cec2038371c513003b84b7900c8

https://github.com/openbmc/linux/commit/5d4c078bc35183e4c8d78d368831feb968a7091a

**Comment by bjwyman** [comment]
Changes in driver.
