### ISSUE TITLE
GUI: SSL Certificate upload page

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#175]
## Due Dates
- [x] UX:  2/28/19
- [x] Backend: 03/28/19
- [ ] FED: 5/30/19

## Stakeholders
**SME**: @ojayanth
**DR**: @nicoleconser  
**UX**: @jandraa 
**FED**: ~@BeccaBroek~ @yoshiemuranaka 

## Use Case
Need a new page for uploading an SSL Certificate

## Invision Prototype
https://ibm.invisionapp.com/d/main#/console/15340578/318935049/preview

## Design Issue
https://github.com/openbmc/phosphor-webui/issues/43

## Development Issue
Gerrit: https://gerrit.openbmc-project.xyz/#/q/topic:26+(status:open+OR+status:merged)

**Comment by gtmills** [comment]
Backend code: https://gerrit.openbmc-project.xyz/#/q/topic:26+(status:open+OR+status:merged)

**Comment by alissaylee** [comment]
https://ibm.invisionapp.com/share/7FNYCEZHU6B#/318902299_SSL_Certification
**SSL certificate upload management page**
- Support/upload more than one CA file (work in progress)
- Client and server each have requirement of uploading single file
- Choose and upload file(s)
- Remove loaded file
- See if file successfully uploaded
- Remove existing file(s)

**Outstanding questions/decisions that need to be made:**
- Is the client certificate upload specific to LDAP?
- Is client certificate an optional or required field?
- Can we expose expiration dates for certificates?
- Can we support generating CSR-based certificates?
- Are CSR-based certificates specific only to server certificates?

**Future requirements to consider**
- Blacklist (disable) certificate files
- Upload private key files*
*private key file upload would go hand-in-hand with certificate file upload but this needs to be further vetted with community to allow/disallow this function

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by yoshiemuranaka** [comment]
[Certificate upload Info and testing.docx](https://github.com/ibm-openbmc/dev/files/3138996/Certificate.upload.Info.and.testing.docx)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/15513

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/15513 merged
