### ISSUE TITLE
Refactor psu gpio presence detect handling

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1750]
Most of the ps information specific to 2U/4U will be contained in entity manager config files so the fw can be data-driven. PS present detect gpio definition currently resides in templated config files to be used by phosphor-gpio-present, which are not chosen based on 2U/4U config.  With the current setup, we would report the 3rd and 4th power supply as missing in the inventory on a 2U, but they can never be present. Whatever is done for presence detection will ideally be updated not to report impossible FRUs as missing on a system that cannot have them.

Options:
1. Update phosphor-gpio-present. We could possibly refactor phosphor-gpio-present to load from entity-mager/D-Bus instead of the templated configuration files.  If there will be multiple classes of gpios that were dependent on 2U/4U config, this would be the lowest denominator.  This however does not appear to be the case for Rainier.

2. Update phosphor-psu-monitor. We could possibly stop using phosphor-gpio-present and add/port presence code to phosphor-psu-monitor, add the gpio information to the em config files, and remove from the then duplicate templated config files.  Should this functionality be spread across different apps, or handled in one place.

Add a call to updateInventory() in the PSU constructor path.

**Comment by bjwyman** [comment]
Everest power supply presence might make this lean towards option #2.

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/43009 IBM: Add BindDelay to IBMCFFPSConnector

**Comment by bjwyman** [comment]
Adding the bindDelay to the entity-manager configuration was apparently over-engineered. That/those commits will likely be abandoned. The delay is hardcoded as a constant in the phosphor-psu-monitor application.

During review, it was noted that device driver name, connector name(s), etc. should probably be configurable in some way. Most reasonable method seems to be some kind of compile time configuration option.

**Comment by bjwyman** [comment]
Review noting ibm-cffps: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/43018

Plan is to make it configurable via a separate commit.

**Comment by bjwyman** [comment]
I think I am waiting on this to merge:
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/44407
There are some downstream coordination things to work out, Rainier has gpio-keys for power supplies removed here:
https://github.com/openbmc/linux/commit/433850c42c5ab57713295ede3d4216260e375c5a#diff-9bc306ed160d15d86bced97c2859c6fdd3aa550e1ad536b5bd1e7adf4538f08e

**Comment by bjwyman** [comment]
This should be the last piece needed to complete this work:
https://github.com/openbmc/openbmc/commit/0def9e22cf97088c01c2ee8fbe296d577648eb9c#diff-3f287003da676fddb68dfcc739079b6f580a01df75b1c860fbf6a9226c74db13
