### ISSUE TITLE
pldmtool:  Enable verbose flag '-v' 

### ISSUE THREAD

**Issue by SrideviRamesh** [ibm-openbmc/dev#1753]
Enable Verbose option

example: pldmtool base GetPLDMTypes -v

**Comment by dkodihal** [comment]
@SrideviRamesh can you also document here an example output now, and what it would look like later after when the verbose option is not provided?

**Comment by SrideviRamesh** [comment]
Intention to hide the informational logs in the pldmtool ouput and provide verbose option 0/1.

Current pldmtool behavior is as shown below

pldmtool base GetPLDMTypes
Encode request successfully
Request Message:
08 01 80 00 04
Success in creating the socket : RC = 3
Success in connecting to socket : RC = 0
Success in sending message type as pldm to mctp : RC = 0
Write to socket successful : RC = 5
Total length:5
Loopback response message:
08 01 80 00 04
On first recv(),response == request : RC = 0
Total length: 14
Shutdown Socket successful :  RC = 0
Response Message:
08 01 00 00 04 00 1d 00 00 00 00 00 00 00
Supported types: 0(base) 2(platform) 3(bios) 4(fru)

With verbose support as shown below

pldmtool base GetPLDMTypes
Request Message:
08 01 80 00 04
Response Message:
08 01 00 00 04 00 1d 00 00 00 00 00 00 00
Supported types: 0(base) 2(platform) 3(bios) 4(fru)

 pldmtool base GetPLDMTypes -v 1
Request Message:
08 01 80 00 04
Success in creating the socket : RC = 3
Success in connecting to socket : RC = 0
Success in sending message type as pldm to mctp : RC = 0
Write to socket successful : RC = 5
Total length:5
Loopback response message:
08 01 80 00 04
On first recv(),response == request : RC = 0
Total length:14
Shutdown Socket successful :  RC = 0
Response Message:
08 01 00 00 04 00 1d 00 00 00 00 00 00 00
Supported types: 0(base) 2(platform) 3(bios) 4(fru)

**Comment by SrideviRamesh** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/29830
