### ISSUE TITLE
GUI : FED : Local user management – manual unlock

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#1755]
## As Is
Currently not existing in Vue UI

## To Be
Should follow existing Angular pattern
When account settings lockout method is set to manual, add ability to manually unlock the user.

Current  Angular: 
![Screen Shot 2020-02-21 at 11.07.02 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/2c36dd46-af58-4818-b2cf-59684ce3dfaf)

**Comment by derick-montague** [comment]
This may not be necessary. @gtmills is following up on this with the community to see how this should be handled.

## Overview
1. Redfish does not have support for setting a manual unlock. Setting the lockout time to `0` is expected to disable the lock out service rather. The way the BMC Web UI works today is that a setting of `0` means the user must be unlocked manually. 
1. If we are to follow the Redfish recommendation, we may need to revisit the design as the `threshold` setting does not have any value if the `no lockout` Redfish recommendation is implemented.

**Comment by derick-montague** [comment]
@gtmills - Any update on this?

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/30711

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/30711 merged
