### ISSUE TITLE
Move OCC pass through REST api under ibm/v1 namespace

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1758]
The REST api that maps directly to D-Bus api's is being deprecated. Moving forward, this interface should be under the ibm/v1 namespace and follow the Redfish design of being introspectable and versioned.

Have confirmed with Todd,Martha, and Justin that this API is needed in shipping IBM systems so can not be a debug-only type interface.

Should verify with team the proposed location prior to implementation.

**Comment by gtmills** [comment]
crassd wants to use this API. @eddiejames are you still a good owner ?

**Comment by gtmills** [comment]
@geissonator @ratagupt @bradbishop This still makes to put this under /ibm/v1/? With what we know today?

**Comment by geissonator** [comment]
> @geissonator @ratagupt @bradbishop This still makes to put this under /ibm/v1/? With what we know today?

Not sure? Something we need to discuss in our overflow meeting?

**Comment by lxwinspur** [comment]
@geissonator @gtmills @mzipse 
Around this issue, Do we have a direction?

**Comment by gtmills** [comment]
Yes, I believe the direction was put under /ibm/v1/

**Comment by gtmills** [comment]
/ibm/v1 can be enabled via https://github.com/openbmc/bmcweb/blob/8401529e4fb52caa1725caaa4777536f541d10e8/meson_options.txt#L29

**Comment by lxwinspur** [comment]
@gtmills 

Sorry, I know very little about this issue.
Does this mean that this issue has been finished?
If so, could you close it?

**Comment by gtmills** [comment]
@lxwinspur It is not done. 
I was trying to explain where the code will go.

**Comment by lxwinspur** [comment]
Thanks @gtmills

**Comment by gtmills** [comment]
@lxwinspur I think we can do this just in the fork: https://github.com/ibm-openbmc/bmcweb

**Comment by lxwinspur** [comment]
Review by: https://github.com/ibm-openbmc/bmcweb/pull/79

**Comment by lxwinspur** [comment]
@gtmills 
Could we close this issue?

**Comment by gtmills** [comment]
I guess we will never upsteam this? 
@geissonator you in agreement? If so, then sure I'll close

**Comment by geissonator** [comment]
> I guess we will never upsteam this?
> @geissonator you in agreement? If so, then sure I'll close

Agree
