### ISSUE TITLE
GUI: Virtual Media page

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#176]
## Due Dates
- [x] UX: 2/28/19
- [ ] Backend: 5/02/19
- [x] FED: 5/30/19

## Stakeholders
**SME**: @anoo1 
**DR**: @nicoleconser 
**UX**: @jandraa 
**FED**: @BeccaBroek 

## Use Case
Need a Virtual Media page on the GUI

## Invision Prototype
https://ibm.invisionapp.com/d/main#/console/15340578/318954652/preview

## Design Issue
https://github.com/openbmc/phosphor-webui/issues/40

## Development Issue
Gerrit Review FED: https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/19439/

**Comment by rfrandse** [comment]
refresh

**Comment by BeccaBroek** [comment]
design Here
https://github.com/openbmc/phosphor-webui/issues/40
[Invision mockup](https://ibm.invisionapp.com/share/B9NYI6RMDJQ#/screens/318954652_Virtual_Media_-_1_Empty_State)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by BeccaBroek** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/19439/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/19439 merged
