### ISSUE TITLE
Update rainier device tree for 2U config vrms

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1761]
Need to ensure all i2c buses that vrms reside on are in the dts.  Don't need the i2c addresses since a device driver is not bound.  The 2U version is picked up based on the 2U config type.

Update "status" for i2c bus in aspeed dts.
Update "status" in aspeed-bmc-ibm-rainier.dts.

**Comment by smccarney** [comment]
Did some investigation into this.  I believe no changes are required.

The main device tree file is aspeed-bmc-ibm-rainier.dts.  It has the following line for all the I2C buses I need to use:

```status = "okay";```

Brad Bishop says that line is what is required for i2c-dev to allow I2C communication to devices on that bus.

No regulators are bound to device drivers in aspeed-bmc-ibm-rainier.dts.

aspeed-bmc-ibm-rainier.dts includes the file aspeed-g6.dtsi, which also contains device tree information.

aspeed-g6.dtsi has the following line for all of the I2C buses I need to use:

```status = "disabled";```

However, Brad said that the information in aspeed-bmc-ibm-rainier.dts overrides the information in aspeed-g6.dtsi, so this should not be a problem.

aspeed-g6.dtsi does not bind device drivers to any of the regulators.

Closing this issue as I think no work is required.
