### ISSUE TITLE
Update rainier device tree for 4U config vrms

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1762]
Need to ensure all i2c buses that vrms reside on are in the dts.  Don't need the i2c addresses since a device driver is not bound.  The 4U version is picked up based on the 4U config type.

Update "status" for i2c bus in aspeed dts.
Update "status" in aspeed-bmc-ibm-rainier.dts.

**Comment by smccarney** [comment]
Eddie James told me the following:
* The latest .dts files are currently in GHE linux for Rainier, though they should be upstream too
* The 1020-dev-5.8 branch of that repo is the current one
* The Rainier 4U file is arch/arm/boot/dts/aspeed-bmc-ibm-rainier-4u.dts
* The 4U .dts file includes the 2U .dts file

Thus, the complete path to the 4U .dts file is
https://github.ibm.com/openbmc/linux/blob/1020-dev-5.8/arch/arm/boot/dts/aspeed-bmc-ibm-rainier-4u.dts

**Comment by smccarney** [comment]
**DTS files to review**
DTS files have the ability to include other DTS files.  So the complete list of DTS files to review is:
* arch/arm/boot/dts/aspeed-bmc-ibm-rainier-4u.dts
* arch/arm/boot/dts/aspeed-bmc-ibm-rainier.dts
* arch/arm/boot/dts/aspeed-g6.dtsi
* arch/arm/boot/dts/aspeed-g6-pinctrl.dtsi

**Ensuring the I2C buses for regulators are enabled**
Regulators exist on the following buses (0-based):
* 3
* 6
* 8
* 9
* 10
* 11

All of those buses have the following attribute in aspeed-bmc-ibm-rainier.dts:
```
status = "okay";
```
Brad Bishop said this is what is required to "enable" the I2C bus.

**Ensuring no device drivers are bound to the regulators**
I checked all 4 DTS files, and I did not see any device drivers being bound to regulators.
