### ISSUE TITLE
GUI : Design : Research - Power Server Operations - Override and One Time Boot

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1764]
## Overview
For IBM systems, we have a proposed design in https://github.com/ibm-openbmc/dev/issues/973. This design does not show options for one time boot. Prior to moving forward with the Power server operations work to support IBM systems, we need to determine if there are any design changes needed. 

Discuss with @geissonator to determine if this is needed for IBM systems.

### Screen capture
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/64140af6-aaf6-4377-a32d-8eb3a425a14f)

**Comment by derick-montague** [comment]
Posted question to @geissonator and @vishwabmc in slack. Will update this story when finalized. It is unlikely that this will change for IBM systems needs.

**Comment by derick-montague** [comment]
@ryanarnell can you please add a link to the slack conversation and a summary of your findings and close this story, please?

**Comment by ryanarnell** [comment]
TOM JOSEPH thinks OPAL on eBMC could still be using IPMI  for boot settings. There is a chance that GUI cannot serve the one-time boot setting which might be needed for OPAL. Slack thread is here - https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1587405282017700 

We plan to discuss it in overflow meeting on 05/11/2020

**Comment by derick-montague** [comment]
A great deal of information was discussed about what is needed to support all system types in the SoS overflow meeting today. Based on that discussion, I am going to create a discovery document and add this information. It will be critical for a successful implementation and I am not able to find a discovery doc for this feature. There is a folder, but nothing linked in the design story.

**Comment by ryanarnell** [comment]
Here is the link to the discovery folder- https://ibm.ent.box.com/folder/69427588495 It was called boot options- maybe that was why it was hard to find.

**Comment by ryanarnell** [comment]
oBMC is fine with the current design we have. There might be changes required in the eBMC design if we want to add BIOS attributes. The eBMC story is opened here- https://github.com/ibm-openbmc/dev/issues/973
