### ISSUE TITLE
Scheduled Host Transition: implement host transition process

### ISSUE THREAD

**Issue by wangkair** [ibm-openbmc/dev#1768]
Set the scheduled time and host transition to trigger power on/off.
Start a timer to count down, and register a callback to handle with the process after the time is reached. When the scheduled time reaches, check the current host state first.
Then set the state as requested transition if current state is not the same as required.

**Comment by vishwabmc** [comment]
@wangkair we would also need to register callbacks when the  new time is set and react accordingly. 

There may be better options or wrappers around it.. One of the ways is to: http://man7.org/linux/man-pages/man2/timerfd_create.2.html

**Comment by wangkair** [comment]
> @wangkair we would also need to register callbacks when the new time is set and react accordingly.
> 
> There may be better options or wrappers around it.. One of the ways is to: http://man7.org/linux/man-pages/man2/timerfd_create.2.html

Thanks for the quick response!
I have callback in my code. I will open them to review late. And yes, I will describe it more detailed here.

**Comment by wangkair** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/29752

**Comment by wangkair** [comment]
Waiting for code review and merge.
