### ISSUE TITLE
GUI: Setup LDAP 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#177]
## Due Dates
- [x] UX: 3/20/19
- [ ] Backend: 4/04/19
- [x] FED: 5/30/19

## Stakeholders
**SME**: @ratagupt 
**DR**:  @nicoleconser 
**UX**: @jandraa 
**FED**: @BeccaBroek 

## Use Case
Need a new page or to use an existing page (user management) to set up LDAP 

## InVision Prototype 
https://ibm.invisionapp.com/d/main#/console/15340578/318942513/preview

## Design Issue
* Server configuration design - openbmc/phosphor-webui#39
* Role group design - openbmc/phosphor-webui#38

## Development Issue
Role Groups: https://github.com/ibm-openbmc/dev/issues/186
### Gerrit Reviews WIP
* https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/20697
* https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/20661

**Comment by alissaylee** [comment]
https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/User/Ldap/Create.interface.yaml < Details on fields to consider for LDAP configuration

**Comment by BeccaBroek** [comment]
The following are fields that the LDAP configuration page will need. Not a final list, but some info for a starting point for design.

Field : Secure LDAP
Type : true or false

Field: Server URI 
Type: String

Field: Bind DN 
Value: String

Field: Bind DN password 
Value: String

Field: Base DN 
Value: String
Example: “ou=people,dc=corp,dc=com”

Field: Search Scope 
Values: sub, one, base (3 options)

Field: LDAP Type 
Values: Active Directory, OpenLDAP (2 options)

** I believe we also need a certificate upload, will check with @ratagupt on this

**Comment by alissaylee** [comment]
https://ibm.invisionapp.com/share/7FNYCEZHU6B#/318878222_LDAP_Manage_Groups
**Configuring LDAP Settings**
- Fields to enter by user: https://github.com/ibm-openbmc/dev/issues/177#issuecomment-425969893
- File upload (3 options): CA certificate file, client certificate file, SSL certificate file

https://ibm.invisionapp.com/share/7FNYCEZHU6B#/318878216_LDAP_Add_Role_Group
**Managing Role Groups**
- Add, Modify or Delete role groups*
*Role groups that have a group name and privilege assigned can only be deleted (this is currently how AMI and SM appear to do it).

Outstanding Questions:
1- Is SSL certificate file only relevant to the LDAP setting configuration or is that a requirement somewhere else in the GUI?
2- In AMI, it looks like they show the valid dates for SSL certificate file "valid from A, valid until Z". I’m assuming this data would be valuable to show to the user as they upload their file. Would this information also be available for the CA and client certificate files (since the CA, client and SSL are the files we are giving our users the ability to upload in the LDAP settings page?)

**Comment by susantjasinski** [comment]
Alissa, are you planning on adding the time duration that each certificate is valid for?

**Comment by alissaylee** [comment]
> Alissa, are you planning on adding the time duration that each certificate is valid for?
I'm not sure -- I listed that as an outstanding question in my comment above, and have asked Tom and Ratan to respond. I'm assuming we'll need to readdress this in a later meeting.

**Comment by susantjasinski** [comment]
Also, how will the user know that a certificate is about to expire? Or already expired? 

Will there be any kind of automated certificate renewal? Or at least an automated notification that the user needs to manually renew a certificate?

**Comment by BeccaBroek** [comment]
@susantjasinski The details of certificate upload of this is something we need to talk more about with the back end developers. We briefly mentioned the upload the last time we talked towards the end of the conversation and were out of time. I think that they will be able to provide a lot of clarification when we talk to them later this week.

**Comment by susantjasinski** [comment]
![image](https://user-images.githubusercontent.com/42817935/47574707-cea84c00-d905-11e8-9636-1d93548024fb.png)

“Configure LDAP settings by editing the fields to the right. Manage role groups by selecting the corresponding checkbox and the  appropriate action.”

**Comment by susantjasinski** [comment]
Add role group dialog should allow the user to select a role group from a drop-down list of role groups that were created in the LDAP sever. 

OR the "Group Name" field label needs to be explicit that the user must type in a name of an existing group created in the LDAP Server, and the field MUST be validated to be an existing group

Otherwise we are aiding and abetting human error

**Comment by susantjasinski** [comment]
Manage Role Group should be changed to "Manage Privileges"

**Comment by alissaylee** [comment]
>     * [x]  Change panel description to: “Configure LDAP settings by editing the fields to the right. Manage role groups by selecting the corresponding checkbox and the  appropriate action.”
>       ![image](https://user-images.githubusercontent.com/42817935/47574707-cea84c00-d905-11e8-9636-1d93548024fb.png)
> 
>     * [x]  Change "Delete Role Group" button and dialog title to "Remove Role Group". We are removing the group from the list, we can't delete the group from the LDAP server
> 
>     * [ ]  Add role group dialog should allow the user to select a role group from a drop-down list of role groups that were created in the LDAP sever -- OR --  the "Group Name" field label needs to be explicit that the user must type in a name of an existing group created in the LDAP Server, and the field MUST be validated to be an existing group. Otherwise we are aiding and abetting human error
> 
>     * [x]   Manage Role Group should be changed to "Manage Privileges"

Tom Joseph will confirm if we can provide a dropdown list of groups. Otherwise, we can move forward with direction to provide field validations and query on the spot if group name input is valid (e.g. Test button)

**Comment by BeccaBroek** [comment]
@susantjasinski 
We might need to update this design to handle multiple URIs. (additional URIs would be fallbacks if authentication fails with the previous URI).
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-user-manager/+/16477/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by BeccaBroek** [comment]
Server configuration design - https://github.com/openbmc/phosphor-webui/issues/39
Role group design - https://github.com/openbmc/phosphor-webui/issues/38

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dixsie** [comment]
**GUI WIP Update:**

- Able to enable LDAP from GUI and display Remote Role Mapping.
- Able to add/edit role groups for LDAP openLDAP from GUI.
- Working on adding/editing role groups in LDAP Active Directory
- Need to test secure LDAP on GUI using dev-663 BMC image (per backend this image passes tests for secure LDAP)

**Waiting on backend changes to test deleting role groups:**

- https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/17943/

- https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/21288

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/20697

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/20697 merged
