### ISSUE TITLE
Review/update Rainier fan settings/fields

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1773]
Review enterprise thermal spreadsheet to add/remove whats needed for Rainier (floor, ceiling, fan configs&zones, loc codes, error rules, times, step sizes, service mode & meltdown count, etc).

Update json config files with values from thermal/system team as appropriate.

Inform OCC when fans have failed or "delay env window" countdown when all fans working again hasn't expired yet so they don't log their own error when taking away power/performance (piggyback on ambient "outside env window" design).

**Comment by msbarth** [comment]
2/27 - Asked Karl on the need for setting a single fan to full speed within a zone when it has a single rotor fail(leaving all other fans under current dynamic control) and he believes that this will not be needed/used and instead all fans within the zone would need to go to full speed.

**Comment by msbarth** [comment]
Resolved by:
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50593
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50597
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50146
