### ISSUE TITLE
Gaurd (GARD) Redfish implementaion

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1775]
Gaurd will be a logService that holds Gaurd records for logEntries.
On the LogService will be a ClearLog to clear the Gaurd.

**Comment by yoshiemuranaka** [comment]
@gtmills any progress on this? we are starting #1509

**Comment by gtmills** [comment]
@ojayanth @dhruvibm ?

**Comment by ojayanth** [comment]
#2935, #2936, #2937, #2938 and #2939 is used to track Redfish implementation
