### ISSUE TITLE
Redfish Push Notifications

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1776]
On the GUI roadmap as Redfish Push Notifications

**Comment by ratagupt** [comment]
Currently, with this story, we are supporting the push notification for below
=> Save area file updates
=> Task service related events
=> host state change

User would be having the support for creating the subscription-based on the resource type.

**Comment by ratagupt** [comment]
We have done the implementation and the reviews are in progress

**Comment by ratagupt** [comment]
it has been delivered and included in GHE.

**Comment by gtmills** [comment]
@ratagupt Is everything upstream here?

**Comment by derick-montague** [comment]
@ratagupt says this has been merged downstream and will be adding Gerrit review links.

**Comment by derick-montague** [comment]
@gtmills : Can we update the milestone for this and determine the status?

**Comment by derick-montague** [comment]
@ratagupt is this story related to https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38059?

**Comment by ratagupt** [comment]
@derick-montague As we spoke this story is having bigger scope and for the Initial Stage the events which is supported are in Internal Driver
=> User can add/delete subscription for event
=> Following events are supported
- Save area file updates
- Task service related events
-  host state change

**Comment by sunharis** [comment]
All framework code is merged to master and some IBM specific code are merged to 1020
