### ISSUE TITLE
Redfish: Bios Attributes: Phyp settings 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1779]
Redfish Bios Attributes to get/set phyp settings on the GUI. 

GUI -> Redfish -> D-Bus -> PLDM?

Phyp settings on the GUI: 
Default partition environment (AIX, i5/OS, Linux)
IPL Mode (i5 OS only)
Logical Memory Block Size
System Memory Page Setup
Predict Dynamic Memory Dealloc 
HW Page Table Size
Dispatch Wheel Time
Virtual TPM

RTAD  ?

Covered under different stories: 
I/O Enclosure config
I/O Enclosure FW Policy Update 
I/O Enlarged Capacity
Capacity on Demand
PCI OpenCAPI 

BIOS Attributes From https://redfish.dmtf.org/schemas/Bios.v1_1_0.json
The schema is flexible.

```
        "Attributes": {
            "additionalProperties": false,
            "description": "The list of BIOS attributes and their values as determined by the manufacturer or provider.",
            "longDescription": "This property shall contain the list of BIOS attributes and their values as determined by the manufacturer or provider.  This object shall describe BIOS attribute settings as additional properties.  If the object specifies a BIOS Attribute Registry, attributes shall be looked up in that Attribute Registry by their attribute name.  Attributes in this Attribute Registry with the AttributeType of Enumeration shall use valid ValueName values in this object, as listed in that Attribute Registry.",
            "patternProperties": {
                "^([a-zA-Z_][a-zA-Z0-9_]*)?@(odata|Redfish|Message)\\.[a-zA-Z_][a-zA-Z0-9_]*$": {
                    "description": "This property shall specify a valid odata or Redfish property.",
                    "type": [
                        "array",
                        "boolean",
                        "integer",
                        "number",
                        "null",
                        "object",
                        "string"
                    ]
                },
                "^[A-Za-z][A-Za-z0-9_]+$": {
                    "type": [
                        "string",
                        "boolean",
                        "number",
                        "null"
                    ]
                }
            },
            "properties": {},
            "type": "object"
```

Rough notes from call:
```
bmc boot:
pldm daemon prepares bios attribute table based on default settings - based on setting interfaces.
pldm daemon subscribes to property change events.

setting attribute flow - host fw is not booted:
rest api for gui to set the property.
these are user settings. implemented as settings d-bus interfaces.  1x1 mapping.
return to http client.  what to return?  200 ok.
property change notification instructs pldm daemon to update the bios table.
... time passes
host boots
host issues get bios table.


setting attribute flow - host fw is booted:
rest api for gui to set the property.
these are user settings. implemented as settings d-bus interfaces.  1x1 mapping.
return to http client.  what to return?  200 ok.
property change notification instructs pldm daemon to update the bios table.
?? not sure how to notify host fw here.  Deepak/Justin/Tom working this.
host issues get bios table.


getting attribute flow
just get the dbus property

inband bios attribute update from host fw
pldm daemon will update properties on dbus.
do we need an event notification for an HTTP client?
no, because we didn't do this on ASM. 
```

@dkodihal Do we need a story for D-Bus work / PLDM work here? 
Gui work is here: #1500

**Comment by dkodihal** [comment]
> Do we need a story for D-Bus work / PLDM work here?

Yes, we do. I'll update it here once I've created the story.

**Comment by derick-montague** [comment]
@gtmills Wondering what the relationship with these are as we are working on #1501.

![image](https://user-images.githubusercontent.com/1183515/89912154-d6f37900-dbb7-11ea-9f89-97e964a23507.png)

**Comment by nicoleconser** [comment]
@gtmills ^^ are you implying that all 14 of the settings listed above fall under a single category (PHYP settings)?

**Comment by derick-montague** [comment]
@gtmills Should RTAD also be added to this story [based on this conversation](https://ibm-systems-power.slack.com/archives/G0199JGQASC/p1597077228012900)?

**Comment by derick-montague** [comment]
> @gtmills ^^ are you implying that all 14 of the settings listed above fall under a single category (PHYP settings)?

@gtmills @nicoleconser - I don't think that is the case. Some seem are part of the Server Power Operations. We need to determine what experience these settings are associated with. I am also wondering about other settings we need for Server Power Operations that aren't listed like `server operating mode`, `server power off policy`, `server firmware start policy`, `AIX/Linux partition boot mode`, and `IBM i partition boot mode`.

**Comment by gtmills** [comment]
> 
> 
> @gtmills ^^ are you implying that all 14 of the settings listed above fall under a single category (PHYP settings)?

These are all Bios Attributes. Some might be part of the Server Power Operations, others yeah probably on a Bios Attributes or Host Attributes page. We should run this by the community. :)

**Comment by gtmills** [comment]
@sampmisr Can you update the milestone here?

**Comment by nmuruli** [comment]
We have most of the BIOS attribute attributes for PHYP consumption is already supported. We will keep this open for any new requirement

**Comment by mzipse** [comment]
Work is complete.  Closing.
