### ISSUE TITLE
Redfish: Implement Autoboot

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1780]
Upstreaming Autoreboot here: https://github.com/ibm-openbmc/dev/issues/1375

Should be in 2020.1 Redfish release

**Comment by mzipse** [comment]
@gtmills I assume you are doing the upstream part.  But then I assume you will mark "ReadyforDev" after that.

**Comment by gtmills** [comment]
Yes, https://github.com/ibm-openbmc/dev/issues/1375 is the upstream part

**Comment by gtmills** [comment]
This is in 2020.1

**Comment by gtmills** [comment]
Done here https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32520 and the commit below
