### ISSUE TITLE
Redfish: USB Port Enable / Disable 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1781]
This story is to enhance [BMCWeb](https://github.com/openbmc/bmcweb) to create a Redfish REST API that models the BMC's direct-attached USB ports.  The server must:
1. Allow a REST API user to GET the list of USB ports present on the BMC.
2. Allow a REST API user to GET the enablement state (enabled or disabled) of each USB port.
3. Allow a REST API user to PATCH the enablement state (enabled or disabled) of each USB port.

These function have a 1-to-1 correspondence with the underlying D-Bus API function described in in #1793.

The corresponding Web GUI application intended to use these REST APIs is here: ~#1275~ - Moved to #1273

**Comment by joseph-reynolds** [comment]
To clarify, this story is for USB ports directly attached to the BMC.  For example, a UPS power supply may communicate via the BMC's direct-attached USB port.  Other direct-attached USB ports could be used to upload or download data (media such as firmware images, or stolen data), so we want to give the BMC admin a way to disable these ports in a way that they can positively confirm to auditors.

An example design is:
- Have a way to identify all direct-attached USB ports, for example as separate D-Bus objects.
- For each USB port, have a property the admin can read/enable/disable that port.

See also: #612 for the story to enable and disable the virtual USB that supports OpenBMC's virtual media.

**Comment by joseph-reynolds** [comment]
Edited the comment above to clarify what this story is not:
1. Virtual media creates USB virtual devices that plug into the host's USB.
2. The BMC does not control its host's USB ports.

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/dev/issues/1793 is needed first

**Comment by nicoleconser** [comment]
Per @joseph-reynolds, the BMC should be able to enable/disable **individually** each of the BMC's 2 USB ports. 

The BMC should also be able to enable/disable access to the host-embedded USB ports (collectively: not individually).

But **we don’t know which of these controls we will have APIs for the BMC admin to use**.  Do we tie them all together?  Articulate them separately?  Control some but not others?

More details in [this Slack conversation](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1615316148474800?thread_ts=1615221577.447900&cid=C0Q6TQP5Z).

**Comment by joseph-reynolds** [comment]
I have more info for the post above:
1. For the present time, the only way for the BMC to control IBM Enterprise host-attached BMC ports is via BIOS settings.  The BMC root user can control BIOS settings, but no D-Bus interface is planned for this.  Therefore, no REST API and no web function.
2. I believe the BMC will have D-Bus APIs to control (enable/disable) each of the BMC-attached USB ports individually.  However, the use case is to be able to collectively control these ports, meaning either both enabled or both disabled.  And we want to expose this control on a REST API and on the GUI.

**Comment by ChicagoDuan** [comment]
Hi @mzipse ,  
#1793 blocked this task. Do you know  the progress of #1793? Can it provide the DBUS interface required for this task? So that I can start this task.

**Comment by ChicagoDuan** [comment]
Hi @gtmills and all, 
I am working on this task.  In redfish, it seems that there is no schema for USB ports to enable / disable. So I'll add it as an OEM schema.

**Comment by ChicagoDuan** [comment]
Done. Please review : https://github.com/ibm-openbmc/bmcweb/pull/115

**Comment by BMC-Bruce** [comment]
Hello @lxwinspur and @ChicagoDuan,

@mzipse Asked that you do Pull Requests (and I do see you have done one for ibm-openbmc/bmcweb#115) for the other parts of the too.    Like 48035: usb: Initialize USB Code Update | https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/48035 associated reviews.
 
[D-Bus service: disable BMC-attached USB ports #1793](https://github.com/ibm-openbmc/dev/issues/1793) is going to be CLOSED, as we are not really disabling USB Ports but just induvial services or features. 

Thank you!  And as always feel free to as questions or suggest other ways of solving the tasks.

-- 
Bruce

**Comment by BMC-Bruce** [comment]
Hello @lxwinspur and @ChicagoDuan,

There was a Decision: Create OEM Redfish API to “disable USB code update”. For now, just disable the USB code update service (which is actually not even done yet). Extra points to disable additional interfaces and services which use USB.

Utilize https://github.com/openbmc/service-config-manager to disable/enable the service
Make it like how we enable/disable ssh via Redfish via bmcweb
Just move this work item under the USB code update work since that's required to have something to disable
This is just to keep you updated on the refinement of this story and any impacts may need to be taken into account
for story Redfish: USB Port Enable / Disable #1781

Please let me know if you have any questions or concerns.

"**Andrew Geissler:  That was from our meeting on this. Seems like we just need the OEM defined and service-config-manager updated.**"

That is the way we are going correct?

Thanks!

-- 
Bruce

**Comment by ChicagoDuan** [comment]
> "**Andrew Geissler: That was from our meeting on this. Seems like we just need the OEM defined and service-config-manager updated.**" 
>"**Gunnar Mills: Yeah, so we won't use State Manager for this. Correct?**" 
>"**Bruce Mitchell: Correct.**"
> 
> That is the way we are going correct?
> 
No.  We can't make it like how we enable/disable ssh via Redfish for the following reasons:
1、The process of service-config-manager is this:  The service-config-manager  will create an object path when a service is started. For example, when the dropbear SSH service is started, it will create /xyz/openbmc_project/control/service/dropbear. We enable/disable SSH by setting the "Running" property on /xyz/openbmc_project/control/service/dropbear to enable/disable SSH.
2、But UsbCodeUpdate service is not a daemon, it is an app that will be called after inserting a USB flash disk. So the service-config-manager won't create a object path about UsbCodeUpdate. So we can't  use service-config-manager to enable/disable the UsbCodeUpdate.

I think of several solutions:
1、Modify the service-config-manager architecture and create the object path when the UsbCodeUpdate service is not started. When the USB srevice app is started, need check the “Enable” property of the object path. If it is false, cancel the update.
However, this direction makes great changes to service-config-manager and is unlikely to be merged. We can only downstream.

2、Change the direction of UsbCodeUpdate, change UsbCodeUpdate to a daemon, and then we can use service-config-manager.

3、Without using service-config-manager, use the redfish of bmcweb to directly delete the service file or udev/rules file of UsbCodeUpdate. However, this does not seem to be in line with the normal practice of openbmc.

What do you think of these solutions? Or do you have other directions?

Thanks!

**Comment by BMC-Bruce** [comment]
Hello @ChicagoDuan and @lxwinspur,

We talked about this today and the response was for you (and ISP) to do what is best for you.  As well as keeping in mind [47753: Add USB code update design doc](https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/47753) and also please up date and include the USB code update Enable / Disable feature to **47753: Add USB code update design doc**.

Thank you! And as always feel free to as questions or suggest other ways of solving the tasks.

--
Bruce

**Comment by lxwinspur** [comment]
> Hello @ChicagoDuan and @lxwinspur,
> 
> We talked about this today and the response was for you (and ISP) to do what is best for you. As well as keeping in mind [47753: Add USB code update design doc](https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/47753) and also please up date and include the USB code update Enable / Disable feature to **47753: Add USB code update design doc**. And these Gerrit review as well: [48035: usb: Initialize USB Code Update](https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/48035) [48236: usb: Add service and rules files](https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/48236)
> 
> Thank you! And as always feel free to as questions or suggest other ways of solving the tasks.
> 
> -- Bruce

Okay, Lem me update it. Thanks Bruce.

**Comment by ChicagoDuan** [comment]
> Hello @ChicagoDuan and @lxwinspur,
> 
> We talked about this today and the response was for you (and ISP) to do what is best for you. As well as keeping in mind [47753: Add USB code update design doc](https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/47753) and also please up date and include the USB code update Enable / Disable feature to **47753: Add USB code update design doc**. And these Gerrit review as well: [48035: usb: Initialize USB Code Update](https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/48035) [48236: usb: Add service and rules files](https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/48236)
> 
> Thank you! And as always feel free to as questions or suggest other ways of solving the tasks.
> 
> -- Bruce

Hi @BMC-Bruce . Thanks.  So what's the result of your discussion? Do we still need to use service-config-manager to enable/disable the UsbCodeUpdate?

**Comment by BMC-Bruce** [comment]
Hello @ChicagoDuan and @lxwinspur,

Using service-config-manager was just a thought brought up, but if it is not the correct place to do the enable/disable the UsbCodeUpdate then done do it in service-config-manager.  Just let us know where enable/disable the UsbCodeUpdate should be placed.  

We are interested in getting PRs up for reviews and comments. 

Thank you!

-- 
Bruce

**Comment by BMC-Bruce** [comment]
Thank you @mzipse, you are correct.
Edited and corrected.

**Comment by ChicagoDuan** [comment]
Hi @BMC-Bruce 
I have pushed a commit of service-config-manager, please review it :  https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/48780

When the phosphor_usb_code_update app is started, it will check the “Enable” property of the object path. If the property is false, phosphor_usb_code_update will cancel the update.
But  I'm not sure whether this commit will be merged. Maybe we can only do downstream.

**Comment by BMC-Bruce** [comment]
Hello @ChicagoDuan,

I +1 it; and I see @joseph-reynolds make some good comments.

Yes, I believe @geissonator would like things up for Gerrit review and if they done merge in a timely fashion then cherry pick the patch to a https://github.com/ibm-openbmc/ repo.

Thank you for your efforts, much appreciated

-- 
Bruce

**Comment by BMC-Bruce** [comment]
Hello @lxwinspur and @ChicagoDuan,

Regarding [48780: ADD USB Code Update enable/disable](https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/48780), @ChicagoDuan once the comments have been addressed please do a PR.

@lxwinspur and @ChicagoDuan am I correct that [48780: ADD USB Code Update enable/disable](https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/48780) is not addressing the Redfsh portion?
Please supply on how the Redfish portion is going?  Is is passing **Redfish-Service-Validator**?

Thank you for your efforts, much appreciated

--
Bruce

**Comment by BMC-Bruce** [comment]
All George Liu, via Discord, said "Yes, we will add the Redfish portion this week"

**Comment by BMC-Bruce** [comment]
Hello @lxwinspur and @ChicagoDuan,
Let's get @rfrandse and/or @geissonator to setup https://github.com/ibm-openbmc/service-config-manager
so that PRs can be made since the MAINTAINERS of https://github.com/openbmc/service-config-manager
are moving so slowly.

**Comment by ChicagoDuan** [comment]
> All George Liu, via Discord, said "Yes, we will add the Redfish portion this week"

Done. Redfish usb code update schema is implemented. Please review it: https://github.com/ibm-openbmc/bmcweb/pull/164

**Comment by BMC-Bruce** [comment]
Thank you @ChicagoDuan, much appreciated.

**Comment by BMC-Bruce** [comment]
Hello @lxwinspur and @ChicagoDuan,

For the service-config-manager repo please do your pull request against the 1020 branch of [ibm-openbmc/service-config-manager](https://github.com/ibm-openbmc/service-config-manager/tree/1020)

Contacting @rfrandse is a good idea when doing a PR from a Gerrit review of something like [openbmc/service-config-manager](https://github.com/openbmc/service-config-manager) to the 1020 branch of [ibm-openbmc/service-config-manager](https://github.com/ibm-openbmc/service-config-manager/tree/1020), as your PR will really be from here [48780: ADD USB Code Update enable/disable](https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/48780) and he knows how to do "the right stuff" to create the PR for you (if you ask him kindly 😄).

Thank you! And as always feel free to make comments and asking questions!

--
Bruce

**Comment by ChicagoDuan** [comment]
> Hello @lxwinspur and @ChicagoDuan,
> 
> For the service-config-manager repo please do your pull request against the 1020 branch of [ibm-openbmc/service-config-manager](https://github.com/ibm-openbmc/service-config-manager/tree/1020)
> 
> Contacting @rfrandse is a good idea when doing a PR from a Gerrit review of something like [openbmc/service-config-manager](https://github.com/openbmc/service-config-manager) to the 1020 branch of [ibm-openbmc/service-config-manager](https://github.com/ibm-openbmc/service-config-manager/tree/1020), as your PR will really be from here [48780: ADD USB Code Update enable/disable](https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/48780) and he knows how to do "the right stuff" to create the PR for you (if you ask him kindly smile).
> 
> Thank you! And as always feel free to make comments and asking questions!
> 
> -- Bruce

Done. Please review it : https://github.com/ibm-openbmc/service-config-manager/pull/1

**Comment by BMC-Bruce** [comment]
Hi @ChicagoDuan,

I do not have the permissions to add Reviewers to https://github.com/ibm-openbmc/service-config-manager/pull/1
If you can please add @rfrandse, @eddiejames, @lxwinspur, @spinler, @joseph-reynolds, @BMC-Bruce, and maybe @gtmills.
Not everyone will review but we need some.

The odd thing is I do have the permissions to add Reviewers https://github.com/ibm-openbmc/bmcweb/pull/164

Thank you!

-- 
Bruce

**Comment by BMC-Bruce** [comment]
Thank you @ChicagoDuan and @lxwinspur for your efforts and getting this far before your meeting with @mzipse.

**Comment by BMC-Bruce** [comment]
Hi  @ChicagoDuan and @lxwinspur,

Looking for a status update and an ETA for completion (I realize code reviews slow things down).
Can we be done by Dec. 15, 2021?  Or give me a a date you are comfortable with.

Thank you! And as always feel free to as questions and/or offer suggestions.

--
Bruce

**Comment by ChicagoDuan** [comment]
> Can we be done by Dec. 15, 2021?

I think this date is OK. But it depends on the time of review. https://github.com/ibm-openbmc/bmcweb/pull/164

**Comment by BMC-Bruce** [comment]
Thank you @ChicagoDuan

**Comment by ChicagoDuan** [comment]
The PR is merged: https://github.com/ibm-openbmc/bmcweb/pull/164
