### ISSUE TITLE
PHAL: Auto generation of Device tree APIs

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1789]
- Add  support for system specific  FAPI targets maps..
- Create  Fapi attribute filter file for the BMC specific   attributes.
- Meta data preparation Device tree APIS
- Generate Device tree macros for read/write attributes.

**Comment by RameshIyyar** [comment]
The above each story point addressed in below patch and its merged in upstream **phal/pdata**
https://github.ibm.com/phal/pdata/commit/79f85543179568930f101957dd01d0fdadde1cfc
https://github.ibm.com/phal/pdata/commit/c20babf8daa63dd1c7e1afe5f57f7ec6e9294387
https://github.ibm.com/phal/pdata/commit/c359d279b11c59601bbc2b9669a0982aea15f45a
https://github.ibm.com/phal/pdata/commit/c3e9ebec3666895722506e41d814101ba406ab88
https://github.ibm.com/phal/pdata/commit/857c783039ab5b6fb13ce8118f5dc2b103fe3603
https://github.ibm.com/phal/pdata/commit/14fd76ac61a51d2d60f38269bd6c82c41c0af1c3
https://github.ibm.com/phal/pdata/commit/84ec4cfa75309329da941c72770919b043d745a9
https://github.ibm.com/phal/pdata/commit/49d9557666183cec31972c230a8643cb75a10c8f
https://github.ibm.com/phal/pdata/commit/a185759408898131aeb1b32154e99363966ea5ce
https://github.ibm.com/phal/pdata/commit/04fd928f2f80cb6833fca8389cc456c7208156dc
https://github.ibm.com/phal/pdata/commit/5b0d866c64ba97780d220dd3b0529ff7f0a69ea9
