### ISSUE TITLE
Login error instances

### ISSUE THREAD

**Issue by alissaylee** [ibm-openbmc/dev#179]

**Comment by alissaylee** [comment]
https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318854510_Login_Enter_fields

**Login Error Instances**
- Invalid username or password: 1 message will appear 30px above "BMC Host or IP address" field. Message will state "Invalid username or password. Please try again." and field validations (with warning icon and red border over field).
- Empty fields will be highlighted.
- Invalid format for IP Address.
- Server is unreachable (after attempting to Login).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by BeccaBroek** [comment]
Resolved with https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/17619/
