### ISSUE TITLE
PFP::control - Allow configurable non-high speed initial fan setting during system boot

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1791]
Allow configurable non-high speed (100% PWM) initial setting defined by thermal team during system boot instead of putting fans to high speed.

**Comment by msbarth** [comment]
An additional (and optional) zone configuration entry should be added to support this that can be applied to a machine temporarily by updating the `zones.json` file within `/etc/phosphor-fan-presence/control/` or permanently by adding it to the `zones.json` file within the machine's BMC image that's installed under `/usr/share/phosphor-fan-presence/control/`

The zone object can look for this optional configuration entry and when it exists, apply this to be the fan speed when the fan control application starts (and sets the initial fan speed). When this entry does not exist within the configuration, the `full_speed` entry should be used to set the initial fan speed at startup. 

***Note: The `full_speed` entry should continue to be used after fan control begins dynamically changing fan speeds in the case the fans should be set to full speed according to the outcome of a configured event.**

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/43594
