### ISSUE TITLE
GUI : FED : AppHeader AppNavigation translations

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#1794]
Add translations to AppHeader and AppNavigation components

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29889

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29889 merged
