### ISSUE TITLE
GUI : FED : TPM Policy to Redfish

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#1795]
## SME
**BMC**: @gtmills, Ali Ahmed (slack: ali.ahmed2)
**RAS**:
**PHYP**:

### Overview
The TPM policy is a enable/disable toggle that currently lives on the Server power operations page. Through user research we found that this is not changed often and also is a security policy. The current implementation uses the REST API and needs to be migrated to Redfish. The backend work is complete and we just need an image from the SME so we can test.

#### As Is UI
![image](https://user-images.githubusercontent.com/1183515/130460521-cb5438d6-ada8-49c6-99b9-a4d5d4ffb602.png)

#### To Be UI
![image](https://user-images.githubusercontent.com/1183515/130460678-254ee539-66f1-45d9-89c1-7c5554df0457.png)

### UX Flow / Interaction Requirements
- [x] Migrate the TPM  component from the Server power operations page to the Security settings page and place under Network settings section.
- [x] Replace the REST API call with the Redfish API call
- [x] Label TPM as Host TPM
- [x] Update section dividers to use global style

### cURL Commands and Redfish Response
- [ ] Add Redfish response (Need impage to see response)

**Curl command**
```
curl -k -H "X-Auth-Token: $token" -X PATCH -d \
'{"TrustedModuleRequiredToBoot":false}' \
https://${bmc}/redfish/v1/Systems/system
```

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [x] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [x] Verified markup is semantic
- [x] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

Move TPM policy status on Server power operations page to Redfish

**Comment by derick-montague** [comment]
Closing as part of #2819

**Comment by derick-montague** [comment]
Opening up to update TPM to move to Redfish

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/46960

TODO: 
- [ ] waiting for https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46928 to merge in order to test patch
- [ ] system endpoint is hardcoded for now and will need to not be hardcoded, Intel is working on a fix for hardcoding endpoints (they shared a demo of their proposal and will push up a WIP commit in Gerrit to discuss further)

**Comment by mzipse** [comment]
Closing.  Work is complete.
