### ISSUE TITLE
Cater for platform errors in libkeb

### ISSUE THREAD

**Issue by devenrao** [ibm-openbmc/dev#1797]
1) For platform specific errors libekb need to return unique error code
2) Notice at present FAPI_TRY macro does coredump when plat form error is returned
3) op-proc-contol need do define unique error message registry values for platform errors.

**Comment by ojayanth** [comment]
Required libekb plat support also to enable this errors . Increasing the complexity.

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/49201 + ipl version bump
