### ISSUE TITLE
Design and implement openBMC REST API to  Upload digitally signed certificate and Private key.

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#18]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ojayanth](https://github.com/ojayanth)**
_Thursday Aug 02, 2018 at 10:57 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3341_

----

Provide REST API to upload Digitally signed certificate and Private key for specific type.
   Note: need to look the use case for with valid CSR and private key requested scenario.

**Comment by joseph-reynolds** [comment]
Today I asked the security working group to review this design under https://gerrit.openbmc-project.xyz/#/c/11840.
