### ISSUE TITLE
User Management: Password error instances

### ISSUE THREAD

**Issue by alissaylee** [ibm-openbmc/dev#180]
https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318854272_Login_Default

**Password Error Instances**
In-field validations:
- Current password: "Invalid password entry."
- New password: "Entry should not match current password."
- Retype new password: "Passwords do not match."
- Empty field validation

- Modal for error (back-end) setting password.
- Iterations to the "Show" and "Hide" interactions (relocated outside of text field and 20px right of it).
- Notifications: will inform user when settings saved successfully or failed (GUI will not save input fields with errors)

**Comment by rfrandse** [comment]
refresh
