### ISSUE TITLE
Allow deleting of Redfish event logs

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1802]
Make sure deleting event logs using Redfish is supported, and that the corresponding PELs get deleted as well.  The same IBM restrictions as deleting regular PELs applies, as in you cannot delete an event log that has a 'gard' record, in which case the delete or delete all would fail

**Comment by spinler** [comment]
Turns out that deleting a redfish event log should not delete the PEL, so renaming issue.

**Comment by gtmills** [comment]
https://github.com/openbmc/bmcweb/blob/4a0bf539728cada806fc7a16a208edc6332bdb86/redfish-core/lib/log_services.hpp#L1712

**Comment by spinler** [comment]
Yes, closing.
