### ISSUE TITLE
Firmware GUI page

### ISSUE THREAD

**Issue by alissaylee** [ibm-openbmc/dev#181]
https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318858591_Firmware_Default_Upload

**Firmware GUI instances:**
- Re-locate Upload/Download image file functionality to top of page (consolidate vertical real-estate with separating out actions as radio buttons).
- Fixed height of 140px between upload/download radio button options and Image file table (to account for file upload/validation messages/progress loading, etc.
- Fixed height of 16px b/t upload/download radio button options and fields that follow (input fields/file uploader)
- Upload instances:
   - Choose single file
   - View loaded file
   - Upload file
   - Error instance: Field validation for failed file upload
- Download instances:
   - Input fields: 
      - TFTP IP address
      - file name
   - Test IP address
   - Download file
   - Error instance: Field validations for invalid TFTP IP address and/or leaving required fields empty

https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318858589_Firmware_Upload_Error
https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318858582_Firmware_Download_Error
**Error instances:**
- Technical error uploading file (i.e. Version already exists or failed to be extracted)
- Technical error downloading file (i.e. Cannot be downloaded in allotted time)
- Leaving page in middle of editing or making changes

https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318858587_Firmware_Upload_Successful
https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318904320_Firmware_Toast_Notifications
**Notifications:**
- Successful/Failed Upload/Download
- Successful/Failed delete of image
- Successful/Failed activation of image file
- Successful /Failed boot priority change

https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318858580_Firmware_Activation_Confirmation
https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318858584_Firmware_Functional_Priority_Change_Confirmation
**Editing uploaded/downloaded file images:**
- Activating image file modal
- Deleting image file modal
- Changing boot priority between active and functional image files
- Changing boot priority between active image files

ITEM TO REVISIT -- Ability to drag-and-drop image files in the tables.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
This tracks the development work to implement https://github.com/openbmc/phosphor-webui/issues/53
