### ISSUE TITLE
Support multiple PEL callouts w/ priorities sent in by user

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1810]
When host diags and PHAL code creates hardware errors, they have some machine data that will contain their callouts, with their priorities.  We need to somehow get that data into an openbmc event log and into a PEL as proper callouts.

An off the wall idea is to have the logging code read that data itself so it can find the callouts based on some key.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/36032/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/36032 merged
