### ISSUE TITLE
Report power supply telemetry data

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1815]
Power supply & system power sensor telemetry data for external collection.  We will need to store the telemetry data in DBUS.  Verify from there they can get pulled out via Redfish telemetry service (will be HMC pulling the data on customer systems).

OCC power sensors list in https://github.com/ibm-openbmc/dev/issues/2150#issuecomment-875640127.

Read trending data along with all other EnergyScale data, handle fails. Buffered Input power 30s rolling average required? In Redfish? yes.

Assume we can read input history from psu's.  At some later point, if some psu don't support it, it can be made configurable.

Need information sent in FSP get_pex_ps_element_info direct cmd in some format. 
 - mod 0 info not needed (label power/etc).  later release will need ps input voltage for https://github.com/ibm-openbmc/dev/issues/1618.
 - mod 2 info just need input power max&ave (30s rolling) and status in DBus; collectable via Redfish.
 - mod 3 nothing else needed - ps loc code already on DBus.

POR is to use what Intel has merged already for telemetry, and do updates to that if needed.

Need phosphor-hwmon configs for the PS sensors.

OCC output power sent to BMC and displayed on power capping gui.

Properties wanted from power team are:
PS Input power 30s rolling max&ave for EnergyStar.
System power every 5 second reading (from OCC).
APSS channels power every 5 second reading (from OCC).
Processor power min/max/ave every hour is extra credit (will be in OCC PEL).
APSS memory power min/max/ave every hour is extra credit (will be in OCC PEL).

For this issue, should be suffice to collect/append once-per-5s readings for 1 hour for every of these sensors in one of the rainier systems when powered on.

**Comment by bjwyman** [comment]
I think there is some slight overlap here.
> Need phosphor-hwmon configs for the PS sensors

I was doing that as part of #1709.

**Comment by bjwyman** [comment]
> Read trending data along with all other EnergyScale data, handle fails. Buffered Input power 30s rolling average required? In Redfish? yes.

I read that as the INPUT_HISTORY command the phosphor-psu-monitor needs to read and push out to D-Bus.

Added myself as one of the assignees due to that.

**Comment by bjwyman** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/328

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/53170
...
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/53173

**Comment by bjwyman** [comment]
GPIO character device -> libgpiod -> line name: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/53120
Merged: https://github.com/openbmc/docs/commit/1f45b3001f01e56226f74f6e1f272ff4adc70874

**Comment by bjwyman** [comment]
[[PATCH] ARM: dts: aspeed: Everest and Rainier: Add power-ffs-sync-history GPIO](https://lore.kernel.org/openbmc/20220421213638.1151193-1-bjwyman@gmail.com/T/#u)

**Comment by bjwyman** [comment]
power-ffs-sync-history GPIO: https://github.com/openbmc/linux/commit/fc8ba762618d0f80130ea68853692c52402d0b36
and https://github.com/openbmc/openbmc/commit/6bc61b816079134c3aaa9e868b1022fbed8b8f18

**Comment by bjwyman** [comment]
phosphor-power changes: https://github.com/openbmc/phosphor-power/commit/49b8ec4924bfde34e9ae6f65d04ba7d47f2bc71e

**Comment by bjwyman** [comment]
Autobump for phosphor-power: https://github.com/openbmc/openbmc/commit/5c73d2a2dea7ed45600e7c9599f1166a8e155d7b

**Comment by bjwyman** [comment]
Lower input history sync delay to 5ms:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/53762
https://github.com/openbmc/phosphor-power/commit/c9e840e443d88bdef496388ccbdbc419868ab1ba

**Comment by bjwyman** [comment]
> [ibm-openbmc/bmcweb#328](https://github.com/ibm-openbmc/bmcweb/pull/328)

I believe this is ready for a re-review after some schema updates, and changing from parallel arrays to an array of InputHistoryItem entries with date/average/maximum.

**Comment by bjwyman** [comment]
https://github.com/ibm-openbmc/bmcweb/commit/adb4133efdf148878799b37be4ff278030572465

**Comment by derekhoward55** [comment]
bash-4.2$ curl -k https://${bmc}/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply0/Metrics
{
  "@odata.id": "/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply0/Metrics",
  "@odata.type": "#PowerSupplyMetrics.v1_0_0.PowerSupplyMetrics",
  "Id": "Metrics",
  "Name": "Metrics for powersupply0",
  "Oem": {
    "@odata.type": "#OemPowerSupplyMetrics.Oem",
    "IBM": {
      "@odata.type": "#OemPowerSupplyMetrics.IBM",
      "InputPowerHistoryItems": [
        {
          "Average": 187,
          "Date": "2022-07-18T15:41:16+00:00",
          "Maximum": 187
        },
        {
          "Average": 187,
          "Date": "2022-07-18T15:40:46+00:00",
          "Maximum": 187
        },
        {
          "Average": 187,
          "Date": "2022-07-18T15:40:16+00:00",
          "Maximum": 187
        },
...
        {
          "Average": 187,
          "Date": "2022-07-18T14:41:44+00:00",
          "Maximum": 187
        }
      ]
    }
  }
}bash-4.2$ curl -k https://${bmc}/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply1/Metrics
{
  "@odata.id": "/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply1/Metrics",
  "@odata.type": "#PowerSupplyMetrics.v1_0_0.PowerSupplyMetrics",
  "Id": "Metrics",
  "Name": "Metrics for powersupply1",
  "Oem": {
    "@odata.type": "#OemPowerSupplyMetrics.Oem",
    "IBM": {
      "@odata.type": "#OemPowerSupplyMetrics.IBM",
      "InputPowerHistoryItems": [
        {
          "Average": 167,
          "Date": "2022-07-18T15:41:48+00:00",
          "Maximum": 167
        },
        {
          "Average": 167,
          "Date": "2022-07-18T15:41:18+00:00",
          "Maximum": 167
        },
        {
          "Average": 167,
          "Date": "2022-07-18T15:40:48+00:00",
          "Maximum": 167
        },
        {
          "Average": 167,
          "Date": "2022-07-18T15:40:18+00:00",
          "Maximum": 167
        },
        {
          "Average": 167,
          "Date": "2022-07-18T15:39:48+00:00",
          "Maximum": 167
        },
...
        {
          "Average": 167,
          "Date": "2022-07-18T14:42:22+00:00",
          "Maximum": 167
        }
      ]
    }
  }
