### ISSUE TITLE
regulators: Read sensors/telemetry and publish values on D-Bus

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1816]
The following sensor/telemetry types need to be read from regulators and published on D-Bus:
* iout
* iout_peak
* iout_valley
* pout
* temperature
* temperature_peak
* vout
* vout_peak
* vout_valley

The sensors should be read once per second while the chassis is powered on.  The sensor data should be published on D-Bus using the standard interfaces so that it can be successfully consumed by bmcweb/Redfish.

**Work Items**
* Define new JSON objects
* Update markdown documentation
* Add new JSON objects to JSON schema and configuration file validation tool
* Enhance C++ firmware to support new JSON objects, read sensor values, and publish them on D-Bus.
* Perform end-to-end testing on Rainier and Everest

**Comment by smccarney** [comment]
This support has been implemented.
