### ISSUE TITLE
Report Rainier fan telemetry data

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1817]
Fan speed telemetry data for external collection.

Fan speeds already placed on DBUS. Verify from there they can get pulled out via Redfish telemetry service (will be HMC pulling the data on customer systems).

Properties wanted from thermal team are:
Fan speed min/max/ave every hour.

For this issue, should be suffice to collect/append once-per-minute readings for 1 hour for every fan rotor in one of the rainier systems when powered on.

**Comment by mzipse** [comment]
@derekhoward55 , can you provide more info to IPS?  Does this story refer to the work to get the fan telemetry into dbus?  Or does this story refer to the work to get this from dbus to the Redfish telemetry framework?  Also can you post a link or some info on the document from Jordan during the workshop?

**Comment by derekhoward55** [comment]
After further investigation, both getting the data onto DBus (https://github.com/ibm-openbmc/dev/issues/1778), and getting the data from DBus into the telemetry service are handled under other github issues.

This issue is for confirming the telemetry data is in place on this system, and adding any other data that is needed that is missing.

As the above issues' work is still in progress, we'll remove the ReadyForDev label for now, until the blocking work has been completed.  Thanks!

**Comment by derekhoward55** [comment]
With Ali's help, built report metrics. Telemetry service created report, snippet below.


>     {
>       "MetricId": "MaxFan0_0_30s",
>       "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan0_0/Reading",
>       "MetricValue": "7324.000000",
>       "Timestamp": "1973-04-11T06:24:04+00:00"
>     },
>     {
>       "MetricId": "AveFan0_0_30s",
>       "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan0_0/Reading",
>       "MetricValue": "7308.125233",
>       "Timestamp": "1973-04-11T07:13:11+00:00"
>     },
>     {
>       "MetricId": "MinFan0_0_30s",
>       "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan0_0/Reading",
>       "MetricValue": "7295.000000",
>       "Timestamp": "1973-04-11T01:57:06+00:00"
>     },
>     {
>       "MetricId": "MaxFan0_1_30s",
>       "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan0_1/Reading",
>       "MetricValue": "9791.000000",
>       "Timestamp": "1973-04-10T22:53:11+00:00"
>     },
>     {
>       "MetricId": "AveFan0_1_30s",
>       "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan0_1/Reading",
>       "MetricValue": "9773.717800",
>       "Timestamp": "1973-04-11T07:13:11+00:00"
>     },
>     {
>       "MetricId": "MinFan0_1_30s",
>       "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan0_1/Reading",
>       "MetricValue": "9765.000000",
>       "Timestamp": "1973-04-10T23:10:39+00:00"
>     },


Timestamps seem odd and need to be verified, will do that as part of power telemetry stories.  Close this out.
