### ISSUE TITLE
GUI: Generate SSL Certificate

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#182]
## Expected Delivery Dates
- [ ] UX: 04/04/19
- [ ] Backend: 03/28/19
- [ ] FED: 05/30/19

## Stakeholders
**SME**: @ojayanth, @devenrao
**DR**: @nicoleconser 
**UX**:  @jandraa   
**FED**: 

## Invision Prototype 
https://ibm.invisionapp.com/share/K8NYRVZVEC5#/319042048_1-_Generate_Certificates

### Open questions
- [x] How do users identify a certificate when there is more than one of a single type?
*Note: The planned way to identify certificates of a single type is by enumerating them. This does not seem like a good experience of identifying certificates.

- [ ] How do users interact with the date? Why is knowing the exact valid from and valid until dates valuable vs the number of days until expiration? ('valid from - valid until' VS. 'X days left')
The date is easy to understand. If a certificate didn't expire for 2 years, the number of days being something like 700 days, the user would have to manually determine the actual expiration date. This could be an issue if they needed that date for any reason.

- [ ] What happens after a CSR has been generated? When and how is it accessed again and where should it live? 
Currently, a CSR is not accessible again after the CSR window is closed. Users would have to go through the generation process again; a CSR is not stored for any period of time. 

- [ ] How / when is the private key uploaded to be part of the CSR? (if at all)
- [ ] Where are private keys stored? 
Currently, a private key is not accessible. I would like to know more about if and when they would want to, for what, if they upload the private key, etc. 

- [ ] Does each certificate have a different private key or do all of your certificates have the same private key because you are always you? 
*Need clarification: 'It is one key for certificate type. This key will be overwritten if user issues another CSR request.' 

- [ ] How would it be beneficial to pre-populate CSR info for users? Could they pre-populate using the passphrase of a different certificate to copy the info?
Research indicates some users get the info for a CSR by using a password to 'decrypt' their previous key/certificate and copy the info from there. 

## Design Issue
https://github.com/openbmc/phosphor-webui/issues/60

## Development Issue
---

**Comment by alissaylee** [comment]
Generating certificates (specific to server certificate file)

1. User may be given option to “download” or generate CSR from our opeBMC GUI
2. User will fill out the CSR form with organization and other relevant fields)
3. Once form is completed, it will be given to the Certificate Authority to generate a certificate.
4. User will wait for the certificate to be generated
5. User will eventually receive server certificate to upload via the GUI

**Outstanding questions:**
- Unsure about private key file's relevance to CSR creation
- Is CSR-related certificate specific to server certificates?
- Can we display expiration dates for certificate?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by BeccaBroek** [comment]
design here https://github.com/openbmc/phosphor-webui/issues/60

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
We would like more feedback, but the design has reached a point where we can start building the layout.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@jandraa @gtmills  - Where in the navigation should this live for now? We have it listed under `Access Control` in our proposed information architecture.

**Comment by jandraa** [comment]
I'd suggest under `Server Control`

**Comment by miramurali23** [comment]
Hey team! I have a few clarifying questions..
@jandraa @gtmills @derick-montague @nicoleconser 

<img width="368" alt="Screen Shot 2019-05-01 at 1 18 31 PM" src="https://user-images.githubusercontent.com/11800028/57035062-c0b9e780-6c16-11e9-91d0-ffab117a0748.png">
**Where should SSL certificate be in terms of the hierarchy of the navigation ordering in Server configurations?** 

<img width="1247" alt="Screen Shot 2019-05-01 at 1 19 00 PM" src="https://user-images.githubusercontent.com/11800028/57035199-0c6c9100-6c17-11e9-9cab-1e7572aec422.png">
**When I click on the information symbol..what should that then display?**

<img width="631" alt="Screen Shot 2019-05-01 at 1 24 19 PM" src="https://user-images.githubusercontent.com/11800028/57035253-358d2180-6c17-11e9-8e7e-6f6daea050b9.png">
**When I add a new certificate is there a difference between upload and add file? I am assuming upload is what you press after adding the file and then the modal closes?** 

<img width="1008" alt="Screen Shot 2019-05-01 at 1 27 47 PM" src="https://user-images.githubusercontent.com/11800028/57035345-653c2980-6c17-11e9-87d7-e849061c977d.png">
**Comments on the CSR modal: When I click on the information symbol, how should the information be displayed? When I add an alternative name would a new text field then appear? Also (maybe we can discuss this after the modal has been implemented) but if the information provided is invalid, what error messages would we be showing?**

<img width="200" alt="Screen Shot 2019-05-01 at 1 33 59 PM" src="https://user-images.githubusercontent.com/11800028/57035430-a7656b00-6c17-11e9-989b-7eebb3cdf1ee.png">
**(Sorry the image is bad..but I could only see both the icons when I had the add certificate modal up) Regarding the two icons on the certificate row..does the refresh icon just refresh the table and the delete icon removes the certificate?** 

Thank you!

**Comment by jandraa** [comment]
> Where should SSL certificate be in terms of the hierarchy of the navigation ordering in Server configurations?
- I can't confidently answer that, I would put it as the last item or second to last item (before Date & Time)

> When I click on the information symbol..what should that then display?
- This should be a description of what that particular type of certificate is used for. Very preliminary text can be found here: https://ibm.box.com/s/527s16f93b3lkd8hvu3v9baow94ylgbl . @ojayanth @devenrao and Kaushik Venkatesh, please review and add suggestions 

> When I add a new certificate is there a difference between upload and add file? I am assuming upload is what you press after adding the file and then the modal closes?
- Your assumption is correct. Adding the file would display the chosen file on the modal. At this point, the user has the option to remove the file, or continue with the upload by pressing 'Upload'. 

> Comments on the CSR modal: When I click on the information symbol, how should the information be displayed? 
- Style should look something like this: 
<img width="257" alt="Screen Shot 2019-05-01 at 3 29 45 PM" src="https://user-images.githubusercontent.com/44675611/57040756-fdd9a600-6c25-11e9-9e2c-9fe1aea13b93.png">
- Very preliminary text can be found here: https://ibm.box.com/s/527s16f93b3lkd8hvu3v9baow94ylgbl @ojayanth @devenrao and Kaushik Venkatesh, please review and add suggestions 

> When I add an alternative name would a new text field then appear? 
- Yes, if possible it would look like this: https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319100170_Generate_Certificates_-_Alternative_Name

> Also (maybe we can discuss this after the modal has been implemented) but if the information provided is invalid, what error messages would we be showing?
- I'm not sure how we would check if the information is invalid, other than the field validation. @devenrao @ojayanth what types of errors could we have? 

> (Sorry the image is bad..but I could only see both the icons when I had the add certificate modal up) Regarding the two icons on the certificate row..does the refresh icon just refresh the table and the delete icon removes the certificate?
- The refresh icon is intended to be a replace icon. Currently, only one certificate of each type can be uploaded, so this should allow a user to replace the current one without deleting and then uploading a new one. The flow would look like this: 

---
You will probably also need the options for the dropdowns. I've pulled this from the Redfish documentation and Google searches. @devenrao and @ojayanth please review to make sure we will support all of this:

**Collection type:** 
- HTTPS
- LDAP client
- CA

**Key bit length:** 
- 512
- 1024
- 2048
- 4096
- 8192
- 16384

**Key usage:**
- ClientAuthentication
- CodeSigning
- CRLSigning
- DataEncipherment
- DecipherOnly
- DigitalSignature
- EmailProtection
- EncipherOnly
- KeyAgreement
- KeyCertSign
- KeyEncipherment
- NonRepudiation
- OCSPSigning
- ServerAuthentication
- Timestamping

**Key pair algorithm:**
- DES
- AES
- RSA

We can talk about if and how to display what they mean in the info-icon text.

**Comment by miramurali23** [comment]
Hey @gtmills! has generating ssl certificate been implemented yet in the backend and if so what is the redfish path? Thanks in advance!

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by miramurali23** [comment]
Are we doing any sort of country code validation in the backend? I tried to generate a CSR form with an invalid country code and it worked.

**Comment by rfrandse** [comment]
refresh

**Comment by miramurali23** [comment]
TESTING: 
1.) Click on Generate CSR button
2.) This is the inputs I used for testing:
```{
    "City": "Austin",
    "CertificateCollection": {
        "@odata.id": "/redfish/v1/Managers/bmc/NetworkProtocol/HTTPS/Certificates/"
    },
    "CommonName": "www.ibm.com",
    "ContactPerson": "myname",
    "AlternativeNames": [],
    "ChallengePassword": "",
    "Email": "",
    "Country": "US",
    "KeyCurveId": "",
    "KeyBitLength": 1024,
    "KeyPairAlgorithm": "RSA",
    "Organization": "IBM",
    "OrganizationalUnit": "ISL",
    "State": "AU"
}```

<img width="902" alt="Screen Shot 2019-05-14 at 3 07 15 PM" src="https://user-images.githubusercontent.com/11800028/59534732-c57be780-8eb4-11e9-956b-4e641e7fbd8f.png">
^^ The data format the fields follow

3.) once all the required fields are filled in, click Generate CSR
4.) You should now see a CSR code displayed with the functionality of copy and download in the bottom
5.) In a failed state the modal should close and you should see an error toast message displayed.

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/22468

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/22468 merged
