### ISSUE TITLE
phosphor-regulators: Improve error checking in config file validator

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#1820]
The following error conditions lead to pretty long, hard to read error messages from the Python interpreter:
* Config file does not exist
* Config file is not readable
* Config file is not a JSON file
* Schema file does not exist
* Schema file is not readable
* Schema file is not a JSON file

Example error message:
```
Traceback (most recent call last):
  File "validate-regulators-config.py", line 193, in <module>
    config_json = validate_schema(args.configuration_file, args.schema_file)
  File "validate-regulators-config.py", line 160, in validate_schema
    config_json = json.load(config_handle)
  File "/usr/lib64/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

The validation tool should be enhanced to check for these conditions and print simple, user-friendly error messages.

File existance and readability can be checked via the following Python APIs:
* os.path.exists(file)
* os.access(file, os.R_OK)

For the case where a file is not in the JSON format, hopefully the error from the JSON interpreter can be caught allowing us to print a simpler message.

The google test function CommandLineSyntax in file validate-regulators-config_tests.cpp will need to be updated to handle the new error messages.

**Comment by bobkingkkp** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/37433
