### ISSUE TITLE
peltool: Support python UserData parsers

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1821]
We've at least gotten far enough in #1166 that we know we'll be running user supplied python scripts for UserData sections when there is a python plugin for it.

This story is for the implementation of the design in #1166.

**Comment by harisuddin82** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/34373

**Comment by spinler** [comment]
Merged.
