### ISSUE TITLE
GUI : FED : Toast Component Icons

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1826]
## As Is
Toast components do not include an icon.

### Screenshot
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/4f4fbb82-2fce-42eb-afd0-ac43649b9627)

## To Be
Toast components, with the exception of the info type, require an icon

### Screenshot
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/67a96c17-9543-420e-8e5d-892f34dc6a27)

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36282

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36408
