### ISSUE TITLE
Redfish: Implement new event log propeties Resolved & Modified Date 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1827]
This will allow the GUI to move to Redfish Logs #616 

#1358 tracks upstreaming these properties. Other properties will come later.

**Comment by gtmills** [comment]
Modified will map to https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/29734

**Comment by XiaochaoMa** [comment]
Since redfish 2020.4 is required, set it to block.

**Comment by gtmills** [comment]
2020.4 is due out 1/15. I will hopefully get us to 2020.4 just a couple of days after it is released. so hoping by the week of 1/18 we are at 2020.4

**Comment by XiaochaoMa** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/39877

**Comment by XiaochaoMa** [comment]
@gtmills 
I searched the specifications of Redfish 2020.4 version. No parameter information for "Modified Date" was found. Did I miss which document?
And after reading the explanation of UpdateTimestamp, I think the "Modified" attribute is enough to meet the conditions.

**Comment by gtmills** [comment]
Modified is the property. 
Work is already done. https://github.com/openbmc/bmcweb/commit/d139c2364bec98a5da1fe803414f3b02fdcd3092 
So after resolved goes in, this is complete. 
Thanks!

**Comment by gtmills** [comment]
@XiaochaoMa Resolved is a ReadWrite property. 
 https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/39877 only does the GET (Read). 
 Do you have plans to push a commit for the write?

**Comment by XiaochaoMa** [comment]
> @XiaochaoMa Resolved is a ReadWrite property.
> https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/39877 only does the GET (Read).
> Do you have plans to push a commit for the write?

Got it.
