### ISSUE TITLE
GUI : FED : Primary Navigation Focus States

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1828]
## As Is
The primary navigation has both `<button>` and `<a>` elements. Each of their focus states are different.

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/5e5495b1-b496-408f-88c9-ea59e858be3c)

## To Be
The focus states should match. The issue is that the `<button>` element has the `outline` CSS property set to `0` and the the `<a>` element does not. This should only be changed in the primary navigation.

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/fdbefe4a-77fe-4af8-9da0-429b38c6b44c)

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/32548

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/32548 merged
