### ISSUE TITLE
GUI: IPKVM 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#183]
## Expected Delivery Dates
- [x] UX: 2/28/19
- [x] Backend: 3/15/19
- [x] FED: 4/04/19

## Stakeholders
**SME**: @eddiejames 
**DR**: @nicoleconser 
**UX**: @jandraa 
**FED**: @gtmills 

## Use Case
Need a new KVM page.

## InVision Prototype
https://ibm.invisionapp.com/d/main#/console/15340578/318953777/preview

## Design Issue
https://github.com/openbmc/phosphor-webui/issues/52

## Development Issue
---

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@gtmills - What is needed from design for this issue? This issue seems to be completed by the UX team and waiting for development completion so we can sign off.

**Comment by gtmills** [comment]
@derick-montague Design is complete for this help, will close when the code is merged.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
