### ISSUE TITLE
Grab PSU device config info from entity manager

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1833]
Ensure entity manager json config files contain appropriate ps i2c bus, address, etc info, and gets populated in DBUS.

In phosphor_psu_monitor grab the info from DBUS to use for config.

Remove https://github.ibm.com/openbmc/phosphor-power/blob/master/phosphor-power-supply/configurations/witherspoon/psu_config.json when the entity-manager stuff is complete.

**Comment by bjwyman** [comment]
If relevant, address I2C parsing from string.
See: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/28851/8/phosphor-power-supply/configurations/witherspoon/psu_config.json#12

**Comment by bjwyman** [comment]
Oh, #1639 comment relevant here as well:
Interface : xyz.openbmc_project.Inventory.Decorator.Compatible
Property : Names

**Comment by bjwyman** [comment]
Should look over updated README: https://github.com/openbmc/entity-manager/blob/master/README.md
(https://github.com/openbmc/entity-manager/commit/1034e026001ceafb64d828622557af25e0fa5a38#diff-04c6e90faac2675aa89e2176d2eec7d8)

**Comment by bjwyman** [comment]
Partially resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/36998

**Comment by bjwyman** [comment]
configurations: Nisqually: use CCIN
https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/37232

configurations: Nisqually: Add additional PS slots
https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/37233

**Comment by bjwyman** [comment]
> Where would one look to find examples of how to actually see and load in this configuration information?
 
dbus-sensors: https://github.com/openbmc/dbus-sensors
phosphor-pid-control: https://github.com/openbmc/phosphor-pid-control

Related example introspect command:
`busctl introspect xyz.openbmc_project.EntityManager /xyz/openbmc_project/inventory/system/chassis/Rainier_2U_Chassis/Compatible_System`

**Comment by bjwyman** [comment]
Noted not using gpio-line-names while doing Everest work.
https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/39586

**Comment by bjwyman** [comment]
Note some debug commands:
```
busctl tree xyz.openbmc_project.EntityManager
busctl introspect xyz.openbmc_project.EntityManager /xyz/openbmc_project/inventory/system/chassis/Rainier_2U_Chassis/Compatible_System
busctl --verbose call xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper xyz.openbmc_project.ObjectMapper GetSubTree sias /xyz/openbmc_project/inventory 0 1 xyz.openbmc_project.Configuration.IBMCFFPSConnector
busctl --verbose call xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper xyz.openbmc_project.ObjectMapper GetSubTreePaths sias /xyz/openbmc_project/inventory 0 1 xyz.openbmc_project.Configuration.IBMCFFPSConnector
busctl get-property xyz.openbmc_project.EntityManager /xyz/openbmc_project/inventory/system/board/Nisqually_Backplane/Power_Supply_Slot_0 xyz.openbmc_project.Configuration.IBMCFFPSConnector I2CBus
busctl get-property xyz.openbmc_project.EntityManager /xyz/openbmc_project/inventory/system/board/Nisqually_Backplane/Power_Supply_Slot_0 xyz.openbmc_project.Configuration.IBMCFFPSConnector I2CAddress
```

**Comment by bjwyman** [comment]
Resolved-by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/41573

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/41636

**Comment by bjwyman** [comment]
https://github.com/openbmc/openbmc/commit/a58e0790ffff73df72e772f0798868cc7ba6ccda
