### ISSUE TITLE
GUI : FED : Update Bootstrap to v4.4.x

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1834]
## As Is
The current version of Bootstrap-Vue is 4.3.x and does not support max width for fluid containers.

## To Be
Set a max width on fluid containers using the Bootstrap-Vue container `fluid="<bp-key>"` for better control over content on large screens. Update the Bootstrap-Vue framework to v4.4.x to support added functionality. This will require some testing, but since the update is a minor release, it `should not` introduce any breaking changes.

**Comment by derick-montague** [comment]
We need to revisit the design on local user management page and server power operations to determine how max-width will be applied.

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31610
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31611

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31611 merged
