### ISSUE TITLE
Retrieve power sequencer device info from entity manager

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1835]
Currently we hardcode the UCD90320 i2c bus/addr in https://github.com/openbmc/meta-ibm/blob/master/meta-witherspoon/recipes-phosphor/power/power-sequencer/rainier/ucd90160.yaml.  
For each system the number, type, and location of the power sequencers may change.

Add the number of sequencers, type of sequencer, and i2c bus and address in an EM config file (eg Nisqually.json).

In the power sequencing app (eg pseq_monitor), get the appropriate data from DBUS.

**Comment by wrightjl1** [comment]
Entity manager repo review: https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/40742
