### ISSUE TITLE
Retrieve power rails/pgoods from entity manager

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1836]
Currently we hardcode the rails and gpi configs in https://github.com/openbmc/meta-ibm/blob/master/meta-witherspoon/recipes-phosphor/power/power-sequencer/rainier/ucd90160.yaml.  For some of the rails, if they fail we may want to shut down the system.  Other rails may just need an error logged, but the system should stay up.
For each system these will change.

In addition, some systems may require 2nd level pgood isolation (eg additional pgoods via an io expander or other device).

Add the rail/pgood info in an EM config file (eg Nisqually.json).

In the power sequencing app (eg pseq_monitor), get the appropriate data from DBUS.

**Comment by wrightjl1** [comment]
First review (add device classes):  https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/42000

**Comment by wrightjl1** [comment]
Second review (Retrieve compatible systems from entity manager): https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/49228

**Comment by wrightjl1** [comment]
Final review (Find and parse configuration file): https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/49484

**Comment by wrightjl1** [comment]
All reviews merged.
