### ISSUE TITLE
Keylock API

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1840]
Some way we can do this in Redfish? 
Part of the Server power operations. 
GUI story #1322

**Comment by mzipse** [comment]
Assigning to @jinuthomas , although details of how this will be defined is not closed.  To be discussed in the Todd's Thurs workshops.

**Comment by mzipse** [comment]
Per feedback from Todd's discussions the Keylock API is not required.  All we need to support is Manual mode and Normal mode API......which is discussed here.... #1068 and possibly here #1977 

@gtmills Based on that, I think we can close this.  Assuming you agree, go ahead and close.

**Comment by gtmills** [comment]
agree. closing
