### ISSUE TITLE
Capacity on Demand (COD) APIs (A new license service?)

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1841]
COD needed on the GUI: Order Info, Activation, Recovery, Command, Processor/Mem Info, Capacity Setting, Virtualization Enablement Technology (VET) Info/Capability Setting

Hoping this will be the license server. We are in discussion now. 
GUI story #1537

**Comment by gtmills** [comment]
https://ibm.box.com/s/6ggkxsb1rn0pc3jay8c6sllhdobrv3oq 
https://ibm.ent.box.com/file/775628653268

**Comment by derick-montague** [comment]
Conversation in the design exchange meeting on 4/6/21:

- Need to get front end interfaces defined first, then plan on back end
- Ratan to schedule meeting to discuss different use cases and proposals
- Gunnar and Ratan to work on this. Gunnar to get on DMTF agenda

**Comment by gtmills** [comment]
@ratagupt Can you update the milestone here?

**Comment by ratagupt** [comment]
@derick-montague @gtmills : Here is the agreed list for the below info, 

- Order Info:

- Processor Info

- Mem Info,

- Virtualization Enablement Technology (VET) Info

```
#1) Machine Type/Model 

/redfish/v1/Systems/system   

#2) Machine Serial 

/redfish/v1/Systems/system   

#3a) Perm Proc Resource ID:  eg  AB41   +   Perm Proc Sequence Number:  eg  0043 

Some field in the Proc license below? Processor license ID:  - Gunnar to further investigate, maybe serialNumber of license(in mockup)?   


#3b) Perm Mem Resource ID:  eg  A212   +   Perm Mem Sequence Number:  eg  0042 

Some field in the Memory license below? Memory license ID: - Gunnar to further investigate  


#3c)  Today we have system-unique Anchor Card Info. This no longer applies. 

Instead we have a ~120 character Public Key  AND ~30 char AP_UniqueID 
```
@gtmills You have some action items above as per the link https://ibm.ent.box.com/file/775628653268?s=qs88rtqutrijrnaqli9vxe10vku5tzl8.

Above can be done once we have a clarity.

- Activation -- Need to define the Redfish API(Mostly it would be OEM  if not published through DMTF).
- CoD Command - Resource Dump Interface.

**Comment by raviteja-b** [comment]
License management design is concluded and implementation started.
@gtmills  seems you have some action items on this story.

**Comment by mzipse** [comment]
This work is now complete.
