### ISSUE TITLE
Remote Console Debug Virtual TTY API/Websocket (2nd host console)?

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1845]
Need some way to get the  Debug Virtual TTY on the GUI. How will we stream to the GUI? 
This is the 2nd host console 

"we are going to route writes to uart#1 to one ssh port and writes to uart #2 to a different ssh port". 
This would be a 2nd web socket the GUI uses to display this 2nd uart. 

https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1588715127390600?thread_ts=1588709628.377800&cid=C0Q6TQP5Z

GUI Story is #1493

**Comment by amboar** [comment]
What is the Debug Virtual TTY?

**Comment by gtmills** [comment]
> Debug Virtual TTY?

year later reply :/  
I took the name from a spreadsheet. 
Debug the virtual teletype.
https://www.ibm.com/support/knowledgecenter/TI0002C/p8hby/debugvirtualtty.htm

This is the websocket work to display the 2nd console on the GUI.

**Comment by ratagupt** [comment]
@amboar : Seems we need to do the piping of the data from obmc-console- to webui..We need to still architect how it needs to be done ...it could be that obmc-console need to provide the unix socket trigger  so that it can start writing on the unix socket.

webGui-(HTTP)--bmcweb ------(Unix Socket)--obmc-console

Why webui can not directly make the ssh connection? seems to me we will be disabling the ssh in the production

**Comment by amboar** [comment]
> Seems we need to do the piping of the data from obmc-console- to webui

We already do this with SOL, so the same solution should apply (just for a different interface).

> it could be that obmc-console need to provide the unix socket trigger so that it can start writing on the unix socket

I don't quite understand what you mean here? What do you mean by 'trigger'?

> Why webui can not directly make the ssh connection? seems to me BMC will be disabling the ssh in the production

Aside from potentially answering your own question here, why would we involve ssh? It's a lot simpler if we don't. Whatever the case, we just do what the SOL stack already does and point it at a different domain socket.

**Comment by gtmills** [comment]
> We already do this with SOL, so the same solution should apply (just for a different interface).

+1

**Comment by patelabhishek9893** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/47105

**Comment by patelabhishek9893** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/47336

**Comment by mzipse** [comment]
Work is complete.  Closing.
