### ISSUE TITLE
Power Management (Power mode settings, Idle Power save) APIs

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1847]
Power Management: Power mode settings (also seen as power policies), Idle Power save
(no tuning parameters for eBMC)

Redfish Bios attribute? These don't require a reboot to change.  Todd said: "These need to be changed on the fly without a re-ipl"

**PowerVM Power mode settings.**
"Power mode settings can be MPM (Maximum Performance mode), DPM (Dynamic Performance mode), Static Power Saver. When all modes are off, you are essentially in Static Nominal -- though it is not a "mode" you can select."

We have on ASM:
Disable all modes
Enable Static Power Saver mode
Enable Dynamic Performance mode
Enable Maximum Performance mode

**Idle Power save**
![idle-power](https://user-images.githubusercontent.com/5455127/81574622-ac511480-936b-11ea-804a-174862a1fce9.png)

GUI issue #1484

**Comment by mzipse** [comment]
@derek, assigning to you.....although it's related to OCC.  My understanding is that we will use BIOS attributes.  So no redfish changes required.  May need to work with Deepak on this, as he is familiar with our BIOS settings for other stuff.

**Comment by derekhoward55** [comment]
I think Martha will really own this code so will assign to her, but feel free to send back to me if appropriate.

**Comment by gtmills** [comment]
@tomjoseph83 Are you planning on Power mode settings being a BIOS attribute #1977 ?

**Comment by gtmills** [comment]
@marthabroyles Do you know what the API will be for Idle Power save ?
Will we have the same fields we have in ASMi for eBMC ?

**Comment by marthabroyles** [comment]
> 
> 
> @marthabroyles Do you know what the API will be for Idle Power save ?
> Will we have the same fields we have in ASMi for eBMC ?

Yes all exact same fields.

**Comment by gtmills** [comment]
Redfish issues are: https://github.com/DMTF/Redfish/issues/4385 and https://github.com/DMTF/Redfish/issues/4386

**Comment by derick-montague** [comment]
Is this story completed by : https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43761

**Comment by gtmills** [comment]
> Power policies is resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43761. Is that right? 

Yes, but power idle save isn't out yet

**Comment by gtmills** [comment]
This is complete. Closing.

**Comment by cjcain** [comment]
FYI, Idle Power Saver support added with:https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/47776
