### ISSUE TITLE
Enable ecmd-pdbg in meta-openpower (upstream)

### ISSUE THREAD

**Issue by lkammath** [ibm-openbmc/dev#1849]
This story scope is following

1. Change the ecmd-pdbg - https://github.com/open-power/ecmd-pdbg recipe to use libecmd and dependent libs built as part of #1848 (This avoids pulling the ecmd via submodule approach and help offline build)
2. Subsequently, remove the ecmd/libecmd and other dependent module build process from ecmd-pdbg meson build

**Comment by lkammath** [comment]
In progress

**Comment by rfrandse** [comment]
tracking in jira
