### ISSUE TITLE
GUI: Update User Mgmt 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#185]
## Due Dates
- [ ] UX: 3/20/19
- [x] Backend
- [ ] FED: 7/11/19

## Team
**SME**: Ed Tanous / Apoo Puli  (Intel)
**DR**: @nicoleconser 
**UX**: TBD
**FED**: TBD (Intel)?

## Use Case
* System Admin should be able to manage the users that can locally access the host/BMC in a way that is consistent with the rest of the GUI.
* Local User Account Mgmt would be the add/change/delete of users and passwords

### Password Error Instances
* In-field validations:
* Current password: "Invalid password entry."
* New password: "Entry should not match current password."
* Retype new password: "Passwords do not match."
* Empty field validation
* Modal for error (back-end) setting password.
* Iterations to the "Show" and "Hide" interactions (relocated outside of text field and 20px right of it).
*Notifications: will inform user when settings saved successfully or failed (GUI will not save input fields with errors)

## InVision Prototype
https://ibm.invisionapp.com/share/4XNZ0JAMJ7B#/319147576_6-4-1_Regular

## Design Issue
https://github.com/openbmc/phosphor-webui/issues/48

## Resources
Discovery & design notes: https://ibm.ent.box.com/notes/466301996553

## Development Issues
*  Password Errors: https://github.com/ibm-openbmc/dev/issues/180
* Back-end Gerrit Review: https://gerrit.openbmc-project.xyz/#/c/10112/

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
This tracks the FED work for https://github.com/openbmc/phosphor-webui/issues/48

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/dev/issues/1040 is the FED work
