### ISSUE TITLE
GUI : Research : Virtual TPM

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1854]
## SMEs
**BMC**: @tomjoseph83 
**PHYP**: Chris Engle
**ASMI**: Jayashankar Padath
**RAS**: George Ahrens

### Background
It is expected this this might be included in the Server power operations page, but that is an assumption that needs to be validated. This is a BIOS setting that should be available by EOY 2020. There is a fair amount of information about the requirement for this in the feature discovery document. 

### End users
- [ ]  TBD

### User Needs
- [ ] TBD

### User Quotes
- [ ] TBD

## User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

## References/Resources
- [eBMC Feature Item: 4.13.1](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)
- feature discovery folder: [Virtual Trusted Platform Module](https://ibm.box.com/s/fbit9bhwgcqghsivw7qxn8hl33ok43xp)
- user research notes*: 
- user research synthesis: 

* This folder is restricted in accordance with GDPR guidelines.

**Comment by derick-montague** [comment]
Slack discussion: https://ibm-systems-power.slack.com/archives/GKXDFTLFJ/p1583254235004800

**Comment by derick-montague** [comment]
@ParishrutB - We can discuss in sprint planning, but this is a Sprint +1 candidate and may need to be bundled with #973's user research efforts.

**Comment by priyanka-pillai97** [comment]
- TPM affects the security of host boot process. It is a setting which is set once and then not changed frequently.

- VTPM (Virtual TPM) is not related to host boot process. It affects the security of logical partitions. It is a setting which is set once and then not changed frequently.

Validated by Nick B (Hostboot) - Understanding is correct; TPM covers boot firmware, vTPM covers logical partitions.

FYI @nicoleconser

**Comment by ParishrutB** [comment]
[Detailed discussion](https://ibm-systems.slack.com/archives/G01JLPJKVG9/p1611844815008500) on the above hypothesis:

From Pete Heyrman, via Lael Daire, 
"virtual TPM is software that is able to emulate functions of a TPM device. A VM can be assigned a virtual TPM which includes some amount of storage that is available for the VM to use for there purposes. It also includes algorithms that can do functions like encryption/compression. The physical TPM is controlled by PHYP and is used for functions like secure boot, LPM encryption, the new KeyStore support for holding OS keys and such."

"A single partition, stand-alone server would use just the TPM." 

"The settings are still required.  The settings only dictate whether TPM is required to boot or not, it does not disable TPM.  For HMC managed systems, the vTPM option in ASMI setting is not enabled (not able to change via ASMI)."

"sometimes we get systems without a physical TPM module and it has to be disabled in the FW to be able to boot - sometimes there are OS changes that require it to be disabled as well - not advisable in general though"

**Comment by nicoleconser** [comment]
**Takeaways from Joe Mulholland —** via [Slack conversation](https://ibm-systems-power.slack.com/archives/GQ8H06RC5/p1611937895004700) 

- vTPM is for Operating Systems, because they are not allowed to have access to TPM
- Whether you have 1 or 20 OS’s, you need to be able to vTPM 
- An LPAR is just an OS with part of the resources of the system
- TPM protects the hypervisor and each ‘LPAR’ can also have a vTPM to protect it — or more specifically, each instance of an operating system can have a vTPM to protect it

**Overall:** **_TPM exists to secure the hypervisor in the same way that vTPM exists to secure the OS boot_**

**Comment by nicoleconser** [comment]
Closed since we are assuming this will live on #1273 Security Panel
