### ISSUE TITLE
phosphor-regulators: Find config file and use parser

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#1855]
This issue will connect several features that are being implemented in other issues:
* 1312: phosphor-regulators: Implement config file parser
* 1474: phosphor-regulators: Obtain config file name from D-Bus

The following enhancements are needed for this issue:
* Search for config file name in test directory and then in standard directory
* Call config file parser
* Store resulting lists of rule and chassis objects
* Handle config file parser errors (write to journal, log error, etc.)

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/31879

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/31879 merged
