### ISSUE TITLE
PLDM host soft off : Send a set effecter to host to trigger host soft off

### ISSUE THREAD

**Issue by ChicagoDuan** [ibm-openbmc/dev#1856]
Currently phosphor-softpoweroff is too tied up to IPMI. Hence it's probably better to write a new PLDM requester application. The application first needs to send a PLDM request message to set a state effecter on the host, then the host will soft off.

**Comment by lxwinspur** [comment]
merged by:
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/31507
