### ISSUE TITLE
PLDM host soft off : Wait the host soft off responds and set chassis off

### ISSUE THREAD

**Issue by ChicagoDuan** [ibm-openbmc/dev#1859]
When the app starts the timer, it needs to wait for the response event of host. If the response event is received and there is no timeout, it will stop the timer and chassis off .If the timeout occurs, record an error log,  chassis off, and stop the timer.

**Comment by lxwinspur** [comment]
merged by:
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/31507
