### ISSUE TITLE
GUI: User/Group permissions 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#186]
User/Group permissions defines roles (and possibly customizations) as to what BMC functions each user/role has permission to execute.

**Comment by alissaylee** [comment]
https://ibm.invisionapp.com/share/7FNYCEZHU6B#/318878222_LDAP_Manage_Groups
**Managing Role Groups**
- Add, Modify or Delete role groups*
*Role groups that have a group name and privilege assigned can only be deleted (this is currently how AMI and SM appear to do it).

https://ibm.invisionapp.com/share/7FNYCEZHU6B#/318878216_LDAP_Add_Role_Group
https://ibm.invisionapp.com/share/7FNYCEZHU6B#/318878215_LDAP_Modify_Role_Group
**Adding/Modifying Role Group**
Field: Group Name
Value: text string

Field: Group Privilege
Dropdown (4 options): Admin, operator, user, no access 

- Actions to "Add group" / "Save changes" or "Close" out of modal.
-----------------------------------------------------------------------------------------
https://ibm.invisionapp.com/share/7FNYCEZHU6B#/318878214_LDAP_Delete_Role_Group
**Deleting Role Group**
Modal message: "Are you sure you want to delete role group <name>?"
- Actions to "Continue" or "Cancel" out of modal.
- User will receive toast notification indicating successful role group delete.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
