### ISSUE TITLE
Auto-Power Restart support

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1860]
APR if "always on" mode selected once AC returns.  Need AC returned to all drawers, don't want to thrash?  Hold off boot if UPS battery low or still experiencing utility failure.

Persist system state to read post-blackout. 

Notifications to state management as appropriate, eg requests from Vishwa:

1/. Black-out: AC is lost. BMC comes back on and reaches Ready.

Power app can see it's a blackout and indicates the blackout case as part of some D-Bus property.
Power app will then ask for a power off operation.
APOR daemon can hook onto this property to see if that is the case and Arm the APOR.

Note: Power app needs to know why BMC is booting. If it's booting because its POR is triggered / or is it coming from a reboot
This is needed because we don't want to arm the APOR if someone did something like smgr toolReset / PHR intentionally.

Power app can check what was the system power state. However, checking that alone will not help. It needs to be in conjunction with why BMC is booting in order to arm APOR.

Add: Power app will clear blackout D-Bus property when things restore / part of IPL.

Action : Vishwa : See how can boot reason be provided / any alternatives.

```
```

2/. Brown-out:  BMC is up and running and there are power glitches that result in loosing cec logic power

Power app can detect this condition and will call for Power off.
Power app can present this information as part of a D-Bus property
APOR daemon can hook onto this property to see if that is the case and Arm the APOR

Add: Power app will clear brownout D-Bus property when things restore / part of IPL.

```
```

3/. Quick Power off:  When the UPS is critically low, an EPOW is sent upwards.

Partitions can indicate that they need to be powered-on as soon as possible. PHYP will then send a Quick Power off request if so.
If no partition is interested to be powered on, PHYP will do normal power-off and APOR should not be armed.

Implementation: PHYP would send a PLDM command indicating a quick power off.
APOR daemon need to somehow use the information that is being sent part of PLDM and Arm the APOR.

Details of implementation can be later..

```
```

4/. Power app will aggregate UPS battery condition + power supply readiness and present this as a D-Bus property.

IPL systemd target should look into this before moving ahead with IPL.
Doing so for any type of IPL makes it more consistent and would save a IPL if the battery was critically low.

Need minimum off delay at beginning of pup sequence to avoid brownout/blackout thrashing.

**Comment by vishwabmc** [comment]
Hi @derekhoward55 thanks for putting it.  We already have https://github.com/ibm-openbmc/dev/issues/870 for this.. As you posted these minutes here, I will close the old one and use this one..

**Comment by derekhoward55** [comment]
ok, note that I didn't copy all of the minutes, just the items that impacted my team.  thanks.

**Comment by geissonator** [comment]
Adjusted from 26 to 10 to track APOR daemon work. @derekhoward55 please be sure you have your portion of this covered elsewhere.

**Comment by geissonator** [comment]
Sorry, lets keep this one for Derek and we'll go back to ours for SMGR work.

**Comment by bjwyman** [comment]
@anoo1 indicated this should essentially be complete after: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/48015

**Comment by bjwyman** [comment]
> @anoo1 indicated this should essentially be complete after: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/48015

That did get merged: https://github.com/openbmc/docs/commit/e67c779ec815d204ae7d9f07da3f533f6aab8364

**Comment by bjwyman** [comment]
This goes with that: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/52283
