### ISSUE TITLE
PSU input fault full function

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1862]
Monitor power supplies for input power faults. Latched vs dynamic AC loss handling. 900W&1400W PS have flaky voltage value reporting.

If main pgood (12v bulk) goes down and any PS reporting AC loss, log 110000AC, and let the pgood monitoring code initiate the system power off.

Deglitch&ignore temporary voltage dips as long as power is good. unlatch vin faults.

If subset of PS lose AC but power remains good, log error against each PS.

If all present PS report input power fault, try to stay up or do orderly shutdown? Try to stay up. No guarantee 12bulk goes down before 12sb. Hw does guarantee 12vbulk fault is reported before it goes down.  Let pgood monitoring code initiate shutdown if the pgoods are faulted.

Ensure pgood hw design appropriate - pgoods flagged before chip errors, etc​.

Ensure dual line cord testing handled.

**Comment by bjwyman** [comment]
- [x] Monitor power supplies for input power faults.
    - https://github.com/openbmc/phosphor-power/commit/3f1242f3a147ee372d1e5c7274cb1db69d626b34
    - https://github.com/openbmc/phosphor-power/commit/b76ab2497e1010c238035b642bfa2123aad66bdf
    - https://github.com/openbmc/phosphor-power/commit/e3b0bb01dc4cf77486510eec2780ed2adf14aad0
- [x] Latched vs dynamic AC loss handling. 
  - 900W & 1400W PS have flaky voltage value reporting.
  - [x] Need to reset counter if see VIN_UV fault set, but READ_VIN returns non-zero voltage.
    - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/51899
    - https://github.com/openbmc/phosphor-power/commit/4fc191f0be23810cb9558661c635bff6b322776d
    - https://github.com/openbmc/phosphor-power/commit/3225a45cc45106f2a91d82a6718f251b00338d4d
  - [x] Trace if READ_VIN good but VIN_UV set
    - Tracing in: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/51899
  - [x] Kernel patch: [PATCH] hwmon: (pmbus) Add Vin unit off handling - Applied 2022/03/18 00:32
    - https://lore.kernel.org/openbmc/20220318053149.GA3333429@roeck-us.net/T/#t
    - https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/commit/?h=hwmon-next
    - https://github.com/openbmc/linux/commit/6f7b3b6368f95822756e280ce0d01ef4bbf49294
    - https://github.com/openbmc/linux/commit/e7265ec49718d7f22c7555c809763771db5db323
    - Downstream has patch merged.
  - [x] Kernel patch for clear_faults debugfs: **Rejected (not applied)**
    - V2 http://patchwork.ozlabs.org/project/openbmc/patch/20220311181014.3448936-1-bjwyman@gmail.com/
      - http://patchwork.ozlabs.org/project/openbmc/patch/20220311001858.4166205-1-bjwyman@gmail.com/
      - https://lore.kernel.org/openbmc/20220311001858.4166205-1-bjwyman@gmail.com/T/#u
      - https://lore.kernel.org/linux-hwmon/20220311001858.4166205-1-bjwyman@gmail.com/T/#u
  - [x] Actually send CLEAR_FAULTS: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/51900
- [x] If main pgood (12v bulk) goes down and any PS reporting AC loss, 
	- log 110000AC, and let the pgood monitoring code initiate the system power off.
	- This is not exactly the brownout logging.
	- PSU monitor uses setPowerSupplyError after https://github.com/ibm-openbmc/dev/issues/1617
	- Power sequencer would log 110015F0 or 110000AC (brownout).
- [x] Deglitch & ignore temporary voltage dips as long as power is good.
    - https://github.com/openbmc/phosphor-power/commit/c2906f471f3ecb4fe021efc657a32c4266a88589
- [x] Unlatch vin faults.
    - Is there a way to confirm a CLEAR_FAULTS was actually sent? 
    - There is with this: http://patchwork.ozlabs.org/project/openbmc/patch/20220311001858.4166205-1-bjwyman@gmail.com/
- [x] If subset of PS lose AC but power remains good, log error against each PS.
    - This is how it already behaves.
- [x] Try to stay up if all present PS report input power fault.
	- Power supply monitor does not issue shut down if all present PSU report input power fault.
	- The pgood monitoring code will initiate shutdown if the pgoods are faulted, PSU error used if set: https://github.com/ibm-openbmc/dev/issues/1617
- [x] Ensure pgood hw design appropriate - pgoods flagged before chip errors, etc​.
    - https://github.com/ibm-openbmc/dev/issues/1617
- [x] Ensure dual line cord testing handled.
    1. Power system/chassis on.
    2. Remove AC from half the power supplies.
    3. Wait about 10 seconds.
    4. Re-apply power to the power supplies that had AC removed.
    5. Wait about 10 seconds. (first half power supplies should be on and holding system up).
    6. Remove AC from second half of the power supplies.
    7. Ensure system stays up (first half still holding up, not terminating due to brownout, etc.).
    8. Ensure new errors calling out second half power supplies (not first half that are back up).
    - Rainier 2S4U tested. E2/E3 drop, wait, E2/E3 good, wait, E0/E1 drop...system stayed up.
    - Rainier 2S2U tested. E1 down 10 seconds, up 10 seconds, E0 down 10 seconds, up 10 seconds. System stayed up.

**Comment by bjwyman** [comment]
```
Mar 04 01:34:13 rainier2s2u phosphor-psu-monitor[550]: INPUT fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:13 rainier2s2u phosphor-psu-monitor[550]: PGOOD fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0
Mar 04 01:34:13 rainier2s2u phosphor-psu-monitor[550]: VIN_UV fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:14 rainier2s2u phosphor-psu-monitor[550]: INPUT fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:14 rainier2s2u phosphor-psu-monitor[550]: PGOOD fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0
Mar 04 01:34:14 rainier2s2u phosphor-psu-monitor[550]: VIN_UV fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:15 rainier2s2u phosphor-psu-monitor[550]: INPUT fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:15 rainier2s2u phosphor-psu-monitor[550]: PGOOD fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0
Mar 04 01:34:15 rainier2s2u phosphor-psu-monitor[550]: VIN_UV fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:15 rainier2s2u ibm-panel[1066]: PEL entry not yet created, Ignoring the signal
Mar 04 01:34:15 rainier2s2u phosphor-log-manager[315]: Created PEL 0x50000f2c (BMC ID 7) with SRC 110015F0
Mar 04 01:34:15 rainier2s2u phosphor-ledmanager[490]: SAI: FRU path: /xyz/openbmc_project/inventory/system
Mar 04 01:34:15 rainier2s2u pldmd[1588]: Failed to decode_platform_event_message_resp: rc=0, cc=1
Mar 04 01:34:15 rainier2s2u phosphor-power-control[305]: callbackSetPowerSupplyError: xyz.openbmc_project.Power.PowerSupply.Error.InputFault
Mar 04 01:34:15 rainier2s2u ibm-panel[1066]: PEL entry not yet created, Ignoring the signal
Mar 04 01:34:26 rainier2s2u phosphor-psu-monitor[550]: INPUT fault cleared: STATUS_WORD = 0x840, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x0
Mar 04 01:34:26 rainier2s2u phosphor-psu-monitor[550]: VIN_UV fault cleared: STATUS_WORD = 0x840, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x0
Mar 04 01:34:26 rainier2s2u phosphor-psu-monitor[550]: READ_VIN back in range: inputVoltageOld = 0 inputVoltage = 220
Mar 04 01:34:27 rainier2s2u phosphor-psu-monitor[550]: PGOOD fault: STATUS_WORD = 0x840, STATUS_MFR_SPECIFIC = 0x0
Mar 04 01:34:28 rainier2s2u phosphor-psu-monitor[550]: PGOOD fault: STATUS_WORD = 0x800, STATUS_MFR_SPECIFIC = 0x0
Mar 04 01:34:29 rainier2s2u phosphor-psu-monitor[550]: pgoodFault cleared path: /xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply1
Mar 04 01:34:39 rainier2s2u phosphor-psu-monitor[550]: INPUT fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:39 rainier2s2u phosphor-psu-monitor[550]: PGOOD fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0
Mar 04 01:34:39 rainier2s2u phosphor-psu-monitor[550]: VIN_UV fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:40 rainier2s2u phosphor-psu-monitor[550]: INPUT fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:40 rainier2s2u phosphor-psu-monitor[550]: PGOOD fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0
Mar 04 01:34:40 rainier2s2u phosphor-psu-monitor[550]: VIN_UV fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:41 rainier2s2u phosphor-psu-monitor[550]: INPUT fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:41 rainier2s2u phosphor-psu-monitor[550]: PGOOD fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0
Mar 04 01:34:41 rainier2s2u phosphor-psu-monitor[550]: VIN_UV fault: STATUS_WORD = 0x2848, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x18
Mar 04 01:34:41 rainier2s2u ibm-panel[1066]: PEL entry not yet created, Ignoring the signal
Mar 04 01:34:41 rainier2s2u phosphor-log-manager[315]: Created PEL 0x50000f2d (BMC ID 9) with SRC 110015F0
Mar 04 01:34:41 rainier2s2u phosphor-power-control[305]: callbackSetPowerSupplyError: xyz.openbmc_project.Power.PowerSupply.Error.InputFault
Mar 04 01:34:53 rainier2s2u phosphor-psu-monitor[550]: INPUT fault cleared: STATUS_WORD = 0x840, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x0
Mar 04 01:34:53 rainier2s2u phosphor-psu-monitor[550]: VIN_UV fault cleared: STATUS_WORD = 0x840, STATUS_MFR_SPECIFIC = 0x0, STATUS_INPUT = 0x0
Mar 04 01:34:53 rainier2s2u phosphor-psu-monitor[550]: READ_VIN back in range: inputVoltageOld = 0 inputVoltage = 220
Mar 04 01:34:54 rainier2s2u phosphor-psu-monitor[550]: PGOOD fault: STATUS_WORD = 0x840, STATUS_MFR_SPECIFIC = 0x0
Mar 04 01:34:55 rainier2s2u phosphor-psu-monitor[550]: PGOOD fault: STATUS_WORD = 0x800, STATUS_MFR_SPECIFIC = 0x0
Mar 04 01:34:56 rainier2s2u phosphor-psu-monitor[550]: pgoodFault cleared path: /xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply0
```
Spare part number (FRU number): 03FP378
Model (CCIN): 51E9
Firmware version: 393141313831

**Comment by bjwyman** [comment]
SRCREV bump: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/52241

**Comment by bjwyman** [comment]
https://github.com/openbmc/openbmc/commit/23b4bb87e4754490acfc26a65312d0feb8767a2a
