### ISSUE TITLE
Full Function interface to PHYP

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1863]
Individual PLDM State Sets previously implemented (eg UPS and EPOWs), full support for PHYP interface with this story.

Confirm Platform Event message sent when ps or fan removed or added:
When a power/thermal FRU is replaced at runtime, the BMC will notify PHYP when the FRU has been removed, and when the vpd collection has completed after it is re-installed.

1. FRU is removed via hot-swap or ccm operation.
2. BMC sends PDR repository changed event message when the FRU is removed.
3. PHYP sends GetFRURecordTable, BMC returns all vpd in response.   BMC no longer clears the Configuration Change Alert (CCA) condition in the node.

When fru added back in.

1. New FRU is added.
2. BMC sends PDR repository changed event message (after the new FRUs vpd is collected?).
3. PHYP sends GetFRURecordTable, BMC returns all vpd in response.  BMC no longer clears the Configuration Change Alert (CCA) condition in the node.

Ensure other state sets set/cleared appropriately, eg:
UPS status and thermal_fault.

Config ID from EM as documented in https://github.com/ibm-openbmc/dev/issues/1751.

See eBMC Host Interferace Arch for status definition.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derekhoward55** [comment]
EPOW full support moved to https://github.com/ibm-openbmc/dev/issues/585.
UPS support tracked with https://github.com/ibm-openbmc/dev/issues/571.

Closing this one out.
