### ISSUE TITLE
GUI : FED : Responsive Site Header

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1864]
## Overview
Update application header to accommodate smaller viewport width.

## UX Flow/ Interaction requirements
- [ ] Medium BP stacks status icons, refresh, and user info to second header row
- [ ] Small BP hides **Refresh** and **username** text and only shows icons
- [ ] Mobile slide-out navigation will be in the same Y-axis position (beneath top level header)

## Screenshots
Medium BP
![01_Responsive_Header_Layout_01@2x Copy 4](https://user-images.githubusercontent.com/8097306/82236138-8508c300-98e8-11ea-8357-aea166023b19.jpg)

Small BP
![01_Responsive_Header_Layout_01@2x Copy 6](https://user-images.githubusercontent.com/8097306/82236158-8d60fe00-98e8-11ea-94bd-3664f0a98744.jpg)

Small BP with navigation open
![01_Responsive_Header_Layout_01@2x Copy 14](https://user-images.githubusercontent.com/8097306/82235747-fe53e600-98e7-11ea-91a1-ec2e872d10de.jpg)

Currently in Vue

![Screen Shot 2020-05-18 at 9 16 01 AM](https://user-images.githubusercontent.com/8097306/82235922-36f3bf80-98e8-11ea-9904-a66626ae7101.png)

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33361

**Comment by SurenNeware** [comment]
Small BP
![Screenshot_2020-06-23-18-25-32-105_com android chrome](https://user-images.githubusercontent.com/42602609/85406249-24237900-b57f-11ea-9b27-fd8e3fac96f8.png)

**Comment by ParishrutB** [comment]
![image](https://user-images.githubusercontent.com/61419136/85407014-410c7c00-b580-11ea-89e3-20db435251d4.png)

**Comment by SurenNeware** [comment]
Thank you so much!
 
----- Original message -----From: ParishrutB <notifications@github.com>To: ibm-openbmc/dev <dev@noreply.github.com>Cc: Suren Neware <sneware9@in.ibm.com>, Assign <assign@noreply.github.com>Subject: [EXTERNAL] Re: [ibm-openbmc/dev] GUI : FED : Responsive Site Header (#1864)Date: Tue, Jun 23, 2020 6:53 PM
