### ISSUE TITLE
Make Python Optional in OpenBMC

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#187]
A high level epic to track all remaining work to remove python from required OpenBMC applications so that we can make the incorporation of python into an OpenBMC image optional.

https://github.com/openbmc/skeleton/issues/136 (obmcutil)

@spinler and @anoo1 I think just about have these out:
chassis_control.py
system_manager.py

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
There is no longer any python in master... closing.

**Comment by rfrandse** [comment]
refresh
