### ISSUE TITLE
PFP - Create tool for setting/displaying fan info

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1870]
Create cmd line interface for getting fan status (loc code, presence, fault, rpm).  Include PRS and "powr fan getrpm/setrpm" replacement.  Allow fan speed setting for individual fans or all fans in a cooling zone.

Per Matt some of this can be collected manually with currently available cmds such as busctl, systemctl, and other standard linux cmds available.

Will probably be worth rolling up into easy to use tool for thermal team, test teams, PE, etc.

**Comment by msbarth** [comment]
An initial tool has been made available

https://github.ibm.com/msbarth/tools/tree/master/OpenBMC/fanctl

When time permits, this could be cleaned up/enhanced so it can be upstreamed under this issue.

**Comment by msbarth** [comment]
Mimic the functionality of the `fansctl` bash script downstream into a C++ application that will be installed into the BMC image when phosphor-fan-control is also included in the image. The use of `busctl` commands within the bash script should be replaced with the appropriate dbus method calls using functions from sdbusplus.hpp.

It is recommended to attempt to keep the same output formatting that the bash script presents for commands echo'ing output to the BMC console unless a better/clearer output can be presented for the same commands. Investigation will be needed to determine the best way to stop/start systemd services (i.e. phosphor-fan-control@0.service) from C++ code without using the `systemctl` tool.
