### ISSUE TITLE
USB Code Update: Add hotplug support

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#1874]
Add support for the BMC to recognize when a USB device is inserted.

**Comment by joseph-reynolds** [comment]
The BMC should write a security audit record when a USB device is inserted or removed.

**Comment by joseph-reynolds** [comment]
Does this story cover starting the systemd service and loading the BMC device driver?  I want to understand how this will work with disabling the BMC-attached USB interface: https://github.com/ibm-openbmc/dev/issues/1793
For example, if security vulnerability is found in the USB driver itself, we'll want a function to unload the USB driver, and not merely stop the code update service.

**Comment by anoo1** [comment]
When a USB key is inserted, the kernel exposes it as a device in /dev/sdX (such as /dev/sda). Need a service that would be triggered when this hotplug event happens so that it can mount the usb device /dev/sdX to a temporary directory such as /media/usb/. We may need some guidance from @eddiejames

**Comment by anoo1** [comment]
Merged upstream: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/48236/
