### ISSUE TITLE
GUARD: Libarary base infrastuctre support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1880]
- Create new guard repository
    - Provide base build/test  infrastructure 
    - Provide base command line  base infrastructure ( help support).

**Comment by devenrao** [comment]
Base infrasturucte support is added here
https://github.ibm.com/devenrao/guard

[devenrao]$ ninja -C build test
ninja: Entering directory `build'
[0/1] Running all tests.

**Comment by devenrao** [comment]
1) Add base infrastructure that caters for LICENCES file and README
2) Add c, c++ language format files
3) Use meson build system as the same is being the new standard to follow
4) Add sub directories for guard library, flash and test

**Comment by ojayanth** [comment]
https://github.ibm.com/open-power/guard/pull/2
