### ISSUE TITLE
Op-Panel Base infrastructure design and coding for BMC

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/dev#1882]
This is to define and create the base infrastructure for the Panel component on BMC

This includes the below stories
	- panel app design
	- panel app base framework implementation 
	- panel function states support 
	- Debounce functionality for functions
	- progress code / lcd display support

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
