### ISSUE TITLE
Op-Panel functions support for display only

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/dev#1891]
This EPIC is to code the display type functions used in the Panel . 
This would contain the below stories
	-  Function Nos. 1 - PHYP via PLDM (probably in DBUS IPLP params)
	-  Function Nos. 11,12,13,14,15,16,17,18,19 - Errl
	-  Function Nos. 20 VPD (probably in DBUS)
	-  Function Nos. 30 check GUI backend for addr and dbus for location

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
