### ISSUE TITLE
Op-Panel functions support for input only

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/dev#1894]
This EPIC is to code the input type functions used in the Panel .
This would contain the below stories
	-  Nos. 2 PHYP via PLDM (probably in DBUS or notification to PHYP)
	-  Nos. 55 <0x01 - 0x0D> - DUMP / PHYP(pldm)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jinuthomas** [comment]
Input functions merging is done
