### ISSUE TITLE
Design and implement openBMC REST API to Activate digitally signed certificates

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#19]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ojayanth](https://github.com/ojayanth)**
_Thursday Aug 02, 2018 at 10:58 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3342_

----

Provide REST interface to activate the new certificate.
     Activation includes validation of the certificate with private key, validity check and restarting the required cerise for the successfully validated certificate.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Support is already available in master. alsi Original issue is already in closed state
