### ISSUE TITLE
Op-Panel functions support for trigger only

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/dev#1903]
This EPIC is to code the trigger type functions used in the Panel .
This would contain the below stories
 	-  Function Nos. 3 - State-manager
 	-  Function Nos. 4 - PANL and LEDS
 	-  Function Nos. 8 - (Button FPO)
	-  Function Nos. 21,22,34,41 - PHYP (via PLDM)
	-  Function Nos. 25,26 - PANL
	-  Function Nos. 42 - DUMP	
	-  Function Nos. 43 - DUMP	
	-  Function Nos. 65,66,67,68,69,70 - PHYP (via pldm)
	-  Function Nos. 73 - Factory Reset
	-  Function Nos. 74 - CE login

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
