### ISSUE TITLE
Op-Panel command line tool for BMC

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/dev#1908]
This is to develop a command line tool to test all the function numbers without the interaction from the physical panel. this would help to test each functionality in the BMC side and on simics before we start on the hardware.
This contains the below tasks:
	- Base infrastructure coding and testing
	- functionality coding and testing - display only functions
	- functionality coding and testing - input only functions
	- functionality coding and testing - trigger only functions

**Comment by mzipse** [comment]
Note this work is for development purposes only.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
