### ISSUE TITLE
Get rid of chassis_control.py for button handling

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#191]
All that does is listen for button presses.

We could do something like:

- Use phosphor-buttons to watch for button presses and send signals
- have the chasssis state manager listen for those signals and do the state changes appropriately

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
this has been done for some time for wspoon
