### ISSUE TITLE
Op-Panel and BMC communication protocol design and coding

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/dev#1911]
This epic will enable the communication between the BMC and the panel micro , this will contain both the two and fro communication , where BMC will act as a master and also a slave as needed and the panel will do the alternate too.
The below are the two stories to be worked for this.
	- I2C - communication BMC as master and LCD Panel as slave in BMC
	- I2C - communication BMC as slave and LCD Panel as master in BMC

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jinuthomas** [comment]
moving the stories to 2Q 2021

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
