### ISSUE TITLE
Op-Panel Hot-Plug support

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/dev#1913]
This will enable the panel hot-plugging feature , basically the panel can be plugged in at any time or removed at any time. This will further take care if setting the I2C buffer also.
The work to be done via below story:
	- Support hot plug - in and hot plug out (including i2c buffer)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jinuthomas** [comment]
Has been merged and VPD changes also in for rainier
