### ISSUE TITLE
Op-Panel Documentation

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/dev#1916]
This is to create the HLD, LLD, Panel_Operations_Spec Micro_controller_protocol_spec , get the Knowledge-centre updated and also the SRC

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
