### ISSUE TITLE
Witherspoon: Add device driver support for IR38063 VRM for hwmon

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#192]
On Witherspoon, the VIO and VPP regulators are IR38063 (and 64) devices.  The HW team would like us to have temp/current/voltage/power sensors for them like we do for the other VRM, the IR35221.

I didn't see anything obvious that could be used as a device driver for them.  Not sure if there is a generic one or not.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
