### ISSUE TITLE
PLDM based host progress codes

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1920]
Host firmware sends down progress codes. The BMC will have to relay the same using Redfish BIOS POST codes. One option is to leverage the https://github.com/openbmc/phosphor-post-code-manager . On IBM enterprise systems the progress code can be 4 byte numbers,  sequence larger than 4 bytes or strings. So the phosphor-code-manager needs to be extended to achieve the IBM requirements.

**Comment by gtmills** [comment]
Does this include mapping the PLDM sensor to the Boot Progress D-Bus interface ? 
https://github.com/openbmc/phosphor-dbus-interfaces/blob/05375b14e5a68ac249da6a8cd68e3d522a7ed022/xyz/openbmc_project/State/Boot/Progress.interface.yaml

So then https://github.com/ibm-openbmc/dev/issues/2355 can look at the boot progress D-Bus interface ?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by manojkiraneda** [comment]
The code is merged downstream & available in tag-19

**Comment by gtmills** [comment]
@manojkiraneda Do we need to track anything to get this upstream?
