### ISSUE TITLE
eBMC LED Management :: Make existing phosphor-led-manager work on eBMC 

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1922]
Work involved :

- LED group definition in MRW
- Any changes in the parser to consume updates
- Working with system Engineer to get LEDs defined for FRU in MRW
- Moving from YAML to JSON for LED group definition file
- Moving from compile time parsing to runtime JSON consumption
- All the LED groups represented as DBus objects
- Make sure the mandatory groups are existing ( "BmcBooted and PowerOn" )
- All GTEST cases covered

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
DONE
