### ISSUE TITLE
eBMC LED Management :: Validate all the Physical LEDs are working

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1923]
`phosphor-led-sysfs` represents all the physical LEDs in the system. 

Work involved :

- Validate all the drive-able physical LEDs in the system are represented in D-Bus. these Include:
  - Processor
  - Memory
  - System Attention Indicator
  - Enclosure ID and Fault
  - Fan
  - PCIe slots
  - Power Supply

- Add GTEST for the new LEDs represented

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by slylinux** [comment]
Hi vishawa, this epic are hardware related,if we test on our 5280 machine ,the code may be modified for IBM machines , so we should support a framework to adapt to different machines? or just make the code machine specific?

**Comment by vishwabmc** [comment]
> Hi vishawa, this epic are hardware related,if we test on our 5280 machine ,the code may be modified for IBM machines , so we should support a framework to adapt to different machines? or just make the code machine specific?

Hi @slylinux Sorry I did not notice.. Thank you, but this is Machine specific only and hence the changes done to 5280 won't work here.. We already have the framework that is in place.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
All the dts changes merged.. However, a supporting change in leds-gpio is not merged yet. Once that is done, it can be closed

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
This is now DONE
