### ISSUE TITLE
eBMC LED Management :: Create JSON and also YAML from MRW

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1926]
Current led-manager does :

- Parse MRW and create YAML
- Generate led-gen.hpp at compile time and bake into the image
- Create D-Bus objects for Groups based on definition 

--------------------

As part of this story, we need: 

-  Parse MRW and create JSON
- Work with system Engineer if LEDs are missing in MRW

**Comment by lxwinspur** [comment]
review:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-mrw-tools/+/31391

**Comment by vishwabmc** [comment]
Looks like, there are some parser changes needed in the new system and hence would like to break this story into 2.

1/. This story will create JSON based on the parsed output.
2/. Another story to make updates to the parser and then create the parsed output. It can then use #1 above to create JSON.
