### ISSUE TITLE
eBMC LED Management :: Update led-manager to use JSON

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1927]
Current LED manager uses compile time generated led-gen.hpp and creates DBus objects for the groups. We would need this changed to use the generated JSON

- Modify the code to such that it should handle JSON ( if available )
- If not, fall back to using compile time generated led-gen.hpp
   - This is needed for backward compatibility
   - And also to support other users of this repo using YAML

  - Verify the DBus objects are seen for those groups
  - Verify GTEST passes

**Comment by lxwinspur** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-led-manager/+/31228

**Comment by lxwinspur** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-led-manager/+/31228
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-led-manager/+/31229

**Comment by vishwabmc** [comment]
Merged the commit.
