### ISSUE TITLE
eBMC LED Management :: LED interface between Hypervisor and BMC

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1930]
* Communication between BMC and PHYP for LED object. *

Traditionally, we never had LED groups and all the actions were targeted on Physical LED. With LED groups and PLDM in picture. we need to decide on how can we communicate between PHYP and BMC for variety of usecases.

- How to handle LEDs that are not accessible by BMC
   - How to handle LEDs that are on IO drawer ( MEX for example )
   - How to handle the PCIe extender 
   - How to communicate the status of Physical LED to PHYP
   - How to take actions on the LEDs that are requested to be turned on / off by partition

- What about LEDs that are handled by BMC and we are at runtime

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
@dkodihal @tomjoseph83 and I had a discussion on the PLDM needs for this and we seem to have hashed out the needs. They are captured n PLDM issue : https://github.com/ibm-openbmc/dev/issues/913

Need to discuss with larger audience among other things..

**Comment by vishwabmc** [comment]
We had a discussion with the Hypervisor team and agree on using PLDM/PDR as stated in #913 for all the LEDs that are accessible by BMC.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
