### ISSUE TITLE
eBMC LED Management :: Define PDRs for Physical LED states

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1931]
Hypervisor wants to be able to return the current status of each Physical LED to OS / PFW and hence coming down to BMC each time is in-efficient.

For that reason, we need to define PDRs for ALL the Physical LEDs addressable by BMC

Need PLDM State Sensor and NO effector as the operation on Physical LED directly is not allowed. Any SET has to come via LED groups

**Comment by dkodihal** [comment]
> hence coming down to BMC each time is in-efficient.

The purpose of a PDR is not optimized sensor reads. The PDR is what helps to identify a sensor.

In this case, I think the LED is going to be a state sensor (implementing state set 17 from https://www.dmtf.org/sites/default/files/standards/documents/DSP0249_1.0.0.pdf). This sensor will be associated to a FRU via the entity association PDR. There will also be a state sensor PDR for the LED itself. Thereby, reading entity association PDRs and the state sensor PDRs will help the hypervisor to enumerate LEDs on the BMC. When the LED state changes, the BMC will send a PLDM event to indicate the same. The event will have a sensor number, and again looking up the PDRs will help to determine what LED the sensor event corresponded to. If it is also necessary to determine the location code related to the LED (and I'm presuming this is the location code of the associated FRU), then that will be present in the FRU record for the FRU that's associated with the LED.

Based on the above, there's work for :
- Creating state sensor PDRs for all LEDs of interest
- Creating entity association PDRs to associate LEDs to FRUs

If this story is just for the above, then the sizing of 10 seems right.

There's also the work of sending up an event when the LED state changes, but I believe that would be a different github issue @vishwabmc?

**Comment by vishwabmc** [comment]
This story won't be tracked here. All the PLDM stories for LED will be under #913
