### ISSUE TITLE
eBMC LED Management :: Handling Callouts

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1933]
phosphor-led-manager has `fru-fault-monitor` that keeps looking for association objects and then would go trigger the `fru_fault`, where `fru` is part of association information.

- We need to do something similar.. We would need to . If the association object still has thing like `fan0` etc, we may not want much changes here.. 

What we need to consider is : How is PEL going to be plugged into this.. 

- And handling multiple call outs 
- Is parsing PEL needed or can we go off of fru in association object.

Need to discuss more on this with @spinler

**Comment by vishwabmc** [comment]
Having 13 points for anything unknown / discussions etc..

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@vishwabmc , can this be closed now?  All the Stories linked to this Epic are now closed.
