### ISSUE TITLE
FRU and VPD data content from BMC available via PLDM

### ISSUE THREAD

**Issue by mzipse** [ibm-openbmc/dev#1934]
Full set of FRU and VPD info available from the BMC via PLDM.  Includes 
BMC Card, Motherboard/backplanes, System, Chassis, TPM, VRMs, Op Panel, PCIE cards, CPUs, DIMMs PSUs.  Only the FAN FRU/VPD will not be included at this time.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
