### ISSUE TITLE
Audit Logging Support

### ISSUE THREAD

**Issue by mzipse** [ibm-openbmc/dev#1935]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
My thinking for Audit logging was  a Redfish Log Service Schema

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
I was pointed to this issue/epic when I questioned the lack of some journal entries regarding who was uploading what from where and when.

When using the GUI to upload a new firmware image, there tends to be a long gap in time if one is following the journal. It sure seems like it would be useful if there was a trace indicating which user logged in, from what IP/MAC, and which user started uploading a file, when, and what the filename was.

An upload complete might be nice to see as well. Apparently something in bmcweb is caching the image in memory, which can lead to a long lag time, and no idea what it was that was uploaded, by whom, etc.

**Comment by geissonator** [comment]
Goal would be to implement https://github.com/openbmc/docs/blob/master/designs/phosphor-audit.md on the back end.

**Comment by lxwinspur** [comment]
@geissonator @gtmills @mzipse 
Could you create a new repo for audit?
eg: phosphor-audit

**Comment by geissonator** [comment]
> @geissonator @gtmills @mzipse
> Could you create a new repo for audit?
> eg: phosphor-audit

Hey George, please send an email to the list stating you're going to start working on this new feature and request a new repository from Brad. I think the new TOF team may be reviewing requests like this.

**Comment by lxwinspur** [comment]
@geissonator @gtmills @mzipse 
I have updated phosphor-audit[1] spec, please review it and check that it meets IBM's requirements.
Welcome to leave a comment.
Thanks!

[1]: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/46023

**Comment by rfrandse** [comment]
refresh

**Comment by joseph-reynolds** [comment]
What are the next steps?  It seems to me we need:
1. Create the "Phosphor Audit Service" per [designs/phosphor-audit.md](https://github.com/openbmc/docs/blob/master/designs/phosphor-audit.md) which is capable of performing the "logging" action (to send log events to a journal).  (We don't need any other actions to be implemented at this time.)
2. Add code throughout the OpenBMC project (multiple repos) to invoke the Phosphor Audit Service "Audit Event" API.
3. Implement a new Redfish GET /redfish/v1/Managers/bmc/LogServices/Audit API to be able to read the audit events.  (Are any other operations needed?)

**Comment by lxwinspur** [comment]
@joseph-reynolds 
Thanks so much for reviewing this design document.

> What are the next steps? It seems to me we need:
> 
> 1. Create the "Phosphor Audit Service" per [designs/phosphor-audit.md](https://github.com/openbmc/docs/blob/master/designs/phosphor-audit.md) which is capable of performing the "logging" action (to send log events to a journal).  (We don't need any other actions to be implemented at this time.)

phosphor-logging/elog is responsible for sending log events to a journal

phosphor-audit-service is only responsible for recording log files, filtering and recording logs according to the configuration, or sending emails and other operations (this function has not been implemented yet)

> 2. Add code throughout the OpenBMC project (multiple repos) to invoke the Phosphor Audit Service "Audit Event" API.

We will create a new service (`phosphor-audit`), we do not need to create a new repo, it belongs to a sub-repository of `phosphor-logging`

> 3. Implement a new Redfish GET /redfish/v1/Managers/bmc/LogServices/Audit API to be able to read the audit events.  (Are any other operations needed?)

I haven't considered adding functionality to Redfish yet, but I'll do it later

I have pushed some patches to Gerrit, would you like to review it? :)
https://gerrit.openbmc-project.xyz/q/topic:audit-log

**Comment by rfrandse** [comment]
tracking in jira
