### ISSUE TITLE
eBMC LED Management :: Hotplug and CM support

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#1939]
This is a place holder in case anything is needed from LED sub system for Hot plug / Service action / Concurrent Maintenance.

In general, all these should already be covered as part of Callout / Clearing the fault / Redfish. But keeping it here if something comes up... 

POWR sub system should be handling these hotplugs and creating obmc logs / PELs too.. So, all these are to be driven by obmc log / PEL.

Also, if User wants to identify the fan ( if the LED is not part of fan ), then that should be part of Redfish IndicatorLED property and is covered part of Redfish epic

**Comment by vishwabmc** [comment]
From LED Manager standpoint, BMC will create LED groups for max config for a system.

**Comment by derekhoward55** [comment]
I'm not sure why we would special-case power supplies and fans.  For any FRU that is optional or can be removed/added, the design should be the same (how the led manager knows they are present, only FRUs that are present are returned to / controlled by external users etc).  I'm not sure how the PDRs are created in general, but they should be indicative of what is actually present in the system.

**Comment by vishwabmc** [comment]
Physical LED  manager will have the work to detect the cable card as part of CM and need some work here. 
- Detect the card
- Bind with the correct name

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
None of the above work actually was done in the LED manager app. The CM flow was handled within the VPD app. and the battery CM flow within bmcweb. Closing this one.
