### ISSUE TITLE
peltool: Don't show informational logs by default

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#1943]
I think it will make the peltool output more useful if we don't show informational errors by default, as some subsystems generate a bunch of them constantly.  Also, the legacy PEL CLI tool worked that way too, though I don't consider just that to be a reason to do it this way now.

**Comment by gkeishin** [comment]
Thanks @spinler need this one.

**Comment by harisuddin82** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30718

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/30718 merged
