### ISSUE TITLE
Fan support for 4U system

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1945]
Update dts and any json config files for 4u fan support (number of fans, rotors/fan, presence info, etc) based on info from system/thermal teams.

Ensure works as appropriate on simics&hw.

**Comment by msbarth** [comment]
Base 4u json configs will be created once #1441 is completed.

@eddiejames is working on the dts updates.

**Comment by msbarth** [comment]
Initial 4u support -> https://gerrit.openbmc-project.xyz/38539
