### ISSUE TITLE
Hostboot trace tool : Continous trace support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1946]
Provide PLDM based  Hostboot trace infrastructure, work involves.
- PLDM BIOS attribute support to control hostboot background trace.
- PLDM  based infrastructure for collecting debug trace data from host and storing in BMC.

Assumption:  Trace data parsing support is available in BMC.

**Comment by mzipse** [comment]
Current thinking from Nick and Deepak is that this will not be via PLDM.  Here's a summary from Nick:

The goal as we sketched out was to route the HB continuous trace through the 2nd UART.  The implication is that eBMC would need a few minor things
		a) A BIOS attr or something so that we could know if the continuous trace should be turned on or not, after we fetch that policy during early boot
		b) A strategy to log the VUART2 output so that it can be retrieved by FFDC collection (is there a size constraint?  does it get mirrored for eBMC file system?  can the output be directed to some mounted file system if it gets huge?  ).  It should also be 	
			possible that a user can open up VUART2 from an ssh session and tee the output to user's own file.
		c) There is also a post-processing tool that consumes the compact trace output and re-inflates it to a full trace.  We'd have to discuss if there is any involvement by eBMC to run that tool to get the fully parsed output, or if that would be left to the consumer.

**Comment by nmuruli** [comment]
Need to check with HB if this is still valid requirement

**Comment by mzipse** [comment]
@nmuruli , Dean was recommending a while back that we pass this work over to the HB team.  They are the ones that need it.  Perhaps we could mark this as A.1.888?

**Comment by nmuruli** [comment]
@mzipse I checked with the Nick from HB team and he mentioned that Hostboot will dump out the continuous trace on the 2nd virtual UART if the eBMC has enabled a specific BIOS attribute policy.  So, as far as I know, nothing else needs to be done on this front .
