### ISSUE TITLE
eBMC State Management - System firmware state (boot progress)

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#1949]
Issue #479 tracks working with the DMTF to define an API which will provide information on the status of the system firmware boot (Hostboot, PHYP, OPAL, OS). 

This story is to implement that Redfish API. It may need to initially go under the OpenBMC OEM in bmcweb.

The HMC team is looking for this.

FYI @gtmills @ratagupt

**Comment by geissonator** [comment]
Design Doc: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/32988

**Comment by gtmills** [comment]
The Redfish API was in 2020.3

**Comment by geissonator** [comment]
The final piece of this work went in with https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38437

https://gerrit.openbmc-project.xyz/q/topic:%22bootprogress%22+(status:open%20OR%20status:merged) tracks the other commits.

There is another Redfish property associated with the BootProgress object, BootProgressLastUpdate, that would track the time of the last boot progress code update. This is not currently required by IBM so we'll defer that to the community if someone ends up needing it.
