### ISSUE TITLE
GUARD: Redfish schema proposal

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1950]
- Proposal to DMTF  Guard Schema.
- Sizing Assumption : Existing logging schema based approach

**Comment by yoshiemuranaka** [comment]
@ojayanth any progress on this? we are starting #1509

**Comment by gtmills** [comment]
@ojayanth @dhruvibm I thought the only thing we needed from Redfish was "manually gard" which we said would be a "readyToRemove" on the processor and memory schemas?

**Comment by derick-montague** [comment]
Proposal: https://lists.ozlabs.org/pipermail/openbmc/2020-December/024262.html

**Comment by gtmills** [comment]
@ojayanth What else is needed here since "manually gard" is in the  processor and memory schemas?

**Comment by RameshIyyar** [comment]
Proposal accepted by DMTF and merged the changes.
Redfish: - Refer section 6.78.3 at 15th row - https://redfish.dmtf.org/schemas/DSP0268_2021.1.pdf
