### ISSUE TITLE
Guard: API- List  Guard records 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1951]
- Provide user level API to get required Guard information for application users.
- Additional functions required to process the data for application use

**Comment by devenrao** [comment]
1) Add option in guard tool for listing the guard records
2) Invoke guard interface method to list the guard recrords
3) Invoke block level device method to read the guard records
3.1) Check if ecc protection is available, if yes need to compute no of bytes to read from the guard pnor flash which includes ecc bytes
3.2) Compute the position and length of bytes to read from the file
3.2) Open the flash file and read the data of the specified size from the specified location and return to the caller.

Classes involved
GuardTool
GuardInterface 
  ---> list()    ( to list the guard records)
    https://github.com/open-power/skiboot/blob/master/external/gard/gard.c#L348
BlockLevelDevice
 ---> block_level_read (https://github.com/open-power/skiboot/blob/master/libflash/blocklevel.c#L103)
         --> Check if any ecc protection bytes need to be verified and accordingly read the bytes.
      --> block_level_raw_read() https://github.com/open-power/skiboot/blob/master/libflash/blocklevel.c#L82
     Compute the position and size of bytes to read from the flash file and then invoke flash read method.

FlashFile
 --> Read() - to read the data from the specified file
https://github.com/open-power/skiboot/blob/master/libflash/file.c#L52

Existing implementation is in C and the same needs to be changed to c++ as part of the new library and also consider only those things that are applicable.

**Comment by ojayanth** [comment]
https://github.ibm.com/open-power/guard/pull/2
