### ISSUE TITLE
Guard  API: Create  records

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1952]
- Provide user level API to create Guard information for application users.
- Additional functions required to process the data for application use

**Comment by devenrao** [comment]
1) Validate the input parameters passed to create the guard record
2) Invoke the create method provided by the guard library
3) Catch any exceptions thrown by the library

**Comment by ojayanth** [comment]
https://github.ibm.com/open-power/guard/pull/2
