### ISSUE TITLE
Guard:  API- Delete support 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1953]
- Provide  user level API support to  delete requested entry and all records.
- Additional functions required to process the data for application use

**Comment by devenrao** [comment]
1) Invoke the delete method provided by the guard library
2) Parse the data and print to the terminal by formatting
3) Catch any exceptions thrown by the library

**Comment by ojayanth** [comment]
https://github.ibm.com/open-power/guard/pull/2
