### ISSUE TITLE
Guard: API- Guard partition read 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1954]
- Get GUARD information from Guard partition.

**Comment by devenrao** [comment]
1. Block level read methods to read guard records from the guard partitoin.
2. Find the position of the record and read bytes for the size of the guard recrod 
3. If ecc protection is enabled, ecc bytes need to be read and validation need to be performed.

Code to refer from skiboot

block_level_read (https://github.com/open-power/skiboot/blob/master/libflash/blocklevel.c#L103)
Flash File
 --> Read() - to read the data from the specified file
https://github.com/open-power/skiboot/blob/master/libflash/file.c#L52

Better to implement the functionality in c++

**Comment by ojayanth** [comment]
https://github.ibm.com/open-power/guard/pull/2
