### ISSUE TITLE
Guard: Adding Guard records based on PEL data

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1962]
Switch to createWithFFDC interface of phosphor-logging and write the PEL data
in JSON format

**Comment by RameshIyyar** [comment]
Patch are ready but, switching API alone won't add any use here for now unless enabling guard support for callouts.
So, Same [patch](https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/37615) will use when enabling guard support for PHAL callout.

**Comment by RameshIyyar** [comment]
I think we can use this story to enable support guard for phal error handling.

**Comment by RameshIyyar** [comment]
Looks like this issue was duplicated with https://github.com/ibm-openbmc/dev/issues/3294 so closing and that pointed issue are addressed.
