### ISSUE TITLE
istep: UpdateHWModel enablement.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1967]
Update Scratch pad registers as part sbe_config_update istep with FW functional Targets. This need GUARD functionality support.

**Comment by ojayanth** [comment]
#727 provides the  design details.
Work involved:
- Enable updateHWModel istep in ipl, which includes the business logic mentioned in #727 
- Enable  updateHWModel in ecmd-pdbg.

**Comment by chiragsibm** [comment]
Changes done, tested and raised for review.
1-> Added guard support to fetch the list of guarded resources and marking them as non-functional(only proc and its childs); incase of MPIPL only cores should be marked as non-functional.
2-> In genesis boot need to mark master proc as functional along with core, pau etc.

**Comment by chiragsibm** [comment]
https://github.ibm.com/phal/ipl/pull/27

**Comment by ojayanth** [comment]
Merged.
