### ISSUE TITLE
op-proc-control: CI test support for all supported features

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1968]
openpower-proc-control introducing PHAL feature to support HW enablement layer. This got Processor target dependency during build time due HWP dependency.. This tosry to support repository specific CI mechanism to support conditional compilation based on Feature specific flags.

**Comment by rsnair** [comment]
Nice to have but can be deferred to GA2 as its not a functional piece.

**Comment by ojayanth** [comment]
@rsnair this issue is already tagged to #3078

**Comment by rfrandse** [comment]
tracking in jira
