### ISSUE TITLE
Device tree standalone build support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#1971]
- Existing device tree build process got some dependency on op-build infrastructure. 
-  Proposed flow is to make independent repository for device tree generation and meta data files.  And  op-build can use this repo as sub module for packaging the Device tree as part of Hostboot image.

**Comment by rsnair** [comment]
This is not needed for GA1. It's only for process improvement. Please tag this appropriately.

**Comment by rfrandse** [comment]
tracking in jira
