### ISSUE TITLE
PLDM: pldmtool commands

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1978]
This epic tracks commands to be added to pldmtool. This enables test code to test out PLDM functionality on the host and BMC firmware.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
