### ISSUE TITLE
PFP::control - Fan control based on proc dvfs limit

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#1982]
Support to dynamically set Processor fan control threshold based on DVFS temp sent back from OCC (value is unique per OCC, current proposal fans increased at DVFS minus some fixed value set in attribute).

The new P10 OCC interface spec has it defined in the poll response where we currently send back the current readings we also send back this new field:
Throttle Temperature – 1 byte. Temperature in degrees C in which the OCC will reduce performance i.e. throttling (memory), DVFS (processor)… in order to lower the temperature.  The BMC/FSP should ensure that fan increases start at a temperature lower than the throttle temperature to try to keep the temperature from reaching the point of impacting performance.
0xFF = No throttle temperature. The OCC does not take any action based on this temperature.  Temperature is used for fan control only.

Potential device driver impacts.

**Comment by msbarth** [comment]
The DVFS temp given by the OCC poll will get a fan control configured delta (for cores and another delta for io) applied to that DVFS value in determining their t-control points in increasing fan speeds.
