### ISSUE TITLE
PLDM: commands for inband code update

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1983]
Implement PLDM commands to enable inband code update of the host firmware.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
The PLDM code has been merged: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/37437/

Likely most if not all of these stories can be closed.

Only remaining task is support the reboot after the update.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
