### ISSUE TITLE
PLDM: Implement mechanism to transfer core count

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1987]
Host firmware needs to relay core count per chip via PLDM.

**Comment by nmuruli** [comment]
Scope of this work in increasing , hence updating the estimate.

**Comment by nmuruli** [comment]
This will depend on the **_PLDM: add entity instance as an input parameter to libpldm dev #3202_** and associated hostboot changes to complete.

**Comment by manojkiraneda** [comment]
merged in tag 29 driver.

**Comment by manojkiraneda** [comment]
Upstream commits : 


oem : Set the Core count property under CPU object | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/42609/20
Add getSubtree utility functions | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/42608/20
Normalization fru record set and state sensor/effecter PDRs from Host | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/45466/20
Customise the DbusObject paths as per IBM | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/45803/16
Implement CpuCore Interfaces for cores | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/42619/26
Add the support for Inventory Item dbus Interface | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/42098/31
Process state sensors PDRs and update Operational Fault Status | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/39796/67
Handle FRU records from host | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/39588/77
Handle entity association records from host | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/39198/79
Update mergeEntityAssociations logic | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/43032/41
libpldm : Enhance the find & add pdr utilities | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/44699/19
Fix buildFRUTable and update to Association tree | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/42833/36

**Comment by manojkiraneda** [comment]
closing as it is merged in downstream driver tag -29.
