### ISSUE TITLE
User Initaited dump: Include GUARD inforamtion

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#199]
Include GUARD file `/var/lib/phosphor-software-manager/pnor/prsv/GUARD` as part of the open bmc dump.

**Comment by shenki** [comment]
This would be useful for all OpenPower machines.

I suggest we include the parsed output in our logs using the 'gard' tool.

**Comment by ojayanth** [comment]
Code is still review.
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-ibm/+/14592/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Abandoned the patch , need to re-submit the same  this to meta-openpower.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-openpower/+/25547 merged.
