### ISSUE TITLE
PLDM: Graceful reboot of host firmware

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1992]
This epic tracks the work around the BMC acting as a PLDM requester to issue a host graceful reboot request to the host firmware.

- The graceful reboot applies to both Hostboot and PHYP.
-  There is no BMC internal trigger to request graceful reboot
- The Redfish `ResetType` is `GracefulRestart` https://github.com/openbmc/docs/blob/master/designs/state-management-and-external-interfaces.md
http://redfish.dmtf.org/schemas/v1/Resource.json#/definitions/ResetType
- #1351 Both `GracefulRestart` and `GracefulShutdown` will leverage the PLDM soft off application.

**Comment by tomjoseph83** [comment]
Redfish API to initiate GracefulRestart
```
curl -k -H "X-Auth-Token: $TOKEN" -X POST https://${BMC_IP}/redfish/v1/Systems/system/Actions/ComputerSystem.Reset -d '{"ResetType": "GracefulRestart"}'
```

**Comment by sampmisr** [comment]
seems to be the follwing effecter in bmc:
{
        "type" : 31,
        "instance" : 0,
        "container" : 0,
        "effecters" : [{
            "set" : {
                "id" : 129,
                "size" : 1,
                "states" : [6]
            },
            "dbus" : {
                "path": "/xyz/openbmc_project/state/host0",
                "interface": "xyz.openbmc_project.State.Host",
                "property_name": "RequestedHostTransition",
                "property_type": "string",
                "property_values": [
                        "xyz.openbmc_project.State.Host.Transition.ForceWarmReboot"
                ]
            }
        }]

**Comment by ibmzach** [comment]
That effecter only supports graceful restarts ("states": [6]), not graceful shutdowns.

**Comment by sampmisr** [comment]
> 
> 
> That effecter only supports graceful restarts ("states": [6]), not graceful shutdowns, which is what we were discussing yesterday.

yeah corrected my stmt. pls check the above notes
