### ISSUE TITLE
PLDM: Implement Capacity On Demand

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1994]
PLDM commands for implementing the COD feature.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jaypadath** [comment]
A. File IO Meta Data Support
   1. Add new encode and Decode functions for FileAckWithMetadata and NewFileAvailableWithMetadata 
       --> Four uint32_t meta data variable additions. File Metadata #1, File Metadata #2, File Metadata #3 and File Metadata #4
      
B. Implementation of new CoD licencing mechanism
   1. Dynamic addition, deletion and update of licence objects by parsing the json file provided by PHYP
   2. Usage of new file IO meta data supported functions
   3. Error handling for License Processing Result
      
C. Support of passing the strings (like licence key, entitlement date etc).

**Comment by rfrandse** [comment]
refresh

**Comment by jaypadath** [comment]
PR created for this change is at https://github.com/ibm-openbmc/pldm/pull/18

**Comment by nmuruli** [comment]
Downstream only work. Closing the story

**Comment by rfrandse** [comment]
refresh
