### ISSUE TITLE
PLDM: Add commands related to Field Core Override

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#1995]
PLDM commands to enable configuring the number of active cores.

**Comment by dkodihal** [comment]
Redfish API story in #1844.

**Comment by nmuruli** [comment]
Assigning to Sagar

**Comment by nmuruli** [comment]
Support for required BIOS attribute is completed

**Comment by sampmisr** [comment]
closing this issue as pldm work is completed
