### ISSUE TITLE
Micro-code changes for IBM LE BMC system

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/dev#2002]
The below tasks have to be completed and the hardware is required for doing so.
  --  Nisqualy micro-code to support system reset
  --  Nisqualy micro-code to support bootfail detection
  --  Finalize on code update from command line via script or executable on the rainier system.
  --  Design to do code update on micro if needed.
  --  Code update on LCD panel on rainier

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
Base code was delivered

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
