### ISSUE TITLE
Display Platform UPS status API 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2004]
On Maury's GUI roadmap as `Platform UPS via BMC`. Will need a GUI story as well. Not For GA

**Comment by gtmills** [comment]
Not for GA. 
Maurice Zipse  12:45 PM
Yes, I think for now that’s all we plan to do.  We might want to make a note about someday putting that status on the BMC GUI, but not for GA1.  Thanks Derek for the clarification.

**Comment by rfrandse** [comment]
tracking in jira
