### ISSUE TITLE
Pending Serviceable tasks (Maintenance ) log API 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2006]
Need an API (hopefully Redfish) for Pending Serviceable tasks log. 

These were the LogServices Justin thought we would have:
Audit (#2008 )
Boot
Events
Maintenance (this story)
Correctable (#2007 )

**Comment by gtmills** [comment]
According to @spinler should be moved to A.2.999 milestone

**Comment by rfrandse** [comment]
tracking in jira
