### ISSUE TITLE
Redfish: Hidden (Correctable/Admin) LogService API

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2007]
Need a Redfish API for the Admin Log. This will be a LogService. This is on the GUI roadmap as "Admin Log API"

#1067 is putting a hidden property out on D-Bus  so bmcweb can return them when the user has the appropriate authority 

This story is the Redfish work. 

These were the LogServices Justin thought we would have:
Audit (#2008 )
Boot
Events
Maintenance (#2006 )
Correctable (this story)

**Comment by gtmills** [comment]
@joseph-reynolds This Hidden event log should only be seen by CElogin? 
Are you working on a service priv? What story tracks that? 

According to conversation here: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1627411616041400?thread_ts=1627407651.037600&cid=C0Q6TQP5Z

We think this should be downstream only 

Changes should be in this final: https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/log_services.hpp

We are going to talk if this makes sense under /redfish/v1/Managers/bmc/ or /redfish/v1/Systems/system

**Comment by gtmills** [comment]
A workaround for if the service permission stuff is not ready: we initially just push the standard permissions and update later to the service permission

**Comment by rahulmah** [comment]
API for seeing hidden logs is `redfish/v1/Systems/system/LogServices/CELog/Entries`. At present, this is working using both root and CE login user.

**Comment by mzipse** [comment]
Work is complete.  Closing.
