### ISSUE TITLE
Progress Indicators: Boot Logservice API

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2009]
Need a Redfish API for Boot/Progress Indicators. 

Thinking this would be 

- Boot Logs /redfish/v1/Managers/bmc/LogServices/Boot/ 

On the GUI roadmap as `Progress Indicators:  Realtime, History`

**Comment by mzipse** [comment]
@gtmills , check out #1920 , wondering if you will be  depending on this?

**Comment by gtmills** [comment]
Yeah it would. added depends on to #1920

**Comment by gtmills** [comment]
@manojkiraneda I believe progress code / Progress Indicators is downstream in a driver. 
@manojkiraneda Should you own this?

**Comment by manojkiraneda** [comment]
The Progress code History - the pldm, post-code-manager, bmcweb changes are merged downstream & available in tag-19 driver.

The Real Time Progress Indicator - Needs eventing support for progress codes in the bmcweb repo - as per my last conversation - this is being picked up by @ratagupt squad.

**Comment by gtmills** [comment]
Needs eventing support for progress codes in the bmcweb repo. @ratagupt Assigned you. Let me know if that is incorrect or if you are tracking elsewhere and I can close.

**Comment by ratagupt** [comment]
I was not signed up for this, One who added the feature support , should support for eventing, We have the infra available.

**Comment by gtmills** [comment]
@manojkiraneda  Can you add the eventing support for this?

**Comment by nmuruli** [comment]
@gtmills We discussed locally this activity and the someone from @rsnair (Rajiv's) squad will pick this activity.

**Comment by gtmills** [comment]
@nmuruli Thank you. I assigned to @rsnair

**Comment by mzipse** [comment]
Reassigning to @ratagupt squad within @rsnair team.  That way it is visible to Ratan's squad.

**Comment by mzipse** [comment]
Reassigning to Sunitha to determine when this could be delivered.

**Comment by sunharis** [comment]
Progress Indicator eventing is delivered to GHE 1020 - downstream only.

**Comment by gtmills** [comment]
@sunharis Shouldn't we leave this open, just in the "code in driver" pipeline until this merges upstream?
