### ISSUE TITLE
PCIe / CAPI devices API for inventory page

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2010]
Need an API (hopefully Redfish) so the GUI can show pcie/capi devices connected and VPD on the inventory page. 
Believe we only need inventory and status properties.

**Comment by dkodihal** [comment]
@gtmills does this cover FRUs on the MEX IO expansion drawer? Or is that #1846?

**Comment by gtmills** [comment]
@dkodihal This is showing the PCIe / CAPI / IO devices on the inventory page. #1846 is IO related to configuration/firmware update. I tried to make this more clear.

**Comment by derick-montague** [comment]
@gtmills - this this milestone accurate?

**Comment by gtmills** [comment]
@santoshpuranik This milestone accurate ? We have everything we need in Redfish?

**Comment by derick-montague** [comment]
@gtmills - Rahul stated that the backend may be complete. Can you share your understanding of the status for the blocking story?

**Comment by gtmills** [comment]
This story requires implementing several new Redfish resources. 
It is not complete. 
@santoshpuranik Is the milestone still accurate?

**Comment by gtmills** [comment]
We have SW542471 which will add the cable cards? What more do we need here, SW542471 should get us to what we had on FSP

**Comment by santoshpuranik** [comment]
Closing as SW542471 is now fixed.
