### ISSUE TITLE
Deconfiguration Records API 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2011]
On the GUI roadmap as Deconfiguration Records: Processor, Unit, Mem

**Comment by derick-montague** [comment]
Is the milestone accurate on this story?

**Comment by gtmills** [comment]
@dhruvibm @ojayanth  Do you have this work covered elsewhere? If so, feel free to close

**Comment by derick-montague** [comment]
If the work is somewhere else, but still WIP, I'd like to make sure we link it to the same stories this is linked to, #1509. Otherwise, we won't know when the work is complete and we can code the front-end. The design is done and we are ready to move forward with the back-end is complete.

**Comment by derick-montague** [comment]
@dhruvibm @ojayanth - Wondering when work will start on this story.

**Comment by yoshiemuranaka** [comment]
@gtmills do you know if there is any progress on this? we are starting work on #1509

**Comment by RameshIyyar** [comment]
@gtmills / @ojayanth what is the scope of this story ?
I have created stories already for bmcweb work items which are accepted for guard milestone. 
#2939
#2938
#2937 
#2936

**Comment by gtmills** [comment]
@RameshIyyar If this is tracked elsewhere, this can be closed.

**Comment by rsnair** [comment]
Closing this one as Guard stories are already created. #1936 is the Guard epic for tracking.

**Comment by derick-montague** [comment]
If we are closing stories that are set as dependents for GUI stories, we need to make sure to set the new dependencies.

**Comment by derick-montague** [comment]
> @gtmills / @ojayanth what is the scope of this story ?
> I have created stories already for bmcweb work items which are accepted for guard redfish enablement milestone from bmc stack.
> #2939
> #2938
> #2937
> #2936

@rsnair and @RameshIyyar are any of these stories being worked currently. I only ask as they are all new and seem to be associated with an older milestone.

![image](https://user-images.githubusercontent.com/1183515/117294902-cf0bf100-ae38-11eb-9e29-93da51105cbc.png)
