### ISSUE TITLE
Upstream to Redfish: TOD Battery, Op/Control Panel Concurrently Maintainable API

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2012]
On the GUI roadmap as 
FRU’s Concurrently Maintainable (TOD Battery & Op/Control Panel).
I don't see anything in Assembly but Drive has

                "ReadyToRemove": {
                    "description": "An indication of whether the drive is prepared by the system for removal.",
                    "longDescription": "This property shall indicate whether the system is prepared for the removal of this drive.",
                    "readonly": false,

https://redfish.dmtf.org/schemas/v1/Drive.v1_10_0.json

Can we get Redfish to add this to Assembly? Use Status to know when it is complete. @santoshpuranik to ask

**Comment by derick-montague** [comment]
The plan is to include all FRUs to the HW Inventory page from a design perspective. Not sure if that matters for this story or not.

**Comment by derick-montague** [comment]
@gtmills do we have a story for DVD? I looked and can't find one. We have that listed as concurrently maintainable also.

**Comment by gtmills** [comment]
@derick-montague I added DVD here to this story

**Comment by gtmills** [comment]
DVD is not rainier or everett. Removing from story.

**Comment by gtmills** [comment]
We added ReadyToRemove to PCIeDevices; Still need to figure out assembly here

**Comment by gtmills** [comment]
Maybe a future Redfish release. Moved to 2nd half of this year.
