### ISSUE TITLE
Security Configuration API

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2013]
Need APIs (Hopefully all Redfish) for security configuration, e.g. SSH and other protocol enable/disable. 
Firewall (if we have enable / disable).

This is on the GUI roadmap as 
Security Configuration
SSH & Firewall enable/disable

**Comment by joseph-reynolds** [comment]
Is this a dup of #612?

**Comment by gtmills** [comment]
@joseph-reynolds Yeah. Is Firewall enable/disable covered by a different story ?

**Comment by gtmills** [comment]
@joseph-reynolds Feel free to close or move around how this is tracked. If you think #612 covers everything, feel free to close.

**Comment by gtmills** [comment]
Covered by #513 #1763 #452 #1808
