### ISSUE TITLE
System Info Indicators (System Attention Indicator) API

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2014]
Need an API for System Info Indicators.
This is on the GUI roadmap as  Sys Info Indicators
The ASMI page looks like:

![system-information-indicator](https://user-images.githubusercontent.com/5455127/97606761-c47a2600-19d5-11eb-88a7-3daa29a65d2d.JPG)

This is the work to support the APIs for same functionality on the eBMC GUI

**Comment by gtmills** [comment]
@vishwabmc Are you tracking the SIA work here? 
Or elsewhere?

**Comment by vishwabmc** [comment]
This is being covered in : https://github.com/ibm-openbmc/dev/issues/2120

**Comment by gtmills** [comment]
@vishwabmc I don't think I should own this

**Comment by vishwabmc** [comment]
Well, the reason I made @gtmills the owner was to handle 
```
If Partition SA is set

If Platform SA is set

If ANY one of them is set, then it shows the SAI is on.. Else shows OFF
```

 I talked to him and he says it's covered in other GUI issues and this one was specifically for APIs.

**Comment by mzipse** [comment]
Work is complete.  Closing.
