### ISSUE TITLE
Tunable Sensor Stream API

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2015]
This is on the GUI roadmap as Tunable Sensor Stream. Need an API for this.

**Comment by gtmills** [comment]
Isn't this just the telemetry schema ? #50

**Comment by spinler** [comment]
@gtmills I think this was for when crassd used the subscribe REST interface and then listened for properties changed events from bmcweb.

**Comment by gtmills** [comment]
This would be Redfish telemetry

**Comment by gtmills** [comment]
Not clear what this is tracking. I am closing and will use different issues for telemetry function. Please reopen if I closed on mistake
