### ISSUE TITLE
LEDs: Service indicators, by Loc Code, LED APIs (Enclosure Indicators ASMI page) 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2016]
On the GUI roadmap as LEDs: Svc indicators, by Loc Code, LED Blink. Need APIs for this work.
This is the "Enclosure Indicators" ASMI page. 

![enclousure-leds](https://user-images.githubusercontent.com/5455127/97613670-94835080-19de-11eb-8838-7bc8c19a5edc.JPG)

This is the APIs to support that functionality in eBMC

**Comment by gtmills** [comment]
Will use the Service Label (Location Code) property and the LocationIndicatorActive property. 
For Fault indicator status will use the resource health. 
We don't need to clear the fault indicator

**Comment by derick-montague** [comment]
I removed this from the GUI Epic so that the milestone update job doesn't keep changing this.

**Comment by gtmills** [comment]
We don't need to write a Fault State. 
Assuming we model Fault LED as the health of the resource? 
Can the GUI just display this as the "health of the resource" ?

**Comment by vishwabmc** [comment]
What is needed from me on this @gtmills ? GUI needs to walk redfish resources and then look at Health

**Comment by gtmills** [comment]
> What is needed from me on this @gtmills ? GUI needs to walk redfish resources and then look at Health

And will do the same for indicator LEDs and Location Codes. 
So as long as this is all covered elsewhere, we can close this

**Comment by vishwabmc** [comment]
> And will do the same for indicator LEDs and Location Codes.
What you mean ?.. You mean GUI does it anyway ?

**Comment by gtmills** [comment]
The GUI needs to walk the Redfish resources and get the health, location code, and indicator LEDs

**Comment by gtmills** [comment]
This work is all tracked elsewhere by @vishwabmc indicator LEDs, location code, and fault LED stories.

**Comment by derick-montague** [comment]
We had this as part of the GUI dependencies. Would be good to know the which stories the GUI is dependent on now.

**Comment by gtmills** [comment]
@vishwabmc Can you help here? ^

**Comment by vishwabmc** [comment]
@gtmills @derick-montague Like I said before, LED code is __not__ responsible for giving location_code. Nor it gives a complete list of all LEDs in custom way.. GUI needs to walk the redfish resource and show it.

https://github.com/ibm-openbmc/dev/issues/2082 is what adds `LocationIndicatorActive` support for Redfish resources.

**Comment by derick-montague** [comment]
We have #2082 as a dependency. Thank you!
