### ISSUE TITLE
Rework on the dump interface implementation once schema gets standardized.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2019]
There are some changes which need to be implemented once schema gets standardized,

**Comment by ratagupt** [comment]
@asmithakarun: Can you mention the Gerrit link?

**Comment by asmithakarun** [comment]
Schemas - https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/33918
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/35269

The change has been merged to the master
