### ISSUE TITLE
openpower: on power off, turn off PCIE slot power

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#202]
Codify this: https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc/+/14389/

Anthony will be working on this.

**Comment by antwil** [comment]
Resolved by:
  https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-proc-control/+/15192/
and
  https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-openpower/+/15194/

**Comment by rfrandse** [comment]
refresh
