### ISSUE TITLE
Enable build-setup.sh to run multiple instances in jenkins

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#203]
There was an issue that I didn't document well with running build-setup.sh in parallel within our jenkins jobs. This story is to track that issue down and fix it (may just be jenkins config).

With our additional build resources, we can do more in parallel now.

**Comment by geissonator** [comment]
The first issue I ran into is that when jenkins runs jobs in parallel, it puts an "@" symbol in the directory path which bitbake does not like. There's an option on startup of Jenkins to change this symbol.

**Comment by geissonator** [comment]
https://stackoverflow.com/questions/13169960/how-to-change-the-concurrent-build-path-separator-in-jenkins shows how to fix this.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Was able to fix this issue by telling jenkins to use a different separator for the directories. https://jenkins.openbmc.org/job/ci-openbmc/ now runs two jobs at once (about as much as our infrastructure can handle)
