### ISSUE TITLE
Serial Tunnel for access to Host

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2037]
Run the SSH server on the 2200(Ibmi-os) port which should get the data from the partition
Make the Recipe changes
Andrew has done some stuff regarding the same.

**Comment by ojayanth** [comment]
@ratagupt 2201 port Support is working in rainier HW ,  Any additional work involved here?

**Comment by ratagupt** [comment]
As we have the support for both the ports
1) 2200 : Ibmi console
2) 2201: Phyp
Hence closing this story.
