### ISSUE TITLE
HMC-BMC Dump Managememt-Stage2

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2045]
=> Rework on the dump interface implementation once schema gets standardized.
=> Implement the Log Services for the manager
=> Implement redfish interface for the "User-initiated dump" (system Log Service)
=> Implement redfish interface for the "User-initiated dump" (Manager Log Service)
=> Implement the clear all /delete functionality for the BMC dumps.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@ratagupt Is there a story to move to the Redfish standard Dump implementation after #2400 is done ?
I thought it would be https://github.com/ibm-openbmc/dev/issues/2019 but that is closed

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
@gtmills We have already implemented the latest schema in the bmcweb and the code has been merged in upstream.

**Comment by mzipse** [comment]
All stories are done now.  Closing this.
