### ISSUE TITLE
Read FRU callout lists for end devices from the MRW

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2046]
On every connection in the MRW, there will be a FRU_PATH attribute that contains an array of targets, with their priorities, to call out for a fail on that device.  We need to make an MRW perl script in phosphor-mrw-tools to read those and generate a JSON file that contains a map of (i2c bus, i2c address) to array of (FRU inventory D-Bus path, priority).  Need to figure out still how to handle this if there is I2C off of a CFAM, like a processor, where there is FSI in the path.

Need to research if the bus/address are the best key into the map, or if an actual device path is, though as I suspect multiple apps can use different device paths for the same device, and that some users will only have the bus and address, that that is the best option.

This JSON will then need to be installed somewhere in /usr/share on the BMC.

If there are multiple XML files for different flavors of the same system, they will need to be processed separately and all installed on the BMC.  Another story will handle using entity manager to look up the right JSON file from inside the code.

In addition to all of that, certain I2C failures require a callout of every FRU on that bus, and not just the FRUs on the path to the end device.  So, the code will also need to gather up a JSON structure that lists all FRU callouts for every bus.

Recipe updates will be required to install this JSON

This also needs to support SPI devices, however that differs from I2C ones.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-mrw-tools/+/33093

The piece about using the errno to alter the callouts will be handled under #2205.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-mrw-tools/+/33093 merged
