### ISSUE TITLE
Read device path callout JSON and add callouts to PELs

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2047]
If an event log has a CALLOUT_DEVICE_PATH key in the AdditionalData property, then when creating the PEL:
- Obtain the I2C or SPI bus and address from the device path
- Use entity manager (wrapped by an existing DataInterface call) to know the name of the device path JSON file to load.
- Look up that device path in the JSON and add the callouts to the PEL.  The code will only have the inventory path, so it will have to make the calls to get the location code/FN/SN/CCIN (those functions already exist).
- It will need to use the errno from the CALLOUT_ERRNO value that accompanies the path to know if it needs to call out just the FRUs for the end device, or every FRU on the bus.

If the code passes in CALLOUT_IIC_BUS and CALLOUT_IIC_ADDR instead of the path, then it needs to do the same but can skip the step of obtaining these values.

This of course all needs unit tests.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/33249/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/33249 merged
