### ISSUE TITLE
eBMC Interfaces available for MFG CFT tool Drop 1

### ISSUE THREAD

**Issue by mzipse** [ibm-openbmc/dev#2048]
@trajeswaran , can you help identify which interfaces are still needed for the MFG Drop 1

**Comment by trajeswaran** [comment]
The interfaces for the below mentioned functions are required.
     - Prevent code update to unsupported levels (minimum ship level)
     - Sync MasterLid List with extu lids on Boot Side (phyp lid Patching)
     - Current IPL boot side and Next IPL boot side
     - Non boot side Mif level

**Comment by mzipse** [comment]
@anoo1 , are any of the functions missing that Rajes lists above?  If we have any outstanding stories, please link them to this Epic.  Thanks.

**Comment by anoo1** [comment]
> - Prevent code update to unsupported levels (minimum ship level)
Done: https://github.com/ibm-openbmc/dev/issues/1293

> - Sync MasterLid List with extu lids on Boot Side (phyp lid Patching)
Lid patching is supported. The lid_update tool handles the updated master lid list, no need to update it on the BMC.

> - Current IPL boot side and Next IPL boot side
Side switching is supported

> - Non boot side Mif level
The non-running version is available via the Refish API.
