### ISSUE TITLE
LED Callouts :: Get the Corresponding FRU given a location code

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2049]
PEL will have location codes and we need to map that to a FRU..  This story will be used to use the interface and have set of location codes.

There is an interface available for this. It is under review 

https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/29761

**Comment by spinler** [comment]
This code is available now, closing.
