### ISSUE TITLE
LED Callout :: Walk the Callout section and determine needed LEDs to be lit

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2050]
LightPath strategy has set of rules to be followed while deciding the LEDs to be lit up. It depends on priority of callouts / how many callouts are there / whether they are FRU callouts or procedure callouts etc.... 

As a result : This story needs to have all the LED groups to be litup and then make D-Bus calls for those groups.

**Comment by vishwabmc** [comment]
The following rules are implemented while parsing the callouts as part of error/event logs in stand-alone servers.
1.	FRU fault activation (or request for activation) criteria based on the error analysis results,  moving from top to bottom through the FRU list:    
●	All high priority HW and symbolic FRUs with trusted location codes only if none of them is a procedure or simple symbolic FRU (including FW callout) and all of them have a fault indicator;
●	Else if no high priority FRUs in the FRU list then activate the first medium priority FRU, or all FRUs in the group if the first medium priority item is a medium priority group callout (group 'A' by the PEL spec),  but only if none of them is a procedure or simple symbolic FRU (including FW callout) and all of them have a fault indicator;
●	Else activate the system check log indicator.
1.	Actions when a FRU fault activation fails
●	Continue activating other fault indicators as per the activation criteria.  
●	It is assumed that if a FRU fault indicator activation fails, the underlying FW will activate the system check log indicator.  A fault activation looping condition must be avoided when fault activation fails and FW is logging and analyzing the activation failure.  An event log for fault activation failure must be made so that a record exists but the event must not be a serviceable event because the strategy is to avoid replacing a FRU for fault indicator activation failure when that FRU would not otherwise be replaced.

**Comment by vishwabmc** [comment]
System CheckLog is nothing but "System Attention Indicator" ( SAI )

**Comment by spinler** [comment]
```
An event log for fault activation failure must be made so that a record exists but the event must not be a serviceable event
```
@vishwabmc what code would create that event log?

**Comment by vishwabmc** [comment]
> ```
> An event log for fault activation failure must be made so that a record exists but the event must not be a serviceable event
> ```
> 
> @vishwabmc what code would create that event log?

@spinler I am looking at this way  

PEL --> Calls the utility --> PEL gets the list of things to drive --> PEL uses utility-2 that will drive each path and logs any error

So, my answer would be "utility-2". Something that the PEL calls in. Something that PEL could code as per my original understanding

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35375

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35375 merged
