### ISSUE TITLE
LED Callouts :: Replace the current fru-fault monitor with the new implementation

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2051]
Today's implementation has "fru-fault" monitor that is looking at the Association objects and then making a D-Bus call. However, we would need PEL way of handling the callout instead of what we have.

This story will :

  - Package PEL for IBM eBMC system
  - Make sure the current fru-fault monitor still holds good for other implementations

**Comment by derekhoward55** [comment]
Note there was a requirement to ignore fault indicator processing for faults logged by PHYP through the SP, but I'm guessing that was due to PHYP driving the leds at runtime.  If BMC will be in charge of leds, then need to decide if that requirement is no longer valid.

**Comment by vishwabmc** [comment]
> Note there was a requirement to ignore fault indicator processing for faults logged by PHYP through the SP, but I'm guessing that was due to PHYP driving the leds at runtime. If BMC will be in charge of leds, then need to decide if that requirement is no longer valid.

@derekhoward55 Are you saying PHYP calling out CEC parts with BMC accessible Indicators ?

**Comment by derekhoward55** [comment]
Yes.  This was not a requirement in my code, but I'm guessing the requirement was regardless of fru being called out.

**Comment by spinler** [comment]
@vishwabmc Is there anything left for us to do on this story?

**Comment by spinler** [comment]
fru-fault-monitor has been removed for the systems with PELs, so closing this as I don't think there's anything else to do here.
