### ISSUE TITLE
eBMC TimeManager : Remove TimeOwner and Deferred updates

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2055]
phosphor-time-manager has the concept of TImeOwners and that can have values of [Host / BMC / SPLIT / BOTH]. Basically telling, who owns the time. To cater to that, it had `time/bmc` and `time/host`

Redfish requests will always update `BMC` and Inband requests will always update `host`. If it's SPLIT, Host's time is calculated as an offset into BMC time..

The feedback from the community is that it is confusing and no one really used that feature.

Other feature time-manager has is [Deferring updates to settings like changing between Manual/NTP]. What it means is, if the setting is changed from Manual to NTP or vice versa and the Host is on, then time manager will continue to run with the setting it had at power on and will only consume this new setting after the host has been powered off.. 

After a long discussion with all needed parties, we agree with RAS that we don't need Host to be powered off before these settings can take into effect.

**Comment by rfrandse** [comment]
refresh

**Comment by lxwinspur** [comment]
- eBMC Time Manager : Remove TimeOwner Feature(https://github.com/ibm-openbmc/dev/issues/2056)
 https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-time-manager/+/31278

**Comment by derick-montague** [comment]
Should this be in a different column...current sprint or review possibly?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@lxwinspur , Can this issue be closed now?  I see the 4 commits above are now merged.

**Comment by rfrandse** [comment]
refresh
