### ISSUE TITLE
eBMC Time Manager : Remove TimeOwner Feature

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2056]
Remove Time Owner feature in Time Manager and needed settings objects.

**Comment by vishwabmc** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-time-manager/+/31278/

**Comment by lxwinspur** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-time-manager/+/31278
