### ISSUE TITLE
eBMC Time Manager :: Remove Deferred Updates

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2057]
Remove deferred consumption of settings Manual/NTP and allow instant consumption.

**Comment by derick-montague** [comment]
Is this the correct Gerrit review? https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-time-manager/+/31284/4

Should the story column be updated?

**Comment by vishwabmc** [comment]
> Is this the correct Gerrit review? https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-time-manager/+/31284/4
> 
> Should the story column be updated?

@derick-montague That is correct. What you mean `update story column` ?

**Comment by derick-montague** [comment]
The **pipeline** which in our ZenHub boards is a Kanban board column. Currently both date and time stories are in the new pipeline. The design team was concerned that these stories were not being worked on and that we might have to redesign the date and time again if that were true. Between the milestone and the pipeline values, we did not think this was being actively worked on. 

If a story is being actively worked on, it should be in the **Current Sprint** pipeline. In this case, it should be in the **Code Review** pipeline.

![image](https://user-images.githubusercontent.com/1183515/81180592-dcb24080-8f70-11ea-97ff-297a620f9931.png)

**Comment by vishwabmc** [comment]
This is already merged: commit https://github.com/openbmc/phosphor-time-manager/commit/0a70452ab01fd76f852c7bd656ae4b36cac5f222
