### ISSUE TITLE
GUI : FED : Security Panel

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2063]
## Overview
Implement new Security Panel design. The design is lacking some of the fidelity and interactions. These requirements will be outlined in the UX Flow / Interaction requirements below, rather than being part of the prototype.

## UX Flow / Interaction Requirements
- [x] Enable and Disable will make calls to API to update settings
- [x] Success and error toasts will be used to indicate to the user if the request was successful or not
- [x] On Error, the switch should return to the previous state
    - Only change the state in the vuex store if the response is successful

## Final Invision Mockup
~~https://ibm.invisionapp.com/share/EFO0P87G8JA~~
https://ibm.invisionapp.com/share/SGO0QDLQ8VD#/screens

### Screen Capture
![Screen Shot 2020-12-02 at 9.09.55 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/d6fe8e65-f0d6-4578-9eb0-bcbdd33731a2)

## cURL Commands
- [x] TBD
The backend will not be ready for all these changes, but the Redfish API should be updated. https://redfish.dmtf.org/schemas/ManagerNetworkProtocol.v1_4_0.json

IPMI
```
curl -k -v  -X PATCH https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol -d '{"IPMI":{"ProtocolEnabled": false}}'
```

## Notes
- [x] Add to the `Configuration` section of the UI (may need to be moved later)
- [x] New pattern that has a 1px border below each form section
    - [`<hr>` not semantically correct](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr) as the `<hr>` would be used for presentation purposes
    - Create a custom class that applies the border to the bottom of the container

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [x] Tested responsive layout on supported viewport sizes
- [x] Verified functionality works as expected, e.g. success and failure use cases
- [x] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [x] Verified markup is semantic
- [x] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by dixsie** [comment]
resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38891

**Comment by derick-montague** [comment]
@dixsie - Can you create stories for the remaining settings that were not ready to be implemented? We should just need one story to accommodate. Thank you!
