### ISSUE TITLE
PLDM: FRU Parser: implement FRU property extraction

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2068]
Implement a `PLDMFRUParser` class (in new file pldm_fru_parser.cpp) under pldm/. Link this with pldmd in meson.build:

1) The `PLDMFRUParser` should be a template class (will help with unit testing)
2) Production code should instantiate this class with template type `T` = sdbusplus::server::object::object<sdbusplus::xyz::openbmc_project::Inventory::Source::PLDM::server::FRU (see https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Inventory/Source/PLDM/FRU.interface.yaml)
3) The class should have a method `parseFRUTable`, which takes a FRU table. For every record set identifier found in the FRU table, it should construct an instance of `T` (could do a make_unique on unique_ptr<T>). After that, for the properties found in the FRU record, it should map those to D-Bus properties (for the interface in 2) and call the setters of the same on the `T` object. Construction of `T` needs a system bus handle and an object path string. The path can be `/xyz/openbmc_project/pldm/fru_record_set/<record_set_identifier>`.
4) `PLDMFRUParser` should also have an API to let the user access the created objects of type `T`. 
5) The unit test code can construct `PLDMFRUParser` with a mocked class `M`. Using the API described in 4), it should be possible to test that properties of `M` have specific values, based on the test FRU table passed to 3).

**Comment by dkodihal** [comment]
@zaxxed note that there is a `struct pldm_fru_record_tlv` and a `struct pldm_fru_record_data_format` in libpldm/fru.h. These should be useful to you.

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/35594

**Comment by nmuruli** [comment]
Closing this story. The work done here was not used for the Rainier/Everest PLDM support
