### ISSUE TITLE
GUI : FED : Move BMC time to Redfish 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2071]
https://github.com/openbmc/webui-vue/blob/master/src/store/modules/GlobalStore.js#L54

can get the BMC time at /redfish/v1/Managers/bmc

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31293

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31293 merged
