### ISSUE TITLE
GUI : FED : Move host status to Redfish 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2072]
https://github.com/openbmc/webui-vue/blob/master/src/store/modules/GlobalStore.js#L65

Can use 
        "PowerState": {
            "enum": [
                "On",
                "Off",
                "PoweringOn",
                "PoweringOff"
            ], 
at /redfish/v1/Systems/system

**Comment by yoshiemuranaka** [comment]
I guess the UI will have to support showing host status for different backend properties? We'll need to map properties from WebSocket changes and from this api request (I think this GET is only made once on initial application/header load. After that this property is only updated through WebSocket changes). does that sound right @gtmills ?

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31609

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31609 merged
