### ISSUE TITLE
GUI : FED : Move hostname to Redfish 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2073]
https://github.com/openbmc/webui-vue/blob/master/src/store/modules/GlobalStore.js#L45

 curl -k https://${bmc}/redfish/v1/Managers/bmc/EthernetIntefaces/eth0 
...
"HostName": "witherspoon-YL10UF76W015",

Should look at the HostName at all EthernetIntefaces. So a query to /redfish/v1/Managers/bmc/EthernetIntefaces first and then all the EthernetIntefaces. 

curl -k https://${bmc}/redfish/v1/Managers/bmc/EthernetIntefaces/sit0

**Comment by yoshiemuranaka** [comment]
If there are multiple EternetInterfaces, which HostName should be shown?

**Comment by gtmills** [comment]
I think all of them

**Comment by yoshiemuranaka** [comment]
Currently showing hostname on the power operations page. Does it make sense to show ethernet info listed with the hostname here? Or do you think it should be removed from this page?

<img width="618" alt="Screen Shot 2020-04-22 at 7 15 59 AM" src="https://user-images.githubusercontent.com/8097306/79998882-1a42a400-8470-11ea-96a3-2c7f2033e533.png">

**Comment by gtmills** [comment]
The server power operations seems like an odd place for the hostname.. Know why it is there?

**Comment by yoshiemuranaka** [comment]
hostname and ip were included in Angular shown in a 'status' bar. We decided to remove this bar from Vue but brought over the hostname in an attempt not to "lose" any information

![Screen Shot 2020-04-22 at 8 33 46 AM](https://user-images.githubusercontent.com/8097306/80002197-31839080-8474-11ea-8c40-f300061ea1ae.png)

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31708

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31708 merged
