### ISSUE TITLE
PLDM: Mark OCCs active

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2076]
See https://github.com/ibm-openbmc/dev/issues/909#issuecomment-612766845.

**Comment by tomjoseph83** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/31518
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/31027
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/31549

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/31518 merged
