### ISSUE TITLE
eBMC LED Management :: Implement LocationIndicatorActive  property for DASD backplane

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2090]
Implement LocationIndicatorActive   for DASD Backplane resource.. 

So, what will this do : 

1/. Get the corresponding Inventory for this resource
2/. See if there is any Association by name "indicator_led_group".
3/. If so, read the Asserted property: ( for GET )
 Example:  `busctl get xyz.openbmc_project.LED.GroupManager <Data from step-2> xyz.openbmc_project.Led.Group Asserted` 
4/. for PATCH, set to true or false depending on the input

**Comment by vishwabmc** [comment]
@santoshpuranik are these more of Assembly Or the Storage schema ?.. The NVME disk is surely the Storage schema. but what about the DASD backplane ?

**Comment by vishwabmc** [comment]
Need Assembly schema implemented before we can get to this. @santoshpuranik is already working on Assembly schema

**Comment by mzipse** [comment]
Closing.  Work is complete.
