### ISSUE TITLE
phosphor-hwmon failure handling improvements

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2092]
See https://github.com/openbmc/phosphor-hwmon/issues/15.  We need to loosen up error log creation a bit in phosphor-hwmon.

If it turns out we can completely switch to dbus-sensors, then we wouldn't need to do this.

**Comment by spinler** [comment]
We're going all-in on dbus-sensors, so closing.  If  that changes can always reopen.

**Comment by msbarth** [comment]
> We're going all-in on dbus-sensors, so closing. If that changes can always reopen.

Are we? What about handling the OCC sensors?

**Comment by mzipse** [comment]
@spinler Thoughts on Matt's question above?

**Comment by spinler** [comment]
Yea, that was the plan from a meeting we had about it, with the decision that we could still start everything off using phosphor-hwmon.

Along with this issue, the other big issue with hwmon is it only runs when the driver is loaded, so with the power off there would be no redfish sensors for DIMM or CPU temps.  While the code itself doesn't care, people weren't happy with that behavior on witherspoon so we had plans to fix it.

So we'd either have to rewrite hwmon to not be bound to the udev rule, and be able to handle it when the sysfs directory isn't even there, or we put all of our energy into dbus sensors, which will also take some effort to make it work how we want.  We decided to go to dbus-sensors because that's where all the community involvement was, and also it helps us move to entity-manager.

I guess we could ship what what we have now with phosphor-hwmon, and it would just behave like it did on witherspoon.

**Comment by mzipse** [comment]
Thanks Matt.  I assume the stories to address the dbus-sensors is under Epic #2099 .  Correct me if I'm wrong.
