### ISSUE TITLE
GUI : Design : Responsive Header Layout

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2094]
## Use Case
As an OpenBMC user that is using the Web UI either on a small screen, magnified, or resized within the available screen size, I need to be able to easily view and interact with all the items in the primary header, in order to open the small screen navigation, determine the status of my system, and access the profile menu.

## Overview
This story only includes the following content:
1. Hamburger menu
1. Logo or Application name
1. System Error status
1. System Power Status
1. Profile dropdown menu that includes a link to profile settings and a logout action

## Resources
- Slack conversation 
  - https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1588606836248700
  - https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1588075260149800

**Comment by ParishrutB** [comment]
Relevant work done in previous header stories has been added to the following Mural:
https://app.mural.co/t/ibmpower1831/m/ibmpower1831/1584599114329/a0270f5cc047acb22d572faa73d1a5fc763d7a3e

**Comment by ParishrutB** [comment]
Phase 1 ideation and ideas added:
https://app.mural.co/t/ibmpower1831/m/ibmpower1831/1584599114329/a0270f5cc047acb22d572faa73d1a5fc763d7a3e

**Comment by ParishrutB** [comment]
Box folder with sketch wireframes:
https://ibm.box.com/s/iywhcd7vkti92nck9czerlcqkz1ihwqp

**Comment by yoshiemuranaka** [comment]
Is this story complete from a design perspective? @ParishrutB @priyanka-pillai97 @derick-montague

**Comment by derick-montague** [comment]
I thought what @ParishrutB and @priyanka-pillai97 provided worked and we all agreed. I am not sure what, if any, feedback is still required to move forward.

**Comment by yoshiemuranaka** [comment]
Based on the slack conversation it looks like most prefer v3.1

<img width="440" alt="Screen Shot 2020-05-18 at 9 08 30 AM" src="https://user-images.githubusercontent.com/8097306/82235172-3b6ba880-98e7-11ea-90aa-3e6bbc3c6a53.png">

**Comment by derick-montague** [comment]
I think we are ready for impleentation!

**Comment by ParishrutB** [comment]
Invision updated.

<576 px (Extra small)

![image](https://user-images.githubusercontent.com/61419136/82570476-451f3580-9b9f-11ea-9e5f-6d61bb643c63.png)
![image](https://user-images.githubusercontent.com/61419136/82570515-510af780-9b9f-11ea-800a-bcd464e81226.png)

576px to 768 px (Small)

![image](https://user-images.githubusercontent.com/61419136/82570653-81529600-9b9f-11ea-825d-44dfb47a7db4.png)
![image](https://user-images.githubusercontent.com/61419136/82570677-87e10d80-9b9f-11ea-8ee2-3fe8d2cf674a.png)

768px to 992px (Medium)

![image](https://user-images.githubusercontent.com/61419136/82571632-da6ef980-9ba0-11ea-9815-632426331ce8.png)
![image](https://user-images.githubusercontent.com/61419136/82571643-dfcc4400-9ba0-11ea-9523-449709adf990.png)
