### ISSUE TITLE
eBMC LED Management :: PHYP and BMC interface for Non BMC Driveable LEDs(MEX)

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2097]
This will be used track the Work needed to support Non BMC Controlled Indicator LEDs.

Currently, there are 2 thoughts.

- Represent MEX Indicator LEDs as redfish URIs. 
   - That means, create the PDR for all resources
    - Convert the PDR data into D-Bus objects in the Inventory
    - Setup Sensor and Effectors and map them to appropriate D-Bus
    - PHYP to send the latest updates to BMC on those cases that are handled at PHYP layer ( where a card is added on R&V of MEX )

-----------

- Represent all these as bunch of Location codes ( Do we really PDR or fine with static JSON ) ?
    - Some form of PDR representation
    - Creating D-Bus object
    - PHYP to send the latest  updates to BMC on those cases that are handled at PHYP layer ( like for example: a card is added on R&V of MEX )

**Comment by vishwabmc** [comment]
The direction is this :

- PHYP will prepare the MEX FRU PDR and send by BMC
- BMC will consume that FRU PDR and host a D-Bus object in xyz.openbmc_project.Inventory
- PHYP will also send LED PDR to BMC
- BMC will consume that PDR and create association.

------------

We can split this into 2 epics:
- PLDM / PDR work
- LED manager work to create LED D-Bus objects based on the FRU creation.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
