### ISSUE TITLE
Dual-boot: Install both BOOTKERNEL files in single image

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2098]
Need both the PHYP and OPAL BOOTKERNEL installed within a single image so the correct one can be chosen. Maybe just BOOTKERNEL.phyp and BOOTKERNEL.opal? 

Story https://github.com/ibm-openbmc/dev/issues/1606 will ensure a link gets created that points BOOTKERNEL to the correct one based on the user requested setting.

**Comment by mzipse** [comment]
@anoo1 , I thought I had heard that you completed this work?  I could be wrong.  If so, can you post the Gerrit commit here?  Thanks.

**Comment by anoo1** [comment]
This was initially built downstream, and before it was posted upstream in gerrit it was decided it was better to wait for Hostboot for the final implementation of the dual boot instead of having this workaround in the BMC.
