### ISSUE TITLE
Key clear (secure storage policy) Redfish API 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2100]
The GUI will have key clear (on ASMI as secure storage policy), need an API for that. 
Should be a BIOS Attribute

URL: /redfish/v1/ComputerSystem/bios
"Attributes": {

**Comment by gtmills** [comment]
curl -k https://$bmc/org/open_power/control/host0/ClearHostSecurityKeys
{
  "data": {
    "ClearHostSecurityKeys": 0

**Comment by gtmills** [comment]
@ratagupt Will your team own this? 
Does a Redfish Bios attribute work ?

**Comment by mzipse** [comment]
Looks like Hostboot team will own this.  All BIOS settings.  I'll assign to me to ensure this happens.

**Comment by gtmills** [comment]
@mzipse will verify with Hostboot

**Comment by gtmills** [comment]
Done here: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/44525
