### ISSUE TITLE
PLDM: Key clear 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2101]
The GUI will have Key clear. 
The Redfish API for this is #2100 
The Redfish API should be a Bios Attribute

**Comment by gtmills** [comment]
@tomjoseph83 assigned this to you

**Comment by sampmisr** [comment]
@gtmills Pls let us know is this implemented ?

**Comment by gtmills** [comment]
> 
> 
> @gtmills Pls let us know is this implemented ?

No I think we need a design discussion on this

**Comment by nmuruli** [comment]
@gtmills Can you please provide more details on the BIOS attribute or bring it up in one of our design meeting

**Comment by gtmills** [comment]
Done here: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/44525
