### ISSUE TITLE
GUI : Key clear (secure storage policy)

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2102]
## SMEs
**BMC**: Isaac Salem, Jayashankar Padath
CE Login/Admin: @joseph-reynolds 
**PHYP**: Chris Engel

## Summary
This is a feature that part of ASMI that was not included in the initial design.

### Research and Design

This will be a BIOS setting. 

### User Case
As an admin or SSR,  I need to clear the security keys so that:
- any sensitive data is not accessible on the system partitions anymore. 
- to install new keys when the old ones are lost or compromised.
This requires physical authentication at the server so that it is not misused.

### Information Architecture
This should be a separate page. It was initially discussed that it should be on Factory Reset page, but we discovered that the use case can be separate from that for Factory Reset. 
IA: Can be in both Operations and Security. Since there is some overlap with Factory Reset, it was decided to put it in Operations.

### Invision prototype
Admin login: https://ibm.invisionapp.com/d/main#/console/15347903/320046975/preview
Developement driver(CE login): https://ibm.invisionapp.com/d/main#/console/15347903/320046973/preview

## References/Resources
- [ASMI Content Inventory item: 5.23.5](https://ibm.box.com/s/8x7coy8mu25datklqikdozzu3zpny1v6)
- Discovery doc: https://ibm.ent.box.com/notes/835732374444

* This folder is restricted in accordance with GDPR guidelines.

### UX Flow / Interaction Requirements
- "Set factory default" and "Clear all and set genesis IPL" will only be shown for developement drivers and is used only in the lab. This requires a service login. [Reference1](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1627316172015500?thread_ts=1626706374.369600&cid=C0Q6TQP5Z) and [reference2](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1627545295087000?thread_ts=1588709628.377800&cid=C0Q6TQP5Z).
- There is a default option called "Clear None" - ~~this needs to be hidden from GUI.~~
- Remove "System security officer key" shown in mockup
-  ~~"OS_KEYS"~~, <--- clear operating system keys -- do not include or hardcode on F/e

### cURL Commands and Redfish Response
-  `/redfish/v1/Systems/system/Bios`
- [ ] Add cURL commands

Need to verify bios attributes:
```
      {
         "attribute_name":"hb_key_clear_request",
         "possible_values":[
            "NONE", <--- Clear none, default value, add this value in radio button list. Help text: " Key clear not requested"
            "ALL", <---- clear all
            ~~"OS_KEYS"~~, <--- clear operating system keys -- do not include or hardcode on F/e
            "POWERVM_SYSKEY", <---- hypervisor system key
            "MFG_ALL", <---- CE login only - clear all and set genesis IPL
            "MFG" <---- CE login only - Set factory default
         ],
         "default_values":[
            "NONE"
         ],
         "helpText" : "Specifies the requested level of security keys to be cleared from the system, requires a reboot to take effect",
         "displayName" : "Key Clear Request (pending)"
      },
      {
         "attribute_name":"hb_key_clear_request_current",
         "possible_values":[
            "NONE",
            "ALL",
            "OS_KEYS",
            "POWERVM_SYSKEY",
            "MFG_ALL",
            "MFG"
         ],
         "default_values":[
            "NONE"
         ],
         "helpText" : "Specifies the requested level of security keys to be cleared from the system for the current IPL. Do not set this attribute directly; set hb_key_clear_request instead.",
         "displayName" : "Key Clear Request (current)"
      }
```
### Notes
- [ ] [Bios attribute](https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/44525/9/oem/ibm/configurations/bios/enum_attrs.json)
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
This is related to `secure boot`. The Engineering team is planning on workshops during the month of June around `secure boot`.

**Comment by derick-montague** [comment]
>1. Was that just for Openpower boxes?  Or we expecting to provide that on Enterprise systems as well?

Both

> 2.  Would this be a feature on the GUI?……the GUI team thinks it is based on prior discussions.

Yes

> 3. And then who would be authorized to use that Key Clear support?

Admin role

> 4. Lastly, is there a Key Clear support required for both the Host Secureboot AND the BMC Secureboot?  or just the Host Secureboot?

key clear is for host secrets, don’t forsee anything related to BMC at this point

**Comment by derick-montague** [comment]
This issue is blocked by #973 and we need to understand the relation between the two and determine if there is design changes needed in the Power Server operations page.

**Comment by nicoleconser** [comment]
![screenshot_from_2020-09-16_14-53-25](https://user-images.githubusercontent.com/15746733/105770348-afedf100-5f24-11eb-92cf-57a076038299.png)

**Comment by nicoleconser** [comment]
![image](https://user-images.githubusercontent.com/15746733/105770572-fe02f480-5f24-11eb-904c-59bf985de4cb.png)

**Comment by nicoleconser** [comment]
KC documentation - https://www.ibm.com/support/knowledgecenter/P9ESS/p9hby/securestorage.htm

![Screen Shot 2021-01-25 at 3 52 01 PM](https://user-images.githubusercontent.com/15746733/105770784-48847100-5f25-11eb-9d34-1860555ce50c.png)

**Comment by nicoleconser** [comment]
Asked Chris E and Tom J on Slack about this here: 
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1611613747052300

**Comment by priyanka-pillai97** [comment]
Based on the information we found on [Knowledge Centre](https://www.ibm.com/support/knowledgecenter/P9ESS/p9hby/securestorage.htm) and ASMI help text for this particular page, we feel it has a similar use case to that of Factory Reset, which is -
- As an admin, I want to get a clean system, so that for example, I can re-purpose my system. 

Also, it enables the users to perform a secure delete of their data.
Our current hypothesis is that it should be clubbed with a page similar to it and not the boot process.

---
**Reference -** 
![image (12)](https://user-images.githubusercontent.com/61419618/106001959-912f5c00-60d6-11eb-8955-5ce51c32c10a.png)

**Comment by derick-montague** [comment]
Updated milestone to meet dependency milestones

**Comment by dixsie** [comment]
@sandeepasingh116 I updated the story with what each value is above

**Comment by dixsie** [comment]
@sandeepasingh116  if current username == 'service' show CE login options.

**Comment by sandeepasingh116** [comment]
Resolved by :  https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/50248
