### ISSUE TITLE
GUI : FED : Unauthorized Screen - i18n

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2105]
## As Is
The page title is not translated.

## To Be
The page title will be translated.

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/a5a5640d-38bd-49d9-9ebb-f25ab6c29fa1)

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31990

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31990 merged
