### ISSUE TITLE
GUI : FED : Power Server Operations - Warm Reboot refactor

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2109]
## As Is
Orderly restart is called in two actions.

## To Be
With changes to the backend design, we can now make this call in one action.

## References
[Slack conversation](https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1587997741129300?thread_ts=1587916266.121100&cid=GBVDZRCQK)

**Comment by gtmills** [comment]
This work could now be done. The backend support is there today.

**Comment by derick-montague** [comment]
> This work could now be done. The backend support is there today.

The conversation was short and can be found at https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1595870042060400

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35107
