### ISSUE TITLE
LED CallOuts :: PELs having non BMC accessible FRUs

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2111]
In the PEL, If the entry is a Non-BMC accessible FRU, then Turn on SAI.

Basically this story is to handle OS driven callouts

**Comment by spinler** [comment]
@vishwabmc Non-BMC accessible is where we can't find a matching LED group for that callout?

**Comment by vishwabmc** [comment]
> @vishwabmc Non-BMC accessible is where we can't find a matching LED group for that callout?

Correct. Basically, this would be lighting up System Attention Indicator.. 

@derekhoward55 ?

**Comment by derekhoward55** [comment]
Also should turn on the SAI if the callout is an iso procedure and not a fru callout.

**Comment by vishwabmc** [comment]
I don't see this is needed since BMC will handle the PEL generated on BMC + HostBoot and #2050 handles that.

Ones generated by PHYP and OS are handled by them. Meaning, they walk the callout and determine what LED needs to be turned on and they send the request down to the BMC.

@spinler Agree ?

**Comment by spinler** [comment]
@vishwabmc If nothing else, I was going to use this story to put in a call to activate the SAI when it is available, either when not all callouts are hardware callouts, as @derekhoward55  mentioned, or when there was a problem looking up the LED for a FRU  callout.

**Comment by vishwabmc** [comment]
@spinler okay.. 

So you would want to use this for setting Platform SA and use #2050 for actual FRU faults ?

**Comment by spinler** [comment]
@vishwabmc Yea.  If you'd rather we create a new issue for setting the SAI and just close this one that is OK with me.

**Comment by vishwabmc** [comment]
Cancelling this and opening #2479
