### ISSUE TITLE
eBMC LED Management :: Create Interface for initiating LampTest

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2118]
Create an interface for initiating the lamp test for all BMC accessible Indicator LEDs. 

----------------------------------------
- Turn on all BMC accessible Indicator LEDs when property is set to : On
- Turn off all BMC accessible indicator LEDs when property is set to : Off

----------------------------------------

- Need to discuss if this included the CXP ( cable card ) connector LEDs also.

- Does Lamp Test also include system-power LED ?. @derekhoward55 ?
............

**Comment by derekhoward55** [comment]
Green power leds are not included in a lamp test, just service indicators.

**Comment by vishwabmc** [comment]
Using this issue just for the interface .. will create another one for implementation

**Comment by vishwabmc** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/36102/

**Comment by vishwabmc** [comment]
@jinuthomas and I talked about it and he will contain this work. Mostly, it would be a method. Operator Panel daemon is what that defines and implements it.

**Comment by vishwabmc** [comment]
We discussed this in Wednesday design call  and here is the takeaway:
- Interface will be implemented by Panel daemon : https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/36102/

- Every time the method is called , the implementation in Panel will create a D-Bus object. `/xyz/opebmc_project/led/lamptest/<some arbitrary number.`

- ledmanager and all other participants of lamp test will watch for `InterfaceAdded` signal on the path `/xyz/opebmc_project/led/lamptest/`

- Participants when then do their lamp test procedure

- If a a user calls LampTest while one is alerady in progress, the implementation will just create another D-Bus object as if it's a fresh request.

LED Manager will go ahead and now implement the code that will listen on `/xyz/opebmc_project/led/lamptest/`

**Comment by vishwabmc** [comment]
A change in the direction now.. We discussed again ( @santoshpuranik @jinuthomas and I ) and we agree that the right thing to do is to handle this in LED Manager.

LED Manager will implement the LampTest interface and 
- OP Panel daemon will catch the InetrfacesAdded signal and act on it for LCD display
- LED manager will  light physical LED and also send a PLDM command to host

**Comment by vishwabmc** [comment]
This is just fir LampTest interface definition file that is in : https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/36102/

**Comment by vishwabmc** [comment]
It is done now.. Finally, we have decided to go back to `xyz/openbmc_project/led/groups/lamp_test` and then have a custom callback handler which the Group can then invoke
