### ISSUE TITLE
eBMC LED Management :: Handling Partition SA / Platform SA / Real SA

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2120]
The PAPR document mentions these :

Partition SA : Each Partition can have a Virtual Service Action
Platform SA : This is the Service Action on the Platform
Real SA        : The actual result on the Physical SAI

- Need to brainstorm and see if these are really needed and what are the RAS requirements and how is it benefiting the customer.

WIll talk to Justin Thaler / Adam and others.

**Comment by vishwabmc** [comment]
After discussing with Justin ( back then ) and others, it is actually a requirement to support these. I have sent an email to the community asking if any others have a need also.

```
Hello,

Sending this email to get feedback on one of the features that IBM would need to implement and is called "Virtual System Attention Indicator".

*What is a System Attention Indicator ( SAI )* : When an error happens in the system, usually, it is isolated to a part to be replaced and the LED for that faulty part would be turned on.

However, in some cases, it may not be possible to isolate the issue to a particular part. In those cases, IBM systems turn on Amber LED that is mostly at the front of the system and is called "System Attention Indicator".

So, it means, there is some issue in the system and that demands service events to be examined to isolate the part.

Such errors can be detected either by Platform management functionality, BMC; or can be detected by the upper layer partitions. When we turn on the System Attention Indicator, it would be useful to say why it is turned on. As in, is it turned on due to an error seen by BMC or is it due to an error seen by the partition.

If BMC encounters an error that falls under SAI, then BMC will set a virtual SAI, which is nothing but a software setting indicating so and is called "Platform Service Attention".

Similarly, if a partition encounters an error, then a virtual SAI will be set and is called "Partition Service Attention".

So, the Physical SAI LED will be turned on if either of these virtual SAs are on.

Admins should be able to clear these software settings and that would result in clearing the real SAI LED under the cover.

As an addition, Admins can say [I know I have an issue in the system] and would chose to turn off the real SAI LED. In that case, both the virtual SA would be turned off as well.

My current proposal is to have an interface defined in phosphor-dbbus-interfaces depicting these above.

The other thing is representing this in Redfish and I have it posted :

https://redfishforum.com/thread/361/virtual-system-attention-indicator-functional

Is anyone in the community having such a need / would be interested ?.

Thank you,
!! Vishwa !!

```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
This can not be attempted until DMTF releases the `Conditions` as part of `V2020.4`.

**Comment by vishwabmc** [comment]
This will key off of xyz/openbmc_project/led/groups/partition_system_attention_indicator and xyz/openbmc_project/led/groups/platform_system_attention_indicator

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
The idea is still OEM : 

phosphor-led-manager already has : 
  /xyz/openbmc_project/led/groups/partition_system_attention_indicator
 /xyz/openbmc_project/led/groups/platform_system_attention_indicator

=======================================================================

PLDM will be making use of this for Sensor and Effector like this : 

*Sensor  and Effector* : 
```
*Partition_SA* 
    - Path: /xyz/openbmc_project/led/groups/partition_system_attention_indicator
    - Interface: xyz.openbmc_project.Led.Group
    - Property : Asserted
    - Type : Boolean
```
*Sensor  and Effector* : 
```
*Platform_SA* 
    - Path: /xyz/openbmc_project/led/groups/platform_system_attention_indicator
    - Interface: xyz.openbmc_project.Led.Group
    - Property : Asserted
    - Type : Boolean
```

*Clear Physical SAI Effector ( this does not have any sensor )*
    - Path: /xyz/openbmc_project/led/groups/platform_system_attention_indicator &&
    -          /xyz/openbmc_project/led/groups/partition_system_attention_indicator
    - Property : Asserted
    - Type : Boolean

=======================================================================

**Comment by rfrandse** [comment]
refresh

**Comment by lxwinspur** [comment]
reveiw by:
https://github.com/ibm-openbmc/phosphor-led-manager/pull/2
https://github.com/ibm-openbmc/bmcweb/pull/197

**Comment by mzipse** [comment]
@ravindra-srikanth , can you work with @jinuthomas to see if we can close these out?  I'm thinking all these PRs are closed/merged.  If we plan to upstream this code, we should at least mark them "Code Review in Driver".

**Comment by ravindra-srikanth** [comment]
@mzipse , did not see "Code review in Driver" label. Marked it "Downstream".

**Comment by rfrandse** [comment]
tracking in jira
