### ISSUE TITLE
VPD: Redfish: Card VRMs

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2124]
Have VPD for Card VRMs. The board VRMs don't have VPD. 

These Card VRMs also have a LED and a location code.  
Could model as a Chassis since a card..?

@vishwabmc to ask Redfish 

`<link to asking Redfish>`

**Comment by santoshpuranik** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/39574

**Comment by mzipse** [comment]
Closing.  Work is complete.
