### ISSUE TITLE
Redfish: RTC battery 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2126]
Have a location code and LED for the RTC battery. How do we model in Redfish? No VPD for the RTC battery. 

@vishwabmc  to ask Redfish
` <link to asking Redfish>`

**Comment by santoshpuranik** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/39574

**Comment by mzipse** [comment]
Closing.  Work is complete.
