### ISSUE TITLE
Support the Redfish OverwritePolicy LogService property

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2129]
Ideally would at least return 'WrapsWhenFull', which is more or less what IBM does.

Unsure still if we want to allow the customer to change this policy, as it could interfere with how IBM services works.  More thought needed.

**Comment by gtmills** [comment]
We hardcode "WrapsWhenFull"
https://github.com/openbmc/bmcweb/blob/4a0bf539728cada806fc7a16a208edc6332bdb86/redfish-core/lib/log_services.hpp#L1013

**Comment by spinler** [comment]
Closing.
