### ISSUE TITLE
eBMC LED Management :: Implement LocationIndicatorActive property for TPM resource

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2134]
Implement the LocationIndicatorActive  for TPM resource

There is currently: "TrustedModules": in "Systems" schema.. but there are no Indicator LEDs.

@gtmills 

So, what will this do-

1/. Get the corresponding Inventory for this resource
2/. See if there is any Association by name "indicator_led_group".
3/. If so, read the Asserted property: ( for GET )
 Example:  `busctl get xyz.openbmc_project.LED.GroupManager <Data from step-2> xyz.openbmc_project.Led.Group Asserted` 
4/. For PATCH, set to true or false depending on the input

This will be Assembly

**Comment by gtmills** [comment]
We should ask Redfish is they are interested in adding VPD and LED to TrustedModule. If not will implement as a chassis. See https://github.com/ibm-openbmc/dev/issues/2123

**Comment by vishwabmc** [comment]
We decided that it will be an Assembly.. We don't have an interface yet. May be xyz.openbmc_project.Item.Assembly ?.. and then need to add support in Redfish for Assembly schema

**Comment by vishwabmc** [comment]
Need Assembly schema implemented before we can get to this. @santoshpuranik is already working on Assembly schema

**Comment by mzipse** [comment]
Closing.  Work is complete.
