### ISSUE TITLE
eBMC LED Management :: Implement LocationIndicatorActive property for VRM resource

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2135]
Implement the LocationIndicatorActive for VRM resource ( The VRM in question now is processor VRM )

Currently. not seeing how this is represented.. @gtmills

**Comment by gtmills** [comment]
This includes VRM on the board? or just Card VRMs?
See https://github.com/ibm-openbmc/dev/issues/2124

**Comment by vishwabmc** [comment]
MRW gives these entries for VRMs.

/system/chassis/motherboard/vdd-vrm-connector0/vdd-vrm
/system/chassis/motherboard/vdd-vrm-connector1/vdd-vrm

/sys-0/node-0/nisqually-0/led-cpu0-vrm-0
/sys-0/node-0/nisqually-0/led-cpu1-vrm-1

**Comment by gtmills** [comment]
@vishwabmc What are those VRMs exactly ?

**Comment by vishwabmc** [comment]
This is in Assembly:

The `fault" will be handled as part of "healthRollUp" functionality #2411 

So, what will this do : 

1/. Get the corresponding Inventory for this resource
2/. See if there is any Association by name "indicator_led_group".
3/. If so, read the Asserted property:
 Example:  `busctl get xyz.openbmc_project.LED.GroupManager <Data from step-2> xyz.openbmc_project.Led.Group Asserted` 
4/. if value from previous is [true], set this new led property in redfish. Else. don't

**Comment by vishwabmc** [comment]
Need Assembly schema implemented before we can get to this. @santoshpuranik is already working on Assembly schema

**Comment by mzipse** [comment]
Closing.  Work is complete.
