### ISSUE TITLE
Redfish: Implement SerialInterface schema

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2137]
SerialInterface is "The SerialInterface schema describes an asynchronous serial interface, such as an RS-232 interface, available to a system or device.". 

It is modeled under Manager ( /redfish/v1/Managers/{ManagerId}/SerialInterfaces/{SerialInterfaceId} ).

Justin Thaler  
the physical serial port we have on Rainier. We'll be using it in the ESS solution with OPAL mode.

Justin Thaler  
the description of the port would have to be put in the MRW, not sure how the BMC can figure that out programmatically otherwise

**Comment by gtmills** [comment]
@joseph-reynolds Are you okay pushing this out of GA ?

**Comment by rfrandse** [comment]
tracking in jira
