### ISSUE TITLE
GUI : FED : Add confirmation modal for batch delete local users

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2140]
## As Is
Currently no confirmation modal when batch deleting users from the local user table.

## To Be
Add confirmation modal when users attempting batch delete to be consistent with other delete actions

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31912

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31912 merged
