### ISSUE TITLE
eBMC LED Management :: Implement LocationIndicatorActive property for RTC Battery resource 

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2145]
Implement LocationIndicatorActive for RTC Battery resource.

**Comment by vishwabmc** [comment]
Ref: https://github.com/ibm-openbmc/dev/issues/2126

**Comment by vishwabmc** [comment]
This will be Assembly

The `fault" will be handled as part of "healthRollUp" functionality #2411 

So, what will this do : 

1/. Get the corresponding Inventory for this resource
2/. See if there is any Association by name "indicator_led_group".
3/. If so, read the Asserted property:
 Example:  `busctl get xyz.openbmc_project.LED.GroupManager <Data from step-2> xyz.openbmc_project.Led.Group Asserted` 
4/. if value from previous is [true], set this new led property in redfish. Else. don't

**Comment by vishwabmc** [comment]
Need Assembly schema implemented before we can get to this. @santoshpuranik is already working on Assembly schema

**Comment by mzipse** [comment]
Closing.  Work is complete.
