### ISSUE TITLE
BMC-Host IPL co-ordination

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#215]
High level epic to track all BMC side requirements  related to boot the POWER processor. 

Requirements:
        - Initialize parameters required for SBE/Core.
        - Existing mechanism is IPMI watchdog from BMC . review this flow.
        - Add support for monitoring and  managing host errors.
        - Limit the BMC-Host sync points.
        - Reconfigure loop - Review this path, looking for simple design here to support this.
        - SBE/Host error management ( TI , error logs).
        - Power management function distribution between Host/BMC.
        - Add support for  istep based IPL.
        - Add support for MPIPL.

**Comment by ojayanth** [comment]
IPL initialization from BMC.
      - core mask ,
      - IPL Modes
      - RISK level
      - SMF enabled or not.
      - Memory synchronized mode
      - PCI reference clock
      - Clock mux settings.
      - Slave/master core info
      - Setting effective Fabric/HRMOR/effective id, memgroups  - BMC need to know the group ID info. for HRMOR calculation
      - GARD record information.
      - Wrap test related info.- need more discussion
      - MPIPL related info 
       Discussion points: Keeping HRMOR info in SBE:   BMC  doesn’t need HRMOR value for  getmem  operation  also HB debug tools going to be simple  with this approach. Need to follow up with SBE team on this.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Added some story points to cover this work since no story points were added previously.
