### ISSUE TITLE
eBMC LED Management :: Use CEREAL to save / restore the current state of asserted groups

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2151]
Today's LED Manager daemon, does not store the current state of groups.  This story is to add that support.

- Call store() when the request comes to add to ( remove from ) asserted group.
   - Basically, the JSON will have names of asserted groups.
- Call restoreGroups() as part of starting LED Manager daemon
   - This will restore the names of the groups and then constructs the asserted group
   - Drives the indicator LEDs

**Comment by lxwinspur** [comment]
review:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-led-manager/+/32104
