### ISSUE TITLE
GUI : Event Logs: Remote Logging Server

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2155]
## Overview
Ability to add, edit, and remove remote logging server Hostname/IP address and Port values from the Event logs page.
**Can't be added until available in Redfish.**

## Interaction requirements
- [ ] If no remote logging server is stored, user should see an option to `Add server`
- [ ] Clicking `Add server` will trigger a modal with Remote logging server form
- [ ] Both `Hostname or IP Address` and `Port` fields are required with standard form validation patterns
- [ ] Once added the Hostname/IP Address should display under the `Remote logging server` label with icons to edit (pencil) or delete (trashcan)
- [ ] Clicking edit (pencil) icon will trigger a modal with the same form but with the values pre-filled. The primary modal action should be `Save`.
- [ ] Clicking delete (trashcan) will trigger a confirmation modal to confirm the delete action–if confirmed, delete server information and show the option to `Add server` again
 

## CURL Commands
```
N/A
```

## InVision Link
https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/screens/319541134_01-Event-Logs-06

## Resources
- Redfish documentation: N/A
- Original AngularJS implementation https://github.com/ibm-openbmc/dev/issues/456

## Screenshots
Vue redesign
![01-event-logs-05@2x](https://user-images.githubusercontent.com/8097306/81861718-8a978f00-951d-11ea-9838-8d4c6269e2ab.png)

Current AngularJS
![81982192-47552300-95e6-11ea-8be0-ae087d199cbc](https://user-images.githubusercontent.com/8097306/82386667-cfbe3400-99e9-11ea-9ea1-6564eff41376.png)
![81982208-4de39a80-95e6-11ea-9a83-2ed2f19ea66a](https://user-images.githubusercontent.com/8097306/82386677-d6e54200-99e9-11ea-874c-a224deffab78.png)

**Comment by derick-montague** [comment]
There is an assumption that this might be included in #1288. @gtmills expressed some concern with adding this to the alerts page. This story may require some research and design.

**Comment by rfrandse** [comment]
tracking in jira
