### ISSUE TITLE
GUI : FED : Event Logs - Resolve event

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2156]
## SME
**Designer**: @ParishrutB 
**BMC Engineer**: @spinler 

## Overview
There have been several changes to the event logs schema in Redfish. These changes needed to be implemented based on the mock up provided by the design team.

## Acceptance Criteria
- [x] Users should be able to sort the table by a 'Status' (Resolved or Unresolved) items
- [x] Users can filter table data by 'Status' (Resolved or Unresolved)
- [x] Users can select one, some, or all entries and have the option to 'Resolve' or 'Unresolve' using batch actions
- [x] Users can resolve an entry by clicking an action item in the row
- [x] Keyboard users will be able to interact with the modal after selecting to resolve the action
- [x] Keyboard focus should return to the element that triggered the modal. 
- [x] If the action was a batch action, the focus should start at the top of the table
- [x] Success/error toasts should indicate backend success/error
- [ ] User can download the PEL associated with the event log entry (will be completed in #3214)

## cURL Commands
```
~$ curl -i -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Systems/system/LogServices/EventLog/Entries/1
{
  "@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/1",
  "@odata.type": "#LogEntry.v1_8_0.LogEntry",
  "Created": "1970-01-01T00:01:09+00:00",
  "EntryType": "Event",
  "Id": "1",
  "Message": "xyz.openbmc_project.Common.Device.Error.ReadFailure",
  "Modified": "1970-01-01T00:01:09+00:00",
  "Name": "System Event Log Entry",
  "Resolved": false,
  "Severity": "Critical"
}%
after marked the log as resolved on webpage OR use the redfish commond:
~$ curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Resolved": true}' https://${bmc}/redfish/v1/Systems/system/LogServices/EventLog/Entries/1
~$ curl -i -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Systems/system/LogServices/EventLog/Entries/1
{
"@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/1",
"@odata.type": "#LogEntry.v1_8_0.LogEntry",
"Created": "1970-01-01T00:00:57+00:00",
"EntryType": "Event",
"Id": "1",
"Message": "xyz.openbmc_project.Common.Device.Error.ReadFailure",
"Modified": "1970-01-01T00:03:05+00:00",
"Name": "System Event Log Entry",
"Resolved": true,
"Severity": "Critical"
}
```

## InVision Link
New https://ibm.invisionapp.com/d/main#/console/15347903/319961625/preview
**Updates:** 
1. 'Export all' and 'Delete all' buttons - Copy update
2. 'Export' batch action - Copy update

Old https://ibm.invisionapp.com/d/main#/console/15366764/319943597/preview

### Notes
- Mockup doesn't include the option to 'Unresolve' during a batch action. 'Unresolve' should be included in development

**Comment by derick-montague** [comment]
May push to A.1.211

**Comment by derick-montague** [comment]
Waiting on: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/39877

**Comment by derick-montague** [comment]
> Waiting on: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/39877

This is merged and @gtmills will keep us informed of when it is in a driver.

**Comment by derick-montague** [comment]
@dixsie Do you want to pick up this story? I think @sandeepasingh116 can pick up #3070

**Comment by derick-montague** [comment]
@dixsie - Looks like these are in the driver. i was looking at the Redfish API on W70 and all the properties seem to be there.

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/42838

**Comment by derick-montague** [comment]
@dixsie - It looks like all FEDs are assigned to review this story. Could you work with the team to determine who the CC'd people should be?
