### ISSUE TITLE
Pdata:  Build infrasture updates to support multi-config

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2159]
Extend the pdata  DTB build infrastructure to generate system specific  DTB file based on MRW files.

**Comment by ojayanth** [comment]
Op-build related changes are tracked by. https://github.ibm.com/phal/pdata/pull/27.
This issue will be used to track BMC standalone related changes with new op-build design to support Multi-config

**Comment by RameshIyyar** [comment]
**Background:**

Currenlty, the generation of device tree will support for only one system based on supplied system mrw xml in SYSTEM_MRW_XML environment variable. To enable multi-config feature (single image need to support different varient of systems which are built based on same host processor) pdata need to support device generation for multiple system but pdata build infrastructure will produce single hard-coded device tree name and it difficult to get system specific device tree so, removing current device tree generation recipe from makefile and added custom build recipes (build, install, uninstall and clean) rules and it will be used based on feature flag so, that consumer can simply use standard automake commands to achieve those steps.

The multiple device tree are generated based on given systems mrw xml
file path in SYSTEMS_MRW_XML environment variable.

**TestedBy:**

- To configure device tree generation
  - ./configure ${CONFIGURE_FLAGS} --enable-gen-dynamicdt CHIP=p10

- To build:
  - make EKB=pub-ekb/ \
    SYSTEMS_MRW_XML="rainier-xml/Rainier-2U-MRW.xml \
    rainier-xml/Rainier-4U-MRW.xml"

- To install:
  - make install or make install-gen_dt

- To clean:
  - make clean or make clean-gen_dt

- To uninstall:
  - make uninstall or make uninstall-gen_dt

**Patches:**
   Patches are available in downstream openPOWER and openBMC for above story.
**pdata:** 
- [Refactored the tools to enable multi-config feature](https://github.ibm.com/phal/pdata/pull/29)
- [Enabled Multi-Config feature](https://github.ibm.com/phal/pdata/pull/32)

**openPOWER:**
-  [Added support for multi-config feature](https://github.ibm.com/open-power/op-build/pull/485)

**openBMC:**
- [Added multi-config support](https://github.ibm.com/openbmc/openbmc/pull/584)
