### ISSUE TITLE
Host VPD Management

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#216]
BMC owns the VPD management due to the Standby VPD  support. 
Provide a host interface to read/update VPD from Host.
Additional information for Host requirements:
      No memory specific VPD updates in the  checkstop path , line repair info updates into VPD.
      A/O -bus repairable errors , provide mechanism to save repair data into VPD.
      Runtime advance  functions still use the VPD updates if required to save repair info.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@ojayanth , I assume you are expecting @santoshpuranik team to own this?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
@mzipse  agreed. Based on  new design direction work is tracked under @santoshpuranik .
closing this epic now.
