### ISSUE TITLE
eBMC GUI : Trusted Platform Module (TPM)

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2168]
## SMEs
**BMC**: TBD
**PHYP**: Chris Engel
**Security**: Joseph Reynolds
**ASMI**: Jayashankar Padath

## Background
- 

## Questions
- Is this needed in the GUI? 
- What all is needed in the GUI? 
- How might this be used? 
- What value does TPM have, to which users? 

## References/Resources
-

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
