### ISSUE TITLE
Host Error handling

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#217]
Need to provide support for PEL type error log natively from BMC.
    - Currently BMC puts esel blob as part of the BMC error log and one callout supported.
    - Looking for detailed  error handling from BMC side , like Bus/fru callout and other related info.x
    - BMC is responsible for adding FRU callout and location code in the HB error log.
    - BMC is responsible for handling BUS specific error handling , FRU,cable callouts.
    - PE required consistency in the error log to use there custom tools.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@spinler I wonder if this Epic is a duplicate of some of the Epics that you created?

**Comment by spinler** [comment]
Yea, I would say https://github.com/ibm-openbmc/dev/issues/400 and https://github.com/ibm-openbmc/dev/issues/401 and maybe others

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@ojayanth , I'd like to close this and reference #755, #756 and #401 .  Assuming you agree, please close.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Closing this one.  covered elsewhere.
