### ISSUE TITLE
eBMC GUI : Network Services

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2170]
## SMEs
**BMC**: @ratagupt 
**PHYP**: Tom Burks
**RAS**: Justin Thaler

## Overview
Network Services is new navigational section listed under `Configuration`. It includes the following items:

5.1.1: ~~Port Assignments~~ (Out of scope)
5.1.2: ~~Network Access~~ (Out of scope - Dean / Maury - 3/21)
5.1.3 ~~Ethernet over USB to Host Enablement~~ (Out of scope)

## Use Case
TBD

## References/Resources
- eBMC Feature Item: 5.1
- feature discovery folder: 
- user research notes*: 
- user research synthesis: 

* This folder is restricted in accordance with GDPR guidelines.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
