### ISSUE TITLE
phosphor-regulators: Implement D-Bus method to reload config file

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#2172]
Currently the phosphor-regulators application reloads the config file when a SIGHUP signal is sent.  This works but has the following downsides:

* Primary use case is a hardware team member who might not be a Linux expert.  Requires using `ps` to find the regulators application PID and then sending the correct signal.  Relatively easy to send the wrong signal (e.g. SIGKILL) or to kill the wrong process (PID typo).
* Dependent on implementation of systemd, dbus, and the associated bindings whether the signal handler can occur while in the middle of another operation such as configuring regulators.  This must not happen.
* Differs from regsctl interface used to initiate regulator configuration or monitoring.

The regsctl tool should be enhanced to provide a new command line option to specify that the phosphor-regulators application should reload the JSON config file.  This would be used instead of SIGHUP.

**Work Required**
regctl changes:
* Add a new --reload or --reload-config-file option.
* Call a new private D-Bus method to reload the config file.

phosphor-regulators changes:
* Add support for new private D-Bus method to reload the config file
* Remove code associated with the SIGHUP signal handler

**Comment by msbarth** [comment]
You dont need to find the PID first, you can issue a SIGHUP to any service using `systemctl`

i.e.) `systemctl kill -s HUP phosphor-regulators.service`

**Comment by smccarney** [comment]
> You dont need to find the PID first, you can issue a SIGHUP to any service using `systemctl`
> 
> i.e.) `systemctl kill -s HUP phosphor-regulators.service`

Thanks Matt.  You are right that is better.

I was still hoping to make this a regsctl action though to avoid a SIGHUP occurring in the middle of a configure or monitor operation.

I thought you were making reference to that in your comment on the end-to-end test plan:

> Verify config file not re-loaded after poweron issued when given a SIGHUP?

**Comment by msbarth** [comment]
> I was still hoping to make this a regsctl action though to avoid a SIGHUP occurring in the middle of a configure or monitor operation.

I dont see how having a regsctl action would help or be any different functionally in the end for inhibiting a user from issuing a reload of the configuration in the middle of configure or monitor. The check to see if configure had been run or currently monitoring is enabled will still have to happen on either path to have the regulators configuration be reloaded or not. If a SIGHUP is sent, within the callback handler, you can add an ability to check the state in which phosphor-regulators is running, which you'd have to do using `regsctl` also, and then decide whether to accept the configuration reload or not. So why not use the standardized way performing this config reload by using SIGHUP.

> I thought you were making reference to that in your comment on the end-to-end test plan:
>> Verify config file not re-loaded after poweron issued when given a SIGHUP?

No, I was referencing verifying the same functionality I described above where the SIGHUP callback handler contains logic to prevent a configuration reload after a system is powered on. At any point, whether a SIGHUP is async or not(as you mentioned this being a possible concern someday), the ability to check the state in which phosphor-regulators is running should be checked prior to reloading the configuration in that handler function.

It seems to me, maybe this issue should instead focus on implementing the necessary checks after receiving a SIGHUP to make sure the config file is not reloaded after a poweron?

**Comment by smccarney** [comment]
In talking with Matt and Brad Bishop, I think this can be closed.
* Matt provided an easier way to deliver the signal.  I'll update the documentation to use that.
* Brad confirmed that the way Matt implemented the signal listener should be synchronous with other D-Bus interactions.  There should not be a danger of an asynchronous signal handler occurring in the middle of some other operation.
