### ISSUE TITLE
phosphor-regulators: Validate config files during CI

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#2176]
The phosphor-regulators application is controlled by a JSON configuration file.  The file name is selected at run time based on a D-Bus property.

All the supported config files are checked into the phosphor-regulators/config_files directory.

If a config file contains any errors, it will cause the phosphor-regulators application to fail at run-time.

For this reason, the validate-regulators-config.py tool should be run during CI on all the files in the config_files directory to make sure they are valid.

This should be implemented by creating a 'run-ci.sh' script in the phosphor-regulators/test directory.

Place where run-ci.sh is called by CI:
* https://github.com/openbmc/openbmc-build-scripts/blob/38356643280ba6c38c03050e7d4a0b9673c5ea7b/scripts/unit-test.py

Example run-ci.sh script from phosphor-logging repo:
* https://github.com/openbmc/phosphor-logging/blob/master/extensions/openpower-pels/registry/run-ci.sh

**Comment by bobkingkkp** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/37782
