### ISSUE TITLE
eBMC LED Management :: Lamp Test :: Redfish enablement for request initiation

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2179]
Current standard redfish does not look to have a way that can represent LampTest. So, we need to do the OEM way.

Since LampTest is at System Level, the proposal is to have a OEM defined under ComputerSystem resource and then implement that for initiating the LampTest.

**Comment by gtmills** [comment]
@vishwabmc You should ask Redfish first if they are interested in adding

**Comment by vishwabmc** [comment]
I have posted https://redfishforum.com/thread/344/lamptest-functionality-system-schema

**Comment by vishwabmc** [comment]
It was decided that it's a OEM functionality. In the slack discussion, we agreed on putting this as OEM under SYSTEMS schema since LampTets is at system purview

**Comment by vishwabmc** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/36102/ is the interface definition file under review

**Comment by vishwabmc** [comment]
This can be split into 2 tasks

- OEM extension enablement
- Making the actual call to D-Bus API.

For now, task-1 can be done. For task-2,  we need to wait for skeleton implementation once the interface definition file is merged.

**Comment by vishwabmc** [comment]
@gtmills FYI ^

**Comment by vishwabmc** [comment]
@jinuthomas and I spoke about this and he will contain this work as part of handling LampTest from Operator Panel daemon.

His squad will contain representing this in Redfish.

I did some of the discussions with @gtmills and others on this and we believe redfish just returns HTTP: 200 as [OK]. I don't see HMC monitoring the status of lamp test. So, no need to create 202 and then a task-id etc

**Comment by vishwabmc** [comment]
Change in direction. This will be hosted by LED Manager

**Comment by vishwabmc** [comment]
The bmcweb interface would anyway be the same. it would be OEM Extn under ComputerSystems ( systems.hpp )schema

A new thought in bmcweb direction as-well. We don't need HTTP:202 and a task ID. it would be a simple `GET/PATCH` on a property. I am working on fitting that request into `Led_Manager` to see if we can contain that.

**Comment by vishwabmc** [comment]
We can get started with defining OEM handler as Step-1 and we can then make a call to property.

**Comment by vishwabmc** [comment]
We have now moved with the direction of using `/xyz/openbmc_project/led/groups/lamp_test` for this feature. So, bmcweb, would set the `asserted` property of `/xyz/openbmc_project/led/groups/lamp_test to `true` as part of `PATCH`. Similarly, it Ould also set `asserted` to `false` if the request is to `stop-the-test`

**Comment by vishwabmc** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38957

**Comment by vishwabmc** [comment]
It has been pulled down-stream and was enabled with update to bmcweb_%.bbappend.

    1: Start the lamp test:
       curl -k -H "X-Auth-Token: $token" -X PATCH
       https://${bmc}/redfish/v1/Systems/system -d
       '{"Oem":{"IBM":{"LampTest": true}}}'
    
    2: Make sure D-Bus object is updated
       busctl get-property xyz.openbmc_project.LED.GroupManager
       /xyz/openbmc_project/led/groups/lamp_test
       xyz.openbmc_project.Led.Group Asserted
       b true
    
    3: Stop the lamp test:
       curl -k -H "X-Auth-Token: $token" -X PATCH
       https://${bmc}/redfish/v1/Systems/system -d
       '{"Oem":{"IBM":{"LampTest": false}}}'
    
    4: Make sure D-Bus object is updated
       busctl get-property xyz.openbmc_project.LED.GroupManager
       /xyz/openbmc_project/led/groups/lamp_test
       xyz.openbmc_project.Led.Group Asserted
       b false
    
    5: Update D-Bus property
       busctl set-property xyz.openbmc_project.LED.GroupManager
       /xyz/openbmc_project/led/groups/lamp_test
       xyz.openbmc_project.Led.Group Asserted b true
    
    6: Make sure Redfish sees it.
       curl -k -H "X-Auth-Token: $bmc_token" -X GET
        https://${BMC_IP}/redfish/v1/Systems/system
    
      "Model": "9105-42A",
      "Name": "system",
      "Oem": {
        "@odata.type": "#OemComputerSystem.Oem",
        "IBM": {
          "@odata.type": "#OemComputerSystem.IBM",
          "LampTest": true
        }
      },
