### ISSUE TITLE
PLDM File IO: Implementing directory lookup

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2181]
Part 1)

- Enhance https://github.com/openbmc/openbmc/blob/master/meta-ibm/recipes-phosphor/pldm/pldm/fileTable.json to work with directories. Something like:
```
   {
      "directory":"/var/lib/pldm",
      "file_traits":4
   }
```

- Process "directory"s at the end. Meaning first process "path"s from the JSON, which is what https://github.com/openbmc/pldm/blob/master/oem/ibm/libpldmresponder/file_table.cpp#L14 does. Note all the pathnames processed this way. Ignore these if they show up while iterating a directory. Iterate directories using C++ FS API and reuse the code in FileTable::FileTable() to construct the file table

- Enhance https://github.com/openbmc/pldm/blob/master/oem/ibm/test/libpldmresponder_fileio_test.cpp#L27 to unit test "directory" parsing.

Part 2)

- Implement fileTable parsing in pldmtool, by issuing the GetFileTable command.

**Comment by JolieKu** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/34793

**Comment by msbarth** [comment]
From gerrit change https://gerrit.openbmc-project.xyz/34793

Deepak: "Since this has been put up, there have been discussions (at IBM) to continue looking at specific PLDM files that can be specified via a JSON config. Those discussions are still ongoing, but it is clear that this commit isn't needed now."

**Comment by mzipse** [comment]
@tomjoseph83 , you had targeted for 1Q21 timeframe to work on this.  Do you think there is still work for this Issue?
