### ISSUE TITLE
Update psu poll rate

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2182]
Use standard 1 second psu poll rate instead of reading from non-entity_manager config file.

**Comment by jjaymeyer** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/34154

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/34154 merged

**Comment by jjaymeyer** [comment]
Downstream update still required to complete this issue.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/34154 merged
