### ISSUE TITLE
PLDM: Implement construction of state sensor PDR

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2184]
This should be similar to how the BMC PLDM stack constructs effecter PDRs today : JSON driven, and consuming data from D-Bus objects.

State Sensor PDR is defined in DSP0248 v1.2.0, section 28.6.

**Comment by lxwinspur** [comment]
review:
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/32106
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/32108
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/32109
