### ISSUE TITLE
PLDM: Implement GetStateSensorReadings

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2186]
Includes libpldm and libpldmresponder work. Depends on #2184.

Section 20.2 from DSP0248 v1.2.0.

**Comment by lxwinspur** [comment]
review:
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/32357
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/32358
