### ISSUE TITLE
ECMD-PDBG : Enable Scom support for all the targets 

### ISSUE THREAD

**Issue by lkammath** [ibm-openbmc/dev#2187]
ECMD work split up:

* Modify the ecmd-pdbg internal table 
->Use pdbg_target_path() to select path from the device tree  
->Use pdbg_address_absolute() to get the absolute address instead of existing hardcoded logic which takes Processor chip as default (https://github.com/open-power/ecmd-pdbg/blob/master/src/dll/edbgEcmdDll.C#L1085)

Optional work: 
* ECMD_PDBG to get rid of its local device  tree manipulation/handling and depend on PDBG to do it 
- Instead of doing mmap -> https://github.com/open-power/ecmd-pdbg/blob/master/src/dll/edbgEcmdDll.C#L278 replace it with 
-- the whole function should just call pdbg_targets_init(NULL) and be done with it
-- We might also want to call pdbg_set_backend() 

Test vehicle: P9 or P10

**Comment by ojayanth** [comment]
Sizing includes testing effort. Code impact is minimal.

**Comment by lkammath** [comment]
https://github.com/open-power/ecmd-pdbg/pull/49 - Closed
https://github.ibm.com/phal/ecmd-pdbg/pull/2/ - Under review

Tested on p9 and p10

Included the option work as well

**Comment by lkammath** [comment]
Both integrated to respective ecmd-pdbg repo. can be marked closed once available in the 1020 build
