### ISSUE TITLE
PFP::watchdog

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2188]
Install the fan watchdog on Rainier using the same services used on Witherspoon and configure to protect the fan control and monitor service with the watchdog.

**Comment by msbarth** [comment]
The fan watchdog recipe and service files are very Witherspoon centric. These need to be de-coupled from being specific for Witherspoon so they can be bbappended and applied to Rainier.

**Comment by msbarth** [comment]
I've split the fan watchdog recipe up and have created configs for Witherspoon, Swift, Tacoma, and Rainier. In the process of building each of these images to verify the image contains the expected config files. I've spot checked the Witherspoon image on hardware and will attempt to spot check the Tacoma image before pushing to gerrit.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/32201

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/32201 merged
