### ISSUE TITLE
Design the Redfish Event Monitor

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2189]
Need to come up with the design, how to do event filtering and monitoring.
There could be the following ways
- D-bus based approach(need to handle the following cases

         [ ] one to one mapping of D-Bus Resource and Redfish resource
                  eg: User, Network etc    
         [ ] one to many mapping of Dbus Resource to Redfish Resource
                  eg: 
         [ ] many to one mapping of Dbus Resource to Redfish resource
                 eg: Computer System
         [ ] Redfish resources which don't have Dbus Resource
             eg: Task
         [ ]  Need Reverse mapping also where Dbus Resources/properties need to map to the Redfish Resources.

- Can we some extension mechanism through phosphor-logging?

**Comment by ratagupt** [comment]
We have delievered this in downstream but we need to do more work to make it upstream.Let's keep it open but change the milestone.
We can do this later.

**Comment by sunharis** [comment]
Not in scope for GA1
