### ISSUE TITLE
Generic Infra for reading and updating the MAC address

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2190]
Currently, we have a script(first-bootsetmac) which reads the MAC address from the inventory and updates the MAC address to the system.
There is a service dependency on the inventory service, now with rainier, the inventory service has become templatized so that makes service dependency bit complicated.

With this story, we have the following task to achieve.
- create a JSON file having mapping of inventory object to the system ethernet interface object
- Service would monitor for the interface added signal on the inventory D-bus object which implements an inventory mac-address interface.
- After receiving the signal, look for the mapped Ethernet interface from the JSON and update the MAc address of the system ethernet interface.

**Comment by manojkiraneda** [comment]
Code is already merged in master. Following are the upstream commits.

https://gerrit.openbmc-project.xyz/33882
https://gerrit.openbmc-project.xyz/32514
https://gerrit.openbmc-project.xyz/32124
https://gerrit.openbmc-project.xyz/33859
https://gerrit.openbmc-project.xyz/33758
https://gerrit.openbmc-project.xyz/32534
https://gerrit.openbmc-project.xyz/32516
https://gerrit.openbmc-project.xyz/32126
