### ISSUE TITLE
PLDM: Implement a Host FRU Handler

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2192]
Implement a HostFRUHandler class, which will be constructed by the HostPDRHandler (this actual construction is outside the scope of this story).

Implement two methods in the HostFRUHandler class:

- fetchFRURecordTableMetadata()
a) This should use `pldm_send_recv` to send the GetFRURecordTableMetadata command to the host firmware, and process the response, by noting the following as class members - FRUTableLength, Total number of Record Set Identifiers in table and Total number of records in table.
b) Can unit test for example by having a function (that can be given mocked inputs or the function can be a non-member) takes in the FRU Table metadata response, and the unit test can verify specific class members (as specified in a) are set.

- fetchFRURecordTable()
a) This should use `pldm_send_recv` to send the GetFRURecordTable command to the host firmware. It should then use the information from a) to pass on the FRU table to the APIs being developed in #2068. It is outside the scope of this story to what happens after receiving a response from the APIs from #2068.
b) Since unit tests are being written in #2068, most likely nothing needed here in terms of UT.

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/35648

**Comment by nmuruli** [comment]
Closing this story. We did not use the work done here for Rainier/Everest PLDM support
