### ISSUE TITLE
Redfish: Make Health rollup work 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2194]
A design for health rollup is at 
https://github.com/openbmc/docs/blob/0dc13146cdf4c7321b6fde4654ffd1aae16a7cbe/designs/redfish_health_rollup.md
and implemented at
https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/health.hpp

Health rollup should work for Chassis, System, and Manager

**Comment by gtmills** [comment]
IPS is doing work here for this: https://github.com/ibm-openbmc/bmcweb/pull/81

**Comment by patelabhishek9893** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/107

**Comment by mzipse** [comment]
Work is complete.  Closing.
