### ISSUE TITLE
GUI : FED : Add last refreshed timestamp in header

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2199]
## Overview
The Angular app has a timestamp in the header to show when page data was last refreshed. This story should determine whether or not the timestamp is still necessary. If so, confirm that proposed toolip design is still appropriate. (Add screenshots/InVision links when provided by design)

## InVision link
N/A

## Notes 

- Currently in Vue, data is re-fetched when clicking the 'Refresh' icon in the header, manually refreshing in browser, or navigation to a new page. The timestamp would need to be updated for each of these usecases

## Screenshots
Angular

![Screen Shot 2020-05-14 at 10 39 19 AM](https://user-images.githubusercontent.com/8097306/81967232-7dd37380-95cf-11ea-98bd-4719e245b960.png)

Currently in Vue

<img width="456" alt="Screen Shot 2020-05-14 at 10 44 28 AM" src="https://user-images.githubusercontent.com/8097306/81967533-e7ec1880-95cf-11ea-8b2c-e92fe1ac2eb7.png">

**Comment by derick-montague** [comment]
Determined at GUI Design workgroup on 6/10/20 that this feature is not needed.
