### ISSUE TITLE
HW DUMP: Host Processor  hardware debug data collection

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#220]
This is High level epic to track all BMC side requirements related to MPIPL and HW dump.

**Comment by dkodihal** [comment]
Should we at least expand MPIPL here?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
This Epic is used to track Host Processor hardware data collection packaging support related changes in BMC

**Comment by bradbishop** [comment]
> Should we at least expand MPIPL here?
yes please!

**Comment by ojayanth** [comment]
Just updated the heading .

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Already created multiple epics in this area based on functional scope.

**Comment by mzipse** [comment]
refresh
