### ISSUE TITLE
GUI : FED : Add link to app header status icons

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2200]
## Overview
The status items in the application header need to be links to pages. They currently do not link to anything.

## Interaction requirements

- [ ] Clicking 'Health' in app header should navigate user to Event logs page
- [ ] Clicking 'Power' in app header should navigate user to Server power operations page

## Screenshots
Vue

<img width="456" alt="Screen Shot 2020-05-14 at 10 44 28 AM" src="https://user-images.githubusercontent.com/8097306/81970641-b32e9000-95d4-11ea-91d2-4e4fd78cf8af.png">

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33082

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33082 merged
