### ISSUE TITLE
GUI : FED : Event Logs - Expansion row log details

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2201]
## Overview
Add the ability to expand and event log row to view log details

## Interaction requirements
- [ ] Users can click the expand arrow to see a detailed view of log information

## InVision link
https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/screens/319540651

## Screenshots
Vue redesign

![Screen Shot 2020-05-14 at 11.56.52 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/fff8de0d-6d5c-41bf-8299-399c454671e6)

Angular

![Screen Shot 2020-05-14 at 11 57 39 AM](https://user-images.githubusercontent.com/8097306/81982366-8f744580-95e6-11ea-898e-de53badc1053.png)

**Comment by derick-montague** [comment]
May push to A.1.211

**Comment by derick-montague** [comment]
Redfish events are being upstreamed in the current sprint. https://github.com/ibm-openbmc/dev/issues/1358

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39222

**Comment by derick-montague** [comment]
@Srisuk - https://github.com/ibm-openbmc/dev/issues/1358#issuecomment-756311181

**Comment by derick-montague** [comment]
Placed the Gerrit review as WIP and will pick this up in sprint 2021-03.

**Comment by derick-montague** [comment]
@Srisuk and @sandeepasingh116: https://github.com/ibm-openbmc/dev/issues/1358#issuecomment-779418089

We will not be supporting UUID or Subsystem ID and we will need design guidance on the new properties being proposed.

**Comment by sandeepasingh116** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40994

**Comment by derick-montague** [comment]
@sandeepasingh116 this was merged, can you please close?

**Comment by sandeepasingh116** [comment]
> @sandeepasingh116 this was merged, can you please close?

Done.
