### ISSUE TITLE
GUI : FED : Hostname/IP Address

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2202]
## Overview 
Current Angular app shows hostname and IP address in header. Confirm whether or not we will be including these data points–need to consider when having multiple network interfaces–there can be multiple hostnames/IP addresses.

## Notes
- Should use existing state values in NetworkSettingsStore file
- The proposed redesign places hostname and ip address in the navigation. There were verbal discussions about moving these items right below the last navigation item instead of at the bottom of the navigation. Confirm placement with design
- User testing revealed hostname/IP address are important and users want it visible at all times

## Screenshots
Vue redesign
![Screen Shot 2020-05-14 at 12 40 04 PM](https://user-images.githubusercontent.com/8097306/81978389-4a4d1500-95e0-11ea-90df-23e625b72eee.png)

Angular

![Screen Shot 2020-05-14 at 1 30 56 PM](https://user-images.githubusercontent.com/8097306/81982793-2b9e4c80-95e7-11ea-98dd-eeca398124de.png)

**Comment by derick-montague** [comment]
Determined at OpenBMC Design workgroup on 6/10/20 that having this on the overview page and the network settings page is all that is needed.
