### ISSUE TITLE
GUI : FED : Profile settings - Timezone offset display preference

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2203]
## Overview
Add ability for user to select a date and time display preference. All instances of date and time will be updated to reflect this setting. The available options to select from will be **Browser offset** and **UTC**. The options will added to the Profile settings page.

## InVision Link
https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/screens/319488037

## Notes
- User preference stored in localstorage (no backend api request)
- Updates to date and time filters to take into account user preference
  - https://github.com/openbmc/webui-vue/blob/master/src/main.js#L36-L57
- Should validate/test that all occurrences of date/time reflects the user preference 

## Screenshots
![Screen Shot 2020-05-14 at 2 43 26 PM](https://user-images.githubusercontent.com/8097306/81989003-4b3a7280-95f1-11ea-82c5-a5d95aa841ed.png)

**Comment by derick-montague** [comment]
When I was testing the UI, I noticed the browser offset is not correctly displayed.

![image](https://user-images.githubusercontent.com/1183515/87200473-411bb400-c2c2-11ea-8da2-34f750d404e4.png)

**Comment by derick-montague** [comment]
Noticed the time on the overview page is not rendering correctly.

![image](https://user-images.githubusercontent.com/1183515/87200849-0fefb380-c2c3-11ea-8a76-3f3a587f8585.png)

**Comment by derick-montague** [comment]
I think we will need to deviate a bit from the design. This makes sense from what I have been reading.

To accomplish this,  you will need to:
1. Install `date-fns-tz`
1. Replace import { format } from 'date-fns';import with `import { utcToZonedTime, format } from 'date-fns-tz';` in the main.js file
1. Update the the filter for `formattime`  for the offset to:

```
    const pattern = `HH:mm:ss (z 'UTC' XXX)`;
    const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    const zonedDate = utcToZonedTime(value, timezone);
    return format(zonedDate, pattern, { timezone });
```

![image](https://user-images.githubusercontent.com/1183515/87205964-454dce80-c2ce-11ea-9915-d331cae30b07.png)

**Comment by derick-montague** [comment]
We will also need to make a quick change to the `ProfileSettings.vue`  timezone computed value.

## As Is

```
    timezone() {
      return format(new Date(), 'z');
    }
```

![image](https://user-images.githubusercontent.com/1183515/87207018-834bf200-c2d0-11ea-895d-8fd3b0fbcaf5.png)

## To Be
```
import { format, utcToZonedTime } from 'date-fns-tz';
```
```
    timezone() {
      const pattern = `z 'UTC' XXX`;
      const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
      const zonedDate = utcToZonedTime(new Date(), timezone);
      return format(zonedDate, pattern, { timezone });
    }
```

![image](https://user-images.githubusercontent.com/1183515/87207335-492f2000-c2d1-11ea-9171-94d955b1efcc.png)

**Comment by Srisuk** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34027
