### ISSUE TITLE
GUI : FED : Server power operations - Server last power operation

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2208]
## Overview
Add 'Server last power operation' timestamp to server power operations page

## Endpoint 
Should use the lastResetTime on systems/system endpoint for the host power operations

## UX Flow / Interaction Requirements
- [ ] Users can see a timestamp of last power operation
- [ ] When users take any actions on the server power operations page, need to refetch this value

## Notes
- [ ] Discuss with design final implementation–Angular implementation may not work in Vue

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

## Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in DAP

## Screenshots
**Vue**
![Screen Shot 2020-05-15 at 11 57 11 AM](https://user-images.githubusercontent.com/8097306/82086405-54841780-96a3-11ea-932b-a428786fd88f.png)

**Angular**
![Screen Shot 2020-05-15 at 11 55 11 AM](https://user-images.githubusercontent.com/8097306/82086275-21da1f00-96a3-11ea-8bd6-7362daf967bc.png)

**Comment by dixsie** [comment]
Thoughts on this placement? It follows the current pattern for date/time formatting and the definition list pattern used on the Date/time settings page @derick-montague @ben-bacon @ParishrutB 


![Screen Shot 2020-08-04 at 7.04.26 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/76c6e63d-8da3-4160-a677-c9812deedf84)

![Screen Shot 2020-08-04 at 7.08.21 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/9dfbeb24-4a93-43e1-ae82-bc57ef374c60)

**Comment by ben-bacon** [comment]
I think the option where host status and power operation are stacked vertically is a better execution IMO. Horizontally, it looks related to "operations", which if it is then we could put it in that section.

**Comment by dixsie** [comment]
resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35347

**Comment by dixsie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [power](https://trello.com/c/bskjnLyH/1-power)

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35347 merged
