### ISSUE TITLE
GUI : FED : Reboot BMC - BMC last reboot

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2209]
## Overview
Add BMC last reboot timestamp on Reboot BMC page

## Endpoint
Should use the lastResetTime on managers/bmc endpoint for the bmc reboot page

## Notes
- [ ] Need to work with design to consider placement

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

## Accessiblity Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in DAP

## Screenshots
**Angular**
![Screen Shot 2020-05-15 at 12 01 33 PM](https://user-images.githubusercontent.com/8097306/82086773-decc7b80-96a3-11ea-8af3-b862ee14482c.png)

**Comment by dixsie** [comment]
Thoughts ? @derick-montague  @ben-bacon @ParishrutB 

![Screen Shot 2020-08-04 at 7.13.40 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/68f4f360-39a4-4077-b30d-bbc637c95f51)

**Comment by dixsie** [comment]
resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35348/1

**Comment by ParishrutB** [comment]
Wondering if this could have been combined with Server Power Operations. 

But I guess your question was regarding the copy? I think it is good improvement over the previous one.

**Comment by derick-montague** [comment]
> Wondering if this could have been combined with Server Power Operations.
>
> But I guess your question was regarding the copy? I think it is good improvement over the previous one.

No, there is a separate power operation timestamp.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35348 merged
