### ISSUE TITLE
Disabled 20 char password limit when IPMI is disabled

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2219]
Need some way to allow the user to set a password >20 characters if IPMI is disabled or the user doesn't care about IPMI access.

**Comment by joseph-reynolds** [comment]
Background information:
- See previous discussion here: https://github.com/ibm-openbmc/dev/issues/981
- See the "ipmi" supported group role explained here: https://github.com/openbmc/docs/blob/master/architecture/user-management.md
- The existing mechanism to limit ipmi passwords to 20 characters is in Linux-PAM module pam_ipmicheck.so.  It looks at the user's account to learn if it is in the "ipmi" group.  If so, it imposes the 20 character limit.  Otherwise, it does not impose a limit.

**Comment by joseph-reynolds** [comment]
This is to capture some of the ideas floating around:
- My opinion is: If out-of-band network IPMI service is enabled or disabled should not factor into any password limits.  The password length limit should be based only on the fact that the user account is in the "ipmi" group.
- Users created via the IPMI interface should be added to the IPMI group by default.
- Users created via the Redfish REST API should not be added to the IPMI group by default.
- We should enhance the Redfish ManagerAccount to show which groups the user account belongs to and allow the admin to modify.  See /xyz/openbmc_project/user/root/attr/UserGroups shown in #981.

**Comment by joseph-reynolds** [comment]
Never mind that last comment.  The correct command is: `ipmitool channel setaccess 1 #user_slot# ipmi=off` that disables only IPMI access.

**Comment by joseph-reynolds** [comment]
Here is an idea how to solve this problem on systems where network IPMI is either not available or is disabled by default.

Background:
- Per OpenBMC user management https://github.com/openbmc/docs/blob/master/architecture/user-management.md#supported-group-roles, only users in the `ipmi` group are allowed to use the network IPMI interface (ipmitool).
- Currently, all default users are in this group, and dynamically-added users are added to this group. 
- Per the implementation, membership in the `ipmi` group restricts the password to 20 characters.

Design changes needed (sketch):
- Do not add default users to the `ipmi` group.
- When users are dynamically-added to the BMC, do not add them to the `ipmi` group by default.

At this point, password are not limited to 20 characters.  However, no users are authorized to use network IPMI, and there is no supported interface to authorize users to use network IPMI.  So we add the following designs:
- A new API that allows the BMC Admin to GET/PATCH /redfish/v1/AccountService/Accounts/joeuser/Oem/OpenBMC {"privilegegroups": one or more of {ssh, ipmi, redfish, and web} }.
- When a user is added to the `ipmi` group, they must also change their password at the same time (so IPKI's copy of the password can be updated) which means that user is subject to the 20 char limit.

With this design, users will not be subject to the 20 character password limit unless and until that user is added to the ipmi group.  Note that enabling and disabling the network IPMI service is independent of adding and removing users from the `ipmi` group.

If the BMC admin desires network IPMI access, the steps are:
- Enable the network IPMI interface.
- Add users to the "ipmi" group (via the new API above).
- Use ipmitool as usual.

**Comment by gtmills** [comment]
@joseph-reynolds Before we add the groups as OEM, we should check with Redfish and see if they would add. 
Redfish knows thier privilege implementation needs work.

**Comment by joseph-reynolds** [comment]
I can re-ask, but I don’t think Redfish is interested in this type of access control.  See https://redfishforum.com/thread/219/account-groups-property

**Comment by joseph-reynolds** [comment]
Good call Gunnar!  Redfish added the ManagerAccount AccountType property for this purpose.  I created #2577 to implement that in BMCWeb.

**Comment by gtmills** [comment]
@joseph-reynolds You are still planning on doing? We really want for the GUI..

**Comment by derick-montague** [comment]
@joseph-reynolds and @gtmills - Now that we can enable and disable from the UI, we are planning to implement the client-side validation. Will this make GA1?

**Comment by joseph-reynolds** [comment]
Implementing this (in #2577) is not my first priority, but is still slated for GA1.

**Comment by joseph-reynolds** [comment]
Update.  I think this is done and can be closed.  You can PATCH /redfish/v1/AccountService/Accounts/SOMEUSER property AccountTypes:
- Including the IPMI value allows the user to use the IPMI interface and limits their password to 20 characters.
- Omitting the IPMI value blocks the user from using the IPMI interface.

Specifically, upstream BMCWeb code implements the AccountTypes IMPI value, and upstream Linux-PAM module pam_ipmicheck implements the 20 char limit when the user is in the ipmi group.

**Comment by gtmills** [comment]
> Update. I think this is done and can be closed. 

I don't think this is upstream yet, just downstream. I moved to "Code Review in Driver"

**Comment by mzipse** [comment]
Work is complete.  Closing.
