### ISSUE TITLE
bmcweb: redfish: implement CertificateService certificate upload

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#222]
Implement the ability to upload HTTPS and LDAP certificates.

The phosphor-certificate-manager application provides a D-Bus API to install certificates, based on type.

Via Redfish API, a certificate will be POSTed to a "certificates collection" location such as `/redfish/v1/Managers/1/NetworkProtocol/HTTPS/Certificates`. Upon receiving this POST request, bmcweb should invoke the D-Bus API.

The CertificateService schema and a README ppt is at https://www.dmtf.org/documents/redfish-spmf/redfish-certificate-management-09a.

The source code of bmcweb is at https://github.com/openbmc/bmcweb.

**Comment by edtanous** [comment]
If there's anything I can do to help support building this out you know how to get in touch with me.

One nitpick, in the case above, because it's a resource that already exists, and you're not creating a new one, but simply modifying the existing, the request would be a PATCH, not a POST.

**Comment by dkodihal** [comment]
@edtanous how about a case where the certificate may not exist? For eg say the root CA of an LDAP server.

**Comment by edtanous** [comment]
Return blank strings for the fields, or auto generate a self signed certificate (depends on the case)

In the ldap case, I would expect blank strings for the fields.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/17595/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by devenrao** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-certificate-manager/+/18861/

**Comment by devenrao** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18545/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/18545 merged
