### ISSUE TITLE
GUI : FED : Server LED - Add toast notifications

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2221]
## Overview
Add toast notifications on the Server LED page after toggling the On/Off switch

## UX Flow / Interaction Requirements
- [ ] After user toggles the Server LED on/off switch, there should be a toast notification to indicate whether or not the API request was successful or failed

## Final Invision Mockup
N/A

## Notes
- [ ] Use async/await pattern in ServerLedStore to wait for response
- [ ] Add translated success/error response in store
- [ ] Confirm toast message

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in DAP

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33935

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33935 merged
