### ISSUE TITLE
GUI : Research : Server LED

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2222]
## Requirements
Determine the correct verbiage to use for the Server LED page

## Notes
- LED stands for light-emitting diode. 
- This title is "light-emitting diode light control"
- Maybe just "LED control". 

## Questions
- [x] Do the notes above from the SME @gtmills apply to the fieldset legend also?

## Vue Implementation
![image](https://user-images.githubusercontent.com/1183515/82483737-8380fb80-9a9e-11ea-8e25-d6b31a51d6cd.png)

## AngularJS Implementation
![image](https://user-images.githubusercontent.com/1183515/82483889-bfb45c00-9a9e-11ea-9d9e-83e7126bbd39.png)

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/30854/11/src/locales/en-US.json#272 has that subtitle as "Server indicator LED"

**Comment by derick-montague** [comment]
Updated the screenshots. Thanks, @gtmills!

**Comment by derick-montague** [comment]
Closing since we implemented this in the current Server LED page.
