### ISSUE TITLE
GUI : FED : Server LED - Add page loader

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2223]
## Overview
Add page loader to Server LED page to indicate data fetch on initial load

## UX Flow / Interaction Requirements
- [ ] Page loading bar should be visible when navigating to Server LED page

## Notes
- [ ] Should use existing LoadingBarMixin

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in DAP

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33556

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33556 merged
