### ISSUE TITLE
Provide adequate controls for service functions

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#2229]
IBM manufacturing and service teams use various interfaces (Web, REST APIs, SSH commands, Cronus, etc.) on FSP-based systems and have toolkits that use these underlying interfaces.  One example is the `cupdcmd -f` command.  The software interfaces on OpenBMC systems are very different from FSP.  The manufacturing and service teams need to know how to perform equivalent functions on OpenBMC-based systems.  Ideally these will be Redfish APIs, but some will be BMC shell commands.

This issue is to ensure the BMC has adequate **controls for our** manufacturing and service functions, and to document them for our teams.

**Caution**: Some manufacturing and service functions will remain proprietary and should not be discussed in this public forum.

**Comment by mzipse** [comment]
@anoo1 , did you close with Joseph on this piece of work?

**Comment by joseph-reynolds** [comment]
This breaks down into several pieces:
- Admin REST APIs.  Example: retrieve logs.
- Service rep REST APIs (related to https://github.com/ibm-openbmc/dev/issues/1323).
- Service rep access to the BMC's command shell and sudo command.  This gives access to various command including busctl, systemctl, etc, and toolkits including cronus.

**Comment by joseph-reynolds** [comment]
Correction / clarification:  This issue was to be a placeholder or reminder to ensure we have adequate controls over our Enterprise Server service functions.  Specifically, the post above shows where service functions can be accessed from.  Our plans to controls these interfaces are represented by: https://github.com/ibm-openbmc/dev/issues/1323 and https://github.com/ibm-openbmc/dev/issues/2577 

I consulted Adriana about providing the actual service functions via other stories, and that is also covered elsewhere.  We agreed to close this issue as a duplicate.
