### ISSUE TITLE
SNMP config : implement property updates

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#223]
At the moment it is possible to create an SNMP config, but not update it. Please add details @ratagupt.

**Comment by ratagupt** [comment]
I think we can close this issue, we already have following two issues for the same.
https://github.com/openbmc/phosphor-snmp/issues/2.

**Comment by ratagupt** [comment]
the fix has been merged, we can close this issue.
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-snmp/+/15897/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
