### ISSUE TITLE
Interface specific default gateway support

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2231]
Presently phosphor-networkd supports system-specific one default gateway, As kernel supports Fall back gateways, hence we are supporting gateway interface specific.

Reference:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-configuring_the_default_gateway

Systemd-Networkd also supports fall back gateways.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
