### ISSUE TITLE
Changes in IPMI required to support Multiple default gateways

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2234]
As the backend Dbus interface gets change for getting the default gateway. Changes are required in IPMI to support this.

**Comment by nmuruli** [comment]
@bradbishop IPMI work , we get help from contractor with IPMI experience ?

**Comment by sunharis** [comment]
Please re-estimate

**Comment by sunharis** [comment]
The parent Epic is blocking GUI. IPMI changes are not a blocker for GUI. Please track this as independent story

**Comment by sunharis** [comment]
@sbteeks Please update the latest status and move the story to the right state/release

**Comment by sbteeks** [comment]
Not looked into this story yet. With IPMI slowing down, and disabling IPMI service by default so not sure we need to focus on this...

**Comment by rfrandse** [comment]
tracking in jira
