### ISSUE TITLE
eBMC GUI : Concurrent Maintenance

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2236]
## Summary
The concurrent maintenance section is ASMI functionality that  includes the following features:
- 4.5.1 - Control Panel (Ops Panel)
- 4.5.2 - DVD Drive

## References/Resources
- eBMC Feature Item 4.5
- [ ] Add feature discovery folder (create if doesn't exist)

**Comment by nicoleconser** [comment]
Is this blocked by back-end #1882 ?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
> Are both the Ops Panel + DVD drive blocked by #1882 ? Trying to figure out our best guess for back-end availability. @derick-montague @mzipse

I think so, but there are API stories for concurrent maintenance that are blocking the actual stories. We are not blocking at the Epic level for the GUI

This will also include Time of day battery, which we don't have a specific story for since we were expecting to include it in HW Inventory.

**Comment by derick-montague** [comment]
Closing will be part of #1521
