### ISSUE TITLE
GUI : Research : Concurrent Maintenance - Control Panel

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2237]
## SME
**BMC**:
**RAS**:
**PHYP**:
**IBM i**:

### Background
- [ ] TBD

### End users
- [ ]  TBD

### User Needs
- [ ] TBD

### User Quotes
- [ ] TBD

## User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

## References
- eBMC Feature Item 4.5.1
- [ ] Link to Discovery folder

**Comment by nicoleconser** [comment]
Is this blocked by back-end #1882 ?

**Comment by derick-montague** [comment]
This may be something to explore during the research story: https://www.ibm.com/support/knowledgecenter/hu/POWER8/p8hb5/p8hb5_kickoff.htm

**Comment by derick-montague** [comment]
Expecting this and all FRUs that are concurrently maintainable to be part of HW Inventory

**Comment by nicoleconser** [comment]
In Mural we have this listed as **Concurrent Maintenance (Ops Panel + DVD Drive)** — no mention of RTC Battery (which is included in this section in ASMI).

**Comment by derick-montague** [comment]
Closing will be part of #1521
