### ISSUE TITLE
Investigate LDAP privilege mappings via Redfish

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#224]
Investigate what API Redfish has to offer, and determine how LDAP user privileges can be specified and retrieved by Redfish API. The goal of the story is to send a proposal to the community.

**Comment by tomjoseph83** [comment]
The redfish JSON schema has the support for the LDAP group privilege mapping.

https://redfish.dmtf.org/schemas/v1/AccountService.v1_3_1.json

ExternalAccountProvider/RemoteRoleMapping/[Collection of privilege mappings]



RoleMapping:
{
    "LocalRole" : "Privilege"
    "Remote Group" : " GroupName"                                 
}

**Comment by mzipse** [comment]
refresh, pls ignor.
