### ISSUE TITLE
GUI : FED : Bootstrap Pill consistency

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2242]
## Overview
In a recent design team demo, we noticed that the pill components in the multiple select component used in the `Generate certificate` modal do not match the pill components in the filter component. 

## Screen captures
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/801203e7-7f77-4ba8-bfa8-bbc046a327ba)

## Notes
- The difference between the two is line-height. The pills in the multiple select component have a line-height  of 1.5. The pills in the filter have a line-height of 1. 

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/ac20f1bc-18f3-48ec-b7d8-3ea00b5651c0)

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33085

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33085 merged
