### ISSUE TITLE
GUI : FED : Manage power usage - Page loader

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2246]
## Overview
Add page loader to Manage power usage page to indicate data fetch on initial load

## UX Flow / Interaction Requirements
- [ ] Page loading bar should be visible when navigating to page

## Notes
- [ ] Should use existing LoadingBarMixin

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by Srisuk** [comment]
Resolved by:- https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33631

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33631 merged
