### ISSUE TITLE
GUI : FED : Login - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2247]
## Overview
Add standardized test hooks to all interactive elements on Login page. The hook should follow agreed naming convention using the `data-*` attribute
- input fields
- login button

## Notes
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-06-01 at 2 17 45 PM](https://user-images.githubusercontent.com/8097306/83455408-b3bb8900-a412-11ea-95ad-4fd7bb91d5e0.png)

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34114
