### ISSUE TITLE
GUI : FED : Navigation - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2248]
## Overview
Add standardized test hooks to all interactive elements in the Navigation component. The hook should follow agreed naming convention using the `data-*` attribute.
- every button
- every link

## Notes
- Also needs to be added to mobile layout
- Agreed naming convention should follow **data-test-id="nav-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots

![Screen Shot 2020-06-01 at 2 21 31 PM copy 3](https://user-images.githubusercontent.com/8097306/83455985-b1a5fa00-a413-11ea-9cdb-60007bd70042.png)

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35027

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35027 merged
