### ISSUE TITLE
GUI : FED : App header - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2249]
## Overview
Add standardized test hooks to all interactive elements on AppHeader component. The hook should follow agreed naming convention using the `data-*` attribute.

- App status
- app refresh
- profile/avatar dropdown and all items inside

## Notes
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-06-01 at 2 21 31 PM copy 4](https://user-images.githubusercontent.com/8097306/83456021-c2ef0680-a413-11ea-9efd-2f9a628b5c2c.png)

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35026
