### ISSUE TITLE
Investigate logging and alerts via Redfish

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#225]
Investigate Redfish LogService schema and server-side events. Figure out how they work with OpenBMC logs and alerts. Send proposals, if any, to the community.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Deepak Kodihalli  
this feature is still not in, but it is ebmc work

**Comment by gtmills** [comment]
@dkodihal Should we update the milestone, epic for this work?

**Comment by dkodihal** [comment]
@gtmills I'm not sure. I'm not working on this at the moment. @santoshpuranik you have anything to comment in this?

**Comment by dkodihal** [comment]
Santosh's got this one, so unassigned myself.

**Comment by gtmills** [comment]
@santoshpuranik Moved this to a later milestone. 
I am not sure what this all entails. 
@santoshpuranik Do you mind updating the description ? Or adding a comment?

**Comment by mzipse** [comment]
Per feedback from Santosh, this is the effort to decide if we stream using RSYSLOG or the Redfish solution.  More discussion on this is required.

**Comment by lxwinspur** [comment]
@gtmills @mzipse 
Is there any progress on this issue?
Do we need to use RSYSLOG?

**Comment by gtmills** [comment]
@santoshpuranik Any update here?

**Comment by rfrandse** [comment]
tracking in jira
