### ISSUE TITLE
GUI : FED : Overview - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2250]
## Overview
Add standardized test hooks to all interactive elements on Overview page. The hook should follow agreed naming convention using the `data-*` attribute.
- Edit network settings button
- Serial over LAN button
- Server LED toggle
- View all logs (if logs are visible)

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-06-01 at 2 21 31 PM copy 4](https://user-images.githubusercontent.com/8097306/83456083-e5811f80-a413-11ea-8387-666f670d740c.png)

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34299

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34299 merged
