### ISSUE TITLE
GUI : FED : Sensors - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2252]
## Overview
Add standardized test hooks to all interactive elements on Sensors page. The hook should follow agreed naming convention using the `data-*` attribute.
- Only need a hook for filters dropdown and all severity checkboxes inside dropdown

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-06-01 at 2 30 45 PM](https://user-images.githubusercontent.com/8097306/83456399-853ead80-a414-11ea-96d8-6bfe63f9f8f5.png)

**Comment by derick-montague** [comment]
@yoshiemuranaka will add the story that added support for filters and checkboxes.

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34403
