### ISSUE TITLE
GUI : FED : Hardware status - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2253]
## Overview
Add standardized test hooks to all interactive elements on Hardware status page. The hook should follow agreed naming convention using the `data-*` attribute.
- Expand button on all tables only

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
<img width="971" alt="Screen Shot 2020-06-02 at 8 48 31 AM" src="https://user-images.githubusercontent.com/8097306/83540976-dfd81800-a4ad-11ea-8bee-aa09c58c5d5a.png">

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34710

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34710 merged
