### ISSUE TITLE
GUI : FED : Manage power usage - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2254]
## Overview
Add standardized test hooks to all interactive elements on Manage power usage page. The hook should follow agreed naming convention using the `data-*` attribute.
- Checkbox
- Input field
- Save button

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshot
![Screen Shot 2020-06-01 at 2 33 44 PM](https://user-images.githubusercontent.com/8097306/83456675-faaa7e00-a414-11ea-842c-34c54af2d3f7.png)

**Comment by Srisuk** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34732

**Comment by Srisuk** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35166
