### ISSUE TITLE
GUI : FED : Reboot BMC - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2255]
## Overview
Add standardized test hooks to all interactive elements on Reboot BMC page. The hook should follow agreed naming convention using the `data-*` attribute.
- Reboot BMC button

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-06-01 at 2 35 03 PM](https://user-images.githubusercontent.com/8097306/83456745-1f065a80-a415-11ea-970e-4efd52c0bfe8.png)

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34696

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34696 merged
