### ISSUE TITLE
GUI : FED : Server LED - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2256]
## Overview
Add standardized test hooks to all interactive elements on Server LED page. The hook should follow agreed naming convention using the `data-*` attribute.
- Toggle switch

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-06-01 at 2 36 09 PM](https://user-images.githubusercontent.com/8097306/83456819-48bf8180-a415-11ea-98e6-bb488aea7515.png)

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34887
