### ISSUE TITLE
GUI : FED : Server power operations - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2257]
## Overview
Add standardized test hooks to all interactive elements on Server power operations page. The hook should follow agreed naming convention using the `data-*` attribute.
- **Do not need** hooks for any of Host OS boot settings
- All power operations options need hooks
  - buttons
  - radio options

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-06-01 at 2 37 30 PM](https://user-images.githubusercontent.com/8097306/83456915-773d5c80-a415-11ea-9b2d-c5dea0bd14e8.png)

**Comment by Srisuk** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34799
