### ISSUE TITLE
GUI : FED : Network settings - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2258]
## Overview
Add standardized test hooks to all interactive elements on Network settings page. The hook should follow agreed naming convention using the `data-*` attribute.
- Select option interface
- All visible (existing) input fields
- Do not need hooks for adding/delete fields 
- Save button

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-06-02 at 8 51 27 AM](https://user-images.githubusercontent.com/8097306/83541391-70165d00-a4ae-11ea-96ad-8486f034564f.png)

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34295

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34295 merged
