### ISSUE TITLE
GUI : FED : Firmware - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2259]
## Overview
Add standardized test hooks to all interactive elements on Firmware page. The hook should follow agreed naming convention using the `data-*` attribute.

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"`

**Comment by yoshiemuranaka** [comment]
Revisit adding test hooks after final design

**Comment by derick-montague** [comment]
Will be completed as part of #1627
