### ISSUE TITLE
Bring-up and lab debug tools.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#226]
Requirements: 
* Provide eCMD equivalent command line tool in BMC to execute below system level and chip level functions.
    * get/put SCAN/SCOM ( BMC native way and using SBE) 
    * system level start/stop clock and set clock speed. 
    * get/put spr/gpr ( BMC native way and using SBE). 
    * get/put memory proc/pba.(BMC native way and using SBE). 
    * Host Processor start/stop/step/sreset/breakpoint.( using SBE). 
* Enable support for Host debug. 
* istep (SBE/Host) 
* Provide infrastructure to execute HWP BMC natively incase SBE is not active. 
* Provide BMC command line support for
    * I2C get/set/reset/dump/detect functions. 
    * get/put vpd image and keywords. 
    * configuring the specified GPIO pin to the specified mode 
    * Reading PNOR partition information. 
    * BMC register access .

**Comment by ojayanth** [comment]
## Existing I2C tools in BMC: 

i2cget: i2cget is a small helper program to read registers visible through the I2C bus (or SMBus).  
https://linux.die.net/man/8/i2cget: 

i2cset: I2cset is a small helper program to set registers visible through the I2C bus. 
https://linux.die.net/man/8/i2cset: 

i2cdump: i2cdump is a small helper program to examine registers visible through the I2C bus. https://linux.die.net/man/8/i2cdump : 

i2cdetect: i2cdetect is a userspace program to scan an I2C bus for devices. It outputs a table with the list of detected devices on the specified bus 
https://linux.die.net/man/8/i2cdetect 

### Requirements:
    * get/put vpd image and keywords.

**Comment by ojayanth** [comment]
### GPIO Utility:

gpioutil --help 
Usage:
 gpioutil -n GPIO_NAME  [-v value] 
gpioutil -i GPIO_NUM  -d <DIRECTION = in,out,falling,rising,both> [-v value]
 gpioutil -p PIN_NAME  -d <DIRECTION = in,out,falling,rising,both> [-v value] 
gpioutil -l PIN_NAME     (lookup pin name only)

**Comment by ojayanth** [comment]
### Primary ecmd-pdbg requirements 
There are already plans in place to support the following requirements in ecmd-pdbg to allow eCMD style commands to be executed directly on the BMC. No issues were identified with using ecmd-pdbg to satisfy the following requirements: 
* get/put SCAN/SCOM ( BMC native way and using SBE) 
* system level start/stop clock and set clock speed. 
* get/put spr/gpr ( BMC native way and using SBE). 
* get/put memory proc/pba.(BMC native way and using SBE). 
* Host Processor start/stop/step/sreset/breakpoint.( using SBE). 
Currently ecmd-pdbg supports get/put SCOM but libpdbg (which is what the plugin uses internally) supports spr/gpr, memory and host processor operations so it will be straight forward to add this support to ecmd-pdbg which Jason and I plan to do. SCAN and clock access is not yet fully supported in libpdbg, but we have a work in progress version and plan to complete these for ecmd-pdbg use. We can make an early preview release with SCOM functionality available for P9 is this is of use. 
  
### BMC Native vs. SBE chip-ops/sbefifo 
* libpdbg currently uses OpenFSI directly on the BMC for all requirements listed above (including spr/gpr/memory) utilising lightweight procedures for more complex operations. 
* support for the above using SBE chip-ops is planned and is currently being worked on. 
* both methods will continue to be supported transparently to allow easy switching between the two depending on user requirements. 
* ecmd-pdbg may also be compiled for PPC64 to allow running the same commands directly on the host without requiring extra code. 
  
### Provide infrastructure to execute HWP BMC natively incase SBE is not active 
* In general the existing eCMD C++/Python/Perl bindings would be best suited for this. 
* It is possible to bind directly to libpdbg (there is a poorly documented API exported as a C library). 
* Might be possible to create lightweight FAPI2 bindings for libpdbg but further discussion would be required if this is a requirement (probably better to just use eCMD bindings). 
  
### Attention Handling 
* There is an existing solution for event monitoring so no special support is required from libpdbg

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Closing this epic
