### ISSUE TITLE
GUI : FED : Date and time settings - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2261]
## Overview
Add standardized test hooks to all interactive elements on Date and time settings page. The hook should follow agreed naming convention using the `data-*` attribute.

- Radio options
- Input fields
- Save button

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-05-14 at 2 36 39 PM](https://user-images.githubusercontent.com/8097306/83541643-c4214180-a4ae-11ea-867e-8a8c7ccc6fe4.png)

**Comment by Srisuk** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34808
