### ISSUE TITLE
GUI : FED : LDAP - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2262]
## Overview
Add standardized test hooks to all interactive elements on LDAP page. The hook should follow agreed naming convention using the `data-*` attribute.

- All form controls in settings (checkbox, radio option, input fields)
- Do not need hook for show/hide password button
- Do need hook fro manage ssl certificates link
- Save settings button
- Nothing for role group

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-06-01 at 2 45 47 PM](https://user-images.githubusercontent.com/8097306/83458031-a7392f80-a416-11ea-9e50-6be130779619.png)

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35017

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35017 merged
