### ISSUE TITLE
GUI : FED : Local user management - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2263]
## Overview
Add standardized test hooks to all interactive elements on Local user management page. The hook should follow agreed naming convention using the `data-*` attribute.

- Edit/delete icons in table row
- Table select checkboxes
- Table batch action options (delete, enable, disable buttons)
- Add user button
- Modal - add user form radio option, input, select (do not need show/hide pw)
- Modal - hooks for cancel, close (X) button 
- No hooks for account policy settings button and modal
- View privilege role description button

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-06-01 at 2 47 04 PM](https://user-images.githubusercontent.com/8097306/83458157-ccc63900-a416-11ea-8423-4f651c3ac769.png)

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34727

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34727 merged
