### ISSUE TITLE
GUI : FED : SSL Certificates - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2264]
## Overview
Add standardized test hooks to all interactive elements on SSL certificates page. The hook should follow agreed naming convention using the `data-*` attribute.

- Only generate CSR modal button and form values
- Do not need hook for alternate names field

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
![Screen Shot 2020-06-01 at 2 47 54 PM](https://user-images.githubusercontent.com/8097306/83458209-f1baac00-a416-11ea-94f7-cfb4c7773dea.png)

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34965

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34965 merged
