### ISSUE TITLE
GUI : Design : BMC Style Guide

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2266]
## Overview
The style guide was left in an incomplete state.

## Design Goals
- Remove  inconsistencies within style guide
- Increase efficiencies for design and developer implementation
- Assure design guidelines meet accessibility guidelines
- Improve consistency throughout the application

## InVision Prototype
- [ ] Iteration 0

## Community
- [ ] Create design review story in webui-vue repo
- [ ] Send email to community sharing the design review story

**Comment by derick-montague** [comment]
## Focus state inconsistency

### Application Header
![image](https://user-images.githubusercontent.com/1183515/83591954-c9b67000-a51e-11ea-967a-bc6cf915f9a2.png)

### Table buttons
![image](https://user-images.githubusercontent.com/1183515/83592299-adff9980-a51f-11ea-9d00-9d708f8331c8.png)

![image](https://user-images.githubusercontent.com/1183515/83592206-7264cf80-a51f-11ea-9f63-9da0896f2f5c.png)

![image](https://user-images.githubusercontent.com/1183515/83592223-78f34700-a51f-11ea-8b92-23cd746b2e70.png)

### Table Filter Cancel button
![image](https://user-images.githubusercontent.com/1183515/83592068-244fcc00-a51f-11ea-80e5-93434e63c42e.png)

### Tables
![image](https://user-images.githubusercontent.com/1183515/83592118-40ec0400-a51f-11ea-8191-7e23bce6a684.png)

### Modal Close Button
![image](https://user-images.githubusercontent.com/1183515/83592264-91636180-a51f-11ea-851c-0e142c2ee4ac.png)

### Buttons
![image](https://user-images.githubusercontent.com/1183515/83592393-dbe4de00-a51f-11ea-974d-448a8b7e8920.png)

![image](https://user-images.githubusercontent.com/1183515/83592383-d4253980-a51f-11ea-957e-db340057a196.png)

**Comment by ben-bacon** [comment]
Effort with **Typography** is to provide a more detailed account of text and heading styles, how the interface uses them, and more versatility with a few body styles. 

Proposal for updated styles can be found at: https://ibm.invisionapp.com/share/EQO03IP5MA6

**Comment by ben-bacon** [comment]
Color adjustments to improve the range and accessibility of the UI. Making three changes to the Gray stack (most used color group in UI) will provide the most impact with the least amount of intrusion. 

Proposal for updated styles can be found at: https://ibm.invisionapp.com/share/U9O039T4Q6E#/319573687_Color_Updates

**Comment by yoshiemuranaka** [comment]
Created FED stories to implement style guide changes

**Comment by yoshiemuranaka** [comment]
@derick-montague the changes made from this story are small–do we need to do items listed under community?

> Create design review story in webui-vue repo
> Send email to community sharing the design review story

**Comment by derick-montague** [comment]
> @derick-montague the changes made from this story are small–do we need to do items listed under community?
> 
> > Create design review story in webui-vue repo
> > Send email to community sharing the design review story

I don't think so. These are small polish.
