### ISSUE TITLE
GUI : FED : Profile settings - Test hooks

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2267]
## Overview
Add standardized test hooks to all interactive elements on Profile settings page. The hook should follow agreed naming convention using the `data-*` attribute.

- input fields
- radio options
- save button

## Notes
- Do not need to work on navigation #2248  or app header #2249 
- Agreed naming convention should follow **data-test-id="_page-element-label_"**
- Add the `data-test-id` attribute to all the selectable/input elements (e.g. button, checkbox, link, input field, menu item etc)
- Login page examples:
  - `data-test-id="login-button-logIn"`
  - `data-test-id="login-input-username"`
  - `data-test-id="login-select-language"` 

## Screenshots
<img width="1060" alt="Screen Shot 2020-06-02 at 8 38 21 AM" src="https://user-images.githubusercontent.com/8097306/83539870-70155d80-a4ac-11ea-91e6-8ac15c83326d.png">

**Comment by Srisuk** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35166

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35166 merged
