### ISSUE TITLE
Fill in calls to GetFRUsByUnexpandedLocationCode and GetExpandedLocationCode

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2268]
When the code for https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/com/ibm/VPD/Manager.interface.yaml  is complete, I need to make calls to the 2 methods from the title in order to be able to fill in the PEL callout sections for callouts listed in the PEL message registry and obtained for device path failures.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35148

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35148 merged
