### ISSUE TITLE
GPIO:I2C3_MUX_SEL: Support defaults

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2269]
I2C3_MUX_SEL0 and I2C3_MUX_SEL1 should default to 0. Need to provide capability for someone to set them to 1 if needed. These are used for debug in mfg.

Need to get the GPIO's named in the device tree.

Similar to other GPIO related stories, we'll need to finalize on our libgpiod usage.

Some things to think about:

- Should we use sysfs intead of char dev to set the GPIO to make it persistent and not need an application running?
- Should we create a generic GPIO applicaiton within OpenBMC to persist these GPIO's if we are going to use char dev?

**Comment by tsawan1** [comment]
Any update on this issue, we would like to have this feature now so we could test the integration of our characterization card that connects to the I2Cs on the debug connector. We had used the i2cput and i2cget commands on Swift and Witherspoon and would like to use the same method to simplify our code changes.

**Comment by geissonator** [comment]
some notes from our discussion on this one:
- chardev not good, just use sysfs
- setting and writing should be sysfs, just echo into sysfs to set gpio’s
- AndrewJ to just do a one shot systemd service using chardev to init gpio’s and provide Ruby with echo commands to switch them

**Comment by amboar** [comment]
Here's a script to export and initialise the mux GPIOs. It can be used to change their state as well (just invoke it again with a different value):

```sh
#!/bin/sh

set -eu

logerr() {
    1>&2 echo $@
}

CHIP=$1 # 1e780000.gpio
LINE=$2 # 52 (GPIOG4) / 53 (GPIOG5)
VALUE=$3

GPIO_DIR=/sys/class/gpio
CHIP_LABEL=$(grep -l $CHIP ${GPIO_DIR}/gpiochip*/label)
if [ -z "$CHIP_LABEL" ]
then
    logerr "Failed to find gpiochip matching $CHIP"
    exit 1
fi

CHIP=$(dirname $CHIP_LABEL)
CHIP_BASE=$(cat ${CHIP}/base)

INDEX=$(($CHIP_BASE + $LINE))

if ! [ -e ${GPIO_DIR}/gpio${INDEX} ]
then
    echo Exporting line $LINE as gpio${INDEX}
    echo $INDEX > ${GPIO_DIR}/export
fi

GPIO=${GPIO_DIR}/gpio${INDEX}
if ! [ -e $GPIO ]
then
    logerr Cannot access GPIO $INDEX at $GPIO
    exit 1
fi

echo out > ${GPIO}/direction
echo $VALUE > ${GPIO}/value
```

**Comment by amboar** [comment]
Okay, I've gone an entirely different route from the script as @geissonator wanted the solution upstream:

https://lists.ozlabs.org/pipermail/openbmc/2020-July/022359.html
https://gerrit.openbmc-project.xyz/c/openbmc/meta-aspeed/+/35038

**Comment by amboar** [comment]
The gist of it is you can just use the standard i2c-utils tools to interact with `/dev/i2c-{16,17,18,19}`, the mux will automatically be configured depending on which bus is being accessed.

**Comment by mzipse** [comment]
This code has been merged in the upstream/downstream drivers.
