### ISSUE TITLE
Certificate: Redfish Interface support for CSR.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#227]
Add required support to enable Redfish based CSR interface

**Comment by edtanous** [comment]
Looking forward to seeing the patchset.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
This issue used to track the  base infrastructure(BMC web) to support schema related to upload and view the certificate properties. 
Changing the complexity to accommodate the additional work

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Discussion details available here.
https://lists.ozlabs.org/pipermail/openbmc/2019-February/015102.html

**Comment by ojayanth** [comment]
Review link: https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/16571/

**Comment by ojayanth** [comment]
Design is tracked by https://github.com/ibm-openbmc/dev/issues/13

**Comment by ojayanth** [comment]
This issue used to track the BMC web side changes to enable CSR request and CSR based certificate uploads.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Coding is in progress.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by devenrao** [comment]
Fixed as part of 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/19421/50
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/21650/29

issue can be closed when the code is merged, currently under review
