### ISSUE TITLE
GPIO:DP_CONN_PWR_EN_CTL: display port enable

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2271]
Needs to be set high as soon as we get to userspace to enable the display port.

Similar to other GPIO related stories, we'll need to finalize on our libgpiod usage.

Some things to think about:

- Should we use sysfs intead of char dev to set the GPIO to make it persistent and not need an application running?
- Should we create a generic GPIO applicaiton within OpenBMC to persist these GPIO's if we are going to use char dev?

**Comment by rfrandse** [comment]
tracking in jira
