### ISSUE TITLE
GPIO: BMC_SYS_SPI_WP_N and CPU_BOOT_FLASH_RST_N config

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2274]
Per discussion with hardware team, these pins need to be configured to GPIOY6 and GPIOY7 and be set to outputs. 

From @amboar analysis:
```So at hardware reset the GPIO controller configures all pins as input. It looks like we need to configure GPIOY6 as an open-source output, and GPIOY7 as an open-drain output, and possibly manipulate these lines from userspace (as required)```

**Comment by rfrandse** [comment]
tracking in jira
