### ISSUE TITLE
Attributetool: Add perl tool to generate attribute info db (database)

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2278]
- Attribute info db will contain meta data information about attributes and it will
     consumed by attribute tool to read|write attributes from power system device tree.
   - Currently attributes info db (which is given as part of libekb build) supporting only
     for FAPI attributes. It need to enhance to support Non-FAPI attributes too.
	 So, Use existing device tree generation infrastructure from pdata and provide way to generate
	 info db because, it already generating intermediate xml file which is contains all attributes with
	 target details
	 - The attribute tool will be used in bmc context so, add target rule to generate and install
	   info db along with attribute info header file generation (No need as new feature - change name if required to make generic).
	 - Attribute info db need to support all existing simple and complex type attributes.

**Comment by RameshIyyar** [comment]
Merged changes for generating info db into upstream phal/pdata
https://github.ibm.com/phal/pdata/pull/18
