### ISSUE TITLE
PLDM: support runtime update of BIOS attributes

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2283]
See https://github.com/ibm-openbmc/dev/issues/1976

This story is to cover the following (all related to out of band and inband updates to BIOS attributes):

1) The host can update a BIOS attribute via `SetBIOSAttributeCurrentValue`. In addition to the existing behavior, the PLDM daemon should also update the `BaseBIOSTable` property on the object that implements `xyz.openbmc_project.BIOSConfig.Manager`. Implementation choice : instead of doing a D-Bus get of this property, updating a specific BIOS attribute, and then doing a D-Bus set, the pldm daemon can instead (once it has updated the persisted attribute value table as a result of `SetBIOSAttributeCurrentValue`) process persisted tables and perform just one D-Bus set on the `BaseBIOSTable` property.

2) An out of band Redfish user can update BIOS attributes. This will result in a `PropertiesChanged` signal on the `PendingAttributes` (https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/BIOSConfig/Manager.interface.yaml#L105) property. The PLDM daemon should subscribe to this. Once there is a change, there are two cases :
a) Hypervisor is not up (this can be checked via a D-Bus property). In this case the pldm daemon should process the `PendingAttributes` property (check the new value is within bounds/allowed) and then update the `BaseBIOSTable` for accepted properties. The code in this section a) should be conditionally compiled in a `oem-ibm` flag (`#ifdef OEM_IBM`).
b) Hypervisor is up - this is outside the scope of this story. Will create another one.

**Comment by lxwinspur** [comment]
1. https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/35588

**Comment by lxwinspur** [comment]
2. https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/35725

**Comment by mzipse** [comment]
@tomjoseph83 , are you really working on this?  Or do we want @lxwinspur to work on this?  You both are assigned.

**Comment by lxwinspur** [comment]
Hi, @mzipse 
I am working on this and ready for review, thanks

**Comment by tomjoseph83** [comment]
@mzipse There is a portion which I am also working on which will utilize the work of @lxwinspur

**Comment by mzipse** [comment]
ok.  Thanks!

**Comment by lxwinspur** [comment]
@tomjoseph83 
I see that this task has been merged, could we close it?
