### ISSUE TITLE
PLDM: FRU: Process remote OEM FRU record containing location code

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2284]
Implement a `PLDMOEMFRUParser` class (in new file pldm_oem_fru_parser.cpp) under pldm/oem/ibm/. Link this with pldmd in meson.build, if oem-ibm is enabled.

1) The `PLDMOEMFRUParser` should be a template class (will help with unit testing).
2) Production code should instantiate this class with template type `T` = sdbusplus::server::object::object<sdbusplus::com::ibm::ipzvpd::server::Location> (https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/com/ibm/ipzvpd/Location.interface.yaml)
3) The class should have a method `parseFRURecord`, which takes a FRU record as input. Assert that the `FRU record type` is `OEM FRU record` (see PLDM FRU spec for values). The code should only process the `TLV` where the `field type number` is `254` (location code). When this is found, the code should construct an instance of `T` (could do a make_unique on unique_ptr<T>). After that, for the properties found in the FRU record, it should map those to D-Bus properties (for the interface in 2) and call the setters of the same on the `T` object. Construction of `T` needs a system bus handle and an object path string. The path can be `/xyz/openbmc_project/pldm/oem_fru_record_set/<record_set_identifier>`.
4) `PLDMOEMFRUParser` should also have an API to let the user access the created objects of type `T`.
5) The unit test code can construct `PLDMOEMFRUParser` with a mocked class `M`. Using the API described in 4), it should be possible to test that properties of `M` have specific values, based on the test FRU record passed to 3).
6) If there is benefit, then inherit `PLDMOEMFRUParser` from the `PLDMFRUParser` being defined in #2068.

**Comment by mzipse** [comment]
Work is complete.  Closing.
