### ISSUE TITLE
Op-Panel and BMC communication infra test

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/dev#2288]
This is to test the basic functionality via the Hardware so that when the software programming is done we do not hit any glitch in hardware , and that would be too late to rectify ,  This will use old micro-code or intermediate code on the firmware and use existing drivers on the BMC and command line to test this.

**Comment by mzipse** [comment]
@jinuthomas , if you haven't already done so, please check with @eddiejames  as he is doing some basic master/slave I2C verification between the AST2600 processor and the Op panel as we speak.

**Comment by jinuthomas** [comment]
@mzipse the testing done by Eddie is using the Tacoma and a Hill panel connected on it , this is not the same with nisqually ,This is to test how the hardware communication works on the Rainier Hardware. Not on a temporary setup.

**Comment by jinuthomas** [comment]
Testing ongoing on Tacoma , 90% done , see an issue , need to talk to Ediee James on the single execution not working.

**Comment by santoshpuranik** [comment]
Driver tested, closing.
