### ISSUE TITLE
Certitificates: Design: Add support to download and view propreties.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#229]
Create individual certificate specific d-bus object , which helpes user to download, delete and view  properties .

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Code review Link : https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/15177/

**Comment by rfrandse** [comment]
refresh
