### ISSUE TITLE
GUI : FED : Add default/empty table state

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2291]
## Overview
All tables need to have text to indicate there are no items in the table. Add the `show-empty` prop to tables and provide appropriate `empty-text` value for table. [Bootstrap Vue documentation](https://bootstrap-vue.org/docs/components/table#custom-empty-and-emptyfiltered-rendering-via-slots)

- [ ] Sensors table
- [ ] Local user management table
- [ ] SSL certificates table
- [ ] LDAP role groups table

## Notes
- [ ] Example of default table state on event logs page

## Screenshots
![Screen Shot 2020-06-12 at 8.51.30 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/2a1537d3-9f07-49d6-aa15-b2a42af43ed9)

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35100

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35100 merged
