### ISSUE TITLE
GUI : FED : Table responsive layout

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2292]
## Overview
Decide which responsive table pattern is appropriate for each table. The two possible options are [stacked](https://bootstrap-vue.org/docs/components/table#stacked-tables) or [responsive](https://bootstrap-vue.org/docs/components/table#responsive-tables). 
Responsive table properties will need to be added to all existing tables:
- [ ] Event logs
- [ ] Sensors
- [ ] LDAP role groups table
- [ ] Local user management
- [ ] SSL certificates

## Notes
- [ ] Implement optimal solution for each table (stacked or responsive)
- [ ] Considerations:
  - [ ] selectable rows
  - [ ] expandable rows
  - [ ] potential number of items in table
- [ ] Overview high priority events table currently using `stacked` method
- [ ] If using 'stacked' option–review visual stying with design

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by yoshiemuranaka** [comment]
@SurenNeware would you mind adding responsive layout to tables on Hardware status page too?

**Comment by SurenNeware** [comment]
@yoshiemuranaka No, i don't mind. I will add responsive layout.

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34468

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34468 merged
