### ISSUE TITLE
Implement full task support (things like PercentComplete) for code update 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2293]
Implement things like PercentComplete

From https://redfish.dmtf.org/schemas/Task.v1_4_3.json

               "PercentComplete": {
                    "description": "The completion percentage of this task.",
                    "longDescription": "This property shall indicate the completion progress of the task, reported in percent of completion.  If the task has not been started, the value shall be zero.",
                    "readonly": true,
                    "type": [
                        "integer",
                        "null"
                    ],
                    "units": "%",
                    "versionAdded": "v1_4_0"
                },

**Comment by gtmills** [comment]
The Redfish `PercentComplete` property should look at 
https://github.com/openbmc/phosphor-dbus-interfaces/blob/854ca29b81425f76d6a241ad50b477e1362060bc/xyz/openbmc_project/Software/ActivationProgress.interface.yaml#L5

**Comment by lxwinspur** [comment]
review by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/39314
