### ISSUE TITLE
API for Speculative Execution Control needed

### ISSUE THREAD

**Issue by mzipse** [ibm-openbmc/dev#2295]
For P10, my understanding is that there will need to be an API that the GUI can call to enable/disable Speculative Execution Control.  My understanding is that this is just an on or off switch similar to P9 DD2.3 parts.

We will revisit this need as we gather performance data.

**Comment by gtmills** [comment]
Redfish Bios Attribute here?

**Comment by gtmills** [comment]
@mzipse I believe we don't need this for eBMC. Closing. @mzipse @derick-montague Please reopen if I closed in error.

**Comment by derick-montague** [comment]
> @mzipse I believe we don't need this for eBMC. Closing. @mzipse @derick-montague Please reopen if I closed in error.

That's correct, we also closed the design story. Maury verified with Dean that this not needed via GUI or CLI.

**Comment by mzipse** [comment]
Agreed.
