### ISSUE TITLE
Certificates: Add support to download and view properties

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#230]
Implementation of #229.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Refere d-bus interface  review for details 
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/15177/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Code review link: 
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-certificate-manager/+/18361/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-certificate-manager/+/18361 merged
