### ISSUE TITLE
I/O Concurrently Maintainable API 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2304]
I/O might include hard drives? Might include Open Capi devices? Need to talk to Phyp. Need to pass up to Phyp. @dkodihal Do we need a PLDM story here?

https://github.com/ibm-openbmc/dev/issues/2012 is for TOD Battery, DVD, Op/Control Panel Concurrently Maintainable API

**Comment by dkodihal** [comment]
@gtmills probably. Copying @santoshpuranik as well. Santosh - do you have this in your radar for any of the inventory/Redfish work?

**Comment by gtmills** [comment]
Closing, not on the GUI. Don't need an API
