### ISSUE TITLE
GUI : FED : Hardware status - Power supplies table missing properties

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2309]
## Overview
The Power supplies table on the Hardware status page is missing properties that were defined in the original design. When these properties are available on the backend, update the table to show missing properties:
- [x] Model (Model in Redfish)
- [x] Hardware Type (Name in Redfish)
- [x] Serial Number (SerialNumber in Redfish)
- [x] Identify LED (LocationIndicatorActive in Redfish)
- [x] PartNumber(PartNumber in Redfish)
- [x] SparePartNumber(SparePartNumber in Redfish)
- [x] Manufacturer (Manufacturer in Redfish)
- [x] Health(Health in Redfish)
- [x] State(State in Redfish)
- [x] EfficiencyPercent(EfficiencyPercent in Redfish)
- [ ] PowerCapacityWatts(PowerCapacityWatts in Redfish)
- [ ] Location code(Location in Redfish)
- [ ] PowerSupplyType(PowerSupplyType in Redfish)

## Notes
- [ ] Design/layout has changed from what is currently in InVision mockup

## Final Invision Mockup
- [ ] https://ibm.invisionapp.com/share/2ZO15RPQ6HP#/screens_01-Hardware-Status-04

## Screenshots 
Invison
![image](https://user-images.githubusercontent.com/25200738/118765089-32197100-b898-11eb-931c-dd8869d320b2.png)

Currently in Vue:
![Screen Shot 2020-06-18 at 1 26 54 PM](https://user-images.githubusercontent.com/8097306/85068515-6441c080-b167-11ea-88d3-985a4b772d1a.png)

**Comment by ParishrutB** [comment]
As per the meeting with Santosh on 3/30, the schema for this might change later and we need to check with @gtmills.

**Comment by Srisuk** [comment]
Updated the missing keys as per the new schema pushed as part of https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40326.

**Comment by Srisuk** [comment]
The schema used to find the missing keys: https://redfish.dmtf.org/schemas/v1/PowerSupply.v1_0_0.json

**Comment by derick-montague** [comment]
Is there a Gerrit review for this story? @dixsie

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43231
