### ISSUE TITLE
Redfish(LDAP):  Add support for LDAP configuration in bmcweb.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#231]
SchemaFile:- https://redfish.dmtf.org/schemas/v1/AccountService.v1_3_1.json

In the above schema file there is a property named ActiveDirectory/LDAP

ActiveDirectory:- Would be used if ldap server is ActiveDirectory
LDAP:- would be used if ldap server is OpenLDAP/ other then AD.

LDAP /ActiveDirectory in redfish is of type of ExternalAccountProvider

Which Redfish Property(ActiveProperty/LDAP) to update it is same as D-Bus Property LDAPType.

Here is a mapping if LDAP Server is OpenLDAP/ActiveDirectory:
```
LDAP/ActiveDirectory:(RedfishProperty)

     AccountProviderType:- "LDAPService",
     ServiceEnabled :- "True,If LDAP needs to be used",
     ServiceAddress:- "Would be mapped to LDAPServerURI(D-Bus Property)",
     Authentication: 
            { "AutenticationType" : "UserNameandPassword"
              "UserName" : "LDAPBindDN (D-Bus Property)" 
               "Password" : "BindPassword "
            },
     LDAPService:
            {
                "SearchSettings" : 
                       {
                            "BaseDistinguishedNames" : "LDAPBaseDN(D-Bus Property)"
                            "UserNameAttribute" : "uid/cn"
                             "GroupsAttribute" : "memberof"
                        },
               },
```
Have not added the mapping for role-mapping, would add it through different story.

D-Bus interface which is used by the backend:- https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/User/Ldap/Config.interface.yaml

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Code is up for review.

https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/16715/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/17294/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
The code is already merged in the master, so closing it.
