### ISSUE TITLE
GUI : FED : Hardware status - BMC manager table missing properties

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2312]
## Overview
The BMC manager table on the Hardware status page is missing properties that were defined in the original design. When these properties are available on the backend, update the table to show missing properties:
- [x] CCIN (Model in Redfish)
- [ ] Location code (Part Location ServiceLabel)
- [x] Identify LED (LocationIndicatorActive in Redfish)
- [x] Hardware type (Name in Redfish)
- [x] Fru number (SparePartNumber in Redfish)
- [x] Manager type (ManagerType in Redfish)
- [x] BMC date and time (DateTime in Redfish)
- [x] Last reset time (LastResetTime in Redfish)

BMC Date   and time
--

## Notes
- [ ] Design/layout has changed from what is currently in InVision mockup

## Final Invision Mockup
- [ ] https://ibm.invisionapp.com/d/main#/console/15347903/319961437/preview

**Comment by ParishrutB** [comment]
As per meeting with Santosh on 3/30, backend code for this has been merged.

**Comment by sandeepasingh116** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/42077

**Comment by derick-montague** [comment]
Blocker: Waiting for `LocationIndicators` to be present in the API before merge is possible.
