### ISSUE TITLE
GUI : FED : Hardware status - Fans table missing properties

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2313]
## Overview
The Fans table on the Hardware status page is missing properties that were defined in the original design. When these properties are available on the backend, update the table to show missing properties:
- [x] Hardware Type (Name in Redfish)
- [x] Identify LED (LocationIndicatorActive in Redfish)
- [x] SpeedPercent(SpeedPercent in Redfish) 
- [x] Health(Health in Redfish)
- [x] State(State in Redfish)
- [ ] IndicatorLED(IndicatorLED in Redfish)
- [ ] Location(Location in Redfish)
- [ ] Manufacturer(Manufacturer in Redfish)
- [ ] Model(Model in Redfish)
- [ ] PartNumber(PartNumber in Redfish)
- [ ] SerialNumber(SerialNumber in Redfish)
- [ ] SparePartNumber(SparePartNumber in Redfish)

## Notes
- [ ] Design/layout has changed from what is currently in InVision mockup
- [ ] Changed table name from Thermal > Fans

## Final Invision Mockup
- [ ] https://ibm.invisionapp.com/share/H5O15ROC4T9#/screens

## Screenshots 

InVision: as of 5/13/21
![Screen Shot 2021-05-13 at 9.13.23 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/560ae94d-16f5-482d-8c9c-467bfd6ab814)

Currently in Vue:
![Screen Shot 2020-06-18 at 1 36 01 PM](https://user-images.githubusercontent.com/8097306/85069250-a8819080-b168-11ea-8724-ed9a862f05f3.png)

**Comment by ParishrutB** [comment]
As per the meeting with Santosh on 3/30, this schema is handled by Derek Howard's team. 
The schema for this might change later and we need to check with @gtmills.

**Comment by Srisuk** [comment]
Updated the missing keys as per the new schema, which is pushed as part of https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41086

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43186

**Comment by Srisuk** [comment]
The schema used to find the missing keys: https://redfish.dmtf.org/schemas/v1/Fan.v1_0_0.json
