### ISSUE TITLE
GUI : FED : Search component - fix icon visibility

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2314]
## Overview
The search icon in the search bar component is visible when the TableToolbar is also active. The icon should not be visible if the TableToolbar is active (visible)

## Steps to Reproduce the Problem
  1. Navigation to Sensors page
  2. Select table rows

## Screenshots
![Screen Shot 2020-06-18 at 1 47 00 PM](https://user-images.githubusercontent.com/8097306/85070189-3b6efa80-b16a-11ea-9667-64b89beb9188.png)
![Screen Shot 2020-06-18 at 1 47 06 PM](https://user-images.githubusercontent.com/8097306/85070196-3dd15480-b16a-11ea-9f2f-b298b04c1416.png)

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34468

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34468 merged
