### ISSUE TITLE
Redfish(LDAP):- Add the support for RoleMapping.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#232]
How to map the redfish properties
https://github.com/ibm-openbmc/dev/issues/224

Need to make the change in the following file in bmcweb to provide this support.
https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/account_service.hpp#L32

-> Add the defuault role mapping property in this class
-> Add the support of patch request to update the property which takes json as input (role, privilege) and add it to the backend.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
changing the points from 8 to 5 as we are not writing the UT.

**Comment by rfrandse** [comment]
refresh

**Comment by ngorugan** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/17943/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/17943 merged
