### ISSUE TITLE
GUI : FED : Overview - Edit network settings link 

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2321]
## Expected Behavior
Clicking the `Edit network settings link on the overview page should direct the user to the network services page.

## Actual Behavior
Clicking the `Edit network settings link on the overview page does not redirect the user

## Steps to Reproduce the Problem

  1. Login
  1. Click on link on Overview page

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34299

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34299 merged
