### ISSUE TITLE
GUI : FED : Event Logs - Add search filter component

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2322]
## Overview
The event logs page does not contain the search filter component that allows the user to filter the table results based on a query

## Final Invision Mockup
- [ ] Add Link

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34265

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34265 merged
