### ISSUE TITLE
GUI : FED : Overview - Server LED toggle does not reflect toggle value in store

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2323]
## Expected Behavior
When the user toggles the SService Indicator LED value on the Server LED page, the value should be reflected on the Server Overview page

## Actual Behavior
Changing the value of the Service Indicator LED on the Server LED page is not reflected don the Overview page.

## Steps to Reproduce the Problem

  1. Login
  1. Go to the Server LED page
  1. Toggle the Service Indicator LED
  1. Go to the Overview page

## Specifications
  - Browser: 
  - Version:

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34335

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34335 merged
