### ISSUE TITLE
GUI : FED : Access Control - Create new user

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2324]
## Expected Behavior
Creating a new user results in a success response

## Actual Behavior
Creating a new user results in a success followed by an error response

## Steps to Reproduce the Problem

  1. Login
  1. Go to Access Control -> Local user management
  1. Create a new user

### Error Code
```
{
  "UserName@Message.ExtendedInfo": [
    {
      "@odata.type": "#Message.v1_0_0.Message",
      "Message": "The requested resource of type #ManagerAccount.v1_4_0.ManagerAccount with the property UserName with the value ReadOnlyUser already exists.",
      "MessageArgs": [
        "#ManagerAccount.v1_4_0.ManagerAccount",
        "UserName",
        "ReadOnlyUser"
      ],
      "MessageId": "Base.1.4.0.ResourceAlreadyExists",
      "Resolution": "Do not repeat the create operation as the resource has already been created.",
      "Severity": "Critical"
    }
  ]
}
```

### Screen shots
![image](https://user-images.githubusercontent.com/1183515/85328299-22ca5180-b496-11ea-972c-d47ae4a72f43.png)

![image](https://user-images.githubusercontent.com/1183515/85328452-5c9b5800-b496-11ea-9bff-1cd2b070967b.png)

![image](https://user-images.githubusercontent.com/1183515/85328466-61f8a280-b496-11ea-9354-f6b7b9f8a7ee.png)

## Specifications
  - Browser: Chrome (expect all browsers)
  - Version: 83.0.4103.97

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33980

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/33980 merged
