### ISSUE TITLE
PFP::presence - Use shared JSON config file finding & loading header

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2325]
A shared JSON config determination header was created based on what was done in the fan presence application for loading its JSON configuration file. The fan presence application should be switched over to using this shared header so all fan applications attempt to get their respective configs similarly.

**Comment by JolieKu** [comment]
Confirm with you that these two header files (`phosphor-fan-presence/json_config.hpp` and `phosphor-fan-presence/presence/json_config.hpp`) have the same defined functions(`getconfigfile()` and `load()`). 
Do you want to remove these two functions from `phosphor-fan-presence/presence/json_config.hpp` and modify the functions which are called by these two functions in `phosphor-fan-presence/presence`?

**Comment by msbarth** [comment]
Yes. This issue is to get `phosphor-fan-presence/presence` using the same shared header for JSON config file loading instead of using its own functions. Then once `phosphor-fan-presence/presence` uses the functions available in `phosphor-fan-presence/json_config.hpp`, the similar functions can be removed from the `phosphor-fan-presence/presence/json_config.[hpp|cpp]`....There will be some necessary modifications to `phosphor-fan-presence/presence/json_config.cpp` in regard to how it calls the `getConfFile` and `load` functions.

**Comment by JolieKu** [comment]
I just push code to gerrit 
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/35651

I have run local ci and compiled pass, is the "Tested" needed?

**Comment by msbarth** [comment]
> I just push code to gerrit
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/35651

I'll take a look soon as I can, thanks!

> I have run local ci and compiled pass, is the "Tested" needed?

Yes, the `Tested` section of the commit describes what tests have been run.
https://github.com/openbmc/docs/blob/master/CONTRIBUTING.md#testing

Unfortunately, the phosphor-fan-presence repo has an extremely limited amount of automated CI unit tests so the `Tested` section is that more important on changes here to show the manual tests that were done to verify the commit. If you're able to include updated unit tests for this change, that'd be great...if not, then a set of manual tests need to be done on this change and noted in a `Tested` section in the commit msg.

**Comment by JolieKu** [comment]
OK, I see.
I am not sure how to test it manually.
I have added this patch to build witherspoon, is it work to use dbus-monitor to test it by qemu?

**Comment by msbarth** [comment]
Are you able to test on witherspoon hardware?

The change you made can be tested in qemu by placing the phosphor-fan-presence-tach binary in the image and running it against the different locations where the config.json file can reside (`/usr/share/phosphor-fan-presence/presence/config.json` or `/etc/phosphor-fan-presence/presence/config.json`). It should still correctly find and load the fan presence configuration from those locations.

Of course, the best would be to add unit test cases for fan presence against loading the config file, but if you're able to verify the config file is being loaded/used from those locations still, that should be sufficient. Thanks.

**Comment by JolieKu** [comment]
Run phosphor-fan-presence-tach can find & load config file in qemu and I have updated the "Tested" section in commit msg.

**Comment by msbarth** [comment]
Thanks! I've reviewed your commit and posted some feedback.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/35651
