### ISSUE TITLE
PLDM: FRU: simplify BMC FRU table construction

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2329]
We should be able to map standard D-Bus FRU inventory properties to standard FRU properties from the PLDM FRU spec. This will simplify things (by enabling removal of JSON files). Following changes are needed :

1) No need to install https://github.com/openbmc/pldm/tree/master/configurations/fru
2) https://github.com/openbmc/pldm/blob/master/libpldmresponder/fru_parser.cpp#L29 should _always_ invoke `setupDefaultDBusLookup()` and `setupDefaultFruRecordMap()`
3) `setupDBusLookup()` should no longer be needed
4) `setupFruRecordMap()` should still be called to process any OEM FRU JSONs (for eg https://github.com/openbmc/pldm/tree/master/oem/ibm/configurations/fru)
5) https://github.com/openbmc/pldm/blob/master/libpldmresponder/fru_parser.cpp#L108 needs to be updated to include ann entity types from the FRU_master.json from 1).

Testing : same FRU table content as before should be generated. Verify response obtained via pldmtool against the spec.

**Comment by mzipse** [comment]
After review with Tom Joseph, this was determined to be post GA1.  Taking out of current sprint.

**Comment by sagisin** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/34651
