### ISSUE TITLE
Redfish(LDAP): Move the logic of changing the PAM Configuration to UserManager

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#233]
In existing implementation changing of PAM configuration file lies in the Process(restServer).
Flow is as below
-> Create the LDAP Config
-> Interested Service/Process receives the Interface added/Removed signal and then change the PAM configuration file.
With the above approach, Ed suggested that changing of pam Configuration file should not be done in the context of rest-server as it brings the security vulnerability.

So with this commit we can move this logic to UserManager which is central place.
We can also discuss this in the design meeting if needed.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Assign it to ManojKiran Eda.

**Comment by rfrandse** [comment]
refresh

**Comment by manojkiraneda** [comment]
code is up for review in the below commit.
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc/+/17860/)

**Comment by bradbishop** [comment]
On Fri, Feb 01, 2019 at 04:32:10AM -0800, ManojKiran Eda wrote:
>code is up for review in the below commit.
>https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc/+/17860/)

Please resubmit to openbmc/meta-phosphor (and have a read of
https://raw.githubusercontent.com/openbmc/docs/master/subtree.md )

**Comment by manojkiraneda** [comment]
Thanks Brad, i did not knew that. I have abandoned the old one.

The new commit is present in https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/17975

**Comment by bradbishop** [comment]
On Wed, Feb 06, 2019 at 12:19:44PM +0000, ManojKiran Eda wrote:
>Thanks Brad, i did not knew that. I have abandoned the old one.
No problemo!

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
This fix is merged, hence closing it.
