### ISSUE TITLE
GUI : FED : Style guide - Colors

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2330]
## Overview
Update gray color palette to match the new design guide. Updates should be made to bmc [colors file ](https://github.com/openbmc/webui-vue/blob/master/src/assets/styles/bmc/helpers/_colors.scss)

- [x] $gray-800
- [x] $gray-300
- [x] $gray-200
- [x] $gray-100

## Notes
- Walk through screens with @ben-bacon when changes made

## Final Invision Mockup
https://ibm.invisionapp.com/share/U9O039T4Q6E#/screens/319573687_Color_Updates

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34731

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34731 merged
