### ISSUE TITLE
GUI : FED : Style guide - Typography

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2331]
## Overview
Make updates to reflect changes in new style guide. Make updates and validate:

- [x] Form labels 
- [x] Form helper text
- [x] Static `<dl>` elements
- [x] Page title
- [x] Section title

## Final Invision Mockup
https://ibm.invisionapp.com/share/EQO03IP5MA6#/screens/319563625

## Notes
Do not need to check:
- [ ] Buttons text styles #2332  
- [ ] Form error validations #2333 

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34894 merged
