### ISSUE TITLE
GUI : FED : Style guide - Buttons

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2332]
## Overview
Make updates to global button styles to reflect changes in new style guide. 

- [ ] Primary, Secondary, Link button variants
  - [ ] hover state (Link button only)
  - [ ] disabled state (Link button only)
  - [ ] focus state
  - [ ] font weights and colors

## Notes
- Link button needs specific overrides/custom code to handle hover/disabled states. the other button variants should inherit the bootstrap hover/disabled visual styles.
- Link button font weight is different than primary/secondary

## Final Invision Mockup
https://ibm.invisionapp.com/share/U9O039T4Q6E#/screens/319575456

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by ben-bacon** [comment]
Updated link for text button style overview: https://ibm.invisionapp.com/share/U9O039T4Q6E#/319613166_Button_Examples

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35678
