### ISSUE TITLE
GUI : FED : Style guide - Form fields

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2333]
## Overview
Make updates to form fields to reflect changes in new style guide. Make updates and validate:

- [x] Input, select, textarea
- [x] Changes to background color
- [ ] Field error state
- [x] Field focus state
- [x] Placeholder text

## Final Invision Mockup
https://ibm.invisionapp.com/share/U9O039T4Q6E#/screens/319560582

## Notes
- [x] New styles have a darker form field background color. If the form field is on a grey background, then it should remain white
- [ ] New form field error state has an error icon in the field
- [x] Make updates to error message size if needed

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by dixsie** [comment]
resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34914

**Comment by ben-bacon** [comment]
Input fields: https://ibm.invisionapp.com/share/37O0A2VZCYF
working on showing you the dropdowns, they follow the same structure and order of information as input fields + icon.
