### ISSUE TITLE
GUI : FED : Style guide - Checkbox

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2334]
## Overview
Make updates to global input checkbox styles to reflect changes in new style guide. Make updates and validate:
Checkbox:
- [ ] Checked/unchecked state
- [ ] Focus state
- [ ] Disabled state

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshots
<img width="493" alt="Screen Shot 2020-06-24 at 9 16 04 AM" src="https://user-images.githubusercontent.com/8097306/85592831-5d013380-b5fb-11ea-850d-146310f2cdda.png">

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35919

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35919 merged
