### ISSUE TITLE
GUI : FED : Style guide - Table toolbar

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2335]
## Overview
Update table toolbar cancel button to match updates in style guide. The cancel button should be changed to a secondary button variant

## Final Invision Mockup
https://ibm.invisionapp.com/share/D8O06PPE32B#/screens/319599536

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshots
<img width="761" alt="Screen Shot 2020-06-24 at 9 21 14 AM" src="https://user-images.githubusercontent.com/8097306/85593633-0fd19180-b5fc-11ea-8708-44e009185d12.png">

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35468
