### ISSUE TITLE
GUI : FED : Style guide - Table

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2336]
## Overview
Make updates to global table styles to reflect changes in new style guide.

- [ ] Cell text alignment: if column is sortable, the text should align with header label (not the sort icons)
- [ ] Updates to cell backgrounds (header and body rows)
  - [ ] hover
  - [ ] selected
  - [ ] expanded (tbd)
- [ ] Styles for focus state on interactive header cells

## Final Invision Mockup
https://ibm.invisionapp.com/share/D8O06PPE32B#/screens

## Notes
- [ ] If the table header is interactive (sort or select all) the header cell should have a hover state
  - [ ] Need to center align select all checkbox in header inside 48px column width

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshots

Interactive (sortable) table header focus state:

<img width="205" alt="Screen Shot 2020-06-25 at 8 14 45 AM" src="https://user-images.githubusercontent.com/8097306/85747354-10316180-b6bc-11ea-97e8-abad35dfdc39.png">

Table data alignment:
<img width="543" alt="Screen Shot 2020-06-25 at 8 15 11 AM" src="https://user-images.githubusercontent.com/8097306/85747397-1cb5ba00-b6bc-11ea-9319-e5cd50df9977.png">

**Comment by ben-bacon** [comment]
WIP: https://ibm.invisionapp.com/share/D8O06PPE32B

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36477
