### ISSUE TITLE
GUI : FED : Style guide - Alerts

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2337]
## Overview
Alerts should include an info icon for informational alert banners to match style guide

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshots

<img width="484" alt="Screen Shot 2020-06-24 at 9 37 26 AM" src="https://user-images.githubusercontent.com/8097306/85596146-545e2c80-b5fe-11ea-99d8-9fc9f215a6fa.png">

**Comment by ben-bacon** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/52676199/86796473-3e0b9400-c034-11ea-93fe-d64a2ab4bc11.png">

**Comment by ben-bacon** [comment]
can include area for a ghost button if a specific action is required

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35433

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35433 merged
