### ISSUE TITLE
GUI : FED : Documentation not rendering correctly

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2338]
## As Is
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/d18d92c3-ace0-4036-a124-a17af66e1c2c)

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/777d6756-5d78-4f60-b977-bc1bbfdc4bfd)

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/eb457b01-d411-4fb9-add9-02fc8a8d5d6f)

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34083

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34083 merged
