### ISSUE TITLE
Enhance PSU tracing support - add device access info

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2339]
From: Bradley W Bishop/Rochester/IBM
Subject: Interlock with Australia team - OpenBMC/SP-Next Discussion
Date: Mon, Jun 1, 2020 3:41 PM

Hi all
I had a todo from the 5/13 call to start to formalize the OpenBMC logging best practices and then identify some work we could do to implement those - the immediate goal being to make debugging problems faster when we do P10 bringup.

I think this will be an iterative process - the one I've heard the most feedback on is that journal -o verbose is required to debug and slows things down, so I started with that and put something out on the project mailing list here:

https://lists.ozlabs.org/pipermail/openbmc/2020-June/021899.html

If you could have a look and weigh in that would be appreciated. Also if you have any thoughts on what the next anti-pattern to fix should be please reply here or to my post on the mailing list, and I'll push that along.

To get started I propose we audit these repositories for interactions with the kernel:

phosphor-hwmon
ibm-vpd-parser/openpower-vpd-parser
phosphor-power

and ensure that anywhere we are doing fileops on i2c devices we add the filename, system call and errno to the MESSAGE field.

To do this, we should implement a phosphor::logging::log wrapper that enables a MESSAGE field format string (right now it only works with a fixed string).

thx - brad

**Comment by jjaymeyer** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/35948
