### ISSUE TITLE
Redfish(LDAP): Implement GetUserInfo function in phosphor-user-manager

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#234]
In existing implementation rest server fetches the details of the user as follows 
```
1) Check if it is local user then get the privilege of the local user.
2) if it is not local user
      a) Get the LDAP group name of the user.
      b) iGet the privilege mapping for the LDAP group.
```
This functionality should go to the Phosphor-User-Manager and the service which requires the User privilege will make the D-bus call to fetch the UserInfo/Privilege.

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Assign it to Ravi Teja

**Comment by rfrandse** [comment]
refresh

**Comment by raviteja-b** [comment]
code is up for review https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-user-manager/+/18132/

**Comment by rfrandse** [comment]
refresh

**Comment by raviteja-b** [comment]
writing unit test

**Comment by raviteja-b** [comment]
Resolved by  https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-user-manager/+/18132/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
There were some dependency in the commits so had to squash the above commit with the following commit https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-user-manager/+/18552/.
The above mentioned commit is merged, hence closing this issue.
