### ISSUE TITLE
eBMC LED Management : Detect and bind cable cards on CM

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2341]
Cable cards are CM'able and hence need to have a code that :

 - detects the card being added / removed
- Do bind / unbind to leds-gpio driver for CXP 9551
- Make sure to chose the same name as in dts

**Comment by spinler** [comment]
Not sure if it helps, but phosphor-gpio-presence watches for a presence detect GPIO and then updates the inventory accordingly, and can also bind/unbind any drivers given to it in its config file.

**Comment by vishwabmc** [comment]
> Not sure if it helps, but phosphor-gpio-presence watches for a presence detect GPIO and then updates the inventory accordingly, and can also bind/unbind any drivers given to it in its config file.

@spinler this is great.. I have a need to bind `leds-gpio` driver to it. Basically for the 9551 that's on CXP

**Comment by santoshpuranik** [comment]
This is the plan for P10:

The VPD app has the capability to perform pre/post actions. When we have successfully collected VPD for the cable card, as a post action we will bind the leds-gpio driver to the right I2C bus and address for the PCA chip on the cable card.

On a CM remove action, we can unbind the device driver (there should be no need to check if one is already bound). The CM remove is a D-Bus method implemented

**Comment by rfrandse** [comment]
tracking in jira
