### ISSUE TITLE
GUI : FED : App Navigation - User focus lost in menu when closed

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2344]
## Overview
When the navigation is removed from view a keyboard user will have to tab through the hidden content in order to get to the page. This can cause confusion for the user as their focus within the page is lost when tabbing.

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [x] Tested responsive layout on supported viewport sizes
- [x] Verified functionality works as expected, e.g. success and failure use cases
- [x] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [x] Verified markup is semantic
- [x] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34189

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34189 merged
