### ISSUE TITLE
VMI Certificate Exchange Stage 2

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2345]
=> Stage 2 is where multiple request should be allowed
=> Dbus based approach
=> Create a request object where CSR fd and Certictate FD would be properties of the dbus object.
=> Implement the back end in phosphor-certificate manager.
=> Write the unit test.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
