### ISSUE TITLE
 openbmctool changes to adapt the new changes in the DMTF for dump.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2348]
=> There are some property name changes in the approved/merged DMTF proposal which need to be incorporated
=> Some enum values changes for the dump types.

**Comment by ratagupt** [comment]
Upstream commit for this story is here: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/36993

**Comment by mzipse** [comment]
Commit merged.  Closing this.
