### ISSUE TITLE
Redfish(LDAP):- How to authorize the request with existing redfish implementation for LDAP users?

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#235]
In existing implementation when user successfully authenticates itself then we assign the priv to the session and in subsequent request priv in the session is used for authorization of REST API.

I don't see this priv assignment in the bmcweb when the session is being created.
bmcweb(redfish) returns the X-authToken and the sessionID once the session is created.

Seems to me the priv is tied with user in the account service.

Few tasks are identified
Implement the authorization for 
-> LDAP users
-> Check whether the request if being authorized for local users/not if yes then how.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Rajeswaran is working on it.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by trajeswaran** [comment]
Resolved by : https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/27952

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/27952 merged
