### ISSUE TITLE
Implement Meson for phosphor-networkd

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2350]
=> Make sure all the compile time configuration works fine with Meson Build
=> Unit test/Code coverage should work fine.

**Comment by manojkiraneda** [comment]
Code is up for review at :
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/33071/17

**Comment by manojkiraneda** [comment]
phosphor-netword is migrated to meson.
