### ISSUE TITLE
Implement Meson for bmcweb

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2351]
=> bmcweb is a cmake based repository.
=> Migrating it to meson have definitely compile time improvement.
=> Make sure all the compile time variable works fine.
=> Necessary changes to be done in the bmcweb_git.bb for the changed compile time variable.

**Comment by amboar** [comment]
> => Migrating it to meson have definitely compile time improvement.

Do we have numbers to back this up? As in, is the task just to upstream patches based on measurements that we've taken after making the changes?

**Comment by manojkiraneda** [comment]
> > => Migrating it to meson have definitely compile time improvement.
> 
> Do we have numbers to back this up? As in, is the task just to upstream patches based on measurements that we've taken after making the changes?

The initial thought of migration was based on :
https://mesonbuild.com/Simple-comparison.html

bmcweb uses traditional cmake+make infrastructure, although cmake also supports ninja backend, configuration though cmake is a bit clumsy and not developer friendly, so the idea is to migrate it over to meson(very simple & intuitive way to configure) + ninja which seems to be proven fastest combination in-terms of compilation & build time.

meson also supports lto , code coverage by default, there by adds less development effort to add those.

Initial work was drafted in the following commit ,
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32816

we do have values as we observed definitive improvement but those values do change based on various factors like build type, features , machine type and we would like to post those numbers only after we get the maintainers +1.

**Comment by manojkiraneda** [comment]
https://gerrit.openbmc-project.xyz/q/topic:%22bmcweb_meson_port%22+(status:open%20OR%20status:merged)

All the commits are merged and bmcweb is already migrated to meson & cmake support has been completely removed from the repo.
