### ISSUE TITLE
GUI : FED : Profile settings - clear password

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2353]
## Overview
After successfully saving a new password on profile settings, clear the input fields

## UX Flow / Interaction Requirements
- [ ] Navigate to profile settings, save new password
- [ ] If password successfully changed, clear input fields

**Comment by Srisuk** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34632
