### ISSUE TITLE
GUI : FED : Tables - total count

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2354]
## Overview
Add total item count to tables. Should be next to search input component showing the total filtered entries and total entries. The total filtered entries would include entries filtered by dropdown and/or search. It should not include pagination or selected rows.

Create a reusable component. The label next to the count should be a dynamic prop to provide as much context/clarity to the user. `items` will be a fallback.

The event log table with 200 items could show:
`200 logs` when no filters are active or
`60 of 200 logs` when some filters are active

- [ ] Event logs
- [ ] Hardware status (DIMM slot, Fans, Power supplies)
- [ ] Sensors 

## Final Invision Mockup
https://ibm.invisionapp.com/share/D8O06PPE32B#/screens/319599536

## Screenshots
![Screen Shot 2020-06-30 at 11 43 37 AM](https://user-images.githubusercontent.com/8097306/86164726-12822a00-bac7-11ea-833a-20d19197d607.png)

**Comment by Srisuk** [comment]
Resolved By: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35102

**Comment by derick-montague** [comment]
@Srisuk - Looks like there are some unresolved comments from Yoshie from the 25th. :)
