### ISSUE TITLE
Redfish: Implement host state boot/OS progress

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2355]
https://github.com/ibm-openbmc/dev/issues/479 added this to Redfish 
This should be in 2020.3

The D-Bus interface has been enhanced: 
https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/State/Boot/Progress.interface.yaml#L29

```
D-Bus                                            Redfish
PrimaryProcInit                       PrimaryProcessorInitializationStarted
BusInit                       BusInitializationStarted
MemoryInit                       MemoryInitializationStarted
SecondaryProcInit                       SecondaryProcessorInitializationStarted
PCIInit                       PCIResourceConfigStarted
SystemInitComplete                       SystemHardwareInitializationComplete
OSStart                       OSBootStarted
OSRunning                       OSRunning
MotherboardInit                       @geissonator Just ignore? or should we map to something above?
Unspecified                       @geissonator Just ignore?  
```

@geissonator We do have a None Redfish. Should we use that at some point?

https://github.com/ibm-openbmc/dev/issues/2017 is the GUI story

**Comment by gtmills** [comment]
This will be in 2020.3 which should be out early September, after we move to 2020.3 this work can start

**Comment by gtmills** [comment]
@geissonator To enhance existing D-Bus interfaced. 
This story is waiting for that for now.

**Comment by mzipse** [comment]
@gtmills Can this issue be unblocked now?  2020.3 spec is out.  Anything holding this work up?

**Comment by gtmills** [comment]
@geissonator Now that https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/38253 is merged can this be worked from a Redfish/bmcweb point?

**Comment by geissonator** [comment]
> @geissonator Now that https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/38253 is merged can this be worked from a Redfish/bmcweb point?

https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38437 was the Redfish API support for it so I think GUI team is good to go now.

**Comment by gtmills** [comment]
This work is done.
