### ISSUE TITLE
GUI : FED : Table filter - refactor component

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2356]
## Overview
Refactor TableFilter and TableFilterMixin. Code updates needed to support having a key value with the filter object, so we can check the right property against select tags. Should also include data-test-id hooks

https://github.com/openbmc/webui-vue/blob/master/src/components/Global/TableFilter.vue#L54

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34346

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34346 merged
