### ISSUE TITLE
Handle PELs deleted from the filesystem

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2357]
Because 
a) Deleting a Redfish (and hence OpenBMC) event log can't delete the PEL file since it's needed for a dump  and
b) peltool should still be able to delete PELs and it can no longer just delete the OpenBMC event log

I can just make peltool delete the PEL file, and have the daemon watch for deleted files and handle it as if the delete came in normally.

This story is for the daemon watching for deleted files.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/34735

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/34735 merged
