### ISSUE TITLE
Redfish(local User) :- Impelment the support for local Users

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#236]
Seems to me local user management support is there in redfish , what is not there is account policy implementation.
```
Redfish Property:                            D-Bus Property

MinPasswordLength :                     MinPasswordLength
AccountLockoutduration:                AccountUnlockTimeout
AccountLockoutThreshold:             MaxLoginAttemptBeforeLockout
```
The below D-bus interface is for reference.

https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/User/AccountPolicy.interface.yaml 

With this issue we can provide the support for the same, If Intel has not started for it.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Refresh

**Comment by mzipse** [comment]
Refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
I could have seen that the above properties have been implemented recently.
There is not an update/patch support for MinPasswordLength as it is a read-only property in redfish.

```
MinPasswordLength |  
description | "The minimum password length for this service."
longDescription | "This property shall reference the minimum password length that the implementation will allow a password to be set to."
minimum | 0
**readonly | true**

```

**Comment by ratagupt** [comment]
I find that user locked property was not implemented so I have implemented that property.
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/17772/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Above commit is merged so closing this issue.
