### ISSUE TITLE
GUI : Research : Power Control Network Trace

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2360]
## SME
**BMC**: Derek Howard, Matt Spinler
**RAS**: TBD
**PHYP**: Adam Stallman

## Summary
This is for getting I/O Tower (eg mex) traces from the field.

### Background
- [ ] TBD

### End users
- [ ]  TBD

### User Needs
- [ ] TBD

### User Quotes
- [ ] TBD

## User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

## References
- [ ] eBMC Feature Item <add number>
- [ ] Link to Discovery folder

**Comment by derick-montague** [comment]
The conversation for this story is in this [slack thread](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1593637746108800)

**Comment by nicoleconser** [comment]
Followed up w/ Adam Stallman, Matt Spinler, Derek Howard, Gunnar Mills on [Slack](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1594744140300300?thread_ts=1593637746.108800&cid=C0Q6TQP5Z) to see if any decisions were made regarding whether to make this a new spcn trace dump or include it as part of the existing phyp resource dump.

**Comment by derick-montague** [comment]
@nicoleconser This was discussed in the OpenBMC Design Exchange meeting today. You can [view the notes](https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/W5d74d2bb8660_4d6e_9bb6_08e4fc6ff375/page/OpenBMC%20Design%20Reviews) from 7/21. At current, this will not required GUI work. Discussing as being part of  a Resource dump. @gtmills will update if something changes.

**Comment by nicoleconser** [comment]
Need confirmation from PHYP / @derekhoward55 / @spinler on whether we can close this or not (we understand this is going into a Resource dump).

**Comment by nicoleconser** [comment]
> @nicoleconser This was discussed in the OpenBMC Design Exchange meeting today. You can [view the notes](https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/W5d74d2bb8660_4d6e_9bb6_08e4fc6ff375/page/OpenBMC%20Design%20Reviews) from 7/21. At current, this will not required GUI work. Discussing as being part of a Resource dump. @gtmills will update if something changes.

Closing this.
