### ISSUE TITLE
CEC CM:  Normalize entity association PDR from Host

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2366]
The BMC merges host's entity association PDRs into it's own repo. This can change the entity instance numbers and container ids. The same must be reflected in host's PDRs that point to this entity.

**Comment by sampmisr** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/35480

**Comment by sampmisr** [comment]
the design has changed and we are taking this up as part of CEC CM work

**Comment by manojkiraneda** [comment]
upstream commits :
Normalization fru record set and state sensor/effecter PDRs from Host | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/45466/20
Customise the DbusObject paths as per IBM | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/45803/16
Implement CpuCore Interfaces for cores | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/42619/26
Add the support for Inventory Item dbus Interface | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/42098/31
Process state sensors PDRs and update Operational Fault Status | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/39796/67
Handle FRU records from host | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/39588/77
Handle entity association records from host | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/39198/79
Update mergeEntityAssociations logic | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/43032/41
libpldm : Enhance the find & add pdr utilities | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/44699/19
Fix buildFRUTable and update to Association tree | https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/42833/36

**Comment by manojkiraneda** [comment]
code is merged downstream : tag 29
