### ISSUE TITLE
Replace sync_inventory_items

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#237]
As part of removing Python, replace sync_inventory_items with other C/C++/shell script apps that implement syncing of MAC address and UUID from the VPD to u-boot.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ngorugan** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-openpower/+/17471/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-openpower/+/17471 merged
