### ISSUE TITLE
PLDM: Mechanism to associate sensor/effecter to FRU entity

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2371]
Currently when effecter/sensor PDRs are created, the entity information - instance and container id, is hard coded to 0. For eg https://github.com/openbmc/pldm/blob/master/configurations/pdr/11.json#L7. While this works for system level PDRs, in certain cases we need to associate the sensors/effecters with specific FRU entities (for eg associated LEDs to FRUs)

Enable this by introducing a "entity_path" key in the PDR JSONs. This will have a FRU D-Bus object path as the value. When this is present, the entity type, instance and container id should not be present in the JSON (should be ignored if they are). The PDR construction code should consult the FruHandler (https://github.com/openbmc/pldm/blob/master/pldmd/pldmd.cpp#L192) to query entity information (type, instance and container id) based on D-Bus object path and add the same to the PDR. The FruHandler must implement an API for the same. The FruHandler can note this information in a data structure when it makes FRU entities (https://github.com/openbmc/pldm/blob/master/libpldmresponder/fru.cpp#L89).

**Comment by lxwinspur** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/34647
