### ISSUE TITLE
GUI : FED : Server LED - refactor component

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2372]
## Overview
On initial load, a toast appears if the LED is on. This happens because the default store value is off–when it is changed after fetching the initial value from the backend, this computed value is updated and triggers the toast.

Refactor the Server LED component to make sure that a toast doesn't appear on initial load. An event callback should be added to the form component and the methods to initiate toasts should be moved out of the setter and into the callback.

**Comment by SurenNeware** [comment]
Resoled By: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34805
