### ISSUE TITLE
IBM CFFPS device driver does not correctly control LEDs

### ISSUE THREAD

**Issue by bjwyman** [ibm-openbmc/dev#2375]
## Expected Behavior
When a power supply fault occurs, or a request to phosphor-led-manager is made to change the LED state, the LED should turn on for a fault, or go to blink state if requested/supported.

## Actual Behavior
No LED changes for fault/blink occur on non-Witherspoon power supplies.

## Steps to Reproduce the Problem

  1. Chassis power on Rainier (with bring-up power supplies).
  2. Cause a power supply fault (remove AC?)
  3. Check amber/fault LED. (NOT on, should be on)

**Comment by bjwyman** [comment]
It was noticed that the amber LED used for fault indication was not turning on for power supplies used for Rainier bring-up.

Manual control of the DAh commands was initially not working using `i2cset`. All `i2cget` operations to all supplies was returning 0x00 after writing 0x02, 0x04, 0xFF.

Some bits are reserved, and should not be attempted to change.

The default state is 0x00, power supply in control, BMC NOT in control.

Bits 7 and 6 control whether the command is intentionally trying to do a write to change the LED state. Bit 7 should be low (0), bit 6 should be high (1), in order to perform a change of the LED state.

The Witherspoon power supply was supposed to have the same write control in place, but apparently at least some power supplies did not properly check those bits, The other IBM CFFPS power supplies appear to all be enforcing those bits.

LED Off (no PSU firmware control): 0x44
LED Blink: 0x41
LED ON: 0x42

The device driver apparently writes 0x04 for off, 0x02 for on. These writes get rejected by non-Witherspoon power supplies.

**Comment by bjwyman** [comment]
@eddiejames pointed out this change: 
https://github.com/openbmc/linux/commit/74a71a831bea81ebb3feb379e62c8accbbec5476#diff-425b49bde3f53a9740fccda555025e4d34c97339a74423e9ca0e6baa5565f0a3
That possibly fixed this.

**Comment by mzipse** [comment]
@bjwyman Does the above fix fix the issue? Or is this still an issue?

**Comment by bjwyman** [comment]
@mzipse No:
>Bits 7 and 6 control whether the command is intentionally trying to do a write to change the LED state. Bit 7 should be low (0), bit 6 should be high (1), in order to perform a change of the LED state.

**Comment by bjwyman** [comment]
Tested image with patch for LED control, and some other fixes.

LED control did not work with prior version of code. Attempted control with echo commands of timer, 255, none to trigger, brightness, and trigger. No change. LED remained off. Confirmed i2cget reading back 0x44. Manually controlled with i2cset. 0x44 off, 0x42 on, 0x41 blink.

With kernel patch, commands to `/sys/class/leds/...` worked as expected.

**Comment by bjwyman** [comment]
http://patchwork.ozlabs.org/project/openbmc/patch/20210728224140.3672294-1-bjwyman@gmail.com/

**Comment by amboar** [comment]
@bjwyman have you fixed up Guenter's comment?

**Comment by bjwyman** [comment]
No.

**Comment by bjwyman** [comment]
http://patchwork.ozlabs.org/project/openbmc/patch/20210806225131.1808759-1-bjwyman@gmail.com/

**Comment by bjwyman** [comment]
Ooo! Patch was applied.

**Comment by bjwyman** [comment]
I had forgotten what it means when Guenter Rock indicates a patch is applied.

I have a bookmark I tracked down, it apparently means that it is merged/committed to his hwmon-next branch: 
https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/commit/?h=hwmon-next&id=9fed8fa99334ed661bf148f6e166c487889d7dee

**Comment by bjwyman** [comment]
https://github.com/openbmc/linux/commit/d672fc0a2a0fc5b02eb450b8a1b96c08a00e2503
