### ISSUE TITLE
GUI : FED : Update table actions cancel button

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2380]
## Task
- [ ] Update the cancel button in the table batch actions to use secondary button variant.

![image](https://user-images.githubusercontent.com/52676199/86368014-53527e00-bc42-11ea-910a-c9cca269120d.png)

_Originally posted by @ben-bacon in https://github.com/ibm-openbmc/dev/issues/580#issuecomment-653022862_

**Comment by ben-bacon** [comment]
Referenced here: https://github.com/ibm-openbmc/dev/issues/2335

**Comment by derick-montague** [comment]
Duplicate
