### ISSUE TITLE
phosphor-regulators: Make poll interval configurable for monitoring regulators

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#2382]
Currently the phosphor-regulators application monitors regulators at a fixed interval.  This includes reading sensors and checking for phase faults.

The JSON config file could be enhanced to support specifying the interval.  A 'global' property could change the interval for all regulators/sensors.  Or a lower level property could change it for selected regulators or sensors.  The design is TBD.

**Comment by derekhoward55** [comment]
No known usage for this; closing.
