### ISSUE TITLE
GUI : FED : Date and Time - NTP to Manual Bug 

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#2383]
## Overview
- [ ] When switching from NTP to Manual, the changes do not persist because NTP has not fully stopped
- [ ] Temporarily add timeout to workaround on frontend while backend explores a more permanent solution

## Notes
- [ ] https://github.com/openbmc/openbmc/issues/3459

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

**Comment by dixsie** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34695

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34695 merged
