### ISSUE TITLE
Host firmware anti-rollback minimum secure version

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#2384]
This is the BMC piece of the design for OpenPOWER host firmware anti-rollback protection.

In that design: The host firmware (PNOR) has a "secure version" field (an integer that starts at 0).  Firmware developers increment this field when there is a significant security fix.  OpenPOWER systems remember the "minimum secure version" and will not allow firmware that has a smaller version.  In this way, an OpenPOWER system cannot have its firmware rolled back to a version that has a security bug, aka anti-rollback protection.
Note the "minimum secure version" function is independent from the minimum ship level (MSL).

This issue is to track the BMC function that works with OpenPOWER minimum secure version design.  Will the BMC detect and prevent host firmware rollback?  Alternately, if the host fails because of its anti-rollback protection: how will the BMC detect and report this to the BMC operator?

**Comment by anoo1** [comment]
Merged. The conclusion was that the BMC would use the Minimum Ship Level as an indicator to log an error.
