### ISSUE TITLE
Dynamic device tree loading for BMC

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2385]
The goal is to build a single flash image that support multiple IBM systems. To do this, we need to support loading a device for the BMC that is specific to the system.

High Level Design
- Load basic device tree initially, enough to get userspace code up and ability to read VPD to determine system type
- Userspace code that reads VPD (or some other system type property), points u-boot variable to correct device tree for system and reboots the BMC
- u-boot sees variable set and ensures proper system-specific device tree is loaded and used

**Comment by anoo1** [comment]
This may require to package the different device trees in the fitImage, adding a task:

- Package the different device trees in the fitImage for u-boot to choose which one to load.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by manojkiraneda** [comment]
@geissonator @ratagupt  looking at 

> Userspace code that reads VPD (or some other system type property), points u-boot variable to correct device tree for system and reboots the BMC 

If the same userspace code which reads VPD also get the MAC address from VPD and set the uboot variable **ethaddr** / **eth1addr/eth2aadr**, we can set the MAC at first boot itself right ? ,  If this is possible we can get rid of the user-space code in networkd or any service to set first boot MAC address right ?

Do you think it is posible ?

**Comment by bradbishop** [comment]
> Do you think it is possible ?

It is possible but I don't think we want to do that.  We'd be moving from a shared solution that works for everyone to an ibm-only solution, which means we incur the maintenance cost ourselves.  With the current solution the maintenance cost is distributed to everyone.


No, because 

Hi Manoj - an interesting question - can you take it to the mailing list?  I'd like to keep this issue focused on device tree loading only.

**Comment by rfrandse** [comment]
refresh

**Comment by manojkiraneda** [comment]
> > Do you think it is possible ?
> 
> It is possible but I don't think we want to do that. We'd be moving from a shared solution that works for everyone to an ibm-only solution, which means we incur the maintenance cost ourselves. With the current solution the maintenance cost is distributed to everyone.

got it brad, understood.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
