### ISSUE TITLE
GUI : FED : Add CPU and GPU to HW Inventory

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2387]
## Overview
CPU and GPU are not included in the HW Inventory. 

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
```
curl -k  https://$bmc/redfish/v1/Systems/system/Processors/
```

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by derick-montague** [comment]
@yoshiemuranaka - Test team noticed that these are missing. Not sure if they were missed or if they aren't available in the API.

**Comment by derick-montague** [comment]
Unclear what properties should be in the table. This was not initially included in the designer mocks.

**Comment by yoshiemuranaka** [comment]
Original design story #1739

**Comment by yoshiemuranaka** [comment]
Slack convo: https://ibm-systems-power.slack.com/archives/C1HT3FHNK/p1594418623398400

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35321

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35321 merged
