### ISSUE TITLE
GUI : Design : Hardware Deconfiguration Policies and Records

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2388]
## Use Case(s)
- [Research Discovery Epic](https://ibm.ent.box.com/notes/668009936935?s=iebfz3tc9cde5205dhfdxev4rmjplcdq)

## Design Goals
- [ ] Consolidate 5 ASMI pages attributed to Hardware Deconfiguration to provide a more informative "hub" to manage deconfigured resources.
- [ ] Level 2 & 3 PEs can easily guide users to identify a deconfigured resource, get a live-text Log, and use that information to reconfigure a deconfigured resource - while maintaining scale-ability for a multi-node system.
- [ ] Level 2 &3 PEs can easily trace and obtain deconfiguration records and attempt to force-reconfigure them in one location. 

## InVision Prototype
- [Deconfiguration Records](https://ibm.invisionapp.com/share/T9O0D452VUC)
- [Hardware Deconfiguration](https://ibm.invisionapp.com/share/X4O0DTDQWFU)

## New compoents introduced
- In-page tab system 
  - [Bootstrap Vue component](https://bootstrap-vue.org/docs/components/tabs) to be restyled

## Community
- [ ] Created [design review story](https://github.com/openbmc/webui-vue/issues/27) in webui-vue repo

- [ ] Sent email to community sharing the design review story

**Comment by ben-bacon** [comment]
Low-fidelity user testing flow: 
- [Deconfiguration Records](https://ibm.invisionapp.com/share/5CO08UVAJDG)
- [Hardware Configuration Overview](https://ibm.invisionapp.com/share/GSO09BRX53E)
- [Hardware Configuration Details](https://ibm.invisionapp.com/share/KCO09BS4Q87)

**Comment by ben-bacon** [comment]
Ready for handoff, @nicoleconser and I will provide an additional doc with the content for tool-tips at a later date.
