### ISSUE TITLE
PLDM: FRU Table: add Manufacturer date

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2395]
If https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Inventory/Decorator/Asset.interface.yaml#L16 is found in the BMC FRU inventory, map that to the "Manufacture Date" property from the FRU spec and add to the FRU table.

The "Manufacture Date"'s type is `Timestamp104`, so need to support this type libpldm/pldm_types.h, and also need to handle the conversion from the D-Bus type to this PLDM type.

**Comment by nmuruli** [comment]
There is no requirement to have FRU MNFG date as part of FRU table as for now even for P11
