### ISSUE TITLE
GUI : FED : Update Interface colors 

### ISSUE THREAD

**Issue by ben-bacon** [ibm-openbmc/dev#2396]
## Overview
We need to update some components that were affected by the color changes in  #2330. 

The following components need to be updated from `Gray200` to `Gray100`
- [x] Sidebar background
![image](https://user-images.githubusercontent.com/52676199/87583405-831d6f00-c6a1-11ea-9d3f-3ba19c00f228.png)
- [x] Overview Action Bar
![image](https://user-images.githubusercontent.com/52676199/87583427-8a447d00-c6a1-11ea-94c2-4029e7d77ca5.png)
- [x] LDAP Settings box
![image](https://user-images.githubusercontent.com/52676199/87583446-93354e80-c6a1-11ea-935a-453ea3d8f6ec.png)
- [x] Server power operations > Host OS Boot settings
![image](https://user-images.githubusercontent.com/52676199/87583372-74cf5300-c6a1-11ea-9893-4ee30ead666e.png)

**Comment by dixsie** [comment]
resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34932
