### ISSUE TITLE
GUI : Research : Previous Boot Progress Indicator & Progress Indicator History LOGS

### ISSUE THREAD

**Issue by nicoleconser** [ibm-openbmc/dev#2397]
## SME
**BMC**:
**RAS**:
**PHYP**:

### Background
- Even though these are separate menu items in ASMI, they are covered by one Redfish LogService. See [7/15 Slack convo](https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1594764817141200) with Gunnar. 

### End users
- [ ]  TBD

### User Needs
- [ ] TBD

### User Quotes
- [ ] TBD

## User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

## References
- [ ] eBMC Feature Item <add number>
- [ ] Link to Discovery folder

**Comment by derick-montague** [comment]
Closing -> Migrating to one System Logs research story #2626
