### ISSUE TITLE
GUI : Design : FED : Table styles for small screen stacked

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2399]
Make any necessary visual style adjustment to the stacked table layout. The stacked layout can be found on the Overview page and Local users management role tables on a small viewport.

![Screen Shot 2020-07-16 at 9.41.24 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/def711fd-ff5e-471c-b0bf-0dc9db191de4)
![Screen Shot 2020-07-16 at 10.11.53 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/bb992270-62a4-46d6-baab-9c5e609961c7)

**Comment by ben-bacon** [comment]
Got some early feedback from @yoshiemuranaka and @dixsie on [this direction](https://ibm.invisionapp.com/share/U9O039T4Q6E#/319695486_Preview_-_Mobile). I think we're good to go here. let me know if something isnt clear.

Note: the stacked tables **does** have zebra striping for the rows (the normal, default table **does not** have zebra striping)

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36798
