### ISSUE TITLE
Redfish(LDAP):  Map the sdbus error to Redfish and Secure LDAP Testing

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#240]
It may happen that we don't need to implement anything here but to track the following items

-> Do we need some thing extra for maping the sdbuserror to redfish error messages.
-> Once certificacte upload/install starts working then need to test the secure LDAP.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
This is a low priority as this is not related to LDAP, this is the common infrastructure which is missing in the bmcweb.

**Comment by sunharis** [comment]
Uncommitted work item. Needs to be resolved in upstream
