### ISSUE TITLE
GUI : FED : Remove text-transform from OverviewNetwork style block

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2401]
## Overview
The following ruleset is used in the OverviewNetwork SFC style block. For internationalization, we cannot use the text-transform property to upper case text. If and when he design calls for specific casing, it is important to add the text in to the i18n file in the proper case.

```
.interface-name {
  text-transform: capitalize;
}
```

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
- [MDN Localization Best Practices](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Create_localizable_UI)

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by dixsie** [comment]
The transform was to transform what it being returned by the backend

**Comment by SurenNeware** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35167

**Comment by derick-montague** [comment]
I left a comment about discussing changes you made to layout. I am not sure this spacing is what we want. 

![image](https://user-images.githubusercontent.com/1183515/88815640-2d58c480-d181-11ea-9ab7-25d1a035b481.png)

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35167 merged
