### ISSUE TITLE
ocmb target support in system device tree for ocmb scom

### ISSUE THREAD

**Issue by RameshIyyar** [ibm-openbmc/dev#2402]
- Change index  property value for ocmb target based on parent omi target CHIP_UNIT attribute value.
- Update ocmb target node name as `ocmbX` (X - instance id) 
- Add required compatible property `"ibm,power-ocmb"` to ocmb for scom operation

**Comment by RameshIyyar** [comment]
- **Updated index property value for OCMB target**
OCMB target index property value should be local scope within proc target for scom operation but ocmb target is not pervasive targets and it does not have CHIP_UNIT attribute so, using OMI target CHIP_UNIT attribute value as index property value for  ocmb target.

- **Changed ocmb target node name**
Currently, all targets node name are picked from PHYS_PATH value i.e considered least target path element from PHYS_PATH attibute value. For example to proc target, If value is "physical:sys-0/node-0/proc-0" then "proc-0" picked and removed "-" from that element value. Similarly, ocmb target name will be "ocmb_chip0" but, pdbg expecting as "ocmb0" i.e without "_chip" to make generic for scom operation so, changed ocmb target node name as per pdbg expectation.

- **Updated ocmb compatible property**
The pdbg expecting ocmb target compatible property value as "ibm,power-ocmb" for scom operation so, added same value into ocmb compatible property list i.e it will support both "ibm,power-ocmb" and "ibm,power10-ocmb" values.

**Comment by ojayanth** [comment]
@RameshIyyar please include PR information.

**Comment by RameshIyyar** [comment]
Above story addressed and merged into phal/pdata
Ref: https://github.ibm.com/phal/pdata/pull/25
