### ISSUE TITLE
GUI : FED : Change password - first time login

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2404]
## Overview
Refactor the current change password flow on first login. When backend code merged, the login request should return the `PasswordChangeRequired` property as part of the response.
- Remove action from Authentication store
https://github.com/openbmc/webui-vue/blob/master/src/store/modules/Authentication/AuthenticanStore.js#L47-L52
- Refactor Login component to use returned property
https://github.com/openbmc/webui-vue/blob/master/src/views/Login/Login.vue#L126-L129

## Notes
- **Blocked by:** https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/39756.
- Original change password story #1648

**Comment by derick-montague** [comment]
Blocked by a Gerrit commit noted in the `notes` section in the description.

**Comment by derick-montague** [comment]
@geissonator - do we know when we might merge https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/33990?

**Comment by gtmills** [comment]
Right now we have to make an extra call to determine if a password change is required

We login, then call https://github.com/openbmc/webui-vue/blob/master/src/store/modules/Authentication/AuthenticanStore.js#L57
This would allow us to get that all in 1 call

**Comment by derick-montague** [comment]
Gerrit review was abandoned due to being stale. We need this work to fulfill this requirement unless it's determined that it is not needed.

**Comment by derick-montague** [comment]
@joseph-reynolds will be pushing up a new Gerrit commit that this story will be dependent on.

**Comment by joseph-reynolds** [comment]
Gerrit commit https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/33990 should remain abandoned, but I still want this function.  I'll push a new review based on the restructured code in https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/39756.

**Comment by derick-montague** [comment]
Verified today the story is still blocked.

**Comment by gtmills** [comment]
@joseph-reynolds Can we move this to the 1.888 milestone?

**Comment by sandeepasingh116** [comment]
@gtmills , should  we migrate it ?

**Comment by rfrandse** [comment]
tracking in jira
