### ISSUE TITLE
GUI : FED : Update style of modal title 

### ISSUE THREAD

**Issue by ben-bacon** [ibm-openbmc/dev#2409]
## Overview
- Modals now should be using the h4 style for headings

Now:
https://files.slack.com/files-pri/T27SFGS2W-F01828TN457/screen_shot_2020-07-24_at_10.06.15_am.png
<img width="536" alt="Screen Shot 2020-07-24 at 10 06 15 AM" src="https://user-images.githubusercontent.com/8097306/88548190-98fd2f00-cfd3-11ea-9863-bedf351c9a47.png">

Proposed:
https://ibm.invisionapp.com/d/main#/console/15362203/319639453/inspect
<img width="862" alt="Screen Shot 2020-08-07 at 10 23 12 AM" src="https://user-images.githubusercontent.com/8097306/89671551-080e3980-d898-11ea-9d10-a8712696ce6d.png">

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36314
