### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#241]
This tracks the capability for a user to backup an OpenBMC config (settings, certificates, network, machine-id(?), ...) and then apply it to a new system.

Hopefully, Redfish provides the API's required to do this function.

**Comment by gtmills** [comment]
@geissonator Does this include the GUI functionality to do this as well? I assume doing this from the GUI is a major use case.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Now that we have a more accurate date for the next GA, I'd like us to work towards pulling this into that delivery. Marking the Milestone as 9.3.1

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
The DMTF group has approved the need for a Backup and Restore functionality in Redfish, and have defined the requirements for how the new schema should work. They are looking for a volunteer to submit a proposed schema, and once approved it can be implemented in OpenBMC.

This epic will track the work from submission of the schema proposal to the DMTF group to implementation in OpenBMC. IBM would like to be involved in the review of the schema. To submit the schema proposal, first join the DMTF https://www.dmtf.org/join , join a workgroup:

```- https://members.dmtf.org/apps/org/workgroup/portal/
- Menu > Group > All Groups -- Select "Redfish Forum"
- When the group info comes up, click on the "join group" link and complete the application.```

and get access to github.com/DMTF/Redfish:
```
- I sent an email like: Please authorize my github.com userid  <id>  to https://github.com/DMTF/Redfish..```

The link to the redfish issue is listed in https://github.com/ibm-openbmc/dev/issues/501

**Comment by rfrandse** [comment]
refresh

**Comment by mine260309** [comment]
@anoo1 The redfish issue https://github.com/DMTF/Redfish/issues/3430 is still open.
What is the status of the proposal?

And in the proposal, it looks like it only suppors two type of backups:

```
/redfish/v1/Managers/bmc/EthernetInterfaces/
/redfish/v1/Managers/1/NetworkProtocol/HTTPS/Certificates
```

How about other information, like settings, machine-id, etc?

**Comment by anoo1** [comment]
DMTF is asking for a volunteer to propose the schema. Their guideline is to support a blob instead of specific interfaces, and have the implementation decide the format and handling of the blob. At IBM we'll probably get to propose the schema in a couple months.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Removing @anoo1 as the owner.  Would like IPS to define and drive development.  Adriana is available for consulting.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
