### ISSUE TITLE
GUI : FED : Style Guide - Form validation error icon

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#2410]
## Overview
Make updates to form fields to reflect changes in new style guide. Make updates and validate:
- [ ] Field error state

## Final Invision Mockup
https://ibm.invisionapp.com/share/37O0A2VZCYF#/screens

## Notes
- [ ] New form field error state has an error icon in the field

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

![Screen Shot 2020-07-27 at 8.36.58 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/9f06567d-f54c-447a-9eff-8f960db01deb)

**Comment by dixsie** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35118

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35118 merged
