### ISSUE TITLE
eBMC LED Management :: Populate Redfish:: "HealthRollUp" property based on fault_led association being present

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2411]
Initially, redfish had Indicator LED property with enum Attention/Identify/Off. However, going forward, that would not be the case. The idea is to use "HealthRollUp" property of a FRU to indicate a fault on thh FRU.

What is needed: 

when a client wants to read HealthRollUp, bmcweb will check if there is any association to led object for that FRU and if so, it reads the asserted state of the group and then populates the Rollup property

For example: each FRU instance will have "fault_led" and "identify_led".   

Sequence of events:
1/. User reads HealthRollUp of a resource

2/. bmcweb checks if there is  any led association object created for that Inventory
Example:
- busctl get-property xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/inventory/system/chassis/motherboard/dimm10/fault_led xyz.openbmc_project.Association endpoints

Example output: "/xyz/openbmc_project/led/groups/dimm10_fault"

3/. If there is an association existing, then read the "asserted" state.

- busctl get-property xyz.openbmc_project.LED.GroupManager /xyz/openbmc_project/led/groups/dimm10_fault xyz.openbmc_project.Led.Group Asserted

4/. Use the result from above step ^ and then set "HealthRollup" is "Critical" if it's "true"

**Comment by lxwinspur** [comment]
changed `fault_led` to `fault_led_group`
changed `identify_led` to `identify_led_group`

**Comment by lxwinspur** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/35541

**Comment by vishwabmc** [comment]
After discussing this with Ed 'et al, I believe the better solution is not to derive health-rollup from the state of Fault_Led. 

Instead, do 2 things as part of setting the fault LED.

- Set the LED
- Set the D-Bus property which is currently used by bmcweb to represent HealthRollup.

Using this approach :

- No changes to bmcweb
- We need to add some code in bmc to do 2 things mentioned above

**Comment by vishwabmc** [comment]
Closing this...

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
For HealthRollup: 
Logging is creating the associations for us here: 
https://github.com/openbmc/phosphor-logging/blob/76198a2ea2e3deb14078e0d3dd3932b657ddd9b8/extensions/openpower-pels/service_indicators.cpp#L83

The only healthrollup we really care about is Chassis, at least for now. 
@santoshpuranik's app will implement the item.global interface. 

For Health: 
We need all resources to use OperationalStatus. Need to modify https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/health.hpp#L44 (either removing Health from it or have it set the health) 

Any changes for this can be downstream only.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
