### ISSUE TITLE
GUI : FED : Design : Update style for FormFile Component

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2412]
## User Story
The [FormFile Component](https://bootstrap-vue.org/docs/components/form-file) styled variant (not simple mode) is currently being used in the code without any style overrides. Revisit the UI styling to match our style guide.

## Use Case(s)
- [ ] Currently being used on Access > SSL Certificates
- [ ] Will eventually be used on Firmware page also

## Design Goals
- [ ] Goal 1
- [ ] Goal 2
- [ ] Goal 3

## InVision Prototype
- [ ] Iteration 0

## Screenshots

Currently in code:
![Screen Shot 2020-07-23 at 8.27.34 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/fb401bdb-8f6b-4941-931a-5d90674d4543)

**Comment by yoshiemuranaka** [comment]
<img width="407" alt="Screen Shot 2020-07-31 at 8 46 41 AM" src="https://user-images.githubusercontent.com/8097306/89052403-8142e500-d30a-11ea-9893-2d31a9ed7ba1.png">

should also consider long file names

**Comment by ben-bacon** [comment]
![image](https://user-images.githubusercontent.com/52676199/89355128-3adde500-d680-11ea-9a76-375ca048ebae.png)
Current thinking for this component, will gather feedback and revise.

**Comment by yoshiemuranaka** [comment]
Do we need to create a separate FED story for this @derick-montague ? or can we just add FED label and move back to Sprint+1

**Comment by derick-montague** [comment]
I'm good with updating to FED and moving to Sprint +1 if you are.

**Comment by derick-montague** [comment]
Adding this to the next community design work group to validate before moving forward. Next work group is 9/02/20.

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36207

**Comment by ben-bacon** [comment]
updated guidance as discussed from casual playback 9/3/20
https://ibm.invisionapp.com/share/U9O039T4Q6E#/319695050_File_Uploader
