### ISSUE TITLE
GUI : FED : Date time settings - UTC bug

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2414]
## Overview
When the date time offset preference is set to UTC and manually changing the current time on date time settings, the manually entered date is saved as the local time.
If the preference is UTC, the manually entered date is assumed to be in UTC as well. 

## Steps to recreate
- Navigate to /profile-settings
- Change time display preference to UTC
- Navigate to Date and time settings page
- Set manual date/time value
- The entered value is saved on the backend as the local offset time and displays incorrectly after save settings clicked

**Comment by Srisuk** [comment]
Resolved By: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35216
