### ISSUE TITLE
GUI : FED : Event logs - date filtering bug

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2415]
## Overview
Date filtering on the event logs page is sometimes inaccurate depending on the user timezone offset display preference. 
The date filtering should check the user preference when filtering logs so the table data accurately reflects the log timestamp and date filters

**Comment by Srisuk** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35332

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35332 merged
