### ISSUE TITLE
dynamic device tree: userspace: set u-boot env variable to correct dts

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2417]
userspace code will look at VPD to determine correct system type, it will then set a u-boot env variable to tell u-boot which dts the kernel should load. It will then reboot the BMC to get the dts loaded.

This service should only run once. It will key off of whether the u-boot env variable is set to determine if it should run or not.

**Comment by bradbishop** [comment]
I'm pretty sure this is a dup of 2556.

**Comment by bradbishop** [comment]
> I'm pretty sure this is a dup of 2556.

Confirmed with @santoshpuranik ...closing.
