### ISSUE TITLE
dynamic device tree: build: package in all possible device trees to bmc image

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2418]
Some work will be needed on the build side to be able to package in all of the different device trees a BMC image may support. This story tracks that work.

**Comment by bradbishop** [comment]
Other work is required but there is a PR here that has been open for a bit that gets us part of the way there.

https://github.ibm.com/openbmc/linux/pull/64

**Comment by bradbishop** [comment]
Hi @eddiejames What are we stuck on here?

**Comment by eddiejames** [comment]
https://github.ibm.com/openbmc/openbmc/pull/693
