### ISSUE TITLE
GUI : FED : SOL Formatting updates

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2419]
## Overview
It was determined at the OpenBMC GUI Design workgroup that the different consoles need to be consistent. This story will be completed using the [OpenBMC webui-vue repo ](https://github.com/openbmc/webui-vue)in story `#25` - Serial Over LAN layout.

## UX Flow / Interaction Requirements
All instructions noted in story noted in overview section.

## Final Invision Mockup
Review in story noted in overview section .

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35774

**Comment by derick-montague** [comment]
I am ok with the open new window screen. If the only way to format the terminal after resizing is a refresh. I do want to figure out a way to resolve this issue though.

![image](https://user-images.githubusercontent.com/1183515/91613454-2ae6b780-e945-11ea-8bf1-e0d6e748bd08.png)
