### ISSUE TITLE
GUI : FED : Update Date and Time Settings Layout to include UTC / Offset label

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2420]
## Overview
The current date and time layout does not allow the user to easily understand the expectation for entering time.

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/99f192a1-88d1-4d7d-a011-a5f09be40460)

### Current Implementation
![image](https://user-images.githubusercontent.com/1183515/88694705-7f88df80-d0c6-11ea-9a38-a96f990b415c.png)

## cURL Commands
N/A

## Notes
- [ ] Use the date time setting state to determine the label for UTC or Offset

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by ben-bacon** [comment]
I think these are good updates

**Comment by ParishrutB** [comment]
+ 1. Good updates.

I may be nitpicking but, to maintain consistency - the '24 Hour time' label should be same for both the instances? Which would mean that for the second instance, 'UTC' could be part of the field itself? One reference would be LDAP page > Server URI field > 'https://' (could not find a screenshot for this).

Additionally, I think it should be '24-hour time' - the 'h' should not be capitalized and there needs to be a hyphen.


<img width="671" alt="image" src="https://user-images.githubusercontent.com/61419136/88816214-cb787900-d1d9-11ea-9d94-684b9564f9b3.png">

**Comment by ParishrutB** [comment]
Reference for date and time format (capitalization of format and use of '/' in date format):

![image](https://user-images.githubusercontent.com/61419136/88817621-602fa680-d1db-11ea-86f2-424ba275da90.png)

**Comment by derick-montague** [comment]
> Reference for date format (capitalization & use of '/' instead of '-')

We are using the iso date format standard. 
https://www.iso.org/iso-8601-date-and-time-format.html

**Comment by derick-montague** [comment]
> Which would mean that for the second instance, 'UTC' could be part of the field itself? One reference would be LDAP page > Server URI field > 'https://' (could not find a screenshot for this).

We did discuss adding in the field as the initial design suggested, but there were some work-arounds needed to support validation icons.

We could, does this make sense in this context? For LDAP, the context is slightly different. 

![image](https://user-images.githubusercontent.com/1183515/88850398-f0a4c180-d1b0-11ea-8295-dfbd333acef5.png)

**Comment by derick-montague** [comment]
> Additionally, I think it should be '24-hour time' - the 'h' should not be capitalized and there needs to be a hyphen.
+1

**Comment by dixsie** [comment]
resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35182

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35182 merged
