### ISSUE TITLE
GUI : Memory Resource Mgmt - Memory - I/O Adapter Enlarged Capacity

### ISSUE THREAD

**Issue by nicoleconser** [ibm-openbmc/dev#2421]
## SME
**BMC**: Nick Bofferding, Chen Du
**RAS**: tbd
**PHYP**: tbd

### Summary
There are two other features that are part of the Resource management/Memory page
-  #1501 
- #3304 

#### Background
[Determination as BIOS setting and milestone]( https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1596667342414300)
- @nicoleconser, @dkodihal, and Nick Bofferding

**From Pete Heyrman & Travis Pizel (PHYP) on [Slack, 7/28](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1595954021097800):** 
- Allows users to set aside memory for better throughput/performance when running Linux 
- Allows customers to indicate how many PCI ports will have adapters that fully map the I/O space (Linux). 
- This is still needed. The amount of memory consumed is still very large on big multi-node systems - and that space is only utilized by Linux. 
- This setting might only go into effect at IPL (need to confirm) 

## ASMI Screen Capture
![image](https://user-images.githubusercontent.com/1183515/114253725-ec03f000-9970-11eb-931a-dd4b63da72a7.png)

### References
- [Discovery folder URL](https://ibm.ent.box.com/notes/823143247894)
- BIOS Attribute name: `hb_ioadapter_enlarged_capacity`

### InVision Prototype
- Final mockup: https://ibm.invisionapp.com/share/PYO1HKPE25X

### Community
- Downstream only

### UX Flow / Interaction Requirements
- [ ] Feature breakdown

### cURL Commands and Redfish Response
- [ ] `https://{$bmc}/redfish/v1/Registries/BiosAttributeRegitry/BiosAttributeRegistry`
- [ ] Add cURL commands
- [Spec](https://ibm.ent.box.com/file/478139954961?s=w7lzdwgawwnt9saob8zs05bs6n6o7tg4)

```
      {
         "attribute_name" : "hb_ioadapter_enlarged_capacity",
         "lower_bound" : 0,
         "upper_bound" : 255,
         "scalar_increment" : 1,
         "default_value" : 0,
         "helpText" : "Specifies the enlarged IO capacity, requires a reboot for a change to be applied.",
         "displayName" : "Enlarged IO Capacity (pending)"
      },
      {
         "attribute_name" : "hb_ioadapter_enlarged_capacity_current",
         "lower_bound" : 0,
         "upper_bound" : 255,
         "scalar_increment" : 1,
         "default_value" : 0,
         "readOnly" : true,
         "helpText" : "Specifies the enlarged IO capacity for the current IPL. Do not set this attribute directly; set hb_ioadapter_enlarged_capacity instead.",
         "displayName" : "Enlarged IO Capacity (current)"
      }

```

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by nicoleconser** [comment]
@mzipse FYI we are unsure of any back-end dependencies for this. Also unsure who the SMEs are.

**Comment by nicoleconser** [comment]
> @mzipse FYI we are unsure of any back-end dependencies for this. Also unsure who the SMEs are.

Travis Pizel suggested that Deepak Kodihal or Nick Boff. might be able to provide guidance on back-end availability.

**Comment by nicoleconser** [comment]
per 8/7 sync-up, research can begin in 3rd quarter 2020

**Comment by derick-montague** [comment]
@priyanka-pillai97 Is this a story we need to work on or is this part of #1501

**Comment by derick-montague** [comment]
Tom Sand suggested this is needed in the GUI and only used for Linux based systems.

**Comment by derick-montague** [comment]
Need to determine what backend work is related to this story and if it is complete.

**Comment by derick-montague** [comment]
This specific BIOS setting is most likely part of the A.1.211 milestone.

**Comment by ParishrutB** [comment]
In discussion: Whether desired state is saved somewhere before an IPL
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1622791063425700

**Comment by derick-montague** [comment]
Waiting on work from Nick B for Hostboot in order to move forward.

**Comment by derick-montague** [comment]
This has been added as part of the design of Memory management and the mock is linked in #1501

**Comment by dixsie** [comment]
@sandeepasingh116 The endpoint will be the same as Logical Memory block size

**Comment by dixsie** [comment]
FYI @sandeepasingh116 the bios attribute needed is in review https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/47810

**Comment by dixsie** [comment]
@sandeepasingh116 the property you were looking for should be in the 32.1 driver.

**Comment by sandeepasingh116** [comment]
Resolved by https://github.ibm.com/openbmc/webui-vue/pull/21

**Comment by mzipse** [comment]
Closing.  Work is complete.
