### ISSUE TITLE
GUI : FED : Date Time Settings - Populate manual time fields on load

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2422]
## Overview
When the Date and Time settings page loads, the date and time input fields do not contain a value. Regardless of whether setting is NTP or Manual, these field should be set based on the current system time. It should also take into account the if the date and time preference is set to UTC or the offset.

## UX Flow / Interaction Requirements
- User visits the date and time page
- The date and time values are updated to represent the current system time

## cURL Commands
- [ ] Add cURL commands

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36049
