### ISSUE TITLE
GUI : FED : Firmware Update - Host / BMC - Separate Upload

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2426]
## Overview
Older systems will still support the two file upload. This work would add a page for updating the BMC and Host Firmware separate to support lab testing of Witherspoon systems.

## UX Flow / Interaction Requirements
See the story in the [webui-vue repo](https://github.com/openbmc/webui-vue), issue `#9`

## Final Invision Mockup
https://ibm.invisionapp.com/share/NTO0AWJW5BV

## cURL Commands
- [ ] Add cURL commands

## Notes
- This is not intended to be ported to a production server at any time in the future.

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by derick-montague** [comment]
@gtmills Can you add the blocking backend story to this?

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/dev/issues/2485 is the backend

**Comment by yoshiemuranaka** [comment]
FYI @gtmills if we don't want to wait for a full design cycle to complete before pushing a version of two file upload, this is the proposed direction. Will check in with fw design progress in current sprint then decide whether to wait for a more polished design to be handed off before implementing in code

<img width="1783" alt="Screen Shot 2020-09-02 at 11 57 27 AM" src="https://user-images.githubusercontent.com/8097306/92025423-59351000-ed14-11ea-8da5-32879982b91b.png">
<img width="1783" alt="Screen Shot 2020-09-02 at 12 00 56 PM" src="https://user-images.githubusercontent.com/8097306/92025445-60f4b480-ed14-11ea-875d-61ba05bba8f9.png">

**Comment by yoshiemuranaka** [comment]
Chatted today with @ParishrutB @derick-montague - we will move forward with this proposed 'temporary' design. @ParishrutB will continue design and research work, keeping the two file upload layout in mind

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37147
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37148

**Comment by derick-montague** [comment]
This isn't fully functional due to some backend dependencies, correct? Do we have a story to change that or are we waiting for the FW redesign?

**Comment by yoshiemuranaka** [comment]
@gtmills can probably clarify, but everything on the backend is available for the two file upload. We lose the ability to reboot from backup for the host firmware, but were ok moving forward without it

**Comment by derick-montague** [comment]
>  everything on the backend is available for the two file upload
Great...Thank you! Just didn't want to miss capturing any future updates needed.
