### ISSUE TITLE
Everest PSU energyscale support

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2431]
Update which (if any) N_MODE_VREF gpio needed for oversubscription in entity manager config file. 

Ensure interface to HTMGT/OCC to determine power cap based on power supplies - based on type of power supplies, number present, and input type - is working as appropriate.  Later GA.

Verify Redfish support - store needed things in DBUS. bmcweb gets from DBUS for redfish, json file with associations in object mapper needs to be updated.

Power supply & system power sensor telemetry data for external collection. We will need to store the telemetry data in DBUS. Verify from there they can get pulled out via Redfish telemetry service (will be HMC pulling the data on customer systems).

OCC power sensors list in #2150 (comment).

Read trending data along with all other EnergyScale data. Buffered Input power 30s rolling average required? In Redfish? yes

Assume we can read input history from psu's. At some later point, if some psu don't support it, it can be made configurable.

Need information sent in FSP get_pex_ps_element_info direct cmd in some format.

POR is to use what Intel has merged already for telemetry, and do updates to that if needed.  This is being done in different github issues.

Need phosphor-hwmon configs for the PS sensors.

Properties wanted from power team are:
PS Input power 30s rolling max&ave for EnergyStar.
System power every 5 second reading (from OCC).
APSS channels power every 5 second reading (from OCC).
Processor power min/max/ave every hour is extra credit (will be in OCC PEL).

For this issue, should be suffice to collect/append once-per-5s readings for 1 hour for every of these sensors in one of the everest systems when powered on.

**Comment by bjwyman** [comment]
- [x] Update which (if any) N_MODE_VREF gpio needed for oversubscription in entity manager config file.
    - https://github.com/ibm-openbmc/entity-manager/pull/12
    - Upstream review: ???
...

**Comment by derekhoward55** [comment]
Results look good, with exception of timestamps.  Fix for this is in https://github.com/ibm-openbmc/bmcweb/pull/412, coming in first service pack.

> {
"@odata.id": ["/redfish/v1/TelemetryService/MetricReports//Power5s_metrics2"](https://ever8bmc.aus.stglabs.ibm.com/redfish/v1/TelemetryService/MetricReports//Power5s_metrics2),
"@odata.type": "#MetricReport.v1_3_0.MetricReport",
"Id": "Power5s_metrics2",
"MetricReportDefinition": {
"@odata.id": ["/redfish/v1/TelemetryService/MetricReportDefinitions//Power5s_metrics2"](https://ever8bmc.aus.stglabs.ibm.com/redfish/v1/TelemetryService/MetricReportDefinitions//Power5s_metrics2)
},
"MetricValues": [
{
"MetricId": "TotalPower_5s",
"MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/total_power/Reading",
"MetricValue": "1478.000000",
"Timestamp": "1979-11-13T04:16:37+00:00"
},
{
"MetricId": "MaxTotalPower_5s",
"MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/total_power/Reading",
"MetricValue": "1478.000000",
"Timestamp": "1979-11-13T04:16:37+00:00"
},




> {
"@odata.id": ["/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply0/Metrics"](https://ever8bmc.aus.stglabs.ibm.com/redfish/v1/Chassis/chassis/PowerSubsystem/PowerSupplies/powersupply0/Metrics),
"@odata.type": "#PowerSupplyMetrics.v1_0_0.PowerSupplyMetrics",
"Id": "Metrics",
"Name": "Metrics for powersupply0",
"Oem": {
"@odata.type": "#OemPowerSupplyMetrics.Oem",
"IBM": {
"@odata.type": "#OemPowerSupplyMetrics.IBM",
"InputPowerHistoryItems": [
{
"Average": 417,
"Date": "2022-07-18T18:31:46+00:00",
"Maximum": 417
},
{
"Average": 417,
"Date": "2022-07-18T18:31:16+00:00",
"Maximum": 417
},
