### ISSUE TITLE
Everest VRM Control & Monitoring - FF

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2432]
Set PMBus or non-PMBus register values to configure VRM as needed, defined in config file.

IO expanders or other devices used for phase fault detection.  Use json config file design, unbind DD.

Collect telemetry data.  Have already unbound DD to vrms, don't collect telemetry in mfg mode.

No requirement to detect redundant enable faults for Everest.

No vrm gard supported - sized elsewhere.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
