### ISSUE TITLE
phosphor-regulators: Create config file(s) for Everest

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2435]
Work with the hardware team to create the config file(s) needed for Everest systems.

Copy file(s) (if necessary) into appropriate OpenBMC repository.

Ensure name correctly located in DBUS and file read at runtime.

**Comment by smccarney** [comment]
I had previously created a mostly empty JSON config file for Everest.  It contained only the information needed to allow for a boot to succeed.  It did not define or configure regulator devices.

I confirmed that the mostly empty file was found by the regulators application and loaded successfully.  I also verified the system booted without regulator errors.

Recently Mark DeMarie created a new version of the JSON configuration file that contains the following enhancements:
* Defines all the regulator devices
* Configures all the regulator devices that need it
* Detects presence of devices that are not present in all system configurations

I reviewed and tested this file, and it looks good to me.  It has been merged into the necessary repositories.

The following major enhancements are still needed to this file:
* Sensor monitoring
* Phase fault detection

However, Derek Howard wanted those enhancements to be tracked under different issues.
