### ISSUE TITLE
Networking: ipv6 address validation

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#244]
<a href="https://github.com/eddiejames"><img src="https://avatars1.githubusercontent.com/u/14914763?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eddiejames](https://github.com/eddiejames)**
_Tuesday Aug 02, 2016 at 14:56 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/496_

----

Not sure what the requirements are for ipv6 addresses

**Comment by rfrandse** [comment]
<a href="https://github.com/vishwabmc"><img src="https://avatars1.githubusercontent.com/u/13940109?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vishwabmc](https://github.com/vishwabmc)**
_Tuesday Aug 02, 2016 at 15:58 GMT_

----

@eddiejames Just chatting with @williamspatrick about it now.. We  need to support IPV6.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
I am closing it as it is already there.
