### ISSUE TITLE
Verify Everest frame/fru vpd pldm collection.

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2441]
Ensure enclosure UTMS returned in GetFRURecordTable PLDM cmd.  Use pldmtool fru GetFRURecordTable.

Ensure actual FRU vpd and frame vpd (in PLDM format) with GetFRURecordTable pldm/pdr.
Ensure fan FRU vpd and phyp indication via pldm sent after hot fan remove and install (using pldmtool, busctl, and journalctl).

Ensure alerts/epows (eg high ambient temp epow3/4) supported.

**Comment by derekhoward55** [comment]
Here is the enclosure UTMS (which matches the system workbook):

        {
            "FRU Record Set Identifier": 1,
            "FRU Record Type": "General(1)",
            "Number of FRU fields": 3,
            "Encoding Type for FRU fields": "ASCII(1)"
        },
        {
            "FRU Field Type": "Model(2)",
            "FRU Field Length": 8,
            "FRU Field Value": "9040-MRX"
        },
        {
            "FRU Field Type": "Serial Number(4)",
            "FRU Field Length": 7,
            "FRU Field Value": "13E8E1X"
        },
        {
            "FRU Field Type": "Version(10)",
            "FRU Field Length": 47,
            "FRU Field Value": "fw1020.00-39.5-1020.2206.20220207a (NM1020_016)"
        }

**Comment by derekhoward55** [comment]
Here is the frame vpd:

    [
        {
            "FRU Record Set Identifier": 3,
            "FRU Record Type": "OEM(254)",
            "Number of FRU fields": 15,
            "Encoding Type for FRU fields": "ASCII(1)"
        },
        {
            "FRU Field Type": "RT(2)",
            "FRU Field Length": 4,
            "FRU Field Value": "VSYS"
        },
        ...
        {
            "FRU Field Type": "SE(11)",
            "FRU Field Length": 7,
            "FRU Field Value": "0x31 0x33 0x45 0x38 0x45 0x31 0x58 "
        },
        {
            "FRU Field Type": "SG(12)",
            "FRU Field Length": 7,
            "FRU Field Value": "0x20 0x20 0x20 0x20 0x20 0x20 0x20 "
        },
        {
            "FRU Field Type": "SU(13)",
            "FRU Field Length": 6,
            "FRU Field Value": "0x00 0x4a 0xc1 0xe9 0x3e 0x03 "
        },
        {
            "FRU Field Type": "TM(14)",
            "FRU Field Length": 8,
            "FRU Field Value": "0x39 0x30 0x34 0x30 0x2d 0x4d 0x52 0x58 "
        },

**Comment by bentyner** [comment]
Testing result of fan present true/false using busctl tool shows consistent but unexpected behavior.
state: fan0, fan1, fan2, fan3 present <-- busctl get property xyz.openbmc_project.Inventory.Item Present
status: pldmtool fru GetFruRecordTable | grep fan:
"FRU Field Value": "fan0"
"FRU Field Value": "fan1"
"FRU Field Value": "fan2"
"FRU Field Value": "fan3"
test: fan0 set not-present <-- busctl set property xyz.openbmc_project.Inventory.Item Present b false
status: pldmtool fru GetFruRecordTable | grep fan:
"FRU Field Value": "fan0"
"FRU Field Value": "fan1"
"FRU Field Value": "fan2"
"FRU Field Value": "fan3"
test: fan0 set present <-- busctl set property xyz.openbmc_project.Inventory.Item Present b true
status: pldmtool fru GetFruRecordTable | grep fan:
"FRU Field Value": "fan0"
"FRU Field Value": "fan1"
"FRU Field Value": "fan2"
"FRU Field Value": "fan3"
"FRU Field Value": "fan0" <-- unexpected additional entry
test: fan0 set present false, set present true <--- busctl set property xyz.openbmc_project.Inventory.Item Present 
status: pldmtool fru GetFruRecordTable | grep fan:
pldmtool: ../git/pldmtool/pldm_fru_cmd.cpp:290: static std::string pldmtool::fru::FRUTablePrint::fruFieldParserU32(const uint8_t*, uint8_t): Assertion `length == 4' failed. Aborted (core dumped)
final state: pldmtool fru GetFruRecordTable core dumps after any further attempt(s) to retrieve the fru record table

**Comment by bentyner** [comment]
systemctl stop pldmd followed by systemctl start pldmd allows pldmtool fru GetFruRecordTable to function again
The unexpected additional fan0 entry and pldmtool core dump behavior can be repeated.

**Comment by bentyner** [comment]
test: pldmtool fru GetFruRecordTable | grep 904
result: "FRU Field Value": "9040-MRX"
expected: 9043-MRX <-- Everest P10 System Workbook, Version 1.3, Date: Jan 25, 2022
SUT os-release detail: VERSION_ID=fw1020.00-41.3

**Comment by bentyner** [comment]
Ensure alerts/epows (eg high ambient temp epow3/4) supported
---
Mar 04 19:05:09 p10bmc sensor-monitor[526]: Starting 900000ms SoftShutdownAlarmHigh shutdown timer due to sensor /xyz/openbmc_project/sensors/temperature/Ambient_Virtual_Temp value 81
...
Mar 04 19:05:09 p10bmc sensor-monitor[526]: Starting 23000ms HardShutdownAlarmHigh shutdown timer due to sensor /xyz/openbmc_project/sensors/temperature/Ambient_Virtual_Temp value 81
...
{                                                                               
    "0x50000088": {                                                             
        "SRC":                  "BD602803",                                     
        "Message":              "A temperature sensor exceeded its warning threshold.",
        "PLID":                 "0x50000088",                                   
        "CreatorID":            "BMC",                                          
        "Subsystem":            "Power/Cooling",                                
        "Commit Time":          "03/04/2022 19:05:09",                          
        "Sev":                  "Predictive Error",                             
        "CompID":               "0x2800"                                        
    },                                                                          
    "0x50000089": {                                                              
        "SRC":                  "BD602807",                                      
        "Message":              "The ambient temperature passed the EPOW3 limit. The system will shut down if temp doesn't decrease.",
        "PLID":                 "0x50000089",                                   
        "CreatorID":            "BMC",                                          
        "Subsystem":            "Power/Cooling",                                
        "Commit Time":          "03/04/2022 19:05:09",                          
        "Sev":                  "Predictive Error",                             
        "CompID":               "0x2800"                                        
    },                                                                          
    "0x5000008A": {                                                              
        "SRC":                  "BD602809",                                      
        "Message":              "The ambient temperature passed the EPOW4 limit. The system will shut down",
        "PLID":                 "0x5000008A",                                   
        "CreatorID":            "BMC",                                          
        "Subsystem":            "Power/Cooling",                                
        "Commit Time":          "03/04/2022 19:05:09",                          
        "Sev":                  "Unrecoverable Error",                          
        "CompID":               "0x2800"                                        
    }                                                                           
} 
...
ID=openbmc-openpower                                                            
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"             
VERSION="fw1020.00-41.3"                                                        
VERSION_ID=fw1020.00-41.3                                                       
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) fw1020.00-41.3"
BUILD_ID="20220527"                                                             
OPENBMC_TARGET_MACHINE="p10bmc"

**Comment by bentyner** [comment]
* Ensure fan FRU vpd and phyp indication via pldm sent after hot fan remove and install (using pldmtool, busctl, and journalctl). 

Note: The PLDM traffic is very chatty and hard to correlate to specific events in time. The following sequence of events seem to be consistent with fan add/remove after several rounds of experimentation. 
...
Apr 03 20:27:21 p10bmc phosphor-fan-monitor[583]: Fan /system/chassis/motherboard/fan0 presence state change to true
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 80 02 0a 01 00 04 02 01 02 01 c9 02 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 81 02 0a 01 00 04 02 01 02 01 ca 02 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 82 02 0a 01 00 04 02 01 02 01 cb 02 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 83 02 0a 01 00 04 02 01 02 01 cc 02 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 87 02 0a 01 00 04 02 01 02 01 cd 02 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 88 02 0a 01 00 04 02 01 03 01 54 00 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 89 02 0a 01 00 04 02 01 03 01 00 00 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Rx: 09 01 8f 02 39 54 01 01 01 04 ...          
                                                                                
Apr 03 20:27:29 p10bmc phosphor-fan-monitor[583]: Fan /system/chassis/motherboard/fan0 presence state change to false
Apr 03 20:27:29 p10bmc pldmd[3179]: Tx: 80 02 0a 01 00 04 02 01 01 01 c9 02 00 00
Apr 03 20:27:29 p10bmc pldmd[3179]: Tx: 81 02 0a 01 00 04 02 01 03 01 54 00 00 00
Apr 03 20:27:29 p10bmc pldmd[3179]: Rx: 09 01 00 02 0a 00 00 ...                   
                                                                                
Apr 03 20:27:21 p10bmc phosphor-fan-monitor[583]: Fan /system/chassis/motherboard/fan1 presence state change to true
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 80 02 0a 01 00 04 02 01 02 01 c4 02 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 81 02 0a 01 00 04 02 01 02 01 c5 02 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 82 02 0a 01 00 04 02 01 02 01 c6 02 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 83 02 0a 01 00 04 02 01 02 01 c7 02 00 00 
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 84 02 0a 01 00 04 02 01 02 01 c8 02 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 85 02 0a 01 00 04 02 01 03 01 54 00 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 86 02 0a 01 00 04 02 01 03 01 00 00 00 00 
Apr 03 20:27:21 p10bmc pldmd[3179]: Rx: 09 01 00 02 0a 00 00 ...                   

Apr 03 20:27:32 p10bmc phosphor-fan-monitor[583]: Fan /system/chassis/motherboard/fan1 presence state change to false
Apr 03 20:27:32 p10bmc pldmd[3179]: Tx: 80 02 0a 01 00 04 02 01 01 01 c4 02 00 00
Apr 03 20:27:32 p10bmc pldmd[3179]: Tx: 81 02 0a 01 00 04 02 01 03 01 54 00 00 00
Apr 03 20:27:32 p10bmc pldmd[3179]: Rx: 09 01 00 02 0a 00 00 ...                    

Apr 03 20:27:21 p10bmc phosphor-fan-monitor[583]: Fan /system/chassis/motherboard/fan2 presence state change to true
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 80 02 0a 01 00 04 02 01 02 01 bf 02 00 00 
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 81 02 0a 01 00 04 02 01 02 01 c0 02 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 82 02 0a 01 00 04 02 01 02 01 c1 02 00 00 
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 83 02 0a 01 00 04 02 01 02 01 c2 02 00 00 
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 84 02 0a 01 00 04 02 01 02 01 c3 02 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 85 02 0a 01 00 04 02 01 03 01 54 00 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Tx: 86 02 0a 01 00 04 02 01 03 01 00 00 00 00
Apr 03 20:27:21 p10bmc pldmd[3179]: Rx: 09 01 00 02 0a 00 00 ...                   
                                                                                
Apr 03 20:27:34 p10bmc phosphor-fan-monitor[583]: Fan /system/chassis/motherboard/fan2 presence state change to false
Apr 03 20:27:34 p10bmc pldmd[3179]: Tx: 80 02 0a 01 00 04 02 01 01 01 bf 02 00 00
Apr 03 20:27:34 p10bmc pldmd[3179]: Tx: 81 02 0a 01 00 04 02 01 03 01 54 00 00 00
Apr 03 20:27:34 p10bmc pldmd[3179]: Rx: 09 01 00 02 0a 00 00 ...                    
                                                                                
Apr 03 20:27:20 p10bmc phosphor-fan-monitor[583]: Fan /system/chassis/motherboard/fan3 presence state change to true
Apr 03 20:27:20 p10bmc pldmd[3179]: Tx: 80 02 0a 01 00 04 02 01 02 01 ba 02 00 00
Apr 03 20:27:20 p10bmc pldmd[3179]: Tx: 81 02 0a 01 00 04 02 01 02 01 bb 02 00 00
Apr 03 20:27:20 p10bmc pldmd[3179]: Tx: 82 02 0a 01 00 04 02 01 02 01 bc 02 00 00
Apr 03 20:27:20 p10bmc pldmd[3179]: Tx: 83 02 0a 01 00 04 02 01 02 01 bd 02 00 00
Apr 03 20:27:20 p10bmc pldmd[3179]: Tx: 84 02 0a 01 00 04 02 01 02 01 be 02 00 00
Apr 03 20:27:20 p10bmc pldmd[3179]: Tx: 85 02 0a 01 00 04 02 01 03 01 54 00 00 00
Apr 03 20:27:20 p10bmc pldmd[3179]: Tx: 86 02 0a 01 00 04 02 01 03 01 00 00 00 00
Apr 03 20:27:20 p10bmc pldmd[3179]: Rx: 09 01 00 02 0a 00 00 ...                    
                                                                                
Apr 03 20:27:37 p10bmc phosphor-fan-monitor[583]: Fan /system/chassis/motherboard/fan3 presence state change to false
Apr 03 20:27:37 p10bmc pldmd[3179]: Tx: 80 02 0a 01 00 04 02 01 01 01 ba 02 00 00
Apr 03 20:27:37 p10bmc pldmd[3179]: Tx: 81 02 0a 01 00 04 02 01 03 01 54 00 00 00
Apr 03 20:27:37 p10bmc pldmd[3179]: Rx: 09 01 00 02 0a 00 00 ...

**Comment by bentyner** [comment]
Defect status:

* Done: Ensure enclosure UTMS returned in GetFRURecordTable PLDM cmd. Use pldmtool fru GetFRURecordTable.

* Done: Ensure actual FRU vpd and frame vpd (in PLDM format) with GetFRURecordTable pldm/pdr.

* Done: Ensure fan FRU vpd and phyp indication via pldm sent after hot fan remove and install (using pldmtool, busctl, and journalctl).

* Done: Ensure alerts/epows (eg high ambient temp epow3/4) supported.
