### ISSUE TITLE
GUI : FED : Overview - Truncated network information

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2448]
## Overview
On smaller screens, network information is being truncated with ellipses using CSS. It is a better solution to not hide information and to stack the content.

## UX Flow / Interaction Requirements
1. Remove the code that creates the ellipses
1. Determine if the breakpoint where stacking occurs needs to change to support the display of the information

## Final Invision Mockup
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/532c3c03-9463-4373-8d73-57234d4458f2)- [ ] Add Link

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39223
