### ISSUE TITLE
Retrieve Everest power sequencer device info from entity manager

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2450]
Add the number of sequencers, type of sequencer, and i2c bus and address in an EM config file (eg Nisqually.json).

In the power sequencing app (eg pseq_monitor), get the appropriate data from DBUS.

**Comment by wrightjl1** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/48990

**Comment by wrightjl1** [comment]
Code merged

**Comment by derekhoward55** [comment]
https://github.com/openbmc/entity-manager/blob/master/configurations/Bellavista.json
