### ISSUE TITLE
Retrieve Everest power rails/pgoods from entity manager

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2452]
Update EM config file with rails/pgoods for Everest.  For some of the rails, if they fail we may want to shut down the system. Other rails may just need an error logged, but the system should stay up.

Add the rail/pgood info in an EM config file (eg Nisqually.json).

Need to add info for DCM voltages to ignore appropriate GPI faults for DCMx not present.  SYS_PWR_OK "system status" gpio will be correct even if DCMs are missing (DCM 2&3 are optional), but the ucd gpis for fault status will say faulted if the associated VRMS are missing, or if the specific domain in shared vrm FRUs is not enabled.  The hardware will complete the pon sequence fine, this is only needed to ignore "false" pgood faults.  One strawman is to not monitor GPIs for vrms for DCMs not present.

In the power sequencing app (eg pseq_monitor), get the appropriate data from DBUS.

**Comment by wrightjl1** [comment]
Everest configuration file review: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/50762

**Comment by wrightjl1** [comment]
Callouts for Everest pgood failures review: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/50903
