### ISSUE TITLE
Everest Fan control and monitoring - FF

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2456]
Leave in the dead zone and the proportional step down based on how far above/below the trip point we are like the current BMC algorithm.

Use same MAX31785 fan controller.  

Update existing json for Everest-specific info – number of fans, zones, a temporary safe floor, etc. Get inputs from thermal team and fill it in.  Work towards thermal team filling it out and owning it as before.  Add/remove whats needed (floor, ceiling, fan configs&zones, loc codes, error rules, times, step sizes, service mode/meltdown count, etc).  Use entity manager to choose correct data based on system type.

Read speeds and log errors for failing fans using available error logging infrastructure.

Confirm no PS fan control needed - monitor/report only.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
