### ISSUE TITLE
Initial Everest fan control - all fans high speed

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2457]
Use same MAX31785 fan controller, just set all fans to high speed (or really high floor) and leave there.

Update existing json for Everest-specific info – number of fans, zones, a temporary safe floor, etc.

**Comment by derekhoward55** [comment]
Matt, this one might be covered already by https://github.com/ibm-openbmc/dev/issues/2771?

**Comment by msbarth** [comment]
Yep, all the needed fan application configs for Everest poweron have been merged upstream under that issue.
