### ISSUE TITLE
Test PEL LightPath LEDs when LEDGroup associations are present

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2458]
I have the code now to assert LED groups based on PEL callouts, but the associations between inventory objects and LED Group objects don't exist yet on Rainier, and those need to be there for end to end testing.  This story is to remember to do some final testing when those show up.

**Comment by vishwabmc** [comment]
Depends on : #2306

**Comment by mzipse** [comment]
Per discussion with Matt, reassigning back to Vishwa.  I think Matt doesn't have any additional error logging work.  Let us know if we are wrong @vishwabmc

**Comment by mzipse** [comment]
Closing based on Vishwa's comments.
