### ISSUE TITLE
phosphor-dbus-interfaces:Update SystemConfiguration.interface.yaml to support list of strings for DefaultGateway

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#246]
<a href="https://github.com/ngorugan"><img src="https://avatars0.githubusercontent.com/u/31090230?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ngorugan](https://github.com/ngorugan)**
_Wednesday Nov 08, 2017 at 16:37 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2570_

----

We need to support multiple DefaultGateways to support dual stack(ipv4/ipv6), Because each address family does its own routing, Right now we are supporting only one.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
same as https://github.com/ibm-openbmc/dev/issues/387

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/17901/
