### ISSUE TITLE
eBMC LED Management :: Virtual Service Attention Indicators :: Redfish GET Support

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2462]
Enable GET functionality for the functionality defined in #2460 

Posted the question in : https://redfishforum.com/thread/361/virtual-system-attention-indicator-functional

**Comment by vishwabmc** [comment]
I presented this in Redfish meeting held on 08/20/2020 and we are kind of leaning towards having a message in the HealthRollup Property. For IBM, we could use the HealthRollUp that is in Systems/ schema

**Comment by vishwabmc** [comment]
This will key off of `xyz/openbmc_project/led/groups/partition_system_attention_indicator` and `xyz/openbmc_project/led/groups/platform_system_attention_indicator`

**Comment by rfrandse** [comment]
tracking in jira
