### ISSUE TITLE
eBMC LED Management :: Virtual Service Attention Indicators :: Redfish PATCH Support

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2463]
Enable PATCH functionality for the functionality defined in #2460

Posted the question in : https://redfishforum.com/thread/361/virtual-system-attention-indicator-functional

**Comment by vishwabmc** [comment]
Code support is already in : https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43391/

**Comment by rfrandse** [comment]
tracking in jira
