### ISSUE TITLE
Everest fan status/telemery support

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2466]
Fan speed telemetry data for external collection.

Fan speeds already placed on DBUS. Verify from there they can get pulled out via Redfish telemetry service (will be HMC pulling the data on customer systems).

Properties wanted from thermal team are:
Fan speed min/max/ave every hour.

For this issue, should be suffice to collect/append once-per-minute readings for 1 hour for every fan rotor in one of the everest systems when powered on.

Also ensure when fan presence or fault status changes the redfish sensor status is updated (eg on GUI) and a pldm PDR change event is generated (if not tested elsewhere).

**Comment by aahmed-2** [comment]
Here is an example Fan report from an Everest system running VERSION="fw1020.00-33.1".


"MetricValues": [
{
        "MetricId": "Ambient_1_Temp",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/Ambient_1_Temp/Reading",
        "MetricValue": "26.324000",
        "Timestamp": "2021-11-23T23:18:22+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan0_0/Reading",
        "MetricValue": "10593.000000",
        "Timestamp": "2021-11-23T23:18:21+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan0_1/Reading",
        "MetricValue": "10901.000000",
        "Timestamp": "2021-11-23T23:18:20+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan1_0/Reading",
        "MetricValue": "10623.000000",
        "Timestamp": "2021-11-23T23:18:22+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan1_1/Reading",
        "MetricValue": "10932.000000",
        "Timestamp": "2021-11-23T23:18:20+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan2_0/Reading",
        "MetricValue": "10714.000000",
        "Timestamp": "2021-11-23T23:18:22+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan2_1/Reading",
        "MetricValue": "10964.000000",
        "Timestamp": "2021-11-23T23:18:22+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan3_0/Reading",
        "MetricValue": "10593.000000",
        "Timestamp": "2021-11-23T23:18:20+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan3_1/Reading",
        "MetricValue": "10932.000000",
        "Timestamp": "2021-11-23T23:18:22+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Thermal#/Fans/0/Reading",
        "MetricValue": "10593.000000",
        "Timestamp": "2021-11-23T23:18:21+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Thermal#/Fans/1/Reading",
        "MetricValue": "10901.000000",
        "Timestamp": "2021-11-23T23:18:20+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Thermal#/Fans/2/Reading",
        "MetricValue": "10623.000000",
        "Timestamp": "2021-11-23T23:18:22+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Thermal#/Fans/3/Reading",
        "MetricValue": "10932.000000",
        "Timestamp": "2021-11-23T23:18:20+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Thermal#/Fans/4/Reading",
        "MetricValue": "10714.000000",
        "Timestamp": "2021-11-23T23:18:22+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Thermal#/Fans/5/Reading",
        "MetricValue": "10964.000000",
        "Timestamp": "2021-11-23T23:18:22+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Thermal#/Fans/6/Reading",
        "MetricValue": "10593.000000",
        "Timestamp": "2021-11-23T23:18:20+00:00"
},
{
        "MetricId": "Fan_Tach",
        "MetricProperty": "/redfish/v1/Chassis/chassis/Thermal#/Fans/7/Reading",
        "MetricValue": "10932.000000",
        "Timestamp": "2021-11-23T23:18:22+00:00"
}
],
"Name": "Fan_Report",
"Timestamp": "2021-11-23T23:18:22+00:00"

**Comment by aahmed-2** [comment]
@gtmills @derekhoward55 what do you think of this output?

**Comment by derekhoward55** [comment]
Collected 30s min/max/ave fan speeds.  Eg:

`{
  "@odata.id": "/redfish/v1/TelemetryService/MetricReports//Thermal_metrics",
  "@odata.type": "#MetricReport.v1_3_0.MetricReport",
  "Id": "Thermal_metrics",
  "MetricReportDefinition": {
    "@odata.id": "/redfish/v1/TelemetryService/MetricReportDefinitions//Thermal_metrics"
  },
  "MetricValues": [
    {
      "MetricId": "MaxFan2_0_30s",
      "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan2_0/Reading",
      "MetricValue": "10932.000000",
      "Timestamp": "2021-09-06T11:45:44+00:00"
    },
    {
      "MetricId": "AveFan2_0_30s",
      "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan2_0/Reading",
      "MetricValue": "10898.457233",
      "Timestamp": "2021-09-06T11:45:44+00:00"
    },
    {
      "MetricId": "MinFan2_0_30s",
      "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan2_0/Reading",
      "MetricValue": "10869.000000",
      "Timestamp": "2021-09-06T11:45:44+00:00"
    },
    {
      "MetricId": "MaxFan2_1_30s",
      "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan2_1/Reading",
      "MetricValue": "11160.000000",
      "Timestamp": "2021-09-06T11:45:44+00:00"
    },
    {
      "MetricId": "AveFan2_1_30s",
      "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan2_1/Reading",
      "MetricValue": "11143.150200",
      "Timestamp": "2021-09-06T11:45:44+00:00"
    },
    {
      "MetricId": "MinFan2_1_30s",
      "MetricProperty": "/redfish/v1/Chassis/chassis/Sensors/fan2_1/Reading",
      "MetricValue": "11127.000000",
      "Timestamp": "2021-09-06T11:45:44+00:00"
    },
`
