### ISSUE TITLE
Everest Temp Monitoring

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2467]
Get component temp sensors expected and limits info in dts, entity manager, etc.

When system team determines which op panel they'll use, get appropriate sensor info (TMP275, DPS310, Si7021-A20) in dts, entity manager etc.  DD should already be written for all, and values should be in DBUS.

Update EPOW/perf loss limits in entity manager backplane.json config file.

Update hot card, cable card, pcie switch, nvme drive config files for card settings, thresholds, etc.

Update Everest altitude settings (logging "outside environment" error (above X m in sys workbook), fan floor settings if supported).

Update ambient floor settings.

Confirm temps in redfish, telemetry, etc as appropriate.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
