### ISSUE TITLE
PFP::control - Everest hot adapter temp sensor updates

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2471]
Update hot card, cable card, pcie switch, nvme drive config files for card settings, thresholds, etc.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50667
and
Resolved by 
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/49514
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/49510
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50263
