### ISSUE TITLE
Read Everest UPS status

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2473]
Configure dts or whatever else is needed to read ups signals from usb connector.

**Comment by smccarney** [comment]
Eddie James said that he thought the kernel configuration changes he did for Rainier would also be in place for Everest.

No Everest-specific functionality was planned for the ibm-ups application.

Tested the ibm-ups application with the "dummy" UPS device today on an Everest system with Marissa Garza's help.

Completed the following test plan.  All tests worked as expected:
```
+ Reading the UPS state over the USB cable
  + Device not plugged in
  + Device plugged in
    + Verify /dev/ttyUSB* file exists when device is plugged in
  + Battery Low signal is false
  + Battery Low signal is true
  + UPS On signal is false
  + UPS On signal is true
  + Utility Fail signal is false
  + Utility Fail signal is true
+ End to end tests
  + UPS is added
  + UPS is removed
  + UPS is re-plugged after being removed for 5+ seconds
  + Verify no errors logged by UPS application
  + Verify no errors written to journal by UPS application
```
