### ISSUE TITLE
Manufacturing policy flags Infrastructre

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2478]
Create all supported Policy flags in Settings Under two different name space , BMC only and BMC-Host common name space.

**Comment by ojayanth** [comment]
Reference commits: 
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/28677
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/31217

**Comment by ojayanth** [comment]
As per discussion with Rajiv moving to Ratan's squad.

**Comment by trajeswaran** [comment]
CFT has infrastructure to enable or disable policy flags for manufacturing. BMC users can use the D-Bus call to enable or disable settings. I don't see a need for this issue. So, I am marking this as closed.

**Comment by ojayanth** [comment]
This issue  created to track the work associated  to settings support for BMC/Host specific  manufacturing policy flags. @trajeswaran need to provide method to  No manufacturing ( FTC/DVT) teams to update the Host policy flags.

**Comment by ratagupt** [comment]
@ojayanth: Can we close this as per our last discussion in the openbmc design meeting?
