### ISSUE TITLE
LED Callout ::  Turn on Platform Service Attention soft indicator on failure to isolate part

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2479]
#2050 will have the work that will walk the callout and determine what LED needs to be asserted. However, in the case where the callout can not be isolated to a FRU or if there are procedure callouts ( as per the LightPath and Guiding Light document , then PEL need to set the virtual indicator called, Platform Service Attention Indicator.

PEL can not set the physical SAI.. Physical SAI will be set by LED manager in response to PEL setting Platform SA.

This issue depends on : #2461

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35938

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35938 merged
