### ISSUE TITLE
Create PSU PELs with SRCs/callouts in message registry

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2480]
Create PELs for existing openbmc event logs and faults in general.  PE, test, and customer doc teams requested that SRCs remain consistent for BMC power/thermal faults as previous systems.  MFG team requested callouts for building systems.

Use standard openbmc APIs to create the PELs.  Add base SRCs to message registry with callouts/severities/action flags etc at https://github.ibm.com/openbmc/phosphor-logging/blob/master/extensions/openpower-pels/registry/message_registry.json.

An example, update/expand as necessary:

{
--
  | "Name": "xyz.openbmc_project.Power.X",
  | "Subsystem": "power",
  | "ComponentID": "0x2700",
  |  
  | "SRC": {
  | "Type": "11",
  | "ReasonCode": "0x1510",
  | "Words6To9": {}
  | },
  |  
  | "Callouts": [
  | {
  | "CalloutList": [
  | { "Priority": "high", "Procedure": "pwrsply" }
  | ]
  | }
  | ],
  |  
  | "Documentation": {
  | "Description": "A power supply detected an AC loss",
  | "Message": "A power supply detected an AC loss",
  | "Notes": [
  | "Callout an iso procedure instead of the FRU as ",
  | "typically this is an input fault, not a bad PSU."
  | ]
  | }
  | },

**Comment by bjwyman** [comment]
PWRSPLY procedure: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/36243
110015xx to registry: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/36244

**Comment by bjwyman** [comment]
psu-ng: Create errors for detected faults
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/36841
psu-ng: Log errors for missing power supplies
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/37235
psu-ng: Limit tracing/logging read failures
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/37098
psu-ng: Create error for communication fault
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/37236
psu-ng: Store PSU firmware version in errors
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/37295

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/37530
	phosphor-logging: srcrev bump ed32c8dad8..38caaf0730
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/37522
	phosphor-power: srcrev bump ca08a79076..76b7643f89

**Comment by bjwyman** [comment]
https://github.com/openbmc/openbmc/commit/a8569fb71bb467725f5d1cc9b1515a98b635b366
https://github.com/openbmc/openbmc/commit/50e8f1af0acdf1b27aaf509e309161a2732cb158

**Comment by bjwyman** [comment]
This is done.
