### ISSUE TITLE
Create fan/thermal PELs with SRCs/callouts in message registry

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2481]
Create PELs for existing openbmc event logs and faults in general. PE, test, and customer doc teams requested that SRCs remain consistent for BMC power/thermal faults as previous systems. MFG team requested callouts for building systems.

Use standard openbmc APIs to create the PELs. Add base SRCs to message registry with callouts/severities/action flags etc at https://github.ibm.com/openbmc/phosphor-logging/blob/master/extensions/openpower-pels/registry/message_registry.json.

An example, update/expand as necessary:

{
  | "Name": "xyz.openbmc_project.Thermal.X",
  | "Subsystem": "thermal",
  | "ComponentID": "0x2800",
  |  
  | "SRC": {
  | "Type": "11",
  | "ReasonCode": "0x7611",
  | "Words6To9": {}
  | },
  |  
  | "Callouts": [
  | {
  | "CalloutList": [
  | { "Priority": "high", "Procedure": "airmovr" }
  | ]
  | }
  | ],
  |  
  | "Documentation": {
  | "Description": "A problem was detected with a fan which can be caused by a fan not being installed.",
  | "Message": "A problem was detected with a fan which can be caused by a fan not being installed.",
  | "Notes": [
  | "Callout an iso procedure instead of the FRU as ",
  | "we won't have the part number if fan is missing."
  | ]
  | }
  | },

**Comment by spinler** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/37588 and https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/36715
