### ISSUE TITLE
Create Pgood PELs with SRCs/callouts in message registry

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2482]
Create PELs for existing openbmc event logs and faults in general. PE, test, and customer doc teams requested that SRCs remain consistent for BMC power/thermal faults as previous systems. MFG team requested callouts for building systems.

Use standard openbmc APIs to create the PELs. Add base SRCs to message registry with callouts/severities/action flags etc at https://github.ibm.com/openbmc/phosphor-logging/blob/master/extensions/openpower-pels/registry/message_registry.json.

An example, update/expand as necessary:

{
  | "Name": "xyz.openbmc_project.Power.X",
  | "Subsystem": "power",
  | "ComponentID": "0x2700",
  |  
  | "SRC": {
  | "Type": "11",
  | "ReasonCode": "0x2620",
  | "Words6To9": {}
  | },
  |  
  | "Callouts": [
  | {
  | "CalloutList": [
  | { "Priority": "high", "Procedure": "pgdpart" }
  | ]
  | }
  | ],
  |  
  | "Documentation": {
  | "Description": "A power-good fault was detected.",
  | "Message": "A power-good fault was detected.",
  | "Notes": [
  | "Callout an iso procedure instead of the FRU as ",
  | "this type of pgood may be caused a variety of ways."
  | ]
  | }
  | },

**Comment by wrightjl1** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/38649
