### ISSUE TITLE
GUI : Research : Configuration - Hardware Management Client Sessions

### ISSUE THREAD

**Issue by nicoleconser** [ibm-openbmc/dev#2483]
## SME
**BMC**: @ratagupt 
**RAS**: George Ahrens
**PHYP**:

## Summary
This is to revisit the Hardware Management Console page #1260 to be more generic. We cannot call this page "Hardware Management Consoles" because that is an IBM term (HMC). This page will show **all** client sessions, not just the HMC. 

## User Story
As a BMC admin, I will need to be able to see which management consoles and users are connected to my BMC and remove them if needed.

## References
- #1260 
- Link to Discovery folder

## Key conversations
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1603275505414000

### Invision prototype
**Lo fi**
https://ibm.invisionapp.com/share/Z2O0QIF5ABE
**HI fi**
https://ibm.invisionapp.com/share/2EO0QDPFHTD

**Comment by derick-montague** [comment]
Backend functionality should be ready. Need @nicoleconser to determine if we need to move this forward and determine the IA naming and placement as part of this story.

**Comment by ratagupt** [comment]
We can show the client Identifier and the IP address for all the connected clients.

}[rgupta@localhost ~]$  curl --insecure -X POST -D headers.txt https://${BMC}/redfish/v1/SessionService/Sessions -d '{"UserName":"root", "Password":"0penBmc", "Oem": { "OpenBMC": {"ClientID": "HMC1"}}}'
{
  "@odata.id": "/redfish/v1/SessionService/Sessions/fdUqAK1ESD",
  "@odata.type": "#Session.v1_3_0.Session",
  "ClientOriginIPAddress": "::ffff:9.102.1.247",
  "Description": "Manager User Session",
  "Id": "fdUqAK1ESD",
  "Name": "User Session",
  "Oem": {
    "OpenBMC": {
      "@odata.type": "#OemSession.v1_0_0.Session",
      "ClientID": "HMC1"
    }
  },
  "UserName": "root"
} 


[rgupta@localhost ~]$ cat headers.txt 
HTTP/1.1 201 Created
X-Auth-Token: goEVmCMzjM8YqxleRan2
Location: /redfish/v1/SessionService/Sessions/fdUqAK1ESD
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: DENY
Pragma: no-cache
Cache-Control: no-Store,no-Cache
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'none'; img-src 'self' data:; font-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self' wss:
Content-Type: application/json
Date: Thu, 22 Oct 2020 10:27:42 GMT
Content-Length: 386

[rgupta@localhost ~]$ export bmc_token=goEVmCMzjM8YqxleRan2


[rgupta@localhost ~]$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC}/redfish/v1/SessionService/Sessions/fdUqAK1ESD
{
  "@odata.id": "/redfish/v1/SessionService/Sessions/fdUqAK1ESD",
  "@odata.type": "#Session.v1_3_0.Session",
  **"ClientOriginIPAddress": "::ffff:9.102.1.247",**
  "Description": "Manager User Session",
  "Id": "fdUqAK1ESD",
  "Name": "User Session",
  "Oem": {
    "OpenBMC": {
      "@odata.type": "#OemSession.v1_0_0.Session",
      **"ClientID": "HMC1"**
    }
  },
  "UserName": "root"
}[rgupta@localhost ~]$ 


GUI needs to show the above two info..
1/ ClientOriginIPAddress
2/ ClientID"

Ratan

**Comment by derick-montague** [comment]
@ratagupt @gtmills  - I know we said that was not going to be possible when this was being designed by Ryan earlier this year. Has that changed?  I thought there was a Redfish API for disconnecting a service.

**Comment by derick-montague** [comment]
[Per @ratagupt:](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1603456993010600?thread_ts=1603275505.414000&cid=C0Q6TQP5Z)
> Disconnecting a service: Might be you want to ask disconnecting the client. if yes then why do we want this?  it is doable. we have the backend API for the same.

**Comment by ParishrutB** [comment]
**Current doubts:**
1. Client ID - What does this mean to the user?
2. Disconnect/delete a session - Whether this will be implemented? https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1603449988007700?thread_ts=1603275505.414000&cid=C0Q6TQP5Z

**To do**
- [ ] Make a mock up with both
- [ ] Have a meeting with internal users along with Nicole
         - Check the copy.
         - Understand use case of each item.
- [ ] Update design, and then discuss with team.

**Comment by ParishrutB** [comment]
Casual playback 13/11/20

**Next steps:**
Design & implement the top half (table)
- Doubt to be checked: What if an HMC disconnects from it's side? Will the connection disappear from the GUI table or will there be a message left behind for the user? 
- Test with internal users.

https://ibm.webex.com/ibm/ldr.php?RCID=f0266e1b3f6048e89fb8c8614c820f73
KxSKjEx8

![image](https://user-images.githubusercontent.com/61419136/99045375-3e560600-25b7-11eb-9d83-3629ca732fd2.png)

**Comment by priyanka-pillai97** [comment]
![2020_11_11 20_21 Office Lens](https://user-images.githubusercontent.com/61419618/99660766-d311a580-2a88-11eb-85ef-5817b6c062bc.jpg)


Casual playback 13/11/20 
**Next steps:**
- [ ] Design & implement the top half (table)
- Test with internal users.

@ratagupt informed us that making the system HMC managed (bottom half of the sketch) is still under backend discussion.  Link to conversation - https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1603275505414000
