### ISSUE TITLE
GUI : FED : Add link to header logo

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2487]
## Overview
Add link to app header logo that will redirect to homepage

## UX Flow / Interaction Requirements
- [ ] When clicking the logo in the application, I should be navigated to Overview page

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35920

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35920 merged
