### ISSUE TITLE
Implement PLDM State Sets for power/thermal events

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2488]
The new design direction is to have a PLDM sensor representing each error bit still required by the Host/OS's (ups status, thermal_faults, etc).  A State Set will need to be implemented for each sensor, and will be associated with an Entity.  The information may also need to be read by other BMC apps (eg ups status. other apps notified by DBUS signal).  

PHYP/Host will get this information by BMC doing a platform event message when the State Set changes.  PHYP will need to accept the status the BMC sends up, and should be able to read the information at any time.

The code support for this story includes includes:

- Create/implement the 3 appropriate entities
- Associate the entities with a state sensor to the appropriate 5 state sets
- Default the sensors to an appropriate state (ambient temp good, no thermal fault.  can't default UPS info until UPS monitoring code puts it on dbus with https://github.com/ibm-openbmc/dev/issues/1037)
- Ensure when the sensor is read via GetStateSensorReading the appropriate value is returned
- Ensure a change in the state of one of the sensors results in a PlatformEventMessage being sent up to PHYP

The function behind setting the sensor states will be implemented/tested in future appropriate issues.

See "Interface Architecture: POWR to BMC" and "eBMC Host Interface Architecture" documents for details.

**Comment by spinler** [comment]
The PLDM state sensor JSON for the thermal fault sensor is at https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/39704

**Comment by spinler** [comment]
The PLDM state sensors for the ambient EPOW3/4 alerts are at https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/39934

**Comment by derekhoward55** [comment]
The UPS-specific state sensors, config files, etc will be implemented under https://github.com/ibm-openbmc/dev/issues/1643.
