### ISSUE TITLE
GUI : FED : Date & time table data formatting

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2489]
## Overview
All instances of date and time displayed in a table should include a line break.
Currently updates are needed on the **Event logs** page and on the **Overview** page for high priority events.

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshots
To be:

<img width="264" alt="Screen Shot 2020-08-10 at 2 33 26 PM" src="https://user-images.githubusercontent.com/8097306/89833788-824bf180-db16-11ea-85f5-5a926d177844.png">

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35923

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35923 merged
