### ISSUE TITLE
GUI : FED : 404 page

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2490]
## Overview
Create a 404 page. Currently navigation to an undefined route shows a blank white page

## UX Flow / Interaction Requirements
- [ ] When a user navigates to a route that is not defined, they should see a 404 page

## Final Invision Mockup
Should follow similar pattern to our unauthorized page (can be seen by navigating directly to /unauthorized)

<img width="1459" alt="Screen Shot 2020-08-10 at 2 37 44 PM" src="https://user-images.githubusercontent.com/8097306/89834180-27ff6080-db17-11ea-9636-e41592f07bc3.png">

## Notes
- [ ] Vue router notes https://router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by derick-montague** [comment]
The title should be:
 `Page not found`.

The description should be:
`The requested resource could not be found.`

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35993

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35993 merged
