### ISSUE TITLE
GUI : FED : Implement consistent "Save" pattern

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2491]
## Overview
Network settings and Server power operations pages are using a pattern we are moving away from for form actions. UX audit determined that we will always keep the primary form action enabled. Update network settings page and server power operations page (boot settings) to always have 'Save' button enabled.

## UX Flow / Interaction Requirements
- [ ] A form action is always enabled. Any validations will prevent invalid form values from being submitted

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshots
<img width="1067" alt="Screen Shot 2020-08-10 at 2 43 39 PM" src="https://user-images.githubusercontent.com/8097306/89834559-f044e880-db17-11ea-96a8-3ede6ad7d657.png">
<img width="713" alt="Screen Shot 2020-08-10 at 2 43 47 PM" src="https://user-images.githubusercontent.com/8097306/89834562-f2a74280-db17-11ea-808a-43fc6486d886.png">

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35924

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35924 merged
