### ISSUE TITLE
GUI : FED : Boot settings - change switch to checkbox

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2492]
## Overview
Boot settings TPM required policy form control should be changed to a checkbox with `Enabled` label.

Currently on the Server power operations page, there is a switch component used in the boot settings form. We have determined from UX audit that the switch component should not be used within a form that requires a save, because the pattern going forward will be that a switch will make an immediate call and should not require a 'Save'

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshots
<img width="395" alt="Screen Shot 2020-08-10 at 2 47 32 PM" src="https://user-images.githubusercontent.com/8097306/89834901-8a0c9580-db18-11ea-9ccd-93382a232a14.png">

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35979

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35979 merged
