### ISSUE TITLE
GUI : FED : Server power operations - In progress alert

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2493]
## Overview
When a server operation is in progress the message that appears should be in an **Info Alert**.

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshots

Current:
<img width="697" alt="Screen Shot 2020-08-10 at 2 51 43 PM" src="https://user-images.githubusercontent.com/8097306/89835152-099a6480-db19-11ea-86c3-b97abada865c.png">

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35823
