### ISSUE TITLE
GUI : FED : Loading bar - striping

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2494]
## Overview
Update the global loading bar visual style from animated stripes to an animated linear gradient. Determine possible options and verify final design with @ben-bacon 

## Notes
- https://bootstrap-vue.org/docs/components/progress#animated-backgrounds

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by derick-montague** [comment]
FED will need to do some research with animating gradients. The current striping of the bootstrap out of the box progress indicator does not meet IBM design quality. Need to discuss with community.

**Comment by yoshiemuranaka** [comment]
@ben-bacon and I discussed whether or not this change should be the default, or if we should add a flag to enable depending on your environment. Thoughts @derick-montague ?

**Comment by derick-montague** [comment]
> @ben-bacon and I discussed whether or not this change should be the default, or if we should add a flag to enable depending on your environment. Thoughts @derick-montague ?

My feeling is a flag since it is custom from Bootstrap. I think we are at the point where changes that stray from OOB Bootstrap, unless critical to the UI, may be better behind the customization flag. We can always share with the community to see if the customization is something others would want.

**Comment by ben-bacon** [comment]
For the OOB component, lets use the $primary color token and then bump the contrast of the stripes up to 25% lighter for accessibility. This should look similar to the bootstrap native component, but also provide brand consistency to whoever changes the theme. Then we can put our own custom loading bar behind the customization flag. 

example: 
![image](https://user-images.githubusercontent.com/52676199/90786035-b4a0e000-e2c8-11ea-9902-10974eec037c.png)

**Comment by derick-montague** [comment]
> For the OOB component, lets use the $primary color token and then bump the contrast of the stripes up to 25% lighter for accessibility. This should look similar to the bootstrap native component, but also provide brand consistency to whoever changes the theme. Then we can put our own custom loading bar behind the customization flag.

This is a great approach. Thanks, @ben-bacon.

**Comment by derick-montague** [comment]
Going to close story as we will put efforts into customization. The community is happy with the Bootstrap OOB experience.
