### ISSUE TITLE
GUI : FED : Firmware - copy to backup

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2495]
## Overview
Add ability to copy running FW version to backup

## UX Flow / Interaction Requirements
- [ ] When clicking `Copy to backup` a modal is triggered to confirm action
- [ ] After confirmation modal, show appropriate toast to indicate success/fail

## Notes
- Search for `stacked move` on[ carbon design system](https://www.carbondesignsystem.com/guidelines/icons/library/) for icon
- `@carbon/icons-vue/es/watson-health/stacked-move/20`

## cURL Commands
- [ ] n/a

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshots
![Screen Shot 2021-02-03 at 1 10 33 PM](https://user-images.githubusercontent.com/8097306/106810544-f5e03e80-6621-11eb-8708-e65278c7ddb5.png)
![Screen Shot 2021-02-03 at 1 11 13 PM](https://user-images.githubusercontent.com/8097306/106810557-fd074c80-6621-11eb-8ea6-31dbba0a3b4a.png)

**Comment by derick-montague** [comment]
This will not be implemented in GA1. Possibly not at all. I am opening a new story that will be part of the same epic for displaying an error message to the user.

**Comment by sandeepasingh116** [comment]
Maury and Adriana met and decided not to do this, `since we just have the user do another code update and that essentially accomplishes the same thing.`. Hence closing this.
