### ISSUE TITLE
GUI : FED : Table filtering empty text translation

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2500]
## Overview
When using the table search filter in tables, if there are no filter matches a default message appears in the table. This value needs to be translated and added to all tables that have the search filter capability. The default value is "There are no records matching your request" this should be changed to `There are no items matching your search input`

## UX Flow / Interaction Requirements
- [ ] When a user types into the search input for a table, if no records match, they should see a translated message

## Notes
- [ ] `empty-filtered-text` property https://bootstrap-vue.org/docs/components/table#comp-ref-b-table-props

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshots
![Screen Shot 2020-08-11 at 11.10.24 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/01ea6ea6-ecc5-4134-bb30-d4d6c32fbbf2)

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36053

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36053 merged
