### ISSUE TITLE
GUI : FED : Table search filter clear button

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2501]
## Overview
Add ability to quickly clear a table input search field

## UX Flow / Interaction Requirements
- [ ] When a value is typed into the table search input field a clear button should become visible
- [ ] If clear button clicked, the input value should clear and the button should disappear

## Notes
- Can follow similar pattern to what is defined in Carbon https://www.carbondesignsystem.com/components/search/usage#live-demo
- Discuss with @ben-bacon if mock is not available or clear

## Invision
https://ibm.invisionapp.com/share/U9O039T4Q6E#/319560582_Search_Bar

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36289
