### ISSUE TITLE
PLDM: oem: support reading LIDS based on type "P" and "T" and writing image LIDs to a specific location in bmc

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2507]
pldm code should change 
std::string dir = permSide ? LID_ALTERNATE_DIR : LID_RUNNING_DIR; <=== instead of this direct check, it should check the current boot side effecter value and decide the path. if current boot side is P then read request of P side should read LID_RUNNING_DIR and similarly for other values

pldm needs to check the "Activation" property of the side always before sending a response to Read LID. Activation property active means the side is valid. Reading happens only on a valid side. Every other value is considered to be an invalid side. Side to version mapping is needed for reading the Activation property

**Comment by dkodihal** [comment]
```
What LID do we get when we
Read a "T" side lid when we booted on the T side
Read a "P" side lid when we booted on the T side
Read a "T" side lid when we booted on the P side
Read a "P" side lid when we booted on the P side
Read a "T" side lid when we booted on the T side but a side rename has happened
Read a "P" side lid when we booted on the T side but a side rename has happened
Read a "T" side lid when we booted on the P side but a side rename has happened
Read a "P" side lid when we booted on the P side but a side rename has happened
```

**Comment by dkodihal** [comment]
```
running
alternate
alternate
running
if side renamed occurred, we’re booted from P now, so alternate
if side renamed occurred, we’re booted from P now, so running
if side renamed occurred, we’re booted from T now, so running
if side renamed occurred, we’re booted from T now, so alternate
```

**Comment by sampmisr** [comment]
code has been merged
