### ISSUE TITLE
PLDM: Platform: event framework to send events to PHYP for different stages of code udpate progress 

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2509]
Create a framework in oem-ibm layer to send PlatformEventMessage to Phyp for different stages of inband code update progress. The event is a state sensor event. The details of the state sets and the state set id is described at github issue #2505 
The api created as part of this story will be called after the relevant state effecter is set

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/36371

**Comment by sampmisr** [comment]
Code is merged
