### ISSUE TITLE
PFP::monitor Investigate/Fix removal of configured trust groups

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2510]
In spec'ing out an updated fan controller chip on Witherspoon that does not latch the feedback speeds of the rear rotors to 0 during fan target transitions, I found that completely removing the fans from a configured trust group (non-zero trust) seems to set the feedbacks to zero and not get updated as they change during the transition. This does not seem to be a result of this updated fan controller chip, so this is to investigate within the fan monitoring configuration why doing this causes the fan monitor application to fail to properly monitor fans that are not configured into a trust group. (Other systems have had configurations that do not use the trust group option without issue, so this may be related to some other area of the fan monitoring application...i.e. JSON config file parsing)

**Comment by msbarth** [comment]
Believe I found the issue. Apparently the way the tach input values are read from dbus are not being implicitly converted to an int64 from double since the `Value` property on the sensor dbus interface was converted over to be of double type.

**Comment by msbarth** [comment]
I should note, the reason this was not found until now while spec'ing a different fan controller chip was due to the Witherspoon fan monitor configuration having a workaround in its configuration was there to handle some fans reporting a 0 fan feedback speed when transitioning to a requested target speed. This update fan controller should allow that workaround to be removed, so when it was removed I was seeing feedbacks of 0 being set which looks to be due to the double->int64 conversion not working.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/35600

**Comment by msbarth** [comment]
Corrected similar issue in the fan presence app
https://gerrit.openbmc-project.xyz/35611

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/35600 merged
