### ISSUE TITLE
GUI : FED : Update empty table state

### ISSUE THREAD

**Issue by SurenNeware** [ibm-openbmc/dev#2511]
## Overview
Update default empty table state to High priority events in Overview page.
- [ ] Keep empty table structure visible if there is no item.
- [ ] Add the `show-empty` prop to tables and provide default empty-text value for table.

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
- [ ] Add cURL commands

## Notes
- Example of default table state on event logs page
- Old story https://github.com/ibm-openbmc/dev/issues/2291

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35767

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35767 merged
