### ISSUE TITLE
GUI : FED : Replace partial border below page section heading

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2515]
## Overview
The updated style guide has removed the partial bottom border below page section headings.

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/114f84d6-c4fb-4fe7-afe9-ec6fa9d2e0d2)

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35921

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35921 merged
