### ISSUE TITLE
PLDM: OEM: create the image for inband code update

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2516]
This story is aiming for an api which generates an image suitable for code update. The bmc and non-bmc LIDS and other required files to build the image are provided by PLDM.

**Comment by anoo1** [comment]
Summar:
- For this story, LIDs are classified into BMC and hostfw files, hostfw LID files are binaries and BMC LID files are a tarball file split into multiple files
- PHYP sends to the BMC individual LID files that with a header identifying the LID file. PLDM will use the header to parse the type information, then the header piece can be thrown away so only the data piece is kept.
- If LID is a BMC file, concatenate it to recreate the tarball file
- If LID Is a hostfw file, add it to a squashfs image file

After all LIDs are received, add the hostfw squashfs image file to the BMC tarball file.

**Comment by anoo1** [comment]
PLDM code has been merged: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/37510
