### ISSUE TITLE
Remove the --long from our git describe call 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2518]
https://git-scm.com/docs/git-describe
```
--long

    Always output the long format (the tag, the number of commits and the abbreviated commit name) even when it matches a tag. This is useful when you want to see parts of the commit object name in "describe" output, even when the commit in question happens to be a tagged version. Instead of just emitting the tag name, it will describe such a commit as v1.2-0-gdeadbee (0th commit since tag v1.2 that points at object deadbee…​.).

```

op940.20-2-0-g41259a41 is still not customer friendly

**Comment by gtmills** [comment]
op940.20-2 would be better

**Comment by gtmills** [comment]
https://github.com/openbmc/meta-phosphor/blob/e9319a8c4b7bc9b737fbb6e5359f878d5ab13e7a/recipes-core/os-release/os-release.bbappend#L17

Some history:

https://github.com/openbmc/meta-phosphor/commit/92823c66587ff16cd8b5200954d4d5ad2ff65ac5

https://github.com/openbmc/openbmc/issues/1692

**Comment by anoo1** [comment]
Example of /etc/os-release:
```
VERSION="fw1020.00-13.5"
VERSION_ID=fw1020.00-13.5-3-g0b10e02e3f-dirty
```

Seems that we could have the phosphor-bmc-code-mgmt code use "VERSION" instead of "VERSION_ID" to populate the d-bus object.

**Comment by anoo1** [comment]
Removing `--long` with:
https://gerrit.openbmc-project.xyz/q/topic:%22git-describe-long%22+(status:open%20OR%20status:merged)

**Comment by gtmills** [comment]
@anoo1  https://gerrit.openbmc-project.xyz/q/topic:%22git-describe-long%22+(status:open%20OR%20status:merged) merged so closing. Please reopen if I was wrong. 

Thanks for doing this work!!!!
