### ISSUE TITLE
Redfish switching running image enhancement needed

### ISSUE THREAD

**Issue by gkeishin** [ibm-openbmc/dev#2519]
## Expected Behavior

If a firmware is already functional,  check if already functional and no-op the PATCH request to switch

## Actual Behavior

If current functional image set to switch by setting itself, the BMC reset and come back with same image as functional

## Steps to Reproduce the Problem

  1. Execute PATCH for a image which is already functional 
```
redfishtool -r xx.xx.xx.xx -u root -p 0penBmc  -S Always raw PATCH /redfish/v1/Managers/bmc --data='{ "Links": { "ActiveSoftwareImage": {"@odata.id":"/redfish/v1/UpdateService/FirmwareInventory/16f4bd34"}}}'
```

## Specifications
NA

**Comment by gkeishin** [comment]
Discussed with Gunnar and need enhancement.

**Comment by rfrandse** [comment]
tracking in jira
