### ISSUE TITLE
GUI : FED :  Control: KVM - Remove from primary navigation

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2521]
## Overview
 Control -> KVM - this is not required for eBMC systems and should be not be part of the IBM build

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/36760 is removing this from the backend

**Comment by dixsie** [comment]
Work not needed. KVM is currently not included in IBM's app nav
