### ISSUE TITLE
GUI : FED : Add title attribute to all icon only buttons

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2524]
## Overview
Buttons that only contain an icon should include a `title` attribute with the value set to the action text that will be displayed on hover. The display of the value is native to the browser and will not be able to be customized in any way.

Some buttons have already been updated. Part of this story is auditing the UI to determine where all these buttons exist and adding the title attribute on icon buttons.

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36000

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36000 merged
