### ISSUE TITLE
pHAL: code upstream

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2525]
This is to track all the work related upstream phal related GHE repos and openbmc/meta-ibm recipies.
Key repositories.
- pdbg
- ecmd-pdbg
- ipl
- pdata
- libekb-p10
- pub-ek
- guard

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Created upstream repos.

https://github.com/open-power/ipl
https://github.com/open-power/pdata
https://github.com/open-power/libekb_p10
https://github.com/open-power/pub-ekb
https://github.com/open-power/guard

**Comment by ojayanth** [comment]
https://github.com/open-power/pub-ekb -- Mirroring enabled .

**Comment by ojayanth** [comment]
ipl/pdata/libekb_p10/pub-ekb/guard code up-streaming completed.

BMC Recipe changes related to PR. https://github.ibm.com/openbmc/openbmc/pull/1119

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
