### ISSUE TITLE
GUI: toast messages

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#253]
The design team came up with new toasts:
![toast-error](https://user-images.githubusercontent.com/5455127/49877708-9f816780-fdeb-11e8-9114-ee6188b69599.PNG)
![toast-success](https://user-images.githubusercontent.com/5455127/49877710-9f816780-fdeb-11e8-82c0-f7e74fe7857a.PNG)

**Comment by rfrandse** [comment]
refresh
