### ISSUE TITLE
GUI : FED : UI Shell updates

### ISSUE THREAD

**Issue by ben-bacon** [ibm-openbmc/dev#2531]
## Overview
Updates to the UI shell to match some of the design system changes introduced elsewhere.

## Notes
- Added a "rule" to the left side of the sidebar to help increase comprehension and division of the product screen
- Updated text styles and colors in the sidebar, and a focus state
- Updated text styles and sizes in the top nav. Size of Nav bar has changed slightly as well.

  - You should be able to export the white OpenBMC logo from the [inspect screen](https://ibm.invisionapp.com/d/main#/console/15362203/319672724/inspect)

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36655

**Comment by derick-montague** [comment]
Did we add the border to the application navigation? Also, here are some screen shots....
<img width="572" alt="image" src="https://user-images.githubusercontent.com/1183515/94370841-e40cee80-00b7-11eb-9304-733d9d9bf975.png">

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/1183515/94370844-e96a3900-00b7-11eb-90ee-3939dc48d5dd.png">

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/1183515/94370849-eff8b080-00b7-11eb-9897-00e3f9d6252d.png">

**Comment by SurenNeware** [comment]
> Did we add the border to the application navigation? Also, here are some screen shots....
> <img alt="image" width="572" src="https://user-images.githubusercontent.com/1183515/94370841-e40cee80-00b7-11eb-9304-733d9d9bf975.png">
> 
> <img alt="image" width="1082" src="https://user-images.githubusercontent.com/1183515/94370844-e96a3900-00b7-11eb-90ee-3939dc48d5dd.png">
> 
> <img alt="image" width="1669" src="https://user-images.githubusercontent.com/1183515/94370849-eff8b080-00b7-11eb-9897-00e3f9d6252d.png">

![image](https://user-images.githubusercontent.com/42602609/95336035-c9afed80-08cd-11eb-87fe-db51f1644f6f.png)
I followed these given outline and kept similar hover and focus state for all the header elements. But not sure for brand or logo, the focus state not looks good when on focus border comes around.

**Comment by derick-montague** [comment]
It is required and it looks fine in your screenshot.
