### ISSUE TITLE
PFP::presence - Design JSON configuration for logging events and PELs for fans missing

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2532]
Determine a design to allow an optional configuration for logging events and PELs for fans missing. The configuration should be similar to how PDM is configured to log events for fans missing where a timer is configured to log the event when the fan has been missing after a period of time.

- [ ] Determine JSON format and location(additional JSON file or contained within current `config.json`)
- [ ] Design class structure based on the determined configuration details

**Comment by spinler** [comment]
Going to handle this in #2533
