### ISSUE TITLE
PFP::presence - Implement logging events and PELs for fans missing

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2533]
- [ ] Parse error logging JSON configuration
- [ ] Construct class structure to log events and/or log PELs as configured
- [ ] Start timer for configured amount of time to log events and/or PELs once expired

*Note: Implementation of event/PEL logging could be shared between the fan presence and fan monitoring apps (static shared lib possibly?

**Comment by spinler** [comment]
This was implemented in phosphor-fan-monitor.
