### ISSUE TITLE
PFP::monitor - Design JSON configuration for logging events and PELs for nonfunctional fans

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2534]
Determine a design to allow an optional configuration for logging events and PELs for nonfunctional fans. The configuration should be similar to how PDM is configured to log events for nonfunctiona fans where a timer is configured to log the event when the fan has been determined to be nonfunctional after a period of time.

- [ ] Determine JSON format and location(additional JSON file or contained within current config.json)
- [ ] Design class structure based on the determined configuration details

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/37083

**Comment by spinler** [comment]
This is complete.
