### ISSUE TITLE
PFP::monitor - Implement logging events and PELs for nonfunctional fans

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2535]
- [ ] Parse error logging JSON configuration
- [ ] Construct class structure to log events and/or log PELs as configured
- [ ] Start timer for configured amount of time to log events and/or PELs once expired

*Note: Implementation of event/PEL logging could be shared between the fan presence and fan monitoring apps (static shared lib possibly?

**Comment by spinler** [comment]
This is complete.
