### ISSUE TITLE
Redfish: Code Update

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#254]
Need to port our existing REST based interfaces for BMC and PNOR firmware update to new Redfish based api's.

**Comment by gtmills** [comment]
This also includes xyz/openbmc_project/software/action/DownloadViaTFTP and upload/image

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Added reference to https://github.com/ibm-openbmc/dev/issues/417 since it will be required to ensure non-UBI systems also have full Redfish code update support.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Removed the final 4 extra points from this epic. We will complete the existing stories here and call it good for the OpenBMC 2.7 release. I opened #654 to track any extra work we want to do for 2.8 since there's a lot of new updates coming to the UpdateService schema.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
9 of 9 Issues completed
24 of 24 Epic Points completed

**Comment by rfrandse** [comment]
refresh
