### ISSUE TITLE
GUI : FED : Update toast drop-shadow opacity

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2540]
## Overview
Create a sass variable to enable a consistent box-shadow for all elements requiring a drop shadow. Currently the only implementation is on toast notifications. Bump up out of box style opacity to 0.3. Currently is at `box-shadow: 0 0.25rem 0.75rem rgba(0, 0, 0, 0.1);`

This sass variable will eventually be reused for back to top button.

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by dixsie** [comment]
@yoshiemuranaka are the requirements just to 1) create the sass variable to use later and 2) change toast opacity to 0.3?

**Comment by yoshiemuranaka** [comment]
Yes @dixsie

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36656
