### ISSUE TITLE
GUI : FED : Add required fields to LDAP form

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2542]
## Overview
We currently do not indicate required fields on the LDAP page. On Angular we showed optional fields. We were waiting on design to determine a pattern for showing required fields in forms. Confirm with design the pattern for showing required and add to page. 

## Notes
- [ ] We are currently indicating required fields with an asterisk `*`  on the SSL certificates, Generate CSR form

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
- [ ] Add cURL commands

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshots

Angular
<img width="1127" alt="Screen Shot 2020-08-25 at 1 38 24 PM" src="https://user-images.githubusercontent.com/8097306/91225404-6e88b980-e6d8-11ea-95b1-1524da3065cc.png">

Vue
<img width="1262" alt="Screen Shot 2020-08-25 at 1 38 48 PM" src="https://user-images.githubusercontent.com/8097306/91225419-747e9a80-e6d8-11ea-8f50-4f80bb0fdd61.png">

**Comment by dixsie** [comment]
![Screen Shot 2020-09-08 at 2.57.35 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/e2035742-42d6-42d3-bd12-11bc852c3959)

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36307

**Comment by dixsie** [comment]
Based on feedback from the playback on 9/10  `optional` was added to generate CSR form and it was decided to display `optional` when there are more required fields than optional fields.

![Screen Shot 2020-09-21 at 9.10.29 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/415938be-6782-41f1-87bf-bef3dc0afe2f)


![Screen Shot 2020-09-21 at 9.10.41 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/9393ad71-eb00-452c-a9f2-b7bd34e84f08)
