### ISSUE TITLE
GUI : FED : Update relative paths to absolute paths in views

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#2543]
## Overview
- [ ] Update relative paths to absolute paths in all views (instead of `../../../` use `@/`) where appropriate

![Screen Shot 2020-08-26 at 1.33.20 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/dc3743bb-191c-49d9-a60c-ccc4c43ab9cb)

## Pages to update as of today (9/8/20)
- [ ] BmcToasts.vue
- [ ] AppHeader.vue
- [ ] Alert.vue
- [ ] AppLayout.vue
- [ ] ~api.js~ **_do not change_**
- [ ] GlobalStore.js
- [ ] SslCertificateStore.js
- [ ] AuthenticationStore.js
- [ ] DateTimeSettingsStore.js
- [ ] NetworkSettingsStore.js
- [ ] BootSettingStore.js
- [ ] ControlStore.js
- [ ] PowerControlStore.js
- [ ] VirtualMediaStore.js
- [ ] SensorsStore.js
- [ ] ServerLedStore.js
- [ ] ModalSettings.vue
- [ ] ModalUser.vue
- [ ] CsrCountryCodes.js
- [ ] ModalGenerateCsr.vue
- [ ] ModalUploadCertificate.vue
- [ ] RebootBmc.vue
- [ ] Login.vue
- [ ] Overview.vue
- [ ] Unauthorized.vue

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36986
