### ISSUE TITLE
GUARD: Primary processor Guard support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2547]

**Comment by RameshIyyar** [comment]
@ojayanth @rsnair The scope of this story, is it something to drop primary processor HWAS_STATE.functional check in phal side ?

**Comment by RameshIyyar** [comment]
Codes are in the review
https://github.com/open-power/ipl/pull/30

**Comment by RameshIyyar** [comment]
Merged the above PR
