### ISSUE TITLE
GUI : FED : Fix Local User Management privileges/groups

### ISSUE THREAD

**Issue by nicoleconser** [ibm-openbmc/dev#2550]
## SME
**BMC**: @joseph-reynolds 
**RAS**:
**PHYP**:

### Summary
Per Joseph Reynolds (8/28/20) — 
- The current privilege role table incorrectly shows all Access Points as being available to all privilege levels 
- Groups & privileges are independent — role groups (aka access points) should not appear in the table 
- An Admin-level user should be able to configure which other users can access which access points (IPMI/Redfish/SSH/WebUI) 

#### Questions 
- What should the default group(s) (IPMI/Redfish/SSH/WebUI) be for each privilege level, if any? 

#### Background
- [ ] TBD

#### End users
- [ ]  TBD

#### User Needs
- [ ] TBD

#### User Quotes
- [ ] TBD

### References
- [ ] Discovery doc folder
- [User Management Design Doc](https://github.com/openbmc/docs/blob/master/architecture/user-management.md) (from Joseph) 
- [User Management](https://www.youtube.com/watch?v=19s-JwLBhTY) (YouTube - OpenBMC Learning Series)

### User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

### Use Case(s)
- [ ] Add use case(s)

### Design Goals
- [ ] Goal 1
- [ ] Goal 2
- [ ] Goal 3

### InVision Prototype
- [ ] Iteration 0
- [ ] Iteration 1
- [ ] Iteration 2
- [ ] Iteation 3 (Final)

### Community
- [ ] Created design review story in webui-vue repo
- [ ] Sent email to community sharing the design review story

### UX Flow / Interaction Requirements
- [ ] Add new column and show Account type in the user table
- [ ] Add multi-select option for admin to set user's access in the new and edit user forms

### cURL Commands and Redfish Response
- Redfish end point: `/redfish/v1/AccountService/Accounts/<account>`
    - https://github.com/ibm-openbmc/dev/issues/2577#issuecomment-736864353
- [ ] Add Redfish Response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
@joseph-reynolds @mzipse - What is the priority on this? Does this also have some dynamic aspects to the changes required to accommodate the need?

**Comment by derick-montague** [comment]
This story will require revisiting user access design for adding and editing users and potentially removing the access points from the tables. 

![image](https://user-images.githubusercontent.com/1183515/93894204-17b0d880-fcb4-11ea-8263-5ac321d7ffb6.png)

**Comment by joseph-reynolds** [comment]
I posted more details to the blocking issue, #2577.

**Comment by derick-montague** [comment]
Redfish example of assigned privs:

```
{
"@odata.id": "/redfish/v1/AccountService/Roles/Administrator",
"@odata.type": "#Role.v1_2_2.Role",
"AssignedPrivileges": [
"Login",
"ConfigureManager",
"ConfigureUsers",
"ConfigureSelf",
"ConfigureComponents"
],
"Description": "Administrator User Role",
"Id": "Administrator",
"IsPredefined": true,
"Name": "User Role",
"OemPrivileges": [],
"RoleId": "Administrator"
}
```

**Comment by derick-montague** [comment]
> I posted more details to the blocking issue, #2577.

https://github.com/ibm-openbmc/dev/issues/2577#issuecomment-786294136
