### ISSUE TITLE
Pass service authorization credentials to PHYP

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#2552]
This story is to ensure there is a mechanism to pass the service agent's credentials along with a request invoke a PHYP macro.  This is known to PLDM development as **Resource Dump with authentication**.

- The setting for this is: the service agent is authenticated to the BMC and is performing an operation to invoke a PHYP macro.  [Is there already a function or story for that?]
- The credentials that need to passed into the request include the ACF (which can be copied from the BMC's file system) and the service account's password that goes with that ACF.
- The credentials are **optionally** provided:
   - Some PHYP macros require only BMC Operator or BMC Administrator level access.  PHYP will not require credentials for these operations.
   - Some PHYP macros require ServiceRep (aka celogin) access.  PHYP will validate the service rep's credentials for these requests, and will fail the request if not authorized.

Design sketch -- code running on the BMC:
- The input is: phyp macro and optionally the service account password.
- If the password is not provided, pass the macro into PHYP.
- If the password is provided, read the ACF from the BMC's file system and pass it into PHYP along with the password.
- The parameters to invoke the PLDM interface will be:
   - The usual parameters to describe which macro to invoke.
   - The service account password and the ACF (binary content, about 800 bytes), optionally provided.
- Handle error conditions.  Examples: What if a password was provided but there is no ACF?  What if PHYP returns an error code indicating unauthorized?

PHYP will then decide for itself if CELogin authorization is needed for the selected macro, and if the credentials (ACF+password) are acceptable.

**Comment by mzipse** [comment]
@sampmisr , I think ultimately this story belongs to the PLDM team but we still need to have a discussion in Dean's meeting.  For now, I'm going to assign to you and link it to your PLDM Epic.  Let me know if you have any concerns.

**Comment by jaypadath** [comment]
If an ACF is present, it will be in the BMC’s file system in file /etc/acf/service.acf.

**Comment by mzipse** [comment]
Work is complete.  Closing.
