### ISSUE TITLE
Redfish Configurable Session Timeout

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2555]
This story is to implement the configurable session timeout property of schema https://redfish.dmtf.org/schemas/v1/SessionService.v1_1_7.json.

**Comment by manojkiraneda** [comment]
The code is up for review in the following gerrit commit:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/36016

**Comment by manojkiraneda** [comment]
commit is merged.
