### ISSUE TITLE
VPD: Make System VPD Service set u-boot env vars to pick the right device tree

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#2556]
In order to support multiple device trees in the same BMC image (the end goal being to support multiple systems in the same image), the system VPD service needs to:

* Read the IM keyword from the system VPD (We already do this today)
* Maintain a map from the IM keyword to the system device tree u-boot environment variable value (The name and values of this variable are TBD).
* Read the u-boot environment variable that u-boot will use to load the right device tree.
* If the above variable is unset (very first boot/factory reset) *OR* if the variable we read is different than what we should be setting it to (case where the BMC was moved from one system to another):
    * Set the u-boot variable to the right value corresponding to the IM keyword we read.
    * Reboot the BMC
* Else (that is if the variable is at the expected value), we have booted from the right device tree and we can continue as usual.

**Comment by santoshpuranik** [comment]
Notes:
* Use an arbitrary name and value for the u-boot variables for now (until we get the right names to be used).
* To reboot the BMC, the following systemd D-Bus API can be used: https://www.freedesktop.org/wiki/Software/systemd/dbus/ (see Reboot)

**Comment by mzipse** [comment]
Already linked to a Multi config Epic so I just removed one of the other links.

**Comment by santoshpuranik** [comment]
This is all done.
