### ISSUE TITLE
Redfish: Implement SNMP Alerts/Traps

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#256]
Need to move `/xyz/openbmc_project/network/snmp/manager` to Redfish

/xyz/openbmc_project/network/snmp/manager was just SNMP Alerts/Traps. We need a replacement in Redfish.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Moving to OP950 since there is no client SNMP in Redfish. Will need to upstream.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
The latest Redfish release has SNMP.

**Comment by gtmills** [comment]
See https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2019.3.pdf

**Comment by gtmills** [comment]
SNMP is spread across multiple schemas: EventDestination, MangerAccount, and MangerNetworkProtocol

EventDestination = Allow destinations to receive events via SNMP trap. I believe this is how we will add a SNMP Manager. 
ManagerAccount = Provide configuration and credentials for accessing SNMP service. Not sure we need this.
![manager-account](https://user-images.githubusercontent.com/5455127/68889725-17829c80-06e3-11ea-9342-119b6b17c98e.PNG)

ManageNetworkProotocol = Enable and configure support for SNMP v1, v2, v3
(Currently, I believe we only support v2). We will want to fill these new properties out. 
![managerNetworkProtocol](https://user-images.githubusercontent.com/5455127/68889679-033e9f80-06e3-11ea-81d4-7fd6bd6c4f91.PNG)

**Comment by XiaochaoMa** [comment]
@gtmills 
 I found that snmp only has the function of creating a client in the machine. (through service search ) 
Are you sure ManagerAccount and ManageNetworkProotocol will be implemented by redfish?

**Comment by XiaochaoMa** [comment]
- [ ] bmcWeb: Add / redfish / v1 / EventService interface

**Comment by XiaochaoMa** [comment]
Add / redfish / v1 / EventService interface

- [ ] 

- [ ]

**Comment by XiaochaoMa** [comment]
- [ ] 1. BMCWeb:  Add /redfish/v1/EventService interface.

- [ ] 2.  BMCWeb: Add /redfish/v1/Manager/SNMP interface.

- [ ] 3. WebUI: Move /xyz/openbmc_project/network/snmp/manager from REST to Redfish

**Comment by XiaochaoMa** [comment]
Add EventService interface (not merge)
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/30574

**Comment by XiaochaoMa** [comment]
NetworkProtocol 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/30575

**Comment by gtmills** [comment]
@XiaochaoMa Any update here?

**Comment by XiaochaoMa** [comment]
Fix the Port number of SNMP
The port 161 is belong to snmp agent with the 162 is right here.
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/34186

**Comment by XiaochaoMa** [comment]
Another question：
In the bmcweb module now, the snmp settings are written into the D-bus tree.
But in AppaRao‘s implementation of event service, he use the redfish's list.
Now thay are talking about  "Redfish EventService Implementation " in the maillist, so I want to refer to and learn from their discussions.

**Comment by gtmills** [comment]
@ratagupt Can @XiaochaoMa base SNMP on Intel's event service implementation?

**Comment by derick-montague** [comment]
Is this `In Progress`?

**Comment by XiaochaoMa** [comment]
Ratan mentioned that adding snmp configuration in "networkprotrocol" is not in line with the status quo. So remove it.  https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/34186

**Comment by XiaochaoMa** [comment]
@derick-montague
Because of Apparao's plan, my original plan for the eventservice interface has been abandoned. The existing snmp configuration is stored in the Dbus list, and the mapping between the dbus interface and redfish-eventservice is still under discussion on the mailing list.
My level is not enough to participate in the discussion in the maillist. So now wait for the plan to be discussed.
If you think I affected the progress of the task, you can unassigned me.

**Comment by derick-montague** [comment]
@XiaochaoMa thank you.

@gtmills since discussion is still happening in the mail list, we won't be able to get it into Sprint 2020-16 that started today.

**Comment by gtmills** [comment]
@XiaochaoMa @ratagupt Most of EventService has been merged into bmcweb, I see 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/31735 is still outstanding. 

Can this SNMP work be done on top of what is already done for EventService or up for review?

**Comment by XiaochaoMa** [comment]
@gtmills 
I will restart with the EventService work that has now been completed.

**Comment by derick-montague** [comment]
Is this in progress and do we know how soon this might be ready so we can move forward with the SNMP GUI story?

**Comment by ChicagoDuan** [comment]
@gtmills Sorry, because of several reasons, I just took over this task. 
I read the comments above. I think the purpose of this task is to set/get/delete the SNMP configurations using Redfish, So what I should do is add the SNMP configurations to the EventDestination class (https://github.com/openbmc/bmcweb/blob/055806b30dd7621b5018247d6fb4ac370bbaa527/redfish-core/lib/event_service.hpp#L458).  Then dbus is called in the EventDestination class to set/get/delete the configurations of SNMP.
@gtmills Is it right ?

@derick-montague  I am working on it, I'll let you know if there's any progress.

**Comment by gtmills** [comment]
@ChicagoDuan Yes, that sounds like a good direction to me.

**Comment by gtmills** [comment]
@ChicagoDuan Can you address comments on the review? https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599

**Comment by ChicagoDuan** [comment]
> @ChicagoDuan Can you address comments on the review? https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599

@gtmills Yes, I am working on it and will submit patchset as soon as possible

**Comment by ChicagoDuan** [comment]
ref:  https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599
It seems that Edtanous has some different opinions about this function. I have asked him about it and I am waiting for his reply

**Comment by gtmills** [comment]
@ChicagoDuan Can you address the other comments, ignoring https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599/10//COMMIT_MSG#85 ?

**Comment by ChicagoDuan** [comment]
> @ChicagoDuan Can you address the other comments, ignoring https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599/10//COMMIT_MSG#85 ?

@gtmills  OK, I can. But I'm afraid Edtanous won't go along with that direction.
I saw your reply to Edtanous. I asked him about it the other day on Discord. He didn't think EventService subscriptions was the way to do that. So I am waiting for his advice.

**Comment by derick-montague** [comment]
@gtmills @ChicagoDuan - How long do we wait for advice before requesting again? :)

**Comment by derick-montague** [comment]
@gtmills is this going to be upstream or will the work for #1288 need to be done downstream?

**Comment by gtmills** [comment]
upstream. 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40169

**Comment by derick-montague** [comment]
I moved this to the Code Review pipleine since it is stuck in the Gerrit review process. It could possibly be in current sprint.

**Comment by gtmills** [comment]
Can we address comments on https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599 ?
I feel this is really close

**Comment by ChicagoDuan** [comment]
> Can we address comments on https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599 ?

Yes, I am working on this.

**Comment by lxwinspur** [comment]
> @ChicagoDuan I think https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599 needs reworked to use the new boost https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46874

Correct, we will push this patch again.

**Comment by ChicagoDuan** [comment]
> @ChicagoDuan Can you bring this in downstream? https://github.com/ibm-openbmc/bmcweb/tree/1020 We are reverting here: [ibm-openbmc/bmcweb#146](https://github.com/ibm-openbmc/bmcweb/pull/146)

Done. Please review it:  https://github.com/ibm-openbmc/bmcweb/pull/147

**Comment by gtmills** [comment]
Can merge conflicts on https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599 be addressed? 
Can we get a few reviews on it?

**Comment by ChicagoDuan** [comment]
> Can merge conflicts on https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599 be addressed?

Done.

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599  has comments and merge conflicts

**Comment by ChicagoDuan** [comment]
> https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599 has comments and merge conflicts

Done.

**Comment by ChicagoDuan** [comment]
> https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599 has comments and merge conflicts

Hi @gtmills , I have addressed all comments, please help review it, thanks.

**Comment by gtmills** [comment]
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/38599 is merging. Closing.
