### ISSUE TITLE
New PAM auth module to handle cert-based service login

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#2562]
A Linux-PAM authentication module is needed to validate the “service” account password with the hashed copy stored in the uploaded certificate (per #1830).  Its logic would be something like this:
1. If the user account != “service” then ignore this module and exit to the next module.
2. If an ACF is not present on the BMC, then deny the request and exit the module.
3. Validate the ACF certificate's signature with the production key (or the development key in some scenarios).  If validation fails, then deny.
4. Validate the certificate's copy of machine serial numbers with BMC's copy of the machine serial number.  If none match, then deny.  The special serial number "UNSET" in the ACF matches only when the BMC has an empty serial number: it is not a match all.  (The UNSET value applies only in manufacturing and extreme FRU replacement scenarios).
5. Validate the certificate's expiration date with the BMC UTC time.  If expired, then deny.
6. Get the user's password, hash it, and compare with the hash stored in the ACF.  If no match, then deny.
7. Approve the request.

**Comment by ratagupt** [comment]
I have unassigned myself from this story as @joseph-reynolds is working on this.

**Comment by joseph-reynolds** [comment]
This was created in a downstream repo: github.com/ibm-openbmc/ibm-acf

**Comment by mzipse** [comment]
Code is now in our downstream driver.

**Comment by mzipse** [comment]
Work is complete.  Closing.
