### ISSUE TITLE
PLDM: BIOS: HelpText and DisplayName

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2565]
Introduce HelpText and DisplayName fields in the PLDM BIOS JSONs. These should be parsed and passed to the D-Bus API that populates the BIOS table (https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/BIOSConfig/Manager.interface.yaml#L68). These fields have the same meaning as in the Redfish AttributeRegistry schema : https://redfish.dmtf.org/schemas/v1/AttributeRegistry.v1_3_3.json (they also have the same names in the Redfish schema).

**Comment by lxwinspur** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/36196

**Comment by mzipse** [comment]
@dkodihal @tomjoseph83 , looks like this commit is waiting for review for the past 3 weeks.  Can you take a look?  Thanks.

**Comment by dkodihal** [comment]
@mzipse this will be merged shortly (this week). While I've looked at the code, I wanted to merge it along with few other commits that were related to this and were work in progress. Same goes for #2566.
