### ISSUE TITLE
PLDM : BIOS: ReadOnly BIOS attributes

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2566]
Currently the PLDM code treats attribute that are defined in the BIOS JSONs, but without a d-bus section, as read-only. This should change, and instead the read-only status should be determined by a new ReadOnly field, which should be introduced in the JSON. Then the same should be passed to https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/BIOSConfig/Manager.interface.yaml#L66.

**Comment by lxwinspur** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/36170

**Comment by mzipse** [comment]
@dkodihal @tomjoseph83 , looks like this one also need review to make progress.
