### ISSUE TITLE
Use ordered_json in PEL code instead of fifo_map

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2568]
We were using the fifo_map header provided by the nlohmann JSON project to preserve JSON object ordering.  In version 3.9 of nlohmann::json, there will be a built in 'ordered_json' type that will do the same.  It would be nice to switch the code to use that and remove the dependency on fifo_map.hpp from configure.ac and from the recipe.

**Comment by spinler** [comment]
For this, one can just use nlohmann::ordered_json instead of the fifoJSON typedef, and all references to fifoJSON/fifoMap/fifo_map.hpp can be removed.

Can be tested by checking that peltool output matches what it was before.

**Comment by sumitk56** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/42251

**Comment by sumitk56** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/42445
