### ISSUE TITLE
Redfish: date-time

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#257]
Need to move /xyz/openbmc_project/time/ to Redfish

**Comment by gtmills** [comment]
https://redfish.dmtf.org/schemas/ManagerNetworkProtocol.v1_3_0.json has NTP. 
/redfish/v1/Managers/{ManagerId}/NetworkProtocol

**Comment by gtmills** [comment]
Not going to support /xyz/openbmc_project/time/owner in Redfish. 
Don't see a field for /xyz/openbmc_project/time/host. ComputerSystem and Bios don't have a dateTime field.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Assign to Vishwa.

**Comment by vishwabmc** [comment]
Time Manager has the concept of TimeOwners and they are ( BMC , HOST, SPLIT and BOTH ). To Facilitate this, TimeManager provides Bmc and Host D-Bus interfaces to deal with BMC and HostTimes respectively.

Inside Redfish Manager, we only have BMC.  So my current thinking is that this RedFish field would map to BMC time Get and Set `only`.  If the owner is *not* BMC and/or the NTP is enabled, then the `Set` operation would result in an error. 

On the Host: I will continue to look to see if it can be fit into any other schema

@mine260309

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
My current thinking is this: Please help provide your feedback

Since Manager is all about the BMC, we will care only for SetTime and GetTime for BMC target

 [ ] Get Time: Put hooks into https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/managers.hpp#L1201 with Dbus calls to `/xyz/openbmc_project/time/bmc` xyz.openbmc_project.Time.EpochTime Elapsed 

[ ] Set Time: Put hooks into https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/managers.hpp#L1201 with Dbus calls to `/xyz/openbmc_project/time/bmc` xyz.openbmc_project.Time.EpochTime Elapsed 

For Host, I am looking at posting this question in the forum.

**Comment by gtmills** [comment]
@vishwabmc There is a property in BIOS for Time. I think it should go there. 
redfish » v1 » Systems » 437XR1138R2 » BIOS on https://redfish.dmtf.org/redfish/mockups/v1/863

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
> @vishwabmc There is a property in BIOS for Time. I think it should go there.
> redfish » v1 » Systems » 437XR1138R2 » BIOS on https://redfish.dmtf.org/redfish/mockups/v1/863

@gtmills : The Time property within the @Redfish.Settings construct is actually meant to hold the time the (Bios) settings were last applied:
As quoted from:
https://redfish.dmtf.org/schemas/Settings.v1_2_1.json
```
"Time": {
                    "description": "Indicates the time the settings were applied.",
                    "format": "date-time",
                    "longDescription": "The value of this property shall indicate the time that the settings object was applied to the resource.",
                    "readonly": true,
                    "type": [
                        "string",
                        "null"
                    ]
                }
```
I can't find anything in standard redfish for the host time. Talking with @vishwabmc today, we were wondering if setting the host time is even a requirement for the BMC?

**Comment by gtmills** [comment]
@santoshpuranik I don't see a place in the Redfish Schema for host time.  For OP940, we said no OEM properties just mapping over the old API to the standard redfish APIs so let's just do the BMC time and NTP servers for this story. Thanks!

**Comment by santoshpuranik** [comment]
Thanks, @gtmills !

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/19571
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/19572

**Comment by santoshpuranik** [comment]
@gtmills : I have, with the commits noted above, added support to set the BMC's time. This will work as long as the time sync method isn't NTP *and* the time owner isn't host. As for setting the NTP servers and enablig/disabling NTP, @raviteja-b is handling that under https://github.com/ibm-openbmc/dev/issues/463

**Comment by santoshpuranik** [comment]
@gtmills : Also something to discuss based on my talks with @gkeishin . Until we get the Host time property in standard redfish and add a concept of time owner to it, what is our stand on how things behave when using redfish vs when using the existing REST APIs? Can we use a mix-and-match of both interfaces to get/modify properties?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
@santoshpuranik @gkeishin @gtmills HostTime is not to be used by Redfish. It's only for Inband IPMI as part of GET/SET_SEL_TIME command. For external world, what would make sense is the BMC time.

**Comment by santoshpuranik** [comment]
@vishwabmc : Yes, that is what we've implemented as a part of this issue. My question was why did we have the whole concept of time owner and REST APIs to set host time in the first place?

As for this story, I believe we can close it now that the commit is merged.

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
Closing this as the code is already merged. Please re-open if anyone disagrees.
