### ISSUE TITLE
GUI : FED : Update name of file of exported log files

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2572]
## Expected Behavior
When exporting the logs, the file is named `event_logs_YYY-MM-DD_HH-MM-SS.json`. The name with the timestamp should be formatted using the ISO date format and 24 hour time as we do through the application.

Example: `event_logs_2020-09-04_21-00-00.json`

## Actual Behavior
When exporting the logs, the file is named `Event logs.json`.

## Steps to Reproduce the Problem

  1. Go to event logs
  1. Select all events
  1. Click export from batch action menu
  1. Review file name of the file saved

## Specifications
  - Browser: N/A
  - Version: N/A

## Internal Bug Ticket
```
Problem:
Mostly when CE/PE deals with event logs file, it will be better if we have
"Export event log file named with bmc file name with date and time".  This will add value to anyone who is debugging or passing the data.

Currently it is exported with title export.json.
```
 https://w3.rchland.ibm.com/projects/bestquest/?defect=SW420240

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36293

**Comment by yoshiemuranaka** [comment]
@derick-montague the timestamp should be the current time (when the user clicks export) not the date/time associated with any particular log correct?

**Comment by derick-montague** [comment]
The `current date and time` is correct.
