### ISSUE TITLE
GUI : FED : Firmware - TFTP input label and helper text

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2573]
## Expected Behavior
~~The user will be alerted if the IP address entered into the TFTP IP Address field does not match the regular expression for a valid IPv4 address.~~

The user can enter either an IP Address or a FQDN for the path to the FW image to use for the update. The input `label` should indicate both IP address and FQDN can be used. When specifying an IP address or FQDN, a valid image should upload successfully.

## Actual Behavior
~~The field validation only validates that a value was added to the field.~~

The label only indicates to the user that the TFTP IP Address can be used. The TFTP process is not working, possibly due to an incorrect API call. [Slack conversation](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1599656643154100?thread_ts=1599584919.133600&cid=C0Q6TQP5Z)

> Seem like backend is not a problem. I can see that GUI is trying /redfish/v1/UpdateService  for TFTP code update. So seem like GUI need call  UpdateService.SimpleUpdate  to make it work.

![image](https://user-images.githubusercontent.com/1183515/92602366-ac0e4a80-f273-11ea-8724-21239dcc9f2f.png)

## Solution
- [ ] Update label to `TFTP server address`
- [ ] Add helper text that states: `IP address or FQDN`

## Steps to Reproduce the Problem

  1. Go to the firmware page
  1. Enter an invalid IP address into the TFTP IP address field
  1. Tab out of the field

## Specifications
  - Browser: All
  - Version: N/A

**Comment by derick-montague** [comment]
@anoo1 - We have a question about the input. Can the user add a FQDN or is it IP address only?

**Comment by derick-montague** [comment]
It's been determined that the user can also add a Fully Qualified Domain Name (FQDN). We need to test that functionality and if backend is working as expected, we need to update the label on the firmware page. Currently, the label states `TFTP IP Address` and does not mention that FQDN is also an option. 

There will not be validation for this field other than `required` if the user selects that option.

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37166
