### ISSUE TITLE
GUI : FED : Sensors - Update export file name

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2574]
## Expected Behavior
When exporting the logs, the file is named `event_logs_YYY-MM-DD_HH-MM-SS.json`. The name with the timestamp should be formatted using the ISO date format and 24 hour time as we do through the application.

Example: `sensors_2020-09-04_21-00-00.json`

## Actual Behavior
When exporting the logs, the file is named `Event logs.json`.

## Steps to Reproduce the Problem

  1. Go to event logs
  1. Select all events
  1. Click export from batch action menu
  1. Review file name of the file saved

## Specifications
  - Browser: N/A
  - Version: N/A

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36601
