### ISSUE TITLE
Implement AccountTypes to control which users can access specific interfaces: ipmi, ssh, etc

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#2577]
This story is to add BMC function so the BMC admin can authorize specific users to specific interfaces.  Specifically, a new Redfish REST API so the BMC admin can GET and PATCH a subset of [OpenBMC group-roles](https://github.com/openbmc/docs/blob/master/architecture/user-management.md#supported-group-roles).

This is needed for #2219 so the BMC admin can authorize a user to use the network IPMI interface.

See Redfish forum post https://redfishforum.com/thread/219/account-groups-property - thanks @ratagupt 
See work here https://github.com/DMTF/Redfish/issues/4189 (private to Redfish). 

The webui GUI user management page should be updated for this.  For example, after this is implemented, the interface each user is allowed to access should be shown, and the BMC admin should be able to add/remove specific user from specific group roles.

**Comment by derick-montague** [comment]
@joseph-reynolds - Is there an expectation from your view is that the user role table show each user opposed to the role?

**Comment by joseph-reynolds** [comment]
Once we get final direction from Redfish, I anticipate the work for this is:
1. Enhance BMCWeb to implement the Redfish ManagerAccount.AccountTypes property to GET/PATCH the list of  interfaces.

As far as I can tell, there is already phosphor-user-manager and D-Bus support to read/write the `UserGroups`:
- https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/User/Manager.interface.yaml
- https://github.com/openbmc/phosphor-user-manager/blob/master/users.hpp

**Comment by joseph-reynolds** [comment]
No.  It must show both.  The User's (a) Role and (b) which interfaces a user is allowed to access the BMC are orthogonal.  For example:

userid | Role | Allowed interfaces
------|------|------
admin | Administrator | redfish web ssh ipmi
backupadmin | Administrator | redfish web
xcatuser | Operator | redfish ipmi
tooluseraccess | Operator | redfish

(except please make this way prettier!)

**Comment by derick-montague** [comment]
This means that table will be dynamic coming from the API. Has there been any thought into how and if this needs to be translated?

**Comment by joseph-reynolds** [comment]
Correct, this will all be present from GET /redfish/v1/AccountService/Accounts/{accountname}.  Let's explore what needs to be translated.  The properties in the ManagerAccount type described in DSP2046 v1.4 (Redfish 2019.3) or later:
- RoleId - is a string
- AccountType - in an array of enum strings described under ManagerAccount definitions.AccountTypes.enumDescriptions 

The RoleId is defined in DSP0266 > Security details > Authorization > Privilege model.
The Roles seems to be defined solely by Redfish privileges.  Does the spec have a description of each role?  Does BMCWeb provide a "Description" property for each role?
Note also that Redfish allow OEM roles to be defined, for example, OemIBMServiceRepresentative.
The RoleId itself might be hard to translate.

The AccountTypes seem to be defined in DSP2046 > ManagerAccount > Property details > AccountTypes.
All of the AccountTypes enum values are defined by the Redfish spec in English.  I suppose you could claim they are not translatable on that basis.  Note there is a similar OEMAccountTypes property whose enum values are not defined by the Redfish spec.

My weak conclusion: All of the names (RoleId and AccountTypes) are defined by the Redfish spec in English and form part of the interoperability layer.  I mean, any Redfish service that has the "Operator" role behaves the same as any other service with that some role; and translating the roleId would be confusing.  I suppose you could claim they are not translatable.  The description of the name is translatable.  And the description of the AccountType enum values is translatable.

**Comment by joseph-reynolds** [comment]
Here is the design wrinkle carried over from https://github.com/ibm-openbmc/dev/issues/2219:
- When a user is granted access via the network IPMI interface (by adding "IPMI" to their AccountTypes), they must also change their password at the same time (so IPMI's copy of the password can be updated).  Note that having access via the IPMI interface means that user is subject to the 20 character password limit.  [To clarify: There are no similar restrictions or requirements to change the password when removing the user from IPMI access.  Just remove "IPMI" from their AccountType array and done!]

**Comment by joseph-reynolds** [comment]
Just to mention the obvious here: With this design it is possible for a BMC admin to lock themselves out by removing access to all of the BMC's interfaces.  They ought not to do that.

**Comment by joseph-reynolds** [comment]
Per clarification by OpenBMC Richard Thomaiyar as agreed in https://redfishforum.com/thread/219/account-groups-property
addressing the Sep 10 comment above:

Adding a user to the IPMI group and subsequently changing that user's password are separate operations.  That user will not be able to access the BMC via network IPMI until both operations are completed.

**Comment by joseph-reynolds** [comment]
This is partly implemented by GET URI `/redfish/v1/AccountService/Accounts/<account>` which returns a ManagerAccount that has an AccountTypes property.  This property is currently returned by the web server with a hard-coded value: `Redfish`.

We anticipate the Redfish spec to add enum values for "ssh" and "ipmi" per thread 219 above.  When that happens, we can enhance BMCWeb to map our D-bus user groups (read from "xyz.openbmc_project.User.Manager", "/xyz/openbmc_project/user") into Redfish values.

After this GET API is enhanced, the WebGUI will be able to articulate which users can access the BMC by which interface.

Here is what I understand about the enum values:
- OpenBMC has enum values: ssh, ipmi, redfish, web
- The `redfish` and `web` values are tied together.  That is, you either have both or neither.  Per agreement in https://redfishforum.com/thread/219/account-groups-property
- We (OpenBMC, OpenPOWER, IBM) have no use case to disable either `redfish` or `web` access.
- The OpenBMC `ipmi` value corresponds to the Redfish `IPMI` value.  
- The OpenBMC `ssh` value corresponds to two distinct Redfish values: `ManagerConsole` (as SSH access to the BMC's command shell), and `HostConsole` (as SSH access via port 2200 to the host console).  For POWER and OpenPOWER systems, these values are tied together (TODO: need reference).

The goal of this issue is to allow the BMC admin to add and remove the `ipmi` and `ssh` values for a user account.  To make that happen, we'll need to enhance BMCWeb so we can PATCH the AccountTypes property (and either specify or omit each IPMI, ManagerConsole, and HostConsole value).
When we have that, the WebGUI can allow a web user to update these settings.

**Comment by joseph-reynolds** [comment]
Note the Redfish spec DSP0266_1.12.0 extended the ManagerAccount AccountTypes property with new values in https://www.dmtf.org/sites/default/files/standards/documents/DSP2046_2020.4.pdf 

Given the new ManagerAccount.AccountTypes values, here is how to handle this for OpenBMC:
 - ipmi - Add or remove the "IPMI" value from the user's ManagerAccount.AccountTypes.
 - ssh - Add or remove the "ManagerConsole" value from the user's ManagerAccount.AccountTypes.  (The Redfish term "ManagerConsole" means SSH to the BMC's command shell.)
 - redfish & web - These correspond to the Redfish & WebUI ManagerAccount.AccountTypes values, however, we (IBM) do not want anyone to be able to disable this access, so we do not plan to implement them.  And if someone else implements them, they must remain present in the ManagerAccount.AccountTypes of each user account.

Note: See notes about the WebUI value here: https://redfishforum.com/thread/219/account-groups-property
I now understand the WebUI value is intended to control legacy WebUI applications, not Web applications that are built entirely on top of Redfish interfaces.  Given this, I believe OpenBMC should not have the WebUI value.  And if it does have the value, it should be tied to the `Redfish` AccountTypes value.

**Comment by joseph-reynolds** [comment]
Here is a design sketch to implement the "ipmi" and "ssh" pieces that I want.

Enhance BMCWeb ManagerAccount.AccountTypes.  Let's track this piece under https://github.com/openbmc/bmcweb/issues/64.  See the existing stub implementation here: https://github.com/openbmc/bmcweb/blob/0260d9d6b252d5fef81a51d4797e27a6893827f4/redfish-core/lib/account_service.hpp#L1613
Note that AccountTypes is currently static, set to "Redfish".  This enhancement is to add two new values:`ManagerConsole` and `IPMI`:
   - Redfish - should always be in the list of Account Types.  If the admin tries to remove this value, the operation shall fail. 
   - ManagerConsole - BMCWeb shall call phosphor-user-manager to read and modify this value.
   - IPMI - BMCWeb shall call phosphor-user-manager to read and modify this value.
The work to implement this in BMCWeb is:
   1. Enhance the ManagerAccount doGet method to get the values from D-Bus.
   2. Enhance the ManagerAccount doPatch method to set the values in D-Bus.

Here is how to translate between Redfish AccountTypes values and Phosphor-D-Bus UserGroups property values (https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/User/Attributes.interface.yaml):
- `ManagerConsole` - `ssh`
- `IPMI` - `ipmi`

Example flows are:
- GET /redfish/v1/AccountService/Accounts/someuser -- The doGet code already uses the D-Bus xyz.openbmc_project.User.Manager service to get the data.   It should populate the AccountTypes property from the D-Bus data (translating between D-Bus and Redfish as shown above).
- PATCH /redfish/v1/AccountService/Accounts/someuser.  The enhanced doPatch method will be able to patch the AccountTypes property (and it will translate the values from the patch request to D-Bus value as above) using the `updateUserProperties` method (which will take a new parameter for this purpose) which will make the request using D-Bus APIs.

**Comment by gtmills** [comment]
I really think we need this and https://github.com/ibm-openbmc/dev/issues/2219 for GA

**Comment by derick-montague** [comment]
> I really think we need this and #2219 for GA

Is there concern that the backend may not make GA?

**Comment by gtmills** [comment]
1. Add the “SSH”, "Redfish" “IPMI” values to GET
2. Add the  “SSH” “IPMI” values to PACTH 

Please try to do as much of this upstream as possible

**Comment by patelabhishek9893** [comment]
downstream:
https://github.com/ibm-openbmc/bmcweb/pull/270

upstream:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/50835
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/50965
