### ISSUE TITLE
GUI : FED :  Get Backup Image from "Links""SoftwareImages"

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2580]
## Overview
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35829 was the start of this but haven't been back 

This elimates a call and is less error prone since looking at the BMC object for the images.

**Comment by derick-montague** [comment]
@gtmills is this something you want a FED to pick up in a future sprint?

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37145
