### ISSUE TITLE
PFP::control - Add t-control based fan speed control on PCI card temp sensors from dbus

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2583]
For PCI cards that have a temp sensor made available on dbus, add the event action to change fan speeds based on the sensor value using a given t-control value for increases and decreases. No additional code should be required, this is configuration changes only.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50263
