### ISSUE TITLE
Create tool to display SRCs/callouts from message registry

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2588]
Need to go over all of our SRCs/PELs with ras/hw teams to ensure the callouts/priorities/action flags are appropriate.  Write a tool to pull power/thermal SRCs out of the message registry and display in one list.

May need to run on running system to pull appropriate CALLOUT_INVENTORY_PATH/CALLOUT_DEVICE_PATH frus from system.

**Comment by rfrandse** [comment]
tracking in jira
