### ISSUE TITLE
Implement "RestartCause" on the Host 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2589]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-host-ipmid/+/29962/4/chassishandler.cpp)

    "RestartCause": "xyz.openbmc_project.State.Host.RestartCause.Unknown"

Would need to drive into Redfish spec 

Andrew Geissler  4 minutes ago
Our systems don’t implement it (so default is always Unknown), but if we did, then it appears to have an IPMI API which would imply we’d want it in Redfish (i.e. https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-host-ipmid/+/29962/4/chassishandler.cpp)

Andrew Geissler  < 1 minute ago
I think we’d need to ask some customers on whether they see value in it. I think it’s useful, but not something critical. We’d need a design doc written up on how different services that drive host state changes would update this (so we’d probably need to do that).

**Comment by gtmills** [comment]
@geissonator Closing because I don't think we want in Redfish. Please reopen if this should still be open

**Comment by rfrandse** [comment]
tracking in jira
