### ISSUE TITLE
OCC Active API

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2590]
``` 
   "/org/open_power/control/occ0": {
      "OccActive": false,
```
Martha Broyles  < 1 minute ago
there are always questions out in the field wanting to know if system is at low frequency due to OCCs in safe mode (not active).

Some way to model this in standard Redfish? 
Redfish OEM ?
/ibm/v1/ ?

**Comment by gtmills** [comment]
So if we move OCC pass through REST api under ibm/v1 namespace #1758  is that good enough to satisfy this "are OCCs active" use case?

**Comment by gtmills** [comment]
We discussed doing this as a part of the throttling API we are proposing https://github.com/ibm-openbmc/dev/issues/958

**Comment by gtmills** [comment]
@derick-montague Do we have a story for displaying OCC Active on the GUI? I know this is something @marthabroyles asked for

**Comment by derick-montague** [comment]
> @derick-montague Do we have a story for displaying OCC Active on the GUI? I know this is something @marthabroyles asked for

I am not sure what `OCC Active` is.

**Comment by gtmills** [comment]
The On Chip Controller (OCC) is a co-processor that is embedded directly on the main processor die. The OCC is used to control the processor frequency, power consumption, and temperature in order to maximize performance and minimize energy usage.

OCC Active is a state of the OCC where it is enabling and functioning properly. An inactive OCC could be the reason your fans are running high or your performance is lagging (e.g. CPUs being throttled) 


https://openpowerfoundation.org/on-chip-controller-occ/
https://community.ibm.com/community/user/power/blogs/todd-j-rosedahl1/2020/06/17/overview-of-the-occ-for-power8

**Comment by rfrandse** [comment]
tracking in jira
