### ISSUE TITLE
PLDM: Support for IPv6 VMI

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2591]
The plan is to keep the IPv6 implementation on VMI to be very simple. The configuration applies for both the network interface. 
Adding some details.

- ipv6-link-local-addr  Host->BMC
- ipv6-static  - single IPv6 address BMC->Host
- ipv6- Stateful auto configuration supported - single IPv6 address Host->BMC
- ipv6- Stateless auto configuration not supported

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
