### ISSUE TITLE
PLDM: Support for Remote Attestation Daemon

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2592]

**Comment by mzipse** [comment]
Expect this to be a BIOS attribute.

**Comment by sampmisr** [comment]
@ratagupt

**Comment by nmuruli** [comment]
"pvm_rtad" ==> BIOS enum attr Already supported.. Closing this ISSUE
"displayName" : "Remote Trusted Attestation Daemon State"
"helpText" : "This option enables or disables the Remote Trusted Attestation Daemon for host firmware.",
