### ISSUE TITLE
Add serialization support for host dumps

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#2597]
Host dump are stored in the host not BMC, so the BMC dump way of restoring the dump after a service restart wont work. Need to add code to serialize the dbus properties and restore after a service restart.

**Comment by chiragsibm** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/47088 -> System dump serialization
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/47234 -> Resource dump serialization

**Comment by rfrandse** [comment]
tracking in jira
