### ISSUE TITLE
Design and implement d-bus interface to activate the signed images.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#26]
Design d-bus interface for activating signed image uploaded using REST interface. 
Create new repo for certificate management
Implementation of Certificate image Application, includes skeleton code for d-bus interface.
Add recipes to Install the certificate management application.

**Comment by ojayanth** [comment]
#146 used for certificate manager application  install related work.

**Comment by rfrandse** [comment]
Jayanth Othayoth [4 minutes ago]
@rfrandse Code is merged
