### ISSUE TITLE
Secure HTTP support for Eventing

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2603]
BMC acts as a HTTP client wrt to push style evening, This story to support the secure https support while sending the event out from the BMC.
Presently event is going out with the use of non secure HTTP.

**Comment by sunharis** [comment]
Implementation is at 
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/31735/

**Comment by sunharis** [comment]
Code pulled downstream.  We are not planning to re-work on the newly proposed design for the upstream merge, at-least until next GA
