### ISSUE TITLE
PFP::monitor - Use the number of failed tach sensors when marking a fan nonfunctional at startup

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2605]
As a follow-up to #1033, when marking a fan nonfunctional due to its tach sensors failing to be read from dbus, a check against the configured number of sensors that should result in the fan being marked as nonfunctional should be checked. This was something I missed on the design layout of #1033 but should just be a matter of calling `Fan::tooManySensorsNonfunctional()` prior to marking updating the fan to nonfunctional each time a fan tach sensor fails to be found on dbus.

**Comment by JolieKu** [comment]
I call `tooManySensorsNonfunctional()` before update fan to nonfunctional and test by witherspoon qemu.
My understanding of `tooManySensorsNonfunctional()` is if the functional of sensor is 0, then count by 1.  
But the `numFailed` is 0 after testing. I have confused is there anything I missed?

**Comment by msbarth** [comment]
That's likely since the sensor was never added to the list of sensors due to the exception being thrown so you probably need to copy the logic that the `tooManySensorsNonfunctional()` function does into the constructor. In that logic, you'll need to count against the number of `sensors` configured vs the number of `_sensors` created(since an exception would not create one) and compare that against the configured `_numSensorFailsForNonFunc` value if the fan should be marked nonfunc yet or not.

**Comment by JolieKu** [comment]
I have push code to gerrit 
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/37610

**Comment by msbarth** [comment]
Great, I'll have a look.

FYA, adding "Resolved by [gerrit change link]" will also automatically close out the issue after that commit you link to is merged.
i.e.)

Resolved by https://gerrit.openbmc-project.xyz/37610

**Comment by JolieKu** [comment]
Roger that!
