### ISSUE TITLE
GUI : FED : Add title attribute to mobile header actions

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2606]
## Overview
A previous story #2524  added the native title attribute and ARIA label to icon only buttons. We should also add them to the app header at the smallest breakpoint

## UX Flow / Interaction Requirements
- [ ] On the smallest screen layout, a user should be able to hover over the hamburger menu, refresh and avatar icons in the application header and see what the button action is
- [ ] Need to be more descriptive for title and ARIA label values
    - Hamburger: `Show navigation` or `Hide navigation`
    - Refresh: `Refresh application data`
    - Profile: `Show profile menu` or `Hide profile menu`

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Screenshots

![Screen Shot 2020-09-28 at 1.26.02 PM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/d6b00ac5-2923-4c1e-a107-adea180fed37)

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37319
