### ISSUE TITLE
GUI : FED : Fix height small layout header height

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2607]
## Overview
The header height is taller than the standard height on our small screen layout. This causes the hamburger icon to look off center when the mobile navigation is in view

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Screenshots

<img width="597" alt="Screen Shot 2020-09-28 at 1 28 55 PM" src="https://user-images.githubusercontent.com/8097306/94482854-c65e8880-018e-11eb-987d-abefb5883efb.png">
<img width="596" alt="Screen Shot 2020-09-28 at 1 28 47 PM" src="https://user-images.githubusercontent.com/8097306/94482860-ca8aa600-018e-11eb-9556-99c89512695a.png">

**Comment by derick-montague** [comment]
Check back on this story after we implement #2531

**Comment by yoshiemuranaka** [comment]
Fixed with #2531
