### ISSUE TITLE
eBMC LED Management :: Implement LocationIndicatorActive property for NVME  resource

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2608]
This will be Assembly

So, what will this do :

1/. Get the corresponding Inventory for this resource
2/. See if there is any Association by name "indicator_led_group".
3/. If so, read the Asserted property: ( GET )
Example: busctl get xyz.openbmc_project.LED.GroupManager <Data from step-2> xyz.openbmc_project.Led.Group Asserted
4/. For PATCH, set true or false depending on the input

**Comment by vishwabmc** [comment]
It is in storage.hpp ( "@odata.id": "/redfish/v1/Systems/system/Storage" )

**Comment by vishwabmc** [comment]
We need to key off of `Item.Drive` for enumerating these.  We can not implement the "Present/Functional" for NVMe drives, because they can not be reached from BMC. So the plan is to not implement Present/Functional for `Item.Drive`. The reason is that BMC does not care for those drives. And also, the LEDs are on Backplane and not on the Drive.

Still the implementation is in `storage.hpp`. If we get any feedback about containing this in `pcieslot`, we can consider then

**Comment by vishwabmc** [comment]
All that said, this story probably is a NO-OP since we anyway have #2090 and all of this would get covered there

**Comment by mzipse** [comment]
Closing.  Work is complete.
