### ISSUE TITLE
GUI : FED : LDAP settings save button shouldn't be disabled

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2609]
## Overview
The `Save settings` button on the LDAP page should always be enabled

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Screenshots
<img width="1215" alt="Screen Shot 2020-09-29 at 1 20 19 PM" src="https://user-images.githubusercontent.com/8097306/94611424-8fec4080-0256-11eb-8fa2-a409081e3cb0.png">

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37332
