### ISSUE TITLE
GUI : FED : Event Logs date filters on small viewports

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2610]
## Expected Behavior
Date picker icons do not overlap input placeholder text. When the viewport hits that breakpoint, the date pickers for the From date and To date should stack vertically.

## Actual Behavior
The inputs do not stack and the icon overlaps the placeholder text

## Steps to Reproduce the Problem

  1. Go to the Events Log page
  1. Change the viewport  size to 380px wide or smaller

## Screen capture
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/30b21dbb-d8a8-4b28-8c1a-9faaca68af7c)
  

## Specifications
  - Browser: All
  - Version:

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37064
