### ISSUE TITLE
GUI : FED : Update indicator LED redfish endpoint to match backend changes

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2611]
## Overview
Backend changes will require updates to frontend code. Currently the Server LED and the Overview page shows an `On/Off` toggle based on the `IndicatorLED` property. The frontend code should now check for the `LocationIndicatorActive` property at the same endpoint `/redfish/v1/Systems/system`

## cURL Commands
```
curl -k https://$bmc/redfish/v1/Systems/system
```

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Related issues
- **Blocked** by backend changes https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/36886

**Comment by derick-montague** [comment]
Blocked by Gerrit review. No GitHub story to associate.

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/36886 merged. This can be worked.

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38546
