### ISSUE TITLE
GUI : FED : Add hamburger menu label

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#2613]
## Overview
- [ ] The hamburger menu on smaller screen sizes does not have an associated label

## Requirements
- [ ] Add missing label

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by derick-montague** [comment]
Closing as duplicate of #2606
