### ISSUE TITLE
GUI : FED : Fix event logs pagination on small screen

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2617]
## Overview
Should fix the pagination (buttons and dropdown) layout on the Event logs page for XS bp

## Screenshots
![Screen Shot 2020-10-06 at 9.37.01 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/e5e5aa01-f3db-432d-98da-ee8949664066)

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37358
