### ISSUE TITLE
eBMC State Management - Redfish: support PoweringOn and PoweringOff states for chassis and system

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2619]
The Redfish PowerState defines the following:

"PowerState": {
            "enum": [
                "On",
                "Off",
                "PoweringOn",
                "PoweringOff"
            ]

OpenBMC code only support "On" and "Off" for the Chassis and Systems Redfish objects. It's been requested that we also support the PoweringOn and PoweringOff states. 

High level this would require the state-manager D-Bus objects support these new states and then bmcweb could utilize that. I don't see any obvious way to do this within bmcweb with what we have because of the independent nature of the D-Bus objects (you can power on the host, which powers on the chassis, and then power off the chassis which powers off the host).

**Comment by geissonator** [comment]
FYI @gtmills

**Comment by geissonator** [comment]
This was implemented via https://gerrit.openbmc-project.xyz/q/topic:%22host-transition%22+(status:open%20OR%20status:merged).

**Comment by gtmills** [comment]
Close this?

**Comment by geissonator** [comment]
> Close this?

I think the rule is it's in a released downstream driver before we close.

**Comment by geissonator** [comment]
The system support is in but we've decided we'd also like to add to the chassis. The following PDI commit is for this:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/39942

**Comment by mzipse** [comment]
Resolves by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/39942

**Comment by mzipse** [comment]
@geissonator I believe we can close this now.  Can you confirm?

**Comment by geissonator** [comment]
We do not have support in for the chassis here but that is not needed currently. HMC team only needed the system portion of this which is in and merged. I'll close this and create a separate one for chassis if the need ever arises.
