### ISSUE TITLE
Redfish: Chassis

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#262]
Need to get Chassis and all its properties into Redfish. Some properties are already there. 
/redfish/v1/Chassis/{ChassisId}

https://redfish.dmtf.org/schemas/Chassis.v1_8_0.json

**Comment by gtmills** [comment]
Need to look for the chassis interface, https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/16586/ 
Need to create the chassis interface.

**Comment by gtmills** [comment]
Also Chassis PowerState, https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/chassis.hpp#L151 should look at:

 ```     "CurrentPowerState": "xyz.openbmc_project.State.Chassis.PowerState.Off", ```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18431/ fixes Chassis PowerState, https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/chassis.hpp#L151 should look at:
` "CurrentPowerState": "xyz.openbmc_project.State.Chassis.PowerState.Off",`
[openbmc/bmcweb#27](https://github.com/openbmc/bmcweb/issues/27)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
VPD is under /redfish/v1/Chassis/motherboard, Powerstate is under all the chassis. 
Although one day we might move to 1 chassis, this is good enough for now. Closing. 
```
curl -k https://${bmc}/redfish/v1/Chassis/motherboard
{
  "@odata.context": "/redfish/v1/$metadata#Chassis.Chassis",
  "@odata.id": "/redfish/v1/Chassis/motherboard",
  "@odata.type": "#Chassis.v1_4_0.Chassis",
  "ChassisType": "RackMount",
  "Id": "motherboard",
  "Links": {
    "ComputerSystems": [
      {
        "@odata.id": "/redfish/v1/Systems/system"
      }
    ],
    "ManagedBy": [
      {
        "@odata.id": "/redfish/v1/Managers/bmc"
      }
    ]
  },
  "Manufacturer": "IPS             ",
  "Model": "",
  "Name": "motherboard",
  "PartNumber": "00VK621         ",
  "Power": {
    "@odata.id": "/redfish/v1/Chassis/motherboard/Power"
  },
  "PowerState": "Off",
  "SerialNumber": "YL10UF78K00B    ",
  "Status": {
    "Health": "OK",
    "State": "StandbyOffline"
  },
  "Thermal": {
    "@odata.id": "/redfish/v1/Chassis/motherboard/Thermal"
```
