### ISSUE TITLE
PLDM: Process PCIe config information sent down by host firmware

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#2625]
- Define a PLDM model (mostly will be OEM FRU) to depict PCIe config info
- Retrieve such records from the host firmware as part of PDR/FRU exchange
- The pldm daemon should host the information on D-Bus. Should be able to use the same/similar D-Bus interface as peci-pcie; might need to define that interface in phosphor-dbus-interfaces.

**Comment by mzipse** [comment]
Work is complete.  Closing.
