### ISSUE TITLE
Update the dump create to return object path instead of dump id

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#2627]
create dump method should return dump object path instead of a dump id

**Comment by ojayanth** [comment]
This issue used to implement back-end for new  d-bus interface. 

Reducing complexity 7->5

**Comment by dhruvibm** [comment]
Change is in master
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/37792
