### ISSUE TITLE
Populating the unpopulated list of variables in the gendumpheader script

### ISSUE THREAD

**Issue by chiragsibm** [ibm-openbmc/dev#2629]
Need to populate the fields in gendumpheader script in phosphor-debug-collector repo.

Fields are listed below:-
1.BCD time stamp
2.Dump requestor
3.Dump requestor user interface ID
4.Dump Requester user ID
5.Number of Dump Entry

**Comment by rsnair** [comment]
Closing this as its completed

**Comment by rsnair** [comment]
@chiragsibm Please update the commit link
