### ISSUE TITLE
GUI : Research : Factory Configuration - Back up and Restore

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2633]
## SME
**BMC**: @anoo1 
**RAS**:
**PHYP**:

## Summary
- Back up & Restore Host / Server Configuration --> need to confirm value to customers (if low, don't include in GUI)
- Back up & Restore BMC Configuration --> need to confirm value to customers (if low, don't include in GUI)

### Background
- [ ] TBD

### End users
- [ ]  TBD

### User Needs
- [ ] TBD

### User Quotes
- [ ] TBD

## User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

## References
- [ ] eBMC Feature Item <add number>
- [ ] Link to Discovery folder
- [Early InVision Prototype (WIP)](https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319095312_01-Backup-Restore__backup-01)
- [Design Discussion](https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/18163/1/designs/backup-and-restore.md)
- [Design Document](https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/18163/)

**Comment by rfrandse** [comment]
tracking in jira
