### ISSUE TITLE
phosphor-regulators: Enhance JSON config file parser to convert relative inventory paths to absolute form

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#2635]
The JSON config file contains relative inventory paths, like `system/chassis/vdd_vrm`.  These need to be converted to absolute inventory paths, like `/xyz/openbmc_project/inventory/system/chassis/vdd_vrm` when logging errors, checking for presence, etc.

Currently this path conversion is occurring in the error logging code.  However, the same conversion is required in other places.  To simplify the code and design, the JSON config file parser should immediately convert the relative inventory paths to absolute format.

This enhancement will require the following changes:
* Enhance the JSON config file parser to convert relative paths to absolute format
* Update associated JSON config file parser testcases
* Update other (non-parser) testcases affected by this change
* Remove the support in the error logging code to convert inventory paths to absolute format, since they will already be in absolute format.

**Comment by bobkingkkp** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/37353
