### ISSUE TITLE
eBMC LED Management :: Turn on/off the [State.Decorator.OperationalStatus Functional]

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2636]
We need to express the health to [Critical] whenever the Fault_Led is turned on/off

When Fault LED Asserted is [triue] : set xyz.openbmc_project.State.Decorator.OperationalStatus Functional to [true]
When Fault LED Asserted is [false] : set xyz.openbmc_project.State.Decorator.OperationalStatus Functional to [false]

In Group::asserted(bool value)

- Check if it has "fru_fault" association
- If so, make a mapper call to know the service hosting that D-Bus object
- Make a call to set xyz.openbmc_project.State.Decorator.OperationalStatus Functional accordingly.

if there is no "fru_fault" association; do what is being done today.

**Comment by lxwinspur** [comment]
For setting the OperationalStatus property value,
it should be the following:
```
When Fault LED the Asserted property is [true], set xyz.openbmc_project.State.Decorator.OperationalStatus Functional to [false]
When Fault LED the Asserted property is [false], set xyz.openbmc_project.State.Decorator.OperationalStatus Functional to [true]
```

**Comment by lxwinspur** [comment]
review by:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-led-manager/+/37312

**Comment by vishwabmc** [comment]
This is merged
