### ISSUE TITLE
pldm oem: validate marker LID before starting inband code update

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2637]
create a new lid type MARKER_LID  with value 7. Upon receiving write request for this lid, the file will be written to staging dir and a codeupdate api will be called to validate the lid

create a sensor PDR with state set id 15 and entity system firmware (31, plus logical bit should be set). based on the return value of the code update api, the sensor state is updated. The value is returned when Phyp does a getStateSensorStateReadings for the sensor before issuing startUpdate

open Q: when to call the code update api? how to know whether writing the marker lid is complete?

**Comment by JoanRies** [comment]
_The value is returned when Phyp does a getStateSensorStateReadings for the sensor before issuing startUpdate_
Phyp doesn't know when the validation is complete.  BMC should send a PlatformEventMessage with event type PLDM_EVENT_TYPE_SENSOR_EVENT=0, sensor event class PLDM_SENSOR_EVENT_CLASS_STATE_SENSOR_STATE=1, and the new sensor state.  That is how we designed/implemented the PLDM_OEM_IBM_ENTITY_FIRMWARE_UPDATE=24577 sensor.

**Comment by sampmisr** [comment]
create state sensor PDR for marker lid validation: 

We need to pass back a value to the OS and these are the values that we use today
// masks for update verification results
#define CUPD_ENTITLEMENT_FAIL       0x0001
#define CUPD_BANNED_PLATFORM_FAIL   0x0002
#define CUPD_MIN_MIF_FAIL           0x0004

and also all the masks could be set at a time. and there is a possibility of new masks getting added in future.
PLDM needs to send a platformEventMessage for the new state of the sensor(validity of marker LID) 

new OEM state set id:  32770:  verification state 
0: valid
1: entitlement fail
2: banned platform fail
4: min mif fail

**Comment by JoanRies** [comment]
The marker lid validation sensor will use entity type PLDM_OEM_IBM_ENTITY_FIRMWARE_UPDATE=24577

**Comment by sampmisr** [comment]
Currently pldm always sends success for marker lid validation. Need an api from code-update app to do the validation process

**Comment by sampmisr** [comment]
@anoo1 Pls let us know when you are planning to take this up. We can also make the change accordingly

**Comment by nmuruli** [comment]
Updates from @anoo1 , 

We are okau as of now the PLDM to always sends success for the Marker lid validation . The API is planned for 3Q since it’s tied to entitlement validation, @anoo1 for now things that she can take care of PLDM changes to call the validation API ...

**Comment by nmuruli** [comment]
@anoo1 for now thinks that she can take care of PLDM changes to call the validation API -- Making her the owner

**Comment by anoo1** [comment]
Moving milestone to match the Entitlement Epic.

**Comment by rfrandse** [comment]
tracking in jira
