### ISSUE TITLE
Updating error log fields in dump header

### ISSUE THREAD

**Issue by chiragsibm** [ibm-openbmc/dev#2639]
Need to create an error log whenever the dump is created and same should be updated in the dump header as well.

Fields which need to be populated are:
1.PLID
2.SRC size
3.SRC dump

**Comment by ojayanth** [comment]
@chiragsibm please include gerrit link

**Comment by rsnair** [comment]
PLID is needed for associating dumps. SRC details are not critical and can be deferred to GA2

**Comment by rsnair** [comment]
Reducing the SP to reflect the pending work

**Comment by spinler** [comment]
@rsnair Can you refresh my memory, is it just the SRC ascii string and the 9 hex words needed here, or is it the whole SRC section, which would include callouts if there are any?

**Comment by rfrandse** [comment]
tracking in jira
