### ISSUE TITLE
MCTP Design and Prototype Implementation

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#264]
See this email thread for details: https://lists.ozlabs.org/pipermail/openbmc/2018-December/014269.html

This epic tracks all work to get MCTP incorporated into OpenBMC:
- Agreement with community on design
- Agreement with OPAL team on common library
- Implementation of common library between OpenBMC and OPAL
- Incorporation of new library and any required services/application to OpenBMC

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by amboar** [comment]
Another dot-point worth having here is the kernel implementation

**Comment by rfrandse** [comment]
refresh

**Comment by amboar** [comment]
I've created an epic for the kernel portion in #620

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Closing this Epic for the prototype.  The MCTP Kernel work will be tracked in the #620 Epic.
