### ISSUE TITLE
PLDM: Send firmware version to Hostboot

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2640]
This story is to meet the requirement of Hostboot to know about the firmware version. The plan is to use the Version(Field type number 10) in the General FRU record (DSP0257). The General FRU record for the logical FRU   `{"xyz.openbmc_project.Inventory.Item.System", 11521},` can hold this firmware revision.

**Comment by Pavithrab7** [comment]
Resolved here - https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/37731
