### ISSUE TITLE
PLDM Design and Implementation

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#265]
See this email thread for details: https://lists.ozlabs.org/pipermail/openbmc/2018-December/014356.html

This epic tracks all work to get MCTP incorporated into OpenBMC:
- Agreement with community on design
- Initial definition of commands required to boot IBM system
- Full command set required to boot IBM systems
- Agreement and upstreaming to DMTF of any enhancement required for us
- Agreement with OPAL team on common library
- Implementation of common library between OpenBMC and OPAL
- Incorporation of new library and any required services/application to OpenBMC
- OpenBMC use of new library for PCI and OpenCAPI communication

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
@PriyangaRamasamy please implement the encode/decode with the BMC as the PLDM requester.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
