### ISSUE TITLE
GUI : FED : Back to top button

### ISSUE THREAD

**Issue by ParishrutB** [ibm-openbmc/dev#2651]
## Overview
Add a Back to Top button to pages longer than 3 screens (depending on the viewport height). 

## Interaction requirements

- [ ] It will be a sticky button. 
- [ ] For viewport width <1366 px, button will stay close the screen's edge, 24 px apart. (It can overlap the content if the viewport size reduces).
- [ ] For viewport width >1366 px, button will stay close the content 's edge, 24 px apart. 
- [ ] It will be shown if both of the following is true: user is on the 4th screen AND scrolls up. 
- [ ] Once it is shown, it disappears if: user starts scrolling down OR has scrolled up to the 2nd screen. 
- [ ] Attribute: "Back to top"

## Resources
- Box doc: https://ibm.ent.box.com/notes/709414056247
- Wireframe: https://ibm.box.com/s/a8uy5u8p50tt1oe0cduevpsako49z6fd

## Final Invision Mockup
https://ibm.invisionapp.com/d/main#/console/15366263/319742283/preview

## Screenshots

Width <1366 px
![image](https://user-images.githubusercontent.com/61419136/96116061-82e17980-0f05-11eb-9c89-4ea9bbe51776.png)
![image](https://user-images.githubusercontent.com/61419136/96116075-87a62d80-0f05-11eb-9855-2c5f3029517d.png)

Width >1366 px
![image](https://user-images.githubusercontent.com/61419136/96115728-09e22200-0f05-11eb-87fa-db4111dcd642.png)

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by dixsie** [comment]
resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38284
