### ISSUE TITLE
phosphor-regulators: Add Services to ActionEnvironment

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#2666]
**Overview**

The ActionEnvironment class should be enhanced to provide access to a Services object.

The Services class will soon be enhanced to provide the following:
* Presence information (whether a hardware FRU is present)
* VPD information (keyword values)

There are currently two actions that will need access to the Services object:
* compare_presence
* compare_vpd

An ActionEnvironment is passed to every action's execute() method, giving the action access to Services.

**Required Changes**

* Add a third parameter to the ActionEnvironment constructor: `Services& services`
* Add a new method to the ActionEnvironment class: `Services& getServices()`
* Add a new data member to the ActionEnvironment class:  `Services& services`
* Update the ActionEnvironment test cases as needed, including tests for the new getServices() method.
* Update classes that create an ActionEnvironment to specify the new third constructor parameter.  They should already have access to a Services&.  For example, Configuration::execute() creates an ActionEnvironment, and this method has a Services& as in input parameter.
* Update all affected testcases that create an ActionEnvironment.  Pass a MockServices object to the ActionEnvironment constructor within testcases.

**Comment by bobkingkkp** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/37614
