### ISSUE TITLE
VPD: CM: Single FRU VPD Collection

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#2672]
For the concurrent maintenance function, we need an external interface that an enable the VPD for a single FRU to be collected.

This epic involves:
* Defining a D-Bus interface that can be used to collect VPD of a single FRU (ex. PLDM can use this when in-band CM is performed).
* Implementing this interface in the VPD manager.
* Any BMCweb changes to invoke this interface?

**Comment by santoshpuranik** [comment]
This epic is meant to cover the following FRUs:
* PCIe cable cards for all systems.
* Op-panel and RTC battery for Everest.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
This one is delivered in the Rainier GA.
