### ISSUE TITLE
PLDM: Add tracing when the BMC PLDM daemon issues GetPDR to host

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2673]
There is no tracing in the GetPDR flow when the BMC reads the PDRs from the host. Need to add tracing for request/response if the verbosity is turned on.

https://github.com/openbmc/pldm/blob/master/host-bmc/host_pdr_handler.cpp#L101

**Comment by SrideviRamesh** [comment]
Done and merged the code
