### ISSUE TITLE
pdata: Sync HB forked process mrw script

### ISSUE THREAD

**Issue by RameshIyyar** [ibm-openbmc/dev#2677]
Currently pdata using copied hb processMrw.pl and Target.pm scripts to process and get required targets and attributes data from system MRW xml but due to using copied scripts if some changes made in MRW xml or those scripts in HB side then pdata missing updated scripts and throwing error during build time or ipling when using latest system mrw xml. 

Approach: 
-  Auto mirror as like pub-ekb for required scripts 
or 
-  Pull only required scripts from hostboot repo during build time (standalone or op-build or openbmc (if required)) - [git sprase checkout](https://git-scm.com/docs/git-sparse-checkout#_sparse_checkout)

**Comment by rfrandse** [comment]
tracking in jira
