### ISSUE TITLE
pdata: Version info in attribute tool and power cec device tree

### ISSUE THREAD

**Issue by RameshIyyar** [ibm-openbmc/dev#2679]
Add version info in attribute tool and device tree to get know missing attribute info while debugging 

Approach:

**Device tree:**
- Add new attribute `ATTR_DEV_TREE_VERSION` as string type into device tree
  - Value can be filled by using `git commit head` during build time

**Attribute tool**
- Add `--version` flag with `git commit head` during build time.

So, We can get to know if the attribute is missed or not while using the power cec device tree.
 - It will be nice to give missing attribute details during the `export`  device tree by using the attribute tool.

**Comment by rfrandse** [comment]
tracking in jira
