### ISSUE TITLE
GUI : FED : Update data option for components using Mixin data

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2683]
## Overview
The Mixin merge behavior for the data option has changed. If a component is relying on a data property defined in a Mixin, it will also need to be defined explicitly on the parent component. The recommended migration strategy is extract the shared properties into an external object

https://v3.vuejs.org/guide/migration/data-option.html#mixin-merge-behavior-change

## Notes
- [ ] This is a breaking change currently listed under [Other Minor Changes](https://v3.vuejs.org/guide/migration/introduction.html#other-minor-changes) in the migration guide. These changes can be made before migrating to Vue 3

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37699
