### ISSUE TITLE
GUI : FED : Add new transition class names 

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2684]
## Overview
The transition class names are being updated. We are currently relying on classes associated with the `<transition>` component for the mobile nav, loading bar and table toolbar. We can add the new classes in addition to the current Vue 2 syntax and remove them after switching to Vue 3

https://v3.vuejs.org/guide/migration/transition.html#overview

## Notes

- This is a breaking change currently listed under [Other Minor Changes](https://v3.vuejs.org/guide/migration/introduction.html#other-minor-changes) in the migration guide. These changes can be made before migrating to Vue 3
- Be sure to comment on the reason we will have duplicate class names.

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38094
