### ISSUE TITLE
GUI : FED : Remove global filter registration

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2685]
## Overview
Filters api is removed. Replace our globally registered date filters
https://v3.vuejs.org/guide/migration/filters.html#global-filters

## Notes
- This is a breaking change currently listed under[ Removed APIs](https://v3.vuejs.org/guide/migration/introduction.html#removed-apis) in the migration guide.

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by rfrandse** [comment]
tracking in jira
