### ISSUE TITLE
GUI : FED : Update "this" reference in component props

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2686]
## Overview
Props default `this` reference will not be available. Currently only referenced in [Search.vue](https://github.com/openbmc/webui-vue/blob/master/src/components/Global/Search.vue#L47) component 

https://v3.vuejs.org/guide/migration/props-default-this.html

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by rfrandse** [comment]
tracking in jira
