### ISSUE TITLE
GUI : FED : Button - Align button icons

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2694]
## Overview
The buttons that contain icons have a slightly larger height and the icon itself is not aligned correctly in all situations. The icon should always be centered with the text (if there is text) or within the button container.

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
- [x] Use `display: inline-flex` declaration for buttons. Currently using `inline-block`
- [x] Add the `align-items: center` declaration to buttons
- [ ] Remove the use of the `vertical-align` property if set in our custom buttons SCSS

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Test the button alignment on all pages
-  ~~Verified functionality works as expected, e.g. success and failure use cases~~
-  ~~Resolved any JavaScript errors thrown to the console~~

### Accessibility Tests
N/A

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37675

**Comment by derick-montague** [comment]
It was decided the best way to resolve layout issue and the need for consistency and quality was to create a new button component that supports with and without icons since that type of component was not provided by the Bootstrap-vue framework.
