### ISSUE TITLE
eBMC - u-boot, kernel panic, watchdog config, and flash side switch support

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2697]
An epic to track the error handling, failure data collection, and recovery around u-boot and kernel failures. Also tracks how we utilize the BMC hardware watchdogs and when/if we automatically change the flash sides in these error scenarios.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
