### ISSUE TITLE
GUI : FED : Documentation -Tables

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2698]
## Overview
Add a components page for tables. This page should show the user how to use the a bootstrap-vue table with all the table mixins and custom components. 

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
N/A

### Accessibility Tests
N/A

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37955

**Comment by derick-montague** [comment]
The base and the sort have been merged.
