### ISSUE TITLE
API definition for PLDM over MCTP binding

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#270]
PLDM has a binding spec over MCTP. The goal of this story is to map that to implementable APIs. This also involves understanding the APIs offered by the MCTP library being designed for OpenBMC.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@dkodihal - The BMC roadmap shows that PLDM over MCTP requires GUI work. Can you verify if that is accurate?

**Comment by dkodihal** [comment]
@derick-montague I don't think the fact that we might switch from IPMI or some proprietary protocol to PLDM by itself causes GUI work, however existing GUI requirements still apply. For example : FRU inventory information has to be displayed in the GUI irrespective of the fact that some of the inventory information might be made available to the BMC via the host, and that communication can be over IPMI or PLDM.

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
This will be done by libmctp.

**Comment by mzipse** [comment]
refresh
