### ISSUE TITLE
GUI : FED : Quick Start - Forms

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2702]
## Overview
Add a page for helping a user create a basic form. This should help them understand how to use the:
- bootstrap-vue form
- bootstrap-vue form group
- vuelidate plugin for client-side validation
- various bootstrap-vue form elements

The user should be able to:
- Find more information about the bootstrap-vue form components (link to the page)
- Easily create their first form using the template provided on this page
- 

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
N/A

### Accessibility Tests
N/A

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/41538
