### ISSUE TITLE
GUI : FED : Components - Status Icon

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2703]
## Overview
Add a components page for the status icon component. This page should show the user how and when to use the status icon component. 

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
N/A

### Accessibility Tests
N/A

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38225
