### ISSUE TITLE
GUI : FED : Component - Page Section

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2704]
## Overview
Add a components page for the page section component. This page should show the user how to use the page section component. 

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
N/A

### Accessibility Tests
N/A

**Comment by derick-montague** [comment]
@dixsie - I was testing some issues with undefined SCSS variables and used this as a test case. I have some of this work done in [this gerrit review marked as wip](https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38115)

**Comment by dixsie** [comment]
resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38265
