### ISSUE TITLE
GUI : FED : Components - Page title

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2705]
## Overview
Add a components page for the page title component. This page should show the user how to use the page title component. 

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
N/A

### Accessibility Tests
N/A

**Comment by dixsie** [comment]
resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38265
