### ISSUE TITLE
IPMI SEL refactor : Part 2

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#271]
This part of the refactor will cater to add callout as part of creating the eSEL.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by tomjoseph83** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-openpower/+/17731/

**Comment by rfrandse** [comment]
refresh
