### ISSUE TITLE
 GUI : FED :  If "Delete All Event logs" is selected should delete via LogService.ClearLog 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2714]
## Overview
If a user deletes all the event logs we should make a call to /redfish/v1/Systems/system/LogServices/EventLog/Actions/LogService.ClearLog/" instead of deleting each individually

For details on the issue, [review the slack conversation](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1603336552434300)

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
- [ ] Add cURL commands

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by derick-montague** [comment]
@gtmills : `Method Not Allowed` is being returned from `redfish/v1/Systems/system/LogServices/EventLog/Actions/LogService.ClearLog/`

**Comment by Srisuk** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37730
