### ISSUE TITLE
GUI : FED : Add emits property for custom component events

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2718]
## Overview
Explicitly define custom emitted events. This is an optional enhancement

https://v3.vuejs.org/guide/component-custom-events.html#defining-custom-events

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by rfrandse** [comment]
tracking in jira
