### ISSUE TITLE
GUI : FED : Upgrade to Vue 3 migration bundle

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2719]
## Overview
[Migration docs](https://v3.vuejs.org/guide/migration/migration-build.html#overview)

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by derick-montague** [comment]
Still no date from vue on when this will be available. Hoping it will be done soon.

**Comment by rfrandse** [comment]
tracking in jira
