### ISSUE TITLE
MPIPL  Requirement analysis.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#272]
Identify the BMC changes required to  boot the system in MPIPL mode.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Issues created see the below issues for details on the investigation.
       https://github.com/ibm-openbmc/dev/issues/324
       https://github.com/ibm-openbmc/dev/issues/325
       https://github.com/ibm-openbmc/dev/issues/326
       https://github.com/ibm-openbmc/dev/issues/327
       https://github.com/ibm-openbmc/dev/issues/328
       https://github.com/ibm-openbmc/dev/issues/329

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
BMC side changes are tracked using Epic #777 . Closing this issue now
