### ISSUE TITLE
GUI : FED : Remove Virtual Media from IBM custom routing

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2724]
## Overview
Virtual media is not needed for IBM systems and should be removed from IBM's custom routing.

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
- [ ] Verify Virtual Media is not part of navigation when running an IBM build

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37674
