### ISSUE TITLE
GUI : FED : Import nextTick 

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2726]
## Overview
A few global APIs have been removed including nextTick() which is used in a few places in our app. This update may also affect unit testing setup. 

https://v3.vuejs.org/guide/migration/global-api-treeshaking.html#global-api-treeshaking

### Affected APIs
These global APIs in Vue 2.x are affected by this change:

- Vue.nextTick
- Vue.observable (replaced by Vue.reactive)
- Vue.version
- Vue.compile (only in full builds)
- Vue.set (only in compat builds)
- Vue.delete (only in compat builds)

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by rfrandse** [comment]
tracking in jira
