### ISSUE TITLE
GUI : FED : Remove unnecessary container elements

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2727]
## Overview
Fragments will allow multi-root components in SFCs. We have a few instances of wrapper `<div>`s that can be removed. 

- AppHeader
- AppNavigation
- TableRowGroup
- OverviewEvents
- OverviewNetworkSettings

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by rfrandse** [comment]
tracking in jira
