### ISSUE TITLE
GUI : FED : Move child :key value in v-for loop into wrapper <template>

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2728]
## Overview
For any `<template>` component using the v-for directive and with children elements using `:key` prop, move `:key` prop from child element to parent `<template>`

https://v3.vuejs.org/guide/migration/key-attribute.html#with-template-v-for

### With `<template v-for>`

In Vue 2.x, a `<template>` tag could not have a key. Instead, you could place the keys on each of its children.
Vue 2.x

```
<template v-for="item in list">
  <div :key="item.id">...</div>
  <span :key="item.id">...</span>
</template>
```

In Vue 3.x, the key should be placed on the `<template>` tag instead.
Vue 3.x

```
<template v-for="item in list" :key="item.id">
  <div>...</div>
  <span>...</span>
</template>
```

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by rfrandse** [comment]
tracking in jira
