### ISSUE TITLE
Fan Control: Design selectable "Fan Control Mode"

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#273]
System thermal differences that require alterations to the default set of the fan control parameters for the system need to have the ability for a user to select a different mode that is configured within fan control.

Example situation:
A fan floor speed at a certain ambient temp causes certain optical cables to overtemp from the heated exhaust air needing the floor speed to be higher to push more of this air over the cables to sufficiently cool them.

**Comment by msbarth** [comment]
- [ ] Create a "xyz.openbmc_project.Control.Thermal" interface with a "Mode" property that is a string with a default of "Default". This is the property that will allow users to switch fan control into a different mode other than the default provided for the system. (Some possible examples would be an acoustic mode or a high floor mode)

This mode would be hosted by the fan(thermal) control application, which would be configured to support modes other than "Default" that could be set by an end user when necessary. The mode value set needs to be persisted so the fan(thermal) control application is started using the altered mode definitions.

Altered mode configurations would be optionally defined within the control application's configuration for a system by the chosen support mode name. These mode names would be used by the application to validate an end users selection of what mode should be used and only altering the mode configuration when a valid mode is set.

Each mode configuration's change to the control application's actions would be defined at compile time for the action to be altered. This is where the altered action's parameters would be used when a mode other than "Default" is set. When an action contains no other mode definitions, the default action is used regardless of what mode is set.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/17287

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/17287 merged
