### ISSUE TITLE
GUI : FED : Local user management - User Privilege auto selecting in Safari

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2731]
## Expected Behavior
When adding a new user in the GUI, the user must select the user's privilege from the select menu. When the modal opens, the privilege select menu should be empty.

## Actual Behavior
When adding a new user in the GUI, the user must select the user's privilege from the select menu. When the modal opens, the privilege select menu auto selects Administrator. When the user submits the form to add the new user, the privilege select menu clears and is marked as a required field

## Steps to Reproduce the Problem

  1. Go to local user management
  1. Add a new user
  1. Submit the user user without changing the privilege select menu value

## Specifications
  - Browser: Safari (ONLY)
  - Version: N/A

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37867
