### ISSUE TITLE
Capacity on Demand Backend work

### ISSUE THREAD

**Issue by mzipse** [ibm-openbmc/dev#2736]
This will cover the work associated with COD.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Here are the summary for this epic.

The model consists of following main entities:1 - licenses - these objects represents the features.  There will be a license represnting 
feature(one is to one relation ship) and these objects have state - active, inactive, unknown, etc.
These objects could implement the Delete interface for when a client wishes to disable the license/feature.

2 - manager - the manager object (distinct from freedesktop object manager) provides a method
interface to create new license objects.


Flow would be as below with the proposed model -1/ Manager object would be having interface like upload (License activation key)
2/ On IBM systems we send this key to the host firmware which activates the features
3/ Host Firmware sends the activated feature list to the BMC
4/ BMC creates the licenses for the activated features.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by sunharis** [comment]
All stories are complete for FW1020 release
