### ISSUE TITLE
Fan Control: Add user exposed persisted "Fan Control Mode"

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#274]
Fan control should host the parameter(s) used in selecting a mode for fan control other than the default due to their specific system configuration. These mode(s) will be thermally characterized for the system and provided with a description of what the mode alters from the default set of fan control parameters.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
- [ ] Investigate what's needed within an application to serve a property on dbus
- [ ] Add bus name and object path(concat zone number) configuration parameters for fan control
- [ ] Construct each fan zone object's interfaces/properties and emit object added
       (before requesting the busname?)
- [ ] Determine if interface/property exposure on dbus is configurable (thru user defined zone yaml)
- [ ] TBD

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/17753/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/17753 merged
