### ISSUE TITLE
GUI : FED : CSRF Allow list

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2741]
## Overview
[Help Wanted story in webui-vue repo](https://github.com/openbmc/webui-vue/issues/29) to reach parity with phosphor-webui. The goal of this story is to:

- [x] Understand the value of a CSRF Allow list
- [x] Determine how it was supported in AngularJS and in [phosphor-webui](https://github.com/openbmc/phosphor-webui)
- [ ]  Determine how and if it is needed for the webui-vue repo
- [ ] If needed, document and implement the feature

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
N/A

### Accessibility Tests
N/A

**Comment by derick-montague** [comment]
Conversation about this feature and the expectation was discussed on discord and added to the webui-vue story.
https://github.com/openbmc/webui-vue/issues/29#issuecomment-738172687

**Comment by dixsie** [comment]
Resolved: Current xsrf cookie implementation protects against CSRF attacks. For added security and consistency accross different browsers we should add the set-cookie sameSite attribute to strict on the backend. Adding this attribute was tested with an image and no breaking changes were observed.
