### ISSUE TITLE
GUI : FED : Add SNMP Route

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2742]
## Overview
Currently, there is a navigational item for SNMP without a route. We need to add the route so that the page 404's until we have the SNMP traps page (parity) in place. 

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Verify clicking the SNMP page in the primary navigation directs the user to the 404 page.

### Accessibility Tests
N/A

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38207
