### ISSUE TITLE
GUI : FED : Component - Button Documentation

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2743]
## Overview
Document how to use buttons and icon-only button class.

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
N/A

### Accessibility Tests
N/A

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40895
