### ISSUE TITLE
Capture PSU STATUS_MFR_SPECIFIC value during analysis

### ISSUE THREAD

**Issue by bjwyman** [ibm-openbmc/dev#2744]
When reading the power supply STATUS_WORD during analysis, the power supply monitor should also capture the value returned from STATUS_MFR_SPECIFIC.

If a fault is indicated in the STATUS_WORD value returned, additional details, "Manufacturer Defined", could quite likely be indicated in the one byte value returned from STATUS_MFR_SPECIFIC.

If there is a fault indicated in STATUS_WORD, the STATUS_MFR_SPECIFIC value should be added to the error log additional data.

**Comment by jjaymeyer** [comment]
Resolved-by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/38651
