### ISSUE TITLE
GUI : FED : Adding LDAP group results in a 404, page not found error

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2745]
## Expected Behavior
When the user adds an LDAP group, a success toast is displayed.

## Actual Behavior
When the user adds an LDAP group, the user is redirected to a page not found page. The request is successful, however, the URL is updated with a `?` and the page displays a page not found message. The update is successful, but instead of the success toast, the user is redirected

## Steps to Reproduce the Problem

  1. Go to the LDAP page
  1.  Enter any necessary LDAP credential info needed to add an LDAP group
  1. Add an LDAP Group

## Screen Captures
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/74e95618-2a29-4a0e-b0d2-31bad334b9a3)

![image](https://user-images.githubusercontent.com/1183515/98188539-cb72ce00-1ed8-11eb-829c-f8a4f5780787.png)

## Specifications
  - Browser: All
  - Version:

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38618
