### ISSUE TITLE
PLDM: Initiate Resource Dump

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2746]
The Dump Manager will be creating a new D-Bus object when the resource dump is initiated from Redfish. PLDM daemon watches for the Interfaces added signal and sends a new FileAvailable to the PHYP for the Resource Dump Parameters. PHYP reads the Resource Dump parameters using File I/O and starts the Resource dump.

**Comment by sampmisr** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/40115

**Comment by sampmisr** [comment]
Code is merged
