### ISSUE TITLE
Redfish: Thermal

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#275]
/redfish/v1/Chassis/{ChassisId}/Thermal

https://redfish.dmtf.org/schemas/Thermal.v1_5_0.json

**Comment by gtmills** [comment]
This will include fans and temperature sensors

From https://redfish.dmtf.org/redfish/mockups/v1/863# 

![redfish_fans](https://user-images.githubusercontent.com/5455127/50982729-74aa3200-14c3-11e9-898a-c3c1d0074610.PNG)
![redfish_temperature](https://user-images.githubusercontent.com/5455127/50982733-7673f580-14c3-11e9-96e2-5ba40186a3ab.PNG)

Should also do properties like Redundancy ( fan Redundancy)

**Comment by gtmills** [comment]
Sensors that will be included in the Thermal Schema:
![old-thermal-api-mappings](https://user-images.githubusercontent.com/5455127/51001226-fa92a100-14f4-11e9-94a1-58e737f54908.PNG)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
I have begun breaking this epic into smaller stories.  More stories will likely be needed as I understand the requirements more fully.

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
I finished creating stories for this epic.  I have added story point estimates to each one and removed all the story points for the epic itself.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
Closing this epic.  Gunnar Mills and Todd Rosedahl feel what we have implemented for Redfish Thermal is acceptable for OP940.

Work remains to implement fan/temperature sensor status.  Right now bmcweb hardcodes this to OK.  This work has been deferred to OP950.  It is being tracked in https://github.com/ibm-openbmc/dev/issues/450.

**Comment by smccarney** [comment]
Re-opening because Maury Zipse wants issue #450 included in OP940.

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
Last story was merged into bmcweb today.
