### ISSUE TITLE
Implement the median functionality for the 3 ambient temps in the ambient virtual sensor

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2750]
When the temp values coming from the altitude and humidity sensors show up on D-Bus, update the ambient virtual sensor expression to calculate the median value.  There are some corner cases here, see the LLDD.

**Comment by spinler** [comment]
Due to what the entity-manager maintainer will allow in that repository, this needs to change:

1.  Create a canned 'median' function in phosphor-virtual-sensor to put a median of other sensors on d-bus.
2.  Make an entity manager schema that defines
    * the virtual sensor name
    * The 'median' function name
    * the sensors involved in the median
    * the thresholds for the virtual sensor, with hysteresis
    * minValue and maxValue entries where if a component sensor is outside of that then don't include it in the median value
 
    It may look something like:
```
    {
        Type: "VirtualSensor"
        Name: "MySensorName"
        Subtype: "Median"
        Sensors: [ "Sensor1", "Sensor2", .... ]
        ThresholdsWithHysteresis [ ]
        minInput: 0
        maxInput: 100
    }
```

    Entity manager will then be able to read this config from the JSON and put it on D-Bus.
3.  Write PVS code to look for this new data on D-Bus, calculate the median appropriately, and have it be the virtual sensor value.

**Comment by BMC-Bruce** [comment]
More of an FYI for this thread:

@rfrandse just merged this PR meta-ibm: Adds virtual Altitude sensor #1164 into 1020

To read the Altitude reading use:
    busctl introspect xyz.openbmc_project.VirtualSensor /xyz/openbmc_project/sensors/altitude/Altitude

To read the DPS310 Pressure sensor use:
    busctl introspect --no-pager xyz.openbmc_project.IIOSensor /xyz/openbmc_project/sensors/pressure/Station_Pressure

To read the DPS310 Temperature sensor use:
    busctl introspect --no-pager xyz.openbmc_project.IIOSensor /xyz/openbmc_project/sensors/temperature/Ambient_1_Temp
