### ISSUE TITLE
Guard: MC functional state handling

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2752]
- Host boot is going to create fake Guard records for MC target, to inform BMC need to update functional state based on actual presence/PG/ associate de-configure rules.
BMC
- Cold boot: Remove fake gurad records , Apply regular guard records  and  mark all  Proc0 MC as functional  without guard records.
- Warm reboot/re-configure loop: Apply regular/fake guard records.
- Hostboot need create fake guard records with special indication. ( this is required , BMC to clear in cold boot/ web ui use case)
- BMC need to remove the existing check to  apply mc gurad record check.

Fake guard:
 60    GARD_Reconfig               = 0xEB, //Force deconfig on reconfig loop

**Comment by rsnair** [comment]
Is this the one Chirag was working a while back? Can we have the commit details updated and mark the story as closed?

**Comment by rsnair** [comment]
@chirshar07 Please do the needful

**Comment by rsnair** [comment]
Please update the story with the commit details. Closing as its completed
