### ISSUE TITLE
GUI : FED : Use <abbr> element for acronyms

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2754]
## Overview
Use native `<abbr>` element for any acronyms in the application. Still need to determine where we should/shouldn't use (eg not in navigation, ok in body copy). 

https://getbootstrap.com/docs/4.5/content/typography/#abbreviations
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Resources
[IBM Knowledge Center - Language and Grammar - Abbreviations](https://www-03preprod.ibm.com/support/knowledgecenter/ibm_style/abbreviations.html)

**Comment by derick-montague** [comment]
The first step of this story is identifying and documenting here all the instances of acronyms and abbreviations. An example is the word OS for operating system.

**Comment by SurenNeware** [comment]
I identified and documented all the instances of acronyms and abbreviations.
[acronyms.txt](https://github.com/ibm-openbmc/dev/files/5616223/acronyms.txt)

**Comment by derick-montague** [comment]
I reviewed the acronyms and feel they are all industry standard and will not require any translation.
