### ISSUE TITLE
GUI : FED : Fix TableFilter component bug

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2758]
## Overview
The table filter on the Event logs page is broken. If you toggle the filter checkbox multiple times, the tags are added multiple times. This broke with an update the the BootstrapVue package (likely with v2.17.0)

## Notes
- [ ] https://github.com/bootstrap-vue/bootstrap-vue/pull/5432
- [ ] Filter worked before this commit https://github.com/openbmc/webui-vue/commit/22bba2914e75d2e4e53059c410402f050f8d70d4#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38338

**Comment by derick-montague** [comment]
Estimate 5...seems we over estimated that! :)
