### ISSUE TITLE
Fan Control: Trigger the use of alternate defined mode values

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#277]
After a user selects a different mode for fan control, load each defined set of fan control parameters within events for the selected mode. This fan control mode property should be cached within fan control for access to its value within each event.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Instead of having to lookup the fan control mode property each time from cache, use the property to trigger the removal of a set of events and replace them with an alternate set of events. These events will be defined within the events yaml configuration and generate the necessary code to perform this unload/load of events by a state of a property.

- [ ] Create an action to unload a current set of events and load an alternate set of events based on a property state
- [ ] Update the parser to generate the event contain this action to unload/load sets of events

**Comment by msbarth** [comment]
The updates to the parser to support this new action are not ideal. Some refactoring has been done within the parser under issue [openbmc/openbmc#2911](https://github.com/openbmc/openbmc/issues/2911) which has not be merged yet that may provide a better way generate the events of the use alternate events action. This will be investigated further when rebased.

Issue [openbmc/phosphor-fan-presence#13](https://github.com/openbmc/phosphor-fan-presence/issues/13) has been created for enhancing the parser due to this change later.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/17287

**Comment by rfrandse** [comment]
refresh
