### ISSUE TITLE
PLDM: softoff: Issue graceful shutdown only if the PHYP is not shutdown

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2773]
The Sensor PDR supports state 1 (Normal) which is the state when PHYP is running  along with states 5 and 7. BMC will read sensor reading using GetStateSensorReadings before issuing SetStateEffecterStates. If the state of the sensor is 5 or 7, then BMC will not issue shutdown request.

**Comment by nmuruli** [comment]
Code changes merged and released
