### ISSUE TITLE
GUI : FED : Unit Test - Page Section

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2774]
## Overview
Create a unit test for the page section component. Follow the testing guidelines of testing input and output

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
N/A

### Accessibility Tests
N/A

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38547
