### ISSUE TITLE
Redfish: CPU Processors  (missing properties)

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#278]
There already, /redfish/v1/Systems/system/Processors/cpu*, but missing some fields like  Manufacturer, core count, SerialNumber

```
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Systems/motherboard/Processors/cpu0
{
  "@odata.context": "/redfish/v1/$metadata#Processor.Processor",
  "@odata.id": "/redfish/v1/Systems/motherboard/Processors/cpu0",
  "@odata.type": "#Processor.v1_1_0.Processor",
  "Id": "cpu0",
  "Name": "Processor",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  }
}
```
```

 curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET  https://${BMC_IP}/xyzopenbmc_project/inventory/system/chassis/motherboard/cpu0
{
  "data": {
    "BuildDate": "1996-01-01 - 00:00:00",
    "Cached": false,
    "FieldReplaceable": true,
    "Functional": true,
    "Manufacturer": "IBM",
    "Model": "",
    "PartNumber": "02CY209",
    "Present": true,
    "PrettyName": "PROCESSOR MODULE",
    "SerialNumber": "YA1934389578",
    "Version": "22"
  },
  "message": "200 OK",
  "status": "ok"
}

```

**Comment by gtmills** [comment]
Should also set things like ProcessorType. 
https://redfish.dmtf.org/schemas/Processor.v1_3_1.json

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Assign to Rajes.

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/17845/ added ProcessorArchitecture and InstructionSet

**Comment by trajeswaran** [comment]
To include Model, PartNumber, SerialNumber, ProductionDate, Producer, and Version in the Redfish output, a navigation property called "Assembly" will be added. This property will provide the Redfish URI which has these fields.

The output of /redfish/v1/Systems/system/Processors/cpu* will include the below field:
Assembly : {
	@data.id : /redfish/v1/Systems/motherboard/Processors/cpu0/Assembly
}

The navigation of this Redfish URI will provide Model, PartNumber, SerialNumber, etc...

/redfish/v1/Systems/motherboard/Processors/cpu0/Assembly
{
   "@odata.type"    : "#Assembly.v1_2_0.Assembly",
   "@odata.context" : "/redfish/v1/$metadata#Assembly.Assembly",
   "@odata.id"      : "/redfish/v1/Systems/motherboard/Processors/cpu0/Assembly
   "Assemblies" : [
       {
		"@odata.id"    :  "/redfish/v1/Systems/motherboard/Processors/cpu0/Assembly#/Assemblies/0
                "MemberId"     :  "0"
		"Name"             :  "Processor"
		"Model"            :  ""
		"PartNumber"   :  "02CY209"
		"SerialNumber" :  "YA1934389578"
		ProductionDate :  "1996-01-01 - 00:00:00"
		Producer            :  "IBM"
		Version              :  "22"		 
	}
   ]
}

**Comment by ratagupt** [comment]
@trajeswaran Currently we don't have the implementation for Assembly or the Assembly Collection in the bmcweb, we need to write that.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by trajeswaran** [comment]
Resolved by : https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18590/

The scope of this issue is limited to "TotalCores". The remaining missing fields Model, PartNumber, SerialNumber, ProductionDate, Producer, and Version will be implemented as part of Assembly.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@ratagupt @trajeswaran There is a processor model can we fill that one out?
https://redfish.dmtf.org/schemas/v1/Processor.v1_5_0.json

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/18590 merged
