### ISSUE TITLE
Redfish: Query parameters: select

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2784]
From DSP0266 version 1.8.0, there is a query parameters (section 7.3)

DSP0266_1.8.0.pdf

**Comment by zhanghch05** [comment]
review: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43118

**Comment by gtmills** [comment]
https://gerrit.openbmc.org/q/project:openbmc/bmcweb+status:merged+select but could be enhanced to be more efficient. That can be a different story
