### ISSUE TITLE
Redfish: Query parameters: expand

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2785]
From DSP0266 version 1.8.0, there is a query parameters (section 7.3)

DSP0266_1.8.0.pdf

**Comment by zhanghch05** [comment]
review: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/42908

**Comment by gtmills** [comment]
@zhanghaodi Can you resolve merge conflicts on https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/42908 ?

**Comment by zhanghch05** [comment]
> @zhanghaodi Can you resolve merge conflicts on https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/42908 ?

I have resolved the "only" conflict. When there is no problem with "only", I will solve "expand".

**Comment by gtmills** [comment]
@zhanghch05 Can you keep going on this? 
Resolve merge conflicts on https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/42908/10 
Have other IPS developers do some reviews?
Would like to pull this in next month

**Comment by zhanghch05** [comment]
> @zhanghch05 Can you keep going on this? Resolve merge conflicts on https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/42908/10 Have other IPS developers do some reviews? Would like to pull this in next month

According to Ed’s new design, "Query Parameters" needs to rely on these two:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/48907
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/48910
48907 was once abandoned because of a mistake. I have solved it now, but Ed doesn't pay attention to this anymore.

**Comment by gtmills** [comment]
@zhanghch05, @aahmed-2 has been looking at being in the expand Query parameters. 
Could you refresh the change ?

**Comment by gtmills** [comment]
@zhanghch05 Could you pull the expand query parameter into https://github.com/ibm-openbmc/bmcweb ?

**Comment by aahmed-2** [comment]
@zhanghch05 - Can I ask you to fix 'Change the completionhandler to accept Res' as well? https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/48002.

 I saw you had a comment on fixing in this commit https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/48864

**Comment by zhanghch05** [comment]
> @zhanghch05 - Can I ask you to fix 'Change the completionhandler to accept Res' as well? https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/48002.
> 
> I saw you had a comment on fixing in this commit https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/48864

@aahmed-2 
Nan Zhou has a new commit and we decided to use his.
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/50742

**Comment by zhanghch05** [comment]
> @zhanghch05 Could you pull the expand query parameter into https://github.com/ibm-openbmc/bmcweb ?

@gtmills ok
IBM's bmcweb code is old and I need some time to merge and test.

**Comment by zhanghch05** [comment]
@aahmed-2 @gtmills 
Change the completionhandler to accept Res:
https://github.com/ibm-openbmc/bmcweb/pull/257

**Comment by gtmills** [comment]
@zhanghch05 the focus of the expand query parameter is on the sensors. 
 /redfish/v1/Chassis/chassis/Sensors?$expand=*($levels=1) ?
 
 
 @aahmed-2 built your code but was still seeing /redfish/v1/Chassis/chassis/Sensors?$expand=*($levels=1) take mins

**Comment by gtmills** [comment]
I think we will need some performance enhancements for the sensors $expand=*($levels=1)

**Comment by zhanghch05** [comment]
>

**Comment by zhanghch05** [comment]
> @zhanghch05 the focus of the expand query parameter is on the sensors.
> /redfish/v1/Chassis/chassis/Sensors?$expand=*($levels=1) ?

done

**Comment by gtmills** [comment]
Reopening since this isn't merged. 
Can you add some performance numbers behind /redfish/v1/Chassis/chassis/Sensors?$expand=*($levels=1) ?

**Comment by zhanghch05** [comment]
> Can you add some performance numbers behind /redfish/v1/Chassis/chassis/Sensors?$expand=*($levels=1) ?

This is related to the number of sensors. I am currently using QEMU to test, only 13 voltage sensors, it takes about 1s.
How many sensors do you have?

**Comment by aahmed-2** [comment]
> This is related to the number of sensors. I am currently using QEMU to test, only 13 voltage sensors, it takes about 1s.
How many sensors do you have?

Generally around 150-200 sensors but as many as 300+. More sensors are being added so expand could take some time.

**Comment by aahmed-2** [comment]
Are you seeing any errors in the output of the expand query when we use $expand=*($levels=2)? 
I'm seeing an output of only the final response instead of all the responses together.

**Comment by zhanghch05** [comment]
> Are you seeing any errors in the output of the expand query when we use $expand=*($levels=2)? I'm seeing an output of only the final response instead of all the responses together.

I don't see an error, I've only tested $expand in /redfish/v1/Systems and /redfish/v1/Chassis/chassis/Sensors. Where are you using $expand=*($levels=2)?

**Comment by gtmills** [comment]
Merged here: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/52272
