### ISSUE TITLE
PFP::control - Move current action functions into the associated action class object

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2787]
Reorganize the action functions into the associated action class objects for use by JSON configured fan control. When doing this, the underlying framework for calling event actions on a zone needs to also be changed for JSON configured fan control only.

The action class objects should have a `run` function that does the primary function of the action, but also include `pre` and `post` functions of the action so that related changes can be made that are associated with the action. An example of this would be, for example on the action that sets/holds fans at a given speed, a `post` function that the group causing this action to run is entered to no longer allow fan speed changes.

**Comment by msbarth** [comment]
This is being done now within #1363 as it was found to not be worth using the current method of returning the action functions when using JSON based configurations.

**Comment by spinler** [comment]
Seems like the previous comment indicates this is no longer needed.  Closing as I can't see we still need to do anything here anyway.
