### ISSUE TITLE
GUI : FED : Table date filter calendar icon appears above table toolbar

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2788]
## Overview
The z-index of the calendar icon for the table date filter component needs to be adjusted so that it sits below the table toolbar component

![Screen Shot 2020-12-04 at 10.49.35 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/6f023b59-6973-4db8-92d7-d620150de109)

## Steps to Reproduce the Problem
This is only found on the dumps page because there isn't a filter button. Without a filter button, the batch actions toolbar will render above the filter inputs.

**Comment by derick-montague** [comment]
This issue will require a bit of testing. The only z-index value the date-picker container can have in order to not render above the batch actions tool bar is 1.

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39185

**Comment by dixsie** [comment]
@yoshiemuranaka I'm wondering if maybe there should also be space between the date picker fields and the table? So instead of the actions going over the form field it would go over the space above the table?

**Comment by derick-montague** [comment]
> @yoshiemuranaka I'm wondering if maybe there should also be space above the table by default or maybe the action button row should push the table down when it appears?

My preference would be to not have the batch actions render above the button. I still need to test the solution proposed, but it feels like the right direction.

**Comment by yoshiemuranaka** [comment]
>I'm wondering if maybe there should also be space above the table by default or maybe the action button row should push the table down when it appears?

@dixsie I don't love the idea of pushing the table (would be jumpy and less performant) 
For the space issue...not sure how that would look, we would want to make sure the association between filter and table is clear.

**Comment by derick-montague** [comment]
We have a fix that I pushed up that resolves both issues: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39415
