### ISSUE TITLE
PLDM: RR-Handle the PLDM restart scenario when the host is powered off

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2789]
BMC issues GetPDR command (Get first PDR in the repository) to the host and if the host is powered off, then the PLDM command  times out. If it powered off/on update the HostState D-Bus property to indicate the status of the host.

**Comment by nmuruli** [comment]
Code Review in Driver (Downstream)

**Comment by mzipse** [comment]
Closing.  Work is complete.
