### ISSUE TITLE
Redfish: Memory  (missing properties) 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#279]
There already but missing some properties like Manufacturer, Model, etc.
```
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Systems/motherboard/Memory/dimm8
{
  "@odata.context": "/redfish/v1/$metadata#Memory.Memory",
  "@odata.id": "/redfish/v1/Systems/motherboard/Memory/dimm8",
  "@odata.type": "#Memory.v1_2_0.Memory",
  "Id": "dimm8",
  "Name": "DIMM Slot",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  }
}
```

```

 curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET  https://${BMC_IP}/xyzopenbmc_project/inventory/system/chassis/motherboard/dimm0
{
  "data": {
    "BuildDate": "",
    "Cached": false,
    "FieldReplaceable": true,
    "Functional": true,
    "Manufacturer": "0x2c80",
    "Model": "36ASF4G72PZ-2G6D1   ",
    "PartNumber": "",
    "Present": true,
    "PrettyName": "0x0c",
    "SerialNumber": "0x17939d64",
    "Version": "0x31"
  },
  "message": "200 OK",
  "status": "ok"

```

https://redfish.dmtf.org/schemas/Memory.v1_6_0.json

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Assign to Raviteja.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by manojkiraneda** [comment]
I didn't see a one-to-one map between the dbus properties that we already have and the redfish properties as per the memory schema.

The below is what i have found :
    DBUS                        REDFISH
BuildDate           -       No direct match
Cached              -       No direct match
FieldReplaceable    -       No direct match
Functional          -       No direct match
Manufacturer        -         Manufacturer    
Model               -       No direct match
PartNumber          -          PartNumber
Present             -       No direct match
PrettyName          -       No direct match
SerialNumber        -         SerialNumber
Version             -       No direct match

**Comment by manojkiraneda** [comment]
Resolved by : https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/23022/

**Comment by manojkiraneda** [comment]
With the patch, it looks like as shown below:
[whoami@dhcp-9-193-95-75 bmcweb]$ curl -k -H "X-Auth-Token: $bmc_tokens" -X GET https://wsbmc022.aus.stglabs.ibm.com:443/redfish/v1/Systems/system/Memory/dimm12
{
  "@odata.context": "/redfish/v1/$metadata#Memory.Memory",
  "@odata.id": "/redfish/v1/Systems/system/Memory/dimm12",
  "@odata.type": "#Memory.v1_6_0.Memory",
  "Id": "dimm12",
  "Manufacturer": "Samsung Electronics",
  "Name": "DIMM Slot",
  "PartNumber": "",
  "SerialNumber": "0x3601b803",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  }

**Comment by manojkiraneda** [comment]
The gerrit commit is merged, hence closing the issue.
