### ISSUE TITLE
PLDM: Implement download of Resource & LPA dump

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2790]
This story is to add support for the download of Resource & LPA dump. The flow will be similar to system dump.

**Comment by sampmisr** [comment]
Resource dump is resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/40115

**Comment by sampmisr** [comment]
Resource dump is done. We will take LPA dump with a separate story
