### ISSUE TITLE
New Thermal Subsystem 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2791]
Part of the new Power / Thermal schemas

**Comment by gtmills** [comment]
FanRedundancy should covered elsewhere so should be pretty small

**Comment by gtmills** [comment]
new thermal subsystem schema at /redfish/v1/Chasssis/chassis/ThermalSubsystem

**Comment by gtmills** [comment]
implement this https://redfish.dmtf.org/schemas/v1/ThermalSubsystem.v1_0_0.json schema

**Comment by XiaochaoMa** [comment]
Commit :
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41012

**Comment by gtmills** [comment]
Merged. Closing
