### ISSUE TITLE
New Power Subsystem 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2792]
Part of the new Power / Thermal schemas

**Comment by gtmills** [comment]
PowerSupplyRedundancy should covered elsewhere so should be pretty small

**Comment by gtmills** [comment]
implement this schema https://redfish.dmtf.org/schemas/v1/PowerSubsystem.v1_0_0.json

**Comment by ChicagoDuan** [comment]
> PowerSupplyRedundancy should covered elsewhere so should be pretty small

Hi @gtmills .  Are you saying there is no need to implement PowerSupplyRedundancy here?

**Comment by gtmills** [comment]
Yes, we don't have today. 
https://github.com/openbmc/bmcweb/search?l=C%2B%2B&q=Redundancy

Just need to match what we have today for the Power / Thermal schemas if this epic.

**Comment by ChicagoDuan** [comment]
ref :  https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40323

**Comment by gtmills** [comment]
Merged at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57672 
Closing
