### ISSUE TITLE
New Power Supply Schema 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2795]
Part of the new Power / Thermal schemas.

**Comment by gtmills** [comment]
implement this schema: https://redfish.dmtf.org/schemas/v1/PowerSupply.v1_0_0.json

**Comment by ChicagoDuan** [comment]
ref: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40326/1

**Comment by ChicagoDuan** [comment]
Hi @gtmills ,
     I met some doubts about the "HealthRollup" of PowerSupply. 
     In health.hpp, it use associations to determine health status(https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/health.hpp#L191).  

So when the PowerSupply Functional is false, we need to create a new association ( such as : 
/xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply0/critical ). Only the path ending with "critical" or "warning" will be detected by the getAllStatusAssociations() function in health.hpp, and then HealthRollup and Health will become "Critical".

So which process will create the association when Functional becomes false? I saw the `callback_manager` in the initial commit of redfish_health_rollup.md on gerrit: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/21380/7/designs/redfish_health_rollup.md#76 .
But it's Intel-specific. Do we have a program like this? If not, I wonder if we can let the phosphor-led-manager to do this or we need to create a new process to do this?

This is also the case with CPU Health and Fan Health. I am looking forward to your reply. Thank you!

**Comment by vishwabmc** [comment]
@ChicagoDuan the Health also uses `State.Decorator.OperationalStatus` `Functional` to determine the Health property and I see it is working in master. But the HealthRollUp is something that is not working

**Comment by ChicagoDuan** [comment]
> @ChicagoDuan the Health also uses `State.Decorator.OperationalStatus` `Functional` to determine the Health property and I see it is working in master. But the HealthRollUp is something that is not working

Yes. No one to create a new association : xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply0/critical , so HealthRollup can't detect Critical.  That's what I said above, we need a daemon to create this new association.  

Or maybe we could modify the health.hpp to search for all Critical/Warning thresholds and OperationalStatus.

**Comment by gtmills** [comment]
Yes, I think health.hpp should be modified to look for OperationalStatus for the Health. 
Ideally, all resources would then use health.hpp. 
It might make sense to rename health.hpp to status.hpp and have it do the health, healthrollup, and state. This is far beyond the scope of this story, just an idea. 

Should probably push a paragraph to:
https://github.com/openbmc/docs/blob/919a7b6816a5f16aa72d298e81e0756d95d5031e/designs/redfish-health-rolllup.md#proposed-design 

```
# Individual Resource Health 
All resources should look at OperationalStatus  to determine the Health 
```

**Comment by ChicagoDuan** [comment]
> Yes, I think health.hpp should be modified to look for OperationalStatus for the Health.
> Ideally, all resources would then use health.hpp.
> It might make sense to rename health.hpp to status.hpp and have it do the health, healthrollup, and state. This is far beyond the scope of this story, just an idea.
> 
> Should probably push a paragraph to:
> https://github.com/openbmc/docs/blob/919a7b6816a5f16aa72d298e81e0756d95d5031e/designs/redfish-health-rolllup.md#proposed-design
> 
> E.g.
> 
> ```
> # Individual Resource Health 
> All resources should look at OperationalStatus  to determine the Health 
> ```

Yes, so now we don't need add HealthRollup to PowerSupply schema and Fan schema.

**Comment by gtmills** [comment]
Merged at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57672 
Closing
