### ISSUE TITLE
Move sensor collection to all sensors 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2796]
Part of the new power / thermal schemas

**Comment by lxwinspur** [comment]
@gtmills @mzipse 
IPS want to do these tasks, Could you describe these tasks in detail? Thanks :)

**Comment by gtmills** [comment]
https://lists.ozlabs.org/pipermail/openbmc/2021-January/024700.html

All sensors from /xyz/openbmc_project/sensors with the "all_sensors" association for that chassis should be under /redfish/v1/Chassis/<chassis id>/Sensors
https://github.com/openbmc/docs/blob/919a7b6816a5f16aa72d298e81e0756d95d5031e/architecture/sensor-architecture.md#association-names

Today it looks at only these sensors: https://github.com/openbmc/bmcweb/blob/88b3dd12851cd7bdd4b5c065ba99f40feafb775e/redfish-core/lib/sensors.hpp#L62

**Comment by lxwinspur** [comment]
review by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40169

**Comment by gtmills** [comment]
@lxwinspur Could you do the performance testing asked for by Ed on this?

**Comment by lxwinspur** [comment]
@gtmills Sorry, I do not know how to test, Could you give me some prompts? Thanks

**Comment by gtmills** [comment]
From the review "If you had the numbers on how much slower this made a full tree dump, and the percentage increase in the time to list the sensor schema specifically, that would help."

Hey @lxwinspur, 
I think 2 things here: 
1) How much slower is 
curl -k -H "X-Auth-Token: $token" https://${bmc}/redfish/v1/Chassis/chassis/Sensors 

2) How much slower is calling curl -k -H "X-Auth-Token: $token" https://${bmc}/redfish/v1/Chassis/chassis/Sensors  and then calling each member i.e. /redfish/v1/Chassis/chassis/Sensors/fan0_0 

These should be an average of a couple runs (in seconds). 
Can you please add the before and after average time to the commit msg? 
E.g. 
```
Performance testing (average of 5 times):
Calling https://${bmc}/redfish/v1/Chassis/chassis/Sensors 
Before: x.x seconds 
With this change: y.y seconds 

Calling https://${bmc}/redfish/v1/Chassis/chassis/Sensors and then calling each member (e.g. /redfish/v1/Chassis/chassis/Sensors/fan0_0)
Before: xx.x seconds
With this change: yy.y seconds

Would vary depending on the number of sensors. This was tested on a <insert system tested on> system and saw the member count in the sensor collection increase from xx to 25.  
```

**Comment by lxwinspur** [comment]
Performance testing (average of 5 times):

> curl -k -H "X-Auth-Token: $token" https://${bmc}/redfish/v1/Chassis/chassis/Sensors

Before: 0.275 s
With this change: 0.394 s

> curl -k -H "X-Auth-Token: $token" https://${bmc}/redfish/v1/Chassis/chassis/Sensors/ps0_input_current

Before: 0.874 s
With this change: 0.913 s

**Comment by gtmills** [comment]
@lxwinspur The 2nd testing is all of the members of in /redfish/v1/Chassis/chassis/Sensors.
Start the time. Then call /redfish/v1/Chassis/chassis/Sensors and get back: 
```
curl -k -H "X-Auth-Token: $token" https://${bmc}/redfish/v1/Chassis/chassis/Sensors
{
  "@odata.id": "/redfish/v1/Chassis/chassis/Sensors",
  "@odata.type": "#SensorCollection.SensorCollection",
  "Description": "Collection of Sensors for this Chassis",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/Sensors/fan0_0"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/Sensors/fan0_1"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/Sensors/fan1_0"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/Sensors/fan1_1"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/Sensors/fan2_0"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/Sensors/fan2_1"
    },
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/Sensors/fan3_0"
    },
```
Then can each of those members: 

/redfish/v1/Chassis/chassis/Sensors/fan0_0
/redfish/v1/Chassis/chassis/Sensors/fan0_1
/redfish/v1/Chassis/chassis/Sensors/fan1_0
/redfish/v1/Chassis/chassis/Sensors/fan1_1
/redfish/v1/Chassis/chassis/Sensors/fan2_0
/redfish/v1/Chassis/chassis/Sensors/fan2_1
/redfish/v1/Chassis/chassis/Sensors/fan3_0

End the time.

**Comment by lxwinspur** [comment]
@gtmills 

> The 2nd testing is all of the members of in /redfish/v1/Chassis/chassis/Sensors.
Start the time. Then call /redfish/v1/Chassis/chassis/Sensors and get back:

Before: 0.475 s
With this change: 0.945s
The above test does not include the fan.

**Comment by lxwinspur** [comment]
@gtmills 
This patch has been merged, can we close this issue?

**Comment by gtmills** [comment]
Closed.
