### ISSUE TITLE
Code Update: Support single signature for the tarball contents

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#2798]
Currently the contents of the code update tarball are individually signed and signature files for each file are created, ex: image-rofs.sig, image-kernel.sig, etc. Need to create an additional single signature file based on the individual signature files to ensure the contents of the tarball are the expected ones as a full package.

This requires changes in 2 areas:
1. Create a single signature file (ex: sign(hash(file1.sig + file2.sig + file3.sig). In file `meta-phosphor/classes/image_types_phosphor.bbclass`, function `make_signatures()`, is where the individual .sig files are created. This function would need to then create a single signature file named `image.sig` for example with the hash of all the signature files created.
2. In the `phosphor-bmc-code-mgmt` repo, need to add support to verify this additional signature during code update.

**Comment by lxwinspur** [comment]
review by:
1. https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/39036
2. https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/39118

**Comment by lxwinspur** [comment]
@anoo1 Lei has the following doubts:
```
I do not understand why it is needed.
Is it to prevent the user who removes part of the images from the tarball?
If yes, one could just remove the image-full.sig becase the code does not check this signature if it does not exist.
```

Also, I would like to know does the `image-full.sig` have to exist?
If yes, We can not update the old image tar package.

**Comment by anoo1** [comment]
Thanks @lxwinspur for making the needed changes.

> @anoo1 Lei has the following doubts:

I'll reply in the review. In summary, there's a concern that it's possible to create a tarball with mismatch file + file.sig files. For example it could be possible to manually create a tarball with a kernel and signature from one level, and a rootfs and signature from another.

> Also, I would like to know does the `image-full.sig` have to exist?
> If yes, We can not update the old image tar package.

Good point. I think we can add a new config option so that users can opt-in if they want to enforce that the image-full.sig file exists. Currently, we have in the phosphor-bmc-code-mgmt code:
```
conf.set('WANT_SIGNATURE_VERIFY', get_option('verify-signature').enabled())
```
We can probably add a new option like 'verify-image-signature', then this new option can be checked in the image_verify.cpp file to see if the file exists or not. What do you think?

**Comment by lxwinspur** [comment]
@anoo1 Thanks for your reply.

> We can probably add a new option like 'verify-image-signature', then this new option can be checked in the image_verify.cpp file to see if the file exists or not

Yes, I agree with you and will fix this patch. Thanks :)

**Comment by lxwinspur** [comment]
Closed by:

https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/39036
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/39118
