### ISSUE TITLE
Implement the BootProgress as a host sensor instead of the effecter

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2799]
https://github.com/openbmc/pldm/blob/master/configurations/pdr/11.json#L5 The Boot progress effecter on BMC is updated by the host using SetStateEffecterStates command. The Boot Progress will be implemented as a host state sensor and host will send a sensor event to BMC. This story is to make the BootProgress as  a host sensor instead of a BMC effecter.

**Comment by Pavithrab7** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/41033
