### ISSUE TITLE
Certificate managment boot path support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#28]
-   Add support for creating new self signed certificate.
- Incase of no certificate or invalid  certificate certificate manager should update the certificate with self signed certificate.
-  Added unit test case for newly added functions.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Already considered as part of the issue https://github.com/ibm-openbmc/dev/issues/354
Also code is up for reveiw.
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-certificate-manager/+/17918/
Closing this issue now.
