### ISSUE TITLE
Redfish: GPUs (Processor schema)

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#280]
Need to get `inventory/system/chassis/motherboard/gv100card*` into Redfish. 
https://redfish.dmtf.org/schemas/Processor.v1_3_1.json with ProcessorType set to GPU. 
/redfish/v1/Systems/{ComputerSystemId}/Processors/{ProcessorId}

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Added https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/18009 here. We will want to use on the GPUs for Witherspoon, then set the processor schema to "Accelerator" in Redfish.

https://redfish.dmtf.org/schemas/Processor.v1_4_0.json
```

ProcessorType |  
-- | --
enum |  
0 | "CPU"
1 | "GPU"
2 | "FPGA"
3 | "DSP"
4 | "Accelerator"
5 | "Core"
6 | "Thread"
7 | "OEM"
enumDescriptions |  
Accelerator | "An Accelerator."
CPU | "A Central Processing Unit."
Core | "A Core in a Processor."
DSP | "A Digital Signal Processor."
FPGA | "A Field Programmable Gate Array."
GPU | "A Graphics Processing Unit."
OEM | "An OEM-defined Processing Unit."
Thread | "A Thread in a Processor."


```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/20958
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/21107
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-host-ipmid/+/21106

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/21218 had to be reverted as it broke swift. Work is underway to fix the issues with Swift. Once that is done, the change will be redone and this issue can be closed.

**Comment by santoshpuranik** [comment]
I pushed the reverted change again here: https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/23452. Swift compile seems to have passed per Jenkins, once this change is merged, this issue can be closed.

**Comment by gtmills** [comment]
@santoshpuranik 23452 is merged. Can we close?

**Comment by santoshpuranik** [comment]
Yes, closing.
