### ISSUE TITLE
GUI : FED : Table row action button style update

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2801]
## Overview
It was expected that we would only use icons. For Client Sessions, design has advocated for the use of text only, `Disconnect`. Based on how the CSS is handling the icon button, we have set an explicit height and width on the button that has been overridden in the single file component template for client sessions. It is possible that this text based actions in table rows could be used on other screens and by other organizations. In this case, we will not want to mandate this override pattern and need to address this use case in a different way.

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by derick-montague** [comment]
This may be able to be consolidated with #2812

**Comment by dixsie** [comment]
this work will be completed as part of #2812
