### ISSUE TITLE
GUI : FED : Dumps - BMC/System dump settings

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2802]
## Overview
Adds ability to adjust dump specific settings before creating a new dump.

## UX Flow / Interaction Requirements
- [ ] 

## Final Invision Mockup
https://ibm.invisionapp.com/share/W2O0ZZFE6C7

![image](https://user-images.githubusercontent.com/1183515/111054006-8b939880-842e-11eb-9f6d-ab01eeaf88f3.png)

## cURL Commands
```
```

## Notes
- [ ] Backend plans to work on on these settings
- [ ] https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1607526391354100

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshot
![Screen Shot 2020-12-04 at 8.05.27 AM.png](https://images.zenhubusercontent.com/5cbe076507507b08996e895c/2cd3d728-01cc-4593-86ed-1ff08f3e2021)

**Comment by derick-montague** [comment]
We need to make sure this is possible. 
![image](https://user-images.githubusercontent.com/1183515/102153192-4619fc00-3e3c-11eb-95b7-d514d8c255b0.png)

**Comment by derick-montague** [comment]
Talked to @priyanka-pillai97 today and we need to verify that this will not be done and we can move this to a different milestone.

**Comment by derick-montague** [comment]
We need to follow up with @dhruvibm - he is the SME to determine is this work can be done.

**Comment by derick-montague** [comment]
Sandhya Somashekar reached out on Slack to discuss this feature on 7/19/21. @dhruvibm is the owner and she said she would be following up with him. We have not heard any more on this.

**Comment by dhruvibm** [comment]
Only dump policy is supported, hardware content and firmware content are always automatic/default
