### ISSUE TITLE
GUI : FED : Add translated cancel title to all modals

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2804]
## Overview
Majority of modal implementation uses the default 'Cancel' title provided bootstrap vue. We will need to provide a translated `cancel-title` prop value for all modals 
https://bootstrap-vue.org/docs/components/modal#comp-ref-b-modal-props

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39197
