### ISSUE TITLE
GUI : FED : Network Settings - Configure DHCP/Static addresses

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#2805]
## Overview
- [ ] Add ability to configure Network Settings to use `Static` or `DHCP` addresses

## UX Flow / Interaction Requirements
- [x] Add radio buttons for `Static` and `DHCP`
- [x] Add `DHCP` table to display `IPv4Addresses` addresses with DHCP `IPv4AddressOrigin`
- [x] When there are no DHCP addresses, table empty-text displays `$t('global.table.emptyMessage')`
- [x] DHCP table should always be readonly, with the delete action and trash icon button disabled
- [x] When DHCP radio is selected, the Static IPV4 table is readonly with the delete action and trash icon button disabled
- [x] Add table headings h3, with class h4

## Mockup
![Screenshot_2020-10-02 Network settings(10)](https://user-images.githubusercontent.com/26472611/94954656-0a170200-04af-11eb-875f-87844a0cca92.png)

![Screenshot_2020-10-02 Network settings(8)](https://user-images.githubusercontent.com/26472611/94954569-ed7aca00-04ae-11eb-956d-d2171344ccaf.png)

## cURL Commands
```
export bmc=<add IP address>

// Get token
export token=`curl -k -H "Content-Type: application/json" -X POST https://${bmc}/login -d '{"username" :  "root", "password" :  "0penBmc"}' | grep token | awk '{print $2;}' | tr -d '"'`

// Get info for the first interface
curl -k -H "X-Auth-Token: $token" https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

// Enable/disable DHCP
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"DHCPv4": {"DHCPEnabled": true}}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
```

## Notes
- [ ] There may not be any DHCP addresses available
- [ ] https://redfish.dmtf.org/schemas/v1/IPAddresses.v1_0_10.json#/definitions/IPv4Address

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by dixsie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Network Settings- DHCP](https://trello.com/c/Cr0PJ9iM/7-network-settings-dhcp)

**Comment by derick-montague** [comment]
There are some [questions with this story that are being discussed in slack](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1608220583009500) with @ratagupt, @dixsie, and @gtmills. The issue is that the system bricks when running the curl command to switch from static to DHCP due to the change to default gateway.

**Comment by dixsie** [comment]
I’m not sure it’s default gateway causing the issue with enabling DHCP, but when I run the `curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"DHCPv4": {"DHCPEnabled": true}}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0` the machine goes down

**Comment by derick-montague** [comment]
@dixsie reached out to @ratagupt in slack and is planning to follow up when we are back in January.

**Comment by derick-montague** [comment]
@dixsie There are two stories, one for changing the default gateway to be interface specific (#2230) and one for fixing an issue to allow both static and DHCP (#386)

**Comment by derick-montague** [comment]
I [reached out to @ratagupt on slack](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1610036217130700) referencing the timeout comment above.
