### ISSUE TITLE
GUI : FED : Fix Icon/Text only button accessibility

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#2812]
## Overview
- Buttons with both aria-label and title attributes have both properties read by JAWS screen readers (see notes below). 
- Buttons should not have aria-label if semantic anchor text is provided. For example, the table-row-action component "as-is" for text only buttons looks like and is incorrect:
 ```<button aria-label="Disconnect" title="Disconnect" type="button" class="btn btn-icon-only btn-link"> Disconnect </button>```
- For Client Sessions, design has advocated for the use of text only, `Disconnect`. Based on how the CSS is handling the icon button, we have set an explicit height and width on the button that has been overridden in the single file component template for client sessions. It is possible that this text based actions in table rows could be used on other screens and by other organizations. In this case, we will not want to mandate this override pattern and need to address this use case in a different way.

##  Requirements
- [ ] Remove the `aria-label` attribute for buttons with text (including icon only buttons in table row actions and password toggle button)
- [ ] Remove the`title` attribute on text only buttons
- [ ] Use `<span class="sr-only"> </span>` to add anchor text to icon only buttons
- [ ] Verify icon only button alignment class `btn-icon-only` still works, may need to adjust
    - Possibly only set this class if the button has an icon only 
- [ ] Remove `disconnect` table row action button style override and find new solution for handling button height/width
    - This might be just removing the SFC override and only injecting the `btn-icon-only` class if the button only uses an icon

## Notes
- Semantic HTML is preferred over Aria
- What is read by screen readers: ![Screen Shot 2020-12-14 at 1.45.38 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/cad984b8-9d65-40ee-b34f-87ab238755d9)
- JAWS is the most common screen reader

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39249

**Comment by derick-montague** [comment]
@SurenNeware can you check the items you have completed in the requirements list, please?
