### ISSUE TITLE
eBMC GUI : Content tracker

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2813]
## Summary
This epic includes stories that require updates to the page copy. There are a couple of problems that need to be solved:

1. Does our copy meet the IBM content creating guidelines
2. Can we meet IBM needs and community  needs through content consensus

## IBM centered content
There has been discussion about page copy and feature descriptions that are required to meet IBM needs, but do not sync with the needs of the OpenBMC community. We are making every effort to create system agnostic copy, it is possible that it will not always be possible.

### Ideas
1. Keep copy basic and agnostic upstream and make slight changes downstream and have both upstream and downstream json files translated. 
1. Determine if there can be a way to swap sections dynamically to avoid downstream work
1. Work with KC team to update info to be more common to the OpenBMC as we move away from FSP-based systems.

### Pages and/or terms
| Location              | Terms            | Suggestion  | Confirmed | Downstream
| ------------- |--------------| -------------|-----------|----------|
| Client Sessions, Factory Reset | `Management consoles` | HMC or Hardware Management Console | Yes  | Yes
| Factory Reset | `hypervisor` | `Host firmware` or `Server firmware` | Yes | No
| FW and Factory reset | `host` | `server` | Yes | No
| POST codes history | POST code | Progress code | Yes | Yes
| Hardware inventory | SparePartNumber | FRU | No | Yes

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
This work is complete.  Closing.
