### ISSUE TITLE
GUI : Page not found when opening new tab

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2814]
## Expected Behavior
A user should be able to open a page in a new tab.

## Actual Behavior
The user is directed to the page and it displays `page not found`

### Screencast
https://youtu.be/vzAL2IgMbDE

## Steps to Reproduce the Problem

  1. Login
  1. Right-click on a page in the primary navigation and select `open in a new tab`
  

## Specifications
  - Browser: All
  - Version: N/A

**Comment by derick-montague** [comment]
The issue is that we are using absolute paths instead of relative in the AppNavigationMixin. If we remove all the leading forward slashes (`/`) from the route path. The issue will be resolved.

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39275

**Comment by derick-montague** [comment]
@Srisuk is this ready for review? The Gerrit review says WIP.

**Comment by Srisuk** [comment]
@derick-montague I tried the above solution provided but the issue is still persisting.

**Comment by derick-montague** [comment]
I pushed up a change. Sorry to lead you in the wrong direction.

**Comment by derick-montague** [comment]
> The issue is that we are using absolute paths instead of relative in the AppNavigationMixin. If we remove all the leading forward slashes (`/`) from the route path. The issue will be resolved.

This was 100% not the issue. The issue was that we need to use <router-link> and then regardless of whether we are in hashed mode or not, the url will be generated correctly.
