### ISSUE TITLE
GUI : Security Panel add additional features

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#2819]
## Overview
- [x] Only IPMI and SSH were implemented in #2063

## UX Flow / Interaction Requirements
- [x] add  RTAD (redfish is ready, it's a bios setting `pvm_rtad`) - need to verify if this goes under network services section
- [x] Add test hooks for RTAD
- [x] add VirtualTPM  `pvm_vtpm` - https://github.com/openbmc/pldm/blob/master/oem/ibm/configurations/bios/enum_attrs.json#L261 "Enabling vTPM makes a TPM available to the guest operating system." 
- [x] Add test hooks for VirtualTPM 
- [x] add TPM (Must use Redfish API (#1795)
    - [x] Label TPM as `Host TPM`
- [x] Remove TPM from power server operations page
- [x] Update section dividers to use section divider class

### Not ready
- [ ] add SSH SOL (redfish **not** ready, ask @joseph-reynolds)

## Final Invision Mockup
~~https://ibm.invisionapp.com/share/EFO0P87G8JA~~
https://ibm.invisionapp.com/share/SGO0QDLQ8VD#/screens

### Screen Capture
![image.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/30467ccc-242f-4a8f-99c5-8ae33eeb73ea)![Screen Shot 2020-12-02 at 9.09.55 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/d6fe8e65-f0d6-4578-9eb0-bcbdd33731a2)

## cURL Commands
- [ ] Add cURL commands TBD

Virtual TPM bios attribute: https://github.com/openbmc/pldm/blob/master/oem/ibm/configurations/bios/enum_attrs.json#L261
```
 {
         "attribute_name":"pvm_vtpm",
         "possible_values":[
            "Disabled",
            "Enabled"
         ],
         "default_values":[
            "Disabled"
         ],
         "helpText" : "Enabling vTPM makes a TPM available to the guest operating system.",
         "displayName" : "Virtual Trusted Platform Module"
      },
```

## Notes
- https://redfish.dmtf.org/schemas/ManagerNetworkProtocol.v1_4_0.json

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
There are also some suggestions on [content from Andrew Jefferery in the webui-vue design review story](https://github.com/openbmc/webui-vue/issues/5#issuecomment-736140680) that we need to ask the design team about and potentially work with Stephanie to validate.

**Comment by nicoleconser** [comment]
Pasting this comment from @joseph-reynolds on #1531 —  https://github.com/ibm-openbmc/dev/issues/1531#issuecomment-769164919

**Comment by derick-montague** [comment]
RTAD ready now. Waiting on USB and SoL.

**Comment by dixsie** [comment]
need to follow up if only `service` and `admin` users can enable/disable sol with SSH?

**Comment by Nikhil-Ashoka** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/50717 for RTAD and VirtualTPM
