### ISSUE TITLE
Redfish: Host watchdog

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#282]
```bash-4.1$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET  https://${BMC_IP}/xyz/openbmc_project/watchdog/host0
{
  "data": {
    "Enabled": false,
    "ExpireAction": "xyz.openbmc_project.State.Watchdog.Action.None",
    "Initialized": true,
    "Interval": 10000,
    "TimeRemaining": 0
  },
  "message": "200 OK",
  "status": "ok"
}
```

https://redfish.dmtf.org/schemas/ComputerSystem.v1_5_1.json has properties for these.
/redfish/v1/Systems/{ComputerSystemId}

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
@gtmills : Some questions that came up:
-- Initialized, Interval and Time Remaining - These properties were not found in standard Redfish.
-- The backend Host watchdog DBUS object only becomes available after we poweron. How do you think that needs to be handled in Redfish?
-- Who are the primary consumers of this API? I guess today it is the host over IPMI?

**Comment by gtmills** [comment]
@santoshpuranik 

> Initialized, Interval and Time Remaining - These properties were not found in standard Redfish.

Let's leave out for now. I will look at upstreaming to Redfish. 

> The backend Host watchdog DBUS object only becomes available after we poweron. How do you think that needs to be handled in Redfish?

If the Host watchdog D-Bus object is not available, I think the FunctionEnabled field of the WatchdogTimer would be set to false. When the D-Bus object is available this field would be true and the other properties available on the Watchdog D-Bus object would be set (e.g. ExpireAction,  called WatchdogTimeoutActions in Redfish)

> Who are the primary consumers of this API? 

This Redfish API will be used by end customers, tools (openbmctool, redfishtool), one day maybe the GUI

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by Alpana07** [comment]
Resolved By: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/19751
Resolved By: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/20308

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
I put this in the gerrit review:

```I have had this discussion with Santosh and Alpana before and putting it here.. Here are my thoughts.

The current Watchdog is aimed at timing the boot. It gets kick started during boot and then gets disabled after reaching certain point during boot when the IPMI message is sent downwards.

So attaching a user command for this watchdog does not look appropriate to me as this watchdog's purpose is not that. 

We need to first define what whatchdog are we really interested in to hook into redfish. Lets say, there is a tiny app that kind of does the watchdog with Host Linux after everything is up, then I think it's something we can hook onto Redfish. But definitely not the boot timed watchdog.```

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
@gtmills , any thoughts on comments made by @vishwabmc ? To me, another watchdog app to track host's boot would make little sense if we are doing the same with the existing one already (Hostboot vs Host Linux?)

Today, does the end user actually even control the watchdog via the REST APIs? I know it is possible to, but is there a real use case?

**Comment by gtmills** [comment]
After discussing on the phone today, moving out to OP950.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@Alpana07 Can we get these merged into master?

**Comment by vishwabmc** [comment]
@Alpana07 @santoshpuranik There was a commit from Intel https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/24532/ that added some of this. .They had a usecase ..

**Comment by Alpana07** [comment]
This feature is already added, with
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24532/
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25982/
So closing this issue.
