### ISSUE TITLE
GUI : Profile settings page - toast notifications

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2823]
## Expected Behavior
When the user saves the profile settings page, a toast notification should be displayed to the user.

## Actual Behavior
If there hasn't been a change to the state of the timezone display preferences, the call is not being sent to the backend and a toast notification is not being displayed to the user. This can cause confusion and violates the consistency and standards heuristics since the user is always presented with notifications when performing an action with the application.

## Steps to Reproduce the Problem

  1. Go to the Profile settings page
  1. Submit the form without making any changes
  

## Specifications
  - Browser: All
  - Version: N/A

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39186
