### ISSUE TITLE
GUI : FED : IBM Custom Nav Access Control name incorrect

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2825]
## Expected Behavior
The last navigation item in the primary navigation is Access Control.

## Actual Behavior
Access control is named configuration when setting `Custom_APP_NAV=true in the development .env file
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/0f65ac62-03c4-415b-873a-5a620bfb60cb)

## Steps to Reproduce the Problem

1. Open the .env.development.local file and add
    ```
    VUE_APP_ENV_NAME="ibm"
    CUSTOM_APP_NAV=true
    CUSTOM_STYLES=true
    ```
1. Restart the local dev instance
1. Login

## Specifications
  - Browser: ALL
  - Version: N/A

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39206
