### ISSUE TITLE
PLDM: Add pldmtool option for GetStateSensorReading

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2826]
Usage: pldmtool platform [OPTIONS] SUBCOMMAND

Options:
  -h,--help                   Print this help message and exit

Subcommands:
  GetPDR                      get platform descriptor records
  SetStateEffecterStates      set effecter states
  SetNumericEffecterValue     set the value for a PLDM Numeric Effecter

**Comment by SrideviRamesh** [comment]
Implemented and merged
