### ISSUE TITLE
GUI : FED : Back to top button appears above page contents

### ISSUE THREAD

**Issue by SurenNeware** [ibm-openbmc/dev#2827]
## Overview
The z-index of the back to top button needs to be adjusted when it is disappeared so that it will not come over the page contents.

<img width="147" alt="image (30)" src="https://user-images.githubusercontent.com/42602609/103089532-39539000-4614-11eb-84f8-75c90b33ae13.png">

## Steps to Reproduce the Problem
- [ ] Mouse hover over the same position where back to top button get appears.

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39274

**Comment by derick-montague** [comment]
I am confused what we are trying to do here. I will comment in Gerrit.
