### ISSUE TITLE
Responsive Design: Fix login screen orientation

### ISSUE THREAD

**Issue by ryanarnell** [ibm-openbmc/dev#283]
Login screen doesn't response well to different screen dimension and orientation for tablets. This task fixes that using by correcting the placement of the logo, login fields etc. like the following mockup 

![image](https://user-images.githubusercontent.com/4976631/51043261-e8ac0f00-1583-11e9-88dc-78a911957653.png)

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
With https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/17331/ patch 3, I see: 
![log-in-17331-3](https://user-images.githubusercontent.com/5455127/51211464-2938bf00-18db-11e9-951e-2c27a282f842.PNG)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ryanarnell** [comment]
That is the intension @gtmills  for widescreens we do not make the fields centered of the gray or white section. We still keep them relatively centered of the screen.

**Comment by rfrandse** [comment]
refresh

**Comment by ryanarnell** [comment]
This task has been completed with this push https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/17331/ 
The code has been merged on Jan 29th. Marking this as done

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
