### ISSUE TITLE
GUI : FED : Unit Test - Form File

### ISSUE THREAD

**Issue by SurenNeware** [ibm-openbmc/dev#2833]
## Overview
- [ ] Create a unit test for the form file component. Follow the testing guidelines of testing input and output

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
The form file component is basically a wrapper for a bootstrap-vue component. We don't need to test third-party components. Do you have an idea on what you want to test in this component?

**Comment by SurenNeware** [comment]
I wasn't aware about "We don't need to test third-party components".
