### ISSUE TITLE
Implement Redfish CPU throttling 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2840]
A requirement for eBMC is CPU throttling. #958 is adding this to Redfish. This is implementing whatever we get added.

**Comment by gtmills** [comment]
@marthabroyles Is this something you would own?

**Comment by gtmills** [comment]
The D-Bus interface is https://github.com/openbmc/phosphor-dbus-interfaces/blob/32304979b404c24e32f195d08c667e65b9b34695/org/open_power/OCC/Status.interface.yaml#L15

**Comment by rfrandse** [comment]
tracking in jira
