### ISSUE TITLE
GUI : FED : Update security settings text

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#2842]
## Overview
- [ ] Update text for BMC shell and network IPMI. Updates were made based on user feedback https://github.com/openbmc/webui-vue/issues/5#issuecomment-753891493

## Invision Mockup
****New prototype** - _changes are underlined in red._
![AE766854-959D-43BB-BA72-6B2E9E997578](https://user-images.githubusercontent.com/61419136/105348100-d6064f00-5c0d-11eb-9379-adbbe2cd0fa7.jpeg)

**Old prototype - for comparison**
![Screenshot_2021-01-21 100585963-6d3cdd80-3314-11eb-932d-04466360c239 jpg (JPEG Image, 1366 × 922 pixels)](https://user-images.githubusercontent.com/61419136/105348175-f33b1d80-5c0d-11eb-945a-89974c83d839.png)

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39835

**Comment by derick-montague** [comment]
@dixsie @ParishrutB This story calls for updating both BMC Shell and Network IPMI. However, I don't see any change to the copy for Network IPMI. @ParishrutB can you verify that no change is needed?
