### ISSUE TITLE
PLDM: Add no-snooping support to phosphor-host-postd

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2843]

**Comment by sampmisr** [comment]
Currently the the snooping daemon, will only start if it sees the lpc-snooping port on the bmc system,
	on IBM Systems the progress codes come down via pldm & we need to add a compile time option to make sure
	the snoopd daemon will still host the dbus objects for us even when the snoop port is not found.

**Comment by manojkiraneda** [comment]
Pushed for an initial review : https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-host-postd/+/40729

**Comment by manojkiraneda** [comment]
code is merged upstream.
