### ISSUE TITLE
PLDM: Design the PLDM model to support Capacity on Demand Feature

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#2845]

**Comment by sampmisr** [comment]
This epic will accomplish two tasks:
1. change the fileio commands to support new parameters (refer fileio box note)
2. implement the COD feature via fileio

**Comment by sampmisr** [comment]
genesis boot: no license info is shown - that means pldm does not create any DBus object
later after pon phyp sends the license files and pldm creates DBus objs if it does not exist. and delete an obj if that entry goes missing from the json
on subsequent boots pldm just updates the status of the license objects 
what happens after a bmc RR: does Phyp sends down the license or bmc asks for the license? - Phyp sends down
the DBus objects will be persisted with all attributes apart from the status
so after a rr bmc will( mark the state of licenses as unavailable) and then rely on Phyp to send down the license file and update the status of the licenses  
when host goes off: the status of the license becomes unavailable - done by pldm 
the DBus objects need to be sustained across reboot - needs serialization or we will keep a binary dump of the json file and when pldmd comes up, it calls the same function to parse the json file and create DBus objects. that saves time
