### ISSUE TITLE
GUI : FED : Update Vue cli node modules

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2847]
## Overview
Update the following components to the latest release.

Run `npm outdated` to get the current release. At the time of this story creation the current version if 4.5.10.

- `@vue/cli-plugin-babel`
- `@vue/cli-plugin-eslint`
- `@vue/cli-plugin-router`
- `@vue/cli-plugin-unit-jest`
- `@vue/cli-plugin-vuex`

## Test
- [ ] Builds successfully
- [ ] Unit tests pass
- [ ] Spot test 3 pages to verify functionality has not been impacted.

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39747
