### ISSUE TITLE
GUI: Responsive Design:  layout in tablets 

### ISSUE THREAD

**Issue by ryanarnell** [ibm-openbmc/dev#285]
Our design team researched users to find out if users are using OpenBMC GUI in their mobile devices like tablets or phone. We found that some of our users do use their company assigned tablets in their labs. They expressed interest using our GUI in those devices. We decided to extent content support to most commonly used tablets with our clients. 

~The lowest resolution we plan to support is 1024*768 in both portrait and landscape orientation. Of course tablets resolution higher than this should scale accordingly and we plan to test on those tablets as well.~ 

Data is being gathered to determine our minimum supported viewport size.

![screen shot 2019-01-11 at 9 55 11 am](https://user-images.githubusercontent.com/4976631/51049353-3b40f780-1593-11e9-9b95-2b5af47b3aa2.png)

**Comment by mzipse** [comment]
test

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@nicoleconser @ryanarnell - Where are we in determining the smallest viewport size we are supporting? Once that is done, we will need to look at #527.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
I am going to close this story since there is no ongoing work at this time. It is something we need to determine, but at this point it is not being actively researched. We have data that was gathered during user research that we can discuss if/when needed.

**Comment by rfrandse** [comment]
refresh
