### ISSUE TITLE
libekb and op-proc-control : Enable procedure callout

### ISSUE THREAD

**Issue by RameshIyyar** [ibm-openbmc/dev#2850]
Currently procedure callout support not in place for phal but, recently `p10_setup_ref_clock` procedure enabled procedure callout. So, need to enable that support in libekb and openpower-proc-control and also need to make sure in pel as well.

**Comment by ojayanth** [comment]
Advanced RAS related support , updating milestone accordingly.

**Comment by ojayanth** [comment]
Discussion in progress related to FAPI procedure handling in BMC side.

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/q/topic:%22PROC_CALLOUT%22+(status:open%20OR%20status:merged)

**Comment by ojayanth** [comment]
https://github.com/open-power/libekb_p10/pull/4
