### ISSUE TITLE
eBMC State Management - Support to move Hypervisor from Standby to Runtime

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2856]
IBM systems have a hypervisor called PHYP. PHYP has different states it can be in (Safe/Standby, Setup, Runtime). When the users selects to have PHYP stop in Safe/Standby state, they then need a way to tell the hypervisor to move from that state to Runtime.

This story tracks the work to provide this support.
- New phosphor-dbus-interface to track and control hypervisor state
- phosphor-state-manager support to host new PDI object and manage properties
- bmcweb support to add new state and control to redfish v1/Systems/hypervisor object
- pldm support to monitor new PDI object and set appropriate effecters to host

**Comment by geissonator** [comment]
PDI Proposal: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/39687

**Comment by mzipse** [comment]
@geissonator , I believe we have this closed too but your work must be under a different commit.  Can you update and close?

**Comment by geissonator** [comment]
All code merged and in under https://gerrit.openbmc-project.xyz/q/topic:%22hyp-state%22+(status:open%20OR%20status:merged)
