### ISSUE TITLE
GUI : FED : Change System IndicatorLED property to use LocationIndicatorActive

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2864]
## Overview
Update SystemStore to use `LocationIndicatorActive` instead of `IndicatorLED` property

- [SystemStore](https://github.com/openbmc/webui-vue/blob/master/src/store/modules/Health/SystemStore.js#L19)

Will need to include mapping on frontend to show an accurate state instead of a boolean value. False => 'Off', True => 'On'

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40052
