### ISSUE TITLE
GUI : FED : Change Power IndicatorLED property to use LocationIndicatorActive

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2865]
## Overview
Update PowerSupplyStore to use `LocationIndicatorActive` instead of `IndicatorLED` property

- [PowerSupplyStore](https://github.com/openbmc/webui-vue/blob/master/src/store/modules/Health/PowerSupplyStore.js#L32)

Will need to include mapping on frontend to show an accurate state instead of a boolean value. False => 'Off', True => 'On'

- Blocked until[ Power supply moves to new Power / Thermal](https://ibm-systems-power.slack.com/archives/GQR6QQXT8/p1611077056003800?thread_ts=1611067206.000400&cid=GQR6QQXT8)

**Comment by dixsie** [comment]
Work being done in #3028
