### ISSUE TITLE
Dump: Hostboot dump - Create hostboot dump on host watchdog timeout

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2866]
This story tracks enhancing the existing watchdog_timeout application to support (via a config option?) the following:

- Create PEL and get PLID
- Call new Dump Create interface and pass it PLID and request hostboot dump
- Wait for dump to complete and then exit process so normal quiesce handling path will start

**Comment by geissonator** [comment]
https://github.com/ibm-openbmc/dev/issues/1414 tracks moving over to PLDM for the watchdog and will need to be in place before we can have this function working end to end.

**Comment by sampmisr** [comment]
pls track #3040

**Comment by geissonator** [comment]
The current code this story will need to manipulate is here: https://github.com/openbmc/openpower-debug-collector/blob/master/watchdog_timeout.cpp

Here's the proposal on break down of this story:
- Convert https://github.com/openbmc/openpower-debug-collector to meson
- Create error utilizing PEL interface (and corresponding registry entry)
- Call the new Hostboot dump create interface, and wait for it to complete (passing in PEL id)

Once watchdog_timeout exits, it will trigger the obmc-host-quiesce.target (and the system recovery from there automatically)

There should be some hw-diagnostic code to look at that does something similar when a checkstop is detected.

**Comment by geissonator** [comment]
For converting to meson, there are a lot of examples of other repos doing it:
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/27873 is the start of a series of commits for doing it in state manager
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/42359/ is a series of commits for phosphor-logging (a more complex repo)

A search in gerrit should pop quite a few others up as well if needed for reference.

**Comment by geissonator** [comment]
https://grok.openbmc.org/xref/openbmc/docs/host-management.md?r=b41aff0f#255 has some background on the host watchdog and the parts involved.

**Comment by geissonator** [comment]
Code - https://gerrit.openbmc-project.xyz/c/openbmc/openpower-debug-collector/+/44354

**Comment by mzipse** [comment]
Work is complete.  Closing.
