### ISSUE TITLE
PFP::sensor-monitoring - Invalid ambient temp sensor error logging

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2867]
Legacy requirements say to log errors when any of the 3 ambient sensors have a reading of outside of 0 and 100.  At this time, I do not know where this code would be implemented.

As far as logging errors due to failed sensor reads, that would be handled by the code that does it for all the dbus-sensors using https://github.com/ibm-openbmc/dev/issues/2146 (there may be a way to do this where the code lives outside  of dbus-sensors and just watches for NaN/Functional.)

**Comment by msbarth** [comment]
Maybe the new thermal monitoring app could handle logging errors for the out-of-range ambient sensors?

**Comment by msbarth** [comment]
Should be able to contain this within config file changes to the sensor-monitoring app.

**Comment by derekhoward55** [comment]
@mikecgithub is this something you could pickup?  apparently just need to add the thresholds to the 3 ambient temp sensors...

**Comment by msbarth** [comment]
@spinler Is this covered with this section the EM config(ex Storm King) -> https://github.com/ibm-openbmc/entity-manager/blob/1020/configurations/Storm%20King.json#L25-L34
Where just the error logging is missing?

**Comment by msbarth** [comment]
Quick glance at phosphor-virtual-sensor seems that values outside of `MaxValidInput` or `MinValidInput` should log an error ?

**Comment by spinler** [comment]
The thresholds need to go on the underlying temp sensors in that file.

**Comment by msbarth** [comment]
Looks like you're not able to use `Thresholds` on the devices with more than one sensor, i.e. DPS310, since the threshold gets applied to both sensors. When I attempted to split the ambient from the pressure on the DPS310 so the threshold would only get applied to the ambient, it doesnt appear the pressure gets put onto dbus by the HwmonTempSensor service any longer (even though they both show up in the `/var/configuration/system.json`).

**Comment by spinler** [comment]
Would this help? https://gerrit.openbmc-project.xyz/c/openbmc/dbus-sensors/+/51366

**Comment by msbarth** [comment]
Yes..obviously not wanting to hard-code "indexes" but that's the exact issue I'm seeing since I only want the thresholds applied to one of the sensors

**Comment by msbarth** [comment]
Guess I'd rather see the number after `Name` be used to associate to thresholds instead of arbitrary index numbers like that commit since that code mentions the number associates to the sysfs filename #

**Comment by msbarth** [comment]
We need that fix included in a bump to dbus-sensors for this issue to get resolved.

**Comment by msbarth** [comment]
Verified the threshold interfaces show up correctly on just the ambient sensors if we bump dbus-sensors to include https://gerrit.openbmc-project.xyz/c/openbmc/dbus-sensors/+/51366

**Comment by msbarth** [comment]
Resolved by https://github.com/ibm-openbmc/entity-manager/pull/24

**Comment by spinler** [comment]
Merged.
