### ISSUE TITLE
Create thermal sensors 

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2869]
Create pdrs for the thermal sensors for bmc . Refer https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/39704.
The dbus backend will not be created until host is up. Verify the GetStateSensor command when host is up. Check pldm behavior when GetStateSensor is issued via tool and host is not up. The pdrs should be created in both the cases

**Comment by spinler** [comment]
Hi @sampmisr, does this refer to this JSON, or other sensors? https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/39704

**Comment by manojkiraneda** [comment]
Hi @spinler , this change is generic for all the sensors. 

With this change, we will be creating the PDR's even when the dbus backend does not exist. and also the getStateSensor command on these sensors whose dbus backedn is not available will return a PLDM_SENSOR_UNAVAILABLE as the sensor operational state.

Resolved by :
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/40011/3
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/39797/13

**Comment by manojkiraneda** [comment]
Both commits are merged upstream.
