### ISSUE TITLE
Redfish: LEDs (system, chassis, fan, power supply LEDs)

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#287]
Need to get `led/physical/<led>` (e.g. `/xyz/openbmc_project/led/physical/fan0`) into Redfish. 
Fan, Chassis, Server, power supplies redfish schemas all have an IndicatorLED property. 

This story only tracks getting system, chassis, fan, power supply physical LEDs into Redfish. 
We have a concept of a group LED, `/xyz/openbmc_project/led/groups/dimm15_fault`, which is not an actual LED but maps to an actual LED, going to exclude those for now.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by antwil** [comment]
Resolved by:
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/24110/

**Comment by gtmills** [comment]
Merged.
