### ISSUE TITLE
GUI : FED : Create unit test for progress indicator component

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2870]
## Overview
Write a unit test against the progress indicator component's API based on unit testing best practices.

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A
### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
N/A

### Accessibility Tests
N/A

### Test Hooks
N/A

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39940

**Comment by yoshiemuranaka** [comment]
No longer creating ProgressIndicator component
