### ISSUE TITLE
PFP::presence - Handle no JSON configuration loaded at poweron

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2872]
Need to handle where no JSON configuration has been provided/loaded by the time the system is powered on. This would be where no override, default, or compatible JSON config file for the machine is found on the BMC's filesystem.

**Comment by spinler** [comment]
@msbarth Was it decided the other day that this won't be necessary, and it should just wait forever?

**Comment by msbarth** [comment]
This is a general issue that we still need to handle for the override and default config file cases.

For the case of the compatible interface provided JSON file, we should wait forever.

However, for users that do not use the compatible interface, work needs to be done to log an error (or halt any poweron?) when the system is powered on and no config file was found by that time.

**Comment by msbarth** [comment]
In addition, there's a bug in fan presence now with the removal of the _match.reset()'s in json_config.hpp where fan presence core dumps now after entity manager is stopped and then started at bmc standby and then the system is chassis on'd

I think fan presence app may not be fully clearing its prior config and reloading things correctly..then needs to be fixed to not reload its config under this scenario where entity manager is restarted.

**Comment by spinler** [comment]
Looks like  `JsonConfig::start()` gets called on InterfacesAdded signals from the compatibility interface, so we would just need to skip running the body of that function if we've already run it once.

**Comment by rfrandse** [comment]
tracking in jira
