### ISSUE TITLE
GUI : FED : Remove account type assignments from privilege role table

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2873]
## Overview
The account type access that is listed in this table is incorrect and needs to be removed. This information will be displayed in the user table when it is available in Redfish. This work is planned in #2550.

## UX Flow / Interaction Requirements
- [x] Remove section from user table
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/0482c1c6-688c-408c-9da0-55da4f276f16)

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
N/A

### Accessibility Tests
N/A

### Test Hooks
N/A

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40025
