### ISSUE TITLE
Function No. 74 - CE login

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/dev#2875]
This function opens a time window when the Service Rep can upload their access control file (ACF) to the BMC without needing Admin access to the BMC. The “allow ACF upload” function is needed to support the Service Rep’s ability to recover the admin password.
Requester: Joseph Reynolds.    
Mode:?
Debounce needed:?
Function number: 74  is to be used

**Comment by joseph-reynolds** [comment]
Here are some ideas about this function.
- What is an appropriate time window?  30 minutes?
- The time window should close after an ACF is successfully uploaded.  Note that an ACF upload is successful only if it signed by the IBM service organization, applies to that specific BMC, etc.
- The fact that the time window is open must be communicated (probably via D-Bus, for example: AllowUnauthenticatedACFUpload: boolean) to the BMCWeb server so it can decide whether to allow unauthenticated ACF uploads.
- We may also need to communicate the fact that the time window is open via a REST API so the web application can provide the "upload ACF" function from the login screen.

**Comment by joseph-reynolds** [comment]
Is there a way to test this function without a physical OpPanel and without the need to be physically present?  For example, if the OpPanel ultimately produces D-Bus events, can we use `busctl` commands to simulate that an OpPanel was hot-plugged into the BMC and then OpPanel function 74 was used?  (Asking for the test team.)

**Comment by jinuthomas** [comment]
I have not. yet started on this will need to look at how it can be done

**Comment by joseph-reynolds** [comment]
There are thoughts that this (an some other) function should display the system serial# so a physically present operator can read the serial number which is  needed to generate the ACF.
