### ISSUE TITLE
Create BMC PDRs dynamically when the D-Bus object shows up

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2876]
the pdr will not be created if dbus is not present. pdr will be created when the dbus interface is added.

for testing:
have an entry in sensor json which does not have a D-Dbus object created. The pdr should not show up when doing a GetPDR.Later create the D-Bus object and the PDR should be created. GetPDR should return the newly created PDR. GetStateSensorReadings should return the sensor

Current design is creating the PDR even if D-Bus is not present. And doing a call to GetStateSensorReadings would return PLDM_SENSOR_UNAVAILABLE

**Comment by sampmisr** [comment]
A follow up of this story would be to intimate Host about new PDRs. Probably a pdr exchange event

**Comment by lxwinspur** [comment]
review by: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/40375

**Comment by manojkiraneda** [comment]
There seems to be a miss understanding on the approach & the intent behind this story.

This should be the example flow:

- For example, if we have PDR json with an object path `/xyz/openbmc_project/foo`. and when ever we get GETPDR command, we should generate the PDR only when the object path is found on the dbus.

- If the object path is not found, then pldm should register the watcher code that will watch out for dbus Interface Added Signal from `/xyz/openbmc_project/foo`

- When the `/xyz/openbmc_project/foo` get added on to dbus by another service , it generates an Interface Added Signal on to dbus, and once pldm receives that signal it should automatically generate the PDR.

**Comment by Pavithrab7** [comment]
commit review - https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/44041

**Comment by nmuruli** [comment]
We attempted this change and this required changes for HB . Its a complex change and we do not want to spend time on this activity
