### ISSUE TITLE
Support a system reboot once inband code update is  completed successfully

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2878]
PHYP needs to send a single PLDM command once inband code update has completed. That command must do the following on the BMC 
Power off PHYP and the chassis
Set the power restore to reboot the host once the BMC is rebooted
Reboot the BMC

To achieve this:
bmc-pldm will create an oem bmc effecter with the following:
entity type: 45(system chassis) 
state set id: 260 (system power state)
state : 6(power cycle hard)

after bmc sends an end update successful event(already happening in current flow), Phyp will set this new effecter.
Upon getting the setStateEffecter call bmc-pldm does the following:
1. Set the power restore to reboot the host once the BMC is rebooted(Will hear from Andrew)
2. power off Phyp and Chassis (setting dbus prop "xyz.openbmc_project.State.Chassis.Transition.Off"   and "xyz.openbmc_project.State.Host.Transition.Off") 
3. reboot the bmc (setting D-Bus prop "xyz.openbmc_project.State.BMC.Transition.Reboot")

Can be unit tested via pldmtool

**Comment by sagisin** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/40421
