### ISSUE TITLE
GUI : FED : Test Hooks - Client Sessions page

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2879]
## Overview
- [ ] Add the `data-test-id="clientSessions-input-search"` to the search box on the client sessions page
- [ ] Add the `data-test-id="clientSessions-button-disconnect"` to the search box on the client sessions page

**Comment by sandeepasingh116** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40384
