### ISSUE TITLE
GUI : FED : Test hooks - Security settings

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2880]
## Overview
Add a test hook to each of the security setting toggle components.

- [ ] Add the `data-test-id="security-toggle-bmcShell"` to the search box on the client sessions page
- [ ] Add the `data-test-id="security-toggle-networkIpmi"` to the search box on the client sessions page

![image](https://user-images.githubusercontent.com/1183515/106652197-b1d63680-655a-11eb-8404-270ed919ae36.png)

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40381
