### ISSUE TITLE
GUI : FED : Test hooks - Power server operations

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2881]
## Overview
Add a test hook to the following elements

- [ ] Add the `data-test-id="powerServerOps-text-hostStatus"` to the `<dd>` element for Host status
- [ ] Add the `data-test-id="powerServerOps-text-lastPowerOp"` to the `<dd>` element for Last power operation

![image](https://user-images.githubusercontent.com/1183515/106652587-493b8980-655b-11eb-9768-3dfe6e7b8f95.png)

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40675
