### ISSUE TITLE
GUI : FED : Test hooks - Event logs

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2882]
## Overview
Add a test hook to the following elements

### Search box
- [ ] Add the `data-test-id="eventLogs-input-search"` to the search element

![image](https://user-images.githubusercontent.com/1183515/106653943-12667300-655d-11eb-8ae1-1f100e14e470.png)

### Delete log confirmation modal delete button
- [ ] Add the `data-test-id="eventLogs-button-confirmDelete` to the delete log confirmation modal delete button

![image](https://user-images.githubusercontent.com/1183515/106655101-89e8d200-655e-11eb-8537-848bada304e1.png)

**Comment by sandeepasingh116** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40418
