### ISSUE TITLE
GUI : FED : Test hooks - Sensors

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2883]
## Overview
Add a test hook to the following elements

- [ ] Add the `data-test-id="sensors-input-search"` to the search element
- [ ] 
![image](https://user-images.githubusercontent.com/1183515/106654129-55c0e180-655d-11eb-902e-a7f6213305ba.png)

**Comment by sandeepasingh116** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40483
