### ISSUE TITLE
GUI : FED : Test hooks - Overview

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2884]
## Overview
Add a test hook to the following elements

- [ ] Add the `data-test-id="overview-text-bmcTime"` to the `<dd>` element

![image](https://user-images.githubusercontent.com/1183515/106654692-13e46b00-655e-11eb-9405-8d237cd54546.png)

**Comment by sandeepasingh116** [comment]
Resolved by https://github.com/ibm-openbmc/dev/issues/2884
