### ISSUE TITLE
GUI : FED : Test hooks - SSL certificates - alternate name field

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2885]
## Overview
Add a test hook to the following elements

- [ ] Add the `data-test-id="sslCert-input-altName"` to the  input element

![image](https://user-images.githubusercontent.com/1183515/106655609-362ab880-655f-11eb-9a8e-0699e2aea41d.png)

**Comment by sandeepasingh116** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40571
