### ISSUE TITLE
GUI : FED : Client Sessions - Incorrect data displayed

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2886]
## Expected Behavior
The ID column should display the ClientID and the IP Address column should display the ClientOriginIPAddress.

## Actual Behavior
The ID column displays the ID that is used to retrieve the results and the IP Address is dislaying the Client ID.

## Steps to Reproduce the Problem

  1. Login to the GUI
  1. Navigate to Access Control > Client Sessions
  1. Verify the data in the response with the data being displayed

## Specifications
  - Browser: N/A
  - Version: N/A

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40290
