### ISSUE TITLE
GUI : FED : Firmware - minimum code version

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2889]
## Overview
Add minimum firmware version required on firmware page. If minimum fw version **_not_** available show `--`

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Continuation of #1627 

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

### Screenshots
![Screen Shot 2021-02-03 at 1 10 33 PM](https://user-images.githubusercontent.com/8097306/106811061-a5b5ac00-6622-11eb-866e-59368f856682.png)

If n/a
![Screen Shot 2021-02-03 at 1 20 00 PM](https://user-images.githubusercontent.com/8097306/106811081-ab12f680-6622-11eb-99c5-22f2b7802ebd.png)

**Comment by rfrandse** [comment]
tracking in jira
