### ISSUE TITLE
Redfish: Power EfficiencyPercent

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#289]
Need `control/power_supply_attributes/attr/DeratingFactor` to
`/redfish/v1/Chassis/chassis/Power/EfficiencyPercent`

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Code will sit on top of Shawn's code for 291. https://github.com/ibm-openbmc/dev/issues/291

**Comment by msbarth** [comment]
What does "sit on top of" mean exactly? Is there a direct dependency with what's being done for #291? Could you please clarify?

**Comment by gtmills** [comment]
@msbarth EfficiencyPercent is under PowerSupply in the Power schema. https://redfish.dmtf.org/schemas/v1/Power.v1_5_3.json
Shawn is moving the PowerSupplies to the power schema. And since EfficiencyPercent is a property of those "moving" PowerSupplies this code will have a dependency on his code.

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24475

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24475 merged
