### ISSUE TITLE
GUI : Firmware Update - Enhancements

### ISSUE THREAD

**Issue by nicoleconser** [ibm-openbmc/dev#2891]
Enhancements to #1627 that did not make it into the MVE. 

## Enhancements
- During testing, several users incorrectly thought that they needed to **manually** copy the Running image over to the Backup slot **before** starting a firmware update. I assume this is because those actions are located higher up on the page than the actual FW update section. How can we make it clear that this takes place automatically? One idea is to move the "Copy to backup" and "Switch with running" actions out of the cards, below the Firmware update section. 
- Find out if the **View progress codes** feature applies to the BMC, or only the server. If you cannot see progress codes for BMC processes, how else can we indicate to the user that the Firmware update is still in progress, since it involves both the Server and BMC? (FW update process can take anywhere from 6 - 30 mins) 
- Review **Host vs server vs CEC vs system vs OS** terminology for consistency & accuracy 
- ? 

## References
- [Latest round of Usability testing in Feb 2021](https://ibm.box.com/s/il1nee02jz68806a4pgzkrj3bhh4ec2a)

**Comment by rfrandse** [comment]
tracking in jira
