### ISSUE TITLE
Reduce multiple oem_ibm entry points in pldmd

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2894]
There was a comment on pldmd.cpp:

Why do we really need multiple OEM_ flags and passing around of handlers from OEM to standard and vice versa? Can this be:
#ifdef OEM_IBM
createOEMIBMHandlers(<pointers to standard handlers>)?
#endif
That way this file will not bloat up with OEM code.

**Comment by sampmisr** [comment]
create a new file which will create all oem handlers and there will be a single entry point in pldmd.cpp for oem_ibm

**Comment by derick-montague** [comment]
Should this be a 212.8 or a 2.13.8?

**Comment by lxwinspur** [comment]
review by: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/44271

**Comment by rfrandse** [comment]
tracking in jira
