### ISSUE TITLE
PFP::monitor - Add configuration option to immediately mark a fan functional upon being replaced

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2898]
Instead of fan monitor waiting for a fan to come back into specs after being replaced, a configuration option should be added to immediately set a fan to functional upon replacing it. Then if the fan never actually returns to within spec in the configured time, the fan would then be re-marked as nonfuncitonal.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/41691

**Comment by spinler** [comment]
Merged.
