### ISSUE TITLE
Redfish: Power PowerMetric

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#290]
sensors/aggregation/per_30s/ps*_input_power/average and sensors/aggregation/per_30s/ps*_input_power/maxium map to /redfish/v1/Chassis/chassis/Power/PowerMetric

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Some initial notes on integrating these sensors into bmcweb
1. Under the /org/open_power object path (and interface)
    - Openpower specific
    - No noticeable plugin structure to bmcweb for power interfaces outside of `xyz.openbmc_project.`
2. Average & Maximum value properties are an array of timestamp-to-value
    - Specific calculations necessary to conform to Redfish that may not align with other BMC systems

**Comment by msbarth** [comment]
A design doc has been proposed along with its accompanying dbus interfaces
Design doc: https://gerrit.openbmc-project.xyz/23493
Dbus interfaces: https://gerrit.openbmc-project.xyz/23405

**Comment by msbarth** [comment]
Changes for the IBM OP940 branch are in review -> https://gerrit.openbmc-project.xyz/24002

**Comment by msbarth** [comment]
PR : https://github.com/ibm-openbmc/bmcweb/pull/23

**Comment by msbarth** [comment]
PR merged into OP940

**Comment by gtmills** [comment]
@msbarth What about the long term plan for this? I think we should either close this issue and open another or don't close this issue.
