### ISSUE TITLE
GUI : FED : Browser refresh after using skip to content button 404s

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2901]
## Expected Behavior
Refreshing a page after clicking the skip to content button will update the page

## Actual Behavior
Refreshing a page after clicking the skip to content button redirects to a 404 error

## Steps to Reproduce the Problem

1. Login
1. Tab to set focus on the `skip to content` button
1. Click or use the space bar to navigate
1. Refresh the page

## Specifications
  - Browser: All
  - Version: N/A

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40610
