### ISSUE TITLE
phosphor-regulators: Support Rainier pass 2 hardware changes

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#2902]
The hardware team recently made changes to the Nisqually planar on Rainier systems.  The old version was pass 1/0z.  The new version is pass 2/1z.  There are some voltage regulator changes in pass 2/1z.

## Identifying the regulator changes in Pass 2
I am aware of the following changes:
* The AVDD regulator changed from 8-bit address 0x48 to 0xE2.  I think it is a new type as well (different mfg/model).
* The Flett regulators are now behind a MUX.  Some may also have new addresses, as they were previously using addresses at the high end of the byte range that are reserved in the I2C specification.

There may be other changes as well.  The latest Rainier workbook should be a good initial source of information.  Ruby Zgabay (Martinez), Abey Mathew, and Justin Henspeter should be able to provide the complete list of changes.

In preparation for modifying the JSON configuration file, we also obtain the following information from the hardware team:
* Will there still be pass 1 systems in the lab that we need to support?  Assuming yes.
* How can we tell whether we are on a pass 2 system?  VPD lookup?  If it is not a VPD keyword that is mapped to a standard (non-IBM-specific) D-Bus interface, can we determine this from a regulator register instead?
* What level of support must be provided for pass 1 hardware if an I2C bus or address has changed?  Can we ignore the pass 1 regulator and only perform configuration/monitoring if it is a pass 2 regulator?  Or do we have to support both?

## Verifying ability to read/write through the MUX
The phosphor-regulators application uses the Linux i2c-dev support to communicate directly with the regulator devices.  So far that communication has not (to my knowledge) been routed through a MUX.

With pass 2, the Flett regulators will be behind a MUX.  We need to verify the following:
* The MUX has been defined correctly in the device tree for all Rainier types (2S4U, 2S2U, and 1S4U).
* Stable bus numbers are defined in the device tree for each of the bus segments behind the MUX.
* i2c-dev can read and write to the device through the MUX.  Specify the bus number defined for the MUX in the device tree and the I2C address of the device from the workbook.  This should be tested on real pass 2 hardware.
  * Note: The i2cget and i2cset commands on the BMC also use i2c-dev, so they can be used for initial testing.

## Verify whether Simics is modeling pass 1 or pass 2
* Ask the Simics team what their plan is.
* If they are modeling pass 2, make sure all the regulator changes will be in the new model.
* If they are modeling pass 1, verify that the updated JSON file will still work without errors in Simics.

## Update Rainier JSON configuration file
* Modify bus numbers and I2C addresses of voltage regulator devices (comments and i2c_interface objects).
* If any regulators changed type (mfg/model), update comment by device object to reflect change.
* Add rule to determine if we are on a pass 2 system (if needed).  Probably will involve a compare_vpd action.
* Update presence_detection objects for regulators that have a changed bus or address.  Use the new rule that determines whether we are on a pass 2 system.
* Test updated file
  * In Simics
  * On pass 1 Rainier systems
  * On pass 2 Rainier systems
* Review changes with Ruby/Abey.

**Comment by msbarth** [comment]
FWIW, I had to deal with i2c mux's on Everest for the fan controller(MAX31785) and the fan presence detects(PCA9552) where the dts provides the i2c aliases that you can then access in userspace. Since the phosphor-regulators app is essential the "device driver", setting up the i2c aliases thru the dts and not bind it to a kernel device driver should result in those aliases still being accessible in userspace that your app could be configured to bind to.

I dont believe the Everest dts is upstreamed yet, but here's my entry for hwmon to bind the driver and access the MAX31785 -> https://github.com/openbmc/openbmc/commit/d31ef576e206582ac9a40f080782ee3699dd3b68#diff-8888b566b9f97808a8434ce3f279a51caceadd776907ae36bb98c03db9cb4c20R79

**Comment by smccarney** [comment]
Thanks Matt!

Initially Brad Bishop thought I would need to do the following:
* Learn how the device driver maps the MUX channels to files/directories in /dev
* Update JSON config file format to support specifying the MUX channel for devices behind a MUX
* Write code to map a channel to the /dev path that can be used for the bus path for user space I2C communication

However, Brad recently did some investigation on work being done to add the MUX to the Rainier device tree.  It looks like there are going to be stable bus aliases to the bus segments provided by the MUX.  If this holds true, then no JSON or C++ changes are required to support this.  I'll just need to copy the MUX provided bus name/number into the JSON config file.

I'm using this issue to track the effort regardless of how it ends up being resolved.

**Comment by spinler** [comment]
Merged with https://github.ibm.com/openbmc/phosphor-power/commit/924f32ec48ce23713013481135d6858557ae740c
