### ISSUE TITLE
PFP::presence - Log error when method of fan presence detection fails

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2903]
Detection of a fan being present can be done using more than one method (i.e. GPIO & tach feedback != 0) but one of those methods may be broken resulting in only the remaining method of presence detection being available. When one of those methods fail to be accessed or that method returns that the fan is not present (i.e. fan not plugged in fully resulting in the GPIO detection method thinking the fan isnt present but a valid tach feedback exists) the configuration should allow that an error log get posted noting that method of fan presence detection may not be functioning properly.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/42519
