### ISSUE TITLE
GUI : Redfish push alerts

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2904]
## SME
**BMC**: @ratagupt 
**RAS**:
**PHYP**:

### Summary
A select number of redfish alert have been implemented downstream. There is discussion in Gerrit about upstreaming. This story is related to #1288, which will be the first section added to a new alerts page. The assumption is that a new alerts page will contain SMTP traps and Redfish push notifications. 

#### Background
- [ ] TBD

#### End users
- [ ]  TBD

#### User Needs
- [ ] TBD

#### User Quotes
- [ ] TBD

### References
- Discovery folder](https://ibm.box.com/s/78peorqemojmbtkagvyqbr2eplfv8n4f)
- Email from Todd Rosedahl on August 5th (@priyanka-pillai97, @ParishrutB, @nicoleconser, @gtmills, and @derick-montague all included)

### User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

### Use Case(s)
- [ ] Add use case(s)

### Design Goals
- [ ] Goal 1
- [ ] Goal 2
- [ ] Goal 3

### InVision Prototype
For feature validation: https://ibm.invisionapp.com/d/main#/console/15366764/319741955/preview

### Community
- [ ] Created design review story in webui-vue repo
- [ ] Sent email to community sharing the design review story

### UX Flow / Interaction Requirements
- [ ] Feature breakdown

### cURL Commands and Redfish Response
 - https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599/8//COMMIT_MSG#40
`^^ more info here also`
```
curl -k -H "X-Auth-Token: $token" -X POST https://${bmc}/redfish/v1/EventService/Subscriptions -d '{"Destination": "http://192.168.31.30:58", "SubscriptionType": "SNMPTrap", "DeliveryRetryPolicy": "TerminateAfterRetries", "Protocol": "SNMPv2c"}'
```

### Notes
- Backend Gerrit Review: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/30575

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by sandeepasingh116** [comment]
Completed in downstream. Will re-open if required in upstream. FYI @mzipse
