### ISSUE TITLE
GUI : FED : Toast notification enhancements

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2905]
## Overview
Enhance the existing BVToastMixin to include multi-lined toast body, timestamps, and actions.

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

### Screenshots
Following general patterns from [Carbon Design System Notification](https://www.carbondesignsystem.com/components/notification/usage)
![Screen Shot 2021-02-09 at 7 45 08 AM](https://user-images.githubusercontent.com/8097306/107388505-c52d5880-6aaa-11eb-8943-a9cce4ba513e.png)

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40446/2
