### ISSUE TITLE
GUI : FED : Look for TFTP  in allowableValues from UpdateService 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2906]
## Overview
Should only show the TFTP button if TFTP is in the allowableValues:
```
curl -k https://$bmc/redfish/v1/UpdateService
{
  "@odata.id": "/redfish/v1/UpdateService",
  "@odata.type": "#UpdateService.v1_4_0.UpdateService",
  "Actions": {
    "#UpdateService.SimpleUpdate": {
      "TransferProtocol@Redfish.AllowableValues": [
        "TFTP"
      ],
      "target": "/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate"
    }
  },

```

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40526
