### ISSUE TITLE
GUI : FED : The GUI could dynamically determine which firmware images are supported on the system

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2907]
## Overview
Inspect all firmware 
BMC images will have `/redfish/v1/Managers/bmc`
```
 curl -k https://$bmc/redfish/v1/UpdateService/FirmwareInventory/4e9a7908
{
  "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/4e9a7908",
  "@odata.type": "#SoftwareInventory.v1_1_0.SoftwareInventory",
  "Description": "BMC image",
  "Id": "4e9a7908",
  "Members@odata.count": 1,
  "Name": "Software Inventory",
  "RelatedItem": [
    {
      "@odata.id": "/redfish/v1/Managers/bmc"
    }
  ],
  "Status": {
    "Health": "OK",
    "HealthRollup": "OK",
    "State": "Enabled"
  },
  "Updateable": true,
  "Version": "fw1020.00-14.5-0-ge3e72e883"
}
```
System images will have `/redfish/v1/Systems/system/Bios` The GUI will know to show the 4 cards 
```
{
"@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/e021f788",
"@odata.type": "#SoftwareInventory.v1_1_0.SoftwareInventory",
"Description": "Host image",
"Id": "e021f788",
"Members@odata.count": 1,
"Name": "Software Inventory",
"RelatedItem": [
{
"@odata.id": "/redfish/v1/Systems/system/Bios"
}
],
"Status": {
"Health": "OK",
"HealthRollup": "OK",
"State": "Enabled"
},
"Updateable": true,
"Version": "IBM-witherspoon-OP9-v2.4.1-4.24"
}
```

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/40711

**Comment by yoshiemuranaka** [comment]
IBM layout
![FW-ibm](https://user-images.githubusercontent.com/8097306/108413411-d9c2cc80-71df-11eb-887f-adabc6add2d7.png)

Default layout
![FW-default](https://user-images.githubusercontent.com/8097306/108413434-e1827100-71df-11eb-8ccc-3d35bee9cb99.png)
