### ISSUE TITLE
pdbg API FFDC and RC support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2915]
- Pdbg already got function extract SBE FFDC , Need to make sure this is working as expected.
- Pdbg changes related to error dc’s for SBE chip-op timeout or the missing FFDC case failures.

**Comment by ojayanth** [comment]
@amitay is working on this issue

**Comment by amitay** [comment]
I am working on it.

**Comment by ojayanth** [comment]
pdbg release p210615  includes this support
