### ISSUE TITLE
p10_extract_sbe_rc  wrapper function support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2917]
- Provide interface to BMC application to call p10_extract_sbe_rc.C to extract RC information for any SBE timeout specific errors.

**Comment by ojayanth** [comment]
As per the current design direction. BMC is not going honour the SBE  extract RC for SEEPROM Side switch. Team agreed to use existing algorithm for SEEPROM Side selection. If required later we need to bring-back this issue. Updating epic.

**Comment by rfrandse** [comment]
tracking in jira
