### ISSUE TITLE
SBE Error Handling: HWP RC Handling

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2918]
Scope: 
- Provide infrastructure to process RC and business logic to select SEEPROM  and update the attributes.  SEEPROM update is also scoped and attribute update to inform host for SEEPROM updates.
- Provide service to BMC application to process SBE timeout specific error handling.
Re-ipl:
RESTART_SBE - Trigger external HRESET to reset SBE
RESTART_CBS - Trigger Warm ipl where we don't switch off VSB just toggle start_cbs from FSP

//SEEProm and measurement/boot  switch and re-ipl
REIPL_BKP_SEEPROM  - Run IPL by selecting backup Boot seeprom
REIPL_BKP_MSEEPROM - Run IPL by selecting backup Measurement seeprom
NO_RECOVERY_ACTION-  No recovery action possible to correct this error

// This need discussion.
REIPL_UPD_SEEPROM - Reload/update of Boot SEEPROM required or deconfig the chip. — This need discussion
REIPL_UPD_MSEEPROM  - Reload/update of Measurement SEEPROM required or deconfig the chip - — This need discussion
REIPL_UPD_SPI_CLK_DIV  - Update SP code and reipl the system/chip

**Comment by ojayanth** [comment]
As per the current design direction. BMC is not going honour the SBE extract RC for SEEPROM Side switch. Team agreed to use existing algorithm for SEEPROM Side selection. If required later we need to bring-back this issue. Updating epic.

**Comment by rfrandse** [comment]
tracking in jira
