### ISSUE TITLE
Responsive Design: Fix the header to accommodate components in tablet

### ISSUE THREAD

**Issue by ryanarnell** [ibm-openbmc/dev#292]
In tablet view, both in case of portrait and landscape, we have a slide in menu. We decided to get rid of the text "Server Info" to make more space so that more portion of header in visible in these views. 

![ee](https://user-images.githubusercontent.com/4976631/51145887-d566a100-181a-11e9-93fb-052cf3f78a37.jpg)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ryanarnell** [comment]
This is completed by this push- https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/17434/ 

The code has been merged Feb 12. Closing the issue :)
