### ISSUE TITLE
PFP::monitor - Fix count method to handle not receiving tach changed signals for a stuck fan

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#2922]
The `count` monitor method is not able to handle when a fan is stuck and not sending property changed signals on the tach feedback. This monitor method appears to work as long as signals are always sent, but needs to have its own timer (1sec repeating? or configurable?) to compare the current input value for a tach sensor.

**Comment by msbarth** [comment]
**Note: TODO Correct `startMonitoring` for `count` method in the trust group**

**Comment by msbarth** [comment]
*Note: Update the `method.md` doc to reflect how the `count` method works after fixing this issue.*

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/41685
