### ISSUE TITLE
eBMC LED Management :: Use Rainier-2u / Rainier-4u / Everest specific config files

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#2924]
Today, when "--enable-use-json" is turned on, the code looks for "led-group-config.json" in "/usr/share/phosphor-led-manager". This works if we have an image supporting just ONE platform. However, we have cases where we want single image supporting multiple systems. For example: we need to be able to run Rainier-2u/rainier-4u/everest out of same image.

So, we need to change the code to handle that.. there is an implementation already at 

https://github.com/openbmc/phosphor-fan-presence/blob/master/json_config.hpp
https://github.com/openbmc/phosphor-fan-presence/blob/master/presence/tach_detect.cpp#L43

and we need to do pretty much the same thing with some tweaks that make sense for phosphor-led-manager.

I have put the commit https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-led-manager/+/40265

When that gets merged, we should have

/usr/share/phosphor-led-manager/ibm,rainier-2u/led-group-config.json
/usr/share/phosphor-led-manager/ibm,rainier-4u/led-group-config.json

and we shall use `InterfacesAdded` on `xyz.openbmc_project.EntityManager`  implementing `"xyz.openbmc_project.Configuration.IBMCompatibleSystem";`

The above referenced code has all that implementation.

By default, lets have ledmanager look at /usr/share/phosphor-led-manager/led-group-config.json, If found, fine.. else fall back to IBMCompatible

**Comment by lxwinspur** [comment]
reveiw by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-led-manager/+/40697
