### ISSUE TITLE
GUI : FW Update - Minimum code level not met error messaging

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2925]
## SME
**BMC**: @anoo1 
**RAS**: George Ahrens

### Summary
Redfish will not have a property that allows us to display the minimum code level to the user. That is coming in a future story, #2889. For MVP, there will be an error message returned from the backend that we can use to inform the user.

### Background
- [ ] TBD

### End users
- [ ]  TBD

### User Needs
- [ ] TBD

### User Quotes
- [ ] TBD

### User Story
As a systems engineer
I need to update my firmware
in order to keep my systems up to date

### Use Case(s)
The user uploads FW that does not meet the minimum requirements. 

### Design Goals
- The user should clearly understand why the update failed and how to recover from it

### InVision Prototype
- [ ] Iteration 0
- [ ] Iteration 1
- [ ] Iteration 2
- [ ] Iteation 3 (Final)

### Community
- [ ] Created design review story in webui-vue repo
- [ ] Sent email to community sharing the design review story

### UX Flow / Interaction Requirements
- [ ] Feature breakdown

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by rfrandse** [comment]
tracking in jira
