### ISSUE TITLE
Fix BIOS to allow updating attributes via D-Bus

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2926]
{
         "attribute_name":"pvm-stop-at-standby",
         "possible_values":[
            "Disabled",
            "Enabled"
         ],
         "default_values":[
            "Enabled"
         ],
         "helpText" : "pvm-stop-at-standby",
         "displayName" : "pvm-stop-at-standby",
         "dbus":
            {
               "object_path" : "/xyz/openbmc_project/control/host0/boot",
               "interface" : "xyz.openbmc_project.Control.Boot.Mode",
               "property_name" : "BootMode",
               "property_type" : "string",
               "property_values" : ["xyz.openbmc_project.Control.Boot.Mode.Modes.Regular", "xyz.openbmc_project.Control.Boot.Mode.Modes.Setup"]
            }
      },

There are few attributes in pldm BIOS which can listen for another D-Bus property. The flow should be like:
1. The BIOS attribute should be changed when the BIOS attribute is changed via Config manager
2. the BIOS attribute should be changed when the other D-Bus property is changed. Like in the above example it is "BootMode" property
3. The D-Bus property ("BootMode") should be changed accordingly when Config manager changes the BIOS attribute

#1 and #2 is achieved via https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/40613
Pls pick that commit and make changes for #3 
also make sure the whole flow works correctly

**Comment by lxwinspur** [comment]
review by:
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/40613
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/40626
