### ISSUE TITLE
PLDM:Receive the SRC buffer from Host

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2927]
This story will make changes in pldm file io to receive the SRC buffer from Phyp/Hostboot.
A new file type needs to be created. 
Host will send a NewFileAvailable command with file type and handle and rest of the parameters.
Pldm will receive the buffer (follow writeFromMemory() and write() in file_io_type_lid.hpp for PLDM_FILE_TYPE_LID_MARKER, commit https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/37562/31/oem/ibm/libpldmresponder/file_io_type_lid.hpp#19)
Post processing of the buffer will be taken up via another story

**Comment by manojkiraneda** [comment]
After discussions with phyp, we have come to a conclusion that, as the progress codes are typically within 1KBytes, phyp would directly call PLDL_WRITE_FILE_BY_TYPE command and does an inband transfer of the whole buffer rather than using the DMA.

**Comment by manojkiraneda** [comment]
This is the PLDL Flow :
1. phyp would call PLDM_WRITE_FILE_BY_TYPE with new file type PLDM_FILE_TYPE_PROGRESS_SRC, & pass on the whole progress code buffer with in the payload of the command.
2. Post receiving the buffer, PLDM would set the buffer on to the Raw Value Property (https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/State/Boot/Raw.interface.yaml#L5)

**Comment by manojkiraneda** [comment]
Initial Review on gerrit : https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/40665

**Comment by manojkiraneda** [comment]
code is merged upstream.
