### ISSUE TITLE
Responsive Design: Fix the spacing in tablet view in server overview page

### ISSUE THREAD

**Issue by ryanarnell** [ibm-openbmc/dev#293]
In Server overview page, there are two alignment issues- 
1.  BMC time label does not align with the time itself- 

Looks like- 
![screen shot 2019-01-14 at 4 42 28 pm](https://user-images.githubusercontent.com/4976631/51146183-b87e9d80-181b-11e9-859f-f76f929731dd.png)

Needs to be like- 
![screen shot 2019-01-14 at 4 42 35 pm](https://user-images.githubusercontent.com/4976631/51146203-c7655000-181b-11e9-98c8-244ead8478d8.png)

2. The events are not aligned properly 
Looks like -
![screen shot 2019-01-14 at 4 42 50 pm](https://user-images.githubusercontent.com/4976631/51146219-d77d2f80-181b-11e9-9513-51f0c8c169da.png)

Need to be like- 
![screen shot 2019-01-14 at 4 43 03 pm](https://user-images.githubusercontent.com/4976631/51146227-dfd56a80-181b-11e9-8396-e25e18eb2fdb.png)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by yoshiemuranaka** [comment]
@jandraa @derick-montague –was chatting with @ryanarnell about the BMC time - did we want to always have the date underneath the label instead of to the right? It was originally designed to be right-aligned. 
Current:
<img width="433" alt="Screen Shot 2019-05-21 at 11 12 45 AM" src="https://user-images.githubusercontent.com/8097306/58116442-84482e80-7bb9-11e9-89c1-ebc2111bb8f0.png">

**Comment by derick-montague** [comment]
@yoshiemuranaka - Can't leave a comment in Gerrit with a screen shot. Looks like the view all event logs link alignment is off.

![image](https://user-images.githubusercontent.com/1183515/58225803-75f93000-7ce9-11e9-96f4-ec4495c392b0.png)

**Comment by rfrandse** [comment]
refresh
