### ISSUE TITLE
Create entity manager configs w/ temp sensors for the Bear*/Flett type PCIE cards

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2941]
The temp sensors need to be in entity-manager so that when the cards are detected and VPD is read, the entity-manager->hwmontempsensor flow can put the temp sensors on D-Bus for fan control.

**Comment by spinler** [comment]
https://github.com/ibm-openbmc/entity-manager/pull/14

**Comment by msbarth** [comment]
This appears it can be closed now?

**Comment by spinler** [comment]
yea.
