### ISSUE TITLE
Blackout handling

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2942]
Verify the blackout support is in and working.

Add 110000AC with appropriate callouts to message registry (https://github.com/openbmc/phosphor-logging/blob/master/extensions/openpower-pels/registry/message_registry.json).

Persist system state to read post-blackout.

Log 110000AC after BMC comes up after blackout (if BMC was previously on, and now coming back up after a POR reset).

**Comment by derekhoward55** [comment]
https://github.com/openbmc/phosphor-state-manager/blob/bbbc01655243fecc83f8734f12a57e665b90ff9a/chassis_state_manager.cpp

https://github.com/openbmc/phosphor-dbus-interfaces/blob/32304979b404c24e32f195d08[…]65b9b34695/xyz/openbmc_project/State/Shutdown/Power.errors.yaml

**Comment by bjwyman** [comment]
Modifying registry and copying as patch for testing is detailed here: https://github.com/openbmc/phosphor-logging/blob/master/extensions/openpower-pels/registry/README.md

**Comment by jjaymeyer** [comment]
Resolved-by: <https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/41274>
Resolved-by: <https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/42120>
