### ISSUE TITLE
PLDM: Recipe support for both phosphor-host-postd & phosphor-post-code-manager

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2954]
Need to bring in recipe support for both of these repos & have to package them while building for 
	tacoma & rainier systems.

**Comment by manojkiraneda** [comment]
Both the phosphor-post-code-manager & phosphor-host-postd are packaged into tacoma & rainier in the following commits:
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/41091
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/40792

Both are merged upstream.
