### ISSUE TITLE
PLDM: Change the default Raw.value property to vector<uint64_t>

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2955]
Change the default PDI Raw.Value property from uint64_t to the vector<uint64_t>

**Comment by manojkiraneda** [comment]
Change is up for review :
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/40903
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/40927

**Comment by manojkiraneda** [comment]
both the commits are merged upstream.
