### ISSUE TITLE
PLDM: Fix all the clients that are using the existing Raw value property

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2956]
Fix all the clients including bmcweb that use the Raw.Value to make sure we dont break them when we change the PDI interface to 
   vector<uint64_t>

**Comment by manojkiraneda** [comment]
Fixed phosphor-host-postd, phosphor-post-code-manager & bmcweb and the changes are up for review :
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-host-postd/+/40933
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-post-code-manager/+/40936
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40981

**Comment by manojkiraneda** [comment]
Few more clients are fixed in the following commits:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41058
https://gerrit.openbmc-project.xyz/c/openbmc/fb-ipmi-oem/+/41210

**Comment by manojkiraneda** [comment]
All the commits are merged upstream.
