### ISSUE TITLE
SBE Error Handling dev tree attribute support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#2960]
//Processor Level
ATTR_PRIMARY_SEEPROM_FAIL_COUNT
ATTR_SECONDARY_SEEPROM_FAIL_COUNT
ATTR_PRIMARY_MSEEPROM_FAIL_COUNT
ATTR_SECONDARY_MSEEPROM_FAIL_COUNT
ATTR_SBE_STATE

**Comment by ojayanth** [comment]
Not required now. Keeping in backlog.

**Comment by rfrandse** [comment]
tracking in jira
