### ISSUE TITLE
VMI IP: Write a new Dbus application for VMI IP configuration

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#2963]
Today what we have in the downstream is:

BMCweb updates the bios-settings manager for the VMI-related BIOS attribute which is not acceptable by the community.

Agreed design:

=> There would be a backend Dbus service that will host the object for the hypervisor and will interact with the BIOS settings manager.
=> bmcweb will directly update those DBus objects.
=> By doing so we are making bmcweb agnostic to the BIOS attribute which would be vendor-specific attributes.

Implement a new application in phosphor-netword which will host the following network objects for the hypervisor

/xyz/openbmc_project/network/hypervisor/
/xyz/openbmc_project/network/hypervisor//<iptype(ipv4/ipv6)>/

These Dbus object will interact with the following Dbus service to persist the Dbus data or populating the Dbus object data.

Details of the Dbus Service:

Service Name: xyz.openbmc_project.BIOSConfigManager
Object: /xyz/openbmc_project/bios_config/manager
Property: BaseBIOSTable

This application has to monitor the BaseBIOSTable/Settings Enable property for the changes which has been applied on the Hypervisor and it has to update the Dbus object from the BaseBiosTable.

**Comment by ratagupt** [comment]
@asmithakarun : You can create further stories like
1) Create the ethernet interface objects.
2) Create the Ip address objects.
3) Update the Dbus properties to the BIOS settings manager
4) Monitor the change in the BIOS settings and update the Dbus object.

**Comment by asmithakarun** [comment]
I have created the same.

https://github.com/ibm-openbmc/dev/issues/3124
https://github.com/ibm-openbmc/dev/issues/3125
https://github.com/ibm-openbmc/dev/issues/3126
https://github.com/ibm-openbmc/dev/issues/3127

**Comment by asmithakarun** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/43173

Initial patch is up in gerri. Will make changes on top of it for pending features and based on the review comments

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by asmithakarun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hypervisor Intermediate App - 2963](https://trello.com/c/4l2J07j7/9-hypervisor-intermediate-app-2963)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by sunharis** [comment]
Migrate-Yes

**Comment by gtmills** [comment]
Closing after talking with Sunitha.
