### ISSUE TITLE
GUI : FED : Hardware Deconfiguration (Guard) records

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2967]
## SME
BMC: @RameshIyyar , @dhruvibm, @gtmills 

## Overview
As a **customer Support team member**, I need to be able to view a server's deconfigured resources, understand why and when they were deconfigured, get the information I need to replace a faulty part, and then re-configure that resource.

As a **customer**, I need to be able to quickly share relevant troubleshooting information with Support (via email or phone), as they may not be able to see what's on my screen.

## UX Flow / Interaction Requirements
- [ ] Consolidate 5 ASMI pages attributed to Hardware Deconfiguration to provide a more informative "hub" to manage deconfigured resources.
- [ ] Level 2 & 3 PEs can easily guide users to identify a deconfigured resource, get a live-text Log, and use that information to reconfigure a deconfigured resource - while maintaining scale-ability for a multi-node system.
- [ ] Level 2 &3 PEs can easily trace and obtain deconfiguration records and attempt to force-reconfigure them in one location. 

## Notes
- Will need to **add hardware ID column to Deconfiguration records page**
- Alerts column **not needed (not supported)**: [slack thread](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1596549463340100)
- [Slack channel: #ebmc_guard_gui](https://ibm-systems-power.slack.com/archives/G01PY3V7C2Z)

## Final Invision Mockup
- [Deconfiguration Records](https://ibm.invisionapp.com/share/T9O0D452VUC)
- [Redfish proposal](https://lists.ozlabs.org/pipermail/openbmc/2020-December/024262.html)

## New components introduced
- In-page tab system 
  - [Bootstrap Vue component](https://bootstrap-vue.org/docs/components/tabs) to be restyled

#### Request:

`curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Systems/system/LogServices/HardwareIsolation`

#### Response
```

{
  "@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation",
  "@odata.type": "#LogService.v1_2_0.LogService",
  "Actions": {
    "#LogService.ClearLog": {
      "target": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Actions/LogService.ClearLog"
    }
  },
  "Description": "Hardware Isolation LogService for system owned devices",
  "Entries": {
    "@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries"
  },
  "Id": "HardwareIsolation",
  "Name": "Hardware Isolation LogService"
}
```

#### Request
`curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries`

#### Response
```
{
  "@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries",
  "@odata.type": "#LogEntryCollection.LogEntryCollection",
  "Description": "Collection of System Hardware Isolation Entries",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/1",                        <— Manually guarded via backend
      "@odata.type": "#LogEntry.v1_9_0.LogEntry",
      "Created": "2021-09-08T17:24:28+00:00",
      "EntryType": "Event",
      "Id": "1",
      "Links": {
        "OriginOfCondition": {
          "@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu0"
        }
      },
      "Message": "6 WAY  PROC CUOD",
      "Name": "Hardware Isolation Entry",
      "Resolved": false,
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/2",                       <— Manually guarded via Redfish
      "@odata.type": "#LogEntry.v1_9_0.LogEntry",
      "Created": "2021-09-08T17:24:33+00:00",
      "EntryType": "Event",
      "Id": "2",
      "Links": {
        "OriginOfCondition": {
          "@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu0/SubProcessors/core0"
        }
      },
      "Message": "core0",
      "Name": "Hardware Isolation Entry",
      "Resolved": false,
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/3",                        <— Manually guarded via Redfish
      "@odata.type": "#LogEntry.v1_9_0.LogEntry",
      "Created": "2021-09-08T17:24:46+00:00",
      "EntryType": "Event",
      "Id": "3",
      "Links": {
        "OriginOfCondition": {
          "@odata.id": "/redfish/v1/Systems/system/Memory/dimm0"
        }
      },
      "Message": “Memory DIMM”,
      "Name": "Hardware Isolation Entry",
      "Resolved": false,
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/4",                       <— Manually guarded (subunit) via backend 
      "@odata.type": "#LogEntry.v1_9_0.LogEntry",
      "Created": "2021-09-08T17:37:01+00:00",
      "EntryType": "Event",
      "Id": "4",
      "Links": {
        "OriginOfCondition": {
          "@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu1"
        }
      },
      "Message": "Memory Controller",
      "Name": "Hardware Isolation Entry",
      "Resolved": false,
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/5”,                       <— System guarded (with error log)
      "@odata.type": "#LogEntry.v1_9_0.LogEntry",
      "AdditionalDataURI": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/1/attachment",
      "Created": "2021-09-09T11:53:56+00:00",
      "EntryType": "Event",
      "Id": “5”,
      "Links": {
        "OriginOfCondition": {
          "@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu0"
        }
      },
      "Message": "Memory Controller",
      "Name": "Hardware Isolation Entry",
      "Resolved": false,
      "Severity": "Critical"
    }
  ],
  "Members@odata.count": 5,
  "Name": "Hardware Isolation Entries"
}
```

#### Request

`curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/5`

#### Response
```
{
  "@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation/Entries/5”,
  "@odata.type": "#LogEntry.v1_9_0.LogEntry",
  "AdditionalDataURI": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/1/attachment",
  "Created": "2021-09-09T11:53:56+00:00",
  "EntryType": "Event",
  "Id": “5”,
  "Links": {
    "OriginOfCondition": {
      "@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu0"
    }
  },
  "Message": "Memory Controller",
  "Name": "Hardware Isolation Entry",
  "Resolved": false,
  "Severity": "Critical"
}
```

#### Request
`curl -k -H "X-Auth-Token: $bmc_token" -X DELETE \
https://${bmc}/redfish/v1/Systems/system/LogServices/ \
HardwareIsolation/Entries/1`

#### Response
```
{
  "@Message.ExtendedInfo": [
    {
      "@odata.type": "#Message.v1_1_1.Message",
      "Message": "Successfully Completed Request",
      "MessageArgs": [],
      "MessageId": "Base.1.8.1.Success",
      "MessageSeverity": "OK",
      "Resolution": "None"
    }
  ]
}
```

### Delete all guard Log Entry
_Note: Unless requested this will not be part of the web ui at request from internal users_

#### Request

`curl -k -H "X-Auth-Token: $bmc_token" -X POST \
https://${bmc}/redfish/v1/Systems/system/LogServices/ \
HardwareIsolation/Actions/LogService.ClearLog`

#### Response
```
{
  "@Message.ExtendedInfo": [
    {
      "@odata.type": "#Message.v1_1_1.Message",
      "Message": "Successfully Completed Request",
      "MessageArgs": [],
      "MessageId": "Base.1.8.1.Success",
      "MessageSeverity": "OK",
      "Resolution": "None"
    }
  ]
}
```
- [ ] Work with Engineering to determine the Redfish endpoints and when they are expected
- [ ] Verify the UI to make sure we can support all of the new UI (two examples below)
    - Clearing of of individual log types, e.g. Memory vs Processor
    - Statistics presented on the UI pages

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Screenshots
Deconfig records page
![Screen Shot 2021-02-18 at 8 45 54 AM](https://user-images.githubusercontent.com/8097306/108390798-dc182d00-71c5-11eb-86d2-ea426946c3c2.png)

**Comment by derick-montague** [comment]
https://github.com/ibm-openbmc/dev/issues/1509#issuecomment-763867772

**Comment by yoshiemuranaka** [comment]
@nicoleconser can you confirm whether or not `Node` column is not needed in this table?

**Comment by nicoleconser** [comment]
> @nicoleconser can you confirm whether or not `Node` column is not needed in this table?

Not needed for this release! This was our attempt at making the design scalable for P11 (when we have multi-node systems).

**Comment by dixsie** [comment]
WIP https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/41265

**Comment by derick-montague** [comment]
This story might not be ready for a while. We want to continue to engage with the engineering team to assure that the user's needs are met regarding showing the deconfiguration types and not just mapping a status. The full convesation is happening in [the #ebmc_guard_gui slack channel](https://ibm-systems-power.slack.com/archives/G01PY3V7C2Z/p1615818764004600)

**Comment by derick-montague** [comment]
We will need to remove the Resource column. This is an SRC that will be part of the PEL download.

**Comment by derick-montague** [comment]
There has been some progress made on this effort from the backend. When we start this work, we will need a driver to test, but for now, @RameshIyyar has provided the endpoints for the `HardwareIsolation` Log services. I have added them to the Curl section in the story description. This came from[ a conversation thread in slack ](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1631203236386000?thread_ts=1626196532.272500&cid=C0Q6TQP5Z)if further reference is required.
