### ISSUE TITLE
Telemetry: Support AppendWrapsWhenFull 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#2969]
Currently, the telemetry service only supports ReportUpdates = Overwrite 

https://github.com/openbmc/bmcweb/blob/081ebf06b4c947e828408029273699ff2d49a54f/redfish-core/lib/metric_report_definition.hpp#L35

This story is to support AppendWrapsWhenFull which allows for more than 1 metric report. 

On the mailing list, Intel mentioned this work was on their roadmap so please work with them and the community 
https://lists.ozlabs.org/pipermail/openbmc/2021-February/025141.html

These changes will need to happen in bmcweb and the telemetry repo.

When this work is complete, the client should be able to set Metric Definitions and store multiple (I would think at least 20) Metrics reports. 
```
        "ReportUpdatesEnum": {
            "description": "Handling of subsequent metric reports when a metric report exists.",
            "enum": [
                "Overwrite",
                "AppendWrapsWhenFull",
                "AppendStopsWhenFull",
                "NewReport"
            ],
            "enumDescriptions": {
                "AppendStopsWhenFull": "New information is appended to the metric report.  The service stops adding entries when the metric report has reached its maximum capacity.",
                "AppendWrapsWhenFull": "New information is appended to the metric report.  The metric report entries are overwritten with new entries when the metric report has reached its maximum capacity.",
                "NewReport": "A new metric report is created, whose resource name is the metric report resource name concatenated with the timestamp.",
                "Overwrite": "Overwrite the metric report."
            },
            "enumLongDescriptions": {
                "AppendStopsWhenFull": "This value shall indicate the service appends new information to the metric report referenced by the MetricReport property.  The service shall stop adding entries when the metric report has reached its maximum capacity.  The State property within Status should be set to `Disabled` and the MetricReportDefinitionEnabled property should be set to `false` when the append limit is reached.",
                "AppendWrapsWhenFull": "This value shall indicate the service appends new information to the metric report referenced by the MetricReport property.  The service shall overwrite entries in the metric report with new entries when the metric report has reached its maximum capacity.",
                "NewReport": "This value shall indicate the service creates a new metric report resource, whose resource name is the metric report resource name concatenated with the timestamp.",
                "Overwrite": "This value shall indicate the service overwrites the metric report referenced by the MetricReport property."
            },
```
Additional references:
https://www.dmtf.org/documents/redfish-spmf/redfish-telemetry-white-paper-0
https://redfish.dmtf.org/redfish/mockups/v1/1027

**Comment by lxwinspur** [comment]
@gtmills @mzipse 

I have read this issue, and have a question:

Since this issue requires changes to the `bmeweb` and the `telemetry` repo, and I got some information by the mailing list:

```
"Append" is on the list of to dos and should be ready till summer
(might be ready). Other feature that are described by Redfish Telemetry
Model should be ready till the end of summer too -> triggers and
collection functions.
```

Do we only need to implement the `bmcweb` repo? Or also need to implement telemetry repo?

Same question as #2968

Thanks

**Comment by lxwinspur** [comment]
Also, I do not know how do I test it?

Right now, I just see using `Unit Test` and `redfish-test` in the `Telemetry` repo.

So I did not found how to trigger the `AddReport` method in `xyz.openbmc_project.Telemetry.ReportManager` interface and the `AddTrigger` method in `xyz.openbmc_project.Telemetry.TriggerManager` interface.

**Comment by lxwinspur** [comment]
>  how to trigger the AddReport method in xyz.openbmc_project.Telemetry.ReportManager interface

I found it in `bmcweb` repo:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32536/59/redfish-core/lib/metric_report_definition.hpp#330

For the `AppendWrapsWhenFull` property, do we need to implement an interface in `phosphor-dbus-interface`? and change the `Telemetry` repo?

Sorry, I am not familiar with the Telemetry service, Please correct me if I am wrong, Thanks.

**Comment by gtmills** [comment]
> Do we only need to implement the bmcweb repo? Or also need to implement telemetry repo?

This work should span both repos. 

> Also, I do not know how to test?

Unit tests and redfish-test are great for the telemetry repo. 
To test end to end, you will want to create a metric definition with ReportUpdatesEnum=AppendWrapsWhenFull  and ensure the behavior is as the API describes. E.g. you have multiple metricValues from different times and that the metricsValues grow until they reach the size of AppendLimit then they wrap. 

![multiple-metric-values](https://user-images.githubusercontent.com/5455127/109541331-ef0de580-7a80-11eb-866f-2ef99a7c24c7.JPG)
![appendLimit](https://user-images.githubusercontent.com/5455127/109541339-f0d7a900-7a80-11eb-8180-f0d279d9654b.JPG)

Note:   AppendLimit is ReadOnly, so would hardcoded to some value the community is agreeable to.

**Comment by gtmills** [comment]
> For the AppendWrapsWhenFull property, do we need to implement an interface in phosphor-dbus-interface? and change the Telemetry repo?

Yes, I believe we need an addition to the phosphor-dbus-interface here. Please be sure to add myself, Ed, and Jozef to any reviews. 

Please be sure to work with the community here. Intel is the telemetry expert having written this code. I think it would be reasonable after the phosphor-dbus-interface is pushed to reply to the above mail with "Here is the phosphor-dbus-interface to add support for "AppendWrapsWhenFull". 

Thanks! 
Keep up the great work. 
Gunnar

**Comment by lxwinspur** [comment]
@gtmills 

Thanks for the reply.
Right now, I have added a new property to the `Report` and `ReportManager` interfaces.
review by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/41010

I will update the `telemetry` service and `bmcweb` after this commit merge.

**Comment by gtmills** [comment]
Intel has plans to work on this during 2Q, https://lists.ozlabs.org/pipermail/openbmc/2021-February/025141.html

it would be great if the owner of this could jump into the conversation (before they start work on this) to avoid duplicated effort (and be transparent) 

Thanks! 
Keep up the great work! 
Gunnar

**Comment by lxwinspur** [comment]
@gtmills 
Thanks for the reply
So, Right now, we need to wait for the Intel team to implement it in the summer, Right?

**Comment by gtmills** [comment]
>  So, Right now, we need to wait for the Intel team to implement it in the summer, Right?

If they implement it by summer, perfect! Then this story would just be testing their code and giving them reviews. 
If they don't get it to, then this story will be implementing the code. 

Before you start working on this, please send something to the mailing (via that email probably) and ask if they have started on it.

**Comment by gtmills** [comment]
@lxwinspur Probably can't wait too long for Intel. Probably want to start on this by May/June (sooner if you want). When you are ready to pick this up, could you reply to the note on the mailing list with something like "we plan to implement AppendWrapsWhenFull"?

**Comment by lxwinspur** [comment]
The first thing:
I added a new interface and merged:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/41010

Next step, I think we need to discuss or wait for Intel to implement it?

**Comment by gtmills** [comment]
> Next step, I think we need to discuss or wait for Intel to implement it? 

Probably time to start on it. 
Can you email the list, respond to that thread that you plan to work on it? 
 https://lists.ozlabs.org/pipermail/openbmc/2021-February/025141.html

**Comment by gtmills** [comment]
I see https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/41010 merged. Any more progress on this?

**Comment by lxwinspur** [comment]
> I see https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/41010 merged. Any more progress on this?

Sorry, I will implement it, but I still read the Telemetry repo first.

**Comment by lxwinspur** [comment]
@gtmills @mzipse 
This is Intel's patch and they have already pushed it to Gerrit, Let me review it
https://gerrit.openbmc-project.xyz/c/openbmc/telemetry/+/46111

**Comment by lxwinspur** [comment]
@gtmills 
can we close this issue?

**Comment by gtmills** [comment]
@lxwinspur Has this been merged upstream ?

**Comment by lxwinspur** [comment]
> @lxwinspur Has this been merged upstream ?

Yeah, I think so
https://gerrit.openbmc-project.xyz/c/openbmc/telemetry/+/46111

**Comment by gtmills** [comment]
> Yeah, I think so
https://gerrit.openbmc-project.xyz/c/openbmc/telemetry/+/46111

And the bmcweb change as well? 
If so, then yeah lets close. If not, let's use this to track getting that in. We might not have to do any coding, just reviews, etc.

**Comment by gtmills** [comment]
I don't see this in bmcweb today: https://github.com/openbmc/bmcweb/search?q=AppendWrapsWhenFull

**Comment by gtmills** [comment]
Need https://gerrit.openbmc.org/c/openbmc/bmcweb/+/44270 
Then this can close :)

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc.org/c/openbmc/bmcweb/+/44270

**Comment by gtmills** [comment]
This merged and I see it here so closing 
https://github.com/search?q=repo%3Aopenbmc%2Fbmcweb+AppendWrapsWhenFull+language%3AC%2B%2B&type=code&l=C%2B%2B
