### ISSUE TITLE
Swift power on services and scripts

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#298]
Make sure all of the power-on services are correct, and bring in any scripts required, like power-workarounds.sh and vrm-control.sh.

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
We probably won't know these until the HW team does the power on, but hopefully it will just be integrating them into our power on sequence, though maybe in a different order than before.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/19389

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
