### ISSUE TITLE
VPD: Redfish: Port Interfaces

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#2981]
This will track all the Redfish schema, bmcweb and backend work needed to expose connectors via Redfish.
At the moment, it appears we have only the CXP ports. These need to be modeled as Ports under the FabricAdapter schema in Redfish.

**Comment by santoshpuranik** [comment]
Work involved is:

* Define a new FabricAdapter D-Bus interface.
* Attach this interface to PCIe card inventory items.
* Define ConnectorType in the Connector inventory interface (?)
* Associate the connector with the PCIe card.
* Implement bmcweb schemas for FabricAdapterCollection, FabricAdapter, PortCollection and Port.

**Comment by santoshpuranik** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41216
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40158

**Comment by bradbishop** [comment]
Also need these interfaces on Flett.

**Comment by mzipse** [comment]
Work is complete.  Closing.
