### ISSUE TITLE
GUI : Design : Expand All menu items

### ISSUE THREAD

**Issue by nicoleconser** [ibm-openbmc/dev#2985]
## User Story
As a GUI user, I need the ability to "Expand All" menu items in one click in order to quickly find information in the GUI. 

## Use Case(s)
- A PE knows what they're looking for, but not where it lives in the GUI's new information architecture – so they want to "expand all" and do a Ctrl + F search for the keyword. 
- A customer doesn't know what they're looking for, so they want to "expand all" and quickly browse through all of the menu items. 

## Design Goals
- Goal 1
- Goal 2
- Goal 3

## InVision Prototype
- Iteration 0
- Iteration 1
- Iteration 2
- Iteration 3 (Final)

## Community
- [ ] Created design review story in webui-vue repo
- [ ] Sent email to community sharing the design review story

**Comment by nicoleconser** [comment]
We are assuming that there is a need for this based on comments made during multiple internal + external user interviews. This will need to be validated with actual end users once we have the finalized GUI IA.

**Comment by rfrandse** [comment]
tracking in jira
