### ISSUE TITLE
PELs: Let user pass in a flag to indicate a fatal/terminating error

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2987]
There is a magic severity that will indicate 'terminating' PELs.  That can be hardcoded in the PEL registry, but there are cases where an error is also terminating in certain cases.  Instead of requiring a new message registry entry with a new SRC, the plan is to come up with an AdditionalData field that can also indicate it.  When the PEL daemon sees that, it will change the severity to the necessary one, and maybe set other bits in the PEL.

**Comment by spinler** [comment]
How about let's use SEVERITY_DETAIL=SYSTEM_TERM

When that is there and the severity is already Critical, then override the Severity to be 0x51 = critical error, system term.

theoretically we could use that to modify other severities too, but for now we can just have it do this one.

**Comment by vflobo** [comment]
@spinler How about supporting all the possibilities for Critical error? We can add SYSTEM_FAIL, PARTITION_TERM, PARTITION_FAIL and complete all the supported types, thoughts?

**Comment by spinler** [comment]
I would suggest writing the code so that is possible, but no need to implement it now since I don't see any use cases yet for those.
