### ISSUE TITLE
Rainier 1s4u EM system config files

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2988]
Need system/chassis file for new IM similar to:
https://github.com/openbmc/entity-manager/blob/master/configurations/Rainier%204U%20Chassis.json
which contains system names, for example:
            "Names": [
                "ibm,rainier-1s4u",
                "ibm,rainier"
            ]

Also need the backplane file since the CCIN for the 1s4u backplane is different, can probably re-use the existing one:
https://github.com/openbmc/entity-manager/blob/master/configurations/Nisqually.json
with the new CCIN being probed.

With these in place, confirm the ucd90320 device access info is placed on dbus and the ibm_rainier.json vrm config file is loaded by using # journalctl /usr/bin/phosphor-regulators.

**Comment by derekhoward55** [comment]
@geissonator I put in your name for now, but if someone else will do this for the bmc team, feel free to change it thanks.

**Comment by spinler** [comment]
IM keywords are also in the associations files.  We'd either need a new file or just add it to an existing one  https://github.com/openbmc/openbmc/blob/master/meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager/rainier/ibm,rainier-4u_associations.json

**Comment by geissonator** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/41259

**Comment by geissonator** [comment]
Work complete and in a downstream driver
