### ISSUE TITLE
Rainier 1s4u fan support

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#2989]
Update appropriate fan config files.  Same max31785 fan controller and type of fans as used in 2s4u, but 4 of them instead of 6.

https://github.com/openbmc/openbmc/tree/master/meta-ibm/recipes-phosphor/fans

Confirm no dts updates needed.

Confirm with thermal team the data to use such as floors (undoubtedly set to high until temp sensor reading support is added), fails before non-info error should be logged, etc.

**Comment by msbarth** [comment]
A 1s4u dts will be required due to how the max31785 is configured. Along with this,  confirm the characteristics of the fan hardware so the max31785 dts configuration attributes are set appropriately according to the fan hardware.

**Comment by geissonator** [comment]
1s4u dts sent to list by Eddie - https://patchwork.ozlabs.org/project/openbmc/patch/20210310173222.17556-3-eajames@linux.ibm.com/

https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/41528 is the last commit in a series for the fan file updates. For now we're just using the same settings as the 2s4u minus the 2 fans.

**Comment by geissonator** [comment]
I know some tweaks will come to the different fan configs as the different teams work on the system but the base code for fan control on 1s4u is all in.
