### ISSUE TITLE
GUI : FED : Add Hostboot Dump

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2995]
## SMEs
- BMC: @asmithakarun 

## Overview
- [ ] Add overview

### Questions
- [ ] Is the hostboot dump disruptive?

## UX Flow / Interaction Requirements
- [ ] Add ability for user to create Hostboot dump
- [ ] Inform user that the dump will not be shown in the list (same  message as System dump)
- [ ] If the dump is disruptive, add the confirmation message (same as System dump)
- [ ] If any new requirements that impact design occur, consult with assigned design team member

## Final Invision Mockup
N/A

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
@mzipse mentioned this is ready. We need to verify.

**Comment by derick-montague** [comment]
@asmithakarun is the SME who can determine if this work is ready for implementation based on feedback from the SoS trello card that @rfrandse updated today.

**Comment by asmithakarun** [comment]
The Redfish APIs are all ready for the hostboot dump.
- Listing of dumps
- Deletion of a single dump
- Delete all dumps
The APIs are same as the other dumps (system/resource) under /redfish/v1/Systems/system path. Just that each dump entry id will be prefixed by "Hostboot_", "Resource_", "System_" based on the respective dump types!

**Comment by dixsie** [comment]
work being completed in #3005

**Comment by dixsie** [comment]
Work will be completed in #3005

**Comment by Srisuk** [comment]
This story cannot be closed, as this includes initiation of Hostboot dumps which is still under progress from the backend, SME for Hostboot dump is @asmithakarun.

**Comment by Srisuk** [comment]
Closing this issue because as per @asmithakarun and @dhruvibm, there is no user-initiated hostboot dump.
Here is the slack conversation [link](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1626855352451800?thread_ts=1626260701.289200&cid=C0Q6TQP5Z).
