### ISSUE TITLE
CEC termination - peltool option to show terminating errors

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2996]
Applications which wish to indicate their error is a terminating error (i.e. an error that is going to stop the boot of the system, or bring a running system down) will indicate this via a specific error logging severity they put in their PEL:

{0x51, "critical_system_term", "Critical Error, System Termination"}

An example of an application associating this error level with a PEL can be found in https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/40747/1/extensions/openpower-pels/registry/message_registry.json#1325

This story is to track an option within peltool to only show these terminating errors. This is useful for lab and bringup debug to quickly understand which specific error is causing the system to fail. If multiple terminating errors are found in the log, then all should be shown.

I'm thinking something like this (note new -t option):
```
# peltool --help
OpenBMC PEL Tool
Usage: peltool [OPTIONS]

Options:
  --help                      Print this help message and exit
  --file TEXT                 Display a PEL using its Raw PEL file
  -i,--id TEXT                Display a PEL based on its ID
  --bmc-id TEXT               Display a PEL based on its BMC Event ID
  -a                          Display all PELs
  -l                          List PELs
  -t                          List only critical system terminating PELs
  -n                          Show number of PELs
  -r                          Reverse order of output
  -h                          Include hidden PELs
  -f,--info                   Include informational PELs
  -d,--delete TEXT            Delete a PEL based on its ID
  -D,--delete-all             Delete all PELs
  -s,--scrub TEXT             File containing SRC regular expressions to ignore
  -x                          Display PEL(s) in hexdump instead of JSON
```

@spinler please provide any of your thoughts on this one

**Comment by lxwinspur** [comment]
@geissonator @spinler 

About this issue, Could you remove `ReadyForDev`?

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/42043

**Comment by geissonator** [comment]
Code merged an in, closing
