### ISSUE TITLE
eBMC State Management - Display terminating error to the panel if available

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#2997]
Terminating errors should be displayed on the panel if they are available. They should be cleared when the corresponding error is resolved or cleared.

**Comment by geissonator** [comment]
@jinuthomas @santoshpuranik is there a story I can link to for op-panel support here?

**Comment by spinler** [comment]
FYI, I have https://github.com/ibm-openbmc/dev/issues/556

**Comment by geissonator** [comment]
oh, lets just use #556
