### ISSUE TITLE
PLDM file io: add Hostboot pnor LIDs into FileTable

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#2998]
Hostboot needs to access the pnor from bmc. This will be achieved by transferring the corresponding LID files. Bmc has to add entries for those files into the FileTable.json so that Hostboot can query for the FileTable and knows the handle and size of each LID beforehand. This will help Hpstboot to reserve the reqired memory area.
Hostboot also needs to be supplied with a new LID type so that it can always read the LIDs from the active side. add a new file type as PLDM_LID_TYPE_ACTIVE and bmc should determine which is the running side and read the LIDs from there

Q. what are the details of the files that are to be added in FileTable? Like the name, size etc
Q. are there another set of LIDs when Hostboot sends read request for PLDM_LID_TYPE_ACTIVE? the LIDs which have entry in FileTable do not need to go via a read file by type path

**Comment by nmuruli** [comment]
Code Review : PLDM : add Hostboot pnor LIDs into FileTable : https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/42442
Depends on the Async Cmd support which is also in code review..

**Comment by nmuruli** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/42442 ==> This was abandoned 
HB Team made the required changes for PLDM (Filetable json updated with required LID list) ==> MERGED
BIOS Attribute changes is in progress ==> Adriana is making the required changes.

**Comment by anoo1** [comment]
> BIOS Attribute changes is in progress ==> Adriana is making the required changes.

This is complete. Closing issue.
