### ISSUE TITLE
Create initial PCIe card JSON files

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#2999]
Create and commit the JSON files that contain the initial list of PCIe card vendorID/subsystemID/etc along with their floor table indexes.  It was asked that we have a common file that contains cards that don't depend on which system one is on, and then also system specific files.   The system owners will take over after that.

**Comment by msbarth** [comment]
This is all up in the following commits to gerrit now:
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50593
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50597
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50667
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50146

**Comment by spinler** [comment]
All merged.
