### ISSUE TITLE
Swift GPIO definitions

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#300]
At the time of this writing, they're in 'skeleton/obmc-libobmc-intf/gpio_defs.json'.

Need these defined to power on the system, and for buttons.

**Comment by spinler** [comment]
... and the chassis-cooling-type GPIO

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
Air/Water chassis-cooling-type GPIOB5.
https://github.com/bradbishop/gpio-keys/blob/master/aspeed-gpio.sh
```
$ ./aspeed-gpio.sh B 5
13
```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/20381

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/20381 merged
