### ISSUE TITLE
GUI : Initiate Resource Dump

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3005]
## SME
**BMC**: @sunharis 
**RAS**:
**PHYP**:

## Summary
The resource dump is another dump the user can initiate. This dump is similar to the system dump. It will `not` be stored on the BMC. This dump will be delivered from PHYP and requires a parameter and a password to be passed with the initiation call. This dump will already be part of the dumps page, but there is not a design to support the string (also referred to as `macro`) and password that needs to be passed with the request to initiate the dump.
Users can also see the listing `Hostboot` dump.

## References

- [Discovery doc with backend](https://ibm.box.com/s/ydzlwid65lermcn64c2myh26ru7cpf39) 

### User Story for Service Login
As an IBM PE/SRR,
I need to access to information and functions
in order to perform actions and see information that the customer does not have access to.

### Use Case(s)
- [ ] **Admin Resource Dumps:** As an admin, I need to initiate a resource dump with specified parameters by providing a resource selector that is passed to the hypervisor. 
- [ ] **Service Login Resource Dumps:** As a PE, I need to initiate a resource dump with specified parameters that requires authorization, by providing a resource selector and a password to the hypervisor.

### InVision Prototype
- [Iteration 0](https://ibm.invisionapp.com/share/HKO157WY2DG) 
- [Iteration 1- Lofi](https://ibm.invisionapp.com/share/CFO157T759W) 

### Community
- [x] ~~Created design review story in webui-vue repo~~
- [x] ~~Sent email to community sharing the design review story~~

## Acceptance criteria
- [x] User should be able to initiate a resource dump
- [x] User should be able to enter a string (macro) when initiating a dump
- [x] PE user should be able to enter a password when initiating a dump for macro's that require authorization
- [x] User should be able to filter dumps by type
- [x] User should be informed if the dump initiation was successful
- [x] User should be informed if there is an error when initiating a dump

### cURL Commands and Redfish Response
- [x] Add Redfish response
- [x] Add cURL commands

### Notes
- [x] Any known API workarounds
- [x] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
WIP: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43230

**Comment by derick-montague** [comment]
We are currently blocked due to a bug in new systems. Initiating a Resource dump results in an error. This was caused by a storage issue. Dumps were resulting in an error due to the number of dumps currently on the System. 

However, on FW1020-21 we are experiencing a 404 when trying to create any dump type.
`/redfish/v1/Managers/bmc/LogServices/Dump/Actions/LogService.CollectDiagnosticData`

## Slack threads
- https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1620408560220100

**Comment by derick-montague** [comment]
@sneha787 - It looks like all the FEDs are assigned as reviewers. Can you work with the team to determine who should be assigned and who should be CC'd?

**Comment by derick-montague** [comment]
We were able to get a system up and tested today. There were some new discoveries and some issues we need to address.

1. There  were JavaScript errors that were keeping the table from displaying correctly when running the code locally regarding an `invalid date format`
        ![image](https://user-images.githubusercontent.com/1183515/121222196-f0069e00-c84b-11eb-8f1c-83f30f0edbe7.png)
2. There are two API endpoints for dumps that need to be pulled in and then pushed to allDumps array in the store
    - Return all Hostboot and Resource dumps: 
    `/redfish/v1/Systems/system/LogServices/Dump/Entries`
    - Returns all BMC dumps:
       `/redfish/v1/Managers/bmc/LogServices/Dump/Entries`

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/44708

**Comment by derick-montague** [comment]
Is this true? Are we adding the Hostboot initiation in this story? I don't see the ability to initiate a Hostboot dump in this story and #2995 was supposed to accommodate that as well.

**Comment by derick-montague** [comment]
@dixsie @Srisuk 
1. The Gerrit commit message does not capture any info about hostboot dumps
2. If this story is plans to include the hostboot story, the user will need to be able to initiate a hostboot dump from the UI, unless that type of dump is not user initiated (I am not sure about how it is triggered)

**Comment by Srisuk** [comment]
@derick-montague I have updated the commit message and posted a query to @asmithakarun on slack regarding initiation and listing of host boot dump [here](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1626260701289200).

**Comment by Srisuk** [comment]
> Is this true? Are we adding the Hostboot initiation in this story? I don't see the ability to initiate a Hostboot dump in this story and #2995 was supposed to accommodate that as well.

@derick-montague No, the only listing of Hostboot dump will be added as part of this story, regarding #2995 we thought that story is also having just adding listing functionality.

**Comment by derick-montague** [comment]
[Resource dump discussion regarding the need for a resource selector value and password in Slack](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1627390200032600?thread_ts=1622555536.358700&cid=C0Q6TQP5Z)

**Summary:**
@asmithakarun asked @dhruvibm to clarify if a resource dump can be created without a resource selector and password. Asmitha and I have different understandings and we need clarification before resource dump initiation is complete. This story will not complete the feature since it simply hardcodes as string that the backend is relying on to initiate a dump.

**Comment by derick-montague** [comment]
There are some delays in the Resource dump. What we will need to do is split the dump initiation from the dump listing. The initiation and communication with PHYP will we delivered in a later milestone.  I want to keep this story for the resource dump initiation and have created a new story, #3302 for adding the Systems/system dump log service.

**Comment by derick-montague** [comment]
@Srisuk - I have moved this to In Plan, can  you mark your Gerrit patchset at WIP until backend is ready? CC:  @asmithakarun and @dhruvibm.

**Comment by dixsie** [comment]
FYI @Srisuk https://github.com/ibm-openbmc/pldm/pull/19 Resource dump fixes merged

>     1. Allow the empty string as resource dump selector
>     2. Avoid setting the resource dump dump explicitly as notify method
>     takes care of the same. This code was causing error when the
>     resource dump is getting initiated from host

**Comment by ghost** [comment]
Resolved By: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/50827

**Comment by ghost** [comment]
From the redfish point of view there is no difference in the signature when user initiates a resource dump. But for ACF Authentication valid password (Should match with ACF installed time password) is mandatory.


Resource Dump With out ACF Authentication:
******************************************
`curl -k -H "X-Auth-Token: $bmc_token" -X POST https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Actions/LogService.CollectDiagnosticData -d '{"DiagnosticDataType":"OEM", "OEMDiagnosticDataType":"Resource_meminfo -pmm full_pwd"}'`

Resource Selector : "meminfo -pmm full"
Password. "pwd"

Note : In this case the provided password ("pwd") is not verified by PHYP.

Resource Dump With ACF Authentication:
***************************************
Before initiating the resource dump user must install the ACF certificates.

`curl -k -H "X-Auth-Token: $bmc_token" -X POST https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Actions/LogService.CollectDiagnosticData -d '{"DiagnosticDataType":"OEM", "OEMDiagnosticDataType":"Resource_meminfo -pmm full_OpenBmc"}'`

Resource Selector : "meminfo -pmm full"
Password. "OpenBmc"

Here password (0penBmc) should match with the one used when they installed the ACF certificate and if password is wrong then PHYP will return error. Internally PLDM fetches the ACF certificate and pass to PHYP which is invisible to the user and user do not worry on that.

**Comment by ghost** [comment]
Resolved By: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/50827
