### ISSUE TITLE
Redfish: Need to fix present / functional (Redfish properties health and state) in Processor.hpp 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3008]
The processor resource needs to look at Present and Functional to determine health and state. 
This is how other resources do it. 
It should not look at totalCores to determine present / State. Instead should look at the Present Property on D-Bus 

https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/processor.hpp#L65 needs to be removed 

https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/processor.hpp#L47 needs to be updated to look at functional 

This comment can be removed: https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/processor.hpp#L44

https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/processor.hpp#L208 can be updated

**Comment by gtmills** [comment]
https://github.com/openbmc/bmcweb/issues/190  also tracks this

**Comment by ChicagoDuan** [comment]
ref: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41714
