### ISSUE TITLE
Redfish: Unknown BIOS attribute 'pvm_os_boot_side' populated 

### ISSUE THREAD

**Issue by SrideviRamesh** [ibm-openbmc/dev#3009]
## Expected Behavior

There is no 'pvm_os_boot_side' bios attribute as per the specifications

## Actual Behavior

  "Attributes": {
    "hb_debug_console": "Disabled",
    "hb_hyp_switch": "PowerVM",
    "pvm_default_os_type": "AIX",
    "pvm_fw_boot_side": "Temp",
    "pvm_hmc_managed": "Disabled",
    "pvm_inband_code_update": "Allowed",
    "pvm_os_boot_side": "Temp",
    "pvm_pcie_error_inject": "Enabled",
    "pvm_rtad": "Enabled",
    "pvm_stop_at_standby": "Disabled",
    "pvm_surveillance": "Enabled",
    "pvm_system_name": "",
    "pvm_system_power_off_policy": "Automatic",
    "vmi_hostname": "",
    "vmi_if0_ipv4_gateway": "1.1.1.1",
    "vmi_if0_ipv4_ipaddr": "1.1.1.1",
    "vmi_if0_ipv4_method": "IPv4Static",
    "vmi_if0_ipv4_prefix_length": 2,
    "vmi_if1_ipv4_gateway": "0.0.0.0",
    "vmi_if1_ipv4_ipaddr": "0.0.0.0",
    "vmi_if1_ipv4_method": "IPv4Static",
    "vmi_if1_ipv4_prefix_length": 0,
    "vmi_if_count": 1
  },

## Steps to Reproduce the Problem

  1. Run the redfish command for bios attributes
  
  curl -k -H "X-Auth-Token: <bmc_token>" -X GET https://<bmc>/redfish/v1/Systems/system/Bios

**Comment by manojkiraneda** [comment]
> There is no 'pvm_os_boot_side' bios attribute as per the specifications

Can you point us to the specification ? if this is a dummy attribute and is not used by both host boot and phyp, then we can remove that entry from bmc json. But we need some one from phyp or hostboot to look at it.

**Comment by SrideviRamesh** [comment]
We can cross check with PHYP BIOS attribute list

**Comment by SrideviRamesh** [comment]
Any update on this issue???

**Comment by jaypadath** [comment]
Manoj has already removed 'pvm_os_boot_side' from spec. You may re-check and close this.

**Comment by manojkiraneda** [comment]
@jaypadath i have not removed it, i was waiting to do the complete check and see what attributes are missing and what else can be removed, can you include this as well in your commit ?

**Comment by manojkiraneda** [comment]
I have comfirmed with the phyp & the hostboot teams, that they are not using this attribute, so we can go ahead and remove this from our jsons .

**Comment by jaypadath** [comment]
@manojkiraneda thanks for the clarification. I have pushed thus json change using https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/41715

**Comment by manojkiraneda** [comment]
merged in master
