### ISSUE TITLE
GUI : FED : Support moving to All Sensors at the Sensor collection

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3013]
## Overview
Before to get all the Sensors 3 of a chassis, 3 calls were made:
/redfish/v1/Chassis/{chassis}/Power
/redfish/v1/Chassis/{chassis}/Thermal
/redfish/v1/Chassis/{chassis}/Sensors

With this change: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40169 
All that is needed is a call to /redfish/v1/Chassis/{chassis}/Sensors to get all the sensors

**Comment by derick-montague** [comment]
Blocked by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40169

**Comment by gtmills** [comment]
This is downstream. Could we pull in downstream?

**Comment by derick-montague** [comment]
Updated and ready for next sprint.

**Comment by derick-montague** [comment]
@dixsie has WIP that will impact this story and is going to work on this going forward.

**Comment by dixsie** [comment]
resolved by https://github.ibm.com/openbmc/webui-vue/pull/7

**Comment by derick-montague** [comment]
I gave it a `+1`. Just need another review.

**Comment by mzipse** [comment]
Work is complete.  Closing.
