### ISSUE TITLE
A bad LogEntryId returns an internal Error instead of 404 / resourceNotFound

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3014]
See
https://github.com/openbmc/bmcweb/issues/191

**Comment by lxwinspur** [comment]
review by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41466

**Comment by gtmills** [comment]
This is great. Nice job!!

If you don't mind (my curl command and where I point at the code are not the same in https://github.com/openbmc/bmcweb/issues/191 My mistake!)

The curl command referred in https://github.com/openbmc/bmcweb/issues/191,
 curl -k -X DELETE  https://$bmc/redfish/v1/Systems/system/LogServices/EventLog/Entries/198274391874 is another logService. 
 
 Could you also do this same change ( https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41466 ) there? 

 https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/log_services.hpp#L1686 is the code.
 
 Can be a separate commit. 
 Bonus if you see any others that need to be fixed. 
 Thanks!
