### ISSUE TITLE
GUI : FED : Node modules - Update all minor and patch releases

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3018]
## Overview
Update all the minor and patch releases and test. It is important to `only` update minor and patch releases. Major releases are known to have breaking changes that we need to spend more time testing. Review the Epic to see the list generated today. 

## UX Flow / Interaction Requirements
1. ``npm outdated``
1. `npx npm-check-updates -u`
1. `npm install`
1. Update the outdated list in the Epic's description section

## Final Invision Mockup
N/A

## cURL Commands
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/41629

**Comment by derick-montague** [comment]
@dixsie did you test everything? The local and a build pushed to System?
