### ISSUE TITLE
GUI : FED : Add ability to upload ACF file - log in page

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3019]
## SME
BMC: Joseph Reynolds (was: Noah Brewer)

## Overview
The user will need the ability to upload the ACF file in order to activate the Service login. The server-side functionality is set for the A.1.2.13 milestone. The design should have been completed in #1291.

It is likely that we will need to copy over the flow from the initial story, #1291.

## UX Flow / Interaction Requirements
- [ ] Add ability to upload ACF file on the login page
- [ ] Verify if the certificate will be compatible with the certification management
    - Likely answer is no and that ACF file will have to expire to be removed from the BMC

## Final Invision Mockup
- [ACF login upload Lofi](https://ibm.invisionapp.com/share/QFO1EMJPNJ4)
- [ACF file certificate uplaod](https://ibm.invisionapp.com/share/ABO1EMHEQ7H) 

## cURL Commands
Curl commands & response: https://ibm-systems-power.slack.com/archives/CPQF3NJTW/p1634847360012100
Get info
```
curl  -k -H "X-Auth-Token: $token" -X GET  https://${bmc}/redfish/v1/AccountService/Accounts/service
```
Upload
```
service_acf_base64=$(base64 -w 0 -i service.acf)
curl  -k -H "X-Auth-Token: $token" -X PATCH -d '{"Oem":{"IBM":{"ACF":{"ACFFile":"'${service_acf_base64}'"}}}}' https://${bmc}/redfish/v1/AccountService/Accounts/service
```
Delete
```
curl  -k -H "X-Auth-Token: $token" -X PATCH -d '{"Oem":{"IBM":{"ACF":{"ACFFile":null}}}}' https://${bmc}/redfish/v1/AccountService/Accounts/service
```

## Notes
- [ACF API endpoint](https://ibm-systems-power.slack.com/archives/CPQF3NJTW/p1628631652013700)
- ACF files for testing can only be used on the machine they are generated for and can be used more than once. Download the ACF files on slack: https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1637011111031400

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by dixsie** [comment]
Asked Noah and Joseph: Is there a schema available for ACF yet? [Slack](https://ibm-systems-power.slack.com/archives/CPQF3NJTW/p1631910842037900)

**Comment by dixsie** [comment]
FYI the login layout changed since the lofi mockup was created. We discuss/tweak at our next backlog grooming. 

New login layout:
![Screen Shot 2021-09-20 at 2 54 27 PM](https://user-images.githubusercontent.com/26472611/134067333-0b39f407-27d0-4112-a593-eeafe8d5626a.png)

Current lofi mockup:
![Screen Shot 2021-09-20 at 2 51 07 PM](https://user-images.githubusercontent.com/26472611/134067193-7702faa0-75ae-476b-968d-9e2cbc69bedd.png)

**Comment by dixsie** [comment]
@sneha787 The backend should be available for this soon, but we can go ahead and work on the front end now

**Comment by dixsie** [comment]
@Srisuk When ready to test upload slack Noah Brewer or Joseph Reynolds to generate a certificate. They will need to know the systems serial number for the machine you check out to test on. The generated certificate will only work with that machine.

**Comment by dixsie** [comment]
ACF files for testing can only be used on the machine they are generated for and can be used more than once. Download the ACF files on slack: https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1637011111031400

**Comment by Srisuk** [comment]
Resolved by https://github.ibm.com/openbmc/webui-vue/pull/33

**Comment by dixsie** [comment]
Moved back to current sprint to add ACF upload to login page

**Comment by dixsie** [comment]
@joseph-reynolds @gtmills Is there a redfish property to check who is allowed to upload an ACF file from the login page? Or can anyone upload from login page? Rahul said we need to check if uploading ACF is selected from the Op panel before uploading from the login page

**Comment by dixsie** [comment]
@sandeepasingh116 let's hold off for now until we can sort ot how to handle uploading ACF from the login page.

**Comment by dixsie** [comment]
@gtmills - Rahul said that the option to upload an ACF file via the login page should only show when a user selects the options from the OP panel. Is there anywhere in redfish to check for this? Or should the upload button always be displayed on the login page

**Comment by joseph-reynolds** [comment]
> The option to upload an ACF file via the login page should only show when a user selects the options from the OP panel. Is there anywhere in redfish to check for this?

I asked in https://github.com/ibm-openbmc/dev/issues/3484
