### ISSUE TITLE
Swift IPMI yaml

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#302]
Set up all of the YAML such that that hostboot can sound down its FRU information, and we can create SELs from error logs, etc.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
I did some random sampling of the generated sensor-gen.cpp and verified the sensors within it matched up with what was in the swift MRW. I also verified that these sensors had different values on witherspoon which means it is successfully picking up the swift MRW. Will wait and see if @tomjoseph83 has any other thoughts on things I should verify before closing this one out.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/22268

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/22268 merged
