### ISSUE TITLE
Add BMC firmware backlevel protection

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#3026]
This is a placeholder to add BMC firmware backlevel aka anti-rollback aka downgrade protection.

Normally a BMC admin can perform firmware update to an older or newer firmware version.  However, when certain security updates are added, the BMC admin may want to ensure that firmware downgrades (or backleveling) cannot occur (or is made more difficult).  This issue is to add a new feature for this.

The design is pending.  Some pieces include:
- New admin controlled BMC policy that says if anti-rollback protection is enabled.  Corresponding APIs and WebUI.
- Enhance the existing BMC firmware update code to follow the anti-rollback protection:
   - When rollback protection is disabled: allow firmware downgrades as before (installing any firmware in the same series, subject to minimum ship level?)
   - When rollback protection is enabled:
      - Lock in the new firmware level as called for.
      - Allow firmware rollback to an image which has the same secure version.
      - Prevent and report firmware update failure when caused by anti-rollback protection.

Contrast with https://github.com/ibm-openbmc/dev/issues/2384 which applies host rollback protection.

**Comment by derick-montague** [comment]
I expect we need error messaging for the GUI, but you probably have that covered. :)

**Comment by anoo1** [comment]
Per discussion with Joseph and Chris, there's no pending work on the BMC side:
```
the minimum secure version check must not block the image install:
For example, the CE/Service Rep would need to do that [roll back to a release earlier than the minimum security version] if they ever need to defeat the host-anti-rollback protection.
Also, when the host anti-rollback protection is engaged, it block the host from booting, but it does not affect the BMC operation (which continues normally).
```
