### ISSUE TITLE
GUI: FED: Switch the GUI to use the new Thermalsubsystem 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3027]
Switch the call for Fans 
https://github.com/openbmc/webui-vue/blob/602e98aa32f82fd3b0c3d250c7cc1f8da971db24/src/store/modules/Health/FanStore.js#L28

The new call 
https://${bmc}/redfish/v1/Chassis/chassis/ThermalSubsystem/Fans/

Backend: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41086

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43372

**Comment by derick-montague** [comment]
@dixsie - It looks like all the FEDs are assigned as reviewers. Can you work with the team to determine who should be assigned and who should be CC'd?

**Comment by gtmills** [comment]
This is downstream. Could we pull in downstream?

**Comment by derick-montague** [comment]
Removing blocked label since it is ready downstream.

**Comment by gtmills** [comment]
After https://github.ibm.com/openbmc/webui-vue/pull/5 merges, can we move this to "code in driver"?

**Comment by mzipse** [comment]
Work is complete.  Closing.
