### ISSUE TITLE
Swift fan and thermal error yaml

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#303]
For fan non-func errors, PS missing errors, shutdown for high core temps, etc

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
PDM recipes need to be updated from native to target based so the Swift and Witherspoon configs can be separated by machine name in the meta layer.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/22591

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/22591 merged
