### ISSUE TITLE
PELs: Let creator pass in flag to indicate a power fault

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#3032]
There is a bit in the SRC section that indicates 'power fault'.    This can be set in the message registry, but there is a use case in the fan code where first a fan fault error is posted when the error is detected, and then again when it shuts down after some amount of delay.  So that the same message registry entry can be used for both errors, we need to have a way for the creator to pass in that the PEL should have the power fault flag set, probably in the AdditionalData property.

**Comment by spinler** [comment]
The key to use could be:  POWER_THERMAL_CRITICAL_FAULT=TRUE

**Comment by vflobo** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/42088
