### ISSUE TITLE
eBMC LED Management :: React to: State.Decorator.OperationalStatus Functional PropertyChanged signal

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#3034]
#2636 put a code where LED manager was setting the OperationalStatus Functional property. However, this would cause trouble for implementations that don't have the LED plumbing.. So, the change in direction is this:

- A new app ( better yet: it can be part of existing phosphor-fru-fault-monitor ) will do these : 
  - Watch for PropertyChanged signal on the interface `xyz.openbmc_project.State.Decorator.OperationalStatus`
  - See if the Inventory D-Bus object has an association with LED groups D-Bus object. If so then:
       - Call "Group Asserted --> true" If the value of `Functional is false`
       - Call "Group Asserted --> false` if the value of `Functional is true`

- We should not change the existing behavior of `phosphor-fru-fault-monitor`.. This new code needs to be a different feature. So, the implementations could use the old behavior or can chose this nw behavior. See if we can make use of package groups or should we use ifdef ( hopefully we don't have to ifdef ? )

**Comment by lxwinspur** [comment]
review by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-led-manager/+/41774

**Comment by vishwabmc** [comment]
This is merged now..
