### ISSUE TITLE
GUI : FED : Update eslint-config-prettier to lastest major release

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3035]
## Overview
The purpose of this story is to update the eslint-config-prettier and sass-loader node packages to their major versions. At the time of this writing the current major versions are:

- `@vue/eslint-config-prettier`: 6.0

## UX Flow / Interaction Requirements
- [ ] Update the package.json file
- [ ] Run `npm uninstall @vue/eslint-config-prettier`
- [ ] Run `npm install`
- [ ] Run `npm run lint` and document and determine
- [ ] Run `npm run serve` and test the application to verify all functionality layout
- [ ] Run `npm run build` and verify the build is successful

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by rfrandse** [comment]
tracking in jira
