### ISSUE TITLE
Power Button Behavior

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#3041]
The "FSP Panel Operations for Power Systems" document at https://ibm.ent.box.com/file/665432307046 describes how the power button should behave.  The power off requirements are different than the current behavior provided by phosphor-buttons, such as a short press shouldn't do anything, and long presses do different things based on how long the press is.

**Comment by sbteeks** [comment]
phosphor-buttons current behavior:
  -  short press - immediate action
      .  Power On host if the host is in Off state
      .  Power Off host if the host is in Running/On state

  -  long press > 3s 
      .  Power Off host after 3 seconds if the host was in On state
      .  No action if the host was Off, will not power On the host
=================================================
High level FSP power button behavior:
Initial 4s:
  - No action if power button is pressed and released within 4 seconds

After initial 4s:
  - Delayed Power Off begins - 10s timeout
    x  button held-down > 10 seconds, Power off stage moves to emergency/fast power off
    x  SRC codes are displayed along with other stuff
    x  Probably some of the components are notified about power Off is coming, and take whatever action needed within that 10 seconds - I'm not really sure
    x  Power button released and pressed again within this 10 second DPO period. Emergency/fast power off begins immediately

After DPO timeout: Emergency Power Off
    x  Host/Chassis Powered Off
    x  FSP panel display is updated

We probably need to do something similar to this. We can possibly have the framework like this but not sure what all has to happen during the DPO phase though. I'll add my thoughts on the design framework here...

**Comment by sbteeks** [comment]
PR up for review: https://github.com/ibm-openbmc/phosphor-buttons/pull/1

**Comment by sbteeks** [comment]
Merged. SRC codes to Op Panel is a TODO...

**Comment by spinler** [comment]
Complete.
