### ISSUE TITLE
GUI : FED : Event Logs: Selected checkboxes are cleared during when changing pages

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3044]
## Expected Behavior
When a user selects any log entries on the event logs table and then changes the page they are viewing, any selected entries should remain selected.

## Actual Behavior
When a user selects any log entries on the event logs table and then changes the page they are viewing, any selected entries are cleared.

## Steps to Reproduce the Problem

  1. Go the the Event logs page (must have more than 20 of entries
  1. Select 1 or more entries on the first page
  1. Change the next page and select a few entries
  1. Return to the first page
  1. Change to the next page

## Tasks
Determine if this is a limitation of Bootstrap-vue tables or how we have implemented them to determine the resolution. If this is a Bootstrap-vue issue, we could create an issue with Bootstrap-vue, but I expect it is how we have implemented the component. 

## Specifications
  - Browser: All
  - Version:

**Comment by dixsie** [comment]
Discussed at daily standup and as a team decided the pattern of checkboxes clearing when changing pages is acceptable. Reason being it would be difficult for the user to keep track of selected items when there could be hundreds of logs.

**Comment by derick-montague** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/42787
