### ISSUE TITLE
BMC Reset with Host Running: IBM specific app to check SCOM regs for host running

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3049]
See https://github.com/openbmc/docs/blob/master/designs/bmc-reset-with-host-up.md#note-on-custom-mechanism-for-ibm-systems

If #3048 can not detect if the host is up, this story will look at a processor scratch register to see if the host is running. This will be a new IBM specific service that runs after #3048 and will create the /run/ file if it is detected the host is running.

**Comment by mzipse** [comment]
@geissonator , do we really need to do this?  I thought @amboar was working on a way to solve this?

**Comment by geissonator** [comment]
> @geissonator , do we really need to do this? I thought @amboar was working on a way to solve this?

Yeah this is the last line of defense to ensure we don't power down a system when PHYP is up and running. The decision from Deans meeting is we have to do it.

**Comment by geissonator** [comment]
All changes merged under https://gerrit.openbmc-project.xyz/q/topic:%22bmc-reset-cfam%22+(status:open%20OR%20status:merged)
