### ISSUE TITLE
Swift VPD collection

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#306]
FRU VPD support for:
* ~storage backplane~  Now part of system FRU
* panel
* BMC riser
* Processor VRMs
* Power Supplies

Probably debatable if this is needed for power on or not.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
As a reminder, the VINI record has been removed from the IBM managed VPD images. The OPFR should be used instead.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
The latest is that the VRM FRU will use 'ipz converged' VPD, and not openpower format.  So those would use the VINI record.

**Comment by spinler** [comment]
The latest is that the VRM FRU will use 'ipz converged' VPD, and not openpower format.  So those would use the VINI record.

**Comment by spinler** [comment]
As of this writing, it is up in the air whether the power supplies will have any keywords filled in besides that #D keyword for the component data.

**Comment by geissonator** [comment]
May need BMC riser for bringup at least due to MAC address

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Reading the BMC card VPD is done with https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/21399

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
It's going to take code changes in gen_openpower_fru.pl to allow there to be more than 1 VRM instance.  Also, not sure yet if openpower-vpd-parser needs changes.

**Comment by spinler** [comment]
changes:
1. Add VRM and PANEL TYPEs to those MRW targets
2. Fix gen_openpower_fru.pl to allow more than 1 VRM
3. Figure out how to add the VRM and PANEL to some derivative of meta-openpower/recipes-phosphor/vpd/openpower-fru-vpd-layout/layout.yaml and maybe config.yaml

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
