### ISSUE TITLE
GUI : FED : Update Vue i18n to support Vue 3

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3060]
## Overview
- [ ] Update to Vue I18n v9 
- [ ] Change `new VueI18n()` to  `createI18n`
- [ ] Determine if vue-i18n-loader and vue-cli-plugin-i18n need to be updated

## Notes
- [Breaking changes](https://vue-i18n.intlify.dev/guide/migration/breaking.html)
- `$tc` supported in legacy mode only https://vue-i18n.intlify.dev/guide/essentials/pluralization.html#basic-usage

**Comment by rfrandse** [comment]
tracking in jira
