### ISSUE TITLE
GUI : FED : Update Bootstrap Vue for Vue 3

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3066]
## Overview
- [ ] Bootstrap Vue currently only supports Vue 2 (as of 6/28/21)
- [ ] Update Bootstrap Vue when Vue 3 support is available
- [ ] Test and verify Bootstrap components

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by dixsie** [comment]
Vue 3 Support issue pinned on [bootstrap-vue issue page](https://github.com/bootstrap-vue/bootstrap-vue/issues)

**Comment by rfrandse** [comment]
tracking in jira
