### ISSUE TITLE
PLDM : Migrate the Location Code interface from com.ibm to xyz.openbmc namespace

### ISSUE THREAD

**Issue by manojkiraneda** [ibm-openbmc/dev#3067]
pldm daemon, consumes the json's present in the `pldm/oem/ibm/configurations/fru` directory and form the FRU Record set PDR's and send them to host (hostboot & phyp)

The FRU jsons entries look at the [com.ibm.ipzvpd.Location](https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/com/ibm/ipzvpd/Location.interface.yaml) interface for populating the Location code FRU record set PDR for host, this story is used to migrate the location code interface from com.ibm namespace to [xyz.openbmc_project](https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Inventory/Decorator/LocationCode.interface.yaml) namespace, as the com.ibm Location code interface will be deprecated in future.

```bash
         "dbus":
            {
               "interface" : "com.ibm.ipzvpd.Location",
               "property_name" : "LocationCode",
               "property_type" : "string"
            }
```
should be converted to 
```bash
         "dbus":
            {
               "interface" : "xyz.openbmc_project.Inventory.Decorator.LocationCode",
               "property_name" : "LocationCode",
               "property_type" : "string"
```

And the bmcweb in it's current state already consumes the `LocationCode` property from the `xyz.openbmc` namespace to get the Location code out of bmc.

**Comment by mzipse** [comment]
Work is complete.  Closing.
