### ISSUE TITLE
GUI : FED : Hardware status - Processors table missing properties

### ISSUE THREAD

**Issue by sandeepasingh116** [ibm-openbmc/dev#3068]
## Overview
The Processors table on the Hardware status page is missing properties that were defined in the original design. When these properties are available on the backend, update the table to show missing properties:

- [ ] Location code (Location in Redfish)
- [ ] Identify LED (LocationIndicatorActive in Redfish)
- [x] Part Number (PartNumber in Redfish)
- [x] Serial Number (SerialNumber in Redfish)
- [x] Fru Number (SparePartNumber in Redfish)
- [x] CCIN (Model in Redfish)
- [x] Processor Type (ProcessorType in Redfish)
- [ ] Manufacturer (Manufacturer in Redfish )
- [ ] Instruction set (InstructionSet in Redfish)
- [ ] Processor Architecture (ProcessorArchitecture in Redfish)
- [ ] Version (Version in Redfish)
- [ ] AssetTag(AssetTag in Redfish)
- [x] Hardware type(Name in Redfish)
- [x] TotalCores(TotalCores in Redfish)
- [x] Max Speed in MHz(MaxSpeedMHz in Redfish)
- [ ] Min Speed in MHz(MaxSpeedMHz in Redfish)
- [ ] Id (ProcessorId in Redfish)
- [x] TotalThreads(TotalThreads in Redfish)

## Notes
- [ ] Box link - https://ibm.box.com/s/i15wf4muw5x09le86l6aa2o7wigq9n35

## Final Invision Mockup
- [ ] https://ibm.invisionapp.com/d/main#/console/15347903/319961438/preview

**Comment by sandeepasingh116** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/42506

**Comment by Srisuk** [comment]
Schema used to get the missing keys: https://redfish.dmtf.org/schemas/v1/Processor.v1_11_0.json

**Comment by derick-montague** [comment]
Blocker: Waiting for LocationIndicators to be present in the API before merge is possible.
