### ISSUE TITLE
Swift presence detects

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#307]
Ensure all of the presence detect services are up and running with the data for the correct GPIOs and FRUs:

* power supplies
* CAPI riser

may also have presence detects, but are required FRUs anyway:
* storage backplane
* panel
* processor VRMs (io expander)
* Processors (io expander)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Other notes: /sys-0/Swift-0/Pallid-0/PCA9553-2/PCA9553.gpio-0 for CP0 OpenCAPI slot and /sys-0/Swift-0/Pallid-0/PCA9553-5/PCA9553.gpio-0 for CP1 OpenCAPI slot

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
both the IPMI daemon and the VPD collector are able to set Present as well on the non hot-pluggable items.

So:
* power supplies:  merged with https://github.com/openbmc/openbmc/commit/6ffd2ac129913a082080c604e0f6513e15d96f0c
* fans:  fan presence yaml - https://github.com/ibm-openbmc/dev/issues/601
* Panel:  handle with VPD collector  - https://github.com/ibm-openbmc/dev/issues/306
* VRMs: handle with VPD collector - https://github.com/ibm-openbmc/dev/issues/306
* Processors:  Use IPMI from hostboot - https://github.com/ibm-openbmc/dev/issues/302
* CAPI card: I think we still want to think about if we want to show it as missing when it isn't plugged, because a customer may decide never to use one. I will open a new story for this and update this issue.

We'll still have to deal with https://github.com/ibm-openbmc/dev/issues/397, which is were we're supposed to call out a missing VRM if someone tries to power on when there isn't a VRM for the corresponding processor, which does imply we'd need to know processor presence before hostboot sends it down.  We can deal with that when we get to that issue.

**Comment by spinler** [comment]
Closing this, as no more code to do under it.
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/20992
