### ISSUE TITLE
GUI : FED : Progress Logs

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3070]
## SME
**BMC**: @manojkiraneda 
**Designer**: @ParishrutB  

## Overview
Create a page for the user to review historical progress codes and boot records

## Acceptance Criteria
- [ ] User will be able to view the entries provided by the Redfish Progress Logs service
- [ ] ASCII information will be displayed to the user when expanding the log details
- [ ] User will be able to view just the PostCode in the table header in order to search, filter, and scan by PostCode
- [ ] Progress codes should be displayed even if the system is out of memory.

## Final Invision Mockup
Check Real-time progress indicators story https://github.com/ibm-openbmc/dev/issues/1303

## cURL Commands
- [ ] Add cURL commands

### Function to decode
https://developer.mozilla.org/en-US/docs/Glossary/Base64
`atob()`

### Function to convert HEX to ASCII
```
function hex2a(hexx) {
    const hex = hexx.toString();//force conversion
    let str = '';
    for (let i = 0; i < hex.length; i += 2)
        str += String.fromCharCode(parseInt(hex.substr(i, 2), 16));
    return str;
}

var hex = hex2a('Ox3030303030304630'); // 000000F0
console.log(hex);
```

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
[Conversation about the display of the ASCII code in the UI](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1619016703321800)

**Comment by ParishrutB** [comment]
Following proposal is currently under review. SME @manojkiraneda 
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/41660

In the workgroup meeting on the same day, Jason Bills suggested that all the property types can be changed to string, and the backend can select whether to send an ASCII code or a HEX code.

**Comment by sandeepasingh116** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43477
