### ISSUE TITLE
Support the MfgSeverity and MfgAction flags PEL message registry fields

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#3073]
These fields provide a way to have different PEL fields when systems are in manufacturing test.

I think it would be appropriate to use the 'quiesce on error' setting.  log_manager.cpp is already using it here:

```
      auto method = this->busLog.new_method_call(
          "xyz.openbmc_project.Settings", "/xyz/openbmc_project/logging/settings",
          "org.freedesktop.DBus.Properties", "Get");    
  
      method.append("xyz.openbmc_project.Logging.Settings", "QuiesceOnHwError");
```

It would be good to look into seeing how we can share the results that log_manager already has so there isn't 2 get property calls on the same property per pel.

**Comment by sumitk56** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/43334
