### ISSUE TITLE
PFP::control - Verify fan watchdog reset path (Hold off reset until after fan control's config is loaded)

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3074]
After the fan watchdog trips (such as at a BMC reset at runtime), need to verify that it can be reset when the BMC comes back as prior functionality required a system poweroff->poweron to reset the fan watchdog.

Along with checking this, fan control needs to be updated to hold off resetting the fan watchdog until after fan control's config is loaded. The fan watchdog can not be reset and allow the fans to return to the last set target without fan control having its config loaded and able to change fan speeds. This would require that the fan control application be updated with the ability to reset the fan watchdog instead of using a systemd service in the BMC poweron path.

**Comment by msbarth** [comment]
The current idea is that the fan watchdog would be initially tripped upon BMC standby-to-poweron state and would be reset(start poking the watchdog) by fan control after fan control successfully loads its config. In addition to this, fan monitor would need to then be started by fan control after the watchdog is being poked since fan monitor can not be running at any point the fan watchdog is tripped due to the differences in fan feedback speeds compared to whatever target was last requested.

**Comment by derekhoward55** [comment]
It is unlikely this will be hit (eg EM crashed), put this in a backlog and fix if seen in field or we have time.

**Comment by rfrandse** [comment]
tracking in jira
