### ISSUE TITLE
PFP::control - Action to override a single fan's speed within a zone

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3076]
With dual rotor fans, a requirement is that when a single rotor fails within a fan FRU, the other rotor should be held at full speed therefore this fan should ignore target change requests while its in this single rotor fail scenario. The idea is to have an action that is triggered by a group containing the pair of fan rotor functional properties to then set a given fan tach sensor object's target to a given value. The override speed should be stored/maintained on the fan object, so the action would need to find the fan name given in the configuration on the zone the action is configured to run against.

**Comment by msbarth** [comment]
The easiest solution is to re-use the `count_state_before_speed` action and update it to support an optional `fans` list that will enable it to set a given target on those fans instead of the zone(like the current action does).

An example of the group & event JSON that could be used to configure the action needed for this issue:
```
groups.json
[
  {
    "name": "fan0 rotors inventory",
    "members": [
      "/xyz/openbmc_project/inventory/system/chassis/motherboard/fan0/fan0_0",
      "/xyz/openbmc_project/inventory/system/chassis/motherboard/fan0/fan0_1"
    ]
  }
]

events.json
[
  {
    "name": "Event - Set/hold fan target",
    "groups": [
      {
        "name": "fan0 rotors inventory",
        "interface": "xyz.openbmc_project.State.Decorator.OperationalStatus",
        "property":
        {
          "name": "Functional"
        }
      }
    ],
    "triggers": [
      { "class": "init", "method": "get_properties" },
      { "class": "signal", "signal": "properties_changed" }
    ],
    "actions": [
      {
        "name": "count_state_before_speed",
        "count": 1,
        "state": false,
        "target": 11200,
        "fans": [
          {
            "name": "fan0",
            "comment": "Fan name from fans.json in zone of this action is valid",
          }
        ]
      }
    ]
  }
]
```

**Comment by spinler** [comment]
Resolved by https://github.com/openbmc/phosphor-fan-presence/commit/59af8caa3c07db908e5a6fe8b3c5f4dbeead8959

**Comment by spinler** [comment]
This still needs the events.json update for rainier 2U and everest.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc.org/c/openbmc/phosphor-fan-presence/+/52276

**Comment by spinler** [comment]
This merged.
