### ISSUE TITLE
Fix the links

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3077]
Some of these are links they should not be 
https://github.com/openbmc/bmcweb/blob/af6298daa55d41d5a47459215b96ca5ec079dfb4/Redfish.md#redfishv1accountserviceaccounts

**Comment by GabrielDonas** [comment]
Hi @gtmills, I create a [pull request](https://github.com/openbmc/bmcweb/pull/201#issue-622244002) on the bmcweb repo to resolve this issue.

**Comment by gtmills** [comment]
@GabrielDonas That is great! Please submit openbmc patches via Gerrit. 
https://github.com/openbmc/docs/blob/master/CONTRIBUTING.md#submitting-changes-via-gerrit-server-to-openbmc
https://gerrit.openbmc-project.xyz/q/project:openbmc%252Fbmcweb+status:open

**Comment by gtmills** [comment]
Escape to characters
