### ISSUE TITLE
bmcweb: redfish: system: Host TransitioningToRunning should be Starting

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3079]
See https://grok.openbmc.org/xref/openbmc/bmcweb/redfish-core/lib/systems.hpp?r=601af5ed#653
```
else if (*s == "xyz.openbmc_project.State.Host.HostState."
                                 "TransitioningToRunning")
                  {
                      aResp->res.jsonValue["PowerState"] = "PoweringOn";
                      aResp->res.jsonValue["Status"]["State"] = "Disabled";
                  }
```

The ["Status"]["State"] should be "Starting", similar to what was done in the hypervisor state code:
https://grok.openbmc.org/xref/openbmc/bmcweb/redfish-core/lib/hypervisor_system.hpp?r=8d1b46d7#67

bmcweb has some requirements on commit message and testing, please see https://github.com/openbmc/bmcweb/blob/master/COMMON_ERRORS.md

**Comment by geissonator** [comment]
High level steps for this:
- Clone bmcweb and make the code change, ensure docker unit tests pass against the change
- devtool modify bmcweb within a openbmc/openbmc build and do a full romulus build
- Boot the build within QEMU and manually verify the change by using busctl to change the state of the HostState
```
busctl set-property xyz.openbmc_project.State.Host /xyz/openbmc_project/state/host0 xyz.openbmc_project.State.Host CurrentHostState s xyz.openbmc_project.State.Host.HostState.TransitioningToRunning
```
- Utilize curl commands to verify Redfish reports the new "Starting" state (https://github.com/openbmc/docs/blob/master/REDFISH-cheatsheet.md)
- Run the Redfish validator against the QEMU session with the BMC in the above state and verify no errors (https://github.com/DMTF/Redfish-Service-Validator)

**Comment by human3rr** [comment]
Curl command to get PowerState and Status:
`curl -k -H "X-Auth-Token: $TOKEN" -X GET https://${BMC_IP}/redfish/v1/Systems/system`
Snippet from redfish response:
`  "PowerState": "PoweringOn",
  "ProcessorSummary": {
    "Count": 0,
    "Status": {
      "State": "Disabled"
    }
  },
  "Processors": {
    "@odata.id": "/redfish/v1/Systems/system/Processors"
  },
  "Status": {
    "Health": "OK",
    "HealthRollup": "OK",
    "State": "Starting"
  },`
Attached file from Redfish response
[UnitTest_getRedfishV1SystemsSystem_ChangeStatusStateToStarting.txt](https://github.com/ibm-openbmc/dev/files/6394371/UnitTest_getRedfishV1SystemsSystem_ChangeStatusStateToStarting.txt)

**Comment by human3rr** [comment]
Docker unit tests passed. Log attached:
[testlog.txt](https://github.com/ibm-openbmc/dev/files/6394453/testlog.txt)

**Comment by human3rr** [comment]
Redfish validator succeeded.
Snippit from test:
`
*** /redfish/v1/Systems/system
INFO -   Type (#ComputerSystem.v1_13_0.ComputerSystem), GET SUCCESS (time: 0.167041)
WARNING - IndicatorLED: The given property is deprecated by revision: This property has been deprecated in favor of the LocationIndicatorActive property.
INFO -   PASS
...
INFO - Validation has succeeded.`

Attaching log file:
[ConformanceLog_04_28_2021_152246.txt](https://github.com/ibm-openbmc/dev/files/6394610/ConformanceLog_04_28_2021_152246.txt)
