### ISSUE TITLE
PFP::presence - Verify and document the use of a direct GPIO detection in place of a GPIO thru I2C expander (i.e. PCA9552)

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3080]
Investigate and verify how fan presence would be configured to use a direct GPIO detection of a fan since primarily it had been used/configured to use GPIO's thru I2C expanders (i.e. PCA9552's)

**Comment by spinler** [comment]
Having a hardware implmentation that needs this will drive any work.  Closing until then.
