### ISSUE TITLE
PELs:  Put the SRC words onto D-Bus

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#3083]
These will go into the redfish event log.  See https://ibm.ent.box.com/notes/791481299908 for details.  Another story will do the bmcweb part of putting this property into a redfish event log.

**Comment by gtmills** [comment]
Ideally, this would be a similar name to EventID..

**Comment by vflobo** [comment]
Resolved https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/43689
