### ISSUE TITLE
Redfish: Resolution property 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3084]
Resolution will have the callouts 
#3082 is the D-Bus work

**Comment by aahmed-2** [comment]
See https://redfish.dmtf.org/schemas/v1/LogEntry.v1_9_0.json for 'Resolution' description

**Comment by gtmills** [comment]
From 9/30 @vflobo is going to own

**Comment by mzipse** [comment]
refresh

**Comment by gtmills** [comment]
Done here https://gerrit.openbmc.org/c/openbmc/bmcweb/+/47655
