### ISSUE TITLE
Redfish ServiceProviderNotified property 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3085]
D-Bus property is #3081

**Comment by aahmed-2** [comment]
See https://redfish.dmtf.org/schemas/v1/LogEntry.v1_9_0.json for 'ServiceProviderNotified' description

**Comment by mzipse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46886

**Comment by mzipse** [comment]
This has been pulled in downstream.

**Comment by patelabhishek9893** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/114 new downstream pr

**Comment by gtmills** [comment]
Still need https://gerrit.openbmc.org/c/openbmc/bmcweb/+/47655  / https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/47683 merged

**Comment by mzipse** [comment]
Work is complete.  Closing.
