### ISSUE TITLE
PFP - Add meson building support

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3089]
The openbmc strategic direction is to have repos built using meson. Need to create all the necessary meson configurations to mimic what autotools currently does when building the fan applications.

**Comment by msbarth** [comment]
My suggestion is to enable meson only for the JSON based configurations for each fan application. This would be the first stepping-stone to then deprecate `phosphor-fan-presence` and create a new repo called `phosphor-fan` (to match the recipe name). Then within this new `phosphor-fan` repo, all the YAML and autotools support can be officially removed and then unit tests(https://github.com/openbmc/phosphor-fan-presence/issues/4) and documentation for fan control can be done(https://github.com/openbmc/phosphor-fan-presence/issues/16)

**Comment by spinler** [comment]
https://gerrit.openbmc.org/c/openbmc/phosphor-fan-presence/+/55023 is the phosphor-fan code, and it merged.  Still have bitbake changes to merge.

**Comment by spinler** [comment]
Merged.
