### ISSUE TITLE
Swift Power Sequencer Monitoring power on support

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#309]
Make sure it does less harm than good.  All of the callouts and GPIOs it monitors need to be swizzled, so either do that all before power on, or just don't start the service.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Going to skip this one and use #312 to do everything in one shot.
