### ISSUE TITLE
bmcweb: Model core in redfish 

### ISSUE THREAD

**Issue by RameshIyyar** [ibm-openbmc/dev#3094]
- Currently, we did not model core in redfish (bmcweb) and the redfish spec have properties (ProcessorType and SubProcessors) in Processor schema to add subunit of processor
- So, we need to extend the existing bmcweb processor schema implementation to provide core information as subunit of processor to the external user.

**Comment by gtmills** [comment]
@RameshIyyar Have you seen https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38570 #1747

**Comment by rsnair** [comment]
@gtmills good one ... If that's covering what we're looking for we'll close this story

**Comment by RameshIyyar** [comment]
> @RameshIyyar Have you seen https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38570 #1747

Ah nice and I will take look.

**Comment by rsnair** [comment]
Reduced the sizing as some of the work is already done via https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38570 #1747

**Comment by rsnair** [comment]
We identified late that the DCM's are not modelled in Redfish. Ramesh is pushing a workaround while the actual fix is getting brainstormed in the redfish dmtf forum.

**Comment by gtmills** [comment]
@RameshIyyar Can you please review https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38570  ? Then I assume after that merges this story is complete and work around the DCM can be tracked elsewhere?

**Comment by RameshIyyar** [comment]
> @RameshIyyar Can you please review https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38570 ? Then I assume after that merges this story is complete and work around the DCM can be tracked elsewhere?

Sure, I will take a look at that patch (I am not an expert in bmcweb, will try to look based on my thoughts if something needs to change or improve)

**Comment by RameshIyyar** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/95 - Merged in ibm-openbmc.
