### ISSUE TITLE
Swift hwmon sensor definitions

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#310]
Need the config files for all of the sensors (which also need to be in the device tree).  Shouldn't be needed for power on.

**Comment by spinler** [comment]
Just noting here there was also a specific request to make a sensor for the power supply fans.

**Comment by spinler** [comment]
So now the list looks something like:
* OCC sensors
* ambient (DPS310)
* TMP275s for pcie ambient
* VDD/VCS/VDN VRMs
* power supply data
* RTC battery voltage if possible
* max31785 fan controller
* IO card temps from MCTP (still uses phosphor-hwmon?)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Doing this piecemeal as not all drivers are available yet.
Finished an easy one first - the pcie temp sensors: https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/21021

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
- [ ] fans (MAX31785)
- [ ] pcie (2x - TMP275)
    - inlet ambient between 0/1
    - inlet ambient between 2/3
- [ ] ambient (TMP275 temp)
- [ ] ambient (DPS310 temp)
- [ ] ambient (DPS310 altitude?)
- [ ] ambient (Si7021-A20 temp)
- [ ] ambient (Si7021-A20 humidity)
- [ ] vrms
    - VDD (IR35219)
    - VDN/VCS (IR35221
- [ ] occ sensors
    - primary sbefifo1
    - secondary sbefifo2
***
Likely need to break the following sensors to other stories as additional work may be necessary
- [ ] power supply data
- [ ] RTC battery voltage if possible
- [ ] IO card temps from MCTP (still uses phosphor-hwmon?)

**Comment by rfrandse** [comment]
refresh

**Comment by amboar** [comment]
> IO card temps from MCTP (still uses phosphor-hwmon?)

phosphor-hwmon won't be involved in anything MCTP-based. You'll need something else to expose sensors on DBus from MCTP land.

**Comment by msbarth** [comment]
Commits providing what's described above:
- https://gerrit.openbmc-project.xyz/22254
- https://gerrit.openbmc-project.xyz/22253
- https://gerrit.openbmc-project.xyz/22252
- https://gerrit.openbmc-project.xyz/22251
- https://gerrit.openbmc-project.xyz/22250
- https://gerrit.openbmc-project.xyz/22249
- https://gerrit.openbmc-project.xyz/22248

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/22254

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/22254 merged
