### ISSUE TITLE
PFP::control - Investigate optimizing the use of `getManagedObjects`

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3101]
Using `getManagedObjects` to populate the cache is efficient from a dbus traffic view, but it does cause (in the current design) the cache to be populated with objects that are not necessarily configured to be used by fan control. Need to investigate a better way to filter the results returned by `getManagedObjects` thru the Groups that are configured since that configuration provides the entire list of possible dbus object paths that could be configured for use in fan control's algorithm.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/52717
