### ISSUE TITLE
GUI : FED : HW Inventory - Remove <br> elements from VPD layout

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3102]
## Overview
The VPD is displayed using a data list. In each data list is a term and definition. In the current implementation, we have used the `<br>` element to create space between the term and definition pairs. This is not a semantic use for this element.

### Resource
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br

### Example
``` 
<dt>{{ $t('pageHardwareStatus.table.partNumber') }}:</dt>
<dd>{{ tableFormatter(item.partNumber) }}</dd>
<br />
<!-- Serial Number -->
<dt>{{ $t('pageHardwareStatus.table.serialNumber') }}:</dt>
<dd>{{ tableFormatter(item.serialNumber) }}</dd>
<br />
<!-- FRU Number -->
<dt>{{ $t('pageHardwareStatus.table.fruNumber') }}:</dt>
<dd>{{ tableFormatter(item.fruNumber) }}</dd>
<br />
<!-- CCIN Model -->
<dt>{{ $t('pageHardwareStatus.table.ccinModel') }}:</dt>
<dd>{{ tableFormatter(item.ccinModel) }}</dd>
```
The easiest way to solve this is to remove the `display` declarations from both dt and dd and add a float: left to the dt.
```
    dt {
      margin-right: $spacer / 2;
      float: left;
      clear: left;
    }
```

## Acceptance criteria
The `<br>` elements will be removed and a style will be added or a margin utility class will be used to create the white space between the term and definition pairs.

## Final Invision Mockup
N/A

## cURL Commands
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by dixsie** [comment]
I suggest wrapping each term & description in a single definition list instead of adding a new style because 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#single_term_and_description

**Comment by sneha787** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43712

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/44471
