### ISSUE TITLE
PFP - Create a flight recorder for fan monitor

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3103]
Need to discuss and determine how we should handle if/when someone (such as a customer) logs into the BMC and alters any of the fan configs (whether knowingly or not) from a support point-of-view since doing this could drastically change the thermal stability of the system.

It may not be a concern as the BMC filesystem could be read-only.

**Comment by msbarth** [comment]
Fan control is handled under issue #3461

The remaining fan apps need to have a "flight recorder" implemented and a method to dump that information to a file. That work should be done under this issue.

**Comment by spinler** [comment]
@mikecgithub We can use this issue to look into a fan monitor dump using the USR1 signal if there's data we'd like to see, like the trailing tach/target values you've added.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc.org/c/openbmc/phosphor-fan-presence/+/56802

**Comment by spinler** [comment]
Merged.
