### ISSUE TITLE
Upstream: Display error on GUI when exceed number of websockets 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3106]
2 parts:

1) bmcweb needs to look for number of sessions / number of max sessions similar to https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25231
and return an error via websocket if this connection will exceed the max number of connections. 
The error might look like 
```
503 Service Unavailable

The server is currently unable to handle the request due to a temporary overloading or maintenance of the server. 
```
2) The GUI (webui-vue) looks for this code and displays a error message https://github.com/openbmc/webui-vue/blob/f3022e5c1ad1f4d83d03d996d77094a87f4be8e0/src/views/Control/Kvm/KvmConsole.vue

**Comment by gtmills** [comment]
This story tracks both the bmcweb work and the GUI. We can break down if need.

**Comment by rfrandse** [comment]
tracking in jira
