### ISSUE TITLE
OP940:  Display error on GUI when exceed number of websockets 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3107]
2 parts:

1) bmcweb needs to look for number of sessions / number of max sessions similar to https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25231
and return an error via websocket if this connection will exceed the max number of connections. 
The error might look like 
```
503 Service Unavailable

The server is currently unable to handle the request due to a temporary overloading or maintenance of the server. 
``` 

2) The GUI (phosphor-webui) looks for this code and displays a error message 
https://github.com/openbmc/phosphor-webui/blob/339db9a4c8610c5ecb92993c0bbc2219933bc858/app/server-control/controllers/kvm-window-controller.js#L19

**Comment by gtmills** [comment]
This story tracks both the bmcweb work and the GUI. We can break down if need.

**Comment by AndyYFWang** [comment]
Hi all,
I have an idea for this.
We may be able to add a warning message from the disconnected function of the KVM session.
(https://github.com/openbmc/phosphor-webui/blob/master/app/server-control/directives/kvm-console.js#L37)

like this:
....
function disconnected(e) {
                 $log.debug('RFB disconnected');
                 alert("503 Service Unavailable.");
                 alert("The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.");
  }

When the KVM session exceeds the connection limit, a warning message will be appeared.
![image](https://user-images.githubusercontent.com/20676758/117927703-29231f80-b32d-11eb-8fb6-d4f2f270c542.png)
![image](https://user-images.githubusercontent.com/20676758/117927758-3dffb300-b32d-11eb-9bdc-59a78f8cdf9a.png)

**Comment by gtmills** [comment]
```
alert("503 Service Unavailable.");
alert("The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.");
```
Would work. Was thinking this would be a specific error, which would require changes in bmcweb

**Comment by Erich-Hauptli** [comment]
@AndyYFWang Is it possible to also identify the user IP that has an open session?  Our PE team requested an alert message that was a bit more specific along the following lines:

"Unable to start a remote KVM session.  Another user at ip address {} has an open session and only 1 active KVM session is supported."

Would you then be able to populate the {} with the active session users IP?

**Comment by AndyYFWang** [comment]
Hi @Erich-Hauptli , @gtmills ,

If the alert message is sent based on the connection restriction, I think I can do this part.
But if the user ip needs to be displayed, I may need some assistance in this part.
As for how to obtain the user ip, I did some tests last week, including writing a php file to enable it through html, such as
...
function getIP(){
if(!empty($_SERVER['HTTP_CLIENT_IP'])){
$ip = $_SERVER['HTTP_CLIENT_IP'];
}else if(!empty($_SERVER['HTTP_X_FORWARDED_FOR'])){
$ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
}else{
$ip = $_SERVER['REMOTE_ADDR'];
}
return $ip;
}
...
But how to obtain the user ip part is still unsuccessful... 
Maybe I am not good at webui architecture and have some negligence. At present, I have no idea how to implement this part.
Do you have any idea about these?

**Comment by Erich-Hauptli** [comment]
Please commit this fix without the IP.  Update the error to "Unable to start a remote KVM session. Only 1 active KVM session is supported."  We can investigate adding the IP in a future commit.

**Comment by AndyYFWang** [comment]
Hi @Erich-Hauptli  @gtmills 

Regarding the part of adding the alert message, I already have a solution.
But I have discovered another new issue(?). 
After I set the maxSession of KVM to 1, I found that abnormalities occurred when running on the "Firefox" browser.
(https://github.com/ibm-openbmc/bmcweb/blob/master/include/kvm_websocket.hpp#L15)

As shown in the figure below, the kvm session is normally opened.
![image](https://user-images.githubusercontent.com/20676758/120787561-12ee3500-c562-11eb-8be0-37080fd7335a.png)

But after I press the "Refresh" button in the upper right corner, the kvm session will be closed directly.
![image](https://user-images.githubusercontent.com/20676758/120787619-1f728d80-c562-11eb-909d-5924150dc70b.png)
I guess it may be caused by the opening of an additional kvm session (2nd session) when the Firefox browser is operating.

The above results will also cause this to happen after I add alert.
But currently only the Firefox browser has this issue, and Chrome and Edge browsers do not.

**Comment by clairefish** [comment]
Hi @Erich-Hauptli @gtmills 

It will be happened on Firefox browser only and won't impact to KVM function.
You can still keep using KVM function after refreshing the web page.
We suppose it's the limitation of Firefox, it could be listed in a known issue.
Do you have any concern with this condition?
If there is no further problem, we will still push this solution to github.

P.S. We can provide the test firmware for you if you'd like to try.

**Comment by rfrandse** [comment]
tracking in jira
