### ISSUE TITLE
QEMU needs model support for Infineon DPS310 Air Pressure and Temperature Sensors

### ISSUE THREAD

**Issue by BMC-Bruce** [ibm-openbmc/dev#3109]
Rainier and Everest have Infineon DPS310 Air Pressure Sensor used to compute Altitude.
Its Temperature Sensor needs to also be part of the model too.
QEMU's model needs work be functional for meeting developers and CI needs.

@mzipse didn't want us to loose this, certainly a low priority presently.

**Comment by rfrandse** [comment]
tracking in jira
