### ISSUE TITLE
Swift VDD VRM device driver

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#311]
The VDD VRM, which is even now a FRU, is different than the previous one used in Witherspoon.  It will probably need some device driver changes.  We at least need to get the temp from it for fan control, though all the currents and voltages would be nice too for sensors.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
Once this driver is done, the device tree can be updated: https://patchwork.ozlabs.org/patch/1108582/

**Comment by amboar** [comment]
Who's doing the driver? What state is it in?

**Comment by anoo1** [comment]
@eddiejames will be doing the driver. It hasn't been started yet, @spinler would know when this is scheduled to be done.

**Comment by rfrandse** [comment]
refresh
