### ISSUE TITLE
GUI : FED : Update to Bootstrap-vue 2.22.x

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3115]
## Overview
When the next version of Bootstrap-vue is released, we need to update to resolve the router-link deprecated tag prop.

```
 console.warn node_modules/vue-router/dist/vue-router.common.js:18
      [vue-router] <router-link>'s tag prop is deprecated and has been removed in Vue Router 4. Use the v-slot API to remove this warning: https://next.router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link.
    console.warn node_modules/vue-router/dist/vue-router.common.js:18
      [vue-router] <router-link>'s event prop is deprecated and has been removed in Vue Router 4. Use the v-slot API to remove this warning: https://next.router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link.
```
## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
I checked today and Boostrap-vue is still on v21.x

**Comment by rfrandse** [comment]
tracking in jira
