### ISSUE TITLE
SBE Chip-op Failure Handling at Runtime( Recovery)

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#3118]
- Use case is limited to only OCC app driven Chip-op failures.
Work Includes:
- PLDM Interface to support SBE Recovery request.
- HBRT support PLDM requests.
- OCC driver support to extract SBE FFDC
- OCC App support for SBE Error handling.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
