### ISSUE TITLE
Swift Power Sequencer Monitoring

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#312]
The current code is in witherspoon-pfault-analysis and is only set up to handle 1 set of data.  Need to figure out how have it be more data driven.

Different rails, GPIOs to monitor, GPUs to call out, and also VRM FRUs to call out now.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
After further discussion with @spinler the plan is to go with YAML/Mako/Python to make this more data driven. The Swift rails, GPIOs, ... will be similar, but there are apparently some differences.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/q/topic:"ibm312"+(status:open%20OR%20status:merged)
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/20728

Not sure on "also VRM FRUs to call out now".

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
MEM_GOODx isolation will need:
1. New error function.
2. YAML updates for pins used in isolation.

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/21488

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
Device tree update from Adriana:
[dev-5.1] ARM: dts: aspeed: swift: Add pca9539 devices
http://patchwork.ozlabs.org/patch/1102339/

**Comment by bjwyman** [comment]
Not clear on DIMM callouts for memory power faults. MRW and Hostboot coordination needed.

**Comment by bjwyman** [comment]
Issue #735 created to address DIMM call outs.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/21488 merged
