### ISSUE TITLE
Create the ethernet interface objects

### ISSUE THREAD

**Issue by asmithakarun** [ibm-openbmc/dev#3124]
For the Epic 2963: To write a new Dbus application for VMI IP configuration:

The first step in creating the application is to create the hypervisor ethernet objects under hypervisor network service.
It should look something like:

create: xyz.openbmc_project.Network.Hypervisor

busctl tree xyz.openbmc_project.Network.Hypervisor
```
└─/xyz
  └─/xyz/openbmc_project
    └─/xyz/openbmc_project/network
      └─/xyz/openbmc_project/network/hypervisor
        ├─/xyz/openbmc_project/network/hypervisor/if0
```

The ethernet interface objects must be read from the base biostable and created.

**Comment by asmithakarun** [comment]
Initial changes are up in gerrit for review https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/43869/

**Comment by sunharis** [comment]
Delivered downstream & also upstreamed
