### ISSUE TITLE
Update the BIOS table on Dbus properties change

### ISSUE THREAD

**Issue by asmithakarun** [ibm-openbmc/dev#3126]
For the Epic 2963: To write a new Dbus application for VMI IP configuration:

The third step is to update the base biostable properties when there is a change in the corresponding properties in the dbus object.

**Comment by asmithakarun** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/43869/
Changes up in gerrit for review

**Comment by sunharis** [comment]
Delivered downstream
