### ISSUE TITLE
A way to Delete Inventory D-Bus Objects (Handle FRUs going away)

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#3136]

**Comment by amboar** [comment]
Just a note that platform-fru-detect is affected by not having a way to delete interfaces or objects: https://github.com/ibm-openbmc/platform-fru-detect/commit/44f393796607d3a2082d8fa39054daf1584320b4

**Comment by rfrandse** [comment]
tracking in jira
