### ISSUE TITLE
bmcweb commits to be upstreamed

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#3138]
This epic is to track the commits which is in downstream and the upstream reviews are going on.

**Comment by ratagupt** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/34208
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38051

**Comment by sunharis** [comment]
Many functionalities of community interest are pushed upstream already. Story can be closed
