### ISSUE TITLE
OCC power sensor averaging

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#314]
https://github.com/openbmc/openbmc/issues/3187 was requested for Swift.  Just putting a pointer to it here so we can track it.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mine260309** [comment]
Carol Wang would like to take this task.

It's noticed that the occ hwmon driver in kernel already reports average power by `powerX_average`, and the implementation is `accumulator / update_tag`.
There are several questions to clarify:
1. The current implementation `accumulator / update_tag` reports the average power starting from the occ active, and it is likely not accurate to the recent "average" power, is that expected?
A recent "average" power could be something like `(accumulator_new - accumulator_old) / (update_tag_new - update_tag_old)`.
2. Should we just report average power to replace the "current" power? Or add a new sensor so a power will have both "current" power and "average" power.

**Comment by spinler** [comment]
For 1, I think the driver will need to change.  @eddiejames had tried to upstream some changes in that area, but they got rejected.  @eddiejames Can you mention what you tried to do?

For 2, you can use the same sensors.

**Comment by mine260309** [comment]
Talked to @eddiejames and understand the current status in occ hwmon driver:
* The plan was to report `average = (accumulator2 - accumulator1)/(updateTag2 - updateTag1)`
* The code was rejected by upstream with below comments:
   * The number reported as average power is more or less useless/random.
   * The code gets so complicated that it is all but impossible to understand.
* The old hwmon driver was to report the `powerX_accumulator` and `powerX_update_tag`, but that was not upstreamed.
* So eventually we get the `average = accumulator / update_tag` for now.

**Comment by spinler** [comment]
@mine260309 Are you planning on leaving the code as accumulator / update_tag?

**Comment by mine260309** [comment]
@spinler It is a good question. I hope I would have a better answer, but due to the situation @eddiejames meets, there is no better way to report the average power.

There are alternatives:
1. Make occ hwmon driver to report `powerX_accumulator` and `powerX_update_tag`, so phosphor-hwmon could calculate the average power in user space.
   This depends on the kernel driver. And it is likely not accepted by upstream. Maybe @eddiejames could provide more information about why?
2. Accept the current kernel driver, so the average power is really the average power since occ works.
Extend @wangkair 's solution, that reports both current power reading and the average for the sensors configured as "AVERAGE_powerX = true", something like:
   ```
    "/xyz/openbmc_project/sensors/power/xxx_power": {
      ...
      "Value": 28000000   # This is the value of powerX_input
      "Average": 27104337   # This is the value of powerX_average
    },
   ```

**Comment by eddiejames** [comment]
Accumulator and update_tag will not be accepted as hwmon attributes. It's possible we could put them in the custom sysfs files associated with the hwmon device.

Userspace could extract both the accumulator and update tag from the existing average and average_interval fields:
update_tag = average_interval / 500 us (occ sample time, a constant)
accumulator = average * update_tag

**Comment by mine260309** [comment]
> It's possible we could put them in the custom sysfs files associated with the hwmon device.

How do we achieve this?

> Userspace could extract both the accumulator and update tag from the existing average and average_interval fields:
> update_tag = average_interval / 500 us (occ sample time, a constant)
> accumulator = average * update_tag

This is interesting, it's doable if we put this specific code in phosphor-hwmon.

@spinler @msbarth Will such specific code accepted in `phosphor-hwmon`?
And what do you think about the suggestion to add a new `Average` property?

**Comment by msbarth** [comment]
Why isnt this averaging happening in the OCC and then be presented in the power*_average for the GPUs?

I would prefer to not have special code treatment in `phosphor-hwmon` for a subset of sensors provided by an OCC using non-hwmon spec sysfs files or having a special case to use those hwmon spec sysfs files(_average & _average_interval) including a calculation for the OCCs.

@mine260309 What interface would the `Average` property be included on? If its on `Sensor.Value`, then all applications that use that interface would also pick up the `Average` property which we probably dont want.

**Comment by mine260309** [comment]
> Why isnt this averaging happening in the OCC and then be presented in the power*_average for the GPUs?

@msbarth Do you mean asking OCC team to do the average calculation and report it in occ poll command? I think that's kind of huge change and breaks the current interface of occ poll command.

> I would prefer to not have special code treatment in phosphor-hwmon for a subset of sensors provided by an OCC using non-hwmon spec sysfs files or having a special case to use those hwmon spec sysfs files(_average & _average_interval) including a calculation for the OCCs.

Then the problem remains: how do we report average power in a reasonable interval?

> @mine260309 What interface would the Average property be included on? If its on Sensor.Value, then all applications that use that interface would also pick up the Average property which we probably dont want.

I am proposing a new interface that defines an `Average` property, and only sensors with `AVERAGE_powerX` will implement the interface and provide the `Avergae` property. So it will not impact other sensors.

**Comment by bradbishop** [comment]
at 9:59 PM, Lei YU <notifications@github.com> wrote:

> I am proposing a new interface that defines an Average property,

In other words, you are proposing new hwmon ABI.  Guenter’s feedback is  
probably worthwhile.  Is there something quick we can do to get it?

**Comment by spinler** [comment]
Just to state it here again, the desired value is the average between polls, which is, (accumulator2 - accumulator1)/(updateTag2 - updateTag1)", however we can get it.

**Comment by msbarth** [comment]
@mine260309 Yes, do we know for sure that it would break the poll response? To me, this seems to be the correct place to have the averaging done and presented thru the driver in the _average & _average_interval files in sysfs, which looks to follow the hwmon spec.

**Comment by mine260309** [comment]
> In other words, you are proposing new hwmon ABI.  Guenter’s feedback is
> probably worthwhile.  Is there something quick we can do to get it?

@bradbishop It's not a new hwmon ABI, instead, existing hwmon already has `powerX_average` sysfs attribute. So what I am proposing is to add a new "average" interface in /xyz/openbmc_project/Sensor, that defines a  `Avergae` property to represent the `powerX_avergae` sysfs attribute.

> Just to state it here again, the desired value is the average between polls, which is, (accumulator2 - accumulator1)/(updateTag2 - updateTag1)", however we can get it.

@spinler
Without OCC's change, the current Linux kernel driver will not be able to handle it, because @eddiejames already tried to push the changes and got rejected by upstream.
It has to be done in user space, e.g. by phosphor-hwmon to handle this specific requirement.

> @mine260309 Yes, do we know for sure that it would break the poll response? To me, this seems to be the correct place to have the averaging done and presented thru the driver in the _average & _average_interval files in sysfs, which looks to follow the hwmon spec.

@msbarth The current occ poll's power reading is already defined as below

```
0x08 Update Tag – 4 bytes. Count of number of 500us samples represented in Accumulator. Used for time derived sensor.
0x0C Accumulator – 8 bytes. Accumulation of 500us power readings
0x14 Current Reading – 2 bytes. Most recent 500us reading in watts
```

I do not think it could be easily changed, unless OCC team is willing to do that and define a new "Sensor Version" to support this case.

@spinler @msbarth Do you think you could make that happen?

**Comment by bradbishop** [comment]
> @bradbishop It's not a new hwmon ABI, instead, existing hwmon already has powerX_average sysfs attribute. So what I am proposing is to add a new "average" interface in /xyz/openbmc_project/Sensor, that defines a Avergae property to represent the powerX_avergae sysfs attribute.

Ah, I misunderstood.  thx for straightening me out.

**Comment by spinler** [comment]
We are already doing unnatural things in phosphor-hwmon just for the OCC, like reading the _label files to find the config files entries, so I would be OK with doing update_tag/accumulator stuff in there too. I assume it can be done in such a way to not affect systems that don't use it.

Keep in mind this comment: https://github.com/openbmc/openbmc/issues/3187#issuecomment-390441800

**Comment by spinler** [comment]
@bradbishop @eddiejames @mine260309 What would you guys think about putting this support into openpower-occ-control?  It already knows when the OCCs are active so it knows the readings are available, and could just host the Sensor.Value interface there?

**Comment by eddiejames** [comment]
> @bradbishop @eddiejames @mine260309 What would you guys think about putting this support into openpower-occ-control? It already knows when the OCCs are active so it knows the readings are available, and could just host the Sensor.Value interface there?

Yea I think that makes sense

**Comment by mine260309** [comment]
> What would you guys think about putting this support into openpower-occ-control? It already knows when the OCCs are active so it knows the readings are available, and could just host the Sensor.Value interface there?

It looks weird to me. openpower-occ-control is for "controlling" the occ, e.g. bind/unbind the occ-hwmon driver, provide methods to passthrough raw data to occ, etc. I feel it weird to handle power sensors there.

So if we are doing this, phosphor-hwmon is a more appropriate place.

**Comment by eddiejames** [comment]
Here's the upstream patch that I tried to support averaging in the driver: https://lkml.org/lkml/2019/5/8/960

**Comment by spinler** [comment]
@mine260309 We talked about this and the outcome was suggesting:
1. Add debugfs attributes for the accumulator and update_tag
2. Put support to read those and put the result on D-Bus in openpower-occ-control.  It already monitors other debugfs entries, like some error flags.
3. The name of the repo can be changed if you can think of a more suitable one, like openpower-occ-hander.  Though I think the consensus was 'control' is still OK.

**Comment by mine260309** [comment]
@spinler Noted.

But maybe you could check @wangkair 's latest PS https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-hwmon/+/24113/9, which calculates the average power by:
1. Calculate the accumulator by kernel's powerX_average * powerX_interval;
2. Calculate the expected average by (accumulator2 - accumulator1) / (interval2 - interval1)

It's nicely done well and tested well, and we do not need extra debugfs attributes.

**Comment by wangkair** [comment]
Closed by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-hwmon/+/24113 .

**Comment by mine260309** [comment]
I think there is one more work to do: update the occ related hwmon configs to use the average power, for all OpenPOWER systems supported in OpenBMC.
