### ISSUE TITLE
Bmcweb changes to store LDAP user role in session object

### ISSUE THREAD

**Issue by raviteja-b** [ibm-openbmc/dev#3140]
Right now bmcweb queries user info using dbus call on every URI, to  improve on performance
we can query information at the time of session creation and store in session object.

getuserinfo interface needs to be done only at the login time not with every request.
=> privilege should be fetched during authentication 
=> persist the privilege in the in memory session object.
=> each successive request will be matched against the privilege which is there in the in-memory session object.

**Comment by raviteja-b** [comment]
Reviews are going on this commit  https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43027/

**Comment by sunharis** [comment]
Ed's bmcweb authentication framework rework at master repo has impact on LDAP. This change is needed to get the LDAP work at upstream master.  Work is still in progress upstream

GHE 1020 works fine. No impact on rainier.

**Comment by sunharis** [comment]
This is needed only if we are pulling Ed's upstream rework on authentication framework

**Comment by sunharis** [comment]
Migrate-Yes

**Comment by rfrandse** [comment]
tracking in jira
