### ISSUE TITLE
COD - Create the Dbus interfaces

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#3147]
The model consists of following main entities:

1 - licenses - these objects represents the features.  There will be a license represnting 
feature(one is to one relation ship) and these objects have state - active, inactive, unknown, etc.
These objects could implement the Delete interface for when a client wishes to disable the license/feature.

2 - manager - the manager object (distinct from freedesktop object manager) provides a method
interface to create new license objects.

**Comment by raviteja-b** [comment]
reviews on going https://github.ibm.com/openbmc/phosphor-dbus-interfaces/pull/43

**Comment by raviteja-b** [comment]
created new PR against ibm-openbmc
https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/23
still reviews going on

**Comment by sunharis** [comment]
Code merged to downstream.
