### ISSUE TITLE
COD: Create the Dbus app

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#3149]
-  Yet to decide about where to HOST this application.
- Either write the new Meson/Auto tools framework or making the changes in the existing one. 
- Write the main function  to make sure that it creates the application. It is a skeleton app.

**Comment by raviteja-b** [comment]
have created new license Dbus  application, Code is up review

**Comment by raviteja-b** [comment]
code in review https://github.ibm.com/openbmc/license-manager/pull/1

**Comment by raviteja-b** [comment]
still in review

**Comment by sunharis** [comment]
Code merged to downstream
