### ISSUE TITLE
COD:  Implement the Manager Interface.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#3151]
Major functionality of the Manager interface would be to Implement a Dbus method which creates the License Dbus object.
This interface would be used by the PLDM to craete the license object once PLDM gets the feature list from the host firmware.

**Comment by raviteja-b** [comment]
code ready and unit tested.
review going on 
https://github.com/ibm-openbmc/license-manager/pull/1

**Comment by sunharis** [comment]
Code merged to downstream
