### ISSUE TITLE
COD: Requirement & Design 

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#3153]
We need to make sure that License object should be persisted on the BMC as it keeps the status of the feature.
Whenever there is a change in the feature, Host firmware notifies to the BMC over PLDM.
PLDM updates the license/feature obect with the correct status.

**Comment by rsnair** [comment]
Story 3149 will cover the efforts needed to persist the license object. Converting this story to cover the requirement & design efforts.

**Comment by rsnair** [comment]
Requirements collection & design direction is complete.
