### ISSUE TITLE
Should use Inventory Item "PrettyName" for Redfish Name

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3158]
https://github.com/openbmc/bmcweb/issues/204

We should look for PrettyName and if it isn't there fall back to the last segment of the URI 

https://ibm-systems-power.slack.com/archives/C1HT3FHNK/p1620407582169500?thread_ts=1620123529.115600&cid=C1HT3FHNK

https://github.com/openbmc/phosphor-dbus-interfaces/blob/495981805244269650bee13d1ee8f13543b2bc5a/xyz/openbmc_project/Inventory/Item.interface.yaml#L5

See review: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40158

This should be a series of commits

**Comment by gtmills** [comment]
https://github.ibm.com/openbmc/bmcweb/pull/143

https://ibm-systems-power.slack.com/archives/G3WAVQYTH/p1620659600330800?thread_ts=1620659278.328800&cid=G3WAVQYTH


https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40158

**Comment by gtmills** [comment]
Google has a review here:  https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43967
@aahmed-2 owns helping drive in

**Comment by aahmed-2** [comment]
Downstream PR here: https://github.com/ibm-openbmc/bmcweb/pull/93

**Comment by aahmed-2** [comment]
Code review in driver

**Comment by mzipse** [comment]
refresh

**Comment by mzipse** [comment]
refresh again

**Comment by mzipse** [comment]
Closing.  Work is complete.
