### ISSUE TITLE
Provide HBB to Hostboot Boot Loader via non-PLDM

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#3159]
Even though this story is not going to be implemented in the PLDM code, it's required to complete the PLDM Hostboot communication Epic.

Background: Hostboot Boot Loader would not use PLDM in P10, it has been deferred to P11. The Hostboot Boot Loader requests the contents of the HBB file. An initial idea was to map the HBB content in a memory window and have a lightweight PLDM download command that the BMC could provide. At this point this new function is not containable.

Therefore, talking with Nick B and Andrew J, the option to provide the HBB content with as little change as the current mechanism (mbox) as possible, is to tweak mboxd so that it doesn't rely in the PNOR table of contents, and instead hardcode whatever is necessary to load HBB (which would be a LID file) into RAM.

**Comment by amboar** [comment]
I suggested we just write a separate tool that's easier to reason about that mboxd. It should only need a couple of open()s, a couple of ioctl()s, mmap() and memcpy(). Should be a 100 lines or so.

**Comment by anoo1** [comment]
The tool could reside in the https://github.com/openbmc/openpower-pnor-code-mgmt repo, which is the one that currently parses the system type.

**Comment by anoo1** [comment]
Assigning to @amboar per Maury's comments in https://github.com/ibm-openbmc/dev/issues/3160#issuecomment-895377324

**Comment by amboar** [comment]
This is desirable but not required as the functionality is provided by the (much more complex) mboxd binary.

**Comment by nmuruli** [comment]
@amboar Can we mark this as code review in driver ?

**Comment by amboar** [comment]
> @amboar Can we mark this as code review in driver ?

Sorry, I don't understand the question? What we have works, just it's about 5% of the code of mboxd. Ideally we'd trim that down, which was the suggestion in some of the comments above.

**Comment by mzipse** [comment]
@amboar , trying to figure out what we should do with this story.  Do we still want to trim down the mboxd code at all?  Also will we still need to do this for P11?  Just trying to figure out whether we should live with what we have or whether this story needs to migrate to Jira.

**Comment by amboar** [comment]
Let's reassess future direction elsewhere.
