### ISSUE TITLE
Swift Power Supply component data readability

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#316]
The power supply EEPROMs have a new VPRI #D keyword that will contain component data that the hardware team wants to be able to get at somehow for inventory tracking/FFDC.

It's a 8KB keyword, can have 128B ASCII data per component, up to 64 components

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Deferring out of Swift.  Can open another issue if we decide a user interface is needed for this on eBMC.
