### ISSUE TITLE
eBMC LED Management :: Enable LEDs on Everest 4S4U box

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#3166]
- Work with System Engineers and understand LED layout and requirements
- Work with system Engineers and get the needed LED details documented in workbook / spread sheet
- Translate the LED information in the workbook / spread sheet into Linux Device tree
- Work with GSI and make sure INDIVIDUAL LEDs are verified
- Update the led-group definition in phosphor-led-manager
- Work with Linux leds-pca955x maintainer

**Comment by vishwabmc** [comment]
I have been working this for some time now .. but opened it here to capture the efforts on this task.

- Work with System Engineers and understand LED layout and requirements :DONE
Work with system Engineers and get the needed LED details documented in workbook / spread sheet :DONE
Translate the LED information in the workbook / spread sheet into Linux Device tree :DONE
Work with GSI and make sure INDIVIDUAL LEDs are verified :ONGOING

**Comment by vishwabmc** [comment]
Work with GSI and make sure INDIVIDUAL LEDs are verified : DONE

Now, waiting on the PR to be reviewed and merged.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Work is complete.  Closing.
