### ISSUE TITLE
GUI : FED : Post Code update table to use ASCII and update the UI for downstream

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3167]
## Overview
- [ ] The UI need to be updated for downstream

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link

## cURL Commands
N/A

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
Need merge of post codes upstream and we can make the small downstream change to show the ASCII instead of HEX

**Comment by sandeepasingh116** [comment]
The UI requires some changes. For reference look [here](https://github.com/ibm-openbmc/dev/issues/1303)

**Comment by sandeepasingh116** [comment]
The code has been pushed downstream:
https://github.ibm.com/openbmc/webui-vue/pull/3

**Comment by mzipse** [comment]
Closing.  Work is complete.
