### ISSUE TITLE
GUI : FED :  Add dividers between table batch action buttons.

### ISSUE THREAD

**Issue by ParishrutB** [ibm-openbmc/dev#3172]
## Overview
- Table batch action buttons (selection actions) need to have dividers between them.

## UX Flow / Interaction Requirements
-  Note: There is no divider between the Cancel button and the button adjacent to it.

## Final Invision Mockup
- https://ibm.invisionapp.com/d/main#/console/15347903/319970027/preview

![image.png](https://images.zenhubusercontent.com/5e53d8992ef7be3be540de28/fc67fd08-96ce-4277-8e82-fd2dc317595c)

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by sneha787** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43500
