### ISSUE TITLE
CEC CM: Add PCIe device/port/cable and battery DBus/Fru record mappings 

### ISSUE THREAD

**Issue by bradbishop** [ibm-openbmc/dev#3175]
Ensure these inventory classes result in FRU record sets and FRU record set PDRs when the FRU inventory table is constructed

**Comment by sampmisr** [comment]
new fru records need to be added and verified

**Comment by jaypadath** [comment]
Below are the not present types in PDR list:

1) PLDM_ENTITY_DRIVE_BACKPLANE = 73,
disk_backplane0
disk_backplane1
disk_backplane2

2) PLDM_ENTITY_FAN = 93,
fan0 to fan5

3) PLDM_ENTITY_SOLID_STATE_SRIVE = 111,
nvme0 to nvme31


4) PLDM_ENTITY_MEMORY_CHIP = 142,
dimm0 to dimm31

5) PLDM_ENTITY_REAL_TIME_CLOCK = 147,
tod_battery

6) PLDM_ENTITY_SLOT = 186,
pcieslot0 to pcieslot11 [total 10 only]

7) PLDM_ENTITY_CABLE = 187,
pcie_cable_card0/cxp_bot
pcie_cable_card0/cxp_top
pcie_cable_card3/cxp_bot
pcie_cable_card3/cxp_top
pcie_cable_card4/cxp_bot
pcie_cable_card4/cxp_top
pcie_cable_card10/cxp_bot
pcie_cable_card10/cxp_top

**Comment by jaypadath** [comment]
CEC CM : Add new inventory items and dd location codes/VINI record in fru record table

https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/43779
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/43862
