### ISSUE TITLE
CEC CM:Implement OEM PCIe link status/type/speed/width effectors

### ISSUE THREAD

**Issue by bradbishop** [ibm-openbmc/dev#3176]
Provide other PLDM stacks a mechanism for informing the BMC of PCIe device status.  These attributes should be passed through to the correct PCIe device inventory object on DBus.

**Comment by sampmisr** [comment]
will have a discussion about defining the state sets and entity ids. also need a way to map an effecter to the correct DBus object

**Comment by nmuruli** [comment]
Moving this to Brad as he will be helping us in PCIe HW Topology work

**Comment by mzipse** [comment]
Closing this the work is complete.  Just not sure we implemented as defined above.  But it's done.
