### ISSUE TITLE
Swift: IO Card temps via PLDM

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#318]
Can get these via MCTP.  Needed for can control.  May need other data from the cards as well, like type.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by amboar** [comment]
> would need to handle missing cards, cards that don't support PLDM, etc

From the structure of your bullet points it sounds like solving the problem at the wrong layer? If the peripheral doesn't support PLDM but supports MCTP, then we need a different daemon, not wedge something non-PLDM into the PLDM daemon.

**Comment by spinler** [comment]
I think I was just capturing requirements at the time.  Doesn't matter to me how it is implemented.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Yes, this is gathering I/O Temps via PLDM.  However at this time, it doesn't look like there are any I/O Adapters that support PLDM.  So this work is on hold.

**Comment by spinler** [comment]
Handled elsewhere.
