### ISSUE TITLE
Add compile flag to turn off the old Power/Thermal 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3183]
Similar to https://github.com/openbmc/bmcweb/commit/2db77d34ca673f32411621b7e34b039dec948bd3#diff-76ea9078099f2ee8cc0e760a874dd153f225ba16ad10375c24ab6cd53518f3c4 need a "redfish-allow-deprecated-power-thermal" which should initially be true (enabled; allowing the old thermal/power).
 
At a later date, let's say 6 months, we can move this flag to defaulted off. 
At an even later date we can remove the old Power / Thermal implementation (this story does not track this work and can be closed after a flag is added)

This work needs to be done after the new PowerSubsystem and ThermalSubsystem commits merge, due to this I added a Blocked label at this time.

**Comment by lxwinspur** [comment]
review by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/44026
