### ISSUE TITLE
GUI : FED : Hardware Inventory / Status - Add Quick  links

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3185]
## Overview
- [ ] Add Overview

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] Add Link
### Screen capture
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/c86d8d26-4e2e-41a3-8a72-32975782ac68)

## cURL Commands
- [ ] Add cURL commands

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43420

**Comment by derick-montague** [comment]
Did you talk with @gtmills about the HTML5 history mode? 
https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

**Comment by derick-montague** [comment]
> Did you talk with @gtmills about the HTML5 history mode?
> https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations
I talked to Gunnar and we don't have the resources to set the priority to add this to BMCWeb.
