### ISSUE TITLE
GUI : FED : Dump download file name

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3186]
## Overview
The test team has found some issues when downloading and extracting the dumps file due to the spaces in the file name. Currently, the name follows this pattern:

`BMC Dump Entry <dump-id>`

The test team has requested that the name use the following pattern so the customer knows what to extract.

`BMC_Dump_Entry_<dump-id>.tar.gz`

## UX Flow / Interaction Requirements
- [ ] Update the file download name

## Final Invision Mockup
N/A

## cURL Commands
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by sneha787** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43800
