### ISSUE TITLE
Rainier: PFP: Initial fan-control(events) configuration

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#319]
Can eventually be broken up into more stories. Just tracking the functions here for now.

* fan-presence config ( #601 )
* fan-monitor config - only 1 rotor per blower ( #959 )
* fan events yaml w/ sensors and temps ( #319 )
* fan error yaml - shutdown on 2 blower fails (https://gerrit.openbmc-project.xyz/22591)
* set QuickPowerDrop GPIO on rotor fails ( #965 )
* air vs water differences, etc ( #966 )

Will need to ensure we have all the necessary hwmon drivers in place and configured ahead of time. ( #310 )

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
This references many Swift stories that have been closed and at this time, all the corresponding Rainier stories for the listed items have been delivered where applicable. Closing
