### ISSUE TITLE
PFP::monitor - `Count` method timer should start/stop when count transistions away/from 0 respectively

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3194]
Instead of having the `count` method's timer running all the time, it should be started when a up-count 'tick' is registered against a tach sensor (i.e. tach sensors was initially seen as out-of-range) and then the timer should stop once a tach sensor returns back to 0.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/43688
