### ISSUE TITLE
PFP::control - Verify signals for objects owned continue to be received

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3195]
After testing whether objects owned on dbus by fan control can have a property changed and fan control handle that property being changed (per configuration), it was found that this works now where it had not back when enabling the `xyz.openbmc_project.Control.ThermalMode` interface on fan control was first put in place. This may be due to changes in sdbusplus async handling of signals, but this functionality in fan control should be re-verified once fan control is fully configured and gets many propertiesChanged signals from dbus to make sure its owned properties are not lost when changed.

If found to not work later on, add the following to the zone object and call it per property on a zone object that can change (i.e. `Current` property on the `xyz.openbmc_project.Control.ThermalMode` interface):
```
void Zone::propertiesChanged(const std::string& intf, const std::string& prop,
                             PropertyVariantType value)
{
    using namespace sdbusplus::bus::match;
    sdbusplus::message::message nullMsg{nullptr};
    auto path = fs::path{CONTROL_OBJPATH} /= getName();

    _manager->setProperty(path, intf, prop, value);
    auto& signalData =
        _manager->getSignal(rules::propertiesChanged(path, intf));
    if (!signalData.empty())
    {
        auto& pkgs = std::get<std::unique_ptr<std::vector<SignalPkg>>>(
            signalData.front());
        if (pkgs)
        {
            _manager->handleSignal(nullMsg, pkgs.get());
        }
    }
}
```
And then filter the associated signal subscription from happening for objects owned by fan control.

**Comment by rfrandse** [comment]
tracking in jira
