### ISSUE TITLE
Tighten ssh encryption protocols (was: and web server xss protection)

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#32]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Wednesday May 16, 2018 at 17:54 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3186_

----

SW429156
This is in response to a security scan.  There are four parts:
1. Disable ssh triple-DES ("DES-CBC3").
2. Disable ssh CBC mode cipher encryption, and enable CTR or GCM cipher mode encryption.
3. Disable ssh MD5 and 96-bit MAC algorithms.
4. Update the web server to protect from XSS vulnerability.  -- Moved to # 3195.

**Comment by rfrandse** [comment]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Thursday May 17, 2018 at 01:17 GMT_

----

Maybe we should go to a more recent openssh version?  It looks like openbmc is using OpenSSH version **7.5p1** (openbmc/import-layers/yocto-poky/meta/recipes-connectivity/openssh/openssh_7.5p1.bb) and **7.7p1** is available.

If we upgrade, are there any concerns connecting older ssh clients?  For example RHEL 6.8 uses OpenSSH 5.3p1 (I think) which ought to able to connect to an OpenSSH 7.7 server (I think).

According to https://www.openssh.com/releasenotes.html:
OpenSSH 7.6 disables CBC by default
OpenSSH 5.1 prefers CTR
OpenSSH 3.7.1 added support for CTR
OpenSSH 6.2 added support for GCM
OpenSSH 7.2 disables MD5
OpenSSH 6.1 removed hmac-sha2-256-96 and hmac-sha2-512-96

**Comment by rfrandse** [comment]
<a href="https://github.com/geissonator"><img src="https://avatars2.githubusercontent.com/u/1612261?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geissonator](https://github.com/geissonator)**
_Thursday May 17, 2018 at 01:23 GMT_

----

We tend to bring in packages like this when we do yocto updates.  We're currently at yocto2.4.  I believe @bradbishop has started looking at getting us up to 2.5.  May want to see what version of ssh that will bring in for us.

**Comment by rfrandse** [comment]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Friday May 18, 2018 at 14:12 GMT_

----

Going to OpenSSH 7.6 would be good enough because it disables CBC.  We wouldn't need to go to 7.7.

If we must stay at OpenSSH 7.5p1 and cannot go to 7.6, we could add a /etc/ssh/sshd_config file that disables CBC.

**Comment by rfrandse** [comment]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Friday May 18, 2018 at 19:53 GMT_

----

According to https://www.yoctoproject.org/software-overview/downloads/,
release information for "YP Core - Sumo 2.5"
contains this entry: openssh: update to 7.6
So, updating to yocto poky 2.5 will fix the openssh issue.

The web server XSS issues was moved to #3195.

**Comment by rfrandse** [comment]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Tuesday May 29, 2018 at 18:23 GMT_

----

Oops.  Although Yocto includes both OpenSSH and Dropbear SSH, I was informed our implementation uses dropbear.  (So fixes to OpenSSH won't fix this problem.)  Issue #1229 has more detail for dropbear.

**Comment by rfrandse** [comment]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Monday Aug 06, 2018 at 22:35 GMT_

----

To configure dropbear to drop the insecure ciphers, according to https://github.com/mkj/dropbear/blob/master/default_options.h, we need to create a new file:
```
localoptions.h
#define DROPBEAR_TWOFISH256 0
#define DROPBEAR_TWOFISH128 0
#define DROPBEAR_ENABLE_CBC_MODE 0
#define DROPBEAR_SHA1_HMAC 0
#define DROPBEAR_SHA1_96_HMAC 0
```

**Comment by joseph-reynolds** [comment]
I had created a review in openbmc/import-layers: https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc/+/11894/
but now will be trying to upstream the dropbear patch.

**Comment by joseph-reynolds** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-phosphor/+/13278/
