### ISSUE TITLE
Swift pinhole reset investigation

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#320]
I think the panel has one.  Is it wired to the BMC?  Any code configuration/handling needed?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Looks like it's wired into GPIOB3, so seems like we'd have work.  This story would just be for resetting the BMC.  #365 is for doing a factory reset on a long press.

**Comment by spinler** [comment]
Asked around, and as of now we don't have a requirement to implement the BMC reset part of this.  Closing.
