### ISSUE TITLE
PLDM:  add entity instance as an input parameter to libpldm

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#3202]
libpldm will be able to take entity instance number while creating entity association records. so that the entity instance number corresponds to the actual instance

**Comment by sampmisr** [comment]
pldm_pdr_add_fru_record_set() adds a fru record set PDR to the repo. this one takes the entity_instance_num of the fru as a parameter. that means currently we can create fru records with entity instance numbers as needed. this api does not need any change 

pldm_entity_association_tree_add() adds an entity to the entity association tree. it takes a pldm_entity as a parameter.
@param[in/out] entity - pointer to the entity to be added. Input has the entity type. On output, instance number and the container id are populated.
                                                   

as of now the current code determines the entity instance number while adding the entity in the tree.
there should be a change made in the above api to take another parameter as "uint16_t entity_instance_number". if that is 0 then use the existing logic. if there is some entity instance number provided which is greater than 0 then that should be used while adding the entity in the tree. make sure we check the existing entity instance numbers of the entity before adding a new instance since we can have arbitrary instance numbers coming in.

and in libpldmresponder/fru.cpp: in populateRecords() function the same entity instance number should be used when creating the fru record set PDR. this should be happening automatically. just verify once 

testing:
1.verify the api through unit test
2.create fru records with arbitrary entity instance number (like 63,37,44 and 89 for procs) and verify the fru record set and entity association PDR 
3.create two same entities with arbitrary instance number like 32 and 67. and then create next instance without passing the entity instance number. the code should create the entity with instance 68. ideally this situation should not happen because one should follow either of the path when populating the entity tree, always provide the instance number or do not provide the instance number. it will be user's responsibility if they mix up both. say for above example an entity instance 68 got created and then user calls pldm_entity_association_tree_add() with entity instance number 68 as input, that should not get added and return some kind of failure

 @return pldm_entity_node* - opaque pointer to added entity - can be changed to return NULL

**Comment by lxwinspur** [comment]
review by: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/44027
