### ISSUE TITLE
GUI : FED : Add Export/delete all logs buttons on Event Logs

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3203]
## Final Invision Mockup
- https://ibm.invisionapp.com/d/main#/console/15347903/319992747/preview

![image](https://user-images.githubusercontent.com/61419136/120800195-4c707180-c55d-11eb-93e2-8a723b544709.png)

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by dixsie** [comment]
resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43751

**Comment by ParishrutB** [comment]
Update after 06/03/2021

![image](https://user-images.githubusercontent.com/61419136/120799703-b6d4e200-c55c-11eb-9818-4a3f26b71989.png)
