### ISSUE TITLE
eBMC LED Management :: GA_2: rainier/everest: opencapi connector LEDs

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#3205]
On PASS_2 boards, there are LEDs by each OpenCAPI connector slots (SLIMSAS) and there are 6 of them.

Work involved here : 
- Update the rainier device tree for these 6 LEDs
- Update `rainier-2u/rainier-4u/rainier-1s4u` `led-group-config.json` with identify and fault groups
    Example: https://github.com/openbmc/phosphor-led-manager/blob/master/configs/ibm%2Ceverest/led-group-config.json#L9136

**Comment by lkammath** [comment]
@jinuthomas we will have to make this changes in the LED group config once all the IM support for everest is in

**Comment by lkammath** [comment]
OpenCAPI connectors are not applicable for rainier. only for everest

**Comment by rfrandse** [comment]
tracking in jira
