### ISSUE TITLE
eBMC LED Management :: Everest :: Update associations file

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#3207]
Currently, only some of the D-Bus objects have associations. The association file needs to be updated to contain everything.

Current association : https://github.com/openbmc/openbmc/blob/master/meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager/p10bmc/ibm%2Ceverest_associations.json

Refer Rainier : https://github.com/openbmc/openbmc/blob/master/meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager/p10bmc/ibm%2Crainier-2u_associations.json

Need Everest D-Bus objects from @santoshpuranik and then we can update the Everest associations.

**Comment by lkammath** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/43925

**Comment by lkammath** [comment]
Completed.
