### ISSUE TITLE
GUI : FED : Table filter menu width and margins

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3215]
## Overview
The filter menu width is not wide enough to accommodate the dump types without wrapping. It will be easier to scan if we can increase the width of the menu and add more white space between the filter items.

## Acceptance criteria
To increase the readability and ease of scanning the filter menu items, this story will: 
- [ ] Increase the menu width
- [ ] Increase filter menu item margins
- [ ] Test the filters on other pages, for example, event logs and verify the changes work with all content

## As is 
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/2a59c1c8-eeef-4677-887c-8b48093ea760)

## To be
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/d81c1dfd-0f90-4551-a476-8db26ec05057)

## cURL Commands
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] **Resolved any JavaScript errors thrown to the console**

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by sandeepasingh116** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43834

**Comment by sandeepasingh116** [comment]
Merged.
