### ISSUE TITLE
Cable Card Port objects are exposed for NVME JBOF

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#3218]
## Actual Behavior

On rain104bmc, on PCIE slot_10, there is a JBOF card. It is reported as Cable card and its Ports have been exposed.

            │ ├─/xyz/openbmc_project/inventory/system/chassis/motherboard/pcie_cable_card10/cxp_bot
            │ └─/xyz/openbmc_project/inventory/system/chassis/motherboard/pcie_cable_card10/cxp_top

Redfish : 

$ curl -k -H "X-Auth-Token: $token" -X GET https://${BMC_IP}/redfish/v1/Systems/system/FabricAdapters/pcie_cable_card10/Ports
{
  "@odata.id": "/redfish/v1/Systems/system/FabricAdapters/pcie_cable_card10/Ports",
  "@odata.type": "#PortCollection.PortCollection",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Systems/system/FabricAdapters/pcie_cable_card10/Ports/cxp_bot"
    },
    {
      "@odata.id": "/redfish/v1/Systems/system/FabricAdapters/pcie_cable_card10/Ports/cxp_top"
    }
  ],
  "Members@odata.count": 2,
  "Name": "Port Collection"
}

However, CXP_TOP and CXP_BOT are applicable only for **true** cable cards. 

## Expected Behavior

Either they are shown as Non-Cable cards -or- their ports should not be exposed.

So, I would expect just this : 

            │ ├─/xyz/openbmc_project/inventory/system/chassis/motherboard/pcie_cable_card10/
            │ └─/xyz/openbmc_project/inventory/system/chassis/motherboard/pcie_cable_card10/

$ curl -k -H "X-Auth-Token: $token" -X GET https://${BMC_IP}/redfish/v1/Systems/system/FabricAdapters/pcie_cable_card10/Ports
{
  "@odata.id": "/redfish/v1/Systems/system/FabricAdapters/pcie_cable_card10/Ports",
  "@odata.type": "#PortCollection.PortCollection",
  "Members": [],
  "Name": "Port Collection"
}

## Steps to Reproduce the Problem

- Put a Non cable card ( NVME JBOF card ) in a slot that takes a cable card

**Comment by bradbishop** [comment]
I don't really view this as a bug.  Perhaps it's a bug that 2 ports are exposed instead of 4 but I need the ports in the Redfish model for Flett to be able to implement the PCIe topology screen correctly.

Does anyone recall the motivation for opening this bug?  Was the observed behavior causing something else to break?

**Comment by spinler** [comment]
FWIW, 'CXP' describes the type of port on a cable card that connects to a MEX.

**Comment by rfrandse** [comment]
tracking in jira
