### ISSUE TITLE
GUI : FED : Update navigation and routes to use updated IA

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3221]
## Overview
The IA study revealed a need to change the navigation and routing for the UI. The following changes need to be made to accommodate the IA findings. This could turn into a large story if we determine we need to accommodate changes in store and i18n key changes. It will be beneficial to break this story down in a refinement session.

## Acceptance criteria
The following are the names and related pages that will need to be updated.

### Overview
- [x] Update icon to use carbon icon - Actions / Controls / dashboard

### Assignees
- [x] Overview & Logs - Derick
- [x] Hardware Status - Sandeepa
- [x] Operations - Sandeepa
- [x] Settings - Sandeepa
- [x] Security - Sandeepa
- [x] Resource - Sandeepa

#### Logs
- [x] Add new `Logs` section
- [x] Use carbon icon - Actions / Controls / `text-link--analysis`

#### Resource management
- [x] Add new `Resource management` section
- [x] Use carbon icon - Organization / Data / `data--base--alt`
- [x]  Move `Manage power usage to `Resource management` and rename to `Power`

### Hardware status
- [x] Rename section from `Health` to `Hardware status`
- [x] Rename `Hardware status` page to `Inventory and `LEDs`
- [x] Move dumps to `Logs` section
- [x] Move event logs to `Logs` section 
- [x] Update route for sensors

### Control
- [x] Rename from `Control` to `Operations`
- [x] Remove `Server LED` page
- [x] Move `Firmware` to `Operations`

### Configuration
- [x]  Rename from `Configuration` to `Settings`
- [x] Move `Power restore policy` from `operations` to `Settings`
- [x] Rename `Date and time settings` to `Date and time`
- [x] Rename `Network settings` to `Network`
- [ ] Remove `SNMP settings`
    - #2173 will be added once merged
    - Sandeepa has a story, #2173, that  needs to be updated to match new IA structure
        - If Alerts is merged first, this will be done in this story.
        - If this story is merged first, Sandeepa will need to update #2173 

### Access and control
- [x] Change icon to Organization / File / `security`
- [x] Rename from `Access and control` to `Security and access`
- [x] Move `Security settings` to `Security and access` and rename to `Policies`
- [x] Rename `Client sessions` page to `Sessions`
- [x] Rename `Local user management` page to `User management`
- [x] Rename `SSL certificates` page to `Certificates`

### IA 
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/ce05ef68-3a28-4039-916b-e2baae329865)

### Navigation
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/de0944b6-71e6-4051-97aa-982260add800)

## cURL Commands
N/A

## Notes
- **This will require changes to routes and I18n keys**

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
Need to add a story for any navigation text changes downstream. For example, Sessions is the upstream name and HMC and user sessions is the downstream link title.

**Comment by derick-montague** [comment]
## Overview icon and Logs section
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/44527

**Comment by sandeepasingh116** [comment]
**Hardware section and Inventory and LEDs page**
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/44724

**Comment by sandeepasingh116** [comment]
### **Update Control section to operations**
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/44912

**Comment by sandeepasingh116** [comment]
### **Update configuration section to settings**

resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/45034

**Comment by sandeepasingh116** [comment]
### **Update access and control to security and access**
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/45229

**Comment by sandeepasingh116** [comment]
### **Add resource management section**
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/45331
