### ISSUE TITLE
eBMC LED Management :: Clear Fault LEDs during PowerOn

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#3228]
https://github.com/ibm-openbmc/dev/issues/2115 added a code to clear both Identify and Fault Indicator LEDs as part of power on. However, we need a small update to that path because the faults are handled via setting the OperationalStatus on the Inventory object as opposed to setting fault led and thus LED setting OperationalStatus.

Here is the summary of the changes needed to be done .

- Update **meta-ibm/recipes-phosphor/leds/phosphor-led-manager/obmc/led/set-all/groups/config**  to exclude _fault groups.
EXCLUDED_GROUPS=bmc_booted power_on **_fault**

- Write a new shell script that would 
  - List all the inventory D-Bus objects implementing `xyz.openbmc_project.State.Decorator.OperationalStatus`
  - For each of those : set `Functional` property to `true`

Make sure this new shell script gets called in all places where the led-set-all-groups-asserted.sh is getting called

Refer: meta-ibm/recipes-phosphor/leds/phosphor-led-manager/obmc-led-set-all-groups-asserted@.service on how to invoke that script

**Comment by vishwabmc** [comment]
There is an additional work here and that is as below : 

- In addition to setting the `OperationalStatus`,  do the one below : 
    - Remove the `critical` association that is set with Chassis.

If `fan0_fault` is what we are acting on to clear the fault, then just remove the critical association. 
Ex : Remove this association : /xyz/openbmc_project/inventory/system/chassis/critical --> /xyz/openbmc_project/inventory/system/chassis/motherboard/fan0  

- Better yet, don't do per objects.. delete all the associations that is ` /xyz/openbmc_project/inventory/system/chassis/critical`

Please see @spinler if there is a way to do this via script..

**Comment by lkammath** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-led-manager/+/45616
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/45615

These two commits take care of the fault clear part 

The additional work mentioned to remove the critical association will be handled with separate commit

**Comment by lkammath** [comment]
As per the design direction plan is to move the script to PIM and write the supporting the recipe . Here are PR's for same

https://github.com/ibm-openbmc/phosphor-inventory-manager/pull/1/
https://github.com/ibm-openbmc/openbmc/pull/185

**Comment by lkammath** [comment]
ibm-openbmc/phosphor-inventory-manager#1 - OperationalStatus related script changes
ibm-openbmc/phosphor-inventory-manager#3 - App to remove critical association
https://github.ibm.com/openbmc/openbmc/pull/1394 - Recipe changes to call both script and remove critical association

**Comment by lkammath** [comment]
https://github.ibm.com/openbmc/openbmc/pull/1401 - SRCREV bump and recipe changes are merged
