### ISSUE TITLE
GUI: Update SNMP page

### ISSUE THREAD

**Issue by BeccaBroek** [ibm-openbmc/dev#323]
The design team proposed some updates and improvements to the current SNMP page. 
https://github.com/openbmc/phosphor-webui/issues/37

The following needs to be updated:
- New 'add manager' button style
- field validation 
- possible 'test' button (still under discussion)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by BeccaBroek** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/17727/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
