### ISSUE TITLE
GUI : FED : Network - Default gateway set to eth0

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3239]
## Expected Behavior
Changing the interface should also update the interface elements.

## Actual Behavior
The default gateway does not change when changing the interface. The user cannot set a default gateway for `eth1`, only for `eth0`

## Steps to Reproduce the Problem

  1. Find a system with two interfaces. I used rain137
  1. Login and go to Network settings
  1. Change the interface to `eth1`

## Specifications
  - Browser: All
  - Version:

**Comment by derick-montague** [comment]
I tested on rain127 earlier and noticed that this patchset was pulled in and working. https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24106

It is expected that the default gateway can be pulled from the first IP as we are doing today, just that it will be based on interface and not system level.

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/44628

**Comment by dixsie** [comment]
Work will be completed in #2130  Network settings redesign
