### ISSUE TITLE
MPIPL:Mechanism to handle memory preserving boot request

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#324]
Still discussing the generic  request type to to inform the BMC about the memory preserving type boot request. 
   This issue will track all work related to handling host/SBE request to change the BMC state to MPIPL type IPL.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Already created sub issues related to this , invalidating this nwo
