### ISSUE TITLE
Rainier: BMC is not sending snmptrap to snmp manager

### ISSUE THREAD

**Issue by sunharis** [ibm-openbmc/dev#3240]
## Expected Behavior
snmp trap should be received at remote snmp manager

## Actual Behavior
Trap is not received

## Steps to Reproduce the Problem
  1. Configure SNMP manager on BMC
  2. Generate error on BMC using busctl commands
  3. Check for the trap received at the snmp manager
  
## Specifications
  - Subscription:
 curl -k -H "X-Auth-Token: $bmc_token" -D get.txt -X GET  https://${bmc}/redfish/v1/EventService/Subscriptions/snmp20
{
  "@odata.id": "/redfish/v1/EventService/Subscriptions/snmp20",
  "@odata.type": "#EventDestination.v1_7_0.EventDestination",
  "Context": "",
  "Destination": "snmp://9.41.166.100:162",
  "EventFormatType": "Event",
  "Id": "snmp20",
  "Name": "Event Destination snmp20",
  "Protocol": "SNMPv2c",
  "SubscriptionType": "SNMPTrap"

Generate error on BMC using busctl commands
busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging xyz.openbmc_project.Logging.Create Create ssa{ss} xyz.openbmc_project.Common.Error.InternalFailure xyz.openbmc_project.Logging.Entry.Level.Error 0

  - Version:
ID=openbmc-openpower
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="fw1020.00-23.3"
VERSION_ID=fw1020.00-23.3-1020.2126.20210623a (NL1020_004)
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) fw1020.00-23.3"
BUILD_ID="fw1020.00-23.3"
OPENBMC_TARGET_MACHINE="p10bmc"

**Comment by sunharis** [comment]
@ChicagoDuan Please check. This issue seems to be originated from https://github.ibm.com/openbmc/bmcweb/commit/c4e2ea375aadb36998a17ee6b57d737c10b56809#diff-b12fbd7828633f3aead13efcff12d6a9

**Comment by ChicagoDuan** [comment]
> @ChicagoDuan Please check. This issue seems to be originated from https://github.ibm.com/openbmc/bmcweb/commit/c4e2ea375aadb36998a17ee6b57d737c10b56809#diff-b12fbd7828633f3aead13efcff12d6a9

I can't open the link, Is it this commit?：https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599/24

Can you use busctrl to check the SNMP client port and address on D-BUS, such as:
busctl introspect xyz.openbmc_project.Network.SNMP /xyz/openbmc_project/network/snmp/manager/20
Please post the result of the busctl introspect command.

**Comment by sunharis** [comment]
> I can't open the link, Is it this commit?：https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599/24
Yes.

I dont have the system in the same state.

**Comment by ChicagoDuan** [comment]
> I dont have the system in the same state.

Sorry I don't understand you. Can you send the following busctl commands ?  Or do you mean you don't have  xyz.openbmc_project.Network.SNMP service?

`busctl introspect xyz.openbmc_project.Network.SNMP /xyz/openbmc_project/network/snmp/manager/20`

`busctl introspect xyz.openbmc_project.Network.SNMP`

**Comment by sunharis** [comment]
@gkeishin Please help with more data.

**Comment by prkatti1** [comment]
root@bmc:~# busctl tree xyz.openbmc_project.Network.SNMP
└─/xyz
  └─/xyz/openbmc_project
    └─/xyz/openbmc_project/network
      └─/xyz/openbmc_project/network/snmp
        └─/xyz/openbmc_project/network/snmp/manager
          ├─/xyz/openbmc_project/network/snmp/manager/13
          └─/xyz/openbmc_project/network/snmp/manager/20

root@rain205bmc:~# busctl introspect xyz.openbmc_project.Network.SNMP /xyz/openbmc_project/network/snmp/manager/20
NAME                                TYPE      SIGNATURE RESULT/VALUE  FLAGS
org.freedesktop.DBus.Introspectable interface -         -             -
.Introspect                         method    -         s             -
org.freedesktop.DBus.Peer           interface -         -             -
.GetMachineId                       method    -         s             -
.Ping                               method    -         -             -
org.freedesktop.DBus.Properties     interface -         -             -
.Get                                method    ss        v             -
.GetAll                             method    s         a{sv}         -
.Set                                method    ssv       -             -
.PropertiesChanged                  signal    sa{sv}as  -             -
xyz.openbmc_project.Network.Client  interface -         -             -
.Address                            property  s         "xx.xx.xx.xx" emits-change writable
.Port                               property  q         162           emits-change writable
xyz.openbmc_project.Object.Delete   interface -         -             -
.Delete

**Comment by prkatti1** [comment]
root@bmc:~# busctl tree xyz.openbmc_project.Network.SNMP
└─/xyz
└─/xyz/openbmc_project
└─/xyz/openbmc_project/network
└─/xyz/openbmc_project/network/snmp
└─/xyz/openbmc_project/network/snmp/manager
├─/xyz/openbmc_project/network/snmp/manager/13
└─/xyz/openbmc_project/network/snmp/manager/20

root@bmc:~# busctl introspect xyz.openbmc_project.Network.SNMP /xyz/openbmc_project/network/snmp/manager/20
NAME TYPE SIGNATURE RESULT/VALUE FLAGS
org.freedesktop.DBus.Introspectable interface - - -
.Introspect method - s -
org.freedesktop.DBus.Peer interface - - -
.GetMachineId method - s -
.Ping method - - -
org.freedesktop.DBus.Properties interface - - -
.Get method ss v -
.GetAll method s a{sv} -
.Set method ssv - -
.PropertiesChanged signal sa{sv}as - -
xyz.openbmc_project.Network.Client interface - - -
.Address property s "xx.xx.xx.xx" emits-change writable
.Port property q 162 emits-change writable
xyz.openbmc_project.Object.Delete interface - - -
.Delete

**Comment by ChicagoDuan** [comment]
> xyz.openbmc_project.Network.Client interface - - -
> .Address property s "xx.xx.xx.xx" emits-change writable
> .Port property q 162 emits-change writable

Hi prkatti1 and sunharis.
If the address and port are correct, so this issue is not related to this commit (https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599/24).  This commit just sets the address and port to D-Bus , it doesn't send SNMP traps.

Do you configure phosphor-snmp correctly? phosphor-snmp is the service that sends the SNMP trap. I think you can ask @ratagupt  for some help. He is maintainer of phosphor-snmp.

**Comment by sunharis** [comment]
Hi @ChicagoDuan , I verified that the POST command to set the SNMP manager at BMC sets the address and port at the DBus. I will check more on why the traps are not sent

**Comment by ChicagoDuan** [comment]
Hi @sunharis , How about this issue？
I did many tests on both withospoon and fp5280g2, and received traps.

Have you configured the following yaml file on Rainier?
https://github.com/openbmc/openbmc/blob/master/meta-ibm/recipes-phosphor/dbus/events-policy/config.yaml

**Comment by sunharis** [comment]
Yes. This yaml is in the rainier.
What i found is - the traps are sent after i patched the phosphor-dbus-monitor from the master repo. I had just added some traces. 
Not sure why it does not work without my patch. 

I think this issue can be closed, since this is something to do with the phosphor-dbus-monitor. Thank you for the support and investigations.
