### ISSUE TITLE
Handle Host Firmware Secure Version

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#3241]
Per Joseph:
BMC code handling (A) host firmware secure version and (B) host minimum secure version.  For example, it would know (and report?) these numbers, and tell the operator when they are about to use a host firmware that is less than the minimum secure version.
BMC code handling the “Secure Version Lock-in Policy” as outlined above.
This would be a follow on to https://github.com/ibm-openbmc/dev/issues/2384 which enhanced the BMC with the bare minimum “host anti-rollback” support.
Contrast with https://github.com/ibm-openbmc/dev/issues/3026 which adds BMC firmware anti-rollback protection.

**Comment by anoo1** [comment]
@joseph-reynolds for your awareness

**Comment by cjengel** [comment]
The changes required for this are :
- Enable host firmware to indicate current minimum secure version to the BMC
- Display current host minimum secure version on UI
- Detect the host secure version of an incoming FW image and block update if below minimum secure version
- Provide a mechanism via the service account to disable the block indicated above

**Comment by anoo1** [comment]
Per discussion with Joseph and Chris, there's no pending work on the BMC side:
```
the minimum secure version check must not block the image install:
For example, the CE/Service Rep would need to do that [roll back to a release earlier than the minimum security version] if they ever need to defeat the host-anti-rollback protection.
Also, when the host anti-rollback protection is engaged, it block the host from booting, but it does not affect the BMC operation (which continues normally).
```

It was also discussed it'd be nice to have a way for the BMC to detect the error and log it.
