### ISSUE TITLE
 eBMC LED Management :: PEL : Create critical association as part of setting OperationalStatus to false

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#3244]
When PEL code decides to make something as faulted, it will:
  - Set State.Decorator.OperationalStatus property:Functional to false
  - Set the `critical` association from `motherboard/chassis` to Inventory D-Bus object on which it sets the `OperationalStatus`.
     Ex : /xyz/openbmc_project/inventory/system/chassis/critical --> /xyz/openbmc_project/inventory/system                        /chassis/motherboard/fan0

It is possible that there are multiple critical associations depending on the number of FRU D-Bus objects but that's okay.

**Comment by spinler** [comment]
Some notes:

- The code would run in the LightPath::activate() function in service_indicators.cpp
- Association documentation is at https://github.com/openbmc/docs/blob/master/architecture/object-mapper.md#associations
- The inventory manager has a Notify() method to create new interfaces on its objects, in this case xyz.openbmc_project.Association.Definitions
- Inventory items may already have this interface on them containing other associations, so would need to RMW it if so
- Probably don't need to add duplicate entries to the Associations property tuple if another PEL is calling out the same inventory item.

**Comment by spinler** [comment]
The Associations property on the xyz.openbmc_project.Association.Definitions interface, an array of tuples, would need the following entry added on the called out object path:
```
 ["health_rollup", "critical", "/xyz/openbmc_project/inventory/system/chassis"]
```
if it isn't already present.  This would tell the mapper to create the follow dbus objects:
.../proc0/health_rollup
.../system/chassis/critical

What I'm not sure of is if every object path will already have that interface on it, from being hardcoded in the inventory manager's associations JSON file.

**Comment by sumitk56** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/45073
