### ISSUE TITLE
eBMC LED Management :: Health support for Manager 

### ISSUE THREAD

**Issue by vishwabmc** [ibm-openbmc/dev#3249]
Implement Health property for Manager schema.. It might already be there.. but need to verify it works all okay.

**Comment by mzipse** [comment]
refresh

**Comment by ChicagoDuan** [comment]
It looks like it already supports Health:
https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/managers.hpp#L2010

Can we close this task?
