### ISSUE TITLE
GUI : FED : Remove IndicatorLED property from locale file

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3253]
## Overview
This property should have been replaced by `IdentifyLED`. The goal of this story is to verify that this propety is no longer used and remove it.
```
      "identifyLed": "Identify LED",
      "indicatorLed": "Indicator LED",
```
## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by Srisuk** [comment]
The key is not present as of now in the code, needs to be checked in @dixsie's [story](https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43231), post that issue will be closed.

**Comment by dixsie** [comment]
@Srisuk just double checked my stories in Gerrit and I am not using the indicatorLed key like I thought (my fans story has a merge conflict I need to resolve and the key will be removed [here](https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/43372/5/src/locales/en-US.json#375) once I do) .

We can close this story.
