### ISSUE TITLE
GUI : FED : Hardware Status: Update multiple <dt> use on BMC Manager table

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3254]
## Overview
In this story we need to create a hierarchy for our <dl> for `Graphic console` and `Serial console` that has a left margin on the <dl> associated with these sections.

## UX Flow / Interaction Requirements
- [ ] Use multiple <dl> elements to separate each section
- [ ] Use a `<p>`element for the group section name, e.g. `<p>Graphic console</p>` rather than a heading
- [ ] Match the white space of the design mock for both the vertical margin between the `<p>...</p><dl>...</dl>` and for the horizontal margin used to indent the associated `<dl>`

## Final Invision Mockup
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/0309490c-dc1d-4e94-84bd-6f667b444552)

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/a2da1c52-04f0-466b-9e53-a8a20f3d006b)- 
![image](https://user-images.githubusercontent.com/68803917/124272871-f3e0c400-db5c-11eb-9d6c-92cdf778f499.png)

[ ] Add Link

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by sandeepasingh116** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/44690
