### ISSUE TITLE
Rainier / Everest Fan Control Sensor Dependencies

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3255]
---
- **TMP275 ambient on dbus**
  - [X] Rainier (Spinler)
  - [x] Everest (Bruce) - https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44670
- **DPS310 ambient on dbus**
  - [X] Rainier (Bruce)
  - [x] Everest (Bruce) - https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44670
- **Si7021-A20 ambient on dbus**
  - [x] Rainier (Bruce) - https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44290
  - [x] Everest (Bruce) - https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44670
- **Median ambient temp on dbus**
  - [x] Rainier (Rashmica) - https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/43484
  - [x] Everest (Rashmica) - https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/45919
> dbus_sensors update for IIO support -> https://gerrit.openbmc-project.xyz/c/openbmc/dbus-sensors/+/43410
> PRs submitted downstream for all DPS310 and SI702* gerrit reviews
> virtual_sensors updated for median calculation -> https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-virtual-sensor/+/44597
---
- **DPS310 altitude on dbus**
   - [X] Rainier (Bruce)
   - [X] Everest (Bruce)
 > Additional notes -> https://github.com/ibm-openbmc/dev/issues/2469
---
- ~~**Si7021-A20 humidity on dbus**~~
   - [x] ~~Rainier (hw team - David?)~~
   - [x] ~~Everest (hw team - David?)~~
> ~~Member of zSystems assigned to work this (Timothy)~~
> ~~Seems to only need dts(or cfg) and EM configs? Should BMC developer take ownership?~~
> No fan control design usage, remove from being a dependency

---
- **OCC temps and dvfs on dbus**
   - [x] Rainier (IPS)
   - [x] Everest (IPS)
> All temp sensors -> https://gerrit.openbmc-project.xyz/c/openbmc/openpower-occ-control/+/44256
> VRM temps(VDD) will be requested to be added (Spinler)
> DVFS related "settings" need driver and userspace handling?
> Driver complete for DVFS, need userspace handling to get on dbus
> Hostboot - sensor ids work required
> Spinler's verifying end2end with patches
> Additional changes needed in error handling and efficiently providing temps that Sheldon's working (https://github.com/ibm-openbmc/dev/issues/3323)

---
- **NVMe temps**
   - [x] Rainier (Andrew J)
   - [x] Everest (Andrew J)
> ? -> https://gerrit.openbmc-project.xyz/q/topic:%22nvme-mi-basic%22+(status:open%20OR%20status:merged)
> Possibly same slot power problem as PCIe depends on how wired
> Available end of Aug timeframe
> "Fragile" NVMe temps available in Andrew's downstream openbmc fork (see Slack for details)
> 9/13 - Not merged yet, still improving so not so fragile, etc..
> 9/27 - PRs created to unreviewed? or stable? changes to get NVMe temps ("combined, the four PRs above should give some basic NVMe temperature sensing capability")
>  - https://github.com/ibm-openbmc/dbus-sensors/pull/4
>  - https://github.com/ibm-openbmc/entity-manager/pull/6
>  - https://github.com/ibm-openbmc/openbmc/pull/193
>  - https://github.com/ibm-openbmc/openbmc/pull/194

---
- **VRM temps**
   - [X] Rainier (Shawn)
   - [x] Everest (Shawn)
> Related fan control stories:
> https://github.com/ibm-openbmc/dev/issues/2753
> https://github.com/ibm-openbmc/dev/issues/1698
> Attempting to get from OCC as preferred way for better fan control event configuration during CFT
> VDD temps will be used from the OCC

---
- **TMP275 temps (Nisqually = Rainier, Bellavista = Everest)**
   - [X] Rainier (Spinler)
   - [X] Everest (Bruce)
> Awaiting SRCREV bump of EM to complete integration into build
---
- **PCIe**
   - Industry standard adapters / hot adapters (Brad / Sampa / Justin)
     - [x] Rainier
     - [x] Everest
     > Need config info via PLDM (in-plan: August)
     > PCIe config dbus interface definition exists, not implemented on dbus yet
     > Need to know slot power state (Brad)
     > PHYP not ready until Oct 6
   
   - IBM adapters (Spinler / Santosh)
     - [x] Rainier
     - [x] Everest
     > Need a way to tell what card is plugged and in what slot
     > Need VPD data from adapters
     - TMP435 switch - **in combination with industry standard adapter requirements**
        > Wired to slot power, so need to know slot power state for EM/dbus-sensors (Brad?)
        > EM probe on CCIN to create config instances but then how dbus-sensors access without slot power?
        > EM needs to link(using associations) to PIM as backup plan?...Sounds like this is the path to take due to time constraints. (will include non-upstreamable dbus-sensors).
        > PHYP not ready until Oct 6
---

**Comment by BMC-Bruce** [comment]
Rainier / Everest Si7021-A20 ambient on dbus pending on 2 PRs
entity-manager: Support for DPS310 and SI7020 Rainier #5
and
dbus-sensors: Adds support for DPS310 Sensors #5

**Comment by BMC-Bruce** [comment]
The Altitude Virtual Sensor is handle by the Gerrit Merged Review.
44526: meta-ibm: Adds virtual Altitude sensor
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/44526

**Comment by BMC-Bruce** [comment]
New PRs, old ones closed.

entity-manager
1020 dps310 and SI7020 #6
https://github.ibm.com/openbmc/entity-manager/pull/6

dbus-sensors: Support DPS310 and SI7020 #6
https://github.ibm.com/openbmc/dbus-sensors/pull/6

**Comment by BMC-Bruce** [comment]
To read Ambient Temperatures, Station Pressure, and Altitude

```
busctl introspect --no-pager xyz.openbmc_project.HwmonTempSensor /xyz/openbmc_project/sensors/temperature/Ambient_0_Temp
busctl introspect --no-pager xyz.openbmc_project.IIOSensor /xyz/openbmc_project/sensors/temperature/Ambient_1_Temp
busctl introspect --no-pager xyz.openbmc_project.IIOSensor /xyz/openbmc_project/sensors/temperature/Ambient_2_Temp
busctl introspect --no-pager xyz.openbmc_project.IIOSensor /xyz/openbmc_project/sensors/pressure/Station_Pressure

busctl introspect xyz.openbmc_project.VirtualSensor /xyz/openbmc_project/sensors/temperature/Ambient_Virtual_Temp
busctl introspect xyz.openbmc_project.VirtualSensor /xyz/openbmc_project/sensors/altitude/Altitude

```

**Comment by BMC-Bruce** [comment]
44290: entity-manager: Support for DPS310 and SI7020 Rainier
       https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44290
44670: entity-manager: Support DPS310 and SI7020 Everest
       https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44670
43410: dbus-sensors: Support DPS310 and SI7020
       https://gerrit.openbmc-project.xyz/c/openbmc/dbus-sensors/+/43410

In reality 44290 is a prerequisite for 44670.
And Ed has In reality made 43410 a prerequisite for both 44290 and 44670.

**Comment by BMC-Bruce** [comment]
For TMP275 temps (backplane = Rainier, JungLi card = Everest)

Support the PCIE_x_Temp Sensors for Everest 
https://github.com/ibm-openbmc/entity-manager/commit/92527c5c1cbee6341e3004d63d2b47d1e73ea976
https://github.com/openbmc/entity-manager/commit/9d983212b744bf22ea3aa5b838b2fbd435667269
