### ISSUE TITLE
phosphor-log-manager[297]: Unable to read PEL ID File!

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#3257]
The above message shows up when the PEL daemon can't read /var/lib/phosphor-logging/extensions/pels/pelID to get the next PEL ID value to use.  In that case, it just uses basically a random number for the ID, which is fine, but I can't think of why that read would be failing.

On the most recent system where I saw this, the file was there:
```
/var/lib/phosphor-logging/extensions/pels# hexdump -C pelID 
00000000  00 00 00 00 00 00                                 |......|
```

It would be good to get  to the bottom of it.

**Comment by sumitk56** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/48981
