### ISSUE TITLE
CEC CM:  implement pcie config space info

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#3260]
this story will set the fan floor information in bmc which are sent by Phyp

Phyp will send all the pcie config space data via setFruRecordTable as agreed in https://ibm.ent.box.com/file/831400864793?s=txdspe9503mq86xhdd3m53mkk7ct996w

bmc will have to parse the data and then populate the pcieDevice interface DBus properties in each pcie slot 

additionally fan floor needs to know the power state for each slot. bmc will create effecters for each slot (entity slot and state set 11) which Phyp will set to mark the power state. 
bmc needs to implement a new interface(? or existing) on the slot object  to mark the power state

**Comment by mzipse** [comment]
Work is complete.  Closing.
