### ISSUE TITLE
cec cm: support hot plug

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#3261]
this story will support hot plugs of fans and psu objects in bmc

pldm will create fru record set and entity association PDR only for existing fans and psus (the fan and psu objects are created statically so need to check the "Present" status before creating the fru record). currently records are created for all objects

and will subscribe to the property change signal on all those static objects. based on add or remove operation, pldm will chnage the fru records and entity association records and send PDR repo change event to Phyp

libpldm apis will be created for add/delete entity and fru record set PDR and sending change event which can be used in other cec cm like pcie

**Comment by mzipse** [comment]
Work is complete.  Closing.
