### ISSUE TITLE
PFP::control: Clean up property cache on nameOwnerChanged signals

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#3262]
Create an action that will handle watching for NameOwnerChanged signals from all services in the Manager's property cache.  When the owner is lost, remove all properties from that owner.  This way, code that tries to read from the cache won't get stale values for properties that are no longer on D-Bus.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50875
