### ISSUE TITLE
Resource dump:  Support resource dump initiation from PHYP

### ISSUE THREAD

**Issue by jaypadath** [ibm-openbmc/dev#3267]
Resource dump initiation from PHYP is not working as there is no dbus path to update it. A new new flow needs to be added to handle it.

Ex: Initiate vmi init-dump from phyp resulting in error

--> DumpHandler::newFileAvailable() failure as there is no dbus entry created for this
--> need to see how to handle this and whether
Received Msg
09 01 82 3f 0a 09 00 00 00 00 04 e0 6a 00 00 00 00 00 00
failed to make a d-bus call to DUMP manager to set resource dump SourceDumpId, ERROR=sd_bus_call: xyz.openbmc_project.Common.Error.ResourceNotFound: path or object not found

--> In case we try initiating the resource dump from PHYP, currently it is being treated it as empty string
--> May be something extra needed here?
Sending Msg
02 3f 0a 00
Empty vsp string

com.ibm.Dump.Entry.Resource         interface -         -                                        -
.Password                           property  s         ""                                       emits-change writable
.SourceDumpId                       property  u         67108864                                 emits-change writable
.VSPString                          property  s         ""                                       emits-change writable

 busctl get-property xyz.openbmc_project.Dump.Manager /xyz/openbmc_project/dump/resource/entry/1 xyz.openbmc_project.Common.Progress Status
s "xyz.openbmc_project.Common.Progress.OperationStatus.Failed

**Comment by rfrandse** [comment]
tracking in jira
