### ISSUE TITLE
PELs:  Guard against hostboot sending down duplicate PEL IDs

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#3268]
There was a case in the lab  where hostboot sent down a PEL with an ID that we already had in our repository.  That caused a PEL to get orphaned in the filesystem without a corresponding valid openbmc event log ID (I think), so that a Redfish clearlog didn't delete the PEL.

So I think we can do the following:
- Reproduce this in simics by grabbing a hostboot PEL file and feeding it back to the BMC again
- Check what actually gets into the _pelAttributes map.  I think the emplace() into it probably returns false, meaning it doesn't actually emplace anything
- Assuming that is the case, change the code to start checking for that emplace to fail, and if it does, print to the journal a message about a duplicate PEL ID, along with its newly requested openbmc ID and the OpenBMC ID of the existing PEL.
- Move the PEL to the archive
- Make sure an OpenBMC event log without a PEL doesn't break anything.

**Comment by sumitk56** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/45500
