### ISSUE TITLE
BIOS: support readonly attributes

### ISSUE THREAD

**Issue by sampmisr** [ibm-openbmc/dev#3281]
This story will make change to support "readonly" BIOS attributes. The attributes can be set by Host but not other out of band entities.
Make corresponding change in pldmtool also

**Comment by lxwinspur** [comment]
PLDM: review by: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/45642

**Comment by lxwinspur** [comment]
BiosConfig-Manager: review by: https://gerrit.openbmc-project.xyz/c/openbmc/bios-settings-mgr/+/45665
