### ISSUE TITLE
COD: bmcweb changes to implement License schema

### ISSUE THREAD

**Issue by sunharis** [ibm-openbmc/dev#3295]
Implement new schema 
Add support to upload licenses
List the licenses

**Comment by raviteja-b** [comment]
in code review
https://github.ibm.com/openbmc/bmcweb/pull/202

**Comment by sunharis** [comment]
https://github.ibm.com/openbmc/openbmc/pull/1432
code review : https://github.ibm.com/openbmc/bmcweb/pull/206
merged: https://github.ibm.com/openbmc/bmcweb/pull/209

**Comment by sunharis** [comment]
Downstream-only change. Merged to 1020. Upstreaming is not yet planned
