### ISSUE TITLE
Log service : Implement enable/disable functionality for dumps

### ISSUE THREAD

**Issue by sunharis** [ibm-openbmc/dev#3296]
This story is to implement the disable or enable facility for redfish endpoints 
1. Systems/system/LogServices/Dump
2. Managers/bmc/LogServices/Dump

LogService enable/disable property is available in redfish schema.
Refer : https://redfish.dmtf.org/schemas/v1/LogService.v1_2_0.json , property "ServiceEnabled"

**Comment by asmithakarun** [comment]
Upstream commit for this: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/45809

**Comment by sunharis** [comment]
Delivered downstream
