### ISSUE TITLE
GUI : FED : Plan to remove Redfish hardcoded hypermedia paths

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3298]
## Overview
When calling the the Redfish API, we have hardcoded paths in the API calls. For example, `/redfish/v1/Chassis`. What we want to do is use the path to get the associated hypermedia link (__odata_ ) value and use the path provided by the API.

### Example schema
```
{
    "@odata.id": "/redfish/v1",
    "@odata.type": "#ServiceRoot.v1_5_0.ServiceRoot",
    "AccountService": {
        "@odata.id": "/redfish/v1/AccountService"
    },
    "CertificateService": {
        "@odata.id": "/redfish/v1/CertificateService"
    },
    "Chassis": {
        "@odata.id": "/redfish/v1/Chassis"
    },
    "EventService": {
        "@odata.id": "/redfish/v1/EventService"
    },
    "Id": "RootService",
    "JsonSchemas": {
        "@odata.id": "/redfish/v1/JsonSchemas"
    },
    "Links": {
        "Sessions": {
            "@odata.id": "/redfish/v1/SessionService/Sessions"
        }
    },
    "Managers": {
        "@odata.id": "/redfish/v1/Managers"
    },
    "Name": "Root Service",
    "RedfishVersion": "1.9.0",
    "Registries": {
        "@odata.id": "/redfish/v1/Registries"
    },
    "SessionService": {
        "@odata.id": "/redfish/v1/SessionService"
    },
    "Systems": {
        "@odata.id": "/redfish/v1/Systems"
    },
    "Tasks": {
        "@odata.id": "/redfish/v1/TaskService"
    },
    "TelemetryService": {
        "@odata.id": "/redfish/v1/TelemetryService"
    },
    "UUID": "xxxxxxxx-xxxxxxxx-xxxxxxx",
    "UpdateService": {
        "@odata.id": "/redfish/v1/UpdateService"
    }
}
```

## UX Flow / Interaction Requirements
- [ ] Create a list of all the API calls using the hard coded paths
- [ ] Create a store to save the references
- [ ] Create stories to make changes

## Final Invision Mockup
N/A

## cURL Commands
- Use the Postman collection shared with the UI squad in slack

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
@Srisuk @sandeepasingh116 @DBurkh @dixsie Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/ibm-openbmcdev-5d02be96c409c87afece6a11/issues/ibm-openbmc/dev/3298?planning-poker)

**Comment by DBurkh** [comment]
Reminder: look into "discovering" paths further down the tree.

**Comment by dixsie** [comment]
During the design workgroup 9/15/21, Intel shared they are working on a proposal for this fix. They demo'd their proposal and will share a WIP commit on Gerrit for further discussion.

**Comment by sandeepasingh116** [comment]
https://gerrit.openbmc.org/c/openbmc/webui-vue/+/47141
