### ISSUE TITLE
Tighten web server xss protection

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#33]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Friday May 18, 2018 at 19:55 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3195_

----

This was split off #3186 to isolate the web server XSS issue from the ssh issues.
SW429156
This is in response to a security scan:
 - Update the web server to protect from XSS vulnerability.

**Comment by rfrandse** [comment]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Friday May 25, 2018 at 15:46 GMT_

----

This appears to be a rediscovery of #1229.

**Comment by rfrandse** [comment]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Wednesday Aug 01, 2018 at 21:58 GMT_

----

See also #3328.

**Comment by rfrandse** [comment]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Wednesday Aug 01, 2018 at 22:02 GMT_

----

The phosphor-rest-server had its XSS vulnerability addressed by https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-rest-server/+/8483/ by @causten by adding HTTP headers:
```
            'X-Frame-Options', 'deny'
            'X-Content-Type-Options', 'nosniff'
            'X-XSS-Protection', '1; mode=block'
            'Content-Security-Policy', "default-src 'self'"
            'Strict-Transport-Security', 'max-age=31536000; includeSubDomains; preload'
```

Can we fix the remaining problems by changing nginx, phosphor-webui, or both?

The configuration changes for nginx would be something like:
```
	add_header "X-XSS-Protection" "1; mode=block";
	add_header "Content-Security-Policy" "default-src 'self'";
	etc.
```

The changes to phosphor-webui (NodeJS?) would be to add HTTP headers as above.

For a little light reading:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

**Comment by rfrandse** [comment]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Wednesday Aug 01, 2018 at 22:03 GMT_

----

The phosphor-rest-server had its XSS vulnerability addressed by https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-rest-server/+/8483/ by adding HTTP headers:
```
            'X-Frame-Options', 'deny'
            'X-Content-Type-Options', 'nosniff'
            'X-XSS-Protection', '1; mode=block'
            'Content-Security-Policy', "default-src 'self'"
            'Strict-Transport-Security', 'max-age=31536000; includeSubDomains; preload'
```

Can we fix the remaining problems by changing nginx, phosphor-webui, or both?

The configuration changes for nginx would be something like:
```
	add_header "X-XSS-Protection" "1; mode=block";
	add_header "Content-Security-Policy" "default-src 'self'";
	etc.
```

The changes to phosphor-webui (NodeJS?) would be to add HTTP headers as above.

For a little light reading:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

**Comment by rfrandse** [comment]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Wednesday Aug 01, 2018 at 22:03 GMT_

----

See also closed issue #2423.

**Comment by rfrandse** [comment]
<a href="https://github.com/joseph-reynolds"><img src="https://avatars3.githubusercontent.com/u/31445374?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joseph-reynolds](https://github.com/joseph-reynolds)**
_Monday Aug 06, 2018 at 17:20 GMT_

----

There are some other security-related HTTP response headers to consider:
- Content-Security-Policy           
- Referrer-Policy                   
- X-Content-Type-Options            
- X-Frame-Options                   
- X-Permitted-Cross-Domain-Policies 
- X-XSS-Protection

See also https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers

**Comment by joseph-reynolds** [comment]
I experimented live on a system by adding http headers.  The headers are:
```
    add_header X-Frame-Options sameorigin;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options nosniff;
    add_header Content-Security-Policy "frame-ancestors 'self'";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
```
The headers are consistent with recommendations and with previous changes to phosphor-rest-server.
These were added to the /etc/nginx/nginx.conf file in three places:
```
  http { server { listen 80 ...redirect to https... } }
  http { server { listen 433 ...https... } }  -- only the Strict-Transport-Security header
  http { server { listen 433 { location / ...web app... } } }
```
Tested via commands like:
```
  curl -D headers -c cjar -b cjar -k -H "Content-Type: application/json" -X GET https://${bmc}/
  cat headers
  curl -D headers -c cjar -b cjar -k -H "Content-Type: application/json" -X GET https://${bmc}/xyz/openbmc_project/software
   etc
```
Also tested via firefox using http and https.
The http headers appear correct, do not interfere with the function, and should pass the scanner tests.

**Comment by mzipse** [comment]
Please ignor; running a test.

**Comment by joseph-reynolds** [comment]
This was merged here:
  https://gerrit.openbmc-project.xyz/12247
Support for WebSockets was added and merged here:
  https://gerrit.openbmc-project.xyz/14268
Support for KVM (the "data:" scheme) was added and is pending here:
  https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-ibm/+/14704/

**Comment by joseph-reynolds** [comment]
Resolved by https://gerrit.openbmc-project.xyz/12247
