### ISSUE TITLE
GUI : FED : Add ability to view Resource and System dumps

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3302]
## Overview
This story will be the integration of these two API responses. 
- Resource and Hostboot dumps: `redfish/v1/Systems/system/LogServices/Dump/Entries`
- BMC Dumps: `/redfish/v1/Managers/bmc/LogServices/Dump/Entries`

Some of this work has already been completed in #3005, but this story will only deliver the integration of both Dump list services.

### BMC Log Services Dump Entries (BMC)
- [x] Use the hypermedia link to get the path the `Managers` response, `/redfish/v1/Managers`
- [x] Hard code the `bmc` member, `/redfish/v1/Managers/bmc`
- [x] Use the hypermedia link to get the `LogServices` response,  `/redfish/v1/Managers/bmc/LogServices`
- [x] Hard code the `Dump` member, `/redfish/v1/Managers/bmc/LogServices/Dump`
- [x] Use the hypermedia link to get the `Entries` response, `/redfish/v1/Managers/bmc/LogServices/Dump/Entries`

### System Log Services Dump entries (Resource, Hostboot)
- [x] Use the hypermedia link to get the path the `Systems` response, `/redfish/v1/Systems`
- [x] Hard code the `system` member, `/redfish/v1/Systems/system`
- [x] Use the hypermedia link to get the `LogServices` response,  `/redfish/v1/Systems/system/LogServices`
- [x] Hard code the `Dump` member, `/redfish/v1/Systems/system/LogServices/Dump`
- [x] Use the hypermedia link to get the `Entries` response, `/redfish/v1/Systems/system/LogServices/Dump/Entries`

### Merge results and test table actions
- [ ] Merge the results of both Entries arrays
- [ ] Show the results on the Dumps list page
- [ ] Add/Test the ability for the user to delete the dumps individually
- [ ] Add/Test the ability for the user to delete the dumps as a batch action
- [ ] Add/Test the ability for the user to download the dumps individually

## Final Invision Mockup
N/A

## cURL Commands
Use OpenBMC collection in Postman

## Notes
- This work is partially done in #3005, which has been pushed to a later milestone.

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/44708

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/45985

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/46120

**Comment by dixsie** [comment]
FYI @Srisuk https://github.com/ibm-openbmc/pldm/pull/19 Resource dump fixes merged

>     1. Allow the empty string as resource dump selector
>     2. Avoid setting the resource dump dump explicitly as notify method
>     takes care of the same. This code was causing error when the
>     resource dump is getting initiated from host

**Comment by mzipse** [comment]
Work is complete.  Closing.
