### ISSUE TITLE
GUI : Memory Resource Mgmt - Memory - System Memory Page Setup

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3304]
## SMEs
**BMC**: @sampmisr , @manojkiraneda 
**PHYP**: Ken Vossen, Stuart Jacobs, Tom Sand 
**RAS**: ~~Justin Thaler~~ George Ahrens
**Host Boot**: Nick Bofferding
**PowerVM**: David Stanton, Adam Stallman
**AIX**: Brian Veale

## Summary
There are two other features that are part of the page

## Background
- System Memory Page Setup: A user can improve system performance by setting up the system with larger memory pages (16GB page sizes). It can be changed at run time, but change will get into affect after IPL.

#### End users
- Paul (Product Engineer)
- Tricia (Power Sys Admin)
- Noah (Junior Sys Admin w/o HMC) - most, but not all

### References/Resources
- [eBMC Feature Item: 4.12.1, 4.12.2, 4.12.3, 4.12.4, 4.12.5](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)
- [feature discovery folder ](https://ibm.ent.box.com/notes/678801706046)
- user research notes*: 
- user research synthesis: https://ibm.ent.box.com/notes/694681453260
- `#openbmc-celogin` slack channel
- `#hmc-peloogin` slack channel

### User Story
As an **admin/PE**,
I need to **manually or automatically change the values of my System Memory Page Setup**
in order to **enhance the system performance.**

### Community
Down stream only

### Overview
- [ ] Add Overview

### UX Flow / Interaction Requirements
- [ ] Feature breakdown

### Final Invision Mockup
- https://ibm.invisionapp.com/share/PYO1HKPE25X

### cURL Commands
- [ ] B/E not available yet - need BIOS setting for huge page

### Notes
- [ ] Bios attribute: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/47070

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by sandeepasingh116** [comment]
Resolved by : https://github.ibm.com/openbmc/webui-vue/pull/29

**Comment by mzipse** [comment]
Closing.  Work is complete.
