### ISSUE TITLE
GUI : Security settings - Server-side USB enable/disable

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3305]
## SME
**BMC**: @joseph-reynolds 
**RAS**:
**PHYP**: Chris E

## Overview
The Security settings page allows users to enable and disable various settings for the BMC. This feature is a service login feature only. There is some ambiguity to this story that requires research.

## UX Flow / Interaction Requirements
- [x] add USB code update https://github.com/ibm-openbmc/bmcweb/pull/164
    - [x] need to confirm what the help text should be @gmtills
- [x] Add to the Security settings page
- [x] Only show when the user logged in is a service login user. If not possible, only show with the Service login is enabled

## Final Invision Mockup
https://ibm.invisionapp.com/share/SGO0QDLQ8VD#/screens
![image.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/edcfcdd0-6506-4c5d-a961-0ccc37e6b928)

## cURL Commands
- [ ] Add cURL commands

## Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by dixsie** [comment]
USB code update disable/enable is in the driver as 38.1
UPS disable/enable is not in the driver
 
 Missing info:
 - What are the hep text/descriptions for each?
 
@anoo1 @smccarney

**Comment by anoo1** [comment]
> USB code update disable/enable is in the driver as 38.1 
>     * What are the hep text/descriptions for each?

I would say something like:

USB Firmware Update Policy: Enabled
Enabling the USB Firmware Update Policy will enable the functionality to allow firmware updates through a USB key.
Disabling the USB Firmware Update Policy will disable the functionality to allow firmware updates through a USB key.

**Comment by Nikhil-Ashoka** [comment]
Resolved by: https://github.ibm.com/openbmc/webui-vue/pull/73

**Comment by joseph-reynolds** [comment]
The BMC admin should be allowed to control the USB Firmware Update Policy (aka USB code update).  This is a toggle (enable/disable).  Operator and readonly users should only have read access to this setting.
