### ISSUE TITLE
Implement PLDM message field APIs

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#331]
- Implement an API to "form" a PLDM message, given instance id, type, command code, [completion code] and the message payload.
- Given a PLDM message, implement an API to strip out the instance id, type, command code, [completion code] and the message payload.
- Handle platform specific byte ordering.

Refer design at https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/17592/.

**Comment by rfrandse** [comment]
refresh

**Comment by tomjoseph83** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/18068/

**Comment by rfrandse** [comment]
refresh

**Comment by tomjoseph83** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/18067/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/18067 merged

**Comment by mzipse** [comment]
refresh
