### ISSUE TITLE
GUI : FED : Remove gerrit commit links from code

### ISSUE THREAD

**Issue by sandeepasingh116** [ibm-openbmc/dev#3312]
### UX Flow / Interaction Requirements
- [ ] There are some gerrit commit links mentioned in the code. Once the respective commit gets merged the link should be removed from the code.

### Screenshot
![2021-08-19_19-07-50.png](https://images.zenhubusercontent.com/6011940df9396067cb32713d/6656d208-9662-4aee-ac79-f6de129ef881)

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by rfrandse** [comment]
tracking in jira
