### ISSUE TITLE
GUI : Hardware Status - Inventory and LEDs - Missing Location codes

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3317]
## Expected Behavior
The user should be able to view a location code on the inventory item.

## Actual Behavior
The location number is not being displayed on any of the inventory items. 

## Steps to Reproduce the Problem

  1. Go to Hardware status / Inventory and LEDs page
 
#### As is
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/89703255-3144-403e-8961-044b12f4ae0c)

#### To Be
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/0722ba5a-8944-4b2e-a6c4-410f12313f07)

## Redifsh API response
The response has changed and needs to use the following on all tables. The As Is and To Be above are only showing two of the tables.
```
  "Location": {
    "PartLocation": {
      "ServiceLabel": "U78DB.ND0.WZS000G"
    }
  },
```

**Comment by sneha787** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/46389
