### ISSUE TITLE
Implement the GetPLDMVersion command

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#332]
Implement the command as per DSP0240.

Refer design at https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/17592/.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Implemented at https://github.com/openbmc/pldm/commit/432e187c11b86659c1b397cebf127e436eec87e9

**Comment by mzipse** [comment]
refresh
