### ISSUE TITLE
GUI : FED : Hidden Logs

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3320]
## SME
**BMC**: @spinler, Todd Rosedahl
**RAS**:
**PHYP**:

### Overview
Hidden logs will be delivered in a downstream log service as part of #2007. This will need to be a separate page that is only accessible to Service login. The page will be part of the Logs page.  

### Follow up needed
- [ ] Determine the name of the logs page - [Slack conversation started on 8/26/21)](https://ibm-systems.slack.com/archives/G01JLPJKVG9/p1630013656001900)
- [ ] Need an image for Service login or for it to be in a driver (Joseph Reynolds to provide image if needed)
- [ ] Need to determine milestone so the work can be proritized
- [ ] Need to test restricting navigation to specific user role types as this is new functionality

### UX Flow / Interaction Requirements
- [ ] Get the Redfish info from the SME
- [ ] Add a route the new page (should model the same patterns as the Event logs table)
- [ ] Add a new log store module
- [ ] Add a new single file component
- [ ] Add the navigation with a conditional to only show when the logged in user has the Service Login role

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [Slack conversation with notes about decisions](https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1630012427011500)

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by mzipse** [comment]
Closing.  Work is complete.
