### ISSUE TITLE
VPD: Required a DBus API to get unexpanded location code

### ISSUE THREAD

**Issue by RameshIyyar** [ibm-openbmc/dev#3322]
- Currently, we don't have D-Bus API to get the unexpanded location code from the expanded location code.
- The PHAL application will use a device tree that contains hardware details with unexpanded location code (only for FRU) and BMC inventory maintaining expanded location code which is pulled from hardware VPD so when we need to get FRU hardware details from the PHAL device tree by using BMC inventory details, we need to use unexpanded location code but, we don't have a way to get that so this issue can be used to track that requirement. 

FYR:
```
busctl introspect com.ibm.VPD.Manager /com/ibm/VPD/Manager
NAME                                TYPE      SIGNATURE  RESULT/VALUE  FLAGS
com.ibm.VPD.Manager                 interface -          -             -
.GetExpandedLocationCode            method    sq         s             -
.GetFRUsByExpandedLocationCode      method    s          ao            -
.GetFRUsByUnexpandedLocationCode    method    sq         ao            -
.PerformVPDRecollection             method    -          -             -
.WriteKeyword                       method    ossay      -             -
```

**Comment by rfrandse** [comment]
tracking in jira
