### ISSUE TITLE
OCC error handling

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#3323]
The openpower-occ-control code that is responsible for polling the OCC and putting the sensors on D-bus doesn't have the error handling implemented yet.

We had a meeting on it, and here are the notes:

Status::readOCCState() will be the first OCC files access done after the poll timer expires, and will send the actual poll command to the OCC.  As such, if the poll failed, the read will fail.  So:
-  The read itself needs an error check (could throw an exception, or I think check for file.fail()/file.good().
- if it fails, would be good to wait at least 1 second and try again, this would force another hardware access.
- If that still fails:
  - Set all sensors to Nan and nonFunc, and don't bother trying to read them
  - and maybe try again to get occ_error to trigger? (see below)

occ_error is already being watched and gets set by the driver after 3 failed polls, that already drives the OCC reset/OCC active = false

Reading the _label/_fault/_fru_type files shouldn't ever fail.  So if it does, do something drastic like throw an exception to crash the daemon so we can see why it happened.

Reading the _input file:
- If it gets an EAGAIN errno, set the sensor to NaN
- otherwise if it fails with another ernno?  set to nonFunctional?

**Comment by baileysh** [comment]
Merged
