### ISSUE TITLE
Implement GetPLDMTypes and GetPLDMCommands

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#333]
Implement the commands as per DSP0240.

Refer design at https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/17592/.

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/18017/.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/18017 merged

**Comment by mzipse** [comment]
refresh
