### ISSUE TITLE
PFP::control - fanctl tool to support controlling PWM and RPM fans simultaneously

### ISSUE THREAD

**Issue by mikecgithub** [ibm-openbmc/dev#3337]
Currently fanctl (ibm1870) assumes a homogeneous group of fan tachs that report either RPM or PWM. This work unit is to track the need for handling a system with both types of fans.

**Comment by derekhoward55** [comment]
I believe this is done and can be closed.  Please re-open if incorrect.

**Comment by spinler** [comment]
Not sure we'll ever have a need to support this, so closing.  Can revisit if the need arises.
