### ISSUE TITLE
regulators: IPMI support

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#3338]
IPMI is a system management interface, similar to Redfish.

Determine if any regulator work is required to support IPMI.

The two types of regulator information that might be reported via IPMI:
* Inventory information such as presence/status/VPD.  This data comes from the inventory manager application and the applications that handle MRW and VPD.  I don't think the phosphor-regulators application would be involved.
* Sensor information.  Todd Rosedahl thought that output voltage would be reported over IPMI.  The phosphor-regulators application publishes all sensors to D-Bus using the standard interfaces.  I'm not sure if any additional regulator work would be required for IPMI.

IPMI has a limit of 255 total sensors.  Given that there are over 300 regulator sensors produced on Everest, all the regulator sensors could definitely not be reported over IPMI.  Todd is aware of this and was only asking for output voltage.

Tom Joseph was involved in IPMI support for Witherspoon.  He said regulator data was not published over IPMI on that system.

Matt Spinler said that a YAML file was used on Witherspoon to map information into IPMI.  He thought that would likely be needed for Everest/Rainier as well.  I believe that work has not been done yet.

Brad Bishop was interested in moving to dynamic IPMI SDRs, which I believe would eliminate the need for the YAML file.  However, that would require significant work and no one is currently assigned to do it.

**Comment by derekhoward55** [comment]
Per discussion with Maury&Todd this is not a GA requirement.  If customers do want to use IPMI instead of Redfish for this, we can entertain putting it in post-GA.

**Comment by derekhoward55** [comment]
No known usage for this; closing.
