### ISSUE TITLE
Pull allow list out (Downstream) have compile option (upstream)

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3339]
Pull this commit out: 
https://github.com/ibm-openbmc/bmcweb/commit/349a2ac3921e17ff0e2bce47ba6698112d586e67

Pull code out, rerun update_script. 
This is downstream only. 

For the upstream part, need a compile option or something

**Comment by patelabhishek9893** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/111/files

**Comment by mzipse** [comment]
Work is complete.  Closing.
