### ISSUE TITLE
Design PLDM provider library registration API

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#334]
Refer design at https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/17592/.

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/18458/.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/18458 merged

**Comment by mzipse** [comment]
refresh
