### ISSUE TITLE
Add psu fault SRCs and callouts to message registry

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#3345]
Additional power supply faults will be detected with issue https://github.com/ibm-openbmc/dev/issues/918.  For this story, set up the following fault information in the message registry (https://github.com/openbmc/phosphor-logging/blob/master/extensions/openpower-pels/registry/message_registry.json):

PS_kill fault (from register MFR_SPECIFIC[4]): SRC 11002500 and callouts "power_overcurrent” iso procedure (BMC0005) for rainier, “ldswtch” symbolic for everest.

Iout_OC fault (STATUS_WORD[4]): SRC 11001B01 and callout “power_overcurrent” iso procedure (BMC0005).

PS fan fault (STATUS_WORD[10]): SRC 110015FF and fru callout Ex using CALLOUT_INVENTORY_PATH.

Need to add the iso procedures to extensions/openpower-pels/pel_values.cpp and extensions/openpower-pels/registry/schema/schema.json as well.

**Comment by bjwyman** [comment]
IOUT_OC/over-current/1B01:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/48944
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/48945

**Comment by bjwyman** [comment]
PSU fan fault: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/48962

**Comment by bjwyman** [comment]
PEL: Add power supply PS_Kill fault: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/49234

The fan fault one was the last to merge. This can no be considered complete.
