### ISSUE TITLE
ServiceProviderNotify: Turn the d-bus property into an enum with 3 values - NotApplicable, Notify, NotNotify

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3346]
Feedback from https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46886/7/redfish-core/lib/log_services.hpp#1411

FYI @spinler @vflobo @patelabhishek9893

**Comment by gtmills** [comment]
https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/47683 and https://gerrit.openbmc.org/c/openbmc/phosphor-logging/+/58815 merged. Just need the bmcweb commit.

**Comment by rfrandse** [comment]
tracking in jira
