### ISSUE TITLE
COD : Implement the DMTF License registry

### ISSUE THREAD

**Issue by sunharis** [ibm-openbmc/dev#3347]
License upload can fail for multiple reasons . There should be a way to differentiate the internal error from the license-upload input data error caused by the user. DMTF is coming up with a license error registry. This story is to implement the same at bmcweb

**Comment by raviteja-b** [comment]
@gtmills I don't see license registry/error schemas in recent release
any idea ?

**Comment by gtmills** [comment]
I see it here: https://redfish.dmtf.org/registries/License.1.0.0.json
Need to create a new registry for it

**Comment by sunharis** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/212  implements this story

**Comment by sunharis** [comment]
Downstream-only change. Merged to 1020. Upstreaming is not yet planned
