### ISSUE TITLE
GUI : FED : Update Capacity on Demand endpoint

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3350]
## SME
**BMC**: @raviteja-b 
**RAS**:
**PHYP**:

### Overview

Endpoint needs to be updated when the following stories are merged: 
- https://github.ibm.com/openbmc/bmcweb/pull/206
- https://github.com/ibm-openbmc/dev/issues/3348

### Acceptance Criteria
- [ ] Feature breakdown

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by rfrandse** [comment]
tracking in jira
