### ISSUE TITLE
GUI : FED : Event Logs Additional Data Base64 conversion

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3352]
### Overview
Feedback from internal users has indicated that the additional data download on the event log page does not meet their needs. 

### Quotes
> much rather have a HEX string than a Base64 format

> Looks like a bunch of redfish (?) tagging around the actual data

> Converting the Base64 to Hex, which appears to actually parse... just not a format I have seen before.

### Acceptance Criteria
- [ ] Convert the Base64 file to HEX
- [ ] Validate format with users in the `#ebmc-gui-internal-users` Slack channel (Point of contact: Lael D)

### cURL Commands and Redfish Response
N/A

### Notes
- [Slack thread](https://ibm-systems-power.slack.com/archives/D02DSQFSDCY/p1633024065002300?thread_ts=1631629393.001000&cid=D02DSQFSDCY)
- Solutions to explore with users
    - https://stackoverflow.com/a/39460727/2432889
    - https://gist.github.com/GeorgioWan/16a7ad2a255e8d5c7ed1aca3ab4aacec

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by rfrandse** [comment]
tracking in jira
