### ISSUE TITLE
Extended Cache Option (ECO) Support

### ISSUE THREAD

**Issue by mzipse** [ibm-openbmc/dev#3358]
This Epic encompasses all the work associated with ECO.

**Comment by rfrandse** [comment]
refresh

**Comment by nmuruli** [comment]
ECO has HDAT work as well, which will be done as part of https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CEC%20HW%20Enablement#action=com.ibm.team.workitem.viewWorkItem&id=247294 
RTC Story 289133 : HDAT: Rainier ECO mode support.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
ECO has been delivered quite some time ago.  Closing.
