### ISSUE TITLE
Protocol Validator: REQ_POST_CREATE_TO_MEMBERS_PROP

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3364]
See https://github.com/openbmc/bmcweb/issues/192

![members](https://user-images.githubusercontent.com/5455127/137345266-53abea37-309c-4087-9efb-4f5ede9c8aed.JPG)

REQ_POST_CREATE_TO_MEMBERS_PROP: "Submitting a POST request to a resource collection is equivalent to submitting the same request to the Members property of that resource collection. Services that support the addition of Members to a resource collection shall support both forms."

Need this for all collections

**Comment by rfrandse** [comment]
tracking in jira
