### ISSUE TITLE
Redfish: Need ProcessorSummary Model on the ComputerSystem

### ISSUE THREAD

**Issue by aahmed-2** [ibm-openbmc/dev#3366]
curl -k -H "X-Auth-Token: $tok" https://$bmc/redfish/v1/Systems/system

...
  "ProcessorSummary": {
    "CoreCount": 24,
    "Count": 2,
    "Model": "test_name", <------ want something like this
    "Status": {
      "Health": "OK",
      "HealthRollup": "OK",
      "State": "Disabled"
    }
  },
...

**Comment by aahmed-2** [comment]
Upstream commit: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/46210

**Comment by aahmed-2** [comment]
Downstream PR: https://github.com/ibm-openbmc/bmcweb/pull/145

**Comment by mzipse** [comment]
refresh

**Comment by mzipse** [comment]
refresh again

**Comment by mzipse** [comment]
Work is complete.  Closing.
