### ISSUE TITLE
GUI: FED: Refresh system info in header

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3378]
## Expected Behavior
When a user clicks the refresh button in the header it is expected that the asset tag, model # and serial # will be refreshed.

## Actual Behavior
The refresh button only refreshes the page container area and not the app header or app nav. https://github.com/openbmc/webui-vue/blob/master/src/layouts/AppLayout.vue#L45

![Screen Shot 2021-10-18 at 11.45.51 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/9a8520d1-3635-40e0-9134-8baa11d9c4ce)

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/48768

**Comment by mzipse** [comment]
Work is complete.  Closing.
