### ISSUE TITLE
GUI: FED: Assembly table expand row button does not expand row

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3379]
## Expected Behavior
When a user clicks the expand row button on the Assembly table, the table row should expand.

## Actual Behavior
Clicking the expand row button does not trigger expand.

## Specifications
  - Browser: Firefox

![Screen Shot 2021-10-19 at 11.54.06 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/92ee4602-f6ae-48c1-bf69-ae5c8fe14615)

**Comment by kennyneedsmilky** [comment]
Closed. Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/46645

**Comment by kennyneedsmilky** [comment]
Resolved by https://github.ibm.com/openbmc/webui-vue/pull/23

**Comment by mzipse** [comment]
Work is complete.  Closing.
