### ISSUE TITLE
P10BMC - Add Si7021 Humidity Readings on to D-Bus

### ISSUE THREAD

**Issue by BMC-Bruce** [ibm-openbmc/dev#3381]
We already have the Si7020 type device added to both Rainier's Blyth and Everest's Storm King Op-panels with GHE that we are reading its Ambient Temperature and putting the reading _appropriately_ on D-Bus.

The Si7020 type device is an **IIO raw device** as compared to the DPS310 provides a directly usable reading that is compatible with **hwmon** sensor scaling's.  **IIO raw devices** that require reading of `/sys/bus/iio/devices/iio:device0/in_humidityrelative_raw` and optionally if they exist `/sys/bus/iio/devices/iio:device0/in_humidityrelative_offset` and `/sys/bus/iio/devices/iio:device0/in_humidityrelative_scale` , offset is to default to 0 and scale to 1, see lore [https://lore.kernel.org/linux-iio/5c79425f-6e88-36b6-cdfe-4080738d039f@metafoo.de/](https://lore.kernel.org/linux-iio/5c79425f-6e88-36b6-cdfe-4080738d039f@metafoo.de/l) and see [https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-bus-iio](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-bus-iio) for IIO kernel documentation.

The **hwmon** units for each sensor type are describe in this kernel documentation [https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface](https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface); for humidity the **hwmon** units: milli-percent (per cent mille, pcm).  So when we compute the reading `value = (raw_value + offset) * scale`  we are computing humidity as milli-percent.  Now for OpenBMC D-Bus sensors we use the International System of Units (i.e. SI) without prefixes, meaning we need % (i.e. per cent), so there is a second scaling of 0.001 to be applied to achieve % (i.e. per cent) from milli-percent (per cent mille, pcm) before putting the reading on D-Bus.

This story extends the `dbus-sensors` to do the analogous work for Humidity to that already exists for Ambient Temperature of the Si7020 type device.  The `entity-manager` build and json files are already done as they were needed for Si7020 type device to read the Ambient Temperature.

Related Stories:

- [Rainier - Add Si7021 ambient & humidity sensor configurations #2653](https://github.com/ibm-penbmc/dev/issues/2653)
- [Rainier - Add DPS310 ambient & altitude sensor configurations #2652](https://github.com/ibm-openbmc/dev/issues/2652)
- [How to handle Altitude in userspace #649](https://github.com/ibm-openbmc/dev/issues/649)
- [Rainier / Everest Fan Control Sensor Dependencies #3255](https://github.com/ibm-openbmc/dev/issues/3255)
- [Rainier Temp Monitoring #573](https://github.com/ibm-openbmc/dev/issues/573)
- [Everest Temp Monitoring #2467](https://github.com/ibm-openbmc/dev/issues/2467)
- [Swift: Add support for DPS310 altitude #472](https://github.com/ibm-openbmc/dev/issues/472)

**Comment by lxwinspur** [comment]
Hi @BMC-Bruce 
I checked `entity-manager` and `dbus-sensors`, and I saw that you have pushed some patches related to DPS310 and SI7020

https://gerrit.openbmc-project.xyz/c/openbmc/dbus-sensors/+/45406
https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44290
https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44670

So, my question is:
What should I do with this issue? Because I think the logic of `SI7021` and `SI7020` are the same right?
Maybe I missed something, please lemme know if I am wrong, thanks :)

**Comment by BMC-Bruce** [comment]
On 12/29/2021 23:40, George Liu wrote:
> Hi @BMC-Bruce
> I checked `entity-manager` and `dbus-sensors`, and I saw that you have pushed some patches related to DPS310 and SI7020
> 
> https://gerrit.openbmc-project.xyz/c/openbmc/dbus-sensors/+/45406
> https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44290
> https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44670
> 
> So, my question is:
> What should I do with this issue? Because I think the logic of `SI7021` and `SI7020` are the same right?
> Maybe I missed something, please lemme know if I am wrong, thanks :)
> 
Yes George, the Si7021 is a Si7020 type sensor.
And on Dec. 10, 2021 Reed has merged them with
https://github.com/ibm-openbmc/dbus-sensors/commits/1020
and with
https://github.com/ibm-openbmc/entity-manager/commits/1020

-- 
Bruce

**Comment by lxwinspur** [comment]
> 

Yeah, I see.
So, I think we can close this issue right?

**Comment by spinler** [comment]
These are all merged now.
