### ISSUE TITLE
GUI: FED: Bug: Power restore radio buttons not modeled correctly

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3383]
## Expected Behavior
When a user selects a radio button and saves, the selected setting should be patched.

## Actual Behavior
When a user clicks through the radio buttons and then submits the form, the setting is not saved. Radio buttons not modeled correctly.

## Steps to Reproduce the Problem

  1. Click through each radio button twice ( always on, always off, last state, always on, always off, last state).
  1. Try to update the setting by selecting a radio button and clicking submit.
  1. The selected option is not correctly modeled. See screenshot below, Last State was selected but did not log a value in console. When user clicks save, a different value other than the selected one is patched.

![Screen Shot 2021-10-21 at 8.20.59 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/0364c981-be80-41db-b828-fa7c535155a0)

## Specifications
  - Browser: Firefox

**Comment by kennyneedsmilky** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/49904
