### ISSUE TITLE
Everest - MAX31785revA config override script

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3384]
Need to create a script to apply a fan monitoring override config after updating Everest's fan monitor config to support the MAX31785revB. This should be similar to what was done to support the revA vs revB on Rainier systems minus the fan hardware changes.

**Comment by derekhoward55** [comment]
Per Matt/Brian will just leave in the workaround for rear-rotor 0 rpm tach readings for all Everests.
