### ISSUE TITLE
Move IBM-Palmetto, IBM-Romulus away from phosphor-webui

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3386]
Ideally webui-vue fits/work. 

https://github.com/openbmc/openbmc/search?q=phosphor-webui&type=

See discussion here: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1636046634439800

This would be upstream work

**Comment by patelabhishek9893** [comment]
commit https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/49259

**Comment by gtmills** [comment]
MERGED. Close.
