### ISSUE TITLE
Have a way to enable error traces without enabling debug traces for bmcweb 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3387]
Currently  --buildtype=debug \ enabled debug and error 
Might be some other changes in 
https://github.com/ibm-openbmc/bmcweb/pull/138 we should make as a separate commit

**Comment by rfrandse** [comment]
tracking in jira

**Comment by baemyung** [comment]
It is being worked on upstream -  https://gerrit.openbmc.org/c/openbmc/bmcweb/+/60212
