### ISSUE TITLE
Consume DMTF property "GeneratedBy" for the dump entries

### ISSUE THREAD

**Issue by sunharis** [ibm-openbmc/dev#3390]
This is a story to work on moving the OEM "GeneratedBy" property to the DMTF standard property - after we get the standard published.
Originated from https://github.com/ibm-openbmc/bmcweb/pull/136

**Comment by sunharis** [comment]
Need to implement the below properties https://redfish.dmtf.org/schemas/v1/LogEntry.v1_11_0.json

                "Originator": {
                    "description": "The source of the log entry.",
                    "longDescription": "This property shall contain the source of the log entry.",
                    "readonly": true,
                    "type": "string",
                    "versionAdded": "v1_11_0"
                },
                "OriginatorType": {
                    "$ref": "#/definitions/OriginatorTypes",
                    "description": "The type of originator data.",
                    "longDescription": "This property shall contain the type of originator data.",
                    "readonly": true,
                    "versionAdded": "v1_11_0"
                },

**Comment by sunharis** [comment]
https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/47057
https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/54955
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/48337

**Comment by sunharis** [comment]
Migrate-Yes

**Comment by rfrandse** [comment]
tracking in jira
