### ISSUE TITLE
GUI: FED: Bug: Remove immediate shutdown option on server power ops

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3392]
At the SoS overflow today it was decided that we should remove the “immediate” reboot option from the UI for IBM customers downstream. It was discussed at the host interlock call on 8/12 that immediate reboot should not be allowed.

https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1634568667010800
![image.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/58da54bd-11f8-4b3e-b478-2cc4e667f921)

**Comment by Srisuk** [comment]
Resolved by https://github.ibm.com/openbmc/webui-vue/pull/28
