### ISSUE TITLE
GUI: FED: Bug: Location code not displaying correctly on Fans and Power table

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3394]
## Expected Behavior
Display correct location code for fans and power on hardware status page (need to check both downstream and upstream changes to be sure both are displaying correctly. Downstream uses thermal and power subsystems)

## Actual Behavior
![Screen Shot 2021-11-15 at 9.14.24 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/c6b586e9-d34c-492a-b17f-cddc5dedb1f1)

Best quest bug: https://9.10.8.209/projects/bestquest/?defect=SW537530

**Comment by Srisuk** [comment]
For Powersupply: resoled by https://github.ibm.com/openbmc/webui-vue/pull/35

**Comment by mzipse** [comment]
Work is complete.  Closing.
