### ISSUE TITLE
GUI: FED: Bug: Add assembly table component name to table

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3395]
- [ ] Replace ID number with name property, instead of displaying `1,2,3,etc` display the `name` property of the component in first table column.

## Actual Behavior
![Screen Shot 2021-11-15 at 9.19.04 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/402bf724-63da-4d84-bd1e-1750eea57f8b)## Expected Behavior

**Comment by kennyneedsmilky** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/49800

**Comment by mzipse** [comment]
Work is complete.  Closing.
