### ISSUE TITLE
GUI: FED: Bug: Processors table

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3396]
- [x] Part number is not modeled correctly, see screenshot.
- [ ] Expanded row details content is not aligned properly

![Screen Shot 2021-11-15 at 9.28.56 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/73b9116a-e1d2-4b2d-8b28-138dabf41bb0)

Note: If backend provides a value with empty spaces that is not a bug on the front end

Bug for issue: https://9.10.8.209/projects/bestquest/?defect=SW537550
- CPU details like Serial number, spare part number and model are not getting displayed correctly displayed in GUI.

## Step to recreate:
1. Go to Inventory page from hardware status menu.

2. Now click on the processor to check its inventory data. (Here we will see that model number is getting displayed in front of serial number. See attached screenshot. Also, no information is shown for spare part number and serial number while this is present in backend.

```
$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC_IP}/redfish/v1/Systems/system/Processors/dcm0-cpu0
{
  "@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu0",
  "@odata.type": "#Processor.v1_12_0.Processor",
  "Id": "dcm0-cpu0",
  "Location": {
    "PartLocation": {
      "ServiceLabel": "U78DA.ND0.WZS0026-P0-C15"
    }
  },
  "LocationIndicatorActive": false,
  "Manufacturer": "",
  "MaxSpeedMHz": 0,
  "Model": "AB42",
  "Name": "PROCESSOR MODULE",
  "PartNumber": "       ",
  "ProcessorId": {
    "EffectiveFamily": ""
  },
  "ProcessorType": "CPU",
  "SerialNumber": "            ",
  "Socket": "",
  "SparePartNumber": "F210110",
  "Status": {
    "Health": "OK",
    "State": "Enabled"
  },
  "SubProcessors": {
    "@odata.id": "/redfish/v1/Systems/system/Processors/dcm0-cpu0/SubProcessors"
  },
  "TotalCores": 8,
  "TotalThreads": 0
}
```

**Comment by dixsie** [comment]
@sandeepasingh116 can you pair with Nikhil on this one and show him our Gerrit processes? Thanks!

**Comment by dixsie** [comment]
Rejected on Bestquest https://w3.rchland.ibm.com/projects/bestquest/?defect=SW537550

> ==== State: Rejected by: us3j1134 on 20 December 2021 12:46:00 ==== 4
> 
> #=#=# 2021-12-20 12:45:59 (CST) #=#=#
> Action = [reject]
> Answer = [Unreproducible]
> 
> Issue not observed in UI. Tested in UI, screenshots of UI and redfish response can be found in comments here https://github.com/ibm-openbmc/dev/issues/3396
> #=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
>

**Comment by sandeepasingh116** [comment]
This is a BE issue,  junk spaces instead of actual values of required keys is causing the broken UI.
Screenshot for reference:
machine used for testing https://rain100bmc.aus.stglabs.ibm.com

<img width="333" alt="1" src="https://user-images.githubusercontent.com/68803917/146817421-7881409e-016f-47ef-8d2c-bc212046d368.PNG">
<img width="504" alt="2" src="https://user-images.githubusercontent.com/68803917/146817428-845a0b06-9d32-45cd-9991-964f7ff86d30.PNG">
<img width="336" alt="3" src="https://user-images.githubusercontent.com/68803917/146817431-b58ac893-4cba-4f50-84bf-e7c386bd91c2.PNG">
ce:
