### ISSUE TITLE
SNMP - Unable to configure SNMP manager with FQDN/Hostname

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3397]
Unable to configure SNMP manager with FQDN/Hostname.

Both GUI interface and Redfish does not allow user to configure SNMP managers with fully qualified domain name or hostname of the system.

Steps:
Run curl command to onfigure snmp manager on BMC.
Give hostname instead of IP address in the destination part.
It throws 500 internal error and does not configure snmp manager

curl -k -H "X-Auth-Token: $bmc_token" -XPOST https://${bmc}/redfish/v1/EventService/Subscriptions   -d '{"Destination": "snmp://snmp.prashanth.com:162", "SubscriptionType": "SNMPTrap", "Protocol":

curl -k -H "X-Auth-Token: $bmc_token" -D post.txt -X POST https://${bmc}/redfish/v1/EventService/Subscriptions   -d '{"Destination": "snmp://snmp.prashanth.com:162", "SubscriptionType": "SNMPTrap", "Protocol": "SNMPv2c"}'
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_1_1.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.8.1.InternalError",
        "MessageSeverity": "Critical",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service."
      }
    ],
    "code": "Base.1.8.1.InternalError",
    "message": "The request failed due to an internal service error.  The service is still operational."
  }
}bash-4.2$ cat post.txt
HTTP/1.1 500 Internal Server Error
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: DENY
Pragma: no-cache
Cache-Control: no-Store,no-Cache
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'none'; img-src 'self' data:; font-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self' wss:; form-action 'none'; frame-ancestors 'none'; plugin-types 'none'; base-uri 'none'
Content-Type: application/json
Date: Mon, 22 Nov 2021 08:01:48 GMT
Content-Length: 598

Currently we are able configure only IP address.
I'm raising the severity as another way of basic SNMP configuration is not working.

Pls refer the following link for different values for configuration:
https://www.ibm.com/docs/en/linux-on-systems?topic=ilops-resetting-your-network-back-dhcp

https://www.ibm.com/docs/en/sim/7.0.1?topic=events-configuring-snmp-objects

@lxwinspur Can your team own? This was reported by an internal test team

@ChicagoDuan FYI. 
We pulled in SNMP here: https://github.com/ibm-openbmc/bmcweb/pull/147

SW539991

**Comment by ChicagoDuan** [comment]
Hi @gtmills , phosphor-snmp uses inet_pton  to check the address, so we cant use hostname.  I think it is the problem:
https://github.com/openbmc/phosphor-snmp/blob/c3600d86bc6a911e11933e5d727f4e5bac8ce411/snmp_conf_manager.cpp#L78

I will try to fix it.

**Comment by ChicagoDuan** [comment]
Hi @gtmills 
This is the commit I pushed: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-snmp/+/49289
I have tested with redfish and busctl, and both are successful. I can also receive snmptrap on the computer with address “snmp.prashanth.com”

**Comment by ChicagoDuan** [comment]
Hi @gtmills , The commit is merged: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-snmp/+/49289

**Comment by gtmills** [comment]
SW539991 is reporting this is still an issue.

**Comment by ChicagoDuan** [comment]
> @ChicagoDuan SW539991 is reporting this is still an issue.

@gtmills I tested it again, no error.
```
chicago@chicago-PC:~/eBMC/qemu$ curl -k -H "X-Auth-Token: $token" -X POST https://${bmc}/redfish/v1/EventService/Subscriptions   -d '{"Destination": "snmp://snmp.prashanth.com:162", "SubscriptionType": "SNMPTrap", "Protocol": "SNMPv2c"}'
{
  "@Message.ExtendedInfo": [
    {
      "@odata.type": "#Message.v1_1_1.Message",
      "Message": "The resource has been created successfully",
      "MessageArgs": [],
      "MessageId": "Base.1.8.1.Created",
      "MessageSeverity": "OK",
      "Resolution": "None"
    }
  ]
}
```
Can you show me your phosphor-snmp and bmcweb commit id ?

**Comment by gtmills** [comment]
I tried on another system and see it work on the first time but fail with an internal error on the 2nd: 
```
curl -k -H "X-Auth-Token: $token" -X POST https://${bmc}/redfish/v1/EventService/Subscriptions   -d '{"Destination": "snmp://snmp.prashanth.com:162", "SubscriptionType": "SNMPTrap", "Protocol": "SNMPv2c"}'
{
  "@Message.ExtendedInfo": [
    {
      "@odata.type": "#Message.v1_1_1.Message",
      "Message": "The resource has been created successfully",
      "MessageArgs": [],
      "MessageId": "Base.1.8.1.Created",
      "MessageSeverity": "OK",
      "Resolution": "None"
    }
  ]
}gmills@gfw279:/esw/san5/gmills/obmc/openbmc$ curl -k -H "X-Auth-Token: $token" -X POST https://${bmc}/redfish/v1/EventService/Subscriptions   -d '{"Destination": "snmp://snmp.prashanth.com:162", "SubscriptionType": "SNMPTrap", "Protocol": "SNMPv2c"}'
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_1_1.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.8.1.InternalError",
        "MessageSeverity": "Critical",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service."
      }
    ],
    "code": "Base.1.8.1.InternalError",
    "message": "The request failed due to an internal service error.  The service is still operational."
  }
}
```

I do see this event: 
```

{
"@odata.id": "/redfish/v1/EventService/Subscriptions/snmp1",
"@odata.type": "#EventDestination.v1_7_0.EventDestination",
"Context": "",
"Destination": "snmp://snmp.prashanth.com:162",
"EventFormatType": "Event",
"Id": "snmp1",
"Name": "Event Destination snmp1",
"Protocol": "SNMPv2c",
"SubscriptionType": "SNMPTrap"
}

```

**Comment by ChicagoDuan** [comment]
> I tried on another system and see it work on the first time but fail with an internal error on the 2nd

We can't have two identical SNMP clients. So the second failed is expected.
I have pushed a new patchset to make it return `resourceAlreadyExists` : https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38599/39

And I creat a PR to sync with upstream : https://github.com/ibm-openbmc/bmcweb/pull/225

**Comment by ChicagoDuan** [comment]
@gtmills Can we close this issue?

**Comment by mzipse** [comment]
@prkatti1 , I believe we are working to get our documentation updated, correct?  Is there anything else needed on this one?

**Comment by prkatti1** [comment]
Yep, we are good with current implementation & new fixes.
Just need documentation for pre-requisites @mzipse

**Comment by mzipse** [comment]
Documentation is in place.

**Comment by gtmills** [comment]
Closing
