### ISSUE TITLE
PAM python module investigation

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#34]
=> This pam module would be used in our current rest server which is python based app.

The outcome of this story would be
=> Bring the python pam module in the image.
=> Verify the pam api which can be used for pam_authentication.

Hoping the python pam should work if that doesn't work then we can write the pam api code in C and can invoke the c methods through python C extension but this one should be a least priority.

**Comment by dkodihal** [comment]
@tomjoseph83 has identifed Pamela as the module of choice. Can you add more details if you want @tomjoseph83?
