### ISSUE TITLE
eBMC LED Management :: Clear Fault LEDs(MEX) during PowerOn

### ISSUE THREAD

**Issue by lkammath** [ibm-openbmc/dev#3400]
#2115 added a code to clear both Identify and Fault Indicator LEDs as part of power on. 

#3228 added what we needed as a small update to that path because the faults are handled via setting the OperationalStatus on the Inventory object as opposed to setting fault led and thus LED setting OperationalStatus.

https://github.com/ibm-openbmc/phosphor-inventory-manager/scripts/clear-all-fault-leds.sh is  the script  which did OperationalStatus on the Inventory object as opposed to setting fault led and thus LED setting OperationalStatus
https://github.com/ibm-openbmc/phosphor-inventory-manager/remove-association is the app to remove critical association

The above scripts needs to modified to cleanup for MEX Chassis

MEX chassis is hosted by PLDM service :  /xyz/openbmc_project/inventory/system/chassis1536X

This issue is opened to track the cleanup for MEX FRU's

**Comment by rfrandse** [comment]
tracking in jira
