### ISSUE TITLE
Check for Pressure, Altitude sensors for Telemetry Service

### ISSUE THREAD

**Issue by aahmed-2** [ibm-openbmc/dev#3404]
Sensors are defined in eBMC systems to have/support the dbus interface "xyz.openbmc_project.Sensor.Value". 

Some sensors are showing up on under "dbus-send --system --print-reply --dest=xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper xyz.openbmc_project.ObjectMapper.GetSubTreePaths string:"/" int32:0 array:string:"xyz.openbmc_project.Sensor.Value", but are NOT showing up under Chassis/chassis/Sensors or TelemetryService/MetricDefinitions. 

From ever10bmc system, mapper call for "xyz.openbmc_project.Sensor.Value

      string "/xyz/openbmc_project/sensors/altitude/Altitude"
      string "/xyz/openbmc_project/sensors/fan_tach/fan0_0"
      string "/xyz/openbmc_project/sensors/fan_tach/fan0_1"
      string "/xyz/openbmc_project/sensors/fan_tach/fan1_0"
      string "/xyz/openbmc_project/sensors/fan_tach/fan1_1"
      string "/xyz/openbmc_project/sensors/fan_tach/fan2_0"
      string "/xyz/openbmc_project/sensors/fan_tach/fan2_1"
      string "/xyz/openbmc_project/sensors/fan_tach/fan3_0"
      string "/xyz/openbmc_project/sensors/fan_tach/fan3_1"
      string "/xyz/openbmc_project/sensors/pressure/Station_Pressure"
      string "/xyz/openbmc_project/sensors/temperature/Ambient_0_Temp"
      string "/xyz/openbmc_project/sensors/temperature/Ambient_1_Temp"
      string "/xyz/openbmc_project/sensors/temperature/Ambient_Virtual_Temp"
      string "/xyz/openbmc_project/sensors/temperature/PCIE_0_Temp"
      string "/xyz/openbmc_project/sensors/temperature/PCIE_1_Temp"
      string "/xyz/openbmc_project/sensors/utilization/CPU"
      string "/xyz/openbmc_project/sensors/utilization/Memory"
      string "/xyz/openbmc_project/sensors/voltage/Battery_Voltage"

**Comment by rfrandse** [comment]
tracking in jira
