### ISSUE TITLE
PCIeSlot LocationIndicatorActive improvements 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3406]
We have pulled in changes like https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/42216. 
Thanks for these commits. 

We have about ~22 PCIeSlots, these changes will allow for much better usability. 

```
curl -k https://$bmc/redfish/v1/Chassis/chassis/PCIeSlots
{
  "@odata.id": "/redfish/v1/Chassis/chassis/PCIeSlots",
  "@odata.type": "#PCIeSlots.v1_4_1.PCIeSlots",
  "Id": "PCIeSlots",
  "Name": "PCIe Slot Information",
  "Slots": [
    {
      "HotPluggable": false,
      "Lanes": 0,
      "Location": {
        "PartLocation": {
          "ServiceLabel": "U78D4.ND0.WZS000C-P1-C0"
        }
      },
      "LocationIndicatorActive": false
    },
    {
      "HotPluggable": false,
      "Lanes": 0,
      "Location": {
        "PartLocation": {
          "ServiceLabel": "U78D4.ND0.WZS000C-P1-C1"
        }
      },
      "LocationIndicatorActive": false
    },
    {
      "HotPluggable": false,
      "Lanes": 0,
      "Location": {
        "PartLocation": {
          "ServiceLabel": "U78D4.ND0.WZS000C-P1-C2"
        }
      },
      "LocationIndicatorActive": false
    },

```

1. Can we not have to give the whole array to turn on LED indicator. We are hitting this line: 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/42216/14/redfish-core/lib/pcie_slots.hpp#419 
Can we make this command work (given 22 slots but I only want to set the 2nd):

```
curl -k -X PATCH -d '{"Slots":[{"LocationIndicatorActive":false},{"LocationIndicatorActive":true}]}' https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_1_1.Message",
        "Message": "The requested resource of type Chassis named slots count was not found.",
        "MessageArgs": [
          "Chassis",
          "slots count"
        ],
        "MessageId": "Base.1.8.1.ResourceNotFound",
        "MessageSeverity": "Critical",
        "Resolution": "Provide a valid resource identifier and resubmit the request."
      }
    ],
    "code": "Base.1.8.1.ResourceNotFound",
    "message": "The requested resource of type Chassis named slots count was not found."
  }
}
```

2. Can we allow for an empty object in the array? 
Can we make we allow for this:
Again, given 22 slots but I only want to set the 2nd one. 
```
curl -k -X PATCH -d '{"Slots":[{},{"LocationIndicatorActive":true}]}' https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
```
@ChicagoDuan @lkammath @lxwinspur FYI. 

Thanks!!

**Comment by ChicagoDuan** [comment]
Hi @gtmills , I've already discussed this with @lkammath 。

For #1.  
> Can we not have to give the whole array to turn on LED indicator.

No. We can't. We need to give the whole array  to turn on LED indicator.  Sending only the first two data cannot determine which slot you want to set. For example, If the 1st slot can't be collected by redfish for some reasons when you sending command, so the total number of slots becomes 21 . At this time , sending only the first two data will light up the wrong led.  So we need to check the total number of the pcieslots.

For #2.
> Can we allow for an empty object in the array?

In the spec of redfish, empty object is allowed, but in bmcweb, empty object is not allowed. We have done some tests, please see the comment : https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/42216/14//COMMIT_MSG#111

**Comment by ChicagoDuan** [comment]
@gtmills Why does bmcweb not support empty objects? This contradicts the redfish spec. Can we make bmcweb support empty objects？

**Comment by gtmills** [comment]
> Why does bmcweb not support empty objects?

I am not sure. :( 
Might be a question for discord.

> Can we make bmcweb support empty objects？

Yes, I really hope we can

**Comment by ChicagoDuan** [comment]
Hi @gtmills please review this PR: https://github.com/ibm-openbmc/bmcweb/pull/201
Then we can use empty JSON object.
For example, If we have 10 pcieslots, and we want to set 2nd slot's LocationIndicatorActive to true, we can use the following command:
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Slots":[{},{"LocationIndicatorActive":true},{},{},{},{},{},{},{},{}]}'

**Comment by gtmills** [comment]
@ChicagoDuan ibm-openbmc/bmcweb#201  looks great, we will merge that today. 
If I have 22 PCIeSlots and want to just update the 2nd, can we allow for 
```
 curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Slots":[{},{"LocationIndicatorActive":true}]}'
```

?

**Comment by ChicagoDuan** [comment]
> 

I think we can't.
This usage is not defined in the redfish spec, and may cause the wrong LocationIndicatorActive to be set.

**Comment by gtmills** [comment]
@ChicagoDuan 
Why may it cause the wrong LocationIndicatorActive to be set?
Why can't we just assume the rest of the array is {}, the rest of the array won't be touched. 

So we treat 
`curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Slots":[{},{"LocationIndicatorActive":true}]}'`
the same as 
`curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Slots":[{},{"LocationIndicatorActive":true},{},{},{},{},{},{},{},{}]}'`

**Comment by ChicagoDuan** [comment]
> Why may it cause the wrong LocationIndicatorActive to be set?

@gtmills 
We need to check the total number of the pcieslots.
For example, If the 1st slot can't be collected by redfish for some reasons when you sending command, so the total number of slots becomes 21 . At this time , sending only the first two data will light up the wrong led(will light up the 3rd slot led). Lighting the wrong led in the operating environment is a serious error. In order to avoid this error, we need to check the total number of the pcieslots.

**Comment by gtmills** [comment]
What we have today works for now. We need to get PCIe Slots merged upstream. I am going to close.
