### ISSUE TITLE
GUI: FED: BUG - DIMMS missing properties

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3409]
## Expected Behavior
Need to display missing properties in expanded row: 

```
{
"@odata.id": "/redfish/v1/Systems/system/Memory/dimm0",
"@odata.type": "#Memory.v1_12_0.Memory",
"AllowedSpeedsMHz": [], <--- Need to confirm what goes here
"BaseModuleType": "RDIMM",
"BusWidthBits": 0,
"CapacityMiB": 0,
"DataWidthBits": 0,
"Enabled": false,
"ErrorCorrection": "NoECC",
"FirmwareRevision": "0",
"Id": "dimm0",
"Location": {
"PartLocation": {
"ServiceLabel": "U78DA.ND0.WZS004A-P0-C12"
}
},
"LocationIndicatorActive": false,
"Name": "DIMM Slot",
"OperatingSpeedMhz": 0,
"RankCount": 0,
"Status": {
"Health": "OK",
"State": "Absent"
}
}
``` 

Add horizontal divider like the chassis table row and list missing properties below divider.

## Actual Behavior

![Screen Shot 2021-12-16 at 3 07 42 PM](https://user-images.githubusercontent.com/26472611/146449173-a083aee5-938b-40a2-b7f6-a88588511336.png)

Defect details: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW539660

**Comment by sandeepasingh116** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/49975
