### ISSUE TITLE
GUI: FED: BUG: Assembly table Identify LED not working

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3410]
## Expected Behavior
Identify LED should toggle on/off successfully.

## Actual Behavior
Enable/disable assembly identify LED is failing.

Slack convo: https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1639685845100800
Defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW540909

**Comment by kennyneedsmilky** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/49843
