### ISSUE TITLE
GUI: FED: BUG: HMC sessions not disconnecting

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3411]
## Steps to Reproduce the Problem

Defect information: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW539042
Defect submitted by: Sandhya Somashekar 

> 1. In BMC GUI , navigate to below option under security and access -> HMC and user sessions
> 2. Click on "Disconnect" button
> 3. After this it displays a message "Successfully disconnected 1 session".
> 4. But if we refresh and check after few secs , HMC connection will be back. And also in HMC it shows as connected.

## Specifications
  - Browser: 
  - Version: fw1020.00-32.4

## Expected Behavior
When clicking disconnect the HMC session disconnects.

## Actual Behavior
When delete  was clicked on second connection item we see 200 response for `DELETE` 
![Screen Shot 2021-12-16 at 4 17 27 PM](https://user-images.githubusercontent.com/26472611/146457421-d32d20f4-121b-495d-819c-e28a7b3a68f5.png)
![Screen Shot 2021-12-16 at 4 16 40 PM](https://user-images.githubusercontent.com/26472611/146457424-6d7f0cfd-0f27-467f-a619-9ad90b5cd076.png)

Then, refreshed and session is still there
![Screen Shot 2021-12-16 at 4 20 42 PM](https://user-images.githubusercontent.com/26472611/146457578-21f5a69f-84d5-45e9-badf-c1c07f466910.png)

**Comment by Srisuk** [comment]
Working as expected, tried logging from two machines, disconnect the other machine then the user got logged out on refreshing the page.

**Comment by dixsie** [comment]
@Srisuk can you share the firmware version so I can share with the test team, thanks

**Comment by Srisuk** [comment]
@dixsie the firmware version is fw1020.00-37.4

**Comment by mzipse** [comment]
@Srisuk , can you please add the link to the Gerrit commit?  Thanks.

**Comment by Srisuk** [comment]
Hey @mzipse, the link is not there as there is no fix for this, I think the error was intermittent which got resolved automatically.

**Comment by Srisuk** [comment]
The machine on which I tested was rain111bmc.aus.stglabs.ibm.com and the firmware version was fw1020.00-37.4

**Comment by dixsie** [comment]
Need to discuss -  HMC can only be disconnected from HMC and not GUI.  

@gtmills is this a front end issue? Rahul suggested displaying an alert message explaining the HMC connection may still be connected after clicking disconnect because HMC can only be disconnected from HMC and not GUI. He said we shouldn't remove the disconnect option  either because some connections can be disconnected.

**Comment by Srisuk** [comment]
Discussion is going to happen on 18th Jan at the design meeting ([slack conversation](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1641985145132300))

**Comment by dixsie** [comment]
HMC session disconnects only from HMC

Closing because HMC will always try to reconnect, not F/e issue.

**Comment by gtmills** [comment]
The ask was to add some helper text here: 
https://github.com/ibm-openbmc/dev/issues/3455 tracks this
