### ISSUE TITLE
GUI: FED: Bug: Not able to configure DHCP property UseNTPServers

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3412]
DHCP property UseNTPServers is not working and its value is not getting reflected in backend. It always remains enabled irrespective on enable or disable on GUI.

## Specifications
  - Version: on 35.6 driver

Defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW540878

**Comment by ghost** [comment]
Resolved By: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/50616
