### ISSUE TITLE
GUI: FED: Bug: Delete button for service user should be disabled

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3416]
- [x] Delete button for `service` user should be disabled like the way it is for `root` user.  All other users can be deleted. 
- [x] Need to confirm with @gtmills - should the edit button for `service` user also be disabled?

![Screen Shot 2021-12-22 at 8.06.33 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/94c3ecb7-0b3d-4aa3-b5c7-5a3b5b19a2e2)

## Specifications
  - Browser: 
  - Version: 33.1

## Defect
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW539395

**Comment by dixsie** [comment]
@gtmills 
@joseph-reynolds 

Do any of these options apply to the service user or should they be disabled?

<img width="529" alt="Screen Shot 2022-01-06 at 9 27 46 AM" src="https://user-images.githubusercontent.com/26472611/148406988-90143c3c-ab6f-4dbf-b8d0-a3e2c173ca51.png">

**Comment by kennyneedsmilky** [comment]
Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/43
