### ISSUE TITLE
GUI: FED: Bug:  Invalid password in profile settings validation error

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3417]
- [ ] This is an older bug from defect list,  verify in the UI if this problem still exists. If it does not exist comment in Github issue what firmware version you tested with.

## Problem Description

* Description: Displays successful message for unsuccessful password change

## Steps to Reproduce the Problem

1. Login to GUI page.
2. After login, in the Header section click on root (user)
3. From the drop down list Navigate to Profile settings page
4. In 'Change Password' section update password to new password with 7 characters
5. Click 'Save settings'.

Page displays 'Success' message, but password will not be changed to new password.

## Specifications
  - Browser: 
  - Version: 32.0

## Defect
- [ ] https://w3.rchland.ibm.com/projects/bestquest/?defect=SW538588

**Comment by sandeepasingh116** [comment]
Resolved by :
 https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/50030
