### ISSUE TITLE
GUI: FED: Bug: System inventory table missing values

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3418]
Problem Description
----------
* Description: System inventory does not have TotalSystemMemoryGiB and CoreCount field

Step to recreate:
1. Go to Inventory page from hardware status menu and expand system table row.
2.  TotalSystemMemoryGiB and CoreCount field is not present. These field are present in the backend.

-[ ] Confirm with @gtmills, do we want to display both CoreCount and Count?

![Screen Shot 2021-12-22 at 8.32.41 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/268382b8-87bd-48ab-b731-d8bde483f755)

## Specifications
  - Browser: 
  - Version: 31.3
  - Defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW537539

```
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC_IP}/redfish/v1/Systems/system
{
...
    "TotalSystemMemoryGiB": 512
  },
...
  "ProcessorSummary": {
    "CoreCount": 16, <--- need to confirm with @gtmills, do we want to display both CoreCount and Count?
    "Count": 2, 
    ...
  },
 ...
}
```

**Comment by Nikhil-Ashoka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/50141
