### ISSUE TITLE
PFP: Eliminate conflicting timeouts in json config

### ISSUE THREAD

**Issue by mikecgithub** [ibm-openbmc/dev#3419]
## Expected Behavior
Any json timeouts should not allow conflicting settings.

## Actual Behavior
Inputs are not validated. for instance, an Emergency Poweroff can be triggered to occur with 10s of fan failure, while the poweron timeout of fan monitor can be set to 30. this will result in a system always being powered off, because the monitor cannot properly assess the state of fans.

**Comment by rfrandse** [comment]
tracking in jira
