### ISSUE TITLE
EM/DS: Investigate/add ambient temp offset

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3420]
There is a need to apply a degree offset to the ambient temp read by an ambient temp sensor to get a more exact ambient reading that may be affected by fan airflow, etc.. over the ambient sensor(s). This would be applicable to the direct ambient sensor(s) and not any virtual sensor(s) that may be created from reading those ambient sensor(s) so it may already exist. This issue is to investigate if this functionality already exists and if not, add it to the appropriate code repository and configuration parsing.

**Comment by msbarth** [comment]
One known use of this is on the Rainier 2U system, where its been found an offset of -2 degrees needs to be applied to a subset of the ambient sensors available. That subset of ambient sensors is yet to be determined specifically by the thermal team but initial findings show there's a deviation between the reporting ambient within the 2U system and the thermal chamber it was placed in.

**Comment by spinler** [comment]
Systems have shipped and no official request for this, so closing.
