### ISSUE TITLE
Unexpected BMC dumps occuring

### ISSUE THREAD

**Issue by mzipse** [ibm-openbmc/dev#3423]
@lxwinspur , wondering if you might be able to help us debug this issue since Bruce Mitchell has decided to leave IBM as of the end of the year.  Seeing some unexpected bmc dumps possibly due to dropbear and the service-config-manager.  CQ SW541052.  Here are some details:

==== State: Open by: swanman on 11 December 2021 11:48:35 ==== 1

Our DVT tests do not yet check for xx number of obmcdumps per each boot type, as it does in FSP.
In preparation for this, I did some snooping in our latest 1020.2150.20211210b runs (as it pulled in an obmcdump fix) and I am seeing several dumps on our everest BMC reboot tests.  Are these all expected dumps, or is there an issue here??

==== State: Open by: swanman on 13 December 2021 14:55:16 ==== 2

From Andrew Geissler:

@Bruce Mitchell I see ever30bmc does not have the 0 file size issue. It has the "very large file size issue". I see srvcfg-manager is consistently failing on that machine:
root@ever30bmc:~# cat /etc/srvcfg-mgr.json | wc
    24195     40326   1130496
root@ever30bmc:~# journalctl | grep srvcfg
Dec 13 13:04:39 ever30bmc srvcfg-manager[286]: terminate called after throwing an instance of 'cereal::RapidJSONException'
Dec 13 13:04:39 ever30bmc srvcfg-manager[286]:   what():  rapidjson internal assertion failure: IsObject()
Dec 13 13:04:40 ever30bmc systemd-coredump[759]: Process 286 (phosphor-srvcfg) of user 0 dumped core.
Dec 13 13:04:40 ever30bmc systemd[1]: srvcfg-manager.service: Main process exited, code=dumped, status=6/ABRT
Dec 13 13:04:40 ever30bmc systemd[1]: srvcfg-manager.service: Failed with result 'core-dump'.
Dec 13 13:04:41 ever30bmc systemd[1]: srvcfg-manager.service: Scheduled restart job, restart counter is at 1.
Dec 13 13:04:41 ever30bmc srvcfg-manager[802]: terminate called after throwing an instance of 'cereal::RapidJSONException'
Dec 13 13:04:41 ever30bmc srvcfg-manager[802]:   what():  rapidjson internal assertion failure: IsObject()
Dec 13 13:04:42 ever30bmc systemd-coredump[828]: Process 802 (phosphor-srvcfg) of user 0 dumped core.
Dec 13 13:04:42 ever30bmc systemd[1]: srvcfg-manager.service: Main process exited, code=dumped, status=6/ABRT
Dec 13 13:04:42 ever30bmc systemd[1]: srvcfg-manager.service: Failed with result 'core-dump'.
Dec 13 13:04:43 ever30bmc systemd[1]: srvcfg-manager.service: Scheduled restart job, restart counter is at 2.
I think we gotta get to the bottom of why that file is growing so large. We seem to add every dropbear session to it and in DVT, with all the logging in and out, it causes a very large file.

==== State: Open by: andrewg on 14 December 2021 08:37:07 ==== 3

#=#=# 2021-12-14 08:37:06 (CST) #=#=#
New Component_Name = [base]
New OwnerInfo = [Mitchell, Bruce (Bruce.Mitchell@ibm.com)]

This file has over 24,000 lines in it, mostly monitoring dropbear connections. I'm not sure if the excessive entries here is responsible for the error but we should get to the bottom of that.

root@ever30bmc:~# cat /etc/srvcfg-mgr.json | wc
    24195     40326   1130496

The dumps are a result of this:

root@ever30bmc:~# journalctl | grep srvcfg
Dec 13 13:04:39 ever30bmc srvcfg-manager[286]: terminate called after throwing an instance of 'cereal::RapidJSONException'
Dec 13 13:04:39 ever30bmc srvcfg-manager[286]:   what():  rapidjson internal assertion failure: IsObject()
Dec 13 13:04:40 ever30bmc systemd-coredump[759]: Process 286 (phosphor-srvcfg) of user 0 dumped core.
Dec 13 13:04:40 ever30bmc systemd[1]: srvcfg-manager.service: Main process exited, code=dumped, status=6/ABRT
Dec 13 13:04:40 ever30bmc systemd[1]: srvcfg-manager.service: Failed with result 'core-dump'.
Dec 13 13:04:41 ever30bmc systemd[1]: srvcfg-manager.service: Scheduled restart job, restart counter is at 1.
Dec 13 13:04:41 ever30bmc srvcfg-manager[802]: terminate called after throwing an instance of 'cereal::RapidJSONException'
Dec 13 13:04:41 ever30bmc srvcfg-manager[802]:   what():  rapidjson internal assertion failure: IsObject()
Dec 13 13:04:42 ever30bmc systemd-coredump[828]: Process 802 (phosphor-srvcfg) of user 0 dumped core.
Dec 13 13:04:42 ever30bmc systemd[1]: srvcfg-manager.service: Main process exited, code=dumped, status=6/ABRT
Dec 13 13:04:42 ever30bmc systemd[1]: srvcfg-manager.service: Failed with result 'core-dump'.
Dec 13 13:04:43 ever30bmc systemd[1]: srvcfg-manager.service: Scheduled restart job, restart counter is at 2.

Bruce is helping out on this one.
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

==== State: Open by: us5j2111 on 15 December 2021 08:55:53 ==== 4

Note the Date Time Stamp /etc/srvcfg-mgr.json
vs the machine time of ever30bmc

root@ever30bmc:~# date
Wed Dec 15 14:51:32 UTC 2021
root@ever30bmc:~# ls -la /etc/srvcfg-mgr.json
-rw-r--r--    1 root     root       1130496 Dec  3 10:31 /etc/srvcfg-mgr.json
root@ever30bmc:~#

Still investigating.

==== State: Open by: us5j2111 on 15 December 2021 11:41:44 ==== 5

This is the upstream OpenBMC commit that added SSH (i.e. dropbear) to
service-config-manager(i.e. srvcfg-manager)
43476: Allow disabling SSH
https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/43476

The service-config-manager(i.e. srvcfg-manager) file src/main.cpp
is the only place that I find that does anything with the file /etc/srvcfg-mgr.json

==== State: Open by: us5j2111 on 16 December 2021 15:18:17 ==== 6

I just found a way to get the file to grow systemctl stop srvcfg-manager and then do a second ssh to the BMC and then systemctl start srvcfg-manager

**Comment by lxwinspur** [comment]
@mzipse 
I have pushed a new patch to Gerrit: https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/50132
I am not sure if it solves this issue, Could you ask IBM colleague to help with the test? and please leave message if you have any questions :)

**Comment by mzipse** [comment]
This has been merged downstream.  We can close this out once it is merged upstream.

**Comment by lxwinspur** [comment]
This has been merged upstream, we can close this issue.
