### ISSUE TITLE
5x increase in code update when running with boost timer with 100 connection limit

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3426]
We reported a 5x increase in code update when running with these commits  https://github.com/ibm-openbmc/bmcweb/pull/207

These commits have been merged upstream so should drive this with the community. 

We reverted them here: https://github.com/ibm-openbmc/bmcweb/pull/213

See:
https://ibm-systems-power.slack.com/archives/C1HT3FHNK/p1641389624166500?thread_ts=1640266834.132600&cid=C1HT3FHNK
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW541514

**Comment by sbteeks** [comment]
I tried code update via Redfish API with upstream image on tacoma, it took little over 6s to upload ~50MB image, and on Rainier with P11-bringup image (200MB) it took ~24s. Looks like the time taken to upload the image and the size are directly related, and I guess this increased time is expected.

Note: The code update via Redfish API seems OK, but noticed an 'Internal error' in the task. After reboot BMC was running with new driver. The 'Internal error' in the task is something that needs to be addressed, and has nothing to do with 5X increase.

**Comment by gtmills** [comment]
Closing.
