### ISSUE TITLE
GUI : FED : Refactor power page

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3427]
## SME
**BMC**:
**RAS**:
**PHYP**:

### Overview
- Refactor power page into separate components

### Acceptance Criteria
- [x]  Refactor power page into separate components
- [ ] update enable checkboxes for power cap and idle power - users can set the values and enable those settings at another time independently of each other
- [ ] update  both checkboxes to toggle switches and change power cap taxt from `apply` to enable/disable
![Screen Shot 2022-01-21 at 10.30.04 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/ab96cda9-ac83-45f3-91ba-8180c90e61e3)

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [x] Tested responsive layout on supported viewport sizes
- [x] Verified functionality works as expected, e.g. success and failure use cases
- [x] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [x] Verified markup is semantic
- [x] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by ghost** [comment]
Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/109
