### ISSUE TITLE
Server Power Operation: Radio buttons for server power policy are not updating on the UI after saving.

### ISSUE THREAD

**Issue by sandeepasingh116** [ibm-openbmc/dev#3432]
## Expected Behavior
On updating and saving the server power policy on server power operations page, the UI should show updated value of server power policy.

## Actual Behavior
However, on updating and saving the server power policy on server power operations page, the UI is not updating and showing the previous value. This is observed when the user checks for the updated value on another browser i.e. user updates and saves value from one browser and refreshes the UI on another browser. On second refresh the updated value will show.

## Steps to Reproduce the Problem

  1. Update the value of server power policy from one browser and save it.
  2. Refresh the server power ops page on another browser.
 

## Specifications
  - Browser: 
  - Version:

**Comment by sandeepasingh116** [comment]
Had a discussion with @Srisuk in order to understand the code to help with debugging. She has owned up to solve this bug as she has better understanding of server power ops page.

**Comment by Su-kan** [comment]
Resolved by https://github.ibm.com/openbmc/webui-vue/pull/48
