### ISSUE TITLE
u-boot: Place TPM in reset

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#3436]
The P10 systems contain a BMC TPM. For the initial firmware release the code will not be in place to do record the boot state, so the system should hold the TPM in reset from the u-boot SPL.

  * Add reset GPIO to device tree
  * Parse device tree to discover the reset GPIO
  * Work out what state it needs to go in (bounce? a specific level?)
  * Set this in u-boot
    * Hog?
    * Code in board_init?
    * Do we need to create a ibm p10 board (like the intel board) in u-boot to 
      hold these things?
    * Do we tie this to the secure boot GPIO to allow TPM testing when secure boot is disabled?

**Comment by eddiejames** [comment]
I'm thinking that the right way to do this is to start writing the I2C TPM2 driver, which we eventually need, and for now just have it put the TPM in reset?

**Comment by eddiejames** [comment]
Nevermind, my understanding of the TPM reset wasn't correct. The GPIO to reset the TPM is latched, meaning that it requires a reboot of the BMC to clear. So in normal operation, where the TPM is going to be used, we won't be touching this GPIO.
Maybe something board specific is better then.

**Comment by shenki** [comment]
This was merged into the aspeed openbmc tree.

https://lore.kernel.org/openbmc/20220207231334.59845-1-eajames@linux.ibm.com/
