### ISSUE TITLE
u-boot: Disable FIT secure boot based on jumper

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#3437]
u-boot will only enforce it's secure boot "vboot" if the secure boot jumper is in the secure state. This is to allow unsigned FIT images to be tested on machines that have the jumper in the insecure state without having to flash a different u-boot SPL.

  * Add "secure boot enable" to device tree (see Linux device tree)
  * Parse device tree to discover the jumper
  * Work out what state it is "disable secure boot"
  * Hook this into FIT vboot verification code

**Comment by amboar** [comment]
`gpio: Add bmc-secure-boot`: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/47134

**Comment by amboar** [comment]
I've sent a couple of patches to upstream u-boot that add partial support for controlling FIT signature verification at runtime:

* https://lore.kernel.org/openbmc/20220131034147.106415-1-andrew@aj.id.au/
* https://lore.kernel.org/openbmc/20220131032405.105204-1-andrew@aj.id.au/

And I've posted a functioning series against the OpenBMC u-boot tree here:

https://lore.kernel.org/openbmc/20220131012538.73021-1-andrew@aj.id.au/

**Comment by shenki** [comment]
Andrew and Chris decided this work is not required for the use case we have, and have stopped working on it.
