### ISSUE TITLE
PLDM Daemon: implement PLDM discovery

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#344]
- [ ] libpldm : implement encode and decode APIs for GetTID
- [ ] libpldmresponder : implement GetTID command handler. A value of 1 could be assigned to the BMC as the PLDM terminus.
- [ ] Write unit tests

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
GetPLDMTypes, GetPLDMCommands and GetPLDMVersion have been implemented, but setting terminus id still needs to be implemented.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/23961/

**Comment by wangzqbj** [comment]
As @vishwabmc mentioned in  gerrit,we have SetTID,shoudle we create a new task to implement it?

**Comment by dkodihal** [comment]
I think SetTID would be another story. I can define that shortly.

**Comment by wangzqbj** [comment]
Merged: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/23961
