### ISSUE TITLE
GUI : FED : Remove "boot settings override" 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3441]
Remove this boot settings override: 
![boot-settings-override](https://user-images.githubusercontent.com/5455127/149348767-35c6d472-3387-41a0-b190-d0c4d0ec1c2d.JPG)

 
 See the slack conversation for more info: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1642083982157400?thread_ts=1642083271.155600&cid=C0Q6TQP5Z
 
 https://github.com/ibm-openbmc/bmcweb/pull/209 removed boot settings override

**Comment by Su-kan** [comment]
Resolved by https://github.ibm.com/openbmc/webui-vue/pull/48
