### ISSUE TITLE
PFP::monitor - Create an equivalent `fanctl` application for fan monitor

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3446]
It would be beneficial to have an application similar to `fanctl` for the fan monitoring application that can display fan status information that's associated with the fan monitoring application (i.e. Functional states, configured fan feedback/target deviation range allowed w/ current feedback/target values, reload fan monitor's config, etc..).

**Comment by spinler** [comment]
Since we have a fan monitor dump now, we can just use that to debug fan monitor.  Closing this.
