### ISSUE TITLE
GUI: FED: Bug: Unable to upload ACF file

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3447]
## Expected Behavior
User should be able to upload .acf file. `form-file` should `accept` .acf files  

## Actual Behavior
.acf file is greyed out and user is unable to upload.

![image.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/15639444-1bf4-4bad-983b-e739a5df4b33)

## Steps to Reproduce the Problem

1. Login to OpenBMC GUI
2. Navigate to certificate page
3. Try to select ACF file from local system and try to upload

Actual result: Files (service.acf) greyed out and so cannot be selected

## Specifications
  - Browser: 
  - Version: 38.4

**Comment by sandeepasingh116** [comment]
Resolved by : https://github.ibm.com/openbmc/webui-vue/pull/52
