### ISSUE TITLE
ibmswtpm2 no longer builds in upstream

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3452]
We get this error:
```
| TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
|    79 | #   error Untested OpenSSL version
|       |     ^~~~~
```

Upstream brought in openssl3.0. https://sourceforge.net/p/ibmswtpm2/tickets/18/ tracks something that appears to be similar but it's not totally clear. 

For now, to keep upstream moving forward, we're going to remove this package from p10bmc systems.

**Comment by rfrandse** [comment]
tracking in jira
