### ISSUE TITLE
Add missing properties to Dimms table

### ISSUE THREAD

**Issue by sandeepasingh116** [ibm-openbmc/dev#3453]
## Expected Behavior
DIMM details like AllowedSpeedsMHz, FirmwareRevision, Manufacturer, Model and RankCount are missing in hardware inventory page.

## Actual Behavior
The above mentioned properties should be added to the Dimms table

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications
  - Browser: 
  - Version:

**Comment by Nikhil-Ashoka** [comment]
Resolved by: https://github.ibm.com/openbmc/webui-vue/pull/58
