### ISSUE TITLE
GUI : FED : Some helper text on the GUI session page to say something like "If the HMC is active, it will attempt to reconnect. To disconnect a working HMC, please do so from the HMC itself."

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3455]
This was discussed at Dean's 1/18 meeting. From https://ibm.ent.box.com/file/907664148976

Unable to convert HMC to non-HMC managed system via eBMC GUI (Gunnar, Brad, Hari, Rahul)
???Discuss https://w3.rchland.ibm.com/projects/bestquest/?defect=SW542000
???GUI triggers disconnect of HMC connection, HMC session gets deleted. But because of HMC behaviour, HMC retries to connect back with the BMC and establish the session FSP behavior:
???A running/working HMC user cannot disconnect from ASMI on the FSPeBMC behavior:
???Add some helper text to the GUI that says that it will only work if HMC disconnected (or that if HMC is active it will re-connect).

This would be a downstream only GUI change to add some helper text to say something like "If the HMC is active, it will attempt to reconnect. To disconnect a working HMC, please do so from the HMC itself."

See defect SW542000

**Comment by mzipse** [comment]
Per feedback from Sandeepa, this test has already been added quite some time back to our downstream code.

**Comment by mzipse** [comment]
Work is complete.  Closing.
