### ISSUE TITLE
GUI : FED : Add toggle to enable/disable the secure version lock in

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#3458]
## SME
**BMC**:
**RAS**:
**PHYP**:

### Overview
There is a requirement to have the GUI offer a toggle to enable/disable the "secure version lock in", which is a bios attribute (https://github.com/openbmc/pldm/commit/ea72f240bbb734b0faa8f9b29056eca5a163c1de). The secure version lock in is a security feature that is Disabled by default. If enabled, the host (bios) firmware prevents the host firmware from running if the firmware level has a non-approved version.

The toggle text could be:
Host Firmware Security Policy
Host firmware secure version lock in: Disable

The help text could be:
Host Firmware Security Policy
The host firmware has anti-rollback protection which is used to block older firmware from being loaded.This protection is provided by comparing the current firmware to a minimum secure version that is programmed into the hardware. Enabling host firmware secure version lock in will cause the host firmware to update the minimum secure version to match the currently running firmware during the power on. Warning: This change cannot be reversed.

### Acceptance Criteria
- [ ] Feature breakdown

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by mzipse** [comment]
Here's the Redfish bios attribute info needed for this work.
   {
         "attribute_name":"hb_secure_ver_lockin_enabled",
         "possible_values":[
            "Enabled",
            "Disabled"
         ],
         "default_values":[
            "Disabled"
         ],
         "helpText" : "Specifies whether the secure version lockin functionality is enabled.",
         "displayName" : "Secure Version Lockin Enabled"
      },

**Comment by Nikhil-Ashoka** [comment]
Resolved by: https://github.ibm.com/openbmc/webui-vue/pull/167
