### ISSUE TITLE
validate secure boot settings when in manufacturing mode

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3462]
Read a GPIO(?) and compare with the sysfs file from https://github.com/ibm-openbmc/dev/issues/3438. If we're in mfg mode, log an error if they are not correct.

More details needed but this is a place holder to track this error logging function.

**Comment by cjengel** [comment]
There are two SB settings.  There is the sysfs file from #3438 which is Aspeed SB as well as J1_SECURE_BOOT which is a GPIO 'gpioget gpiochip0 70'.

If the sysfs file indicates Aspeed SB disabled or the GPIO==0 need to log an error in MFG mode so that the MFG team can detect misconfigured HW and correct it.

**Comment by geissonator** [comment]
Generic GPIO name was added via https://github.com/openbmc/docs/commit/d55349e10ec2432886b26b00322ef0eaff2b919a (bmc-secure-boot)

So basic flow is:
- Check if "mfg mode" is enabled - QuiesceOnHwError?
- If not enabled, exit and do not run below logic

GPIO Logic
- Check if `bmc-secure-boot` is a defined GPIO on system. If not, exit
- Read the GPIO, if 0 log an error, do not run next Sysfs check (only one error needed)

Sysfs Logic
- Check if /sys/firmware/bootinfo/secure_boot exists on systems, If not, exit
- Read the file, if 0 log an error

**Comment by shenki** [comment]
The files are now at /sys/kernel/debug/aspeed/

* /sys/kernel/debug/aspeed/secure_boot
* /sys/kernel/debug/aspeed/abr_image
* /sys/kernel/debug/aspeed/otp_protected

A correctly provisioned system should have secure_boot and otp_protected set to 1.

abr_image is a per-boot setting. It should always be 0. Raise an error if set to 1.

**Comment by shenki** [comment]
> Generic GPIO name was added via [openbmc/docs@d55349e](https://github.com/openbmc/docs/commit/d55349e10ec2432886b26b00322ef0eaff2b919a) (bmc-secure-boot)
> 
> So basic flow is:
> 
>     * Check if "mfg mode" is enabled - QuiesceOnHwError?
> 
>     * If not enabled, exit and do not run below logic

Can we log something to the journal, without creating a formal log?

> 
> 
> GPIO Logic
> 
>     * Check if `bmc-secure-boot` is a defined GPIO on system. If not, exit
> 
>     * Read the GPIO, if 0 log an error, do not run next Sysfs check (only one error needed)
> 
> 
> Sysfs Logic
> 
>     * Check if /sys/firmware/bootinfo/secure_boot exists on systems, If not, exit

We should still log if the file does not exist.

I suggest we check all of the bits, and output the information in the journal. It's only once the info is collected and we're in manufacturing mode that if we have any errors we raise a error.

**Comment by geissonator** [comment]
Series of commits up at https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/51765

**Comment by mzipse** [comment]
This got pulled in downstream.

**Comment by mzipse** [comment]
Refresh

**Comment by geissonator** [comment]
This was merged upstream
