### ISSUE TITLE
 ProcessorSummary and MemorySummary Status 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3464]
Typically we map "Status""State" to the Present property on D-Bus. E.g. https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/fan.hpp#L15
And we map "Status""Health" to the Functional property on D-Bus. E.g.
https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/power_supply.hpp#L168

In the ComputerSystem ProcessorSummary and MemorySummary we are mapping ["Status"]["State"] to Functional. 
Revisit this. We should probably map  ["Status"]["State"] to Present and ["Status"]["Health"] to Functional

**Comment by rfrandse** [comment]
tracking in jira
