### ISSUE TITLE
Add support for USER_DATA_14 (BEh)

### ISSUE THREAD

**Issue by bjwyman** [ibm-openbmc/dev#3471]
The IBM power supplies use USER_DATA_14 (BEh) for some various other indicators that may be of interest to monitor.
* AC or DC input
* High or low voltage input  (if don't use this, need to deglitch the read_vin value so we don't think wrong type of ac attached?)
* THROTTLE#

Some other bits that may be worth monitoring.

Device driver and PSU monitor application updates.

**Comment by rfrandse** [comment]
tracking in jira
