### ISSUE TITLE
The Sessions page should be hidden from the navigation when operator user is logged in 

### ISSUE THREAD

**Issue by sandeepasingh116** [ibm-openbmc/dev#3474]
Hide the sessions page from the navigation when operator is logged in, as an operator is not allowed to disconnect any alive session

**Comment by dixsie** [comment]
@gtmills how should we check for operator users? Will operators always have "operator" as the username (like admin and service usernames)

**Comment by gtmills** [comment]
You will have to check the username's role

**Comment by dixsie** [comment]
Is this  story  still needed since the  operator  role is going away? @gtmills
