### ISSUE TITLE
Update Assembly Resource To Populate Status::State

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3476]
Similar to how we look at Operational Status to set the Status::Health Redfish property (See https://github.com/ibm-openbmc/bmcweb/pull/202), we can look at the Present property on D-Bus to set the Status::State property

If Present is true, set Status::State to Enabled, else set it to Absent.

We do this for other resources like:
https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/power_supply.hpp#L134

https://github.com/ibm-openbmc/bmcweb/issues/247 is same issue

**Comment by SunnySrivastava1984** [comment]
Code updated under PR 
https://github.com/ibm-openbmc/bmcweb/pull/256

**Comment by mzipse** [comment]
Work is complete.  Closing.
