### ISSUE TITLE
Add Firmware Version to Power Supplies 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3477]
```
root@srainier2s2u:~# busctl get-property xyz.openbmc_project.Inventory.Manager /xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply0 xyz.openbmc_project.Software.Version Purpose Version
s "xyz.openbmc_project.Software.Version.VersionPurpose.Unknown"
s "313033323330"
root@srainier2s2u:~# busctl get-property xyz.openbmc_project.Inventory.Manager /xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply1 xyz.openbmc_project.Software.Version Purpose Version
s "xyz.openbmc_project.Software.Version.VersionPurpose.Unknown"
s "313033323330"
root@srainier2s2u:~#
```
Might have to add this interface to your test machine's power supplies to test 

Redfish supports this for PowerSupplies we just haven't implemented 

```
                "FirmwareVersion": {
                    "description": "The firmware version for this power supply.",
                    "longDescription": "This property shall contain the firmware version as defined by the manufacturer for this power supply.",
                    "readonly": true,
                    "type": [
                        "string",
                        "null"
                    ]
                },
```
https://redfish.dmtf.org/schemas/v1/PowerSupply.v1_3_0.json

https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/power_supply.hpp

**Comment by lxwinspur** [comment]
@gtmills 
Is this issue upstream or downstream?

**Comment by gtmills** [comment]
downstream, but I would like this change to be added on top of https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40326

**Comment by ChicagoDuan** [comment]
Done. Please review: https://github.com/ibm-openbmc/bmcweb/pull/259
And this change has be added on top of https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/40326

**Comment by ChicagoDuan** [comment]
Close this issue. https://github.com/ibm-openbmc/bmcweb/pull/259

**Comment by gtmills** [comment]
Let's keep this open until upstream merged

**Comment by mzipse** [comment]
@gtmills , have we pulled this in downstream yet?

**Comment by lxwinspur** [comment]
> [ibm-openbmc/bmcweb#259](https://github.com/ibm-openbmc/bmcweb/pull/259)

Yes, I think so, it has been merged downstream: https://github.com/ibm-openbmc/bmcweb/pull/259

**Comment by mzipse** [comment]
Thank you!  Marking "Code Review in Driver"

**Comment by gtmills** [comment]
This merged at https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57672 
Closing
