### ISSUE TITLE
bmcweb "Can't find usb code update service" logs

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#3478]
When the BMC boots up, there are sometimes multiple "Can't find usb code update service" logs created by bmcweb. These were added as part of the USB Enable/Disable feature: https://github.com/ibm-openbmc/bmcweb/pull/164

Discussing with the IBM team, it may be the USB service is not running yet, therefore it'd be better if service is not available, to not return the data associated with it, instead of returning an InternalError response for it.

Other internal errors due to services not being available will be cleaned up, but this issue is for the usb one.

**Comment by ChicagoDuan** [comment]
Please review: https://github.com/ibm-openbmc/bmcweb/pull/258

**Comment by ChicagoDuan** [comment]
Merged. https://github.com/ibm-openbmc/bmcweb/pull/258
