### ISSUE TITLE
GUI: FED: Bug: Multiple pages have multiple calls to the same endpoint

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3479]
https://github.com/openbmc/webui-vue/issues/43 might fix some of this. Multiple pages have multiple calls to the same endpoint. 

Multiple calls to system, bmc and redfish/v1/ on the overview page 
![image](https://user-images.githubusercontent.com/5455127/152570979-2902a0ca-e3b6-4cd5-aa95-dad8a4b9aec3.png)

The power operations page has 3 calls to the system resource 
![3 calls](https://user-images.githubusercontent.com/5455127/152571139-966a39c2-30c0-4d39-a788-3f16aac23ffe.JPG)

Inventory page has multiple calls to system, chassis and redfish/v1/

**Comment by rfrandse** [comment]
tracking in jira
