### ISSUE TITLE
Evaluate existing IPv6 support from the upstream networkd

### ISSUE THREAD

**Issue by sunharis** [ibm-openbmc/dev#3480]
Check the existing IPv6 Dbus and networkd support for Static & DHCP

**Comment by rsnair** [comment]
Modifying the story scope for the following -
=> Master refresh for networkd 
=> Effort for Merge conflict resolution 
=> Regression test effort to ensure the existing features are not broken
=> Evaluating the IPv6 support from the latest master

**Comment by raviteja-b** [comment]
Currently Networkd does not have full IPv6 support.
there are two commits for IPv6 support under review.
Created a test build with these commits and started verifying IPv6 functions

**Comment by sunharis** [comment]
Done. We have the list of changes needed from upstream and code ready for the missing part.
