### ISSUE TITLE
PLDM: Consume availability interface for cores

### ISSUE THREAD

**Issue by manojkiraneda** [ibm-openbmc/dev#3481]
In the current state, the logic is bmcweb for displaying cores is that :

It checks the [Present property](https://github.com/openbmc/phosphor-dbus-interfaces/blob/08baf48ad5f15774d393fbbf4e9479a0ef3e82d0/yaml/xyz/openbmc_project/Inventory/Item.interface.yaml#L9) on core dbus object to update the [Status][State] as [Enabled/Absent](https://github.com/ibm-openbmc/bmcweb/blob/8044381620b228f99b707ea2b444c7675e714f26/redfish-core/lib/processor.hpp#L1055).

In addition to to Present property, we should also use the [Available property](https://github.com/openbmc/phosphor-dbus-interfaces/blob/bc6b8a7649129e271404d96abb98ae24c11701aa/yaml/xyz/openbmc_project/State/Decorator/Availability.interface.yaml#L4) , if the Available is false, then set the [Status][State] should be set as "UnavailableOffline".

**Comment by lxwinspur** [comment]
review by: https://github.com/ibm-openbmc/bmcweb/pull/254

**Comment by mzipse** [comment]
@manojkiraneda, I see the PR 254 is merged.  Can we mark this issue "Code Review in Driver"?  Also, do we need this upstreamed as well?

**Comment by manojkiraneda** [comment]
yes, this is needed upstream , but it depends on a lot of base commits - for now..i think we can close this as its in the driver.
