### ISSUE TITLE
Additional properties on /redfish/v1 needed for ACF generation

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3484]
/redfish/v1 as new Oem.IBM properties:

    The system Model. E.g. "Model": "9105-42A", 
    The system serial number.
    The BMC’s time of day (or yyyy-mm-dd).
    
    

@joseph-reynolds FYI

**Comment by joseph-reynolds** [comment]
Do we also need to know if the "OpPanel function 74 time window" is currently open to satisfy https://github.com/ibm-openbmc/dev/issues/3019

**Comment by gtmills** [comment]
This only tracks what was on ASMI and is needed for ACF generation: 

ASMI had on the header of the login: 
```
Server-<repeat of model>-<repeat of serial number> 	FW950.40 (UM950_096)
		Update Access Key Exp Date (YYYY-MM-DD): 2050-12-31
``` 
And the body 
```
 Welcome

Machine type-model: xxxxx
Serial number: xxx
Date: 2022-3-22
Time: 17:16:08 UTC
Service Processor: Primary (Location: U78D4.ND1.CSS0FFW-P1-C1)
```

Not sure if all of that is needed..

**Comment by aahmed-2** [comment]
Downstream PR: https://github.com/ibm-openbmc/bmcweb/pull/305

**Comment by mzipse** [comment]
Work is complete.  Closing.
