### ISSUE TITLE
Rainier/Everest - Update floor config with "IPS active" floors

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3485]
Need to confirm with thermal team on each system's use of this "IPS active" state in regard to adjusting fan floors (may need to reference use of this on prior generation systems).
```
On 0->1 transition of Active bit:
Ø BMC will check if fan floor needs to be updated due to IPS active.  This can only be done if all IPS parameters are set to their default.

On 1->0 transition of Active bit:
Ø BMC will check if fan floor needs to change due to IPS no longer active
```

**Comment by msbarth** [comment]
```
IPS active takes precedence over the set power management mode (Max Performance, static....) and the fan floor for IPS is used when we have actively entered into IPS "active".  When we exit IPS "active" then the fan floor goes back to whatever is required for the power management mode.
```
After looking at prior use of IPS, there doesnt appear to be lower floors for IPS vs the other power modes. Will need to confirm the use/need for this as another floor within fan control's config after exposed onto dbus by the OCC control app.

**Comment by msbarth** [comment]
This depends on getting the "IPS Active" sensors exposed onto dbus by @baileysh

**Comment by rfrandse** [comment]
tracking in jira
