### ISSUE TITLE
PFP::control::actions::mapped_floor - Implement a "deadband" area when transitioning between keys

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3486]
The floor action used on witherspoon had a transitioning "deadband" between ambient temps which needs to be pulled forward into the `mapped_floor` action now to prevent oscillating between choosing floors when a ambient hovers between keys.

**Comment by msbarth** [comment]
One option to have a "deadband" is to wait until the key transitions by a configured minimum (<= 1.0) before transitioning to the next key. This would then keep the mapped floor from transitioning to quickly based on how often the key's value is updated on dbus. (i.e. a key could be updated ever 0.001 value on dbus, but maybe this mapped floor action for fan control should only wait until the key value changes by a full digit, 1.0).

**Comment by msbarth** [comment]
For IBM's configuration, its possible that the `Fan floors` event could be updated to utilize a timer trigger in place of the signal triggers for the ambient group where it would preload the ambient group ever X seconds and run the mapped_floor action. Any change in parameters would still trigger the mapped_floor action to run.
i.e.)
```
"name": "Fan floors",
     "groups": [
      {
        "name": "ambient temp",
        "interface": "xyz.openbmc_project.Sensor.Value",
        "property": { "name": "Value" }
      }
     ],
     "triggers": [
       {
         "class": "init",
         "method": "get_properties"
       },
       {
         // Refresh ambient and run actions every 1sec
         "class": "timer",
         "type": "repeating",
         "interval": 1000000,
         "preload_groups": true
       },
       {
         "class": "parameter",
         "parameter": "pcie_floor_index"
       },
       {
         "class": "parameter",
         "parameter": "ambient_20_altitude_offset"
       },
       {
         "class": "parameter",
         "parameter": "ambient_25_altitude_offset"
       },
       {
         "class": "parameter",
         "parameter": "ambient_30_altitude_offset"
       },
       {
         "class": "parameter",
         "parameter": "ambient_35_altitude_offset"
       },
       {
         "class": "parameter",
         "parameter": "ambient_40_altitude_offset"
       }
     ]
     .
     .
     .
```

**Comment by spinler** [comment]
WIP commits up at https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/52564

**Comment by rfrandse** [comment]
tracking in jira
