### ISSUE TITLE
Fix user patching invalid duplicate values 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3494]
if a user PATCHes ["1.1.1.1", "1.1.1.1"]
that's invalid
we shouldn't just silently fix it for them

Should return probably a 
```
        "PropertyDuplicate": {
            "Description": "Indicates that a duplicate property was included in the request body.",`
```

https://redfish.dmtf.org/registries/Base.1.12.1.json

**Comment by rfrandse** [comment]
tracking in jira
