### ISSUE TITLE
Redfish::Fan - Add `HotPluggable` attribute to fans

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3495]
Need to reflect the `HotPluggable` state related to each fan within a system:

- [ ] Investigate where a dbus property should exist to show `HotPluggable` state per fan
- [ ] Update dbus interface with property for `HotPluggable` state
- [ ] Populate `HotPluggable` state (thru a fan app? how to configure? or other app?)
- [ ] Check Redfish correctly returns `HotPluggable` state on fan objects

**Comment by msbarth** [comment]
For reference: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/51320

**Comment by rfrandse** [comment]
tracking in jira
