### ISSUE TITLE
Power supplies are hot pluggable - update D-Bus

### ISSUE THREAD

**Issue by bjwyman** [ibm-openbmc/dev#3496]
The IBM power supplies are hot pluggable. They can be removed while the system is powered up, in order to be replaced.

It is a bit unclear if one considers this as also concurrently maintainable, since usually one associates a need to power off the device/FRU in order to replace it.

References:
`yaml/xyz/openbmc_project/Inventory/Item/PCIeSlot.interface.yaml`

`yaml/xyz/openbmc_project/Inventory/Decorator/Replaceable.interface.yaml`

https://github.com/openbmc/phosphor-dbus-interfaces

**Comment by bjwyman** [comment]
NOTE: This should end up very similar to fan HotPluggable attribute: https://github.com/ibm-openbmc/dev/issues/3495.

Plan is to work out details for that attribute, and re-use it for the power supplies.

**Comment by rfrandse** [comment]
tracking in jira
