### ISSUE TITLE
Design and implement PDR storage for an Effecter

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#350]
Implement this as per DSP0248.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
The design/tasks below talks specifically about the state effecter PDR, but the same applies mostly to any other PDR type as well

- [ ] libpldm : define a C structure for the common PDR header format
- [ ] libpldm : define a C structure for state effecter PDR
	- [ ] The last field of information is variable, use the single byte payload trick
- [ ] libpldm : encode/decode APIs for GetPDR
- [ ] GetPDR command
	- Based on the platform specific data (see below) and the PDR C struct, create a list of (PDR record handle, PDR buffer, PDR buffer length ) tuples
	- [ ] Assign a unique id to each PDR
	- [ ] Have type specific PDRs in separate lists
	- [ ] Open Item : should the PDRs always be in memory (the keep it simple option)?
- [ ] Platform specific PDR creation
	- [ ] Have JSON files in PDR type specific locations named by tye (eg /var/lib/pldm/pdrs/state_effecter_pdr)
	- [ ] Have the following info in the json as a list to depict the list of state effecter pdrs : 
		effecter id
		entity type
		entity instance
		container id
		possibleStates (state set id, size, list of supported states)
		D-Bus object corresponding to effecter id (future - d-bus interface and match criteria)
	- [ ] Load json into a c++ datastructure - have a map per PDR type, effecter id is the key, everything else are values
- [ ] PLDM State set to D-Bus mapping (can’t be in the JSON because types need to be known at compile time)
	- Assumption : PLDM state set maps to a single D-Bus interface. Effecter id maps to D-Bus object
	- [ ] Have a stateToDBus map of uint32 (PLDM state set id bitwise OR state value) to lambda. Lambda takes in an object path and a uint16 state value and makes a D-Bus call to set a property.
	- [ ] setEffecter routing : lookup state effecter JSON map and pull out pldm state set and enum value. Bitwise OR them. Also pull out D-Bus object.  Lookup stateToDbusMap based on OR result and invoke the lambda, passing in d-bus object and uint16 state value
- [ ] FindPDR command - optional, but more efficient than GetPDR, TBD

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/21446/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/21446 merged
