### ISSUE TITLE
LED::Fan - Setup/Verify `Identify` LED path to blink amber LED

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3502]
The fan `Identify` LED path is not working to blink the amber LED on the fan enclosures. Need to setup/verify what's needed to enable this on fans with expose amber LEDs (does Rainier 2U have an LED on chassis since fans are inside?).

**Comment by msbarth** [comment]
Verified 4U blowers have a green and amber LED on the physical blower and the amber blinks when the "Identify" toggle is turned on in the GUI (BMC level -38.9)

**Comment by msbarth** [comment]
Dont foresee this being an issue with 2U or Everest unless its config related, so only need to test on these systems to verify the amber LED of each fan blinks when the "Identity" toggle is turned on in the GUI.

**Comment by spinler** [comment]
Going to assume this has been done.  Closing.
