### ISSUE TITLE
One time boot options are removed from the GUI so the alert message needs to be removed. 

### ISSUE THREAD

**Issue by sandeepasingh116** [ibm-openbmc/dev#3503]
## Expected Behavior
One time boot options are removed from the GUI so the alert message needs to be removed.

 Best Quest Link: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW544037
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications
  - Browser: 
  - Version:

**Comment by sandeepasingh116** [comment]
Resolved by : https://github.ibm.com/openbmc/webui-vue/pull/69

**Comment by mzipse** [comment]
Work is complete.  Closing.
