### ISSUE TITLE
GUI: FED: Bug: Power page defects

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3506]
### Idle power save
- [ ] [SW544233](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW544233) - FTC1020:Rainier:GUI: Unable to provide different values for enter and exit for Utilization threshold *WIP on backend*
- [ ] Add info icon for ExitUtilizationPercent  with following text: 
  - When the IdlePowerSaver ExitUtilizationPercent is set to 0, the factory default Idle Power Saver parameters will be restored and used.
  -    `curl -k -X PATCH -d '{"IdlePowerSaver":{"ExitUtilizationPercent":0}}' ` this will reset idle pwer to default parameters
- [x] [SW543100](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW543100) : HST:STC1020:Rainier:rain505 - System power mode change doesn't work via BMC GUI
- [X] [link](https://github.ibm.com/openbmc/webui-vue/pull/83) Update Power saver modes descriptions

**Comment by kennyneedsmilky** [comment]
[SW543421](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW543421) : FTC1020:Rainier: GUI: Displaying OemIBMServiceAgent in Group Privilege

Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/76

**Comment by ghost** [comment]
[SW543100](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW543100) : HST:STC1020:Rainier:rain505 - System power mode change doesn't work via BMC GUI

Power cap settings
Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/82

Power saver modes
Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/47

Idle power saver
Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/34
@Srisuk

**Comment by ghost** [comment]
[link](https://github.ibm.com/openbmc/webui-vue/pull/83) Update Power saver modes descriptions

Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/83

**Comment by dixsie** [comment]
moving to GHE  tracker
