### ISSUE TITLE
GUI : FED : Event logs add missing information

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#3507]
## SME
@spinler 

### Overview
Need to add missing info to expanded row details  on Event  logs.

![Screen Shot 2022-02-24 at 11.42.40 AM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/578fd484-cca2-4ff9-a911-8d8276cd7338)

### Acceptance Criteria
- [x] add definition list for `EventID`
- [x] add dl for `Resolution` need to format text redfish response value ( add new line after `\n`) 
- [x] add section divider

### cURL Commands and Redfish Response

```
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/11313",
      "@odata.type": "#LogEntry.v1_9_0.LogEntry",
      "AdditionalDataURI": "/redfish/v1/Systems/system/LogServices/EventLog/Entries/11313/attachment",
      "Created": "2022-02-24T14:47:49+00:00",
      "EntryType": "Event",
      "EventId": "BD752004 00000055 2E2D0010 00000000 00000000 00000000 00000000 00000000 00000000",
      "Id": "11313",
      "Message": "BD752004 event in subsystem: Not Applicable",
      "Modified": "2022-02-24T14:47:49+00:00",
      "Name": "System Event Log Entry",
      "Oem": {
        "OpenBMC": {
          "@odata.type": "#OemLogEntry.v1_0_0.LogEntry",
          "ManagementSystemAck": false
        }
      },
      "Resolution": "1. Priority: High, Procedure: BMC0001\n",
      "Resolved": false,
      "ServiceProviderNotified": true,
      "Severity": "Critical"
    },
```

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by Nikhil-Ashoka** [comment]
Resolved by: https://github.ibm.com/openbmc/webui-vue/pull/111
