### ISSUE TITLE
GUI: FED: Bug: Sensors page defects

### ISSUE THREAD

**Issue by ghost** [ibm-openbmc/dev#3510]
- [x] [SW535672](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW535672) : FTC1020:Rainier:GUI: Sensor information are not getting displayed in Sensor page

**Comment by ghost** [comment]
SW535672 : FTC1020:Rainier:GUI: Sensor information are not getting displayed in Sensor page

Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/77

**Comment by dixsie** [comment]
moving to GHE
