### ISSUE TITLE
GUI : FED : Bug: Security and Access page defects

### ISSUE THREAD

**Issue by ghost** [ibm-openbmc/dev#3511]
- [x] [SW543421](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW543421) : FTC1020:Rainier: GUI: Displaying OemIBMServiceAgent in Group Privilege 

- [ ] [SW542643](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW542643) : FTC1020:Rainier:GUI session logs out upon trying to disconnect the stale HMC connection.

- [x] [SW541853](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW541853) : FTC1020:Everest:GUI: ever57bmc.isst Need indication of a user creation fail for too weak of a password

**Comment by ghost** [comment]
[SW543421](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW543421) : FTC1020:Rainier: GUI: Displaying OemIBMServiceAgent in Group Privilege

Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/76

**Comment by ghost** [comment]
[SW541853](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW541853) : FTC1020:Everest:GUI: ever57bmc.isst Need indication of a user creation fail for too weak of a password

Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/81

**Comment by dixsie** [comment]
moving to GHE
