### ISSUE TITLE
GUI : FED : Bug: Logs page defects

### ISSUE THREAD

**Issue by ghost** [ibm-openbmc/dev#3512]
- [x] [SW536647](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW536647) : FTC1020:Rainier:System dump : BMC GUI : GUI gives a message saying dump will be offloaded to OS , even though system is connected to HMC
- [x] [SW539054](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW539054) : FTC1020:Rainier: GUI : Appropriate error message not displayed in BMC GUI upon trying to trigger system dump at wrong system state

**Comment by ghost** [comment]
[SW536647](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW536647) : FTC1020:Rainier:System dump : BMC GUI : GUI gives a message saying dump will be offloaded to OS , even though system is connected to HMC

Resolved By: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW536647

**Comment by ghost** [comment]
[SW539054](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW539054) : FTC1020:Rainier: GUI : Appropriate error message not displayed in BMC GUI upon trying to trigger system dump at wrong system state

Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/80

**Comment by dixsie** [comment]
Moving to Status board
