### ISSUE TITLE
GUI: FED: Bug: Profile settings page defects

### ISSUE THREAD

**Issue by ghost** [ibm-openbmc/dev#3516]
- [x] [SW529065](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW529065) : FW1020:Rainier: GUI allows user to attempt service user password modification

**Comment by ghost** [comment]
[SW529065](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW529065) : FW1020:Rainier: GUI allows user to attempt service user password modification

Resolved By: https://github.ibm.com/openbmc/webui-vue/pull/88

**Comment by dixsie** [comment]
moving issue to GHE
