### ISSUE TITLE
PFP::control::actions: Use event name in action's unique instance name

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3522]
Currently an incremented instance number is concatenated to each instance of an action to create a uniquely identifiable name for that action's instance. It would be more beneficial to instead concatenate the event's name (which is forced to be unique) to the action name.

Since an event could technically be configured to call the same action more than once, keeping the instance number attached to the unique name is recommended but maybe another enhancement exists here to ensure that the action instance unique name stays unique within the event since there could be more than one instance of the action within the same event.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/52719

Examples:
```
 "floor_holds": {
      "count_state_floor-4(Non-active OCCs)": 18000,
      "mapped_floor-64(Fan floors)": 11200
  }
```
