### ISSUE TITLE
PFP::control::actions: Update actions that have other actions as input support the same configuration options an action does on an event

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3523]
There are actions (i.e. `TimerBasedActions::setActions`-> https://github.com/openbmc/phosphor-fan-presence/blob/master/control/json/actions/timer_based_actions.cpp#L184) that take actions in their configuration input which should support the same configuration options that can be provided when an action is configured on an event. These configuration options include the use of "profiles" and setting what zones the action should run against.

For reference, these actions should have the same json configuration support as `Event::setActions`->https://github.com/openbmc/phosphor-fan-presence/blob/master/control/json/event.cpp#L174 does.

This issue is not all inclusive, and all currently supported actions should be updated if they support taking a list of actions in as input to their configuration.

**Comment by spinler** [comment]
If there is an explicit action that needs this I will revisit, but closing for now.
