### ISSUE TITLE
Rainier/Everest: Configure fan override action

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#3524]
Need to add the configuration as outlined in #3076 so that when a rotor fails within a dual rotor fan, the other rotor is locked at these system's full speed value (aka `poweron_target` from zones.json of each system).

**Comment by spinler** [comment]
Asking the thermal team if this is needed and what values to use if it is.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc.org/c/openbmc/phosphor-fan-presence/+/52276
