### ISSUE TITLE
Restrict Redfish/REST APIs to the service user

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#3525]
This story is to restrict certain BMCWeb Redfish and REST APIs so only the service user is allowed to use them.  For example:
- /redfish/v1/Systems/system/LogServices/EventLog/** -- see below
- /redfish/v1/Systems/system/LogServices/CELog/** -- see below
- the API to allow the service user to login to theBMC command shell

One way to enforce that is for the operation to require the new OemIBMPerformService privilege.  Only the special "service" user will have the OemIBMServiceAgent Role, and only the OemIBMServiceAgent Role has the OemIBMPerformService privilege.

Test:
Login as a user with the Administrator role, and ensure you are not allowed to perform the operations.
Login as the special "service" user, and ensure you are allowed to perform the operations.

**Comment by gtmills** [comment]
It was decided not to restrict CELog.
From a Aug 25, 2021 email after this was discussed in a meeting 

```
Current BMC design POR
1. There are 4 login profiles:  CE, Sys  Admin, Operator, Read only.
2.  All profiles can retrieve all logs.
3.  HMC uses Sys Admin, so we cannot restrict the hidden/info logs to only CE login.  HMC needs to get all logs.
4.  All profiles can display non-hidden/non-info logs on the GUI.
5.  Only CE login can display hidden and info logs on the GUI.
```

**Comment by gtmills** [comment]
And /redfish/v1/Systems/system/LogServices/EventLog/** should not be restricted either

**Comment by joseph-reynolds** [comment]
The appropriate operations now require service privilege.  Closing this issue.
