### ISSUE TITLE
GUI: FED: Bug: QuiesceOnError and Manual mode should not be coupled 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3527]
## Expected Behavior
QuiesceOnError and Manual mode should not be coupled 
When setting Manual mode it should not adjust QuiesceOnError.

## Actual Behavior
Setting Manual Mode sets QuiesceOnError 

```
Andrew Geissler
yep, completely decouple it
```

https://ibm-systems-power.slack.com/archives/G3WAVQYTH/p1647535411586139?thread_ts=1647451541.496879&cid=G3WAVQYTH

**Comment by sandeepasingh116** [comment]
@gtmills I m unable to open the above link, can you tag me in the slack thread?

**Comment by gtmills** [comment]
@sandeepasingh116 I think this is done. Can we close?
