### ISSUE TITLE
GUI : FED : Add "Dump in progress; dump will be lost if server is power off" when Dump is in progress

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3528]
## SME
**BMC**: @geissonator 

### Overview

If the user were to power off the system when a dump is happening the dump is lost. 
There is going to be a Bios Attribute to allow the HMC and the GUI to know a Dump is in progress. 
On the Server Power Operations page need to warn the user a power off will result in the dump being lost. 
Either a message on the screen before a reboot or power off is clicked or an warning when reboot or power off is clicked. 

The user could still ignore this warning on power off.

**Comment by gtmills** [comment]
This is ready for GUI development. The bios attribute value is pvm_sys_dump_active

**Comment by gtmills** [comment]
@sandeepasingh116 I think this can be closed?

**Comment by sandeepasingh116** [comment]
> @sandeepasingh116 I think this can be closed?

Yes closing it. thanks !
