### ISSUE TITLE
PCIe Topology: Redfish: Cable links 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3533]
Cable need downstream/upstream port 
Downstream resource, upstream resource, downstream chassis  
https://github.ibm.com/gmills/pcie-topology

Code will go here: https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/cable.hpp

https://github.ibm.com/openbmc/openbmc/pull/2264 is the resource upstream and downstream and port upstream and downstream

https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/55/files defines the upstream and downstream chassis

**Comment by patelabhishek9893** [comment]
downstream commit 
https://github.com/ibm-openbmc/bmcweb/pull/338

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/338 merged

**Comment by mzipse** [comment]
Work is complete.  Closing.
