### ISSUE TITLE
PCIe Topology: Redfish: Link Properties like LinkId, Link Width, Link Speed

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3537]
LinkId, Link Width, Link Speed

**Comment by gtmills** [comment]
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1650400200647849?thread_ts=1650399924.109139&cid=C0Q6TQP5Z

**Comment by aahmed-2** [comment]
Dbus interfaces: 

https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/50/files
https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/49

**Comment by gtmills** [comment]
The D-Bus interfaces merged

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/348 is the PR

**Comment by mzipse** [comment]
refresh

**Comment by mzipse** [comment]
Work is complete.  Closing.
