### ISSUE TITLE
Event Log: Redfish: OEM for full PEL 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3538]
Place holder for some Oem Additional Data URI which will contain the Full PEL.
This will be a 2nd Oem Additional Data URI.
OemAdditionalDataPel is a possible property name

A possible path might be something like:
/redfish/v1/Systems/system/LogServices/EventLog/Entries/1/OemPelAttachment

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/52275

**Comment by mzipse** [comment]
Work is complete.  Closing.
