### ISSUE TITLE
Certificates:  Infrastructure code support redfish schema 2018.3

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#354]
Add required support for enabling new Redfish schemas.

**Comment by dkodihal** [comment]
This is to support certificate upload.

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Design flow:
Uploading a  pre-generated certificate:
bmcweb:  
  - The User navigates to the appropriate certificate collection.
         Example: for uploading HTTPS server certificate:
                     URI:  /redfish/v1/Managers/{ManagerId}/NetworkProtocol/HTTPS/Certificates
   - The user performs a POST on the Certificate with the certificate ( includes Private key) string in the body.
   - copies the certificate and private key file to a temporary location.
   - bmcweb should maintain a map to call the the target DBus application (Certs) object.
   	- Design point is to maintain same blackened structure for both redfish/rest.  
 	  Example:  /redfish/v1/Managers/{ManagerId}/NetworkProtocol/HTTPS/Certificates to /xyz/	openbmc_project/certs/server/https.
  - call the certificate application instance install method.

phosphor-certificate-manager.
   - Validate the certificate
   - Increment the certificate counter. 
   - copy the the input file into service specific path .
        - rename the certificate with file_name with certificate counter. ( Only required for multiple certificate files)
   	 - create  certificate d-bus object ( <base path>/<id> and store into service specific d-bus list.
   - Follow the error handling same as existing way.

Implementation of certificate location:
    - bmcweb should get the all supported service specific list and create the url based on redfish spec.

Viewing certificate properties 
   - use the certificate interface properties for this 
         - date format is epoch time , some code changes required in bmcweb to convert this into redfish way.

Updating Certificate:
   - use #CertificateService.ReplaceCertificate  action in certificate service to replace this.
   	- bmcweb should call the certificate string property update.
        - certificate manager Should validating the certificate and update d-bus properties.with new value.
        		- Note : no id change.

Service start time:
   - each service should create d-bus certificate d-bus objects based available files the certificate path.
          - open item d-bus id should be investigated. ( this is required only for multiple certificate file supported service)

Deletion of certificate. 
   - Redfish doesn’t support delete. need to discuss rest use case.
   - Assumption: any run time self signed certificate creation should be controlled by certificate manager.
         - Need change in ldap/nginx.

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-certificate-manager/+/17918/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by devenrao** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-certificate-manager/+/18861/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
