### ISSUE TITLE
Unable to configure SNMP managers with fully qualified domain name or hostname

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3540]
As SW539991 states, still seeing 
```
curl -k -H "X-Auth-Token: $bmc_token" -D post.txt -X POST https://${bmc}/redfish/v1/EventService/Subscriptions   -d '{"Destination": "snmp://snmp.prashanth.com:162", "SubscriptionType": "SNMPTrap", "Protocol": "SNMPv2c"}'
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_1_1.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.8.1.InternalError",
        "MessageSeverity": "Critical",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service."
      }
    ],
    "code": "Base.1.8.1.InternalError",
    "message": "The request failed due to an internal service error.  The service is still operational."
  }
}
```
return an InternalError using https://github.com/ibm-openbmc/bmcweb

**Comment by ChicagoDuan** [comment]
Hi @gtmills ,  What is the commitID of the phosphor-snmp you use?  I have fixed this issue here:https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-snmp/+/49289 .  Can you post more information? Thanks.

**Comment by gtmills** [comment]
We are using https://github.com/ibm-openbmc/phosphor-snmp/commits/1020. Which has your commit @ChicagoDuan

**Comment by gtmills** [comment]
From our recipe:
```
SRC_URI += "git://github.com/ibm-openbmc/phosphor-snmp;nobranch=1"
SRCREV = "46bba731d0d24989b97a4d7ef6757cf069b2c221"
```

**Comment by gtmills** [comment]
@prkatti1 Anymore detail to help @ChicagoDuan ?

**Comment by prkatti1** [comment]
SNMP configuration with IP address via redfish works
SNMP configuration with IP address via GUI works

SNMP configuration with FQDN address via redfish used to work, but not working from yesterday build.
SNMP configuration with FQDN address via GUI does not work. Did not work earlier also.

**Comment by mzipse** [comment]
@ChicagoDuan , the GUI part, you don't need to worry about.  We think we have that fixed.  But if you can help us figure out what's going on with the "SNMP configuration with FQDN address via redfish used to work, but not working from yesterday build." , we would really appreciate it.  The bmcweb code we are using in our drivers is here... https://github.com/ibm-openbmc/bmcweb/commits/1020 as of April 1st.

**Comment by ChicagoDuan** [comment]
Hi @mzipse @gtmills @prkatti1 
I did some tests and it worked well on my machine. The bmcweb I use is  https://github.com/ibm-openbmc/bmcweb/commits/1020 . commit id: 7edde88e6de8847fb53be0ce36adf48c1000002f (Commits on Apr 1).
```
curl -k -H "X-Auth-Token: $token" -X POST   https://${bmc}/redfish/v1/EventService/Subscriptions   -d '{"Destination": "snmp://snmp.prashanth.com:162", "SubscriptionType": "SNMPTrap", "Protocol": "SNMPv2c"}'
{
  "@Message.ExtendedInfo": [
    {
      "@odata.type": "#Message.v1_1_1.Message",
      "Message": "The resource has been created successfully",
      "MessageArgs": [],
      "MessageId": "Base.1.8.1.Created",
      "MessageSeverity": "OK",
      "Resolution": "None"
    }
  ]
}
```
Can you help with the following tests?
1. Can you see some error logs using `journalctl` ？
2. Test whether the snmptrap client can be created using busctl:
    `busctl call xyz.openbmc_project.Network.SNMP /xyz/openbmc_project/network/snmp/manager xyz.openbmc_project.Network.Client.Create Client sq "snmp.prashanth.com" 162`

**Comment by prkatti1** [comment]
@ChicagoDuan yep, it worked for us in today's build.
Now it is GUI only issue.

**Comment by ChicagoDuan** [comment]
> @ChicagoDuan yep, it worked for us in today's build. Now it is GUI only issue.

Okay, please let me know after you fix the GUI issue. I will close this issue page.

**Comment by mzipse** [comment]
@prkatti1 , I see your comment in the defect indicating that you tested on the 51.2.  Something is not making sense.  The GUI fix was in the 50.3 BMC level.  @sandeepasingh116 just removed the enforcement to allow the fully qualified name to get passed to the  Redfish API.  Can you show Sandeepa on your system tommorrow.....perhaps she can debug it directly on your machine.

**Comment by ChicagoDuan** [comment]
By the way, When there is no DNS IP address in BMC, checking the hostname by accessing the DNS server will throw an error, so the redfish will return a internal error.

**Comment by prkatti1** [comment]
Ok, but that should not fail during configuration.
That can fail during address resolution or while sending trap.

**Comment by lxwinspur** [comment]
@prkatti1 Could we discuss this issue on discord? and your discord Id is @Prashanth#8294 right?
@ChicagoDuan , please ping him on discord.

**Comment by ChicagoDuan** [comment]
> Ok, but that should not fail during configuration. 

No. it will fail during configuration.  When we use hostname to creat a snmptrap client, the phosphor-snmp will check the hostname by accessing the DNS server: https://github.com/openbmc/phosphor-snmp/blob/master/snmp_util.cpp#L54-L73

**Comment by prkatti1** [comment]
Ideally phosphor SNMP manager should contact DNS server while sending trap. Configuration doesn't send trap or connection or any packets so doesn't make much sense to contact DNS server during configuration.

**Comment by ChicagoDuan** [comment]
> Ideally phosphor SNMP manager should contact DNS server while sending trap. Configuration doesn't send trap or connection or any packets so doesn't make much sense to contact DNS server during configuration.

Yes, I agree with you. But you'd better talk to the maintainer of phosphor-snmp.

**Comment by gtmills** [comment]
>>     Ideally phosphor SNMP manager should contact DNS server while sending trap. Configuration doesn't send trap or connection or any packets so doesn't make much sense to contact DNS server during configuration.

> Yes, I agree with you. But you'd better talk to the maintainer of phosphor-snmp.

Can we open an issue in phosphor-snmp ?

**Comment by ChicagoDuan** [comment]
I want to know the latest status of this bug "Unable to configure SNMP managers with fully qualified domain name or hostname#3540". I see from @prkatti1 's comment that it has been solved. Can you update the latest status?

**Comment by ChicagoDuan** [comment]
> > > ```
> > > Ideally phosphor SNMP manager should contact DNS server while sending trap. Configuration doesn't send trap or connection or any packets so doesn't make much sense to contact DNS server during configuration.
> > > ```
> 
> > Yes, I agree with you. But you'd better talk to the maintainer of phosphor-snmp.
> 
> Can we open an issue in phosphor-snmp ?

Hi @ratagupt  What do you think of  @prkatti1 's comment? https://github.com/ibm-openbmc/dev/issues/3540#issuecomment-1092400342

**Comment by lxwinspur** [comment]
@gtmills @mzipse 
Could we close this issue?

**Comment by mzipse** [comment]
We can mark this Code Review in Driver.  All is working downstream.  Did the code get merged upstream?

**Comment by ChicagoDuan** [comment]
> Did the code get merged upstream?

Not merged : https://gerrit.openbmc.org/c/openbmc/bmcweb/+/38599/44

**Comment by mzipse** [comment]
ok.  We'll leave this open until we get the commit upstreamed.

**Comment by mzipse** [comment]
Adding an extra label.  This is a test.  Please disregard.

**Comment by gtmills** [comment]
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/38599/44 is merging. Is there anything left we need to do here? Does what merged upstream handle the SNMP managers with fully qualified domain name or hostname ? @ChicagoDuan

**Comment by gtmills** [comment]
@ChicagoDuan @lxwinspur @prkatti1 I closed. Please reopen if there is still anything here
