### ISSUE TITLE
bmcweb: AccountType on Post support

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3542]
Need support for AccountType on Post 
https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/account_service.hpp#L1994

https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1649353788101469?thread_ts=1649268527.377349&cid=C0Q6TQP5Z

**Comment by joseph-reynolds** [comment]
Note the Redfish AccountTypes property corresponds to the [phosphor user management group roles](https://github.com/openbmc/docs/blob/master/architecture/user-management.md#supported-group-roles) which controls which interfaces a user is allowed to use (ssh, ipmi, redfish, and web).

Currently the Redfish API to create a new user (via `POST /redfish/v1/AccountService/Accounts/`) does not accept the AccountType property.  Instead this API reads the phosphor user manager D-Bus AllGroups property, and uses that.

What should the new behavior be?
1. For the OpenBMC community, the default (when the AccountTypes property is omitted) should be to continue with the existing behavior (reading the AllGroups property).
2. For IBM p10bmc systems (which have IPMI disabled by default), the default should be to read the AllGroups property and remove the "ipmi" value.  Perhaps we could have a "IPMI disabled by default" built-time flag.  Also for IBM p10bmc systems, the "ssh" account type should only be provided by default for role=Administrator accounts. 
3. If the AccountTypes property is specified, then use that.

**Comment by rfrandse** [comment]
tracking in jira
