### ISSUE TITLE
Add support for redfish PowerSubsystem wattages

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#3543]
This is basically a child of https://github.com/ibm-openbmc/dev/issues/1709, view that and https://github.com/ibm-openbmc/dev/issues/2792 and https://github.com/ibm-openbmc/dev/issues/2795 for background info.  

Fill out fields (for PowerSubsystem):

- "CapacityWatts" = PS output * #ofPS (just at boot time, don't change based on hotplug) (output wattage value TBD)
- "RequestedWatts" = .MaxPowerCapValue (xyz.openbmc_project.Control.Power.Cap interface)
- "AllocatedWatts" = .PowerCapValue if .PowerCapEnable is true, .MaxPowerCapValue if false (xyz.openbmc_project.Control.Power.Cap interface)

- Investigate if straightforward to do rollup of individual "Health" and "State" for those fields, if not, then we'll add in some later release.

Fill out fields (for PowerSupply)

- "PowerCapacityWatts" = PS output for this PS, as determined above.

See mockups in comments below.

**Comment by derekhoward55** [comment]
Mockup
![image](https://user-images.githubusercontent.com/22683949/162274104-9fd86225-c1cd-4f53-9ddb-cfcd4be6a769.png)
...
![image](https://user-images.githubusercontent.com/22683949/162274221-5bcfe636-9f56-44b2-a404-a2eef89baa5d.png)

**Comment by smccarney** [comment]
Support for the RequestedWatts and AllocatedWatts properties is implemented in the following PR
* https://github.com/ibm-openbmc/bmcweb/pull/334

**Comment by rfrandse** [comment]
tracking in jira
