### ISSUE TITLE
Expand Query parameter sensor collection optimization  

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3544]
The GUI has a page for all the sensors, with https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/52272/31 merging it would good to look at any optimization we can do for `/redfish/v1/Chassis/chassis/Sensors?\$expand\=.\(\$levels\=1\`. 

This should up upstream.

Possible optimization: 

A special if for the expand query parameter and having bmcweb get all the sensors in one call and use that to populate each of the sensors
D-Bus cacheing 

@lxwinspur FYI

**Comment by zhanghch05** [comment]
Ed has merged this patchset.
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/52418
Can this issue be closed?
