### ISSUE TITLE
VMI IPv6 Redfish interface implementation

### ISSUE THREAD

**Issue by sunharis** [ibm-openbmc/dev#3549]
Implement the bmcweb component changes for supporting VMI IPv6 network configuration. Required schema is available from DMTF

**Comment by mzipse** [comment]
Refresh

**Comment by sunharis** [comment]
Upstream commit at : https://gerrit.openbmc.org/c/openbmc/bmcweb/+/54109

**Comment by sunharis** [comment]
Migrate-Yes

**Comment by rfrandse** [comment]
tracking in jira
