### ISSUE TITLE
PCIe Topology: Redfish: Reset Link

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3551]
See conversation here: 
https://ibm-systems-power.slack.com/archives/C02LD8E1F18/p1650384784018809?thread_ts=1650380328.037139&cid=C02LD8E1F18

D-Bus property defined here: https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/53/files

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/bmcweb/pull/352 is the PR

**Comment by mzipse** [comment]
Work is complete.  Closing.
