### ISSUE TITLE
BMC pass up PSU config in HTMGT poll at boot time

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#3555]
The BMC will pass up the ps configuration to HTMGT in it's poll, and HTMGT will get the correlated bulk power limit from the MRW HB attributes and send to the OCC.  Update poll response format.

PS types, input type, etc can only change at standby, so HTMGT can just check at boot what the configuration is.  Losses of PS function only realized by the oversubscription line.

**Comment by rfrandse** [comment]
tracking in jira
