### ISSUE TITLE
PSU EM config updates and determination for mfg

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#3556]
1s4u supports either 2+2, or 1+1 “limited configs” with 1000W ps.  Therefore need to change the design to allow the same ps to be in either 1+1 or 2+2 config.  

Also need to change design to know whether system is supposed to be a 1+1 or 2+2 configuration, so we log the ps missing errors correctly, and use the correct power caps (both standard and in oversubscription).  Systems will have same IM, and same MTM.  Have mfg update system vpd - stored in bmc and backplane.

**Comment by rfrandse** [comment]
tracking in jira
