### ISSUE TITLE
phosphor-logging: org.open_power.PHAL.Error.HostRunning error should be cec_sp_hyp_iface subsystem

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3557]
This error is actually an indication of a failure between the BMC and PHYP subsystem. 

Need to change: https://grok.openbmc.org/xref/openbmc/phosphor-logging/extensions/openpower-pels/registry/message_registry.json?r=d29837f8#531

to cec_sp_hyp_iface subsystem.

**Comment by geissonator** [comment]
High level steps for this:
- Checkout phosphor-logging from gerrit (scp the git hooks per gerrit setup doc)
- Make a dev branch - git checkout -b fix-phal-subsystem
- Make change to file documented above
- Run the unit test docker script against your repo to ensure it builds
- git add <file you changed>
- git commit --signoff
- push your change to gerrit

**Comment by NodeMan97** [comment]
Done and pushed to Gerrit!

**Comment by geissonator** [comment]
oops, be sure to not close these out until the change has been merged into both gerrit and GHE.

Change up at https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/53420

**Comment by NodeMan97** [comment]
https://gerrit.openbmc.org/c/openbmc/phosphor-logging/+/53420
