### ISSUE TITLE
VMI IPv6- Add new Dbus property for IPv6 interface status

### ISSUE THREAD

**Issue by sunharis** [ibm-openbmc/dev#3558]
Phyp has separate attr for IPv4 and IPv6 notification. 
This story is to implement a new Dbus property to hold the active/inactive of IPV6. Interface can go "enabled" if either one of the IPv4 or IPv6 address property is true.

**Comment by sunharis** [comment]
Upstream commit https://gerrit.openbmc.org/c/openbmc/phosphor-networkd/+/53995

**Comment by sunharis** [comment]
Migrate-Yes

**Comment by rfrandse** [comment]
tracking in jira
