### ISSUE TITLE
Capture BMC dumps on fan/ambient shutdowns

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#3559]
It would be good to capture a BMC dump after the system is shut down to do fan or high ambient related changes, after all of  the error logs are created.

I think this would be in:
1. fan-monitor: System::handleOfflineFanController()
2. fan-monitor: the powerOff() functions in power_off_action.hpp
3. fan-monitor: meltdownTimerExpired() in power_off_action.hpp
4. sensor-monitor: timerExpired() in shutdown_alarm_monitor.cpp

An example of code that creates the dump is https://github.com/ibm-openbmc/phosphor-state-manager/blob/1020/utils.cpp#L167

**Comment by mikecgithub** [comment]
Reviewed and merged:

https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/53307
