### ISSUE TITLE
Redfish: Thermal Investigation and Testing

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#356]
This story tracks investigating what is available after Gunnar gets the Chassis fix in. A lot of this function should be in there so this story is about verifying what we have and fixing any issues found. No new DBUS objects should be created, but stories can be opened if they are found to be missing. Also, if a test env is available, some unit tests should be added to test the available function.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
After completing the previous stories, we are now getting basic power and thermal information for Redfish.

With this story, I would like investigate the following:
* Redfish Fan properties in schema vs. information available on DBus
* Redfish Temperature properties in schema vs. information available on DBus.
* How to use associations Matt is providing and what information to obtain.

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
A Google Docs spreadsheet is being used to track this work:
* The first sheet shows all the Redfish Thermal properties. For those currently being set by bmcweb, it also shows the value being returned.
* The second sheet shows DBus properties that are currently used or could be used in the future to set Redfish Thermal properties.
* The third sheet shows the value of relevant Redfish enumerations.

Link to spreadsheet: https://docs.google.com/spreadsheets/d/1bAlM3clyDUWACzyi2qjNwYfI58GYqOx2EjmFVeLf2hI/edit?usp=sharing

The spreadsheet is a work in progress. All the Redfish properties and their current values are included. However, which Redfish properties to begin setting in the future is not yet filled in. Also, there may be additional DBus properties that can be added to sheet 2.

**Comment by smccarney** [comment]
Meeting scheduled for Wed, March 27.  Hoping to decide on which properties to support there.  Will then close this issue and move on to implementation last two issues (Temperatures and Fans).

**Comment by smccarney** [comment]
Held meeting and filled out spreadsheet.  I believe we have a plan for which Thermal properties to support in the short term.
