### ISSUE TITLE
phosphor-state-manager: ensure bmc stays in Quiesce

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3563]
Once the BMC state changes to Quiesced, it needs to stay there until the BMC is rebooted. I keep seeing situations where this is not working:
```
Apr 27 02:24:03 p10bmc systemd[1]: Reached target BMC Quiesce Target.
Apr 27 02:24:03 p10bmc phosphor-bmc-state-manager[519]: BMC has entered BMC_QUIESCED state
Apr 27 02:24:03 p10bmc phosphor-bmc-state-manager[519]: Setting the BMCState field to xyz.openbmc_project.State.BMC.BMCState.Quiesced
...
Apr 27 02:24:31 p10bmc systemd[1]: Reached target Multi-User System.
Apr 27 02:24:31 p10bmc phosphor-bmc-state-manager[519]: BMC_READY
Apr 27 02:24:31 p10bmc phosphor-bmc-state-manager[519]: Setting the BMCState field to xyz.openbmc_project.State.BMC.BMCState.Ready
```

I think in the end we just need a check in https://grok.openbmc.org/xref/openbmc/phosphor-state-manager/bmc_state_manager.cpp?r=71e538fc#193 that says "if BMC is in Quiesced state, return from function" and basically just ignore any other events.

**Comment by NodeMan97** [comment]
Pushed to Gerrit! Currently running into issues with building BitBake. Once figured out I would love to manually test this.

**Comment by geissonator** [comment]
This was pulled into downstream via PR 2333. Keep this issue open until we get the upstream gerrit merged though.

**Comment by NodeMan97** [comment]
Hopefully the changes should be good to get merged. Just documented the manual testing I did.

**Comment by NodeMan97** [comment]
https://gerrit.openbmc.org/c/openbmc/phosphor-state-manager/+/53320
