### ISSUE TITLE
PCIe Topology: Redfish: Cable Status

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3564]
Cable Status 

0x00 = inactive
0x01 = running
0x02 = powered off
0xFF = unknown

Are the values
https://github.com/ibm-openbmc/phosphor-dbus-interfaces/pull/55 is the interface 

D-Bus to Redfish mapping: 

inactive - State == "StandbyOffline"; CableStatus = Normal; Health = Ok
running - State "Enable"; CableStatus = Normal;  Health = Ok
powered offmState == "StandbyOffline" ; CableStatus = Disabled;  Health = Ok
unknown  - Let's leave the health and state off like we will do for link status

**Comment by aahmed-2** [comment]
Available Redfish values for CableStatus: https://redfish.dmtf.org/schemas/v1/Cable.v1_2_0.json

      "CableStatus": {
            "enum": [
                "Normal",
                "Degraded",
                "Failed",
                "Testing",
                "Disabled",
                "SetByService"
            ],

**Comment by aahmed-2** [comment]
PR here: https://github.com/ibm-openbmc/bmcweb/pull/357

**Comment by mzipse** [comment]
refresh

**Comment by mzipse** [comment]
refresh again

**Comment by mzipse** [comment]
Work is complete.  Closing.
