### ISSUE TITLE
Redfish: Upstream support for Redfish PowerSubsystem wattages

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#3568]
In issue #3543, support for several new properties was added to the PowerSubsystem.

This support was only implemented downstream for the following reasons:
* The PowerSubsystem has not merged yet upstream.
* A more general design is probably needed for upstream acceptance:
  * Use associations to find PowerCap interface for the specified chassis
  * Update YAML for PowerCap interface to document the association
  * Update mapper JSON files to create the association
* Lack of available time to perform the additional upstream design/implementation.

This issue is being opened to track the work to move this enhancement upstream.

**Comment by rfrandse** [comment]
tracking in jira
