### ISSUE TITLE
Investigate PEL requirements and staging

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#357]
The PHYP and the outside world want to deal with PEL (Platform Event/(Error? Logging) logs.

Figure out what the real requirements are here, and if any staging needs to be done for bringup.

High Level Questions:
* Does the BMC need to parse PELs it gets from the host?
* Does the BMC code need to natively create PELs?  If so, how?
* Does the BMC need to convert OpenBMC format logs to PELs?
* tons of questions about callouts, user data, etc

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
I consider the investigation done.  We know what we have to do. closing.
