### ISSUE TITLE
PHAL: Did not apply preserved ECO_MODE and HWAS_STATE attributes after the disruptive code update

### ISSUE THREAD

**Issue by RameshIyyar** [ibm-openbmc/dev#3573]
**Background:**

- The openpower-hw-isolation application is used to return the isolated
  (aka guarded) hardware list to the end-user through Redfish via D-Bus.

- BMC needs to display a different name ( i.e. `Cache-Only Core`) for
  the isolated ECO cores so the BMC inventory is modeled with
  a static D-Bus object under each processor.

- Whenever the ECO core is isolated, the openpower-hw-isolation needs to
  create a D-Bus entry that points to the respective BMC inventory D-Bus
  object path through the entry "Associations" property.

  - To achieve that, the op-hw-isolation application relies on
    the ATTR_ECO_MODE attribute that's added in the PHAL device tree
    because currently, the BMC itself won't discover Core ECO mode.

**Problem:**

- Currently, the PHAL device tree did not apply the preserved ATTR_ECO_MODE
  attribute value when the BMC boots after the disruptive code update.

- So, whenever the op-hw-isolation application starts (part of the BMC boot),
  it will restore the hardware isolation records from the persisted partition
  file, and it is not able to create D-Bus entries for the isolated ECO cores
  because failed to find the inventory path.

So, This issue is used to track the required PHAL changes to preserve the ATTR_ECO_MODE attribute in the code update path (includes both disruptive and concurrent code updates).

Similarly, an HWAS_STATE attribute that's used to get a deconfigured reason to display in the Hardware reconfiguration page for the DIMM and Core.

**Comment by RameshIyyar** [comment]
Once addressed this issue needs to remove the below workarounds added in the openpower-hw-isolation. 

- [Core ECO mode](https://github.com/ibm-openbmc/openpower-hw-isolation/commit/9b543d974ee6c9a500e4023c08f67fe6a75daf1e) 
- [Hardware Isolation event](https://github.com/ibm-openbmc/openpower-hw-isolation/commit/b27829f135232ca39898f8ccdfd0fdeb060350d5)

**Note:** Whenever removing a workaround, need to add forward compatibility to remove the unused persisted directory (the workaround would create that in the BMC) in the production system.

For example:

We could add the below code in the `hw_isolation::record::Manager::cleanupPersistedFiles()` function.
```
// Forward compatibility to handle the workaround that added
// for ibm-openbmc/dev/issues/3573 issue.
if (auto path = fs::path(HW_ISOLATION_ENTRY_MGR_PERSIST_PATH).parent_path();
    fs::is_directory(path) && fs::is_empty(path))
{
    fs::remove(path);
}
```

**Comment by rfrandse** [comment]
tracking in jira
