### ISSUE TITLE
GUI : Revisit how we display an Absent FRU 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3574]
## SME
**BMC**: @manojkiraneda @gtmills 
**RAS**: Joe Mulholland, Russ Young
**PHYP**: Adam Stallman

### Summary

Today an absent FRU looks like:
![absent](https://user-images.githubusercontent.com/5455127/168299997-e20fc4b5-3a56-48bf-b793-cc5c7d61a7aa.JPG)

From discussion on 
https://ibm-systems-power.slack.com/archives/C03F0R308J1/p1652364586315499
and defect https://w3.rchland.ibm.com/projects/bestquest/?defect=SW550308 there was concern this isn't clear enough when the FRU is Absent. Should the text be different or an icon when the FRU is absent? 
Should we not display the health (from discussion in that slack channel, we need the health for at least some absent frus).
"Health state" == "Fault indicator state"

**Comment by rfrandse** [comment]
tracking in jira
