### ISSUE TITLE
phosphor-state-manager: Technical Debt Epic

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3575]
Track all downstream changes that incurred technical debt that need to be worked into upstream

**Comment by rfrandse** [comment]
refresh

**Comment by NodeMan97** [comment]
An additional compilation setting was added ('ONLYRUNAPRONPOWERLOSS'. By default it is set to false which allows APR to behave regularly as expected. If the flag is set to true then APR will only be run if there was an AC power loss on the chassis.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Closing this Epic.  The remaining story #3580 will be migrated to Jira.
