### ISSUE TITLE
Only run power store on AC losses

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3577]
Commit: https://github.com/ibm-openbmc/phosphor-state-manager/commit/d8270f6c8942bedf66462d1951284d015cf2f9b5 and https://github.com/ibm-openbmc/phosphor-state-manager/commit/45f36e60c253b1450ddf65225e619e51d215561a

Action: Update the gerrit commit upstream to make this a configurable option where the default is the standard behavior and the needed IBM behavior is enabled via a meta-ibm bbappend override.

**Comment by geissonator** [comment]
Refresh

**Comment by NodeMan97** [comment]
Merged 
https://github.com/openbmc/phosphor-state-manager/blob/master/discover_system_state.cpp#L127
