### ISSUE TITLE
host-check: add extra debug and time

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3578]
Commit: https://github.com/ibm-openbmc/phosphor-state-manager/commit/25ee40ba611e49554230afc06b18405f210f0599

Action: I think this can probably be upstreamed as-is. Maybe some improvement to the comments around the new code.

**Comment by NodeMan97** [comment]
Added a comment to the logging message. Since the firmware condition of each service is being logged for each attempt I don't see where else any debug could be added(unless you would like to inspect situations where the host/chassis are not on or running).

**Comment by NodeMan97** [comment]
Pushed to upstream.

**Comment by geissonator** [comment]
Please add link to all upstream gerrit reviews for these issues to keep tracking easy

**Comment by NodeMan97** [comment]
https://gerrit.openbmc.org/c/openbmc/phosphor-state-manager/+/54138
