### ISSUE TITLE
Stop FSI scan service if chassis power on but host not booting

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3580]
Commit: https://github.com/ibm-openbmc/phosphor-state-manager/commit/8418950330cbf73b5362cdc5a2756be8ae4950f0 and https://github.com/ibm-openbmc/phosphor-state-manager/commit/2b8218dbd2185fef0ab15971427188c1b0797204

Action: This is a bit complicated as it mostly has to do with our use of cronus and how it ties in with our chassis on and boot process. We'll need to review this path and see if there is a better solution here or if this is just something we continue to carry downstream.

**Comment by rfrandse** [comment]
tracking in jira
