### ISSUE TITLE
PCIe Topology: Make redfish adapter objects unique 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3581]
From https://syswiki02.rchland.ibm.com/openbmc/openbmc-design-reviews
bmcweb shows redfish adapter objects with the same path even though all the dbus objects have unique path.
```
    {      "@odata.id": "/redfish/v1/Systems/system/PCIeDevices/adapter1"    },
    {      "@odata.id": "/redfish/v1/Systems/system/PCIeDevices/adapter1"    }
```
What did we do for cores and cpu's? Guard looked at further up the path, we should do the same. 
Going to have to move away from the generic getCollectionMembers :( 
https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/FabricAdapters.hpp#L265

`<some parent>-adapter1`

**Comment by mzipse** [comment]
Work is complete.  Closing.
