### ISSUE TITLE
PCIe Topology: Link from PCIe Device to PCIe Slot

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3585]
As discussed on the 6/3 call, we need an OEM link from the PCIE Device to the PCIe Slot..
You should be able to look at the parent of the PCIe Device to get the PCIe Slot. The chassis would be a further grandparent.

**Comment by gtmills** [comment]
Will be something like  "Links""Oem""Ibm""PcieSlot" on the PcieDevice here https://redfish.dmtf.org/schemas/PCIeDevice.v1_9_0.json

**Comment by mzipse** [comment]
Work is complete.  Closing.
