### ISSUE TITLE
PFP: fan watchdog timeouts will lead to fan callouts

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#3586]
if the watchdog process ends up not pinging the fan watchdog fast enough and it trips, the fans will go to high speed.  Fan monitor won't know that, so it will consider those fan errors and shut down the system.

While I think we do need some error logs here, the system should really stay up.

**Comment by spinler** [comment]
Thinking about this some more, with our newer code it's more likely that we'd get stuck in a loop of:

1) fans get set to nonfunc because it's running too fast
2) 1 minute shutdown timer starts
2) new fan target of max speed gets set because of the nonfunc fans
3) fans are now within range of max so they become func and shutdown timer is cancelled
4) fans start to decrease again
5) start over at 1)

**Comment by rfrandse** [comment]
tracking in jira
