### ISSUE TITLE
IPMI: Support listing most/all sensors and SDRs

### ISSUE THREAD

**Issue by sbteeks** [ibm-openbmc/dev#3589]
Currently we support listing sensors related to DIMMs, CPUs, FANs, Ambient temperatures, CPU(Core0) and DIMM(dram) temperatures. However, there is a need for other sensors for current, voltage, and power consumption. We need to support these in the future release...

**Comment by mzipse** [comment]
We will consider this for a future release.  By rebasing with upstream master in a future release, there is opportunity to expand the number of sensors beyond the current 255 limitations.

**Comment by rfrandse** [comment]
tracking in jira
