### ISSUE TITLE
Redfish: Code Update - Basic BMC and PNOR firmware image update

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#359]
Most of the plumbing is in place. This story is to ensure a BMC code update can happen over Redfish using a POST to /redfish/v1/UpdateService/. At a minimum it does need to be updated to take the new HttpPushUriTargets parameter defined in http://redfish.dmtf.org/schemas/v1/UpdateService.v1_3_0.json so a user can target the BMC or the BIOS. This story will only ensure BMC works.

Note that the priority feature is not included in this. Activation and the BMC reboot will happen automatically when the update is complete.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Once I dug in, it seemed more relevant to ensure that both BMC and PNOR update worked. There is no need to support the HttpPushUriTargets since the redfish schema states if no targets are provided then the back end code needs to apply the supplied image to all appropriate targets. So the code change I did was to support both a POST of a BMC image and a PNOR image.

**Comment by geissonator** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18888/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/18888 merged
