### ISSUE TITLE
PCIe Topology: SavePCIeTopologyInfo

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3591]
Need an Oem Property on SavePCIeTopologyInfo like we did for PCIeTopologyRefresh. Let's put it on System as well. Let's make it a PATCH and a GET.

https://github.com/ibm-openbmc/phosphor-dbus-interfaces/blob/9fe8e065b4e73a888483bafbc02d8397883d3763/yaml/com/ibm/PLDM/PCIeTopology.interface.yaml#L11

**Comment by mzipse** [comment]
Work is complete.  Closing.
