### ISSUE TITLE
Redfish: Add accuracy for power supply input power sensors

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#3592]
Implement support for the Accuracy attribute of Redfish power supply input power sensors.  This is needed for EnergyStar compliance.

A short term, downstream solution was implemented as a stop-gap.  However, a proper upstream solution is needed.

## High Level Design
* Resolve open question about exact meaning of Redfish Accuracy property
* Create D-Bus interface for accuracy value
* Implement support for publishing correct accuracy value on D-Bus
* Implement bmcweb support to read accuracy value from D-Bus and include in Redfish output

## Resolve open question about exact meaning of Redfish Accuracy property
A key design issue that is still open is whether the accuracy percentage is standalone or is related to other min/max values?

For example, a sensor has an Accuracy of 2% and a Reading of 10.  Does that mean the actual sensor value is 9.8 to 10.2?  Or is the Accuracy based on a min/max range?  For example, if the min/max range of the Sensor is 0-100, then the actual value is 8 to 12?

I asked this question on the Redfish forum.

https://redfishforum.com/thread/657/simple-sensor-accuracy-property

I received a response, but the response was still interpreted two different ways by the OpenBMC community.  I asked for a clarification in a follow-up question.  That question had not been answered at the time this issue was opened.

I believe it is supposed to be standalone based on the answer on the Redfish forum and the way the Redfish property is described in the documentation.  However, it may take some confirmation from the Redfish leaders before this will be accepted by the community.

This question is important because it will affect not only how the D-Bus interface is documented but also how the value is calculated and used by bmcweb.

## Create D-Bus interface for accuracy value

Brandon Wyman pushed a commit to Gerrit with a proposed solution:

https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/53569

This was based on conversation with the open source community.  At the time this issue was created, the commit had multiple +1s but had not merged.  Part of the reason is likely the need to resolve the design issue mentioned above.

## Implement support for publishing correct accuracy value on D-Bus
At a high level, it seems like this could be done in at least three different ways:
* phosphor-hwmon
* dbus-sensors
* bitbake recipes

### phosphor-hwmon
The phosphor-hwmon application reads sensor values from hwmon-style device drivers and publishes them on D-Bus.  It supports multiple D-Bus interfaces related to sensors.

Some of the information this application publishes, such as min and max values, are obtained from configuration files.

The configuration file syntax could be expanded to support an accuracy value.  The application could be enhanced to read this value and publish it on the new D-Bus Accuracy interface.

There are two challenges if this design is selected:
* It requires use of phosphor-hwmon.  While IBM systems currently use this application, my understanding is that dbus-sensors is considered the strategic direction.
* I believe it would require that all power supply types that can be plugged into a certain location have a common accuracy value.  For example, if both a 1600W and 2000W power supply could be plugged into the first power supply location, they would need to have the same accuracy value.  I believe the config files are based on an I2C bus/address and not the device type.

### dbus-sensors
The dbus-sensors application also reads sensor values and publishes them on D-Bus.  I believe this is considered the strategic direction.

My understanding at the time this issue was opened is that this application does not currently support accuracy.  So I believe either this application or perhaps EntityManager would need to be enhanced to support the new Accuracy interface.

The primary challenge if this design is selected is that IBM systems would need to migrate from phosphor-hwmon to dbus-sensors for power supply sensors.  This may be the strategic direction, but there is probably some amount of work required.

### bitbake recipes
Bitbake recipes could be used to define and publish system-specific Accuracy values on D-Bus.  I believe there are examples of other system-specific attributes handled in this way.  I believe they are considered system "settings" and are handled by an associated application.

The primary challenge of this solution would probably be the same as the second one identified for phosphor-hwmon.  It would likely require that all power supplies plugged into a specific location have the same accuracy value.

## Implement bmcweb support to read accuracy value from D-Bus and include in Redfish output
The bmcweb sensors implementation would need to be enhanced to look for the new Accuracy D-Bus interface and use it in the Redfish output.

The interface would likely be optional and would only apply to certain sensors.  It would also probably be desired to obtain all the Accuracy values in one D-Bus query, or one query per service.  Querying once per sensor would lead to performance issues.

**Comment by gtmills** [comment]
Might just have to poke Redfish again on https://redfishforum.com/thread/657/simple-sensor-accuracy-property :/

**Comment by smccarney** [comment]
> Might just have to poke Redfish again on https://redfishforum.com/thread/657/simple-sensor-accuracy-property :/

Done.

**Comment by bjwyman** [comment]
Attempting to summarize what was discussed in the Redfish forum:
- The sensor Accuracy format is "%" with a valid value being from 0 to 100.
  - A value of 0.25 would mean 0.25%.

- The Accuracy value is standalone, it is not related to the min/max values.
  - If you have an Accuracy of 2%, and a reading of 10, the actual metric could be from 9.8 to 10.2.

- Sometimes, a sensor accuracy is rated in terms of a sensor's units instead of a percentage.
  - As of June 29, 2022, clarification is needed in the Redfish model for how to establish an accuracy as a percentage in the Redfish model for such devices. For instance, a thermal sensor might have an accuracy of +/- 0.5°C, over a range of -20°C to 100°C.

**Comment by bjwyman** [comment]
Updated YAML file in Gerrit commit under review to reflect the clarifications noted in the Redfish forum: https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/53569

**Comment by bjwyman** [comment]
Accuracy interface merged: https://github.com/openbmc/phosphor-dbus-interfaces/commit/0020fa3da6a30f7f63afb0d2de41b508b7a8f18d

**Comment by lxwinspur** [comment]
@mzipse 
I will look at this issue tomorrow, and I will ping @derekhoward55 if we have any questions, thanks :)

**Comment by derekhoward55** [comment]
Brandon got the dbus interface agreed to and completed, so all that is remaining is hwmon changes to make the accuracy available, and bmcweb changes to grab it from dbus.

The accuracy of all the psu's we use is 1%.

**Comment by lxwinspur** [comment]
@derekhoward55 
one question: for this issue, do we need to upstream or downstream?

**Comment by derekhoward55** [comment]
@lxwinspur upstream please

**Comment by lxwinspur** [comment]
@derekhoward55 
I am working on this issue, so I have a question: Should we update `phosphor-hwmon` or `dbus-sensors`?

For Power Supply, I see that IBM used `phosphor-hwmon`, but in the community, dbus-sensor is the future direction.

**Comment by spinler** [comment]
@lxwinspur We need it for phosphor-hwmon.

It's possible we'd move to PSUSensor from dbus-sensors for the power supplies in the future, but we don't use that app at all now.  If you also wanted to do that one it would be less work for later.

**Comment by lxwinspur** [comment]
phosphor-hwmon merged by: https://gerrit.openbmc.org/c/openbmc/phosphor-hwmon/+/57839
redfish review by: https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57893

**Comment by derekhoward55** [comment]
Can you please add the 1% value for ibm psu's as well?  Per Matt "the config files need to be updated in openbmc/openbmc https://github.com/openbmc/openbmc/tree/master/meta-ibm/recipes-phosphor/sensors/phosphor-hwmon/p10bmc"

Thanks!

**Comment by lxwinspur** [comment]
> Can you please add the 1% value for ibm psu's as well? Per Matt "the config files need to be updated in openbmc/openbmc https://github.com/openbmc/openbmc/tree/master/meta-ibm/recipes-phosphor/sensors/phosphor-hwmon/p10bmc"
> 
> Thanks!

Review by: https://gerrit.openbmc.org/c/openbmc/openbmc/+/58044

**Comment by lxwinspur** [comment]
@derekhoward55 @spinler 
Could you please reivew this patch? https://gerrit.openbmc.org/c/openbmc/openbmc/+/58044

**Comment by derekhoward55** [comment]
@lxwinspur Hi anything needed to get fixed with https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57893?

**Comment by lxwinspur** [comment]
> @lxwinspur Hi anything needed to get fixed with https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57893?

Hi, @derekhoward55 , I just waiting for review.

**Comment by lxwinspur** [comment]
@derekhoward55 , this issue has been merged upstream, can we close it?

**Comment by derekhoward55** [comment]
Yes, closing, thanks for doing the changes!
