### ISSUE TITLE
GUI: FED: Bug: The GUI should not be checking model numbers to determine features 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3593]
## Expected Behavior
The GUI should not be checking model numbers to determine if we need to show a page. The concurrent maintenance page should show based on the API  

## Actual Behavior
The GUI hardcodes some model numbers (this is very error-prone)

The backend needs to verify we only show battery concurrent maintenance on Everett, not rainier

**Comment by rfrandse** [comment]
tracking in jira
