### ISSUE TITLE
RedFish returns success on reset identify before it actually completes the operation

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3595]
From Dean's host interlock on 6/28. Need to look at this for FW1030. FYI @manojkiraneda @jinuthomas 

Maury asked me to open this. 

· RedFish returns success on reset identify before it actually completes the operation.
https://ibm.ent.box.com/file/977390262945

Need to probably return a task here

**Comment by rfrandse** [comment]
tracking in jira
