### ISSUE TITLE
GUI : FED : I/O Adapter Enlarged Capacity Upper bound improvement

### ISSUE THREAD

**Issue by mzipse** [ibm-openbmc/dev#3597]
## SME
**BMC**:
**RAS**:
**PHYP**:

## FED 
Nikhil
### Overview
For the Memory page setting for the I/O Adapter Enlarged Capacity, the GUI needs to show the upper bound based on the  BIOS attribute upper bound.  This upper bound also needs to be enforced when the user types in the value.  The upper bound is currently hardcoded to 21.

### Acceptance Criteria
- [ ] Feature breakdown

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by mzipse** [comment]
This issue coincides with issue #3598 .

**Comment by rfrandse** [comment]
tracking in jira
