### ISSUE TITLE
I/O Adapter Enlarged Capacity Upper Bound calculation

### ISSUE THREAD

**Issue by mzipse** [ibm-openbmc/dev#3598]
Per feedback from Travis Pizel, the I/O Adapter Enlarged Capacity upper bound varies by the model configuration and the number of slots in the system and possibly some other parameters....Travis has details.

We need to adjust the upper limit of the I/O Adapater Enlarged Capacity BIOS setting to match the specific configuration.  Current this value is set at '21', which is the largest upper bound of a max config Everest system. 

Assigning to Santosh's team to investigate.

**Comment by rfrandse** [comment]
tracking in jira
