### ISSUE TITLE
Utilize PowerRestoreDelay to delay APR in phosphor-state-manager

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#3605]
https://github.com/ibm-openbmc/phosphor-state-manager/commit/683013a7c19906ffd185bdca16963db5c35167cb went in recently to fix an issue with APR starting too early in the boot.

After that went in, it was noticed that a PowerRestoreDelay had been added to the  xyz.openbmc_project.Control.Power.RestorePolicy interface. So instead of hard coding, lets set the 30s in our meta-ibm override for this property, and have the APR function just read that property to know how long to delay.

This should be upstreamable. So two things here:

- Build on https://gerrit.openbmc.org/c/openbmc/openbmc/+/55285 to set a default for IBM systems
- Update discover_host_code.cpp to read this new property and use it for the delay.

**Comment by NodeMan97** [comment]
merged
https://github.com/openbmc/phosphor-state-manager/blob/master/discover_system_state.cpp#L180
