### ISSUE TITLE
GUI : FED : Base favicon file relocation

### ISSUE THREAD

**Issue by ghost** [ibm-openbmc/dev#3610]
### Overview
The backend eventually will have a way to load up logos and icons depending on what company will be using the product. In our current frontend, the file location for favicons are located in the `./public` directory. It should follow uniform with the other files being changed via backend and go under `./src/assets/` directory

My suggestion is that we have a base, generic placeholder icon file in the ./src/assets/` directory with a name that matches whatever the backend name will be for replacing the icon file.

From there we can write a new function on the frontend that takes the image coming from the backend and replace the favicon with the backend one.

**Comment by ghost** [comment]
@gtmills @Nikhil-Ashoka @sandeepasingh116 fyi

**Comment by rfrandse** [comment]
tracking in jira
