### ISSUE TITLE
PSU support for 2x low-line (110v) on 2s2u

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#3611]
Update the EM config file (https://github.com/ibm-openbmc/entity-manager/blob/1030/configurations/Rainier%202U%20Chassis.json) to allow the 2000W psu's in 2s2u to be hooked up to 110v (220v support is already in place).

Ask gsi/ftc to test.

**Comment by wrightjl1** [comment]
PR: https://github.com/ibm-openbmc/entity-manager/pull/35

**Comment by wrightjl1** [comment]
1030 entity manager bump: https://github.ibm.com/openbmc/openbmc/pull/2806#

**Comment by wrightjl1** [comment]
Merged into [fw1030.00-2.9](https://github.ibm.com/openbmc/release-notes/wiki/fw1030.00-2.9)
Available in [1030.2235.20220823a](https://rchweb.rchland.ibm.com//afs/rchland/projects/esw/fw1030/Builds/1030.2235.20220823a/logs/status.html) or greater builds.

**Comment by wrightjl1** [comment]
Request for testing: https://ibm-systems-power.slack.com/archives/CPVHLBD3R/p1661792740491309
