### ISSUE TITLE
Fix NTP server field 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3613]
Pull in https://github.com/openbmc/bmcweb/commit/b9e1522807ac9411a03f0d37b07ac35f4cebbe3c 

https://github.com/openbmc/bmcweb/commit/b9e1522807ac9411a03f0d37b07ac35f4cebbe3c, which makes the NTP server field follow Redfish correctly.

"The Redfish specification for PATCH of arrays defines a number of requirements.
- Setting a value to null, should remove it from the list.
- Setting a value to empty object "{}" should leave the value unmodified"

I think this should just go on 1030

**Comment by rfrandse** [comment]
tracking in jira
