### ISSUE TITLE
Rainier 1S4U support 2x 1000W power supplies with limited config

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#3614]
Update the EM config file (https://github.com/ibm-openbmc/entity-manager/blob/1030/configurations/Rainier%201S4U%20Chassis.json) to allow 2 1000W psu's in 1s4u, and so oversubscription is not activated when only 2 psu are attached.  There is no different IM/MTM for the 2-psu and 4-psu system.

Do not need to specifically allow 2- or 4-psu configs; anything with 2 or more is fine.  Same power cap can be used with either 2 or 4 psu present.  Mfg will ensure the appropriate minimal procs/dimms/pci are installed in the 2 psu orders.

Note this means that we will not log an error if only 2 or 3 psu are attached, even if the customer ordered a 4 psu system, as we do not know what the customer ordered.

Ask gsi/ftc to test both a 2-psu and 4-psu config.

**Comment by wrightjl1** [comment]
Gerrit code review for phosphor-power: https://gerrit.openbmc.org/c/openbmc/phosphor-power/+/58026

**Comment by wrightjl1** [comment]
PR for ibm-openbmc entity-manager: https://github.com/ibm-openbmc/entity-manager/pull/38

**Comment by wrightjl1** [comment]
Take 2 PR for ibm-openbmc entity-manager: https://github.com/ibm-openbmc/entity-manager/pull/39

**Comment by wrightjl1** [comment]
All commits merged.
