### ISSUE TITLE
1050:CT:Rainier:IPMI: dcmi get_conf_parm command is failing

### ISSUE THREAD

**Issue by yadlapati** [ibm-openbmc/dev#3624]
Internal Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=481287

FTC1050:CT:Rainier:IPMI: dcmi get_conf_parm command is failing

Problem Description
__________________________________________________________________
unable to perform dcmi get_conf_parm/set_conf_parm command is failing.

Driver details:
_______________________________________________________________
root@p10bmc:~#  cat /etc/os-release
ID=openbmc-openpower
NAME="IBM eBMC (OpenBMC for IBM Enterprise Systems)"
VERSION="fw1050.00-2.14"
VERSION_ID=fw1050.00-2.14-1050.2313.20230329a (NL1050_008)
VERSION_CODENAME="${DISTRO_CODENAME}"
PRETTY_NAME="IBM eBMC (OpenBMC for IBM Enterprise Systems) fw1050.00-2.14"
BUILD_ID="20231001"
OPENBMC_TARGET_MACHINE="p10bmc"
EXTENDED_VERSION=NL1050_008
BMC_SIGNATURE_TYPE=Development
HOST_SIGNATURE_TYPE=Development

_________________________________________

Error Steps
______________________________________

[rahulmah@gfwa180:~]$ ipmitool -I lanplus -C 17 -N 3 -p 623 -U ipmi_admin -H rain40bmc dcmi get_conf_param

DCMI request failed because: Unspecified error (ff)
Error Get DCMI Configuration Parameters!

_______________________________________
Journal log
_______________________________________
root@p10bmc:~# journalctl -f
Mar 30 12:01:08 p10bmc systemd[1]: Started SSH Per-Connection Server (9.3.62.100:49870).
Mar 30 12:01:08 p10bmc systemd-timesyncd[262]: Timed out waiting for reply from 10.5.5.30:123 (10.5.5.30).
Mar 30 12:01:18 p10bmc systemd-timesyncd[262]: Timed out waiting for reply from 10.5.5.30:123 (10.5.5.30).
Mar 30 12:01:30 p10bmc systemd-journald[255]: Forwarding to syslog missed 5 messages.
Mar 30 12:01:58 p10bmc ipmid[545]: failed to convert major string to uint8_t: Invalid argument
Mar 30 12:01:58 p10bmc ipmid[545]: sd_bus_call: xyz.openbmc_project.Common.Error.ResourceNotFound: The resource is not found.
Mar 30 12:01:58 p10bmc netipmid[1593]: Removing idle IPMI LAN session, id: 27620112, handler: 1
Mar 30 12:02:01 p10bmc systemd-journald[255]: Forwarding to syslog missed 3 messages.

 This function is working fine in 1040 driver.

**Comment by anoo1** [comment]
This is fixed now with fw1050.00-2.34
