### ISSUE TITLE
FTC1050:Rainier: getting [ERROR "webassets.hpp":139] Cannot determine content-type for /usr/share/www/changeLogo.sh

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3629]
When starting bmcweb (so every boot of the bmc) see the following trace 
```
[ERROR "webassets.hpp":139] Cannot determine content-type for /usr/share/www/changeLogo.sh
```

Can we move that script to somewhere else?

**Comment by gtmills** [comment]
Also would be good if `changeLogo.sh` didn't have .sh at the end

**Comment by gtmills** [comment]
Let's put this in /usr/bin
From Adriana: 

 /usr/bin for all bmc app scripts as the general rule. Dir description for reference: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s04.html

seems we've also documented that in an [antipattern](https://github.com/openbmc/docs/blob/master/anti-patterns.md#resolution-5) so yeah we're good with /usr/bin

**Comment by lxwinspur** [comment]
@gtmills 
Review by: https://github.com/ibm-openbmc/openbmc/pull/284

**Comment by lxwinspur** [comment]
@ChicagoDuan  FYI ^

**Comment by gtmills** [comment]
Reed copied to GHE and merged. Closing. Thanks for all the help here!
