### ISSUE TITLE
IPS bmcweb changes for 1110 bmcweb 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#3636]
For https://github.com/ibm-openbmc/bmcweb/tree/1110 we reset to upstream master. 
All changes not merged upstream need to be pulled back in. Some of these are already merged upstream and already in 1110, but I think most need to be pulled back in  

commit | Author | Title | In 1110? | Merged Upstream
-- | -- | -- | -- | -- 
c8f20c7bc4 | George Liu | 1050: Add Redfish total_power object ([710](https://github.com/ibm-openbmc/bmcweb/pull/710)) | [reviewing](https://github.com/ibm-openbmc/bmcweb/pull/837) | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57717)
07faf31c26 | George Liu | Fix internal error due to system_attention_indicator while booting ([709](https://github.com/ibm-openbmc/bmcweb/pull/709)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/827) | no
d6b98b17c8 | George Liu | 1050: Fix fan resources in the ThermalSubsystem info ([684](https://github.com/ibm-openbmc/bmcweb/pull/684)) | yes | [merged](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57533)
f8e0a386a8 | George Liu | Implement LocationIndicatorActive property for CXP connector resource | no | [abandoned](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/43391)
45b4cee5bf | George Liu | Implementation of Port schema in bmcweb | no | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61097)
a4f5c0cce5 | George Liu | Add Ports schema | yes | [merged](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/61090)
66dbc15314 | George Liu | Implement LocationIndicatorActive for Memory resource ([571](https://github.com/ibm-openbmc/bmcweb/pull/571)) | no | [abandoned](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/37310)
9ec664e797 | George Liu | Consume availability interface for cores ([254](https://github.com/ibm-openbmc/bmcweb/pull/254)) | no | no
4dbe5ec81f | George Liu | Implement LocationIndicatorActive for CPU resource | no | [abandoned](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/37045)
bb811111ed | George Liu | Implement SubProcessors for processor core | no | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/38570)
10c9933e8a | George Liu | ~Implement LocationIndicatorActive for Memory resource~
1afe3f87f6 | George Liu | ~Implement SubProcessors for processor core~ | 
335f1ee091 | George Liu | ~Implement LocationIndicatorActive for CPU resource~
0e47f14655 | George Liu | Update indicator LED verification ([560](https://github.com/ibm-openbmc/bmcweb/pull/560)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/826) | [Merged](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/48868)
a1340ea6b8 | George Liu | Add Redfish ThermalMetrics schema in bmcweb ([561](https://github.com/ibm-openbmc/bmcweb/pull/561)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/901) | [reviewing](https://gerrit.openbmc.org/q/topic:%22redfish-EnvironmentMetrics%22)
3ba2a2e767 | George Liu | ibm: Move OCC pass through REST api under /ibm/v1 namespace ([544](https://github.com/ibm-openbmc/bmcweb/pull/544)) | [reviewing](https://github.com/ibm-openbmc/bmcweb/pull/828) | no
ebfe8e42fb | George Liu | Add support for redfish StopBootOnFault ([539](https://github.com/ibm-openbmc/bmcweb/pull/539)) | yes | [merged](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/44175)
ae56b19a46 | George Liu | Redfish: Implement OEM lamp test and SAI ([541](https://github.com/ibm-openbmc/bmcweb/pull/541)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/827) | no
d1b91b96c7 | George Liu | Add PowerLimitWatts in EnvironmentMetrics | [reviewing](https://github.com/ibm-openbmc/bmcweb/pull/837)  | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/47300)
b0dd489ff4 | George Liu | Add FanSpeedsPercent for EnvironmentMetrics | [reviewing](https://github.com/ibm-openbmc/bmcweb/pull/837)  | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57715)
4ffe002e28 | George Liu | Add SpeedPercent information for Fan | no | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/57657)
644058e178 | George Liu | Fix set/get Asserted property | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/818) | no
a460f243ca | Albert Zhang | Implement LocationIndicatorActive for Fan | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/819) | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42210)
4842d3e8ca | Chicago Duan | 1050: Redfish: Check snmpTrap port ([688](https://github.com/ibm-openbmc/bmcweb/pull/688)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/814) | no
ed2f50384a | Chicago Duan | 1050: Redfish SNMP: Allow use of empty port ([675](https://github.com/ibm-openbmc/bmcweb/pull/675)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/814) | no
ff5ff98b66 | Chicago Duan | 1050: Redfish check snmpTrap port ([668](https://github.com/ibm-openbmc/bmcweb/pull/668)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/814) | no
12b7346fc5 | Chicago Duan | Fix redfish can't show USBCodeUpdateEnabled ([585](https://github.com/ibm-openbmc/bmcweb/pull/585)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/813) | no
45cfaee9e7 | Chicago Duan | Redfish: Fix issue of set Assemply LocationIndicatorActive ([566](https://github.com/ibm-openbmc/bmcweb/pull/566)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/844) | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42441)
c58b410e24 | Chicago Duan | Redfish : Look for OperationalStatus for the memory Health ([555](https://github.com/ibm-openbmc/bmcweb/pull/555)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/835) | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/69859)
1aafde0f5c | Chicago Duan | Fix bug: bmcweb SNMP errors in the Journal ([557](https://github.com/ibm-openbmc/bmcweb/pull/557)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/815) | no
ef9190bfda | Chicago Duan | Redfish: Implement HealthRollup in chassis schema ([556](https://github.com/ibm-openbmc/bmcweb/pull/556)) | [merged](https://github.com/ibm-openbmc/bmcweb/pull/836) | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/69861)
33ba53054a | Chicago Duan | Redfish: Implements Redfish Assembly Health ([553](https://github.com/ibm-openbmc/bmcweb/pull/553)) | [merged](https://github.com/ibm-openbmc/bmcweb/pull/900) | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/39574)
3fb9d46925 | Chicago Duan | Implement LocationIndicatorActive property for Manager ([550](https://github.com/ibm-openbmc/bmcweb/pull/550)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/821) | [abandoned](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/50494)
7ed5079232 | Chicago Duan | Redfish : Add USB code update Enable/Disable ([547](https://github.com/ibm-openbmc/bmcweb/pull/547)) | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/813) | no
e6ac33a78b | Chicago Duan | Implement LocationIndicatorActive for PowerSupplies | [**Merged**](https://github.com/ibm-openbmc/bmcweb/pull/818) | [reviewing](https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42221)

**Comment by lxwinspur** [comment]
@gtmills 
Updated

**Comment by lxwinspur** [comment]
12b7346fc5
7ed5079232
**Merged**: https://github.com/ibm-openbmc/bmcweb/pull/813

**Comment by lxwinspur** [comment]
4842d3e8ca
ed2f50384a
ff5ff98b66
**Merged**:https://github.com/ibm-openbmc/bmcweb/pull/814

**Comment by lxwinspur** [comment]
1aafde0f5c
**Merged**:https://github.com/ibm-openbmc/bmcweb/pull/815

**Comment by lxwinspur** [comment]
3fb9d46925
**Merged**:https://github.com/ibm-openbmc/bmcweb/pull/821

**Comment by lxwinspur** [comment]
0e47f14655
**Merged**: https://github.com/ibm-openbmc/bmcweb/pull/826

**Comment by lxwinspur** [comment]
07faf31c26
ae56b19a46
**Merged**: https://github.com/ibm-openbmc/bmcweb/pull/827

**Comment by lxwinspur** [comment]
3ba2a2e767
https://github.com/ibm-openbmc/bmcweb/pull/829

**Comment by lxwinspur** [comment]
c58b410e24
**Merged**: https://github.com/ibm-openbmc/bmcweb/pull/835

**Comment by lxwinspur** [comment]
ef9190bfda
https://github.com/ibm-openbmc/bmcweb/pull/836

**Comment by lxwinspur** [comment]
c8f20c7bc4
d1b91b96c7
b0dd489ff4
https://github.com/ibm-openbmc/bmcweb/pull/837

**Comment by gtmills** [comment]
@lxwinspur Thank you for all your effort here, can you get the remaining PRs in downstream ? Keep going upstream on these changes ?

**Comment by gtmills** [comment]
We are looking for the ` In 1110? ` column to say either `"Merged"` or `"Not needed in 1110"`

**Comment by gtmills** [comment]
@lxwinspur Can you address the comments on https://github.com/ibm-openbmc/bmcweb/pull/837/files ? Can you finish out the commits? Thanks!

Updated

**Comment by lxwinspur** [comment]
> @lxwinspur Can you address the comments on https://github.com/ibm-openbmc/bmcweb/pull/837/files ? Can you finish out the commits? Thanks!
 
Updated

**Comment by gtmills** [comment]
> 3ba2a2e767 | George Liu | ibm: Move OCC pass through REST api under /ibm/v1 namespace (544) | reviewing | no

Is this done here?
https://github.com/ibm-openbmc/bmcweb/pull/829/files
If so, can you update that row?

**Comment by gtmills** [comment]
This should all be done. Closing.
