### ISSUE TITLE
IPMI: Setting Power Cap Value via IPMI throws error (at runtime)

### ISSUE THREAD

**Issue by youhour** [ibm-openbmc/dev#3637]
## Problem Description: 
Setting Power Cap Value via IPMI, while system at runtime (OS is running), throws error

Internal EWM defect # 598518

## Expected Behavior
ipmitool -I lanplus -C 17 -N 3 -p 623 -U ipmi_admin -H rain57bmc.aus.stglabs.ibm.com dcmi power set_limit limit 1530
Must be successful and reading the value back correctly

## Actual Behavior
bash-4.2$ ipmitool -I lanplus -C 17 -N 3 -p 623 -U ipmi_admin -H rain57bmc.aus.stglabs.ibm.com dcmi power set_limit limit 1530
Password:

    **DCMI request failed because: Request data length invalid (c7)**

bash-4.2$ ipmitool -I lanplus -C 17 -N 3 -p 623 -U ipmi_admin -H rain57bmc.aus.stglabs.ibm.com dcmi power get_limit
Password:

    Current Limit State: Power Limit Active
    Exception actions:   Hard Power Off & Log Event to SEL
    **Power Limit:         1999 Watts**
    Correction time:     0 milliseconds
    Sampling period:     0 seconds

## Steps to Reproduce the Problem

  1.  Login to Rainier system
  2.  Boot the Rainier to OS
  3. Executing the IPMI command to set the power cap value :
 

## Specifications
BMC firmware version:  BMC fw : fw1060.00-4.20-1060.2408.20240215a

**Comment by lxwinspur** [comment]
@youhour  @anoo1 
Fixed in: https://github.com/ibm-openbmc/phosphor-host-ipmid/pull/20
Please test again.

**Comment by lxwinspur** [comment]
@youhour 
can you close this issue?

**Comment by mzipse** [comment]
Yes, we have validated this fix and merged in FW1060.  Closing.
