### ISSUE TITLE
Swift: BMC-alive LED

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#364]
There is some sort of requirement about an LED that says the BMC is alive.  Do we already do this?
At one point I heard the requirement was:
```
blink the rear power LED on the back of the system only , and at standby only
```
but don't we already do something like that?

I also heard there was going to be a new hardware driven LED that would blink when a certain voltage domain was good (probably the BMC's).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
The rear power LED is now driven by HW, with no BMC control, to achieve this goal.  Closing.
