### ISSUE TITLE
FVT1060:Bonnell:After deactivating Power Cap  , the Power Cap state remains active in IPMI command output 

### ISSUE THREAD

**Issue by yadlapati** [ibm-openbmc/dev#3640]
System Details:
root@bonn027:~# obmcutil state

CurrentBMCState     : xyz.openbmc_project.State.BMC.BMCState.Ready

CurrentPowerState   : xyz.openbmc_project.State.Chassis.PowerState.On

CurrentHostState    : xyz.openbmc_project.State.Host.HostState.Running

BootProgress        : xyz.openbmc_project.State.Boot.Progress.ProgressStages.OSRunning

OperatingSystemState: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.Inactive

root@bonn027:~#

root@bonn027:~# cat /etc/os-release

ID=openbmc-openpower

NAME="IBM eBMC (OpenBMC for IBM Enterprise Systems)"

VERSION="fw1060.00-4.42"

VERSION_ID=fw1060.00-4.42-1060.2414.20240327a (NL1060_036)

VERSION_CODENAME="nanbield"

PRETTY_NAME="IBM eBMC (OpenBMC for IBM Enterprise Systems) fw1060.00-4.42"

CPE_NAME="cpe:/o:openembedded:openbmc-openpower:fw1060.00-4.42"

BUILD_ID="20240614"

OPENBMC_TARGET_MACHINE="p10bmc"

EXTENDED_VERSION=NL1060_036

BMC_SIGNATURE_TYPE=Development

HOST_SIGNATURE_TYPE=Development

root@bonn027:~#

Error Details:

After deactivating power cap using IPMI commands, the power limit is still shown as active.

bash-4.4$ ipmitool -I lanplus -C 17 -p 623 -U ipmi_test -P 0penBmc0 -H bonn027 dcmi power deactivate

    Power limit successfully deactivated

bash-4.4$

bash-4.4$ ipmitool -I lanplus -C 17 -p 623 -U ipmi_test -P 0penBmc0 -H bonn027 dcmi power get_limit

    Current Limit State: Power Limit Active

    Exception actions:   Hard Power Off & Log Event to SEL

    Power Limit:         556 Watts

    Correction time:     0 milliseconds

    Sampling period:     0 seconds

bash-4.4$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc_ip}/redfish/v1/Chassis/chassis/EnvironmentMetrics | grep -A5 -i PowerLimitWatts

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100  1186  100  1186    0     0  15813      0 --:--:-- --:--:-- --:--:-- 15813

  "PowerLimitWatts": {

    "AllowableMax": 3982,

    "AllowableMin": 568,

    "ControlMode": "Disabled",

    "SetPoint": 570

  },

**Comment by yadlapati** [comment]
EWM defect https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=605548

**Comment by lxwinspur** [comment]
@yadlapati @anoo1 @mzipse 
This issue has been fixed upstream, https://gerrit.openbmc.org/c/openbmc/phosphor-host-ipmid/+/66659
please cherry-pick this patch and test it again.

**Comment by mzipse** [comment]
Thanks @lxwinspur !  I've asked the team to pull that in and test.  We'll close this out once we verify it.

**Comment by mzipse** [comment]
This fix was pulled in back in April 2024.  It is part of both FW1060 and FW1110.  Closing this.
