### ISSUE TITLE
Swift: network reset via pinhole reset long press

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#365]
The request was to do a factory reset if the pinhole reset is held for some longer amount of time.

**Comment by spinler** [comment]
```
Talking with manufacturing, currently the request is for this reset button to cause the BMC IP to be set back to DHCP and to have any existing IP and Gateway wiped off the system.
```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Changing title to indicate this is just a network reset

**Comment by spinler** [comment]
To do a network reset:
```
busctl call xyz.openbmc_project.Network /xyz/openbmc_project/network xyz.openbmc_project.Common.FactoryReset Reset
```

**Comment by spinler** [comment]
Proposed design:
Add functionality to phosphor-gpio-monitor to be able to call a D-Bus method instead of starting a unit, so we don't have to make a new service just to call the method.   Also add support for an option to use libgpiod's C++ APIs as opposed to using libevdev, which requires device tree changes for every GPIO.

**Comment by ratagupt** [comment]
@spinler Do you want the deferred update(network reset to take effect after boot) or immediate update?

**Comment by spinler** [comment]
It's looking like it will need to take effect immediately.

**Comment by vishwabmc** [comment]
> Proposed design:
> Add functionality to phosphor-gpio-monitor to be able to call a D-Bus method instead of starting a unit, so we don't have to make a new service just to call the method. Also add support for an option to use libgpiod's C++ APIs as opposed to using libevdev, which requires device tree changes for every GPIO.

@spinler Why would MFG not make a CFT call to invoke the D-Bus API ?.. What is the hard requirement on the button ?

**Comment by spinler** [comment]
@vishwabmc what is CFT?

Also.  If the network  was misconfigured somehow, there is no way to get to the BMC to reset it, especially in the field.

**Comment by mzipse** [comment]
@spinler, the CFT is the Manufacturing Common Function Toolkit.
