### ISSUE TITLE
Fan Control: wspoon: Enable alternative floor table

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#366]
Using a thermal control mode property on the cooling zone, create an event that will load an alternative fan floor speed table when the mode is enabled.

**Comment by msbarth** [comment]
- [ ] Update fan control event yaml with new alternative fan floor speed table event
- [ ] End-to-end test function

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/17755/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/17755 merged
