### ISSUE TITLE
Fan Control: Create design template for thermal mode interface

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#374]
A design template is needed for the new thermal mode interface to upstream the fan control changes that utilize this in regard to ibm-openbmc/dev#274

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/18044

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/18044 merged
