### ISSUE TITLE
Fan Control: Adjust mode support to new interface

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#375]
Make the necessary changes to support the updated thermal control mode interface that was initially implemented so the changes can be upstreamed from ibm-openbmc/dev#274.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/18409

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/18409 merged
