### ISSUE TITLE
GUI: fix inventory dropdown 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#377]
![inventory_dropdown](https://user-images.githubusercontent.com/5455127/52367517-e7022980-2a11-11e9-8808-ca0f0e496abe.PNG)

**Comment by BeccaBroek** [comment]
@gtmills Can you give more detail on what needs to be fixed here? Think I'm missing some context

**Comment by gtmills** [comment]
@BeccaBroek The light gray should extend all the way to the right. Also I think we are cutting off properties in the drop downs, if you select a inventory item with a lot of properties, you should be able to see this.

**Comment by BeccaBroek** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/18412/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/18412 merged
