### ISSUE TITLE
Implement pldm-requester-tool

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#380]
This tool is an PLDM client (requester), and covers two flow paths :
a) in-band : It runs on the BMC, and targets the BMC's responder function. Since the responder and requester functions in this case are both on the BMC. the tool can just rely on IPC (for e.g D-Bus).
b) out-of-band : runs on the BMC, but targets another PLDM device over a connected physical channel.

FYI @tomjoseph83 @jinuthomas.

**Comment by dkodihal** [comment]
We think three use-cases are of interest :
a) The tool running on the BMC, targeting BMC as a PLDM responder.
b) The tool running on the BMC, targeting remote PLDM device as a PLDM responder.
c) The tool targeting the BMC as a PLDM responder over the network.

a) is of immediate priority. @tomjoseph83 and @jinuthomas are working to send out a design template to the mailing list.

For a), D-Bus can be the IPC of choice between the pldm tool and the pldm daemon on the BMC. The tool here is like any other PLDM requester app sending a D-Bus message to the daemon to have it respond to a PLDM message. The daemon will emit a D-Bus signal indicating the response.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by lkammath** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/22942/ 

Code is under review

**Comment by lkammath** [comment]
Integrated and available in master. so closing it

**Comment by rfrandse** [comment]
refresh
