### ISSUE TITLE
Network(IPV6): Populate the D-Bus objects for Linklocal local addresses

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#383]
-> Create the D-bus Object having the link-local addresses.
-> Address Origin property should tell that it is link-local address.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
seems this functionality is already working so closing this issue.
