### ISSUE TITLE
Network(IPV6): Allow multiple default gateways

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#387]
OpenBMC supports that IPv4 and IPv6 can be enabled at a time
so there can be defualt gateway for ipv4 as well as for Ipv6.

Currently, the system configuration supports only a single gateway.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/17901/
