### ISSUE TITLE
Network(IPv6): DUID Support.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#389]
DUID based solution should work now, Earlier it was a problem as the mac address based solution was not working with DUID.
 
Seems now we can use DUID based solution if we configure DUID type=linklayer.
 
Now systemd-networkd provided a fix couple of months back, Please find the following issue for reference.
 
https://github.com/systemd/systemd/issues/9805
 
Seems also need to make the changes in the D-bus interface to get the DUID type.

The following side effect may come if the DUID type is selected other then Link layer.

Side effect: Need to identify that what could be break with this, eg external application which depends on the mac address based IP address

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by trajeswaran** [comment]
Resolved by : https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/21964

**Comment by rsnair** [comment]
Changing it back to original sizing. This was put on hold. Will have to resume and revalidate if this issue is addressed

**Comment by sunharis** [comment]
Out of scope
