### ISSUE TITLE
Network(IPV6): Create Interface should return the D-Bus object ID.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#391]
Currently, the create interface doesn't return the Object identifier, with this story it should return the object identifier.
This identifier should be consistent even if the service gets restarted due to any reason.
eg :- IP1 has some identifier id1
        IP2 has some identifier id2
now if network service gets restarted so both IP should get the same identifier.
Currently, the identifier is a hash of properties which doesn't allow to change the property value as if the property value gets change, Object Identifier will get change.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by raviteja-b** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/19754

**Comment by rfrandse** [comment]
refresh
