### ISSUE TITLE
HMC-BMC Requirement specification

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#393]
The outcome of this story is the requirement doc which is being discussed with HMC team and we have agreed on for phase1.
This doc will cover the requirement for below areas
=> Discovery
=> Connection Management
=> Save Area
=> Lock Management
=> VMI configuration.
=> Dump Management
=> Firmware Update

**Comment by ratagupt** [comment]
Assign it to Sunitha Harish.

**Comment by ratagupt** [comment]
First draft have been uploaded on the internal IBM box folder.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by sunharis** [comment]
The document is available at https://ibm.ent.box.com/file/400939629547

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
we can close this as it is done.
