### ISSUE TITLE
Login and Overview layout is off when using Safari 

### ISSUE THREAD

**Issue by BeccaBroek** [ibm-openbmc/dev#396]
When using Safari, the login page and system overview page layout is off.

<img width="1680" alt="screen shot 2019-02-08 at 10 11 58 am" src="https://user-images.githubusercontent.com/26717697/52492311-877d5880-2b8e-11e9-80fa-e1b0e838f66e.png">

<img width="1586" alt="screen shot 2019-02-08 at 10 12 09 am" src="https://user-images.githubusercontent.com/26717697/52492366-aa0f7180-2b8e-11e9-8ee7-b407b0d1ff6d.png">

**Comment by BeccaBroek** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/18234/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/18234 merged
