### ISSUE TITLE
Implement multipart transfer

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#398]
Implement a common API/framework to enable multipart transfer and checksum validation of PLDM commands. Also enable multipart transfer for already implemented PLDM commands.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Low-level design details :

- Provide a maximum transport MTU runtime configurable field to pldmd

- Define a `class MultiPartResponse` with following APIs
	- `const split(response& buffer);`
        - `virtual nextEntrySize() = 0;`
	- implementation for eg `class GetVersionMultiPartResponse` will implement nextEntrySize() (see algorith below)
	- return list of tuple(start offset into buffer, length)

- Define a `class MultiPartTransferMgr` with the following APIs
	- `split(mctp eid, pldm type, command code, instance id, response&& buffer)`
                - Take ownership of the buffer
		- daemon to call this before sending each response
		- if response.size() <= maxMTU, return back response as is : tuple(start_and_end, 0, response.size()), don’t store anything.
		- if response.size() > maxMTU, enter switch case on (pldm type bitwise-OR command code)
			- if no split handler, throw an exception
			- invoke handler split
			- assign data transfer handle and transfer flag for each tuple entry returned by handler
			- store internally the buffer and map dataTransferHandle : tuple(transfer flag, start offset, length)
			- return tuple(data transfer flag, start offset, len)
	- dataTranserHandle(mctp eid, instance id)
		- generate unique id (eid bitwise-OR instance id bitwise-OR incrementing uint16)
	- next(dataTransferHandle, transfer op flag)
		- daemon to call this on each request
		- throw exception if dataTransferHandle is 0
		- if dataTransferHandle exists, pop out entry from tuple list, if tuple empty, erase entry from map
		- return tuple(buffer&, cc, data transfer flag, start offset, len)
		- throw exception if dataTransferHandle not found or empty

- Caller : use vectored I/O to write response


Multipart split() algo :
```
buffer += sizeof(cc) + sizeof(transferHandle) + sizeof(transferFlag)
maxMTU -= sizeof(cc) + sizeof(transferHandle) + sizeof(transferFlag)

start = buffer.start()
end  = buffer.end()
curr = start;


tuple<offset, len> tup{};

while ((end - start) >= maxMTU) {
  nextSize = curr;
  while((nextSize - start) < maxMTU) {
    curr = nextSize;
    nextSize += nextEntrySize(buffer&, curr);
  }
  tup.push_hack((start, curr - start));
  start = curr;
}
if (end - start) {
  tup.push_back((start, end - start));
}
```

**Comment by jk-ozlabs** [comment]
Wouldn't it be somewhat simpler to do the reassembly at the MCTP layer? We already have this implemented in libmctp, and the algorithm to do so is quite straightforward.

Is there a particular reason why this needs to be done within the PLDM components?

**Comment by dkodihal** [comment]
@jk-ozlabs I can think of two reasons to do this in PLDM :

- the lack of packetisation and reassembly in a certain MCTP implementation
- it's in the PLDM spec :)

**Comment by jk-ozlabs** [comment]
Sounds like implementing packetisation in that MCTP implementation would be a much better approach then.

(rather than having to implement packetisation in both MCTP and PLDM everywhere...)

**Comment by lxwinspur** [comment]
Currently, we don’t need to do this task.
