### ISSUE TITLE
GUI: Design: TPM fault sensor

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#403]
## Team
**SME TPM**: Nick Bofferding (BMC), Cris Engle (PHYP), @devenrao (FSP)
**DR**: @nicoleconser 
**UX**: TBD
**FED**: TBD

## Description
`"/xyz/openbmc_project/control/host0/TPMEnable"`

## TPM Fault Sensors Questions
1. Is this related to the following ASMi panels?
2. Do we need these to enable the sensors?
- ASMI Security > TPM Required Policy
- ASMI System Config > Virtual Trusted Platform Module (vTPM) configuration 
- Sensors panel (GUI needs table refactoring)

## Use Case
As a user, I need a TPM sensor to check the 'health' of the TPM (a FRU) to indicate when I need to replace it. It is also important because it works in tandem with the TPM required policy and when that kicks in, there would be functions not available and I'd like to know why. 
Usually, I always want to booth with the TPM unit functional because it is a security related topic that stores passwords, certificates, encryption keys. However, if the TPM sensor indicates that the TPM is not properly functioning and I still want to boot up, I can disable the TPM required policy and the system will be able to boot regardless of the TPM hardware itself not working. 

## InVision Prototype
TBD

## Design Issues
TBD

## Development Issues
* https://github.com/openbmc/openbmc/issues/3072
* TPM FRU Support: https://github.com/ibm-openbmc/dev/issues/238
* Support for a host TPM Sensor: https://github.com/ibm-openbmc/dev/issues/1010

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
This is a lower priority since we have the ability to turn off TPM in the event it is bad, the user can run the command line function to turn off the TPM.

**Comment by jandraa** [comment]
This should be handled in the same pattern that has been established by other FRU components in the GUI; need to determine what other FRUs exist and how they are treated.

**Comment by jandraa** [comment]
@nicoleconser 

**Need to understand the general use case** 
- How do users expect to be alerted that the TPM is nonfunctional? (and other FRUs)
- What other functions are related to TPM and how? Think of a time you were trying to complete a task dealing with TPM, what other functions did you have to interact with and what were you trying to do? (For each, sensor, virtual TPM, and required policy) 
- Tell us about a time you needed to clear the TPM, what did you need to do and why? (potentially ask about clearing keys) 


**What if the sensor only works during boot** 
- Why is it important to know that the TPM is not functioning? 
- What is the impact of only being able to know that the TPM is functional during boot? and would it be worth it at that point?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
We know that we can only test for fault at boot time. This has been pushed out to a later release, but we have added #590 that adds a toggle for booting with or without the TPM enabled.

**Comment by derick-montague** [comment]
Will not be in GUI
