### ISSUE TITLE
GUI: Power Supply redundancy

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#405]
```$ curl -b cjar -k -H "Content-Type: application/json" -X PUT https://${bmc}/xyz/openbmc_project/control/power_supply_redundancy/attr/PowerSupplyRedundancyEnabled -d '{"data": 1}'```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@spinler - It was briefly discussed today. It seems that you didn't believe this needed any GUI work when you talked with @susantjasinski?

**Comment by spinler** [comment]
Yea.  Our discussion was that this isn't something a user can change, so it wouldn't need to go into the GUI.

**Comment by derick-montague** [comment]
@gtmills - I am closing this story since it doesn't require any GUI work.
