### ISSUE TITLE
eBMC GUI : Factory Configuration

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#406]
## Stakeholders
**SME**: @anoo1 

## Overview
There are three functions included in "Factory Configuration"
- **Back up & Restore Host / Server Configuration** --> need to confirm value to customers (if low, don't include in GUI) 
- **Back up & Restore BMC Configuration**  --> need to confirm value to customers (if low, don't include in GUI) 
- **Reset to Factory Configuration**  --> high value to Support (needed in GUI); need to confirm if user will have options on what to reset 

## Use Case
This page allows you to:
- Select the specific configuration items to be backup in case of `Backup Configuration`
- Will allow to restore the configuration in case of `Restore Configuration`.
- User can reset the system as a complete reset or reset partitions only

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ryanarnell** [comment]
This might move to P10 timeframe (possibly GA2). 
"No one is really asking for it, but we're trying to get up to functional equivalency w/ AMI & Supermicro. The alternative is clunky but it does work."

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Looks like this is moving out further. @gtmills which milestone should we change it to?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by nicoleconser** [comment]
Should this page also allow the user to **reset to factory configuration**? @gtmills @derick-montague

**Comment by derick-montague** [comment]
> Should this page also allow the user to **reset to factory configuration**? @gtmills @derick-montague

I assume that is a design goal that would be determined by #1472.

**Comment by nicoleconser** [comment]
Ah - missed that - just looked at the description on this epic page and didn't see any mention of it. **Reset to factory configuration** is a menu item in ASMI, so wanted to make sure it didn't get lost. Looks like it's covered!

**Comment by gtmills** [comment]
Reset to factory configuration Redfish API is there today. I think there is still some question if Backup and Restore makes eBMC.. 
Backup and Restore allows the user to download a file of their settings and restore from it.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by nicoleconser** [comment]
@gtmills I realize we are still deciding if this is even going into the first release (I'll be asking customers about this to understand the value) — but can you help me understand why the [Gerrit Design Doc](https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/18163/1/designs/backup-and-restore.md) for this only mentions a **BMC** configuration backup/restore, but no mention of a **server/host** configuration backup/restore? I thought the ASMI Backup & Restore functionality covered both.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
From https://github.com/ibm-openbmc/dev/issues/2520

>    would we perform the BIOS reset first, wait for it to complete, then initiate the BMC reset, then reboot the BMC

Yeah, that makes sense to me. The BMC reset includes a reboot of the BMC already. https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32991

So the GUI doesn't need to call a reboot, just warn the user, A reboot will happen.

Should warn the user on all of these, that they will lose network, user data or PHYP partition information or both. Only do this if you are sure you know what you are doing.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
