### ISSUE TITLE
GUI: Add IPV6 to network page

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#408]
## Expected Dates
- [ ] UX: 3/20/19
- [ ] Backend: 6/13/19
- [ ] FED: 7/11/19

## Stakeholders
**SME**: @ratagupt 
 **DR**: @nicoleconser 
**UX**: @jandraa 
**FED**: 

## Overview
https://github.com/ibm-openbmc/dev/issues/407 is the new network design. This is a different story than https://github.com/ibm-openbmc/dev/issues/407. This story is just adding IPV6 support to the network page. These are different issues since they are slated for different milestones. 

## InVision Prototype
---

## Design Issue
* https://github.com/openbmc/phosphor-webui/issues/7

## Development Issue
* **Error Instances**: https://github.com/openbmc/phosphor-webui/issues/14
* **Feature Updates**: https://github.com/openbmc/phosphor-webui/issues/15

## Resources

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@gtmills @jandraa and I believe the use case of this story is to just add the IPV6 support. IF that is correct, @jandraa will you please add either a link to InVision or a screen shot of the existing layout with IPV6 support to the resources section in the story description. It will be ready for  the `Design Sign-off Needed` label and moving it to `In Plan` so a FED can pick it up.

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@gtmills  - Can you help us understand the scope of work needed here. Based on various feedback from users, IPV6 is not being used right now. We are conducing more research, but I don't think this is something we need to focus on for 9.4.1.

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
So far in our Sponsor User testing, none of the users are utilizing IPV6. The design team is still researching.

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Can we push the milestone out to one of these milestones 9.5.x or 9.4.99?

**Comment by derick-montague** [comment]
This issue will be included as part of #407.

**Comment by mzipse** [comment]
Work is moved to GA2.

**Comment by derick-montague** [comment]
Reopening for GA2 work

**Comment by derick-montague** [comment]
[In depth conversation in Discord starting on 3/03/21](https://discord.com/channels/775381525260664832/776550056391606352/816854612744208384)

Summary: If backend is in place it can be implemented by the community. It is low priority for us.

**Comment by dixsie** [comment]
FED work being sone in #2130
