### ISSUE TITLE
Redfish: Meet OCP Server Hardware Management Redfish Interface

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#409]
[OCP Server Mgmt Interface v0.2.1.pdf](https://github.com/ibm-openbmc/dev/files/2862418/OCP.Server.Mgmt.Interface.v0.2.1.pdf)

OCP Server Hardware Management is a superset of the OCP Baseline Hardware Management

![ocp-server-hardware-management-refish-interface](https://user-images.githubusercontent.com/5455127/52748919-67de9980-2fad-11e9-92e8-529afe77ef29.PNG)

**Comment by gtmills** [comment]
I think 40 is a high estimate but until we determine how to do some of the properties, will stay with it. 

The properties in OCP Server Hardware Management that aren't in our old APIs and that I think will cause use the most work:

    DIMM's SizeMiB (Hostboot has this data but would need them to send it down)
    EthernetInterface's SpeedMbps
    PowerCapacityWatts ("total amount of power available to the chassis for allocation", maybe we could get this from the power supplies? )
    Fan Redundancy (We have logic for shutting down the system if not enough functional fans but we don't expose this in the APIs, e.g. number of fans needed).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
