### ISSUE TITLE
Design for extensive PEL capture data

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#410]
Somehow allow error log creators to capture whatever data when creating an error log and have it added to a PEL in a user data section when a PEL is requested.

For sure we need to add traces to PELs, so when a log is created a mini/complete snapshot of the journal can be taken and saved away, and added to the PEL later.

We can make use of phosphor-debug-collector to have it collect whatever we need on certain/all error logs, and then somehow later pull those sections into error logs.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Scope this to just how users can add their own blobs of data to the user data sections in a PEL via the phosphor-logging API.  Right now leaning toward passing in a file path.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
There was an email on the list about passing file descriptors to pass large amounts of data.  If we go that direction, we could:

Create a new D-Bus method to create an event log that also has an argument to take 1 or more FDs:
```
CreateWithDebugData(or whatever)
parameters:
    ...
    -name: DebugFiles
     type: array[unixfd]
```
phosphor-logging would simply pass that on to the PEL plugin.  The PEL plugin would read those and add the data as separate UD sections.  Would still need to figure out how to specify the format type so that the correct parsers could be invoked when needed.

Also, sdbusplus does not yet support closing FDs after it passes them on D-Bus.  Something here would need to be changed:  https://github.com/openbmc/sdbusplus/blob/master/tools/sdbusplus/templates/method.mako.prototype.hpp.in#L121

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/28482

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/28482 merged
