### ISSUE TITLE
Create PEL retrieval D-Bus APIs

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#415]
Create an app in openpower-logging that will do the openbmc error log -> PEL conversion when asked to via D-Bus methods:
* GetAllPELs
* GetPEL(id)

These methods need to be defined in openpower-dbus-interfaces

**Comment by bradbishop** [comment]
On Thu, Feb 14, 2019 at 12:11:48PM -0800, Matt Spinler wrote:
>Create an app in openpower-logging that will do the openbmc error log -> PEL conversion when asked to via D-Bus methods:
>* GetAllPELs
>* GetPEL(id)

Are these functions DBus methods?  What sorts of applications would be
calling those?  Callback handlers for OEM endpoints of the various end
user interfaces like Redfish or IPMI (or whatever the flavor of the year
is)?

**Comment by spinler** [comment]
@bradbishop yep

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Going to close this for now as I'm not sure if we're going to be using D-Bus, and the fewer issues we have open the better. Will reopen if necessary.

**Comment by mzipse** [comment]
refresh
