### ISSUE TITLE
Return host PELs along with BMC converted PELs when PELs are requested

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#416]
when the host, or an OEM Redfish cmd, or whatever, asks the BMC to get all of the PELs, aside from returning all of the PELs that are on-the-fly converted to PELs from OpenBMC logs, we also need to return the PELs that the host (hostboot, opal, PowerVM, etc) had sent down.

**Comment by jayeshmpatel** [comment]
You may have to manage/handles PELs that are already reported/acknowledged by Host/HMC so you don't report it again to Host/HMC and then reported/acknowledged PEL can be deleted/purged from BMC if need more storage.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Closing this.  Tracking this elsewhere.

**Comment by mzipse** [comment]
refresh
