### ISSUE TITLE
Implement PNOR update in the Software interfaces

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#417]
Implement the org.openbmc.control.Flash.service that updates the PNOR in the xyz.openbmc_project.Software interfaces.

The first step is to support a straight PNOR update using the libflash library that the org Flash service currently uses.
Afterwards, the other features like signature validation, factory reset, etc, can be investigated on how to implement them.

**Comment by rfrandse** [comment]
refresh

**Comment by mine260309** [comment]
The code in `openpower-pnor-code-mgmt` is based on ubifs, and has too many assumption of ubifs based PNOR, e.g.
1. The existing pnor version id is got from ubifs volume's name (for example, `ubinfo -d 8 -n 1` we got `pnor-rw-a378a49b`)
2. The whole process of `item_updater` is based on ubifs.
3. The `activation` is based on ubifs.

So it is a bit hard to "split" the code update and filesystem.

To make it support static layout PNOR, I would suggest:
1. Modify `generate-squashfs` script to make it generate a static tarball, containing MANIFEST and whole pnor image, possibly compress it to reduce the size.
   If we want to support image verification, the signature is done based on the whole pnor.
2. Re-write (or more precisely, add a new) `item_updater` for static layout pnor, that handles the PNOR version, etc.
3. In `activation.cpp`, split the filesystem and activation, similar to BMC code update;
   Or just re-write (add a new) activation for static layout if the above is too hard.
4. Re-use other code.

Then for PNOR version and code update, the similar process is followed:
1. PNOR version is extracted from `VERSION` partition via libflash;
2. To do code update, a tarball is uploaded to `/tmp/image`
3. The `MANIFEST` and pnor is extracted, and activation is created;
4. Use libflash (or pflash) to flash the pnor.

**Comment by mine260309** [comment]
I am starting to work on this task.

**Comment by rfrandse** [comment]
refresh

**Comment by mine260309** [comment]
The functions like PNOR version, code update, factory reset are implemented and submitted to gerrit, patches series starts from:
https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-pnor-code-mgmt/+/18747/

The image verification is not done yet.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mine260309** [comment]
The image verification is implemented at https://gerrit.openbmc-project.xyz/c/openbmc/openpower-pnor-code-mgmt/+/19324

**Comment by rfrandse** [comment]
refresh

**Comment by mine260309** [comment]
All the changes are merged.
@anoo1 Please close this issue.

**Comment by anoo1** [comment]
Thanks @mine260309 !
