### ISSUE TITLE
GUI: Design: Firmware Update -  Limited Redfish / Single File Upload

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#420]
## Expected Delivery Dates
- [ ] 09/17/19 - UX - Sprint 2019-19
- [ ] 10/15/19 - Backend - Sprint 2019-21
- [ ] 11/12/19 - FED - Spring 2019-23

## Stakholders
**BMC SME**: @anoo1 
**PHYP SME**: BJ Vette
**RAS SME**: Justin Thaler
**DR**: @nicoleconser 
**UX**: @jandraa 
**FED**: TBD

## InVision Prototype
For this story : eBMC prototype (single file) - https://ibm.invisionapp.com/share/4XNZ0JAMJ7B#/319207131_4-8-S-2A_TFTP_Server

Related: oBMC prototype (two files) - https://ibm.invisionapp.com/share/4XNZ0JAMJ7B#/319212821_4-8-D-1_Home

## Design Issue
https://github.com/openbmc/phosphor-webui/issues/53

## Development Issue
https://github.com/ibm-openbmc/dev/issues/181

## References/Resources
- feature discovery folder: https://ibm.box.com/s/wvt99ss4luxq3w86atl9p37bv8fe0pdw
- user research synthesis*: https://ibm.box.com/s/1b6yh7qf9ja7jf80v4xy82c12y4xv50p
- error messages documentation: https://github.com/openbmc/phosphor-dbus-interfaces/blob/ddc9e9f9d6ed0282ec6c1421a706b45f3c09ebcc/xyz/openbmc_project/Software/Activation.interface.yaml#L16

*This folder is restricted in accordance with GDPR guidelines.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dixsie** [comment]
@jandraa Can we add a last reboot time to this page like we have on the BMC reboot page? I think it will help clear up some confusion for the user when they activate and reboot an image as to whether the BMC rebooted. When they refresh the page they will be able to see the last reboot time. I think that would make sense for activate and reboot the host as well to have the last power operation for the server/host. @derick-montague 

<img width="1335" alt="Screen Shot 2019-05-14 at 2 07 55 PM" src="https://user-images.githubusercontent.com/26472611/57725305-6bd49300-7652-11e9-9d4e-f5d9e5649f0c.png">
<img width="1553" alt="Screen Shot 2019-05-14 at 2 08 39 PM" src="https://user-images.githubusercontent.com/26472611/57725316-70994700-7652-11e9-9f7c-24382b934d11.png">

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jandraa** [comment]
From @anoo1 : The discussion about a single file for both the server and BMC firmware pushes this out to Rainier.

Do we want to include Dixsie's suggestion about last power operation before then?

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
> Do we want to include Dixsie's suggestion about last power operation before then?

I think we leave it for now since that design doesn't work and the current design shows the current versions of each section already.

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@jandraa - Can we update the InVision prototype link. It opens to LDAP and I don't see update firmware in the sections list.

**Comment by jandraa** [comment]
Just updated. The goal is that both the BMC and server firmware will be updated with a single file. This design does not reflect that since it is old and we haven't picked it up again.

**Comment by dixsie** [comment]
> > Do we want to include Dixsie's suggestion about last power operation before then?
> 
> I think we leave it for now since that design doesn't work and the current design shows the current versions of each section already.

It looks like each section shows when the firmware was activated/released, not when it was rebooted. The user has the option to reboot after activating an image. How will the user know they rebooted after activating the image if they choose that option?

**Comment by jandraa** [comment]
Updated designs to support single file uploads are now reflected in InVision

**Comment by derick-montague** [comment]
@jandraa - FYI in the eBMC content inventory spreadsheet, [eBMC Features worksheet, item 4.11.3: HMC Firmware Update](https://ibm.ent.box.com/file/455779315260)

I don't think we are planning to have this functionality in the HMC menu? Can you help me verify that. I also see that there is a different BMC owner. It has @ratagupt instead of @anoo1. My thought is that this functionality is part of the Firmware update view when the system is HMC managed.

**Comment by jandraa** [comment]
Resolved by InVision prototype (see link in description above)
