### ISSUE TITLE
Run automated accessibility test on all panels

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#423]
## Overview
1. Use a combination of Deque's Axe tool and Lighthouse (Audit->Accessibility in Chrome)
2. Determine severity and complexity of violations
3. Resolve any issues with minimal impact to UI
4. Create issues for complex violations that require deeper discussion

## Screens to test
- [x] Login
- [x] Server Overview

### Server Health
- [x] Sever health -> Event log
- [x] Server health -> Hardware status
- [x] Server health -> Sensors

### Server control
- [x] Server control -> Server power operations
- [x] Server control -> Mange power usage
- [x] Server control -> Server LED
- [x] Server control -> Reboot BMC
- [x] Server control -> Serial over LAN Console

### Server configuration
- [x] Server configuration -> Network Settings
- [x] Server configuration -> SNMP Settings
- [x] Server configuration -> Firmware
- [x] Server configuration -> Date and time settings

### Users
- [x] Users -> Mange user accounts

#### Global
- [x] Main heading has attribute role value set to `heading`. 
Resolved by openbmc/phosphor-webui#76

This is an odd role to have since it is meant to replace `heading` elements like `<h1>, <h2>`, etc
**Solution**: 
Remove the role

![image](https://user-images.githubusercontent.com/1183515/53751175-503e5680-3e71-11e9-8ee8-f640b3e2135b.png)

#### Server Control -> Manage Power Usage
Resolved by openbmc/phosphor-webui#76

- [x] All form elements require a label
![image](https://user-images.githubusercontent.com/1183515/54480731-1a4a8c00-47fa-11e9-9f70-9395a7522ed9.png)

#### Server Configuration -> Network Settings
Resolved by openbmc/phosphor-webui#76

- [x] All form elements require a label
![image](https://user-images.githubusercontent.com/1183515/54481122-d312ca00-47fe-11e9-938c-34c7bb05d112.png)

- [x] Radio inputs with the same name attribute value must be part of a group
Resolved by openbmc/phosphor-webui#76

![image](https://user-images.githubusercontent.com/1183515/54481246-57198180-4800-11e9-8397-981aae486ca1.png)
**Solution**: Radio buttons need to be wrapped in a fieldset

#### Server Configuration -> SNMP Settings
Resolved by openbmc/phosphor-webui#76

- [x] Form elements must have labels
![image](https://user-images.githubusercontent.com/1183515/55685651-2e2b6e80-591e-11e9-9aee-846fc07348bd.png)

- [x] Elements must have sufficient color contrast
**Resolved by:** https://github.com/openbmc/phosphor-webui/issues/70
![image](https://user-images.githubusercontent.com/1183515/54481601-ca24f700-4804-11e9-9547-040866339ecf.png)

#### Server Configuration -> Firmware
**Resolved by:** https://github.com/openbmc/phosphor-webui/issues/70

- [x] Elements must have sufficient color contrast
![image](https://user-images.githubusercontent.com/1183515/54481715-73202180-4806-11e9-9a26-909521e58659.png)

#### Server Configuration -> Dave and Time Settings 
Resolved by openbmc/phosphor-webui#76

- [x] Form elements must have labels
![image](https://user-images.githubusercontent.com/1183515/54483838-cb681b00-4828-11e9-943d-d89e8212e580.png)

#### Server Health -> Hardware Status
Resolved by: https://github.com/openbmc/phosphor-webui/issues/76

- [x] Buttons must have discernible text
All dropdown arrows for expanding rows require an `aria-label` or visually hidden text to identify their action.
 **Solution**:
   - Add `aria-label` to describe action

#### Server Configuration -> Network Settings
Resolved by: openbmc/phosphor-webui#70

- [x] Elements must have sufficient color contrast
![image](https://user-images.githubusercontent.com/1183515/54481226-0013ac80-4800-11e9-9a31-55757dfd6d69.png)

#### Global
- [x] All page content must be contained by landmarks
This is related to the Main Heading critical issue.

  **Solution**: 
  Restructure markup to move the header functions in the the header element. Required CSS changes to accommodate this change.

#### Server Overview
Resolved by https://github.com/openbmc/phosphor-webui/issues/76

- [x] Heading levels should only increase by one
  - `<h3>Server information</h3>` follows an `<h1>` should be `<h2>`
  -  Use `<dl>` definition list to define the key value pairs model: 8335-GTG, etv

![image](https://user-images.githubusercontent.com/1183515/55298482-9ac0dd80-53f3-11e9-8edd-d7d0bef8c914.png)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
This issues is almost complete. There are only two remaining tasks that haven't been completed or in progress right now in phosphor-webui.

**Comment by rfrandse** [comment]
refresh
