### ISSUE TITLE
SVG icon validation

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#425]
Verify icons are accessible
- [ ] SVG content is either hidden or includes an appropriate aria-label
- [ ]  Icons using background images or glyphs are updated to use icon directive

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
This story will be about finding and converting all icons over to use the icon directive and removing all the implementations using background images.

**Comment by derick-montague** [comment]
This will not be an issue in the Vue rewrite and largely isn't an issue today.
