### ISSUE TITLE
Certificates: Root CA Certificate upload design

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#426]
Looking at the latest certificate management schema( DSP2046 Version 2018.3), not seeing any url's related  to well-known public CA certificates. 
Initiated discussion in Redfish forum.
https://redfishforum.com/thread/169/certificate-management-ca-upload?page=1&scrollTo=553
Need to look an option satisfy the openBM requirement  to upload the LDAP root CA certificates .
Also explore the option to install well-known CA certificates in openbmc .

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Community proposal available[here](https://lists.ozlabs.org/pipermail/openbmc/2019-April/016136.html)

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Issue related to the CA and intermediate certificate management proposal is tracked here https://github.com/DMTF/Redfish/issues/3207.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Implementation is in progress based on internal proposal. Closing this  issue now
