### ISSUE TITLE
LDAP: Extend the LDAP config schema to support new properties

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#428]
Extend the LDAP config to support the following Properties
1) Service Enabled
2) UserName attribute
3) GroupName attribute
Whether the LDAP service would be started or not it will depend on the "ServiceEnabled" property.
UserNameAttribute contains the LDAP server attribute name which contains the userName.
eg cn or uid may contain the username and similar for the groupName.

Following Task would be needed to implement this
Phosphor-Dbus-Interfaces
=> Extend the schema (https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/User/Ldap/Config.interface.yaml)

Phosphor-User_manager
=> Extend the support in phosphor-user-manager/ldap_config for the new properties
=> New properties should be persisted
=> UserNameattribute and group-name-attribute can be persisted in the nslcd.conf
=> ServiceEnabled property would be persisted through Cereal way.

**Comment by ratagupt** [comment]
Resolved By: 
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/18016/
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-user-manager/+/18551/
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-user-manager/+/18552/
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-user-manager/+/18553/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/18016 merged
