### ISSUE TITLE
Unable to configure new IP address on eth interface

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#429]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [prkatti1](https://github.com/prkatti1)**
_Thursday Jan 31, 2019 at 15:31 GMT_
_Originally opened as https://github.com/openbmc/bmcweb/issues/36_

----

Unable to configure new IP address on eth interface via redfish.
Following command is run:
}bash-4.1$curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"IPv4Addresses": [{"Address": "10.7.7.7","AddressOrigin": "Static","SubnetMask": "255.255.0.0","Gateway":"10.7.7.1"},{"Address": "x.x.x.x","AddressOrigin": "Static","SubnetMask": "255.255.255.0","Gateway":"x.x.x.1"}]}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

When we run to get configured results: it replaces link local address:
curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/
{
  "@odata.context": "/redfish/v1/$metadata#EthernetInterface.EthernetInterface",
  "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0",
  "@odata.type": "#EthernetInterface.v1_2_0.EthernetInterface",
  "Description": "Management Network Interface",
  "IPv4Addresses": [
    {
      "Address": "10.7.7.7",
      "AddressOrigin": "IPv4LinkLocal",
      "Gateway": "0.0.0.0",
      "SubnetMask": "255.255.0.0"
    },
    {
      "Address": "x.x.x.x",
      "AddressOrigin": "Static",
      "Gateway": "x.x.x.1",
      "SubnetMask": "255.255.255.0"
    }
  ],
  "Id": "eth0",
  "MACAddress": "x.x.x.x.x.x",
  "Name": "Manager Ethernet Interface",
  "SpeedMbps": 0,
  "VLAN": {
    "VLANEnable": false,
    "VLANId": 0

But on system using ip addr:
root@witherspoon:/tmp# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether x.x.x.x.x.x.x brd ff:ff:ff:ff:ff:ff
    inet 169.254.245.177/16 brd 169.254.255.255 scope link eth0
       valid_lft forever preferred_lft forever
    inet x.x.x.x/24 brd x.x.x.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::72e2:84ffxx:xx/64 scope link
       valid_lft forever preferred_lft forever
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1000

**Comment by rfrandse** [comment]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [prkatti1](https://github.com/prkatti1)**
_Thursday Jan 31, 2019 at 15:32 GMT_

----

@ratagupt FYI...

**Comment by rfrandse** [comment]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [prkatti1](https://github.com/prkatti1)**
_Friday Feb 01, 2019 at 06:56 GMT_

----

@edtanous could you Pls take a look into it.

**Comment by rfrandse** [comment]
<a href="https://github.com/edtanous"><img src="https://avatars0.githubusercontent.com/u/599897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edtanous](https://github.com/edtanous)**
_Saturday Feb 02, 2019 at 18:44 GMT_

----

Bad gateway makes it sound like bmcweb is crashing.  I don't have the time to look into it this moment, but it would help a lot if you could dump the logs from journalctl.

**Comment by rfrandse** [comment]
<a href="https://github.com/gkeishin"><img src="https://avatars2.githubusercontent.com/u/19584499?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gkeishin](https://github.com/gkeishin)**
_Monday Feb 04, 2019 at 03:43 GMT_

----

@prkatti1 Can u provide the data here for @edtanous to take a look. Thanks

**Comment by rfrandse** [comment]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [prkatti1](https://github.com/prkatti1)**
_Monday Feb 04, 2019 at 06:03 GMT_

----

@edtanous Pls find journald logs as requested.

Feb 04 05:55:27 witherspoon login[1187]: pam_unix(login:session): session opened for user root by LOGIN(uid=0)
Feb 04 05:55:27 witherspoon login[1412]: ROOT LOGIN  on '/dev/ttyS4'





Feb 04 05:56:25 witherspoon systemd[1]: Started BMC Redfish Server (bmcweb).
Feb 04 05:57:54 witherspoon bmcweb[1418]: terminate called after throwing an instance of 'nlohmann::detail::type_error'
Feb 04 05:57:54 witherspoon bmcweb[1418]:   what():  [json.exception.type_error.305] cannot use operator[] with a string argument with array
Feb 04 05:57:54 witherspoon nginx[1144]: 2019/02/04 05:57:54 [error] 1146#1146: *3 upstream prematurely closed connection while reading response header from upstream, client: xx.xx.xx.xx, server: 127.0.0.1, request: "PATCH /redfish/v1/Managers/bmc/EthernetInterfaces/eth0 HTTP/1.1", upstream: "http://127.0.0.1:8082/redfish/v1/Managers/bmc/EthernetInterfaces/eth0", host: "bmchost"
Feb 04 05:57:54 witherspoon systemd[1]: bmcweb.service: Main process exited, code=killed, status=6/ABRT
Feb 04 05:57:54 witherspoon systemd[1]: bmcweb.service: Failed with result 'signal'.
Feb 04 05:57:55 witherspoon systemd[1]: bmcweb.service: Service RestartSec=1s expired, scheduling restart.
Feb 04 05:57:55 witherspoon systemd[1]: bmcweb.service: Scheduled restart job, restart counter is at 1.
Feb 04 05:57:55 witherspoon systemd[1]: Stopped BMC Redfish Server (bmcweb).
Feb 04 05:57:55 witherspoon systemd[1]: Started BMC Redfish Server (bmcweb).

**Comment by rfrandse** [comment]
<a href="https://github.com/edtanous"><img src="https://avatars0.githubusercontent.com/u/599897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edtanous](https://github.com/edtanous)**
_Monday Feb 04, 2019 at 21:17 GMT_

----

This looks like it's in the area where we already have a patchset in progress.  Can you pull it down and try it?

https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/16596

**Comment by rfrandse** [comment]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [prkatti1](https://github.com/prkatti1)**
_Wednesday Feb 06, 2019 at 10:33 GMT_

----

@edtanous  CI build is not there anymore can u rebase ?

**Comment by rfrandse** [comment]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [prkatti1](https://github.com/prkatti1)**
_Thursday Feb 14, 2019 at 09:07 GMT_

----

@edtanous could you Pls update on this?

**Comment by rfrandse** [comment]
<a href="https://github.com/gkeishin"><img src="https://avatars2.githubusercontent.com/u/19584499?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gkeishin](https://github.com/gkeishin)**
_Thursday Feb 14, 2019 at 13:01 GMT_

----

@prkatti1 Can u bit bake image and run the test perhaps and confirm if it works

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18799/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/18799 merged
