### ISSUE TITLE
Unable to modify MAC address

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#430]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [prkatti1](https://github.com/prkatti1)**
_Friday Feb 15, 2019 at 11:12 GMT_
_Originally opened as https://github.com/openbmc/bmcweb/issues/43_

----

Unable to modify MAC address. Tried both PATCH and PUT methods.
PATCH gives 400 error
PUT gives 200 OK, but MAC address is not getting changed.

PUT method output:
bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X PUT -D put.txt -d '{"MACAddress": "x2:xx:xx:xx:xx:xx"}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/
bash-4.1$ cat put.txt
HTTP/1.1 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: DENY
Pragma: no-cache
Cache-Control: no-Store,no-Cache
Content-Security-Policy: default-src 'self'
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: IE=11
Server: iBMC
Date: Fri, 15 Feb 2019 10:53:45 GMT
Content-Length: 0

PATCH method:
bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"MACAddress": "x2:xx:xx:xx:xx:xx"}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/
{
  "MACAddress@Message.ExtendedInfo": [
    {
      "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
      "Message": "The property MACAddress is not in the list of valid properties for the resource.",
      "MessageArgs": [
        "MACAddress"
      ],
      "MessageId": "Base.1.4.0.PropertyUnknown",
      "Resolution": "Remove the unknown property from the request body and resubmit the request if the operation failed.",
      "Severity": "Warning"
    }
  ]
}bash-4.1$ cat patch.txt
HTTP/1.1 400 Bad Request
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: DENY
Pragma: no-cache
Cache-Control: no-Store,no-Cache
Content-Security-Policy: default-src 'self'
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: IE=11
Content-Type: application/json
Server: iBMC
Date: Fri, 15 Feb 2019 10:53:14 GMT
Content-Length: 481

**Comment by rfrandse** [comment]
<a href="https://github.com/ratagupt"><img src="https://avatars1.githubusercontent.com/u/15628264?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ratagupt](https://github.com/ratagupt)**
_Saturday Feb 16, 2019 at 04:33 GMT_

----

Hoping @prkatti1 you are using the local admin mac to change the mac address, I digged in the code and find that we don't have the support for PATCH of MAC Address.

**Comment by rfrandse** [comment]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [prkatti1](https://github.com/prkatti1)**
_Tuesday Feb 19, 2019 at 05:48 GMT_

----

@edtanous could you Pls take a look at it.

**Comment by rfrandse** [comment]
<a href="https://github.com/edtanous"><img src="https://avatars0.githubusercontent.com/u/599897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edtanous](https://github.com/edtanous)**
_Tuesday Feb 19, 2019 at 05:56 GMT_

----

The code is available to you.  Are you having trouble understanding it?  Having trouble putting together a patch to fix it?  I think ratagupt gave you some basic triage and his explanation seems to make sense to me.

I don’t know what’s going on here off the top of my head, if that’s what you were looking for.

**Comment by rfrandse** [comment]
<a href="https://github.com/ratagupt"><img src="https://avatars1.githubusercontent.com/u/15628264?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ratagupt](https://github.com/ratagupt)**
_Tuesday Feb 19, 2019 at 10:17 GMT_

----

@edtanous seems bmweb doesn't have support for PATCH of MAC address(even for local admin mac), we would be pushing the code for review next week.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18844/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/18844 merged
