### ISSUE TITLE
Unable to configure hostname using redfish

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#431]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [prkatti1](https://github.com/prkatti1)**
_Friday Feb 15, 2019 at 11:16 GMT_
_Originally opened as https://github.com/openbmc/bmcweb/issues/44_

----

PATCH is giving 405 method not allowed.
PUT is giving 200OK but hostname is not getting changed.
bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"HostName": "bmcbmc"}' https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol
Method Not Allowedbash-4.1$ cat patch.txt
HTTP/1.1 405 Method Not Allowed
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: DENY
Pragma: no-cache
Cache-Control: no-Store,no-Cache
Content-Security-Policy: default-src 'self'
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: IE=11
Server: iBMC
Date: Fri, 15 Feb 2019 11:05:15 GMT
Content-Length: 18

bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X PUT -D put.txt -d '{"HostName": "bmcbmc"}' https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol

bash-4.1$ cat put.txt
HTTP/1.1 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: DENY
Pragma: no-cache
Cache-Control: no-Store,no-Cache
Content-Security-Policy: default-src 'self'
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: IE=11
Server: iBMC
Date: Fri, 15 Feb 2019 11:05:47 GMT
Content-Length: 0

bash-4.1$  curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Managers/bmc/NetworkProtocol
{
  "@odata.context": "/redfish/v1/$metadata#ManagerNetworkProtocol.ManagerNetworkProtocol",
  "@odata.id": "/redfish/v1/Managers/bmc/NetworkProtocol",
  "@odata.type": "#ManagerNetworkProtocol.v1_1_0.ManagerNetworkProtocol",
  "Description": "Manager Network Service",
  "HTTPS": {
    "ProtocolEnabled": false
  },
  "HostName": "witherspoon",
  "IPMI": {
    "Port": 623,
    "ProtocolEnabled": false
  },
  "Id": "NetworkProtocol",
  "Name": "Manager Network Protocol",
  "SSH": {
    "Port": 22,
    "ProtocolEnabled": false
  },
  "Status": {
    "Health": "OK",
    "HealthRollup": "OK",
    "State": "Enabled"

**Comment by rfrandse** [comment]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [prkatti1](https://github.com/prkatti1)**
_Tuesday Feb 19, 2019 at 05:48 GMT_

----

@edtanous could you Pls take a look at it.

**Comment by rfrandse** [comment]
<a href="https://github.com/edtanous"><img src="https://avatars0.githubusercontent.com/u/599897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edtanous](https://github.com/edtanous)**
_Tuesday Feb 19, 2019 at 06:04 GMT_

----

Are you having trouble understanding the code for this functionality?  I don’t see any specific requests on what you need help with, so I’m at a bit of a loss on how I can help you triage this without just debugging it for you.
I don’t know any specifics of how this code works beyond just looking at the code.

**Comment by rfrandse** [comment]
<a href="https://github.com/ratagupt"><img src="https://avatars1.githubusercontent.com/u/15628264?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ratagupt](https://github.com/ratagupt)**
_Wednesday Feb 20, 2019 at 04:15 GMT_

----

@edtanous https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/network_protocol.hpp
Seems we need to mark it as an enhancement as we don't have PATCH support here.

I would we working with somebody from IBM to work on it.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18862/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/18862 merged
