### ISSUE TITLE
Refactor skeleton op-power-ctl to use gpio lines

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#432]
Right now that code uses /sys/class/gpio, which prevents some other code from accessing those GPIOs with the newer gpio line kernel APIs.  As /sys/class/gpio is the 'old way' of doing it, we'll update the skeleton code.

**Comment by amboar** [comment]
I 100% support this. Please take a look at libgpiod:

https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/skeleton/+/19158
