### ISSUE TITLE
Fan Control: Attempt PID control on wspoon

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#433]
Configure and build an image without phosphor-fan-presence/control replacing it with phosphor-pid-control. This will require understanding of pid control's configuration setup and attempting to add each functional area of the current fan control to pid control's config noting which are capable or not. It is expected that not all functionality will be available. Also the pid algorithm itself should be characterized against the current fan control application used.

**Comment by mine260309** [comment]
Some information I could share:
* A while ago (maybe one year ago?) I tried phosphor-pid-control on Romulus.
* Its basic function works fine, e.g. fan speeds are increased when the temperature exceeds the set-point, and decreased vice versa.
* Some functions are missing, e.g. it does not support to configure sensors that are missing. For example, if we configure all 24 cores, and the CPU on the systems only has 16 cores, phosphor-pid-control will fail to start due to unable to find the missing sensors.
   It was discussed in https://lists.ozlabs.org/pipermail/openbmc/2018-June/012030.html thread.
   Not sure how it works now though.

**Comment by msbarth** [comment]
@mine260309 Thanks for the info.

I think I recall the discussion about using it on Romulus but I dont remember what the reasons were for not at the time, so this helps. I'm going to try and note how things go here as I get things working or not. I'm thinking, like you said, the basic function will work, however the extended specific conditions that we adjust fan speeds for may be abit more difficult to get configured/working or not handled at all (e.g. speed changes allowed only after OCCs are active).

**Comment by amboar** [comment]
> speed changes allowed only after OCCs are active

Isn't this a matter of configuring the set-point before and after the OCCs are active?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Here's an initial list of limitations I've discovered while prototyping PID control on a wspoon attempting to replicate similar thermal functionality. This is not to be a complete list nor a concrete determination to never use pid control, this is just a list of notes for findings that would seem to require enhancements to achieve or that I didn't understand how to configure it in the json.

- Dbus RPM target (add if required)
- Speed change/failsafe due to fan failure/missing
- Speed change/failsafe due to service failures
- Use of sensors already on Dbus by another service (i.e. hwmon provided sensors)
   - Using sysfs must have all sensors available when started
- Faulted temp sensors causing specific speed changes
- Water vs Air cooled config differences
- Thermal mode property altering control parameters
   - No configurable actions based on property state (hosted by phosphor-settingsd)
- Update/detail documentation
   - 'detail' documentation refers to what seems some parameters have different meanings by type
- “Precondition” met prior to speed changes (i.e. OCCs active)
   - `setpoint` only supports type double
- Unable to slew(dec/inc too fast within pid) with output limits
- Adjust min/max fan speeds based on sensor(s)
   - May require external app that restarts pid with different json with adjusted min/max speeds
- Not able to enter failsafe when set of sensors are unbound
   - OCC going inactive, removing all temps it provides doesnt seem to trigger failsafe

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Investigation and time constraints conclude that we are not able to switch to pid control at this time from the initial list of limitations discovered.
