### ISSUE TITLE
phosphor-objmgr: Refactor and unit tests

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#434]
This story tracks refactoring objmgr code in a way to make it more testable and then writing the gtest unit tests for it.

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-objmgr/+/18733/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-objmgr/+/18733 merged
