### ISSUE TITLE
phosphor-objmgr: Use InterfacesAdded in place of Introspect

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#435]
Moving to using InterfacesAdded to collect interface information. This will be more efficient and close the race conditions caused by introspection.

https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-objmgr/+/17837/ is the base for this.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Unfortunately, testing showed that this optimization was not working as expected and it appeared to be a limitation of what was provided on d-bus.
