### ISSUE TITLE
GUI: Change OpenBMC logo to "Built on"

### ISSUE THREAD

**Issue by krtaylor** [ibm-openbmc/dev#436]

**Comment by krtaylor** [comment]
Use "built on" logo to make it clear that the product is being built based on OpenBMC

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
We do this downstream already. 
![ibm-branding-login-page](https://user-images.githubusercontent.com/5455127/53349261-5c12a180-38e2-11e9-9d0d-d7d516fbd054.PNG)
