### ISSUE TITLE
GUI: Change login screen to product template

### ISSUE THREAD

**Issue by krtaylor** [ibm-openbmc/dev#437]
Something like: <Your product firmware name here> in the info on the left of the login

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
We do this downstream already. 
![ibm-branding-login-page](https://user-images.githubusercontent.com/5455127/53349298-6fbe0800-38e2-11e9-9d89-2039ca50a2c7.PNG)
