### ISSUE TITLE
Association management

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#438]
Need to find a way to add inventory<->sensor associations and inventory<->LED associations

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Adding the functionality into phosphor-inventory-manager to be able to define associations to other d-bus paths based on a JSON definition.

Also, going to add functionality to the mapper to have the actual association objects match the lifetime of the endpoint paths.  For example, if /pathA creates an org.openbmc.Association object with [foo, bar, /pathB] as the property, then the mapper will make sure that pathA/foo and pathB/bar only exist when both /pathA and /pathB exist.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-ibm/+/19175/
A readme for the functionality is at https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-inventory-manager/+/18966/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/19175 merged
