### ISSUE TITLE
Redfish(Network): How to delete the IP addresses?

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#441]
<a href="https://github.com/ratagupt"><img src="https://avatars1.githubusercontent.com/u/15628264?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ratagupt](https://github.com/ratagupt)**
_Thursday Feb 21, 2019 at 08:50 GMT_
_Originally opened as https://github.com/openbmc/bmcweb/issues/48_

----

In redfish ipv4addresses(array type) is the property under ethernet interface resource, So user should be allowed to add and deletion of certain ip addresses.
I could have seen that user can not delete the ip address as we have the following condition which stops deleting the IPaddress.
```    void handleIPv4Patch(
        const std::string &ifaceId, const nlohmann::json &input,
        const boost::container::flat_set<IPv4AddressData> &ipv4Data,
        const std::shared_ptr<AsyncResp> asyncResp)
    {
        if (!input.is_array())
        {
            messages::propertyValueTypeError(asyncResp->res, input.dump(),
                                             "IPv4Addresses");
            return;
        }

        // According to Redfish PATCH definition, size must be at least equal
        if (input.size() < ipv4Data.size())      <<<<<<<<<<<<  here if input size is less then existing list then patch is not allowed which is incorrect.
        {
            messages::propertyValueFormatError(asyncResp->res, input.dump(),
                                               "IPv4Addresses");
            return;
}```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18837/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/18837 merged
