### ISSUE TITLE
Redfish(Systems): Unnecessary code is there for CPU and Dimm interface(Empty Interface)

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#442]
<a href="https://github.com/ratagupt"><img src="https://avatars1.githubusercontent.com/u/15628264?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ratagupt](https://github.com/ratagupt)**
_Thursday Feb 21, 2019 at 15:18 GMT_
_Originally opened as https://github.com/openbmc/bmcweb/issues/49_

----

I saw that bmcweb code is referring to some properties which is not there in the meta-phosphor/phosphor-dbus-interfaces.

I could have seen that the dimm or cpu are empty interfaces but in the code, we are expecting the following properties

```           
 for (const std::pair<std::string, VariantType>
                                                 &property : properties)
  {
     if (property.first == "MemorySizeInKb") >>>>>>> we don't have this property under Dimm inetrface(https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Inventory/Item/Dimm.interface.yam)
                        
  connection.first, path,
  "org.freedesktop.DBus.Properties", "GetAll",                                     "xyz.openbmc_project.Inventory.Item.Dimm"
```

```
 if (property.first == "ProcessorFamily") >>>> same here I don't see this property under (https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Inventory/Item/Cpu.interface.yaml)
           
 connection.first, path,
  "org.freedesktop.DBus.Properties", "GetAll", 
  "xyz.openbmc_project.Inventory.Item.Cpu");
```
I am not getting why we are expecting this property here?

@edtanous ^^^^

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
Ratan said  "This is very low priority" I'm moving this to 9.4.99

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Moving out of Redfish v1 to v2.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
https://github.com/openbmc/phosphor-dbus-interfaces/commit/9bf62f10c91dbd1d4327f5fe256d11aec0aa6be6 merged (added MemorySizeInKb)

https://github.com/openbmc/phosphor-dbus-interfaces/commit/259f49e0c40b287d9ea79f77db1654da47161340
merged (added Family)
but bmcweb still needs fixed https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/35949/5/redfish-core/lib/systems.hpp

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/36379/2/redfish-core/lib/systems.hpp fixed this. Closing. Please reopen if any more work needs to be done.
