### ISSUE TITLE
"BuildDate" in /redfish/v1/Systems/system

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#443]
There is no BuildDate in the Redfish ComputerSystem schema. https://redfish.dmtf.org/schemas/ComputerSystem.v1_6_0.json 

Should not blindly add the System properties https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/systems.hpp#L266 
Need to do checks as we do here, https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/cpudimm.hpp#L141

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by BeccaBroek** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18922/
