### ISSUE TITLE
Redfish: Chassis: Fix issues with properties that are returned

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#444]
There are three problems with the current bmcweb implementation of /redfish/v1/Chassis/\<chassis\> properties:

Problem 1:
Sets the property @odata.id incorrectly

Problem 2:
Assumes that all DBus properties are also Redfish properties, which is not true

Problem 3:
Assumes that all DBus properties have the same name and data format as the corresponding Redfish properties.

This issue will be used to fix these problems.

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
Working on this now.

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/18809

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/18809 merged
