### ISSUE TITLE
Redfish: Chassis: Single chassis support

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#445]
Currently the Redfish support in bmcweb assumes there could be multiple chassis.  This matches the Redfish specification.

Redfish associates sensors with a specific chassis, and the current bmcweb implementation uses EntityManager to find the sensors in a given chassis.

IBM does not use EntityManager, and currently IBM systems only have one "chassis" in the Redfish sense.  bmcweb should be modified to support a build flag/#ifdef for one chassis systems.  When this flag is enabled, bmcweb will report only one chassis with the hardcoded name "chassis".

This design is in alignment with the way bmcweb provides a single system named "system" and a single BMC named "bmc".

Gunnar Mills already pushed up an initial commit as a work in progress:  https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/17563/

I am taking over this commit and making changes so that it can be merged.

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
I believe I am done with this.  It is up for review.

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/17563

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
https://gerrit.openbmc-project.xyz/17563 merged
