### ISSUE TITLE
Redfish: Thermal: Support single chassis flag for sensors

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#446]
In the Redfish schema sensors are within a specific chassis.  A machine can contain one or more chassis.

The current bmcweb support for Thermal sensors determines which sensors are in a chassis using EntityManager.  This does not work on IBM systems because IBM does not use EntityManager.

The bmcweb sensor code should be updated to support the new flag indicating a single chassis system.  If this flag is enabled, the sensor code should not use EntityManager.  It will instead obtain all sensors using ObjectMapper.

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
Working on this now.

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/19099

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
https://gerrit.openbmc-project.xyz/19099 merged
