### ISSUE TITLE
Redfish: Chassis: Only looks at properties in one service/connection

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#447]
When bmcweb is obtaining the Redfish properties of a Chassis, it calls ObjectMapper to get all the services/connections for the chassis DBus object path.

For the given object path, there could be multiple services/connections that provide DBus properties.

However, the bcmweb implementation currently only obtains properties from the first service/connection returned by the mapper.  The other connections are ignored.  This could result in missing properties.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
