### ISSUE TITLE
Redfish: Chassis: Some property values are right-padded with spaces

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#448]
When using the following Redfish URL:

/redfish/v1/Chassis/\<chassis\>

I noticed that some of the returned property values are right-padded with spaces:

```
"Manufacturer": "IPS             ",
"PartNumber": "00VK672         ",
"SerialNumber": "YL30UF77V007    ",
```

I assume this is because these values are coming from VPD, and VPD is often right-padded with spaces.  In discussing this with Gunnar, he felt that we probably do not want these trailing spaces.  He also wondered whether they should be removed before being put on DBus vs. expecting the Redfish code to "clean them up."

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@santoshpuranik to investigate whether this is still an issue on Rainier.

**Comment by rfrandse** [comment]
tracking in jira
