### ISSUE TITLE
Add Aspeed Video Engine Driver

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#45]
<a href="https://github.com/eddiejames"><img src="https://avatars1.githubusercontent.com/u/14914763?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eddiejames](https://github.com/eddiejames)**
_Tuesday Apr 10, 2018 at 18:06 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3082_

----

Init HW video engine
Setup compression
Use Video4Linux2 for userspace interface

Under the "KVM over IP" epic, #2799

**Comment by rfrandse** [comment]
<a href="https://github.com/edtanous"><img src="https://avatars0.githubusercontent.com/u/599897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edtanous](https://github.com/edtanous)**
_Wednesday May 02, 2018 at 15:45 GMT_

----

Has any progress been made on this?  I would love to see/test an early WIP if you have one.

**Comment by rfrandse** [comment]
<a href="https://github.com/amboar"><img src="https://avatars0.githubusercontent.com/u/526481?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amboar](https://github.com/amboar)**
_Thursday May 10, 2018 at 03:27 GMT_

----

I haven't heard of any progress.

**Comment by rfrandse** [comment]
<a href="https://github.com/eddiejames"><img src="https://avatars1.githubusercontent.com/u/14914763?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eddiejames](https://github.com/eddiejames)**
_Thursday May 10, 2018 at 14:05 GMT_

----

Still working on it; side-tracked with other work at the moment.

**Comment by eddiejames** [comment]
Development is complete. Upstreaming in progress...

Current task is to get the driver to conform with Video4Linux compliance tool, which is required by Linux maintainer.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by eddiejames** [comment]
merged in linux 5.0
