### ISSUE TITLE
Redfish: Thermal: Return actual sensor status

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#450]
## Overview
Currently the bmcweb Redfish implementation returns hard-coded values for Thermal sensor status:
- Status->Health is set to 'OK'
- Status->State is set to 'Enabled'

We need to return the actual Thermal sensor status.  This applies to both fans and temperature sensors.  If the fan/temp sensor is not working, the Health should be set to 'Critical'.  If the fan/temp sensor is missing, the State should be set to 'Absent'.

### Health
The fan/temp sensor Health will be obtained from the Functional property of the DBus xyz.openbmc_project.State.Decorator.OperationalStatus interface.

This interface is not implemented on sensor object paths, such as /xyz/openbmc_project/sensors/fan_tach/fan0_0.  The interface is instead implemented on related inventory object path, such as /xyz/openbmc_project/inventory/system/chassis/motherboard/fan0.

ObjectMapper associations can link a sensor to the associated inventory item.  Matt has already defined these associations for Witherspoon (https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/21154).

The sensor -> inventory item associations can be obtained from the ObjectMapper.  The ObjectMapper can then be used to find the services that implement the OperationalStatus interface for those inventory items.  Last the Functional property value for each inventory item can be obtained from the respective service.

### State

The fan/temp sensor State (present or absent) will be obtained from the the Present property of the DBus xyz.openbmc_project.Inventory.Item interface.

Like OperationalStatus, this interface is on the inventory item rather than the sensor.  The same algorithm should be used as for fan/temp sensor Health.  Find the inventory item associated with a sensor and then get the Present property of that inventory item.

### Implementation within bmcweb

Efficiency and minimizing the number of DBus calls is a heavy focus for the bmcweb maintainers.  To meet this goal, the new information could be obtained in a small number of DBus calls that return multiple entries (vs. one DBus call per sensor):
- Call org.freedesktop.DBus.ObjectManager.GetManagedObjects on the ObjectMapper to obtain all associations in one DBus call.  Filter the output to select only associations from fan/temp sensors to inventory items.
- Call GetSubTree on the ObjectMapper with the object path /xyz/openbmc_project/inventory looking for the interfaces xyz.openbmc_project.Inventory.Item and xyz.openbmc_project.State.Decorator.OperationalStatus.  Filter the output to select only services that implement those interfaces for fan/temp sensor inventory items.
- Call org.freedesktop.DBus.ObjectManager.GetManagedObjects on each service to get all object paths, interfaces, and properties.  Obtain the Functional and Present properties for returned fan/temp sensor inventory object paths.

Intel does not use the OperationalStatus interface.  Instead, they use the DBus threshold interface to determine if a sensor has failed.  As such, they plan to implement support to obtain fan/temp sensor Health using DBus threshold information.  They have agreed to let us obtain fan/temp sensor Health using an association and OperationalStatus as a second/backup approach.

Intel uses the xyz.openbmc_project.Inventory.Item interface, but I think they implement it on the sensor object path rather than an associated inventory item path.  I think they plan to enhance bmcweb to look for the Present value on the sensor object path.  They have agreed to let us obtain fan/temp sensor presence using an association to the inventory path as a second/backup approach.

Intel documented their initial design for Redfish Health here:  https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/21380.

### ObjectMapper Association Naming Issue

There are two types of ObjectMapper associations needed between sensors and inventory items:

1. An association from a chassis inventory item to all the sensors within that chassis.  In Redfish sensors are contained within a chassis.  The Thermal URI is /redfish/v1/Chassis/{chassisName}/Thermal.  A system can contain multiple chassis (and Intel systems do), so we must return only sensors for the chassis specified in the URI.  This ObjectMapper association is used to provide the list of sensors in the chassis.  This is already implemented in bmcweb.  The necessary associations for Witherspoon were already defined by Matt Spinler.
2. An association from a sensor to the corresponding low-level inventory item.  For example, from the fan sensor /xyz/openbmc_project/sensors/fan_tach/fan0_0 to the inventory item /xyz/openbmc_project/inventory/system/chassis/motherboard/fan0.  Matt defined these associations for Witherspoon, but they are not currently used by bmcweb.

The naming issue arises because of these two different types of associations.  The bmcweb code currently assumes the first association from chassis <-> sensors has the end point names "sensors" and "inventory".  For example:
- /xyz/openbmc_project/inventory/system/chassis/sensors is an association that contains the list of all sensors within that chassis.  An example sensor object path in this list would be /xyz/openbmc_project/sensors/fan_tach/fan0_0.
- /xyz/openbmc_project/sensors/fan_tach/fan0_0/inventory is an association that contains the chassis for this sensor.  It contains the object path /xyz/openbmc_project/inventory/system/chassis.

In the Witherspoon YAML file, both types of associations are implemented.  But they use different association end point names than what bmcweb expects:
- For the first association, "sensors" and "chassis" are used.
- For the second assocation, "child_sensors" and "inventory" are used.

Given that the bmcweb code already expects the end point names "sensors" and "inventory" for the first type of association, we may need change the Witherspoon YAML to comply with that.  We next need to come up with new association end point names for the second type of association.

## References
- Original Redfish Thermal epic:  https://github.com/ibm-openbmc/dev/issues/275
- Matt Spinler's commit that created Witherspoon associations between sensors and inventory items:  https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/21154
- James Feist/Intel design document for Redfish Health:  https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/21380
- Object Mapper: https://github.com/openbmc/docs/blob/master/object-mapper.md
- DBus spec: https://dbus.freedesktop.org/doc/dbus-specification.html

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22765

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
This has been merged.
