### ISSUE TITLE
BMC firewall rules

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#453]
This is to ensure the correct firewall rules are established per #452.  This includes both IPv4 and IPv6 (see #243).  The main idea is to restrict IP traffic to what the BMC needs if it was configured with all of its features.
As part of this, document how the firewall rules relate to features; later work items can tighten the rules (to make OpenBMC "secure by design") or adapt them to a specific configuration (for example, to remove support for SSH or IPMI).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by joseph-reynolds** [comment]
Firewall was not implemented.
