### ISSUE TITLE
BMC firewall docs

### ISSUE THREAD

**Issue by joseph-reynolds** [ibm-openbmc/dev#455]
Document (in openbmc/docs) for system integrators and admins:
- to how configure the firewall (systemd config, start/stop, IPv4 vs IPv6)
- how the firewall rules relate to OpenBMC features
- how to work with the firewall logging support (start/stop it, interpret logs)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by joseph-reynolds** [comment]
This is not a firewall doc, but addresses the same problems a firewall attempts to solve:
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/22106/1/security/network-security-assurance-guide.md

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by joseph-reynolds** [comment]
Firewall was not implemented.
