### ISSUE TITLE
GUI: Remote Logging - Manage Server

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#456]
## Due Dates
- [ ] UX: 04/18/19
- [x] Backend
- [ ] FED: 05/30/19

## Team
**SME**: @dkodihal
**DR**: @nicoleconser 
**UX**:  @ryanarnell 
**FED**: 

## Use Case
Remote Logging is currently command line only. We need to be able to do remote logging set up on the GUI. Remote login enables the user to have an external machine read the current health status of the server. It creates an audit log, streams the data to a remote server, and sets up that remote server.

### Open Questions
- [x] Is there a need to be able to add multiple servers?
  Backend is complete and this is not being requested by many users
- [x] Would users like to be able to enable and disable a remote logging servers?
  Not supported in this story
- [x] Would users see a value in having a history of servers?
  Not important for this story

## InVision Prototype
https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319093113_Remote-Logging-01

## Design Issue
https://github.com/openbmc/phosphor-webui/issues/68

## Development Issue
---

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Remote Logging will be part of the event logs page. We need to redesign the prototype.

**Comment by gtmills** [comment]
@derick-montague @ryanarnell Why part of the existing log page?

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@gtmills - This came up in a meeting between @susantjasinsk during the IA meetings with RAS and PHYP. Do we need further conversation about this?

**Comment by rfrandse** [comment]
refresh

**Comment by ryanarnell** [comment]
These are commands to connect remote logging server and perform different operations if this is helpful for FEDs

**Successful connection to remote logging server**
```
$ python openbmctool.py -H wsbmc002 -U root -P 0penBmc logging remote_logging_config -a 9.3.40.50 -p 5000

Attempting login...
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}

User root has been logged out
```

**Unsuccessful connection to remote logging server**
```
$ python openbmctool.py -H wsbmc002 -U root -P 0penBmc logging remote_logging_config -a 9.3.40.5500 -p 514
Attempting login...
{
  "data": {
    "description": "The specified property cannot be created"
  },
  "message": "Input/output error",
  "status": "error"
}
User root has been logged out
```
**View current status of the server**

```
$ python openbmctool.py -H wsbmc002 -U root -P 0penBmc logging remote_logging view
Attempting login...
{
  "data": {
    "Address": "9.3.40.50",
    "Port": 514
  },
  "message": "200 OK",
  "status": "ok"
```

**To check if remote login server is configured on the BMC**

```
$ python openbmctool.py -H wsbmc002 -U root -P 0penBmc logging remote_logging view
Attempting login...
{
  "data": {
    "Address": "",
    "Port": 0
  },
  "message": "200 OK",
  "status": "ok"
}
```
**To remove remote logging on the BMC if configured**
```
$ python openbmctool.py -H wsbmc002 -U root -P 0penBmc logging remote_logging disable
Attempting login...
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}
User root has been logged out
```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by yoshiemuranaka** [comment]
https://github.com/openbmc/phosphor-logging

**Comment by yoshiemuranaka** [comment]
I chatted with Ryan about the green/red status icon when a remote server is configured. We don't have the ability to check the status of the remote server so agreed to remove the icon

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/22002

**Comment by rfrandse** [comment]
refresh

**Comment by yoshiemuranaka** [comment]
Can be tested with remote server 
IP: 9.3.40.50
Port: 514

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
