### ISSUE TITLE
Add support to debug unresponsive host.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#457]
The background information:
 There are situation at customer places where OPAL/Linux goes unresponsive causing a system hang. And there is no way to figure out what went wrong with Linux kernel OR OPAL. 
Looking for a way to trigger a dump capture on Linux host so that we can capture the OS dump for post analysis.

Proposed solution:
   Get all Host CPUs in reset vector and Linux then has a mechanism to patch it into panic-kdump path to trigger dump capture. This will enable us to analyse and fix customer issue where we see Linux hang and unresponsive system.

x86 boxes supports IPMI based command to do similar operation:

IPMI command – ipmitool -I lan -H <RemoteServerBMCAddress> -U <Username> -a chassis power diag

BMC  Support :
  Enable SBE chip-op based SRESET  d-bus interface and enable this via IPMI command. 

SBE chip-op wrapper code is already available for review.
https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-sbe-interface/+/11401/

In future we need provide Redfish support by using   Computer System schema( https://redfish.dmtf.org/schemas/ComputerSystem.v1_6_0.json)  Reset type “Nmi”.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Initial interface proposal to community  
https://lists.ozlabs.org/pipermail/openbmc/2019-May/016329.html

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by lkammath** [comment]
Design template -> https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/21772/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
