### ISSUE TITLE
PLDM M&C : Responder : Implement SetStateEffecterStates

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#459]
This story covers only the decode of the command and encode of the response. This does not cover the responder handling.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by sampmisr** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/19374

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/19374 merged
