### ISSUE TITLE
Redfish: DNS configuration not working

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#461]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [prkatti1](https://github.com/prkatti1)**
_Friday Feb 22, 2019 at 07:37 GMT_
_Originally opened as https://github.com/openbmc/bmcweb/issues/50_

----

Unable to configure nameservers on BMC.

```
bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"NameServers": ["10.6.6.6"]}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/
{
  "NameServers@Message.ExtendedInfo": [
    {
      "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
      "Message": "The property NameServers is not in the list of valid properties for the resource.",
      "MessageArgs": [
        "NameServers"
      ],
      "MessageId": "Base.1.4.0.PropertyUnknown",
      "Resolution": "Remove the unknown property from the request body and resubmit the request if the operation failed.",
      "Severity": "Warning"
    }
  ]
```
```
}bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"NameServers": "10.6.6.6"}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0/
{
  "NameServers@Message.ExtendedInfo": [
    {
      "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
      "Message": "The property NameServers is not in the list of valid properties for the resource.",
      "MessageArgs": [
        "NameServers"
      ],
      "MessageId": "Base.1.4.0.PropertyUnknown",
      "Resolution": "Remove the unknown property from the request body and resubmit the request if the operation failed.",
      "Severity": "Warning"
    }
  ]
```

**Comment by rfrandse** [comment]
<a href="https://github.com/edtanous"><img src="https://avatars0.githubusercontent.com/u/599897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edtanous](https://github.com/edtanous)**
_Thursday Feb 28, 2019 at 17:11 GMT_

----

Patch on the NameServers property is not yet supported.

**Comment by ratagupt** [comment]
We are planning to support it. This issue is for tracking.

**Comment by rfrandse** [comment]
refresh

**Comment by trajeswaran** [comment]
Resolved by : https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18939/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by trajeswaran** [comment]
NameServers property is read-only. If a PATCH is applied to this property, then propertyNotWritable will be returned.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
@prkatti1 Can you please close this issue?

**Comment by prkatti1** [comment]
Closing this as, this property is read only. ANd there is another property staticnameserver, that s working fine.

**Comment by prkatti1** [comment]
@ratagupt I've everified it and working fine with staticnameserver property.
It can be closed.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/18939 merged
