### ISSUE TITLE
Default gateway resouce URL does not exist on BMC

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#464]
<a href="https://github.com/prkatti1"><img src="https://avatars3.githubusercontent.com/u/22515480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [prkatti1](https://github.com/prkatti1)**
_Friday Feb 22, 2019 at 10:23 GMT_
_Originally opened as https://github.com/openbmc/bmcweb/issues/54_

----

Default gateway resouce URL does not exist on BMC

**Comment by rfrandse** [comment]
refresh

**Comment by manojkiraneda** [comment]
I have couple of questions here :
1. What do you mean by Default Gateway in Redfish ?
As far as i see , there is no "DefaultGateway" property in Redfish at all, the close mapping would be "Gateway" property as per the [https://redfish.dmtf.org/schemas/IPAddresses.v1_1_0.json](url)

From the source code , i can see that there is already a GET and PATCH support for Gateway Property.

**GET:**
[2019-03-17 09:49.34]  /mnt/c/Users/ManojkiranEda/Documents/Backup/Work/myworkspace/bmcweb
[ManojkiranEda.DESKTOP-OJL5HCI] ➤  curl -k -H "X-Auth-Token: $bmc_token" -X GET https://127.0.0.1:5443/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
{
  "@odata.context": "/redfish/v1/$metadata#EthernetInterface.EthernetInterface",
  "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0",
  "@odata.type": "#EthernetInterface.v1_2_0.EthernetInterface",
  "Description": "Management Network Interface",
  "HostName": "qemuarm",
  "IPv4Addresses": [
    {
      "Address": "10.0.2.15",
      "AddressOrigin": "DHCP",
      "Gateway": "",
      "SubnetMask": "255.255.255.0"
    },
    {
      "Address": "169.254.250.190",
      "AddressOrigin": "IPv4LinkLocal",
      "Gateway": "",
      "SubnetMask": "255.255.0.0"

**PATCH :**
[ManojkiranEda.DESKTOP-OJL5HCI] ➤  curl -k -H "X-Auth-Token: $bmc_token" -X PATCH https://127.0.0.1:5443/redfish/v1/Managers/bmc/EthernetInterfaces/eth0 -d '{"IPv4Addresses" :[{"Gateway":"10.0.2.1"},{"Gateway":"169.254.250.1"}]}'
{
  "@odata.id": "/redfish/v1/Managers/bmc/EthernetInterfaces/eth0",
  "HostName": "qemuarm",
  "IPv4Addresses": [
    {
      "Address": "10.0.2.15",
      "AddressOrigin": "DHCP",
      "Gateway": "10.0.2.1",
      "SubnetMask": "255.255.255.0"
    },
    {
      "Address": "169.254.250.190",
      "AddressOrigin": "IPv4LinkLocal",
      "Gateway": "169.254.250.1",
      "SubnetMask": "255.255.0.0"
    }
  ],

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
@prkatti1 ^^^^
