### ISSUE TITLE
Investigation: Host Failure Debug data collection 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#465]
Capture the requirements related to collect Host debug data during Host initialization  and run time.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Design discussion still in progress.

**Comment by ojayanth** [comment]
@dhruvibm will be initiating  design documentation review based on the current analysis early next week.
 Debug data collection process still need more discussion.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
All Requirements are captured under Epic #777 .
