### ISSUE TITLE
Location Code Design

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#466]
We need to implement the IBM location code spec.  Location codes, as their name suggests, represent a location of a part inside of a server.  Most likely, we'd have these under inventory entries.

We'll need to handle the case where where there are multiple options for a card in a slot, each with different location codes, such as a storage riser.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Per feedback from Santosh, this work is now done.  Closing
