### ISSUE TITLE
devops: Gerrit upgrade and disaster recovery testing

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#468]
Per the 3/6 infrastructure workgroup meeting, https://github.com/openbmc/openbmc/wiki/OpenBMC-Infrastructure-Workgroup#03-06-19-meeting-minutes, we'll be updating gerrit to the latest 2.16 release.  This story is to track doing that, as well as verifying the disaster recovery works as expected.

The gerrit persistent filesystem is rsync'd every day to an external server. Ensure this data can be used to restart gerrit with all data that was backed up at that time. So worst case is we lose any reviews or review comments that occurred since that last rsync.

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
gerrit 2.16.6 up at https://gerrit-test.openbmc.org/ for testing. Verified I could use the backup data to start this up so disaster recovery looks good.

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
New gerrit upgraded and disaster recovery verified
