### ISSUE TITLE
Redfish: Code Update -Support ApplyTime in software manager

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#469]
http://redfish.dmtf.org/schemas/v1/UpdateService.v1_4_0.json

The initial goal with Redfish code update is to support similar capabilities as we had with our custom REST api. So initially we will just support the following:

```
"Immediate",
"OnReset",
```

Story #482 tracks creating the needed property and connecting it up to the Redfish API's in bmcweb. This story will track the work within the software management code to read this dbus property after a software activate to know whether an automatic reboot of the bmc or host should be done.
```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jaypadath** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/20797/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/20797 merged
