### ISSUE TITLE
IKVM: userspace daemon for vnc and input

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#47]
<a href="https://github.com/eddiejames"><img src="https://avatars1.githubusercontent.com/u/14914763?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eddiejames](https://github.com/eddiejames)**
_Friday Jun 22, 2018 at 15:06 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3270_

----

Create an application to run a vncserver on the BMC providing video data to the network and receiving input events to pipe to the host.

**Comment by eddiejames** [comment]
Resolved-by: https://gerrit.openbmc-project.xyz/#/c/openbmc/obmc-ikvm/+/12126/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by eddiejames** [comment]
Code is merged but the recipe to include it in the BMC image is not yet merged due to waiting on linux kernel support (ast2500 clocking patch) for the video engine driver

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by eddiejames** [comment]
Resolved-by: https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/20444
