### ISSUE TITLE
phosphor-state-manager: Required enterprise enhancements

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#470]
Track all stories required for enterprise class systems running openbmc. Some areas to investigate:

Any refactoring - move appropriate targets into phosphor-state-manager repo
Host Diagnostics - New host state(s) and/or targets required?
BMC reset with host up - Impacts of MCTP/PLDM
Revisit targets which clear host persistent data

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
I forgot I created this and ended up creating https://github.com/ibm-openbmc/dev/issues/767. Lets track there.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
