### ISSUE TITLE
phosphor-state-manager: Enterprise requirement gathering

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#471]

**Comment by geissonator** [comment]
Start the discussion on any requirements coming for phosphor-state-manager in the future. See parent epic for list of areas to investigate.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Discussions have taken place and #767 was created with the appropriate sub epics for the major functions.
