### ISSUE TITLE
Swift:  Add support for DPS310 altitude

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#472]
The DPS310 provides both temperature and altitude.  We already have support for the temperature portion, but we also now need altitude as an input to fan control.

This would take a device driver change, and maybe something new in user space as it will be in the iio subsystem.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by eddiejames** [comment]
This code has been merged into upstream Linux.
