### ISSUE TITLE
Swift humidity sensor user space code

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#475]
Swift has a humidity sensor that will make use of an existing device driver to give us relative humidity in the iio subsystem.  We'll need some user space code to put this on D-Bus.  As it isn't hwmon, we can't use the phosphor-hwmon code.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Not exposing this.  Closing.
