### ISSUE TITLE
IP: Provide support for configurable Zeroconf

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#476]
Currently, the zeroconf address is not configurable and it is always there, by this story we want to make it configurable.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
This story is just to provide the configuration support in backend(phosphor-networkd)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by raviteja-b** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/21088

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@gtmills  This is included in the Redfish Network Epic and I am wondering how we support this before Redfish supports this?

**Comment by ratagupt** [comment]
@derick-montague: It is supported in redfish.
https://redfish.dmtf.org/schemas/EthernetInterface.v1_5_1.json (DHCP-Fallback)

**Comment by ratagupt** [comment]
This is being blocked due to the backend(systemd) limitation. The following issue is used to track that limitation.
https://github.com/systemd/systemd/issues/13316

**Comment by gtmills** [comment]
@ratagupt Any update here?

**Comment by gtmills** [comment]
@ratagupt Still planning this for eBMC ? Is this feature parity we had in OP940?

**Comment by ratagupt** [comment]
@raviteja-b Can you check the systemd, Have the systemd fix the issue?

**Comment by raviteja-b** [comment]
@ratagupt  
Seems systemd still does not support LinkLocalAddressing=fallback with MaxAttempts=infinity

`LinkLocalAddressing=fallback has no reason to exist, because LL address must always be allocated as a fallback option when using DHCP. Having both DHCP and LL address at the same time is an RFC violation, so LinkLocalAdressing=yes correctly implemented is already the "fallback" behavior. The fallback option must be deprecated and if present in older configs must be interpreted as LinkLocalAddressing=yes.`

**Comment by ratagupt** [comment]
@dixsie @derick-montague Is it still needed? I heard that our customers doesn't want the link local address while the static/ DHCP address is there. Is it still valid?
Seems we have to get the fix from systemd and I don't think so we are going to get the fix soon.

**Comment by derick-montague** [comment]
I have asked the team to follow up on this. I don't remember the issue anymore, but Dixsie may. One thing that @BMC-Bruce mentioned was that people may not want the SIT interface shown at all.

**Comment by derick-montague** [comment]
@ratagupt the concern came from the GUI community work group and is discussed in this thread on slack. 

https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1591810665268100

## Summary
> there was concern in the GUI workgroup today about network info and redfish. Both Phoenix and Intel stated issues with the 169.254.140.104 IP address and the SIT 0 where there wasn’t an IP address and seemed like they were Redfish issues.
>
> It was suggested that they were backend issues. They also mentioned @ratagupt possibly having input. I can’t fully explain their concern, but said I would bring it back to you both.

@BMC-Bruce might be able to speak a little to this also as he was in the meeting.

**Comment by BMC-Bruce** [comment]
sit0, to me, doesn't seem like something to normally display, however there has been much debate as how to control sit0's existence and it usage.

See this Gerrit review for more details "Prevent sit0 virtual device being added to the list of NICs"
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/38407

**Comment by sunharis** [comment]
Migrate-Yes

**Comment by rfrandse** [comment]
tracking in jira
