### ISSUE TITLE
Call Home

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#477]
As of now, in certain cases (no HMC and host dead) we need to be able to send errors back to IBM from the BMC.  There will be a RAS meeting in the future to decide if this still needs to be a requirement.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Confirmed with the RAS team today that BMC based call home is not required.  There are other off-BMC based call home methods.
