### ISSUE TITLE
Time Owner dropdown missing icon

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#478]
## As Is:
On the Server Config -> Date and Time Settings screen, the "Time Owner" dropdown is missing the caret icon that visually indicates to the user that the form element is a dropdown.

## To Be: 
The icon should be displayed so the user is aware that the form element is a dropdown.

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/62bf7ca0-3c0a-4848-baef-ed7bfd8bbc3e)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by yoshiemuranaka** [comment]
There are different implementations of adding carets to dropdown menus in the current codebase. The current working examples in the UI (event logs page) are using `<button>` elements and adding pseudo elements to create the caret. The dropdown in this story is a `<select>` element and is using `background-image: url()` to add the caret. 
This story will include updating all dropdown menus in the UI to use `<select>` elements and `background-image: url()` to add carets.
