### ISSUE TITLE
Redfish: Upstream host state boot/OS progress

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#479]
Should look to upstream https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/State/OperatingSystem and https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/State/Boot/Progress.interface.yaml as a field in ComputerSystem or additional values in ComputerSystem -> PowerState

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
https://github.com/DMTF/Redfish/issues/3834 is the redfish issue for this

**Comment by gtmills** [comment]
Pull request up and continuing to be worked in Redfish.

**Comment by gtmills** [comment]
Should be in 2020.3

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/dev/issues/2355 is the story to implement this
