### ISSUE TITLE
REST logging API doesn't log RESTful calls 

### ISSUE THREAD

**Issue by gkeishin** [ibm-openbmc/dev#481]
In master, I see that after we enabled the REST logging

```
https://xx.xx.xx.xx:443/xyz/openbmc_project/logging/rest_api_logs/attr/Enabled, method:Put, args:{u'data': {u'data': True}, u'headers': {u'Content-Type': u'application/json', u'X-Auth-Token': u'leKwEqbAvfLXeqgXkoan'}}
Response code:200, Content:{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}
```

I see no subsequent REST / Redfish call made to the BMC are logged.

Discussed with @dkodihal on this and it looks like there are changes needed from bmcweb to enable the logging.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
We're hoping there are two aspects to this issue.
- A short term fix where we get this working within bmcweb similar to how it was working with the legacy REST server. Maybe a debug flag in bmcweb that the REST api for this could enable (to log the REST commands).
- A long term fix where we propose a change to the DMTF for a Redfish audit logging capability

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
Resolved here:
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22699
https://gerrit.openbmc-project.xyz/c/openbmc/meta-openpower/+/22702

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@santoshpuranik Did we get this into master I see https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22699 has merge conflicts ?

**Comment by mzipse** [comment]
Per feedback from Santosh, this is complete.  Closing.
