### ISSUE TITLE
Redfish: Code Update - Define and implement new dbus attributes for ApplyTime

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#482]
http://redfish.dmtf.org/schemas/v1/UpdateService.v1_4_0.json

The schema defines an Enum, ApplyTime:
```
        "ApplyTime": {
            "enum": [
                "Immediate",
                "OnReset",
                "AtMaintenanceWindowStart",
                "InMaintenanceWindowOnReset"
            ]
```

This is a property under the HttpPushUriApplyTime object which is itself a property under the HttpPushUriOptions object.

HttpPushUriOptions is then a property under the UpdateService.

This story has two parts (and can be broken into separate stories if desired):
1. Define the dbus interface for this new property out in https://github.com/openbmc/phosphor-dbus-interfaces. Some discussions with @dkodihal was leading us to think putting this under the settings namespace made the most sense.
2. Support the reading/writing of this property (and all necessary redfish object paths) in bmcweb (so redfish commands can be used to read and write it).

There are some extra properties under the HttpPushUriApplyTime object (MaintenanceWindowDurationInSeconds, MaintenanceWindowStartTime) which are not planned for our 2.7 release and can be deferred to later.

#469 will track looking at this dbus property and acting upon it in the software manager code.

Design doc is out at https://github.com/openbmc/docs/blob/master/designs/firmware-update-over-redfish.md. This story was somewhat vague in the design doc so feel free to update design to match.

**Comment by dkodihal** [comment]
Needs to be assigned to Jayashankar.

**Comment by rfrandse** [comment]
refresh

**Comment by jaypadath** [comment]
Resolves the first part : https://gerrit.openbmc-project.xyz/c/openbmc/openpower-pnor-code-mgmt/+/4795

**Comment by rfrandse** [comment]
refresh

**Comment by jaypadath** [comment]
Scope of the work:

1. Define a new dbus interface for the ApplyTime property
2. Make the change in the phosphor-settingsd
3. bmcweb changes will be done separately

**Comment by jaypadath** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/19707 and https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/20071

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/20071 merged
