### ISSUE TITLE
Redfish: Code Update - Support new RedfishHttpPushUri

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#483]
Per https://github.com/DMTF/Redfish/pull/3296, a new URI property to push the software image at, RedfishHttpPushUri, is on its way.  This is to track the work to move over to this new property. Should be minimal effort, seems like mostly a conformance thing.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
This was replaced by MultipartHttpPushUri so closing out.
