### ISSUE TITLE
Manufacturing: Rest to Redfish porting.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#484]
Through this epic we would implement all the current REST API which has been used in manufacturing  needs to be ported to Redfish.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@ratagupt When is this needed by? What milestone? Swift? eBMC ?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
@gtmills This was needed by the manufacturing for D0 milestone for Rainier.

**Comment by trajeswaran** [comment]
The manufacturing tool has been modified to use Redfish API instead of Rest API wherever Redfish support is available.
