### ISSUE TITLE
Manufacturing: Change the authentication framework for redfish

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#486]
With this story we need to make the change in the manufacturing authentication framework to use the X-auth Token based approach.
This would be the building block of other mfg API .

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Reduced priority for it.

**Comment by trajeswaran** [comment]
code changes have been completed and reviewed.  It is not yet merged.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
it is merged and has been released.
