### ISSUE TITLE
PLDM M&C : SetStateEffecter : Implement encode/decode

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#487]
Implement encoder for SetStateEffecter request message, and decoder for SetStateEffecter response message. Look at https://github.com/openbmc/pldm/tree/master/libpldm for examples. Write unit tests as well.

**Comment by dkodihal** [comment]
Needs to be assigned to Varsha.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vkaverap** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/20076

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/20076 merged
