### ISSUE TITLE
Redfish: Code Update - SimpleUpdate Investigation and Design

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#488]
References:

https://redfish.dmtf.org/schemas/UpdateService.v1_4_0.json (SimpleUpdate)
https://github.com/openbmc/docs/blob/master/designs/firmware-update-over-redfish.md

The goal with this story is the following:
- Understand the SimpleUpdate action and review existing implementations of it
- Test and verify the existing legacy REST base API for doing a TFTP update to understand the mechanics
- Propose a solution for OpenBMC to support it to the mailing list
  - The initial goal is to support just TFTP since that is all the existing software management code in OpenBMC supports

Some things to think about:
- TFTP does not require username/password so those fields will not be required
- There were security concerns during the design review, are they still here or do we let the user do what they want?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Design uploaded to https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/20700

Verified existing TFTP via REST api worked as expected

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/20700

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/20700 merged
