### ISSUE TITLE
Telemetry : define and document external API

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#49]
<a href="https://github.com/dkodihal"><img src="https://avatars1.githubusercontent.com/u/22700515?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dkodihal](https://github.com/dkodihal)**
_Wednesday Apr 18, 2018 at 12:51 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3105_

----

Define external REST API that clients can use to subscribe to telemetry data. For eg would this just use the event subscription API (which is based on D-Bus)? There should be means to control the aggregation and telemetry intervals.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Gunnar to create stories and make sure we have everything covered then will close this issue

**Comment by gtmills** [comment]
Tracking through other telemetry stories. Closing.
