### ISSUE TITLE
Redfish: Requires phosphor-fan-control / phosphor-dbus-monitor / new application to provide DBus data needed for Fan Redundancy

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#491]
The Redfish Thermal information includes an optional Redundancy collection.  This is used to show redundancy for fans.

The bmcweb application currently supports the Redundancy collection if the correct data is available on DBus.  The  phosphor-fan-control application does not currently provide this data to DBus.  Thus, no fan redundancy information is returned by Redfish for systems using phosphor-fan-control.

I believe the Redfish Redundancy information is required by the OCP Server Management Interface (OCP Basic Server Profile).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
What the profile needs:
```
                "Redundancy": {
                    "PropertyRequirements": {
                        "MemberId": {},
                        "RedundancySet": {},
                        "Mode": {},
                        "Status": {},
                        "MinNumNeeded": {},
                        "MaxNumSupported": {
                            "ReadRequirement": "Recommended"
                        }
```

http://redfish.dmtf.org/schemas/v1/Redundancy.v1_3_4.json#/definitions/Redundancy is the full spec for Redundancy something like
```
"Fans": [
     {
     "@odata.id": "/redfish/v1/Chassis/chassis/Thermal#/Fans/0"
     "Redundancy": {
        "MemberId": 0,
        "RedundancySet": {'/redfish/v1/Chassis/chassis/Thermal#/Fans/0', '/redfish/v1/Chassis/chassis/Thermal#/Fans/1',  '/redfish/v1/Chassis/chassis/Thermal#/Fans/2', '/redfish/v1/Chassis/chassis/Thermal#/Fans/3'},
        "Mode": N+m,
        "Status": {
             "State": "Enabled",
              "Health": "OK"
           } 
          "MinNumNeeded": 3,
          "MaxNumSupported": 4,
```
Mode I think should be `N+n` or `sharing` on Witherspoon 

![mode](https://user-images.githubusercontent.com/5455127/70266722-a6bf2500-1762-11ea-9a50-19bea0d5c8f2.PNG)

**Comment by gtmills** [comment]
Intel uses https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Control/FanRedundancy.interface.yaml
https://github.com/openbmc/bmcweb/blob/4bb3dc346522b5f1e3bf6241c64238837caff5d2/redfish-core/lib/sensors.hpp#L1147

We would want to use that interface, and extend in anyway we need.

**Comment by gtmills** [comment]
phosphor-dbus-monitor has all this data (fans functional/present) but it currently does not expose anything on D-Bus. @msbarth A maintainer of phosphor-dbus-monitor (pdm), mentioned if this logic is written there, it is written in a generic way so it could also be used for other Redundancy like power supply Redundancy.

**Comment by bradbishop** [comment]
> On Dec 5, 2019, at 5:52 PM, Gunnar Mills <notifications@github.com> wrote:
> 
> phosphor-dbus-monitor has all this data (fans functional/present) but it currently does not expose anything on D-Bus. @msbarth A maintainer of phosphor-dbus-monitor (pdm), mentioned if this logic is written there, it is written in a generic way so it could also be used for other Redundancy like power supply Redundancy.

A word of caution on adding too much logic to phosphor-dbus-monitor.  I only designed it to be an option for implementing one-off esoteric requirements.

**Comment by rfrandse** [comment]
tracking in jira
