### ISSUE TITLE
Redfish: Need valid minimum and maximum values for temp/fan sensors

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#492]
The Redfish Thermal output includes information about each fan and temperature sensor.

There is an issue with the following two properties returned for each sensor by bmcweb:
* MaxReadingRange
* MinReadingRange

The values of those properties are obtained from the following DBus properties:
* xyz.openbmc_project.Sensor.Value.MaxValue
* xyz.openbmc_project.Sensor.Value.MinValue

On Witherspoon, both values are 0 for all sensors.  This seems like a bug, especially for the maximum values.

I believe Redfish is working properly here, so the fix is in the application(s) that provide the DBus properties.

Note: It was not clear during some initial investigation what the correct values of these DBus properties should be.  For example, is the MinValue of a fan rotor the slowest it can physically spin?  Or the minimum value that is allowed given the current temperature/fan algorithm?  Something else?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by wangzqbj** [comment]
Sorry, at first I thought it was a generic and redfish-related task. I don't have a witherspoon machine,  so removed the assignment.

**Comment by mine260309** [comment]
This task requires the inputs from HW about the fan speed's min/max values.
If we got the input, this task becomes ready for dev, otherwise, we could not really work on this.

@smccarney @gtmills Is it possible to get that information for Witherspoon?

**Comment by mzipse** [comment]
@mine260309 , after further discussions, we're going to pull the ReadyForDev label off this story for now.  There are underlying things that we need to sort out, like the use of Entity Manager, before we go off an come up with an implementation.  This story isn't so much as to identify the specific values for a platform like Witherspooon.  It's more to get the infrastructure set up generically so that no matter what platform we are talking about, we can easily plug in those HW values for a given platform when the time comes.  We also need to be more clearer on what we want for these min/max values.

**Comment by mzipse** [comment]
@msbarth , is this issue needed anymore?.  We have no plans to do anything on P9 servers.  And I'm guessing you have this covered somehow on the P10 servers, true?

**Comment by msbarth** [comment]
@mzipse It doesnt appear that the updated Redfish fan schema is pulling in any min/max values for the fans (https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/41086) and I'm not aware if the Redfish temp sensor schema would be attempting to populate a min/max value.

In P9 servers, the hwmon configs for temp devices and the fans contained what I'd think would be used as the min/max values for this issue as the `CRITLO` and `CRITHI` values. (We did not have these defined in the hwmon config for the MAX31785 fan controller)
i.e.) DPS310 temp sensor -> https://github.com/openbmc/openbmc/blob/master/meta-ibm/recipes-phosphor/sensors/phosphor-hwmon/witherspoon/obmc/hwmon/ahb/apb/bus%401e78a000/i2c-bus%40100/dps310%4076.conf#L4-L5

For P10, I'd imagine that each app handling the different devices providing temps needs to provide a min/max value on dbus for Redfish to consume (assuming the schema is looking for them).

Sensor dbus interface min/max properties -> https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/yaml/xyz/openbmc_project/Sensor/Value.interface.yaml#L26-L35

Fan sensors would use the same interface, however IBM is still using the MAX31785 with phosphor-hwmon which has limited support for providing a min/max value on that interface and would need further investigation/work for those min/max properties to be populated on the fan sensor dbus objects.

**Comment by mzipse** [comment]
@bradbishop or @gtmills , would like your opinion on this.  Do we need to communicate a direction on what the teams need to be doing for min/max values on dbus objects?  If so, could we add this to Brad's design calls for discussion?

**Comment by gtmills** [comment]
Can we revisit after GA ? I see the milestone is marked such.

**Comment by gtmills** [comment]
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW556929 was a defect in this area. ReadingRangeMax / ReadingRangeMin

**Comment by rfrandse** [comment]
tracking in jira
