### ISSUE TITLE
Redfish: Need accurate OperationalStatus.Functional value for temperature sensors

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#493]
The Redfish Thermal output includes information about all temperature sensors.

One field of the output is Status->Health.  This field is an enumeration with the following valid values:
* OK: Normal.
* Warning: A condition exists that requires attention.
* Critical: A critical condition exists that requires immediate attention.

If a temperature sensor is not working properly, such as invalid output or I2C communication errors, the Redfish Health value should be Warning or Critical (not OK).

To accomplish this, the Redfish Health property could be based on the DBus xyz.openbmc_Project.State.Decorator.OperationalStatus.Functional value.

However, this is not the current behavior on IBM systems.  Depending on the type of sensor error that occurs, the hwmon process may exit.  This causes the sensor to be removed from DBus.  So rather than have a false Functional value, it just disappears.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@smccarney Completed this work. Closing
