### ISSUE TITLE
Redfish: Investigate whether fan speed value/units correct on Romulus systems

### ISSUE THREAD

**Issue by smccarney** [ibm-openbmc/dev#494]
The Redfish Thermal output includes the speed of all fans.  A fan speed value is accompanied by a unit field containing "RPM" or "Percent".

bmcweb currently determines the fan speed unit based on the DBus object path.  If the second to last node is "fan" or "fan_tach", the unit is assumed to be "RPM".  If the second to last node is "fan_pwm", the unit is assumed to be "Percent".

Matt Barth was not sure if this logic would work on Romulus systems.  He thought the DBus fan object paths may contain "fan_pwm" because the target fan speed is set via a PWM value.  However, he thought the resulting actual fan speed reported by the sensor may be in RPMs.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@smccarney @msbarth @mine260309 Anything we need to do here?

**Comment by mine260309** [comment]
On Romulus (and many other OpenPOWER systems), the fan contols is done by Aspeed's fan tach.
Thus on DBus:
* The fan speed `Value` is RPM, and the `Unit` is `RPMS`
* The fan `Target` is a value of PWM.

I tried to get the Redfish sensors from Romulus, it's empty. Not sure if bmcweb does support hwmon sensors or not.

```
$ curl -k -b cjar -H "X-Auth-Token: $token" https://$bmc/redfish/v1/Chassis/chassis/Sensors
{
  "@odata.context": "/redfish/v1/$metadata#SensorCollection.SensorCollection",
  "@odata.id": "/redfish/v1/Chassis/chassis/Sensors",
  "@odata.type": "#SensorCollection.SensorCollection",
  "Description": "Collection of Sensors for this Chassis",
  "Members": [],
  "Members@odata.count": 0,
  "Name": "Sensors"
}
```

**Comment by gtmills** [comment]
@msbarth @smccarney Can we close?

**Comment by mzipse** [comment]
@msbarth , at this point, is there any reason to worry about this?  Can we close?

**Comment by msbarth** [comment]
@mzipse Correct, this is NA for eBMC. I dont see a need for this issue at this point, specifically for Shawn or I to investigate, as this looks to be something that should be tested/verified for Redfish devs in support of PWM based fan thru Redfish.

**Comment by gtmills** [comment]
Closing. Please reopen if this still needs to be tracked.
