### ISSUE TITLE
Color label consistency between CSS and Style Guide

### ISSUE THREAD

**Issue by susantjasinski** [ibm-openbmc/dev#497]
Cross-company FEDs need a CSS color variable naming convention that is documented and scalable to encourage the use of consistent colors in the application:
- [ ] consolidate variations of color to a single color that is accessible, where applicable
- [ ] remove colors from CSS list that are not being used in the GUI, where applicable
- [ ] improve color naming convention so that it can scale when new colors are added

Cross-company UX and Visual designers need a Style Guide color palette  that matches the CSS color naming convention so that they can communicate accurately with their FED team members.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/23031

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/23031 merged
