### ISSUE TITLE
LDAP authentication and groups

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#5]
The base requirements are :

- Have the ability for the BMC to authenticate a REST against an LDAP server.
- There would be a read-only and admin LDAP groups, the BMC must restrict REST access accordingly.

Here's a high level break down and person day sizing that we discussed :

LDAP authentication
 
1) Pull openldap (libs and client) and pam_ldap into the image. 2 PD.
2) Configure pam_ldap to point to the openldap client. 2 PD.
3) Changes in phosphor-rest-server to route auth requests to pam_ldap. 12 PD.
4) LDAP server provisioning. 5 PD.
5) Active directory should be supported.
6) Secure (production) and unsecure (test) LDAP.
 
 
LDAP groups
 
1) phosphor-rest-server : fetch user LDAP group and permissions. 8 PD.
2) phosphor-rest-server : authorize requests against LDAP group permissions. 8 PD.

Open items :
- Do we need an API to map user permissions to LDAP groups, or just fetch from LDAP server (assuming groups and permissions would be stored on the server)?

**Comment by ratagupt** [comment]
@dkodihal 

Seems one more story would be needed 

Define the boolean D-bus property in global settings or user manager which tells whether LDAP is enabled or not.
Action:
if enabled then disable all the local user accounts. 
if disabled then enable all the local accounts.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
