### ISSUE TITLE
Fixup PLDM message structure

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#503]
At the moment, it isn't possible to case a uint8 buffer directly into a PLDM message structure or vice versa.

There are two different structures now, representing the header and payload, and they don't reside in contiguous memory, so memcpying one of them becomes necessary.

This story is to come up with a data structure to fix this problem. Something similar to a https://en.wikipedia.org/wiki/Flexible_array_member, but C++ doesn't have it.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/21214 merged
