### ISSUE TITLE
Investigation: POWER Host - initialization and management

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#504]
Capture the BMC side requirements related to initialize host and mange host requests.

Capture all required requirements and create issues .

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Initial investigation completed, Working Design documentation.
@dhruvibm  will be sending proposal in this week.

**Comment by ojayanth** [comment]
Initial set of data is available , Need to close some of the open items related to  Guard data handling.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Epic #661 provides the details of the created based on this investigation
