### ISSUE TITLE
Redfish Network(IPv6): Support to configure the Static IP address 

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#505]
This story is to support the IPV6 static address configuration through redfish.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by raviteja-b** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/20631/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/20631 merged
