### ISSUE TITLE
GUI: SNMP: Focus states when adding, editing, and removing manager

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#506]
There are some keyboard user usability issues specific to the edit, delete and add buttons. For keyboard users, we want to keep them from having to start back at the top of the page. For screen readers, it will read to them where they are on the page when an element gains focus.

1. When the user adds a manager, I think that the host name/IP address field should gain focus
2. When the user clicks edit and the inputs are in the edit state, the host name/IP address should gain focus
3. When the user deletes a manager, the add manager button should gain focus.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jandraa** [comment]
When you say 'should gain focus' do you mean enabled vs disabled? 
I think we will likely need an inactive state and an active / in-focus state for enabled fields to more clearly show which of the fields is the one in focus (ex. host name vs IP address). 

If you agree, there is this design in the style guide although I do not believe it has been implemented anywhere yet. 
https://ibm.invisionapp.com/d/main#/console/15339466/318902253/preview
<img width="860" alt="Screen Shot 2019-06-12 at 4 31 49 PM" src="https://user-images.githubusercontent.com/44675611/59387801-ae5fbd00-8d2f-11e9-9b8e-ab7091acde1f.png">

**Comment by derick-montague** [comment]
Issue 1 can be debated. but 2 and 3 are best practices. Focus is visually indicated by the blue outline you usually see when tabbing or after a user clicks on an element. None of these mean anything to a mouse user, but to a keyboard user they vastly improve the experience. 

1. Means they don't have to tab back to the host name/ip address to start entering information
1. Means the user activates edit and the cursor is set in the first field in the form so the user can start typing
1. Setting the cursor on the next section the user can take action. This is the most important of the three is this item since if there isn't an item to focus on when the last one is deleted a keyboard user would have to tab through the entire UI to get back to the section. This is another reason that the `skip to content` link enhances a keyboard users overall experience trying to navigate.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Will be handled by new UI and bootstrap components. No longer valid story.
