### ISSUE TITLE
Rainier: PFP: Support altitude index into fan floor table

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#509]
Create a new fan floor table action that will use an altitude value to index into a set of tables of ambient temp to fan floor speed. Initial requirements are to read the altitude value at poweron to determine the fan floor table(ambient ranges -> floor speed) to use.
This requirement could change to include polling the altitude at a specified interval in case the fan floor table needs to be updated(this should already be contained with configuring a timer trigger in addition to an init trigger).

This is dependent on https://github.com/ibm-openbmc/dev/issues/472
(and likely dependent on updates to the iio-hwmon space to expose altitude on dbus, issue TBD)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Opened https://github.com/ibm-openbmc/dev/issues/649 to track how to deal with altitude in user space as only the pressure is presented in sysfs.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
This has moved back into plan for Swift. Additional discussions will occur to finalize the thermal requirements and design details for handling the pressure sensor (or convert to altitude value and use that).

**Comment by msbarth** [comment]
This is now out of plan for Swift.

Thermal requirements are to use the pressure sensor value as an additional index into the fan floor table. This means the current fan floor table based on ambient will expand to a 2-D set of configurable inputs for determining the fan floor table.

The tentative design would be to retrieve the pressure on a configured timer interval separate from the ambient changes that signal the action to update the fan floor speed. The action triggered on ambient changes would need to incorporate the cached pressure value when indexing into a provided 2-D fan floor table.

Detailed design TBD

**Comment by msbarth** [comment]
ex.)

  | 1015mbar | 1030mbar | 1050mbar
-- | -- | -- | --
35C | 1000RPM | 1500RPM | 2000RPM
36C | 1800RPM | 2000RPM | 2500RPM
37C | 2000RPM | 2500RPM | 3000RPM

**Comment by BMC-Bruce** [comment]
Pressure in Pascals (i.e. 1 mbar is 100 Pascals) can be read with:
`busctl introspect --no-pager xyz.openbmc_project.IIOSensor /xyz/openbmc_project/sensors/pressure/Station_Pressure`

Altitude in Meters can be read with:
`busctl introspect xyz.openbmc_project.VirtualSensor /xyz/openbmc_project/sensors/altitude/Altitude`

**Comment by spinler** [comment]
That's correct.  Can close this unless you want to track the implementation of the JSON.

**Comment by msbarth** [comment]
Resolved by:
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50667
- https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/50146
(Rainier 4U not planning to use altitude in floor determination)
