### ISSUE TITLE
Redfish: Code Update - Generate pull request and upstream priority concept

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#510]
We need the priority concept in Redfish so we can easily switch back and forth between firmware images (similar to how we can do now with the legacy REST api).

PR's are made against https://github.com/DMTF/Redfish
See https://github.com/DMTF/Redfish/pull/3296 for an example.

**Comment by rfrandse** [comment]
refresh

**Comment by bradbishop** [comment]
>We need the priority concept in Redfish so we can easily switch back and forth between firmware images (similar to how we can do now with the legacy REST api).
>
>PR's are made against https://github.com/DMTF/Redfish
>See https://github.com/DMTF/Redfish/pull/3296 for an example.

I got 404s when I tried to look at these links...

**Comment by geissonator** [comment]
> We need the priority concept in Redfish so we can easily switch back and forth between firmware images (similar to how we can do now with the legacy REST api). PR's are made against https://github.com/DMTF/Redfish See https://github.com/DMTF/Redfish/pull/3296 for an example.
> I got 404s when I tried to look at these links...

Ahh, yeah good point. You have to be a member of the DMTF github group to view those. I can send you directions on how to get that access.

**Comment by geissonator** [comment]
Opened https://github.com/DMTF/Redfish/issues/3357
Proposed schema changes up at https://github.com/geissonator/Redfish/commit/20cc036ff82b8baadcf9d3d80c906c31fc9eaaf1

You'll need github access to the DMTF/Redfish repo to see them.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
https://github.com/ibm-openbmc/dev/issues/794 tracks the outcome of the DMTF issue. The code will be written once officially approved in the Redfish spec. Will close this issue once the PR (https://github.com/DMTF/Redfish/commit/e27681b47b53bb12d51f73b241f2901b1055c6ef) is pulled in.

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Changes to spec have been approved and merged. This will now go through the standard DMTF process and eventually be published to the public. Once published to the public we can start working on implementing in #794
