### ISSUE TITLE
Swift: Update hwmon recipe(s) and add max31785 device

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#511]
Setup the hwmon recipe(s) to support swift under the witherspoon system layer and add support for the max31785 chip so fans are able to poweron for bring-up.

Related to issue https://github.com/ibm-openbmc/dev/issues/310

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/20638

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/20638 merged
