### ISSUE TITLE
GUI : Design :  Disable/enable out of band IPMI

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#512]
## Stakeholders
**SME**: Andrew Geissler, Joseph Reynolds
**Design Researcher**:
**UX Designer**:
**FED**:

## Use Case
As as user, I want the ability to enable and disable IPMI to prevent security vulnerability stemming from out of band network access to BMC / host. 

https://redfish.dmtf.org/schemas/ManagerNetworkProtocol.v1_4_0.json defines a property, IPMI, that is of type protocol, that has a ProtocolEnabled property. Use that to toggle the enable/disable of out of band IPMI

## References/Resources
Notes: https://ibm.ent.box.com/notes/476773318955

**Comment by gtmills** [comment]
Maybe a setting page for this feature?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
is this still planned for 9.4.1? @gtmills

**Comment by gtmills** [comment]
Andrew Geissler  
This fits in with @joseph-reynolds looking into disabling ssh. Users want a mechanism to pick and choose which external interfaces are enabled.

**Comment by joseph-reynolds** [comment]
Agreed.  See also #612.  The REST API for this is the Redfish ManagerNetworkProtocol IPMI property (https://redfish.dmtf.org/schemas/ManagerNetworkProtocol.v1_4_0.json).  It's the same Redfish protocol, but a different property (IPMI vs SSH).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/dev/issues/513 is the backend for this.

**Comment by jandraa** [comment]
- IPMI enable / disable currently possible via IPMI Command Line only 
- Use case of disabling IPMI = to prevent security vulnerability stemming from out of band network access to BMC / host 
- This feature would be admin-only and has no system state limitations + no reboot is required. 
- Will likely need a 'Security' page for this and others like disabling BMC shell access (https://github.com/ibm-openbmc/dev/issues/734) , Virtual Media, Redfish.

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/dev/issues/513 is the backend story for this.

**Comment by derick-montague** [comment]
Closing: Work being done in #1273
