### ISSUE TITLE
Redfish: Disable/enable out of band IPMI

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#513]
https://redfish.dmtf.org/schemas/ManagerNetworkProtocol.v1_4_0.json defines a property, IPMI, that is of type protocol, that has a ProtocolEnabled property. Use that to toggle the enable/disable of out of band IPMI

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Also, need a new D-Bus interface for this.

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
EdTanous> Disable of IPMI needs to be completely disabling the port.  Probably shutting down all the bridges.
<EdTanous> otherwise, it's still vulnerable at a protocol level

**Comment by bradbishop** [comment]
I think Intel has already implemented this.  Please make sure to interlock with Richard T over there before we write a bunch of code.

**Comment by gtmills** [comment]
Agree should interlock with Richard T over at Intel before working. ReadOnly is implemented, disabling is not. 

https://github.com/openbmc/bmcweb/blob/ec4974dd6a419b7f5556d4dcf4b8b836b5efbbd9/redfish-core/lib/network_protocol.hpp#L58

**Comment by wangkair** [comment]
1. I find there is no Settings for ipmi. How can we get the current status of ipmi? Add interfaces in Settings or check it by daemon phosphor-ipmi-net?
2. After getting the current status, do nothing if the status is correct already, or change the status to be false/true, then stop/start the daemon phosphor-ipmi-net?
3. Do we need to judge the current status first? Or just disable/enable ipmi directly?

**Comment by gtmills** [comment]
I think we need a D-Bus interface first, https://github.com/openbmc/phosphor-dbus-interfaces

Then some place to implement that interface.

**Comment by gtmills** [comment]
Could you send something to the list ?
I think a generic, Protocol phosphor-dbus-interface, with a ProtocolEnabled property

**Comment by wangkair** [comment]
Maybe the related D-Bus part is already implemented by Intel, but the code is not merged into openbmc yet. Wait for the code merge first, then go on this issue.
[1] https://github.com/Intel-BMC/provingground/tree/master/srvcfg-manager
[2] https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Control/Service/README.md

**Comment by gtmills** [comment]
Sounds good. Thanks for driving this. https://lists.ozlabs.org/pipermail/openbmc/2019-December/019889.html is the email from Richard

**Comment by gtmills** [comment]
I see https://github.com/openbmc/service-config-manager/tree/33816cf9125737e9ec931961bad2924a6104c5bb out there, can we use it?

**Comment by gtmills** [comment]
@tomjoseph83 https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32705 merged. Can we close this ?

**Comment by gtmills** [comment]
Closing. Please reopen if there is still work to do here.

**Comment by joseph-reynolds** [comment]
The patch identified GETs the SSH, HTTPS, and IPMI properties along with SNMP, NTP, etc., and HostName.  But it only allows PATCH for NTP and HostName.  GET/redfish/v1/Managers/bmc/NetworkProtocol returns data like:
```
{
  "@odata.id": "/redfish/v1/Managers/bmc/NetworkProtocol",
  "@odata.type": "#ManagerNetworkProtocol.v1_5_0.ManagerNetworkProtocol",
  "Description": "Manager Network Service",
  "FQDN": "witherspoon-REDACTED",
  "HTTP": {
    "Port": 0,
    "ProtocolEnabled": false
  },
  "HTTPS": {
    "Certificates": {
      "@odata.id": "/redfish/v1/Managers/bmc/NetworkProtocol/HTTPS/Certificates"
    },
    "Port": 443,
    "ProtocolEnabled": true
  },
  "HostName": "witherspoon-REDACTED",
  "IPMI": {
    "Port": 623,
    "ProtocolEnabled": true
  },
  "Id": "NetworkProtocol",
  "NTP": {
    "NTPServers": [
      "1.1.1.1",
      "2.2.2.2"
    ],
    "ProtocolEnabled": true
  },
  "Name": "Manager Network Protocol",
  "SNMP": {
    "AuthenticationProtocol": "CommunityString",
    "CommunityAccessMode": "Full",
    "CommunityStrings": [
      {
        "AccessMode": "Full"
      },
      {
        "CommunityString": ""
      },
      {
        "Name": ""
      }
    ],
    "EnableSNMPv1": false,
    "EnableSNMPv2c": true,
    "EnableSNMPv3": false,
    "EncryptionProtocol": "None",
    "EngineId": {
      "EnterpriseSpecificMethod": null,
      "PrivateEnterpriseId": null
    },
    "HideCommunityStrings": true,
    "Port": 161,
    "ProtocolEnabled": true
  },
  "SSH": {
    "Port": 22,
    "ProtocolEnabled": true
  },
  "Status": {
    "Health": "OK",
    "HealthRollup": "OK",
    "State": "Enabled"
  }
```

The next step would be to allow IPMI.Protocol Enabled to be PATCHed.

**Comment by joseph-reynolds** [comment]
Reopening to do the work described in the comment Sep 21, 2020.

**Comment by gtmills** [comment]
@joseph-reynolds Didn't https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/32705 add support for PATCHing IPMI.ProtocolEnabled ?

**Comment by joseph-reynolds** [comment]
Yes.  Yes it did.  Nice.  I completely missed that.  Thanks!  Re-closing this issue.
