### ISSUE TITLE
Propose plugin design for phosphor-logging

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#514]
To be able to convert xyz.openbmc_project.Logging.Entry objects to PELs, we're going to need to have plugins inside of phosphor-logging, and it needs a design.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/21071

**Comment by spinler** [comment]
Abandoning this and not going this direction.
