### ISSUE TITLE
GUI: FED: Login: Make Host field Read-only

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#515]
## Expected Delivery Dates
- [ ] FED: 5/30/19

## Stakeholders
**SME**:  N/A

## Description
For security reasons, we cannot switch to a different host on this panel. Make Hostname/IP address value read-only/not editable. We are making the BMC Hostname or IP address field read only

![image](https://media.github.ibm.com/user/1071/files/33667300-5544-11e9-89d4-8879a58e9868)

## Development Issue
---

**Comment by derick-montague** [comment]
@gtmills  This was in our Box file of work to be completed for OP940. Making the field read-only is great to let the user know that it can't be changed, but won't prevent a user from removing the read-only attribute from the DOM and changing the host. I expect that we already have security built in to the back-end code to handle this. Would that be true?

**Comment by gtmills** [comment]
Moved to OP950. Won't need changes on the backend. If the changes are as I understand, this will break running the GUI locally.

**Comment by derick-montague** [comment]
It will, but we can just remove the read-only attribute in the Developer Tools. If the concern is security, making it read-only client-side doesn't really protect us from someone changing the value.

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Can we close this ticket as something we won't implement?

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@derick-montague Why did we decide not to do this?

**Comment by derick-montague** [comment]
> Moved to OP950. Won't need changes on the backend. If the changes are as I understand, this will break running the GUI locally.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Discussed at sprint planning that we should remove the text field and simply display the IP address. We will need to have the backend create a flag that allows us to change the value for local development.

**Comment by gtmills** [comment]
@derick-montague I think the front end should have the flag that switches from Read-only to editable.

**Comment by derick-montague** [comment]
Already resolved in the Vue rewrite.

**Comment by derick-montague** [comment]
This is no longer valid. Updated in vue rewrite.
