### ISSUE TITLE
AST2600: u-boot updates required for AST2600

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#521]
All changes required to u-boot to support the new AST2600 chip system bringup
- platform.S, ethernet, timer, cortex a7, smp, mtd

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
We are up and running on AST2600.  Future uboot work will be tracked under separate issues.

**Comment by rfrandse** [comment]
refresh
