### ISSUE TITLE
AST2600: linux updates required for AST2600

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#522]
All Linux kernel and device driver updates required to use the AST2600 to boot a system.
- ethernet, timer, cortex a7, smp, mtd, pinmux, fsi 

Pinmux and FSI are the bigger parts of this story, we could break those down into their own stories if needed.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by shenki** [comment]
This is done.

**Comment by rfrandse** [comment]
refresh
