### ISSUE TITLE
AST2600: linux updates to support i2c and eMMC/SDIO

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#524]
The eMMC SDIO based NAND chip will be required in future OpenBMC systems so ensure it is working as expected with the new AST2600 chip from within Linux (and upstream any required change to make it work).

i2c support will also be critical for OpenBMC systems so ensure this function is working as well (and upstream any required change to make it work).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by eddiejames** [comment]
Support for both I2C and eMMC/SDIO on the AST2600 has been sent upstream
