### ISSUE TITLE
AST2600: secure boot support in u-boot

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#525]
Verified and secure boot along with crypto/hash functions in u-boot

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by shenki** [comment]
This has been merged into the openbmc u-boot tree as of https://github.com/openbmc/u-boot/commit/44a8c618c1215e0faac0f335f0afd56ed4240e76
