### ISSUE TITLE
Table: Semantic markup

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#527]
## As Is
Our current table layouts are not using HTML table elements. The primary reason is to better handle small screen display of the data. The usability from a screen reader perspective is not acceptable, but the markup used will not be flagged by accessibility testing tools. 

## To Be
We need more research prior to making changes to the mark up. Specifically, what screen sizes we support and how our table data should render.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
We have a pattern in place on the Sensors table that we can use to update other tables. This is also an accessibility enhancement.

**Comment by derick-montague** [comment]
All tables will be coded semantically in the vue rewrite.
