### ISSUE TITLE
PDM: Median temp sensor based shutdown

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#528]
Enhance PDM to support performing a shutdown based on the median value of a group of sensors. Verify that when an odd number of sensors are in the group, the median is the center value, when there's an even number of sensors, the median is the average of the 2 middle values. Use `std::nth_element` ?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/25001

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-monitor/+/25001 merged
