### ISSUE TITLE
Swift: PFP: Update fan floor action to use median ambient temp

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#529]
To support additional ambient temp sensors, the fan floor action should predetermine the ambient temp to index into the fan floor table based on the median value of the group of ambient sensors.

Verify that when an odd number of sensors are in the group, the median is the center value, when there's an even number of sensors, the median is the average of the 2 middle values. Use std::nth_element ?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
The "median" ambient temp to be used will be determined from the set of ambient temp sensors that are within a configured range of valid ambient temps. This boundary range will remove any ambient temp sensor that provides a reading that's out-of-range when determining what fan floor speed should be used.

The end result of valid ambient temps will be handled as follows as a selectable action within the fan control events:
- 0 valid ambient temp readings, run with the default fan floor speed
- 1 valid ambient temp reading, determine fan floor speed from provided table using that reading
- 2 valid ambient temp readings, use the highest reading to determine fan floor speed from provided table
- \>=3 valid ambient temp readings, use the median reading to determine fan floor speed from provided table

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/22101

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-fan-presence/+/22101 merged
