### ISSUE TITLE
Telemetry implementation : Implement Layer 1

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#53]
<a href="https://github.com/dkodihal"><img src="https://avatars1.githubusercontent.com/u/22700515?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dkodihal](https://github.com/dkodihal)**
_Tuesday Sep 05, 2017 at 11:59 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2253_

----

Implement the design from #1957. @tomjoseph83 to add details to both stories.

**Comment by rfrandse** [comment]
<a href="https://github.com/tomjoseph83"><img src="https://avatars3.githubusercontent.com/u/15232150?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomjoseph83](https://github.com/tomjoseph83)**
_Thursday Sep 21, 2017 at 08:35 GMT_

----

- [ ] YAML parser for the policy yaml, to generate code
- [ ] Define the data structure to process updates for each aggregation dbus object
- [ ] Implement the minimum, maximum and average interface

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
No plans to implement.  Closing this.
