### ISSUE TITLE
Redfish: Code Update - SimpleUpdate implementation of TFTP

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#531]
This is the implementation story of #488 

This is the bmcweb code required to implement the proposed design there

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/20884/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/20884 merged
