### ISSUE TITLE
Create eBMC Code Update Design doc

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#533]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by sivassrr** [comment]
@anoo1 the above link points to emmc (is it intended for eBMC) storage design. Is it the right link for code update design?

**Comment by anoo1** [comment]
I guess there could be a separate doc on how to write to the emmc.

**Comment by anoo1** [comment]
Have been doing incrementing updates to the emmc doc. The code update interfaces remain the same.
