### ISSUE TITLE
Design: SBE and Host initlization Infrastructre.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#535]
Provide a generic infrastructure design  for SBE/Host initialization  and error handling

Host IPL Requirements 
* Provide an infrastructure to initiate and manage all BMC isteps requests , based on  IPL flow  document. 
* Istep function should be easily pluggable in eCMD istep infrastructure  ( Nice to have now)
Design Direction: Extend the existing Target based IPL infrastructure. 

Functional Requirements 
* Support  all required BMC owned  isteps as per the  IPL flow document.
    * Call  appropriate procedure provider or applications. 
* Support special Sate manager Request like , termination request, power-off, Reset-reload, during IPLing. . 
* Call  Error log services for error log processing and send updated error log back to IPL Service for action.  
* Must be able to interrupt a sync point incase of IPL Failure 
* Must provide interface to hostboot to generate FFDC (used in situations where terminating error is detected and BMC is going to take down hostboot) 
* Must provide required interfaces as defined by other services (OCC reset support) 
* Must provide interface to see payload running/Host boot state. 
* Interface , which includes Host functions , to Prepare the system for power off. 
* Support all reset and ipl types (reset/reload, memory preserving, re-ipl, and hardware configuration changes) 

---

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Initial investigation completed, Working Design documentation.
@dhruvibm will be sending proposal in this week.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
@dhruvibm is going to upload new version document by 09/11 , 
  - Closing all open issues. and addressing all Review comments.

**Comment by ojayanth** [comment]
With new direction , planing to use Openpower based IPL repository for  Boot process. BMC front design direction is to extend the existing  start-host in openpower-power-procontrol to iPL the system and for command line use ecmd based infrastructure.  

Closing this issuie .
