### ISSUE TITLE
Design Interface:  debug unresponsive host

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#536]
#457 provides the background details.

Issue scope: 
- Design d-bus interface for SBE sreset chip-op to issue processor reset.
- Proposal for the redfish based external interface.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
@lkammath

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by lkammath** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/21770/ (Under review)
https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-proc-control/+/22193/ (Under review)
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-openpower/+/22502/ (Under review)
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/22661/ (Integrated)
