### ISSUE TITLE
HMC-BMC : Design the redfish interface for save-area

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#538]
HMC keeps the save area files in side the BMC, there requirement is to provide the read/write/update these files.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
will track this with this epic https://github.com/ibm-openbmc/dev/issues/787
