### ISSUE TITLE
HMC-BMC : Design the framework for lock management

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#539]
HMC have various use cases where they want to get the lock and then provide the operation on the bmc.
One of the requirement is, when there are multiple HMC connected on the BMC and one of the HMC doing the virtualisation operation then other HMC should not be allowed to do the virtualisation operation.
There are more such use cases, still needs to be discussed.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by manojkiraneda** [comment]
Code is up for review : https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/27671

**Comment by ratagupt** [comment]
The aim for this story to come up with the framework for the lock management seems that is done so closing this story.
