### ISSUE TITLE
HMC-BMC: HMC should be uniquely identifiable

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#540]
If there are multiple clients connected to the BMC then BMC should be having a way to uniquely identify the HMC.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
With this story needs to do the following

- Extend the session schema to support the OEM property(Client Identifier,IP address)
- Implement the session schema
- During the creation of the session store the IP address also.
- Support the PATCH operation only for ClientIdentifier not for IP address.

**Comment by sunharis** [comment]
Below are the commits for the same.

https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/32118/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/32179/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/32593/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/32704/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/32911/

**Comment by sunharis** [comment]
Code merged to master

**Comment by sunharis** [comment]
Support the PATCH operation only for ClientIdentifier not for IP address. ===> The PATCH operation is dropped.
