### ISSUE TITLE
Redfish: SensorCollection and sensors underneath

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#542]
Sensor Collection should be all the sensors not underneath Power/Thermal. 

Should include the current/ sensors since there isn't a place in Power/Thermal
```
}bash-4.1$ curl -k https://${bmc}/xyz/openbmc_project/sensors/current/
{
  "data": [
    "/xyz/openbmc_project/sensors/current/p0_vcs_current",
    "/xyz/openbmc_project/sensors/current/p0_vdd_current",
    "/xyz/openbmc_project/sensors/current/p0_vddr_current",
    "/xyz/openbmc_project/sensors/current/p0_vdn_current",
    "/xyz/openbmc_project/sensors/current/p1_vcs_current",
    "/xyz/openbmc_project/sensors/current/p1_vdd_current",
    "/xyz/openbmc_project/sensors/current/p1_vddr_current",
    "/xyz/openbmc_project/sensors/current/p1_vdn_current",
    "/xyz/openbmc_project/sensors/current/ps0_output_current",
    "/xyz/openbmc_project/sensors/current/ps1_output_current"
  ],
```

Should include all non-powersupply power/ sensors (e.g. /xyz/openbmc_project/sensors/power/p0_vcs_power)
```
curl -k https://${bmc}/xyz/openbmc_project/sensors/power/
{
  "data": [
    "/xyz/openbmc_project/sensors/power/p0_vcs_power",
    "/xyz/openbmc_project/sensors/power/p0_vdd_power",
    "/xyz/openbmc_project/sensors/power/p0_vddr_power",
    "/xyz/openbmc_project/sensors/power/p0_vdn_power",
    "/xyz/openbmc_project/sensors/power/p1_vcs_power",
    "/xyz/openbmc_project/sensors/power/p1_vdd_power",
    "/xyz/openbmc_project/sensors/power/p1_vddr_power",
    "/xyz/openbmc_project/sensors/power/p1_vdn_power",
    "/xyz/openbmc_project/sensors/power/ps0_input_power",
    "/xyz/openbmc_project/sensors/power/ps1_input_power"
  ],

```

`/xyz/openbmc_project/sensors/power/ps1_input_power` will be mapped to Power -> PowerSupply -> PowerInputWatts

So everything in power/  but ps1_input_power and ps0_input_power should in the SensorCollection.

All /xyz/openbmc_project/sensors/temperature/ sensors should be under Thermal -> temperatures so no need for them.

All /xyz/openbmc_project/sensors/voltage/ sensors should be under Power -> Voltages so no need for them. 

Alll /xyz/openbmc_project/sensors/fan_tach/ should be under Thermal -> Fans so need for them.

https://redfishforum.com/thread/190/sensorcollection-contain-all-sensors-chassis

https://redfish.dmtf.org/schemas/SensorCollection.json
https://redfish.dmtf.org/schemas/Sensor.v1_0_0.json

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22496

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22496 merged
