### ISSUE TITLE
Phosphor-user-manager: Restructure the code to support multiple LDAP configs

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#543]
Restructure the backend code to support the following requirement
1) Default ldap config object should always there
2) Should support for ldap and active directory default object.
3) Should be scope for enhancement if additional account provider needed to support.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@ratagupt What commit closed this?

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Following commit fixes this issue and they are merged, so closing the issue.

https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-user-manager/+/20580
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-user-manager/+/18746/
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-user-manager/+/20581/
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-user-manager/+/20585/
