### ISSUE TITLE
Options: GPU Throttle

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#545]
## Expected Delivery Dates
- [ ] UX: 5/30/19
- [ ] Backend: xx/xx/xx
- [ ] FED: 7/11/19

## Team
**SME**: Martha Broyles, @spinler 
**DR**: @nicoleconser 
**UX**: 
**FED**: 

## Use Case
- [ ] GPU Throttle
Unclear what work is needed. Backend not ready.
If the temps get too high, instead of burning down the system or getting too hot, it crack up the fans, if still too high, cut down on the power to processor (lower voltage rate) and memory (slow down transaction rate). This is called throttling. As a user, it is important to know when throttling is happening because it will affect my performance. 

## Requirements
Similar to displaying temperature sensors, we also need to display the throttling sensors.  All we need to show is the current status of the sensors, e.g. if they are throttling or not. There is no need to show any event logs or error logs as they are not necessarily error conditions.

## InVision Prototype
---

## Design Issue (phosphor-webui)
---

## Development Issue 
---

## References/Resources
---

**Comment by derick-montague** [comment]
Conversations with @spinler indicated that:
1. GPU Power is a sensor and does not require design work
2. GPU Throttle is not ready enough to determine if GUI work is needed or not based on the SME feedback provided to @jandraa.
3. Min/Max is still being researched

**Comment by jandraa** [comment]
GPU Throttling sensors will be moved out until the P10 timeframe for the Swift follow on

**Comment by derick-montague** [comment]
Seems like the milestone should be updated to one of the A milestones.

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Removed GPU power from this design issue since it will not require any FED or Design work

**Comment by derick-montague** [comment]
> GPU Throttling sensors will be moved out

The milestone has been updated and correctly reflects the expected OP950 milestone.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jandraa** [comment]
Likely will not support in the GUI; waiting on confirmation from @mzipse and Todd Rosedahl.

The main reasoning is that we cannot get an instant read of GPUs from the OCC so it could often be outdated information by the time a user sees it.

**Comment by derick-montague** [comment]
Determined that we will want to support throttle for 9.5.x. Moving these to backlog.

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@ryanarnell - Please consolidate this with #588 and close this story. Thank you!

**Comment by ryanarnell** [comment]
Consolidated this with #588 and closing this issue
