### ISSUE TITLE
Design for PEL message registry

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#546]
For every error we create, we need a message registry entry to hold the PEL related fields, along the lines of

```
[
    {
        "name": "xyz.openbmc_project.Power.Error.PGOODFault",
        "reasoncode": "0x2525",
        "subsystem": "PROCESSOR",
        "severity": "unrecoverable",
        "callhome": true,
        "desc": "A power unit had a PGOOD fault",
        "message": "Power unit $1 had a pgood fault of type $2",
        "messageArgs":
        [
            {"type": "string", "desc": "power unit type"},
            {"type": "string", "desc": "type of pgood fault"}
        ]
    }
]

```

We will need to go through the PEL spec to figure out what all we'll need here.  Some of the things above may only be for Redfish, though we can probably use a separate story to track those.  If applicable, we'd want build time validation on fields that may be enums.

This would probably be 1 or more JSON files on the BMC.  Is there also 1 master one in a layer somewhere?   maybe multiple ones?  where?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/23240

**Comment by spinler** [comment]
Probably not going to merge this.  Design done though.
