### ISSUE TITLE
Design for PEL repository/API

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#547]
A PEL needs to be created when openbmc log entries are created, and deleted when they are deleted.  PELs can be up to 16KB in size, and need to be storied persistently in the filesystem somewhere, somehow.  The plan now is for there to be a shared library API for managing them.  If there needs to be any additional metadata with the PELs, like maybe a mapping of Logging.Entry IDs to PEL IDs, that will also need to be persisted.

Users of this API would be:
* the log-manager daemon
* the PLDM handlers
* possibly bmcweb, depending on if it would be allowed in.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Not going to make a separate design doc for this.  Will do as part of #402.
