### ISSUE TITLE
PEL construction:  Add AdditionalData fields to user data 

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#549]
Cram the 'AdditionalData' error log property into a user data section in the PEL

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
In fact, we should probably just store the entire obmc event log, so we get the error name and original severity too.

**Comment by spinler** [comment]
Just the AdditionalData handled by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/26537
