### ISSUE TITLE
PEL construction: Required sections

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#550]
Fill in the required sections in a PEL:

* Private Header
* User Header
* Extended User Head
* Failing MTMs

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
These sections are all done, except for the Extended User Header section which is tracked by #1090.  Closing.
