### ISSUE TITLE
Implement PEL repository/API

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#552]
Implement what was designed in #547

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Need this support before converting obmc logs into PELS for receiving PELs from the host  - https://github.com/ibm-openbmc/dev/issues/755.  Created more granular issues there for this, so closing this one.
