### ISSUE TITLE
Implement StoreErrorLog PLDM command backend

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#554]
When a PEL comes down from PLDM, create an openbmc error log out of it.  Also have to take the original PEL, probably modify a few fields in it, and associate it with that error log instead of having the log-manager PEL handler create its own PEL.

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Renaming this to describe the actual PLDM command it will use.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Creating an OpenBMC log will happen in the PLDM handler. Feels like I should still track that here though.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
No extra work needed here. The PLDM team is creating the event log to pass over the PEL.
