### ISSUE TITLE
Write Terminating SRC to the panel

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#556]
Need to post terminating and progress SRCs to the panel.

In manufacture mode, the first error log (of any type?) should terminate.

Need to keep a history of progress SRCs.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
A doc on Redfish POST codes that maybe we can use: https://github.com/openbmc/docs/blob/master/designs/redfish-postcodes.md

**Comment by spinler** [comment]
I'm changing the scope of this to just deal with writing terminating SRCs to the panel.  progress SRCs will be handled elsewhere.

**Comment by sumitk56** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/46944

**Comment by sumitk56** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/46944
