### ISSUE TITLE
Create IPMI SELs out of PELs in SPNext

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#558]
Not sure yet if what we are doing for Witherspoon will still work or not.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
This is for getting SELs into IPMI, like ipmitool

**Comment by spinler** [comment]
I have seen no plans to change the IPMI SEL strategy between Witherspoon and Rainier, so I'm going to close this.  Any work to do any SEL support needed on Rainier would be covered by the IPMI team just like all the  other IPMI functionality.
