### ISSUE TITLE
Telemetry design : define Layer 2 YAML.

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#56]
<a href="https://github.com/dkodihal"><img src="https://avatars1.githubusercontent.com/u/22700515?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dkodihal](https://github.com/dkodihal)**
_Friday Sep 15, 2017 at 10:39 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2315_

----

@tomjoseph83 to add details here and/or #1957.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
No plans to implement.  Closing.
