### ISSUE TITLE
Support the PELish Redfish log format

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#560]
There will be a new Redfish log format, either OEM, or normal with OEM fields, or a new standardized format, that will contain a lot of the fields from the PEL, plus a message, a description, and some message args.  These will be created, probably, in bmcweb from our PELs.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
I'm very tempted to close this since field support only wants to use PELs to debug, but the thing that is hanging out is how a user without an HMC would be able to get the SRCs from event logs to look them up in the KnowledgeCenter, or for that matter to know what was called out.

**Comment by spinler** [comment]
The fields that are needed in the event log are at https://ibm.ent.box.com/notes/791481299908.

When building the response, bmcweb can only get things from D-Bus, so we'll need to put new interfaces on the log entries.
Some are:
* SRC ascii string + SRC words for the event ID
* The call home action flag value for AutomatedServiceNotify
* The Resolution field, a string, which contains all  the callouts.

**Comment by spinler** [comment]
Step 1:  Figure out which additional information is needed on D-Bus and propose phosphor-dbus-interface interfaces for them.
Step 2:  Write phosphor-logging code to put those fields on D-Bus
Step 3: Write bmcweb code to get those fields from D-Bus and put them in the Redfish response.

**Comment by spinler** [comment]
Created stories #3081, #3082, #3083  for the pieces.

**Comment by spinler** [comment]
Closing this one since I broke it out into separate issues.
