### ISSUE TITLE
Propose  Redfish log format(s) that contains our PEL data

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#562]
Need to come up with the actual log format(s) that can contain our PEL fields, plus a way to provide access to the raw PELs.  Get it standardized?  An OEM field in an existing format?  All OEM?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
This was done by others. Closing.
