### ISSUE TITLE
   Additional VPD collection (panel, Cassin, VRMs)

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#564]
## Expected Delivery Dates
- [ ] UX: xx/xx/xx
- [ ] Backend: xx/xx/xx
- [ ] FED: xx/xx/xx

## Stakeholders
**SME**: @santoshpuranik 
**DR**: @nicoleconser 
**UX**: 
**FED**: 

## Use Case
---

## InVision Prototype
---

## Design Issue (phosphor-webui)
---

## Development Issue 
---

## References/Resources
---

**Comment by spinler** [comment]
I don't think this will take any GUI work.  It will just end up being new items in the firmware inventory.

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Closing this GUI ticket. Verified by @gtmills  and @spinler that no GUI work should be needed. Can create new in the future if needed.
