### ISSUE TITLE
When a part is replaced, resolve any errors that have that as the only callout

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#565]
Set the Resolved property to true on error logs when we detect a part is replaced and that part is the only callout.  Then these would be able to be pruned if necessary.

If there were multiple callouts, I'm not sure how we'd track if all those FRUs were replaced, so putting a stake in the ground saying we're not going to do that.

This is just a hunch, we should ensure we really need to do this.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
This would be going above and beyond, which we aren't in a position to do.  Closing.
