### ISSUE TITLE
Redfish Maintenance Logs

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#566]
The request is:

Provides logs for when the hardware or firmware change in the system
Firmware changes are recorded today on FSP
CPU changed from SN xxxx to SN yyyy
Firmware changed from version xxxx to yyyy
Need to flag VPD changes up the stack.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@spinler is this the same as #2006  ?

**Comment by spinler** [comment]
At this point I think this would need a line item, so closing.

**Comment by Tommy-git2033** [comment]
Hi,spinler.
I'm now also trying to do what you referred:Maintenance Logs for HW changes or firmware Update. Have you already implemented it? Or any design docs.

**Comment by spinler** [comment]
No, I never ended up getting anywhere with this.
