### ISSUE TITLE
Rainier Power On and Sequencing, Pgood - FF

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#569]
High-level Requirements:

1.  Power app must support power on requests. 
2.  Power app must initiate hardware power on sequence to the power sequencer.
3.  Power app must configure the power sequencer if hardware defaults are not suffice. 
4.  Power app must monitor the power sequencer for power/reset problems (during IPL and at runtime only).   Power app must power the system down if needed. 
5.  Power app must detect (from power sequencer), isolate, and report individual power FRU faults (during IPL and at runtime only).

Design:

Power on and sequencing:
IPL progress codes.  Discuss timings in error log discussions.

Re-collect vpd from anything appropriate since could be swapped at standby (eg op panel if need to know type of sensors, procs if ensuring procs correct or it specifies reg requirements, etc).
Ensure minimum off delay expired.
Ensure PS config valid.

Dasd bp vpd handled via common PLDM vpd design.

Power off:
start 25s min off delay - allows caps to discharge etc and helps prevent thrashing during brownouts

Runtime Pgood monitoring:

Update pgood monitoring code for UCD90320 (and other 2nd level isolation as needed).  Simplify isolation methodology, and make data driven.
Deglitch as appropriate (5s+) to be able to point to PS fail as root cause.
Retry pon seq (3 times total) if get runtime pgood fail?

Pgoods from ddimm pmics how (sbe or io expander)?

Ensure chip resets ("BMC_DCM_ALL_RESET") cleared, monitored, and checked during failures appropriately.  Will not go to each system chip, just a subset, sometimes just to sanitize chips.  This defaults to inactive in hardware, and state management will toggle during ipl/re-ipl.  Should we monitor it when seeing pgood fails?

System config file (mrw xml or json? need to write script/etc to get the data from source file) have data that defines deglitch counts (5+), # of seconds between reads (1), # of fails etc to abstract from code).

No GPUs planned so no unique handling needed.

**Comment by mzipse** [comment]
refresh....test.  please ignor.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
