### ISSUE TITLE
Rainier UPS Support

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#571]
High-level Requirements:

1.  Power app must monitor and report utility failures if UPS hardware present. 
2.  Power app must ensure UPS backup power is adequate when present.

Design:

USB device drivers available per discussion below.
Determine if any UPS code is already available (such as networkupstools.org).

Log errors for utility fail / battery low status.
Send PLDM events to PHYP with State Set changes.
Determine what DBUS notification to BMC state management apps are needed.
Prevent system power on if seeing uf/battlow status.
No consolidation of inputs from USB, RPC, enet, io tower, etc needed. Do not need to consolidate UPS bits with impending power failures and thermal fault bits in event.  IPF no longer needed, and TF will be portrayed in a separate state set. PHYP will consolidate as needed for OS expectations.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bradbishop** [comment]
Was there anything useful at networkupstools.org?

At a minimum, there is a "drivers" directory that seems like we could reuse to support different upses.  they aren't "drivers" in the kernel sense but rather a bunch of code that attaches via usb/serial and makes sense of the signals coming out of the specific ups.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@derekhoward55 Does this include all the APIs the GUI will call for Platform UPS?

**Comment by bjwyman** [comment]
@mzipse I doubt this can be tested on SIM-HW. I am not aware of any models to mimic what this would be looking for to reflect a USB attached UPS status.

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@bjwyman, I'm not surprised about the simulation models not existing.  That "Test on SIM-HW" implies either testing on SIMICS OR testing on real Rainier HW.  I agree that in this case, we'll want real HW.  I guess there might be a question on whether we could test this on a Witherspoon/Tacoma HW system?......not sure if all the connections exist or not.

**Comment by bjwyman** [comment]
@mzipse Sorry, misinterpreted the label's meaning.

Testing on real Rainier hardware makes the most sense. I really doubt the connections/hardware exist on Witherspoon or Tacoma.

**Comment by rfrandse** [comment]
refresh

**Comment by amboar** [comment]
What UPS are we supporting? I guess this ties into @bradbishop 's networkupstools.org question.

**Comment by derekhoward55** [comment]
> What UPS are we supporting? I guess this ties into @bradbishop 's networkupstools.org question.

I believe there are many different UPS's from many different vendors that can be attached to the systems.  I can ask someone in planning like Joe Prisco if he has a complete official list if you'd like.  But we've never needed to know that in the past, as long as we get the 4 standard bits (via usb cable in this case), it doesn't really matter what type of UPS is attached.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by joseph-reynolds** [comment]
The UPS can be plugged into the BMC's USB port so they can communicates with each other.  There were discussions about whether or not the BMC admin should have the ability to disable this interface.  (When the BMC's UPS USB interface is disabled, the BMC no longer communicates with the UPS.)
We decided this is not a priority and will not work on it at this time.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
