### ISSUE TITLE
Rainier Power Line Disturbance (brownout, blackout)

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#572]
High-level Requirements:

1. Power and state management apps must keep system in appropriate state after brownouts and blackouts. 
2. Power app must report utility power faults (during boot and at runtime only).

Design:

Monitor power supplies for input power faults.  Latched vs dynamic AC loss handling.  900W&1400W PS have flaky voltage value reporting.

If main pgood (12v bulk) goes down and any PS reporting AC loss, shut off with 00AC equivalent.

Deglitch&ignore temporary voltage dips as long as power is good. unlatch vin faults.

If subset of PS lose AC but power remains good, log error against each PS.

If all present PS report input power fault, try to stay up or do orderly shutdown? Try to stay up. no guarantee 12bulk goes down before 12sb. Hw does guarantee 12vbulk fault is reported before it goes down.

APR if "always on" mode selected once AC returns.  Need AC returned to all, don't want to thrash? No, in case dual line cord configuration, and one utility comes back and other one doesn't.

Persist system state to read post-blackout.  APR if "always on" mode selected.

Differentiate standby vrm fault vs AC loss? Yes, implemented on BMC systems already, confirm implementation with EmileK.  If 12VCS_FAULT_N gpio inactive after BMC comes up after it was POR reset when powered on, callout backplane (standby vrm fail) instead of AC loss.

Ensure pgood hw design appropriate - pgoods flagged before chip errors, chip resets tied together, etc​.

Ensure dual line cord testing handled.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
