### ISSUE TITLE
Rainier Temp Monitoring

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#573]
High-level Requirements:

1. Thermal app must collect temperatures from system components.  This includes disk backplane, pcie card sensors (either in-band or direct sensor reads), and pcie planar (during IPL and at runtime only). 
2. Power app must collect ambient temperature from hardware sensors. 
3. Power app must collect ambient temperature and altitude limits from the yaml configuration file. 
4. Power app must log errors for exceeding ambient warning limits, ambient EPOW3/4 limits, and altitude limits. 
5. Thermal app must log errors for component over-temperatures received from OCC. 
6. Power app must report ambient temps to IPMI&DCMI&Redfish requests. 
7. Power app must report altitude to Redfish requests. 
8. Thermal app must determine EHI based on power usage, altitude, and ambient, and report to Redfish requests. 
9. Thermal app must collect component temperature information from the OCC for reporting to IPMI&Redfish. 
10. Thermal app must report component temperatures to IPMI&Redfish requests.  Refer to the EnergyScale Accipiter Command Architecture document for the complete list of thermal interface requirements. 

Design:

Confirmed number and types of ambient (1 TMP275), altitude (1 DPS310), humidity (1 Si7021-A20) sensors.
Si7021-A20 has a similar DD already.  Temp in dbus already, work needed to get humidity in dbus.
DPS310 pressure sensor DD already done by Eddie.  Stories exist for previous system.  Temp in dbus already, work needed to get altitude in dbus.

Thermal team cares about pressure, not necessarily altitude, for fan control.  Need to be converted to altitude for fan control?  Yes, to meet up with ASHRAE requirements.  Determine if alt or pressure should be in config data.  Read once per IPL for logging "outside environment" error (above 4000m in sys workbook).  Thermal team would like it included in fan floor determination, TBD if we have time to add support.

Does humidity affect fan control? typically not, only in extreme dry/humid environments.  Just wanted for smarter data or potentially if system out of spec, not fan control.  DD supports the sensor, but data not in dbus. No support planned.

What is exhaust temperature used for? Not used for ibm systems.  Was estimated and passed up in past.  Is used in pid control openBMC code.  Not needed.

Design/implement data-driven.  Sensors expected and limits in yaml today, convert to json.  EPOW/perf loss limits in def file today, store these where?  (eg entity manager backplane.json config file)

Design hot card determination for fan speeds or additional fans if needed? No boost fan.  General hot adapters, cable cards, PCIe switches, and nvme drives.

Design/implement ambient temp sensor(s) reading, pick floor, log errors.  
3-ambient reading alg should be implemented like on previous system.

Read component temp sensors using appropriate interfaces. BMC-connected and from OCC.
(PMICs? Which TMP275s? etc)

Vdd VRM temp is the only vrm temp needed for fan control per thermal engineers.  Already read via i2c and part of fan control for witherspoon, use same support for Rainier.  OCC also reads Vdd vrm temp over AVSbus and returns to BMC in poll response.  BMC ignores this, but can use in future if need be.  VRM temps included in telemetry data.

Any different GPU handling (temp or power)? No GPUs supported in this system.

Determine if corrosion sensor support needed.  Not much value according to hw team. None in system workbook. No support needed.

Put this info in LLDD?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
