### ISSUE TITLE
IPKVM: Page heading and new tab

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#576]
1. New tab button
2. Page heading

*More info coming*

**Comment by gtmills** [comment]
See: https://github.com/openbmc/phosphor-webui/issues/81

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Are we still expecting to do this for 9.4.1. I don't remember talking about it during sprint planning.

**Comment by derick-montague** [comment]
@gtmills this is a tracking ticket based on the story you opened in phosphor-webui. Is this critical for OP940?

**Comment by gtmills** [comment]
We can move to OP950, if we have time we can pull in.

**Comment by rfrandse** [comment]
refresh

**Comment by jandraa** [comment]
Does this need design work?

**Comment by derick-montague** [comment]
> Does this need design work?

I don't think so. Looks like this in InVision

![image](https://user-images.githubusercontent.com/1183515/59623117-fa787c00-90f8-11e9-8431-6da51e52666d.png)

**Comment by rfrandse** [comment]
refresh

**Comment by dixsie** [comment]
Waiting until the following changes are applied to the next build https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25231 to test if multiple KVM consoles can run concurrently (in main window and new window).

If it works need delete the rfb.disconnect()

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24577

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24577 merged
