### ISSUE TITLE
Make new D-Bus method for creating a Logging.Entry event log

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#578]
If we just make a D-Bus method for creating a phosphor-logging event log and use that instead of the elog()/commit()/report() calls, it could simplify a lot of things:

* Since all of the metadata would be passed into the method, the logging code wouldn't have to go digging around in the journal, which isn't the fastest.
* There would be no need to include either elog-errors.hpp with the predefined metadata fields since they aren't used anymore, or the sdbusplus error header files, since there doesn't need to be an exception created.
* The error doesn't need to be predefined in a YAML file anymore, for compile time processing by both sdbusplus and phosphor-logging, which can be a big headache when working in SDKs.
* Since we don't need elog-errors.hpp, we don't have to worry about the compatibility problem of trying to have both that global header and a repo specific version of that header included by the same file.

The downsides are:
* There are no compile time checks of what is passed into the error like before.
* There is no concept of passing around that error like elog() could do by throwing an exception.
* The logging code isn't able to use any predefined data at all, so the caller would have to pass in all of it, like the severity which it didn't have to before.
* There is no place to have a description which was in the yaml before, which would show up in the journal.  (Note that our PEL message registry files would have this still)
* These types of errors couldn't be returned from D-Bus method/property calls like they can be today.  However one could still just use the old method if that was desired.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
D-Bus interface proposed at https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/22053

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23927

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23927 merged
