### ISSUE TITLE
Include Power Cycle count in System telemetry data

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#58]
<a href="https://github.com/spinler"><img src="https://avatars1.githubusercontent.com/u/9370114?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [spinler](https://github.com/spinler)**
_Wednesday Nov 01, 2017 at 14:46 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2543_

----

There is a requirement to know how many times the system has booted.

This will need to persist across AC loss of course.

**Comment by rfrandse** [comment]
<a href="https://github.com/geissonator"><img src="https://avatars2.githubusercontent.com/u/1612261?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geissonator](https://github.com/geissonator)**
_Thursday Nov 02, 2017 at 16:16 GMT_

----

FYI @tomjoseph83 @dkodihal

**Comment by rfrandse** [comment]
<a href="https://github.com/spinler"><img src="https://avatars1.githubusercontent.com/u/9370114?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [spinler](https://github.com/spinler)**
_Monday Nov 20, 2017 at 14:55 GMT_

----

To clarify - the count is how many times we turn on power, not necessarily how many times the host has booted all the way.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Discussed this today with @derekhoward55 and others.  This is still desired on eBMC because it was done on the FSP.  On P9 FSP the power on count was written into each processor VPD, though there is some question if that still occurred on P10.  If not done on P10 FSP, then it won't be needed on P10 eBMC.  However, having this in telemetry is still required.

**Comment by spinler** [comment]
In case it matters, the FSP also reported power on hours in telemetry.  That is already on D-Bus with the xyz.openbmc_project.State.PowerOnHours interface in the chassis state manager.

**Comment by spinler** [comment]
It was decided that we no longer need to do this, since there were no users of it.
