### ISSUE TITLE
Humidity Sensor Support

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#581]
## Expected Delivery Dates
- [ ] UX: xx/xx/xx
- [ ] Backend: xx/xx/xx
- [ ] FED: xx/xx/xx

## Stakeholders
**SME**: @spinler 
**Design Researcher**:
**UX Designer**:
**FED**:

## Use Case
---

## InVision Prototype
---

## Design Issue (phosphor-webui)
---

## Development Issue 
---

## References/Resources
---

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jandraa** [comment]
Not supporting https://github.com/ibm-openbmc/dev/issues/475

**Comment by derick-montague** [comment]
Will not be in GUI
