### ISSUE TITLE
GUI: Design: Options - Display Min / Max Power Cap

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#582]
## Stakeholders
**SME**: @spinler, Martha Broyles
**Design Researcher**:
**UX Designer**:
**FED**:

## Use Case
As a user I need to know the system's power min and max limits in order to set the power cap.

## InVision Prototype
https://ibm.invisionapp.com/share/QKNZAGECYNF#/319278728_01-Min-Max

## Design Issue (phosphor-webui)
Display Min / Max Powercap:
https://github.com/openbmc/phosphor-webui/issues/95

## Development Issue 
Should display the min/max power cap on D-Bus/Redfish:
https://github.com/ibm-openbmc/dev/issues/957

## References/Resources
https://ibm.ent.box.com/notes/450253563151

**Comment by derick-montague** [comment]
@jandraa @nicoleconser  - Do we need to determine if this needs to be delivered as part of OP940 instead of OP950?

**Comment by jandraa** [comment]
Yes, Maury said it would be good to have for OP940, and to verify with Todd Rosedahl what his thoughts are.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
https://github.com/ibm-openbmc/dev/issues/957 is the backend story

**Comment by derick-montague** [comment]
I believe we are moving this out to a 9.5.x release

**Comment by rfrandse** [comment]
refresh
