### ISSUE TITLE
Rainier Power Supply Debug tool

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#583]
Create a command line interface for getting power supply (PS) status (presence, on, fault, AC fault, location code, input power, etc).  Include power resource status (PRS) and "powr psu status" info:

-------------------------------------------------------------
Entry 1, total entries: 4
-------------------------------------------------------------
Power supply status dump: (pnnum=0)
  Presence: PRESENT  Node state: POWER_NODE_DOMAIN_STATE
  AC Source: 220V    Last voltage: 202 V
  Power: 1400W       12V bulk domain on: YES
Fault Analysis:
  rsp_status: 0x80 poll_data3: 0x00 poll_data4: 0x80
  Communication fault: NO
  Over voltage fault: NO
  Under voltage fault: NO
  Over current fault: NO
  Temperature fault: NO
  Current share fault: NO
  12V Vaux fault: NO
  Voltage source fault: NO
  AC Loss fault: NO
  Pgood to domain fault: NO
  Unknown or Other fault: NO

-------------------------------------------------------------
Entry 2, total entries: 4
-------------------------------------------------------------
Power supply status dump: (pnnum=1)
  Presence: PRESENT  Node state: POWER_NODE_DOMAIN_STATE
  AC Source: 220V    Last voltage: 203 V
  Power: 1400W       12V bulk domain on: YES
Fault Analysis:
  rsp_status: 0x80 poll_data3: 0x00 poll_data4: 0x80
  Communication fault: NO
  Over voltage fault: NO
  Under voltage fault: NO
  Over current fault: NO
  Temperature fault: NO
  Current share fault: NO
  12V Vaux fault: NO
  Voltage source fault: NO
  AC Loss fault: NO
  Pgood to domain fault: NO
  Unknown or Other fault: NO

And include "powr lsp" comm cmd/rsp tracing/display.
$ powr lsp
--> Start LSP Trace... (echo "0000d0004022000400000002" | spif -)
  rack/unit: 0000 / D0  (CEC)
    command: 22 "DCC - Diagnostic Control" (command)
      modif: 0040 "Start Network/LSP/Fan Trace
                   (Network:/tmp/debug_net_trace.log, LSP:/tmp/debug_iop_file.log, Fan:/tmp/debug_fan_file.log)"
data length: 4 (0x0004)
       data:
    0000  00000002                              "...."             "...."
<--
  rack/unit: 0000 / D0  (CEC)
    command: 22 "DCC - Diagnostic Control" (response)
     status: 0001 "Successful"
data length: 0 (0x0000)
Tailing /tmp/debug_iop_file.log... (use "powr lsp off" to stop trace)
time:0x1605, POLL: pnnum 00 device /dev/iic/1 addr d0
time:0x1605, read at reg 0x79 0000 (This STATUS_WORD command returns the unit's faults if any.)
             The unit is providing power to the output.
time:0x1605, read at reg 0x80 00 (This STATUS_MFR_SPECIFIC command returns some manufacturer defined faults and warn   ings if any.)
time:0x1605, read at reg 0x88 28f3 (This READ_VIN command reads the input power voltage in volts.)
             The input voltage is 202 volts.
time:0x1605, read at reg 0x7e 00 (This STATUS_CML command returns communications, logic and memory fault if any.)
time:0x1605, READ TRENDING ENTRY: pnnum 00 device /dev/iic/1 addr d0
time:0x1605, read at reg 0xd6 64ef6ff2 82f2 (This INPUT_HISTORY command returns the previous 10 minutes of input pow   er data.)
             The byte count is 100.
             The packet sequence number is 239.
             The power-input average is 155 W.
             The power-input maximum is 160 W.
time:0x1605, READ_P_IN: pnnum 00 device /dev/iic/1 addr d0
time:0x1605, read at reg 0x97 6ff2 (This READ_P_IN command reads a 30sec average of input power in watts.)
             The input power is 155 W.

time:0x1605, POLL: pnnum 01 device /dev/iic/2 addr d0
time:0x1605, read at reg 0x79 0000 (This STATUS_WORD command returns the unit's faults if any.)
             The unit is providing power to the output.
time:0x1605, read at reg 0x80 00 (This STATUS_MFR_SPECIFIC command returns some manufacturer defined faults and warn   ings if any.)
time:0x1605, read at reg 0x88 2cf3 (This READ_VIN command reads the input power voltage in volts.)
             The input voltage is 203 volts.
time:0x1605, read at reg 0x7e 00 (This STATUS_CML command returns communications, logic and memory fault if any.)
time:0x1605, READ TRENDING ENTRY: pnnum 01 device /dev/iic/2 addr d0
time:0x1605, read at reg 0xd6 64dc6bf2 85f2 (This INPUT_HISTORY command returns the previous 10 minutes of input pow   er data.)
             The byte count is 100.
             The packet sequence number is 220.
             The power-input average is 154 W.
             The power-input maximum is 161 W.
time:0x1605, READ_P_IN: pnnum 01 device /dev/iic/2 addr d0
time:0x1605, read at reg 0x97 6bf2 (This READ_P_IN command reads a 30sec average of input power in watts.)
             The input power is 154 W.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
