### ISSUE TITLE
Primary Navigation: Tab Order

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#586]
## Accessibility Issue
*Elements should not have a tabindex greater than zero*

## As Is
1. A keyboard user loses the focus state when navigating past the last primary navigation menu item due to the tabindex set on each navigational item. This forces the user to have to tab a significant number of times to get to the main content of the page.
1. A keyboard user, when expanding a menu, has to tab through the any items with a lower tab index before reaching the navigational item in the expanded menu

## To Be
The focus state will not be hidden and will follow a natural tabbing order. Navigating past the last focusable menu item will set the focus on the first tabbable/focusable item in the main content.

## Solution
1. Remove the tabindex attributes to allow for the natural tab order.
1. Add logic to set tabindex="-1" when menus are closed and tabindex="0" when menus are opened. 
1. Restructure markup to support nested lists and a natural tab order
1. Resolve animation issues created by the updated markup structure

**Comment by derick-montague** [comment]
## Accessibility Issue
*Elements should not have a tabindex greater than zero*

## As Is
1. A keyboard user loses the focus state when navigating past the last primary navigation menu item due to the tabindex set on each navigational item. This forces the user to have to tab a significant number of times to get to the main content of the page.
1. A keyboard user, when expanding a menu, has to tab through the any items with a lower tab index before reaching the navigational item in the expanded menu

## To Be
The focus state will not be hidden and will follow a natural tabbing order. Navigating past the last focusable menu item will set the focus on the first tabbable/focusable item in the main content.

## Solution
1. Remove the tabindex attributes to allow for the natural tab order.
1. Add logic to set tabindex="-1" when menus are closed and tabindex="0" when menus are opened. 
1. Restructure markup to support nested lists and a natural tab order
1. Resolve animation issues created by the updated markup structure

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
