### ISSUE TITLE
A11Y: Skip Navigation Link

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#587]
## Use Case
As a keyboard user, I would like to be able to efficiently navigation to the primary page content without having to tab through all of the navigation items.

## Implementation
1. Add a `visibly` hidden anchor link to the main content section
1. The link should be the first element in the body
1. When the page loads and the user hits the tab key and the link gains focus, it should be come visible

## References
* https://webaim.org/techniques/skipnav/

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
