### ISSUE TITLE
Sensors: Power Redundancy

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#589]
## Expected Delivery Dates
- [ ] UX: xx/xx/xx
- [ ] Backend: xx/xx/xx
- [ ] FED: xx/xx/xx

## Stakeholders
**SME**:
**Design Researcher**:
**UX Designer**:
**FED**:

## Use Case
---

## InVision Prototype
---

## Design Issue (phosphor-webui)
---

## Development Issue 
---

## References/Resources
---

**Comment by derick-montague** [comment]
We have a command line function that user's can utilize until the GUI is in place.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@derick-montague I thought we decided we didn't need the GUI for this?

**Comment by derick-montague** [comment]
I thought we decided to add this just to verify because we weren't sure. If we don't need it, we can close it.

**Comment by gtmills** [comment]
See https://github.com/ibm-openbmc/dev/issues/405
