### ISSUE TITLE
Remote logging via rsyslog

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#59]
Implement ability to forward BMC journal logs to a remote rsyslog server. BMC will have to run an rsyslog client. Filtering capabilities are already provided by rsyslog (can be applied at the client or server).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
This has been implemented via rsyslog.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Work is complete.  Closing.
