### ISSUE TITLE
GUI: TPM - Enable / Disable 

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#590]
## Stakeholders
**SME**: Chris Engle, Nick Bofferding
**Design Researcher**: @nicoleconser  
**UX Designer**: @jandraa 
**FED**:

## Use Case
As a user I need a way to enable the 'TPM required policy' so that my system does not run if the TPM is faulty. I need a way to disable the policy so that my system does run regardless of if the TPM is functional or not.

Our proposal is to place this functionality in the Server Power Operations panel given that the required policy will really only matter and take effect during reboot/power on. Additionally, this is where users would be configuring 'how' the boot occurs.

## InVision Prototype
https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319150964_3-7-1A_Boot_Options_Empty (Navigate by clicking on any flashing blue rectangles or using the keyboard arrows).

Since the interaction is a simple on/off, we added the component in the 'on' state to the boot options flow. To navigate the prototype, click on flashing blue rectangles or use the right and left keyboard arrows.

## Design Issue (phosphor-webui)
https://github.com/openbmc/phosphor-webui/issues/90

## Development Issue 
---

## References/Resources
---

**Comment by jandraa** [comment]
This story refers to the TPM policy, correct?

**Comment by derick-montague** [comment]
@jandraa - are you doing research and discovery on this as part of #403?

**Comment by jandraa** [comment]
> @jandraa - are you doing research and discovery on this as part of #403?

Yes, definitely! 
I am looking at all of TPM (the sensor for the FRU, enable/disable for the policy, and virtual TPM configurations). I am doing it this way to understand the wider use case and be able to get a better idea of where these things should live and in proximity to what. 

So far, I have not created any designs yet. Maybe at that point it would make sense for them to be separate issues, especially if this ends up in a different panel than the sensor, for example.

**Comment by derick-montague** [comment]
> Maybe at that point it would make sense for them to be separate issues, especially if this ends up in a different panel than the sensor, for example.

@gtmills and I discussed that today. That seems odd, but maybe with more discovery it makes sense. I will add this as a dependency.

**Comment by jandraa** [comment]
Different issues seems odd or different panels?

**Comment by derick-montague** [comment]
That TPM is on its own panel, but I could be wrong.

**Comment by jandraa** [comment]
My thinking, as of now, is that the actual TPM sensor would be on the Hardware Status with the other FRUs, and the policy would be with security stuff (I'm still figuring out what all 'security stuff' would entail).

**Comment by gtmills** [comment]
@derick-montague Why the blocked by the https://github.com/ibm-openbmc/dev/issues/403  ?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jandraa** [comment]
Should be placed with the Server Power operations (power on, orderly shutdown, reboot, etc.)?

The logic is the required policy will really only matter and take effect during reboot/power on. Additionally, this is where users would be configuring 'how' the boot occurs.

Chris and Nick agree.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/23928

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/23928 merged
