### ISSUE TITLE
Investigation: GUARD Requirements and Design

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#591]
IBM Powers  system provides feature to  guard the system from hardware failures  called GARD.
This issue used to capture the requirements  and High level design related to this feature.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Epic #659  created based on this investigation.
