### ISSUE TITLE
Openbmctool : Certificate interface updates.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#593]
- [ ] Replace existing REST certificate uploads/replace commands with Redfish

- [ ] Remove Certificate delete interfaces.

- [ ] Add CSR interfaces support

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by devenrao** [comment]
openbmc-tool changes to certificate are merged and can be closed
