### ISSUE TITLE
BMC CEC( POWER based)  Managment

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#594]
This Epic created to track all  POWER processor based central electronics complex (CEC) management work.  Most of the requirements are from hostboot/SBE and HBRT.

The hostboot firmware performs all processor, bus, and memory initialization within IBM® POWER® based systems. It initializes the central electronics complex (CEC) of the IBM POWER processor and the memory subsystem. It prepares the hardware to load and run an appropriate payload and provides runtime services to the payload.

Refer https://github.com/open-power/docs/blob/master/hostboot/HostBoot_PG.md for details on POWER based Hostboot firmware.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
