### ISSUE TITLE
Call NewLogAvailable PLDM command

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#596]
Called when a new error log is available.  Take into consideration the fact that the host might not be up, or its repository is full.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/28079/
