### ISSUE TITLE
Implement GetErrorLogByID PLDM command backend

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#597]
This is how PHYP gets a PEL.

Note we'll need to track that we already sent it up this power cycle, and if it doesn't get OS acked we'll need to send it again next power cycle.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/28080/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/28080 merged
