### ISSUE TITLE
Redfish(LDAP): Make changes in the get user info as per the new design

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#599]
Now with the new design role mapping is inside the config object, Earlier there was standalone mapper service.

With the new changes proposing the following changes
1) Look for the active ldap config profile.
2) find out the group-priv mapping under the active config for the given user name.
Return the privilege.

**Comment by raviteja-b** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-user-manager/+/21219

**Comment by raviteja-b** [comment]
Resolved by : https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-user-manager/+/21219

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-user-manager/+/21219 merged
