### ISSUE TITLE
Design and implement OpenBMC REST API to upload LDAP server information

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#6]
Design an OpenBMC REST API (to be implemented in phosphor-rest-server) to let a user inform the BMC about an external LDAP server configuration.

The API should just consume an ldap.conf and copy to relevant location. Not sure at the moment if we need to do any validation and/or restart any services.

**Comment by dkodihal** [comment]
From @ratagupt 

=> We can have the following D-Bus properties defined in the D-Bus interface which would be required to configure the LDAP Client.
[] SecureLDAP could be boolean true ==> ssl enabled, false ===> not secure
[] LDAPServerURI :- server address in uri format
[] LDAPBindDN:- The distinguished name to bind to the server with.
[] LDAPBaseDN:- The distinguished name of the search base.
[] LDAPBINDDNpassword:-Bind password.
[] LDAPBaseSearch:- Where the search should start in the LDAP tree.
[] LDAPSearchScope:- could be one level or till the leaf of the tree etc(sub|one|base)

=> Write a small D-Bus service which would be creating the backend ldap conf file from redaing configuration object.
=> Persist the D-Bus configuration,seems to me the easiest way to persist the D-Bus object and create the conf file.

**Comment by dkodihal** [comment]
- [ ] Need unit tests
- [ ] Add exception handling
- [ ] Need D-Bus persistency

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Seems we can close this issue now.It has already done.Now we are moving to redfish.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Seems we are done with it, we can close this.
