### ISSUE TITLE
Openbmctool(LDAP): Changes required to address the interface change.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#600]
=> Make sure we can configure the group-priv mapping which is under each config object.
=> Make sure we should be able to create the ldap config.

**Comment by trajeswaran** [comment]
Resolved by : https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/21288

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Also Resolved by : https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/23664/4

**Comment by trajeswaran** [comment]
Raviteja made the changes to support OP930 as well. After that, his changes were merged to my changes to support interface changes in LDAP for OP940. The resultant code changes are in https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/23664.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/23664 merged
