### ISSUE TITLE
Swift: PFP: Initial fan-presence yaml file

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#601]
They're currently empty, need to populate them:
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/21130

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/22674

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/22674 merged
