### ISSUE TITLE
HMC-BMC: Interface for HMC session Management

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#602]
As part of this story we need to come up with design doc which tells that how BMC can identify that the connected client is HMC.
We need to come up with the sequence diagram that how HMC would be talking to various resources(session,manager).
Any OEM specific extension if needed.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Need to handle two things here
1) How HMC would discover the BMC?
2) How HMC would create the session
      Do we need Rest Session?
      Do we need redfish session?
      Connection drop scenario

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
As part of this story we have created the internal design doc and shared with HMC team which covers the all above connection creation/.termination scenario.
How HMC can use the same session for REST and Redfish.
No need to do the session management for both interfaces.
This doc covers the details of each command and its output, sequence diagram etc.
