### ISSUE TITLE
Flash Layout

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#603]
Support to run OpenBMC on a emmc NAND chip, including u-boot and kernel work. Determine filesystem to be used.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
https://gerrit.openbmc-project.xyz/q/topic:ext4-image

**Comment by anoo1** [comment]
https://gerrit.openbmc-project.xyz/q/topic:mmc
