### ISSUE TITLE
Build a combined image BMC+PNOR

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#604]
Bitbake changes to import the host firmware image files(s) alongside the BMC firmware to create a single file.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-openpower/+/25155
