### ISSUE TITLE
Build changes to break the BMC image into 16MB files

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#605]
IBM's OSs require by legacy for the firmware file(s) to be 16MB in size. In addition a 'master table of contents' is needed to know what each file is and if it's part of a bigger file overall.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
This work is now complete.  Closing.
