### ISSUE TITLE
PLDM commands for code update

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#606]
As part of PLDM, need certain commands to be supported for code update, such as "Read firmware file", "Code update has started", "Code update has ended", "BMC is rebooting", etc.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
Being tracked with the PLDM epic.
