### ISSUE TITLE
Create Custom I/O PLDM handler

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#607]
This handler would process the 16MB files that make up the firmware image and call existing D-Bus interfaces to perform the update.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
Being tracked with the PLDM epic.
