### ISSUE TITLE
rsyslog: provision API

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#61]
Implement REST/D-Bus API to let a user specify to the BMC a target rsyslog server.

- [ ] Write app in phosphor-logging to implement https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Network/Client.interface.yaml
- [ ] Upon receiving both the rsyslog server's IP address and port, update rsyslog.conf and restart rsyslog service.

This story assumes TCP will be used for streaming the logs. If UDP support is required as well, another story will be opened.

**Comment by rfrandse** [comment]
Done
