### ISSUE TITLE
Inband Update for i5OS / AIX

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#610]
Epic to add support for inband update for systems running IBM's OSs such as i5 and AIX.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Should we convert this story to an Epic. I see it has the label, but it's not an Epic.

**Comment by anoo1** [comment]
> Should we convert this story to an Epic. I see it has the label, but it's not an Epic.

How do you convert it? Don't see a button that says "Convert to Epic". Maybe @rfrandse would know.

**Comment by derick-montague** [comment]
In zenhub its an option in the menu for associating with an Epic. Its an odd interface. I can do it.

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Bringup in progress.

**Comment by anoo1** [comment]
Stories tracking the PLDM changes: https://github.com/ibm-openbmc/dev/issues/1983

The PLDM changes have been merged: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/37437/31

Only remaining task is support the reboot after the update.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
End-to-end verification requires Hostboot to transition to reading LIDs. This is being tracked with: #907

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
No more changes expected from BMC to support inband update. Any fixes will be tracked via issues. Closing epic.
