### ISSUE TITLE
GUI: Research: SNMP Alerts - Trap only

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#613]
## Expected Delivery Dates
- [ ] UX: xx/xx/xx
- [ ] Backend: xx/xx/xx
- [ ] FED: xx/xx/xx

## Stakeholders
**SME**: @ratagupt 
**Design Researcher**: @nicoleconser 
**UX Designer**:
**FED**:

## Use Case
---

## Context
---
- SNMP trap configuration is required. We plan to have back-end support and this should be on the GUI. Note that this is not full SNMP support - just the trap.  It would be good to get (customer?) feedback on this. (email from Todd R on **August 5, 2020**) 
- Need to confirm w/ customers that full SNMP Alerts function (filtering, etc) is not needed in the first release

## Design Issue (phosphor-webui)
---

## Development Issue 
---

## References/Resources
---

**Comment by derick-montague** [comment]
The SNMP page will need filtering and some additional features added. Additional featured to be determined through design discovery. This is called SNMP full function on @mzipse's roadmap.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by nicoleconser** [comment]
Tagging you here @ParishrutB as this seems to be part of the work you were doing already - correct? 

also FYI @derick-montague

**Comment by derick-montague** [comment]
Yes, this would be part of the alerts story, but I thought Redfish alerts has been de-prioritized and we are going to try to determine the importance to users. We still need SNMP, which there is a FED story for, #1223.

**Comment by nicoleconser** [comment]
> Yes, this would be part of the alerts epic #2173, but I thought Redfish alerts has been de-prioritized and we are going to try to determine the importance to users. We still need SNMP, which there is a FED story for, #1223.

Yep agreed - my takeaway from today is that we need to validate the value of having Redfish Alerts (#1288) in the GUI with our customers, specifically our smaller customers. In other words, we need to validate Todd's assumption that Redfish Alerts are **not** useful in the GUI. 

Since #1288 has been de-prioritized, are you suggesting we press pause on it altogether, and validate Todd's assumption with customers at a later date? Or should we validate his assumption now?

**Comment by nicoleconser** [comment]
Re: your comment `We still need SNMP, which there is a FED story for, #1223` — is there any research / design work that is needed for that, or is it purely FED? Asking because I thought SNMP was part of what Pari was working on with #1288.

**Comment by derick-montague** [comment]
> Re: your comment We still need SNMP, which there is a FED story for, #1223 — is there any research / design work that is needed for that, or is it purely FED? Asking because I thought SNMP was part of what Pari was working on with #1288.

We will just code it like the existing page and place it in the same place within the IA to reach parity. It was part of Pari's work because we were trying to see if we could create those alerts into one experience rather than separate them into their own. 

> Since #1288 has been de-prioritized, are you suggesting we press pause on it altogether, and validate Todd's assumption with customers at a later date? Or should we validate his assumption now?

I think we need to get some initial feedback sooner than later if we want to make sure it is not just a late add-on to the engineering team's workload. :)

**Comment by nicoleconser** [comment]
`I think we need to get some initial feedback sooner than later if we want to make sure it is not just a late add-on to the engineering team's workload. :)`

Agreed, especially if we think it makes sense to include SNMP onto this page, right? I'll add this to my to-do list.

**Comment by derick-montague** [comment]
Closing. Work will be done as part of #1288.
