### ISSUE TITLE
GUI : Research : Audit Logs

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#614]
## SME
**BMC**:
**RAS**:
**PHYP**:

## Summary
```
/redfish/v1/Managers/bmc/LogServices/Audit/
```
### Background
- [ ] TBD

### End users
- [ ]  TBD

### User Needs
- [ ] TBD

### User Quotes
- [ ] TBD

## User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

## References
- [ ] eBMC Feature Item <add number>
- [ ] Link to Discovery folder

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Closing -> Migrating to one Systems Log story #2626
