### ISSUE TITLE
GUI: FED: eBMC Redfish Logs

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#616]
## Stakeholders
**SME BMC**: @gtmills 
**SME RAS**: Justin Thaler
**Design Researcher**:
**UX Designer**:
**FED**:

### As Is
There are two logs pages. One created by Intel that uses Redfish. One that IBM created that uses a REST API. The IBM event log page allows users to resolve and un-resolve issues. These actions are not supported by the Redfish standard.

### ToBe
1. Work with Redfish to update the standard to support more error log functionality
1. Work with Intel and Community to consolidate the two event log pages.

## References/Resources
- [eBMC Feature Item: 2.5.2](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)

**Comment by derick-montague** [comment]
We will be moving the events logs from the REST API to Redfish. We need to determine the logs as well as functionality that matches community and IBM needs.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
This is being completed in #1211 
Intel can use the Event Logs page with the new design once Redfish has been implemented.
