### ISSUE TITLE
Local User Management

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#618]
## Expected Delivery Dates
- [ ] UX: xx/xx/xx
- [ ] Backend: xx/xx/xx
- [ ] FED: xx/xx/xx

## Stakeholders
**SME**:
**Design Researcher**:
**UX Designer**:
**FED**:

## Use Case
As a user, I would like to be able to easily view, edit, and delete user information.

## Description
- [ ] Incorporate customer feedback into user management page

## InVision Prototype
---

## Design Issue (phosphor-webui)
---

## Development Issue 
---

## References/Resources
---

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@jandraa - I think this is the same as #185. Do you agree?

**Comment by derick-montague** [comment]
Duplicate of #185 - Closing
