### ISSUE TITLE
Kernel MCTP Support

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#620]
MCTP's purpose is to provide a bus-agnostic on-platform packet-based network for communication between managed and management devices. The base specification defines packetisation, addressing and routing of messages through an MCTP network, and delegates to bindings documentations to describe how these features map on to different physical bus types.

To avoid polluting the kernel's userspace interface with miscellaneous APIs related to MCTP bindings, we're proposing a unified, socket-based interface coupled with netlink MCTP network management functions to allow implementation of MCTP bindings to exist in the kernel itself.

This issue tracks the work required to implement the socket-based kernel MCTP concept.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
