### ISSUE TITLE
Kernel MCTP: Basic AF_MCTP support

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#621]
Implement the new address-family backend and expose the necessary definitions to userspace for interacting with `AF_MCTP` sockets. We should be able to successfully call e.g. `socket(AF_MCTP, SOCK_RAW, 0)` without error.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
