### ISSUE TITLE
Kernel MCTP: Add interface kernel object and in-kernel mock MCTP binding

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#622]
The mock MCTP binding should be used to flesh out the implementation of the interface object, where an interface is the object that is composed of a binding implementation an appropriate kernel device for that binding. The mock binding should have the capability to add mock devices that we can talk to from userspace.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
