### ISSUE TITLE
Kernel MCTP: Implement `mctp` tool and `mctp interface` subcommands

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#624]
The `mctp` tool is the MCTP equivalent of the `ip` tool for IP-based networks - a user-oriented tool for defining and exploring MCTP networks on a machine. `mctp` will primarily drive a netlink-based kernel interface, though will also have the ability to talk the MCTP control protocol in order to perform functions like device address allocation.

The first order of operation for the tool is to enable binding interfaces to devices from userspace. We should be able to bind and unbind the mock interface successfully.

Required subcommands:

* `mctp interface bind INTERFACE DEVICE upstream|downstream`
* `mctp interface unbind INTERFACE`
* `mctp interface list`

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
