### ISSUE TITLE
Kernel MCTP: Send and receive an MCTP packet from the mocks

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#627]
Add a mock MCTP device to a mock interface, and use `SO_BINDTODEVICE` in userspace to send packets directly via the mock interface to the device. This will need injection of the EID-to-physical mapping via the `mctp` tool against the interface via `mctp endpoint offer` as userspace will only deal with EIDs in `struct sockaddr_mctp` for `AF_MCTP` sockets.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
