### ISSUE TITLE
Kernel MCTP: Add primary `mctp endpoint` subcommands

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#628]
The primary `mctp endpoint` subcommands are:

* `mctp endpoint offer INTERFACE DEVICE EID`
* `mctp endpoint reclaim NETWORK|ALIAS EID`
* `mctp endpoint list NETWORK|ALIAS`

The MCTP base specification defines to classes of EIDs: static and dynamic. The base specification spends much time describing dynamic EID assignment, and leaves the mechanics around static EID assignment largely to the implementation of both devices and top-level bus masters.

The kernel MCTP implementation therefore relies on userspace to describe the static topology via the netlink interface as part of the network initialisation process, before addresses are actively allocated to devices via the `Set Endpoint ID` command. This enables the `AF_MCTP` interface to only deal with EIDs, while the gory binding-specific details are dealt with via the out-of-band netlink management interface.

The first phase of static address assignment is captured by `mctp endpoint offer INTERFACE DEVICE EID`. This sets up the EID-to-physical mapping in the interface object, eventually allowing address allocation to complete via the `Set Endpoint ID`, triggered by e.g. an `mctp endpoint allocate static` command (not yet described) once description of the static network toplogy has been completed.

`mctp endpoint reclaim NETWORK|ALIAS EID` simply adds the given EID back to the dynamic EID pool for the given network.

`mctp endpoint list NETWORK|ALIAS` lists all endpoints participating in the network and with their associated routing EID.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
