### ISSUE TITLE
Kernel MCTP: Add netlink API for EID management

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#629]
The subcommands of `mctp endpoint` need a way to talk to the kernel. Add appropriate netlink commands to add and remove EID mappings as required. The shape of this interface will be influenced primarily by #628 and the needs of the interface and network kernel objects.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
