### ISSUE TITLE
Implement Remote Virtual Media Support

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#63]
<a href="https://github.com/anoo1"><img src="https://avatars0.githubusercontent.com/u/9052527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anoo1](https://github.com/anoo1)**
_Monday May 09, 2016 at 17:29 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/261_

----

This is a work in progress.

**Comment by rfrandse** [comment]
<a href="https://github.com/amboar"><img src="https://avatars0.githubusercontent.com/u/526481?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amboar](https://github.com/amboar)**
_Tuesday May 10, 2016 at 00:10 GMT_

----

@anoo1 can you provide more detail here? What media are we exposing? What's the motivation behind the work? Also, it sounds like someone's taken up the task and I think it would be useful to set the Assignee field so we know who's doing what.

**Comment by rfrandse** [comment]
<a href="https://github.com/anoo1"><img src="https://avatars0.githubusercontent.com/u/9052527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anoo1](https://github.com/anoo1)**
_Tuesday May 10, 2016 at 20:55 GMT_

----

@mdmillerii  has being working on this item, he would be able to provide more details.
Don't have permissions to set the Assignee, will ask Patrick to assign.

**Comment by rfrandse** [comment]
<a href="https://github.com/mdmillerii"><img src="https://avatars0.githubusercontent.com/u/16150300?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mdmillerii](https://github.com/mdmillerii)**
_Thursday Jun 30, 2016 at 18:39 GMT_

----

The plan for this item is to support remote media by presenting a virtual CD drive over the USB2.0 vhub as a usb gadget device.

**Comment by rfrandse** [comment]
<a href="https://github.com/mdmillerii"><img src="https://avatars0.githubusercontent.com/u/16150300?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mdmillerii](https://github.com/mdmillerii)**
_Thursday Jun 30, 2016 at 18:41 GMT_

----

Current status is I have tried a minimal forward port of the code in facebook/openbmc but writes to the reset register in the vhub were not taking effect.  I had the minimum 10us delay for clock start but did not verify strapping registers or pin muxes for usb clock and 24 or 48MHz refclock.

**Comment by rfrandse** [comment]
<a href="https://github.com/spinler"><img src="https://avatars1.githubusercontent.com/u/9370114?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [spinler](https://github.com/spinler)**
_Monday Jul 30, 2018 at 14:25 GMT_

----

A design proposal is at https://lists.ozlabs.org/pipermail/openbmc/2018-July/012647.html

We still need to break it into stories.

**Comment by rfrandse** [comment]
test

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
@anoo1 This is done! Can we close this?

**Comment by anoo1** [comment]
Yeah, done! Closing.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
