### ISSUE TITLE
Kernel MCTP: Add SOCK_DGRAM for AF_MCTP to expose MCTP messages

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#630]
`SOCK_DGRAM` support for `AF_MCTP` is the dual to #626 - with `SOCK_DGRAM` we expose the fully assembled MCTP message data composed from packets belonging to the same `{ Msg Tag, TO, Source Endpoint ID }` set. The message data is the concatenated message bodies from the packet set, _including_ the `Message type`, `IC` and `Msg integrity check` fields. This is necessary as the `Msg integrity check` field size and associated algorithm are defined by the message type. We do not want to process this in the kernel as the kernel must therefore, a-priori, know the definition of all current and future MCTP message types.

Resolution of the issue requires implementation of all the message assembly semantics defined by sections 8.5 to 8.9 inclusive in DSP0236 v1.3.0.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
