### ISSUE TITLE
Kernel MCTP: Add network kernel object

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#631]
The network object maps a network UUID to an interface or bridge associated with the network. The associated bridge object fulfils the task of packet forwarding by holding the mapping of EIDs to interfaces. The interface's EID-to-physical mapping then takes care of addressing the correct device for the packet. The `AF_MCTP` implementation maps the network ID embedded in `struct sockaddr_mctp` to the associated network object, which passes messages between its associated sockets and the attached interface or bridge.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
