### ISSUE TITLE
Kernel MCTP: Add `mctp network` subcommands

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#633]
The primary network subcommands are:

* `mctp network create NETWORK`
* `mctp network alias NETWORK ALIAS`
* `mctp network destroy NETWORK|ALIAS`
* `mctp network list`

Each uses the netlink kernel API implemented in #632 to list and manipulate the network kernel objects.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
