### ISSUE TITLE
Kernel MCTP: Add `mctp network` endpoint subcommands

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#635]
The remaining two `mctp network` subcommands attach interfaces (#622) and bridges (#640) to a network (#631) created by the commands in #633:

* `mctp network add NETWORK|ALIAS BRIDGE|INTERFACE`
* `mctp network delete NETWORK|ALIAS BRIDGE|INTERFACE`

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
