### ISSUE TITLE
Kernel MCTP: Add static-EID `mctp endpoint` subcommands

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#636]
MCTP endpoint allocation involves sending a `Set Endpoint ID` command to the relevant devices. This has two outcomes for the bus master. It learns whether:

* The device accepts the EID it was offered
* The device requires a dynamic EID pool be allocated to it

Concentrating on the static EIDs for the moment, we require several relevant `mctp endpoint` subcommands:

1. `mctp endpoint allocate NETWORK|ALIAS EID`
2. `mctp endpoint allocate static NETWORK|ALIAS`
3. `mctp endpoint allocate BRIDGE|INTERFACE EID`
4. `mctp endpoint allocate INTERFACE DEVICE EID`

The first command is the counterpart to `mctp endpoint offer` discussed in #628 - using the information provided by `mctp endpoint offer` invocations `mctp endpoint allocate EID` issues the `Set Endpoint ID` to the device previously associated with the EID.

The second command iterates each of the devices in the `offered` state issuing `Set Endpoint ID` to each.

The third command allows assignment of EID to local objects. This may be unnecessary with expansion of `mctp endpoint offer` to cover bridge and interface names.

The fourth command coalesces calls to both `mctp endpoint offer` and `mctp endpoint allocate NETWORK|ALIAS EID` into one command simply for convenience.

In general we need to consider how we might track any dynamic EID pool requirements for each command. This may be a simple as writing the mapping between EID and its pool size requirement to stdout for consumption by later `mctp` invocations.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
