### ISSUE TITLE
Kernel MCTP: Send and receive an MCTP message from a network of mocks

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#637]
Use the functionality developed so far (see issues listed in #620) to do as the title suggests. This can be done under QEMU. Expect a bunch of integration effort to be needed here, as we've spent our time so far building each of the required pieces.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
