### ISSUE TITLE
Kernel MCTP: Implement the DSP0253 serial binding

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#638]
Implement the [DMTF DSP0253 serial binding (PDF)](https://www.dmtf.org/sites/default/files/standards/documents/DSP0253_1.0.0.pdf). Test the result under QEMU by plumbing out the serial device to the host, and sending messages between the host and the guest.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
