### ISSUE TITLE
Kernel MCTP: Implement the OpenPOWER KCS/LPC binding

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#639]
The OpenPOWER KCS/LPC binding allocates regions of the LPC FW address space as Rx/Tx buffers between the host and the BMC, and uses a KCS IPMI channel to manage protocol initialisation and buffer ownership over the MCTP channel's lifetime.

This effort requires some rework of the existing aspeed-lpc-ctrl driver as it now has multiple clients for its reserved memory region (used now by [hiomapd](https://github.com/openbmc/hiomapd) _and_ the kernel's MCTP subsystem).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
