### ISSUE TITLE
Kernel MCTP: Add the bridge kernel object

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#640]
Bridge objects enable in-kernel routing of MCTP packets and the ability to attach multiple interfaces to a network. As part of this, a bridge may itself hold an EID representing all of its subservient interfaces. Bridges hold the EID-to-interface map that enables packet routing to remain in the kernel, and also correct selection of interfaces on which to route messages originating from userspace. A bridge may only be attached to one network.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
