### ISSUE TITLE
Kernel MCTP: Add `mctp bridge` subcommands

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#642]
Implement the following `mctp bridge` subcommands:

* `mctp bridge create BRIDGE`
* `mctp bridge add BRIDGE INTERFACE [INTERFACE...]`
* `mctp bridge delete BRIDGE INTERFACE [INTERFACE...]`
* `mctp bridge destroy BRIDGE`
* `mctp bridge list`

This uses the netlink interface described in #641 to manipulate bridge objects described in #640.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
