### ISSUE TITLE
Kernel MCTP: Add `mctp route` subcommands

### ISSUE THREAD

**Issue by amboar** [ibm-openbmc/dev#644]
The `mctp route` subcommand sets up the EID-to-interface mappings that allow devices on remote bus segments to communicate through the BMC. This enables handling of packet routing for the full generality of bus topologies in the kernel. The following commands are required:

* `mctp route add NETWORK|ALIAS DESTINATION-EID via LOCAL-EID`
* `mctp route delete NETWORK|ALIAS DESTINATION-EID via LOCAL-EID`
* `mctp route list NETWORK|ALIAS`

The first two form include `via LOCAL-EID` - this is necessary as MCTP bridges may choose to allocate EIDs to all, some or none of their participating interfaces (see Section 9.1.2 EID options for MCTP bridges, Figure 9 - EID options for MCTP bridges in DSP0236 v1.3.0).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
