### ISSUE TITLE
Change buttons to straight corners

### ISSUE THREAD

**Issue by jandraa** [ibm-openbmc/dev#647]
## Description
Change all buttons from rounded corners to straight corners. 

This will create more visual consistency between the components in the GUI since there are some, such as text fields, dropdowns, sections, etc. are all designed with straight corners. 

Buttons should include a 16px padding on both sides of the text. 

## Expected visual
<img width="421" alt="Screen Shot 2019-05-10 at 10 55 25 AM" src="https://user-images.githubusercontent.com/44675611/57540353-2a6e7b80-7312-11e9-8005-2af97f36a0cf.png">

## Actual visual
<img width="331" alt="Screen Shot 2019-05-10 at 10 55 12 AM" src="https://user-images.githubusercontent.com/44675611/57540346-24789a80-7312-11e9-9229-a38302b9a901.png">

**Comment by derick-montague** [comment]
@gtmills - For something this simple, do we need to vet through the community?

**Comment by gtmills** [comment]
@derick-montague We probably don't have to, but wouldn't hurt to send something to the mailing list (could do after we push the change), add a webui issue, or bring up in the GUI design workgroup meeting (and therefore gets into the meeting mins that go to the emailing list).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
