### ISSUE TITLE
Swift: Handle CAPI riser card presence

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#648]
This riser plugs into/around a PCI slot when used for CAPI cards, and has a presence GPIO to the BMC.  While we could just set up phosphor-gpio-presence to detect it, that app will still create the inventory item if it isn't present, and I'm not entirely sure we'll want to do that, as it is an optional item.

So either:
a) business as usual, an empty card is in the inventory with Present=False
b) modify phosphor-gpio-presence to only create the inventory item if it is present, and to remove it if it isn't (would need a PIM update for that).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
