### ISSUE TITLE
How to handle Altitude in userspace

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#649]
The issue https://github.com/ibm-openbmc/dev/issues/472 was used to update the DPS310 to put the pressure in sysfs.

We need to decide 
* What code converts the pressure to altitude, if it even actually needs to
* Do we need to put this on D-Bus?  Could maybe just have the fan code read pressure directly and convert to altitude itself.  My worry could be that making the altitude available to the user could be more trouble than it's worth since it's pressure dependent which can change based on the weather.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
A new application should be created to handle sensors, such as altitude, that are in the iio subsystem. This should result in a similar application to phosphor-hwmon.

For reference: https://wiki.analog.com/software/linux/docs/iio/iio

**Comment by amboar** [comment]
Can we make sure to investigate using libiio?

https://wiki.analog.com/resources/tools-software/linux-software/libiio

**Comment by vishwabmc** [comment]
@spinler @msbarth Could Fan application directly read the raw data and convert it to consumable way ?.. Will anyone else be interested in the altitude value ?.. Was this a feature in Enterprise box ?. I am asking if we need to feature map..

**Comment by msbarth** [comment]
@vishwabmc 
Yes, it's preferred to have this exposed onto dbus which is why its been marked `ReadyForDev`.
Yes, there has been discussion on the mailing list and the app create under this issue would be for any iio devices.
If you're referring to altitude, yes this existed. This issue is for creating an app to handle iio devices, not just altitude sensors.

**Comment by mine260309** [comment]
Currently, phoshpor-hwmon has support for IIO sensors, e.g. RTC battery sensor is from IIO and it is supported.

What exactly is the goal of this issue? Is it to investigate how altitude sensor data should be handled by the fan control, or just provide the information on D-Bus?

**Comment by msbarth** [comment]
@mine260309 The goal of this issue is to get the altitude sensor on dbus. Currently, my understanding is, IIO devices are using an IIO bridge to hwmon resulting in phosphor-hwmon being able to load those device's sensors onto dbus. The object of this issue would be to remove the need of the IIO bridge to hwmon and get these IIO devices onto dbus natively using some IIO userspace application (such as amboar suggested above with the use of `libiio`).

**Comment by mine260309** [comment]
Yeah, phosphor-hwmon has IIO support, what is missing is that there is no `altitude` sensor support.
The simplest way to get altitude sensor on DBus would be adding the support in phosphor-hwmon.

May I ask why do we want a separated application for that?

**Comment by msbarth** [comment]
@bradbishop There was a drive to get away from having the IIO bridge to hwmon, is that something we should still move towards or do is there a new strategic direction to eventually shift away from the use of `phosphor-hwmon` to `dbus-sensors` which affects how this issue should be handled? i.e.) Should we just get the altitude sensor support into `phosphor-hwmon` for now instead of creating a new IIO userspace application? or continue with having an IIO application that'd be used in parallel with `dbus-sensors`?

**Comment by derekhoward55** [comment]
Per discussion, need to write an iio app to at minimum get the altitude from the already-written DD and place in DBus so we can use it as needed in our fan control apps.  This should be done in the dbus-sensors repo (https://github.com/openbmc/dbus-sensors), and contained in the Sensor.Value interface.

**Comment by amboar** [comment]
The DPS310 provides pressure and temperature sensors but the issue calls for exposing altitude on D-Bus. What are we actually trying to achieve? Why do we want altitude? I would have thought air density would be what we care about for fans. Is altitude a proxy for density? If altitude is what we want for some reason, who can provide guidance on the approach we should take for estimating it from pressure and temperature in the application?

**Comment by derekhoward55** [comment]
We need altitude for at least 3 reasons.
1. We log an error is customer has system above the supported altitude.
2. Altitude is needed for the "Workload Optimized Frequency" design.
3. Thermal team bases fan floor on altitude as that is what the ASHREA standard defines.

The DPS310 spec / users guide should explain how to convert their pressure into altitude.

**Comment by mzipse** [comment]
Reassigning this work to @eddiejames .  Eddie, we haven't discussed this but we're likely going to need your help on this.  We'll discuss this soon.

**Comment by derekhoward55** [comment]
The new app should get the ambient temps from the dps310 and Si7021-A20 and place on dbus as well.
Ensure the sensors are in the dts and blyth.json EM config file.
Ensure dbus-sensors does the correct associations so bmcweb can map the URI's to dbus objects correctly.

**Comment by BMC-Bruce** [comment]
@rfrandse just merged this PR meta-ibm: Adds virtual Altitude sensor #1164 into 1020

To read the Altitude reading use:
    busctl introspect xyz.openbmc_project.VirtualSensor /xyz/openbmc_project/sensors/altitude/Altitude

To read the DPS310 Pressure sensor use:
    busctl introspect --no-pager xyz.openbmc_project.IIOSensor /xyz/openbmc_project/sensors/pressure/Station_Pressure

To read the DPS310 Temperature sensor use:
    busctl introspect --no-pager xyz.openbmc_project.IIOSensor /xyz/openbmc_project/sensors/temperature/Ambient_1_Temp

**Comment by BMC-Bruce** [comment]
Here is the model for the Altitude computation from Pressure that we are using:
`G_absAltitude = 44330 * ( 1 - pow((G_pressureInPascal / 101325.0), (1 / 5.255)));  // altitude in meters.`
 
 And in the virtual_sensor_config.json file it looks like this:
The Altitude measurement is from the computation of
the DPS310 pressure sensor with this
`"Expression": "44330.0 * (1.0 - ((P0/101325.0) ^ (1/5.255)))"`

**Comment by BMC-Bruce** [comment]
Rainier / Everest Si7021-A20 ambient on dbus pending on 2 PRs
entity-manager: Support for DPS310 and SI7020 Rainier #5
and
dbus-sensors: Adds support for DPS310 Sensors #5

**Comment by BMC-Bruce** [comment]
The Altitude Virtual Sensor is handle by the Gerrit Merged Review.
44526: meta-ibm: Adds virtual Altitude sensor
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/44526

**Comment by BMC-Bruce** [comment]
New PRs, old ones closed.

entity-manager
1020 dps310 and SI7020 #6
https://github.ibm.com/openbmc/entity-manager/pull/6

dbus-sensors: Support DPS310 and SI7020 #6
https://github.ibm.com/openbmc/dbus-sensors/pull/6

**Comment by BMC-Bruce** [comment]
To read Ambient Temperatures, Station Pressure, and Altitude

```
busctl introspect --no-pager xyz.openbmc_project.HwmonTempSensor /xyz/openbmc_project/sensors/temperature/Ambient_0_Temp
busctl introspect --no-pager xyz.openbmc_project.IIOSensor /xyz/openbmc_project/sensors/temperature/Ambient_1_Temp
busctl introspect --no-pager xyz.openbmc_project.IIOSensor /xyz/openbmc_project/sensors/temperature/Ambient_2_Temp
busctl introspect --no-pager xyz.openbmc_project.IIOSensor /xyz/openbmc_project/sensors/pressure/Station_Pressure

busctl introspect xyz.openbmc_project.VirtualSensor /xyz/openbmc_project/sensors/temperature/Ambient_Virtual_Temp
busctl introspect xyz.openbmc_project.VirtualSensor /xyz/openbmc_project/sensors/altitude/Altitude

```

**Comment by BMC-Bruce** [comment]
44290: entity-manager: Support for DPS310 and SI7020 Rainier
       https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44290
44670: entity-manager: Support DPS310 and SI7020 Everest
       https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/44670
43410: dbus-sensors: Support DPS310 and SI7020
       https://gerrit.openbmc-project.xyz/c/openbmc/dbus-sensors/+/43410

In reality 44290 is a prerequisite for 44670.
And Ed has In reality made 43410 a prerequisite for both 44290 and 44670.

**Comment by BMC-Bruce** [comment]
This PR [meta-ibm: Adds virtual Altitude sensor #1164](https://github.ibm.com/openbmc/openbmc/pull/1164)
and this upstream commit [44526: meta-ibm: Adds virtual Altitude sensor](https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/44526)

Implement the user space Altitude virtual sensor.
