### ISSUE TITLE
DevOps : QEMU

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#65]
<a href="https://github.com/rfrandse"><img src="https://avatars3.githubusercontent.com/u/15894767?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rfrandse](https://github.com/rfrandse)**
_Tuesday Mar 21, 2017 at 21:19 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/1365_

----

Someone to get the 200 docker QEMU sessions running
Someone to introduce new state changes to make it all work
August timeframe so we have time

**Comment by mzipse** [comment]
Please ignor this comment.  Just a test for reporting.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
