### ISSUE TITLE
GUI: Design: Event log page redesign based on redfish and user feedback

### ISSUE THREAD

**Issue by ryanarnell** [ibm-openbmc/dev#650]
The event log page needs to be redesigned to support new redfish api and also to be more user friendly. 
## Expected Delivery Dates
- [ ] UX: xx/xx/xx
- [ ] Backend: xx/xx/xx
- [ ] FED: xx/xx/xx

## Stakeholders
**SME**: @spinler, @dkodihal , Justin Thaler
**Design Researcher**: @nicoleconser 
**UX Designer**: @ryanarnell 
**FED**:

## Use Case
User needs a way to easily find (sort/search) event logs they need to be able to troubleshoot their systems/environment that might end up in a critical or warning state. Also be compatible with redfish api so that we do not have two separate log pages in the build serving almost the same purpose. 

## InVision Prototype
https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319141765_01-Event-Logs

## Design Issue (phosphor-webui)
---

## Development Issue 
---

## References/Resources
- feature discovery folder: https://ibm.box.com/s/r3xb3videph78cwpomxlca93ne5ttskg
- user research synthesis*: https://ibm.box.com/s/hmlinznmk8kq7nqmpy89pdogmosinsi7

*This folder is restricted in accordance with GDPR guidelines.

---

## Proposal:
Redesign the page to make more event logs visible. Reconsider the filtering and sorting methods to make the page more user friendly. Additional minor design changes and adding fields that might be useful to users. 

## InVision Prototype
https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319141765_01-Event-Logs

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ryanarnell** [comment]
https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319141765_01-Event-Logs 
Screens for research

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
