### ISSUE TITLE
Simplify libpldm encode/decode

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#653]
Current implementations of encode/decode require extensive pointer arithmetic and memcpys. Representing requests and response as structs can simplify this greatly (alignment comes for free from the struct, and mecmpys become simple assignments, for simple types at least).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Resolved by https://github.com/openbmc/pldm/commit/8b9766599f09b7dc5c2f1def8ff3218e95990b55
