### ISSUE TITLE
Sreset: SBE chip-op wrapper function support.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#655]
- [ ] SBE Chip-op wrapper function code support. Initial version of SBE chip-op wrapper code is already available for review. https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-sbe-interface/+/11401/, Need to address all outstanding review comments and upstream the code into master.

- [ ] Provide system level Interface wrapper function. This includes issuing chipops on all functional  processors  and basic error handling.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by lkammath** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/21770/ (Under review)
https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-proc-control/+/22193/ (Under review)
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-openpower/+/22502/ (Under review)
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/22661/ (Integrated)

We decided to use pdbg . So, NMI callback will invoke service file that executes pdbg sreset on all the available processors

**Comment by lkammath** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/21770/ (Integrated)
https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-proc-control/+/22193/ (Integrated)
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-openpower/+/22502/ (Need to rebase against the master and integrate)
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/22661/ (Integrated)

**Comment by lkammath** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-dbus-interfaces/+/21770/ (Integrated)
https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-proc-control/+/22193/ (Integrated)
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-openpower/+/22502/ (Integrated)
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/22661/ (Integrated)
