### ISSUE TITLE
Implement host requested system soft poweroff via PLDM effecter

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#656]
The host firmware requests the BMC to power down the system. This is a regular power off (not qick power off)

- [ ] Update State effecter PDR JSON to denote new effecter for system power state
- [ ] Update set state effecter code to map  set 260/enum 9 to host state D-Bus object

Also investigate quick power off/pci bus reset usecase.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/22755

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/25985/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/25985 merged
