### ISSUE TITLE
pHAL support for BMC Standby

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#657]
Creating basic infrastructure to enable pHAL in BMC.  This will help BMC applications to access the open POWER hardware. 
- DTM (Static)  modelling - MRW parsing, DTM  data compiler 
            - Supporting to minimum set of attributes
- Importing pHAL libraries to BMC, which includes 
            - Basic hardware  access  layer
            - Hardware procedure infrastructure.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Current plan is to use Hand coded device tree for initial bring-up.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
All required code is in the Build closing this epic.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
