### ISSUE TITLE
pHAL support for host initialization Phase-1

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#658]
This epic is to track the work for  basic infrastructure to initialize the host and hardware  debugging facilities. 
- Method to update  user settings to hostboot
          - Since DTM is static , need to use attribute override to update the user settings. 
- HWPF ( hardware procedure frame work) plat support.
- Infrastructure for controlling open power specific booting sequence. 
- Creating [eCMD](https://github.com/open-power/eCMD/blob/master/docs/README) infrastructure for debug.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
All required code is in the Build closing this epic.

**Comment by rfrandse** [comment]
refresh
