### ISSUE TITLE
Power/Cooling - OCC Interface: Create power supply redundancy and derating factor sensors

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#66]
<a href="https://github.com/geissonator"><img src="https://avatars2.githubusercontent.com/u/1612261?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [geissonator](https://github.com/geissonator)**
_Tuesday Aug 15, 2017 at 14:09 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2154_

----

Some details in #1213.  Need to implement these using the new ipmid sensor design.

**Comment by rfrandse** [comment]
<a href="https://github.com/geissonator"><img src="https://avatars2.githubusercontent.com/u/1612261?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geissonator](https://github.com/geissonator)**
_Tuesday Aug 15, 2017 at 14:11 GMT_

----

Phase 5 for now, @spinler to check with occ team on impacts.

**Comment by rfrandse** [comment]
<a href="https://github.com/dhruvibm"><img src="https://avatars0.githubusercontent.com/u/16666879?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dhruvibm](https://github.com/dhruvibm)**
_Thursday Aug 24, 2017 at 09:23 GMT_

----

- [ ] Add YAMLs for ps derating and redundancy

- [ ] Create an application for handling PS redundancy and derating

- [ ] Add IPMI sensor read support for new interfaces.

**Comment by rfrandse** [comment]
<a href="https://github.com/tomjoseph83"><img src="https://avatars3.githubusercontent.com/u/15232150?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomjoseph83](https://github.com/tomjoseph83)**
_Friday Sep 01, 2017 at 11:34 GMT_

----

# **STATUS**

09/01
Made changes that are need for Phase 5.  It is ready for merge review.
I would be completing 2220 first before moving on to this one.

**Comment by rfrandse** [comment]
<a href="https://github.com/tomjoseph83"><img src="https://avatars3.githubusercontent.com/u/15232150?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomjoseph83](https://github.com/tomjoseph83)**
_Thursday Sep 07, 2017 at 04:59 GMT_

----

We should be removing the Power Supply redundancy/Power derating & Turbo allowed(Power specific) from the legacy dbus path check, once we get these changes in.

**Comment by rfrandse** [comment]
<a href="https://github.com/rfrandse"><img src="https://avatars3.githubusercontent.com/u/15894767?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rfrandse](https://github.com/rfrandse)**
_Wednesday Sep 20, 2017 at 12:45 GMT_

----

Merged
<https://gerrit.openbmc-project.xyz/6782> Remove legacy reading of PS derating
Resolves  #2154 Create power supply redundancy and derating factor sensors

**Comment by rfrandse** [comment]
<a href="https://github.com/geissonator"><img src="https://avatars2.githubusercontent.com/u/1612261?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [geissonator](https://github.com/geissonator)**
_Wednesday Nov 29, 2017 at 15:33 GMT_

----

This was backed out, need to find story where we bring this back in.

**Comment by rfrandse** [comment]
<a href="https://github.com/dkodihal"><img src="https://avatars1.githubusercontent.com/u/22700515?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dkodihal](https://github.com/dkodihal)**
_Thursday Nov 30, 2017 at 15:52 GMT_

----

@dhruvibm can you use this story to write new dbus interfaces and app for the PS sensors, along with ipmid changes?

**Comment by rfrandse** [comment]
<a href="https://github.com/dhruvibm"><img src="https://avatars0.githubusercontent.com/u/16666879?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dhruvibm](https://github.com/dhruvibm)**
_Thursday Dec 14, 2017 at 13:47 GMT_

----

# **Status**
Need to decide the application implementing the PS derating and redundancy servers.

**Comment by rfrandse** [comment]
<a href="https://github.com/dkodihal"><img src="https://avatars1.githubusercontent.com/u/22700515?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dkodihal](https://github.com/dkodihal)**
_Friday Mar 30, 2018 at 10:30 GMT_

----

This was implemented via https://gerrit.openbmc-project.xyz/#/q/topic:PowerSupplyRedundancy

**Comment by rfrandse** [comment]
<a href="https://github.com/dkodihal"><img src="https://avatars1.githubusercontent.com/u/22700515?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dkodihal](https://github.com/dkodihal)**
_Friday May 18, 2018 at 12:24 GMT_

----

It looks like there are still a bunch of sensors implemented via the legacy code path/python apps. @ngorugan and @tomjoseph83 will figure out which and will switch them over to the data-driven code.

**Comment by rfrandse** [comment]
<a href="https://github.com/tomjoseph83"><img src="https://avatars3.githubusercontent.com/u/15232150?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomjoseph83](https://github.com/tomjoseph83)**
_Monday May 21, 2018 at 10:20 GMT_

----

There are 2 sensors that needs to be moved from legacy code to generated code.

a) Power Supply Redundancy is supported in the settings. So the input yaml for the sensor generation needs to be updated.

b) The implementation of power derating sensor needs to be discussed.

**Comment by rfrandse** [comment]
<a href="https://github.com/gtmills"><img src="https://avatars3.githubusercontent.com/u/5455127?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gtmills](https://github.com/gtmills)**
_Wednesday Jul 18, 2018 at 14:41 GMT_

----

@tomjoseph83 @dkodihal What is this issue tracking now? Should it just be closed? We have a power supply redundancy sensor.

**Comment by anoo1** [comment]
Done with:
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-phosphor/+/12165/
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-phosphor/+/12166/
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-phosphor/+/12167/
