### ISSUE TITLE
pHAL support for Host Debug Tooling.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#660]
This epic is used for track pHAL support for Hostboot firmware debugging and  Hypervisor debugging tools.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Scope:

Provide a set of eCMD utilities as a standalone application on OpenBMC to:
       get/put scom
       get/put cfam
       host memory access(ADU/PBA) using get/put memproc & get/put mempba
       instruction control using start, stop, step & sreset
       architected state register access using get/put gpr, get/put fpr & get/put spr
       get/put SRAM (OCC) ??
       Execute any Arbitrary Istep to exercise HWPs that will be extended to exercise the HWPs across different Isteps to boot and also support  handling   of error during each Istep execution.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
All required code is in the Build closing this epic.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
