### ISSUE TITLE
pHAL RAS Phase-2

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#662]
pHAL Error handling
HWPF Platform Error handling
[SBE](https://github.com/open-power/sbe) failure handling
- Host PNOR Volatile section handling - Hostboot uses to distinguish between full restart and reconfigure loop.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
RAS work splitted into multiple epics. closing this now

**Comment by rfrandse** [comment]
refresh
