### ISSUE TITLE
pHAL: Device Tree Model Proposal

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#663]
Device Tree Model  is used to track the state of the entire system and resources for pHAL. This issues used for tracking the proposal to community about the DTM ( Device Tree Model).

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Epic #661 is used to track all dynamic device tree related work. Changing Epic.

**Comment by ojayanth** [comment]
Initial design is  reviewed Hostboot and pHAL impacted components. , Working on documentation.

**Comment by ojayanth** [comment]
Initial version is available https://pages.github.ibm.com/apopple/pdbg/html/index.html
