### ISSUE TITLE
DTM: Static Binary delivery.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#664]
- Creation of DTM Static Binary based on MRW.
    - Device node naming convention is based on conventional linux approach
    - Provide generic script for creating DTM binary based on the MRW with custom file filter.
    - Share the Device Node logic to Hostboot team for adding this info as part of the Hostboot targeting  infrastructure.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Initial Attribute data base is available for testing

**Comment by ojayanth** [comment]
As per current plan , Hostboot is not going to use static device tree, This work is tracked under Dynamic device tree support. 
Tested the existing device tree in P9 systems. and working good.

**Comment by ojayanth** [comment]
Closing this issue.  pdata code working good.
