### ISSUE TITLE
pHAL:  Investigation: Device tree Generation based on MRW data

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#665]
- Customize MRW for Initial testing
    - Identify minimum set of attributes required for  pHAL
    - Work with MRW team on creating custom MRW, which includes required  information pHAL 
    - Provide mechanism to Parse MRW in custom way.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Design Approach: 

<img width="301" alt="image" src="https://user-images.githubusercontent.com/12947151/70858276-357f2f00-1f25-11ea-9324-be9d9f25140d.png">

**Comment by ojayanth** [comment]
Splitting this issue based on the design direction . This issue used for Tracking High level design and attributes information required for initial power-on.
Additional issue required
- Customizing the existing op-build based parser and addiing custom filters.
- Generating dtb ( device tree blob) from intermediate file.
Adjusting the complexity to 3 for this issue.

**Comment by ojayanth** [comment]
Target and attribute list is prepared and available for consumption
