### ISSUE TITLE
pHAL: DTM Packaging in Hostboot build

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#666]
- DTM Packaging in the Hostboot Build
    - Package the DTM script  as part of Hostboot build infrastructure.
    - Include DTM binary as special partition in the  Hostboot PNOR image.
    - Update Hostboot targeting script to include the Device node information as part of the Targetting binary.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
This issue need to split in smaller based on the  detailed investigation.

**Comment by ojayanth** [comment]
Need to investigate details of  work and split into smaller issues.

**Comment by ojayanth** [comment]
#1656 is used fir investigation. issue , reducing the complexity to 13->8

**Comment by ojayanth** [comment]
Based on the latest discussion, using new pHAL repository to keep all BMC specific tooling infrastructure and API's.
#1656 already supported DTB pacakage in Host boot build.

**Comment by ojayanth** [comment]
This issue will use for tracking additional work involved 
- Recipe changes 
- Bring-up effort.

**Comment by ojayanth** [comment]
https://github.ibm.com/openbmc/openbmc/pull/351
