### ISSUE TITLE
DTM Service API Support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#667]
- DTM Service API Requirements.
    - Get  the given attributes, determine relationships, 
    - Allows clients to iterate over every Device Nodes in the system blueprint, 
    - Allows  using predicates/range filters etc. 
    - Provide ODE friendly packaging infrastructure.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
pHAL support for BMC standby support is available. i the latest release.  Most of the advanced function are tracked under #661. 
Moving to #661 .

**Comment by ojayanth** [comment]
https://pages.github.ibm.com/apopple/pdbg/html/index.html provides the details of the interfaces.

**Comment by ojayanth** [comment]
Issue #669 is used to track API's support for Device tree API's based on dynamic device tree backend.
