### ISSUE TITLE
DTM(static) packaging in BMC 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#668]
- DTM packaging in BMC 
    - Recipes updates to Package the DTM library as part of the required IBM specific systems.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Need a mechanism to generate DTM based on MRW/eKB attributes and package as part of BMC build

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-openpower/+/25636

**Comment by RameshIyyar** [comment]
As per layout direction recipe is changed into different layer and recipe changes is in up for review.
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/27065
https://gerrit.openbmc-project.xyz/c/openbmc/meta-openpower/+/25802
