### ISSUE TITLE
DTM (Dynamic)  API support 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#669]
- DTM Dynamic binary update support 
    - Provide infrastructure to Dynamically update of devices and attribute

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
https://github.ibm.com/phal/pdata/blob/master/attribute/attribute_api.h

**Comment by mzipse** [comment]
Closing this issue. Work is complete.
