### ISSUE TITLE
Inband Firmware Update for OpenPOWER

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#67]
<a href="https://github.com/anoo1"><img src="https://avatars0.githubusercontent.com/u/9052527?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anoo1](https://github.com/anoo1)**
_Tuesday Oct 03, 2017 at 15:24 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2404_

----

Epic to track all the work related to enabling inband firmware updates.

**Comment by rfrandse** [comment]
<a href="https://github.com/anoo1"><img src="https://avatars0.githubusercontent.com/u/9052527?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anoo1](https://github.com/anoo1)**
_Wednesday Nov 15, 2017 at 16:17 GMT_

----

* Need protocol (mbox, ipmi, lpc, pci, ...,) to send image file from host to BMC to the location where the REST upload currently copies image files to (/tmp/images/).
* New IPMI command handler to trigger the activation when ipmitool hpm request is done. The request could be blocked for out-of-band.

**Comment by rfrandse** [comment]
<a href="https://github.com/shenki"><img src="https://avatars1.githubusercontent.com/u/207355?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shenki](https://github.com/shenki)**
_Monday Jan 15, 2018 at 21:17 GMT_

----

Discussion on in-band code update from January OpenBMC hackfest: https://docs.google.com/document/d/1xO3Vl_M5sY3lcCAAM3noBtleH1d9xk-bwqxzVbTX36o/edit?usp=sharing

**Comment by mzipse** [comment]
This is a tewst

**Comment by rfrandse** [comment]
test

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
No current plans for this.
