### ISSUE TITLE
pHAL: DTM attribute support in MRW

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#670]
- DTM Attributes support in MRW
    - Work with stake-holders and identify the attributes should be part of the DTM

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Scope is limited now based on the new design direction . BMC side attribute information ( excpet, Attn/PRD) apps are already part of System workbook ,  waiting for input from Hostboot team . 
Reducing the complexity 13->5.

**Comment by ojayanth** [comment]
Attribute xml is available fro development.  Will be closing this issue once it is merged in pdata.

**Comment by mzipse** [comment]
Closing this issue. Work is complete.
