### ISSUE TITLE
DTM Dynamic binary service upates.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#671]
- DTM Service updates 
    - Provide Attribute set function and allows updates during Hostboot window.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Need a mechanism in Device tree Backened to restrict device tree updates during Hostboot IPL window.

**Comment by ojayanth** [comment]
This feature got dependency on Hostboot Device enablement milestone Currently targeted for 07/15 with @apopple moving this to #1513

**Comment by ojayanth** [comment]
Moving Backlog , This is required only in Device tree Lock support ferature.

**Comment by rfrandse** [comment]
tracking in jira
