### ISSUE TITLE
DTM data Persistency  management.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#672]
- Organize the Attributes to support  the System specific use case like
        - BMC reboot should persist the Hostboot attributes. 
        - Cec- power of path Hostboot attributes should be reset to default. 
        - BMC should add required support to enable this .

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
* Attribute xml provides the information of persistency information( Volatile, semi-volatile and no-volatile ) of each attribute. 
* BMC and hsotboot owned attributes persistency management is different
    * Usecases: BMC reset-reload and CEC power-off . 
* Currently three types of attributes
    * , BMC only, Hostboot only and Common attributes. 
* Need to set common process of setting attribute types. From the persistency point. 
* Persistency design approch
    *  Keeping implementation level meta data for each attributes, which includes type and persistency level during build time
        * Device tree API  can provide iterator functions  to get specific persistency type attributes.
            * Pros : Supports all type  targets. 
            * Cons: Additional logic in the Device tree API level to manage this 
    * Provide a mechanism in Device tree API to reset these attributes in each IPL context. 
    * Include default data information in the meta-data section to support this.

**Comment by ojayanth** [comment]
New Design direction: preserve all Hostboot updated attributes / HWAS states related attributes in non genesis mode ipl. Only apply Guard records. 

Current BMC Flow:
Genesis mode:
- All units marked as non functional/presence

Normal Poweron
Get present processor in the system based on fsi presence ( pdbg probe).
Mark all the processors and primary processor child  chiplets({"core", "pauc", "pau", "iohs", "mc", "chiplet", "pec", "fc"} as  present/functional.
This direction we choose to support gard record removal at standby use case. Like incase some one celar the guard receords , BMC need to mark as functional to run step 0 procedures/ SBE updates.
Remove fake guard records
Apply the  the guard records: Unset the functional state of the guarded resources ( Note: Rule is applied for all targets in the system)
To be added: Skip Primary processor guard apply. 
Note:
- No updates related to non HWAS state attributes updated by Hostboot.

REIPL;
Apply the  the guard records( including fake Guard): Unset the functional state of the guarded resources ( Note: Rule is applied for all targets in the system)
To be added: Skip Primary processor guard apply. 
Note: 
- No fake Guard removal in this flow
- No updates related to non HWAS state attributes updated by Hostboot.

MPIPL:
Apply only core guards
Note: 
- No fake Guard removal in this flow
- No updates related to non HWAS state attributes updated by Hostboot.

**Comment by ojayanth** [comment]
Reducing the issue complexity , need to revisit this incase any any additional requirement for SBE/Hostboot team

**Comment by ojayanth** [comment]
open-power/pdata#9 -- Pdata changes - Merged.

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/49101/
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/49102/

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/49406
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/49405
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/49298
