### ISSUE TITLE
 DTM support for Concurrent Code update: Design

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#673]
Need to support new device node/ attribute support and data persistency.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Customer settings are handled by BIOS attributes and not part of device tree.
*   No impact from Device tree point. 
Mainly need to look below use cases in concurrent code update path.
* Preserving attributes ( Eg state )  and special attributes handling  during code update. 
* New target/attribute addition/removal  in the new device tree with new code update. 
Need to look impact on Disruptive code update path

**Comment by ojayanth** [comment]
Concurrent code update impact on device tree: 
- Key attributes we need to persist after concurrent code update is functional states. 
      - Most of  non-fapi attributes usage scope are limited to step 0 procedure execution
             - No reason to recover this value back in this path
     - Other r/w attributes updated by hostboot during ipl time is only consumed by host in the next ipl path.
            - System run time -> concurrent code update -> reboot-> system runtime-> re-ipl 
     - Any us case for hostboot to preserve attributes ( including functional )states in this path?  Or genesis mode will create any additional issues other than additional re-ipl for memory related targets functional states.
           - Hostboot agreed additional reconfig loop in this loop to reduce sync complexity.
     - MPIPL use case required to prserve functional status after concurrent code update
           - Any other Hostboot updated attributes need to preserve in the concurrent code update path?
     -  Phal requires functional processors to issue Processor Stopall command
           - Since this error path we can rely on pdbg way, probe hw and issue stop only present hw’s 
     -  Guard tool/manager is not having any direct impact on this.
     - HW Dump requests comes only for functional proc,
          - This path also required functional states, for sbe chip-op.
          - Dan mentioned that , it will be good to include hwas state in the hw dump data.
     - Attn/PRD currently using pdbg based functional state not the HWAS state
        - Discussed with Zane , PRD/ATTN currently using pdbg based state , and not seeing any issues  now
        - some limitation on this approch
           - Pdbg doesn't supports OCMB probe. also it is going to work only after step 11.
          - Getting OCMB presence early required DIMM SPD read. in pdbg, that would require knowledge of the DDIMM SPD format.
          - Hostboot sync's the presence/functional state attribute during first Host-BMC dev tree sync at step 6.
         - pdbg only provides hw  presence state using prob function. Not reall providing actual functional state.
         - functional state is based on GUARD+VPD PG + Associated deconfigure rules.
         - Recommend PRD team to use HWAS state nstead of pdbg presene for OCMB .

**Comment by ojayanth** [comment]
High level design Direction:
1. Collecting attribute data , which need to be preserved across the code update use attribute tool and store in preserve partition.
2. Apply attribute override in the BMC reboot path after concurrent code update triggered reboot.

Work involved:
- Identify the attribute list need to preserve.
- Extend attribute tool import/export option to support selected attributes.
- Currently common code update interfaces used for both concurrent/disruptive updates . Need to  explore the option to identify , the concurrent code update trigger.

**Comment by ojayanth** [comment]
This issue used for tracking Requirement/High level Design Direction.
