### ISSUE TITLE
DTM Attribute coherency support 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#674]
Need to add support related to BMC application access for the attributes during  host boot update window.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Not seeing any issue related to this . Updating the milestone.

**Comment by rfrandse** [comment]
tracking in jira
