### ISSUE TITLE
DTM Performance tuning

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#676]
DTM apis Performance tuning.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
- Used to track all  device tree performance related issues.
- Device tree size optimisation , Need to limit size  dab size less than 500K.

**Comment by rsnair** [comment]
Estimated Story Points - 20. Modifying this to 0 as it's not in scope for GA1. If there is a better way to have this not getting included in the reports, we can change it back.

**Comment by ojayanth** [comment]
Updated Story points and updated the milestone.

**Comment by ojayanth** [comment]
No performance issues reported , Closing this now,
