### ISSUE TITLE
Create an error log if system loses power during a BMC reboot

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#677]
If the chassis was on, and then the BMC reboots and when it comes back the chassis is off, we should create an error log to provide a hint that there as probably a power issue.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Proposed Solution:

1. In chassis_state_manager.cpp, persist the currentPowerState using cereal.
2. In the Chassis class contructor, after determineInitialState runs, check for the newly determined current state to be off, and for the persisted state to be on.
3. If the check above is true, create an error log (come up with an appropriate one)
4. After the check, persist the latest current state again.
5. every time the Current state property changes, persist it.

**Comment by spinler** [comment]
Proposed an error definition for this at https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/22791

**Comment by geissonator** [comment]
This feels like something right on the cusp of needing a design doc since the proposal is that common phosphor-state-manager code will create this new error. Everyone may not want that. Maybe we'll need it configurable? It's own app? If everyone does want it then obviously the design above makes sense.

**Comment by rfrandse** [comment]
refresh

**Comment by joseph-reynolds** [comment]
I am curious what logs are written for:
- The BMC initiating a reboot of itself (warm reset or code update)
- The BMC booting up (three cases: for its initial boot after installation, after a deliberate reboot, or after something like a power failure) - (I guess we'll have plenty of log entries for this)
- The BMC booting up and detecting the host power state is different (this issue)

It seems like the log should record the facts, with "blackout detected" being one of the events.  I can't imagine anyone would object to these log entries.

**Comment by bjwyman** [comment]
Noted mailing list topic.
June - https://lists.ozlabs.org/pipermail/openbmc/2019-June/016894.html

Curiously, mail archive does not have next thread, have to move onto July to see thread continue.
July - https://lists.ozlabs.org/pipermail/openbmc/2019-July/017227.html

**Comment by spinler** [comment]
Done.

**Comment by bjwyman** [comment]
https://github.com/openbmc/phosphor-state-manager/commit/27115aec886d69def59d18be7534d1156a9712ce
