### ISSUE TITLE
pHAL Initial delivery

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#681]
- Basic infrastructure code to support  CFAM (getCFAMReg and putCFAMReg ) and BMC native SCOM
    - library based Packaging design.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Initial Version code is available. Bring-up is in progress.

**Comment by ojayanth** [comment]
Successfully booted Witherspoon system with latest pHAL code .
