### ISSUE TITLE
pHAL SBE Chip-op Infrastructure  support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#683]
- Enable the Chip-op based SCOM support
    - API level support to call chip-ops from the  BMC applications.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Basic chip-ops based infrastructure is available for initial Bring-up

**Comment by ojayanth** [comment]
Required sbe-chipop Support is available in pdbg .
