### ISSUE TITLE
pHAL SCOM Address translation support. 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#684]
- Add support for SCOM Address translation for step 0 procedures and ecmd , scoms.
    - Assumption:  Hardware team will be providing the common code for address translation.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Required pdbg side changes based on new Device tree .

**Comment by ojayanth** [comment]
No impact on step0 procedure execution, Required only for poweron.
Adjusted the staging plan

**Comment by ojayanth** [comment]
https://github.ibm.com/openbmc/openbmc/pull/422
