### ISSUE TITLE
pHAL HWP infrastructure support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#685]
-  Allow BMC application to execute arbitrary hardware procedures supplied by the hardware team
        - Which includes FAPI/Plat based HWPF infrastructure in PHAL layer.
        - Error handling and Plat work is not included here.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
pHAL is going to use libekb based infrastructure  for enabling HWPF in BMC. 
Scope of this issue to add required recipe and bring-up effort in BMC.

**Comment by ojayanth** [comment]
Code Review is in progress .

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-openpower/+/25637
