### ISSUE TITLE
pHAL HWP plat support- Phase1

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#686]
BMC specific plat code implementation for HWP execution.

**Comment by ojayanth** [comment]
This covers only positive path step0 hardware procedure execution.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
P9 Plat  infrastructure  code tested  and working good . Need to do validate compilation for p10

**Comment by ojayanth** [comment]
Tested in simulation environment
