### ISSUE TITLE
HWPF: eKB mirroring support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#687]
Enable eKB mirroring support to sync Hardware procedure from common repo.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Finalized high level direction and curently Sumit from Infrastructure team is working on it.

**Comment by ojayanth** [comment]
ekb repository  Infrastructure  is  ready.
Working on getting initial version of ekb code in pub-ekb repo

**Comment by ojayanth** [comment]
Issue created #1674 to track Base infrastructure code.
Reducing complexity.

**Comment by ojayanth** [comment]
Local version of pub-ekb is ready.  
Remaining work :  update openbmc recipes to support pub-ekb related support and testing

**Comment by ojayanth** [comment]
https://github.ibm.com/openbmc/openbmc/pull/380.
