### ISSUE TITLE
pHAL HWPF Error handling infrastructure support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#689]
- HWPF BMC platform code must translate native BMC errors and targets to HWPF platform neutral versions, and back

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Place Holder: This issue will used to update  hwp plat changes relate work

**Comment by ojayanth** [comment]
Support is already in place
