### ISSUE TITLE
pHAL SBE Chip-op failure Infrastructre support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#690]
- SBE response with failure data Attach SBE FFDC ( chip response packet) to the BMC error log. 
       - Timeout : SBE FIFO failure : Time out error ( not sure SBE's problem) 
            - Force SBE in debug mode.and collect register in FSI path and switch to fail state. 
            - Collect SBE dump using  P9 extract SBE HWP : Reason code / Recovery action / Or hard failure. 
            - Reset FIFO 
            - Switch SEEPROM and re-boot.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
- Restrict SBE chip-op requests  during SBE dumping and maintenance modes.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
**Use cases:**

- Chip-op Failure IPL Time ( continue MPIPL, check attn reason code  and  host Dump chip-ops)
- Chip-op Failure run Time - No recovery ( enter MPIPL, check attn reason code  and  host Dump chip-ops )
- Chip-op Failure run Time -  recover SBE ( enter MPIPL, check attn reason code  and  host Dump chip-ops )
- SBE  time-out at IPL Time ( Host watch dog time out due to SBE belly-up  + above chip-ops)
- HB  SBE operation failure ( IPL time )
- HBRT  SBE operation failure ( run time )

**pHAL/op-proc-contol**

- SBE RC handling Infrastructure/ interfaces for state management and Chip-ops user  during SBE belly-up
- Interface to extract rc based extract_sbe_rc procedure.
- SBE FFDC to PEL conversion infrastructure.
- Get SBE FFDC chip-op support
- Pdbg chip-op RC conversion to meaningful reason codes.
- Runtime non-recovery failure 
- Runtime SBE Recovery failure.
- SBE SEEPROM selection logic during errors ( include , measurement/normal SEEPROM handling)
- Interface to check SBE state
- SBE state management infrastructure ( devtree attribute based)
- Additi onal attributes  related SEEPROM selection , Measurement Seeprom related and SBE selection.(Processor Level)

    - ATTR_PRIMARY_SEEPROM_FAIL_COUNT
    - ATTR_SECONDARY_SEEPROM_FAIL_COUNT
    - ATTR_PRIMARY_MSEEPROM_FAIL_COUNT
    - ATTR_SECONDARY_MSEEPROM_FAIL_COUNT
    - ATTR_SBE_STATE 

- SEEPROM Selection related attributes updates in various use cases.


Checkstop monitor:
- Interface to Check  SBE checkstop or vital attn handling is in progress
- HB-SBE communication failure related TI handling
- Chip-op failure handling updates.

State Management:
- Target file / reboot count updates to support various SBE failing use cases. 

Dump:
- Chip-op failure handling updates.

PLDM:
- Update in Host watchdog timeout handling to invoke SBE error handling during SBE boot window
- Interface to recover SBE during runtime SBE chip-op failure

SBE:
- FFDC support for chip-op failure
- Get SBE FFDC chip-op support

Hostboot:
- TI support for HB-SBE communication failures

HBRT:

- Runtime SBE recovery during failures/BMC requests.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Scope: Provide PEL based d-bus Interface to create SBE FFDC based error log.
- Processing of HWP failures provided by SBE
- Adding HW callout and service actions related information in the error log.
- SBE internal failure logged as raw hex data.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
