### ISSUE TITLE
pHAL SCOM ( BMC native) failure handling

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#692]
BMC native scom failure Debug data info in the error log.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
- BMC Native SCOM  ( SBE Dump use case only)
    - Callout end point and bus path
    - SCOM should fail if Clock’s are off.
        - SBE Dump procedure need to include pre-check
            - Check SBE pervasive clock’s are on  and SBE CBS engine started.
            - Return appropriate error rc’s based on type of pre-check failures
            - Callout details need to update based on the error type.

**Comment by ojayanth** [comment]
SBE HWP team agreed to get required pr-check support in the SBE dump specific hwp's . Out look is May end 2021.

**Comment by ojayanth** [comment]
BMC native scom is only used by sbe dump hardware procedure. Since sump is taken onlly in error path also existing dump flow ignores the errors and collects data  with best available approach.  Considering this use the best approch is to keep log file to capture all failures and package as part of sbe dump. This approch will help dump users to know the failure reason.s @dhruvibm

**Comment by ojayanth** [comment]
Since this is considering as double failure moving milestone to  cec-management advaned functions and backlog #3382

**Comment by rfrandse** [comment]
tracking in jira
