### ISSUE TITLE
create a dbus interface to initiate dump

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#694]
dbus Interface definition for initiating a dump with content type, used by external interfaces and internal applications.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
D-bus interface for user initiated system dump

**Comment by msbarth** [comment]
Will this interface also be what's used by another BMC application to initiate a dump?

**Comment by ojayanth** [comment]
Direction is to use existing interface.

Details available here https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/33911
