### ISSUE TITLE
Implementation of dump base infrastructure

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#695]
Implement a generic infrastructure to initiate dump

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
This is used to track user initiated system dump. 
Based on the current priority moving to post power-on milestone

**Comment by ojayanth** [comment]
All the required code is merged 
Last commit in the chain https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/36746
