### ISSUE TITLE
Implementation for initiate system dump

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#697]
Implement initiate interface for system dump, this includes calling chip-ops to start and continue MPIPL, implementing targets and services to do the required operations.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Increasing complexity to contain the chip-op work here.

**Comment by dhruvibm** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/29449 Add support for memory preserving reboot
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/29482 Add service to enter and continue mpreboot

**Comment by ojayanth** [comment]
Code is in master.
