### ISSUE TITLE
SBE dump: Implementation of SBE dump in dump manager

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#698]
Implement initiate SBE dump to call SBE error handling function. Collect the dump, package and store it.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
#690  is used to track all the SBE dump triggering  error use cases. This issue is mainly used for - 
- HWP reviews and integration related to SBE extract rc procdeure.
- Dump manager related changes to support SBE dump type.
- Packaging infrastructure support

**Comment by dhruvibm** [comment]
This epic to track the implementation of SBE dump in dump manager,

**Comment by rfrandse** [comment]
tracking in jira
