### ISSUE TITLE
phosphor-rest-server: Fetch user LDAP group and permissions from the LDAP server

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#7]
When a user login to the BMC using the LDAP user credentials, the goal is to fetch the LDAP group corresponding to the LDAP user account and assign a permission based on the LDAP group. The possible permission combinations are Admin and Read only and this information should be part of the REST session.

There is an open item to investigate how to map the user permission to LDAP group.

a) BMC provides a configure API for the user to create entries like <Group_Name>,<User_Permission>. This information will be used at the time of user authentication. The LDAP user credentials will be used to get the LDAP group information. The LDAP group info will be mapped to User permission with the configures data and assigned to session.

b) LDAP group attributes will be used to figure out the permission needed for session.

**Comment by dkodihal** [comment]
This is same as #8.
