### ISSUE TITLE
User initiated hardware dump

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#701]
Implement collection from SBE and packaging of hardware dump

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
SBE chip-op basaed hw dump collection , packaging and bring-up effort.

**Comment by dhruvibm** [comment]
This issue is for tracking the user initiated hw dump

**Comment by rfrandse** [comment]
tracking in jira
