### ISSUE TITLE
BMC initialization for Hostboot attributes. 

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#703]
IPL initialization from BMC.
- core mask ,
- IPL Modes
- RISK level
- SMF enabled or not.
- Memory synchronized mode
- PCI reference clock
- Clock mux settings.
- Slave/master core info
- Setting effective Fabric/HRMOR/effective id, memgroups  - BMC need to know the group ID info. for HRMOR calculation.

Note: this list is incomplete.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Power-on related attribute initialization is handled under  issue #1278.
Moving this under #1964 now.  to support all remaining Hostboot requirements, once the support is available

**Comment by ojayanth** [comment]
Reducing complexity,  based on #1278 support work.

**Comment by ojayanth** [comment]
#672 Already covered this work.
