### ISSUE TITLE
Implementation for host dump clearing.

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#708]
Create a dbus interface for removing an existing dump

**Comment by ojayanth** [comment]
We can use the existing delete/deleteall method. 
Requirement tracking purpose keeping this issue open.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
System Dump Delete is handled via PLDM message. Use this issue for tracking this.

**Comment by dhruvibm** [comment]
This story is to implement the clearing of offloaded host dumps based on the request from the user.

**Comment by RameshIyyar** [comment]
Addressed in below patches to enable host system dump deletion. 
https://gerrit.openbmc-project.xyz/q/topic:%22host-system-dump-delete%22+(status:open%20OR%20status:merged)
