### ISSUE TITLE
Implementation for downloading dump

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#712]
Implement changes to support downloading of a dump to an external interface.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
This issue used for tracking non-system dump download

**Comment by dhruvibm** [comment]
The dump offload is implemented https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/31628
