### ISSUE TITLE
Host interface for system dump status

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#713]
Implement changes to get the status of system dumps from host.

**Comment by dhruvibm** [comment]
Pre-req: PLDM Interface support is available

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@ojayanth , can this be closed?  I think all the PLDM Dump support is being tracked under Epic 910?

**Comment by dhruvibm** [comment]
Yes this is done by PLDM
