### ISSUE TITLE
Implementation of dump redfish schema

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#716]
Implement redfish schema for managing dump
Note: This is a place holder story, need to revisit based on redfish schema content.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@dhruvibm , please take a look at the stories that @ratagupt has defined for HMC.  I think this might be a duplicate for some of them in this query.... https://github.com/ibm-openbmc/dev/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+dump

For example:  #844 #845 #846 #847 and #848

**Comment by gtmills** [comment]
@dhruvibm @ratagupt How is this work separate from #844 #845 #846 #847 and #848 ? Should this be the epic and those stories under it?

**Comment by ojayanth** [comment]
@ratagupt already got issues to track reddish related work
