### ISSUE TITLE
BMC IPL steps: sbe start

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#717]
- Set POWER config/control regs (mailbox scratch registers for SBE side selection/mfg flags)
- Execute HWP to  kick-off Master processor chip SBE

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
- Add any P10 specific IPL application  changes if required.
- Add support for statically  switching device tree for p9/p10.
   - Add recipe to install Device tree baased on the system type .
   - IPL application should use generic file name for all types of system.
