### ISSUE TITLE
BMC IPL steps:  set_ref_clock

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#719]
•	Test to see if the ref clock is valid.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Work includes:

- Review HWP related to this istep.
- Enable HWP in Libekb Build infrastructre
- Enable IPL support for this istep.

**Comment by ojayanth** [comment]
- Enabled the HWP procedure in the BMC Build.
- During testing found some attribute access issue , working with Amitay on this.

**Comment by ojayanth** [comment]
Tested with pdbg patch , working good.  Will push the PR once pdbg fix is upstream.

**Comment by ojayanth** [comment]
https://github.ibm.com/openbmc/openbmc/pull/351#
