### ISSUE TITLE
System dump enablement on Simulation

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#720]
Combine all pieces together and test system dump functionality

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Bring-up work on Hardware.

**Comment by dhruvibm** [comment]
The scope of this story is to do the initial bringup on simulation

**Comment by dhruvibm** [comment]
Bringup in progress

**Comment by ojayanth** [comment]
@dhruvibm New dump code validate in Simics?

**Comment by ojayanth** [comment]
Rainier, HW MPIPL and system dump path validation completed.  Dump offload is not working due to know nbd issue.

Need to validate  the latest driver in simulation environment.

**Comment by mzipse** [comment]
@ojayanth , can this be closed now?  I believe the final version of the Dump Offload is now working.

**Comment by dhruvibm** [comment]
The testing on the simulation is completed hence closing
