### ISSUE TITLE
IPL: Create generic open power IPL DBUS interface

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#724]
Create a dbus interface for initiating isteps on open power systems

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Based on the discussion reducing complexity to 3.

**Comment by ojayanth** [comment]
Based on the design discussion , d-bus not required . See design template for details

**Comment by amboar** [comment]
What design template?

**Comment by geissonator** [comment]
> What design template?

https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/23054

**Comment by amboar** [comment]
Also - and this is a real narky nitpicky clarification - a "design template" ceases to be a template when someone actually fills it out; at that point it's just a "design".
