### ISSUE TITLE
IPL: Extending state manager to accept system specific implementation

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#726]
Extend state manager to accept system or architecture specific transition requests.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Based on the design discussion , State manager specific changes are not required .
