### ISSUE TITLE
IPL support for unit discovery before starting the host

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#727]
Add support to discover some of the key components like master processor before initializing the host

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
This a post-poweron feature.

**Comment by ojayanth** [comment]
Design Direction:
- BMC should update all the available processor functional state based fsi presence and GUARD records status.
-  BMC should update the device tree functional state for all required chiplets in the master processor based on the GUARD records except for mc units.
- MC alway's marked as functional in the genesis mode. and hostboot will update the status during ipl anny mismatch in scractch register status with actual presence , will initaite re-ipl.
- In the MPIPL path only core state , based on GUARD records should be updated .

**Comment by ojayanth** [comment]
#1967 is  the implementation story . This is used for investigation/design.
Reducing complexity and updating #1967 complexity for the implementation work.
