### ISSUE TITLE
IPL: support for clock test

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#728]
Create an entry point for clock test

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Work includes:
 - Review Clock test HWP
 - Enable Clock test HWP in libekb 
-  Enable HWP in HWP infrastrucre.

**Comment by ojayanth** [comment]
Found some failure in Simics . Required action file updates.

**Comment by ojayanth** [comment]
Successfully Tested in Simics and all  required support is available in Simics driver.
Required updated device tree support in BMC driver to enable this support BMC build.

**Comment by ojayanth** [comment]
https://github.ibm.com/openbmc/openbmc/pull/351#

**Comment by mzipse** [comment]
Closing this issue. Work is complete.
