### ISSUE TITLE
IPL: Support for SBE start

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#729]
Create an entry point for SBE start ipl step

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Duplicate

**Comment by ojayanth** [comment]
This issue will use for prototyping start sbe in Power 9 based procedure with new IPL service infrastructure.

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/25680

**Comment by RameshIyyar** [comment]
As per new direction this story is changed to use libipl instead of boot app and same support added and code is up for review.
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/27095
