### ISSUE TITLE
IPL: SBE IPL failure handling

### ISSUE THREAD

**Issue by dhruvibm** [ibm-openbmc/dev#731]
Failure handling during SBE IPL window

**Comment by ojayanth** [comment]
Mainly interface function to invoke the right error handling function.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Already handled as part of SBE Error Handling epic
