### ISSUE TITLE
GUI : Design : Disable BMC shell access for support

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#734]
Discovery work for determining the need for security page and the functionality it controls. 

Related Story: #512

**Comment by derick-montague** [comment]
Need to add the description for this based on the associated Epic. The priority and timing of this will be based on the back-end item prioritization.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Closing story, work being done in #1273
