### ISSUE TITLE
Swift DIMM call out mapping for memory power faults

### ISSUE THREAD

**Issue by bjwyman** [ibm-openbmc/dev#735]
Mapping of OMI* to DIMM* call outs may need to be updated/corrected.

See openbmc/meta-ibm/meta-witherspoon/recipes-phosphor/power/power-sequencer/swift/ucd90160.yaml

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
