### ISSUE TITLE
pHAL: Processor Stop instruction Interface support

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#736]
Need a mechanism issue processor stop instruction  on all cores in the system.  
Work includes 
- SBE chip-op enablement in BMC.
-d-bus interface for external application.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/49173
pdbg changes are in reveiw.

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/49362/
https://gerrit.openbmc-project.xyz/c/openbmc/openpower-proc-control/+/49362/
