### ISSUE TITLE
pHAL Requirements analysis

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#737]
This is to track all investigation stories related to BMC  pHAL.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Initially created this epic to Track all High level requirement.  A
Discussed the High level requirements  and created issues based on this.
