### ISSUE TITLE
Unable configure IP on VLAN interface via redfish

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#738]
This is a mirror of https://github.com/openbmc/bmcweb/issues/79

**Comment by rfrandse** [comment]
refresh

**Comment by sunharis** [comment]
The DMTF standard does not support the patch of IP address on the Vlan interface. Discussing this with the forum on the below link asking to get this support into the standards.
https://redfishforum.com/thread/202/configuring-vlan-ip-address

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Seems dmtf is agreed on enhancing the schema, will do this once the DMTF schema is published.
Closing this story for now.
