### ISSUE TITLE
pHAL HWP plat support- Phase2

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#739]
This include Error path and additional functions to support complete FAPI infrastructure in the BMC

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Few commits already merged. 
 https://github.ibm.com/phal/libekb_p10/pull/10. still review

**Comment by mzipse** [comment]
Closing this issue. Work is complete.
