### ISSUE TITLE
Hostboot trace tool

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#741]
Provide a tool to collect hostboot background tool from BMC

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Tooling work involves.
 - use ecmd  based back-end function to collect required debug trace data from host memory area.
- Provide parsing infrastructure.

**Comment by ojayanth** [comment]
Nice to have.

**Comment by rfrandse** [comment]
tracking in jira
