### ISSUE TITLE
pHAL: Memory address translation procedure

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#743]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by trajeswaran** [comment]
Ken Vossen has gone through the P9 fsp code memory address translation of effective/virtual to real address and has confirmed that there are no changes in P9.  This issue to port fsp code to run on Cronus. Initially, it will be tested using P9 hardware.

**Comment by trajeswaran** [comment]
I have ported firmware address translation module to Cronus. I could not test the ported code in firmware. so, I have shared the ported code with Matt for testing in Cronus environment.

**Comment by trajeswaran** [comment]
Shubha, from PHYP Tools team, has confirmed that she is able to set a breakpoint on a virtual / effective address. So, this story can be closed.
