### ISSUE TITLE
GUI: Create multi-select component

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#746]
## Expected Delivery Dates
- [ ] FED: 7/1/19

## Use Case
---

## References/Resources
http://react.carbondesignsystem.com/?selectedKind=MultiSelect&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@jandraa - Is this ready for FED work? I believe it is, but want to clarify.

**Comment by jandraa** [comment]
Yes, it is ready for FED work

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Will use bootstrap...no longer valid story
