### ISSUE TITLE
Add PEL extension to phosphor-logging

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#748]
This just covers the basics, probably stubbed callback functions.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23637/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23637 merged
