### ISSUE TITLE
Add OpenPower logging D-Bus interfaces to phosphor-logging PEL extension

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#749]
These APIs are for talking to the PLDM daemon.

**Comment by spinler** [comment]
This is just for the interface YAML.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/28080/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/28080 merged
