### ISSUE TITLE
PEL Repository - Save a PEL

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#750]
in the PEL extension, be able to pull a PEL referenced in an incoming openbmc log and save it in the repository

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23645

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23645 merged
