### ISSUE TITLE
PEL Repository - Implement GetPEL D-Bus API

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#751]
After a PEL is in the Repo, implement the D-Bus API to get it

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/28080

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/28080 merged
