### ISSUE TITLE
PEL Repository - implement Delete Hook

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#752]
When an OpenBMC log is deleted, also delete a PEL

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23654

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23654 merged
