### ISSUE TITLE
PEL Repository - Update host PEL fields

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#753]
For incoming PHYP PELs, set the log ID and committed timestamp

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Will deliver this as part of #750.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23645/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23645 merged
