### ISSUE TITLE
Support to parse/update the PEL Private Header section

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#754]
The committed timestamp and log Id are in the Private Header.  Need to add support to be able to modify fields in there.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Will deliver this along with #750.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23641/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/23641 merged
