### ISSUE TITLE
FP5280G2: kernel support

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#759]
This task is to add kernel support for FP5280G2, including kernel device tree, configs.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by wangzqbj** [comment]
Merged: https://gerrit.openbmc-project.xyz/c/openbmc/meta-aspeed/+/22618
