### ISSUE TITLE
FP5280G2: power on services and scripts

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#760]
This task is to add services and scripts related to power on the FP5280G2 system.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by wangzqbj** [comment]
The hardware engineer completed the relevant settings of avsbus/vrm. :smile:  so, there is nothing need to do, so close it.

**Comment by mine260309** [comment]
So the estimate of 5 is not correct.
@wangzqbj Could you kindly update the estimate to an appropriate value?
