### ISSUE TITLE
FP5280G2: add sensors

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#761]
This task is to add temperature, occ, and other sensors related to hwmon.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by lxwinspur** [comment]
- [X] temperature adc fan_tach

Merged: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/22656

- [ ] occ

**Comment by rfrandse** [comment]
refresh
