### ISSUE TITLE
FP5280G2: add led configs

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#762]
This task is to add configs for LEDs.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by wangzqbj** [comment]
Fp5280g2 led light control mode is not compatible with obmc, and CPLD has achieved one-to-one control of buttons and LEDs, so there is nothing to do here right now.

**Comment by wangzqbj** [comment]
Currently, power led doesn't work as expected, we should fix it. And we need to add some other led s to the system.

tasks

- Remove  the GPIO INIT_OK node from the dts 
- Treat the  init-ok pin  as a led, add it to led.yaml
-  Add necessary led to DTS(cpu failure,mem failure ... )

**Comment by ChicagoDuan** [comment]
Patch has been completed and added:
https://lists.ozlabs.org/pipermail/openbmc/2019-September/018014.html
