### ISSUE TITLE
FP5280G2: fans support

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#763]
This task is to add fans support, including fan presents, monitor, and controls.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by wangzqbj** [comment]
Tasks:

- [ ] presence config
- [ ] monitor config
- [ ] events config
- [ ] zone config

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
