### ISSUE TITLE
FP5280G2: GPIO configs

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#764]
This task is to add GPIO related configs, including `gpio_defs.json`, possible gpio presences checks, and gpio monitors.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mine260309** [comment]
Possible tasks:

- [x] Define `gpio_defs.json`
- [ ] Define gpio monitor for checkstop
- [ ] ...

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
