### ISSUE TITLE
FP5280G2: ipmi configs

### ISSUE THREAD

**Issue by mine260309** [ibm-openbmc/dev#765]
This task is to add configs related to ipmi, sensors, inventories, frus, etc.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by wangzqbj** [comment]
Tasks:
- [ ] ipmi channel
- [ ] fru
- [ ] sensors
- [ ] sel

**Comment by mine260309** [comment]
Be noted that the ipmi channel config is now using a json config.
On Romulus currently there is no channel config at all.
See related code at:
https://github.com/openbmc/phosphor-host-ipmid/blob/c419680b2905f5ed559a6eed43387cdc827125af/user_channel/channel_mgmt.cpp#L39-L46

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by lxwinspur** [comment]
Merged: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/23311
- [X] fru
- [X] sensor
- [X] sel

**Comment by slylinux** [comment]
Some sensors still need to config

**Comment by lxwinspur** [comment]
test completed, sensors does not need to be configured
Merged: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/23311
