### ISSUE TITLE
Hostboot debug-frame work enablement in BMC

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#766]
Enabling Hostboot debug tool in in BMC environment :

- single image ( BMC +Host) will have  hostboot  .syms files.

- Hostboot need to provide install options to BMC fro the debug frame related files installation in BMC .

- Recipes support  to install host-boot debug tools in BMC

Additional information is  available [here](https://github.com/ibm-openbmc/dev/issues/490)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by lkammath** [comment]
WIP

**Comment by rfrandse** [comment]
tracking in jira
