### ISSUE TITLE
eBMC State Management - CEC Termination and Error Recovery

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#768]
Tracks the following work:
- Automated error recovery from boot failures
  - OnError Target definitions, automated reboots
- Required CTRM function
  - Ensure terminating error logged
  - Provide mechanism for applications to terminate system and go into recovery
  - Capability for an error to cause a termination but not go into recovery (for example a power error where a re-ipl should not be attempted)
- GARD / Deconfig
  - Minimum requirements to handle GARD and deconfig data

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
#2987 tracks a way for users to have an error that can be both terminating and non-terminating depending on the situation.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
All stories and epics complete, just waiting to for last one to get pulled into downstream.
