### ISSUE TITLE
eBMC State Management - BMC Reset with Host Running

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#769]
PLDM work tracked in #905 

May need this path to work with both IPMI and PLDM paths depending on support plans.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
High level, I think we have 3 stories here:
- Finalize design doc
- Write small service to check with PLDM if host is running and incorporate with IPMI service that does the same
- Write custom IBM service that looks at SCOM registers and logs appropriate errors per design doc

15 story points seems reasonable for the above work.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@geissonator , can this Epic be closed?  There is more R/R work tracked under Epic #905 and Epic #1072.  Or are there some stories that need to be created.

**Comment by geissonator** [comment]
Stories created and points from this epic moved into them.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Everything is now in
