### ISSUE TITLE
Support multiple eSEL sensors calling out the same FRU

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#77]
On Witherspoon, hostboot can call out the motherboard with the motherboard_fault sensor (which we support), but also the todclock sensor, pcieclock sensor, refclock sensor, and apss_fault sensor.  The code is set up to just allow 1 sensor per inventory item callout, so somehow the structure in invsensor.yaml/inventory-sensor-gen.cpp needs to be changed to allow multiple ones.

At this moment the apss_fault one is the only other one hostboot has code to use, but when I asked them about it they didn't realize they could use the others so now they might start.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
