### ISSUE TITLE
eBMC State Management - IBM Manufacturing Support

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#770]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
These would be things like:
- Providing an aggregated system state to the MFG
   - This is already in place.  CFT combines Chassis + BMC + Host to give a holistic view

- Providing the BringUp Mode:
   - This is mostly things like:
      - Do not do automatic error recovery ( ie, Do not Re-IPL )
       - Do not reset BMC if some application dies.. I am hoping this can be plugged into some systemd service definition params

**Comment by vishwabmc** [comment]
@vishwabmc to close with @trajeswaran on the CFT needs

**Comment by vishwabmc** [comment]
I did speak to Rajesh and Dean and here is where it is now :

1/. CFT used `smgr mfgState` majorly. CFT already has the code support for this and hence this is [DONE]

2/. Equivalent of "smgr toolReset'.. --> This does not need a lot of change in CFT. Changes are in BMC and for which, the work has not yet been kick started.

**Comment by bradbishop** [comment]
I suspect if I think long enough I could figure it out but what is CFT?

> Equivalent of "smgr toolReset'.

This would just be ```reboot -f``` right?

**Comment by vishwabmc** [comment]
> I suspect if I think long enough I could figure it out but what is CFT?

CFT --> Converged Firmware Toolkit. A kit that abstracts the MFG commands targeting FSP / BMC and gives a unified interface to MFG not caring BMC / FSP

> 
> > Equivalent of "smgr toolReset'.
> 
> This would just be `reboot -f` right?

So with toolReset, we had the power off done abruptly. I need to see if that can be achieved so.
But a good pointer. I will give it a try

```
       -f, --force
           Force immediate halt, power-off, or reboot. When specified once, this results in an immediate but
           clean shutdown by the system manager. When specified twice, this results in an immediate shutdown
           without contacting the system manager. See the description of --force in systemctl(1) for more
           details.
```

**Comment by vishwabmc** [comment]
@bradbishop I tried this 

```
root@witherspoon:~# obmcutil state
CurrentBMCState     : xyz.openbmc_project.State.BMC.BMCState.Ready
CurrentPowerState   : xyz.openbmc_project.State.Chassis.PowerState.On
CurrentHostState    : xyz.openbmc_project.State.Host.HostState.Off
BootProgress        : xyz.openbmc_project.State.Boot.Progress.ProgressStages.OSStart
OperatingSystemState: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.BootComplete

root@witherspoon:~# systemctl poweroff --force --force
Powering off.
Write failed: Broken pipe
vishwa@vishwa:/home/OpenBmc/phosphor-gpio-monitor$ ssh root@wsbmc006
 
root@wsbmc006:~# obmcutil state
CurrentBMCState     : xyz.openbmc_project.State.BMC.BMCState.Ready
CurrentPowerState   : xyz.openbmc_project.State.Chassis.PowerState.On
CurrentHostState    : xyz.openbmc_project.State.Host.HostState.Running
BootProgress        : xyz.openbmc_project.State.Boot.Progress.ProgressStages.Unspecified
OperatingSystemState: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.Inactive
root@wsbmc006:~# 
```
So, this does not seem to do what I want. ( unless I missed something ).

**Comment by vishwabmc** [comment]
Need to have a discussion with @derekhoward55 and team on taking this forward.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
All stories complete, closing.
