### ISSUE TITLE
eBMC State Management - Istep Support

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#773]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
In Enterprise box, this is how it's done:
---> ECMD --> Maintains a table with list of isteps mapping to what needs to be done on that
 - When it gets a request, ECMD would go look up in the table and would take appropriate action,
      - For certain commands, it would directly invoke an API from the IPL services from HWSV component.
         - HWSV then will see what kind of command it is: For the commands that are to be run by the Host Boot, it would send up. 
          - For the commands that are to be run on the Service Processor, it would run locally. 
     - For certain commmands, ECMD would directly invoke the API posted by ATTN
     - For some other commands, it would invoke a TF ( Transition File ) and that TF is essentially, a set of commands and APIs to get executed

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
In the conversation that I had with @ojayanth last week, they are in agreement that ISTEP won't need any State Managerment support.. @dhruvibm has the action to come-up with the ISTEP proposal.. 

I believe, as a State Manager, we may have to handle the contentions between a user asking to do a full power-on vs someone doing an istep behind the scene. Some sort of pre check -or- checking some target etc...

Also, we need to see if State Management should take recovery actions if the istep results in a failure leading to termination. My thinking is that we stay whereever we endup in and do not take recovery actions if it's a istep

**Comment by geissonator** [comment]
No work needed here for state manager
