### ISSUE TITLE
Rainier Power Host Interface - HW pon

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#774]
PHYP interfaces – support PLDM cmds for:

QSX replacement - OEM GetAlertStatus PLDM cmd to report unit addresses of system, alert status and flags, and config ID.  Alert status and flags defaulted to typical values, full support for alert interface will be later.  config ID from mapping of property "IM" under the "com.ibm.ipzvpd.vsys" (names could change) on the "/xyz/openbmc_project/inventory/system" D-Bus object in the inventory.

PVD mod 3 replacement - report enclosure UTMS in GetFRURecordTable PLDM cmd.  Done elsewhere via pldm/pdr.  Eg https://github.com/ibm-openbmc/dev/issues/793,  https://github.com/ibm-openbmc/dev/issues/1450.

PVD mod 1 replacement - actual FRU vpd and frame vpd (in PLDM format) with GetFRURecordTable if possible to allow the Host to continue to power on.  FRU vpd done elsewhere with via pldm/pdr.

No  alerts/epows/leds supported yet.  Support unit address. Ongoing meetings discussing what function is needed.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@derekhoward55 @dkodihal , I think this is supposed to be owned by Deepak's team.  Let me know if you disagree.  Assigning to Deepak.......please note that this is needed for Chassis Bringup.

**Comment by derekhoward55** [comment]
I think it should probably be in my name, we get help from Deepak, but I'm on the hook for figuring out the data etc.  But Deepak if you think it should be in your name feel free to assign back to yourself!

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
