### ISSUE TITLE
Rainier Fan control - HW pon

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#775]
Leave in the dead zone and the proportional step down based on how far above/below the trip point we are like the current BMC algorithm or whatever else previous system has in place.  

Use same MAX31785 fan controller, just set all fans to high speed (or really high floor) and leave there.  

Update existing yaml/json for Rainier-specific info – number of fans, zones, a temporary safe floor, etc.  

Read speeds and log errors for failing fans using available error logging infrastructure. 

No temp sensor reads supported yet.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
