### ISSUE TITLE
PHAL: DUMP: MPIPL and System Dump  Enablement.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#777]
This epic is used to track the BMC side changes related to enable [platform system dump ](https://www.ibm.com/support/knowledgecenter/en/9119-MHE/p8ect/pxect_platform_dump.htm).

Scope: User Dump initiation and dump extraction on Bringup system

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
This epic is used to enable system dump in simulation environment.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dhruvibm** [comment]
MPIPL/System dump is enabled
