### ISSUE TITLE
Rainier: Add RTC battery voltage sensor

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#78]

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Will move to Swift.  Never got a hard enough requirement for witherspoon, and I want to make sure we have the upper/lower thresholds right.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
@spinler Why is this a requirement ?. At-least from the Enterprise systems, we did not have anything that represented this. We had the battery test tho.

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
@vishwabmc Pretty much every other OpenBMC system I've ever seen has this.  Our enterprise systems didn't even have a concept of things like temp/voltage sensors on any UIs.

**Comment by vishwabmc** [comment]
> @vishwabmc Pretty much every other OpenBMC system I've ever seen has this. Our enterprise systems didn't even have a concept of things like temp/voltage sensors on any UIs.

@spinler Is this something that can be hooked into hwmon ?. What support from the battery do we have to read the temp ?

**Comment by spinler** [comment]
Yep, we put it in the device tree, so we have:
```
cat /sys/class/hwmon/hwmon10/name
iio_hwmon_battery
```
all that's left is to put in the hwmon config file with the appropriate name and thresholds.

**Comment by mine260309** [comment]
Be noted that it likely needs to configure a GPIO for this sensor, so that hwmon will toggle the GPIO before reading the RTC voltage, and toggle back after reading. Otherwise, RTC battery will be drained quickly.

**Comment by mdmillerii** [comment]
I understand that the test circuit will drain the battery.  Might need to limit the polling vs regular sensors?

**Comment by spinler** [comment]
Yea.  The interval is configurable and would be set to a day, and we already have support in phosphor-hwmon to do what it calls gpio unlocking before the read and locking after.

But, it's a moot point anyway.

**Comment by spinler** [comment]
Reopening to track for rainier

**Comment by spinler** [comment]
This is complete.
