### ISSUE TITLE
Hostboot TI handling

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#780]
- Need more discussion on this in the Attn handling Application. 
- Like handling special reason codes from BMC , like PNOR reset incase of PNOR failure.
- Other than re-configure loop request in the TI path, BMC should handle all the special reason codes from Host.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@ojayanth @zane131 Can either of you comment on this.  Are the details of this issue worked out yet?  Jayanth or Zane, is there any eBMC work in Attention Handling for this?

**Comment by zane131** [comment]
@ojayanth This is covered in RTC 212847. Let me know if you have any questions.

**Comment by ojayanth** [comment]
Duplicate issue , closing.
