### ISSUE TITLE
Asset protection

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#781]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Provide infrastructure  to validate system CCINs  like  Backplane, OpPanel, Processor things is a "legal combination".

**Comment by ojayanth** [comment]
As per new plan , not required this.
