### ISSUE TITLE
HMC-BMC Discovery

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#782]
-> Need to define the discovery data.
-> How can we dynamically add the service data
-> System should always come with unique hostname so that avahi discovery time will be less
-> Work with HMC team to incorporate the avahi data.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
closing it as it is completed.
