### ISSUE TITLE
HMC-BMC Session Management

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#783]
-> Create HMC session
-> More than two HMC should not be connected
-> Work with HMC team to get the system capabilities
            Need to give the redfish URL for the system capabilities
->  Connection timeout/drop scenarios
       During cleanup of session object related to HMC, Need to clean the associated manager object.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by mzipse** [comment]
@ratagupt , Can this be closed now?  I suspect so.  And I believe the parent Stage 2 Epic can also now be closed.  Please take a look.
