### ISSUE TITLE
HMC-BMC Know your Client

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#784]
-> HMC has a requirement that BMC should identify the HMC for the following use cases
     1.    HMC requires that BMC should notify other HMC which is connected if there is any change in save area files (CRUD operations)
     2.    HMC requires that only HMC as a management client should be allowed to configure the certificates required by VMI partition
     3.    HMC requires to send notifications to other HMC connected to the BMC. For these events, the BMC will act as a pass through/proxy
-> Design the workflow for the BMC to identify the HMC.
-> Create a new manager object by the HMC once HMC gets connected.
-> Put a restriction on how many HMC manager objects can be created by the HMC.
->  Define the policy for the same.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
This contains all stories related for the API for HMC Config, Connectivity

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by nicoleconser** [comment]
Unclear if this is related to **HMC Monitoring / Surveillance Enablement**. https://ibm-systems-power.slack.com/archives/GQ8H06RC5/p1591045878003100

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Nicole this is not for HMC monitoring..HMC has the requirement to know the connected client info so that HMC can restrict the number of HMC.

BMC will provide all the session details, HMC will get those session details and take a decision depends on whether the session belongs to HMC or not.

BMC has all the infrastructure, where admin can create HMC user and then HMC connect to the BMC through HMC user.
Closing this epic.
