### ISSUE TITLE
HMC-BMC PassThrough Events

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#785]
Need to define the redfish interface for the passthrough events.
This is a unique requirement that event is there with HMC and they want that BMC should notify other connected HMC.
Implement the Interface for the same.
No need to persist the pass-through event.

**Comment by ratagupt** [comment]
This issue is dependent on the Redfish Event notification.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
It is done, hence closing this issue
