### ISSUE TITLE
HMC-BMC Save-Area management

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#787]
-> Define the redfish interface for the Save area.
-> Implement the interface supporting (CRUD) operation.
-> Notify other HMC for the updates in the save area file.
-> Persist the save area file on the BMC.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by mzipse** [comment]
Just running a test of our reports.  Please ignor my changes.....I will change back.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Closing this epic as all the issues have been closed.
