### ISSUE TITLE
HMC-BMC FirmwareUpdate

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#790]
This issue addresses that all code update scenarios from HMC works well with epic 654.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by ratagupt** [comment]
HMC can consume the Redfish interface, nothing left on the BMC side, Hence closing the issue.
