### ISSUE TITLE
Redfish: Code Update - Support multiple software images for a single target 

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#794]
https://github.com/DMTF/Redfish/issues/3357 (need DMTF access) was opened to request support for our OpenBMC priority concept. Where you can associate multiple software images with a single target.

After some discussion within the DMTF, https://github.com/DMTF/Redfish/commit/e27681b47b53bb12d51f73b241f2901b1055c6ef was created which will create new o_data.id fields in the firmware inventory:

The user will then be able to use the "ActiveSoftwareImage" in the Settings object to chose what image they want active during the next activation window (i.e. bmc or host reboot).

The information will be available to the broader community once officially approved as a part of the DMTF process.

**Comment by geissonator** [comment]
Could be broken into 2 stories. 
- Support reporting the current firmware images in the new firmware inventory fields
- Support the modification in Settings and handling on a reboot of BMC or Host

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
New SoftwareImages and ActiveSoftwareImage properties are available:

https://redfish.dmtf.org/schemas/v1/Bios.v1_1_0.json
https://redfish.dmtf.org/schemas/v1/Manager.v1_6_0.json

**Comment by anoo1** [comment]
I haven't done much bmcweb development but from what I understand I'd say we can first implement this for single-version systems, by populating the new Links fields with the running version of the system:

```        
"ActiveSoftwareImage": {
             "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/abcd1234"
         },
         "SoftwareImages": [
             {
               "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/abcd1234
             }
         ],
```

The bmcweb that populates the other Links fields is this one, so this may be the place where these 2 new Links fields can be populated - https://github.com/openbmc/bmcweb/blob/e9a14131650d30389eaf9dc38a3c32f1cb552f52/redfish-core/lib/managers.hpp#L1564

**Comment by slylinux** [comment]
what we should do is just to list the "Software Images" and "Active Software Image"? for single image system, you mean we do not need to store another image on flash?

**Comment by anoo1** [comment]
> what we should do is just to list the "Software Images" and "Active Software Image"? for single image system, you mean we do not need to store another image on flash?

In summary yes:
"Software Images": Loop through the FirmwareInventory and add the BMC images. For single image system, only one will be found and added.
"Active Software Image": @geissonator is this the image that's currently running or the one the system will boot from on the next BMC reboot? On single image system this will be the same image that the system is running on.

**Comment by geissonator** [comment]
When it comes to the BIOS, there is a Redfish.Settings concept for BIOS attributes. This work is being done under https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/29670. When that is in, we'll actually use redfish/v1/Systems/system/Bios/Settings to indicate what ActiveSoftwareImage in situations where the host is up and running. If the host is not running then we just directly update ActiveSoftwareImage under redfish/v1/Systems/system/Bios/. Initially we can just create the new properties under the "Links" in https://redfish.dmtf.org/schemas/v1/Bios.v1_1_0.json

With the BMC, it's not as clear to me there. I don't believe the BMC has this concept of current value, and value it should be after next activation window.

So yeah, for the BMC, it appears ActiveSoftwareImage should be what we want it to be when we next do a firmware activation for the BMC (based on HttpPushUriApplyTime)

FirmwareVersion under the BMC object will continue to be the currently running firmware on the BMC.

**Comment by gtmills** [comment]
First commit was https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/34960

**Comment by gtmills** [comment]
3 commits that have been merged for some time: 
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/34960 GET "ActiveSoftwareImage"
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/35934 GET "SoftwareImages"
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/35226 Manager: Support for switching running image i.e. Manager PATCH "ActiveSoftwareImage"

I did not add support for switching the Host Software Image, i.e. Bios PATCH "ActiveSoftwareImage", because this is not used on eBMC, only Witherspoon.

**Comment by gtmills** [comment]
Done. https://github.com/ibm-openbmc/dev/issues/2485 could add additional support for systems like Witherspoon.
