### ISSUE TITLE
Implement encode/decode APIs for NewFileAvailable

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#795]
Please refer #998 and https://ibm.ent.box.com/file/392172076032.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/24630

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/24630 merged
