### ISSUE TITLE
Implement encode/decode API for ReadFileByTypeIntoMemory

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#796]
Please refer #998 and https://ibm.ent.box.com/file/392172076032.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/24181/
