### ISSUE TITLE
Implement encode/decode APIs for WriteFileByTypeFromMemory

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#797]
Please refer https://github.com/ibm-openbmc/dev/issues/998 and https://ibm.ent.box.com/file/392172076032.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/24179

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/24179 merged
