### ISSUE TITLE
phosphor-rest-server : authorize requests against LDAP group permissions.

### ISSUE THREAD

**Issue by tomjoseph83** [ibm-openbmc/dev#8]
The plan is to authorize the REST operation based on the permission assigned for the session. If the session has the Read permission  restrict PUT,POST operation, else if the session has Read/Write operation allow all REST operations.

python passwd library will be used to figure the group name associated with the LDAP user. The group name will be looked up in the /xyz/openbmc_project/user/ldap/<group_name> to figure out the privilege.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by tomjoseph83** [comment]
This is implemented with redfish and no support is planned for phosphor-rest-server.
