### ISSUE TITLE
BMC Dump: Add support for Termination

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#80]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ojayanth](https://github.com/ojayanth)**
_Tuesday Apr 25, 2017 at 12:27 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/1511_

----

- Need to interlock with SBE/Hostboot/OPAL team on defining contents.
- Identify the dump contents and  add support required Bash commands]
- Enable termination dump support in Dump Service

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Only State management chnages required all dump related work is tracked in the Host dump storeis

**Comment by geissonator** [comment]
This tracks state management / systemd infrastructure to run these different dump scenarios.

**Comment by geissonator** [comment]
https://gerrit.openbmc-project.xyz/q/topic:%22diag-refactor%22+(status:open%20OR%20status:merged) is the code to support this.

**Comment by geissonator** [comment]
All code merged
