### ISSUE TITLE
Design framework for PLDM BIOS tables

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#800]
Design common framework to enable creation of and access to the BIOS tables.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by tomjoseph83** [comment]
We are trying to capture here the framework for the PLDM BIOS tables.

BIOS is the owner of the BIOS attributes that get used by the system.The MC maintains a cached copy of the attributes. The BIOS commands is used to exchange bios attribute and its values between MC and BIOS. The BIOS attribute types are like BIOSEnumeration, BIOSString, BIOSPassword, BIOSInteger, etc.

To enable platform specific boot attributes and setup the bios tables, the bios attribute information can be captured in the JSON files.

- [ ] Separate JSON per attribute type
- [ ] Attribute Name, Type specific Possible Values, Type specific Default Values
- [ ] Parse the JSON and create BIOS tables using C++ data structure
- [ ] Set up the BIOS Tables - BIOSStringTable, BIOSAttributeTable,BIOSAttributeValueTable
- [ ] The integrity checksum of the BIOS Tables are used as the table tags

The following BIOS specification commands needs to implemented for the exchange of the BIOS Tables.

- [ ] GetBIOSTable
- [ ] SetBIOSTable
- [ ] SetBIOSAttributeCurrentValue
- [ ] GetBIOSAttributeCurrentValueByHandle
- [ ] GetBIOSTableTags
- [ ] SetBIOSTableTags

The BIOS parameters are mapped to D-Bus objects in the JSON files. A C++ map with the attribute handle as key is mapped to a getter and setter function for the bios attribute.

- [ ] Create getter function which maps the D-Bus property value to BIOS attribute type
- [ ] Create setter function which maps the BIOS attribute type to D-Bus property value

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Closing based on task breakdown above.
