### ISSUE TITLE
Define PLDM BIOS attribute for boot "side"

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#801]
BIOS attribute would indicate whether the BMC booted from the primary or alternate side.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Per review with Tom, this work is complete.  Closing.
