### ISSUE TITLE
Define PLDM sensor to denote BMC's operational state

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#809]

**Comment by dkodihal** [comment]
- [ ] libpldm encode/decode for GetStateSensorReadings
- [ ] Implementation of State Sensor PDR
- [ ] JSON entry for PDR for BMC's functional state : entity id is 137, state set can be Availability (2).
- [ ] D-Bus mapping to https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/State/BMC.interface.yaml, property BMCState
- [ ] libpldmresponder implementation for GetStateSensorReadings
- [ ] Routing to D-Bus object for BMC functional state
- [ ] Investigate PLDM timeout w.r.t to this command
- [ ] Unit Tests

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by sampmisr** [comment]
GetStateSensorReading is implemented. Need to check the rest portions

**Comment by nmuruli** [comment]
Not going to need this anymore
