### ISSUE TITLE
BMC Dump: Add support for Kernel Panic Dump data collection

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#81]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ojayanth](https://github.com/ojayanth)**
_Tuesday Apr 25, 2017 at 12:27 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/1512_

----

- Need to interlock with Linux Kernel team on requirements, and provide mechanism to enable this support in existing dump infrastructure.
  - Enable this support in Dump Service

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Need to check with Kernel team  about the details of mini kdump data availability to be packaged as part of dump.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
#1058 is used to track kdump support.
