### ISSUE TITLE
CEC LED :Define PLDM sensor to read the system attention LED

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#810]

**Comment by dkodihal** [comment]
- [ ] JSON entry for PDR for system attention LED : entity id has to be OEM, state set can be Identify State (17).
- [ ] D-Bus mapping in PDR JSON and routing to D-Bus. Can be left out now. Might need to open a tracking issue.
-[ ] Unit Tests

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
