### ISSUE TITLE
Implement platform specific handling for PLDM BIOS tables

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#812]
Implement common framework to enable creation of and access to the BIOS tables.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
- [ ] JSON for platform specific BIOS information - cover all BIOS types
- [ ] libpldmresponder : code to perform D-Bus look-ups based on JSON

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by tomjoseph83** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/22823/6

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/22823 merged
