### ISSUE TITLE
Dump: System Dump extraction

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#814]
Extract the system dump from Host memory and transfer to External entities.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Rescope: Provide a command line mechanism to extract dump for lab debug.

**Comment by ojayanth** [comment]
Not required
