### ISSUE TITLE
Qemu: Model AST2600 SMP

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#816]
The ast2600 has two CPUs. The second CPU is placed in a wait for interrupt state by u-boot, and the kernel resumes execution in SMP mode.

This requires a stub to be implemented in qemu, similar to the raspi model. See https://github.com/qemu/qemu/blob/v4.0.0/hw/arm/raspi.c#L40

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by shenki** [comment]
I have this working now if we boot with u-boot:

```
qemu-system-arm -M ast2600-evb -drive file=/test.img,format=raw,if=mtd -serial mon:stdio -d guest_errors,cpu_reset -nographic  -s -no-reboot  -m 1G -net nic -net user,tftp=/srv/tftp -smp 2
```

The next step is to add a rom to the qemu model so we can boot both CPUs without running u-boot first.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
