### ISSUE TITLE
Qemu: AST2600 SCU

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#817]
The ast2600 has a very different SCU layout than previous SoCs. It must be modeled before u-boot can boot in qemu.

This requires abstracting out the common code in hw/misc/aspeed_scu.c and creating a new model for the 2600 register layout. This issue can be closed once u-boot is able to load Linux.

**Comment by shenki** [comment]
I have started to work on this. It is more work that initially expected.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by shenki** [comment]
I have a working patch that has been included in @legoater's aspeed-4.1 branch. It needs rework before it can be upstreamed.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
