### ISSUE TITLE
Qemu: AST2600 SDMC

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#818]
Model the ast2600 SDRAM memory controller such that it can run the ast2600 SDRAM training code in u-boot.

**Comment by shenki** [comment]
I have begun work on this.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by shenki** [comment]
I have a working patch that has been included in @legoater's aspeed-4.1 branch.

**Comment by rfrandse** [comment]
tracking in jira
