### ISSUE TITLE
Qemu: Model SD/MMC device

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#820]
This should model the SD/MMC controller in the BMC so we can use it as a block device for the Linux kernel.

It should be modeled as part of the ast2500 SOC, and added to the swift machine.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by shenki** [comment]
@eddiejames has posted a first cut of this. It needs review and upstreaming.
