### ISSUE TITLE
Qemu: Update timer model for ast2600

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#821]
Ensure u-boot and Linux can run on the ast2600 machine in qemu.

**Comment by shenki** [comment]
A first pass has been completed and committed to Cedric's aspeed-4.1 branch. It is able to run aspeed's u-boot branch `aspeed-master-v2017.01`.

The next step is to send this change upstream.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
