### ISSUE TITLE
GUARD design

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#822]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Issue is used to track GARD  Design document and d-bus interfaces

**Comment by amboar** [comment]
What are the requirements? Why does GARD management need a DBus interface?

**Comment by dhruvibm** [comment]
Uploaded the design document, Dbus interfaces need to be pushed.

**Comment by dhruvibm** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/27804 - Design

**Comment by ojayanth** [comment]
@dhruvibm need to include  guard library API's information in the design document.

**Comment by ojayanth** [comment]
d-bus interface support is tracked  separate issue. This covers only high level design

**Comment by ojayanth** [comment]
As per new plan the scope this document is changed  redfish support.  Guard redfish enablement is tracked  https://github.com/ibm-openbmc/dev/issues/1936 .
Updating milestone.,

**Comment by RameshIyyar** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/27804 - merged
