### ISSUE TITLE
Qemu: Model FSI master

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#823]
Model the FSI master so we can exercise the kernel driver and userspace code in Qemu.

This may involve creating a model of the master, and then a qemu bus type that we can attach further models that simulate devices that the BMC talks to, eg OCC, SBE, SBEFIFO.

The goal is to enable testing of the kernel driver.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
