### ISSUE TITLE
Linux: mdio driver

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#824]
The ast2600 moves the MDIO registers out of the ehternet mac (ftgmac100), allowing the sharing of one MDIO bus between the four MAC devices in the system.

We require a MDIO driver to control this bus, and modifications to ftgmac100 to use this new driver via device tree bindings. 

The register layout is compatible with the "new" MDIO device in the ast2500. Therefore most of the work can be completed on an ast2500 evb or qemu.

**Comment by shenki** [comment]
I have a prototype of the mdio driver. The device tree probing in the ftgmac100 driver needs to be debugged before it can be tested on an ast500 evb.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@shenki , can we consider this complete now?  Or do we still have to upstream this?  I assume we have code in a driver.

**Comment by shenki** [comment]
This was upstreamed in v5.3 https://github.com/torvalds/linux/commit/f160e99462c68ab5b9e2b9097a4867459730b49a
