### ISSUE TITLE
Linux: AST2600 pinmux

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#825]
This is blocked on an updated datasheet from aspeed.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by shenki** [comment]
@amboar has a working patch set. Aspeed has tested it on hardware.

**Comment by amboar** [comment]
I've unbroken upstream pinctrl/devel, should be able to send the 2600 pinmux series shortly (it depended on the patches that broke upstream).

**Comment by amboar** [comment]
http://patchwork.ozlabs.org/project/linux-aspeed/list/?series=118889

**Comment by mzipse** [comment]
@amboar , can this story be closed now?

**Comment by shenki** [comment]
This is merged upstream and in dev-5.3
