### ISSUE TITLE
Linux: SD/MMC driver

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#826]
The driver that was posted to the openbmc list works on the ast2500 evb (verified by Joel). It needs to be cleaned up before it can be merged into the openbmc tree.

https://patchwork.ozlabs.org/project/openbmc/list/?series=103018

Doing this work requires a system with a SD/MMC device attached. Candidates are evaluation boards or Swift BMC cards.

**Comment by shenki** [comment]
This is required for Swift.

See also https://github.com/ibm-openbmc/dev/issues/820 which tracks the modelling of this device in Qemu, and #827 which tracks the u-boot equivalent.

**Comment by geissonator** [comment]
oops, I had created a bunch of epics and stories a while ago to track this work (i.e. https://github.com/ibm-openbmc/dev/issues/524).  https://github.com/ibm-openbmc/dev/issues/519 was the top level epic and I had broken it down into sub-epics and stories based on required for bringup, critical, and security related. I can just close the one's I created that are redundant since you've got more detail and break down in these new one's.

**Comment by rfrandse** [comment]
refresh

**Comment by shenki** [comment]
I was able to verify that we could see the MMC device under Linux:

```
[    2.821044] mmc0: SDHCI controller on 1e740200.sdhci_slot1 [1e740200.sdhci_slot1] using ADMA
[    2.995237] mmc0: new high speed MMC card at address 0001
[    3.004909] mmcblk0: mmc0:0001 R1J56L 13.8 GiB 
[    3.010107] mmcblk0boot0: mmc0:0001 R1J56L partition 1 16.0 MiB
[    3.016582] mmcblk0boot1: mmc0:0001 R1J56L partition 2 16.0 MiB
[    3.024159] mmcblk0rpmb: mmc0:0001 R1J56L partition 3 128 KiB, chardev (248:0)
```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by shenki** [comment]
@amboar is reworking the driver in order to upstream it.

**Comment by amboar** [comment]
I've sent several series upstream to add support for MMC:

clk fix: http://patchwork.ozlabs.org/project/linux-aspeed/list/?series=118793
driver: http://patchwork.ozlabs.org/project/linux-aspeed/list/?series=118805
config: http://patchwork.ozlabs.org/project/linux-aspeed/list/?series=118795
dts: http://patchwork.ozlabs.org/project/linux-aspeed/list/?series=118797

Need to do a v2 of probably everything except clk so far.

**Comment by shenki** [comment]
This has been merged upstream and enabled in Tacoma.
