### ISSUE TITLE
u-boot: SD/MMC driver

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#827]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by eddiejames** [comment]
Working on this today; I had real trouble configuring u-boot correctly for an additional SDHCI driver. I started testing and also had trouble even getting into the u-boot prompt as I'm used to booting into a kernel directly.

**Comment by eddiejames** [comment]
Booted from sd card:

ast# mmc read 90000000 0 10000

MMC read: dev # 0, block # 0, count 65536 ... 65536 blocks read: OK
ast# bootm 90080000
## Loading kernel from FIT Image at 90080000 ...
   Using 'conf@aspeed-bmc-opp-romulus.dtb' configuration
   Trying 'kernel@1' kernel subimage
     Description:  Linux kernel
     Type:         Kernel Image
     Compression:  uncompressed
     Data Start:   0x90080128
     Data Size:    2876096 Bytes = 2.7 MiB
     Architecture: ARM
     OS:           Linux
     Load Address: 0x80001000
     Entry Point:  0x80001000
     Hash algo:    sha256
     Hash value:   77a2a5ebfb27253d8e516bb58258a7c947c73699bf0c07b21ae5c8c7c0d37175
   Verifying Hash Integrity ... sha256+ OK
## Loading ramdisk from FIT Image at 90080000 ...
   Using 'conf@aspeed-bmc-opp-romulus.dtb' configuration
   Trying 'ramdisk@1' ramdisk subimage
     Description:  obmc-phosphor-initramfs
     Type:         RAMDisk Image
     Compression:  lzma compressed
     Data Start:   0x90346d08
     Data Size:    1530561 Bytes = 1.5 MiB
     Architecture: ARM
     OS:           Linux
     Load Address: unavailable
     Entry Point:  unavailable
     Hash algo:    sha256
     Hash value:   55b6121b7c9a5b08e8b9f0290de5f65deaac0a1f1e515f3273550d01f0ade5d7
   Verifying Hash Integrity ... sha256+ OK
## Loading fdt from FIT Image at 90080000 ...
   Using 'conf@aspeed-bmc-opp-romulus.dtb' configuration
   Trying 'fdt@aspeed-bmc-opp-romulus.dtb' fdt subimage
     Description:  Flattened Device Tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x9033e500
     Data Size:    34619 Bytes = 33.8 KiB
     Architecture: ARM
     Hash algo:    sha256
     Hash value:   347e405f8c40aa5876022284d82551312a1c68952e5be0d6cfcd5972a9f9c5f4
   Verifying Hash Integrity ... sha256+ OK
   Booting using the fdt blob at 0x9033e500
   Loading Kernel Image ... OK
   Loading Ramdisk to 9ea16000, end 9eb8bac1 ... OK
   Loading Device Tree to 9ea0a000, end 9ea1573a ... OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.1.16-2caf12c-dirty-db5b216 (oe-user@oe-host) (gcc version 9.1.0 (GCC)) #1 Thu Jul 11 14:50:08 UTC 2019

**Comment by eddiejames** [comment]
This was accepted in upstream u-boot

**Comment by OguzhanCaglar** [comment]
Hi, I want to ask something. How can i boot the ast2500 from SD-Card? And how can i generate image that compatible with sd-card?
