### ISSUE TITLE
Linux: AST2600 FSI master driver

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#828]
A driver must be developed for the ast2600 FSI master.

A prototype was developed by @shenki against the FPGA implementation. This must be completed with the latest register layout, dma support, and clock/reset handling.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Closing this issue.  Work is complete.
