### ISSUE TITLE
Linux: AST2600 timer driver

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#829]
The ast2600 makes some minor changes to the timer device. The driver in `drivers/clocksource/timer-fttmr010.c` must be updated with these changes and tested on hardware.

@shenki has a prototype of the changes required, and has tested them on the ARM11 FPGA and Qemu. Some of the changes can be tested on the ast2500.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@amboar , can this story be closed now?

**Comment by shenki** [comment]
These changes in dev-5.3 and were submitted upstream.
