### ISSUE TITLE
GARD and error log interactions

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#830]
Will need to do things like ensure the PLID (platform log id) of an error log that causes a gard can be stored in the gard record, and make sure that an error log can't be deleted if it's PLID is in a gard record.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Platform Log ID (PLID)
Unique identifier for a single event. Note that it is possible for
multiple log entries to be made for a single error / event. The
entries are linked to the same event by using the same PLID.
The Log Entry ID (next field) is used to distinguish entries
sharing the same PLID.

**Comment by spinler** [comment]
There will be a shared library to use to look for gard records based on PLID.

**Comment by spinler** [comment]
There was a discussion today that since Redfish doesn't really support only partially deleting a collection, in this case the LogService collection, then we will not skip deleting logs that have guard records associated with them.

**Comment by spinler** [comment]
`ensure the PLID (platform log id) of an error log that causes a gard can be stored in the gard record`
- guarding will now be handled by the application that finds the error, not the logging daemon.

`make sure that an error log can't be deleted if it's PLID is in a gard record.`
- We're not doing this anymore, as described above.

Closing this story since there is nothing left here
