### ISSUE TITLE
Linux: Rebase on 5.2

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#831]
When the 5.2 kernel is released an updated openbmc tree will be released based on it.

**Comment by shenki** [comment]
The 5.2 release should appear around 2019-07-14.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by shenki** [comment]
Initial work done. Blocked on https://github.com/systemd/systemd/issues/12784

**Comment by shenki** [comment]
Tree has been pushed to openbmc/linux. 

Gerrit bump is here: https://gerrit.openbmc-project.xyz/c/openbmc/meta-aspeed/+/23344
