### ISSUE TITLE
Linux: Rebase on 5.3

### ISSUE THREAD

**Issue by shenki** [ibm-openbmc/dev#832]
When the 5.3 kernel is released an updated openbmc tree will be released based on it.

The 5.3 release should appear around 2019-09-15.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
We are beyond 5.3 now.  Closing this.
