### ISSUE TITLE
HMC-BMC Discovery-> Define the service data

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#833]
Need to work with HMC team and define the service data, Currently, avahi publishes the IP address, service, and the port.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/23484
