### ISSUE TITLE
HMC-BMC Discovery-> DBus-API to add more data Dynamically

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#835]
=> Need to identify the Avahi Dbus API which can be used to add more data Dynamically in the avahi service

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
We don't see the requirement now for adding the avahi data at runtime. so closing this issue.
