### ISSUE TITLE
HMC-BMC Discovery-> External mgmt client integration

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#836]
Efforts to sit with HMC team and help HMC team to consume avahi service data.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
This issue is to sit with HMC team to make them understand that how can they use the avahi.
=> How HMC can consume the avahi-data?
=> How HMC can use avahi-discover/avahi-browse with HMC?
HMC is able to consume the data, hence closing this issue.
