### ISSUE TITLE
HMC-BMC discovery: How to add the plugin for the additional data

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#837]
In avahi we need to figure out that how can we add the additional data 
   -> Do we need to write  a plugin?
   -> Does Avahi provides the D-bus api for the same?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
This was the kind of evaluation story, we did the following stuff
=> Evaluate the avahi source code for adding additional data
=> Evaluate avahi-publish utility which is used to publish the data at runtime
=> Avahi doesn't provide the D-bus API for publishing the data at runtime.
=> We enhanced the existing infrastructure through which additional data can be added at configuration time.
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/22950
