### ISSUE TITLE
HMC-BMC Session: More than 2 HMC should not be connected.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#838]
Implement the condition to make sure that more than two HMC should not be connected.
Connect two HMC and try to connect third HMC, it should fail
However other client can be connected even there is already two HMC.

This story would be dependent on the KYC epic.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
In the recent workshop we identified that this restriction would be done by the HMC.
BMC will provide the way through which HMC knows that the connected client is HMC.
Lower priority for now.

**Comment by mzipse** [comment]
refresh

**Comment by ratagupt** [comment]
closing this story as restriction would be done by the HMC.
