### ISSUE TITLE
HMC-BMC Session: Session/Timeout scenarios

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#839]
Need to define the behavior in case of session timeout.
    Eg: Do we need to delete the manager(HMC) object?
        : How to link the session with the Manager object etc?

What about if HMC detects a surveillance failure?
        Currently assuming it would be a no-op and session would be time out.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Internal doc having all the details so closing this.
