### ISSUE TITLE
IPMI : Implement user management commands

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#84]
<a href="https://github.com/williamspatrick"><img src="https://avatars0.githubusercontent.com/u/105009?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [williamspatrick](https://github.com/williamspatrick)**
_Thursday Jun 30, 2016 at 15:33 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/446_

----

**Comment by rfrandse** [comment]
<a href="https://github.com/agangidi53"><img src="https://avatars1.githubusercontent.com/u/14833059?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [agangidi53](https://github.com/agangidi53)**
_Monday Jul 18, 2016 at 21:46 GMT_

----

Are the use management commands referenced here managed via ipmitool ?

@anoo1  some time back indicated that it is inband ipmitool how we are gonna be managing the users but now since ipmi over lan implementation is being considered I want to know if that's going to be changed.

**Comment by rfrandse** [comment]
<a href="https://github.com/tomjoseph83"><img src="https://avatars3.githubusercontent.com/u/15232150?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomjoseph83](https://github.com/tomjoseph83)**
_Thursday Nov 16, 2017 at 14:28 GMT_

----

IPMI commands related to User account management:-

1) User Access Commands (3pts)
- Set/Get User Access

2) User Name Command (1pt)
- Set/Get name Command

3) Set user password command (1pt)

4) User Payload Access (1pt)
- Set/Get User Payload Access

5) Get user payload access (1pt)

6) Set channel security access (TBD, may be optional)

7) Channel Access Commands (1pt)
- Set/Get Channel Access

**Comment by rfrandse** [comment]
<a href="https://github.com/rthomaiy"><img src="https://avatars2.githubusercontent.com/u/19327744?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rthomaiy](https://github.com/rthomaiy)**
_Thursday Nov 16, 2017 at 14:43 GMT_

----

do we have plans on how ipmi will do the user management verification ? It requires clear text password. Are we plan to create a encrypted file in which the clear text password will be stored (say in phosphor-user-manager). 
i.e. d-bus calls to Phosphor-user-manager --> Create new user / change password --> has to update both /etc/shadow, groups file along with a separate encrypted file (to store user-information), from which IPMI will do the authentication ?
Do we have plan of implementation like this or a different one ? 
So other than IPMI. Can we assume other app's say webui / redfish etc. will use PAM authentication directly. 
All apps including IPMI will trigger d-bus method API calls to create / change user / password ?

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh
