### ISSUE TITLE
HMC-BMC discovery: Unicast support

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#840]
Avahi doesn't support unicast discovery However HMC uses it.
   Till now we haven't find any use case, but this issue is just to track it.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
We have discussed in the workshop as we would be defining the oem redfish property which would help in discovery the system whether its is running with PHYP/KVM.

**Comment by ratagupt** [comment]
Not a priority for now.

**Comment by ratagupt** [comment]
HMC is using the Ibm/v1 interface to find out whether they are managing the Ranier system v/s other openbmc based systems.
We will reopen another story if we get this requirement.
