### ISSUE TITLE
HMC-BMC Session: System Capabilities

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#841]
Work with HMC team to get the System Capabilities via Redfish URL.
    Need to get the system capabilities once the session has been established.

If some capabilities come where we don't have the redfish url then we would open a new story.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Till now what so ever was asked by the HMC has been identified and shared with HMC team.
It is on going activity, we close it for now, will open new one if some more requirement comes where we need to do the development work.
