### ISSUE TITLE
HMC-BMC Save Area: Define the interface

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#842]
Define the Redfish/Rest interface for the save area.
        Allow the CRUD operations on the save area file.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
closing this as it is a duplicate of https://github.com/ibm-openbmc/dev/issues/986
