### ISSUE TITLE
HMC-BMC Save Area: Backend app to manage save area

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#843]
=> List all the save area files
=> Allow add/delete/update of save area.

**Comment by ratagupt** [comment]
Still needs to analyze that do we need this app, or through bmcweb we can directly manage this.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
It was not needed so closing it,
