### ISSUE TITLE
HMC-BMC Dump: Define the proposal for the dump management

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#844]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
This story will use to propose the dump management redfish interface to the openBMC community.

**Comment by ratagupt** [comment]
Current Status:
I have presented twice in DMTF.
DMTF has agreed on the proposed schema
Next Action Item is to create a pull request so that it can be pulled in the schema

**Comment by ratagupt** [comment]
Status:
   Proposal has been merged in DMTF private repo, hence closing it.
