### ISSUE TITLE
HMC-BMC Dump: Implement Redfish Delete/clearall action.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#846]
-  Get the ID from the LogEntry and fire the Dbus delete request on the DUMP.

To Implement Delete all of an specific type of dump requires the following.
-> Find out the Log service type
-> Delete only those dumps whose type matches with the log service type.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by raviteja-b** [comment]
https://github.com/openbmc/bmcweb/commit/013487e5d56e4e7964e85a38d6c3044f081a753b
