### ISSUE TITLE
HMC-BMC Dump: Extend the Logservice Service to support the dump.

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#847]
=> Create new Log Service for the different dump types at the start up.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by raviteja-b** [comment]
https://github.com/openbmc/bmcweb/commit/c9bb6861cd1bac2e1849b09176564f01c185207c
