### ISSUE TITLE
HMC-BMC Dump: Implement dump collection through Redfish log services

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#848]
-> Query the dump manager to get all the dumps
-> Create the redfish resources under various LogServices depends on the dump type.
      eg: BMC dump would go under /redfish/v1/systems/system/logservices/<ID_BMC>/entries/
             System dump would go under /redfish/v1/systems/system/logservices/<ID_SYSTEM>/entries/.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by raviteja-b** [comment]
https://github.com/openbmc/bmcweb/commit/c9bb6861cd1bac2e1849b09176564f01c185207c
