### ISSUE TITLE
HMC-BMC: Implement the pass through event interface

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#850]
=> Send the event data to the connected HMC.
=> HMC who send the event, should not receive this event, Would confirm with HMC team once more.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Done, closing
