### ISSUE TITLE
VPD: Collect all BMC FRU VPD at BMC Standby

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#855]
The BMC needs to collect VPD for all FRUs that it has direct access to, at BMC standby. On Rainier, this includes the BMC card itself, the system backplane, the processor FRUs (for callout puposes), power supplies, fans, VRMs, JBOF cards etc. A full list will be clear once we have the final version of the system workbook/MRW.

This epic entails the following:

1. Design template created and approved in the community. Design of the VPD app finalized.
2. Implement the VPD application (skeleton)
3. Config: Determine what FRUs need VPD collected at BMC standby for Rainier.
4. Config: Determine device paths (for ex sysfs paths) to be used for each FRU.
5. Add VPD application bitbake recipe(s)
6. Update openpower vpd parser with IPZ VPD support.
7. Update openpower vpd parser with keyword format VPD.
8. Update openpower vpd parser with HMS card keyword format VPD.
9. Figure out what VPD data needs to go into the FRU inventory
10. Update the inventory with data that needs to go into it for FRUs (callout related keywords)
11. Implement collection of fan VPD
12. Implement collection of power supply VPD
13. Decide if/how we need persistency for FRU VPD
14. APIs to query specific portions of the VPD
15. APIs to update FRU VPD
16. Update expanded location codes into the inventory.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
This is now complete. More FRUs that need to be supported shall be added via JSON updates.

**Comment by rfrandse** [comment]
refresh
