### ISSUE TITLE
VPD: VPD Functions For Poweron

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#856]
This epic tracks all the VPD function needed for Rainier HW poweron:

* Data needed by PHYP over PLDM (Location Codes, and system blueprint).
* Collection of Module VPD (SPI)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
VPD is written out to D-Bus as inventory objects. The PLDM daemon picks up the FRUs it is interested in from there.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
Add to this epic:
* Update JSON with all the missing FRUs (Processor, Memory, DASD backplanes, PCIe cards)
* Figure out how to detect FRU presence and bind drivers (Talk to Brad).

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
This can now be closed. The JSON still needs to be updated completely, but that is a WIP which will be tracked under the LNF with another story.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
