### ISSUE TITLE
HMC-BMC : Analysis for how to send the event through bmcweb

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#857]
Should we use the websocket/Raw socket?
Should we close the socket after send the notification
Performnace impact?

Outcome for this story is design template and get it approved.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by trajeswaran** [comment]
AppaRao has uploaded the design document and it is in review. 
Design document : https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/24749 

The initial commit has been uploaded for review.
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/29464
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-user-manager/+/29463
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/29462

**Comment by trajeswaran** [comment]
Prototype has been implemented and demonstrated in the Scrum demo. This story can be closed.
