### ISSUE TITLE
VPD: Presence Detection and FRU VPD Recollection

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#864]
Certain FRUs can be swapped/changed at BMC standby. Certain FRUs can also be concurrently maintained. In each case, there is a need to "recollect" VPD for these FRUs.

This epic is to:
1. Figure out if we can do this via hwmon presence detection where we'd automatically detect FRUs being plugged in/out and update the VPD accordingly.
2. Or do we need to explicitly invoke a VPD recollection via the state manager/systemd units when the BMC is requested to poweron.
3. Determine if a FRU really needs to be recollected before attempting a full colection (?)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
Presence detect and VPD recollection isn't needed until later. Reassigning the milestones.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
Add to this epic:
* How do we delete Inventory objects from D-Bus? PIM does not have support?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
