### ISSUE TITLE
VPD: MRW Based Config

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#865]
This epic is to investigate and implement MRW based config generation for the VPD application(s). The configuration may include (but not limited to):

1. List of FRUs VPD is to be collected for.
2. Which records of these FRUs need to sent to the Host over PLDM.
3. Presence detect information.
4. Device path/sysfs path information for FRUs.

The initial idea is that these configuration will be hardcoded, but this epic simply aims to fetch possible configs from the MRW instead.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
I think this work is behind us.  Closing this.
