### ISSUE TITLE
VPD: Design and Implement VPD Tool

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#867]
Manufacturing and field engineers need to be able to view all FRU VPD (inventory) at BMC standby. Since the BMC does not collect all VPD at standby, this is not possible directly with the VPD application.

This epic is to design and implement a VPD tool that can read and write to any FRU VPD on the system. It should be able to present a list of installed FRUs as well as a blueprint to the user.

The tool should also provide the ability to update VPD data (another manufacturing requirement).

This entails:
1. FRU VPD write application. A daemon that will expose D-Bus interfaces to update.
2. Update the VPD inventory JSON as needed to support the write application.
3. Program a command line front-end (a CLI application or a tool) that will allow user to:
- Display FRU inventory.
- Read VPD keywords.
- Write VPD keywords.
4. Determine the output format of the tool (such as how it would display the FRU inventory). Work with manufacturing toolkit users to figure this out.
5. Create necessary bitbake recipes to get this into the image.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Per feedback from Santosh, the work is done.  A few bugs are being worked but they can be tracked with defects.
