### ISSUE TITLE
VPD: ECC Support

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/dev#868]
This epic is to implement ECC support for the IPZ VPD. More details are awaited here since the VPD ECC algorithm currently used is closed-source. Any algorithm that we do end up using, we will have to:

1. When reading VPD, validate ECC, fix VPD if needed/possible.
2. When writing VPD, also update the ECC.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by santoshpuranik** [comment]
All of this is in a driver.

**Comment by rfrandse** [comment]
refresh
