### ISSUE TITLE
eBMC State Management - Auto Power On

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#870]
Majority of this in place with PowerRestorePolicy and https://github.com/openbmc/phosphor-state-manager/blob/master/discover_system_state.cpp but there's some extra logic required for eBMC (blackout/brownout interactions with SPCN)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vishwabmc** [comment]
Closing this one .. Derek created #1860 and put the minutes from the internal discussions we have had

**Comment by geissonator** [comment]
#1860 will track POWER work, lets use this one to track SMGR.

**Comment by geissonator** [comment]
Need to match up with #1860 milestone so moving to it.

**Comment by gtmills** [comment]
@geissonator This is PowerRestorePolicy ? Redfish support is there today. The GUI can add this correct? This issue tracks work to meet enterprise requirements?

**Comment by geissonator** [comment]
Also need a way to tell Hostboot if the current boot is from a Auto PON. PHYP requires Hostboot to put this in HDAT .

**Comment by geissonator** [comment]
All changes are merged and in. Closing this issue. Adriana is working the Brownout piece separately.  See https://github.com/openbmc/docs/blob/master/designs/power-recovery.md for details on this work.
