### ISSUE TITLE
HMC-BMC IPL Parameters

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#871]
=> HMC team need to give the IPL parameter list.
=> It may happen that some IPL parameters which is not supported by any backend service, in that case we need to define the interface for the same and implement it.
=> some parameters which HMC stores it on the BMC and Phyp consumes it

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
What is pending here wrt this story:

- Redfish implementation for BIOS schema which is being done by the Intel through the following commit.
  https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/29670

- PLDM impact(Not sure if there is any impact)

@dkodihal @tomjoseph83 ^^^^ Can you confirm on the same?

**Comment by ratagupt** [comment]
With this epic, we have given the support for the following.

1/ GET on the BIOS redfish Resource - Contributed by intel (https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/29670)

2/ Extend the support for the GET through  (https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/39783/3)

3/ PATCH support for the BIOS Redfish Resource (https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/38702/16)

4) Send the Redfish Event when the BIOS attribute get updated.

5) Following BIOS attributes are supported with this epic.

1. hb_debug_console | BIOS
2.  hb_hyp_switch | BIOS
3. pvm_default_os_type | BIOS
4. pvm_fw_boot_side | BIOS
5. pvm_system_name | BIOS
6. pvm_system_power_off_policy | BIOS
7. pvm_hmc_managed | BIOS
8. pvm_inband_code_update | BIOS
9. pvm_os_boot_side | BIOS
10. pvm_pcie_error_inject | BIOS
11. pvm_rtad | BIOS
12. pvm_surveillance | BIOS
13. pvm_stop_at_standby

**Comment by sunharis** [comment]
All changes are pulled downstream
