### ISSUE TITLE
devops: CI for Swift and witherspoon-128

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#872]
Get downstream CI going for Swift and witherspoon-128. Build them and run 1 or both on real hardware and update gerrit.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Both are now building in CI and updates are put in gerrit. Just waiting on hardware so we can put one or both into hardware CI.

**Comment by geissonator** [comment]
Getting hardware is not imminent for either. For now, CI will just have to be building them (which is happening now)
