### ISSUE TITLE
eBMC State Management - CEC Termination: Initial design doc proposal

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#873]
Write up a summary of the current OpenBMC termination and recovery mechanism and propose additions required for eBMC

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/22395

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
New simpler proposal out at https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/37506/

**Comment by geissonator** [comment]
Design doc was merged
