### ISSUE TITLE
Create FSI SPI driver

### ISSUE THREAD

**Issue by eddiejames** [ibm-openbmc/dev#874]
SEEPROMs will be connected over SPI to the processor. In order to access those from the BMC, we need an SPI driver over FSI bus.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by eddiejames** [comment]
This has been accepted upstream.
