### ISSUE TITLE
Rainier Power BMC standby support - HW pon

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#875]
Get correct boxid from vpd somehow (need to write script/etc to get system config data from source file) or hardcoding to specific Rainier.  IBMi needs config ID value.

Setup right meta-ibm/meta-rainier apps to build.

Replace any functional requirements on frame resource table with replacement design. 

Collect system vpd, eg MTMS.

Enable infrastructure such as minimal error logging, tracing, termination, interrupts, event, DD, etc changes.

Investigate the substancial powr_server replacements needed for hardware power on.
Investigate direct command replacements. Support sync_ps and get_pex_ps_element_info if needed.
Investigate existing spif/panel commands.  Only need PSX replacement to get alerts to phyp (via pldm) or power/ups status to rest of BMC.

Investigate registries needed.
Investigate events needed. Some reasons for sending/receiving events still needed, likely can be implemented with DBUS.

Investigate replacements for Spif:
 - no commands needed, either no longer needed or function mentioned elsewhere.
 - determine which events needed.  EVEN_ID_POWER_PSS is unused. EVEN_ID_POWER_UPS is looked at by APOR to auto power restart if uf&bl bits clear. EVEN_ID_POWER_UPDATE_REG is looked at by cimp&smgr&menu to know system power state changed.
 - determine which registries needed. UpsFlags, PssFlags, PsxFlags are not looked at. PowerState is used a lot - smgr, hwsv, nmgr, intf, mnfg, gard, tipl, etc.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
