### ISSUE TITLE
Rainier VRM - initial design doc proposal

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#876]
Create design doc for VRM handling, document design decisions including:
- app(s) names in meta-ibm/meta-rainier/wherever appropriate
- high level code design
- JSON file naming scheme
- JSON file structure and content (elements, rules, etc)
- DD structure (what is in DD vs app vs json file)
- support for init/config and voltage updates
- JSON parser, validator

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
First draft complete and sent to squad for early review.  Planning to push to Gerrit for normal review on Wednesday afternoon.

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/24611

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/24611 merged
