### ISSUE TITLE
Rainier Power on Seq - initial design doc proposal

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#877]
Create design doc for pon and poff - document design decisions such as:
- app(s) names in meta-ibm/meta-rainier/wherever appropriate. power_up_state replacement in app, not script
- high level code design (eg interaction with systemd/dbus for proper sequence order between other apps)
- what UCD90320 init/config/enabling needed
- what pgoods/resets need to be verified
- what other init/enabling needed
- what UCD90320 DD updates needed

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
I think the Zenhub workspace tinkering changed the pipeline from Current Sprint to New Issues a while back. Changed it back to Current Sprint now that we think the workspace is working again.

**Comment by wrightjl1** [comment]
Upstream Gerrit code reviews:
pseq: Add README for configuration file directory: https://gerrit.openbmc.org/c/openbmc/phosphor-power/+/57003 (merged)
pseq: Add README for source file directory: https://gerrit.openbmc.org/c/openbmc/phosphor-power/+/57482
pseq: Add README for power sequencer directory: https://gerrit.openbmc.org/c/openbmc/phosphor-power/+/57618

**Comment by wrightjl1** [comment]
Closing issue, above Gerrit reviews have all merged.
