### ISSUE TITLE
Rainier power supply control - initial design doc

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#878]
Create design doc for ps control and monitoring - document design decisions such as:
- app(s) names in meta-ibm/meta-rainier/wherever appropriate. one app for system (for all ps)
- high level code design (limited function just to enable ps and minimal error logging)
- what if any DD changes needed
- poll rates, deglitch counts, how ensure each response is from new poll, etc
- determine how supported configs (type of ps, # of ps, input type) are specified
- init state machine after ac apply, add, download, poff/pon, etc

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/23038

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/23038 merged

**Comment by bjwyman** [comment]
https://github.com/openbmc/docs/commit/fd60b6016efd47571b93bd769da513e371aefb7e#diff-75554d60e86cef9c1079f84fda2a1003
