### ISSUE TITLE
Rainier fan control - all fans high speed

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#879]
Use same MAX31785 fan controller, just set all fans to high speed (or really high floor) and leave there.

Update existing yaml/json for Rainier-specific info – number of fans, zones, a temporary safe floor, etc.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Do we know who is the thermal lead for Rainer so I can find out what the default ceiling(aka full speed) and default floor speeds might be?

**Comment by derekhoward55** [comment]
Phil Mann.  Lets discuss when this is really needed by, thanks!

**Comment by msbarth** [comment]
Ok, I was just thinking I'd be able to really complete this issue at the same time as #1116 in the base configs.

**Comment by msbarth** [comment]
Discovered error in zone config parsing where `zone_conditions` should be optional and the parser is not fully treating it as optional. Plan to fix under this issue after all configs are verified.

**Comment by msbarth** [comment]
Also should correct the generated fan control defs file from being created within the `git` dir within bitbake and instead create it in the `build` dir of the phosphor-fan package.

**Comment by msbarth** [comment]
In getting the fan app configs created, came across an issue with the 9552 gpios for fan presence having name collisions and not showing up in the device list for inputs. Debugging what's causing these gpios to not be accessible where its believed they should be in user space for the fan presence application.

**Comment by msbarth** [comment]
Pushed the updated Rainier dts upstream -> https://lists.ozlabs.org/pipermail/openbmc/2020-February/020664.html

**Comment by msbarth** [comment]
PR -> https://github.ibm.com/openbmc/openbmc/pull/208
