### ISSUE TITLE
GUI: Update button styles to match style guide

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#880]
## Description
The implementation of the colors used in the primary and secondary buttons states is inconsistent. When looking at the style guide, there are some inconsistencies with the button visual and the pseudo styles. 

## Requirements
1. Work with designer to update style guide
1. Implement the style guide changes in the UI

**Comment by yoshiemuranaka** [comment]
@derick-montague should I refer to this file for the colors? https://ibm.ent.box.com/notes/425904576116

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
