### ISSUE TITLE
 Define the backend to store & manage VMI IP configuration on BMC

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#883]
Can we use the phosphor-settings for the same?
On the rainier system we would need to support ipV4/IPv6 address configuration, Need to design the API by considering the redfish EthernetInterafce schema as well as the Ip address schema
Need to support one IPv4 and multiple IPv6 address configuration.

Seems VMI will support the IPv4 Static Ipv4 Dhcp Ipv6 Static Ipv6 dhcp.
Ipv6 Link local may have possibility but need to discuss.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by sunharis** [comment]
Changes are pushed at https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc/+/28686/

**Comment by ratagupt** [comment]
The scope of this story has been reduced and it supports the IPv4 Static configuration.

**Comment by ratagupt** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/30205/11
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/30424/15

Closing this issue as the above commits are merged
