### ISSUE TITLE
HMC-BMC ErrorLog

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#885]
This issue is to make sure that HMC has all the interfaces to access the error log..
Implementation of error log and implemenetation of redfish/rest/odata interface will be tracked by other issue.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
refresh

**Comment by ratagupt** [comment]
Basic Logging infrastructure as well as the interfcaces are there, hence closing this issue.
Redfish lgging service supports the error logs.
