### ISSUE TITLE
HMC-BMC LED Commands

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#886]

**Comment by vishwabmc** [comment]
@ratagupt What is this Usecase ?. What are all the different LED space usecases the HMC would be interested in ?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ratagupt** [comment]
Till now they have not come up with any use case, hence closing it, will open if there is something

**Comment by ratagupt** [comment]
Few requirements from the spec are as follows:

Get System Attention LED Indicator State
Set System Attention LED Indicator State
Get FRU Identify Indicator State
Set FRU Identify Indicator State
Get Location Code List
Perform Lamp Test
Clear Inactives

**Comment by vishwabmc** [comment]
@ratagupt @gtmills 

**Get FRU Identify Indicator State**
**Set FRU Identify Indicator State**

All of this must be covered as part of https://github.com/ibm-openbmc/dev/issues/2082 . Please let me know if there is anything more.

---------------

**Get System Attention LED Indicator State**
**Set System Attention LED Indicator State**

------------------


**Perform Lamp Test**

Handled by: https://github.com/ibm-openbmc/dev/issues/2179 . Please let me know if there is anything more.

`Get Location Code List` --> This was a Custom API and I had sent an email a long ago ( about April / May 2020 ) on this topic that there won't be any custom APIs and that HMC or any Redfish client would walk all the Redfish Inventory resources and possibly create a view.

Email Subject:  Rainier :: HMC and LEDs functionality :: "13.1.5 Get Location Code List" 

---------------------
