### ISSUE TITLE
HMC-BMC Energy Scale Commands

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#887]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by marthabroyles** [comment]
@ratagupt   Please give a detail description of the commands you are looking for.

**Comment by mzipse** [comment]
@gtmills can you help answer Martha's questions.  I also asked Chris Cain to reach out to you.

**Comment by ratagupt** [comment]
@gmills: Here seems we need to find a way for the following settings.

Query Power Save Mode
Set Power Save Mode
Query Idle Power Save Mode
Set Idle Power Save Mode 
Query Dynamic Power Save Tunables
Set Dynamic Power Save Tunables

Has not finalized with HMC that they still needs this

**Comment by mzipse** [comment]
Per feedback from Chris Cain, the Dynamic Power Save Tunables settings are no longer planned for GA.

**Comment by cjcain** [comment]
These are all currently available via Redfish.

Query Power Mode: 

```
curl -s -k -X GET https://$bmc/redfish/v1/Systems/system  | grep -A4 PowerMode

  "PowerMode": "MaximumPerformance",
  "PowerMode@Redfish.AllowableValues": [
      "Static",
      "MaximumPerformance",
      "PowerSaving"
  ],
```

Set Power Mode:

`curl -k -X PATCH -d '{ "PowerMode":"PowerSaving"}' https://$bmc/redfish/v1/Systems/system
`

Query Idle Power Saver:
```
curl -s -k -X GET https://$bmc/redfish/v1/Systems/system | grep -A6 IdlePowerSaver

      "IdlePowerSaver": {
        "Enabled": false,
        "EnterDwellTimeSeconds": 240,
        "EnterUtilizationPercent": 8,
        "ExitDwellTimeSeconds": 10,
        "ExitUtilizationPercent": 12
      },
```

Enable Idle Power Save:

`curl -k -X PATCH -d '{"IdlePowerSaver":{"Enabled":true}}' https://$bmc/redfish/v1/Systems/system
`

Disable Idle Power Save:

`curl -k -X PATCH -d '{"IdlePowerSaver":{"Enabled":false}}' https://$bmc/redfish/v1/Systems/system
`

Dynamic Power Save Tunables are no longer supported.

**Comment by rfrandse** [comment]
tracking in jira
