### ISSUE TITLE
Rainier Power system type determination

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#888]
Get correct boxid from vpd for appropriate power/thermal apps.  Two different flavors of Rainier supported, 2u and 4u. 1s/2s flavors will not populate missing socket vrms, so need to support checking for proc presence in json file.  Power supply and fan config will have to be the same for 1s&2s.  This boxid determination will not be done globally, but inside each individual app that needs it, and tracked in those issues:

- IM keyword in backplane vpd will specify type of system.  Each of 2 configs will have a unique backplane (unique ccin).  There will be an IM keyword in the system VPD (backplane - record name should stay VSYS). For apps to be able to read it, look up the property "IM" under the "com.ibm.ipzvpd.vsys" (names could change) on the "/xyz/openbmc_project/inventory/system" D-Bus object in the inventory.

For general data usage from MRW, need to write script/etc to get system config data from source file, or alternately hardcode to specific Rainier.  This will not be done globally, but inside each individual app that needs it, and tracked in those issues as well. 

Define config ID (IBMi needs config ID value) based on system vpd.  Rainier = 0x30. Updated POWR config IDs doc.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
