### ISSUE TITLE
Rainier Power system/bmc init

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#892]
Review por_state behavior to enable.

- No need for cec rack address.  No global frame resource table, resource type table, config table, fru instance to unit table.  Any needed info done by appropriate app.
- G_spcn_state handled in individual apps with phosphor_state_manager state checks.
- System type based on IM keyword checked during power up - issue #928
- No need for backplane/op panel/fsp level checks yet - add if/when needed.
- SRC table replaced with PEL message registry - issue #1402
- Pointing to appropriate config data (eg ambient epow, ps, pgoods) handled in individual apps.
- Reading IPL types for appropriate reset handling - issue #1072
- PLD checks for ipl type and 12vcs standby reg fails - issue #572 
- Any fru vpd collection needed by individual apps done there.
- Any led function done by led apps.

Setup right meta-ibm/meta-rainier apps to build.

Enable infrastructure such as minimal error logging, tracing, termination, etc changes.  Infrastructure is enabled, enhancements are tracked via other issues.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
