### ISSUE TITLE
Rainier power infrastructure - registries&events

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#893]
Investigate powr registries needed and how implemented on eBMC.  eBMC provides persistency levels as needed.  All existing registries that previously existed on fsp that are needed for function in eBMC have had the info added to the appropriate issues.

Investigate powr events needed. Some reasons for sending/receiving events still needed, likely can be implemented with DBus signals:

- EVEN_ID_NEBS_STATUS_CHANGED no longer needed.
- EVEN_ID_USB_UPS_STATUS_CHANGE received when ups status bits read via usb have changed. Will be done via DBus.
- EVEN_ID_ETHERNET_UPS_STATUS_CHANGE no longer needed.
- EVEN_ID_DPSS_INT no longer needed, ucd90320 pgoods will be polled.
- EVEN_ID_CIM_OBJECT_CHANGED generated when power/thermal fru changed. Is handled via DBus.
- EVEN_ID_VRM_PHASE_FAIL_CHANGE no longer needed.
- EVEN_ID_THERMAL_LIMIT_REACHED used to notify IPMI component when epow3 timer started for ambient temp (to shut down in 15 minutes).  Determine if this is needed as part of amb temp ipmi/redfish work (https://github.com/ibm-openbmc/dev/issues/1703).

-------
Determine which spif registries needed. UpsFlags, PssFlags, PsxFlags are not looked at. PowerState is used a lot - smgr, hwsv, nmgr, intf, mnfg, gard, tipl, etc.   A DBus "state" property exists (hosted by the chassis state manager that reflects the state of the systemd target which does a chassis poweron) that can be used as the replacement for the PowerState registry .

root@witherspoon-YL30UF74T02X:~# obmcutil power
pgood = 0
state = 0

Determine which spif events needed. 

- EVEN_ID_POWER_PSS is unused. 

- EVEN_ID_POWER_UPS is looked at by APOR to auto power restart if uf&bl bits clear. The UPS bits will be stored in DBus to be looked at by the chassis state manager.

- EVEN_ID_POWER_UPDATE_REG is looked at by cimp&smgr&menu to know system power state changed. The "state" DBus property is used to determine the system power state as detailed above.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derekhoward55** [comment]
Results from investigation and plan of action documented above.
