### ISSUE TITLE
Rainier power interfaces for hw pon

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#894]
Investigate the substantial powr_server replacements to determine what is needed for hardware standby and power on. None are needed for initial hw power on.  Created https://github.com/ibm-openbmc/dev/issues/2104 to later ensure functionality has been added.

Investigate direct command replacements. Only need get_pex_ps_element_info function going forward.  This not needed for hw pon, will be combed through for needed functionality in a later story.

Investigate existing spif/panel commands. Only need PSX replacement to get alerts to phyp (via pldm) or power/ups status to rest of BMC.  Instead of blocking the power on until the PSX with pgood notification is sent, the existing obmc-power-on target can be used to hold off other apps until pgoods are active.  This is needed for hw pon but is in place already.  The rest of the power/epow information in the PSX (3 bytes) can be stored in DBUS to be populated, sent to PHYP, and read by other apps (other apps notified by DBUS signal).  Created https://github.com/ibm-openbmc/dev/issues/2488 for this piece.

Investigate replacements for Spif.  No commands needed, either no longer needed or function mentioned elsewhere.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
