### ISSUE TITLE
New IPMI Key Clear sensor for openpower systems

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#896]
The host team has requested we create a new IPMI OEM sensor for witherspoon and swift systems which can be used to indicate when the user wants certain security keys cleared from the system.

Swift IPMI files are in progress but on Witherspoon, we've determined that 0xE8 is available for a sensor ID.

Here's the work break down:
- Work with witherspoon and swift MRW owner and add this new sensor
- Create a new DBUS interface out in https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Control/TPM/
- Update the appropriate yaml to get the new DBUS object into xyz.openbmc_project.Settings
   https://github.com/openbmc/meta-phosphor/blob/master/recipes-phosphor/settings/phosphor-settings-defaults/defaults.yaml
- Update the IPMI config files to associate this new IPMI sensor with the new xyz.openbmc_project.Settings object https://github.com/openbmc/meta-ibm/blob/master/meta-witherspoon/recipes-phosphor/configuration/acx22-yaml-config/acx22-ipmi-sensors-mrw.yaml

This setting needs to be persistent and the host needs to be able to read/write it (even in IPMI restricted mode).
An external user should only be able to write this sensor using ipmitool or REST if they have admin privileges.

**Comment by rfrandse** [comment]
refresh

**Comment by stewart-ibm** [comment]
This breaks the separate security domains of host and BMC that has been a key design point of POWER Secure Boot design, and makes it impossible to not have "root on the BMC == executing arbitrary code with HV=1 on the host"

**Comment by cjengel** [comment]
Nothing about this breaks that design.  The BMC can only request the clear but the host will only honor the clear if it sees the request AND physical presence has been asserted to the machine as well either through the power button or jumper on the TPM card (based on system design).  

Stewart, I thought Nayna and Claudio had shown this to you before so there shouldn't be any surprises here.

**Comment by rfrandse** [comment]
refresh

**Comment by stewart-ibm** [comment]
but the power button is hooked up to the BMC, right?

A jumper on the TPM should be okay as that's only accessible to the host, but I thought the physical power button was just a GPIO on the BMC.

**Comment by amboar** [comment]
> but the power button is hooked up to the BMC, right?
> 
> A jumper on the TPM should be okay as that's only accessible to the host, but I thought the physical power button was just a GPIO on the BMC.

Yes, the power button is (usually) hooked up as a GPIO on the BMC.

**Comment by stewart-ibm** [comment]
Andrew Jeffery <notifications@github.com> writes:
>> but the power button is hooked up to the BMC, right?
>> 
>> A jumper on the TPM should be okay as that's only accessible to the host, but I thought the physical power button was just a GPIO on the BMC.
>
> Yes, the power button is (usually) hooked up as a GPIO on the BMC.

If that's the case, then root on the BMC would be able to fake physical presence.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by cjengel** [comment]
The BMC has no way to fake physical presence through the power button.  The HW has a mechanism that is only accessible to the host to open a physical presence detection window and to read if the physical button has been pressed during that window.  This is a completely different mechanism than what the BMC uses to power on/off a system and can not be faked by the BMC.  I can try to locate the design in the WSP board schematics if you are interested

**Comment by amboar** [comment]
> This is a completely different mechanism than what the BMC uses to power on/off a system and can not be faked by the BMC. I can try to locate the design in the WSP board schematics if you are interested

Sounds interesting. If you can dig it up I'm keen to take a look.

**Comment by rfrandse** [comment]
refresh

**Comment by jaypadath** [comment]
New DBUS interface code review link:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/23267

Default setting code review link:
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/23285

**Comment by jaypadath** [comment]
New review link : https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/28814

**Comment by jaypadath** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/28814

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/28814 merged
