### ISSUE TITLE
Handling invalid PELs

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#897]
If the BMC receives an invalid PEL from the host, we won't send it back to them.  Instead, we should create a new PEL that contains the bad PEL's SRC (if we can get it.)  This was informational on previous systems, but PowerVM requested we make it unrecoverable so that they will actually see it and fix their issue.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/28279

**Comment by spinler** [comment]
merged
