### ISSUE TITLE
Swift power supply device driver support for the firmware version

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#898]
The power supplies on Swift have a slightly different way to read their firmware version out.

0xFA for 2 bytes: primary software revision major/minor
0xFB for 2 bytes: secondary software revision major/minor
0xFC for 2 bytes: communication software revision major/minor

When the current code runs on swift, it fails:
```
/sys/kernel/debug/pmbus/hwmon4/cffps1# cat fw_version 
cat: read error: Bad message
```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by eddiejames** [comment]
Accepted in openbmc Linux and upstream.
