### ISSUE TITLE
User management : design password REST API

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#90]
<a href="https://github.com/dkodihal"><img src="https://avatars1.githubusercontent.com/u/22700515?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dkodihal](https://github.com/dkodihal)**
_Thursday Jul 12, 2018 at 09:42 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/3303_

----

Design OpenBMC REST API to set/change user passwords. See if https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/User/Password.interface.yaml can be leveraged.

**Comment by rfrandse** [comment]
<a href="https://github.com/vishwabmc"><img src="https://avatars1.githubusercontent.com/u/13940109?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vishwabmc](https://github.com/vishwabmc)**
_Thursday Jul 12, 2018 at 11:59 GMT_

----

@dkodihal Are we using this and use the pam libraries to updt/create the password ?

**Comment by rfrandse** [comment]
<a href="https://github.com/dkodihal"><img src="https://avatars1.githubusercontent.com/u/22700515?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dkodihal](https://github.com/dkodihal)**
_Thursday Jul 12, 2018 at 13:18 GMT_

----

@vishwabmc I think that would be the way to go. The implementation of the set/change password API would be in the REST server. The REST server will directly make calls to PAM to store/authenticate passwords (no passwords over D-Bus).

**Comment by dkodihal** [comment]
This is being addressed via #155.
