### ISSUE TITLE
PLDM : Handle BMC Reset/Reload

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#905]
The goal of this epic is to provide a mechanism for BMC to check if the Host is On/Off in the reset/reload path so that Host state can be update appropriately. This story will try to express the specific mechanism to ascertain the state of the host.

The following document covers the flow of the reset/reload path.

https://github.com/openbmc/phosphor-state-manager#bmc-reset-with-host-andor-chassis-on

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bradbishop** [comment]
I'm curious what the basic design is here.  Does the BMC need to know _why_ it was reset?  If so, what is the hw mechanism for doing that - this isn't something the BMC chip itself has functionality for.

**Comment by vishwabmc** [comment]
@bradbishop  In the traditional systems, we used this to see if we need to go back to the previous state / stay at standby / should I do Auto Power-On kind of things.

I am not too sure if we need something like that. @derekhoward55 do u ?

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
#769 might needs this.

**Comment by rfrandse** [comment]
refresh

**Comment by tomjoseph83** [comment]
There are couple of options to check if the host is on/off:

- The service acts as a PLDM requester and issues a PLDM discovery command (GetTID or GetPLDMVersion) to the host, in case of a timeout/error the host is deemed to be OFF otherwise host is considered to be ON.
- Another choice is that this might need only a lower layer protocol like MCTP and a MCTP control message can ascertain the status of the host.

@amboar @geissonator @dkodihal Please do chime in with your thoughts.

**Comment by geissonator** [comment]
> * The service acts as a PLDM requester and issues a PLDM discovery command (GetTID or GetPLDMVersion) to the host, in case of a timeout/error the host is deemed to be OFF otherwise host is considered to be ON.

If this needs to be run at some point, we may as well do it here. That way we can get it discovered and log the appropriate error if communication can not be started.

> * Another choice is that this might need only a lower layer protocol like MCTP and a MCTP control message can ascertain the status of the host.

The R/R code will not terminate the host or cut power to the chassis if communication fails. Therefore there's not really much benefit in trying to short circuit the communication path. We need PLDM up and running, and if it can't get started, we need to be sure to log an error so my vote is the first option.

**Comment by derekhoward55** [comment]
sorry looks like I never answered @vishwabmc question.  yes we need to know the type of reset, if it was a POR reset we'll auto-power-restart or log other errors depending on what caused the POR.  If it's other types of resets (they were SMGR_MAJOR_STANDBY if someone wants a list of them, I believe a common one was a tool reset) to standby it was not supposed to APR. 
If it was a reset that did not bring the system down to standby, then we have to use the persisted state (or re-determine it) for various things like power sequencer, power supplies, fans etc to ensure they stay on.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Closing.  Work is complete.
