### ISSUE TITLE
GUI: Design: Dumps

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#908]
## Stakeholders
**BMC SME**: Jayanth Othayoth, Ratan Gupta, Dhruvaraj Subhashchandran, Amit J Tendolkar   
**SBE Development**:  Raja Das    
**PHYP SME**: Adam Stallman, Tom Burks, David Stanton
**RAS SME**: Justin Thaler
**IBM i SME**: Randy Tomforhde
**FW Architect**: Dean Sanner
**HMC**: Hariganesh Muralidharan

## Use Case
Initiate a dump to diagnose a potential problem 

## InVision Prototype (Low-fi)
https://ibm.invisionapp.com/share/QKNZAGECYNF#/319267167_01-Dumps-1

## InVision Prototype (Hi-fi)
https://ibm.invisionapp.com/share/HYNZEHVFDG3#/319332166_01-Dumps-3

## Design Issue (webui-vue)
- [ ] Add Design Review story

## Development Epics
Refer to the eBMC GUI: Dumps Epic

## References/Resources
- [Dump Function Interlock Dates](https://ibm.ent.box.com/folder/79558112251)
- [Discovery notes](https://ibm.ent.box.com/notes/671632459559) 
- [Phosphor Debug Collector Software Design Document](https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/25357/1/README.md#45)
- PE and Customer Input: https://ibm.ent.box.com/notes/695914452017
- Missing UI requirements: https://ibm.ent.box.com/notes/720291476189

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Backend design being reviewed, but requires changes to Redfish prior to moving forward with design.

**Comment by derick-montague** [comment]
Added a new resource: Internal Box Note - See link in the Resources / References above

**Comment by derick-montague** [comment]
@priyanka-pillai97 did you hear from PE's on Service Processor dumps? It is possible they are needed data that none of the dumps are providing. Also, #1517 Singular Collect Data button is a dump that should contain all dumps and information that support will need to troubleshoot a system. @nicoleconser can share anything I missed. This came out of a HW Deconfig user feedback session today.

> We can't support the system without all the dump data we need.

**Comment by nicoleconser** [comment]
Re: Derick's comment above, note that Service Processor dump = FSP dump = BMC dump. The PEs explained that the BMC dump _should_ (in theory) be the **same** as what an FSP dump was, in that it should contain the same _amount_ and _granularity_ of data. It sounds like that might not currently be the case, i.e. the BMC dump is currently incomplete. This is a concern because PEs need all of this info in order to troubleshoot the more complicated customer problems.

**Comment by priyanka-pillai97** [comment]
@derick-montague Service processor dump is the same as BMC dump. As of now, there's a small defect with starting a BMC dump, but that will be fixed soon. @ratagupt

**Comment by nicoleconser** [comment]
@priyanka-pillai97 I have it in my notes that in a 7/21 meeting, @derekhoward55 said that **Resource Dumps** should include **Power Network Control Trace**. Not sure if this is relevant at all to our GUI work, but want to make sure you're aware. Just sent you a screenshot via Slack.

**Comment by priyanka-pillai97** [comment]
System dump - 09/30/2020
Resource Dump - 12/15/2020
BMC Dump - It should be working now, there will be enhancements. 
SBE (Self boot engine) Dump - 02/26/2021
Hostboot dump - 12/15/2020
Power Management dump - 03/30/2021
Hardware dump - 01/29/2021
Partition dump - There will be new partition dump, but need to find more details about that. Still deciding whether there it will be a separate type or stay as a resource dump. 

@dhruvibm @nicoleconser

**Comment by derick-montague** [comment]
> @priyanka-pillai97 I have it in my notes that in a 7/21 meeting, @derekhoward55 said that Resource Dumps should include Power Network Control Trace. Not sure if this is relevant at all to our GUI work, but want to make sure you're aware. Just sent you a screenshot via Slack.

It also looks like Resource Dumps may also include the Partition dump info.

**Comment by derick-montague** [comment]
Expect that partition dump will be part of resource dump and should be ready by the A.1.204 milestone. @mzipse will be meeting with @ratagupt next week to be sure. It most likely will not have any impact on design.
