### ISSUE TITLE
PLDM commands for OCC load

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#909]
Summary of the PLDM requirements for OCC :

- Support to handle message from HBRT that OCCs have gone active
- Support to request an OCC reset via PLDM request to HBRT

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by tomjoseph83** [comment]
- Support to handle message from HBRT that OCCs have gone active:

The proposal is to have two PLDM state sensors, representing the status of OCC1 and OCC2 respectively. The entity ID of the sensor is PROC and entity instance to match the PROC. The State Set ID  is 11 (Operational Running Status - The running status of the monitored entity) with the supported states 3 (Stopped  - The entity is no longer running) and 4 (In Service - The entity is available for use). HBRT sends the state sensor PDR's to the BMC for the BMC to get the sensor information. Whenever there is a change in the state of the sensor, HBRT sends a PlatformEventMessage with the new sensor state and BMC takes the action.

- Support to request an OCC reset via PLDM request to HBRT:

The proposal is to have a State Effecter implemented by the HBRT to trigger OCC reset. This effecter can be associated with the system entity(or OEM entity type) and implement the state set ID 192 ( Boot/Restart cause - Represents the stimulus that booted the entity. ) with the supported state 3 (warm reset) or 4 (hard reset). The BMC will be a PLDM requester and issue SetStateEffecterStates command to the HBRT to do an OCC reset.

**Comment by dkodihal** [comment]
Requirements:
	•	Support to handle message from HBRT that OCCs have gone active
	•	Support to request an OCC reset via PLDM request to HBRT
PLDM Model Details
HBRT/Hostboot needs to model the OCCs as follows:
1) Define a state sensor for each OCC to determine its running state.
	a) From the PLDM state spec, DSP0249 v1.0.0, State Set ID 11 (Operational Running Status - The running status of the monitored entity) with the supported states 3 (Stopped - The entity is no longer running) and 4 (In Service - The entity is available for use).
	b) Need a state set PDR (or temporary hard coded sensor id, see "PLDM Flow Details").
	c) In the state set PDR, there has to be an associated entity id. There are two options:
		c1) Don't make a separate entity id for the OCC. Associate the sensor with the processor entity (ntity code of 67 - Processor module). This means the processor can't have the same state set applied (from 1a).
		c2) Make a separate entity id for the OCC. The entity code of 136 - Chipset component. This doesn't have the problem with c1 above, but is more work - an entity association PDR entry is needed to associate the OCC with the corresponding PROC entity. This might mean HBRT and Hostboot firmware might have to exchange entity information?
2) Define a state effecter for each OCC to control its reset.
	a) State Set ID 192 (Boot/Restart cause - Represents the stimulus that booted the entity) with the supported state 3 (warm reset). Alternate option for this can be state 4 (hard reset).
	b) Need a state set PDR (or temporary hard coded effecter id, see "PLDM Flow Details").
	c) Same as 1c.
PLDM Flow Details
1) BMC reads the PDRs for the OCC sensor and effecters during the PDR exchange with Hostboot. If this cannot be met for the milestone, hardcoded sensor/effecter ids can be used.
2) For a change in the state of OCC state sensors, host sends a PlatformEventMessage with the new state and BMC takes action.
3) For OCC reset, BMC acts as a PLDM requester and issues SetStateEffecterStates command to the HBRT to do an OCC reset.

**Comment by dkodihal** [comment]
- What does the occ control app do if IPMI communication to the host fail?
- What causes occs to be marked not active when host powers off?

@tomjoseph83 ^

**Comment by dkodihal** [comment]
Stories under this epic

Story 1) To handle OCC active from host (@tomjoseph83)

1) Introduce a HostPDRHandler class and implement parseStateSensorPDR(pdr, size):

Parse the state sensor PDR to have a map of

```
Sensor Number ->
	struct{
		PLDM entity information,
		List of offset specific info[
			{
			State Set Id,
			Allowed Values Info
			},
			…
		]
	}
```

3) Need a host-sensors.json and parser. Parser should be in HostPDRHandler. This helps mapping a
sensorEvent from host to a BMC D-Bus operation.	

```
“entries”: [{
	“entity_type”: 100,
	“states”: [{
		“state_set_id”: 196,
		“state_values”: [4, 5],
		“dbus_mapping”:{
			“base_object_path”: “/foo/bar”,
			“interface”: “com.foo.bar”,
			“property”: “foo”,
			“property_type”: “bool”,
			“values”: [true, false]
		},
                {
		“state_set_id”: 197,
		“state_values”: [5, 6],
		“dbus_mapping”:{
			“base_object_path”: “/foo/bar/baz”,
			“interface”: “com.foo.bar”,
			“property”: “bar”,
			“property_type”: “bool”,
			“values”: [true, false]
		}
	]
}]
```

4) Handling of a PlatformEventMessage command for sensor event
- based on sensor # and offset #, pull out entity info and state set info from parsed PDR
- Check if new value in sensorEvent is allowed
- Pull out dbus mapping based on entity id and state set id
	- form d-bus path based on base object path and instance id
	- get d-bus value based on currently set value
	- do a d-bus property set

5) Write JSON for OCC sensors

6) The above can be unit tested.

**Comment by tomjoseph83** [comment]
> What does the occ control app do if IPMI communication to the host fail?

Once the OCC reset is requested, BMC sends that message to host. If the host does not ack the message, then there would be a timeout and it was caught to log an error.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by nmuruli** [comment]
The remaining Story will be done Post GA: ie Handle mapping of OCC instance on the BMC based on the MRU ID

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by nmuruli** [comment]
The remaining Story will be done Post GA: ie Handle mapping of OCC instance on the BMC based on the MRU ID #2630 is added as part of MISC commands story #652  and we are closing this Epic
