### ISSUE TITLE
PLDM commands for LED control

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#913]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
PLDM Model for LED read
a) LED is a PLDM sensor (PLDM state spec can denote LED states)
b) Associated PLDM entity for a) is a FRU
	- How does PLDM daemon find this out?
	- TBD : No associations b/w LED object and FRU today. The link today is the FRU name.
	- Check if the FRU pathname suffices
c) Based on a and b - make a state sensor PDR for every physical LED
	- What if the FRU information is collected by Hostboot? How will the association be made?
d) PLDM daemon will send a sensor change event (sensor number and new state value)

PLDM Model for LED write
a) Couple of state effecters for the physical LED - one each for fault and identity
b) PHYP has a location code to start with. PHYP looks up FRU record PDRs, entity association PDRs
and state effecter PDR to determine corresponding LED effecter.
c) PHYP will call a SetEffecter
d) BMC will has to map that to a group LED set operation

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
