### ISSUE TITLE
PLDM commands for power control

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#914]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
@derekhoward55 , I believe you have stories already open for this work?  Can @dkodihal close this Epic?

**Comment by derekhoward55** [comment]
I do have stories open for any work for power/thermal pldm intf to phyp/host, so I believe this epic can be closed.
