### ISSUE TITLE
GUI: Boot Options - Update layout and boot options

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#915]
## Use Case
As a user, I need to be able choose a boot mode and source for booting the BMC Host OS.
Notes & Context: https://ibm.ent.box.com/notes/443193157118

## InVision Prototype
https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319150964_3-7-1A_Boot_Options_Empty

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/23928

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/23928 merged
