### ISSUE TITLE
GUI: Boot Options - Next Boot Research

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#916]
## Goals
Determine if users want and/or need a next boot option.

**Comment by jandraa** [comment]
Current design proposal supports both : https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319150964_3-7-1A_Boot_Options_Empty

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
The design that is being implemented includes this feature. Closing this as a duplicative issue related to #404
