### ISSUE TITLE
Power supply monitoring 

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#918]
Number of deglitches (needs to be less time to log fault than pgood deglitching) - 3. 1 per second.

Interrupts from kernel, not from PS hardware.  Regardless, if kernel is doing the poll, how does app know the data is new every time it looks at response?

Change DD to NOT clear faults every poll?

Verify cmds needing be sent, fault handling bits, etc.  Prioritize multiple faults correctly (per PS, no cross-domain analysis). Specific reason in error log for hardware teams usage. [See BMC_PS_responses.doc]

Log error for missing ps (should be done already).

Look for fan faults in status_word register in ps app.  In future, we could externalize the fan speeds and compare them to a limit from fan config in the fan app instead.  This is a better approach as it would require a bmc fw update instead of ps microcode update if the ps fans have troubles maintaining the expected limits, however we do not have time to implement this for GA.

Handle ps_kill fails, any other random fails.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
Changing the device driver to not do the clear faults (as part of hwmon) is not sounding like a viable option, based on conversations/chats with Eddie James while working with ibm-openbmc/dev#1424.

Adding a CLEAR_FAULTS to debug also did not sound like an option. One suggestion was that intentional CLEAR_FAULTS could be done by reading from a file associated with the hwmon path.

**Comment by bjwyman** [comment]
We should not clear faults after power state has changed to on.
https://github.ibm.com/openbmc/phosphor-power/blob/6345c6c569603d45f20c64029e731de06f55f4f0/phosphor-power-supply/psu_manager.cpp#L130

**Comment by bjwyman** [comment]
Need a commFault concept, and probably stop trying to read if having a commFault issue:

@anoo1 noted this in some testing with 5.8 kernel:
> ...the bmc logs continuously these errors, anything of concern?
```
    "MESSAGE" : "Failed to read sysfs file",
    "SYSLOG_IDENTIFIER" : "phosphor-psu-monitor",
    "FILENAME" : "/sys/kernel/debug/pmbus/hwmon7/status0",
```
Something along these lines in analyze()?
```
if ((present) && (commFault < ???))
...
     read...
```

**Comment by bjwyman** [comment]
Log error for missing ps - handled with ibm-openbmc/dev#2480

**Comment by bjwyman** [comment]
- [x] ~~Blackout (AC loss) error~~ https://github.com/ibm-openbmc/dev/issues/2942
- PEL for trending/calibration error different from comm fault. 
  - https://github.com/ibm-openbmc/dev/issues/1815 ?
- Change DD to NOT clear faults every poll. 
  -  I think we got this for free via: https://github.com/openbmc/linux/commit/a919ba06979a7858dab65492eb580121ccbd524f
- [x] 3 reads of fault before log fault
  - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/50479
  - https://github.com/openbmc/phosphor-power/commit/c2906f471f3ecb4fe021efc657a32c4266a88589
- [x] Keep trying to read from power supply after logging fault.
  - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/49775
  - https://github.com/openbmc/phosphor-power/commit/32453e9b9a4b1f8233efc68646cf317c2e8f7173
- [x] CML fault (https://github.com/openbmc/phosphor-power/commit/85c7bf41fe4f1aed2667e434e3b1db2d6b80f6ab#diff-9ce36f15bc5c4330d445103ff83361d975955fbb06ed77d9de6ef99cef995d84)
- [x] VIN_UV_FAULT, INPUT fault.
- [x] MFR_SPECFIC bit 4: PS_Kill fault/PEL
  - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/49069
  - https://github.com/openbmc/phosphor-power/commit/39ea02bc9458f3d5a7fdd317cb546ed046eaff78#diff-9ce36f15bc5c4330d445103ff83361d975955fbb06ed77d9de6ef99cef995d84
- [x] VOUT_OV_FAULT (https://github.com/openbmc/phosphor-power/commit/6710ba2cc776dc9e4306807f4f586c22822100b4#diff-9ce36f15bc5c4330d445103ff83361d975955fbb06ed77d9de6ef99cef995d84)
- [x] IOUT_OC_FAULT
  - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/48943
  - https://github.com/openbmc/phosphor-power/commit/b10b3be0da7284082afab79881d9e015c9ae4728
- [x] VOUT fault (STATUS_WORD bit 15)
  - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/48946
  - https://github.com/openbmc/phosphor-power/commit/2cf46945e354a96e8216ed8d9c774cb5963f7705
- [x] MFR_SPECIFIC bit 6: 12Vcs
  - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/49069
  - https://github.com/openbmc/phosphor-power/commit/39ea02bc9458f3d5a7fdd317cb546ed046eaff78#diff-9ce36f15bc5c4330d445103ff83361d975955fbb06ed77d9de6ef99cef995d84
- [x] MFR_SPECIFIC bit 7: 12V CS
  - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/49069
  - https://github.com/openbmc/phosphor-power/commit/39ea02bc9458f3d5a7fdd317cb546ed046eaff78#diff-9ce36f15bc5c4330d445103ff83361d975955fbb06ed77d9de6ef99cef995d84
- [x] FANS fault (STATUS_WORD bit 10)
  - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/49016
  - https://github.com/openbmc/phosphor-power/commit/7ee4d7e41d301c99cef377028264124fe35b7baa#diff-9ce36f15bc5c4330d445103ff83361d975955fbb06ed77d9de6ef99cef995d84
- [x] TEMPERATURE fault (STATUS_WORD bit 2)
  - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/48671
  - https://github.com/openbmc/phosphor-power/commit/96893a469bb867b45489fc8b3c1ca34ed9ae1c57#diff-9ce36f15bc5c4330d445103ff83361d975955fbb06ed77d9de6ef99cef995d84
- [x] PG_STATUS# or OFF (STATUS_WORD bits 11 or 6)
  - https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/48672
  - https://github.com/openbmc/phosphor-power/commit/2916ea52b3d4c9ba0d0d90c1e33f333aeb720047#diff-9ce36f15bc5c4330d445103ff83361d975955fbb06ed77d9de6ef99cef995d84
- [~] USER_DATA_14 (BEh)
  - Nice to have? Separate issue/story created: https://github.com/ibm-openbmc/dev/issues/3471

**Comment by bjwyman** [comment]
> Need a commFault concept, and probably stop trying to read if having a commFault issue:
> 
> @anoo1 noted this in some testing with 5.8 kernel:
> 
> > ...the bmc logs continuously these errors, anything of concern?
> 
> ```
>     "MESSAGE" : "Failed to read sysfs file",
>     "SYSLOG_IDENTIFIER" : "phosphor-psu-monitor",
>     "FILENAME" : "/sys/kernel/debug/pmbus/hwmon7/status0",
> ```
> 
> Something along these lines in analyze()?
> 
> ```
> if ((present) && (commFault < ???))
> ...
>      read...
> ```

This was fixed as part of #2480

**Comment by bjwyman** [comment]
> We should not clear faults after power state has changed to on.
> https://github.ibm.com/openbmc/phosphor-power/blob/6345c6c569603d45f20c64029e731de06f55f4f0/phosphor-power-supply/psu_manager.cpp#L130

Right now, the power state we are looking at is the pgood, and it is clearing faults when pgood goes active.
`constexpr auto POWER_IFACE = "org.openbmc.control.Power";`
`constexpr auto POWER_OBJ_PATH = "/org/openbmc/control/power0";`

That is AFTER things have started the enable and power up process. Ideally we would clear faults as close as possible to the point where we are going to activate the enable signal.

**Comment by bjwyman** [comment]
Some additional things that seemed appropriate to address:
- [x] Be sure to set Functional property to false when a fault occurs.
  - Not needed. Handled by PEL/LED code for call outs. Set Functional back to true when missing to present occurs already covered.
- [~] Try to avoid that error on bind if the device driver is already bound.
  - Created separate issue/story: https://github.com/ibm-openbmc/dev/issues/3470
- [x] Decimal values for STATUS_* in call outs is confusing, try to make that hexadecimal.
  - https://github.com/openbmc/phosphor-power/commit/786b6f4cbfb8e3779570a09f89bce589ba2e75d4

**Comment by bjwyman** [comment]
Plan on separating out BEh command support and the errno DD bind tracing to separate issues/stories.

**Comment by bjwyman** [comment]
> Plan on separating out BEh command support and the errno DD bind tracing to separate issues/stories.

Done.

**Comment by bjwyman** [comment]
> Handle ... trending data collection fails....

Is that trending data collection part of: https://github.com/ibm-openbmc/dev/issues/1815
