### ISSUE TITLE
Power supply presence detection

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#919]
Setup ps presence detection and binding of device driver.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
I am not sure if the intent here was to replace the current `phosphor-gpio-monitor` setup that is currently used by Witherspoon and Swift, or if this would just be an update to the application to watch the D-Bus properties to change.
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/23038/5/designs/psu-control.md#42
I am going to assume we can just have the application watching the D-Bus properties.

**Comment by bjwyman** [comment]
I am also assuming this will depend on a device tree update, to get the presence pins defined and working with gpiolib.

I do not currently see such a story for Rainier. We would need something similar to ibm-openbmc/dev#296.

**Comment by bjwyman** [comment]
Still leaning towards initial change here would be to make updates necessary for `phosphor-gpio-monitor` to read GPIO pins for Rainier (configuration file addition/change) and update appropriate D-Bus properties.

**Comment by bjwyman** [comment]
There seems to be an existing YAML file for a policy on what to do if a power supply is removed while a system is powered on:
https://github.com/openbmc/meta-ibm/blob/4b80c4f2b3a62d8084fc43f95177e299d53387ae/meta-witherspoon/recipes-phosphor/dbus/power-supply-policy/power-supply-policy.yaml

That only accounts for two power supplies. Rainier can have up to four power supplies, so not quite sure how to handle that right now.

**Comment by bjwyman** [comment]
Seems I was overly optimistic on what was in the device tree file. I think there are at least two parts to making this work. One is a kernel patch for gpio-keys for the power supply presence lines, and another is a configuration file for Rainier to use with `phosphor-gpio-monitor`.

Working on both of those.

**Comment by bjwyman** [comment]
Kernel patch to get gpio-keys section with power supply presence submitted: https://lists.ozlabs.org/pipermail/openbmc/2019-October/019185.html

**Comment by bjwyman** [comment]
Those changes made it to openbmc/linux:
https://github.com/openbmc/linux/commit/fadfe5880be510fc29e83441881e4e7d43e78da5

**Comment by bjwyman** [comment]
> Kernel patch to get gpio-keys section with power supply presence submitted: https://lists.ozlabs.org/pipermail/openbmc/2019-October/019185.html

Reviewed by Eddie James, https://lists.ozlabs.org/pipermail/openbmc/2019-November/019254.html, then it was merged.

**Comment by bjwyman** [comment]
I thought I might need to submit this upstream to linux-next as well, but that has already been done:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/arch/arm/boot/dts/aspeed-bmc-ibm-rainier.dts?id=1dd785ba304d9f72330921acd72133591d362a43

**Comment by bjwyman** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/26934

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/26934 merged
