### ISSUE TITLE
BMC Dump: Add user configure support

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#92]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ojayanth](https://github.com/ojayanth)**
_Tuesday Apr 25, 2017 at 12:28 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/1513_

----

— Provide a User option to configure Dump.

**Comment by rfrandse** [comment]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ojayanth](https://github.com/ojayanth)**
_Friday Sep 22, 2017 at 11:35 GMT_

----

 https://github.com/openbmc/openbmc/issues/2351 support basic support for the GA.
Please move to Phase 7.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
Already enabled support to configure dump based on various type of error log. So closing this issue now.
