### ISSUE TITLE
Power supply config validation

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#920]
Initial setup of specifying ps config - number of ps required, type (1600w/2000w), input type (220/110/dc), etc. 

Read from entity manager config file / dbus.

Strawman at https://github.ibm.com/bradleyb/entity-manager/blob/wip-rainier-configurations/configurations/Rainier%202U.json.

Separate business logic from init data as appropriate.

Full support for handling the config types (actions to take) in https://github.com/ibm-openbmc/dev/issues/1588.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
Some notes on getting system type from D-Bus in #1474: https://github.com/ibm-openbmc/dev/issues/1474#issuecomment-580406603

**Comment by anoo1** [comment]
Entity Manager:
- [ ] IBM CFFPS json files: https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/40195/
- [ ] Supported configuration schema: https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/40293/
- [ ] Add supported configuration to Rainier 2U: https://gerrit.openbmc-project.xyz/c/openbmc/entity-manager/+/40595/
- [ ] Add supported configuration to Rainier 4U and Everest

Phosphor Power:
- [ ] Read max # of PSs from EM: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/40971
- [ ] Determine # of PSs plugged in the system
- [ ] Add policy to log error if expected max # of PSs is different than actual
- [ ] Read min voltage from EM
- [ ] Determine voltage from plugged PSs
- [ ] Add policy to log error if min voltage does not match actual

**Comment by derekhoward55** [comment]
also need to verify the type (trio is: for this type of ps, need this many plugged in, with this type of input)

**Comment by anoo1** [comment]
This is done.
