### ISSUE TITLE
Power supply init state machine

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#921]
PS state machine on insert, AC apply, etc. - read VPD, clear faults, any config, etc.

List the cmds we send today on bmc/fsp systems, and determine which of those we do/don't need to do going forward.

Ensure vpd gets populated in inventory manager.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
Looks like successfully reading all the VPD will depend on ibm-openbmc/dev#1424 :
```
root@rainier:~# ls /sys/kernel/debug/pmbus/hwmon7
cffps1         status0        status0_cml    status0_fan12  status0_input  status0_iout   status0_mfr    status0_other  status0_temp   status0_vout
root@rainier:~# ls /sys/kernel/debug/pmbus/hwmon7/cffps1
ccin           fru            fw_version     header         input_history  max_power_out  on_off_config  part_number    serial_number
root@rainier:~# ls /sys/kernel/debug/pmbus/hwmon7/cffps1/ccin
/sys/kernel/debug/pmbus/hwmon7/cffps1/ccin
root@rainier:~# cat /sys/kernel/debug/pmbus/hwmon7/cffps1/ccin
E951
root@rainier:~# cat /sys/kernel/debug/pmbus/hwmon7/cffps1/part_number 
cat: read error: Bad message
root@rainier:~# cat /sys/kernel/debug/pmbus/hwmon7/cffps1/serial_number 
cat: read error: Bad message
root@rainier:~# cat /sys/kernel/debug/pmbus/hwmon7/cffps1/fw_version    
cat: read error: Bad message
root@rainier:~# 
```

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/q/topic:"ibm921"+(status:open OR status:merged)

**Comment by bjwyman** [comment]
Resolved-by: https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/34117

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/34117 merged.
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/34441 merged.
https://github.com/openbmc/openbmc/commit/c978da3dbd1f7d7047be9ad9bee3f0df377932d0
