### ISSUE TITLE
phosphor-regulators: Implement regulator configuration (voltage setting)

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#923]
Implement firmware for executing VRM JSON file specs.  Should be limited to voltage setting and any needed config just for powering on hw.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
Implement regulator configuration, which includes voltage setting.

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/31348

**Comment by smccarney** [comment]
Review has been merged.
