### ISSUE TITLE
phosphor-regulators: Configuration File Validator

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#924]
Replace usage of xmllint validation with some json file validation for eBMC for both build time and for hw engineers to manually run.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by smccarney** [comment]
The phosphor-regulators application is controlled by a JSON configuration file (config file).  The config file defines the regulators in the system and what regulator operations to perform.

A validation tool is needed to check config files for errors, such as:
* Invalid JSON syntax like a missing brace
* Unrecognized JSON objects or properties
* Non-unique rule or device IDs
* References to rule or device IDs that do not exist
* Infinite loops, such as rule A runs rule B which runs rule A

The validation tool will be run manually by config file writers.  It will also be run automatically during OpenBMC builds.  The tool will likely be run on Intel Linux and Apple MacBooks.

The validation tool should be a Python script.  It should use a JSON schema file and the associated Python support.  See https://json-schema.org/

The tool should be named validate_regs_config.py and should provide the following command line interface:
```
validate_regs_config.py -c <config file> -s regulators_schema.json
```

The valid JSON objects and properties that can appear in the config file are documented in markdown files.

**Comment by bradbishop** [comment]
at 5:26 PM, Shawn McCarney <notifications@github.com> wrote:

> The phosphor-regulators application is controlled by a JSON configuration  
> file (config file). The config file defines the regulators in the system  
> and what regulator operations to perform.
>
> A validation tool is needed to check config files for errors, such as:
>
> 	• Invalid JSON syntax like a missing brace
> 	• Unrecognized JSON objects or properties
> 	• Non-unique rule or device IDs
> 	• References to rule or device IDs that do not exist
> 	• Infinite loops, such as rule A runs rule B which runs rule A
> The validation tool will be run manually by config file writers. It will  
> also be run automatically during OpenBMC builds. The tool will likely be  
> run on Intel Linux and Apple MacBooks.
>
> The validation tool should be a Python script. It should use a JSON  
> schema file and the associated Python support. See  
> https://json-schema.org/
>
> The tool should be named validate_regs_config.py and should provide the  
> following command line interface:
>
> validate_regs_config.py -c <config file> -s regulators_schema.json

I was looking around here https://json-schema.org/implementations.html

None of these work?  There is a python one:

https://github.com/Julian/jsonschema

Why do we need to write our own?

**Comment by smccarney** [comment]
> I was looking around here https://json-schema.org/implementations.html None of these work? There is a python one: https://github.com/Julian/jsonschema Why do we need to write our own?

I was planning to use an existing Python implementation of JSON Schema, like https://github.com/Julian/jsonschema.  That is not the focus of this issue.

The goal is to write a tool that calls the normal JSON Schema support and then does some additional validation that is not supported in the schema.  There will be some errors that I don't think can be expressed in JSON schema.

I believe Matt Spinler is taking a very similar approach in validating the new error log JSON file.

**Comment by bradbishop** [comment]
> I was planning to use an existing Python implementation of JSON Schema
👍

**Comment by smccarney** [comment]
I updated my [initial comment](https://github.com/ibm-openbmc/dev/issues/924#issuecomment-535692471) to better reflect the design and requirements.

**Comment by smccarney** [comment]
Resolved by https://gerrit.openbmc-project.xyz/30475
