### ISSUE TITLE
VRM support for DDIMMs/EDIMMs

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#925]
PMIC/DDIMM/EDIMM impacts (collect phase fails, telemetry, temps, vpd, etc via SBE)? Can SBE put the appropriate data on DBUS? Need to write interface for SBE to put on DBUS, then Redfish support can work as normal. Phase fault info, vpd, temps, etc make sense to put on DBUS?
BMC-SBE FIFO-OCC path in kernel already. New chip ops for pmics in SBE, but same concept?

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derekhoward55** [comment]
Duplicate issue.
