### ISSUE TITLE
Cold Reboot does not restart on some systems

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#926]
## Expected Behavior
When running a cold reboot, the system should restart following shutdown.

## Actual Behavior
Their is a client-side error that prevents the system from restarting. The error is caused by a timeout that triggers the catch block in the Promise and indicates that the shutdown was not successful. The shutdown is successful, but due to the error, the restart is not initiated.

## Steps to Reproduce the Problem

  1. Go to Server control > Server power operations
  1. Initiate a Cold reboot

## Specifications
Test has a specific image and it seems to be when they have a larger hardware profile.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
