### ISSUE TITLE
Power on support based on system configuration

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#928]
Power on skeleton replacement - read/set/monitor gpios (BMCPOWER_UP, SYS_PWROK_BUFF).

The UCD90320 has a built-in delay after enabling the vrms before activating SYS_PWROK_BUFF, which along with going back to the BMC to ensure the sequencing has completed, also goes to the cec chip resets to take them out of reset.  There is no separate resets signal to control or monitor - everything comes up with BMC_POWER_UP/SOFTWARE_PGOOD->SYS_PWROK_BUFF.  Get gpios from dts (correct dts will be picked by EM).

We don't need to toggle BMC_DCM_ALL_RESET gpio (instead of just deactivating) for resets_out.  It is disabled by the hardware by default.  The preference is to toggle it during the power on so the procs come up clean, and it also needs to be toggled during warm ipls/reboots, these will be handled by state management code elsewhere.

Ensure appropriate apps re-read mrw/xml (fan config, ps config, vrm config, epow limits, etc) during ipl.

Stop IPL if node type not recognized - put IM in json config file? POR is need system type in vpd, not separate code image for each. Recommended to separate code that stops IPL from general power on sequencing, as different users of code have different requirements.
phosphor_regulators will stop the IPL before the power sequencing code uses the dts gpios to kick off the sequencing, so no need to look at IM directly in the power sequencing code to stop IPL.

Trace the IM value in the journal during the power on sequencing so we know the system type in field/lab debug and can validate that the correct config files are used.

Alert other apps (eg via DBUS) that power is completed.  This is already done as a DBUS "state" property exists (hosted by the chassis state manager that reflects the state of the systemd target which does a chassis poweron) that can be used.

Need PSX replacement to get alerts to phyp (via pldm) or power/ups status to rest of BMC. This follows issues 893&894, ensure handled appropriately.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by wrightjl1** [comment]
Doc review for GPIO line names: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/45054

**Comment by wrightjl1** [comment]
Initial application commit: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/45126

**Comment by wrightjl1** [comment]
Second power control application review:  https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/45515

**Comment by wrightjl1** [comment]
p10bmc device tree updates review / approval:
(Openbmc) https://lore.kernel.org/openbmc/CACPK8XcgFkcA4cpqzTmwS-tpauWeAeFHqzhjyxOWvggKSOJFQw@mail.gmail.com/T/#t
(Aspeed) https://lists.ozlabs.org/pipermail/linux-aspeed/2021-August/006151.html

**Comment by wrightjl1** [comment]
dbus server interface review: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/46176

**Comment by wrightjl1** [comment]
dbus implementation review: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/46288

**Comment by wrightjl1** [comment]
GPIO support review: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/46395
