### ISSUE TITLE
Support for UCD90320 sequencer

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#929]
Config sequencer (eg clear faults), etc.  Define/enable interrupts and comm paths.

Execute ucd90320 sequencing (enabling vrms, verifying pgoods come up).  Base on sequence from previous system until we get the Rainier sequence from hw team.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derekhoward55** [comment]
work handled elsewhere.
