### ISSUE TITLE
dreport: Improve -t option.

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#93]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ojayanth](https://github.com/ojayanth)**
_Thursday Aug 03, 2017 at 03:06 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2076_

----

refer reveiw link for details.
https://gerrit.openbmc-project.xyz/#/c/5451/3/dreport/dreport.sh@23

**Comment by rfrandse** [comment]
<a href="https://github.com/ojayanth"><img src="https://avatars2.githubusercontent.com/u/12947151?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ojayanth](https://github.com/ojayanth)**
_Friday Sep 22, 2017 at 11:21 GMT_

----

This is included as part of issue https://github.com/openbmc/openbmc/issues/2037.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
#2076 already closed.
