### ISSUE TITLE
System power off / power off sequence

### ISSUE THREAD

**Issue by derekhoward55** [ibm-openbmc/dev#930]
Insert delay (2s) to get terminating error log out and allow things to quiesce (such as other services getting through hard power off target) before power removed. 

Execute UCD90320 power off sequencing.
Ensure sequencing/pgoods turned off successfully.

Anything else needed to get system to standby such as requesting hard power off when pgoods/ucd fail, log PEL if ucd doesn't power off.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by wrightjl1** [comment]
Bulk of the power off code was done in conjunction with power on story:  https://github.com/ibm-openbmc/dev/issues/928

**Comment by wrightjl1** [comment]
Review for power off two second wait:  https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/48792

**Comment by wrightjl1** [comment]
phosphor-logging review for power on and off PELs: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/48812

**Comment by wrightjl1** [comment]
Review for calling chassis hard power off target on pgood fail:  https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/48878

**Comment by wrightjl1** [comment]
Review for logging timeout entries: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-power/+/48922

**Comment by derekhoward55** [comment]
All changes merged.
