### ISSUE TITLE
Implement API for accessing PLDM BIOS Tables

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#932]
- [x] Define structures for all PLDM BIOS tables
- [x] Implement API to store a particular table
- [ ] Implement API to modify a particular row in a table
- [ ] Implement API to query a certain tow in a table
- [x] Implement API to load a certain table

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/22756/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/22756 merged
