### ISSUE TITLE
Implement GetBIOSTable

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#933]
- [ ] libpldm : implement encoders and decoders
- [ ] libpldmresponder : SetBIOSTable : invoke API to store received tables
- [ ] libpldmresponder : GetBIOSTable : invoke APIs to create tables and send response

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Responder flow for GetBIOSTable and tasks :

- [ ] Register responder handle for GetBIOSTable to pldm daemon
- [ ] Write request decoder
- [ ] If table type is string, invoke API to get list of strings. Dependency on #812

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
Resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/23283/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/23283 merged
