### ISSUE TITLE
PLDM OEM IBM : Implement ReadFile and WriteFile commands

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#934]
- [x] Implement encoders and decoders
- [ ] Implement responders

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/22941 - encoder/decoder

**Comment by vkaverap** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/23229 - responder

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/22941 merged

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/23229 merged
