### ISSUE TITLE
GUI: FED: Network Page Layout

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#935]
## Use Case
As a user, I need to be able to easily update the network settings page. 

## As Is
The Network page layout is overly complex and can be simplified to improve the user experience. The new layout will accommodate updates for future enhancements.

![image](https://user-images.githubusercontent.com/1183515/59371440-a0e40c00-8d0a-11e9-88a0-ff0ceeab2f1d.png)

## To Be
Can be referenced in the Invision prototype

## InVision Prototype
https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/screens/319333952

## Resources
Refer to GUI: Update network page Epic

**Comment by derick-montague** [comment]
@jandraa @miramurali23 @yoshiemuranaka - Based on our conversation at sprint planning today, there are few changes to the UI prototype that we agreed to change.

1. We will not be using the `Save` icon (floppy) when the section is in the edit state. Follow the UI Pattern on the SNMP Settings screen
1. `Remove` icon (trash) and` Edit` icon (pencil) will be disabled when the section is in the edit state (there is a story to update this on the SNMP screen)
1. Settings page `Save Settings` and `Cancel` buttons will be disabled until something has changed on the page.

**Comment by rfrandse** [comment]
refresh

**Comment by mzipse** [comment]
Sorry Mira, looks like you wanted this in "In Progress" status.

**Comment by rfrandse** [comment]
refresh

**Comment by miramurali23** [comment]
Note: Converting all calls to Redfish

**Comment by derick-montague** [comment]
@ratagupt mentioned there is a bug being addressed in [this gerrit review](https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24106). The bug is resulting in all Gateways being returned as 0.0.0.0 even though the gateway is included in the request's payload. Also experiencing blocking issues related to FQDN. Conversation is taking place in Slack, but would be great to have stories to associate as blockers so we are aware when we can move forward with the client-side work (review and testing).

**Comment by derick-montague** [comment]
Blocked by Gerrit review: https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24106

**Comment by derick-montague** [comment]
@gtmills @ratagupt @mzipse  - There hasn't been any activity on the Gerrit review that is blocking this from moving forward. We have more work to complete, linked in the associated Epic, around DHCP settings. Do we know when this can move forward?

**Comment by derick-montague** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24317

**Comment by derick-montague** [comment]
@gtmills @mzipse - Not sure what to do about this one since there hasn't been any activity on the Gerrit commit.

**Comment by gtmills** [comment]
@ratagupt we still need https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24106 correct? Can we get that in

**Comment by derick-montague** [comment]
Planning to abandon and will be part of the vue rewrite.
