### ISSUE TITLE
GUI: Toggle component update

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#937]
## Use Case
As a user I need to be able to clearly understand the changes I am making with using a toggle component. 

## Accessibility
Accessible and usable components do not rely solely on color to convey meaning. Having text to indicate the current state of the toggle button is needed to meet accessibility guidelines.

## As Is
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/9e460cf6-6354-46e6-a09d-673a99af5011)

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/849d2a29-f5a3-43f6-a525-9d40b077ec03)

## To Be
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/7ddd5d26-c744-4883-a97c-c31089f13a53)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
