### ISSUE TITLE
GUI: SNMP Settings Update

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#938]
## Changes Required
1. Disable buttons in edit state

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/57238775-0295-41e7-baa4-9a34d75a6fb7)

2. Update text color to use the body color.
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/3f283c0f-1425-44e0-ae41-8f9a9349d17e)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rahulmah** [comment]
Test story for testing these changes - https://github.com/openbmc/openbmc-test-automation/issues/1865

**Comment by dixsie** [comment]
Edit button removed in https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/25039

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/24314
