### ISSUE TITLE
SetBIOSAttributeCurrentValue : encode/decode API

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#939]
- [ ] libpldm : implement encode and decode APIs for this command for the requester flow
- [ ] libpldm : implement encode and decode APIs for this command for the responder flow
- [ ] Write unit tests

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by wangzqbj** [comment]
Merged: https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/24458
