### ISSUE TITLE
Redfish Code Update - Provide correct firmware inventory status of images

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#941]
https://github.com/openbmc/bmcweb/issues/75 has the details on this issue.

https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/21986 is the design doc proposal.

This story will be to implement the solution.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22900

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22900 merged
