### ISSUE TITLE
pHAL: BMC code layout design.

### ISSUE THREAD

**Issue by ojayanth** [ibm-openbmc/dev#942]
Set-up High level  direction on the pHAL code layout in BMC. 
Currently  pHAL includes , pdbg ,  Hardware procedures and glue code layer for BMC application interaction .
Need an initial frame work proposal in the BMC to support this layout.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by ojayanth** [comment]
![image](https://user-images.githubusercontent.com/12947151/60520075-61558200-9d02-11e9-9f43-d81364115388.png)

**Comment by ojayanth** [comment]
![pHAL Layout_V4](https://user-images.githubusercontent.com/12947151/61534256-bdcbd780-aa4c-11e9-8a1b-7ddf9e7c0a37.png)

**Comment by ojayanth** [comment]
New version of pHAL layout.

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/23287

**Comment by ojayanth** [comment]
Need some updates on the design document based on the  recent ipl ( openpower repo ) based IPL infrastructure.

**Comment by ojayanth** [comment]
Still discussion is in progress with respect to handling device tree data. Moving this issue under device tree Milestone.

**Comment by ojayanth** [comment]
#663 is used for design document to community.  This issue is used for working on initail design for phal.
