### ISSUE TITLE
Replace certificate  - should cater for appending private key from system and install

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#943]
<a href="https://github.com/devenrao"><img src="https://avatars3.githubusercontent.com/u/26330444?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [devenrao](https://github.com/devenrao)**
_Tuesday Mar 26, 2019 at 02:48 GMT_
_Originally opened as https://github.com/openbmc/phosphor-certificate-manager/issues/5_

----

During replace certiificate, user might pass only certificate string. If there is no private key system should use the private key generated as part of CSR and append it to the certificate string and install onto the system.

This requirement has dependency on GenerateCSR

**Comment by ojayanth** [comment]
Resolves by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-certificate-manager/+/22523

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
