### ISSUE TITLE
eBMC State Management - Tool to visualize systemd target and services

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#944]
Write a static analysis tool which can be run against an openbmc bitbake rootfs which will provide the following information:

- All targets and their dependencies (targets and services)
- All targets and their OnError behavior
- Handle some OpenBMC specific things like mapper-wait@ syntax

Put this tool in openbmc-tools repository

**Comment by rfrandse** [comment]
refresh

**Comment by amboar** [comment]
> Put this tool in openbmc-tools repository

Can it go upstream into systemd instead?

**Comment by geissonator** [comment]
> > Put this tool in openbmc-tools repository
> 
> Can it go upstream into systemd instead?

Yeah, I was starting to draft an email to their mailing list to see if it's something they'd be interested in. One concern I have is our openbmc-isms like the mapper stuff in the service files. Long term we want to get rid of that but handling it now is a big part of the tool. Also, I'm still contemplating finding a way to just use systemd-analyze. But either way, I'll def involve upstream.

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Although a nice to have, I just don't see this happening. I'm going to keep https://github.com/ibm-openbmc/dev/issues/105 open to track better documentation.
