### ISSUE TITLE
eBMC State Management - Design to ensure error created for OpenBMC systemd target failures

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#945]
Track the design doc to define how we can ensure an error is created for any critical OpenBMC systemd target.

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/22707

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/22707 merged
