### ISSUE TITLE
Single Image Code Update with eMMC NAND

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#950]
Epic to track the support needed to use the eMMC NAND including flash layout, code update, etc.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
GPT partitions were implemented instead: https://gerrit.openbmc-project.xyz/q/topic:mmc
