### ISSUE TITLE
Create code update service to update rootfs lvm volume

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#953]
Update the bmc-code-mgmt code to support the ext4 filesystem (current supported filesystems are static and ubi), create an LVM volume during activation, and populate it with the rootfs file.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by antwil** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-ibm/+/26428/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-pnor-code-mgmt/+/25815/
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-openpower/+/26184/

**Comment by anoo1** [comment]
We won't be using LVM, instead the partitions will be static.
