### ISSUE TITLE
Support to boot roofts from a logical volume

### ISSUE THREAD

**Issue by anoo1** [ibm-openbmc/dev#954]
This might require an initramfs.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by anoo1** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/24747

**Comment by anoo1** [comment]
GPT partitions were implemented instead: https://gerrit.openbmc-project.xyz/q/topic:mmc
