### ISSUE TITLE
HMC-BMC Event Notification: How to send the redfish events through Redfish

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#956]
The outcome from this story is to find out a way in bmcweb how can we implement server side event.
How the redfish events can be plugged with redfish backend or how the infrastructure can be used.
Need to come with the design doc for the same.

**Comment by rfrandse** [comment]
refresh

**Comment by trajeswaran** [comment]
As a part of this story,
- understood the Redfish specification for SSE
- understood how bmcweb handles Redfish API support
- identified what can be done to support Redfish SSE.

I have prepared the design proposal in a word document. I am preparing the md file.

**Comment by trajeswaran** [comment]
Ratan has sent a mail to openbmc development community to ask for the interested parties. For that, Intel has replied that they are interested and uploaded their design document. Based on their design document,, Intel is working on that feature.
