### ISSUE TITLE
Should display the min/max power cap on D-Bus/Redfish

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#957]
Currently, if a user sets the power cap too high or too low, they get an error. 
The min/max power cap values are not displayed on the D-Bus API here: 
/xyz/openbmc_project/control/host0/power_cap 
Redfish does have a concept as a min value for the power cap. 
![power-cap-redfish](https://user-images.githubusercontent.com/5455127/59612137-36541700-90e2-11e9-9d42-c8fe2f7b67d7.PNG)
https://redfish.dmtf.org/schemas/v1/Power.v1_5_3.json

This would improve usability, the GUI story is here: https://github.com/ibm-openbmc/dev/issues/582

**Comment by rfrandse** [comment]
refresh

**Comment by geissonator** [comment]
@spinler indicated the ranges are in the settings yaml, so we just need to get those into D-Bus objects and then lined up with the Redfish properties noted above.

**Comment by geissonator** [comment]
Per Martha it's best if we get the pcap limits from the poll response to the OCC and use those.
 OCC poll response /(PS_DERATING/100)

So work here is for @eddiejames to put the pcap limits somewhere userspace can get to them, then put those on D-Bus, then connect bmcweb up with them in Redfish.

**Comment by mzipse** [comment]
@derekhoward55 , I'm assigning this to you.  I'm hoping the power team can take a look at this.  If we came up with a solution, we might consider backporting this to OP940.

**Comment by derekhoward55** [comment]
I discussed this with Martha, it seems to be under her umbrella so changing owner to her.

**Comment by gtmills** [comment]
I am assuming this includes the Redfish work. Please feel free to change the estimate. https://github.com/ibm-openbmc/dev/issues/1257 is the GUI work for this.

**Comment by derick-montague** [comment]
@gtmills @marthabroyles - Do we know when this might be ready?

**Comment by marthabroyles** [comment]
@derick-montague  goal is May

**Comment by gtmills** [comment]
Do we need to add "Max" to the Redfish spec? They currently only have "Min"

**Comment by cjcain** [comment]
Code implemented for the pcap hard minimum and maximum.

Dbus:
```
xyz.openbmc_project.Control.Power.Cap interface -         -            -
.MaxPowerCapValue                     property  u         3584   emits-change writable
.MinPowerCapValue                     property  u         2700            emits-change writable
.PowerCap                             property  u         990          emits-change writable
.PowerCapEnable                       property  b         false         emits-change writable
```

```
$ curl -s -k -X GET https://$bmc/redfish/v1/Chassis/chassis/EnvironmentMetrics  | grep -A5 -i PowerLimitWatts
  "PowerLimitWatts": {
    "AllowableMax": 3584,
    "AllowableMin": 2700,
    "ControlMode": "Disabled",
    "SetPoint": 990
```

Pull request for 1020: https://github.ibm.com/openbmc/openbmc/pull/2002

**Comment by cjcain** [comment]
Code available in fw1020.00-45.2

**Comment by mzipse** [comment]
This work is complete.  Closing.
