### ISSUE TITLE
Redfish: Upstream CPU throttling 

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#958]
Need to upstream to Redfish CPU throttling. An indicator of if the CPUs are throttling. 
Since CPU is the same data model as GPU (Redfish processor schema) we would get this free for GPUs, if we needed in the future.

**Comment by gtmills** [comment]
Need a story to implement this.

**Comment by gtmills** [comment]
See https://redfishforum.com/thread/211/indicator-professor-throttled

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Nvidia is pushing a bunch of GPU properties into Redfish. GPU throttling is one of them.

**Comment by gtmills** [comment]
Todd confirmed we need this for eBMC

**Comment by derick-montague** [comment]
@gtmills - Todd told me today that we do not need GPU Throttling any longer.

**Comment by gtmills** [comment]
Not for eBMC

**Comment by rfrandse** [comment]
tracking in jira
