### ISSUE TITLE
Swift: PFP: Initial fan-monitor config file

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#959]
Create an initial config file for Swift fan monitoring.

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/22675

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/22675 merged
