### ISSUE TITLE
Rainier power supply device driver support for the firmware version

### ISSUE THREAD

**Issue by bjwyman** [ibm-openbmc/dev#960]
The Rainier systems can use power supplies with the four 1-byte read firmware version (like Witherspoon) or the three 2-byte read firmware version (like Swift). A device driver update to choose the correct way to read/interpret the power supply firmware version will be needed.

**Comment by rfrandse** [comment]
refresh

**Comment by bjwyman** [comment]
http://patchwork.ozlabs.org/patch/1192241/

**Comment by bjwyman** [comment]
https://github.com/openbmc/linux/commit/a020f40ab4c48ff808cdcf937419cc1a3dd6ea50
