### ISSUE TITLE
Unable to configure IP address on latest build

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#961]
This is mirror of the following issue https://github.com/openbmc/openbmc/issues/3562

**Comment by rfrandse** [comment]
refresh

**Comment by raviteja-b** [comment]
Resolved by : https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22940/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22940 merged
