### ISSUE TITLE
Redfish: Delete a single event log

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#962]
Need support to delete a single event log.

From https://redfish.dmtf.org/schemas/v1/LogEntry_v1.xml
It would be a DELETE to the LogEntryId
(e.g. /redfish/v1/Managers/{ManagerId}/LogServices/{LogServiceId}/Entries/{LogEntryId} )
![image](https://user-images.githubusercontent.com/5455127/59680486-0dda2480-9197-11e9-8714-21d521c9e712.png)

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/23528

**Comment by vishwabmc** [comment]
> Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/23528

Can this be closed then ?

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/23528 merged

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/23528 merged
