### ISSUE TITLE
PDM: Set a GPIO based on the state of a set of properties

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#964]
Create an available dbus monitor configuration function that can set a GPIO. This could then be configured for PDM to set the configured GPIO upon a set of rotor fail(s). Its best this functionality is contained here rather than within the fan monitor application since this could be viewed as a reaction to a rotor fail, which PDM handles similarly with logging errors and/or shutting down the system due to rotor fails.

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
QuickPowerDrop GPIO = FAN_FAULT_N(GPIOT6)

**Comment by derekhoward55** [comment]
This is not applicable to rainier

**Comment by msbarth** [comment]
There is currently no requirement for this change, closing.
