### ISSUE TITLE
Swift: PFP: Add booster fan configurations

### ISSUE THREAD

**Issue by msbarth** [ibm-openbmc/dev#967]
There is an optional booster fan that may be plugged within the chassis near the IO cards. This booster fan needs to be added to the hwmon max31785 config along with fan monitoring & fan control. Initially fan presence detection is checking the GPIO for the booster fan and will also need to be updated to check the tach feedback for presence detection.

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
The boost fan configuration is no longer needed on Swift
