### ISSUE TITLE
GUI: Remove content not accessible to to user based on permission level

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#968]
## Stakholders
**SME**: @dkodihal, @gkeishin, @ratagupt 

## Use Case
As a non-admin user, I should not be able to view or see call to action elements (submit, save, etc).

## Requirements 
1. Determine what is not available to non-admin users
1. Update the code to not include the content that is not accessible to the non-admin user
1. Handle any response returning a 403 status

## References/Resources
---

**Comment by rfrandse** [comment]
refresh

**Comment by gtmills** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/23650

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/23650 merged
