### ISSUE TITLE
PFP: Move to support `double` sensor values(essentially removes 'Scale' requirement)

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#97]
<a href="https://github.com/msbarth"><img src="https://avatars2.githubusercontent.com/u/14202667?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [msbarth](https://github.com/msbarth)**
_Friday Jun 23, 2017 at 15:31 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/1839_

----

Each sensor includes a 'Scale' property that needs to be investigated & taken into account for accurately reflecting the sensor's value. This also allows the user to define each event with the "human readable" values. i.e.) Ambient temp sensor - Value = 22800, Scale = -3 --> 22.800 degC

**Comment by rfrandse** [comment]
<a href="https://github.com/msbarth"><img src="https://avatars2.githubusercontent.com/u/14202667?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [msbarth](https://github.com/msbarth)**
_Thursday Jun 29, 2017 at 14:33 GMT_

----

- [x] Add single event for each 'Scale' property with an action to update an associated 'Value' property when changed
- [x] Add a handler function to set a property after calling a factor function to apply any conversions('Scale') when storing the property
- [x] Update all sensor 'Value' groups to call new handler function so scaled value is stored
- [ ] Update property storage map to attempt retrieving property if found missing (ensure 'Scale' exists prior to accessing 'Value' properties)
- [ ] Update parser to generate all necessary 'Scale' property entries without exposing this in the yaml(for now)

# **STATUS**
**7/25**
Vacation. A couple areas of changes are still required to complete this.

Catching up on things while out and had meeting with Todd over OpenBMC.
Walked thru #1835 handoff with Brandon, begin reviewing #1835 changes for reuse after acquiring.

Priority changed to #1835. This issue will be revisited once #1835 is completed.
Blockers - #1835

**8/9**
Not a priority currently

Should be able to make these updates seamlessly without affect end user testing

Blockers -

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
There is a push to move away from a scale factor and use a double instead for sensor values. This issue should be used to update fan control to no longer require the scale attribute in the event yaml and instead use a double sensor value directly.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by msbarth** [comment]
Resolved by https://gerrit.openbmc-project.xyz/29187
