### ISSUE TITLE
GUI: Design: eBMC Network Settings

### ISSUE THREAD

**Issue by jandraa** [ibm-openbmc/dev#971]
## Stakeholders
**SME**: Ratan Gupta, Tom Burks, Dave Stanton
**Design Researcher**: Nicole Conser
**UX Designer**: Jandra Aranguren
**FED**:

## Use Case
As an enterprise user, I need to configure the IP addresses and DNS servers on the system's network interfaces. This story includes VMI and BMC IP addresses.

## InVision Prototype
There is a difference in copy between HMC connected and not HMC connected. 

**NOTE:** HMC connected in this scenario means it _can_ be connected to an HMC, and hasn't been for some reason (rare scenario). Generic upstream design should remove the 'The Virtualization Management Interface is disabled until an HMC is connected to the BMC.' banner altogether. 

Static - not HMC connected: https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319333952_eBMC_-_Static_Empty
Static - HMC connected: https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319330192_eBMC_-_Static_-_No_VMI

DHCP - not HMC connected: https://ibm.invisionapp.com/share/Q6NZ13M3A5B#/319330191_eBMC_-_DHCP
DHCP - HMC connected: https://ibm.invisionapp.com/share/Q6NZ13M3A5B

**Comment by rfrandse** [comment]
refresh

**Comment by jandraa** [comment]
Waiting on confirmation from @ratagupt regarding whether or not `Hostname` and `Send hostname` are mutually exclusive. 
<img width="331" alt="Screen Shot 2019-12-05 at 2 13 00 PM" src="https://user-images.githubusercontent.com/44675611/70270155-61eabc80-1769-11ea-92b5-1950f1d5e4f7.png">

**Comment by jandraa** [comment]
^ Confirmed they are not mutually exclusive
