### ISSUE TITLE
LDAP role groups indeterminate checkbox

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#975]
## As Is
The parent checkbox has no visual indicator when one or many (not all) of the nested checkbox children are selected.

When items are removed from the role groups list and the parent checkbox is selected, it is not cleared.

## To Be 
LDAP select all groups checkbox should show a horizontal line when a group or multiple groups are selected and a check when all groups are selected. 

A checkbox can have three states: checked, unchecked, or indeterminate. Indeterminate state is visual only, but lets the user know a child checkbox has been selected.

When items are removed from the role groups list and the parent checkbox is selected, it will be cleared.

### Requirements
- [ ] Create as a reusable component

![Screen Shot 2019-06-24 at 1.51.39 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/6089eaa9-87fe-420a-b610-b40150c002cf)

![Screen Shot 2019-06-24 at 1.50.42 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/2b23ebb6-865b-416a-ab57-2dad1e38800f)

![Screen Shot 2019-06-24 at 1.42.16 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/4b6ed3be-90fb-455e-b6c2-b6c09c20308c)

**Comment by derick-montague** [comment]
Will be resolved by Vue rewrite

**Comment by derick-montague** [comment]
This issue will be handles by bootstrap in the vue rewrite
