### ISSUE TITLE
On an OpenBMC event log delete, do not delete the PEL

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#976]
If a PEL is not allowed to be deleted, the Delete and DeleteAll calls that phosphor-logging has should return a special D-Bus error.  I will confirm this makes sense in the Redfish realm.

It's possible there is some concept in Redfish of this and I could make an error that resembles that.

**Comment by spinler** [comment]
The new direction is that deleting an openbmc event log should not delete the corresponding PEL, so that the PEL can still be returned in a dump and seen by peltool.

I will use this issue to do that.

**Comment by spinler** [comment]
Note this case that is broken with this:
1. An event log is created with ID 1, and PEL with ID 0x50000001
1. Delete all Redfish/openbmc event logs
2. Restart phosphor-logging, like with a reboot
3. Create another event log, phosphor-logging will create event logs starting at 1 again, but the PEL ID is 0x50000002
4. Now both PELs think they were created from OpenBMC event log 1.
5. Use peltool to delete PEL 0x50000001
6.  It deletes its corresponding event log, OpenBMC event log 1, **but this is the wrong one!**

Could fix this by having phosphor-logging persist its last used ID, or, you know, not doing this issue.

**Comment by spinler** [comment]
I think the way to go that can avoid the problem is to make an archive subdirectory for the PELs, and move the files over there when the corresponding event log is deleted.   peltool could ignore those files, unless maybe a '--archive' argument was given.

We'd need to keep a cap on that directory size, probably a few MB would suffice.

We'll also need to make sure they are captured in BMC dumps.

**Comment by spinler** [comment]
As far as the  size cap goes, I think we're going to have to build it into the current size management checks.  So the total size of the archived PELs will count toward the 20MB cap.  To keep it a little easier, when we reach the warning limit, then I think we can delete the whole archive (as opposed to deleting just enough of it), and see if it's still over the limit before doing anything else.

**Comment by sumitk56** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/43863
