### ISSUE TITLE
wspoon/swift: Don't bind VRM hwmon device drivers with power off

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#979]
They report bad temperature values, and talking to the HW team the circuit was not designed to provide good values with main power off.

**Comment by spinler** [comment]
This could be trickier than I thought, because the phosphor-hwmon app for this will start as soon as the driver is bound on the way to BMC ready...

**Comment by mine260309** [comment]
For now udev rules starts a shell script to start phosphor-hwmon.
It is possible to extend (only for wspoon/swift) the script to check the power status and the device, and not to start phosphor-hwmon in specific cases.

**Comment by spinler** [comment]
I'm leaning toward wanted to handle this within phosphor-hwmon code so we can then just support it with a hwmon config file var instead of yet more systemd target dependencies that we have to deal with for every system going forward.

**Comment by msbarth** [comment]
@mine260309 That's what I was initially thinking, however it would involve extending a problem we initially addressed similarly with the max31785 chip. Issue openbmc/openbmc#3455 was created to remove the use of helper services and use the udev rules directly to start hwmon for all devices.

**Comment by mine260309** [comment]
Got it. It will make `phosphor-hwmon` a bit more complicated to handle a new config, I guess?

**Comment by derekhoward55** [comment]
this is not applicable to rainier

**Comment by spinler** [comment]
Closing, as not needed for Rainier.
