### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by rfrandse** [ibm-openbmc/dev#98]
<a href="https://github.com/zahrens"><img src="https://avatars1.githubusercontent.com/u/19207242?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zahrens](https://github.com/zahrens)**
_Friday Nov 17, 2017 at 19:37 GMT_
_Originally opened as https://github.com/openbmc/openbmc/issues/2651_

----

**Comment by rfrandse** [comment]
<a href="https://github.com/gtmills"><img src="https://avatars3.githubusercontent.com/u/5455127?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gtmills](https://github.com/gtmills)**
_Monday Jul 09, 2018 at 16:40 GMT_

----

@rfrandse   Why do we have an "IBM milestone 2 : Epic" and an "IBM milestone 2" https://github.com/openbmc/openbmc/issues/2658? 

Can 1 or both be closed?

**Comment by mzipse** [comment]
test

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Since this is an Epic, should it live in the Epic pipeline @mzipse?

**Comment by rfrandse** [comment]
tracking in jira
