### ISSUE TITLE
wspoon/swift:  Remove fan tach sensor thresholds

### ISSUE THREAD

**Issue by spinler** [ibm-openbmc/dev#980]
What the real low and high thresholds are varies, and cannot reliably be set with a hardcoded value.  Also, the Redfish sensor output looks at the functional status on the fan inventory to report sensor health, which is the accurate way of doing it.

These are located in the hwmon config files.

**Comment by sotaoverride** [comment]
Resolved by https://gerrit.openbmc-project.xyz/23430

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/23430 merged
