### ISSUE TITLE
GUI: Design: Customer with 32 character minimum password requirement

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#981]
## Use Case
**In "Add User" modal:**
If user password exceeds 20 characters, validation text notifies the admin/user that 
1. their initial password is too long
2. they will later have the opportunity to change this password to a longer length

**In "Modify User" modal**
If user password is changed to a length of over 20 characters, a warning notifies the admin/user that
1. a password of longer than 20 characters will result in the user losing IPMI access

## InVision Prototype
Add User modal: Error message for initial PW over 20 characters.
https://ibm.invisionapp.com/share/V2NZ99JW6DN
-if user types a password of exactly 20 characters in "user password" text field no validation message appears
-if user types a 21st character in "user password" text field a red validation message appears 
-the red validation message disappears when password is 20 characters or less

Modify User modal: PW over 20 characters // warning user will lose IPMI access.
https://ibm.invisionapp.com/share/T9NZA218WN4
-when 21st character is typed in "new user password" text field yellow warning message appears
-yellow warning message disappears when password is less than 21 characters

Other minor Modify User modal changes:
-button changed from "add user" to "update user"
-headings changed from "user password" and "confirm user password" to "new user password" and "confirm new user password"

_note: all users are by default part of the IPMI group so this message will appear for any user who attempts to modify their password to greater than 21 characters_

## ToDo
- [ ] Follow up with users to determine if they understand the warning message sequence

## References
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/19574 will cause problems

**Comment by bradbishop** [comment]
@ratagupt fyi...

**Comment by gtmills** [comment]
IPMI requires a password of less than 20.
Redfish max password length property to set length is read-only
If someone tries to change password to greater then 20, and user is in the IPMI group, password change fails.
If user turns off IPMI, it does *not* remove them from IPMI group?
dropbear allows 100 chars

**Comment by tomjoseph83** [comment]
```
curl -k -H "X-Auth-Token: $bmc_token" -X PUT -d '{"data":["redfish", "ssh", "web"]}'  https://${BMC_IP}/xyz/openbmc_project/user/root/attr/UserGroups
```
This REST API will remove `root` user from the IPMI group, after which password greater than 20 chars can be applied for the user.

**Comment by gtmills** [comment]
@tomjoseph83 What about a new user? How do we allow the new user to set a password greater than 20?

**Comment by tomjoseph83** [comment]
@gtmills This proposal is a temporary workaround and needs to be haFor the new user, there are two cases to be handled. 

1) If the user does not belong to IPMI group. ( a check box on the GUI can specify whether the user is part of the IPMI).

a) Password lesser than < 21

i) Create the user with the Redfish API.(password is a parameter here)
ii) Remove the user from the IPMI group. (REST API)

b) Password greater than > 20

i) Create the user with the Redfish API.(use a stripped 20 char password at the time of user creation)
ii) Remove the user from the IPMI group. (REST API)
iii) Set the password to the originally requested password( If any of the step fails, delete the user account and report a failure).

2) If the user belongs to the IPMI group, then the password should be restricted to 20 chars and Redfish API is sufficient.

**Comment by gtmills** [comment]
@jandraa proposed:
1. create a user
--- if the password attempt >20 characters, throw an error to say something along the lines of "initial password cannot be greater than 20 char. Once an account has been created, the password can be changed to longer passwords, which will cause the user to be removed from IPMI."
--- if password attempt is <= 20 characters, we're good2. after a user has been created:
3. Go to edit settings for an account
4. Try to change the password to > 20
5. Show warning that the account will be removed from IPMI

I prefer this solution because we are not setting a temporary password, a stripped 20 char password, a little lower risk.

**Comment by tomjoseph83** [comment]
@gtmills The solution depends on how the UI wants to handle the IPMI 20 char length restriction. @jandraa proposal looks fine, if setting the password > 20 char is done in a two step fashion.

When a user is created please highlight that the user is part of IPMI and also provide a provision to delete the user from IPMI group.
