### ISSUE TITLE
Implement Redfish Interface for VMI Static IP configuration 

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#988]
Management console would need the REST api for configuring the VMI IP configuration. BMC would provide the interface for the same and this config would be consumed by the VMI once phyp comes up.

**Comment by sunharis** [comment]
The HostInterface configuration is possible using the DMTF standard redfish interface. The design is up for review and discussion
https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/23416/

**Comment by ratagupt** [comment]
As per internal  discussion on 17/02/2020, It was decided.

-> Implement VMI as a system resource at the root level
-> This system would be of type "oem(Hypervisor)"
-> Implement the ethernet interaces under the system resource
-> State of the ethernet interface would be marked as "UnavailableOffline".

http://redfish.dmtf.org/schemas/v1/Resource.json#/definitions/Status

**Comment by ratagupt** [comment]
@sunharis Can you paste the gerrit commit here?

**Comment by ratagupt** [comment]
Scope of this story has been reduced and only allow to configure the static IPv4 configuration

**Comment by sunharis** [comment]
Below are the bmcweb commits for the VMI Static IPv4 changes. 

https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/29514/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/29666/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/29667/
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/29668/

**Comment by sunharis** [comment]
bmcweb changes are in master
