### ISSUE TITLE
Create the Interface for VMI Certificate Exchange

### ISSUE THREAD

**Issue by ratagupt** [ibm-openbmc/dev#989]
Before management console starts communication with VMI, it needs a certificate signed by VMI which acts as CA. through BMC.
Need to design the API through which HMC sends the CSR to VMI and gets the signed certificate and the CA certificate from VMI.
Can we extend the redfish certificate service for the same?

**Comment by raviteja-b** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/23420/

**Comment by ratagupt** [comment]
We have already delivered this functionality so closing the issue, New changes are being tracked through 2345.
