### ISSUE TITLE
eBMC State Management - Ability to enable and disable state management recovery actions

### ISSUE THREAD

**Issue by geissonator** [ibm-openbmc/dev#990]
There are use cases, especially when bringing up a new system, where a user wants to disable all automatic recovery built into the system. They don't want the recovery software to affect the state of the system once it's in a fail state so they can debug the issue.

The proposal is to wrap the commands to disable (and enable) recovery into obmcutil.
From a OpenBMC perspective we want to disable the auto reboot of the host and the 
host watchdog.

**obmcutil recoveryoff**
- busctl set-property xyz.openbmc_project.Settings /xyz/openbmc_project/control/host0/auto_reboot xyz.openbmc_project.Control.Boot.RebootPolicy AutoReboot b false
- systemctl disable obmc-enable-host-watchdog@0.service

**obmcutil recoveryon**
- busctl set-property xyz.openbmc_project.Settings /xyz/openbmc_project/control/host0/auto_reboot xyz.openbmc_project.Control.Boot.RebootPolicy AutoReboot b true
- systemctl enable obmc-enable-host-watchdog@0.service

TODO:
- The obmc-enable-host-watchdog@0.service is static which means you can't disable it, need to figure out best way to handle this.
- Commands to disable fan or power code from terminating? Running in some kind of safe thermal mode?
- Disable OnError target in obmc-host-start targets?
- Disable ALL reboots (even one's requested by the user or host). There are times where the host may request a reboot for certain error paths. There's a request to even disable these. This will need some discussion. What about when the host is updating SBE's? How do we get out of this, user requests power off?

Discussion:
A wrapper really needed? New services will be added and targets/properties may change. It's good to abstract the specific commands from the broad user base that will need this.

Host watchdog info can be found at https://github.com/openbmc/docs/blob/master/host-management.md#host-watchdog

**Comment by amboar** [comment]
Can we have them as genuine subcommands rather than options (i.e. e.g. `obmcutil enable-recovery` or `obmcutil recovery enable`)? Options without an argument don't make a lot of sense.

**Comment by geissonator** [comment]
> Can we have them as genuine subcommands rather than options (i.e. e.g. `obmcutil enable-recovery` or `obmcutil recovery enable`)? Options without an argument don't make a lot of sense.

Yeah, good point. To keep consistent with other obmcutil commands, I think recoveryon and recoveryoff would probably make the most sense (i.e. chassison, chassisoff, poweron, poweroff...). I'd prefer enable-recovery and disable-recovery though.

**Comment by vishwabmc** [comment]
@geissonator
I am in agreement with obmcutil recovery[on/off]

*From the legacy requirements, we have just these :*
---
-1- Disable the Re-IPL
-2- Disable the SP reboot requests that are controlled by State Manager and fspinit
-3- Run in Manual mode

-1-, as you suggested, we can with xyz.openbmc_project.Control.Boot.RebootPolicy
-2-, I believe, we could disable the systemd service recovery
    ( be it with: "on error target", or "AutoRestart="" )
   -- We should be able to disable the automatic re-spin of the process
-3- This is kind of achieved by -1-
--------------
The obmc-enable-host-watchdog@0.service is static which means you can't disable it, need to figure out best way to handle this.
-  Why is this needed ?. 
-  Even if needed, we could mock a IPMI command to stop the timer and have that part of the obmcutil wrapper
    
Commands to disable fan or power code from terminating? Running in some kind of safe thermal mode?
- Why is this a requirement ?. Termination is fine.

Disable OnError target in obmc-host-start targets?
- Mentioned above. We need to handle the AutoRestart= and also the failure targets. I believe, systemd has something like this ?

Disable ALL reboots (even one's requested by the user or host). There are times where the host may request a reboot for certain error paths. There's a request to even disable these. This will need some discussion. What about when the host is updating SBE's? How do we get out of this, user requests power off?

- This is part of -2- mentioned above. If we have reboot BMC target, then can we just disable it ?

**Comment by geissonator** [comment]
> @geissonator
> I am in agreement with obmcutil recovery[on/off]
> ## From the legacy requirements, we have just these :
> 
> -1- Disable the Re-IPL
> -2- Disable the SP reboot requests that are controlled by State Manager and fspinit
> -3- Run in Manual mode
> 
> 1/. as you suggested, we can with xyz.openbmc_project.Control.Boot.RebootPolicy
> 2/. I believe, we could disable the systemd service recovery
> ( be it with: "on error target", or "AutoRestart="" )
> -- We should be able to disable the automatic re-spin of the process
> 3/. This is kind of achieved by -1-
> 
> The [obmc-enable-host-watchdog@0.service](mailto:obmc-enable-host-watchdog@0.service) is static which means you can't disable it, need to figure out best way to handle this.
> 
>     * Why is this needed ?.

The requirement is we do nothing to the system or the host when they have this mode enabled so we have to somehow disable all of our services that run when the watchdog expires, or just prevent it from expiring all together (which is what I would prefer for the cleanest approach).

>     * Even if needed, we could mock a IPMI command to stop the timer and have that part of the obmcutil wrapper

The problem is that you can't disable the watchdog until it's been started, which is not until the boot has started.

> 
> Commands to disable fan or power code from terminating? Running in some kind of safe thermal mode?
> 
>     * Why is this a requirement ?. Termination is fine.

ok, I wasn't sure if there was anything we needed to do here, sounds like no.

> 
> Disable OnError target in obmc-host-start targets?
> 
>     * Mentioned above. We need to handle the AutoRestart= and also the failure targets. I believe, systemd has something like this ?

Any details? I'm not familiar with anything.

> 
> 
> Disable ALL reboots (even one's requested by the user or host). There are times where the host may request a reboot for certain error paths. There's a request to even disable these. This will need some discussion. What about when the host is updating SBE's? How do we get out of this, user requests power off?
> 
>     * This is part of -2- mentioned above. If we have reboot BMC target, then can we just disable it ?

Code update has a target they start and then stop which disables BMC reboots (to ensure a reboot doesn't not happen during a BMC code update). Maybe we can piggy back off of that. Although seems like disabling BMC reboots should be a separate command and not grouped in with recoveryoff?

**Comment by bradbishop** [comment]
> -2- Disable the SP reboot requests that are controlled by State Manager and fspinit

Can we document why this is a requirement?  I'd like to consider not doing any special code for this.  It seems like:

1 - our automatic data gathering code should be good enough to debug problems such that this isn't needed 99% of the time
2 - if a developer -really- wants to disable recovery there are ways to do it using systemctl directly.

am I forgetting other uses of this?

**Comment by vishwabmc** [comment]
> > -2- Disable the SP reboot requests that are controlled by State Manager and fspinit
> 
> Can we document why this is a requirement? I'd like to consider not doing any special code for this. It seems like:
>

```
The goal is to have the BMC be at failed state and not take a reboot etc so we have the "point of failure" active to debug the problem. One of the reason was the time it took for the people to debug the earlier Bringup issues if we needed to wait for the recovery to kick in etc.
 ```
> 1 - our automatic data gathering code should be good enough to debug problems such that this isn't needed 99% of the time

```
Sorry, but which one are you mentioning here ?. Are you referring the BMC dump ?
```
> 2 - if a developer -really- wants to disable recovery there are ways to do it using systemctl directly.
> 

``
Yeah.. the proposal is to make it a wrapper instead of someone doing it by hand for many. Just making it easier for the end user
```
> am I forgetting other uses of this?


--------------

**Comment by vishwabmc** [comment]
> > The [obmc-enable-host-watchdog@0.service](mailto:obmc-enable-host-watchdog@0.service) is static which means you can't disable it, need to figure out best way to handle this.
> > ```
> > * Why is this needed ?.
> > ```
> 
> The requirement is we do nothing to the system or the host when they have this mode enabled so we have to somehow disable all of our services that run when the watchdog expires, or just prevent it from expiring all together (which is what I would prefer for the cleanest approach).
> 
> > ```
> > * Even if needed, we could mock a IPMI command to stop the timer and have that part of the obmcutil wrapper
> > ```
> 
> The problem is that you can't disable the watchdog until it's been started, which is not until the boot has started.
> 

``` I will keep looking.. but jotting down the immediate thought I had.. Since this is a lab only usecase, I suppose, we can start the unit as part of the wrapper script and then disable the timer ```

**Comment by bradbishop** [comment]
> The goal is to have the BMC be at failed state and not take a reboot etc so we have the "point of failure" active to debug the problem. 
We are talking about applications that have crashed and coredumped right?  Any "point of failure" state is in the core dump file, or in any data that has been captured by bmc dump.

> One of the reason was the time it took for the people to debug the earlier Bringup issues if we needed to wait for the recovery to kick in etc.
The 60 seconds it takes for the dump to be collected is too long?

> Sorry, but which one are you mentioning here ?. Are you referring the BMC dump ?
Yes.

I have been told elsewhere that we must to be able to solve problems from the data gathered.  So why are we spending time writing tools that make it easier to solve problems in a way that we can't rely on?

**Comment by vishwabmc** [comment]
> We are talking about applications that have crashed and coredumped right? Any "point of failure" state is in the core dump file, or in any data that has been captured by bmc dump.

```Applications crash.. Yes for the most part.  Do we reset BMC on loosing critical daemons ?. The aim was to have BMC alive so the debug can be done right away as opposed to waiting for BMC to take a reset, come back, establish network etc.. At least, that was the need then.  Now that i think again, having the BMC alive while not having the critical daemon would still hamper debug```.

 *I am leaning towards asking Dean on how it was really used before investing time on this. *

> > One of the reason was the time it took for the people to debug the earlier Bringup issues if we needed to wait for the recovery to kick in etc.
> 
> The 60 seconds it takes for the dump to be collected is too long?
> 

```Not really.. The concern is *not* about the time taken by BMCdump. The concern was about waiting for FSP to come back on on resets
```
> > Sorry, but which one are you mentioning here ?. Are you referring the BMC dump ?
> 
> Yes.
> 
> I have been told elsewhere that we must to be able to solve problems from the data gathered. So why are we spending time writing tools that make it easier to solve problems in a way that we can't rely on?

``` We are not writing tools to collect more data.. We are trying to see if we can have BMC up and running instead of taking recovery actions like Re-IPL ( which is easy ) , dishonour reboot request on loosing critical daemons if we can intercept that ( on which I have a counter argument already :) ```

**Comment by geissonator** [comment]
> I have been told elsewhere that we must to be able to solve problems from the data gathered. So why are we spending time writing tools that make it easier to solve problems in a way that we can't rely on?

This is always the goal, but how often is it really the case, especially early in bringup? When a team is deep into debugging critical processor, memory, hostboot, SBE, ... issues and the BMC just reboots itself on them because it's trying to recover from something, it's not the BMC they're trying to debug, it's the system, but the BMC is the conduit to that debug. I definitely see this story as lab-only type function. We should not be doing any of this once a system has shipped. That is when we definitely rely on our FFDC and dumps.

From a "is it in a obmcutil command or systemctl command" discussion. I feel like because our dbus and systemd targets have not stayed consistent, and I still want the ability to refactor as needed, providing a wrapper in obmcutil for these lab commands is best. I caught a lot of flak over the last few years for how complicated and how many times the commands I gave people to disable auto reboot and the watchdog changed.

**Comment by vishwabmc** [comment]
> This is always the goal, but how often is it really the case, especially early in bringup? When a team is deep into debugging critical processor, memory, hostboot, SBE, ... issues and the BMC just reboots itself on them because it's trying to recover from something, it's not the BMC they're trying to debug, it's the system, but the BMC is the conduit to that debug. I definitely see this story as lab-only type function. We should not be doing any of this once a system has shipped. That is when we definitely rely on our FFDC and dumps.
>

We are **not** writing new debug tools etc.. We are only helping the bringup team to debug the issues using Cronus for example and the goal is to see if we can avoid BMC downtime here. They just need BMC to be up and running for debugging system issues as @geissonator mentioned. 

Dean mentioned that it has been quite often used and hence we would continue to need this.

> From a "is it in a obmcutil command or systemctl command" discussion. I feel like because our dbus and systemd targets have not stayed consistent, and I still want the ability to refactor as needed, providing a wrapper in obmcutil for these lab commands is best. I caught a lot of flak over the last few years for how complicated and how many times the commands I gave people to disable auto reboot and the watchdog changed.

I agree and I support the wrapper.

**Comment by geissonator** [comment]
A good overview of static systemd units - https://bbs.archlinux.org/viewtopic.php?id=147964

**Comment by vishwabmc** [comment]
On the watchdog issue; Here is what I came up with and that is working fine.

Mask the unit `obmc-host-timeout@0.target` so that watchdog can not execute that target on timeout. It will end up putting an error entry. but that's okay for lab purpose.. 

Here is the snippet:
```
root@localhost:/lib/systemd/system/obmc-host-startmin@0.target.wants# phosphor-watchdog --continue --service=xyz.openbmc_project.Watchdog --path=/xyz/openbmc_project/watchdog/host0 --target=obmc-host-timeout@0.target &
[1] 558
root@localhost:/lib/systemd/system/obmc-host-startmin@0.target.wants# Action Targets:
  xyz.openbmc_project.State.Watchdog.Action.PowerCycle -> obmc-host-timeout@0.target
  xyz.openbmc_project.State.Watchdog.Action.HardReset -> obmc-host-timeout@0.target
  xyz.openbmc_project.State.Watchdog.Action.PowerOff -> obmc-host-timeout@0.target

root@localhost:/lib/systemd/system/obmc-host-startmin@0.target.wants# obmcutil state
CurrentBMCState     : xyz.openbmc_project.State.BMC.BMCState.Ready
CurrentPowerState   : xyz.openbmc_project.State.Chassis.PowerState.Off
CurrentHostState    : xyz.openbmc_project.State.Host.HostState.Off
BootProgress        : xyz.openbmc_project.State.Boot.Progress.ProgressStages.Unspecified
OperatingSystemState: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.Inactive

Oct 15 11:40:22 localhost phosphor-watchdog[558]: watchdog: enabled and started
Oct 15 11:40:52 localhost phosphor-watchdog[558]: watchdog: Timed out
Oct 15 11:40:53 localhost phosphor-watchdog[558]: watchdog: Failed to start unit
Oct 15 11:40:53 localhost phosphor-fru-fault-monitor[396]: /xyz/openbmc_project/logging/entry/2 created
Oct 15 11:40:53 localhost phosphor-watchdog[558]: watchdog: disabled

CurrentBMCState     : xyz.openbmc_project.State.BMC.BMCState.Ready
CurrentPowerState   : xyz.openbmc_project.State.Chassis.PowerState.Off
CurrentHostState    : xyz.openbmc_project.State.Host.HostState.Off
BootProgress        : xyz.openbmc_project.State.Boot.Progress.ProgressStages.Unspecified
OperatingSystemState: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.Inactive
root@localhost:/lib/systemd/system/obmc-host-startmin@0.target.wants# 
```

**Comment by vishwabmc** [comment]
Pushed https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-state-manager/+/26510/ to `enable/disable` Auto Reboot

**Comment by vishwabmc** [comment]
I believe, this can be closed with the latest patchset on enable/disable reboot..
