### ISSUE TITLE
GUI : FED : Accessibility: LDAP

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#992]
## Accessibility Issues that need to be addressed

- [x] Sort buttons need aria-label or screen-reader-text

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/45484b58-23e7-4ff0-b53d-1da5a2cfbba0)
---
- [x] Fieldsets must of a single, non-empty legend

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/71ef8dcf-c25f-4fb9-884d-e4b0333cdb62)
---

- [x] Checkbox and radio buttons must have label after the input control

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/eacb436e-2b61-4fab-b628-b09b8c358ae3)

Issue here is that the input is wrapped in a label and also has a `for` attribute. The `for` attribute is not necessary since the input is wrapped in the label. The best solution is to move he input out of the label. This will require some styling changes.

---

- [x] An interactive element must have an accessible name

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/c1e78647-0f1f-47df-bfdb-d2f9927a02db)

Modal containers require an `aria-label` or `aria-describedby` attribute
- Resource: https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/23472

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/23472 merged
