### ISSUE TITLE
PLDM BIOS spec : implement processing of the BIOS string type

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#994]

**Comment by dkodihal** [comment]
- [ ] Define JSON structure for BIOS String type
- No extra work needed for populating string table
- [ ] Implement API to retrieve attribute table data
- [ ] Implement API to retrieve current value (for the attr value data)
- [ ] Implement adding BIOS string attribute/value sections to the BIOS table response
- [ ] Unit tests

**Comment by wangkair** [comment]
Some questions about this issue.

1. When write string json file, is there a spec to define attribute name and related string type?
I think real examples are better, both for code reading and BIOS table comprehension, though I can write a fake file temporarily.

2. In one BIOSAttributeTableData, will it include all the attr types? Or only include some of them, depending on how many different types of json file?

3. Is there any command or process to indicate which attr type it is now before construct attr table?
From the existing code, we can distinguish them by name format of json files. But I'm not sure if this is the only and right way.
e.g.,
enum_attrs.json is for type enum,
string_attrs.json is for type string
<br>If every BIOSAttributeTableData includes all the attr types, then distinguishing types means nothing. But if it may only include a part of these types, I want to distinguish them to discard the types not included.

4. two nits:
1) In enum_attrs.json, '"object_path" : "/xyz/abc/def",' should be in "dbus".
```
  "entries":[
      {
         "attribute_name" : "HMCManagedState",
         "possible_values" : [ "On", "Off" ],
         "default_values" : [ "On" ],
         "object_path" : "/xyz/abc/def",
         // This BIOS attribute has a D-Bus property as backend. 
         "dbus":
            {
               "interface" : "xyz.openbmc_project.HMCManaged.State",
               "property_name" : "State",
               "property_type" : "string",
               # Number of property_values should match to the number of possible values.
               # Each is entry in the possible_values is mapped to entry in property_values. 
               "property_values" : ["xyz.openbmc_project.State.On", "xyz.openbmc_project.State.Off"]
            }
      },
```
2) In function buildBIOSTables, is it possible that BIOSAttributeTable is not empty, but BIOSStringTable is empty already due to some faulty operation？
```
            case PLDM_BIOS_ATTR_VAL_TABLE:
                if (BIOSAttributeTable.isEmpty())
                {
                    rc = PLDM_BIOS_TABLE_UNAVAILABLE;
                }
                else
                {
                    response = getBIOSAttributeValueTable(
                        BIOSAttributeValueTable, BIOSAttributeTable,
                        BIOSStringTable, transferHandle, transferOpFlag,
                        request->hdr.instance_id, biosJsonDir);
                }
                break;
```

**Comment by dkodihal** [comment]
> Some questions about this issue.
> 
>     1. When write string json file, is there a spec to define attribute name and related string type?
>        I think real examples are better, both for code reading and BIOS table comprehension, though I can write a fake file temporarily.

There's an example here - https://github.com/openbmc/pldm/tree/master/libpldmresponder/examples/bios. This is for the enum type attributes. I think for the string one, the code would expect the name of the attribute in a key called "attribute_name". A README or a guide on how to write these BIOS JSONs would be useful. That's on my TODO list, but if you want to submit something for this, that would be great!

>     2. In one BIOSAttributeTableData, will it include all the attr types? Or only include some of them, depending on how many different types of json file?

I'm not sure I followed. Do you mean whether the BIOS tables that the BMC builds should aggregate attributes from all the JSONs? If so, the answer is yes. Also note, and this is outside the scope of this issue, the BMC can even be presented a BIOS table from a BIOS firmware, and we have work to do store and distinguish BIOS tables generated by the BMC and those provided by others.
> 
>     3. Is there any command or process to indicate which attr type it is now before construct attr table?
>        From the existing code, we can distinguish them by name format of json files. But I'm not sure if this is the only and right way.
>        e.g.,
>        enum_attrs.json is for type enum,
>        string_attrs.json is for type string
>        If every BIOSAttributeTableData includes all the attr types, then distinguishing types means nothing. But if it may only include a part of these types, I want to distinguish them to discard the types not included.

Right now the name of the JSON file indicates the BIOS attribute type as well. There could be other ways of doing this, but what's there now definitely makes the processing of it in code easier. If you have better ideas, I'm open to discussing that.
The BIOS table constructed by the BMC will have attributes read and parsed from all the JSONs.

>     4. two nits:
>        1> In enum_attrs.json, '"object_path" : "/xyz/abc/def",' should be in "dbus".
> 
> 
> ```
>   "entries":[
>       {
>          "attribute_name" : "HMCManagedState",
>          "possible_values" : [ "On", "Off" ],
>          "default_values" : [ "On" ],
>          "object_path" : "/xyz/abc/def",
>          // This BIOS attribute has a D-Bus property as backend. 
>          "dbus":
>             {
>                "interface" : "xyz.openbmc_project.HMCManaged.State",
>                "property_name" : "State",
>                "property_type" : "string",
>                # Number of property_values should match to the number of possible values.
>                # Each is entry in the possible_values is mapped to entry in property_values. 
>                "property_values" : ["xyz.openbmc_project.State.On", "xyz.openbmc_project.State.Off"]
>             }
>       },
> ```
> 
> 2> In function buildBIOSTables, is it possible that BIOSAttributeTable is not empty, but BIOSStringTable is empty already due to some faulty operation？
> 
> ```
>             case PLDM_BIOS_ATTR_VAL_TABLE:
>                 if (BIOSAttributeTable.isEmpty())
>                 {
>                     rc = PLDM_BIOS_TABLE_UNAVAILABLE;
>                 }
>                 else
>                 {
>                     response = getBIOSAttributeValueTable(
>                         BIOSAttributeValueTable, BIOSAttributeTable,
>                         BIOSStringTable, transferHandle, transferOpFlag,
>                         request->hdr.instance_id, biosJsonDir);
>                 }
>                 break;
> ```

Good catch (both of these)! Please either :
- submit patches to fix them
- submit these as bugs (issues) here - https://github.com/openbmc/pldm/issues
- do nothing, and I will make sure they're addressed shortly :) 

Also, not sure if you've noted this in the code, but the BIOS processing code is kind of broken now because it assumes/works with only the BIOS enum types, and would need some changes to make processing of other types possible. Please reach out to me if you have questions on this.

**Comment by wangkair** [comment]
1. About json file, I proposed to use some real examples like the examples of enum (FWBootSide, InbandCodeUpdate, ...) But I don't know the real attribute names of string and integer. So I write two examples using some fake strings.
string_attrs.json  -->
```
   "entries":[
      {
         "attribute_name" : "example1",
         // Possible values of string type {Unknown=0x00, ASCII=0x01, Hex=0x02, UTF-8=0x03, 
         // UTF-16LE=0x04, UTF-16BE=0x05, Vendor Specific=0xFF}
         "string_type" : 0x01, 
         "minimum_string_length" : 1,
         "maximum_string_length" : 100,
         "default_string_length" : 3,
         "default_string" : "abc",
         // This BIOS attribute has a D-Bus property as backend. 
         "dbus":
            {
               "object_path" : "/xyz/abc/def",
               "interface" : "xyz.openbmc_project.example1.value",
               "property_name" : "Example1",
               "property_type" : "string"
            }
      },
     ...
```
integer_attrs.json
```
{
   "entries":[
      {
         "attribute_name" : "example1",
         "lower_bound" : 0,
         "upper_bound" : 10000,
         "scalar" : -3,
         "default_value" : 1000,
         // This BIOS attribute has a D-Bus property as backend. 
         "dbus":
            {
               "object_path" : "/xyz/abc/def",
               "interface" : "xyz.openbmc_project.example1.value",
               "property_name" : "Example1",
               "property_type" : "uint64_t"
            }
      },
   ...
```
Can I use such content temporarily if there are no real attr examples? Is there any improper content above?

2.  "but the BIOS processing code is kind of broken now because it assumes/works with only the BIOS enum types, and would need some changes to make processing of other types possible"
-->
Yes, I noted that. That's one reason why I asked the questions 2 and 3 last comments. Your point, constructing the type data into attr table if there is corresponding json files, I got it.
e.g., there are two json files, enum_attrs.json and string_attrs.json, then the attr table should be something like

| Attr table| 
|--------|
|attr_hdl(0)|
|type(0) is enum|
|attr_name_hdl(0)|
|enum data(0)|
|...|
|attr_hdl(n)|
|type(n) is enum|
|attr_name_hdl(n)|
|enum data(n)|
|attr_hdl(n+1)|
|type(n+1) is string|
|attr_name_hdl(n+1)|
|string data(n+1)|
|...|
|attr_hdl(m)|
|type(m) is string|
|attr_name_hdl(m)|
|string data(m)|
|pad|
|checksum|

But one more thing I want to double check is: 
if there is no related json file, we don't need to construct such type data into attr table, right?
Like above example, there is no integer json file, so the data of type integer won't appear in attr table? If yes, my initial idea is to distinguish the types via json file names and use different namespaces (bios_type_enum, bios_type_string) before construct attr table.

**Comment by dkodihal** [comment]
>     1. About json file, I proposed to use some real examples like the examples of enum (FWBootSide, InbandCodeUpdate, ...) But I don't know the real attribute names of string and integer. So I write two examples using some fake strings.
>        string_attrs.json  -->
> 
> 
> ```
>    "entries":[
>       {
>          "attribute_name" : "str_example1",
>          // Possible values of string type {Unknown=0x00, ASCII=0x01, Hex=0x02, UTF-8=0x03, 
>          // UTF-16LE=0x04, UTF-16BE=0x05, Vendor Specific=0xFF}
>          "string_type" : 0x01, 
>          "minimum_string_length" : 1,
>          "maximum_string_length" : 100,
>          "default_string_length" : 3,
>          "default_string" : "abc",
>          // This BIOS attribute has a D-Bus property as backend. 
>          "dbus":
>             {
>                "object_path" : "/xyz/abc/def",
>                "interface" : "xyz.openbmc_project.str_example1.value",
>                "property_name" : "Str_example1",
>                "property_type" : "string"
>             }
>       },
>      ...
> ```
> 
> integer_attrs.json
> 
> ```
> {
>    "entries":[
>       {
>          "attribute_name" : "int_example1",
>          "lower_bound" : 0,
>          "upper_bound" : 10000,
>          "scalar" : -3,
>          "default_value" : 1000,
>          // This BIOS attribute has a D-Bus property as backend. 
>          "dbus":
>             {
>                "object_path" : "/xyz/abc/def",
>                "interface" : "xyz.openbmc_project.int_example1.value",
>                "property_name" : "Int_example1",
>                "property_type" : "uint64_t"
>             }
>       },
>    ...
> ```
> 
> Can I use such content temporarily if there are no real attr examples? Is there any improper content above?

This looks fine. You should be able to unit test with the same.

>     1. "but the BIOS processing code is kind of broken now because it assumes/works with only the BIOS enum types, and would need some changes to make processing of other types possible"
>        -->
>        Yes, I noted that. That's one reason why I asked the questions 2 and 3 last comments. Your point, constructing the type data into attr table if there is corresponding json files, I got it.
>        e.g., there are two json files, enum_attrs.json and string_attrs.json, then the attr table should be something like
> 
> 
> Attr table
> attr_hdl(0)
> type(0) is enum
> attr_name_hdl(0)
> enum data(0)
> ...
> attr_hdl(n)
> type(n) is enum
> attr_name_hdl(n)
> enum data(n)
> attr_hdl(n+1)
> type(n+1) is string
> attr_name_hdl(n+1)
> string data(n+1)
> ...
> attr_hdl(m)
> type(m) is string
> attr_name_hdl(m)
> string data(m)
> pad
> checksum
> 
> But one more thing I want to double check is:
> if there is no related json file, we don't need to construct such type data into attr table, right?

Right.

> Like above example, there is no integer json file, so the data of type integer won't appear in attr table? If yes, my initial idea is to distinguish the types via json file names and use different namespaces (bios_type_enum, bios_type_string) before construct attr table.

That sounds right. There should a namespace for bios enum type already.

**Comment by wangkair** [comment]
In getBIOSAttributeTable,
```
if (BIOSAttributeTable.isEmpty())
{  constructAttrTable();  get resp; }
else
{  load resp;  }
```
Q1: Is it possible that one new json file is added during pldm runtime? If yes, the attr table is not empty, but still need to construct new added type info into it.

Q2: Is it possible that one existing json file is modified/deleted during pldm runtime? If yes, maybe we need to clear the current data in table first, then reconstruct it.

Or we only consider the initial status of json dir, whatever the files under json dir is changed later, we just ignore it?

**Comment by dkodihal** [comment]
> In getBIOSAttributeTable,
> 
> ```
> if (BIOSAttributeTable.isEmpty())
> {  constructAttrTable();  get resp; }
> else
> {  load resp;  }
> ```
> 
> Q1: Is it possible that one new json file is added during pldm runtime? If yes, the attr table is not empty, but still need to construct new added type info into it.
> 
> Q2: Is it possible that one existing json file is modified/deleted during pldm runtime? If yes, maybe we need to clear the current data in table first, then reconstruct it.
> 
> Or we only consider the initial status of json dir, whatever the files under json dir is changed later, we just ignore it?

The code today constructs the BIOS tables "lazily" (when a GetBIOSTable or related command is received). I think the pldmd daemon should build tables on startup - and always build new tables on startup (I have a TODO for this, will write that up as an issue soon). Once we do that, it addresses your concerns, plus it also means we don't have to build tables on each GetBIOSTable command. I don't think there is a use-case of modifications/additions/deletions to the JSON file while the pldm daemon is running. If something like that happens, we can ignore it, and the pldm daemon will process it when it starts up next time (a typical BMC firmware update scenario, where we'd reboot the BMC).

**Comment by wangkair** [comment]
This has been merged in https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/24951/18
The enhancement about enum type can be done in another issue.
