### ISSUE TITLE
PLDM BIOS spec : implement processing of the BIOS integer type

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#995]
This commit chain : https://gerrit.openbmc-project.xyz/#/c/openbmc/pldm/+/23283/ adds support for the BIOS Enumeration type. This story is to implement similar support for the BIOS string type.

**Comment by wangzqbj** [comment]
- bios: Add en/decodes for integer attribute
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/26155  under review
-  bios: Define json structure for integer attribute
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/24775 under review
- bios: Add a configuration parser for integer attribute
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/26217 under review
- bios: table construct: Add support for integer attribute
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/26218 under review
