### ISSUE TITLE
PLDM BIOS spec : implement GetBIOSAttributeCurrentValueByHandle

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#996]

**Comment by dkodihal** [comment]
- [ ] libpldm responder encode/decode and tests
- [ ] Add API to extract a row from the existing attribute value table (assume notification mechanism has already updated table)
- [ ] Invoke API from above, prepare response packet and send it
- [ ] Responder and new API unit tests

**Comment by wangzqbj** [comment]
Resolved by

- [ ] ibpldm: bios: Implement iter for attr value table
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27639

- [ ] libpldm: Add API to find an attribute value entry
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27640

- [ ] Add cc only response
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27667

- [ ] Implement GetBIOSAttributeCurrentValueByHandle
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27731

**Comment by wangzqbj** [comment]
- [x] ibpldm: bios: Implement iter for attr value table
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27639 merged

- [x] libpldm: Add API to find an attribute value entry
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27640 merged

- [x] Add cc only response
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27667 merged

- [x] Implement GetBIOSAttributeCurrentValueByHandle
https://gerrit.openbmc-project.xyz/c/openbmc/pldm/+/27731 merged
