### ISSUE TITLE
PLDM FRU spec : low-level design

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#997]
The aim of this story is to split up work into stories for which tasks are well defined.

**Comment by tomjoseph83** [comment]
The PLDM FRU records will be generated from the D-Bus inventory objects using platform specific JSON configuration files. If there are multiple OEM FRU records then the first field indicates the Record Name. The PLDM FRU General fields are populated for fields like Part Number and Serial Number. All the PLDM FRU fields should have a mapping D-Bus property.

PLDM FRU mandatory commands "Get FRURecordTableMetadata" and "GetFRURecordTable" will be implemented.
